aa: com.cliffc.aa.HM.HM7.VStack Class Reference
com.cliffc.aa.HM.HM7.VStack Class Reference
Classes
class Iter
Public Member Functions
Iterator< T2 > iterator ()
String toString ()
Package Functions
VStack (VStack par, T2 nongen)
SB str (SB sb, VBitSet dups)
Package Attributes
final T2 _nongen
final VStack _par
Detailed Description
Definition at line 215 of file HM7.java.
Constructor & Destructor Documentation
VStack()
com.cliffc.aa.HM.HM7.VStack.VStack (VStack par, T2 nongen) package
Definition at line 218 of file HM7.java.
 { _par=par; _nongen=nongen; }
References com.cliffc.aa.HM.HM7.VStack._nongen, and com.cliffc.aa.HM.HM7.VStack._par.
Member Function Documentation
iterator()
Iterator<T2> com.cliffc.aa.HM.HM7.VStack.iterator ()
Definition at line 232 of file HM7.java.
 { return new Iter(); }
str()
SB com.cliffc.aa.HM.HM7.VStack.str (SB sb, VBitSet dups) package
Definition at line 227 of file HM7.java.
{
       _nongen.str(sb,new VBitSet(),dups);
       if( _par!=null ) _par.str(sb.p(" , "),dups);
       return sb;
     }
References com.cliffc.aa.HM.HM7.VStack._nongen, com.cliffc.aa.HM.HM7.VStack._par, com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM7.VStack.str(), and com.cliffc.aa.HM.HM7.T2.str().
Referenced by com.cliffc.aa.HM.HM7.VStack.str(), and com.cliffc.aa.HM.HM7.VStack.toString().
toString()
String com.cliffc.aa.HM.HM7.VStack.toString ()
Definition at line 219 of file HM7.java.
{
       // Collect dups across the forest of types
       VBitSet dups = new VBitSet();
       for( VStack vs = this; vs!=null; vs = vs._par )
         vs._nongen.get_dups(dups);
       // Now recursively print
       return str(new SB(),dups).toString();
     }
References com.cliffc.aa.HM.HM7.VStack._par, com.cliffc.aa.HM.HM7.VStack.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_nongen
final T2 com.cliffc.aa.HM.HM7.VStack._nongen package
Definition at line 217 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.VStack.Iter.next(), com.cliffc.aa.HM.HM7.VStack.str(), and com.cliffc.aa.HM.HM7.VStack.VStack().
_par
final VStack com.cliffc.aa.HM.HM7.VStack._par package
Definition at line 216 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.VStack.Iter.next(), com.cliffc.aa.HM.HM7.VStack.str(), com.cliffc.aa.HM.HM7.VStack.toString(), and com.cliffc.aa.HM.HM7.VStack.VStack().
The documentation for this class was generated from the following file:
HM7.java