aa: com.cliffc.aa.node.ScopeNode.IfScope Class Reference
com.cliffc.aa.node.ScopeNode.IfScope Class Reference
Package Functions
Node check (ScopeNode scope, boolean arm, Parse bad, GVNGCM gvn, Node ctrl, Node mem)
void def (String name, Access mutable, boolean create)
void flip ()
Package Attributes
boolean _arm = true
HashMap< String, Access > _fvars
HashMap< String, Access > _tvars
Detailed Description
Definition at line 198 of file ScopeNode.java.
Member Function Documentation
check()
Node com.cliffc.aa.node.ScopeNode.IfScope.check (ScopeNode scope, boolean arm, Parse bad, GVNGCM gvn, Node ctrl, Node mem) package
Definition at line 216 of file ScopeNode.java.
{
       if( _tvars == null ) return mem; // No new vars on either arm
       // Pull from both variable sets names that are common to both
       if( arm ) {               // Only do it first time
         Ary<String> names = new Ary<>(String.class).addAll(_tvars.keySet());
         while( !names.isEmpty() ) {
           String name = names.pop();
           if( _fvars.remove(name)!=null ) _tvars.remove(name);
         }
       }
       // Everything in this set is a partially-created variable error
       HashMap<String,Access> vars = arm ? _fvars : _tvars;
       if( vars.isEmpty() ) return mem;
       mem.unkeep(2);             // Passed-in 'hooked' memory
       for( String name : vars.keySet() ) {
         String msg = "'"+name+"' not defined on "+arm+" arm of trinary";
         Node err = gvn.xform(new ErrNode(ctrl,bad,msg));
         // Exactly like a parser store of an error, on the missing side
         mem = gvn.xform(new StoreNode(mem,scope.ptr(),err,Access.Final,name,bad));
       }
       return mem.keep(2);        // Return 'hooked' memory
     }
References com.cliffc.aa.node.ScopeNode.IfScope._fvars, com.cliffc.aa.node.ScopeNode.IfScope._tvars, com.cliffc.aa.util.Ary< E >.addAll(), com.cliffc.aa.node.ScopeNode.ctrl(), com.cliffc.aa.node.Node.err(), com.cliffc.aa.type.TypeFld.Access.Final, com.cliffc.aa.util.Ary< E >.isEmpty(), com.cliffc.aa.node.Node.keep(), com.cliffc.aa.node.ScopeNode.mem(), com.cliffc.aa.util.Ary< E >.pop(), com.cliffc.aa.node.ScopeNode.ptr(), com.cliffc.aa.node.Node.unkeep(), and com.cliffc.aa.GVNGCM.xform().
def()
void com.cliffc.aa.node.ScopeNode.IfScope.def (String name, Access mutable, boolean create) package
Definition at line 203 of file ScopeNode.java.
{
       if( _tvars == null ) { _tvars = new HashMap<>(); _fvars = new HashMap<>(); }
       // If there was no prior create inside the same if, then this update
       // predates the if and is not involved in a partial-creation error
       if( !create && !_arm && _tvars.get(name) != null )
         _fvars.put(name,mutable);
       if( create ) {
         HashMap<String,Access> vars = _arm ? _tvars : _fvars;
         Access res = vars.put(name,mutable);
         assert res==null;         // No double-creation
       }
     }
References com.cliffc.aa.node.ScopeNode.IfScope._arm, com.cliffc.aa.node.ScopeNode.IfScope._fvars, and com.cliffc.aa.node.ScopeNode.IfScope._tvars.
flip()
void com.cliffc.aa.node.ScopeNode.IfScope.flip () package
Definition at line 201 of file ScopeNode.java.
 { _arm = !_arm; }
References com.cliffc.aa.node.ScopeNode.IfScope._arm.
Member Data Documentation
_arm
boolean com.cliffc.aa.node.ScopeNode.IfScope._arm = true package
Definition at line 200 of file ScopeNode.java.
Referenced by com.cliffc.aa.node.ScopeNode.IfScope.def(), and com.cliffc.aa.node.ScopeNode.IfScope.flip().
_fvars
HashMap<String,Access> com.cliffc.aa.node.ScopeNode.IfScope._fvars package
Definition at line 199 of file ScopeNode.java.
Referenced by com.cliffc.aa.node.ScopeNode.IfScope.check(), and com.cliffc.aa.node.ScopeNode.IfScope.def().
_tvars
HashMap<String,Access> com.cliffc.aa.node.ScopeNode.IfScope._tvars package
Definition at line 199 of file ScopeNode.java.
Referenced by com.cliffc.aa.node.ScopeNode.IfScope.check(), and com.cliffc.aa.node.ScopeNode.IfScope.def().
The documentation for this class was generated from the following file:
ScopeNode.java