aa: com.cliffc.aa.HM.HM.Field Class Reference
com.cliffc.aa.HM.HM.Field Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Field (String id, Syntax str)
void add_hm_work (Worklist work)
void add_val_work (Syntax child, Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
Type val (Worklist work)
Package Attributes
Type _flow
T2 _hmt
final String _id
VStack _nongen
Syntax _par
final Syntax _rec
Detailed Description
Definition at line 890 of file HM.java.
Constructor & Destructor Documentation
Field()
com.cliffc.aa.HM.HM.Field.Field (String id, Syntax str) package
Definition at line 893 of file HM.java.
 { _id=id; _rec =str; }
References com.cliffc.aa.HM.HM.Field._id, com.cliffc.aa.HM.HM.Field._rec, com.cliffc.aa.HM.HM.id(), and com.cliffc.aa.HM.HM.Field.str().
Member Function Documentation
add_hm_work()
void com.cliffc.aa.HM.HM.Field.add_hm_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 917 of file HM.java.
{
       work.push(_par);
       work.push(_rec);
       _rec.add_hm_work(work);
     }
References com.cliffc.aa.HM.HM.Syntax._par, com.cliffc.aa.HM.HM.Field._rec, com.cliffc.aa.HM.HM.Syntax.add_hm_work(), and com.cliffc.aa.HM.HM.Worklist.push().
add_val_work()
void com.cliffc.aa.HM.HM.Syntax.add_val_work (Syntax child, Worklist work) package inherited
Reimplemented in com.cliffc.aa.HM.HM.PrimSyn, com.cliffc.aa.HM.HM.Apply, com.cliffc.aa.HM.HM.Let, and com.cliffc.aa.HM.HM.Lambda.
Definition at line 365 of file HM.java.
 {} // Add affected neighbors to worklist
Referenced by com.cliffc.aa.HM.HM.hm().
debug_find()
T2 com.cliffc.aa.HM.HM.Syntax.debug_find () package inherited
Definition at line 348 of file HM.java.
 { return _hmt.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM.Syntax._hmt, and com.cliffc.aa.HM.HM.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM.hm().
find()
T2 com.cliffc.aa.HM.HM.Syntax.find () package inherited
Definition at line 344 of file HM.java.
               {                 // U-F find
       T2 t = _hmt.find();
       return t== _hmt ? t : (_hmt =t);
     }
References com.cliffc.aa.HM.HM.Syntax._hmt, and com.cliffc.aa.HM.HM.T2.find().
Referenced by com.cliffc.aa.HM.HM.Lambda.add_hm_work(), com.cliffc.aa.HM.HM.Let.add_hm_work(), com.cliffc.aa.HM.HM.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM.Lambda.add_val_work(), com.cliffc.aa.HM.HM.Let.add_val_work(), com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM.Ident.hm(), com.cliffc.aa.HM.HM.Lambda.hm(), com.cliffc.aa.HM.HM.Apply.hm(), com.cliffc.aa.HM.HM.Root.hm(), com.cliffc.aa.HM.HM.Struct.hm(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.PrimSyn.hm(), com.cliffc.aa.HM.HM.If.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.Let.prep_tree(), com.cliffc.aa.HM.HM.Struct.prep_tree(), com.cliffc.aa.HM.HM.NotNil.prep_tree(), com.cliffc.aa.HM.HM.Apply.val(), com.cliffc.aa.HM.HM.Root.val(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
hm()
boolean com.cliffc.aa.HM.HM.Field.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 897 of file HM.java.
{
       if( find().is_err() ) return false; // Already an error; no progress
       T2 rec = _rec.find();
       if( rec.is_nilable() || (rec._alias!=null && rec._alias.test(0)) )
         return find().unify(T2.make_err("May be nil when loading field "+_id),work);
       rec.push_update(this);
       int idx = rec._ids==null ? -1 : Util.find(rec._ids,_id);
       if( idx!= -1 )            // Unify against a pre-existing field
         return rec.args(idx).unify(find(), work);
       // The remaining cases all make progress and return true
       if( work==null ) return true;
       if( rec.is_err() ) return find().unify(rec,work);
       // Not a struct or no field, force it to be one
       if( rec.is_struct() && rec._open ) // Effectively unify with an extended struct.
         return rec.add_fld(_id,find(),work);
       if( rec.is_leaf() )
         return T2.make_struct(BitsAlias.EMPTY,new String[]{_id}, new T2[]{find().push_update(rec._deps)},true).unify(rec, work);
       return find().unify(rec.miss_field(_id),work);
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.Field._id, com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.HM.HM.T2._open, com.cliffc.aa.HM.HM.Field._rec, com.cliffc.aa.HM.HM.T2.add_fld(), com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.type.BitsAlias.EMPTY, com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM.Syntax.find(), com.cliffc.aa.HM.HM.T2.is_err(), com.cliffc.aa.HM.HM.T2.is_leaf(), com.cliffc.aa.HM.HM.T2.is_nilable(), com.cliffc.aa.HM.HM.T2.is_struct(), com.cliffc.aa.HM.HM.T2.make_err(), com.cliffc.aa.HM.HM.T2.make_struct(), com.cliffc.aa.HM.HM.T2.miss_field(), com.cliffc.aa.HM.HM.T2.push_update(), com.cliffc.aa.type.Bits< B extends Bits< B >.test(), and com.cliffc.aa.HM.HM.T2.unify().
more_work()
boolean com.cliffc.aa.HM.HM.Field.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 941 of file HM.java.
{
       if( !more_work_impl(work) ) return false;
       return _rec.more_work(work);
     }
References com.cliffc.aa.HM.HM.Field._rec, com.cliffc.aa.HM.HM.Syntax.more_work(), and com.cliffc.aa.HM.HM.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 381 of file HM.java.
{
       if( work.has(this) ) return true;
       if( DO_HM && hm(null) )   // Any more HM work?
         return false;           // Found HM work not on worklist
       if( DO_GCP && val(null)!=_flow )
         return false;           // Found GCP work not on worklist
       return true;
     }
References com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Worklist.has(), com.cliffc.aa.HM.HM.Syntax.hm(), and com.cliffc.aa.HM.HM.Syntax.val().
Referenced by com.cliffc.aa.HM.HM.Con.more_work(), com.cliffc.aa.HM.HM.Ident.more_work(), com.cliffc.aa.HM.HM.Lambda.more_work(), com.cliffc.aa.HM.HM.Let.more_work(), com.cliffc.aa.HM.HM.Apply.more_work(), com.cliffc.aa.HM.HM.Struct.more_work(), com.cliffc.aa.HM.HM.Field.more_work(), and com.cliffc.aa.HM.HM.PrimSyn.more_work().
p()
String com.cliffc.aa.HM.HM.Syntax.p () inherited
Definition at line 393 of file HM.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 394 of file HM.java.
{
       _hmt.get_dups(dups);
       VBitSet visit = new VBitSet();
       p1(sb.i());
       if( DO_HM  ) _hmt .str(sb.p(", HM="), visit,dups);
       if( DO_GCP ) _flow.str(sb.p(", CCP="),visit.clr(),null,false);
       sb.nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.util.VBitSet.clr(), com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM.Syntax.p1(), com.cliffc.aa.HM.HM.Syntax.p2(), com.cliffc.aa.type.Type< T extends Type< T >.str(), and com.cliffc.aa.HM.HM.T2.str().
Referenced by com.cliffc.aa.HM.HM.Syntax.p(), com.cliffc.aa.HM.HM.Lambda.p2(), com.cliffc.aa.HM.HM.Let.p2(), com.cliffc.aa.HM.HM.Apply.p2(), com.cliffc.aa.HM.HM.Struct.p2(), and com.cliffc.aa.HM.HM.Field.p2().
p1()
SB com.cliffc.aa.HM.HM.Field.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 895 of file HM.java.
 { return sb.p(".").p(_id); }
References com.cliffc.aa.HM.HM.Field._id, and com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM.Field.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 896 of file HM.java.
 { return _rec.p0(sb,dups); }
References com.cliffc.aa.HM.HM.Field._rec, and com.cliffc.aa.HM.HM.Syntax.p0().
prep_lookup_deps()
void com.cliffc.aa.HM.HM.Syntax.prep_lookup_deps (Ident id) package inherited
Reimplemented in com.cliffc.aa.HM.HM.Let, and com.cliffc.aa.HM.HM.Lambda.
Definition at line 377 of file HM.java.
 {}
prep_tree()
int com.cliffc.aa.HM.HM.Field.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 937 of file HM.java.
{
       prep_tree_impl(par, nongen, work, T2.make_leaf());
       return _rec.prep_tree(this,nongen,work)+1;
     }
References com.cliffc.aa.HM.HM.Field._rec, com.cliffc.aa.HM.HM.T2.make_leaf(), com.cliffc.aa.HM.HM.Syntax.prep_tree(), and com.cliffc.aa.HM.HM.Syntax.prep_tree_impl().
prep_tree_impl()
final void com.cliffc.aa.HM.HM.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 370 of file HM.java.
{
       _par = par;
       _hmt = t;
       _flow= Type.XSCALAR;
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.Syntax._nongen, com.cliffc.aa.HM.HM.Syntax._par, com.cliffc.aa.HM.HM.Worklist.push(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Referenced by com.cliffc.aa.HM.HM.Con.prep_tree(), com.cliffc.aa.HM.HM.Ident.prep_tree(), com.cliffc.aa.HM.HM.Lambda.prep_tree(), com.cliffc.aa.HM.HM.Let.prep_tree(), com.cliffc.aa.HM.HM.Apply.prep_tree(), com.cliffc.aa.HM.HM.Struct.prep_tree(), com.cliffc.aa.HM.HM.Field.prep_tree(), and com.cliffc.aa.HM.HM.PrimSyn.prep_tree().
str()
SB com.cliffc.aa.HM.HM.Field.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 894 of file HM.java.
 { return _rec.str(sb).p(".").p(_id); }
References com.cliffc.aa.HM.HM.Field._id, com.cliffc.aa.HM.HM.Field._rec, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM.Syntax.str().
Referenced by com.cliffc.aa.HM.HM.Field.Field().
toString()
final String com.cliffc.aa.HM.HM.Syntax.toString () inherited
Definition at line 390 of file HM.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.HM.HM.Lambda.p1().
val()
Type com.cliffc.aa.HM.HM.Field.val (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 922 of file HM.java.
{
       Type trec = _rec._flow;
       if( trec.above_center() ) return Type.XSCALAR;
       if( trec instanceof TypeMemPtr ) {
         TypeMemPtr tmp = (TypeMemPtr)trec;
         if( tmp._obj instanceof TypeStruct ) {
           TypeStruct tstr = (TypeStruct)tmp._obj;
           int idx = tstr.fld_find(_id);
           if( idx!=-1 ) return tstr.at(idx); // Field type
         }
         if( tmp._obj.above_center() ) return Type.XSCALAR;
       }
       // TODO: Need an error type here
       return Type.SCALAR;
     }
References com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.Field._id, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.HM.HM.Field._rec, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.above_center(), com.cliffc.aa.type.Type< T extends Type< T >.above_center(), com.cliffc.aa.type.TypeStruct.at(), com.cliffc.aa.type.TypeStruct.fld_find(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Member Data Documentation
_flow
Type com.cliffc.aa.HM.HM.Syntax._flow package inherited
Definition at line 351 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM.Lambda.apply(), com.cliffc.aa.HM.HM.Pair1.apply(), com.cliffc.aa.HM.HM.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM.Pair.apply(), com.cliffc.aa.HM.HM.Triple.apply(), com.cliffc.aa.HM.HM.If.apply(), com.cliffc.aa.HM.HM.EQ.apply(), com.cliffc.aa.HM.HM.EQ0.apply(), com.cliffc.aa.HM.HM.IsEmpty.apply(), com.cliffc.aa.HM.HM.NotNil.apply(), com.cliffc.aa.HM.HM.Mul.apply(), com.cliffc.aa.HM.HM.Add.apply(), com.cliffc.aa.HM.HM.Dec.apply(), com.cliffc.aa.HM.HM.Str.apply(), com.cliffc.aa.HM.HM.Factor.apply(), com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.Lambda.Lambda(), com.cliffc.aa.HM.HM.Syntax.more_work_impl(), com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.HM.HM.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM.Ident.val(), com.cliffc.aa.HM.HM.Let.val(), com.cliffc.aa.HM.HM.Apply.val(), com.cliffc.aa.HM.HM.Root.val(), com.cliffc.aa.HM.HM.Struct.val(), com.cliffc.aa.HM.HM.Field.val(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
_hmt
T2 com.cliffc.aa.HM.HM.Syntax._hmt package inherited
Definition at line 343 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Syntax.debug_find(), com.cliffc.aa.HM.HM.Syntax.find(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.HM.HM.Let.prep_tree(), com.cliffc.aa.HM.HM.PrimSyn.prep_tree(), com.cliffc.aa.HM.HM.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM.PrimSyn.PrimSyn(), com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.HM.TestHM.test05(), com.cliffc.aa.HM.TestHM9.test05(), com.cliffc.aa.HM.TestHM.test06(), com.cliffc.aa.HM.TestHM9.test06(), com.cliffc.aa.HM.TestHM.test14(), com.cliffc.aa.HM.TestHM9.test14(), com.cliffc.aa.HM.TestHM.test18(), com.cliffc.aa.HM.TestHM9.test18(), com.cliffc.aa.HM.TestHM.test20(), com.cliffc.aa.HM.TestHM9.test20(), com.cliffc.aa.HM.TestHM9.test32(), com.cliffc.aa.HM.TestHM.test32(), com.cliffc.aa.HM.TestHM9.test33(), com.cliffc.aa.HM.TestHM.test33(), com.cliffc.aa.HM.TestHM9.test34(), com.cliffc.aa.HM.TestHM.test34(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.HM.TestHM.test36(), com.cliffc.aa.HM.TestHM.test39(), com.cliffc.aa.HM.TestHM9.test39(), com.cliffc.aa.HM.TestHM.test40(), com.cliffc.aa.HM.TestHM9.test40(), com.cliffc.aa.HM.TestHM.test41(), com.cliffc.aa.HM.TestHM9.test41(), com.cliffc.aa.HM.TestHM.test42(), com.cliffc.aa.HM.TestHM9.test42(), com.cliffc.aa.HM.TestHM.test43(), com.cliffc.aa.HM.TestHM9.test43(), com.cliffc.aa.HM.TestHM.test44(), com.cliffc.aa.HM.TestHM9.test44(), com.cliffc.aa.HM.TestHM.test45(), com.cliffc.aa.HM.TestHM9.test45(), com.cliffc.aa.HM.TestHM.test49(), com.cliffc.aa.HM.TestHM9.test49(), com.cliffc.aa.HM.TestHM.test50(), com.cliffc.aa.HM.TestHM9.test50(), com.cliffc.aa.HM.TestHM.test51(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.HM.TestHM.test55(), com.cliffc.aa.HM.TestHM.test56(), and com.cliffc.aa.HM.TestHM.test57().
_id
final String com.cliffc.aa.HM.HM.Field._id package
Definition at line 891 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Field.Field(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.Field.p1(), com.cliffc.aa.HM.HM.Field.str(), and com.cliffc.aa.HM.HM.Field.val().
_nongen
VStack com.cliffc.aa.HM.HM.Syntax._nongen package inherited
Definition at line 342 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Ident.add_hm_work(), com.cliffc.aa.HM.HM.Ident.hm(), and com.cliffc.aa.HM.HM.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM.Syntax._par package inherited
Definition at line 341 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Ident.add_hm_work(), com.cliffc.aa.HM.HM.Lambda.add_hm_work(), com.cliffc.aa.HM.HM.Let.add_hm_work(), com.cliffc.aa.HM.HM.Apply.add_hm_work(), com.cliffc.aa.HM.HM.Struct.add_hm_work(), com.cliffc.aa.HM.HM.Field.add_hm_work(), com.cliffc.aa.HM.HM.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.Ident.prep_tree(), and com.cliffc.aa.HM.HM.Syntax.prep_tree_impl().
_rec
final Syntax com.cliffc.aa.HM.HM.Field._rec package
Definition at line 892 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Field.add_hm_work(), com.cliffc.aa.HM.HM.Field.Field(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.Field.more_work(), com.cliffc.aa.HM.HM.Field.p2(), com.cliffc.aa.HM.HM.Field.prep_tree(), com.cliffc.aa.HM.HM.Field.str(), and com.cliffc.aa.HM.HM.Field.val().
The documentation for this class was generated from the following file:
HM.java