aa: com.cliffc.aa.node.CallEpiNode Class Reference
com.cliffc.aa.node.CallEpiNode Class Reference
Public Member Functions
CallEpiNode (Node... nodes)
Node add_def (Node n)
void add_flow_def_extra (Node chg)
void add_flow_extra (Type old)
void add_flow_use_extra (Node chg)
void add_reduce_extra ()
TypeMem all_live ()
CallNode call ()
boolean check_and_wire ()
Node copy (boolean copy_edges)
void del (int idx)
Node do_flow ()
Node do_grow ()
Node do_mono ()
Node do_reduce ()
String dump (int max)
String dump (int max, boolean prims, boolean plive)
String dumprpo (boolean prims, boolean plive)
boolean equals (Object o)
ErrMsg err (boolean fast)
Node find (int uid)
Node get_mem_writer ()
int hashCode ()
Node ideal_grow ()
Node ideal_mono ()
Node ideal_reduce ()
Node in (int i)
Node init1 ()
Node insert (int idx, Node n)
void insert (Node nnn)
Node is_copy (int idx)
boolean is_dead ()
boolean is_forward_ref ()
boolean is_mem ()
boolean is_multi_head ()
boolean is_prim ()
Node kill ()
int len ()
TypeMem live (GVNGCM.Mode opt_mode)
TypeMem live_use (GVNGCM.Mode opt_mode, Node def)
boolean live_uses ()
final int more_flow (boolean lifting)
final boolean more_ideal (VBitSet bs)
TV2 new_tvar (String alloc_site)
int nwired ()
byte op_prec ()
Node pop ()
Node remove (int idx)
void replace (Node old, Node nnn)
void set_dead ()
Node set_def (int idx, Node n)
Type sharptr (Node mem)
boolean should_con (Type t)
Node subsume (Node nnn)
String toString ()
TV2 tvar ()
TV2 tvar (int x)
void unelock ()
boolean unify (boolean test)
Type val (int idx)
Type value (GVNGCM.Mode opt_mode)
final void walk_initype (GVNGCM gvn, VBitSet bs)
void walk_opt (VBitSet visit)
void walkerr_def (HashSet< ErrMsg > errs, VBitSet bs)
RetNode wired (int x)
Node xliv (GVNGCM.Mode opt_mode)
String xstr ()
Type xval ()
Static Public Member Functions
static Node con (Type t)
static void init0 ()
static void reset_to_init0 ()
static void roll_back_CNT ()
Public Attributes
Ary< Node > _defs
boolean _elock
boolean _is_copy
byte _keep
TypeMem _live
int _uid
Ary< Node > _uses
Type _val
Static Public Attributes
static int _INIT0_CNT
static final ConcurrentHashMap< Node, Node > VALS = new ConcurrentHashMap<>()
Package Functions
Node _elock ()
boolean check_solo_mem_writer (Node memw)
BitsAlias escapees ()
boolean is_CFG ()
Node is_pure_call ()
public< N extends Node > N keep ()
public< N extends Node > N keep (int d)
int newuid ()
boolean sane_wiring ()
String str ()
public< N extends Node > N unhook ()
public< N extends Node > N unkeep ()
public< N extends Node > N unkeep (int d)
CallEpiNode unwire (CallNode call, RetNode ret)
Node walk_dom_last (Predicate< Node > P)
void wire0 (CallNode call, Node fun)
void wire1 (CallNode call, Node fun, Node ret)
Static Package Functions
[static initializer]
static BitsAlias esc_out (TypeMem tmem, Type trez)
Package Attributes
final byte _op
TV2 _tvar
Static Package Attributes
static final byte OP_CALL = 1
static final byte OP_CALLEPI = 2
static final byte OP_CAST = 3
static final byte OP_CON = 4
static final byte OP_CONTYPE = 5
static final byte OP_CPROJ = 6
static final byte OP_DEFMEM = 7
static final byte OP_ERR = 8
static final byte OP_FP2DISP =10
static final byte OP_FRESH = 9
static final byte OP_FUN =11
static final byte OP_FUNPTR =12
static final byte OP_IF =13
static final byte OP_JOIN =14
static final byte OP_LOAD =15
static final byte OP_LOOP =16
static final byte OP_MAX =36
static final byte OP_NAME =17
static final byte OP_NEWARY =19
static final byte OP_NEWOBJ =18
static final byte OP_NEWSTR =20
static final byte OP_PARM =21
static final byte OP_PHI =22
static final byte OP_PRIM =23
static final byte OP_PROJ =24
static final byte OP_REGION =25
static final byte OP_RET =26
static final byte OP_SCOPE =27
static final byte OP_SPLIT =28
static final byte OP_START =29
static final byte OP_STMEM =30
static final byte OP_STORE =31
static final byte OP_THRET =32
static final byte OP_THUNK =33
static final byte OP_TYPE =34
static final byte OP_UNR =35
Private Member Functions
Node _do_reduce ()
void adderr (HashSet< ErrMsg > errs)
boolean check_vals ()
SB dump (int d, SB sb, boolean plive)
SB dump (int d, SB sb, int max, VBitSet bs, boolean prims, boolean plive)
void dump (int d, SB sb, VBitSet bs, boolean plive)
Node find (int uid, VBitSet bs)
boolean is_multi_tail ()
Node merge (Node x)
int more_flow (boolean lifting, int errs)
void postorder (Ary< Node > nodes, VBitSet bs)
CallEpiNode set_is_copy (Node ctl, Node mem, Node rez)
Node unuse (Node old)
Static Private Member Functions
static void _header (FunNode fun, SB sb)
Static Private Attributes
static int CNT =1
static final VBitSet FLOW_VISIT = new VBitSet()
static final VBitSet LIVE = new VBitSet()
static final String[] STRS = new String[] { null, "Call", "CallEpi", "Cast", "Con", "ConType", "CProj", "DefMem", "Err", "Fresh", "FP2Disp", "Fun", "FunPtr", "If", "Join", "Load", "Loop", "Name", "NewObj", "NewAry", "NewStr", "Parm", "Phi", "Prim", "Proj", "Region", "Return", "Scope","Split", "Start", "StartMem", "Store", "Thret", "Thunk", "Type", "Unresolved" }
Detailed Description
Definition at line 24 of file CallEpiNode.java.
Constructor & Destructor Documentation
CallEpiNode()
com.cliffc.aa.node.CallEpiNode.CallEpiNode (Node... nodes)
Definition at line 26 of file CallEpiNode.java.
{
     super(OP_CALLEPI,nodes);
     assert nodes[1] instanceof DefMemNode;
   }
References com.cliffc.aa.node.Node.OP_CALLEPI.
Member Function Documentation
[static initializer]()
com.cliffc.aa.node.Node.[static initializer] static package inherited
_do_reduce()
Node com.cliffc.aa.node.Node._do_reduce () private inherited
Definition at line 570 of file Node.java.
{
     // Replace with a constant, if possible
     if( should_con(_val) )
       return con(_val);
     // Try CSE
     if( !_elock ) {             // Not in VALS
       Node x = VALS.get(this);  // Try VALS
       if( x != null )           // Hit
         return merge(x);        // Graph replace with x
     }
     // Try general ideal call
     Node x = ideal_reduce();    // Try the general reduction
     if( x != null )
       return merge(x);          // Graph replace with x
     return null;                // No change
   }
References com.cliffc.aa.node.Node._elock, com.cliffc.aa.node.Node._val, com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.Node.ideal_reduce(), com.cliffc.aa.node.Node.merge(), com.cliffc.aa.node.Node.should_con(), and com.cliffc.aa.node.Node.VALS.
Referenced by com.cliffc.aa.node.Node.do_reduce().
_elock()
Node com.cliffc.aa.node.Node._elock () package inherited
Definition at line 137 of file Node.java.
                 {               // No assert version, used for new nodes
     assert check_vals();        // elock & VALs match
     if( !_elock && VALS.get(this)==null ) { _elock = true; VALS.put(this,this); }
     return this;
   }
References com.cliffc.aa.node.Node._elock, com.cliffc.aa.node.Node.check_vals(), and com.cliffc.aa.node.Node.VALS.
_header()
static void com.cliffc.aa.node.Node._header (FunNode fun, SB sb) static private inherited
Definition at line 380 of file Node.java.
{
     sb.p("============ ").p(fun==null?"null":fun.name()).p(" ============").nl();
   }
References com.cliffc.aa.node.FunNode.name(), com.cliffc.aa.util.SB.nl(), and com.cliffc.aa.util.SB.p().
Referenced by com.cliffc.aa.node.Node.dumprpo().
add_def()
Node com.cliffc.aa.node.Node.add_def (Node n) inherited
Definition at line 152 of file Node.java.
 { unelock(); _defs.add(n); if( n!=null ) n._uses.add(this); return this; }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._uses, and com.cliffc.aa.node.Node.unelock().
Referenced by com.cliffc.aa.node.MemJoinNode.add_alias_above(), com.cliffc.aa.node.MemJoinNode.add_alias_below(), com.cliffc.aa.node.UnresolvedNode.add_def_unresolved(), com.cliffc.aa.node.NewObjNode.add_fun(), com.cliffc.aa.node.MemPrimNode.ReadPrimNode.as_fun(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.as_fun(), com.cliffc.aa.node.PrimNode.as_fun(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun(), com.cliffc.aa.node.TestNodeSmall.check(), com.cliffc.aa.node.MemJoinNode.combine_splits(), com.cliffc.aa.node.IntrinsicNode.convertTypeName(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.node.Node.copy(), com.cliffc.aa.node.ConTypeNode.def_fref(), com.cliffc.aa.Parse.do_exit(), com.cliffc.aa.Parse.func(), com.cliffc.aa.node.FunNode.FunNode(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.LoadNode.ideal_grow(), com.cliffc.aa.node.UnresolvedNode.ideal_reduce(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.node.DefMemNode.make_mem(), com.cliffc.aa.Parse.merge_exits(), com.cliffc.aa.node.ScopeNode.ScopeNode(), com.cliffc.aa.node.CallEpiNode.set_is_copy(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.node.RegionNode.stacked_region(), com.cliffc.aa.node.RetNode.tail_recursive(), com.cliffc.aa.node.TestNode.test1monotonic_prim(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.node.CallEpiNode.wire0(), and com.cliffc.aa.node.CallEpiNode.wire1().
add_flow_def_extra()
void com.cliffc.aa.node.Node.add_flow_def_extra (Node chg) inherited
Reimplemented in com.cliffc.aa.node.CallNode, com.cliffc.aa.node.NewNode< T extends TypeObj< T >, com.cliffc.aa.node.RegionNode, com.cliffc.aa.node.MrgProjNode, and com.cliffc.aa.node.MemJoinNode.
Definition at line 515 of file Node.java.
 { }
Referenced by com.cliffc.aa.node.ScopeNode.set_mem(), and com.cliffc.aa.node.Node.unuse().
add_flow_extra()
void com.cliffc.aa.node.Node.add_flow_extra (Type old) inherited
Reimplemented in com.cliffc.aa.node.CallNode, com.cliffc.aa.node.FunPtrNode, com.cliffc.aa.node.StoreNode, com.cliffc.aa.node.CastNode, and com.cliffc.aa.node.FreshNode.
Definition at line 513 of file Node.java.
 { }
Referenced by com.cliffc.aa.node.Node.do_flow(), and com.cliffc.aa.GVNGCM.gcp().
add_flow_use_extra()
void com.cliffc.aa.node.CallEpiNode.add_flow_use_extra (Node chg)
Reimplemented from com.cliffc.aa.node.Node.
Definition at line 369 of file CallEpiNode.java.
{
     if( chg instanceof CallNode ) { // If the Call changes value
       Env.GVN.add_flow(chg.in(MEM_IDX));       // The called memory   changes liveness
       Env.GVN.add_flow(((CallNode)chg).fdx()); // The called function changes liveness
       for( int i=0; i<nwired(); i++ )          // Called returns change liveness
         Env.GVN.add_flow(wired(i));
     }
   }
References com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.in(), com.cliffc.aa.node.CallEpiNode.nwired(), and com.cliffc.aa.node.CallEpiNode.wired().
add_reduce_extra()
void com.cliffc.aa.node.Node.add_reduce_extra () inherited
Reimplemented in com.cliffc.aa.node.CallNode, com.cliffc.aa.node.StoreNode, com.cliffc.aa.node.NewNode< T extends TypeObj< T >, and com.cliffc.aa.node.MemSplitNode.
Definition at line 517 of file Node.java.
 { }
Referenced by com.cliffc.aa.node.Node.do_reduce().
adderr()
void com.cliffc.aa.node.Node.adderr (HashSet< ErrMsg > errs) private inherited
Definition at line 789 of file Node.java.
{
     ErrMsg msg = err(false);
     if( msg==null ) return;
     msg._order = errs.size();
     errs.add(msg);
   }
References com.cliffc.aa.node.Node.ErrMsg._order, and com.cliffc.aa.node.Node.err().
Referenced by com.cliffc.aa.node.Node.walkerr_def().
all_live()
TypeMem com.cliffc.aa.node.CallEpiNode.all_live ()
Reimplemented from com.cliffc.aa.node.Node.
Definition at line 437 of file CallEpiNode.java.
 { return TypeMem.ALLMEM; }
References com.cliffc.aa.type.TypeMem.ALLMEM.
Referenced by com.cliffc.aa.node.CallEpiNode.live_use().
call()
CallNode com.cliffc.aa.node.CallEpiNode.call ()
Definition at line 35 of file CallEpiNode.java.
 { return (CallNode)in(0); }
References com.cliffc.aa.node.Node.in().
Referenced by com.cliffc.aa.node.LoadNode._find_previous_store_call(), com.cliffc.aa.node.CallEpiNode.check_and_wire(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.CallEpiNode.is_pure_call(), com.cliffc.aa.node.CallEpiNode.live_use(), com.cliffc.aa.node.CallEpiNode.sane_wiring(), com.cliffc.aa.node.CallEpiNode.set_is_copy(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.node.RetNode.tail_recursive(), com.cliffc.aa.node.CallEpiNode.unwire(), com.cliffc.aa.node.CallEpiNode.value(), com.cliffc.aa.node.CallEpiNode.wire0(), and com.cliffc.aa.node.CallEpiNode.wire1().
check_and_wire()
boolean com.cliffc.aa.node.CallEpiNode.check_and_wire ()
Definition at line 179 of file CallEpiNode.java.
{
     if( !(_val instanceof TypeTuple) ) return false; // Collapsing
     CallNode call = call();
     Type tcall = call._val;
     if( !(tcall instanceof TypeTuple) ) return false;
     BitsFun fidxs = CallNode.ttfp(tcall)._fidxs;
     if( fidxs.above_center() )  return false; // Still choices to be made during GCP.
     // Check all fidxs for being wirable
     boolean progress = false;
     for( int fidx : fidxs ) {                 // For all fidxs
       if( BitsFun.is_parent(fidx) ) continue; // Do not wire parents, as they will eventually settle out
       FunNode fun = FunNode.find_fidx(fidx);  // Lookup, even if not wired
       if( fun.is_dead() ) continue;           // Already dead, stale fidx
       if( fun.is_forward_ref() ) continue;    // Not forward refs, which at GCP just means a syntax error
       RetNode ret = fun.ret();
       if( ret==null ) continue;               // Mid-death
       if( _defs.find(ret) != -1 ) continue;   // Wired already
       if( !CEProjNode.good_call(tcall,fun) ) continue; // Args fail basic sanity
       progress=true;
       wire1(call,fun,ret);      // Wire Call->Fun, Ret->CallEpi
     }
     return progress;
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.type.TypeFunPtr._fidxs, com.cliffc.aa.node.Node._val, com.cliffc.aa.type.Bits< B extends Bits< B >.above_center(), com.cliffc.aa.node.CallEpiNode.call(), com.cliffc.aa.node.FunNode.find_fidx(), com.cliffc.aa.node.CEProjNode.good_call(), com.cliffc.aa.node.Node.is_dead(), com.cliffc.aa.node.FunNode.is_forward_ref(), com.cliffc.aa.type.BitsFun.is_parent(), com.cliffc.aa.node.FunNode.ret(), com.cliffc.aa.node.CallNode.ttfp(), and com.cliffc.aa.node.CallEpiNode.wire1().
Referenced by com.cliffc.aa.GVNGCM.check_and_wire(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), and com.cliffc.aa.node.CallNode.ideal_reduce().
check_solo_mem_writer()
boolean com.cliffc.aa.node.Node.check_solo_mem_writer (Node memw) package inherited
Definition at line 845 of file Node.java.
{
     if( is_prim() ) return true; // Several top-level memory primitives, including top scope & defmem blow this
     boolean found=false;
     for( Node use : _uses )
       if( use == memw ) found=true; // Only memw mem-writer follows
       else if( use.is_mem() ) return false; // Found a 2nd mem-writer
     return found;
   }
References com.cliffc.aa.node.Node._uses, and com.cliffc.aa.node.Node.is_prim().
Referenced by com.cliffc.aa.node.MemJoinNode.add_alias_above(), com.cliffc.aa.node.MemSplitNode.check_split(), com.cliffc.aa.node.StoreNode.ideal_grow(), and com.cliffc.aa.node.MemJoinNode.ideal_mono().
check_vals()
boolean com.cliffc.aa.node.Node.check_vals () private inherited
Definition at line 143 of file Node.java.
{
     Node x = VALS.get(this), old=null;
     if( x == this ) old=this;   // Found in table quickly
     // Hunt the hard way
     else for( Node o : VALS.keySet() ) if( o._uid == _uid ) { old=o; break; }
     return (old!=null) == _elock;
   }
References com.cliffc.aa.node.Node._elock, com.cliffc.aa.node.Node._uid, and com.cliffc.aa.node.Node.VALS.
Referenced by com.cliffc.aa.node.Node._elock(), com.cliffc.aa.node.Node.do_reduce(), and com.cliffc.aa.node.Node.unelock().
con()
static Node com.cliffc.aa.node.Node.con (Type t) static inherited
Definition at line 670 of file Node.java.
{
     assert t==t.simple_ptr();
     Node con;
     if( t instanceof TypeFunPtr && ((TypeFunPtr)t)._fidxs.abit()!=-1 )
       con = new FunPtrNode(FunNode.find_fidx(((TypeFunPtr)t).fidx()).ret(),Env.ANY);
     else
       con = new ConNode<>(t);
     Node con2 = VALS.get(con);
     if( con2 != null ) {        // Found a prior constant
       con.kill();               // Kill the just-made one
       con = con2;
       con._live = TypeMem.LIVE_BOT; // Adding more liveness
     } else {                        // New constant
       con._val = t;                 // Typed
       con._elock(); // Put in VALS, since if Con appears once, probably appears again in the same XFORM call
     }
     Env.GVN.add_flow(con);      // Updated live flows
     return con;
   }
References com.cliffc.aa.node.Node._elock, com.cliffc.aa.node.Node._live, com.cliffc.aa.node.Node._val, com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.Env.ANY, com.cliffc.aa.node.FunNode.find_fidx(), com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.kill(), com.cliffc.aa.type.TypeMem.LIVE_BOT, com.cliffc.aa.node.FunNode.ret(), com.cliffc.aa.type.Type< T extends Type< T >.simple_ptr(), and com.cliffc.aa.node.Node.VALS.
Referenced by com.cliffc.aa.node.Node._do_reduce(), com.cliffc.aa.node.MemPrimNode.ReadPrimNode.as_fun(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.as_fun(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun(), com.cliffc.aa.Parse.con(), com.cliffc.aa.node.IntrinsicNode.convertTypeName(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.node.CallNode.copy(), com.cliffc.aa.node.ConNode< T extends Type >.equals(), com.cliffc.aa.node.FunPtrNode.forward_ref(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.ScopeNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.Env.init(), com.cliffc.aa.node.NewNode< TypeStruct >.kill2(), com.cliffc.aa.node.DefMemNode.make_mem(), com.cliffc.aa.node.NewObjNode.promote_forward(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.TestLive.testNewObj(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.Env.top_scope(), and com.cliffc.aa.node.Node.walk_opt().
copy()
Node com.cliffc.aa.node.Node.copy (boolean copy_edges) inherited
Reimplemented in com.cliffc.aa.node.FunNode, com.cliffc.aa.node.MemSplitNode, com.cliffc.aa.node.CallNode, com.cliffc.aa.node.NewNode< T extends TypeObj< T >, and com.cliffc.aa.node.CastNode.
Definition at line 264 of file Node.java.
{
     try {
       Node n = (Node)clone();
       n._uid = newuid();                  // A new UID
       n._defs = new Ary<>(new Node[1],0); // New empty defs
       n._uses = new Ary<>(new Node[1],0); // New empty uses
       n._tvar = n.new_tvar("copy_constructor");
       n._keep = 0;              // Not keeping, even if cloning a mid-keeper operation
       n._elock=false;           // Not in GVN
       if( copy_edges )
         for( Node def : _defs )
           n.add_def(def);
       Env.GVN.add_work_all(n);
       return n;
     } catch( CloneNotSupportedException cns ) { throw new RuntimeException(cns); }
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._elock, com.cliffc.aa.node.Node._keep, com.cliffc.aa.node.Node._tvar, com.cliffc.aa.node.Node._uid, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node.add_def(), com.cliffc.aa.GVNGCM.add_work_all(), com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.new_tvar(), com.cliffc.aa.node.Node.newuid(), and com.cliffc.aa.node.Node.Node().
Referenced by com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.FunNode.split_callers(), and com.cliffc.aa.node.TestNode.test1monotonic_prim().
del()
void com.cliffc.aa.node.Node.del (int idx) inherited
Definition at line 169 of file Node.java.
{
     unelock();
     Node n = _defs.del(idx);
     if( n != null ) n._uses.del(this);
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._uses, and com.cliffc.aa.node.Node.unelock().
Referenced by com.cliffc.aa.node.FunNode.split_callers(), and com.cliffc.aa.node.CallEpiNode.unwire().
do_flow()
Node com.cliffc.aa.node.Node.do_flow () inherited
Definition at line 592 of file Node.java.
{
     Node progress=null;
     // Compute live bits.  If progress, push the defs on the flow worklist.
     // This is a reverse flow computation.  Always assumed live if keep.
     if( _keep==0 ) {
       TypeMem oliv = _live;
       TypeMem nliv = live(Env.GVN._opt_mode);
       if( oliv != nliv ) {        // Progress?
         progress = this;          // Progress!
         assert nliv.isa(oliv);    // Monotonically improving
         _live = nliv;             // Record progress
         for( Node def : _defs )   // Put defs on worklist... liveness flows uphill
           if( def != null ) Env.GVN.add_flow(def).add_flow_def_extra(this);
         add_flow_extra(oliv);
       }
     }
     // Compute best value.  If progress, push uses on the flow worklist.
     // This is a forward flow computation.
     Type oval = _val; // Get old type
     Type nval = value(Env.GVN._opt_mode);// Get best type
     if( nval!=oval ) {
       progress = this;          // Progress!
       assert nval.isa(oval);    // Monotonically improving
       _val = nval;
       // If becoming a constant, check for replacing with a ConNode
       if( !oval.may_be_con() && nval.may_be_con() ) {
         Env.GVN.add_reduce(this);
         Env.GVN.add_flow_defs(this); // Since a constant, inputs are no longer live
       }
       // Put uses on worklist... values flows downhill
       for( Node use : _uses )
         Env.GVN.add_flow(use).add_flow_use_extra(this);
       // Progressing on CFG can mean CFG paths go dead
       if( is_CFG() ) for( Node use : _uses ) if( use.is_CFG() ) Env.GVN.add_reduce(use);
       add_flow_extra(oval);
     }
     return progress;
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._keep, com.cliffc.aa.node.Node._live, com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node._val, com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.GVNGCM.add_flow_defs(), com.cliffc.aa.node.Node.add_flow_extra(), com.cliffc.aa.GVNGCM.add_reduce(), com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.is_CFG(), com.cliffc.aa.type.Type< T extends Type< T >.isa(), com.cliffc.aa.node.Node.live(), com.cliffc.aa.type.Type< T extends Type< T >.may_be_con(), and com.cliffc.aa.node.Node.value().
Referenced by com.cliffc.aa.node.DefMemNode.make_mem(), and com.cliffc.aa.GVNGCM.xreduce().
do_grow()
Node com.cliffc.aa.node.Node.do_grow () inherited
Definition at line 639 of file Node.java.
{
     Node nnn = ideal_grow();
     if( nnn==null || nnn==this || is_dead() ) return nnn;
     assert _keep<=1;
     if( _keep==1 ) { _keep--; nnn._keep++; Env.GVN.add_dead(this); } // Doing an arbitrary replacement
     return Env.GVN.add_flow(Env.GVN.add_reduce(nnn));
   }
References com.cliffc.aa.node.Node._keep, com.cliffc.aa.GVNGCM.add_dead(), com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.GVNGCM.add_reduce(), com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.ideal_grow(), and com.cliffc.aa.node.Node.is_dead().
Referenced by com.cliffc.aa.node.Node.more_ideal().
do_mono()
Node com.cliffc.aa.node.Node.do_mono () inherited
Definition at line 632 of file Node.java.
{
     Node x= ideal_mono();
     if( x==null ) return null;
     assert x==this;
     return Env.GVN.add_mono(Env.GVN.add_flow(Env.GVN.add_reduce(x)));
   }
References com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.GVNGCM.add_mono(), com.cliffc.aa.GVNGCM.add_reduce(), com.cliffc.aa.Env.GVN, and com.cliffc.aa.node.Node.ideal_mono().
Referenced by com.cliffc.aa.node.Node.more_ideal().
do_reduce()
Node com.cliffc.aa.node.Node.do_reduce () inherited
Definition at line 545 of file Node.java.
{
     assert check_vals();
     Node nnn = _do_reduce();
     if( nnn!=null ) {                   // Something happened
       if( nnn!=this ) {                 // Replacement
         assert _keep<=1;                // Can only replace if zero or one
         Env.GVN.add_flow_uses(this);    // Visit users
         add_reduce_extra();
         if( _keep==1 ) { _keep--; nnn._keep++; } // Move keep bits over
         subsume(nnn);                   // Replace
         for( Node use : nnn._uses ) {
           use.add_reduce_extra();
           use.add_flow_use_extra(nnn);
         }
       }
       Env.GVN.add_reduce(nnn);  // Rerun the replacement
       return nnn._elock();      // After putting in VALS
     }
     // No progress; put in VALS and return
     _elock();
     return null;
   }
References com.cliffc.aa.node.Node._do_reduce(), com.cliffc.aa.node.Node._elock, com.cliffc.aa.node.Node._keep, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node.add_flow_use_extra(), com.cliffc.aa.GVNGCM.add_flow_uses(), com.cliffc.aa.GVNGCM.add_reduce(), com.cliffc.aa.node.Node.add_reduce_extra(), com.cliffc.aa.node.Node.check_vals(), com.cliffc.aa.Env.GVN, and com.cliffc.aa.node.Node.subsume().
Referenced by com.cliffc.aa.node.Node.more_ideal(), com.cliffc.aa.GVNGCM.Build< N extends Node >.xform(), and com.cliffc.aa.GVNGCM.xreduce().
dump() [1/5]
SB com.cliffc.aa.node.Node.dump (int d, SB sb, boolean plive) private inherited
Definition at line 290 of file Node.java.
{
     String xs = String.format("%s%4d: %-7.7s ",plive ? _live : "",_uid,xstr());
     sb.i(d).p(xs);
     if( is_dead() ) return sb.p("DEAD");
     for( Node n : _defs ) sb.p(n == null ? "____ " : String.format("%4d ",n._uid));
     sb.p(" [[");
     for( Node n : _uses ) sb.p(String.format("%4d ",n._uid));
     sb.p("]]  ");
     sb.p(str()).s();
     if( _val==null ) sb.p("----");
     else _val.str(sb,new VBitSet(),null,true);
     return sb;
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._live, com.cliffc.aa.node.Node._uid, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node._val, com.cliffc.aa.util.SB.i(), com.cliffc.aa.node.Node.is_dead(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.util.SB.s(), com.cliffc.aa.type.Type< T extends Type< T >.str(), com.cliffc.aa.node.Node.str(), and com.cliffc.aa.node.Node.xstr().
dump() [2/5]
SB com.cliffc.aa.node.Node.dump (int d, SB sb, int max, VBitSet bs, boolean prims, boolean plive) private inherited
Definition at line 310 of file Node.java.
{
     if( bs.tset(_uid) ) return sb;
     if( d < max ) {    // Limit at depth
       // Print parser scopes first (deepest)
       for( Node n : _defs ) if( n instanceof ScopeNode ) n.dump(d+1,sb,max,bs,prims,plive);
       // Print constants early
       for( Node n : _defs ) if( n instanceof ConNode ) n.dump(d+1,sb,max,bs,prims,plive);
       // Do not recursively print root Scope, nor Unresolved of primitives.
       // These are too common, and uninteresting.
       for( Node n : _defs ) if( n != null && (!prims && n.is_prim() && n._defs._len > 3) ) bs.set(n._uid);
       // Recursively print most of the rest, just not the multi-node combos and
       // Unresolve & FunPtrs.
       for( Node n : _defs )
         if( n != null && !n.is_multi_head() && !n.is_multi_tail() &&
             !(n instanceof UnresolvedNode) && !(n instanceof FunPtrNode) )
           n.dump(d+1,sb,max,bs,prims,plive);
       // Print Unresolved and FunPtrs, which typically catch whole functions.
       for( Node n : _defs )
         if( (n instanceof UnresolvedNode) || (n instanceof FunPtrNode) )
           n.dump(d+1,sb,max,bs,prims,plive);
       // Print anything not yet printed, including multi-node combos
       for( Node n : _defs ) if( n != null && !n.is_multi_head() ) n.dump(d+1,sb,max,bs,prims,plive);
       for( Node n : _defs ) if( n != null ) n.dump(d+1,sb,max,bs,prims,plive);
     }
     // Print multi-node combos all-at-once, including all tails even if they
     // exceed the depth limit by 1.
     Node x = is_multi_tail() ? in(0) : this;
     if( x != null && x.is_multi_head() ) {
       int dx = d+(x==this?0:1);
       // Print all tails paths, all at once - nothing recursively below the tail
       for( Node n : x._uses )
         if( n.is_multi_tail() )
           for( Node m : n._defs )
             if( dx<max) m.dump(dx+1,sb,max,bs,prims,plive);
       if( x==this ) bs.clear(_uid); // Reset for self, so prints right now
       x.dump(dx,sb,bs,plive); // Conditionally print head of combo
       // Print all combo tails, if not already printed
       if( x!=this ) bs.clear(_uid); // Reset for self, so prints in the mix below
       for( Node n : x._uses ) if( n.is_multi_tail() ) n.dump(dx-1,sb,bs,plive);
       return sb;
     } else { // Neither combo head nor tail, just print
       return dump(d,sb,plive).nl();
     }
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._uid, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node.dump(), com.cliffc.aa.node.Node.in(), com.cliffc.aa.node.Node.is_multi_head(), com.cliffc.aa.node.Node.is_multi_tail(), and com.cliffc.aa.util.VBitSet.tset().
dump() [3/5]
void com.cliffc.aa.node.Node.dump (int d, SB sb, VBitSet bs, boolean plive) private inherited
Definition at line 305 of file Node.java.
{
     if( bs.tset(_uid) ) return;
     dump(d,sb,plive).nl();
   }
References com.cliffc.aa.node.Node._uid, com.cliffc.aa.node.Node.dump(), and com.cliffc.aa.util.VBitSet.tset().
dump() [4/5]
String com.cliffc.aa.node.Node.dump (int max) inherited
Definition at line 286 of file Node.java.
 { return dump(max,is_prim(),false); }
References com.cliffc.aa.node.Node.dump(), and com.cliffc.aa.node.Node.is_prim().
Referenced by com.cliffc.aa.Parse.dump(), com.cliffc.aa.node.Node.dump(), com.cliffc.aa.node.Node.dumprpo(), com.cliffc.aa.node.Node.more_flow(), and com.cliffc.aa.node.Node.toString().
dump() [5/5]
String com.cliffc.aa.node.Node.dump (int max, boolean prims, boolean plive) inherited
Definition at line 288 of file Node.java.
 { return dump(0, new SB(),max,new VBitSet(),prims,plive).toString();  }
References com.cliffc.aa.node.Node.dump().
Referenced by com.cliffc.aa.node.Node.dump().
dumprpo()
String com.cliffc.aa.node.Node.dumprpo (boolean prims, boolean plive) inherited
Definition at line 358 of file Node.java.
{
     Ary<Node> nodes = new Ary<>(new Node[1],0);
     postorder(nodes,new VBitSet());
     // Dump in reverse post order
     SB sb = new SB();
     Node prior = null;
     for( int i=nodes._len-1; i>=0; i-- ) {
       Node n = nodes.at(i);
       if( !(n._uid <= Env.ALL_CTRL._uid || !n.is_prim() || prims) )
         continue;               // Visited, but do not print
       // Add a nl after the last of a multi-tail sequence.
       if( (prior != null && prior.is_multi_tail() && !n.is_multi_tail()) ||
           // Add a nl before the start of a multi-head sequence.
           n.is_multi_head() )
         sb.nl();
       if( n._op==OP_FUN ) _header((FunNode)n,sb);
       n.dump(0,sb,plive).nl();
       if( n._op==OP_RET && n.in(4) instanceof FunNode ) _header((FunNode)n.in(4),sb);
       prior = n;
     }
     return sb.toString();
   }
References com.cliffc.aa.node.Node._header(), com.cliffc.aa.util.Ary< E >._len, com.cliffc.aa.node.Node._op, com.cliffc.aa.node.Node._uid, com.cliffc.aa.Env.ALL_CTRL, com.cliffc.aa.util.Ary< E >.at(), com.cliffc.aa.node.Node.dump(), com.cliffc.aa.node.Node.in(), com.cliffc.aa.node.Node.is_multi_head(), com.cliffc.aa.node.Node.is_multi_tail(), com.cliffc.aa.node.Node.is_prim(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.node.Node.OP_FUN, com.cliffc.aa.node.Node.OP_RET, com.cliffc.aa.node.Node.postorder(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.Parse.dumprpo().
equals()
boolean com.cliffc.aa.node.Node.equals (Object o) inherited
Reimplemented in com.cliffc.aa.node.FunNode, com.cliffc.aa.node.CallNode, com.cliffc.aa.node.PrimNode.RandI64, com.cliffc.aa.node.LoadNode, com.cliffc.aa.node.ScopeNode, com.cliffc.aa.node.StoreNode, com.cliffc.aa.node.PrimNode, com.cliffc.aa.node.NewNode< T extends TypeObj< T >, com.cliffc.aa.node.UnresolvedNode, com.cliffc.aa.node.ConTypeNode, com.cliffc.aa.node.FreshNode, com.cliffc.aa.node.ProjNode, com.cliffc.aa.node.DefMemNode, com.cliffc.aa.node.RetNode, com.cliffc.aa.node.ConNode< T extends Type >, com.cliffc.aa.node.ThunkNode, com.cliffc.aa.node.ErrNode, com.cliffc.aa.node.ParmNode, com.cliffc.aa.node.PhiNode, com.cliffc.aa.node.StartNode, com.cliffc.aa.node.CEProjNode, and com.cliffc.aa.node.StartMemNode.
Definition at line 112 of file Node.java.
{
     if( this==o ) return true;
     if( !(o instanceof Node) ) return false;
     Node n = (Node)o;
     if( _op != n._op ) return false;
     if( n._defs==null || _defs._len != n._defs._len ) return false;
     // Note pointer-equality
     for( int i=0; i<_defs._len; i++ ) if( _defs._es[i] != n._defs._es[i] ) return false;
     return true;
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._op, and com.cliffc.aa.node.Node.Node().
err()
ErrMsg com.cliffc.aa.node.Node.err (boolean fast) inherited
Reimplemented in com.cliffc.aa.node.CallNode, com.cliffc.aa.node.LoadNode, com.cliffc.aa.node.FunPtrNode, com.cliffc.aa.node.MemPrimNode.LValueWriteFinal, com.cliffc.aa.node.PrimNode.ConvertTypeName, com.cliffc.aa.node.PrimNode, com.cliffc.aa.node.StoreNode, com.cliffc.aa.node.IntrinsicNode, com.cliffc.aa.node.AssertNode, com.cliffc.aa.node.ParmNode, com.cliffc.aa.node.PhiNode, com.cliffc.aa.node.ErrNode, and com.cliffc.aa.node.MemPrimNode.
Definition at line 526 of file Node.java.
 { return null; }
Referenced by com.cliffc.aa.node.Node.adderr(), com.cliffc.aa.node.ScopeNode.IfScope.check(), com.cliffc.aa.node.Node.ErrMsg.equals(), com.cliffc.aa.node.Node.live_uses(), and com.cliffc.aa.node.Node.should_con().
esc_out()
static BitsAlias com.cliffc.aa.node.CallEpiNode.esc_out (TypeMem tmem, Type trez) static package
Definition at line 361 of file CallEpiNode.java.
{
     if( trez == Type.XNIL || trez == Type.NIL ) return BitsAlias.EMPTY;
     if( trez instanceof TypeFunPtr ) trez = ((TypeFunPtr)trez)._disp;
     if( trez instanceof TypeMemPtr )
       return tmem.all_reaching_aliases(((TypeMemPtr)trez)._aliases);
     return TypeMemPtr.OOP0.dual().isa(trez) ? BitsAlias.NZERO : BitsAlias.EMPTY;
   }
References com.cliffc.aa.type.TypeMem.all_reaching_aliases(), com.cliffc.aa.type.Type< T extends Type< T >.dual(), com.cliffc.aa.type.BitsAlias.EMPTY, com.cliffc.aa.type.Type< T extends Type< T >.NIL, com.cliffc.aa.type.BitsAlias.NZERO, com.cliffc.aa.type.TypeMemPtr.OOP0, and com.cliffc.aa.type.Type< T extends Type< T >.XNIL.
Referenced by com.cliffc.aa.node.CallNode._ideal_grow(), com.cliffc.aa.node.CallNode.escapees(), and com.cliffc.aa.node.CallEpiNode.value().
escapees()
BitsAlias com.cliffc.aa.node.CallEpiNode.escapees () package
Reimplemented from com.cliffc.aa.node.Node.
Definition at line 509 of file CallEpiNode.java.
 { return BitsAlias.FULL; }
References com.cliffc.aa.type.BitsAlias.FULL.
find() [1/2]
Node com.cliffc.aa.node.Node.find (int uid) inherited
Definition at line 427 of file Node.java.
 { return find(uid,new VBitSet()); }
References com.cliffc.aa.node.Node.find().
Referenced by com.cliffc.aa.node.FunNode.bad_mem_use(), and com.cliffc.aa.node.Node.find().
find() [2/2]
Node com.cliffc.aa.node.Node.find (int uid, VBitSet bs) private inherited
Definition at line 428 of file Node.java.
{
     if( _uid==uid ) return this;
     if( bs.tset(_uid) || is_dead() ) return null;
     Node m;
     for( Node n : _defs ) if( n!=null && (m=n.find(uid,bs)) !=null ) return m;
     for( Node n : _uses ) if(            (m=n.find(uid,bs)) !=null ) return m;
     return null;
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._uid, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node.find(), com.cliffc.aa.node.Node.is_dead(), and com.cliffc.aa.util.VBitSet.tset().
get_mem_writer()
Node com.cliffc.aa.node.Node.get_mem_writer () inherited
Definition at line 840 of file Node.java.
{
     for( Node use : _uses ) if( use.is_mem() ) return use;
     return null;
   }
References com.cliffc.aa.node.Node._uses.
Referenced by com.cliffc.aa.node.StoreNode.ideal_reduce().
hashCode()
int com.cliffc.aa.node.Node.hashCode () inherited
Reimplemented in com.cliffc.aa.node.CallNode, com.cliffc.aa.node.LoadNode, com.cliffc.aa.node.ScopeNode, com.cliffc.aa.node.StoreNode, com.cliffc.aa.node.PrimNode, com.cliffc.aa.node.NewNode< T extends TypeObj< T >, com.cliffc.aa.node.UnresolvedNode, com.cliffc.aa.node.ConTypeNode, com.cliffc.aa.node.FreshNode, com.cliffc.aa.node.ProjNode, com.cliffc.aa.node.RetNode, com.cliffc.aa.node.ConNode< T extends Type >, com.cliffc.aa.node.ErrNode, com.cliffc.aa.node.ParmNode, com.cliffc.aa.node.PhiNode, com.cliffc.aa.node.StartNode, com.cliffc.aa.node.CEProjNode, and com.cliffc.aa.node.StartMemNode.
Definition at line 105 of file Node.java.
{
     int sum = _op;
     for( int i=0; i<_defs._len; i++ ) if( _defs._es[i] != null ) sum ^= _defs._es[i]._uid;
     return sum;
   }
References com.cliffc.aa.node.Node._defs, and com.cliffc.aa.node.Node._op.
ideal_grow()
Node com.cliffc.aa.node.Node.ideal_grow () inherited
Reimplemented in com.cliffc.aa.node.PrimNode.OrElse, com.cliffc.aa.node.PrimNode.AndThen, com.cliffc.aa.node.CallNode, com.cliffc.aa.node.LoadNode, com.cliffc.aa.node.StoreNode, com.cliffc.aa.node.MrgProjNode, and com.cliffc.aa.node.AssertNode.
Definition at line 450 of file Node.java.
 { return null; }
Referenced by com.cliffc.aa.node.Node.do_grow().
ideal_mono()
Node com.cliffc.aa.node.Node.ideal_mono () inherited
Reimplemented in com.cliffc.aa.node.RetNode, com.cliffc.aa.node.StoreNode, com.cliffc.aa.node.MemJoinNode, com.cliffc.aa.node.LoadNode, com.cliffc.aa.node.MrgProjNode, and com.cliffc.aa.node.CastNode.
Definition at line 445 of file Node.java.
 { return null; }
Referenced by com.cliffc.aa.node.Node.do_mono().
ideal_reduce()
Node com.cliffc.aa.node.CallEpiNode.ideal_reduce ()
Reimplemented from com.cliffc.aa.node.Node.
Definition at line 40 of file CallEpiNode.java.
{
     if( _is_copy ) return null;
     CallNode call = call();
     Type tc = call._val;
     if( !(tc instanceof TypeTuple) ) return null;
     TypeTuple tcall = (TypeTuple)tc;
     if( CallNode.tctl(tcall) != Type.CTRL ) return null; // Call not executable
     // Get calls resolved function.
     BitsFun fidxs = CallNode.ttfp(tcall).fidxs();
     // If the call's allowed functions excludes any wired, remove the extras
     if( !fidxs.test(BitsFun.ALL) ) { // Shortcut
       for( int i = 0; i < nwired(); i++ ) {
         RetNode ret = wired(i);
         if( !fidxs.test_recur(ret.fidx()) ) { // Wired call not in execution set?
           assert !BitsFun.is_parent(ret.fidx());
           // Remove the edge.  Pre-GCP all CG edges are virtual, and are lazily
           // and pessimistically filled in by ideal calls.  During the course
           // of lifting types some of the manifested CG edges are killed.
           // Post-GCP all CG edges are manifest, but types can keep lifting
           // and so CG edges can still be killed.
           unwire(call,ret);
           return this; // Return with progress
         }
       }
     }
     // See if we can wire any new fidxs directly between Call/Fun and Ret/CallEpi.
     // This *adds* edges, but enables a lot of shrinking via inlining.
     if( check_and_wire() ) return this;
     // The one allowed function is already wired?  Then directly inline.
     // Requires this calls 1 target, and the 1 target is only called by this.
     if( nwired()==1 && fidxs.abit() != -1 ) { // Wired to 1 target
       RetNode ret = wired(0);                 // One wired return
       FunNode fun = ret.fun();
       Type tdef = Env.DEFMEM._uses._len==0 ? null : Env.DEFMEM._val;
       TypeTuple tret = ret._val instanceof TypeTuple ? (TypeTuple) ret._val : (TypeTuple)ret._val.oob(TypeTuple.RET);
       Type tretmem = tret.at(1);
       if( fun != null && fun._defs._len==2 && // Function is only called by 1 (and not the unknown caller)
           (call.err(true)==null || fun._thunk_rhs) &&       // And args are ok
           (tdef==null || CallNode.emem(tcall).isa(tdef)) && // Pre-GCP, call memory has to be as good as the default
           (tdef==null || tretmem.isa(tdef)) &&  // Call and return memory at least as good as default
           call.mem().in(0) != call &&   // Dead self-recursive
           fun.in(1)._uses._len==1 &&    // And only calling fun
           ret._live.isa(_live) &&       // Call and return liveness compatible
           !fun.noinline() ) {           // And not turned off
         assert fun.in(1).in(0)==call;   // Just called by us
         fun.set_is_copy();              // Collapse the FunNode into the Call
         return set_is_copy(ret.ctl(), ret.mem(), ret.rez()); // Collapse the CallEpi into the Ret
       }
     }
     // Parser thunks eagerly inline
     if( call.fdx() instanceof ThretNode ) {
       ThretNode tret = (ThretNode)call.fdx();
       wire1(call,tret.thunk(),tret);
       return set_is_copy(tret.ctrl(), tret.mem(), tret.rez()); // Collapse the CallEpi into the Thret
     }
     // Only inline wired single-target function with valid args.  CallNode wires.
     if( nwired()!=1 ) return null; // More than 1 wired, inline only via FunNode
     int fidx = fidxs.abit();       // Could be 1 or multi
     if( fidx == -1 ) return null;  // Multi choices, only 1 wired at the moment.
     if( fidxs.above_center() ) return null; // Can be unresolved yet
     if( BitsFun.is_parent(fidx) ) return null; // Parent, only 1 child wired
     if( call.err(true)!=null ) return null; // CallNode claims args in-error, do not inline
     // Call allows 1 function not yet inlined, sanity check it.
     int cnargs = call.nargs();
     FunNode fun = FunNode.find_fidx(fidx);
     assert !fun.is_forward_ref() && !fun.is_dead()
       && fun.nargs() == cnargs; // All checked by call.err
     if( fun._val != Type.CTRL ) return null;
     RetNode ret = fun.ret();    // Return from function
     if( ret==null ) return null;
     // Single choice; check no conversions needed.
     TypeTuple formals = fun._sig._formals;
     for( Node parm : fun._uses ) {
       if( parm instanceof ParmNode && parm.in(0)==fun ) {
         int idx = ((ParmNode)parm)._idx;
         if( idx < 0 ) continue; // RPC
         Type actual = CallNode.targ(tcall,idx);
         if( actual.isBitShape(formals.at(idx)) == 99 ) // Requires user-specified conversion
           return null;
       }
     }
     // Check for several trivial cases that can be fully inlined immediately.
     Node cctl = call.ctl();
     Node cmem = call.mem();
     Node rctl = ret.ctl();      // Control being returned
     Node rmem = ret.mem();      // Memory  being returned
     Node rrez = ret.rez();      // Result  being returned
     boolean inline = !fun.noinline();
     // If the function does nothing with memory, then use the call memory directly.
     if( (rmem instanceof ParmNode && rmem.in(CTL_IDX) == fun) || rmem._val ==TypeMem.XMEM )
       rmem = cmem;
     // Check that function return memory and post-call memory are compatible
     if( !(_val instanceof TypeTuple) ) return null;
     Type selfmem = ((TypeTuple) _val).at(MEM_IDX);
     if( !rmem._val.isa( selfmem ) && !(selfmem==TypeMem.ANYMEM && call.is_pure_call()!=null) )
       return null;
     // Check for zero-op body (id function)
     if( rrez instanceof ParmNode && rrez.in(CTL_IDX) == fun && cmem == rmem && inline )
       return unwire(call,ret).set_is_copy(cctl,cmem,call.arg(((ParmNode)rrez)._idx)); // Collapse the CallEpi
     // Check for constant body
     Type trez = rrez._val;
     if( trez.is_con() && rctl==fun && cmem == rmem && inline )
       return unwire(call,ret).set_is_copy(cctl,cmem,Node.con(trez));
     // Check for a 1-op body using only constants or parameters and no memory effects
     boolean can_inline=!(rrez instanceof ParmNode) && rmem==cmem && inline;
     for( Node parm : rrez._defs )
       if( parm != null && parm != fun &&
           !(parm instanceof ParmNode && parm.in(0) == fun) &&
           !(parm instanceof ConNode) )
         can_inline=false;       // Not trivial
     if( can_inline ) {
       Node irez = rrez.copy(false); // Copy the entire function body
       ProjNode proj = ProjNode.proj(this,REZ_IDX);
       irez._live = proj==null ? TypeMem.ESCAPE : proj._live;
       for( Node parm : rrez._defs )
         irez.add_def((parm instanceof ParmNode && parm.in(CTL_IDX) == fun) ? call.arg(((ParmNode)parm)._idx) : parm);
       if( irez instanceof PrimNode ) ((PrimNode)irez)._badargs = call._badargs;
       GVN.add_work_all(irez);
       return unwire(call,ret).set_is_copy(cctl,cmem,irez);
     }
     return null;
   }
References com.cliffc.aa.node.CallNode._badargs, com.cliffc.aa.node.Node._defs, com.cliffc.aa.type.TypeFunSig._formals, com.cliffc.aa.node.CallEpiNode._is_copy, com.cliffc.aa.node.Node._live, com.cliffc.aa.node.FunNode._sig, com.cliffc.aa.node.FunNode._thunk_rhs, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node._val, com.cliffc.aa.type.Bits< B extends Bits< B >.abit(), com.cliffc.aa.type.Bits< B extends Bits< B >.above_center(), com.cliffc.aa.node.Node.add_def(), com.cliffc.aa.type.BitsFun.ALL, com.cliffc.aa.type.TypeMem.ANYMEM, com.cliffc.aa.node.CallNode.arg(), com.cliffc.aa.type.TypeTuple.at(), com.cliffc.aa.node.CallEpiNode.call(), com.cliffc.aa.node.CallEpiNode.check_and_wire(), com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.Node.copy(), com.cliffc.aa.node.RetNode.ctl(), com.cliffc.aa.node.CallNode.ctl(), com.cliffc.aa.node.ThretNode.ctrl(), com.cliffc.aa.type.Type< T extends Type< T >.CTRL, com.cliffc.aa.Env.DEFMEM, com.cliffc.aa.node.CallNode.emem(), com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.type.TypeMem.ESCAPE, com.cliffc.aa.node.CallNode.fdx(), com.cliffc.aa.node.RetNode.fidx(), com.cliffc.aa.type.TypeFunPtr.fidxs(), com.cliffc.aa.node.FunNode.find_fidx(), com.cliffc.aa.node.RetNode.fun(), com.cliffc.aa.node.Node.in(), com.cliffc.aa.type.Type< T extends Type< T >.is_con(), com.cliffc.aa.node.Node.is_dead(), com.cliffc.aa.node.FunNode.is_forward_ref(), com.cliffc.aa.type.BitsFun.is_parent(), com.cliffc.aa.node.CallNode.is_pure_call(), com.cliffc.aa.type.Type< T extends Type< T >.isa(), com.cliffc.aa.type.Type< T extends Type< T >.isBitShape(), com.cliffc.aa.node.ThretNode.mem(), com.cliffc.aa.node.RetNode.mem(), com.cliffc.aa.node.CallNode.mem(), com.cliffc.aa.node.CallNode.nargs(), com.cliffc.aa.node.FunNode.nargs(), com.cliffc.aa.node.FunNode.noinline(), com.cliffc.aa.node.CallEpiNode.nwired(), com.cliffc.aa.type.Type< T extends Type< T >.oob(), com.cliffc.aa.node.ProjNode.proj(), com.cliffc.aa.type.TypeTuple.RET, com.cliffc.aa.node.FunNode.ret(), com.cliffc.aa.node.ThretNode.rez(), com.cliffc.aa.node.RetNode.rez(), com.cliffc.aa.node.CallEpiNode.set_is_copy(), com.cliffc.aa.node.FunNode.set_is_copy(), com.cliffc.aa.node.CallNode.targ(), com.cliffc.aa.node.CallNode.tctl(), com.cliffc.aa.type.Bits< B extends Bits< B >.test(), com.cliffc.aa.type.Bits< B extends Bits< B >.test_recur(), com.cliffc.aa.node.ThretNode.thunk(), com.cliffc.aa.node.CallNode.ttfp(), com.cliffc.aa.node.CallEpiNode.unwire(), com.cliffc.aa.node.CallEpiNode.wire1(), com.cliffc.aa.node.CallEpiNode.wired(), and com.cliffc.aa.type.TypeMem.XMEM.
in()
Node com.cliffc.aa.node.Node.in (int i) inherited
Definition at line 126 of file Node.java.
 { return _defs.at(i); }
References com.cliffc.aa.node.Node._defs.
Referenced by com.cliffc.aa.node.MemJoinNode.add_alias_above(), com.cliffc.aa.node.MemJoinNode.add_alias_below(), com.cliffc.aa.node.UnresolvedNode.add_def_unresolved(), com.cliffc.aa.node.CallNode.add_flow_def_extra(), com.cliffc.aa.node.MProjNode.add_flow_use_extra(), com.cliffc.aa.node.ParmNode.add_flow_use_extra(), com.cliffc.aa.node.LoadNode.add_flow_use_extra(), com.cliffc.aa.node.CallEpiNode.add_flow_use_extra(), com.cliffc.aa.node.MemPrimNode.adr(), com.cliffc.aa.node.LoadNode.adr(), com.cliffc.aa.node.StoreNode.adr(), com.cliffc.aa.node.AssertNode.arg(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun(), com.cliffc.aa.node.StoreNode.bad(), com.cliffc.aa.node.LoadNode.bad(), com.cliffc.aa.node.CallEpiNode.call(), com.cliffc.aa.node.MemJoinNode.can_bypass(), com.cliffc.aa.node.FunNode.check_callers(), com.cliffc.aa.node.MemSplitNode.check_split(), com.cliffc.aa.node.CastNode.checked(), com.cliffc.aa.node.MemJoinNode.combine_splits(), com.cliffc.aa.node.RetNode.ctl(), com.cliffc.aa.node.CallNode.ctl(), com.cliffc.aa.node.ThretNode.ctrl(), com.cliffc.aa.node.ScopeNode.ctrl(), com.cliffc.aa.node.FunPtrNode.display(), com.cliffc.aa.node.CallNode.dsp(), com.cliffc.aa.node.Node.dump(), com.cliffc.aa.node.Node.dumprpo(), com.cliffc.aa.node.ScopeNode.early_ctrl(), com.cliffc.aa.node.ScopeNode.early_mem(), com.cliffc.aa.node.ScopeNode.early_val(), com.cliffc.aa.node.ParmNode.err(), com.cliffc.aa.node.PhiNode.err(), com.cliffc.aa.node.MProjNode.escapees(), com.cliffc.aa.node.MrgProjNode.escapees(), com.cliffc.aa.node.IntrinsicNode.escapees(), com.cliffc.aa.node.FunNode.find_body(), com.cliffc.aa.node.LoadNode.find_previous_store(), com.cliffc.aa.node.MemJoinNode.find_sese_head(), com.cliffc.aa.node.NewNode< TypeStruct >.fld(), com.cliffc.aa.node.FP2DispNode.fptr2disp(), com.cliffc.aa.node.ParmNode.fun(), com.cliffc.aa.node.RetNode.fun(), com.cliffc.aa.node.FunNode.has_unknown_callers(), com.cliffc.aa.node.FreshNode.id(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.StoreNode.ideal_grow(), com.cliffc.aa.node.LoadNode.ideal_grow(), com.cliffc.aa.node.CallNode.ideal_grow(), com.cliffc.aa.node.PrimNode.AndThen.ideal_grow(), com.cliffc.aa.node.PrimNode.OrElse.ideal_grow(), com.cliffc.aa.node.FunNode.ideal_inline(), com.cliffc.aa.node.CastNode.ideal_mono(), com.cliffc.aa.node.LoadNode.ideal_mono(), com.cliffc.aa.node.MemJoinNode.ideal_mono(), com.cliffc.aa.node.FP2DispNode.ideal_reduce(), com.cliffc.aa.node.IfNode.ideal_reduce(), com.cliffc.aa.node.RegionNode.ideal_reduce(), com.cliffc.aa.node.FreshNode.ideal_reduce(), com.cliffc.aa.node.CastNode.ideal_reduce(), com.cliffc.aa.node.ProjNode.ideal_reduce(), com.cliffc.aa.node.ErrNode.ideal_reduce(), com.cliffc.aa.node.MemJoinNode.ideal_reduce(), com.cliffc.aa.node.UnresolvedNode.ideal_reduce(), com.cliffc.aa.node.PhiNode.ideal_reduce(), com.cliffc.aa.node.StoreNode.ideal_reduce(), com.cliffc.aa.node.ParmNode.ideal_reduce(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.IntrinsicNode.ideal_reduce(), com.cliffc.aa.node.RetNode.ideal_reduce(), com.cliffc.aa.node.ScopeNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.node.FunNode.ideal_reduce(), com.cliffc.aa.node.PrimNode.ConvertStrStr.ideal_reduce(), com.cliffc.aa.node.MemPrimNode.idx(), com.cliffc.aa.node.MemSplitNode.insert_split(), com.cliffc.aa.node.ThunkNode.is_copy(), com.cliffc.aa.node.IfNode.is_copy(), com.cliffc.aa.node.RegionNode.is_copy(), com.cliffc.aa.node.RetNode.is_copy(), com.cliffc.aa.node.CallEpiNode.is_copy(), com.cliffc.aa.node.PrimNode.AndThen.is_copy(), com.cliffc.aa.node.PrimNode.OrElse.is_copy(), com.cliffc.aa.node.CallNode.is_copy(), com.cliffc.aa.node.FunNode.is_copy(), com.cliffc.aa.node.FunPtrNode.is_pure_call(), com.cliffc.aa.node.CallEpiNode.is_pure_call(), com.cliffc.aa.node.CallNode.least_cost(), com.cliffc.aa.node.ThunkNode.live_use(), com.cliffc.aa.node.DefMemNode.live_use(), com.cliffc.aa.node.CastNode.live_use(), com.cliffc.aa.node.MrgProjNode.live_use(), com.cliffc.aa.node.PhiNode.live_use(), com.cliffc.aa.node.CallEpiNode.live_use(), com.cliffc.aa.node.PrimNode.AndThen.live_use(), com.cliffc.aa.node.PrimNode.OrElse.live_use(), com.cliffc.aa.node.MemPrimNode.mem(), com.cliffc.aa.node.MrgProjNode.mem(), com.cliffc.aa.node.ThretNode.mem(), com.cliffc.aa.node.MemSplitNode.mem(), com.cliffc.aa.node.LoadNode.mem(), com.cliffc.aa.node.IntrinsicNode.mem(), com.cliffc.aa.node.RetNode.mem(), com.cliffc.aa.node.AssertNode.mem(), com.cliffc.aa.node.StoreNode.mem(), com.cliffc.aa.node.ScopeNode.mem(), com.cliffc.aa.node.CallNode.mem(), com.cliffc.aa.node.MemJoinNode.MemJoinNode(), com.cliffc.aa.node.FunPtrNode.merge_ref_def(), com.cliffc.aa.node.MemJoinNode.msp(), com.cliffc.aa.node.MrgProjNode.nnn(), com.cliffc.aa.node.FunNode.noinline(), com.cliffc.aa.node.ProjNode.op_prec(), com.cliffc.aa.node.IntrinsicNode.ptr(), com.cliffc.aa.node.ScopeNode.ptr(), com.cliffc.aa.Parse.remove_unknown_callers(), com.cliffc.aa.node.FunPtrNode.ret(), com.cliffc.aa.GVNGCM.retype_mem(), com.cliffc.aa.node.MemPrimNode.rez(), com.cliffc.aa.node.ThretNode.rez(), com.cliffc.aa.node.RetNode.rez(), com.cliffc.aa.node.StoreNode.rez(), com.cliffc.aa.node.ScopeNode.rez(), com.cliffc.aa.node.RetNode.rpc(), com.cliffc.aa.node.CallEpiNode.sane_wiring(), com.cliffc.aa.node.Node.should_con(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.node.FunNode.split_size(), com.cliffc.aa.node.RegionNode.stacked_region(), com.cliffc.aa.node.ScopeNode.stk(), com.cliffc.aa.node.TestNode.stx(), com.cliffc.aa.node.CallNode.swap_new(), com.cliffc.aa.node.RetNode.tail_recursive(), com.cliffc.aa.Parse.term(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.node.TestNodeSmall.testUnresolvedAdd(), com.cliffc.aa.node.ThretNode.thunk(), com.cliffc.aa.node.Node.tvar(), com.cliffc.aa.node.ProjNode.unify(), com.cliffc.aa.node.FunNode.unwire(), com.cliffc.aa.node.CallEpiNode.unwire(), com.cliffc.aa.node.Node.val(), com.cliffc.aa.node.ParmNode.valid_args(), com.cliffc.aa.node.DefMemNode.value(), com.cliffc.aa.node.MProjNode.value(), com.cliffc.aa.node.CastNode.value(), com.cliffc.aa.node.IfNode.value(), com.cliffc.aa.node.PhiNode.value(), com.cliffc.aa.node.ParmNode.value(), com.cliffc.aa.node.MrgProjNode.value(), com.cliffc.aa.node.RegionNode.value(), com.cliffc.aa.node.FunPtrNode.value(), com.cliffc.aa.node.PrimNode.EQ_OOP.value(), com.cliffc.aa.node.PrimNode.NE_OOP.value(), com.cliffc.aa.node.FunNode.value(), com.cliffc.aa.node.LoopNode.walk_dom_last(), com.cliffc.aa.node.ThunkNode.walk_dom_last(), com.cliffc.aa.node.RegionNode.walk_dom_last(), com.cliffc.aa.node.Node.walk_dom_last(), com.cliffc.aa.node.CallEpiNode.wire0(), com.cliffc.aa.node.CallEpiNode.wired(), com.cliffc.aa.node.FunPtrNode.xfun(), com.cliffc.aa.node.CProjNode.xstr(), and com.cliffc.aa.node.UnresolvedNode.xstr().
init0()
static void com.cliffc.aa.node.Node.init0 () static inherited
Definition at line 70 of file Node.java.
{
     assert LIVE.get(CNT-1) && !LIVE.get(CNT);
     _INIT0_CNT=CNT;
   }
References com.cliffc.aa.node.Node._INIT0_CNT, com.cliffc.aa.node.Node.CNT, and com.cliffc.aa.node.Node.LIVE.
Referenced by com.cliffc.aa.Env.record_for_top_reset2().
init1()
Node com.cliffc.aa.node.Node.init1 () inherited
Definition at line 708 of file Node.java.
{
     Node x = VALS.get(this);
     if( Env.GVN._opt_mode == GVNGCM.Mode.Opto ) _live = TypeMem.DEAD;
     if( x!=null ) {             // Hit in GVN table
       merge(x);
       kill();                                 // Kill just-init'd
       return x;                               // Return old
     }
     _elock();
     _val = value(Env.GVN._opt_mode);
     return Env.GVN.add_work_all(this);
   }
References com.cliffc.aa.node.Node._elock, com.cliffc.aa.node.Node._live, com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.node.Node._val, com.cliffc.aa.GVNGCM.add_work_all(), com.cliffc.aa.type.TypeMem.DEAD, com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.kill(), com.cliffc.aa.node.Node.merge(), com.cliffc.aa.GVNGCM.Mode.Opto, com.cliffc.aa.node.Node.VALS, and com.cliffc.aa.node.Node.value().
Referenced by com.cliffc.aa.node.CallEpiNode.wire0().
insert() [1/2]
Node com.cliffc.aa.node.Node.insert (int idx, Node n) inherited
Definition at line 165 of file Node.java.
 { unelock(); _defs.insert(idx,n); if( n!=null ) n._uses.add(this); return this; }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._uses, and com.cliffc.aa.node.Node.unelock().
Referenced by com.cliffc.aa.node.MemJoinNode.add_alias_above(), com.cliffc.aa.node.MemJoinNode.add_alias_below(), com.cliffc.aa.Parse.remove_unknown_callers(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.node.Node.subsume(), com.cliffc.aa.node.CallNode.swap_new(), and com.cliffc.aa.node.RetNode.tail_recursive().
insert() [2/2]
void com.cliffc.aa.node.Node.insert (Node nnn) inherited
Definition at line 191 of file Node.java.
{
     if( _uses._len>0 ) unelock(); // Hacking edges
     while( _uses._len > 0 ) {
       Node u = _uses.del(0);  // Old use
       u.replace(this,nnn);    // was this now nnn
       nnn._uses.add(u);
     }
   }
References com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node.replace(), and com.cliffc.aa.node.Node.unelock().
is_CFG()
boolean com.cliffc.aa.node.Node.is_CFG () package inherited
Definition at line 356 of file Node.java.
 { return _op==OP_CALL || _op==OP_CALLEPI || _op==OP_FUN || _op==OP_RET || _op==OP_IF || _op==OP_LOOP || _op==OP_REGION || _op==OP_START || _op==OP_CPROJ || _op==OP_SCOPE; }
References com.cliffc.aa.node.Node._op, com.cliffc.aa.node.Node.OP_CALL, com.cliffc.aa.node.Node.OP_CALLEPI, com.cliffc.aa.node.Node.OP_CPROJ, com.cliffc.aa.node.Node.OP_FUN, com.cliffc.aa.node.Node.OP_IF, com.cliffc.aa.node.Node.OP_LOOP, com.cliffc.aa.node.Node.OP_REGION, com.cliffc.aa.node.Node.OP_RET, com.cliffc.aa.node.Node.OP_SCOPE, and com.cliffc.aa.node.Node.OP_START.
Referenced by com.cliffc.aa.node.RegionNode.add_flow_def_extra(), com.cliffc.aa.node.Node.do_flow(), com.cliffc.aa.node.Node.postorder(), com.cliffc.aa.node.RegionNode.stacked_region(), and com.cliffc.aa.node.RetNode.tail_recursive().
is_copy()
Node com.cliffc.aa.node.CallEpiNode.is_copy (int idx)
Reimplemented from com.cliffc.aa.node.Node.
Definition at line 394 of file CallEpiNode.java.
 { return _is_copy ? in(idx) : null; }
References com.cliffc.aa.node.CallEpiNode._is_copy, and com.cliffc.aa.node.Node.in().
is_dead()
boolean com.cliffc.aa.node.Node.is_dead () inherited
Definition at line 820 of file Node.java.
 { return _uses == null; }
References com.cliffc.aa.node.Node._uses.
Referenced by com.cliffc.aa.Parse._short_circuit_expr(), com.cliffc.aa.tvar.UQNodes.add(), com.cliffc.aa.GVNGCM.add_work_all(), com.cliffc.aa.node.CallEpiNode.check_and_wire(), com.cliffc.aa.Env.close(), com.cliffc.aa.node.Node.do_grow(), com.cliffc.aa.node.Node.dump(), com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.node.Node.find(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.RetNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.node.MemSplitNode.insert_split(), com.cliffc.aa.GVNGCM.iter(), com.cliffc.aa.node.Node.kill(), com.cliffc.aa.node.NewNode< TypeStruct >.kill2(), com.cliffc.aa.tvar.UQNodes.make(), com.cliffc.aa.node.FunNode.names(), com.cliffc.aa.node.FunNode.ret(), com.cliffc.aa.node.FunPtrNode.str(), com.cliffc.aa.node.Node.subsume(), com.cliffc.aa.node.Node.walk_opt(), com.cliffc.aa.GVNGCM.xform(), com.cliffc.aa.node.CProjNode.xstr(), com.cliffc.aa.node.UnresolvedNode.xstr(), com.cliffc.aa.node.CallEpiNode.xstr(), com.cliffc.aa.node.RetNode.xstr(), com.cliffc.aa.node.FunPtrNode.xstr(), and com.cliffc.aa.node.CallNode.xstr().
is_forward_ref()
boolean com.cliffc.aa.node.Node.is_forward_ref () inherited
Reimplemented in com.cliffc.aa.node.FunNode, com.cliffc.aa.node.FunPtrNode, com.cliffc.aa.node.RetNode, and com.cliffc.aa.node.ConTypeNode.
Definition at line 830 of file Node.java.
 { return false; }
Referenced by com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.node.StoreNode.ideal_reduce(), com.cliffc.aa.Parse.inc(), com.cliffc.aa.node.NewObjNode.promote_forward(), com.cliffc.aa.Parse.stmt(), and com.cliffc.aa.node.Node.walkerr_def().
is_mem()
boolean com.cliffc.aa.node.CallEpiNode.is_mem ()
Reimplemented from com.cliffc.aa.node.Node.
Definition at line 36 of file CallEpiNode.java.
 { return true; }
is_multi_head()
boolean com.cliffc.aa.node.Node.is_multi_head () inherited
Definition at line 354 of file Node.java.
 { return _op==OP_CALL || _op==OP_CALLEPI || _op==OP_FUN || _op==OP_IF || _op==OP_LOOP || _op==OP_NEWOBJ || _op==OP_NEWSTR || _op==OP_REGION || _op==OP_SPLIT || _op==OP_START; }
References com.cliffc.aa.node.Node._op, com.cliffc.aa.node.Node.OP_CALL, com.cliffc.aa.node.Node.OP_CALLEPI, com.cliffc.aa.node.Node.OP_FUN, com.cliffc.aa.node.Node.OP_IF, com.cliffc.aa.node.Node.OP_LOOP, com.cliffc.aa.node.Node.OP_NEWOBJ, com.cliffc.aa.node.Node.OP_NEWSTR, com.cliffc.aa.node.Node.OP_REGION, com.cliffc.aa.node.Node.OP_SPLIT, and com.cliffc.aa.node.Node.OP_START.
Referenced by com.cliffc.aa.node.Node.dump(), com.cliffc.aa.node.Node.dumprpo(), com.cliffc.aa.node.FunNode.find_body(), and com.cliffc.aa.node.Node.postorder().
is_multi_tail()
boolean com.cliffc.aa.node.Node.is_multi_tail () private inherited
Definition at line 355 of file Node.java.
 { return _op==OP_PARM || _op==OP_PHI || _op==OP_PROJ || _op==OP_CPROJ; }
References com.cliffc.aa.node.Node._op, com.cliffc.aa.node.Node.OP_CPROJ, com.cliffc.aa.node.Node.OP_PARM, com.cliffc.aa.node.Node.OP_PHI, and com.cliffc.aa.node.Node.OP_PROJ.
Referenced by com.cliffc.aa.node.Node.dump(), com.cliffc.aa.node.Node.dumprpo(), and com.cliffc.aa.node.Node.postorder().
is_prim()
boolean com.cliffc.aa.node.Node.is_prim () inherited
Definition at line 260 of file Node.java.
 { return _INIT0_CNT==0 || _uid<_INIT0_CNT; }
References com.cliffc.aa.node.Node._INIT0_CNT, and com.cliffc.aa.node.Node._uid.
Referenced by com.cliffc.aa.node.FunNode.check_callers(), com.cliffc.aa.node.Node.check_solo_mem_writer(), com.cliffc.aa.node.Node.dump(), com.cliffc.aa.node.Node.dumprpo(), com.cliffc.aa.node.MrgProjNode.ideal_grow(), com.cliffc.aa.node.FunNode.ideal_inline(), com.cliffc.aa.node.MemJoinNode.ideal_mono(), com.cliffc.aa.node.RegionNode.ideal_reduce(), com.cliffc.aa.node.MrgProjNode.ideal_reduce(), com.cliffc.aa.node.RetNode.ideal_reduce(), com.cliffc.aa.node.FunNode.ideal_reduce(), com.cliffc.aa.node.Node.live_uses(), com.cliffc.aa.Parse.remove_unknown_callers(), com.cliffc.aa.node.Node.should_con(), and com.cliffc.aa.node.Node.walkerr_def().
is_pure_call()
Node com.cliffc.aa.node.CallEpiNode.is_pure_call () package
Reimplemented from com.cliffc.aa.node.Node.
Definition at line 503 of file CallEpiNode.java.
 { return in(0) instanceof CallNode ? call().is_pure_call() : null; }
References com.cliffc.aa.node.CallEpiNode.call(), com.cliffc.aa.node.Node.in(), and com.cliffc.aa.node.CallNode.is_pure_call().
keep() [1/2]
public<N extends Node> N com.cliffc.aa.node.Node.keep () package inherited
Definition at line 228 of file Node.java.
 { return keep(1); }
References com.cliffc.aa.node.Node.keep().
Referenced by com.cliffc.aa.Parse._expr(), com.cliffc.aa.Parse._expr_higher(), com.cliffc.aa.Parse._short_circuit_expr(), com.cliffc.aa.GVNGCM.Build< N extends Node >.add(), com.cliffc.aa.node.MemJoinNode.add_alias_above(), com.cliffc.aa.node.MemJoinNode.add_alias_below_new(), com.cliffc.aa.Parse.apply(), com.cliffc.aa.node.ScopeNode.IfScope.check(), com.cliffc.aa.Parse.do_call0(), com.cliffc.aa.Parse.do_exit(), com.cliffc.aa.node.UnresolvedNode.filter(), com.cliffc.aa.node.FunNode.FunNode(), com.cliffc.aa.Parse.go(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.Parse.ifex(), com.cliffc.aa.Parse.inc(), com.cliffc.aa.Env.init(), com.cliffc.aa.GVNGCM.Build< N extends Node >.init(), com.cliffc.aa.GVNGCM.iter(), com.cliffc.aa.node.Node.keep(), com.cliffc.aa.Parse.merge_exits(), com.cliffc.aa.node.ScopeNode.ScopeNode(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.Parse.stmt(), com.cliffc.aa.Parse.stmts(), com.cliffc.aa.Parse.struct(), com.cliffc.aa.node.Node.subsume(), com.cliffc.aa.node.CallNode.swap_new(), com.cliffc.aa.Parse.term(), com.cliffc.aa.TestLive.testNewObj(), com.cliffc.aa.Env.top_scope(), and com.cliffc.aa.Parse.tuple().
keep() [2/2]
public<N extends Node> N com.cliffc.aa.node.Node.keep (int d) package inherited
Definition at line 230 of file Node.java.
 { _keep+=d;  return (N)this; }
References com.cliffc.aa.node.Node._keep.
kill()
Node com.cliffc.aa.node.Node.kill () inherited
Definition at line 211 of file Node.java.
                       {
     if( is_dead() ) return null;
     assert _uses._len==0 && _keep==0;
     // Similar to unelock(), except do not put on any worklist
     if( _elock ) { _elock = false; Node x = VALS.remove(this); assert x == this; }
     while( _defs._len > 0 ) unuse(_defs.pop());
     set_dead();                 // officially dead now
     LIVE.clear(_uid);           // Off the LIVE set.  CNT cannot roll back unless the GVN worklists are also clear
     return this;
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._elock, com.cliffc.aa.node.Node._keep, com.cliffc.aa.node.Node._uid, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node.is_dead(), com.cliffc.aa.node.Node.LIVE, com.cliffc.aa.node.Node.set_dead(), com.cliffc.aa.node.Node.unuse(), and com.cliffc.aa.node.Node.VALS.
Referenced by com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.Node.init1(), com.cliffc.aa.Parse.kill(), com.cliffc.aa.node.Node.subsume(), and com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve().
len()
int com.cliffc.aa.node.Node.len () inherited
Definition at line 125 of file Node.java.
 { return _defs._len; }
References com.cliffc.aa.node.Node._defs.
Referenced by com.cliffc.aa.node.MemPrimNode.err(), com.cliffc.aa.node.CallNode.ideal_reduce(), and com.cliffc.aa.node.CallEpiNode.value().
live()
TypeMem com.cliffc.aa.node.Node.live (GVNGCM.Mode opt_mode) inherited
Reimplemented in com.cliffc.aa.node.CallNode, com.cliffc.aa.node.RetNode, com.cliffc.aa.node.MemJoinNode, com.cliffc.aa.node.ScopeNode, com.cliffc.aa.node.FunPtrNode, com.cliffc.aa.node.ConNode< T extends Type >, com.cliffc.aa.node.ThretNode, and com.cliffc.aa.node.StartNode.
Definition at line 478 of file Node.java.
{
     if( _keep>0 ) return all_live();
     // Compute meet/union of all use livenesses
     TypeMem live = TypeMem.DEAD; // Start at lattice top
     for( Node use : _uses )      // Computed across all uses
       if( use.live_uses() ) {
         TypeMem ulive = use.live_use(opt_mode, this);
         live = (TypeMem)live.meet(ulive); // Make alive used fields
       }
     assert live==TypeMem.DEAD || live.basic_live()==all_live().basic_live();
     assert live!=TypeMem.LIVE_BOT || (_val !=Type.CTRL && _val !=Type.XCTRL);
     return live;
   }
References com.cliffc.aa.node.Node._keep, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node._val, com.cliffc.aa.node.Node.all_live(), com.cliffc.aa.type.TypeMem.basic_live(), com.cliffc.aa.type.Type< T extends Type< T >.CTRL, com.cliffc.aa.type.TypeMem.DEAD, com.cliffc.aa.type.TypeMem.LIVE_BOT, com.cliffc.aa.type.Type< T extends Type< T >.meet(), and com.cliffc.aa.type.Type< T extends Type< T >.XCTRL.
Referenced by com.cliffc.aa.node.Node.do_flow(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.node.PhiNode.ideal_reduce(), com.cliffc.aa.node.MemPrimNode.LValueLength.live_use(), com.cliffc.aa.node.LoadNode.live_use(), com.cliffc.aa.node.Node.more_flow(), com.cliffc.aa.node.Node.more_ideal(), com.cliffc.aa.GVNGCM.revalive(), and com.cliffc.aa.node.Node.xliv().
live_use()
TypeMem com.cliffc.aa.node.CallEpiNode.live_use (GVNGCM.Mode opt_mode, Node def)
Reimplemented from com.cliffc.aa.node.Node.
Definition at line 440 of file CallEpiNode.java.
{
     assert _keep==0 || _live==all_live();
     if( _is_copy ) return def._live; // A copy
     // Not a copy
     if( def==in(0) ) return _live; // The Call
     if( def==in(1) ) return opt_mode._CG ? TypeMem.DEAD : _live; // The DefMem
     // Wired return.
     // The given function is alive, only if the Call will Call it.
     Type tcall = call()._val;
     if( !(tcall instanceof TypeTuple) ) return tcall.above_center() ? TypeMem.DEAD : _live;
     BitsFun fidxs = CallNode.ttfp(tcall).fidxs();
     int fidx = ((RetNode)def).fidx();
     if( fidxs.above_center() || !fidxs.test_recur(fidx) )
       return TypeMem.DEAD;    // Call does not call this, so not alive.
     return _live;
   }
References com.cliffc.aa.node.CallEpiNode._is_copy, com.cliffc.aa.node.Node._keep, com.cliffc.aa.node.Node._live, com.cliffc.aa.node.Node._val, com.cliffc.aa.type.Bits< B extends Bits< B >.above_center(), com.cliffc.aa.type.Type< T extends Type< T >.above_center(), com.cliffc.aa.node.CallEpiNode.all_live(), com.cliffc.aa.node.CallEpiNode.call(), com.cliffc.aa.type.TypeMem.DEAD, com.cliffc.aa.type.TypeFunPtr.fidxs(), com.cliffc.aa.node.Node.in(), com.cliffc.aa.type.Bits< B extends Bits< B >.test_recur(), and com.cliffc.aa.node.CallNode.ttfp().
live_uses()
boolean com.cliffc.aa.node.Node.live_uses () inherited
Definition at line 491 of file Node.java.
{
     return _live != TypeMem.DEAD &&    // Only live uses make more live
       // And no chance use turns into a constant (which then does not use anything)
       !(_live.basic_live() && _val.may_be_con() && !is_prim() && err(true)==null &&
         // FunPtrs still use their Rets, even if constant
         !(this instanceof FunPtrNode));
   }
References com.cliffc.aa.node.Node._live, com.cliffc.aa.node.Node._val, com.cliffc.aa.type.TypeMem.basic_live(), com.cliffc.aa.type.TypeMem.DEAD, com.cliffc.aa.node.Node.err(), com.cliffc.aa.node.Node.is_prim(), and com.cliffc.aa.type.Type< T extends Type< T >.may_be_con().
merge()
Node com.cliffc.aa.node.Node.merge (Node x) private inherited
Definition at line 702 of file Node.java.
{
     x._live = (TypeMem)x._live.meet(_live);
     return Env.GVN.add_flow(x);
   }
References com.cliffc.aa.node.Node._live, com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.Env.GVN, and com.cliffc.aa.type.Type< T extends Type< T >.meet().
Referenced by com.cliffc.aa.node.Node._do_reduce(), and com.cliffc.aa.node.Node.init1().
more_flow() [1/2]
final int com.cliffc.aa.node.Node.more_flow (boolean lifting) inherited
Definition at line 747 of file Node.java.
 { FLOW_VISIT.clear();  return more_flow(lifting,0);  }
References com.cliffc.aa.node.Node.FLOW_VISIT, and com.cliffc.aa.node.Node.more_flow().
Referenced by com.cliffc.aa.GVNGCM.check_and_wire(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.node.Node.more_flow(), and com.cliffc.aa.GVNGCM.remove_ambi().
more_flow() [2/2]
int com.cliffc.aa.node.Node.more_flow (boolean lifting, int errs) private inherited
Definition at line 748 of file Node.java.
{
     if( FLOW_VISIT.tset(_uid) ) return errs; // Been there, done that
     if( Env.GVN.on_dead(this) ) return errs; // Do not check dying nodes
     // Check for only forwards flow, and if possible then also on worklist
     Type    oval= _val, nval = value(Env.GVN._opt_mode);
     TypeMem oliv=_live, nliv = live (Env.GVN._opt_mode);
     boolean hm = false;
     if( nval != oval || nliv != oliv || hm ) {
       boolean ok = lifting
         ? nval.isa(oval) && nliv.isa(oliv)
         : oval.isa(nval) && oliv.isa(nliv);
       if( !ok || (!Env.GVN.on_flow(this) && !Env.GVN.on_dead(this) && _keep==0) ) { // Still-to-be-computed?
         FLOW_VISIT.clear(_uid); // Pop-frame & re-run in debugger
         System.err.println(dump(0,new SB(),true)); // Rolling backwards not allowed
         errs++;
       }
     }
     for( Node def : _defs ) if( def != null ) errs = def.more_flow(lifting,errs);
     for( Node use : _uses ) if( use != null ) errs = use.more_flow(lifting,errs);
     return errs;
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._keep, com.cliffc.aa.node.Node._live, com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.node.Node._uid, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node._val, com.cliffc.aa.node.Node.dump(), com.cliffc.aa.node.Node.FLOW_VISIT, com.cliffc.aa.Env.GVN, com.cliffc.aa.type.Type< T extends Type< T >.isa(), com.cliffc.aa.node.Node.live(), com.cliffc.aa.GVNGCM.on_dead(), com.cliffc.aa.GVNGCM.on_flow(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.node.Node.value().
more_ideal()
final boolean com.cliffc.aa.node.Node.more_ideal (VBitSet bs) inherited
Definition at line 722 of file Node.java.
{
     if( bs.tset(_uid) ) return false; // Been there, done that
     if( _keep == 0 && _live.is_live() ) { // Only non-keeps, which is just top-level scope and prims
       Type t = value(Env.GVN._opt_mode);
       if( _val != t )
         return true;            // Found a value improvement
       TypeMem live = live(Env.GVN._opt_mode);
       if( _live != live )
         return true;            // Found a liveness improvement
       Node x;
       x = do_reduce(); if( x != null )
                          return true; // Found an ideal call
       x = do_mono(); if( x != null )
                        return true; // Found an ideal call
       x = do_grow(); if( x != null )
                        return true; // Found an ideal call
       if( this instanceof FunNode ) ((FunNode)this).ideal_inline(true);
     }
     for( Node def : _defs ) if( def != null && def.more_ideal(bs) ) return true;
     for( Node use : _uses ) if( use != null && use.more_ideal(bs) ) return true;
     return false;
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._keep, com.cliffc.aa.node.Node._live, com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.node.Node._uid, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node._val, com.cliffc.aa.node.Node.do_grow(), com.cliffc.aa.node.Node.do_mono(), com.cliffc.aa.node.Node.do_reduce(), com.cliffc.aa.Env.GVN, com.cliffc.aa.type.TypeMem.is_live(), com.cliffc.aa.node.Node.live(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.node.Node.value().
Referenced by com.cliffc.aa.GVNGCM.iter().
new_tvar()
TV2 com.cliffc.aa.node.Node.new_tvar (String alloc_site) inherited
Definition at line 101 of file Node.java.
 { return TV2.make_leaf(this,alloc_site); }
References com.cliffc.aa.tvar.TV2.make_leaf().
Referenced by com.cliffc.aa.node.Node.copy(), and com.cliffc.aa.node.Node.Node().
newuid()
int com.cliffc.aa.node.Node.newuid () package inherited
Definition at line 61 of file Node.java.
                {
     assert CNT < 100000 : "infinite node create loop";
     if( CNT==AA.UID )
       System.out.print("");
     LIVE.set(CNT);
     return CNT++;
   }
References com.cliffc.aa.node.Node.CNT, com.cliffc.aa.node.Node.LIVE, and com.cliffc.aa.AA.UID.
Referenced by com.cliffc.aa.node.Node.copy(), and com.cliffc.aa.node.Node.Node().
nwired()
int com.cliffc.aa.node.CallEpiNode.nwired ()
Definition at line 37 of file CallEpiNode.java.
 { return _defs._len-2; }
References com.cliffc.aa.node.Node._defs.
Referenced by com.cliffc.aa.node.CallEpiNode.add_flow_use_extra(), com.cliffc.aa.node.CallNode.all_fcns_wired(), com.cliffc.aa.Parse.do_call0(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.CallNode.live(), com.cliffc.aa.node.CallEpiNode.sane_wiring(), com.cliffc.aa.node.FunNode.split_callers(), and com.cliffc.aa.node.CallEpiNode.value().
op_prec()
byte com.cliffc.aa.node.Node.op_prec () inherited
Reimplemented in com.cliffc.aa.node.MemPrimNode.LValueWriteFinal, com.cliffc.aa.node.MemPrimNode.LValueWrite, com.cliffc.aa.node.FunPtrNode, com.cliffc.aa.node.MemPrimNode.LValueRead, com.cliffc.aa.node.UnresolvedNode, com.cliffc.aa.node.ProjNode, com.cliffc.aa.node.FreshNode, and com.cliffc.aa.node.CProjNode.
Definition at line 533 of file Node.java.
 { return -1; }
Referenced by com.cliffc.aa.Parse.bal_open(), com.cliffc.aa.Parse.fact(), com.cliffc.aa.node.FunNode.FunNode(), com.cliffc.aa.Env.lookup_filter_fresh(), com.cliffc.aa.node.FunNode.name(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.NewPrimNode(), com.cliffc.aa.node.FreshNode.op_prec(), com.cliffc.aa.node.ProjNode.op_prec(), and com.cliffc.aa.Parse.term().
pop()
Node com.cliffc.aa.node.Node.pop () inherited
Definition at line 174 of file Node.java.
 { unelock(); Node n = _defs.pop(); unuse(n); return n; }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node.unelock(), and com.cliffc.aa.node.Node.unuse().
Referenced by com.cliffc.aa.node.ScopeNode.early_kill(), com.cliffc.aa.node.PrimNode.AndThen.ideal_grow(), com.cliffc.aa.node.PrimNode.OrElse.ideal_grow(), com.cliffc.aa.node.UnresolvedNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.node.NewNode< TypeStruct >.kill2(), com.cliffc.aa.node.FunNode.make_new_fun(), com.cliffc.aa.node.CallEpiNode.set_is_copy(), and com.cliffc.aa.node.FunNode.split_callers().
postorder()
void com.cliffc.aa.node.Node.postorder (Ary< Node > nodes, VBitSet bs) private inherited
Definition at line 383 of file Node.java.
{
     if( bs.tset(_uid) ) return;
     // If CFG, walk the CFG first.  Do not walk thru Returns (into Calls) as
     // this breaks up the whole- functions-at-once.
     if( is_CFG() && _op!=OP_RET ) {
       // Walk any CProj first.
       for( Node use : _uses )
         if( use._op == OP_CPROJ )
           use.postorder(nodes,bs);
       // Walk the CFG, walking CallEpis last
       for( Node use : _uses )
         if( !(use instanceof CallEpiNode) && use.is_CFG() )
           use.postorder(nodes,bs);
       for( Node use : _uses )
         if(  (use instanceof CallEpiNode) && use.is_CFG() )
           use.postorder(nodes,bs);
     }
     // Walk the rest (especially data).  Since visit bits are set on the CFGs
     // its OK to walk them also.  Calls are special, since their Proj's feed
     // into a Fun's Parms.  We want the Fun to walk its own Parms, in order so
     // ignore these edges.  Since the Parms are all reachable from the Fun they
     // get walked eventually.
     if( _op != OP_CALL && _op!=OP_RET ) {
       if( _op!=OP_SPLIT || _uses._len!=2 )
         for( Node use : _uses )
           use.postorder(nodes,bs);
       else {                    // For MemSplit, walk the "busy" side first
         Node p0 = _uses.at(0), p1 = _uses.at(1);
         if( ((ProjNode)p0)._idx==1 ) { p0=p1; p1=_uses.at(0); } // Swap
         p1.postorder(nodes,bs);
         p0.postorder(nodes,bs);
       }
     }
     // Slight PO tweak: heads and tails together.
     if( is_multi_head() )
       for( Node use : _uses )
         if( use.is_multi_tail() )
           nodes.push(use);
     if( !is_multi_tail() ) nodes.push(this);
   }
References com.cliffc.aa.node.Node._op, com.cliffc.aa.node.Node._uid, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node.is_CFG(), com.cliffc.aa.node.Node.is_multi_head(), com.cliffc.aa.node.Node.is_multi_tail(), com.cliffc.aa.node.Node.OP_CALL, com.cliffc.aa.node.Node.OP_CPROJ, com.cliffc.aa.node.Node.OP_RET, com.cliffc.aa.node.Node.OP_SPLIT, com.cliffc.aa.node.Node.postorder(), com.cliffc.aa.util.Ary< E >.push(), and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.node.Node.dumprpo(), and com.cliffc.aa.node.Node.postorder().
remove()
Node com.cliffc.aa.node.Node.remove (int idx) inherited
Definition at line 176 of file Node.java.
 { unelock(); return unuse(_defs.remove(idx)); }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node.unelock(), and com.cliffc.aa.node.Node.unuse().
Referenced by com.cliffc.aa.node.RegionNode.stacked_region().
replace()
void com.cliffc.aa.node.Node.replace (Node old, Node nnn) inherited
Definition at line 163 of file Node.java.
 { unelock(); _defs.replace(old,nnn); }
References com.cliffc.aa.node.Node._defs, and com.cliffc.aa.node.Node.unelock().
Referenced by com.cliffc.aa.node.Node.insert().
reset_to_init0()
static void com.cliffc.aa.node.Node.reset_to_init0 () static inherited
Definition at line 77 of file Node.java.
{
     CNT = 0;
     LIVE.clear();
     VALS.clear();
   }
References com.cliffc.aa.node.Node.CNT, com.cliffc.aa.node.Node.LIVE, and com.cliffc.aa.node.Node.VALS.
Referenced by com.cliffc.aa.Env.top_reset().
roll_back_CNT()
static void com.cliffc.aa.node.Node.roll_back_CNT () static inherited
Definition at line 222 of file Node.java.
 { while( !LIVE.get(CNT-1) ) CNT--; }
References com.cliffc.aa.node.Node.CNT, and com.cliffc.aa.node.Node.LIVE.
Referenced by com.cliffc.aa.GVNGCM.iter().
sane_wiring()
boolean com.cliffc.aa.node.CallEpiNode.sane_wiring () package
Definition at line 379 of file CallEpiNode.java.
{
     CallNode call = call();
     for( int i=0; i<nwired(); i++ ) {
       RetNode ret = wired(i);
       if( ret.is_copy() ) return true; // Abort check, will be misaligned until dead path removed
       FunNode fun = ret.fun();
       boolean found=false;
       for( Node def : fun._defs )
         if( def instanceof CEProjNode && def.in(0)==call )
           { found=true; break; }
       if( !found ) return false;
     }
     return true;
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.CallEpiNode.call(), com.cliffc.aa.node.RetNode.fun(), com.cliffc.aa.node.Node.in(), com.cliffc.aa.node.RetNode.is_copy(), com.cliffc.aa.node.CallEpiNode.nwired(), and com.cliffc.aa.node.CallEpiNode.wired().
Referenced by com.cliffc.aa.node.CallEpiNode.unwire().
set_dead()
void com.cliffc.aa.node.Node.set_dead () inherited
Definition at line 821 of file Node.java.
 { _defs = _uses = null; }   // TODO: Poor-mans indication of a dead node, probably needs to recycle these...
References com.cliffc.aa.node.Node._defs, and com.cliffc.aa.node.Node._uses.
Referenced by com.cliffc.aa.node.Node.kill().
set_def()
Node com.cliffc.aa.node.Node.set_def (int idx, Node n) inherited
Definition at line 154 of file Node.java.
{
     unelock();
     Node old = _defs.at(idx);  // Get old value
     // Add edge to new guy before deleting old, in case old goes dead and
     // recursively makes new guy go dead also
     if( (_defs._es[idx] = n) != null ) n._uses.add(this);
     return unuse(old);
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node.unelock(), and com.cliffc.aa.node.Node.unuse().
Referenced by com.cliffc.aa.node.CallNode._ideal_grow(), com.cliffc.aa.node.MemJoinNode.add_alias_above(), com.cliffc.aa.node.MemJoinNode.add_alias_below(), com.cliffc.aa.node.MemJoinNode.combine_splits(), com.cliffc.aa.Parse.do_exit(), com.cliffc.aa.node.PrimNode.AndThen.ideal_grow(), com.cliffc.aa.node.PrimNode.OrElse.ideal_grow(), com.cliffc.aa.node.CastNode.ideal_mono(), com.cliffc.aa.node.FP2DispNode.ideal_reduce(), com.cliffc.aa.node.IfNode.ideal_reduce(), com.cliffc.aa.node.RegionNode.ideal_reduce(), com.cliffc.aa.node.FreshNode.ideal_reduce(), com.cliffc.aa.node.CastNode.ideal_reduce(), com.cliffc.aa.node.ErrNode.ideal_reduce(), com.cliffc.aa.node.UnresolvedNode.ideal_reduce(), com.cliffc.aa.node.RetNode.ideal_reduce(), com.cliffc.aa.node.FunPtrNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.node.FunNode.ideal_reduce(), com.cliffc.aa.node.MemSplitNode.insert_split(), com.cliffc.aa.node.DefMemNode.make_mem(), com.cliffc.aa.node.FunPtrNode.merge_ref_def(), com.cliffc.aa.node.NewObjNode.promote_forward(), com.cliffc.aa.Parse.remove_unknown_callers(), com.cliffc.aa.node.ScopeNode.replace_mem(), com.cliffc.aa.node.CallNode.set_arg(), com.cliffc.aa.node.ScopeNode.set_ctrl(), com.cliffc.aa.node.CallNode.set_dsp(), com.cliffc.aa.node.CallNode.set_fdx(), com.cliffc.aa.node.FunNode.set_is_copy(), com.cliffc.aa.node.LoadNode.set_mem(), com.cliffc.aa.node.ScopeNode.set_mem(), com.cliffc.aa.node.CallNode.set_mem(), com.cliffc.aa.node.ScopeNode.set_ptr(), com.cliffc.aa.node.ScopeNode.set_rez(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.node.CallNode.swap_new(), com.cliffc.aa.node.RetNode.tail_recursive(), and com.cliffc.aa.node.CallEpiNode.unwire().
set_is_copy()
CallEpiNode com.cliffc.aa.node.CallEpiNode.set_is_copy (Node ctl, Node mem, Node rez) private
Definition at line 396 of file CallEpiNode.java.
{
     CallNode call = call();
     if( FunNode._must_inline == call._uid ) // Assert an expected inlining happens
       FunNode._must_inline = 0;
     if( mem instanceof IntrinsicNode ) // Better error message for Intrinsic if Call args are bad
       ((IntrinsicNode)mem)._badargs = call._badargs[1];
     call._is_copy=_is_copy=true;
     // Memory was split at the Call, according to the escapes aliases, and
     // rejoined at the CallEpi.  We need to make that explicit here.
     GVNGCM.retype_mem(null,call,this,false);
     Env.GVN.add_reduce_uses(call);
     Env.GVN.add_reduce_uses(this);
     while( _defs._len>0 ) pop();
     add_def(ctl);
     add_def(mem);
     add_def(rez);
     return this;
   }
References com.cliffc.aa.node.CallNode._badargs, com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.CallEpiNode._is_copy, com.cliffc.aa.node.CallNode._is_copy, com.cliffc.aa.node.FunNode._must_inline, com.cliffc.aa.node.Node._uid, com.cliffc.aa.node.Node.add_def(), com.cliffc.aa.GVNGCM.add_reduce_uses(), com.cliffc.aa.node.CallEpiNode.call(), com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.pop(), and com.cliffc.aa.GVNGCM.retype_mem().
Referenced by com.cliffc.aa.node.CallEpiNode.ideal_reduce().
sharptr()
Type com.cliffc.aa.node.Node.sharptr (Node mem) inherited
Definition at line 855 of file Node.java.
 { return mem._val.sharptr(_val); }
References com.cliffc.aa.node.Node._val, and com.cliffc.aa.type.Type< T extends Type< T >.sharptr().
Referenced by com.cliffc.aa.node.ParmNode.err(), com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.Parse.get_display_ptr(), com.cliffc.aa.node.AssertNode.ideal_reduce(), com.cliffc.aa.node.FunNode.split_size(), com.cliffc.aa.node.ParmNode.valid_args(), com.cliffc.aa.node.ParmNode.value(), com.cliffc.aa.node.MemPrimNode.LValueLength.value(), com.cliffc.aa.node.AssertNode.value(), and com.cliffc.aa.node.MemPrimNode.LValueRead.value().
should_con()
boolean com.cliffc.aa.node.Node.should_con (Type t) inherited
Definition at line 651 of file Node.java.
{
     if( this instanceof ConNode || // Already a constant
         (this instanceof FunPtrNode && _val.is_con()) || // Already a constant
         this instanceof ErrNode || // Never touch an ErrNode
         this instanceof FreshNode ||// These modify the TVars but not the constant flows
         is_prim() )                // Never touch a Primitive
       return false; // Already a constant, or never touch an ErrNode
     // Constant argument to call: keep for call resolution.
     // Call can always inline to fold constant.
     if( this instanceof ProjNode && in(0) instanceof CallNode && ((ProjNode)this)._idx>0 )
       return false;
     // Is in-error; do not remove the error.
     if( err(true) != null )
       return false;
     // Is a constant
     return t.is_con();
   }
References com.cliffc.aa.node.Node._val, com.cliffc.aa.node.Node.err(), com.cliffc.aa.node.Node.in(), com.cliffc.aa.type.Type< T extends Type< T >.is_con(), and com.cliffc.aa.node.Node.is_prim().
Referenced by com.cliffc.aa.node.Node._do_reduce(), and com.cliffc.aa.node.Node.walk_opt().
str()
String com.cliffc.aa.node.Node.str () package inherited
Reimplemented in com.cliffc.aa.node.FunNode, com.cliffc.aa.node.CallNode, com.cliffc.aa.node.FunPtrNode, com.cliffc.aa.node.NewNode< T extends TypeObj< T >, com.cliffc.aa.node.MemSplitNode, com.cliffc.aa.node.StoreNode, com.cliffc.aa.node.LoadNode, and com.cliffc.aa.node.ErrNode.
Definition at line 283 of file Node.java.
 { return xstr(); }    // Inline longer name
References com.cliffc.aa.node.Node.xstr().
Referenced by com.cliffc.aa.node.Node.dump(), and com.cliffc.aa.node.ConNode< T extends Type >.toString().
subsume()
Node com.cliffc.aa.node.Node.subsume (Node nnn) inherited
Definition at line 201 of file Node.java.
{
     assert !nnn.is_dead();
     insert(nnn);                // Change graph shape
     nnn.keep();                 // Keep-alive
     kill();                     // Delete the old, and anything it uses
     return nnn.unkeep();        // Remove keep-alive
   }
References com.cliffc.aa.node.Node.insert(), com.cliffc.aa.node.Node.is_dead(), com.cliffc.aa.node.Node.keep(), com.cliffc.aa.node.Node.kill(), and com.cliffc.aa.node.Node.unkeep().
Referenced by com.cliffc.aa.node.MemJoinNode.combine_splits(), com.cliffc.aa.node.CallNode.copy(), com.cliffc.aa.node.Node.do_reduce(), com.cliffc.aa.node.IfNode.flip(), and com.cliffc.aa.node.Node.walk_opt().
toString()
String com.cliffc.aa.node.Node.toString () inherited
Reimplemented in com.cliffc.aa.node.ConNode< T extends Type >.
Definition at line 284 of file Node.java.
 { return dump(0,new SB(),false).toString(); }
References com.cliffc.aa.node.Node.dump().
tvar() [1/2]
TV2 com.cliffc.aa.node.Node.tvar () inherited
Definition at line 96 of file Node.java.
                     {
     TV2 tv = _tvar.find();     // Do U-F step
     return tv == _tvar ? tv : (_tvar = tv); // Update U-F style in-place.
   }
References com.cliffc.aa.node.Node._tvar, and com.cliffc.aa.tvar.TV2.find().
Referenced by com.cliffc.aa.node.MemJoinNode.add_alias_below(), com.cliffc.aa.Parse.func(), com.cliffc.aa.node.Node.tvar(), com.cliffc.aa.node.ProjNode.unify(), com.cliffc.aa.node.FreshNode.unify(), com.cliffc.aa.node.MemSplitNode.unify(), com.cliffc.aa.node.CastNode.unify(), com.cliffc.aa.node.MemJoinNode.unify(), com.cliffc.aa.node.StoreNode.unify(), and com.cliffc.aa.node.LoadNode.unify().
tvar() [2/2]
TV2 com.cliffc.aa.node.Node.tvar (int x) inherited
Definition at line 100 of file Node.java.
 { return in(x).tvar(); } // nth TV2
References com.cliffc.aa.node.Node.in(), and com.cliffc.aa.node.Node.tvar().
unelock()
void com.cliffc.aa.node.Node.unelock () inherited
Definition at line 128 of file Node.java.
{
     assert check_vals();        // elock & VALs match
     if( _elock ) {              // Edge-locked
       _elock=false;             // Unlock
       Node x = VALS.remove(this);
       assert x==this;           // Got the right node out
       Env.GVN.add_reduce(Env.GVN.add_flow(this));
     }
   }
References com.cliffc.aa.node.Node._elock, com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.GVNGCM.add_reduce(), com.cliffc.aa.node.Node.check_vals(), com.cliffc.aa.Env.GVN, and com.cliffc.aa.node.Node.VALS.
Referenced by com.cliffc.aa.node.NewNode< TypeStruct >._init(), com.cliffc.aa.node.Node.add_def(), com.cliffc.aa.node.Node.del(), com.cliffc.aa.node.Node.insert(), com.cliffc.aa.node.NewNode< TypeStruct >.kill2(), com.cliffc.aa.node.Node.pop(), com.cliffc.aa.node.Node.remove(), com.cliffc.aa.node.Node.replace(), com.cliffc.aa.node.Node.set_def(), com.cliffc.aa.node.RetNode.set_fidx(), com.cliffc.aa.node.ProjNode.set_idx(), com.cliffc.aa.node.CallNode.set_rpc(), and com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve().
unhook()
public<N extends Node> N com.cliffc.aa.node.Node.unhook () package inherited
Definition at line 239 of file Node.java.
{
     if( _keep==1 ) Env.GVN.add_work_all(this);
     return unkeep();
   }
References com.cliffc.aa.node.Node._keep, com.cliffc.aa.GVNGCM.add_work_all(), com.cliffc.aa.Env.GVN, and com.cliffc.aa.node.Node.unkeep().
Referenced by com.cliffc.aa.Parse.apply(), com.cliffc.aa.Parse.func(), and com.cliffc.aa.Parse.term().
unify()
boolean com.cliffc.aa.node.Node.unify (boolean test) inherited
Reimplemented in com.cliffc.aa.node.FunNode, com.cliffc.aa.node.LoadNode, com.cliffc.aa.node.MemPrimNode.LValueWriteFinal, com.cliffc.aa.node.MemPrimNode.LValueWrite, com.cliffc.aa.node.MemPrimNode.WritePrimNode, com.cliffc.aa.node.StoreNode, com.cliffc.aa.node.MemJoinNode, com.cliffc.aa.node.MemPrimNode.LValueRead, com.cliffc.aa.node.MemPrimNode.LValueLength, com.cliffc.aa.node.CastNode, com.cliffc.aa.node.MemSplitNode, com.cliffc.aa.node.FreshNode, com.cliffc.aa.node.ProjNode, and com.cliffc.aa.node.StartMemNode.
Definition at line 523 of file Node.java.
 { return false; }
unkeep() [1/2]
public<N extends Node> N com.cliffc.aa.node.Node.unkeep () package inherited
Definition at line 232 of file Node.java.
 { return unkeep(1); }
References com.cliffc.aa.node.Node.unkeep().
Referenced by com.cliffc.aa.Parse._args(), com.cliffc.aa.Parse._expr(), com.cliffc.aa.Parse._expr_higher(), com.cliffc.aa.Parse._short_circuit_expr(), com.cliffc.aa.node.MemJoinNode.add_alias_above(), com.cliffc.aa.node.MemJoinNode.add_alias_below(), com.cliffc.aa.node.MemJoinNode.add_alias_below_new(), com.cliffc.aa.Parse.apply(), com.cliffc.aa.node.ScopeNode.IfScope.check(), com.cliffc.aa.node.TestNodeSmall.check(), com.cliffc.aa.Env.close_display(), com.cliffc.aa.Parse.do_call0(), com.cliffc.aa.node.UnresolvedNode.filter(), com.cliffc.aa.Parse.go(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.Parse.ifex(), com.cliffc.aa.Parse.inc(), com.cliffc.aa.Env.init(), com.cliffc.aa.node.MemSplitNode.insert_split(), com.cliffc.aa.GVNGCM.iter(), com.cliffc.aa.node.FunNode.make_new_fun(), com.cliffc.aa.Parse.merge_exits(), com.cliffc.aa.Parse.remove_unknown_callers(), com.cliffc.aa.node.RetNode.RetNode(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.Parse.stmt(), com.cliffc.aa.Parse.struct(), com.cliffc.aa.node.Node.subsume(), com.cliffc.aa.node.CallNode.swap_new(), com.cliffc.aa.Parse.term(), com.cliffc.aa.Parse.tuple(), com.cliffc.aa.node.Node.unhook(), and com.cliffc.aa.node.Node.unkeep().
unkeep() [2/2]
public<N extends Node> N com.cliffc.aa.node.Node.unkeep (int d) package inherited
Definition at line 234 of file Node.java.
{
     assert _keep >= d; _keep-=d;
     return (N)this;
   }
References com.cliffc.aa.node.Node._keep.
unuse()
Node com.cliffc.aa.node.Node.unuse (Node old) private inherited
Definition at line 178 of file Node.java.
{
     if( old == null ) return this;
     old._uses.del(this);
     // Either last use of old & goes dead, or at least 1 fewer uses & changes liveness
     Env.GVN.add_unuse(old);
     if( old._uses._len!=0 && old._keep ==0 ) old.add_flow_def_extra(this);
     return this;
   }
References com.cliffc.aa.node.Node._keep, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node.add_flow_def_extra(), com.cliffc.aa.GVNGCM.add_unuse(), and com.cliffc.aa.Env.GVN.
Referenced by com.cliffc.aa.node.Node.kill(), com.cliffc.aa.node.Node.pop(), com.cliffc.aa.node.Node.remove(), and com.cliffc.aa.node.Node.set_def().
unwire()
CallEpiNode com.cliffc.aa.node.CallEpiNode.unwire (CallNode call, RetNode ret) package
Definition at line 416 of file CallEpiNode.java.
{
     assert sane_wiring();
     if( !ret.is_copy() ) {
       FunNode fun = ret.fun();
       for( int i = 1; i < fun._defs._len; i++ ) // Unwire
         if( fun.in(i).in(0) == call ) {
           fun.set_def(i, Env.XCTRL);
           Env.GVN.add_flow(fun);
           for( Node use : fun._uses ) {
             Env.GVN.add_flow(use); // Dead path, all Phis can lift
             Env.GVN.add_flow_defs(use); // All Phi uses lose a use
           }
           break;
         }
     }
     del(_defs.find(ret));
     Env.GVN.add_reduce(ret);
     assert sane_wiring();
     return this;
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._uses, com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.GVNGCM.add_flow_defs(), com.cliffc.aa.GVNGCM.add_reduce(), com.cliffc.aa.node.CallEpiNode.call(), com.cliffc.aa.node.Node.del(), com.cliffc.aa.node.RetNode.fun(), com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.in(), com.cliffc.aa.node.RetNode.is_copy(), com.cliffc.aa.node.CallEpiNode.sane_wiring(), com.cliffc.aa.node.Node.set_def(), and com.cliffc.aa.Env.XCTRL.
Referenced by com.cliffc.aa.node.CallEpiNode.ideal_reduce().
val()
Type com.cliffc.aa.node.Node.val (int idx) inherited
Definition at line 470 of file Node.java.
 { return in(idx)._val; }
References com.cliffc.aa.node.Node._val, and com.cliffc.aa.node.Node.in().
Referenced by com.cliffc.aa.node.NewNode< TypeStruct >.captured(), com.cliffc.aa.node.FunNode.check_callers(), com.cliffc.aa.node.ParmNode.err(), com.cliffc.aa.node.PrimNode.err(), com.cliffc.aa.node.PrimNode.ConvertTypeName.err(), com.cliffc.aa.node.FunNode.find_type_split(), com.cliffc.aa.node.FunNode.find_type_split_index(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.FunNode.ideal_inline(), com.cliffc.aa.node.IfNode.ideal_reduce(), com.cliffc.aa.node.RegionNode.ideal_reduce(), com.cliffc.aa.node.MrgProjNode.ideal_reduce(), com.cliffc.aa.node.MemJoinNode.ideal_reduce(), com.cliffc.aa.node.PhiNode.ideal_reduce(), com.cliffc.aa.node.PhiNode.live_use(), com.cliffc.aa.node.RetNode.RetNode(), com.cliffc.aa.node.StoreNode.StoreNode(), com.cliffc.aa.node.ThretNode.ThretNode(), com.cliffc.aa.node.StoreNode.unify(), com.cliffc.aa.node.LoadNode.unify(), com.cliffc.aa.node.ParmNode.valid_args(), com.cliffc.aa.node.CEProjNode.value(), com.cliffc.aa.node.ErrNode.value(), com.cliffc.aa.node.ProjNode.value(), com.cliffc.aa.node.MProjNode.value(), com.cliffc.aa.node.FreshNode.value(), com.cliffc.aa.node.CastNode.value(), com.cliffc.aa.node.FP2DispNode.value(), com.cliffc.aa.node.IfNode.value(), com.cliffc.aa.node.PhiNode.value(), com.cliffc.aa.node.ParmNode.value(), com.cliffc.aa.node.MemPrimNode.LValueLength.value(), com.cliffc.aa.node.RegionNode.value(), com.cliffc.aa.node.MemJoinNode.value(), com.cliffc.aa.node.MemPrimNode.LValueRead.value(), com.cliffc.aa.node.PrimNode.value(), com.cliffc.aa.node.RetNode.value(), com.cliffc.aa.node.MemPrimNode.LValueWrite.value(), com.cliffc.aa.node.MemPrimNode.LValueWriteFinal.value(), com.cliffc.aa.node.PrimNode.ConvertStrStr.value(), com.cliffc.aa.node.CallEpiNode.value(), com.cliffc.aa.node.PrimNode.AndI64.value(), com.cliffc.aa.node.PrimNode.OrI64.value(), com.cliffc.aa.node.PrimNode.EQ_OOP.value(), com.cliffc.aa.node.PrimNode.NE_OOP.value(), com.cliffc.aa.node.PrimNode.Not.value(), com.cliffc.aa.node.PrimNode.RandI64.value(), com.cliffc.aa.node.PrimNode.Id.value(), com.cliffc.aa.node.FunNode.value(), and com.cliffc.aa.node.Node.walk_opt().
value()
Type com.cliffc.aa.node.CallEpiNode.value (GVNGCM.Mode opt_mode)
Reimplemented from com.cliffc.aa.node.Node.
Definition at line 254 of file CallEpiNode.java.
{
     if( _is_copy ) return _val; // A copy
     Type tin0 = val(0);
     if( !(tin0 instanceof TypeTuple) )
       return tin0.oob();     // Weird stuff?
     TypeTuple tcall = (TypeTuple)tin0;
     if( tcall._ts.length < ARG_IDX ) return tcall.oob(); // Weird stuff
     // Get Call result.  If the Call args are in-error, then the Call is called
     // and we flow types to the post-call.... BUT the bad args are NOT passed
     // along to the function being called.
     // tcall[0] = Control
     // tcall[1] = Memory passed around the functions.
     // tcall[2] = TypeFunPtr passed to FP2Closure
     // tcall[3+]= Arg types
     Type ctl = CallNode.tctl(tcall); // Call is reached or not?
     if( ctl != Type.CTRL && ctl != Type.ALL )
       return TypeTuple.CALLE.dual();
     TypeFunPtr tfptr= CallNode.ttfpx(tcall); // Peel apart Call tuple
     TypeMemPtr tescs= CallNode.tesc(tcall);  // Peel apart Call tuple
     // Fidxes; if still in the parser, assuming calling everything
     BitsFun fidxs = tfptr==null || tfptr.is_forward_ref() ? BitsFun.FULL : tfptr.fidxs();
     // NO fidxs, means we're not calling anything.
     if( fidxs==BitsFun.EMPTY ) return TypeTuple.CALLE.dual();
     if( fidxs.above_center() ) return TypeTuple.CALLE.dual(); // Not resolved yet
     // Default memory: global worse-case scenario
     TypeMem defmem = Env.DEFMEM._val instanceof TypeMem
       ? (TypeMem)Env.DEFMEM._val
       : Env.DEFMEM._val.oob(TypeMem.ALLMEM);
     // Any not-wired unknown call targets?
     if( fidxs!=BitsFun.FULL ) {
       // If fidxs includes a parent fidx, then it was split - currently exactly
       // in two.  If both children are wired, then proceed to merge both
       // children as expected; same if the parent is still wired (perhaps with
       // some children).  If only 1 child is wired, then we have an extra fidx
       // for a not-wired child.  If this fidx is really some unknown caller we
       // would have to get super conservative; but its actually just a recently
       // split child fidx.  If we get the RetNode via FunNode.find_fidx we suffer
       // the non-local progress curse.  If we get super conservative, we end up
       // rolling backwards (original fidx returned int; each split will only
       // ever return int-or-better).  So instead we "freeze in place".
       outerloop:
       for( int fidx : fidxs ) {
         int kids=0;
         for( int i=0; i<nwired(); i++ ) {
           int rfidx = wired(i)._fidx;
           if( fidx == rfidx ) continue outerloop; // Directly wired is always OK
           if( fidx == BitsFun.parent(rfidx) ) kids++; // Count wired kids of a parent fidx
         }
         if( BitsFun.is_parent(fidx) ) { // Child of a split parent, need both kids wired
           if( kids==2 ) continue;       // Both kids wired, this is ok
           return _val;                  // "Freeze in place"
         }
         if( !opt_mode._CG ) // Before GCP?  Fidx is an unwired unknown call target
           { fidxs = BitsFun.FULL; break; }
       }
     }
     // Compute call-return value from all callee returns
     Type trez = Type   .ANY   ;
     Type tmem = TypeMem.ANYMEM;
     if( fidxs == BitsFun.FULL ) { // Called something unknown
       trez = Type.ALL;            // Unknown target does worst thing
       tmem = defmem;
     } else {                      // All targets are known & wired
       for( int i=0; i<nwired(); i++ ) {
         RetNode ret = wired(i);
         if( fidxs.test_recur(ret._fidx) ) { // Can be wired, but later fidx is removed
           Type tret = ret._val;
           if( !(tret instanceof TypeTuple) ) tret = tret.oob(TypeTuple.RET);
           tmem = tmem.meet(((TypeTuple)tret).at(MEM_IDX));
           trez = trez.meet(((TypeTuple)tret).at(REZ_IDX));
         }
       }
     }
     TypeMem post_call = (TypeMem)tmem;
     // If no memory projection, then do not compute memory
     if( (_keep==0 && ProjNode.proj(this,MEM_IDX)==null) || call().mem()==null )
       return TypeTuple.make(Type.CTRL,TypeMem.ANYMEM,trez);
     Type premem = call().mem()._val;
     // Build epilog memory.
     // Approximate "live out of call", includes things that are alive before
     // the call but not flowing in.  Catches all the "new in call" returns.
     BitsAlias esc_out = esc_out(post_call,trez);
     TypeMem caller_mem = premem instanceof TypeMem ? (TypeMem)premem : premem.oob(TypeMem.ALLMEM);
     int len = opt_mode._CG ? Math.max(caller_mem.len(),post_call.len()) : defmem.len();
     TypeObj[] pubs = new TypeObj[len];
     for( int i=1; i<pubs.length; i++ ) {
       boolean ein  = tescs._aliases.test_recur(i);
       boolean eout = esc_out       .test_recur(i);
       TypeObj pre = caller_mem.at(i);
       TypeObj obj = ein || eout ? (TypeObj)(pre.meet(post_call.at(i))) : pre;
       if( !opt_mode._CG )       // Before GCP, must use DefMem to keeps types strong as the Parser
         obj = (TypeObj)obj.join(defmem.at(i));
       pubs[i] = obj;
     }
     TypeMem tmem3 = TypeMem.make0(pubs);
     return TypeTuple.make(Type.CTRL,tmem3,trez);
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.node.RetNode._fidx, com.cliffc.aa.node.CallEpiNode._is_copy, com.cliffc.aa.node.Node._keep, com.cliffc.aa.type.TypeTuple._ts, com.cliffc.aa.node.Node._val, com.cliffc.aa.type.Bits< B extends Bits< B >.above_center(), com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.type.TypeMem.ALLMEM, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.type.TypeMem.ANYMEM, com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.node.CallEpiNode.call(), com.cliffc.aa.type.TypeTuple.CALLE, com.cliffc.aa.type.Type< T extends Type< T >.CTRL, com.cliffc.aa.Env.DEFMEM, com.cliffc.aa.type.Type< T extends Type< T >.dual(), com.cliffc.aa.type.BitsFun.EMPTY, com.cliffc.aa.node.CallEpiNode.esc_out(), com.cliffc.aa.type.TypeFunPtr.fidxs(), com.cliffc.aa.type.BitsFun.FULL, com.cliffc.aa.type.TypeFunPtr.is_forward_ref(), com.cliffc.aa.type.BitsFun.is_parent(), com.cliffc.aa.type.Type< T extends Type< T >.join(), com.cliffc.aa.node.Node.len(), com.cliffc.aa.type.TypeMem.len(), com.cliffc.aa.type.TypeTuple.make(), com.cliffc.aa.type.TypeMem.make0(), com.cliffc.aa.type.Type< T extends Type< T >.meet(), com.cliffc.aa.node.CallNode.mem(), com.cliffc.aa.node.CallEpiNode.nwired(), com.cliffc.aa.type.Type< T extends Type< T >.oob(), com.cliffc.aa.type.BitsFun.parent(), com.cliffc.aa.node.ProjNode.proj(), com.cliffc.aa.type.TypeTuple.RET, com.cliffc.aa.node.CallNode.tctl(), com.cliffc.aa.node.CallNode.tesc(), com.cliffc.aa.type.Bits< B extends Bits< B >.test_recur(), com.cliffc.aa.node.CallNode.ttfpx(), com.cliffc.aa.node.Node.val(), and com.cliffc.aa.node.CallEpiNode.wired().
walk_dom_last()
Node com.cliffc.aa.node.Node.walk_dom_last (Predicate< Node > P) package inherited
Reimplemented in com.cliffc.aa.node.ScopeNode, com.cliffc.aa.node.RegionNode, com.cliffc.aa.node.ConNode< T extends Type >, com.cliffc.aa.node.ThunkNode, com.cliffc.aa.node.StartNode, and com.cliffc.aa.node.LoopNode.
Definition at line 863 of file Node.java.
{
     assert in(0) != null;       // All default control nodes pass ctrl in slot 0
     Node n = in(0).walk_dom_last(P);
     if( n != null ) return n;   // Take last answer first
     return P.test(this) ? this : null;
   }
References com.cliffc.aa.node.Node.in(), and com.cliffc.aa.node.Node.walk_dom_last().
Referenced by com.cliffc.aa.node.CastNode.ideal_mono(), com.cliffc.aa.node.LoopNode.walk_dom_last(), com.cliffc.aa.node.ThunkNode.walk_dom_last(), com.cliffc.aa.node.RegionNode.walk_dom_last(), and com.cliffc.aa.node.Node.walk_dom_last().
walk_initype()
final void com.cliffc.aa.node.Node.walk_initype (GVNGCM gvn, VBitSet bs) inherited
Definition at line 691 of file Node.java.
{
     if( bs.tset(_uid) ) return;    // Been there, done that
     _val = Type.ANY;               // Highest value
     _live = TypeMem.DEAD;          // Not alive
     // Walk reachable graph
     gvn.add_flow(this);
     for( Node use : _uses ) use.walk_initype(gvn,bs);
     for( Node def : _defs ) if( def != null ) def.walk_initype(gvn,bs);
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._live, com.cliffc.aa.node.Node._uid, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node._val, com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.type.TypeMem.DEAD, and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.GVNGCM.gcp().
walk_opt()
void com.cliffc.aa.node.Node.walk_opt (VBitSet visit) inherited
Definition at line 797 of file Node.java.
{
     assert !is_dead();
     if( visit.tset(_uid) ) return; // Been there, done that
     // Replace any constants.  Since the node computes a constant, its inputs
     // were never marked live, and so go dead and so go to ANY and so are not
     // available to recompute the constant later.
     Type val = _val;
     TypeFunPtr tfp;
     if( val instanceof TypeFunPtr &&
         _live.live_no_disp() &&
         (tfp=(TypeFunPtr)val)._disp!=TypeMemPtr.NO_DISP )
       val = tfp.make_no_disp();
     if( should_con(val) )
       subsume(con(val)).xliv(GVNGCM.Mode.Opto);
     // Walk reachable graph
     if( is_dead() ) return;
     Env.GVN.add_work_all(this);
     for( Node def : _defs )  if( def != null )  def.walk_opt(visit);
     for( Node use : _uses )                     use.walk_opt(visit);
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._live, com.cliffc.aa.node.Node._uid, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node._val, com.cliffc.aa.GVNGCM.add_work_all(), com.cliffc.aa.node.Node.con(), com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.is_dead(), com.cliffc.aa.type.TypeMem.live_no_disp(), com.cliffc.aa.type.TypeFunPtr.make_no_disp(), com.cliffc.aa.type.TypeMemPtr.NO_DISP, com.cliffc.aa.GVNGCM.Mode.Opto, com.cliffc.aa.node.Node.should_con(), com.cliffc.aa.node.Node.subsume(), com.cliffc.aa.util.VBitSet.tset(), com.cliffc.aa.node.Node.val(), com.cliffc.aa.node.Node.walk_opt(), and com.cliffc.aa.node.Node.xliv().
Referenced by com.cliffc.aa.GVNGCM.gcp(), and com.cliffc.aa.node.Node.walk_opt().
walkerr_def()
void com.cliffc.aa.node.Node.walkerr_def (HashSet< ErrMsg > errs, VBitSet bs) inherited
Definition at line 771 of file Node.java.
{
     if( bs.tset(_uid) ) return; // Been there, done that
     for( int i=0; i<_defs._len; i++ ) {
       Node def = _defs.at(i);   // Walk data defs for more errors
       if( def == null || def._val == Type.XCTRL ) continue;
       // Walk function bodies that are wired, but not bare FunPtrs.
       if( def instanceof FunPtrNode && !def.is_forward_ref() )
         continue;
       def.walkerr_def(errs,bs);
     }
     if( is_prim() ) return;
     // Skip reporting if any input is 'all', as the input should report instead.
     for( Node def : _defs )
       if( def !=null && def._val ==Type.ALL )
         return;                 // Skip reporting.
     adderr(errs);
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._uid, com.cliffc.aa.node.Node._val, com.cliffc.aa.node.Node.adderr(), com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.node.Node.is_forward_ref(), com.cliffc.aa.node.Node.is_prim(), com.cliffc.aa.util.VBitSet.tset(), com.cliffc.aa.node.Node.walkerr_def(), and com.cliffc.aa.type.Type< T extends Type< T >.XCTRL.
Referenced by com.cliffc.aa.Parse.gather_errors(), and com.cliffc.aa.node.Node.walkerr_def().
wire0()
void com.cliffc.aa.node.CallEpiNode.wire0 (CallNode call, Node fun) package
Definition at line 218 of file CallEpiNode.java.
{
     // Wire.  Bulk parallel function argument path add
     // Add an input path to all incoming arg ParmNodes from the Call.  Cannot
     // assert finding all args, because dead args may already be removed - and
     // so there's no Parm/Phi to attach the incoming arg to.
     for( Node arg : fun._uses ) {
       if( arg.in(0) != fun || !(arg instanceof ParmNode) ) continue;
       Node actual;
       int idx = ((ParmNode)arg)._idx;
       switch( idx ) {
       case 0: actual = new ConNode<>(TypeRPC.make(call._rpc)); break; // Always RPC is a constant
       case MEM_IDX: actual = new MProjNode(call,(Env.DEFMEM._uses._len==0) ? Env.ANY : Env.DEFMEM); break;    // Memory into the callee
       default: actual = idx >= call.nargs()              // Check for args present
           ? new ConNode<>(Type.ALL) // Missing args, still wire (to keep FunNode neighbors) but will error out later.
           : new ProjNode(call,idx); // Normal args
         break;
       }
       actual._live = arg._live; // Set it before CSE during init1
       arg.add_def(actual.init1());
       if( arg._val.is_con() ) // Added an edge, value may change or go in-error
         GVN.add_flow_defs(arg); // So use-liveness changes
     }
     // Add matching control to function via a CallGraph edge.
     fun.add_def(new CEProjNode(call,fun instanceof FunNode && !((FunNode) fun)._thunk_rhs ? ((FunNode)fun)._sig : null).init1());
     GVN.add_flow(fun);
     GVN.add_flow_uses(fun);
     if( fun instanceof ThunkNode ) GVN.add_reduce_uses(fun);
     if( fun instanceof FunNode ) GVN.add_inline((FunNode)fun);
   }
References com.cliffc.aa.node.Node._live, com.cliffc.aa.node.CallNode._rpc, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node._val, com.cliffc.aa.node.Node.add_def(), com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.Env.ANY, com.cliffc.aa.node.CallEpiNode.call(), com.cliffc.aa.Env.DEFMEM, com.cliffc.aa.node.Node.in(), com.cliffc.aa.node.Node.init1(), com.cliffc.aa.type.Type< T extends Type< T >.is_con(), com.cliffc.aa.type.TypeRPC.make(), and com.cliffc.aa.node.CallNode.nargs().
Referenced by com.cliffc.aa.node.FunNode.split_callers(), and com.cliffc.aa.node.CallEpiNode.wire1().
wire1()
void com.cliffc.aa.node.CallEpiNode.wire1 (CallNode call, Node fun, Node ret) package
Definition at line 207 of file CallEpiNode.java.
{
     assert _defs.find(ret)==-1; // No double wiring
     wire0(call,fun);
     // Wire self to the return
     add_def(ret);
     GVN.add_flow(this);
     GVN.add_flow(call);
     GVN.add_flow_defs(call);
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node.add_def(), com.cliffc.aa.node.CallEpiNode.call(), and com.cliffc.aa.node.CallEpiNode.wire0().
Referenced by com.cliffc.aa.node.CallEpiNode.check_and_wire(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), and com.cliffc.aa.node.FunNode.split_callers().
wired()
RetNode com.cliffc.aa.node.CallEpiNode.wired (int x)
Definition at line 38 of file CallEpiNode.java.
 { return (RetNode)in(x+2); }
References com.cliffc.aa.node.Node.in().
Referenced by com.cliffc.aa.node.CallEpiNode.add_flow_use_extra(), com.cliffc.aa.Parse.do_call0(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.CallEpiNode.sane_wiring(), com.cliffc.aa.node.FunNode.split_callers(), and com.cliffc.aa.node.CallEpiNode.value().
xliv()
Node com.cliffc.aa.node.Node.xliv (GVNGCM.Mode opt_mode) inherited
Definition at line 500 of file Node.java.
 { _live = live(opt_mode); return this; }
References com.cliffc.aa.node.Node._live, and com.cliffc.aa.node.Node.live().
Referenced by com.cliffc.aa.TestLive.testBasic(), com.cliffc.aa.TestLive.testNewObj(), and com.cliffc.aa.node.Node.walk_opt().
xstr()
String com.cliffc.aa.node.CallEpiNode.xstr ()
Reimplemented from com.cliffc.aa.node.Node.
Definition at line 30 of file CallEpiNode.java.
                                  {// Self short name
     if( _is_copy ) return "CopyEpi";
     if( is_dead() ) return "XallEpi";
     return "CallEpi";
   }
References com.cliffc.aa.node.CallEpiNode._is_copy, and com.cliffc.aa.node.Node.is_dead().
xval()
Type com.cliffc.aa.node.Node.xval () inherited
Definition at line 460 of file Node.java.
                       {
     Type oval = _val;                     // Get old type
     Type nval = value(Env.GVN._opt_mode); // Get best type
     if( nval!=oval ) {
       _val = nval;
       Env.GVN.add_flow_uses(this); // Put uses on worklist... values flows downhill
     }
     return nval;
   }
References com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.node.Node._val, com.cliffc.aa.GVNGCM.add_flow_uses(), com.cliffc.aa.Env.GVN, and com.cliffc.aa.node.Node.value().
Referenced by com.cliffc.aa.node.MemSplitNode.add_alias(), com.cliffc.aa.node.MemJoinNode.add_alias_below_new(), com.cliffc.aa.node.NewObjNode.add_fun(), com.cliffc.aa.node.TestNodeSmall.check(), com.cliffc.aa.node.MemJoinNode.combine_splits(), com.cliffc.aa.node.ConTypeNode.def_fref(), com.cliffc.aa.node.LoadNode.ideal_mono(), com.cliffc.aa.node.MemJoinNode.ideal_reduce(), com.cliffc.aa.node.StoreNode.ideal_reduce(), com.cliffc.aa.node.IntrinsicNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.node.FunNode.make_new_fun(), com.cliffc.aa.node.FunPtrNode.merge_ref_def(), com.cliffc.aa.node.NewObjNode.promote_forward(), com.cliffc.aa.node.MemSplitNode.remove_alias(), com.cliffc.aa.node.FunNode.split_callers(), and com.cliffc.aa.TestLive.testNewObj().
Member Data Documentation
_defs
Ary<Node> com.cliffc.aa.node.Node._defs inherited
Definition at line 124 of file Node.java.
Referenced by com.cliffc.aa.node.MemJoinNode.add_alias_above(), com.cliffc.aa.node.MemJoinNode.add_alias_below(), com.cliffc.aa.node.Node.add_def(), com.cliffc.aa.node.UnresolvedNode.add_def_unresolved(), com.cliffc.aa.node.CallNode.add_flow_extra(), com.cliffc.aa.GVNGCM.add_work_defs(), com.cliffc.aa.node.CallNode.arg(), com.cliffc.aa.node.MemPrimNode.ReadPrimNode.as_fun(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.as_fun(), com.cliffc.aa.node.PrimNode.as_fun(), com.cliffc.aa.node.FunNode.bad_mem_use(), com.cliffc.aa.node.CallEpiNode.check_and_wire(), com.cliffc.aa.node.FunNode.check_callers(), com.cliffc.aa.node.MemJoinNode.combine_splits(), com.cliffc.aa.node.UnresolvedNode.copy(), com.cliffc.aa.node.Node.copy(), com.cliffc.aa.node.ConTypeNode.def_fref(), com.cliffc.aa.node.Node.del(), com.cliffc.aa.node.Node.do_flow(), com.cliffc.aa.node.Node.dump(), com.cliffc.aa.node.Node.equals(), com.cliffc.aa.node.MemPrimNode.err(), com.cliffc.aa.node.ErrNode.err(), com.cliffc.aa.node.ParmNode.err(), com.cliffc.aa.node.PrimNode.err(), com.cliffc.aa.node.CallNode.fdx(), com.cliffc.aa.node.UnresolvedNode.filter(), com.cliffc.aa.node.Node.find(), com.cliffc.aa.node.FunNode.find_body(), com.cliffc.aa.node.UnresolvedNode.find_fidx(), com.cliffc.aa.node.FunNode.find_type_split(), com.cliffc.aa.node.FunNode.find_type_split_index(), com.cliffc.aa.node.UnresolvedNode.funptr(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.node.CallNode.get_fptr(), com.cliffc.aa.node.FunNode.has_unknown_callers(), com.cliffc.aa.node.Node.hashCode(), com.cliffc.aa.node.LoadNode.ideal_grow(), com.cliffc.aa.node.CallNode.ideal_grow(), com.cliffc.aa.node.PrimNode.AndThen.ideal_grow(), com.cliffc.aa.node.PrimNode.OrElse.ideal_grow(), com.cliffc.aa.node.FunNode.ideal_inline(), com.cliffc.aa.node.FP2DispNode.ideal_reduce(), com.cliffc.aa.node.IfNode.ideal_reduce(), com.cliffc.aa.node.RegionNode.ideal_reduce(), com.cliffc.aa.node.UnresolvedNode.ideal_reduce(), com.cliffc.aa.node.MemJoinNode.ideal_reduce(), com.cliffc.aa.node.PhiNode.ideal_reduce(), com.cliffc.aa.node.ParmNode.ideal_reduce(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.NewNode< TypeStruct >.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.node.Node.in(), com.cliffc.aa.node.Node.insert(), com.cliffc.aa.node.ScopeNode.is_closure(), com.cliffc.aa.node.ThunkNode.is_copy(), com.cliffc.aa.node.RegionNode.is_copy(), com.cliffc.aa.node.PrimNode.AndThen.is_copy(), com.cliffc.aa.node.PrimNode.OrElse.is_copy(), com.cliffc.aa.node.UnresolvedNode.is_pure_call(), com.cliffc.aa.node.Node.kill(), com.cliffc.aa.node.NewNode< TypeStruct >.kill2(), com.cliffc.aa.node.Node.len(), com.cliffc.aa.node.MemPrimNode.ReadPrimNode.live_use(), com.cliffc.aa.node.PhiNode.live_use(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.node.DefMemNode.make_mem(), com.cliffc.aa.node.FunPtrNode.merge_ref_def(), com.cliffc.aa.node.Node.more_flow(), com.cliffc.aa.node.Node.more_ideal(), com.cliffc.aa.node.CallNode.nargs(), com.cliffc.aa.node.Node.Node(), com.cliffc.aa.node.CallEpiNode.nwired(), com.cliffc.aa.node.CProjNode.op_prec(), com.cliffc.aa.node.UnresolvedNode.op_prec(), com.cliffc.aa.node.CallNode.parms(), com.cliffc.aa.node.Node.pop(), com.cliffc.aa.node.Node.remove(), com.cliffc.aa.node.Node.replace(), com.cliffc.aa.node.FunNode.ret(), com.cliffc.aa.node.CallEpiNode.sane_wiring(), com.cliffc.aa.node.Node.set_dead(), com.cliffc.aa.node.Node.set_def(), com.cliffc.aa.node.CallNode.set_fdx(), com.cliffc.aa.node.CallEpiNode.set_is_copy(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.node.FunNode.split_size(), com.cliffc.aa.node.RegionNode.stacked_region(), com.cliffc.aa.node.FunPtrNode.str(), com.cliffc.aa.Parse.string(), com.cliffc.aa.node.TestNode.stx(), com.cliffc.aa.node.RetNode.tail_recursive(), com.cliffc.aa.Parse.term(), com.cliffc.aa.node.TestNode.test1monotonic(), com.cliffc.aa.node.TestNode.test1monotonic_intrinsic(), com.cliffc.aa.node.TestNode.test1monotonic_prim(), com.cliffc.aa.node.MemJoinNode.unify(), com.cliffc.aa.node.FunNode.unwire(), com.cliffc.aa.node.CallEpiNode.unwire(), com.cliffc.aa.node.DefMemNode.value(), com.cliffc.aa.node.UnresolvedNode.value(), com.cliffc.aa.node.PhiNode.value(), com.cliffc.aa.node.ParmNode.value(), com.cliffc.aa.node.ConTypeNode.value(), com.cliffc.aa.node.RegionNode.value(), com.cliffc.aa.node.MemJoinNode.value(), com.cliffc.aa.node.PrimNode.value(), com.cliffc.aa.node.PrimNode.ConvertTypeName.value(), com.cliffc.aa.node.CallNode.value(), com.cliffc.aa.node.FunNode.value(), com.cliffc.aa.node.RegionNode.walk_dom_last(), com.cliffc.aa.node.Node.walk_initype(), com.cliffc.aa.node.Node.walk_opt(), com.cliffc.aa.node.Node.walkerr_def(), com.cliffc.aa.node.CallEpiNode.wire1(), and com.cliffc.aa.node.FunPtrNode.xstr().
_elock
boolean com.cliffc.aa.node.Node._elock inherited
Definition at line 87 of file Node.java.
Referenced by com.cliffc.aa.node.Node._do_reduce(), com.cliffc.aa.node.Node._elock(), com.cliffc.aa.node.NewNode< TypeStruct >._init(), com.cliffc.aa.node.Node.check_vals(), com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.Node.copy(), com.cliffc.aa.node.Node.do_reduce(), com.cliffc.aa.node.Node.init1(), com.cliffc.aa.node.Node.kill(), com.cliffc.aa.node.FunNode.split_callers(), and com.cliffc.aa.node.Node.unelock().
_INIT0_CNT
int com.cliffc.aa.node.Node._INIT0_CNT static inherited
Definition at line 58 of file Node.java.
Referenced by com.cliffc.aa.node.Node.init0(), com.cliffc.aa.node.Node.is_prim(), and com.cliffc.aa.TestLive.testNewObj().
_is_copy
boolean com.cliffc.aa.node.CallEpiNode._is_copy
Definition at line 25 of file CallEpiNode.java.
Referenced by com.cliffc.aa.Parse.do_call0(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.CallEpiNode.is_copy(), com.cliffc.aa.node.CallEpiNode.live_use(), com.cliffc.aa.node.CallEpiNode.set_is_copy(), com.cliffc.aa.node.CallEpiNode.value(), and com.cliffc.aa.node.CallEpiNode.xstr().
_keep
byte com.cliffc.aa.node.Node._keep inherited
Definition at line 86 of file Node.java.
Referenced by com.cliffc.aa.GVNGCM.add_unuse(), com.cliffc.aa.node.NewNode< TypeStruct >.captured(), com.cliffc.aa.node.Node.copy(), com.cliffc.aa.node.Node.do_flow(), com.cliffc.aa.node.Node.do_grow(), com.cliffc.aa.node.Node.do_reduce(), com.cliffc.aa.node.IfNode.flip(), com.cliffc.aa.node.CallNode.ideal_grow(), com.cliffc.aa.node.IfNode.ideal_reduce(), com.cliffc.aa.node.RegionNode.ideal_reduce(), com.cliffc.aa.node.MrgProjNode.ideal_reduce(), com.cliffc.aa.node.MemJoinNode.ideal_reduce(), com.cliffc.aa.node.StoreNode.ideal_reduce(), com.cliffc.aa.node.IntrinsicNode.ideal_reduce(), com.cliffc.aa.node.FunNode.ideal_reduce(), com.cliffc.aa.node.Node.keep(), com.cliffc.aa.node.Node.kill(), com.cliffc.aa.node.ConNode< T extends Type >.live(), com.cliffc.aa.node.MemJoinNode.live(), com.cliffc.aa.node.Node.live(), com.cliffc.aa.node.CallEpiNode.live_use(), com.cliffc.aa.node.Node.live_use(), com.cliffc.aa.node.Node.more_flow(), com.cliffc.aa.node.Node.more_ideal(), com.cliffc.aa.node.Node.unhook(), com.cliffc.aa.node.Node.unkeep(), com.cliffc.aa.node.Node.unuse(), com.cliffc.aa.node.ThunkNode.value(), com.cliffc.aa.node.CallEpiNode.value(), com.cliffc.aa.GVNGCM.xform(), and com.cliffc.aa.GVNGCM.xreduce().
_live
TypeMem com.cliffc.aa.node.Node._live inherited
Definition at line 89 of file Node.java.
Referenced by com.cliffc.aa.node.LoadNode._live_use(), com.cliffc.aa.node.NewNode< TypeStruct >.add_flow_def_extra(), com.cliffc.aa.node.FunPtrNode.add_flow_extra(), com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.ConNode< T extends Type >.ConNode(), com.cliffc.aa.node.Node.do_flow(), com.cliffc.aa.node.Node.dump(), com.cliffc.aa.node.ErrNode.ErrNode(), com.cliffc.aa.node.IfNode.flip(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.node.LoadNode.get_fld2(), com.cliffc.aa.node.MrgProjNode.ideal_reduce(), com.cliffc.aa.node.StoreNode.ideal_reduce(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.node.FunNode.ideal_reduce(), com.cliffc.aa.node.Node.init1(), com.cliffc.aa.node.MemSplitNode.insert_split(), com.cliffc.aa.node.MemJoinNode.live(), com.cliffc.aa.node.CallNode.live(), com.cliffc.aa.node.ThretNode.live_use(), com.cliffc.aa.node.DefMemNode.live_use(), com.cliffc.aa.node.FreshNode.live_use(), com.cliffc.aa.node.FP2DispNode.live_use(), com.cliffc.aa.node.MProjNode.live_use(), com.cliffc.aa.node.CastNode.live_use(), com.cliffc.aa.node.NewNode< TypeStruct >.live_use(), com.cliffc.aa.node.MrgProjNode.live_use(), com.cliffc.aa.node.PhiNode.live_use(), com.cliffc.aa.node.MemPrimNode.LValueLength.live_use(), com.cliffc.aa.node.AssertNode.live_use(), com.cliffc.aa.node.IntrinsicNode.live_use(), com.cliffc.aa.node.StoreNode.live_use(), com.cliffc.aa.node.FunPtrNode.live_use(), com.cliffc.aa.node.ScopeNode.live_use(), com.cliffc.aa.node.MemJoinNode.live_use(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.live_use(), com.cliffc.aa.node.RetNode.live_use(), com.cliffc.aa.node.LoadNode.live_use(), com.cliffc.aa.node.CallEpiNode.live_use(), com.cliffc.aa.node.Node.live_use(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.node.Node.live_uses(), com.cliffc.aa.node.Node.merge(), com.cliffc.aa.node.Node.more_flow(), com.cliffc.aa.node.Node.more_ideal(), com.cliffc.aa.node.Node.Node(), com.cliffc.aa.node.PhiNode.PhiNode(), com.cliffc.aa.GVNGCM.revalive(), com.cliffc.aa.node.RetNode.tail_recursive(), com.cliffc.aa.TestLive.testBasic(), com.cliffc.aa.TestLive.testNewObj(), com.cliffc.aa.node.ThretNode.ThretNode(), com.cliffc.aa.node.DefMemNode.value(), com.cliffc.aa.node.Node.walk_initype(), com.cliffc.aa.node.Node.walk_opt(), com.cliffc.aa.node.CallEpiNode.wire0(), and com.cliffc.aa.node.Node.xliv().
_op
final byte com.cliffc.aa.node.Node._op package inherited
Definition at line 85 of file Node.java.
Referenced by com.cliffc.aa.node.FunNode.bad_mem_use(), com.cliffc.aa.node.Node.dumprpo(), com.cliffc.aa.node.Node.equals(), com.cliffc.aa.node.FunNode.find_body(), com.cliffc.aa.node.Node.hashCode(), com.cliffc.aa.node.LoadNode.ideal_grow(), com.cliffc.aa.node.Node.is_CFG(), com.cliffc.aa.node.Node.is_multi_head(), com.cliffc.aa.node.Node.is_multi_tail(), com.cliffc.aa.node.Node.Node(), com.cliffc.aa.node.Node.postorder(), com.cliffc.aa.node.RegionNode.stacked_region(), com.cliffc.aa.node.RetNode.tail_recursive(), com.cliffc.aa.node.FunNode.unwire(), and com.cliffc.aa.node.Node.xstr().
_tvar
TV2 com.cliffc.aa.node.Node._tvar package inherited
Definition at line 94 of file Node.java.
Referenced by com.cliffc.aa.node.MemJoinNode.add_alias_below(), com.cliffc.aa.node.Node.copy(), com.cliffc.aa.node.Node.Node(), and com.cliffc.aa.node.Node.tvar().
_uid
int com.cliffc.aa.node.Node._uid inherited
Definition at line 84 of file Node.java.
Referenced by com.cliffc.aa.tvar.TV2._push_update(), com.cliffc.aa.tvar.UQNodes.add(), com.cliffc.aa.node.Node.check_vals(), com.cliffc.aa.node.Node.copy(), com.cliffc.aa.node.Work.del(), com.cliffc.aa.node.Node.dump(), com.cliffc.aa.node.Node.dumprpo(), com.cliffc.aa.node.Node.find(), com.cliffc.aa.node.FunNode.find_body(), com.cliffc.aa.node.FunNode.ideal_inline(), com.cliffc.aa.node.Node.is_prim(), com.cliffc.aa.node.Node.kill(), com.cliffc.aa.tvar.UQNodes.make(), com.cliffc.aa.node.Node.more_flow(), com.cliffc.aa.node.Node.more_ideal(), com.cliffc.aa.node.Node.Node(), com.cliffc.aa.node.Work.on(), com.cliffc.aa.node.Work.pop(), com.cliffc.aa.node.Node.postorder(), com.cliffc.aa.tvar.UQNodes.rename(), com.cliffc.aa.tvar.TV2.reset(), com.cliffc.aa.node.CallEpiNode.set_is_copy(), com.cliffc.aa.node.Node.walk_initype(), com.cliffc.aa.node.Node.walk_opt(), and com.cliffc.aa.node.Node.walkerr_def().
_uses
Ary<Node> com.cliffc.aa.node.Node._uses inherited
Definition at line 245 of file Node.java.
Referenced by com.cliffc.aa.node.CallNode._ideal_grow(), com.cliffc.aa.node.Node.add_def(), com.cliffc.aa.node.MemJoinNode.add_flow_def_extra(), com.cliffc.aa.node.MrgProjNode.add_flow_def_extra(), com.cliffc.aa.node.RegionNode.add_flow_def_extra(), com.cliffc.aa.node.CProjNode.add_flow_use_extra(), com.cliffc.aa.node.ParmNode.add_flow_use_extra(), com.cliffc.aa.node.RegionNode.add_flow_use_extra(), com.cliffc.aa.node.StoreNode.add_reduce_extra(), com.cliffc.aa.GVNGCM.add_unuse(), com.cliffc.aa.GVNGCM.add_work_uses(), com.cliffc.aa.node.MemPrimNode.ReadPrimNode.as_fun(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.as_fun(), com.cliffc.aa.node.PrimNode.as_fun(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun(), com.cliffc.aa.node.FunNode.bad_mem_use(), com.cliffc.aa.node.NewNode< TypeStruct >.captured(), com.cliffc.aa.node.CallNode.cepi(), com.cliffc.aa.node.FunNode.check_callers(), com.cliffc.aa.node.Node.check_solo_mem_writer(), com.cliffc.aa.node.MemSplitNode.check_split(), com.cliffc.aa.node.MemJoinNode.combine_splits(), com.cliffc.aa.node.Node.copy(), com.cliffc.aa.node.Node.del(), com.cliffc.aa.node.FunPtrNode.display_used(), com.cliffc.aa.node.Node.do_flow(), com.cliffc.aa.node.Node.do_reduce(), com.cliffc.aa.node.Node.dump(), com.cliffc.aa.node.ErrNode.err(), com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.node.Node.find(), com.cliffc.aa.node.FunNode.find_body(), com.cliffc.aa.node.FunNode.find_type_split_index(), com.cliffc.aa.node.IfNode.flip(), com.cliffc.aa.node.FunNode.fptr(), com.cliffc.aa.node.RetNode.funptr(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.node.Node.get_mem_writer(), com.cliffc.aa.node.StoreNode.ideal_grow(), com.cliffc.aa.node.PrimNode.AndThen.ideal_grow(), com.cliffc.aa.node.PrimNode.OrElse.ideal_grow(), com.cliffc.aa.node.IfNode.ideal_reduce(), com.cliffc.aa.node.RegionNode.ideal_reduce(), com.cliffc.aa.node.MrgProjNode.ideal_reduce(), com.cliffc.aa.node.MemJoinNode.ideal_reduce(), com.cliffc.aa.node.StoreNode.ideal_reduce(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.IntrinsicNode.ideal_reduce(), com.cliffc.aa.node.RetNode.ideal_reduce(), com.cliffc.aa.node.FunNode.ideal_reduce(), com.cliffc.aa.node.Node.insert(), com.cliffc.aa.node.Node.is_dead(), com.cliffc.aa.node.MemSplitNode.join(), com.cliffc.aa.node.Node.kill(), com.cliffc.aa.Parse.kill(), com.cliffc.aa.node.NewNode< TypeStruct >.kill2(), com.cliffc.aa.node.ConNode< T extends Type >.live(), com.cliffc.aa.node.ScopeNode.live(), com.cliffc.aa.node.Node.live(), com.cliffc.aa.node.FunNode.make_new_fun(), com.cliffc.aa.node.FunPtrNode.merge_ref_def(), com.cliffc.aa.node.Node.more_flow(), com.cliffc.aa.node.Node.more_ideal(), com.cliffc.aa.node.NewNode< TypeStruct >.mrg(), com.cliffc.aa.node.FunNode.names(), com.cliffc.aa.node.Node.Node(), com.cliffc.aa.node.FunNode.parm(), com.cliffc.aa.node.FunNode.parms(), com.cliffc.aa.node.Node.postorder(), com.cliffc.aa.node.ProjNode.proj(), com.cliffc.aa.node.NewNode< TypeStruct >.ptr(), com.cliffc.aa.node.MemSplitNode.remove_alias(), com.cliffc.aa.Parse.remove_unknown_callers(), com.cliffc.aa.node.FunNode.ret(), com.cliffc.aa.GVNGCM.retype_mem(), com.cliffc.aa.node.Node.set_dead(), com.cliffc.aa.node.Node.set_def(), com.cliffc.aa.node.ScopeNode.set_mem(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.node.RegionNode.stacked_region(), com.cliffc.aa.node.RetNode.tail_recursive(), com.cliffc.aa.node.ThunkNode.thret(), com.cliffc.aa.node.Node.unuse(), com.cliffc.aa.node.CallEpiNode.unwire(), com.cliffc.aa.node.CEProjNode.value(), com.cliffc.aa.node.Node.walk_initype(), com.cliffc.aa.node.Node.walk_opt(), com.cliffc.aa.node.CallEpiNode.wire0(), com.cliffc.aa.GVNGCM.xform(), and com.cliffc.aa.GVNGCM.xreduce().
_val
Type com.cliffc.aa.node.Node._val inherited
Definition at line 88 of file Node.java.
Referenced by com.cliffc.aa.node.Node._do_reduce(), com.cliffc.aa.node.LoadNode._find_previous_store_call(), com.cliffc.aa.node.CallNode._ideal_grow(), com.cliffc.aa.node.MemPrimNode.LValueLength._live_use(), com.cliffc.aa.node.LoadNode._live_use(), com.cliffc.aa.node.FreshNode.add_flow_extra(), com.cliffc.aa.node.CastNode.add_flow_extra(), com.cliffc.aa.node.CallNode.add_flow_extra(), com.cliffc.aa.node.FunPtrNode.add_flow_use_extra(), com.cliffc.aa.node.CallEpiNode.check_and_wire(), com.cliffc.aa.node.RetNode.check_phi_type(), com.cliffc.aa.node.CastNode.checked(), com.cliffc.aa.node.MemJoinNode.combine_splits(), com.cliffc.aa.node.ScopeNode.compute_live_mem(), com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.NewObjNode.create_active(), com.cliffc.aa.Parse.do_exit(), com.cliffc.aa.node.Node.do_flow(), com.cliffc.aa.node.Node.dump(), com.cliffc.aa.node.MemPrimNode.err(), com.cliffc.aa.node.ErrNode.err(), com.cliffc.aa.node.ParmNode.err(), com.cliffc.aa.node.PhiNode.err(), com.cliffc.aa.node.AssertNode.err(), com.cliffc.aa.node.IntrinsicNode.err(), com.cliffc.aa.node.StoreNode.err(), com.cliffc.aa.node.LoadNode.err(), com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.node.StoreNode.escapees(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.escapees(), com.cliffc.aa.node.CallNode.escapees(), com.cliffc.aa.Parse.fact(), com.cliffc.aa.node.CallNode.fidxs(), com.cliffc.aa.node.LoadNode.find_previous_store(), com.cliffc.aa.node.FunNode.find_type_split(), com.cliffc.aa.node.FunNode.find_type_split_index(), com.cliffc.aa.Parse.func(), com.cliffc.aa.Parse.gather_errors(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.StoreNode.ideal_grow(), com.cliffc.aa.node.CallNode.ideal_grow(), com.cliffc.aa.node.FunNode.ideal_inline(), com.cliffc.aa.node.LoadNode.ideal_mono(), com.cliffc.aa.node.IfNode.ideal_reduce(), com.cliffc.aa.node.FreshNode.ideal_reduce(), com.cliffc.aa.node.MrgProjNode.ideal_reduce(), com.cliffc.aa.node.CastNode.ideal_reduce(), com.cliffc.aa.node.MemJoinNode.ideal_reduce(), com.cliffc.aa.node.LoadNode.ideal_reduce(), com.cliffc.aa.node.PhiNode.ideal_reduce(), com.cliffc.aa.node.StoreNode.ideal_reduce(), com.cliffc.aa.node.ParmNode.ideal_reduce(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.IntrinsicNode.ideal_reduce(), com.cliffc.aa.node.RetNode.ideal_reduce(), com.cliffc.aa.node.FunPtrNode.ideal_reduce(), com.cliffc.aa.node.ScopeNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.Parse.ifex(), com.cliffc.aa.node.Node.init1(), com.cliffc.aa.node.IfNode.is_copy(), com.cliffc.aa.node.CallNode.is_copy(), com.cliffc.aa.node.CallNode.least_cost(), com.cliffc.aa.node.Node.live(), com.cliffc.aa.node.CallNode.live(), com.cliffc.aa.node.MemPrimNode.ReadPrimNode.live_use(), com.cliffc.aa.node.CallEpiNode.live_use(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.node.CallNode.live_use_call(), com.cliffc.aa.node.Node.live_uses(), com.cliffc.aa.Env.lookup_valtype(), com.cliffc.aa.Parse.merge_exits(), com.cliffc.aa.node.Node.more_flow(), com.cliffc.aa.node.Node.more_ideal(), com.cliffc.aa.node.Node.Node(), com.cliffc.aa.GVNGCM.remove_ambi(), com.cliffc.aa.GVNGCM.retype_mem(), com.cliffc.aa.node.ScopeNode.set_mem(), com.cliffc.aa.node.TestNode.set_type(), com.cliffc.aa.node.Node.sharptr(), com.cliffc.aa.node.Node.should_con(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.node.FunNode.split_size(), com.cliffc.aa.node.RetNode.tail_recursive(), com.cliffc.aa.Parse.term(), com.cliffc.aa.node.TestNode.test1jig(), com.cliffc.aa.node.TestNode.test1monotonic_init(), com.cliffc.aa.TestLive.testBasic(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.TestLive.testNewObj(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.node.TestNodeSmall.testUnresolvedAdd(), com.cliffc.aa.Parse.tstmt(), com.cliffc.aa.Parse.type0(), com.cliffc.aa.Parse.typechk(), com.cliffc.aa.node.NewObjNode.update(), com.cliffc.aa.node.Node.val(), com.cliffc.aa.node.DefMemNode.value(), com.cliffc.aa.node.MProjNode.value(), com.cliffc.aa.node.MemSplitNode.value(), com.cliffc.aa.node.UnresolvedNode.value(), com.cliffc.aa.node.MrgProjNode.value(), com.cliffc.aa.node.AssertNode.value(), com.cliffc.aa.node.IntrinsicNode.value(), com.cliffc.aa.node.StoreNode.value(), com.cliffc.aa.node.FunPtrNode.value(), com.cliffc.aa.node.RetNode.value(), com.cliffc.aa.node.LoadNode.value(), com.cliffc.aa.node.CallEpiNode.value(), com.cliffc.aa.node.CallNode.value(), com.cliffc.aa.node.Node.walk_initype(), com.cliffc.aa.node.Node.walk_opt(), com.cliffc.aa.node.Node.walkerr_def(), com.cliffc.aa.node.CallEpiNode.wire0(), and com.cliffc.aa.node.Node.xval().
CNT
int com.cliffc.aa.node.Node.CNT =1 static private inherited
Definition at line 59 of file Node.java.
Referenced by com.cliffc.aa.node.Node.init0(), com.cliffc.aa.node.Node.newuid(), com.cliffc.aa.node.Node.reset_to_init0(), and com.cliffc.aa.node.Node.roll_back_CNT().
FLOW_VISIT
final VBitSet com.cliffc.aa.node.Node.FLOW_VISIT = new VBitSet() static private inherited
Definition at line 746 of file Node.java.
Referenced by com.cliffc.aa.node.Node.more_flow().
LIVE
final VBitSet com.cliffc.aa.node.Node.LIVE = new VBitSet() static private inherited
Definition at line 60 of file Node.java.
Referenced by com.cliffc.aa.node.Node.init0(), com.cliffc.aa.node.Node.kill(), com.cliffc.aa.node.Node.newuid(), com.cliffc.aa.node.Node.reset_to_init0(), and com.cliffc.aa.node.Node.roll_back_CNT().
OP_CALL
final byte com.cliffc.aa.node.Node.OP_CALL = 1 static package inherited
Definition at line 17 of file Node.java.
Referenced by com.cliffc.aa.node.FunNode.bad_mem_use(), com.cliffc.aa.node.CallNode.CallNode(), com.cliffc.aa.node.Node.is_CFG(), com.cliffc.aa.node.Node.is_multi_head(), com.cliffc.aa.node.Node.postorder(), com.cliffc.aa.node.FunNode.split_size(), and com.cliffc.aa.node.FunNode.unwire().
OP_CALLEPI
final byte com.cliffc.aa.node.Node.OP_CALLEPI = 2 static package inherited
Definition at line 18 of file Node.java.
Referenced by com.cliffc.aa.node.CallEpiNode.CallEpiNode(), com.cliffc.aa.node.Node.is_CFG(), com.cliffc.aa.node.Node.is_multi_head(), and com.cliffc.aa.node.RetNode.tail_recursive().
OP_CAST
final byte com.cliffc.aa.node.Node.OP_CAST = 3 static package inherited
Definition at line 19 of file Node.java.
Referenced by com.cliffc.aa.node.FunNode.bad_mem_use(), and com.cliffc.aa.node.CastNode.CastNode().
OP_CON
final byte com.cliffc.aa.node.Node.OP_CON = 4 static package inherited
Definition at line 20 of file Node.java.
Referenced by com.cliffc.aa.node.ConNode< T extends Type >.ConNode().
OP_CONTYPE
final byte com.cliffc.aa.node.Node.OP_CONTYPE = 5 static package inherited
Definition at line 21 of file Node.java.
Referenced by com.cliffc.aa.node.ConTypeNode.ConTypeNode().
OP_CPROJ
final byte com.cliffc.aa.node.Node.OP_CPROJ = 6 static package inherited
Definition at line 22 of file Node.java.
Referenced by com.cliffc.aa.node.CProjNode.CProjNode(), com.cliffc.aa.node.Node.is_CFG(), com.cliffc.aa.node.Node.is_multi_tail(), com.cliffc.aa.node.Node.postorder(), and com.cliffc.aa.node.RetNode.tail_recursive().
OP_DEFMEM
final byte com.cliffc.aa.node.Node.OP_DEFMEM = 7 static package inherited
Definition at line 23 of file Node.java.
Referenced by com.cliffc.aa.node.DefMemNode.DefMemNode(), and com.cliffc.aa.node.FunNode.find_body().
OP_ERR
final byte com.cliffc.aa.node.Node.OP_ERR = 8 static package inherited
Definition at line 24 of file Node.java.
Referenced by com.cliffc.aa.node.ErrNode.ErrNode().
OP_FP2DISP
final byte com.cliffc.aa.node.Node.OP_FP2DISP =10 static package inherited
Definition at line 26 of file Node.java.
Referenced by com.cliffc.aa.node.FP2DispNode.FP2DispNode().
OP_FRESH
final byte com.cliffc.aa.node.Node.OP_FRESH = 9 static package inherited
Definition at line 25 of file Node.java.
Referenced by com.cliffc.aa.node.FunNode.bad_mem_use(), and com.cliffc.aa.node.FreshNode.FreshNode().
OP_FUN
final byte com.cliffc.aa.node.Node.OP_FUN =11 static package inherited
Definition at line 27 of file Node.java.
Referenced by com.cliffc.aa.node.Node.dumprpo(), com.cliffc.aa.node.FunNode.find_body(), com.cliffc.aa.node.FunNode.FunNode(), com.cliffc.aa.node.Node.is_CFG(), com.cliffc.aa.node.Node.is_multi_head(), and com.cliffc.aa.node.FunNode.split_size().
OP_FUNPTR
final byte com.cliffc.aa.node.Node.OP_FUNPTR =12 static package inherited
Definition at line 28 of file Node.java.
Referenced by com.cliffc.aa.node.FunPtrNode.FunPtrNode(), and com.cliffc.aa.node.RetNode.tail_recursive().
OP_IF
final byte com.cliffc.aa.node.Node.OP_IF =13 static package inherited
Definition at line 29 of file Node.java.
Referenced by com.cliffc.aa.node.FunNode.bad_mem_use(), com.cliffc.aa.node.IfNode.IfNode(), com.cliffc.aa.node.Node.is_CFG(), com.cliffc.aa.node.Node.is_multi_head(), and com.cliffc.aa.node.FunNode.split_size().
OP_JOIN
final byte com.cliffc.aa.node.Node.OP_JOIN =14 static package inherited
Definition at line 30 of file Node.java.
Referenced by com.cliffc.aa.node.MemJoinNode.MemJoinNode().
OP_LOAD
final byte com.cliffc.aa.node.Node.OP_LOAD =15 static package inherited
Definition at line 31 of file Node.java.
Referenced by com.cliffc.aa.node.FunNode.bad_mem_use(), com.cliffc.aa.node.LoadNode.LoadNode(), and com.cliffc.aa.node.FunNode.split_size().
OP_LOOP
final byte com.cliffc.aa.node.Node.OP_LOOP =16 static package inherited
Definition at line 32 of file Node.java.
Referenced by com.cliffc.aa.node.LoadNode.ideal_grow(), com.cliffc.aa.node.Node.is_CFG(), com.cliffc.aa.node.Node.is_multi_head(), and com.cliffc.aa.node.LoopNode.LoopNode().
OP_MAX
final byte com.cliffc.aa.node.Node.OP_MAX =36 static package inherited
Definition at line 52 of file Node.java.
Referenced by com.cliffc.aa.node.FunNode.split_size().
OP_NAME
final byte com.cliffc.aa.node.Node.OP_NAME =17 static package inherited
Definition at line 33 of file Node.java.
Referenced by com.cliffc.aa.node.FunNode.bad_mem_use(), and com.cliffc.aa.node.IntrinsicNode.IntrinsicNode().
OP_NEWARY
final byte com.cliffc.aa.node.Node.OP_NEWARY =19 static package inherited
Definition at line 35 of file Node.java.
OP_NEWOBJ
final byte com.cliffc.aa.node.Node.OP_NEWOBJ =18 static package inherited
Definition at line 34 of file Node.java.
Referenced by com.cliffc.aa.node.FunNode.bad_mem_use(), com.cliffc.aa.node.Node.is_multi_head(), and com.cliffc.aa.node.FunNode.split_size().
OP_NEWSTR
final byte com.cliffc.aa.node.Node.OP_NEWSTR =20 static package inherited
Definition at line 36 of file Node.java.
Referenced by com.cliffc.aa.node.FunNode.bad_mem_use(), and com.cliffc.aa.node.Node.is_multi_head().
OP_PARM
final byte com.cliffc.aa.node.Node.OP_PARM =21 static package inherited
Definition at line 37 of file Node.java.
Referenced by com.cliffc.aa.node.FunNode.find_body(), com.cliffc.aa.node.Node.is_multi_tail(), and com.cliffc.aa.node.ParmNode.ParmNode().
OP_PHI
final byte com.cliffc.aa.node.Node.OP_PHI =22 static package inherited
Definition at line 38 of file Node.java.
Referenced by com.cliffc.aa.node.LoadNode.ideal_grow(), com.cliffc.aa.node.Node.is_multi_tail(), com.cliffc.aa.node.PhiNode.PhiNode(), com.cliffc.aa.node.RegionNode.stacked_region(), and com.cliffc.aa.node.RetNode.tail_recursive().
OP_PRIM
final byte com.cliffc.aa.node.Node.OP_PRIM =23 static package inherited
Definition at line 39 of file Node.java.
Referenced by com.cliffc.aa.node.FunNode.bad_mem_use(), com.cliffc.aa.node.PrimNode.PrimNode(), and com.cliffc.aa.node.FunNode.split_size().
OP_PROJ
final byte com.cliffc.aa.node.Node.OP_PROJ =24 static package inherited
Definition at line 40 of file Node.java.
Referenced by com.cliffc.aa.node.Node.is_multi_tail(), and com.cliffc.aa.node.ProjNode.ProjNode().
OP_REGION
final byte com.cliffc.aa.node.Node.OP_REGION =25 static package inherited
Definition at line 41 of file Node.java.
Referenced by com.cliffc.aa.node.RegionNode.add_flow_def_extra(), com.cliffc.aa.node.Node.is_CFG(), com.cliffc.aa.node.Node.is_multi_head(), com.cliffc.aa.node.RegionNode.RegionNode(), com.cliffc.aa.node.FunNode.split_size(), com.cliffc.aa.node.RegionNode.stacked_region(), and com.cliffc.aa.node.RetNode.tail_recursive().
OP_RET
final byte com.cliffc.aa.node.Node.OP_RET =26 static package inherited
Definition at line 42 of file Node.java.
Referenced by com.cliffc.aa.node.FunNode.bad_mem_use(), com.cliffc.aa.node.Node.dumprpo(), com.cliffc.aa.node.FunNode.find_body(), com.cliffc.aa.node.Node.is_CFG(), com.cliffc.aa.node.Node.postorder(), com.cliffc.aa.node.RetNode.RetNode(), and com.cliffc.aa.node.FunNode.split_size().
OP_SCOPE
final byte com.cliffc.aa.node.Node.OP_SCOPE =27 static package inherited
Definition at line 43 of file Node.java.
Referenced by com.cliffc.aa.node.Node.is_CFG(), com.cliffc.aa.node.ScopeNode.ScopeNode(), and com.cliffc.aa.node.FunNode.split_size().
OP_SPLIT
final byte com.cliffc.aa.node.Node.OP_SPLIT =28 static package inherited
Definition at line 44 of file Node.java.
Referenced by com.cliffc.aa.node.Node.is_multi_head(), com.cliffc.aa.node.MemSplitNode.MemSplitNode(), and com.cliffc.aa.node.Node.postorder().
OP_START
final byte com.cliffc.aa.node.Node.OP_START =29 static package inherited
Definition at line 45 of file Node.java.
Referenced by com.cliffc.aa.node.Node.is_CFG(), com.cliffc.aa.node.Node.is_multi_head(), and com.cliffc.aa.node.StartNode.StartNode().
OP_STMEM
final byte com.cliffc.aa.node.Node.OP_STMEM =30 static package inherited
Definition at line 46 of file Node.java.
Referenced by com.cliffc.aa.node.StartMemNode.StartMemNode().
OP_STORE
final byte com.cliffc.aa.node.Node.OP_STORE =31 static package inherited
Definition at line 47 of file Node.java.
Referenced by com.cliffc.aa.node.FunNode.bad_mem_use(), com.cliffc.aa.node.FunNode.split_size(), and com.cliffc.aa.node.StoreNode.StoreNode().
OP_THRET
final byte com.cliffc.aa.node.Node.OP_THRET =32 static package inherited
Definition at line 48 of file Node.java.
Referenced by com.cliffc.aa.node.ThretNode.ThretNode().
OP_THUNK
final byte com.cliffc.aa.node.Node.OP_THUNK =33 static package inherited
Definition at line 49 of file Node.java.
Referenced by com.cliffc.aa.node.ThunkNode.ThunkNode().
OP_TYPE
final byte com.cliffc.aa.node.Node.OP_TYPE =34 static package inherited
Definition at line 50 of file Node.java.
Referenced by com.cliffc.aa.node.AssertNode.AssertNode().
OP_UNR
final byte com.cliffc.aa.node.Node.OP_UNR =35 static package inherited
Definition at line 51 of file Node.java.
Referenced by com.cliffc.aa.node.UnresolvedNode.UnresolvedNode().
STRS
final String [] com.cliffc.aa.node.Node.STRS = new String[] { null, "Call", "CallEpi", "Cast", "Con", "ConType", "CProj", "DefMem", "Err", "Fresh", "FP2Disp", "Fun", "FunPtr", "If", "Join", "Load", "Loop", "Name", "NewObj", "NewAry", "NewStr", "Parm", "Phi", "Prim", "Proj", "Region", "Return", "Scope","Split", "Start", "StartMem", "Store", "Thret", "Thunk", "Type", "Unresolved" } static private inherited
Definition at line 54 of file Node.java.
Referenced by com.cliffc.aa.node.Node.xstr().
VALS
final ConcurrentHashMap<Node,Node> com.cliffc.aa.node.Node.VALS = new ConcurrentHashMap<>() static inherited
Definition at line 537 of file Node.java.
Referenced by com.cliffc.aa.node.Node._do_reduce(), com.cliffc.aa.node.Node._elock(), com.cliffc.aa.node.Node.check_vals(), com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.Node.init1(), com.cliffc.aa.node.Node.kill(), com.cliffc.aa.node.Node.reset_to_init0(), and com.cliffc.aa.node.Node.unelock().
The documentation for this class was generated from the following file:
CallEpiNode.java