aa: com.cliffc.aa.HM.HM4.Lambda2 Class Reference
com.cliffc.aa.HM.HM4.Lambda2 Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Lambda2 (String arg0, String arg1, Syntax body)
T2 find ()
T2 hm (Ary< Syntax > work)
void live (IBitSet visit)
boolean more_work (Ary< Syntax > work)
final boolean more_work_impl (Ary< Syntax > work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_tree (Syntax par, Ary< Syntax > work)
void prep_tree_impl (Syntax par, T2 t, Ary< Syntax > work)
T2 prep_tree_lookup (String name, Syntax prior)
SB str (SB sb)
T2 targ0 ()
T2 targ1 ()
Package Attributes
final String _arg0
final String _arg1
final Syntax _body
Syntax _par
T2 _t
T2 _targ0
T2 _targ1
Detailed Description
Definition at line 189 of file HM4.java.
Constructor & Destructor Documentation
Lambda2()
com.cliffc.aa.HM.HM4.Lambda2.Lambda2 (String arg0, String arg1, Syntax body) package
Definition at line 194 of file HM4.java.
 { _arg0=arg0; _arg1 = arg1; _body=body; _targ0 = T2.tnew(); _targ1 = T2.tnew(); }
References com.cliffc.aa.HM.HM4.Lambda2._arg0, com.cliffc.aa.HM.HM4.Lambda2._arg1, com.cliffc.aa.HM.HM4.Lambda2._body, com.cliffc.aa.HM.HM4.Lambda2._targ0, com.cliffc.aa.HM.HM4.Lambda2._targ1, and com.cliffc.aa.HM.HM4.T2.tnew().
Member Function Documentation
find()
T2 com.cliffc.aa.HM.HM4.Syntax.find () package inherited
Definition at line 77 of file HM4.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM4.Syntax._t, and com.cliffc.aa.HM.HM4.T2.find().
Referenced by com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Con.hm(), com.cliffc.aa.HM.HM4.Ident.hm(), com.cliffc.aa.HM.HM4.Lambda.hm(), com.cliffc.aa.HM.HM4.Lambda2.hm(), com.cliffc.aa.HM.HM4.Let.hm(), com.cliffc.aa.HM.HM4.Apply.hm(), and com.cliffc.aa.HM.HM4.Syntax.more_work_impl().
hm()
T2 com.cliffc.aa.HM.HM4.Lambda2.hm (Ary< Syntax > work) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 200 of file HM4.java.
{
       // The normal lambda work
       T2 fun = T2.fun(targ0(),targ1(),_body.find());
       // Force forwards progress; an Apply may already have lifted _t to
       // something better than just a plain fun wrapper.
       return find().unify(fun,work);
     }
References com.cliffc.aa.HM.HM4.Lambda2._body, com.cliffc.aa.HM.HM4.Syntax.find(), com.cliffc.aa.HM.HM4.T2.fun(), com.cliffc.aa.HM.HM4.Lambda2.targ0(), com.cliffc.aa.HM.HM4.Lambda2.targ1(), and com.cliffc.aa.HM.HM4.T2.unify().
live()
void com.cliffc.aa.HM.HM4.Lambda2.live (IBitSet visit) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 221 of file HM4.java.
{
       if( _t!=null ) _t.live(visit);
       _targ0.live(visit);
       _targ1.live(visit);
       _body .live(visit);
     }
References com.cliffc.aa.HM.HM4.Lambda2._body, com.cliffc.aa.HM.HM4.Syntax._t, com.cliffc.aa.HM.HM4.Lambda2._targ0, com.cliffc.aa.HM.HM4.Lambda2._targ1, com.cliffc.aa.HM.HM4.Syntax.live(), and com.cliffc.aa.HM.HM4.T2.live().
more_work()
boolean com.cliffc.aa.HM.HM4.Lambda2.more_work (Ary< Syntax > work) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 217 of file HM4.java.
{
       if( !more_work_impl(work) ) return false;
       return _body.more_work(work);
     }
References com.cliffc.aa.HM.HM4.Lambda2._body, com.cliffc.aa.HM.HM4.Syntax.more_work(), and com.cliffc.aa.HM.HM4.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM4.Syntax.more_work_impl (Ary< Syntax > work) package inherited
Definition at line 91 of file HM4.java.
{
       if( work.find(this)!=-1 ) return true; // On worklist, so ok
       // Check does not make progress
       int old = T2.CNT;  int olen = work._len;
       boolean more_work;
       try {
         T2 t = find();
         Type con = t._con;
         T2 hm = hm(null);       // Run H-M, with null work, looking for progress
         T2 un = find().unify(hm,null);
         more_work = t!=un || con!=un._con || work._len!=olen; // Something happened?
         assert !more_work;
       } catch( RuntimeException no_unify ) { more_work=true; } // Fail to unify assert is progress
       if( !more_work ) T2.CNT=old;  // Reset if no error; prevents assert from endlessly raising CNT
       return !more_work;
     }
References com.cliffc.aa.HM.HM4.T2._con, com.cliffc.aa.util.Ary< E >._len, com.cliffc.aa.HM.HM4.T2.CNT, com.cliffc.aa.HM.HM4.Syntax.find(), com.cliffc.aa.util.Ary< E >.find(), com.cliffc.aa.HM.HM4.Syntax.hm(), com.cliffc.aa.HM.HM4.Syntax.more_work(), and com.cliffc.aa.HM.HM4.T2.unify().
Referenced by com.cliffc.aa.HM.HM4.Con.more_work(), com.cliffc.aa.HM.HM4.Ident.more_work(), com.cliffc.aa.HM.HM4.Lambda.more_work(), com.cliffc.aa.HM.HM4.Lambda2.more_work(), com.cliffc.aa.HM.HM4.Let.more_work(), and com.cliffc.aa.HM.HM4.Apply.more_work().
p()
String com.cliffc.aa.HM.HM4.Syntax.p () inherited
Definition at line 111 of file HM4.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM4.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM4.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 112 of file HM4.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM4.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM4.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM4.Syntax.p1(), com.cliffc.aa.HM.HM4.Syntax.p2(), and com.cliffc.aa.HM.HM4.T2.str().
Referenced by com.cliffc.aa.HM.HM4.Syntax.p(), com.cliffc.aa.HM.HM4.Lambda.p2(), com.cliffc.aa.HM.HM4.Lambda2.p2(), com.cliffc.aa.HM.HM4.Let.p2(), and com.cliffc.aa.HM.HM4.Apply.p2().
p1()
SB com.cliffc.aa.HM.HM4.Lambda2.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 196 of file HM4.java.
 { return sb.p("{ ").p(_arg0).p(" ").p(_arg1).p(" -> ... } "); }
References com.cliffc.aa.HM.HM4.Lambda2._arg0, com.cliffc.aa.HM.HM4.Lambda2._arg1, and com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM4.Lambda2.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 197 of file HM4.java.
 { return _body.p0(sb,dups); }
References com.cliffc.aa.HM.HM4.Lambda2._body, and com.cliffc.aa.HM.HM4.Syntax.p0().
prep_tree()
void com.cliffc.aa.HM.HM4.Lambda2.prep_tree (Syntax par, Ary< Syntax > work) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 207 of file HM4.java.
{
       prep_tree_impl(par,T2.tnew(),work);
       _body.prep_tree(this,work);
     }
References com.cliffc.aa.HM.HM4.Lambda2._body, com.cliffc.aa.HM.HM4.Syntax.prep_tree(), com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM4.T2.tnew().
prep_tree_impl()
void com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl (Syntax par, T2 t, Ary< Syntax > work) package inherited
Definition at line 86 of file HM4.java.
 { _par=par; _t=t; work.push(this); }
References com.cliffc.aa.HM.HM4.Syntax._par, com.cliffc.aa.HM.HM4.Syntax._t, and com.cliffc.aa.util.Ary< E >.push().
Referenced by com.cliffc.aa.HM.HM4.Con.prep_tree(), com.cliffc.aa.HM.HM4.Ident.prep_tree(), com.cliffc.aa.HM.HM4.Lambda.prep_tree(), com.cliffc.aa.HM.HM4.Lambda2.prep_tree(), com.cliffc.aa.HM.HM4.Let.prep_tree(), and com.cliffc.aa.HM.HM4.Apply.prep_tree().
prep_tree_lookup()
T2 com.cliffc.aa.HM.HM4.Lambda2.prep_tree_lookup (String name, Syntax prior) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 212 of file HM4.java.
{
       if( Util.eq(_arg0,name) ) return _targ0;
       if( Util.eq(_arg1,name) ) return _targ1;
       return null;
     }
References com.cliffc.aa.HM.HM4.Lambda2._arg0, com.cliffc.aa.HM.HM4.Lambda2._arg1, com.cliffc.aa.HM.HM4.Lambda2._targ0, com.cliffc.aa.HM.HM4.Lambda2._targ1, and com.cliffc.aa.util.Util.eq().
str()
SB com.cliffc.aa.HM.HM4.Lambda2.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 195 of file HM4.java.
 { return _body.str(sb.p("{ ").p(_arg0).p(" ").p(_arg1).p(" -> ")).p(" }"); }
References com.cliffc.aa.HM.HM4.Lambda2._arg0, com.cliffc.aa.HM.HM4.Lambda2._arg1, com.cliffc.aa.HM.HM4.Lambda2._body, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM4.Syntax.str().
targ0()
T2 com.cliffc.aa.HM.HM4.Lambda2.targ0 () package
Definition at line 198 of file HM4.java.
 { T2 targ = _targ0.find(); return targ==_targ0 ? targ : (_targ0=targ); }
References com.cliffc.aa.HM.HM4.Lambda2._targ0, and com.cliffc.aa.HM.HM4.T2.find().
Referenced by com.cliffc.aa.HM.HM4.Lambda2.hm().
targ1()
T2 com.cliffc.aa.HM.HM4.Lambda2.targ1 () package
Definition at line 199 of file HM4.java.
 { T2 targ = _targ1.find(); return targ==_targ1 ? targ : (_targ1=targ); }
References com.cliffc.aa.HM.HM4.Lambda2._targ1, and com.cliffc.aa.HM.HM4.T2.find().
Referenced by com.cliffc.aa.HM.HM4.Lambda2.hm().
toString()
final String com.cliffc.aa.HM.HM4.Syntax.toString () inherited
Definition at line 108 of file HM4.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM4.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_arg0
final String com.cliffc.aa.HM.HM4.Lambda2._arg0 package
Definition at line 190 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Lambda2.Lambda2(), com.cliffc.aa.HM.HM4.Lambda2.p1(), com.cliffc.aa.HM.HM4.Lambda2.prep_tree_lookup(), and com.cliffc.aa.HM.HM4.Lambda2.str().
_arg1
final String com.cliffc.aa.HM.HM4.Lambda2._arg1 package
Definition at line 190 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Lambda2.Lambda2(), com.cliffc.aa.HM.HM4.Lambda2.p1(), com.cliffc.aa.HM.HM4.Lambda2.prep_tree_lookup(), and com.cliffc.aa.HM.HM4.Lambda2.str().
_body
final Syntax com.cliffc.aa.HM.HM4.Lambda2._body package
Definition at line 191 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Lambda2.hm(), com.cliffc.aa.HM.HM4.Lambda2.Lambda2(), com.cliffc.aa.HM.HM4.Lambda2.live(), com.cliffc.aa.HM.HM4.Lambda2.more_work(), com.cliffc.aa.HM.HM4.Lambda2.p2(), com.cliffc.aa.HM.HM4.Lambda2.prep_tree(), and com.cliffc.aa.HM.HM4.Lambda2.str().
_par
Syntax com.cliffc.aa.HM.HM4.Syntax._par package inherited
Definition at line 75 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Ident.prep_tree(), and com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM4.Syntax._t package inherited
Definition at line 76 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Syntax.find(), com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Con.live(), com.cliffc.aa.HM.HM4.Ident.live(), com.cliffc.aa.HM.HM4.Lambda.live(), com.cliffc.aa.HM.HM4.Lambda2.live(), com.cliffc.aa.HM.HM4.Let.live(), com.cliffc.aa.HM.HM4.Apply.live(), com.cliffc.aa.HM.HM4.Syntax.p0(), and com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl().
_targ0
T2 com.cliffc.aa.HM.HM4.Lambda2._targ0 package
Definition at line 192 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Lambda2.Lambda2(), com.cliffc.aa.HM.HM4.Lambda2.live(), com.cliffc.aa.HM.HM4.Lambda2.prep_tree_lookup(), and com.cliffc.aa.HM.HM4.Lambda2.targ0().
_targ1
T2 com.cliffc.aa.HM.HM4.Lambda2._targ1 package
Definition at line 193 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Lambda2.Lambda2(), com.cliffc.aa.HM.HM4.Lambda2.live(), com.cliffc.aa.HM.HM4.Lambda2.prep_tree_lookup(), and com.cliffc.aa.HM.HM4.Lambda2.targ1().
The documentation for this class was generated from the following file:
HM4.java