aa: com.cliffc.aa.HM.TestHM8 Class Reference
com.cliffc.aa.HM.TestHM8 Class Reference
Public Member Functions
void reset ()
void test00 ()
void test01 ()
void test02 ()
void test03 ()
void test04 ()
void test05 ()
void test05a ()
void test06 ()
void test07 ()
void test08 ()
void test09 ()
void test10 ()
void test11 ()
void test12 ()
void test13 ()
void test14 ()
void test15 ()
void test16 ()
void test17 ()
void test18 ()
void test19 ()
void test20 ()
void test21 ()
void test22 ()
void test23 ()
void test24 ()
void test25 ()
void test25a ()
void test25b ()
void test26 ()
void test27 ()
void test28 ()
void test29 ()
void test30 ()
void test30a ()
void test31 ()
void test32 ()
void test33 ()
void test34 ()
void test35 ()
void test36 ()
Detailed Description
Definition at line 9 of file TestHM8.java.
Member Function Documentation
reset()
void com.cliffc.aa.HM.TestHM8.reset ()
Definition at line 11 of file TestHM8.java.
 { HM8.reset(); }
References com.cliffc.aa.HM.HM8.reset().
test00()
void com.cliffc.aa.HM.TestHM8.test00 ()
Definition at line 14 of file TestHM8.java.
{
     HM8.hm("fred");
   }
References com.cliffc.aa.HM.HM8.hm().
test01()
void com.cliffc.aa.HM.TestHM8.test01 ()
Definition at line 19 of file TestHM8.java.
{
     Syntax syn = HM8.hm("3");
     assertEquals("3",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test02()
void com.cliffc.aa.HM.TestHM8.test02 ()
Definition at line 26 of file TestHM8.java.
{
     Syntax syn = HM8.hm("(pair1 3)");
     assertEquals("{ A -> (pair 3 A) }",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test03()
void com.cliffc.aa.HM.TestHM8.test03 ()
Definition at line 33 of file TestHM8.java.
{
     Syntax syn = HM8.hm("{ z -> (pair (z 3) (z \"abc\")) }");
     assertEquals("{ { all -> A } -> (pair A A) }",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test04()
void com.cliffc.aa.HM.TestHM8.test04 ()
Definition at line 40 of file TestHM8.java.
{
     Syntax syn = HM8.hm("fact = { n -> (if (?0 n) 1 (* n (fact (dec n))))}; fact");
     assertEquals("{ int64 -> int64 }",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test05()
void com.cliffc.aa.HM.TestHM8.test05 ()
Definition at line 54 of file TestHM8.java.
{
     // Because {y->y} is passed in, all 'y' types must agree.
     // This unifies 3 and "abc" which results in 'all'
     Syntax syn = HM8.hm("({ x -> (pair (x 3) (x \"abc\")) } {y->y})");
     assertEquals("(pair all all)",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test05a()
void com.cliffc.aa.HM.TestHM8.test05a ()
Definition at line 47 of file TestHM8.java.
{
     Syntax syn = HM8.hm("id={x->x}; (pair (id 3) (id \"abc\"))");
     assertEquals("(pair 3 \"abc\")",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test06()
void com.cliffc.aa.HM.TestHM8.test06 ()
Definition at line 63 of file TestHM8.java.
{
     // recursive unification
     Syntax syn = HM8.hm("{ f -> (f f) }");
     assertEquals("{ A:{ $A -> B } -> B }",syn._t.p());
     assertEquals("[]",syn._post.p());
     // We can argue the pretty-print should print:
     // "A:{ $A -> B }"
   }
References com.cliffc.aa.HM.HM8.hm().
test07()
void com.cliffc.aa.HM.TestHM8.test07 ()
Definition at line 73 of file TestHM8.java.
{
     Syntax syn = HM8.hm("g = {f -> 5}; (g g)");
     assertEquals("5",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test08()
void com.cliffc.aa.HM.TestHM8.test08 ()
Definition at line 80 of file TestHM8.java.
{
     // example that demonstrates generic and non-generic variables:
     Syntax syn = HM8.hm("{ g -> f = { x -> g }; (pair (f 3) (f \"abc\"))}");
     assertEquals("{ A -> (pair A A) }",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test09()
void com.cliffc.aa.HM.TestHM8.test09 ()
Definition at line 88 of file TestHM8.java.
{
     Syntax syn = HM8.hm("{ f g -> (f g)}");
     assertEquals("{ { A -> B } A -> B }",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test10()
void com.cliffc.aa.HM.TestHM8.test10 ()
Definition at line 95 of file TestHM8.java.
{
     // Function composition
     Syntax syn = HM8.hm("{ f g -> { arg -> (g (f arg))} }");
     assertEquals("{ { A -> B } { B -> C } -> { A -> C } }",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test11()
void com.cliffc.aa.HM.TestHM8.test11 ()
Definition at line 103 of file TestHM8.java.
{
     // Stacked functions ignoring all function arguments
     Syntax syn = HM8.hm("map = { fun -> { x -> 2 } }; ((map 3) 5)");
     assertEquals("2",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test12()
void com.cliffc.aa.HM.TestHM8.test12 ()
Definition at line 111 of file TestHM8.java.
{
     // map takes a function and an element (collection?) and applies it (applies to collection?)
     Syntax syn = HM8.hm("map = { fun -> { x -> (fun x)}}; { p -> 5 }");
     assertEquals("{ A -> 5 }",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test13()
void com.cliffc.aa.HM.TestHM8.test13 ()
Definition at line 119 of file TestHM8.java.
{
     // Looking at when tvars are duplicated ("fresh" copies made).
     // This is the "map" problem with a scalar instead of a collection.
     // Takes a '{a->b}' and a 'a' for a couple of different prims.
     Syntax syn = HM8.hm("map = { fun -> { x -> (fun x)}};"+
                   "(pair ((map str) 5) ((map factor) 2.3))");
     assertEquals("(pair str (divmod flt64 flt64))",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test14()
void com.cliffc.aa.HM.TestHM8.test14 ()
Definition at line 130 of file TestHM8.java.
{
     // map takes a function and an element (collection?) and applies it (applies to collection?)
     Syntax syn = HM8.hm("map = { fun x -> (fun x)}; (map {a->3} 5)");
     assertEquals("3",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test15()
void com.cliffc.aa.HM.TestHM8.test15 ()
Definition at line 138 of file TestHM8.java.
{
     // map takes a function and an element (collection?) and applies it (applies to collection?)
     Syntax syn = HM8.hm("map = { fun x -> (fun x)}; (map { a-> (pair a a)} 5)");
     assertEquals("(pair 5 5)",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test16()
void com.cliffc.aa.HM.TestHM8.test16 ()
Definition at line 146 of file TestHM8.java.
{
     Syntax syn = HM8.hm("fcn = { p -> { a -> (pair a a) }};"+
                   "map = { fun x -> (fun x)};"+
                   "{ q -> (map (fcn q) 5)}");
     assertEquals("{ A -> (pair 5 5) }",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test17()
void com.cliffc.aa.HM.TestHM8.test17 ()
Definition at line 155 of file TestHM8.java.
{
     // Checking behavior when using "if" to merge two functions with
     // sufficiently different signatures, then attempting to pass them to a map
     // & calling internally.
     // fcn takes a predicate 'p' and returns one of two fcns.
     //   let fcn = { p -> (if p {a -> pair[a,a        ]}
     //                               {b -> pair[b,pair[3,b]]}) } in
     // map takes a function and an element (collection?) and applies it (applies to collection?)
     //   let map = { fun x -> (fun x) }
     //          in { q -> ((map (fcn q)) 5) }
     // Should return { q -> q ? [5,5] : [5,[3,5]] }
     // Ultimately, unifies "a" with "pair[3,a]" which throws recursive unification.
     Syntax syn = HM8.hm("fcn = {p -> (if p {a -> (pair a a)} {b -> (pair b (pair 3 b))})};"+
                   "map = { fun x -> (fun x)};"+
                   "{ q -> (map (fcn q) 5)}");
     assertEquals("{ A -> (pair Cannot unify $V123:(pair 3 $V123) and 5 Cannot unify $V123:(pair 3 $V123) and 5) }",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test18()
void com.cliffc.aa.HM.TestHM8.test18 ()
Definition at line 175 of file TestHM8.java.
{
     Syntax syn = HM8.hm("cons ={x y-> {cadr -> (cadr x y)}};"+
                   "cdr ={mycons -> (mycons { p q -> q})};"+
                   "(cdr (cons 2 3))");
     assertEquals("3",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test19()
void com.cliffc.aa.HM.TestHM8.test19 ()
Definition at line 191 of file TestHM8.java.
{
     Syntax syn = HM8.hm("cons ={x y-> {cadr -> (cadr x y)}};"+
                   "cdr ={mycons -> (mycons { p q -> q})};"+
                   "map ={fun parg -> (fun (cdr parg))};"+
                   "(pair (map str (cons 0 5)) (map isempty (cons 0 \"abc\")))"
                   );
     assertEquals("(pair str int1)",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test20()
void com.cliffc.aa.HM.TestHM8.test20 ()
Definition at line 203 of file TestHM8.java.
{
     Syntax syn = HM8.hm("f0 = { f x -> (if (?0 x) 1 (f (f0 f (dec x)) 2))}; (f0 * 99)");
     assertEquals("int64",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test21()
void com.cliffc.aa.HM.TestHM8.test21 ()
Definition at line 211 of file TestHM8.java.
{
     // let f0 = fn f x => (if (?0 x) 1 (* (f0 f (dec x)) 2) ) in f0 f0 99
     // let f0 = fn f x => (if (?0 x) 1 (f (f0 f (dec x)) 2) ) in f0 *  99
     Syntax syn = HM8.hm("f0 = { f x -> (if (?0 x) 1 (* (f0 f (dec x)) 2))}; (f0 f0 99)");
     assertEquals("int64",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test22()
void com.cliffc.aa.HM.TestHM8.test22 ()
Definition at line 221 of file TestHM8.java.
{
     Syntax syn = HM8.hm("is_even = "+
                   "  is_odd = { n -> (if (?0 n) 0 (is_even (dec n)))}; "+
                   "     { n -> (if (?0 n) 1 (is_odd (dec n)))};"+
                   "(is_even 3)"
                   );
     assertEquals("int1",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test23()
void com.cliffc.aa.HM.TestHM8.test23 ()
Definition at line 233 of file TestHM8.java.
{
     Syntax syn = HM8.hm("{ g -> fgz = "+
                   "         cons = {x y -> {cadr -> (cadr x y)}};"+
                   "         cdr = {mycons -> (mycons { p q -> q})};"+
                   "         (cdr (cons 2 { z -> (g z) }));"+
                   "      (pair (fgz 3) (fgz 5))"+
                   "}"
                   );
     assertEquals("{ { nint8 -> A } -> (pair A A) }",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test24()
void com.cliffc.aa.HM.TestHM8.test24 ()
Definition at line 247 of file TestHM8.java.
{
     Syntax syn = HM8.hm("@{x=2, y=3}");
     assertEquals("*[7]@{ x = 2, y = 3}",syn._t.p());
     assertEquals("[  7:*[7]@{ x = 2, y = 3}]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test25()
void com.cliffc.aa.HM.TestHM8.test25 ()
Definition at line 255 of file TestHM8.java.
{
     Syntax syn = HM8.hm(".x @{x =2, y =3}");
     assertEquals("2",syn._t.p());
     assertEquals("[  7:*[7]@{ x = 2, y = 3}]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test25a()
void com.cliffc.aa.HM.TestHM8.test25a ()
Definition at line 263 of file TestHM8.java.
{
     Syntax syn = HM8.hm(".x 5");
     assertEquals("Cannot unify *[-2]@{ x = V24} and 5",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test25b()
void com.cliffc.aa.HM.TestHM8.test25b ()
Definition at line 271 of file TestHM8.java.
{
     Syntax syn = HM8.hm(".x @{ y =3}");
     assertEquals("Missing field x in *[7]@{ y = 3, x = all}",syn._t.p());
     assertEquals("[  7:*[7]@{ y = 3, x = Missing field x in *[7]@{ y = 3, x = all}}]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test26()
void com.cliffc.aa.HM.TestHM8.test26 ()
Definition at line 278 of file TestHM8.java.
{
     Syntax syn = HM8.hm("{ g -> @{x=g, y=g}}");
     assertEquals("{ A -> *[7]@{ x = A, y = A} }",syn._t.p());
     assertEquals("[  7:*[7]@{ x = A, y = A}]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test27()
void com.cliffc.aa.HM.TestHM8.test27 ()
Definition at line 285 of file TestHM8.java.
{
     // Load common field 'x', ignoring mismatched fields y and z
     Syntax syn = HM8.hm("{ pred -> .x (if pred @{x=2,y=3} @{x=3,z= \"abc\"}) }");
     assertEquals("{ A -> nint8 }",syn._t.p());
     assertEquals("[  7:A:*[7,8]@{ x = nint8, z = all, y = all}, 8:$A]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test28()
void com.cliffc.aa.HM.TestHM8.test28 ()
Definition at line 293 of file TestHM8.java.
{
     // Load some fields from an unknown struct: area of a square.
     // Since no nil-check, correctly types as needing a not-nil input.
     Syntax syn = HM8.hm("{ sq -> (* .x sq .y sq) }"); // { sq -> sq.x * sq.y }
     assertEquals("{ *[-2]@{ y = int64, x = int64} -> int64 }",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test29()
void com.cliffc.aa.HM.TestHM8.test29 ()
Definition at line 302 of file TestHM8.java.
{
     // Recursive linked-list discovery, with no end clause
     Syntax syn = HM8.hm("map = { fcn lst -> @{ n1 = (map fcn .n0 lst), v1 = (fcn .v0 lst) } }; map");
     assertEquals("{ { A -> B } C:*[-2]@{ v0 = A, n0 = $C} -> D:*[7]@{ n1 = $D, v1 = B} }",syn._t.p());
     assertEquals("[  7:A:*[7]@{ n1 = $A, v1 = B}]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test30()
void com.cliffc.aa.HM.TestHM8.test30 ()
Definition at line 310 of file TestHM8.java.
{
     // Recursive linked-list discovery, with nil.  Note that the output memory
     // has the output memory alias, but not the input memory alias (which must
     // be made before calling 'map').
     Syntax syn = HM8.hm("map = { fcn lst -> (if lst @{ n1=(map fcn .n0 lst), v1=(fcn .v0 lst) } nil) }; map");
     assertEquals("{ { A -> B } C:*[-2]@{ v0 = A, n0 = $C}? -> D:*[7]@{ n1 = $D, v1 = B}? }",syn._t.p());
     assertEquals("[  7:A:*[7]@{ n1 = $A, v1 = B}?]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test30a()
void com.cliffc.aa.HM.TestHM8.test30a ()
Definition at line 320 of file TestHM8.java.
{
     // Recursive linked-list discovery, with no end clause
     Syntax syn = HM8.hm("map = { fcn lst -> (if lst @{ n1 = (map fcn .n0 lst), v1 = (fcn .v0 lst) } nil) }; (map dec @{n0 = nil, v0 = 5})");
     assertEquals("A:*[7]@{ n1 = $A, v1 = int64}?",syn._t.p());
     assertEquals("[  7:A:*[7]@{ n1 = $A, v1 = B}?, 8:*[8]@{ n0 = (Nil), v0 = int64}?]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test31()
void com.cliffc.aa.HM.TestHM8.test31 ()
Definition at line 329 of file TestHM8.java.
{
     // Recursive linked-list discovery, with nil
     Syntax syn = HM8.hm("p0 = { x y z -> (triple x y z) };"+
                  "p1 = (triple p0 p0 p0);"+
                  "p2 = (triple p1 p1 p1);"+
                  "p3 = (triple p2 p2 p2);"+
                  "p3");
     assertEquals("(triple (triple (triple { A B C -> (triple A B C) } { D E F -> (triple D E F) } { G H I -> (triple G H I) }) (triple { J K L -> (triple J K L) } { M N O -> (triple M N O) } { P Q R -> (triple P Q R) }) (triple { S T U -> (triple S T U) } { V21 V22 V23 -> (triple V21 V22 V23) } { V24 V25 V26 -> (triple V24 V25 V26) })) (triple (triple { V27 V28 V29 -> (triple V27 V28 V29) } { V30 V31 V32 -> (triple V30 V31 V32) } { V33 V34 V35 -> (triple V33 V34 V35) }) (triple { V36 V37 V38 -> (triple V36 V37 V38) } { V39 V40 V41 -> (triple V39 V40 V41) } { V42 V43 V44 -> (triple V42 V43 V44) }) (triple { V45 V46 V47 -> (triple V45 V46 V47) } { V48 V49 V50 -> (triple V48 V49 V50) } { V51 V52 V53 -> (triple V51 V52 V53) })) (triple (triple { V54 V55 V56 -> (triple V54 V55 V56) } { V57 V58 V59 -> (triple V57 V58 V59) } { V60 V61 V62 -> (triple V60 V61 V62) }) (triple { V63 V64 V65 -> (triple V63 V64 V65) } { V66 V67 V68 -> (triple V66 V67 V68) } { V69 V70 V71 -> (triple V69 V70 V71) }) (triple { V72 V73 V74 -> (triple V72 V73 V74) } { V75 V76 V77 -> (triple V75 V76 V77) } { V78 V79 V80 -> (triple V78 V79 V80) })))",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test32()
void com.cliffc.aa.HM.TestHM8.test32 ()
Definition at line 343 of file TestHM8.java.
{
     // Recursive linked-list discovery, with nil.  Unrolled once.
     Syntax syn = HM8.hm("map = { lst -> (if lst @{ n1= arg= .n0 lst; (if arg @{ n1=(map .n0 arg), v1=(str .v0 arg)} nil), v1=(str .v0 lst) } nil) }; map");
     assertEquals("{ A:*[-2]@{ v0 = int64, n0 = *[-2]@{ n0 = $A, v0 = int64}?}? -> B:*[8]@{ n1 = *[7]@{ n1 = $B, v1 = str}?, v1 = str}? }",syn._t.p());
     assertEquals("[  7:A:*[7]@{ n1 = B:*[8]@{ n1 = $A, v1 = str}?, v1 = str}?, 8:$B]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test33()
void com.cliffc.aa.HM.TestHM8.test33 ()
Definition at line 351 of file TestHM8.java.
{
     Syntax syn = HM8.hm("x = { y -> (x (y y))}; x");
     assertEquals("{ A:{ $A -> $A } -> B }",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test34()
void com.cliffc.aa.HM.TestHM8.test34 ()
Definition at line 358 of file TestHM8.java.
{
     // Example from SimpleSub requiring 'x' to be both a struct with field
     // 'v', and also a function type - specifically disallowed in 'aa'.
     Syntax syn = HM8.hm("{ x -> y = ( x .v x ); 0}");
     assertEquals("{ Cannot unify *[-2]@{ v = V40} and { V40 -> V34 } -> 0 }",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test35()
void com.cliffc.aa.HM.TestHM8.test35 ()
Definition at line 367 of file TestHM8.java.
{
     Syntax syn = HM8.hm("x = { z -> z}; (x { y -> .u y})");
     assertEquals("{ *[-2]@{ u = A} -> A }",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
test36()
void com.cliffc.aa.HM.TestHM8.test36 ()
Definition at line 374 of file TestHM8.java.
{
     // Example from SimpleSub requiring 'x' to be both:
     // - a recursive self-call function from "w = (x x)": $V66:{ $V66 -> V67 } AND
     // - a function which takes a struct with field 'u'
     // The first arg to x is two different kinds of functions, so fails unification.
     Syntax syn = HM8.hm("x = w = (x x); { z -> z}; (x { y -> .u y})");
     assertEquals("Cannot unify $V66:{ $V66 -> V67 } and *[-2]@{ u = V39}",syn._t.p());
     assertEquals("[]",syn._post.p());
   }
References com.cliffc.aa.HM.HM8.hm().
The documentation for this class was generated from the following file:
TestHM8.java