aa: com.cliffc.aa.HM.HM4.Apply Class Reference
com.cliffc.aa.HM.HM4.Apply Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Apply (Syntax fun, Syntax... args)
T2 find ()
T2 hm (Ary< Syntax > work)
void live (IBitSet visit)
boolean more_work (Ary< Syntax > work)
final boolean more_work_impl (Ary< Syntax > work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_tree (Syntax par, Ary< Syntax > work)
void prep_tree_impl (Syntax par, T2 t, Ary< Syntax > work)
T2 prep_tree_lookup (String name, Syntax prior)
SB str (SB sb)
Package Attributes
final Syntax[] _args
final Syntax _fun
Syntax _par
T2 _t
Detailed Description
Definition at line 267 of file HM4.java.
Constructor & Destructor Documentation
Apply()
com.cliffc.aa.HM.HM4.Apply.Apply (Syntax fun, Syntax... args) package
Definition at line 270 of file HM4.java.
 { _fun = fun; _args = args; }
References com.cliffc.aa.HM.HM4.Apply._args, and com.cliffc.aa.HM.HM4.Apply._fun.
Member Function Documentation
find()
T2 com.cliffc.aa.HM.HM4.Syntax.find () package inherited
Definition at line 77 of file HM4.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM4.Syntax._t, and com.cliffc.aa.HM.HM4.T2.find().
Referenced by com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Con.hm(), com.cliffc.aa.HM.HM4.Ident.hm(), com.cliffc.aa.HM.HM4.Lambda.hm(), com.cliffc.aa.HM.HM4.Lambda2.hm(), com.cliffc.aa.HM.HM4.Let.hm(), com.cliffc.aa.HM.HM4.Apply.hm(), and com.cliffc.aa.HM.HM4.Syntax.more_work_impl().
hm()
T2 com.cliffc.aa.HM.HM4.Apply.hm (Ary< Syntax > work) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 284 of file HM4.java.
{
       T2 tfun = _fun.find();
       if( tfun.is_fresh() )
         tfun.get_fresh().push_update(this);
       T2[] targs = new T2[_args.length+1];
       for( int i=0; i<_args.length; i++ )
         targs[i] = _args[i].find();
       // if testing, allow progress on the last new result tvar....
       targs[_args.length] = Util.eq(tfun._name,"->") && work==null ? tfun.find(tfun._args.length-1) : T2.tnew(); // Return is new unconstrained T2
       T2 nfun = T2.fun(targs);
       T2 ufun = tfun.unify(nfun,work);
       if( _fun.find()!=tfun && work!=null ) work.push(_fun);
       // Return last element
       T2 trez = ufun.find(_args.length);
       // Force forward progress
       return trez.unify(find(),work);
     }
References com.cliffc.aa.HM.HM4.Apply._args, com.cliffc.aa.HM.HM4.T2._args, com.cliffc.aa.HM.HM4.Apply._fun, com.cliffc.aa.HM.HM4.T2._name, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM4.Syntax.find(), com.cliffc.aa.HM.HM4.T2.find(), com.cliffc.aa.HM.HM4.T2.fun(), com.cliffc.aa.HM.HM4.T2.get_fresh(), com.cliffc.aa.HM.HM4.T2.is_fresh(), com.cliffc.aa.util.Ary< E >.push(), com.cliffc.aa.HM.HM4.T2.push_update(), com.cliffc.aa.HM.HM4.T2.tnew(), and com.cliffc.aa.HM.HM4.T2.unify().
live()
void com.cliffc.aa.HM.HM4.Apply.live (IBitSet visit) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 312 of file HM4.java.
{
       if( _t!=null ) _t.live(visit);
       for( Syntax arg : _args ) arg.live(visit);
     }
References com.cliffc.aa.HM.HM4.Apply._args, com.cliffc.aa.HM.HM4.Syntax._t, and com.cliffc.aa.HM.HM4.T2.live().
more_work()
boolean com.cliffc.aa.HM.HM4.Apply.more_work (Ary< Syntax > work) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 306 of file HM4.java.
{
       if( !more_work_impl(work) ) return false;
       if( !_fun.more_work(work) ) return false;
       for( Syntax arg : _args ) if( !arg.more_work(work) ) return false;
       return true;
     }
References com.cliffc.aa.HM.HM4.Apply._args, com.cliffc.aa.HM.HM4.Apply._fun, com.cliffc.aa.HM.HM4.Syntax.more_work(), and com.cliffc.aa.HM.HM4.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM4.Syntax.more_work_impl (Ary< Syntax > work) package inherited
Definition at line 91 of file HM4.java.
{
       if( work.find(this)!=-1 ) return true; // On worklist, so ok
       // Check does not make progress
       int old = T2.CNT;  int olen = work._len;
       boolean more_work;
       try {
         T2 t = find();
         Type con = t._con;
         T2 hm = hm(null);       // Run H-M, with null work, looking for progress
         T2 un = find().unify(hm,null);
         more_work = t!=un || con!=un._con || work._len!=olen; // Something happened?
         assert !more_work;
       } catch( RuntimeException no_unify ) { more_work=true; } // Fail to unify assert is progress
       if( !more_work ) T2.CNT=old;  // Reset if no error; prevents assert from endlessly raising CNT
       return !more_work;
     }
References com.cliffc.aa.HM.HM4.T2._con, com.cliffc.aa.util.Ary< E >._len, com.cliffc.aa.HM.HM4.T2.CNT, com.cliffc.aa.HM.HM4.Syntax.find(), com.cliffc.aa.util.Ary< E >.find(), com.cliffc.aa.HM.HM4.Syntax.hm(), com.cliffc.aa.HM.HM4.Syntax.more_work(), and com.cliffc.aa.HM.HM4.T2.unify().
Referenced by com.cliffc.aa.HM.HM4.Con.more_work(), com.cliffc.aa.HM.HM4.Ident.more_work(), com.cliffc.aa.HM.HM4.Lambda.more_work(), com.cliffc.aa.HM.HM4.Lambda2.more_work(), com.cliffc.aa.HM.HM4.Let.more_work(), and com.cliffc.aa.HM.HM4.Apply.more_work().
p()
String com.cliffc.aa.HM.HM4.Syntax.p () inherited
Definition at line 111 of file HM4.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM4.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM4.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 112 of file HM4.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM4.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM4.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM4.Syntax.p1(), com.cliffc.aa.HM.HM4.Syntax.p2(), and com.cliffc.aa.HM.HM4.T2.str().
Referenced by com.cliffc.aa.HM.HM4.Syntax.p(), com.cliffc.aa.HM.HM4.Lambda.p2(), com.cliffc.aa.HM.HM4.Lambda2.p2(), com.cliffc.aa.HM.HM4.Let.p2(), and com.cliffc.aa.HM.HM4.Apply.p2().
p1()
SB com.cliffc.aa.HM.HM4.Apply.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 277 of file HM4.java.
 { return sb.p("(...)"); }
References com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM4.Apply.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 278 of file HM4.java.
{
       _fun.p0(sb,dups);
       for( Syntax arg : _args ) arg.p0(sb,dups);
       return sb;
     }
References com.cliffc.aa.HM.HM4.Apply._args, com.cliffc.aa.HM.HM4.Apply._fun, and com.cliffc.aa.HM.HM4.Syntax.p0().
prep_tree()
void com.cliffc.aa.HM.HM4.Apply.prep_tree (Syntax par, Ary< Syntax > work) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 301 of file HM4.java.
{
       prep_tree_impl(par,T2.tnew(),work);
       _fun.prep_tree(this,work);
       for( Syntax arg : _args ) arg.prep_tree(this,work);
     }
References com.cliffc.aa.HM.HM4.Apply._args, com.cliffc.aa.HM.HM4.Apply._fun, com.cliffc.aa.HM.HM4.Syntax.prep_tree(), com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM4.T2.tnew().
prep_tree_impl()
void com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl (Syntax par, T2 t, Ary< Syntax > work) package inherited
Definition at line 86 of file HM4.java.
 { _par=par; _t=t; work.push(this); }
References com.cliffc.aa.HM.HM4.Syntax._par, com.cliffc.aa.HM.HM4.Syntax._t, and com.cliffc.aa.util.Ary< E >.push().
Referenced by com.cliffc.aa.HM.HM4.Con.prep_tree(), com.cliffc.aa.HM.HM4.Ident.prep_tree(), com.cliffc.aa.HM.HM4.Lambda.prep_tree(), com.cliffc.aa.HM.HM4.Lambda2.prep_tree(), com.cliffc.aa.HM.HM4.Let.prep_tree(), and com.cliffc.aa.HM.HM4.Apply.prep_tree().
prep_tree_lookup()
T2 com.cliffc.aa.HM.HM4.Syntax.prep_tree_lookup (String name, Syntax prior) package inherited
Reimplemented in com.cliffc.aa.HM.HM4.Let, com.cliffc.aa.HM.HM4.Lambda2, and com.cliffc.aa.HM.HM4.Lambda.
Definition at line 87 of file HM4.java.
 { return null; }
str()
SB com.cliffc.aa.HM.HM4.Apply.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 271 of file HM4.java.
{
       _fun.str(sb.p("(")).p(" ");
       for( Syntax arg : _args )
         arg.str(sb).p(" ");
       return sb.unchar().p(")");
     }
References com.cliffc.aa.HM.HM4.Apply._args, com.cliffc.aa.HM.HM4.Apply._fun, com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM4.Syntax.str(), and com.cliffc.aa.util.SB.unchar().
toString()
final String com.cliffc.aa.HM.HM4.Syntax.toString () inherited
Definition at line 108 of file HM4.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM4.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_args
final Syntax [] com.cliffc.aa.HM.HM4.Apply._args package
Definition at line 269 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Apply.Apply(), com.cliffc.aa.HM.HM4.Apply.hm(), com.cliffc.aa.HM.HM4.Apply.live(), com.cliffc.aa.HM.HM4.Apply.more_work(), com.cliffc.aa.HM.HM4.Apply.p2(), com.cliffc.aa.HM.HM4.Apply.prep_tree(), and com.cliffc.aa.HM.HM4.Apply.str().
_fun
final Syntax com.cliffc.aa.HM.HM4.Apply._fun package
Definition at line 268 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Apply.Apply(), com.cliffc.aa.HM.HM4.Apply.hm(), com.cliffc.aa.HM.HM4.Apply.more_work(), com.cliffc.aa.HM.HM4.Apply.p2(), com.cliffc.aa.HM.HM4.Apply.prep_tree(), and com.cliffc.aa.HM.HM4.Apply.str().
_par
Syntax com.cliffc.aa.HM.HM4.Syntax._par package inherited
Definition at line 75 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Ident.prep_tree(), and com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM4.Syntax._t package inherited
Definition at line 76 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Syntax.find(), com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Con.live(), com.cliffc.aa.HM.HM4.Ident.live(), com.cliffc.aa.HM.HM4.Lambda.live(), com.cliffc.aa.HM.HM4.Lambda2.live(), com.cliffc.aa.HM.HM4.Let.live(), com.cliffc.aa.HM.HM4.Apply.live(), com.cliffc.aa.HM.HM4.Syntax.p0(), and com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM4.java