aa: com.cliffc.aa.util.Ary< E > Class Template Reference
com.cliffc.aa.util.Ary< E > Class Template Reference
Classes
class Iter
Public Member Functions
Ary (Class< E > clazz)
Ary (E[] es)
Ary (E[] es, int len)
Ary< E > add (E e)
Add element in amortized constant time.
Ary< E > addAll (Ary<? extends E > c)
Ary< E > addAll (Collection<? extends E > c)
E[] asAry ()
E at (int i)
E atX (int i)
void clear ()
Remove all elements.
void clear (int i)
Clear element.
Ary< E > deepCopy ()
E del (E e)
Element removal, using '=='.
E del (int i)
Fast, constant-time, element removal.
boolean equals (Object o)
void fill (E e)
Ary< E > filter_update (Predicate< E > P)
int find (E e)
Find the first matching element using ==, or -1 if none.
int find (Predicate< E > P)
Find the first element matching predicate P, or -1 if none.
int hashCode ()
void insert (int i, E e)
Slow, linear-time, element insert.
boolean isEmpty ()
Iterator< E > iterator ()
E last ()
int len ()
Ary< E > map_update (Function< E, E > f)
E pop ()
E push (E e)
Add element in amortized constant time.
E remove (int i)
Slow, linear-time, element removal.
boolean replace (E old, E nnn)
Find and replace the first matching element using ==.
E set (int i, E e)
Set existing element.
Ary< E > set_len (int len)
E setX (int i, E e)
void sort_update (Comparator<? super E > c)
Sorts in-place.
String toString ()
Static Public Member Functions
static< X extends Comparable< X > Ary< X > merge_and (Ary< X > a0, Ary< X > a1)
Merge-And.
static< X extends Comparable< X > Ary< X > merge_or (Ary< X > a0, Ary< X > a1)
Merge-Or.
static< X > Ary< X > merge_or (Ary< X > a0, Ary< X > a1, Comparator< X > cmpr, Predicate< X > filter)
Merge-Or.
Public Attributes
E[] _es
int _len
Package Functions
public< F extends E > Ary< E > addAll (F[] es)
Private Member Functions
void range_check (int i)
Detailed Description
Definition at line 11 of file Ary.java.
Constructor & Destructor Documentation
Ary() [1/3]
com.cliffc.aa.util.Ary< E >.Ary (E[] es)
Definition at line 14 of file Ary.java.
 { this(es,es.length); }
Referenced by com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.equals().
Ary() [2/3]
com.cliffc.aa.util.Ary< E >.Ary (E[] es, int len)
Definition at line 15 of file Ary.java.
 { if( es.length==0 ) es=Arrays.copyOf(es,1); _es=es; _len=len; }
Ary() [3/3]
com.cliffc.aa.util.Ary< E >.Ary (Class< E > clazz)
Definition at line 17 of file Ary.java.
 { this((E[]) Array.newInstance(clazz, 1),0); }
Member Function Documentation
add()
Ary<E> com.cliffc.aa.util.Ary< E >.add (E e)
Add element in amortized constant time.
Parameters
e Element to add at end of list
Returns
'this' for flow-coding
Definition at line 49 of file Ary.java.
{
     if( _len >= _es.length ) _es = Arrays.copyOf(_es,Math.max(1,_es.length<<1));
     _es[_len++] = e;
     return this;
   }
Referenced by com.cliffc.aa.node.MemSplitNode.add_alias(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.addAll(), com.cliffc.aa.node.FunNode.find_body(), com.cliffc.aa.Parse.func(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.merge_and(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.merge_or(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.Parse.stmt(), and com.cliffc.aa.Parse.type0().
addAll() [1/3]
Ary<E> com.cliffc.aa.util.Ary< E >.addAll (Ary<? extends E > c)
Parameters
c Collection to be added
Definition at line 163 of file Ary.java.
{
     if( c==null || c._len==0 ) return this;
     while( _len+c._len > _es.length ) _es = Arrays.copyOf(_es,_es.length<<1);
     System.arraycopy(c._es,0,_es,_len,c._len);
     _len += c._len;
     return this;
   }
addAll() [2/3]
Ary<E> com.cliffc.aa.util.Ary< E >.addAll (Collection<? extends E > c)
Parameters
c Collection to be added
Definition at line 151 of file Ary.java.
 { if( c!=null ) for( E e : c ) add(e); return this; }
Referenced by com.cliffc.aa.node.ScopeNode.IfScope.check(), com.cliffc.aa.node.FunNode.find_body(), and com.cliffc.aa.GVNGCM.retype_mem().
addAll() [3/3]
public<F extends E> Ary<E> com.cliffc.aa.util.Ary< E >.addAll (F[] es) package
Parameters
es Array to be added
Definition at line 154 of file Ary.java.
{
     if( es==null || es.length==0 ) return this;
     while( _len+es.length > _es.length ) _es = Arrays.copyOf(_es,_es.length<<1);
     System.arraycopy(es,0,_es,_len,es.length);
     _len += es.length;
     return this;
   }
asAry()
E [] com.cliffc.aa.util.Ary< E >.asAry ()
Returns
compact array version
Definition at line 172 of file Ary.java.
 { return Arrays.copyOf(_es,_len); }
Referenced by com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.Parse.func(), com.cliffc.aa.node.PrimNode.PRIMS(), com.cliffc.aa.HM.HM8.term(), com.cliffc.aa.HM.HM6.term(), com.cliffc.aa.HM.HM7.term(), com.cliffc.aa.HM.HM9.term(), com.cliffc.aa.HM.HM.term(), com.cliffc.aa.type.TestType.testStructTuple(), com.cliffc.aa.Parse.tuple(), com.cliffc.aa.Parse.type0(), and com.cliffc.aa.type.TypeMem.update().
at()
E com.cliffc.aa.util.Ary< E >.at (int i)
Parameters
i element index
Returns
element being returned; throws if OOB
Definition at line 25 of file Ary.java.
{
     range_check(i);
     return _es[i];
   }
Referenced by com.cliffc.aa.Parse._short_circuit_expr(), com.cliffc.aa.node.MemSplitNode._update(), com.cliffc.aa.node.MemSplitNode.add_alias(), com.cliffc.aa.node.MemJoinNode.can_bypass(), com.cliffc.aa.node.MemJoinNode.combine_splits(), com.cliffc.aa.node.Node.dumprpo(), com.cliffc.aa.node.MemSplitNode.find_alias_index(), com.cliffc.aa.Parse.func(), com.cliffc.aa.type.TypeStruct.get_cyclic(), com.cliffc.aa.type.TypeStruct.reachable(), com.cliffc.aa.node.MemSplitNode.remove_alias(), com.cliffc.aa.Parse.remove_unknown_callers(), com.cliffc.aa.type.TypeStruct.shrink(), com.cliffc.aa.Parse.stmt(), com.cliffc.aa.node.MemSplitNode.str(), com.cliffc.aa.HM.HM9.term(), com.cliffc.aa.HM.HM.term(), com.cliffc.aa.node.MemJoinNode.unify(), com.cliffc.aa.node.MemSplitNode.value(), and com.cliffc.aa.node.MemJoinNode.value().
atX()
E com.cliffc.aa.util.Ary< E >.atX (int i)
Parameters
i element index
Returns
element being returned, or null if OOB
Definition at line 31 of file Ary.java.
{
     return i < _len ? _es[i] : null;
   }
clear() [1/2]
void com.cliffc.aa.util.Ary< E >.clear ()
Remove all elements.
Definition at line 110 of file Ary.java.
 { _len=0; }
clear() [2/2]
void com.cliffc.aa.util.Ary< E >.clear (int i)
Clear element.
Does nothing if element is OOB, since these are clear by default.
Parameters
i element to clear
Definition at line 126 of file Ary.java.
 {  if( i<_len ) _es[i]=null; }
deepCopy()
Ary<E> com.cliffc.aa.util.Ary< E >.deepCopy ()
Definition at line 333 of file Ary.java.
{
     return new Ary<>(_es.clone(),_len);
   }
Referenced by com.cliffc.aa.node.MemSplitNode.copy().
del() [1/2]
E com.cliffc.aa.util.Ary< E >.del (E e)
Element removal, using '=='.
Does not preserve order.
Parameters
e element to be removed
Returns
element removed
Definition at line 88 of file Ary.java.
                       {
     for( int i=0; i<_len; i++ ) {
       E tmp = _es[i];
       if( tmp==e ) {
         _es[i]=_es[--_len];
         return tmp;
       }
     }
     return null;
   }
del() [2/2]
E com.cliffc.aa.util.Ary< E >.del (int i)
Fast, constant-time, element removal.
Does not preserve order
Parameters
i element to be removed
Returns
element removed
Definition at line 78 of file Ary.java.
{
     range_check(i);
     E tmp = _es[i];
     _es[i]=_es[--_len];
     return tmp;
   }
Referenced by com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.filter_update(), and com.cliffc.aa.HM.HM4.hm().
equals()
boolean com.cliffc.aa.util.Ary< E >.equals (Object o)
Definition at line 315 of file Ary.java.
{
     if( this==o ) return true;
     if( !(o instanceof Ary) ) return false;
     Ary ary = (Ary)o;
     if( _len != ary._len ) return false;
     if( _es == ary._es ) return true;
     for( int i=0; i<_len; i++ )
       if( !(_es[i]==null ? (ary._es[i] == null) : _es[i].equals(ary._es[i])) )
         return false;
     return true;
   }
fill()
void com.cliffc.aa.util.Ary< E >.fill (E e)
Definition at line 112 of file Ary.java.
 { Arrays.fill(_es,0,_len,e); }
filter_update()
Ary<E> com.cliffc.aa.util.Ary< E >.filter_update (Predicate< E > P)
Parameters
P filter out elements failing to pass the predicate; updates in place and shuffles list.
Returns
this, for flow-coding
Definition at line 179 of file Ary.java.
{
     for( int i=0; i<_len; i++ )
       if( !P.test(_es[i]) )
         del(i--);
     return this;
   }
find() [1/2]
int com.cliffc.aa.util.Ary< E >.find (E e)
Find the first matching element using ==, or -1 if none.
Note that most del calls shuffle the list, so the first element might be random.
Parameters
e Element to find
Returns
index of first matching element, or -1 if none
Definition at line 192 of file Ary.java.
{
     for( int i=0; i<_len; i++ )  if( _es[i]==e )  return i;
     return -1;
   }
Referenced by com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.Env.lookup_fref(), com.cliffc.aa.HM.HM4.Syntax.more_work_impl(), com.cliffc.aa.type.TypeStruct.push(), and com.cliffc.aa.Parse.type0().
find() [2/2]
int com.cliffc.aa.util.Ary< E >.find (Predicate< E > P)
Find the first element matching predicate P, or -1 if none.
Note that most del calls shuffle the list, so the first element might be random.
Parameters
P Predicate to match
Returns
index of first matching element, or -1 if none
Definition at line 200 of file Ary.java.
{
     for( int i=0; i<_len; i++ )  if( P.test(_es[i]) )  return i;
     return -1;
   }
hashCode()
int com.cliffc.aa.util.Ary< E >.hashCode ()
Definition at line 326 of file Ary.java.
{
     int sum=_len;
     for( int i=0; i<_len; i++ )
       sum += _es[i]==null ? 0 : _es[i].hashCode();
     return sum;
   }
Referenced by com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.hashCode().
insert()
void com.cliffc.aa.util.Ary< E >.insert (int i, E e)
Slow, linear-time, element insert.
Preserves order.
Parameters
i index to insert at, between 0 and _len inclusive.
e Element to insert
Definition at line 67 of file Ary.java.
{
     if( i < 0 || i>_len )
       throw new ArrayIndexOutOfBoundsException(""+i+" >= "+_len);
     if( _len >= _es.length ) _es = Arrays.copyOf(_es,Math.max(1,_es.length<<1));
     System.arraycopy(_es,i,_es,i+1,(_len++)-i);
     _es[i] = e;
   }
isEmpty()
boolean com.cliffc.aa.util.Ary< E >.isEmpty ()
Returns
list is empty
Definition at line 20 of file Ary.java.
 { return _len==0; }
Referenced by com.cliffc.aa.type.TypeStruct.ax_impl_struct(), com.cliffc.aa.node.ScopeNode.IfScope.check(), com.cliffc.aa.type.TypeMemPtr.depth(), com.cliffc.aa.node.FunNode.find_body(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.Env.VStack.isEmpty(), com.cliffc.aa.type.Type< T extends Type< T >.Pool.malloc(), com.cliffc.aa.GVNGCM.retype_mem(), and com.cliffc.aa.Parse.stmt().
iterator()
Iterator<E> com.cliffc.aa.util.Ary< E >.iterator ()
Returns
an iterator
Definition at line 291 of file Ary.java.
 { return new Iter(); }
last()
E com.cliffc.aa.util.Ary< E >.last ()
Returns
last element
Definition at line 35 of file Ary.java.
                    {
     range_check(0);
     return _es[_len-1];
   }
Referenced by com.cliffc.aa.Parse.stmt().
len()
int com.cliffc.aa.util.Ary< E >.len ()
Returns
active list length
Definition at line 22 of file Ary.java.
 { return _len; }
Referenced by com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.Ary(), and com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.set_len().
map_update()
Ary<E> com.cliffc.aa.util.Ary< E >.map_update (Function< E, E > f)
Parameters
f function to apply to each element. Updates in-place.
Definition at line 175 of file Ary.java.
 { for( int i = 0; i<_len; i++ ) _es[i] = f.apply(_es[i]); return this; }
merge_and()
static <X extends Comparable<X> Ary<X> com.cliffc.aa.util.Ary< E >.merge_and (Ary< X > a0, Ary< X > a1) static
Merge-And.
Merge 2 sorted Arys, keeping only duplicates. Return a new sorted Ary with the merged list. Undefined if the original arrays are not sorted. Error if they are not of the same type. Elements must implement Comparable.
Parameters
a0 Sorted Ary to merge
a1 Sorted Ary to merge
Returns
A new sorted merged Ary
Definition at line 275 of file Ary.java.
{
     int i=0, j=0;
     Ary<X> res = new Ary<>(Arrays.copyOf(a0._es,Math.min(a0._len,a1._len)),0);
     while( i<a0._len && j<a1._len ) {
       X x = a0._es[i];
       X y = a1._es[j];
       int cmp = x.compareTo(y);
       if( cmp<0 )      { i++;      }
       else if( cmp>0 ) {      j++; }
       else { res.add(x); i++; j++; }
     }
     return res;
   }
merge_or() [1/2]
static <X extends Comparable<X> Ary<X> com.cliffc.aa.util.Ary< E >.merge_or (Ary< X > a0, Ary< X > a1) static
Merge-Or.
Merge 2 sorted Arys, tossing out duplicates. Return a new sorted Ary with the merged list. Undefined if the original arrays are not sorted. Error if they are not of the same type. Elements must implement Comparable.
Parameters
a0 Sorted Ary to merge
a1 Sorted Ary to merge
Returns
A new sorted merged Ary
Definition at line 222 of file Ary.java.
{
     int i=0, j=0;
     Ary<X> res = new Ary<>(Arrays.copyOf(a0._es,a0._len+a1._len),0);
     while( i<a0._len && j<a1._len ) {
       X x = a0._es[i];
       X y = a1._es[j];
       int cmp = x.compareTo(y);
       if( cmp<0 )      { res.add(x); i++;      }
       else if( cmp>0 ) { res.add(y);      j++; }
       else             { res.add(x); i++; j++; }
     }
     while( i<a0._len ) res.add(a0._es[i++]);
     while( j<a1._len ) res.add(a1._es[j++]);
     return res;
   }
merge_or() [2/2]
static <X> Ary<X> com.cliffc.aa.util.Ary< E >.merge_or (Ary< X > a0, Ary< X > a1, Comparator< X > cmpr, Predicate< X > filter) static
Merge-Or.
Merge two sorted Arys, tossing out duplicates and elements not passing the filter. Return a new sorted Ary with the merged list. Undefined if the original arrays are not sorted. Error if they are not of the same type. Elements must implement Comparable.
Parameters
a0 Sorted Ary to merge
a1 Sorted Ary to merge
cmpr Comparator
filter Predicate, null means no filter
Returns
A new sorted merged Ary
Definition at line 249 of file Ary.java.
{
     int i=0, j=0;
     Ary<X> res = new Ary<>(Arrays.copyOf(a0._es,a0._len+a1._len),0);
     while( i<a0._len && j<a1._len ) {
       X x = a0._es[i];   if( !filter.test(x) ) { i++; continue; }
       X y = a1._es[j];   if( !filter.test(y) ) { j++; continue; }
       int cmp = cmpr.compare(x,y);
       if( cmp<0 )      { res.add(x); i++;      }
       else if( cmp>0 ) { res.add(y);      j++; }
       else             { res.add(x); i++; j++; }
     }
     while( i<a0._len ) if( filter.test(a0._es[i++]) ) res.add(a0._es[i-1]);
     while( j<a1._len ) if( filter.test(a1._es[j++]) ) res.add(a1._es[j-1]);
     return res;
   }
pop()
E com.cliffc.aa.util.Ary< E >.pop ()
Returns
remove and return last element
Definition at line 41 of file Ary.java.
                   {
     range_check(0);
     return _es[--_len];
   }
Referenced by com.cliffc.aa.type.TypeStruct.ax_impl_struct(), com.cliffc.aa.node.ScopeNode.IfScope.check(), com.cliffc.aa.node.MemJoinNode.combine_splits(), com.cliffc.aa.type.TypeMemPtr.depth(), com.cliffc.aa.node.FunNode.find_body(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.type.TypeStruct.get_cyclic(), com.cliffc.aa.type.Type< T extends Type< T >.Pool.malloc(), com.cliffc.aa.GVNGCM.retype_mem(), and com.cliffc.aa.Parse.type0().
push()
E com.cliffc.aa.util.Ary< E >.push (E e)
Add element in amortized constant time.
Parameters
e Element to add at end of list
Definition at line 58 of file Ary.java.
{
     if( _len >= _es.length ) _es = Arrays.copyOf(_es,Math.max(1,_es.length<<1));
     return (_es[_len++] = e);
   }
Referenced by com.cliffc.aa.Env.VStack.add_var(), com.cliffc.aa.type.TypeStruct.ax_impl_struct(), com.cliffc.aa.type.Type< TypeFlt >.concat(), com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.node.FunNode.find_body(), com.cliffc.aa.type.Type< T extends Type< T >.Pool.free(), com.cliffc.aa.Parse.func(), com.cliffc.aa.type.TypeStruct.get_cyclic(), com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Apply.hm(), com.cliffc.aa.node.Node.postorder(), com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl(), com.cliffc.aa.node.PrimNode.PRIMS(), com.cliffc.aa.type.TypeStruct.push(), com.cliffc.aa.GVNGCM.retype_mem(), com.cliffc.aa.type.TypeStruct.shrink(), com.cliffc.aa.HM.HM6.term(), com.cliffc.aa.HM.HM8.term(), com.cliffc.aa.HM.HM7.term(), com.cliffc.aa.HM.HM9.term(), com.cliffc.aa.HM.HM.term(), and com.cliffc.aa.Parse.tuple().
range_check()
void com.cliffc.aa.util.Ary< E >.range_check (int i) private
Definition at line 307 of file Ary.java.
{
     if( i < 0 || i>=_len )
       throw new ArrayIndexOutOfBoundsException(""+i+" >= "+_len);
   }
Referenced by com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.at(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.del(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.last(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.pop(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.remove(), and com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.set().
remove()
E com.cliffc.aa.util.Ary< E >.remove (int i)
Slow, linear-time, element removal.
Preserves order.
Parameters
i element to be removed
Returns
element removed
Definition at line 102 of file Ary.java.
{
     range_check(i);
     E e = _es[i];
     System.arraycopy(_es,i+1,_es,i,(--_len)-i);
     return e;
   }
Referenced by com.cliffc.aa.node.MemSplitNode.remove_alias().
replace()
boolean com.cliffc.aa.util.Ary< E >.replace (E old, E nnn)
Find and replace the first matching element using ==.
Parameters
old Element to find
nnn Element replacing old
Returns
true if replacement happened
Definition at line 208 of file Ary.java.
{
     for( int i=0; i<_len; i++ )  if( _es[i]==old )  { _es[i]=nnn; return true; }
     return false;
   }
set()
E com.cliffc.aa.util.Ary< E >.set (int i, E e)
Set existing element.
Parameters
i element to set
e value to set
Returns
old value
Definition at line 133 of file Ary.java.
{
     range_check(i);
     E old = _es[i];
     _es[i] = e;
     return old;
   }
Referenced by com.cliffc.aa.node.MemSplitNode._update(), com.cliffc.aa.node.MemSplitNode.add_alias(), com.cliffc.aa.node.MemJoinNode.combine_splits(), com.cliffc.aa.node.MemSplitNode.remove_alias(), com.cliffc.aa.HM.HM9.term(), and com.cliffc.aa.HM.HM.term().
set_len()
Ary<E> com.cliffc.aa.util.Ary< E >.set_len (int len)
Definition at line 140 of file Ary.java.
{
     if( len > _len )
       while( len>= _es.length ) _es = Arrays.copyOf(_es,_es.length<<1);
     _len = len;
     while( _es.length > (len<<1) ) // Shrink if hugely too large
       _es = Arrays.copyOf(_es,_es.length>>1);
     Arrays.fill(_es,len,_es.length,null);
     return this;
   }
Referenced by com.cliffc.aa.Parse.func().
setX()
E com.cliffc.aa.util.Ary< E >.setX (int i, E e)
Definition at line 115 of file Ary.java.
{
     if( i >= _len ) Arrays.fill(_es,_len,_es.length,null);
     while( i>= _es.length ) _es = Arrays.copyOf(_es,_es.length<<1);
     if( i >= _len ) _len = i+1;
     return (_es[i] = e);
   }
Referenced by com.cliffc.aa.type.TestType.testStructTuple(), and com.cliffc.aa.type.TypeMem.update().
sort_update()
void com.cliffc.aa.util.Ary< E >.sort_update (Comparator<? super E > c)
Sorts in-place.
Parameters
c Comparator to sort by
Definition at line 187 of file Ary.java.
 { Arrays.sort(_es, 0, _len, c);  }
Referenced by com.cliffc.aa.tvar.TV2.str().
toString()
String com.cliffc.aa.util.Ary< E >.toString ()
Definition at line 298 of file Ary.java.
{
     SB sb = new SB().p('{');
     for( int i=0; i<_len; i++ ) {
       if( i>0 ) sb.p(',');
       if( _es[i] != null ) sb.p(_es[i].toString());
     }
     return sb.p('}').toString();
   }
Referenced by com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.toString().
Member Data Documentation
_es
E [] com.cliffc.aa.util.Ary< E >._es
Definition at line 12 of file Ary.java.
Referenced by com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.add(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.addAll(), com.cliffc.aa.type.Type< TypeFlt >.ALL_TYPES(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.Ary(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.asAry(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.at(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.atX(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.clear(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.deepCopy(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.del(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.equals(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.fill(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.filter_update(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.find(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.hashCode(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.insert(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.last(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.map_update(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.merge_and(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.merge_or(), com.cliffc.aa.util.Ary< E >.Iter.next(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.pop(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.push(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.remove(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.replace(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.set(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.set_len(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.setX(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.sort_update(), and com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.toString().
_len
int com.cliffc.aa.util.Ary< E >._len
Definition at line 13 of file Ary.java.
Referenced by com.cliffc.aa.Parse._short_circuit_expr(), com.cliffc.aa.node.MemSplitNode._update(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.add(), com.cliffc.aa.node.MemSplitNode.add_alias(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.addAll(), com.cliffc.aa.type.Type< TypeFlt >.ALL_TYPES(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.Ary(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.asAry(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.atX(), com.cliffc.aa.node.MemJoinNode.can_bypass(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.clear(), com.cliffc.aa.node.MemJoinNode.combine_splits(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.deepCopy(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.del(), com.cliffc.aa.node.Node.dumprpo(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.equals(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.fill(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.filter_update(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.find(), com.cliffc.aa.node.MemSplitNode.find_alias_index(), com.cliffc.aa.Parse.func(), com.cliffc.aa.type.TypeStruct.get_cyclic(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.hashCode(), com.cliffc.aa.util.Ary< E >.Iter.hasNext(), com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.insert(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.isEmpty(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.last(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.len(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.map_update(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.merge_and(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.merge_or(), com.cliffc.aa.HM.HM4.Syntax.more_work_impl(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.pop(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.push(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.range_check(), com.cliffc.aa.type.TypeStruct.reachable(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.remove(), com.cliffc.aa.Parse.remove_unknown_callers(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.replace(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.set_len(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.setX(), com.cliffc.aa.type.TypeStruct.shrink(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.sort_update(), com.cliffc.aa.Parse.stmt(), com.cliffc.aa.node.MemSplitNode.str(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.toString(), com.cliffc.aa.Parse.type0(), com.cliffc.aa.node.MemSplitNode.unify(), and com.cliffc.aa.node.MemSplitNode.value().
The documentation for this class was generated from the following file:
Ary.java