aa: com.cliffc.aa.type.TypeStruct Class Reference
com.cliffc.aa.type.TypeStruct Class Reference
A memory-based collection of optionally named fields.
Classes
class TPair
Public Member Functions
boolean above_center ()
TypeStruct add_fld (String name, Access mutable)
TypeStruct add_fld (String name, Access mutable, Type tfld)
TypeStruct approx (int cutoff, int alias)
Type at (int idx)
TypeStruct close ()
int compute_hash ()
TypeStruct crush ()
boolean cycle_equals (Type o)
boolean equals (Object o)
TypeFld fld (int idx)
int fld_find (String fld)
TypeFld[] flds ()
TypeStruct install_cyclic (Ary< Type > reachs)
boolean is_con ()
byte isBitShape (Type t)
Type last ()
int len ()
TypeStruct make_from (String name)
TypeStruct make_from (Type head, TypeMem mem, VBitSet visit)
TypeStruct make_from (TypeFld[] flds)
TypeStruct make_from_flds (TypeStruct ts)
boolean may_be_con ()
boolean may_nil ()
Type meet_loop (Type t2)
Type meet_nil (Type nil)
boolean must_nil ()
Ary< Type > reachable ()
TypeStruct set_fld (int i, Type t, Access ff)
SB str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
TypeStruct update (Access fin, String fld, Type val)
TypeObj update (TypeInt idx, Type val)
void walk (Predicate< Type > p)
TypeStruct widen ()
Static Public Member Functions
static TypeFld[] flds (Type t1)
static TypeFld[] flds (Type t1, Type t2)
static TypeStruct make (String fld_name, Type t)
static TypeStruct make (String fld_name, Type t, Access a)
static TypeStruct make (String name, boolean any, TypeFld[] flds, boolean open)
static TypeStruct make (Type... ts)
static TypeStruct make (TypeFld... flds)
static TypeStruct malloc (String name, boolean any, TypeFld[] flds, boolean open)
static TypeStruct open (Type tdisp)
static TypeStruct shrink (Ary< Type > reaches, TypeStruct tstart)
static TypeFld[] tups (Type t1, Type t2)
static TypeFld[] tups (Type t1, Type t2, Type t3)
Public Attributes
boolean _cyclic
boolean _open
Static Public Attributes
static final TypeStruct A = make("a",TypeFlt.FLT64)
static final TypeStruct ALLSTRUCT = make("",false,new TypeFld[0],true)
static final TypeStruct ANYSTRUCT = make("",true ,new TypeFld[0],false)
static final TypeStruct ARW = make("a",TypeFlt.FLT64,Access.RW)
static final TypeStruct FLT64 = make(flds(TypeFlt.FLT64))
static final TypeStruct INT64_INT64 = make(flds(TypeInt.INT64,TypeInt.INT64))
static final TypeObj ISUSED
static final TypeStruct NAMEPT = make("Point:",false,POINT._flds,false)
static final TypeObj OBJ
static final TypeStruct POINT = make(flds(TypeFlt.FLT64,TypeFlt.FLT64))
static final NonBlockingHashMapLong< Type > UF = new NonBlockingHashMapLong<>()
static final TypeObj UNUSED
static final TypeObj XOBJ
Protected Member Functions
O init (byte type, String name, boolean any, boolean use)
TypeStruct xdual ()
Type xmeet (Type t)
Package Functions
boolean any_modifiable ()
boolean contains (Type t, VBitSet bs)
TypeObj flatten_fields ()
boolean intern_check1 ()
boolean is_display ()
TypeStruct rdual ()
TypeObj remove_other_flds (String fld, Type live)
TypeStruct repeats_in_cycles ()
TypeStruct repeats_in_cycles (TypeStruct head, VBitSet bs)
Static Package Functions
[static initializer]
static boolean isDigit (char c)
static TypeMemPtr sharpen (TypeMem mem, TypeMemPtr dull)
Package Attributes
boolean _any
boolean _use
Static Package Attributes
static final TypeStruct TFLT64 = make(".",TypeFlt.FLT64)
static final TypeStruct[] TYPES = new TypeStruct[]{ALLSTRUCT,POINT,NAMEPT,A,C0,D1,ARW,INT64_INT64}
Private Member Functions
TypeStruct _clone ()
int cmp (TypeStruct t)
boolean cycle_equals0 (TypeStruct t)
TypeStruct cyclic_meet (TypeStruct that)
TypeStruct find_other ()
BitSet get_cyclic ()
TypeStruct hashcons_freeS ()
TypeStruct init (String name, boolean any, TypeFld[] flds, boolean open)
boolean is_tup ()
int len (TypeStruct tt)
int len0 (TypeStruct tmax)
void mark_cyclic (BitSet bcs, Ary< Type > reaches)
void push (Ary< Type > work, Type t)
TypeStruct update (Access fin, String fld, Type val, boolean precise)
TypeStruct xmeet1 (TypeStruct tmax, boolean is_loop)
Static Private Member Functions
static void _dull (TypeMem mem, TypeMemPtr dull, HashMap< BitsAlias, TypeMemPtr > dull_cache)
static boolean _is_sharp (Type t)
static TypeMemPtr _sharp (TypeMem mem, TypeMemPtr dull, HashMap< BitsAlias, TypeMemPtr > dull_cache)
static Type ax_impl_fptr (int alias, int cutoff, Ary< TypeStruct > cutoffs, int d, TypeStruct dold, TypeFunPtr old)
static TypeMemPtr ax_impl_ptr (int alias, int cutoff, Ary< TypeStruct > cutoffs, int d, TypeStruct dold, TypeMemPtr old)
static TypeStruct ax_impl_struct (int alias, boolean isnews, int cutoff, Ary< TypeStruct > cutoffs, int d, TypeStruct dold, TypeStruct old)
static Type ax_meet (BitSetSparse bs, Type nt, Type old)
static boolean check_interned (Ary< Type > reachs)
static boolean check_uf (Ary< Type > reaches)
static BitSet get_cyclic (BitSet bcs, VBitSet bs, Ary< Type > stack, Type t)
static boolean post_mod (Type t)
static< T extends Type > T ufind (T t)
static< T extends Type > T union (T lost, T kept)
Private Attributes
TypeFld[] _flds
Static Private Attributes
static final TypeStruct C0 = make("c",TypeInt.FALSE)
static final Ary< TypeStruct > CYCLES = new Ary<>(new TypeStruct[0])
static final TypeStruct D1 = make("d",TypeInt.TRUE)
static final IHashMap DUPS = new IHashMap()
static final HashMap< TPair, TypeStruct > MEETS0 = new HashMap<>()
static final IHashMap OLD2APX = new IHashMap()
Detailed Description
A memory-based collection of optionally named fields.
This is a recursive type, only produced by NewNode and structure or tuple constants. Fields can be indexed by field name or numeric constant (i.e. tuples), but NOT by a general number - thats an Array. Field access mods make a small lattice of: {choice,r/w,final,r-o}. Note that mixing r/w and final moves to r-o and loses the final property.
The recursive type poses some interesting challenges. It is represented as literally a cycle of pointers which must include a TypeStruct (and not a TypeTuple which only roots Types) and a TypeMemPtr (edge) or a TypeFunPtr (display pointer). Type inference involves finding the Meet of two cyclic structures. The cycles will not generally be of the same length. However, each field Meets independently (and fields in one structure but not the other are not in the final Meet). This means we are NOT trying to solve the general problem of graph-equivalence (a known NP hard problem). Instead we can solve each field independently and also intersect across common fields.
When solving across a single field, we will find some prefix and then possibly a cycle - conceptually the type unrolls forever. When doing the Meet we conceptually unroll both types forever, compute the Meet element by element... but when both types have looped, we can stop and the discovered cycle is the Meet's cycle.
TODO: Cleaning up this mess somewhat... A try-with-resources: try(Ary<TypeFld> flds = TypeFld.get_flds()) { while(pred) flds.push(fld); // Accumulate, drop dups, screw around malloc(... flds ...); // Finally use } // Exit unwinds the get_flds These can be scope-alloced from a free-list. Moving TypeStruct to an UNORDERED list of fields.
Definition at line 50 of file TypeStruct.java.
Member Function Documentation
[static initializer]()
com.cliffc.aa.type.TypeStruct.[static initializer] static package
_clone()
TypeStruct com.cliffc.aa.type.TypeStruct._clone () private
Definition at line 465 of file TypeStruct.java.
{
     assert interned();
     TypeFld[] flds = TypeFlds.clone(_flds); // Shallow field clone
     TypeStruct t = malloc(_name,_any,flds,_open);
     t._hash = t.compute_hash();
     return t;
   }
References com.cliffc.aa.type.TypeObj< TypeStruct >._any, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeFlds.clone(), com.cliffc.aa.type.TypeStruct.compute_hash(), com.cliffc.aa.type.TypeStruct.flds(), and com.cliffc.aa.type.TypeStruct.malloc().
Referenced by com.cliffc.aa.type.TypeStruct._sharp(), and com.cliffc.aa.type.TypeStruct.cyclic_meet().
_dull()
static void com.cliffc.aa.type.TypeStruct._dull (TypeMem mem, TypeMemPtr dull, HashMap< BitsAlias, TypeMemPtr > dull_cache) static private
Definition at line 909 of file TypeStruct.java.
{
     // Check caches and return
     if( mem.sharp_get(dull) != null ) return;
     if( dull_cache.get(dull._aliases) != null ) return;
     if( dull==NO_DISP || dull==NO_DISP.dual() ) { mem.sharput(dull,dull); return; }
     // Walk and meet "dull" fields; all TMPs will point to ISUSED (hence are dull).
     boolean any = dull._aliases.above_center();
     Type t = any ? TypeObj.ISUSED : TypeObj.UNUSED;
     for( int alias : dull._aliases )
       if( alias != 0 )
         for( int kid=alias; kid != 0; kid=BitsAlias.next_kid(alias,kid) ) {
           TypeObj x = mem.at(kid);
           t = any ? t.join(x) : t.meet(x);
         }
     TypeMemPtr dptr = dull.make_from((TypeObj)t);
     if( _is_sharp(t) ) {        // If sharp, install and return
       mem.sharput(dull,dptr);
       return;
     }
     // Install in dull result in dull cache BEFORE recursing.  We might see it
     // again if cyclic types.
     dull_cache.put(dull._aliases,dptr);
     // Visit all dull pointers and recursively collect
     for( TypeFld fld : ((TypeStruct)t)._flds ) {
       Type tt = fld._t;
       if( tt instanceof TypeFunPtr ) tt = ((TypeFunPtr)tt)._disp;
       if( tt instanceof TypeMemPtr )
         _dull(mem,(TypeMemPtr)tt,dull_cache);
     }
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct._is_sharp(), com.cliffc.aa.type.TypeFld._t, com.cliffc.aa.type.Bits< B extends Bits< B >.above_center(), com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.type.Type< T extends Type< T >.dual(), com.cliffc.aa.type.TypeStruct.fld(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.ISUSED, com.cliffc.aa.type.Type< T extends Type< T >.join(), com.cliffc.aa.type.TypeMemPtr.make_from(), com.cliffc.aa.type.Type< T extends Type< T >.meet(), com.cliffc.aa.type.BitsAlias.next_kid(), com.cliffc.aa.type.TypeMem.sharp_get(), com.cliffc.aa.type.TypeMem.sharput(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED.
Referenced by com.cliffc.aa.type.TypeStruct.sharpen().
_is_sharp()
static boolean com.cliffc.aa.type.TypeStruct._is_sharp (Type t) static private
Definition at line 940 of file TypeStruct.java.
{
     if( !(t instanceof TypeStruct) ) return true;
     TypeStruct ts = (TypeStruct)t;
     for( TypeFld fld : ts._flds ) {
       Type tt = fld._t;
       assert fld.interned()==tt.interned();
       if( !tt.interned() ||     // Not interned internal, then this is not finished
           (tt instanceof TypeMemPtr && // Or has internal dull pointers
            ((TypeMemPtr)tt)._obj == TypeObj.ISUSED) )
         return false;
     }
     return true;
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.TypeFld._t, com.cliffc.aa.type.TypeStruct.fld(), com.cliffc.aa.type.Type< T extends Type< T >.interned(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.ISUSED.
Referenced by com.cliffc.aa.type.TypeStruct._dull(), and com.cliffc.aa.type.TypeStruct._sharp().
_sharp()
static TypeMemPtr com.cliffc.aa.type.TypeStruct._sharp (TypeMem mem, TypeMemPtr dull, HashMap< BitsAlias, TypeMemPtr > dull_cache) static private
Definition at line 963 of file TypeStruct.java.
{
     TypeMemPtr sharp = mem.sharp_get(dull);
     if( sharp != null ) return sharp; // Value returned is sharp and interned
     TypeMemPtr dptr = dull_cache.get(dull._aliases);
     if( !dptr.interned() )      // Closed a cycle
       return dptr; // Not-yet-sharp and not interned; return the work-in-progress
     // Copy, replace dull with not-interned dull clone.  Fields are also cloned, not interned.
     TypeStruct dts2 = ((TypeStruct)dptr._obj)._clone();
     TypeMemPtr dptr2 = (TypeMemPtr)dptr.clone();
     dptr2._obj = dts2;  dptr2._hash = dptr2.compute_hash();
     dull_cache.put(dull._aliases,dptr2);
     // walk all fields, copy unless TMP.
     for( int i=0; i<dts2._flds.length; i++ ) {
       TypeFld dts2_fld = dts2._flds[i];
       Type t = dts2_fld._t;
       if( t instanceof TypeMemPtr ) // For TMP, recurse on dull pointers.
         dts2_fld.setX(_sharp(mem,((TypeMemPtr)t),dull_cache));
       if( t instanceof TypeFunPtr ) {
         TypeFunPtr tf = (TypeFunPtr) t;
         if( tf._disp instanceof TypeMemPtr ) { // Need  a pointer to sharpen
           TypeMemPtr dptr3 = _sharp(mem, (TypeMemPtr) tf._disp, dull_cache);
           dts2_fld.setX(dptr3.interned()             // Sharp return?
             ? tf.make_from(dptr3)        // Make sharp TFP field
             : tf._sharpen_clone(dptr3)); // Make dull  TFP field
         }
       }
       if( dts2_fld._t.interned() )
         dts2._flds[i] = dts2_fld.hashcons_free();
     }
     if( !_is_sharp(dts2) ) return dptr2; // Return the work-in-progress
     // Then copied field types are all sharp and interned.
     // Intern the fields themselves.
     for( int i=0; i<dts2._flds.length; i++ )
       if( !dts2._flds[i]._t.interned() )
         dts2._flds[i] = dts2._flds[i].hashcons_free();
     dull_cache.remove(dull._aliases);// Move the entry from dull cache to sharp cache
     TypeStruct sts = dts2.hashcons_freeS();
     return mem.sharput(dull,dull.make_from(sts));
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeStruct._clone(), com.cliffc.aa.type.TypeFunPtr._disp, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.Type< T extends Type< T >._hash, com.cliffc.aa.type.TypeStruct._is_sharp(), com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.TypeFunPtr._sharpen_clone(), com.cliffc.aa.type.TypeFld._t, com.cliffc.aa.type.Type< T extends Type< T >.clone(), com.cliffc.aa.type.TypeMemPtr.compute_hash(), com.cliffc.aa.type.Type< T extends Type< T >.hashcons_free(), com.cliffc.aa.type.TypeStruct.hashcons_freeS(), com.cliffc.aa.type.Type< T extends Type< T >.interned(), com.cliffc.aa.type.TypeMemPtr.make_from(), com.cliffc.aa.type.TypeFunPtr.make_from(), com.cliffc.aa.type.TypeFld.setX(), com.cliffc.aa.type.TypeMem.sharp_get(), and com.cliffc.aa.type.TypeMem.sharput().
Referenced by com.cliffc.aa.type.TypeStruct.sharpen().
above_center()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.above_center inherited
Definition at line 77 of file TypeObj.java.
 { return _any; }
add_fld() [1/2]
TypeStruct com.cliffc.aa.type.TypeStruct.add_fld (String name, Access mutable)
Definition at line 1021 of file TypeStruct.java.
 { return add_fld(name,mutable,Type.SCALAR); }
References com.cliffc.aa.type.TypeStruct.add_fld(), and com.cliffc.aa.type.Type< T extends Type< T >.SCALAR.
Referenced by com.cliffc.aa.type.TypeStruct.add_fld().
add_fld() [2/2]
TypeStruct com.cliffc.aa.type.TypeStruct.add_fld (String name, Access mutable, Type tfld)
Definition at line 1022 of file TypeStruct.java.
{
     assert name==null || Util.eq(name,TypeFld.fldBot) || fld_find(name)==-1;
     assert !_any && _open;
     TypeFld[] flds = TypeFlds.copyOf(_flds,_flds.length+1);
     flds[_flds.length] = TypeFld.make(name==null ? TypeFld.fldBot : name,tfld,mutable,_flds.length);
     return make(_name,_any,flds,true);
   }
References com.cliffc.aa.type.TypeObj< TypeStruct >._any, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeFlds.copyOf(), com.cliffc.aa.util.Util.eq(), com.cliffc.aa.type.TypeStruct.fld_find(), com.cliffc.aa.type.TypeFld.fldBot, com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeFld.make(), and com.cliffc.aa.type.TypeStruct.make().
any_modifiable()
boolean com.cliffc.aa.type.TypeStruct.any_modifiable () package
Definition at line 1080 of file TypeStruct.java.
{
     //if( _open ) return true;
     //for( byte b : _flags )
     //  if( is_modifable(fmod(b)) )
     //    return true;
     //return false;
     throw unimpl();
   }
approx()
TypeStruct com.cliffc.aa.type.TypeStruct.approx (int cutoff, int alias)
Definition at line 477 of file TypeStruct.java.
{
     boolean shallow=true;
     for( TypeFld fld : _flds )
       if( fld._t._type == TMEMPTR ) { shallow=false; break; }
     if( shallow ) return this;  // Fast cutout for boring structs
     // Scan the old copy for elements that are too deep.
     // 'Meet' those into the clone at one layer up.
     RECURSIVE_MEET++;
     assert UF.isEmpty();
     assert OLD2APX.isEmpty();
     TypeStruct apx = ax_impl_struct( alias, true, cutoff, null, 0, this, this );
     // Remove any leftover internal duplication
     apx = shrink(apx.reachable(),apx);
     RECURSIVE_MEET--;
     TypeStruct rez = this;
     if( apx != this ) {
       Ary<Type> reaches = apx.reachable();
       assert check_uf(reaches);
       assert !check_interned(reaches);
       rez = apx.install_cyclic(reaches);
       assert this.isa(rez);
     }
     UF.clear();
     OLD2APX.clear();
     return rez;
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeFld._t, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.type.TypeStruct.ax_impl_struct(), com.cliffc.aa.type.TypeStruct.check_interned(), com.cliffc.aa.type.TypeStruct.check_uf(), com.cliffc.aa.util.IHashMap.clear(), com.cliffc.aa.type.TypeStruct.fld(), com.cliffc.aa.type.TypeStruct.install_cyclic(), com.cliffc.aa.util.IHashMap.isEmpty(), com.cliffc.aa.type.TypeStruct.OLD2APX, com.cliffc.aa.type.TypeStruct.reachable(), com.cliffc.aa.type.TypeStruct.shrink(), and com.cliffc.aa.type.TypeStruct.UF.
Referenced by com.cliffc.aa.HM.TestHM.build_cycle(), com.cliffc.aa.HM.TestHM9.build_cycle(), com.cliffc.aa.HM.TestHM.build_cycle2(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.type.TestApprox.testApprox1(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox4(), com.cliffc.aa.type.TestApprox.testApprox5(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestApprox.testApprox7(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.type.TestType.testType(), com.cliffc.aa.HM.HM9.Struct.val(), and com.cliffc.aa.HM.HM.Struct.val().
at()
Type com.cliffc.aa.type.TypeStruct.at (int idx)
Definition at line 1013 of file TypeStruct.java.
 { return _flds[idx]._t; }  // Type by index
References com.cliffc.aa.type.TypeStruct._flds, and com.cliffc.aa.type.TypeFld._t.
Referenced by com.cliffc.aa.HM.TestHM.build_cycle(), com.cliffc.aa.HM.TestHM9.build_cycle(), com.cliffc.aa.HM.TestHM.build_cycle2(), com.cliffc.aa.type.TestApprox.check_leaf(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.node.LoadNode.get_fld(), com.cliffc.aa.type.TypeTuple.make(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.type.TestApprox.testApprox1(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox4(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestType.testNameCycle(), com.cliffc.aa.TestParse.testParse06(), com.cliffc.aa.TestParse.testParse07(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.type.TestApprox.testTSMeet(), com.cliffc.aa.HM.HM9.Field.val(), com.cliffc.aa.HM.HM.Field.val(), com.cliffc.aa.HM.HM9.T2.walk_types_in(), com.cliffc.aa.HM.HM.T2.walk_types_in(), com.cliffc.aa.HM.HM9.T2.walk_types_out(), and com.cliffc.aa.HM.HM.T2.walk_types_out().
ax_impl_fptr()
static Type com.cliffc.aa.type.TypeStruct.ax_impl_fptr (int alias, int cutoff, Ary< TypeStruct > cutoffs, int d, TypeStruct dold, TypeFunPtr old) static private
Definition at line 569 of file TypeStruct.java.
{
     assert old.interned();
     // TODO: If past depth, never use OLD, forces maximal cloning for the
     // last step, as the last step will be MEET with an arbitrary structure.
     // Use alternative OLD past depth, to keep looping unrelated types
     // folding up.  Otherwise unrelated types might expand endlessly.
     TypeFunPtr nt = OLD2APX.get(old);
     if( nt != null ) return ufind(nt);
     if( old._disp==Type.ANY )
        return old; // no ufind because its old
     // Walk internal structure, meeting into the approximation
     TypeFunPtr nmp = (TypeFunPtr)old.clone();
     OLD2APX.put(old,nmp);
     nmp._disp = ax_impl_ptr(alias,cutoff,cutoffs,d,dold,(TypeMemPtr)old._disp);
     OLD2APX.put(old,null);      // Do not keep sharing the "tails"
     return nmp;
   }
References com.cliffc.aa.type.TypeFunPtr._disp, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.type.TypeStruct.ax_impl_ptr(), com.cliffc.aa.type.Type< T extends Type< T >.clone(), com.cliffc.aa.util.IHashMap.get(), com.cliffc.aa.type.Type< T extends Type< T >.interned(), com.cliffc.aa.type.TypeStruct.OLD2APX, com.cliffc.aa.util.IHashMap.put(), and com.cliffc.aa.type.TypeStruct.ufind().
Referenced by com.cliffc.aa.type.TypeStruct.ax_impl_struct().
ax_impl_ptr()
static TypeMemPtr com.cliffc.aa.type.TypeStruct.ax_impl_ptr (int alias, int cutoff, Ary< TypeStruct > cutoffs, int d, TypeStruct dold, TypeMemPtr old) static private
Definition at line 546 of file TypeStruct.java.
{
     assert old.interned();
     // TODO: If past depth, never use OLD, forces maximal cloning for the
     // last step, as the last step will be MEET with an arbitrary structure.
     // Use alternative OLD past depth, to keep looping unrelated types
     // folding up.  Otherwise unrelated types might expand endlessly.
     TypeMemPtr nt = OLD2APX.get(old);
     if( nt != null ) return ufind(nt);
     // Walk internal structure, meeting into the approximation
     TypeMemPtr nmp = (TypeMemPtr)old.clone();
     OLD2APX.put(old,nmp);
     if( old._obj instanceof TypeStruct )
       nmp._obj = ax_impl_struct(alias,nmp._aliases.test(alias),cutoff,cutoffs,d,dold,(TypeStruct)old._obj);
     else if( old._obj == TypeObj.XOBJ || old._obj==nmp._obj )
       ; // No change to nmp._obj
     else if( old._obj == TypeObj.OBJ )
       nmp._obj = TypeObj.OBJ;   // Falls hard
     else
       throw com.cliffc.aa.AA.unimpl();
     OLD2APX.put(old,null);      // Do not keep sharing the "tails"
     return nmp;
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.TypeStruct.ax_impl_struct(), com.cliffc.aa.type.Type< T extends Type< T >.clone(), com.cliffc.aa.util.IHashMap.get(), com.cliffc.aa.type.Type< T extends Type< T >.interned(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.OBJ, com.cliffc.aa.type.TypeStruct.OLD2APX, com.cliffc.aa.util.IHashMap.put(), com.cliffc.aa.type.Bits< B extends Bits< B >.test(), com.cliffc.aa.type.TypeStruct.ufind(), com.cliffc.aa.AA.unimpl(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.XOBJ.
Referenced by com.cliffc.aa.type.TypeStruct.ax_impl_fptr(), and com.cliffc.aa.type.TypeStruct.ax_impl_struct().
ax_impl_struct()
static TypeStruct com.cliffc.aa.type.TypeStruct.ax_impl_struct (int alias, boolean isnews, int cutoff, Ary< TypeStruct > cutoffs, int d, TypeStruct dold, TypeStruct old) static private
Definition at line 507 of file TypeStruct.java.
{
     assert old.interned();
     // TODO: If past depth, never use OLD, forces maximal cloning for the
     // last step, as the last step will be MEET with an arbitrary structure.
     // Use alternative OLD past depth, to keep looping unrelated types
     // folding up.  Otherwise unrelated types might expand endlessly.
     TypeStruct nt = OLD2APX.get(old);
     if( nt != null ) return ufind(nt);
     if( isnews ) {            // Depth-increasing struct?
       if( d==cutoff ) {       // Cannot increase depth any more
         cutoffs.push(old);    // Save cutoff point for later MEET
         return OLD2APX.get(dold); // Return last valid depth - forces cycle
       } else {
         assert cutoffs == null; // Approaching max depth, make a place to record cutoffs
         if( d+1==cutoff ) cutoffs = new Ary<>(TypeStruct.class);
       }
       d++;              // Increase depth
       dold = old;       // And this is the last TypeStruct seen at this depth
     }
     // Clone the old, to make the approximation into
     TypeStruct nts = (TypeStruct)old.clone();
     nts._flds  = TypeFlds.clone(old._flds);
     OLD2APX.put(old,nts);
     for( int i=0; i<old._flds.length; i++ ) // Fill clone with approximation
       if( old._flds[i]._t._type == TMEMPTR )
         nts._flds[i].setX(ax_impl_ptr (alias,cutoff,cutoffs,d,dold,(TypeMemPtr)old._flds[i]._t));
       else if( old._flds[i]._t._type == TFUNPTR )
         nts._flds[i].setX(ax_impl_fptr(alias,cutoff,cutoffs,d,dold,(TypeFunPtr)old._flds[i]._t));
     if( isnews && d==cutoff ) {
       while( !cutoffs.isEmpty() ) { // At depth limit, meet with cutoff to make the approximation
         Type mt = ax_meet(new BitSetSparse(), nts,cutoffs.pop());
         assert mt==nts;
       }
     }
     OLD2APX.put(old,null); // Do not keep sharing the "tails"
     return nts;
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeFld._t, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.type.TypeStruct.ax_impl_fptr(), com.cliffc.aa.type.TypeStruct.ax_impl_ptr(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.TypeFlds.clone(), com.cliffc.aa.util.IHashMap.get(), com.cliffc.aa.util.Ary< E >.isEmpty(), com.cliffc.aa.type.TypeStruct.OLD2APX, com.cliffc.aa.util.Ary< E >.pop(), com.cliffc.aa.util.Ary< E >.push(), com.cliffc.aa.util.IHashMap.put(), com.cliffc.aa.type.TypeFld.setX(), and com.cliffc.aa.type.TypeStruct.ufind().
Referenced by com.cliffc.aa.type.TypeStruct.approx(), and com.cliffc.aa.type.TypeStruct.ax_impl_ptr().
ax_meet()
static Type com.cliffc.aa.type.TypeStruct.ax_meet (BitSetSparse bs, Type nt, Type old) static private
Definition at line 591 of file TypeStruct.java.
{
     assert old.interned();
     if( nt._hash != 0 && nt.interned() ) return nt.meet(old);
     assert nt._hash==0;         // Not definable yet
     nt = ufind(nt);
     if( nt == old ) return old;
     if( bs.tset(nt._uid,old._uid) ) return nt; // Been there, done that
     // TODO: Make a non-recursive "meet into".
     // Meet old into nt
     switch( nt._type ) {
     case TSCALAR: break; // Nothing to meet
     case TFUNPTR: {
       TypeFunPtr nptr = (TypeFunPtr)nt;
       if( old == Type.NIL || old == Type.XNIL ) return nptr.ax_meet_nil(old);
       if( old == Type.SCALAR )
         return union(nt,old); // Result is a scalar, which changes the structure of the new types.
       if( old == Type.XSCALAR ) break; // Result is the nt unchanged
       if( !(old instanceof TypeFunPtr) ) throw AA.unimpl(); // Not a xscalar, not a funptr, probably falls to scalar
       TypeFunPtr optr = (TypeFunPtr)old;
       nptr._fidxs = nptr._fidxs.meet(optr._fidxs);
       // While structs normally meet, function args *join*, although the return still meets.
       nptr._disp = ax_meet(bs,nptr._disp,optr._disp);
       break;
     }
     case TMEMPTR: {
       TypeMemPtr nptr = (TypeMemPtr)nt;
       if( old == Type.NIL || old == Type.XNIL ) return nptr.ax_meet_nil(old);
       if( old == Type.SCALAR )
         return union(nt,old); // Result is a scalar, which changes the structure of the new types.
       if( old == Type.XSCALAR || old == Type.ANY ) break; // Result is the nt unchanged
       if( !(old instanceof TypeMemPtr) ) throw AA.unimpl(); // Not a xscalar, not a memptr, probably falls to scalar
       TypeMemPtr optr = (TypeMemPtr)old;
       nptr._aliases = nptr._aliases.meet(optr._aliases);
       nptr._obj = (TypeObj)ax_meet(bs,nptr._obj,optr._obj);
       break;
     }
     case TSTRUCT:
       if( old == TypeObj. OBJ || old == TypeObj.ISUSED ) { nt = old; break; }
       if( old == TypeObj.XOBJ || old == TypeObj.UNUSED ) break; // No changes, take nt as it is
       if( !(old instanceof TypeStruct) ) throw AA.unimpl();
       TypeStruct ots = (TypeStruct)old, nts = (TypeStruct)nt;
       // Compute a new target length.  Generally size is unchanged, but will
       // change if mixing structs.
       int len = ots.len(nts);     // New length
       if( len != nts._flds.length ) // Grow/shrink as needed
         nts._flds = Arrays.copyOf(nts._flds, len);
       int clen = Math.min(len,ots._flds.length);
       // Meet all the non-recursive parts
       nts._any &= ots._any ;  nts._use = nts._any;
       nts._open|= ots._open;
       for( int i=0; i<clen; i++ )
         nts._flds[i].cmeet(ots._flds[i]);
       // Now recursively do all common fields
       for( int i=0; i<clen; i++ )
         nts._flds[i].setX(ax_meet(bs,nts._flds[i]._t,ots._flds[i]._t));
       break;
     default: throw AA.unimpl();
     }
     return nt;
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >._any, com.cliffc.aa.type.TypeFunPtr._disp, com.cliffc.aa.type.TypeFunPtr._fidxs, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.Type< T extends Type< T >._hash, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeFld._t, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.type.Type< T extends Type< T >._uid, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.type.TypeFunPtr.ax_meet_nil(), com.cliffc.aa.type.TypeMemPtr.ax_meet_nil(), com.cliffc.aa.type.Type< T extends Type< T >.interned(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.ISUSED, com.cliffc.aa.type.TypeStruct.len(), com.cliffc.aa.type.Bits< B extends Bits< B >.meet(), com.cliffc.aa.type.Type< T extends Type< T >.meet(), com.cliffc.aa.type.Type< T extends Type< T >.NIL, com.cliffc.aa.type.TypeObj< TypeStruct >.OBJ, com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, com.cliffc.aa.util.BitSetSparse.tset(), com.cliffc.aa.type.TypeStruct.ufind(), com.cliffc.aa.AA.unimpl(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED, com.cliffc.aa.type.Type< T extends Type< T >.XNIL, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.XOBJ, and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Referenced by com.cliffc.aa.type.TypeStruct.ax_impl_struct().
check_interned()
static boolean com.cliffc.aa.type.TypeStruct.check_interned (Ary< Type > reachs) static private
Definition at line 770 of file TypeStruct.java.
{
     for( Type t : reachs )
       if( t.intern_lookup() != null )
         return true;
     return false;
   }
Referenced by com.cliffc.aa.type.TypeStruct.approx().
check_uf()
static boolean com.cliffc.aa.type.TypeStruct.check_uf (Ary< Type > reaches) static private
Definition at line 804 of file TypeStruct.java.
{
     int err=0;
     HashMap<Type,Type> ss = new HashMap<>();
     for( Type t : reaches ) {
       Type tt;
       if( ss.get(t) != null || // Found unresolved dup; ts0.equals(ts1) but ts0!=ts1
           ((tt = t.intern_lookup()) != null && tt != t) ||
           ufind(t) != t )
         err++;
       ss.put(t,t);
     }
     return err == 0;
   }
References com.cliffc.aa.type.Type< T extends Type< T >.intern_lookup(), and com.cliffc.aa.type.TypeStruct.ufind().
Referenced by com.cliffc.aa.type.TypeStruct.approx(), com.cliffc.aa.type.TypeStruct.cyclic_meet(), and com.cliffc.aa.type.TypeStruct.sharpen().
close()
TypeStruct com.cliffc.aa.type.TypeStruct.close ()
Definition at line 212 of file TypeStruct.java.
 { assert _open; return malloc(_name,_any,_flds,false).hashcons_freeS(); } // Mark as no-more-fields
References com.cliffc.aa.type.TypeObj< TypeStruct >._any, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeStruct.hashcons_freeS(), and com.cliffc.aa.type.TypeStruct.malloc().
Referenced by com.cliffc.aa.node.ConTypeNode.def_fref().
cmp()
int com.cliffc.aa.type.TypeStruct.cmp (TypeStruct t) private
Definition at line 76 of file TypeStruct.java.
{
     if( !super.equals(t) ) return 0;
     if( _flds.length != t._flds.length || _open != t._open ) return 0;
     if( _flds == t._flds ) return 1;
     for( int i=0; i<_flds.length; i++ )
       if( !Util.eq(_flds[i]._fld,t._flds[i]._fld) || _flds[i]._access!=t._flds[i]._access )
         return 0;
     for( int i=0; i<_flds.length; i++ )
       if( _flds[i]._t!=t._flds[i]._t )
         return -1;              // Some not-pointer-equals child types, must do the full check
     return 1;                   // All child types are pointer-equals, so must be equals.
   }
References com.cliffc.aa.type.TypeFld._access, com.cliffc.aa.type.TypeFld._fld, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeFld._t, and com.cliffc.aa.util.Util.eq().
Referenced by com.cliffc.aa.type.TypeStruct.cycle_equals(), and com.cliffc.aa.type.TypeStruct.equals().
compute_hash()
int com.cliffc.aa.type.TypeStruct.compute_hash ()
Definition at line 66 of file TypeStruct.java.
{
     int hash1 = super.compute_hash(), hash = hash1 +(_open?1023:0);
     assert hash1 != 0;
     // Compute hash from field names and orders and access.
     for( TypeFld fld : _flds ) { assert fld._hash!=0; hash = (hash + fld._hash) | (hash >>> 17); }
     return hash == 0 ? hash1 : hash;
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.Type< T extends Type< T >._hash, com.cliffc.aa.type.TypeStruct._open, and com.cliffc.aa.type.TypeStruct.fld().
Referenced by com.cliffc.aa.HM.HM9.T2._as_flow(), com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.type.TypeStruct._clone(), com.cliffc.aa.type.TypeStruct.cyclic_meet(), com.cliffc.aa.type.TypeStruct.rdual(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.type.TestType.testNameCycle(), com.cliffc.aa.type.TestType.testRecursive(), and com.cliffc.aa.type.TestApprox.testTSMeet().
contains()
boolean com.cliffc.aa.type.TypeStruct.contains (Type t, VBitSet bs) package
Definition at line 1128 of file TypeStruct.java.
{
     if( bs==null ) bs=new VBitSet();
     if( bs.tset(_uid) ) return false;
     for( TypeFld fld : _flds ) if( fld._t==t || fld._t.contains(t,bs) ) return true;
     return false;
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeFld._t, com.cliffc.aa.type.Type< T extends Type< T >.contains(), com.cliffc.aa.type.TypeStruct.fld(), and com.cliffc.aa.util.VBitSet.tset().
crush()
TypeStruct com.cliffc.aa.type.TypeStruct.crush ()
Definition at line 1092 of file TypeStruct.java.
{
     if( _any ) return this;     // No crush on high structs
     TypeFld[] flds = TypeFlds.get(_flds.length);
     // Keep only the display pointer, as it cannot be stomped even with error code
     if( _flds.length>0 && _flds[0].is_display_ptr() )
       flds[0] = _flds[0].simple_ptr();
     for( int i=1; i<_flds.length; i++ ) { // Widen all fields, as-if crushed by errors, even finals.
       // Keep the name and field names untouched.
       TypeFld fld = _flds[i];
       flds[i] = TypeFld.make(fld._fld,Type.ALL,Access.bot(),fld._order);
     }
     // Low input so low output.
     return make_from(flds);
   }
References com.cliffc.aa.type.TypeObj< TypeStruct >._any, com.cliffc.aa.type.TypeFld._fld, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeFld._order, com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.type.TypeFld.Access.bot(), com.cliffc.aa.type.TypeStruct.fld(), com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeFlds.get(), com.cliffc.aa.type.TypeFld.is_display_ptr(), com.cliffc.aa.type.TypeFld.make(), com.cliffc.aa.type.TypeStruct.make_from(), and com.cliffc.aa.type.TypeFld.simple_ptr().
Referenced by com.cliffc.aa.node.NewObjNode.ideal_mono().
cycle_equals()
boolean com.cliffc.aa.type.TypeStruct.cycle_equals (Type o)
Definition at line 110 of file TypeStruct.java.
{
     if( this==o ) return true;
     if( !(o instanceof TypeStruct) ) return false;
     TypeStruct t = (TypeStruct)o;
     TypeStruct t2 = find_other();
     if( t2 !=null ) return t2==t   ; // Already in cycle report equals or not
     TypeStruct t3 = t.find_other();
     if( t3 !=null ) return t3==this;// Already in cycle report equals or not
     int x = cmp(t);
     if( x != -1 ) return x == 1;
     int len = CYCLES._len;
     CYCLES.add(this).add(t);
     boolean eq=cycle_equals0(t);
     assert CYCLES._len==len+2;
     CYCLES._len=len;
     return eq;
   }
References com.cliffc.aa.type.TypeStruct.cmp(), com.cliffc.aa.type.TypeStruct.cycle_equals0(), com.cliffc.aa.type.TypeStruct.CYCLES, com.cliffc.aa.type.TypeStruct.find_other(), and com.cliffc.aa.type.TypeStruct.len().
Referenced by com.cliffc.aa.type.TypeStruct.equals().
cycle_equals0()
boolean com.cliffc.aa.type.TypeStruct.cycle_equals0 (TypeStruct t) private
Definition at line 128 of file TypeStruct.java.
{
     for( int i=0; i<_flds.length; i++ ) {
       Type t0 =   _flds[i]._t;
       Type t1 = t._flds[i]._t;
       if( t0!=t1 &&                // Normally suffices to test ptr-equals only
           (t0==null || t1==null || // Happens when asserting on partially-built cyclic types
            !t0.cycle_equals(t1)) ) // Must do a full cycle-check
         return false;
     }
     return true;
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeFld._t, and com.cliffc.aa.type.Type< T extends Type< T >.cycle_equals().
Referenced by com.cliffc.aa.type.TypeStruct.cycle_equals().
cyclic_meet()
TypeStruct com.cliffc.aa.type.TypeStruct.cyclic_meet (TypeStruct that) private
Definition at line 351 of file TypeStruct.java.
{
     // Walk 'this' and 'that' and map them both (via MEETS0) to a shared common
     // Meet result.  Only walk the cyclic parts... cyclically.  When visiting a
     // finite-sized part we use the normal recursive Meet.  When doing the
     // cyclic part, we use the normal Meet except we need to use the mapped
     // Meet types.  As part of these Meet operations we can end up Meeting Meet
     // types with each other more than once, or more than once from each side -
     // which means already visited Types might need to Meet again, even as they
     // are embedded in other Types - which leads to the need to use Tarjan U-F
     // to union Types on the fly.
     // See if we have worked on this unique pair before.  If so, the cycle has
     // been closed and just return that prior (unfinished) result.
     TypeStruct mt = MEETS0.get(TPair.set(this,that));
     if( mt != null ) return mt; // Cycle has been closed
     mt = this._clone();
     TypeStruct mx = that;
     MEETS0.put(new TPair(this,that),mt);
     // Do a shallow MEET: meet of field names and _any and all things that can
     // be computed without the cycle.  _flds[]._t not filled in yet.
     int len = mt.len(mx); // Length depends on all the Structs Meet'ing here
     if( len != mt._flds.length )
       mt._flds = Arrays.copyOf(mt._flds, len);// escaped a _flds
     if( mt._any  && !mx._any ) mt._any = mt._use = false;
     if(!mt._open &&  mx._open) mt._open=true ;
     for( int i=0; i<len; i++ )
       mt._flds[i] = TypeFld.cmeet(mt._flds[i],i<mx._flds.length ? mx._flds[i] : null);
     mt._name = mt.mtname(mx,mt);
     mt._hash = mt.compute_hash(); // Compute hash now that fields and flags are set
     // Since the result is cyclic, we cannot test the cyclic parts for
     // pre-existence until the entire cycle is built.  We can't intern the
     // partially built parts, but we want to use the normal xmeet call - which
     // normally recursively interns.  Turn off interning with the global
     // RECURSIVE_MEET flag.
     RECURSIVE_MEET++;
     // For-all _ts edges do the Meet.  Some are not-recursive and mapped, some
     // are part of the cycle and mapped, some
     for( int i=0; i<len; i++ ) {
       Type lfi = i<this._flds.length ? this._flds[i]._t : null;
       Type rti = i<that._flds.length ? that._flds[i]._t : null;
       Type mti = (lfi==null) ? rti : (rti==null ? lfi : lfi.meet(rti));
       Type mtx = mt._flds[i]._t; // Prior value, perhaps updated recursively
       Type mts = mtx==null ? mti : mtx.meet(mti); // Meet again
       mt._flds[i].setX(mts);                      // Finally update
     }
     // Check for repeats right now
     for( TypeStruct ts : MEETS0.values() )
       if( ts!=mt && ts.equals(mt) )
         { mt = ts; break; } // Union together
     // Lower recursive-meet flag.  At this point the Meet 'mt' is still
     // speculative and not interned.
     if( --RECURSIVE_MEET > 0 )
       return mt;                // And, if not yet done, just exit with it
     // Remove any final UF before installation.
     // Do not install until the cycle is complete.
     RECURSIVE_MEET++;
     mt = shrink(mt.reachable(),mt);
     Ary<Type> reaches = mt.reachable(); // Recompute reaches after shrink
     assert check_uf(reaches);
     UF.clear();
     RECURSIVE_MEET--;
     // This completes 'mt' as the Meet structure.
     return mt.install_cyclic(reaches);
   }
References com.cliffc.aa.type.TypeObj< O extends TypeObj< O >._any, com.cliffc.aa.type.TypeStruct._clone(), com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeFld._t, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >._use, com.cliffc.aa.type.TypeStruct.check_uf(), com.cliffc.aa.type.TypeFld.cmeet(), com.cliffc.aa.type.TypeStruct.compute_hash(), com.cliffc.aa.type.TypeStruct.equals(), com.cliffc.aa.type.TypeStruct.install_cyclic(), com.cliffc.aa.type.TypeStruct.len(), com.cliffc.aa.type.Type< T extends Type< T >.meet(), com.cliffc.aa.type.TypeStruct.MEETS0, com.cliffc.aa.type.TypeStruct.reachable(), com.cliffc.aa.type.TypeStruct.TPair.set(), com.cliffc.aa.type.TypeFld.setX(), com.cliffc.aa.type.TypeStruct.shrink(), and com.cliffc.aa.type.TypeStruct.UF.
Referenced by com.cliffc.aa.type.TypeStruct.xmeet().
equals()
boolean com.cliffc.aa.type.TypeStruct.equals (Object o)
Definition at line 89 of file TypeStruct.java.
{
     if( this==o ) return true;
     if( !(o instanceof TypeStruct) ) return false;
     TypeStruct t = (TypeStruct)o;
     // While we would like to use the notion of interned Type[] during the
     // normal Type.INTERN check, we also get here during building of cyclic
     // structures for which we'll fall into the cyclic check - as the Type[]s
     // are not interned yet.
     int x = cmp(t);
     if( x != -1 ) return x == 1;
     // Unlike all other non-cyclic structures which are built bottom-up, cyclic
     // types have to be built all-at-once, and thus hash-cons and equality-
     // tested with a cyclic-aware equals check.
     return cycle_equals(t);
   }
References com.cliffc.aa.type.TypeStruct.cmp(), and com.cliffc.aa.type.TypeStruct.cycle_equals().
Referenced by com.cliffc.aa.type.TypeStruct.cyclic_meet(), com.cliffc.aa.type.TypeStruct.TPair.equals(), com.cliffc.aa.type.TypeStruct.install_cyclic(), and com.cliffc.aa.type.TypeStruct.repeats_in_cycles().
find_other()
TypeStruct com.cliffc.aa.type.TypeStruct.find_other () private
Definition at line 106 of file TypeStruct.java.
{
     int idx = CYCLES.find(this);
     return idx != -1 ? CYCLES.at(idx^1) : null;
   }
References com.cliffc.aa.type.TypeStruct.CYCLES.
Referenced by com.cliffc.aa.type.TypeStruct.cycle_equals().
flatten_fields()
TypeObj com.cliffc.aa.type.TypeStruct.flatten_fields () package
Definition at line 1060 of file TypeStruct.java.
{
     TypeFld[] flds = TypeFlds.get(_flds.length);
     for( int i=0; i<_flds.length; i++ )
       flds[i] = _flds[i].make_from(Type.SCALAR,Access.bot());
     return make_from(flds);
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeFld.Access.bot(), com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeFlds.get(), com.cliffc.aa.type.TypeStruct.make_from(), and com.cliffc.aa.type.Type< T extends Type< T >.SCALAR.
fld()
TypeFld com.cliffc.aa.type.TypeStruct.fld (int idx)
Definition at line 1012 of file TypeStruct.java.
 { return _flds[idx]; } // Field by index
References com.cliffc.aa.type.TypeStruct._flds.
Referenced by com.cliffc.aa.type.TypeStruct._dull(), com.cliffc.aa.type.TypeStruct._is_sharp(), com.cliffc.aa.type.TypeStruct.approx(), com.cliffc.aa.type.TypeStruct.compute_hash(), com.cliffc.aa.type.TypeStruct.contains(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.type.TypeStruct.crush(), com.cliffc.aa.node.StoreNode.err(), com.cliffc.aa.type.TypeStruct.fld_find(), com.cliffc.aa.type.TypeMem.fld_is_mod(), com.cliffc.aa.type.TypeStruct.get_cyclic(), com.cliffc.aa.type.TypeStruct.intern_check1(), com.cliffc.aa.node.NewObjNode.NewObjNode(), com.cliffc.aa.node.NewObjNode.promote_forward(), com.cliffc.aa.type.TypeStruct.remove_other_flds(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.type.TestType.testNameCycle(), com.cliffc.aa.TestParse.testParse06(), com.cliffc.aa.TestParse.testParse07(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.type.TestApprox.testTSMeet(), com.cliffc.aa.type.TypeStruct.update(), com.cliffc.aa.type.TypeStruct.walk(), com.cliffc.aa.HM.HM9.T2.walk_types_out(), com.cliffc.aa.HM.HM.T2.walk_types_out(), and com.cliffc.aa.type.TypeStruct.widen().
fld_find()
int com.cliffc.aa.type.TypeStruct.fld_find (String fld)
Definition at line 1038 of file TypeStruct.java.
{
     assert !Util.eq(fld,TypeFld.fldTop) && !Util.eq(fld,TypeFld.fldBot);
     return TypeFld.fld_find(_flds,fld);
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.type.TypeStruct.fld(), com.cliffc.aa.type.TypeFld.fld_find(), com.cliffc.aa.type.TypeFld.fldBot, and com.cliffc.aa.type.TypeFld.fldTop.
Referenced by com.cliffc.aa.type.TypeStruct.add_fld(), com.cliffc.aa.node.StoreNode.err(), com.cliffc.aa.node.LoadNode.find(), com.cliffc.aa.node.StoreNode.find(), com.cliffc.aa.type.TypeMem.fld_is_mod(), com.cliffc.aa.node.LoadNode.get_fld(), com.cliffc.aa.type.TypeStruct.remove_other_flds(), com.cliffc.aa.type.TypeStruct.str(), com.cliffc.aa.type.TypeStruct.update(), com.cliffc.aa.HM.HM9.Field.val(), com.cliffc.aa.HM.HM.Field.val(), com.cliffc.aa.HM.HM9.T2.walk_types_in(), com.cliffc.aa.HM.HM.T2.walk_types_in(), com.cliffc.aa.HM.HM9.T2.walk_types_out(), and com.cliffc.aa.HM.HM.T2.walk_types_out().
flds() [1/3]
TypeFld [] com.cliffc.aa.type.TypeStruct.flds ()
Definition at line 1018 of file TypeStruct.java.
 { return _flds; }
References com.cliffc.aa.type.TypeStruct._flds.
Referenced by com.cliffc.aa.type.TypeStruct._clone(), com.cliffc.aa.type.TypeStruct.add_fld(), com.cliffc.aa.type.TypeStruct.crush(), com.cliffc.aa.type.TypeStruct.flatten_fields(), com.cliffc.aa.type.TypeStruct.init(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.TypeStruct.make_from(), com.cliffc.aa.type.TypeStruct.malloc(), com.cliffc.aa.type.TypeStruct.rdual(), com.cliffc.aa.type.TypeStruct.remove_other_flds(), com.cliffc.aa.type.TypeStruct.set_fld(), com.cliffc.aa.type.TypeStruct.update(), com.cliffc.aa.type.TypeStruct.widen(), com.cliffc.aa.type.TypeStruct.xdual(), and com.cliffc.aa.type.TypeStruct.xmeet1().
flds() [2/3]
static TypeFld [] com.cliffc.aa.type.TypeStruct.flds (Type t1) static
Definition at line 184 of file TypeStruct.java.
 { return TypeFlds.ts(TypeFld.NO_DISP,TypeFld.make_arg(t1,1)); }
References com.cliffc.aa.type.TypeFld.make_arg(), com.cliffc.aa.type.TypeFld.NO_DISP, and com.cliffc.aa.type.TypeFlds.ts().
Referenced by com.cliffc.aa.type.TypeMem.all_reaching_aliases(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.type.TypeMemPtr.depth(), com.cliffc.aa.HM.TestHM.test25(), and com.cliffc.aa.HM.TestHM9.test25().
flds() [3/3]
static TypeFld [] com.cliffc.aa.type.TypeStruct.flds (Type t1, Type t2) static
Definition at line 185 of file TypeStruct.java.
 { return TypeFlds.ts(TypeFld.NO_DISP,TypeFld.make_arg(t1,1), TypeFld.make_arg(t2,2)); }
References com.cliffc.aa.type.TypeFld.make_arg(), com.cliffc.aa.type.TypeFld.NO_DISP, and com.cliffc.aa.type.TypeFlds.ts().
get_cyclic() [1/2]
BitSet com.cliffc.aa.type.TypeStruct.get_cyclic () private
Definition at line 822 of file TypeStruct.java.
{
     return get_cyclic(new BitSet(),new VBitSet(),new Ary<>(Type.class),this);
   }
Referenced by com.cliffc.aa.type.TypeStruct.get_cyclic(), and com.cliffc.aa.type.TypeStruct.install_cyclic().
get_cyclic() [2/2]
static BitSet com.cliffc.aa.type.TypeStruct.get_cyclic (BitSet bcs, VBitSet bs, Ary< Type > stack, Type t) static private
Definition at line 825 of file TypeStruct.java.
{
     if( t.interned() ) return bcs;
     if( bs.test(t._uid) ) {     // If visiting again... have found a cycle t->....->t
       // All on the stack are flagged as being part of a cycle
       int i;
       i=stack._len-1;
       while( i >= 0 && stack.at(i)!=t ) i--;
       if( i== -1 ) return bcs;  // Due to multi-edges, we might not find if dupped, so just ignore
       for( ; i < stack._len; i++ )
         bcs.set(stack.at(i)._uid);
       bcs.set(t._uid);
       return bcs;
     }
     stack.push(t);              // Push on stack, in case a cycle is found
     switch( t._type ) {
     case TMEMPTR: get_cyclic(bcs,bs,stack,((TypeMemPtr)t)._obj ); break;
     case TFUNPTR: get_cyclic(bcs,bs,stack,((TypeFunPtr)t)._disp); break;
     case TFLD   : get_cyclic(bcs,bs,stack,((TypeFld   )t)._t   ); break;
     case TSTRUCT: bs.set(t._uid); for( TypeFld fld : ((TypeStruct)t)._flds ) get_cyclic(bcs,bs,stack,fld); break;
     }
     stack.pop();                // Pop, not part of anothers cycle
     return bcs;
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.util.Ary< E >._len, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.type.Type< T extends Type< T >._uid, com.cliffc.aa.util.Ary< E >.at(), com.cliffc.aa.type.TypeStruct.fld(), com.cliffc.aa.type.TypeStruct.get_cyclic(), com.cliffc.aa.type.Type< T extends Type< T >.interned(), com.cliffc.aa.util.Ary< E >.pop(), com.cliffc.aa.util.Ary< E >.push(), and com.cliffc.aa.util.VBitSet.test().
hashcons_freeS()
TypeStruct com.cliffc.aa.type.TypeStruct.hashcons_freeS () private
Definition at line 178 of file TypeStruct.java.
{
     _flds = TypeFlds.hash_cons(_flds);
     return hashcons_free();
   }
References com.cliffc.aa.type.TypeStruct._flds, and com.cliffc.aa.type.TypeFlds.hash_cons().
Referenced by com.cliffc.aa.type.TypeStruct._sharp(), com.cliffc.aa.type.TypeStruct.close(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.TypeStruct.make_from(), com.cliffc.aa.type.TypeStruct.make_from_flds(), and com.cliffc.aa.type.TypeStruct.xmeet1().
init() [1/2]
O com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.init (byte type, String name, boolean any, boolean use) protected inherited
Definition at line 19 of file TypeObj.java.
{
     super.init(type,name);
     _any=any;
     _use=use;
     return (O)this;
   }
init() [2/2]
TypeStruct com.cliffc.aa.type.TypeStruct.init (String name, boolean any, TypeFld[] flds, boolean open) private
Definition at line 55 of file TypeStruct.java.
{
     super.init(TSTRUCT, name, any, any);
     _flds  = flds;
     _open  = open;
     return this;
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeStruct.init(), and com.cliffc.aa.type.TypeStruct.open().
Referenced by com.cliffc.aa.type.TypeStruct.init(), com.cliffc.aa.type.TypeStruct.malloc(), com.cliffc.aa.type.TypeStruct.rdual(), and com.cliffc.aa.type.TypeStruct.xdual().
install_cyclic()
TypeStruct com.cliffc.aa.type.TypeStruct.install_cyclic (Ary< Type > reachs)
Definition at line 422 of file TypeStruct.java.
{
     // Check for dups.  If found, delete entire cycle, and return original.
     TypeStruct old = (TypeStruct)intern_lookup();
     // If the cycle already exists, just drop the new Type on the floor and let
     // GC get it and return the old Type.
     if( old == null ) {         // Not a dup
       mark_cyclic(get_cyclic(),reachs);
       assert !_cyclic || repeats_in_cycles()==null;
       rdual();               // Complete cyclic dual
       // Insert all members of the cycle into the hashcons.  If self-symmetric,
       // also replace entire cycle with self at each point.
       if( equals(_dual) ) throw AA.unimpl();
       walk( t -> {
           assert t._hash==0 || t._hash==t.compute_hash();
           if( t.interned() ) return false;
           if( t.retern() != t._dual ) t._dual.retern();
           return true;
         });
       assert _flds[0]._t.interned();
       old = this;
     }
     MEETS0.clear();
     return old;
   }
References com.cliffc.aa.type.TypeStruct._cyclic, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeFld._t, com.cliffc.aa.type.TypeStruct.equals(), com.cliffc.aa.type.TypeStruct.get_cyclic(), com.cliffc.aa.type.Type< T extends Type< T >.interned(), com.cliffc.aa.type.TypeStruct.mark_cyclic(), com.cliffc.aa.type.TypeStruct.MEETS0, com.cliffc.aa.type.TypeStruct.rdual(), com.cliffc.aa.type.TypeStruct.repeats_in_cycles(), com.cliffc.aa.AA.unimpl(), and com.cliffc.aa.type.TypeStruct.walk().
Referenced by com.cliffc.aa.HM.HM9.T2._as_flow(), com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.type.TypeStruct.approx(), com.cliffc.aa.type.TypeStruct.cyclic_meet(), com.cliffc.aa.type.TypeStruct.sharpen(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.type.TestType.testNameCycle(), com.cliffc.aa.type.TestType.testRecursive(), and com.cliffc.aa.type.TestApprox.testTSMeet().
intern_check1()
boolean com.cliffc.aa.type.TypeStruct.intern_check1 () package
Definition at line 1150 of file TypeStruct.java.
{
     for( TypeFld fld : _flds )
       if( fld.intern_lookup()==null )
         return false;
     return true;
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct.fld(), and com.cliffc.aa.type.Type< T extends Type< T >.intern_lookup().
is_con()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.is_con inherited
Definition at line 79 of file TypeObj.java.
 { return false; }
is_display()
boolean com.cliffc.aa.type.TypeStruct.is_display () package
Definition at line 220 of file TypeStruct.java.
{
     return
       this==TypeMemPtr.DISPLAY || this==TypeMemPtr.DISPLAY._dual ||
         (_flds.length >= 1 && _flds[0].is_display_ptr());
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeMemPtr.DISPLAY, and com.cliffc.aa.type.TypeFld.is_display_ptr().
is_tup()
boolean com.cliffc.aa.type.TypeStruct.is_tup () private
Definition at line 141 of file TypeStruct.java.
{
     if( _flds.length<=1 ) return true;
     return isDigit(_flds[1]._fld.charAt(0));
   }
References com.cliffc.aa.type.TypeStruct._flds, and com.cliffc.aa.type.TypeStruct.isDigit().
Referenced by com.cliffc.aa.type.TypeStruct.str().
isBitShape()
byte com.cliffc.aa.type.TypeStruct.isBitShape (Type t)
Definition at line 1120 of file TypeStruct.java.
{
     if( isa(t) ) return 0; // Can choose compatible format
     if( t.isa(this) ) return 0; // TODO: really: test same flds, each fld isBitShape
     return 99;
   }
References com.cliffc.aa.type.Type< T extends Type< T >.isa().
isDigit()
static boolean com.cliffc.aa.type.TypeStruct.isDigit (char c) static package
Definition at line 140 of file TypeStruct.java.
 { return '0' <= c && c <= '9'; }
Referenced by com.cliffc.aa.type.TypeStruct.is_tup(), and com.cliffc.aa.type.TypeFld.str().
last()
Type com.cliffc.aa.type.TypeStruct.last ()
Definition at line 1014 of file TypeStruct.java.
 { return _flds[_flds.length-1]._t; }
References com.cliffc.aa.type.TypeStruct._flds, and com.cliffc.aa.type.TypeFld._t.
len() [1/2]
int com.cliffc.aa.type.TypeStruct.len ()
Definition at line 1015 of file TypeStruct.java.
 { return _flds.length; } // Count of fields
References com.cliffc.aa.type.TypeStruct._flds.
Referenced by com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.TypeStruct.cycle_equals(), com.cliffc.aa.type.TypeStruct.cyclic_meet(), and com.cliffc.aa.type.TypeStruct.xmeet1().
len() [2/2]
int com.cliffc.aa.type.TypeStruct.len (TypeStruct tt) private
Definition at line 865 of file TypeStruct.java.
 { return _flds.length <= tt._flds.length ? len0(tt) : tt.len0(this); }
References com.cliffc.aa.type.TypeStruct._flds, and com.cliffc.aa.type.TypeStruct.len0().
Referenced by com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.type.TypeStruct.cyclic_meet(), com.cliffc.aa.type.TypeTuple.make(), com.cliffc.aa.node.NewObjNode.promote_forward(), com.cliffc.aa.HM.HM9.T2.walk_types_out(), and com.cliffc.aa.HM.HM.T2.walk_types_out().
len0()
int com.cliffc.aa.type.TypeStruct.len0 (TypeStruct tmax) private
Definition at line 866 of file TypeStruct.java.
 { return _any ? tmax._flds.length : _flds.length; }
References com.cliffc.aa.type.TypeObj< TypeStruct >._any, and com.cliffc.aa.type.TypeStruct._flds.
Referenced by com.cliffc.aa.type.TypeStruct.len().
make() [1/5]
static TypeStruct com.cliffc.aa.type.TypeStruct.make (String fld_name, Type t) static
Definition at line 190 of file TypeStruct.java.
 { return make(fld_name,t,Access.Final); }
References com.cliffc.aa.type.TypeFld.Access.Final, and com.cliffc.aa.type.TypeStruct.make().
Referenced by com.cliffc.aa.type.TypeStruct.add_fld(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Pair.apply(), com.cliffc.aa.HM.HM.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Triple.apply(), com.cliffc.aa.HM.HM.Pair.apply(), com.cliffc.aa.HM.HM.Triple.apply(), com.cliffc.aa.HM.TestHM.build_cycle(), com.cliffc.aa.HM.TestHM9.build_cycle(), com.cliffc.aa.HM.TestHM.build_cycle2(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.HM.TestHM.make_tups(), com.cliffc.aa.type.TypeStruct.open(), com.cliffc.aa.HM.TestHM9.test02(), com.cliffc.aa.HM.TestHM9.test06(), com.cliffc.aa.HM.TestHM9.test14(), com.cliffc.aa.HM.TestHM9.test18(), com.cliffc.aa.HM.TestHM9.test20(), com.cliffc.aa.HM.TestHM.test25(), com.cliffc.aa.HM.TestHM9.test25(), com.cliffc.aa.HM.TestHM9.test35(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.HM.TestHM9.test41(), com.cliffc.aa.HM.TestHM9.test49(), com.cliffc.aa.HM.TestHM9.test50(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.HM.TestHM.test55(), com.cliffc.aa.HM.TestHM.test57(), com.cliffc.aa.type.TestApprox.testApprox1(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox4(), com.cliffc.aa.type.TestApprox.testApprox5(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestApprox.testApprox7(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.node.TestNodeSmall.testMemoryArgs(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.TestParse.testParse01a(), com.cliffc.aa.TestParse.testParse02(), com.cliffc.aa.TestParse.testParse03(), com.cliffc.aa.TestParse.testParse04(), com.cliffc.aa.TestParse.testParse06(), com.cliffc.aa.TestParse.testParse07(), com.cliffc.aa.TestParse.testParse08(), com.cliffc.aa.TestParse.testParse09(), com.cliffc.aa.TestParse.testParse10(), com.cliffc.aa.TestParse.testParse14(), com.cliffc.aa.TestParse.testParse15(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.type.TestType.testStructTuple(), com.cliffc.aa.type.TestType.testType(), com.cliffc.aa.Parse.type0(), com.cliffc.aa.type.TypeStruct.update(), com.cliffc.aa.HM.HM9.Struct.val(), and com.cliffc.aa.HM.HM.Struct.val().
make() [2/5]
static TypeStruct com.cliffc.aa.type.TypeStruct.make (String fld_name, Type t, Access a) static
Definition at line 191 of file TypeStruct.java.
 { return make(TypeFlds.ts(TypeFld.NO_DISP,TypeFld.make(fld_name,t,a,1))); }
References com.cliffc.aa.type.TypeFld.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.TypeFld.NO_DISP, and com.cliffc.aa.type.TypeFlds.ts().
Referenced by com.cliffc.aa.type.TypeStruct.make().
make() [3/5]
static TypeStruct com.cliffc.aa.type.TypeStruct.make (String name, boolean any, TypeFld[] flds, boolean open) static
Definition at line 207 of file TypeStruct.java.
 { return malloc(name,any,flds,open).hashcons_freeS(); }
References com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeStruct.hashcons_freeS(), com.cliffc.aa.type.TypeStruct.malloc(), and com.cliffc.aa.type.TypeStruct.open().
make() [4/5]
static TypeStruct com.cliffc.aa.type.TypeStruct.make (Type... ts) static
Definition at line 199 of file TypeStruct.java.
{
     TypeFld[] flds = TypeFlds.get(ts.length+1);
     flds[0]=TypeFld.NO_DISP;
     for( int i=0; i<ts.length; i++ )
       flds[i+1] = TypeFld.make(TypeFld.fldBot,ts[i],i+1);
     return make("",false,flds,false);
   }
References com.cliffc.aa.type.TypeFld.fldBot, com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeFlds.get(), com.cliffc.aa.type.TypeFld.make(), com.cliffc.aa.type.TypeStruct.make(), and com.cliffc.aa.type.TypeFld.NO_DISP.
make() [5/5]
static TypeStruct com.cliffc.aa.type.TypeStruct.make (TypeFld... flds) static
Definition at line 196 of file TypeStruct.java.
 { return make("",false,flds,false); }
References com.cliffc.aa.type.TypeStruct.flds(), and com.cliffc.aa.type.TypeStruct.make().
Referenced by com.cliffc.aa.type.TypeStruct.make().
make_from() [1/3]
TypeStruct com.cliffc.aa.type.TypeStruct.make_from (String name)
Definition at line 215 of file TypeStruct.java.
 { return malloc(name,_any,_flds,_open).hashcons_freeS();  }
References com.cliffc.aa.type.TypeObj< TypeStruct >._any, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeStruct.hashcons_freeS(), and com.cliffc.aa.type.TypeStruct.malloc().
Referenced by com.cliffc.aa.type.TypeStruct.crush(), com.cliffc.aa.type.TypeStruct.flatten_fields(), com.cliffc.aa.type.TypeStruct.make_from(), com.cliffc.aa.type.TypeStruct.remove_other_flds(), com.cliffc.aa.type.TypeStruct.set_fld(), com.cliffc.aa.HM.HM9.T2.walk_types_out(), com.cliffc.aa.HM.HM.T2.walk_types_out(), and com.cliffc.aa.type.TypeStruct.widen().
make_from() [2/3]
TypeStruct com.cliffc.aa.type.TypeStruct.make_from (Type head, TypeMem mem, VBitSet visit)
Definition at line 1141 of file TypeStruct.java.
{
     if( visit.tset(_uid) ) return null;
     TypeFld[] flds = TypeFlds.clone(_flds);
     for( int i=0; i<flds.length; i++ )
       flds[i] = flds[i].make_from(head,mem,visit);
     return make_from(flds);
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeFlds.clone(), com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeStruct.make_from(), and com.cliffc.aa.util.VBitSet.tset().
make_from() [3/3]
TypeStruct com.cliffc.aa.type.TypeStruct.make_from (TypeFld[] flds)
Definition at line 217 of file TypeStruct.java.
 { return malloc(_name,_any,flds,_open).hashcons_freeS();  }
References com.cliffc.aa.type.TypeObj< TypeStruct >._any, com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeStruct.hashcons_freeS(), and com.cliffc.aa.type.TypeStruct.malloc().
make_from_flds()
TypeStruct com.cliffc.aa.type.TypeStruct.make_from_flds (TypeStruct ts)
Definition at line 218 of file TypeStruct.java.
 { return malloc(_name,_any,ts._flds,_open).hashcons_freeS();  }
References com.cliffc.aa.type.TypeObj< TypeStruct >._any, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeStruct.hashcons_freeS(), and com.cliffc.aa.type.TypeStruct.malloc().
malloc()
static TypeStruct com.cliffc.aa.type.TypeStruct.malloc (String name, boolean any, TypeFld[] flds, boolean open) static
Definition at line 175 of file TypeStruct.java.
{
     return POOLS[TSTRUCT].<TypeStruct>malloc().init(name, any,flds,open);
   }
References com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeStruct.init(), and com.cliffc.aa.type.TypeStruct.open().
Referenced by com.cliffc.aa.HM.HM9.T2._as_flow(), com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.type.TypeStruct._clone(), com.cliffc.aa.type.TypeStruct.close(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.TypeStruct.make_from(), com.cliffc.aa.type.TypeStruct.make_from_flds(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.type.TestType.testNameCycle(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.type.TestApprox.testTSMeet(), and com.cliffc.aa.type.TypeStruct.xmeet1().
mark_cyclic()
void com.cliffc.aa.type.TypeStruct.mark_cyclic (BitSet bcs, Ary< Type > reaches) private
Definition at line 849 of file TypeStruct.java.
{
     for( Type t : reaches ) {
       if( bcs.get(t._uid) ) {
         assert t.intern_lookup()==null; // Not interned
         t._dual=null;           // Remove any duals, so re-inserted clean
         if( t instanceof TypeStruct ) {
           TypeStruct ts = (TypeStruct)t;
           ts._cyclic = true;
           ts._flds = TypeFlds.hash_cons(ts._flds); // hashcons cyclic arrays
         }
       }
     }
   }
References com.cliffc.aa.type.TypeStruct._cyclic, com.cliffc.aa.type.TypeStruct._flds, and com.cliffc.aa.type.TypeFlds.hash_cons().
Referenced by com.cliffc.aa.type.TypeStruct.install_cyclic().
may_be_con()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.may_be_con inherited
Definition at line 78 of file TypeObj.java.
 { return _any; }
may_nil()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.may_nil inherited
Definition at line 81 of file TypeObj.java.
 { return false; }
meet_loop()
Type com.cliffc.aa.type.TypeStruct.meet_loop (Type t2)
Definition at line 1003 of file TypeStruct.java.
{
     if( this==t2 ) return this;
     if( !(t2 instanceof TypeStruct) ) return meet(t2);
     if( _flds.length != ((TypeStruct)t2)._flds.length ) return meet(t2);
     return xmeet1((TypeStruct)t2,true);
   }
References com.cliffc.aa.type.TypeStruct._flds, and com.cliffc.aa.type.TypeStruct.xmeet1().
meet_nil()
Type com.cliffc.aa.type.TypeStruct.meet_nil (Type nil)
Definition at line 1126 of file TypeStruct.java.
 { return this; }
must_nil()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.must_nil inherited
Definition at line 80 of file TypeObj.java.
 { return false; }
open()
static TypeStruct com.cliffc.aa.type.TypeStruct.open (Type tdisp) static
Definition at line 210 of file TypeStruct.java.
 { return make("",false,TypeFlds.ts(TypeFld.make_tup(tdisp,0)),true); }
References com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.TypeFld.make_tup(), and com.cliffc.aa.type.TypeFlds.ts().
Referenced by com.cliffc.aa.Env.init(), com.cliffc.aa.type.TypeStruct.init(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.TypeStruct.malloc(), and com.cliffc.aa.Parse.tuple().
post_mod()
static boolean com.cliffc.aa.type.TypeStruct.post_mod (Type t) static private
Definition at line 743 of file TypeStruct.java.
{
     t._hash = t.compute_hash();
     DUPS.put(t);
     return true;
   }
References com.cliffc.aa.type.Type< T extends Type< T >._hash, com.cliffc.aa.type.Type< T extends Type< T >.compute_hash(), com.cliffc.aa.type.TypeStruct.DUPS, and com.cliffc.aa.util.IHashMap.put().
Referenced by com.cliffc.aa.type.TypeStruct.shrink().
push()
void com.cliffc.aa.type.TypeStruct.push (Ary< Type > work, Type t) private
Definition at line 795 of file TypeStruct.java.
{
     int y = t._type;
     if( (y==TMEMPTR || y==TFUNPTR || y==TSTRUCT || y==TFLD) &&
         (t._hash == 0 || !t.interned()) && work.find(t)==-1 )
       work.push(t);
   }
References com.cliffc.aa.type.Type< T extends Type< T >._hash, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.util.Ary< E >.find(), com.cliffc.aa.type.Type< T extends Type< T >.interned(), and com.cliffc.aa.util.Ary< E >.push().
Referenced by com.cliffc.aa.type.TypeStruct.reachable().
rdual()
TypeStruct com.cliffc.aa.type.TypeStruct.rdual () package
Definition at line 252 of file TypeStruct.java.
{
     if( _dual != null ) return _dual;
     // Clone the fields for the recursive dual, and grab the field duals
     TypeFld[] flds = TypeFlds.get(_flds.length);
     for( int i=0; i<_flds.length; i++ )
       // Some fields are interned already, the cyclic ones are not.
       flds[i] = _flds[i].interned() ? _flds[i]._dual : _flds[i].xdual();
     TypeStruct dual = _dual = new TypeStruct().init(_name,!_any,flds,!_open);
     if( _hash != 0 ) {
       assert _hash == compute_hash();
       dual._hash = dual.compute_hash(); // Compute hash before recursion
     }
     for( int i=0; i<_flds.length; i++ )
       flds[i] = _flds[i].interned() ? _flds[i]._dual : _flds[i].rdual();
     dual._flds = TypeFlds.hash_cons(flds); // hashcons cyclic arrays
     dual._dual = this;
     dual._cyclic = _cyclic;
     return dual;
   }
References com.cliffc.aa.type.TypeObj< TypeStruct >._any, com.cliffc.aa.type.TypeStruct._cyclic, com.cliffc.aa.type.Type< T extends Type< T >._dual, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeStruct.compute_hash(), com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeFlds.get(), com.cliffc.aa.type.TypeFlds.hash_cons(), com.cliffc.aa.type.TypeStruct.init(), com.cliffc.aa.type.TypeFld.rdual(), and com.cliffc.aa.type.TypeFld.xdual().
Referenced by com.cliffc.aa.type.TypeStruct.install_cyclic().
reachable()
Ary<Type> com.cliffc.aa.type.TypeStruct.reachable ()
Definition at line 779 of file TypeStruct.java.
{
     Ary<Type> work = new Ary<>(new Type[1],0);
     push(work, this);
     int idx=0;
     while( idx < work._len ) {
       Type t = work.at(idx++);
       switch( t._type ) {
       case TMEMPTR:  push(work, ((TypeMemPtr)t)._obj ); break;
       case TFUNPTR:  push(work, ((TypeFunPtr)t)._disp); break;
       case TFLD   :  push(work, ((TypeFld   )t)._t   ); break;
       case TSTRUCT:  for( TypeFld tf : ((TypeStruct)t)._flds ) push(work, tf); break;
       default: break;
       }
     }
     return work;
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.util.Ary< E >._len, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.util.Ary< E >.at(), and com.cliffc.aa.type.TypeStruct.push().
Referenced by com.cliffc.aa.HM.HM9.T2._as_flow(), com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.type.TypeStruct.approx(), com.cliffc.aa.type.TypeStruct.cyclic_meet(), com.cliffc.aa.type.TypeStruct.sharpen(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.type.TestType.testNameCycle(), com.cliffc.aa.type.TestType.testRecursive(), and com.cliffc.aa.type.TestApprox.testTSMeet().
remove_other_flds()
TypeObj com.cliffc.aa.type.TypeStruct.remove_other_flds (String fld, Type live) package
Definition at line 1069 of file TypeStruct.java.
{
     int idx = fld_find(fld);
     if( idx == -1 ) return UNUSED; // No such field, so all fields will be XSCALAR so UNUSED instead
     TypeFld[] flds = TypeFlds.clone(_flds);
     for( int i=0; i<_flds.length; i++ ) {
       if( i != idx ) flds[i] = flds[i].setX(XSCALAR,Access.bot());
       flds[i] = flds[i].hashcons_free();
     }
     return make_from(flds);
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeFld.Access.bot(), com.cliffc.aa.type.TypeFlds.clone(), com.cliffc.aa.type.TypeStruct.fld(), com.cliffc.aa.type.TypeStruct.fld_find(), com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.Type< T extends Type< T >.hashcons_free(), com.cliffc.aa.type.TypeStruct.make_from(), com.cliffc.aa.type.TypeFld.setX(), and com.cliffc.aa.type.TypeObj< TypeStruct >.UNUSED.
repeats_in_cycles() [1/2]
TypeStruct com.cliffc.aa.type.TypeStruct.repeats_in_cycles () package
Definition at line 450 of file TypeStruct.java.
{
     assert _cyclic;
     return repeats_in_cycles(this,new VBitSet());
   }
References com.cliffc.aa.type.TypeStruct._cyclic.
Referenced by com.cliffc.aa.type.TypeStruct.install_cyclic(), com.cliffc.aa.type.TypeStruct.repeats_in_cycles(), and com.cliffc.aa.type.TestApprox.testTSMeet().
repeats_in_cycles() [2/2]
TypeStruct com.cliffc.aa.type.TypeStruct.repeats_in_cycles (TypeStruct head, VBitSet bs) package
Definition at line 454 of file TypeStruct.java.
{
     if( bs.tset(_uid) ) return null;
     if( this!=head && equals(head) ) return this;
     for( TypeFld t : _flds ) {
       TypeStruct ts = t.repeats_in_cycles(head,bs);
       if( ts!=null ) return ts;
     }
     return null;
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct.equals(), com.cliffc.aa.type.TypeStruct.repeats_in_cycles(), and com.cliffc.aa.util.VBitSet.tset().
set_fld()
TypeStruct com.cliffc.aa.type.TypeStruct.set_fld (int i, Type t, Access ff)
Definition at line 1030 of file TypeStruct.java.
{
     TypeFld[] flds = TypeFlds.copyOf(_flds,_flds.length);
     flds[i] = TypeFld.make(_flds[i]._fld,t,ff,_flds[i]._order);
     return make_from(flds);
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeFlds.copyOf(), com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeFld.make(), and com.cliffc.aa.type.TypeStruct.make_from().
Referenced by com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), and com.cliffc.aa.TestParse.test_struct().
sharpen()
static TypeMemPtr com.cliffc.aa.type.TypeStruct.sharpen (TypeMem mem, TypeMemPtr dull) static package
Definition at line 875 of file TypeStruct.java.
{
     assert dull==dull.simple_ptr() && mem.sharp_get(dull)==null;
     // Pass 1:  fill "dull" cache
     HashMap<BitsAlias,TypeMemPtr> dull_cache = new HashMap<>();
     _dull(mem,dull,dull_cache);
     // Pass 2: Stitch together structs with dull pointers to make a possibly cyclic result.
     TypeMemPtr sharp = _sharp(mem,dull,dull_cache);
     assert sharp.interned() == dull_cache.isEmpty();
     // See if we need to cycle-install any cyclic types
     if( dull_cache.isEmpty() )
       return sharp;
     // On exit, cyclic-intern all cyclic things; remove from dull cache.
     RECURSIVE_MEET++;
     TypeStruct mt = (TypeStruct)sharp._obj;
     mt = shrink(mt.reachable(),mt); // No shrinking nor UF expected
     Ary<Type> reaches = mt.reachable(); // Recompute reaches after shrink
     assert check_uf(reaches);
     UF.clear();
     RECURSIVE_MEET--;
     mt = mt.install_cyclic(reaches); // But yes cycles
     sharp = sharp.make_from(mt);
     return mem.sharput(dull,sharp);
   }
References com.cliffc.aa.type.TypeStruct._dull(), com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.TypeStruct._sharp(), com.cliffc.aa.type.TypeStruct.check_uf(), com.cliffc.aa.type.TypeStruct.install_cyclic(), com.cliffc.aa.type.Type< T extends Type< T >.interned(), com.cliffc.aa.type.TypeMemPtr.make_from(), com.cliffc.aa.type.TypeStruct.reachable(), com.cliffc.aa.type.TypeMem.sharp_get(), com.cliffc.aa.type.TypeMem.sharput(), com.cliffc.aa.type.TypeStruct.shrink(), com.cliffc.aa.type.TypeMemPtr.simple_ptr(), and com.cliffc.aa.type.TypeStruct.UF.
Referenced by com.cliffc.aa.type.TypeMem.sharpen().
shrink()
static TypeStruct com.cliffc.aa.type.TypeStruct.shrink (Ary< Type > reaches, TypeStruct tstart) static
Definition at line 657 of file TypeStruct.java.
{
     assert DUPS.isEmpty();
     // Structs never change their hash based on field types.  Set their hash first.
     for( int i=0; i<reaches._len; i++ ) {
       Type t = reaches.at(i);
       if( t instanceof TypeStruct || t instanceof TypeFld )
         t._hash = t.compute_hash();
     }
     // TMPs depend on Structs
     for( int i=0; i<reaches._len; i++ ) {
       Type t = reaches.at(i);
       if( t instanceof TypeMemPtr )
         t._hash = t.compute_hash();
     }
     // TFPs depend on TMPS for display
     for( int i=0; i<reaches._len; i++ ) {
       Type t = reaches.at(i);
       if( t instanceof TypeFunPtr )
         t._hash = t.compute_hash();
     }
     // Need back-edges to do this iteratively in 1 pass.  This algo just sweeps
     // until no more progress, but with generic looping instead of recursion.
     boolean progress = true;
     while( progress ) {
       progress = false;
       DUPS.clear();
       for( int j=0; j<reaches._len; j++ ) {
         Type t = reaches.at(j);
         Type t0 = ufind(t);
         Type t1 = t0.intern_lookup();
         if( t1==null ) t1 = DUPS.get(t0);
         if( t1 != null ) t1 = ufind(t1);
         if( t1 == t0 ) continue; // This one is already interned
         if( t1 != null ) { union(t0,t1); progress = true; continue; }
         switch( t._type ) {
         case TMEMPTR:           // Update TypeMemPtr internal field
           TypeMemPtr tm = (TypeMemPtr)t0;
           TypeObj t4 = tm._obj;
           TypeObj t5 = ufind(t4);
           if( t4 != t5 ) {
             tm._obj = t5;
             progress |= post_mod(tm);
             if( !t5.interned() ) reaches.push(t5);
           }
           break;
         case TFUNPTR:           // Update TypeFunPtr internal field
           TypeFunPtr tfptr = (TypeFunPtr)t0;
           Type t6 = tfptr._disp;
           Type t7 = ufind(t6);
           if( t6 != t7 ) {
             tfptr._disp = t7;
             progress |= post_mod(tfptr);
             if( !t7.interned() ) reaches.push(t7);
           }
           break;
         case TSTRUCT:           // Update all TypeStruct fields
           TypeStruct ts = (TypeStruct)t0;
           for( int i=0; i<ts._flds.length; i++ ) {
             TypeFld tfld = ts._flds[i], tfld2 = ufind(tfld);
             if( tfld != tfld2 ) {
               progress = true;
               ts._flds[i] = tfld2;
             }
           }
           break;
         case TFLD:              // Update all TFlds
           TypeFld tfld = (TypeFld)t0;
           Type tft = tfld._t, t2 = ufind(tft);
           if( tft != t2 ) {
             progress = true;
             tfld.setX(t2);
           }
           break;
         default: break;
         }
         DUPS.put(t0);
       }
     }
     DUPS.clear();
     return ufind(tstart);
   }
References com.cliffc.aa.type.TypeFunPtr._disp, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.Type< T extends Type< T >._hash, com.cliffc.aa.util.Ary< E >._len, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.TypeFld._t, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.util.Ary< E >.at(), com.cliffc.aa.util.IHashMap.clear(), com.cliffc.aa.type.Type< T extends Type< T >.compute_hash(), com.cliffc.aa.type.TypeStruct.DUPS, com.cliffc.aa.util.IHashMap.get(), com.cliffc.aa.type.Type< T extends Type< T >.intern_lookup(), com.cliffc.aa.type.Type< T extends Type< T >.interned(), com.cliffc.aa.util.IHashMap.isEmpty(), com.cliffc.aa.type.TypeStruct.post_mod(), com.cliffc.aa.util.Ary< E >.push(), com.cliffc.aa.util.IHashMap.put(), com.cliffc.aa.type.TypeFld.setX(), and com.cliffc.aa.type.TypeStruct.ufind().
Referenced by com.cliffc.aa.HM.HM9.T2._as_flow(), com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.type.TypeStruct.approx(), com.cliffc.aa.type.TypeStruct.cyclic_meet(), and com.cliffc.aa.type.TypeStruct.sharpen().
str()
SB com.cliffc.aa.type.TypeStruct.str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
Definition at line 145 of file TypeStruct.java.
{
     if( dups.tset(_uid) ) return sb.p('$'); // Break recursive printing cycle
     if( _any ) sb.p('~');
     sb.p(_name);
     boolean is_tup = is_tup();
     sb.p(is_tup ? "(" : "@{");
     // Special shortcut for the all-prims display type
     if( fld_find("!") != -1 && fld_find("math_pi") != -1 ) {
       Type t1 = _flds[1]._t;
       sb.p(t1 instanceof TypeFunPtr
            ? (((TypeFunPtr)t1)._fidxs.above_center() ? "PRIMS" : "LOW_PRIMS")
            : "PRIMS_"+t1);
     } else {
       boolean field_sep=false;
       for( int i=0; i<_flds.length; i++ ) {
         if( !debug && i==0 && Util.eq(_flds[0]._fld,"^") ) continue; // Do not print the ever-present display
         _flds[i].str(sb,dups,mem,debug); // Field name, access mod, type
         sb.p(is_tup ? ", " : "; ");      // Between fields
         field_sep=true;
       }
       if( _open ) sb.p("...");    // More fields allowed
       else if( field_sep ) sb.unchar().unchar();
     }
     sb.p(!is_tup ? "}" : ")");
     return sb;
   }
References com.cliffc.aa.type.TypeObj< TypeStruct >._any, com.cliffc.aa.type.TypeFld._fld, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeFld._t, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.type.TypeStruct.fld_find(), com.cliffc.aa.type.TypeStruct.is_tup(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.TypeFld.str(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.util.SB.unchar().
tups() [1/2]
static TypeFld [] com.cliffc.aa.type.TypeStruct.tups (Type t1, Type t2) static
Definition at line 186 of file TypeStruct.java.
 { return TypeFlds.ts(TypeFld.NO_DISP,TypeFld.make_tup(t1,1), TypeFld.make_tup(t2,2)); }
References com.cliffc.aa.type.TypeFld.make_tup(), com.cliffc.aa.type.TypeFld.NO_DISP, and com.cliffc.aa.type.TypeFlds.ts().
Referenced by com.cliffc.aa.HM.HM.Pair1.Pair1X.apply(), com.cliffc.aa.HM.TestHM.make_tups(), com.cliffc.aa.TestParse.testParse01a(), com.cliffc.aa.TestParse.testParse02(), com.cliffc.aa.TestParse.testParse03(), com.cliffc.aa.TestParse.testParse06(), com.cliffc.aa.TestParse.testParse07(), com.cliffc.aa.TestParse.testParse09(), and com.cliffc.aa.TestParse.testParse14().
tups() [2/2]
static TypeFld [] com.cliffc.aa.type.TypeStruct.tups (Type t1, Type t2, Type t3) static
Definition at line 187 of file TypeStruct.java.
 { return TypeFlds.ts(TypeFld.NO_DISP,TypeFld.make_tup(t1,1), TypeFld.make_tup(t2,2), TypeFld.make_tup(t3,3)); }
References com.cliffc.aa.type.TypeFld.make_tup(), com.cliffc.aa.type.TypeFld.NO_DISP, and com.cliffc.aa.type.TypeFlds.ts().
ufind()
static <T extends Type> T com.cliffc.aa.type.TypeStruct.ufind (T t) static private
Definition at line 751 of file TypeStruct.java.
{
     T t0 = (T)UF.get(t._uid), tu;
     if( t0 == null ) return t;  // One step, hit end of line
     // Find end of U-F line
     while( (tu = (T)UF.get(t0._uid)) != null ) t0=tu;
     // Set whole line to 1-step end of line
     while( (tu = (T)UF.get(t ._uid)) != null ) { assert t._uid != t0._uid; UF.put(t._uid,t0); t=tu; }
     return t0;
   }
References com.cliffc.aa.type.TypeStruct.UF.
Referenced by com.cliffc.aa.type.TypeStruct.ax_impl_fptr(), com.cliffc.aa.type.TypeStruct.ax_impl_ptr(), com.cliffc.aa.type.TypeStruct.ax_impl_struct(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.TypeStruct.check_uf(), and com.cliffc.aa.type.TypeStruct.shrink().
union()
static <T extends Type> T com.cliffc.aa.type.TypeStruct.union (T lost, T kept) static private
Definition at line 760 of file TypeStruct.java.
{
     if( lost == kept ) return kept;
     assert lost._hash==0 || !lost.interned();
     assert UF.get(lost._uid)==null && UF.get(kept._uid)==null;
     assert lost._uid != kept._uid;
     UF.put(lost._uid,kept);
     return kept;
   }
References com.cliffc.aa.type.TypeStruct.UF.
update() [1/3]
TypeStruct com.cliffc.aa.type.TypeStruct.update (Access fin, String fld, Type val)
Definition at line 1044 of file TypeStruct.java.
 { return update(fin,fld,val,false); }
References com.cliffc.aa.type.TypeStruct.fld(), and com.cliffc.aa.type.TypeStruct.update().
Referenced by com.cliffc.aa.type.TypeStruct.update().
update() [2/3]
TypeStruct com.cliffc.aa.type.TypeStruct.update (Access fin, String fld, Type val, boolean precise) private
Definition at line 1046 of file TypeStruct.java.
{
     int idx = fld_find(fld);
     if( idx == -1 ) return this; // Unknown field, assume changes no fields
     // Pointers & Memory to a Store can fall during GCP, and go from r/w to r/o
     // and the StoreNode output must remain monotonic.  This means store
     // updates are allowed to proceed even if in-error.
     if( fin==Access.Final || fin==Access.ReadOnly ) precise=false;
     Type   pval = precise ? val : _flds[idx]._t.meet(val);
     Access pfin = precise ? fin : _flds[idx]._access.meet(fin);
     TypeFld[] flds = TypeFlds.copyOf(_flds,_flds.length);
     flds[idx] = TypeFld.make(fld,pval,pfin,idx);
     return make(_name,_any,flds,_open);
   }
References com.cliffc.aa.type.TypeFld._access, com.cliffc.aa.type.TypeObj< TypeStruct >._any, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeFld._t, com.cliffc.aa.type.TypeFlds.copyOf(), com.cliffc.aa.type.TypeFld.Access.Final, com.cliffc.aa.type.TypeStruct.fld(), com.cliffc.aa.type.TypeStruct.fld_find(), com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeFld.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.TypeFld.Access.meet(), com.cliffc.aa.type.Type< T extends Type< T >.meet(), and com.cliffc.aa.type.TypeFld.Access.ReadOnly.
update() [3/3]
TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.update (TypeInt idx, Type val) inherited
Definition at line 69 of file TypeObj.java.
{
     if( this==ISUSED || this==OBJ ) return this;
     return TypeAry.ARY.dual().update(idx,val);
   }
walk()
void com.cliffc.aa.type.TypeStruct.walk (Predicate< Type > p)
Definition at line 1135 of file TypeStruct.java.
{
     if( p.test(this) )
       for( TypeFld fld : _flds ) fld.walk(p);
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct.fld(), and com.cliffc.aa.type.TypeFld.walk().
Referenced by com.cliffc.aa.node.ConTypeNode.def_fref(), and com.cliffc.aa.type.TypeStruct.install_cyclic().
widen()
TypeStruct com.cliffc.aa.type.TypeStruct.widen ()
Definition at line 1107 of file TypeStruct.java.
{
     boolean widen=false;
     for( TypeFld fld : _flds )
       if( fld._t.widen()!=fld._t )
         { widen=true; break; }
     if( !widen ) return this;
     TypeFld[] flds = TypeFlds.clone(_flds);
     for( int i=0; i<_flds.length; i++ )
       flds[i] = flds[i].setX(_flds[i]._t.widen()).hashcons_free();
     return make_from(flds);
   }
References com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeFld._t, com.cliffc.aa.type.TypeFlds.clone(), com.cliffc.aa.type.TypeStruct.fld(), com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.Type< T extends Type< T >.hashcons_free(), com.cliffc.aa.type.TypeStruct.make_from(), and com.cliffc.aa.type.Type< T extends Type< T >.widen().
xdual()
TypeStruct com.cliffc.aa.type.TypeStruct.xdual () protected
Definition at line 245 of file TypeStruct.java.
{
     TypeFld[] flds = TypeFlds.get(_flds.length);
     for( int i=0; i<_flds.length; i++ ) flds[i] = _flds[i].dual();
     return new TypeStruct().init(_name,!_any,TypeFlds.hash_cons(flds),!_open);
   }
References com.cliffc.aa.type.TypeObj< TypeStruct >._any, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeFlds.get(), com.cliffc.aa.type.TypeFlds.hash_cons(), and com.cliffc.aa.type.TypeStruct.init().
xmeet()
Type com.cliffc.aa.type.TypeStruct.xmeet (Type t) protected
Definition at line 280 of file TypeStruct.java.
{
     switch( t._type ) {
     case TSTRUCT:break;
     case TARY:
     case TLIVE:
     case TSTR:   return OBJ;
     case TOBJ:   return t.xmeet(this);
     case TFUNSIG:
     case TFLT:
     case TINT:
     case TTUPLE :
     case TFUNPTR:
     case TMEMPTR:
     case TRPC:
     case TMEM:   return ALL;
     default: throw typerr(t);   // All else should not happen
     }
     TypeStruct thsi = this;
     TypeStruct that = (TypeStruct)t;
     // INVARIANT: Both this and that are prior existing & interned.
     assert RECURSIVE_MEET > 0 || (thsi.interned() && that.interned());
     // INVARIANT: Both MEETS are empty at the start.  Nothing involved in a
     // potential cycle is interned until the Meet completes.
     assert RECURSIVE_MEET > 0 || (MEETS0.isEmpty());
     // If both are cyclic, we have to do the complicated cyclic-aware meet
     if( _cyclic && that._cyclic )
       return cyclic_meet(that);
     // Recursive but not cyclic; since at least one of these types is
     // non-cyclic normal recursion will bottom-out.
     // If unequal length; then if short is low it "wins" (result is short) else
     // short is high and it "loses" (result is long).
     return thsi._flds.length <= that._flds.length ? thsi.xmeet1(that,false) : that.xmeet1(thsi,false);
   }
References com.cliffc.aa.type.TypeStruct._cyclic, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.type.TypeStruct.cyclic_meet(), com.cliffc.aa.type.TypeStruct.MEETS0, com.cliffc.aa.type.TypeObj< TypeStruct >.OBJ, com.cliffc.aa.type.Type< T extends Type< T >.xmeet(), and com.cliffc.aa.type.TypeStruct.xmeet1().
xmeet1()
TypeStruct com.cliffc.aa.type.TypeStruct.xmeet1 (TypeStruct tmax, boolean is_loop) private
Definition at line 317 of file TypeStruct.java.
{
     int len = _any ? tmax._flds.length : _flds.length;
     // Meet of common elements
     TypeFld[] flds = TypeFlds.get(len);
     for( int i=0; i<_flds.length; i++ )
       flds[i] = is_loop && flds[i]._access==Access.Final
         ? _flds[i]              // Ignore RHS on final fields around loops
         : _flds[i].xmeet(tmax._flds[i]); // Recursive not cyclic
     // Elements only in the longer tuple; the short struct must be high and so
     // is effectively infinitely extended with high fields.
     for( int i=_flds.length; i<len; i++ )
       flds[i] = tmax._flds[i];
     // Ignore name in the non-recursive meet, it will be computed by the outer
     // 'meet' call anyways.
     return malloc("",_any&tmax._any,flds,_open|tmax._open).hashcons_freeS();
   }
References com.cliffc.aa.type.TypeObj< TypeStruct >._any, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >._any, com.cliffc.aa.type.TypeStruct._flds, com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeFld.Access.Final, com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeFlds.get(), com.cliffc.aa.type.TypeStruct.hashcons_freeS(), com.cliffc.aa.type.TypeStruct.len(), com.cliffc.aa.type.TypeStruct.malloc(), and com.cliffc.aa.type.TypeFld.xmeet().
Referenced by com.cliffc.aa.type.TypeStruct.meet_loop(), and com.cliffc.aa.type.TypeStruct.xmeet().
Member Data Documentation
_any
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >._any package inherited
Definition at line 16 of file TypeObj.java.
_cyclic
boolean com.cliffc.aa.type.TypeStruct._cyclic
Definition at line 54 of file TypeStruct.java.
Referenced by com.cliffc.aa.HM.HM9.T2._as_flow(), com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.type.TypeStruct.install_cyclic(), com.cliffc.aa.type.TypeStruct.mark_cyclic(), com.cliffc.aa.type.TypeStruct.rdual(), com.cliffc.aa.type.TypeStruct.repeats_in_cycles(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.type.TestType.testNameCycle(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.type.TestApprox.testTSMeet(), and com.cliffc.aa.type.TypeStruct.xmeet().
_flds
TypeFld [] com.cliffc.aa.type.TypeStruct._flds private
Definition at line 51 of file TypeStruct.java.
Referenced by com.cliffc.aa.type.TypeStruct._clone(), com.cliffc.aa.type.TypeStruct._dull(), com.cliffc.aa.type.TypeStruct._is_sharp(), com.cliffc.aa.type.TypeStruct._sharp(), com.cliffc.aa.type.TypeStruct.add_fld(), com.cliffc.aa.type.TypeStruct.approx(), com.cliffc.aa.type.TypeStruct.at(), com.cliffc.aa.type.TypeStruct.ax_impl_struct(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.TypeStruct.close(), com.cliffc.aa.type.TypeStruct.cmp(), com.cliffc.aa.type.TypeStruct.compute_hash(), com.cliffc.aa.type.TypeStruct.contains(), com.cliffc.aa.type.TypeStruct.crush(), com.cliffc.aa.type.TypeStruct.cycle_equals0(), com.cliffc.aa.type.TypeStruct.cyclic_meet(), com.cliffc.aa.type.TypeStruct.flatten_fields(), com.cliffc.aa.type.TypeStruct.fld(), com.cliffc.aa.type.TypeStruct.fld_find(), com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeStruct.get_cyclic(), com.cliffc.aa.type.TypeStruct.hashcons_freeS(), com.cliffc.aa.type.TypeStruct.init(), com.cliffc.aa.type.TypeStruct.install_cyclic(), com.cliffc.aa.type.TypeStruct.intern_check1(), com.cliffc.aa.type.TypeStruct.is_display(), com.cliffc.aa.type.TypeStruct.is_tup(), com.cliffc.aa.type.TypeStruct.last(), com.cliffc.aa.type.TypeStruct.len(), com.cliffc.aa.type.TypeStruct.len0(), com.cliffc.aa.type.TypeStruct.make_from(), com.cliffc.aa.type.TypeStruct.make_from_flds(), com.cliffc.aa.type.TypeStruct.mark_cyclic(), com.cliffc.aa.type.TypeStruct.meet_loop(), com.cliffc.aa.type.TypeStruct.rdual(), com.cliffc.aa.type.TypeStruct.reachable(), com.cliffc.aa.type.TypeStruct.remove_other_flds(), com.cliffc.aa.type.TypeStruct.repeats_in_cycles(), com.cliffc.aa.type.TypeStruct.set_fld(), com.cliffc.aa.type.TypeStruct.shrink(), com.cliffc.aa.type.TypeStruct.str(), com.cliffc.aa.type.TypeStruct.update(), com.cliffc.aa.type.TypeStruct.walk(), com.cliffc.aa.type.TypeStruct.widen(), com.cliffc.aa.type.TypeStruct.xdual(), com.cliffc.aa.type.TypeStruct.xmeet(), and com.cliffc.aa.type.TypeStruct.xmeet1().
_open
boolean com.cliffc.aa.type.TypeStruct._open
Definition at line 52 of file TypeStruct.java.
Referenced by com.cliffc.aa.type.TypeStruct._clone(), com.cliffc.aa.type.TypeStruct.add_fld(), com.cliffc.aa.type.TypeMem.all_reaching_aliases(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.TypeStruct.close(), com.cliffc.aa.type.TypeStruct.cmp(), com.cliffc.aa.type.TypeStruct.compute_hash(), com.cliffc.aa.type.TypeStruct.cyclic_meet(), com.cliffc.aa.type.TypeStruct.init(), com.cliffc.aa.type.TypeStruct.make_from(), com.cliffc.aa.type.TypeStruct.make_from_flds(), com.cliffc.aa.type.TypeStruct.rdual(), com.cliffc.aa.type.TypeStruct.str(), com.cliffc.aa.type.TypeStruct.update(), com.cliffc.aa.type.TypeStruct.xdual(), and com.cliffc.aa.type.TypeStruct.xmeet1().
_use
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >._use package inherited
Definition at line 17 of file TypeObj.java.
A
final TypeStruct com.cliffc.aa.type.TypeStruct.A = make("a",TypeFlt.FLT64) static
Definition at line 234 of file TypeStruct.java.
Referenced by com.cliffc.aa.type.TestType.testCrush().
ALLSTRUCT
final TypeStruct com.cliffc.aa.type.TypeStruct.ALLSTRUCT = make("",false,new TypeFld[0],true) static
Definition at line 228 of file TypeStruct.java.
Referenced by com.cliffc.aa.type.TestType.testCrush(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.type.TestType.testRecursive(), and com.cliffc.aa.node.TestNodeSmall.tmem().
ANYSTRUCT
final TypeStruct com.cliffc.aa.type.TypeStruct.ANYSTRUCT = make("",true ,new TypeFld[0],false) static
Definition at line 227 of file TypeStruct.java.
Referenced by com.cliffc.aa.node.NewObjNode.dead_type().
ARW
final TypeStruct com.cliffc.aa.type.TypeStruct.ARW = make("a",TypeFlt.FLT64,Access.RW) static
Definition at line 237 of file TypeStruct.java.
Referenced by com.cliffc.aa.type.TestType.testCrush().
C0
final TypeStruct com.cliffc.aa.type.TypeStruct.C0 = make("c",TypeInt.FALSE) static private
Definition at line 235 of file TypeStruct.java.
CYCLES
final Ary<TypeStruct> com.cliffc.aa.type.TypeStruct.CYCLES = new Ary<>(new TypeStruct[0]) static private
Definition at line 105 of file TypeStruct.java.
Referenced by com.cliffc.aa.type.TypeStruct.cycle_equals(), and com.cliffc.aa.type.TypeStruct.find_other().
D1
final TypeStruct com.cliffc.aa.type.TypeStruct.D1 = make("d",TypeInt.TRUE) static private
Definition at line 236 of file TypeStruct.java.
DUPS
final IHashMap com.cliffc.aa.type.TypeStruct.DUPS = new IHashMap() static private
Definition at line 656 of file TypeStruct.java.
Referenced by com.cliffc.aa.type.TypeStruct.post_mod(), and com.cliffc.aa.type.TypeStruct.shrink().
FLT64
final TypeStruct com.cliffc.aa.type.TypeStruct.FLT64 = make(flds(TypeFlt.FLT64)) static
Definition at line 238 of file TypeStruct.java.
INT64_INT64
final TypeStruct com.cliffc.aa.type.TypeStruct.INT64_INT64 = make(flds(TypeInt.INT64,TypeInt.INT64)) static
Definition at line 239 of file TypeStruct.java.
Referenced by com.cliffc.aa.type.TestType.testCrush().
ISUSED
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.ISUSED static inherited
Definition at line 45 of file TypeObj.java.
MEETS0
final HashMap<TPair,TypeStruct> com.cliffc.aa.type.TypeStruct.MEETS0 = new HashMap<>() static private
Definition at line 346 of file TypeStruct.java.
Referenced by com.cliffc.aa.type.TypeStruct.cyclic_meet(), com.cliffc.aa.type.TypeStruct.install_cyclic(), and com.cliffc.aa.type.TypeStruct.xmeet().
NAMEPT
final TypeStruct com.cliffc.aa.type.TypeStruct.NAMEPT = make("Point:",false,POINT._flds,false) static
Definition at line 232 of file TypeStruct.java.
Referenced by com.cliffc.aa.type.TestType.testCrush(), and com.cliffc.aa.node.TestNode.testMonotonic().
OBJ
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.OBJ static inherited
Definition at line 44 of file TypeObj.java.
OLD2APX
final IHashMap com.cliffc.aa.type.TypeStruct.OLD2APX = new IHashMap() static private
Definition at line 476 of file TypeStruct.java.
Referenced by com.cliffc.aa.type.TypeStruct.approx(), com.cliffc.aa.type.TypeStruct.ax_impl_fptr(), com.cliffc.aa.type.TypeStruct.ax_impl_ptr(), and com.cliffc.aa.type.TypeStruct.ax_impl_struct().
POINT
final TypeStruct com.cliffc.aa.type.TypeStruct.POINT = make(flds(TypeFlt.FLT64,TypeFlt.FLT64)) static
Definition at line 231 of file TypeStruct.java.
Referenced by com.cliffc.aa.type.TestType.testCrush().
TFLT64
final TypeStruct com.cliffc.aa.type.TypeStruct.TFLT64 = make(".",TypeFlt.FLT64) static package
Definition at line 233 of file TypeStruct.java.
Referenced by com.cliffc.aa.type.TestType.testStructTuple().
TYPES
final TypeStruct [] com.cliffc.aa.type.TypeStruct.TYPES = new TypeStruct[]{ALLSTRUCT,POINT,NAMEPT,A,C0,D1,ARW,INT64_INT64} static package
Definition at line 242 of file TypeStruct.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.ALL_TYPES(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.type.TestType.testLoad(), com.cliffc.aa.type.TestType.testNameCycle(), and com.cliffc.aa.type.TestApprox.testTSMeet().
UF
final NonBlockingHashMapLong<Type> com.cliffc.aa.type.TypeStruct.UF = new NonBlockingHashMapLong<>() static
Definition at line 475 of file TypeStruct.java.
Referenced by com.cliffc.aa.HM.HM9.T2._as_flow(), com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.type.TypeStruct.approx(), com.cliffc.aa.type.TypeStruct.cyclic_meet(), com.cliffc.aa.type.TypeStruct.sharpen(), com.cliffc.aa.type.TypeStruct.ufind(), and com.cliffc.aa.type.TypeStruct.union().
UNUSED
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED static inherited
Definition at line 46 of file TypeObj.java.
XOBJ
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.XOBJ static inherited
Definition at line 47 of file TypeObj.java.
The documentation for this class was generated from the following file:
TypeStruct.java