aa: com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotE Class Reference
com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotE Class Reference
Public Member Functions
SnapshotE ()
boolean hasNext ()
Map.Entry< TypeK, TypeV > next ()
void remove ()
Package Attributes
final SnapshotV _ss
Detailed Description
Definition at line 1328 of file NonBlockingHashMap.java.
Constructor & Destructor Documentation
SnapshotE()
com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotE.SnapshotE ()
Definition at line 1330 of file NonBlockingHashMap.java.
 { _ss = new SnapshotV(); }
Member Function Documentation
hasNext()
boolean com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotE.hasNext ()
Definition at line 1333 of file NonBlockingHashMap.java.
 { return _ss.hasNext(); }
References com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.hasNext().
next()
Map.Entry<TypeK,TypeV> com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotE.next ()
Definition at line 1332 of file NonBlockingHashMap.java.
 { _ss.next(); return new NBHMEntry((TypeK)_ss._prevK,_ss._prevV); }
References com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._prevK, com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._prevV, and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.next().
remove()
void com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotE.remove ()
Definition at line 1331 of file NonBlockingHashMap.java.
 { _ss.remove(); }
References com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.remove().
Member Data Documentation
_ss
final SnapshotV com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotE._ss package
Definition at line 1329 of file NonBlockingHashMap.java.
The documentation for this class was generated from the following file:
NonBlockingHashMap.java