aa: com.cliffc.aa.HM.HM2.HMVar Class Reference
com.cliffc.aa.HM.HM2.HMVar Class Reference
Public Member Functions
String _str ()
String str ()
String toString ()
Type type ()
Package Functions
HMVar ()
HMVar (Type t)
HMType _fresh (HashSet< HMVar > nongen, HashMap< HMType, HMType > vars)
HMType find ()
HMType fresh (HashSet< HMVar > nongen)
boolean is_top ()
boolean occurs_in (HashSet< HMVar >nongen)
boolean occurs_in (HMType[] args)
boolean occurs_in_type (HMType v)
HMType union (HMType that)
Static Package Functions
static void reset ()
Package Attributes
HMType _u
Private Attributes
Type _t
final int _uid
Static Private Attributes
static int CNT
Detailed Description
Definition at line 220 of file HM2.java.
Constructor & Destructor Documentation
HMVar() [1/2]
com.cliffc.aa.HM.HM2.HMVar.HMVar () package
Definition at line 224 of file HM2.java.
 { this(Type.ANY); }
References com.cliffc.aa.type.Type< T extends Type< T >.ANY.
Referenced by com.cliffc.aa.HM.HM2.HMVar.union().
HMVar() [2/2]
com.cliffc.aa.HM.HM2.HMVar.HMVar (Type t) package
Definition at line 225 of file HM2.java.
 { _uid=CNT++; _t=t; }
References com.cliffc.aa.HM.HM2.HMVar._t, com.cliffc.aa.HM.HM2.HMVar._uid, and com.cliffc.aa.HM.HM2.HMVar.CNT.
Member Function Documentation
_fresh()
HMType com.cliffc.aa.HM.HM2.HMType._fresh (HashSet< HMVar > nongen, HashMap< HMType, HMType > vars) package inherited
Definition at line 186 of file HM2.java.
{
       HMType t2 = find();
       if( t2 instanceof HMVar ) {
         return t2.occurs_in(nongen) //
           ? t2                      // Keep same var
           : vars.computeIfAbsent(t2, e -> new HMVar(((HMVar)t2)._t));
       } else {
         Oper op = (Oper)t2;
         HMType[] args = new HMType[op._args.length];
         for( int i=0; i<args.length; i++ )
           args[i] = op._args[i]._fresh(nongen,vars);
         return new Oper(op._name,args);
       }
     }
References com.cliffc.aa.HM.HM2.Oper._args, com.cliffc.aa.HM.HM2.HMType._fresh(), com.cliffc.aa.HM.HM2.Oper._name, com.cliffc.aa.HM.HM2.HMType.find(), and com.cliffc.aa.HM.HM2.HMType.occurs_in().
Referenced by com.cliffc.aa.HM.HM2.HMType._fresh(), and com.cliffc.aa.HM.HM2.HMType.fresh().
_str()
String com.cliffc.aa.HM.HM2.HMVar._str ()
Reimplemented from com.cliffc.aa.HM.HM2.HMType.
Definition at line 233 of file HM2.java.
{
       String s = "v"+_uid;
       if( _t!=Type.ANY ) s += ":"+_t.str(new SB(),new VBitSet(),null,false);
       return s;
     }
References com.cliffc.aa.HM.HM2.HMVar._t, com.cliffc.aa.HM.HM2.HMVar._uid, com.cliffc.aa.type.Type< T extends Type< T >.ANY, and com.cliffc.aa.type.Type< T extends Type< T >.str().
Referenced by com.cliffc.aa.HM.HM2.HMVar.toString().
find()
HMType com.cliffc.aa.HM.HM2.HMVar.find () package
Reimplemented from com.cliffc.aa.HM.HM2.HMType.
Definition at line 239 of file HM2.java.
{
       HMType u = _u;
       if( u==null ) return this; // Top of union tree
       if( u._u==null ) return u; // One-step from top
       // Classic U-F rollup
       while( u._u!=null ) u = u._u; // Find the top
       HMType x = this;              // Collapse all to top
       while( x._u!=u ) { HMType tmp = x._u; x._u=u; x=tmp;}
       return u;
     }
References com.cliffc.aa.HM.HM2.HMType._u.
Referenced by com.cliffc.aa.HM.HM2.HMVar.union().
fresh()
HMType com.cliffc.aa.HM.HM2.HMType.fresh (HashSet< HMVar > nongen) package inherited
Definition at line 182 of file HM2.java.
{
       HashMap<HMType,HMType> vars = new HashMap<>();
       return _fresh(nongen,vars);
     }
References com.cliffc.aa.HM.HM2.HMType._fresh().
Referenced by com.cliffc.aa.HM.HM2.Ident.hm().
is_top()
boolean com.cliffc.aa.HM.HM2.HMType.is_top () package inherited
Definition at line 180 of file HM2.java.
 { return _u==null; }
References com.cliffc.aa.HM.HM2.HMType._u.
Referenced by com.cliffc.aa.HM.HM2.HMType.occurs_in_type(), and com.cliffc.aa.HM.HM2.HMVar.type().
occurs_in() [1/2]
boolean com.cliffc.aa.HM.HM2.HMType.occurs_in (HashSet< HMVar > nongen) package inherited
Definition at line 201 of file HM2.java.
{
       for( HMVar x : nongen ) if( occurs_in_type(x) ) return true;
       return false;
     }
References com.cliffc.aa.HM.HM2.HMType.occurs_in_type().
Referenced by com.cliffc.aa.HM.HM2.HMType._fresh(), and com.cliffc.aa.HM.HM2.HMType.occurs_in_type().
occurs_in() [2/2]
boolean com.cliffc.aa.HM.HM2.HMType.occurs_in (HMType[] args) package inherited
Definition at line 205 of file HM2.java.
{
       for( HMType x : args ) if( occurs_in_type(x) ) return true;
       return false;
     }
References com.cliffc.aa.HM.HM2.HMType.occurs_in_type().
occurs_in_type()
boolean com.cliffc.aa.HM.HM2.HMType.occurs_in_type (HMType v) package inherited
Definition at line 209 of file HM2.java.
{
       assert is_top();
       HMType y = v.find();
       if( y==this )
         return true;
       if( y instanceof Oper )
         return occurs_in(((Oper)y)._args);
       return false;
     }
References com.cliffc.aa.HM.HM2.HMType.find(), com.cliffc.aa.HM.HM2.HMType.is_top(), and com.cliffc.aa.HM.HM2.HMType.occurs_in().
Referenced by com.cliffc.aa.HM.HM2.HMType.occurs_in(), and com.cliffc.aa.HM.HM2.HMVar.union().
reset()
static void com.cliffc.aa.HM.HM2.HMVar.reset () static package
Definition at line 226 of file HM2.java.
 { CNT=1; }
References com.cliffc.aa.HM.HM2.HMVar.CNT.
Referenced by com.cliffc.aa.HM.HM2.reset().
str()
String com.cliffc.aa.HM.HM2.HMType.str () inherited
Definition at line 178 of file HM2.java.
 { return find()._str(); }
References com.cliffc.aa.HM.HM2.HMType._str(), and com.cliffc.aa.HM.HM2.HMType.find().
Referenced by com.cliffc.aa.HM.HM2.Oper._str().
toString()
String com.cliffc.aa.HM.HM2.HMVar.toString ()
Definition at line 228 of file HM2.java.
{
       String s = _str();
       if( _u!=null ) s += ">>"+_u;
       return s;
     }
References com.cliffc.aa.HM.HM2.HMVar._str(), and com.cliffc.aa.HM.HM2.HMType._u.
type()
Type com.cliffc.aa.HM.HM2.HMVar.type ()
Definition at line 227 of file HM2.java.
 { assert is_top(); return _t; }
References com.cliffc.aa.HM.HM2.HMVar._t, and com.cliffc.aa.HM.HM2.HMType.is_top().
union()
HMType com.cliffc.aa.HM.HM2.HMVar.union (HMType that) package
Reimplemented from com.cliffc.aa.HM.HM2.HMType.
Definition at line 249 of file HM2.java.
{
       if( _u!=null ) return find().union(that);
       if( that instanceof HMVar ) that = that.find();
       if( this==that ) return this; // Do nothing
       if( occurs_in_type(that) )
         throw new RuntimeException("recursive unification");
       if( that instanceof HMVar ) {
         HMVar v2 = (HMVar)that;
         v2._t = _t.meet(v2._t);
       }
       else assert _t==Type.ANY; // Else this var is un-MEETd with any Con
       return _u = that;         // Classic U-F union
     }
References com.cliffc.aa.HM.HM2.HMVar._t, com.cliffc.aa.HM.HM2.HMType._u, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.HM.HM2.HMType.find(), com.cliffc.aa.HM.HM2.HMVar.find(), com.cliffc.aa.HM.HM2.HMVar.HMVar(), com.cliffc.aa.type.Type< T extends Type< T >.meet(), com.cliffc.aa.HM.HM2.HMType.occurs_in_type(), and com.cliffc.aa.HM.HM2.HMType.union().
Referenced by com.cliffc.aa.HM.HM2.Let.hm().
Member Data Documentation
_t
Type com.cliffc.aa.HM.HM2.HMVar._t private
Definition at line 221 of file HM2.java.
Referenced by com.cliffc.aa.HM.HM2.HMVar._str(), com.cliffc.aa.HM.HM2.HMVar.HMVar(), com.cliffc.aa.HM.HM2.HMVar.type(), and com.cliffc.aa.HM.HM2.HMVar.union().
_u
HMType com.cliffc.aa.HM.HM2.HMType._u package inherited
Definition at line 175 of file HM2.java.
Referenced by com.cliffc.aa.HM.HM2.HMVar.find(), com.cliffc.aa.HM.HM2.HMType.is_top(), com.cliffc.aa.HM.HM2.HMVar.toString(), and com.cliffc.aa.HM.HM2.HMVar.union().
_uid
final int com.cliffc.aa.HM.HM2.HMVar._uid private
Definition at line 222 of file HM2.java.
Referenced by com.cliffc.aa.HM.HM2.HMVar._str(), and com.cliffc.aa.HM.HM2.HMVar.HMVar().
CNT
int com.cliffc.aa.HM.HM2.HMVar.CNT static private
Definition at line 223 of file HM2.java.
Referenced by com.cliffc.aa.HM.HM2.HMVar.HMVar(), and com.cliffc.aa.HM.HM2.HMVar.reset().
The documentation for this class was generated from the following file:
HM2.java