aa: com.cliffc.aa.util.IBitSet.Iter Class Reference
com.cliffc.aa.util.IBitSet.Iter Class Reference
Public Member Functions
boolean hasNext ()
Integer next ()
Package Attributes
int _i =-1
Detailed Description
Definition at line 135 of file IBitSet.java.
Member Function Documentation
hasNext()
boolean com.cliffc.aa.util.IBitSet.Iter.hasNext ()
Definition at line 137 of file IBitSet.java.
{
       int idx;
       while( (idx=idx(++_i)) < _bits._len )
         if( (_bits._es[idx]&mask(_i)) != 0 )
           return true;
       return false;
     }
References com.cliffc.aa.util.IBitSet._bits, com.cliffc.aa.util.AryInt._es, com.cliffc.aa.util.IBitSet.Iter._i, com.cliffc.aa.util.AryInt._len, com.cliffc.aa.util.IBitSet.idx(), and com.cliffc.aa.util.IBitSet.mask().
next()
Integer com.cliffc.aa.util.IBitSet.Iter.next ()
Definition at line 144 of file IBitSet.java.
{
       if( idx(_i) < _bits._len ) return _i;
       throw new java.util.NoSuchElementException();
     }
References com.cliffc.aa.util.IBitSet._bits, com.cliffc.aa.util.IBitSet.Iter._i, com.cliffc.aa.util.AryInt._len, and com.cliffc.aa.util.IBitSet.idx().
Member Data Documentation
_i
int com.cliffc.aa.util.IBitSet.Iter._i =-1 package
Definition at line 136 of file IBitSet.java.
Referenced by com.cliffc.aa.util.IBitSet.Iter.hasNext(), and com.cliffc.aa.util.IBitSet.Iter.next().
The documentation for this class was generated from the following file:
IBitSet.java