aa: com.cliffc.aa.HM.HM8.Lambda Class Reference
com.cliffc.aa.HM.HM8.Lambda Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Lambda (Syntax body, String... args)
void add_work (Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
T2 lookup (String name)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
T2 post ()
T2 pre ()
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
T2 targ (int i)
Package Attributes
final String[] _args
final Syntax _body
VStack _nongen
Syntax _par
T2 _post
T2 _pre
T2 _t
T2[] _targs
Detailed Description
Definition at line 357 of file HM8.java.
Constructor & Destructor Documentation
Lambda()
com.cliffc.aa.HM.HM8.Lambda.Lambda (Syntax body, String... args) package
Definition at line 361 of file HM8.java.
{
       _args=args;
       _body=body;
       _targs = new T2[args.length];
       for( int i=0; i<args.length; i++ ) _targs[i] = T2.make_leaf();
     }
References com.cliffc.aa.HM.HM8.Lambda._args, com.cliffc.aa.HM.HM8.Lambda._body, com.cliffc.aa.HM.HM8.Lambda._targs, and com.cliffc.aa.HM.HM8.T2.make_leaf().
Member Function Documentation
add_work()
void com.cliffc.aa.HM.HM8.Lambda.add_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 407 of file HM8.java.
{
       work.push(_par );
       work.push(_body);
       for( int i=0; i<_targs.length; i++ )
         if( targ(i).occurs_in_type(find()) ) work.addAll(_targs[i]._deps);
     }
References com.cliffc.aa.HM.HM8.Lambda._body, com.cliffc.aa.HM.HM8.Syntax._par, com.cliffc.aa.HM.HM8.Lambda._targs, com.cliffc.aa.HM.HM8.Worklist.addAll(), com.cliffc.aa.HM.HM8.Syntax.find(), com.cliffc.aa.HM.HM8.Worklist.push(), and com.cliffc.aa.HM.HM8.Lambda.targ().
debug_find()
T2 com.cliffc.aa.HM.HM8.Syntax.debug_find () package inherited
Definition at line 249 of file HM8.java.
 { return _t.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM8.Syntax._t, and com.cliffc.aa.HM.HM8.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM8.hm().
find()
T2 com.cliffc.aa.HM.HM8.Syntax.find () package inherited
Definition at line 245 of file HM8.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._t, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.T2._occurs_in(), com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Ident.hm(), com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.HM.HM8.Apply.is_if_nil(), and com.cliffc.aa.HM.HM8.Struct.prep_tree().
hm()
boolean com.cliffc.aa.HM.HM8.Lambda.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 379 of file HM8.java.
{
       boolean progress = false;
       // Lambda memory: pre-memory unifies with body-pre, post-memory unifies with post-body.
       progress |= pre ().unify(_body.pre (),work);
       progress |= post().unify(_body.post(),work);
       if( work==null && progress ) return true;
       // The normal lambda work
       T2 old = find();
       if( old.is_err() ) return false;
       if( old.is_fun() ) {      // Already a function?  Compare-by-parts
         for( int i=0; i<_targs.length; i++ )
           if( old.args(i).unify(targ(i),work) )
             { progress=true; break; }
         if( !progress && !old.args(_targs.length).unify(_body.find(),work) )
           return false;           // Shortcut: no progress, no allocation
       }
       // Make a new T2 for progress
       T2[] targs = Arrays.copyOf(_targs,_targs.length+1);
       targs[_targs.length] = _body.find();
       T2 fun = T2.make_fun(targs);
       return old.unify(fun,work);
     }
References com.cliffc.aa.HM.HM8.Lambda._body, com.cliffc.aa.HM.HM8.Lambda._targs, com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.HM.HM8.Syntax.find(), com.cliffc.aa.HM.HM8.T2.is_err(), com.cliffc.aa.HM.HM8.T2.is_fun(), com.cliffc.aa.HM.HM8.T2.make_fun(), com.cliffc.aa.HM.HM8.Syntax.post(), com.cliffc.aa.HM.HM8.Syntax.pre(), com.cliffc.aa.HM.HM8.Lambda.targ(), and com.cliffc.aa.HM.HM8.T2.unify().
lookup()
T2 com.cliffc.aa.HM.HM8.Lambda.lookup (String name) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 402 of file HM8.java.
{
       for( int i=0; i<_args.length; i++ )
         if( Util.eq(_args[i],name) ) return targ(i);
       return _par==null ? null : _par.lookup(name);
     }
References com.cliffc.aa.HM.HM8.Lambda._args, com.cliffc.aa.HM.HM8.Syntax._par, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM8.Syntax.lookup(), and com.cliffc.aa.HM.HM8.Lambda.targ().
more_work()
boolean com.cliffc.aa.HM.HM8.Lambda.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 424 of file HM8.java.
{
       if( !more_work_impl(work) ) return false;
       return _body.more_work(work);
     }
References com.cliffc.aa.HM.HM8.Lambda._body, com.cliffc.aa.HM.HM8.Syntax.more_work(), and com.cliffc.aa.HM.HM8.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM8.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 283 of file HM8.java.
{
       boolean no_more_work = work.has(this) || !hm(null); // Either on worklist, or no-progress
       return no_more_work;
     }
References com.cliffc.aa.HM.HM8.Worklist.has(), and com.cliffc.aa.HM.HM8.Syntax.hm().
Referenced by com.cliffc.aa.HM.HM8.Con.more_work(), com.cliffc.aa.HM.HM8.Ident.more_work(), com.cliffc.aa.HM.HM8.Lambda.more_work(), com.cliffc.aa.HM.HM8.Let.more_work(), com.cliffc.aa.HM.HM8.Apply.more_work(), com.cliffc.aa.HM.HM8.Struct.more_work(), and com.cliffc.aa.HM.HM8.Field.more_work().
p()
String com.cliffc.aa.HM.HM8.Syntax.p () inherited
Definition at line 291 of file HM8.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM8.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM8.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 292 of file HM8.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM8.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM8.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM8.Syntax.p1(), com.cliffc.aa.HM.HM8.Syntax.p2(), and com.cliffc.aa.HM.HM8.T2.str().
Referenced by com.cliffc.aa.HM.HM8.Syntax.p(), com.cliffc.aa.HM.HM8.Lambda.p2(), com.cliffc.aa.HM.HM8.Let.p2(), com.cliffc.aa.HM.HM8.Apply.p2(), com.cliffc.aa.HM.HM8.Struct.p2(), and com.cliffc.aa.HM.HM8.Field.p2().
p1()
SB com.cliffc.aa.HM.HM8.Lambda.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 372 of file HM8.java.
{
       sb.p("{ ");
       for( String arg : _args ) sb.p(arg).p(' ');
       return sb.p(" -> ... } ");
     }
References com.cliffc.aa.HM.HM8.Lambda._args, and com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM8.Lambda.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 377 of file HM8.java.
 { return _body.p0(sb,dups); }
References com.cliffc.aa.HM.HM8.Lambda._body, and com.cliffc.aa.HM.HM8.Syntax.p0().
post()
T2 com.cliffc.aa.HM.HM8.Syntax.post () package inherited
Definition at line 254 of file HM8.java.
               {
       T2 t = _post.find();
       return t==_post ? t : (_post=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._post, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), and com.cliffc.aa.HM.HM8.Field.hm().
pre()
T2 com.cliffc.aa.HM.HM8.Syntax.pre () package inherited
Definition at line 250 of file HM8.java.
              {
       T2 t = _pre.find();
       return t==_pre ? t : (_pre=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._pre, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), and com.cliffc.aa.HM.HM8.Field.hm().
prep_lookup_deps()
void com.cliffc.aa.HM.HM8.Lambda.prep_lookup_deps (Ident id) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 420 of file HM8.java.
{
       for( int i=0; i<_args.length; i++ )
         if( Util.eq(_args[i],id._name) ) _targs[i].push_update(id);
     }
References com.cliffc.aa.HM.HM8.Lambda._args, com.cliffc.aa.HM.HM8.Lambda._targs, com.cliffc.aa.util.Util.eq(), and com.cliffc.aa.HM.HM8.T2.push_update().
prep_tree()
int com.cliffc.aa.HM.HM8.Lambda.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 413 of file HM8.java.
{
       prep_tree_impl(par,nongen,work,T2.make_leaf());
       VStack vs = nongen;
       for( int i=0; i<_targs.length; i++ )
         vs = new VStack(vs,_targs[i]);
       return _body.prep_tree(this,vs,work) + 1;
     }
References com.cliffc.aa.HM.HM8.Lambda._body, com.cliffc.aa.HM.HM8.Lambda._targs, com.cliffc.aa.HM.HM8.T2.make_leaf(), com.cliffc.aa.HM.HM8.Syntax.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
prep_tree_impl()
final void com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 267 of file HM8.java.
{
       _par=par;
       _pre = T2.make_mem();
       _t=t;
       _post = T2.make_mem();
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM8.Syntax._nongen, com.cliffc.aa.HM.HM8.Syntax._par, com.cliffc.aa.HM.HM8.Syntax._post, com.cliffc.aa.HM.HM8.Syntax._pre, com.cliffc.aa.HM.HM8.Syntax._t, com.cliffc.aa.HM.HM8.T2.make_mem(), and com.cliffc.aa.HM.HM8.Worklist.push().
Referenced by com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), com.cliffc.aa.HM.HM8.Lambda.prep_tree(), com.cliffc.aa.HM.HM8.Let.prep_tree(), com.cliffc.aa.HM.HM8.Apply.prep_tree(), com.cliffc.aa.HM.HM8.Struct.prep_tree(), and com.cliffc.aa.HM.HM8.Field.prep_tree().
str()
SB com.cliffc.aa.HM.HM8.Lambda.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 367 of file HM8.java.
{
       sb.p("{ ");
       for( String arg : _args ) sb.p(arg).p(' ');
       return _body.str(sb.p("-> ")).p(" }");
     }
References com.cliffc.aa.HM.HM8.Lambda._args, com.cliffc.aa.HM.HM8.Lambda._body, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM8.Syntax.str().
targ()
T2 com.cliffc.aa.HM.HM8.Lambda.targ (int i) package
Definition at line 378 of file HM8.java.
 { T2 targ = _targs[i].find(); return targ==_targs[i] ? targ : (_targs[i]=targ); }
References com.cliffc.aa.HM.HM8.Lambda._targs, com.cliffc.aa.HM.HM8.T2.find(), and com.cliffc.aa.HM.HM8.Lambda.targ().
Referenced by com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Lambda.lookup(), and com.cliffc.aa.HM.HM8.Lambda.targ().
toString()
final String com.cliffc.aa.HM.HM8.Syntax.toString () inherited
Definition at line 288 of file HM8.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM8.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_args
final String [] com.cliffc.aa.HM.HM8.Lambda._args package
Definition at line 358 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Lambda.Lambda(), com.cliffc.aa.HM.HM8.Lambda.lookup(), com.cliffc.aa.HM.HM8.Lambda.p1(), com.cliffc.aa.HM.HM8.Lambda.prep_lookup_deps(), and com.cliffc.aa.HM.HM8.Lambda.str().
_body
final Syntax com.cliffc.aa.HM.HM8.Lambda._body package
Definition at line 359 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Lambda.Lambda(), com.cliffc.aa.HM.HM8.Lambda.more_work(), com.cliffc.aa.HM.HM8.Lambda.p2(), com.cliffc.aa.HM.HM8.Lambda.prep_tree(), and com.cliffc.aa.HM.HM8.Lambda.str().
_nongen
VStack com.cliffc.aa.HM.HM8.Syntax._nongen package inherited
Definition at line 241 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Ident.hm(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM8.Syntax._par package inherited
Definition at line 240 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._occurs_in(), com.cliffc.aa.HM.HM8.Con.add_work(), com.cliffc.aa.HM.HM8.Ident.add_work(), com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Apply.add_work(), com.cliffc.aa.HM.HM8.Struct.add_work(), com.cliffc.aa.HM.HM8.Field.add_work(), com.cliffc.aa.HM.HM8.Ident.hm(), com.cliffc.aa.HM.HM8.Lambda.lookup(), com.cliffc.aa.HM.HM8.Let.lookup(), com.cliffc.aa.HM.HM8.Apply.lookup(), com.cliffc.aa.HM.HM8.Struct.lookup(), com.cliffc.aa.HM.HM8.Field.lookup(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_post
T2 com.cliffc.aa.HM.HM8.Syntax._post package inherited
Definition at line 244 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Syntax.post(), com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_pre
T2 com.cliffc.aa.HM.HM8.Syntax._pre package inherited
Definition at line 242 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Syntax.pre(), com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM8.Syntax._t package inherited
Definition at line 243 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Syntax.debug_find(), com.cliffc.aa.HM.HM8.Syntax.find(), com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM8.Syntax.p0(), com.cliffc.aa.HM.HM8.Let.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_targs
T2 [] com.cliffc.aa.HM.HM8.Lambda._targs package
Definition at line 360 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Lambda.Lambda(), com.cliffc.aa.HM.HM8.Lambda.prep_lookup_deps(), com.cliffc.aa.HM.HM8.Lambda.prep_tree(), and com.cliffc.aa.HM.HM8.Lambda.targ().
The documentation for this class was generated from the following file:
HM8.java