aa: com.cliffc.aa.node.Node.ErrMsg Class Reference
com.cliffc.aa.node.Node.ErrMsg Class Reference
Public Member Functions
ErrMsg (Parse loc, String msg, Level lvl)
int compareTo (ErrMsg msg)
boolean equals (Object obj)
int hashCode ()
String toString ()
Static Public Member Functions
static ErrMsg asserterr (Parse loc, Type actual, Type t0mem, Type expected)
static ErrMsg badGC (Parse loc)
static ErrMsg field (Parse loc, String msg, String fld, boolean closure, TypeObj to)
static ErrMsg forward_ref (Parse loc, FunPtrNode fun)
static ErrMsg forward_ref (Parse loc, String name)
static ErrMsg niladr (Parse loc, String msg, String fld)
static ErrMsg syntax (Parse loc, String msg)
static ErrMsg trailingjunk (Parse loc)
static ErrMsg typerr (Parse loc, Type actual, Type t0mem, Type expected)
static ErrMsg typerr (Parse loc, Type actual, Type t0mem, Type expected, Level lvl)
static ErrMsg typerr (Parse loc, Type actual, Type t0mem, Type[] expecteds)
static ErrMsg unresolved (Parse loc, String msg)
Public Attributes
Parse _loc
final Level _lvl
final String _msg
int _order
Static Public Attributes
static final ErrMsg BADARGS = new ErrMsg(null,"bad arguments",Level.BadArgs)
static final ErrMsg FAST = new ErrMsg(null,"fast",Level.Syntax)
Detailed Description
Definition at line 888 of file Node.java.
Constructor & Destructor Documentation
ErrMsg()
com.cliffc.aa.node.Node.ErrMsg.ErrMsg (Parse loc, String msg, Level lvl)
Definition at line 895 of file Node.java.
 { _loc=loc; _msg=msg; _lvl=lvl; }
References com.cliffc.aa.node.Node.ErrMsg._loc, com.cliffc.aa.node.Node.ErrMsg._lvl, and com.cliffc.aa.node.Node.ErrMsg._msg.
Referenced by com.cliffc.aa.node.Node.ErrMsg.badGC(), com.cliffc.aa.node.Node.ErrMsg.equals(), com.cliffc.aa.node.Node.ErrMsg.field(), com.cliffc.aa.node.Node.ErrMsg.forward_ref(), com.cliffc.aa.node.Node.ErrMsg.niladr(), com.cliffc.aa.node.Node.ErrMsg.syntax(), com.cliffc.aa.node.Node.ErrMsg.trailingjunk(), com.cliffc.aa.node.Node.ErrMsg.typerr(), and com.cliffc.aa.node.Node.ErrMsg.unresolved().
Member Function Documentation
asserterr()
static ErrMsg com.cliffc.aa.node.Node.ErrMsg.asserterr (Parse loc, Type actual, Type t0mem, Type expected) static
Definition at line 926 of file Node.java.
{
       return typerr(loc,actual,t0mem,expected,Level.Assert);
     }
References com.cliffc.aa.node.Node.Level.Assert, and com.cliffc.aa.node.Node.ErrMsg.typerr().
Referenced by com.cliffc.aa.node.AssertNode.err().
badGC()
static ErrMsg com.cliffc.aa.node.Node.ErrMsg.badGC (Parse loc) static
Definition at line 938 of file Node.java.
{
       return new ErrMsg(loc,"Cannot mix GC and non-GC types",Level.MixedPrimGC);
     }
References com.cliffc.aa.node.Node.ErrMsg.ErrMsg(), and com.cliffc.aa.node.Node.Level.MixedPrimGC.
Referenced by com.cliffc.aa.node.PhiNode.err().
compareTo()
int com.cliffc.aa.node.Node.ErrMsg.compareTo (ErrMsg msg)
Definition at line 948 of file Node.java.
{
       int cmp = _lvl.compareTo(msg._lvl);
       if( cmp != 0 ) return cmp;
       return _order - msg._order;
       //cmp = _loc.compareTo(msg._loc);
       //if( cmp != 0 ) return cmp;
       //return _msg.compareTo(msg._msg);
     }
References com.cliffc.aa.node.Node.ErrMsg._lvl, and com.cliffc.aa.node.Node.ErrMsg._order.
equals()
boolean com.cliffc.aa.node.Node.ErrMsg.equals (Object obj)
Definition at line 956 of file Node.java.
{
       if( this==obj ) return true;
       if( !(obj instanceof ErrMsg) ) return false;
       ErrMsg err = (ErrMsg)obj;
       if( _lvl!=err._lvl || !_msg.equals(err._msg) ) return false;
       // Spread a missing loc; cheaty but only a little bit.
       // TODO: track down missing loc in Parser
       if( _loc==null && err._loc!=null ) _loc=err._loc;
       if( _loc!=null && err._loc==null ) err._loc=_loc;
       return _loc==err._loc || _loc.equals(err._loc);
     }
References com.cliffc.aa.node.Node.ErrMsg._loc, com.cliffc.aa.node.Node.ErrMsg._lvl, com.cliffc.aa.node.Node.ErrMsg._msg, com.cliffc.aa.Parse.equals(), com.cliffc.aa.node.Node.err(), and com.cliffc.aa.node.Node.ErrMsg.ErrMsg().
Referenced by com.cliffc.aa.node.ErrNode.equals().
field()
static ErrMsg com.cliffc.aa.node.Node.ErrMsg.field (Parse loc, String msg, String fld, boolean closure, TypeObj to) static
Definition at line 929 of file Node.java.
{
       SB sb = new SB().p(msg).p(closure ? " val '" : " field '.").p(fld).p("'");
       if( to != null && !closure ) to.str(sb.p(" in "),new VBitSet(),null,false);
       return new ErrMsg(loc,sb.toString(),Level.Field);
     }
References com.cliffc.aa.node.Node.ErrMsg.ErrMsg(), com.cliffc.aa.node.Node.Level.Field, com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.str(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.node.StoreNode.bad(), and com.cliffc.aa.node.LoadNode.bad().
forward_ref() [1/2]
static ErrMsg com.cliffc.aa.node.Node.ErrMsg.forward_ref (Parse loc, FunPtrNode fun) static
Definition at line 896 of file Node.java.
 { return forward_ref(loc,fun._name); }
References com.cliffc.aa.node.FunPtrNode._name, and com.cliffc.aa.node.Node.ErrMsg.forward_ref().
Referenced by com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.node.FunPtrNode.forward_ref(), com.cliffc.aa.node.Node.ErrMsg.forward_ref(), and com.cliffc.aa.Parse.inc().
forward_ref() [2/2]
static ErrMsg com.cliffc.aa.node.Node.ErrMsg.forward_ref (Parse loc, String name) static
Definition at line 897 of file Node.java.
{
       return new ErrMsg(loc,"Unknown ref '"+name+"'",Level.ForwardRef);
     }
References com.cliffc.aa.node.Node.ErrMsg.ErrMsg(), and com.cliffc.aa.node.Node.Level.ForwardRef.
hashCode()
int com.cliffc.aa.node.Node.ErrMsg.hashCode ()
Definition at line 967 of file Node.java.
{
       return (_loc==null ? 0 : _loc.hashCode())+_msg.hashCode()+_lvl.hashCode();
     }
References com.cliffc.aa.node.Node.ErrMsg._loc, com.cliffc.aa.node.Node.ErrMsg._lvl, com.cliffc.aa.node.Node.ErrMsg._msg, and com.cliffc.aa.Parse.hashCode().
Referenced by com.cliffc.aa.node.ErrNode.hashCode().
niladr()
static ErrMsg com.cliffc.aa.node.Node.ErrMsg.niladr (Parse loc, String msg, String fld) static
Definition at line 934 of file Node.java.
{
       String f = fld==null ? msg : msg+" field '."+fld+"'";
       return new ErrMsg(loc,f,Level.NilAdr);
     }
References com.cliffc.aa.node.Node.ErrMsg.ErrMsg(), and com.cliffc.aa.node.Node.Level.NilAdr.
Referenced by com.cliffc.aa.node.MemPrimNode.err(), com.cliffc.aa.node.StoreNode.err(), and com.cliffc.aa.node.LoadNode.err().
syntax()
static ErrMsg com.cliffc.aa.node.Node.ErrMsg.syntax (Parse loc, String msg) static
Definition at line 900 of file Node.java.
{
       return new ErrMsg(loc,msg,Level.Syntax);
     }
References com.cliffc.aa.node.Node.ErrMsg.ErrMsg(), and com.cliffc.aa.node.Node.Level.Syntax.
Referenced by com.cliffc.aa.node.MemPrimNode.LValueWriteFinal.err(), com.cliffc.aa.node.CallNode.err(), and com.cliffc.aa.Parse.stmt().
toString()
String com.cliffc.aa.node.Node.ErrMsg.toString ()
Definition at line 945 of file Node.java.
{
       return _loc==null ? _msg : _loc.errLocMsg(_msg);
     }
References com.cliffc.aa.node.Node.ErrMsg._loc, com.cliffc.aa.node.Node.ErrMsg._msg, and com.cliffc.aa.Parse.errLocMsg().
trailingjunk()
static ErrMsg com.cliffc.aa.node.Node.ErrMsg.trailingjunk (Parse loc) static
Definition at line 941 of file Node.java.
{
       return new ErrMsg(loc,"Syntax error; trailing junk",Level.TrailingJunk);
     }
References com.cliffc.aa.node.Node.ErrMsg.ErrMsg(), and com.cliffc.aa.node.Node.Level.TrailingJunk.
Referenced by com.cliffc.aa.Parse.gather_errors().
typerr() [1/3]
static ErrMsg com.cliffc.aa.node.Node.ErrMsg.typerr (Parse loc, Type actual, Type t0mem, Type expected) static
Definition at line 906 of file Node.java.
 { return typerr(loc,actual,t0mem,expected,Level.TypeErr); }
References com.cliffc.aa.node.Node.Level.TypeErr, and com.cliffc.aa.node.Node.ErrMsg.typerr().
Referenced by com.cliffc.aa.node.Node.ErrMsg.asserterr(), com.cliffc.aa.node.MemPrimNode.err(), com.cliffc.aa.node.ParmNode.err(), com.cliffc.aa.node.IntrinsicNode.err(), com.cliffc.aa.node.PrimNode.err(), com.cliffc.aa.node.PrimNode.ConvertTypeName.err(), com.cliffc.aa.node.CallNode.err(), and com.cliffc.aa.node.Node.ErrMsg.typerr().
typerr() [2/3]
static ErrMsg com.cliffc.aa.node.Node.ErrMsg.typerr (Parse loc, Type actual, Type t0mem, Type expected, Level lvl) static
Definition at line 907 of file Node.java.
{
       TypeMem tmem = t0mem instanceof TypeMem ? (TypeMem)t0mem : null;
       VBitSet vb = new VBitSet();
       SB sb = actual.str(new SB(),vb, tmem, false).p(" is not a ");
       vb.clear();
       expected.str(sb,vb,null,false); // Expected is already a complex ptr, does not depend on memory
       if( actual==Type.ALL && lvl==Level.TypeErr ) lvl=Level.AllTypeErr; // ALLs have failed earlier, so this is a lower priority error report
       return new ErrMsg(loc,sb.toString(),lvl);
     }
References com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.node.Node.Level.AllTypeErr, com.cliffc.aa.util.SB.clear(), com.cliffc.aa.node.Node.ErrMsg.ErrMsg(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.Type< T extends Type< T >.str(), com.cliffc.aa.util.SB.toString(), and com.cliffc.aa.node.Node.Level.TypeErr.
typerr() [3/3]
static ErrMsg com.cliffc.aa.node.Node.ErrMsg.typerr (Parse loc, Type actual, Type t0mem, Type[] expecteds) static
Definition at line 916 of file Node.java.
{
       TypeMem tmem = t0mem instanceof TypeMem ? (TypeMem)t0mem : null;
       VBitSet vb = new VBitSet();
       SB sb = actual.str(new SB(),vb, tmem,false);
       sb.p( expecteds.length==1 ? " is not a " : " is none of (");
       vb.clear();
       for( Type expect : expecteds ) expect.str(sb,vb,null,false).p(',');
       sb.unchar().p(expecteds.length==1 ? "" : ")");
       return new ErrMsg(loc,sb.toString(),Level.TypeErr);
     }
References com.cliffc.aa.util.SB.clear(), com.cliffc.aa.node.Node.ErrMsg.ErrMsg(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.Type< T extends Type< T >.str(), com.cliffc.aa.util.SB.toString(), com.cliffc.aa.node.Node.Level.TypeErr, and com.cliffc.aa.util.SB.unchar().
unresolved()
static ErrMsg com.cliffc.aa.node.Node.ErrMsg.unresolved (Parse loc, String msg) static
Definition at line 903 of file Node.java.
{
       return new ErrMsg(loc,msg,Level.UnresolvedCall);
     }
References com.cliffc.aa.node.Node.ErrMsg.ErrMsg(), and com.cliffc.aa.node.Node.Level.UnresolvedCall.
Referenced by com.cliffc.aa.node.CallNode.err().
Member Data Documentation
_loc
Parse com.cliffc.aa.node.Node.ErrMsg._loc
Definition at line 889 of file Node.java.
Referenced by com.cliffc.aa.node.Node.ErrMsg.equals(), com.cliffc.aa.node.Node.ErrMsg.ErrMsg(), com.cliffc.aa.node.Node.ErrMsg.hashCode(), and com.cliffc.aa.node.Node.ErrMsg.toString().
_lvl
final Level com.cliffc.aa.node.Node.ErrMsg._lvl
Definition at line 891 of file Node.java.
Referenced by com.cliffc.aa.node.Node.ErrMsg.compareTo(), com.cliffc.aa.node.Node.ErrMsg.equals(), com.cliffc.aa.node.Node.ErrMsg.ErrMsg(), and com.cliffc.aa.node.Node.ErrMsg.hashCode().
_msg
final String com.cliffc.aa.node.Node.ErrMsg._msg
Definition at line 890 of file Node.java.
Referenced by com.cliffc.aa.node.Node.ErrMsg.equals(), com.cliffc.aa.node.Node.ErrMsg.ErrMsg(), com.cliffc.aa.node.Node.ErrMsg.hashCode(), com.cliffc.aa.node.Node.ErrMsg.toString(), and com.cliffc.aa.node.ErrNode.xstr().
_order
int com.cliffc.aa.node.Node.ErrMsg._order
Definition at line 892 of file Node.java.
Referenced by com.cliffc.aa.node.Node.adderr(), and com.cliffc.aa.node.Node.ErrMsg.compareTo().
BADARGS
final ErrMsg com.cliffc.aa.node.Node.ErrMsg.BADARGS = new ErrMsg(null,"bad arguments",Level.BadArgs) static
Definition at line 894 of file Node.java.
Referenced by com.cliffc.aa.node.PrimNode.err().
FAST
final ErrMsg com.cliffc.aa.node.Node.ErrMsg.FAST = new ErrMsg(null,"fast",Level.Syntax) static
Definition at line 893 of file Node.java.
Referenced by com.cliffc.aa.node.StoreNode.bad(), com.cliffc.aa.node.LoadNode.bad(), com.cliffc.aa.node.MemPrimNode.err(), com.cliffc.aa.node.ParmNode.err(), com.cliffc.aa.node.IntrinsicNode.err(), com.cliffc.aa.node.StoreNode.err(), com.cliffc.aa.node.LoadNode.err(), and com.cliffc.aa.node.CallNode.err().
The documentation for this class was generated from the following file:
Node.java