aa: com.cliffc.aa.HM.HM5 Class Reference
com.cliffc.aa.HM.HM5 Class Reference
Classes
class Apply
class Con
class Ident
class Lambda
class Lambda2
class Let
class Syntax
class T2
class VStack
class Worklist
Static Public Member Functions
static T2 hm (Syntax prog)
Static Package Functions
static void reset ()
Static Package Attributes
static boolean DEBUG_LEAKS =false
static final HashMap< String, T2 > PRIMS = new HashMap<>()
Detailed Description
Definition at line 23 of file HM5.java.
Member Function Documentation
hm()
static T2 com.cliffc.aa.HM.HM5.hm (Syntax prog) static
Definition at line 27 of file HM5.java.
{
     Worklist work = new Worklist();
     // Simple types
     T2 bool  = T2.make_base(TypeInt.BOOL);
     T2 int64 = T2.make_base(TypeInt.INT64);
     T2 flt64 = T2.make_base(TypeFlt.FLT64);
     T2 strp  = T2.make_base(TypeMemPtr.STRPTR);
     // Primitives
     T2 var1 = T2.make_leaf();
     T2 var2 = T2.make_leaf();
     PRIMS.put("pair1",T2.make_fun(var1, T2.make_fun(var2, T2.prim("pair",var1,var2) )));
     PRIMS.put("pair",T2.make_fun(var1, var2, T2.prim("pair",var1,var2) ));
     PRIMS.put("if/else",T2.make_fun(bool,var1,var1,var1));
     PRIMS.put("dec",T2.make_fun(int64,int64));
     PRIMS.put("*"  ,T2.make_fun(int64,int64,int64));
     PRIMS.put("==0",T2.make_fun(int64,bool));
     PRIMS.put("isempty",T2.make_fun(strp,bool));
     // Print a string; int->str
     PRIMS.put("str",T2.make_fun(int64,strp));
     // Factor; FP div/mod-like operation
     PRIMS.put("factor",T2.make_fun(flt64,T2.prim("divmod",flt64,flt64)));
     // Prep for SSA: pre-gather all the (unique) ids
     int cnt_syns = prog.prep_tree(null,null,work);
     int init_T2s = T2.CNT;
     int cnt=0, DEBUG_CNT=-1;
     while( work.len()>0 ) {     // While work
       int oldcnt = T2.CNT;      // Used for cost-check when no-progress
       Syntax syn = work.pop();  // Get work
       T2 old = syn._t;          // Old value for progress assert
       if( cnt==DEBUG_CNT )
         System.out.println("break here");
       if( syn.hm(work) ) {      // Compute a new HM type and check for progress
         assert !syn.debug_find().unify(old.find(),null);// monotonic: unifying with the result is no-progress
         syn.add_kids(work);     // Push children on worklist
         syn.add_occurs(work);   // Push occurs-check ids on worklist
         if( syn._par !=null ) work.push(syn._par); // Parent updates
       } else {
         assert !DEBUG_LEAKS || oldcnt==T2.CNT;  // No-progress consumes no-new-T2s
       }
       // VERY EXPENSIVE ASSERT: O(n^2).  Every Syntax that makes progress is on the worklist
       //assert prog.more_work(work);
       cnt++;
     }
     assert prog.more_work(work);
     //System.out.println("Initial T2s: "+init_T2s+", Prog size: "+cnt_syns+", worklist iters: "+cnt+", T2s: "+T2.CNT);
     return prog._t;
   }
References com.cliffc.aa.HM.HM5.Syntax._par, com.cliffc.aa.HM.HM5.Syntax._t, com.cliffc.aa.HM.HM5.Syntax.add_kids(), com.cliffc.aa.HM.HM5.Syntax.add_occurs(), com.cliffc.aa.type.TypeInt.BOOL, com.cliffc.aa.HM.HM5.T2.CNT, com.cliffc.aa.HM.HM5.Syntax.debug_find(), com.cliffc.aa.HM.HM5.DEBUG_LEAKS, com.cliffc.aa.HM.HM5.T2.find(), com.cliffc.aa.type.TypeFlt.FLT64, com.cliffc.aa.HM.HM5.Syntax.hm(), com.cliffc.aa.type.TypeInt.INT64, com.cliffc.aa.HM.HM5.Worklist.len(), com.cliffc.aa.HM.HM5.T2.make_base(), com.cliffc.aa.HM.HM5.T2.make_fun(), com.cliffc.aa.HM.HM5.T2.make_leaf(), com.cliffc.aa.HM.HM5.Syntax.more_work(), com.cliffc.aa.HM.HM5.Worklist.pop(), com.cliffc.aa.HM.HM5.Syntax.prep_tree(), com.cliffc.aa.HM.HM5.T2.prim(), com.cliffc.aa.HM.HM5.PRIMS, com.cliffc.aa.HM.HM5.Worklist.push(), com.cliffc.aa.type.TypeMemPtr.STRPTR, and com.cliffc.aa.HM.HM5.T2.unify().
Referenced by com.cliffc.aa.HM.TestHM5.test00(), com.cliffc.aa.HM.TestHM5.test01(), com.cliffc.aa.HM.TestHM5.test02(), com.cliffc.aa.HM.TestHM5.test03(), com.cliffc.aa.HM.TestHM5.test04(), com.cliffc.aa.HM.TestHM5.test05(), com.cliffc.aa.HM.TestHM5.test06(), com.cliffc.aa.HM.TestHM5.test07(), com.cliffc.aa.HM.TestHM5.test08(), com.cliffc.aa.HM.TestHM5.test09(), com.cliffc.aa.HM.TestHM5.test10(), com.cliffc.aa.HM.TestHM5.test11(), com.cliffc.aa.HM.TestHM5.test12(), com.cliffc.aa.HM.TestHM5.test13(), com.cliffc.aa.HM.TestHM5.test14(), com.cliffc.aa.HM.TestHM5.test15(), com.cliffc.aa.HM.TestHM5.test16(), com.cliffc.aa.HM.TestHM5.test17(), com.cliffc.aa.HM.TestHM5.test18(), com.cliffc.aa.HM.TestHM5.test19(), com.cliffc.aa.HM.TestHM5.test20(), com.cliffc.aa.HM.TestHM5.test21(), com.cliffc.aa.HM.TestHM5.test22(), and com.cliffc.aa.HM.TestHM5.test23().
reset()
static void com.cliffc.aa.HM.HM5.reset () static package
Definition at line 83 of file HM5.java.
 { PRIMS.clear(); T2.reset(); }
References com.cliffc.aa.HM.HM5.PRIMS, and com.cliffc.aa.HM.HM5.T2.reset().
Referenced by com.cliffc.aa.HM.TestHM5.reset().
Member Data Documentation
DEBUG_LEAKS
boolean com.cliffc.aa.HM.HM5.DEBUG_LEAKS =false static package
Definition at line 25 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.T2.fresh_unify(), and com.cliffc.aa.HM.HM5.hm().
PRIMS
final HashMap<String,T2> com.cliffc.aa.HM.HM5.PRIMS = new HashMap<>() static package
Definition at line 24 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Ident.add_occurs(), com.cliffc.aa.HM.HM5.hm(), com.cliffc.aa.HM.HM5.Ident.hm(), and com.cliffc.aa.HM.HM5.reset().
The documentation for this class was generated from the following file:
HM5.java