aa: com.cliffc.aa.Exec Class Reference
com.cliffc.aa.Exec Class Reference abstract
an implementation of language AA
Static Public Member Functions
static String dump ()
static TypeEnv go (Env top, String src, String str)
Static Package Functions
static TypeEnv open (Env top, String src, String str)
Static Private Attributes
static Parse P
Detailed Description
an implementation of language AA
Definition at line 6 of file Exec.java.
Member Function Documentation
dump()
static String com.cliffc.aa.Exec.dump () static
Definition at line 16 of file Exec.java.
 { return Env.START.dumprpo(false,false); } // Debugging hook
References com.cliffc.aa.Env.START.
go()
static TypeEnv com.cliffc.aa.Exec.go (Env top, String src, String str) static
Definition at line 8 of file Exec.java.
                                                               { // Execute string
     try( TypeEnv te = open(top,src,str) ) { return te; }
   }
References com.cliffc.aa.Exec.open().
Referenced by com.cliffc.aa.REPL.go_one(), com.cliffc.aa.AA.main(), com.cliffc.aa.TestParse.testary(), com.cliffc.aa.TestParse.testerr(), com.cliffc.aa.TestParse.testParse06(), and com.cliffc.aa.TestParse.testParse07().
open()
static TypeEnv com.cliffc.aa.Exec.open (Env top, String src, String str) static package
Definition at line 12 of file Exec.java.
                                                          { // Execute string
     return (P=new Parse(src,top,str)).go();
   }
References com.cliffc.aa.Exec.P.
Referenced by com.cliffc.aa.Exec.go(), com.cliffc.aa.TestParse.run(), and com.cliffc.aa.TestParse.test_prim().
Member Data Documentation
P
Parse com.cliffc.aa.Exec.P static private
Definition at line 7 of file Exec.java.
Referenced by com.cliffc.aa.Exec.open().
The documentation for this class was generated from the following file:
Exec.java