aa: com.cliffc.aa.HM.HM4.Syntax Class Reference
com.cliffc.aa.HM.HM4.Syntax Class Reference abstract
Public Member Functions
String p ()
final String toString ()
Package Functions
T2 find ()
abstract T2 hm (Ary< Syntax > work)
abstract void live (IBitSet visit)
abstract boolean more_work (Ary< Syntax > work)
final boolean more_work_impl (Ary< Syntax > work)
final SB p0 (SB sb, VBitSet dups)
abstract SB p1 (SB sb)
abstract SB p2 (SB sb, VBitSet dups)
abstract void prep_tree (Syntax par, Ary< Syntax > work)
void prep_tree_impl (Syntax par, T2 t, Ary< Syntax > work)
T2 prep_tree_lookup (String name, Syntax prior)
abstract SB str (SB sb)
Package Attributes
Syntax _par
T2 _t
Detailed Description
Definition at line 74 of file HM4.java.
Member Function Documentation
find()
T2 com.cliffc.aa.HM.HM4.Syntax.find () package
Definition at line 77 of file HM4.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM4.Syntax._t, and com.cliffc.aa.HM.HM4.T2.find().
Referenced by com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Con.hm(), com.cliffc.aa.HM.HM4.Ident.hm(), com.cliffc.aa.HM.HM4.Lambda.hm(), com.cliffc.aa.HM.HM4.Lambda2.hm(), com.cliffc.aa.HM.HM4.Let.hm(), com.cliffc.aa.HM.HM4.Apply.hm(), and com.cliffc.aa.HM.HM4.Syntax.more_work_impl().
hm()
abstract T2 com.cliffc.aa.HM.HM4.Syntax.hm (Ary< Syntax > work) abstract package
Reimplemented in com.cliffc.aa.HM.HM4.Apply, com.cliffc.aa.HM.HM4.Let, com.cliffc.aa.HM.HM4.Lambda2, com.cliffc.aa.HM.HM4.Lambda, com.cliffc.aa.HM.HM4.Ident, and com.cliffc.aa.HM.HM4.Con.
Referenced by com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM4.Syntax.more_work_impl().
live()
abstract void com.cliffc.aa.HM.HM4.Syntax.live (IBitSet visit) abstract package
Reimplemented in com.cliffc.aa.HM.HM4.Apply, com.cliffc.aa.HM.HM4.Let, com.cliffc.aa.HM.HM4.Lambda2, com.cliffc.aa.HM.HM4.Lambda, com.cliffc.aa.HM.HM4.Ident, and com.cliffc.aa.HM.HM4.Con.
Referenced by com.cliffc.aa.HM.HM4.Lambda.live(), com.cliffc.aa.HM.HM4.Lambda2.live(), and com.cliffc.aa.HM.HM4.Let.live().
more_work()
abstract boolean com.cliffc.aa.HM.HM4.Syntax.more_work (Ary< Syntax > work) abstract package
Reimplemented in com.cliffc.aa.HM.HM4.Apply, com.cliffc.aa.HM.HM4.Let, com.cliffc.aa.HM.HM4.Lambda2, com.cliffc.aa.HM.HM4.Lambda, com.cliffc.aa.HM.HM4.Ident, and com.cliffc.aa.HM.HM4.Con.
Referenced by com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Lambda.more_work(), com.cliffc.aa.HM.HM4.Lambda2.more_work(), com.cliffc.aa.HM.HM4.Let.more_work(), com.cliffc.aa.HM.HM4.Apply.more_work(), and com.cliffc.aa.HM.HM4.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM4.Syntax.more_work_impl (Ary< Syntax > work) package
Definition at line 91 of file HM4.java.
{
       if( work.find(this)!=-1 ) return true; // On worklist, so ok
       // Check does not make progress
       int old = T2.CNT;  int olen = work._len;
       boolean more_work;
       try {
         T2 t = find();
         Type con = t._con;
         T2 hm = hm(null);       // Run H-M, with null work, looking for progress
         T2 un = find().unify(hm,null);
         more_work = t!=un || con!=un._con || work._len!=olen; // Something happened?
         assert !more_work;
       } catch( RuntimeException no_unify ) { more_work=true; } // Fail to unify assert is progress
       if( !more_work ) T2.CNT=old;  // Reset if no error; prevents assert from endlessly raising CNT
       return !more_work;
     }
References com.cliffc.aa.HM.HM4.T2._con, com.cliffc.aa.util.Ary< E >._len, com.cliffc.aa.HM.HM4.T2.CNT, com.cliffc.aa.HM.HM4.Syntax.find(), com.cliffc.aa.util.Ary< E >.find(), com.cliffc.aa.HM.HM4.Syntax.hm(), com.cliffc.aa.HM.HM4.Syntax.more_work(), and com.cliffc.aa.HM.HM4.T2.unify().
Referenced by com.cliffc.aa.HM.HM4.Con.more_work(), com.cliffc.aa.HM.HM4.Ident.more_work(), com.cliffc.aa.HM.HM4.Lambda.more_work(), com.cliffc.aa.HM.HM4.Lambda2.more_work(), com.cliffc.aa.HM.HM4.Let.more_work(), and com.cliffc.aa.HM.HM4.Apply.more_work().
p()
String com.cliffc.aa.HM.HM4.Syntax.p ()
Definition at line 111 of file HM4.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM4.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM4.Syntax.p0 (SB sb, VBitSet dups) package
Definition at line 112 of file HM4.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM4.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM4.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM4.Syntax.p1(), com.cliffc.aa.HM.HM4.Syntax.p2(), and com.cliffc.aa.HM.HM4.T2.str().
Referenced by com.cliffc.aa.HM.HM4.Syntax.p(), com.cliffc.aa.HM.HM4.Lambda.p2(), com.cliffc.aa.HM.HM4.Lambda2.p2(), com.cliffc.aa.HM.HM4.Let.p2(), and com.cliffc.aa.HM.HM4.Apply.p2().
p1()
abstract SB com.cliffc.aa.HM.HM4.Syntax.p1 (SB sb) abstract package
Reimplemented in com.cliffc.aa.HM.HM4.Apply, com.cliffc.aa.HM.HM4.Let, com.cliffc.aa.HM.HM4.Lambda2, com.cliffc.aa.HM.HM4.Lambda, com.cliffc.aa.HM.HM4.Ident, and com.cliffc.aa.HM.HM4.Con.
Referenced by com.cliffc.aa.HM.HM4.Syntax.p0().
p2()
abstract SB com.cliffc.aa.HM.HM4.Syntax.p2 (SB sb, VBitSet dups) abstract package
Reimplemented in com.cliffc.aa.HM.HM4.Apply, com.cliffc.aa.HM.HM4.Let, com.cliffc.aa.HM.HM4.Lambda2, com.cliffc.aa.HM.HM4.Lambda, com.cliffc.aa.HM.HM4.Ident, and com.cliffc.aa.HM.HM4.Con.
Referenced by com.cliffc.aa.HM.HM4.Syntax.p0().
prep_tree()
abstract void com.cliffc.aa.HM.HM4.Syntax.prep_tree (Syntax par, Ary< Syntax > work) abstract package
Reimplemented in com.cliffc.aa.HM.HM4.Apply, com.cliffc.aa.HM.HM4.Let, com.cliffc.aa.HM.HM4.Lambda2, com.cliffc.aa.HM.HM4.Lambda, com.cliffc.aa.HM.HM4.Ident, and com.cliffc.aa.HM.HM4.Con.
Referenced by com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Lambda.prep_tree(), com.cliffc.aa.HM.HM4.Lambda2.prep_tree(), com.cliffc.aa.HM.HM4.Let.prep_tree(), and com.cliffc.aa.HM.HM4.Apply.prep_tree().
prep_tree_impl()
void com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl (Syntax par, T2 t, Ary< Syntax > work) package
Definition at line 86 of file HM4.java.
 { _par=par; _t=t; work.push(this); }
References com.cliffc.aa.HM.HM4.Syntax._par, com.cliffc.aa.HM.HM4.Syntax._t, and com.cliffc.aa.util.Ary< E >.push().
Referenced by com.cliffc.aa.HM.HM4.Con.prep_tree(), com.cliffc.aa.HM.HM4.Ident.prep_tree(), com.cliffc.aa.HM.HM4.Lambda.prep_tree(), com.cliffc.aa.HM.HM4.Lambda2.prep_tree(), com.cliffc.aa.HM.HM4.Let.prep_tree(), and com.cliffc.aa.HM.HM4.Apply.prep_tree().
prep_tree_lookup()
T2 com.cliffc.aa.HM.HM4.Syntax.prep_tree_lookup (String name, Syntax prior) package
Reimplemented in com.cliffc.aa.HM.HM4.Let, com.cliffc.aa.HM.HM4.Lambda2, and com.cliffc.aa.HM.HM4.Lambda.
Definition at line 87 of file HM4.java.
 { return null; }
str()
abstract SB com.cliffc.aa.HM.HM4.Syntax.str (SB sb) abstract package
Reimplemented in com.cliffc.aa.HM.HM4.Apply, com.cliffc.aa.HM.HM4.Let, com.cliffc.aa.HM.HM4.Lambda2, com.cliffc.aa.HM.HM4.Lambda, com.cliffc.aa.HM.HM4.Ident, and com.cliffc.aa.HM.HM4.Con.
Referenced by com.cliffc.aa.HM.HM4.Lambda.str(), com.cliffc.aa.HM.HM4.Lambda2.str(), com.cliffc.aa.HM.HM4.Let.str(), com.cliffc.aa.HM.HM4.Apply.str(), and com.cliffc.aa.HM.HM4.Syntax.toString().
toString()
final String com.cliffc.aa.HM.HM4.Syntax.toString ()
Definition at line 108 of file HM4.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM4.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_par
Syntax com.cliffc.aa.HM.HM4.Syntax._par package
Definition at line 75 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Ident.prep_tree(), and com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM4.Syntax._t package
Definition at line 76 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Syntax.find(), com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Con.live(), com.cliffc.aa.HM.HM4.Ident.live(), com.cliffc.aa.HM.HM4.Lambda.live(), com.cliffc.aa.HM.HM4.Lambda2.live(), com.cliffc.aa.HM.HM4.Let.live(), com.cliffc.aa.HM.HM4.Apply.live(), com.cliffc.aa.HM.HM4.Syntax.p0(), and com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM4.java