aa: com.cliffc.aa.HM.HM9.VStack Class Reference
com.cliffc.aa.HM.HM9.VStack Class Reference
Classes
class Iter
Public Member Functions
Iterator< T2 > iterator ()
String toString ()
Package Functions
VStack (VStack par, T2 nongen)
T2 nongen ()
SB str (SB sb, VBitSet dups)
Package Attributes
final int _d
final VStack _par
Private Attributes
T2 _nongen
Detailed Description
Definition at line 289 of file HM9.java.
Constructor & Destructor Documentation
VStack()
com.cliffc.aa.HM.HM9.VStack.VStack (VStack par, T2 nongen) package
Definition at line 293 of file HM9.java.
 { _par=par; _nongen=nongen; _d = par==null ? 0 : par._d+1; }
References com.cliffc.aa.HM.HM9.VStack._d, com.cliffc.aa.HM.HM9.VStack._nongen, com.cliffc.aa.HM.HM9.VStack._par, and com.cliffc.aa.HM.HM9.VStack.nongen().
Member Function Documentation
iterator()
Iterator<T2> com.cliffc.aa.HM.HM9.VStack.iterator ()
Definition at line 311 of file HM9.java.
 { return new Iter(); }
nongen()
T2 com.cliffc.aa.HM.HM9.VStack.nongen () package
Definition at line 294 of file HM9.java.
                 {
       T2 n = _nongen.find();
       return n==_nongen ? n : (_nongen=n);
     }
References com.cliffc.aa.HM.HM9.VStack._nongen, and com.cliffc.aa.HM.HM9.T2.find().
Referenced by com.cliffc.aa.HM.HM9.VStack.Iter.next(), and com.cliffc.aa.HM.HM9.VStack.VStack().
str()
SB com.cliffc.aa.HM.HM9.VStack.str (SB sb, VBitSet dups) package
Definition at line 306 of file HM9.java.
{
       _nongen.str(sb,new VBitSet(),dups);
       if( _par!=null ) _par.str(sb.p(" , "),dups);
       return sb;
     }
References com.cliffc.aa.HM.HM9.VStack._nongen, com.cliffc.aa.HM.HM9.VStack._par, com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM9.VStack.str(), and com.cliffc.aa.HM.HM9.T2.str().
Referenced by com.cliffc.aa.HM.HM9.VStack.str(), and com.cliffc.aa.HM.HM9.VStack.toString().
toString()
String com.cliffc.aa.HM.HM9.VStack.toString ()
Definition at line 298 of file HM9.java.
{
       // Collect dups across the forest of types
       VBitSet dups = new VBitSet();
       for( VStack vs = this; vs!=null; vs = vs._par )
         vs._nongen.get_dups(dups);
       // Now recursively print
       return str(new SB(),dups).toString();
     }
References com.cliffc.aa.HM.HM9.VStack._par, com.cliffc.aa.HM.HM9.VStack.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_d
final int com.cliffc.aa.HM.HM9.VStack._d package
Definition at line 292 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.VStack.VStack().
_nongen
T2 com.cliffc.aa.HM.HM9.VStack._nongen private
Definition at line 291 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.VStack.nongen(), com.cliffc.aa.HM.HM9.VStack.str(), and com.cliffc.aa.HM.HM9.VStack.VStack().
_par
final VStack com.cliffc.aa.HM.HM9.VStack._par package
Definition at line 290 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.VStack.Iter.next(), com.cliffc.aa.HM.HM9.VStack.str(), com.cliffc.aa.HM.HM9.VStack.toString(), and com.cliffc.aa.HM.HM9.VStack.VStack().
The documentation for this class was generated from the following file:
HM9.java