aa: com.cliffc.aa.type.TypeMemPtr Class Reference
com.cliffc.aa.type.TypeMemPtr Class Reference
Public Member Functions
boolean above (Type t)
boolean above_center ()
BitsAlias aliases ()
Type ax_meet_nil (Type nil)
final boolean contains (Type t)
boolean cycle_equals (Type o)
final T dual ()
boolean equals (Object o)
int getbit ()
int getbit0 ()
double getd ()
long getl ()
String getstr ()
boolean has_name ()
final int hashCode ()
Type high ()
boolean is_con ()
boolean is_display_ptr ()
boolean is_forward_ref ()
boolean isa (Type t)
final boolean isa_scalar ()
byte isBitShape (Type t)
Type join (Type t)
Type make_from (Type head, TypeMem mem, VBitSet visit)
TypeMemPtr make_from (TypeObj obj)
boolean may_be_con ()
boolean may_nil ()
final Type meet (Type t)
Type meet_loop (Type t2)
Type meet_nil (Type nil)
boolean must_nil ()
Type oob ()
Type oob (Type e)
TypeMem oob (TypeMem e)
TypeMemPtr oob (TypeMemPtr e)
TypeObj oob (TypeObj e)
TypeStruct oob (TypeStruct e)
Type oob_deep (Type t)
Type oop_deep_impl (Type t)
final T remove_name ()
final T set_name (String name)
Type sharptr (Type ptr)
Type simple_ptr ()
SB str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
final String toString ()
void walk (Predicate< Type > p)
TypeMemPtr widen ()
Static Public Member Functions
static Ary< Type > ALL_TYPES ()
static boolean eq (Type[] t0, Type[] t1)
static void init0 (HashMap< String, Type > types)
static boolean intern_check ()
static TypeMemPtr make (BitsAlias aliases, TypeObj obj)
static TypeMemPtr make (int alias, TypeObj obj)
static TypeMemPtr make_nil (int alias, TypeObj obj)
Public Attributes
BitsAlias _aliases
int _hash
String _name
TypeObj _obj
int _uid
Static Public Attributes
static final TypeMemPtr ABC0 = make(ABCPTR._aliases.meet_nil(),TypeStr.ABC)
static final TypeMemPtr ABCPTR = make(BitsAlias.ABC ,TypeStr.ABC)
static final Type ALL
static final Type ANY
static final TypeMemPtr ARY0 = make(BitsAlias.ARYBITS0,TypeAry.ARY)
static final TypeMemPtr ARYPTR = make(BitsAlias.ARYBITS ,TypeAry.ARY)
static final Type CTRL
static final TypeFld DISP_FLD = TypeFld.malloc("^",Type.NIL,Access.Final,0)
static final TypeMemPtr DISP_SIMPLE = make(BitsAlias.RECORD_BITS0,TypeObj.ISUSED)
static final TypeStruct DISPLAY = TypeStruct.malloc("",false,TypeFlds.ts(DISP_FLD),true)
static final TypeMemPtr DISPLAY_PTR = new TypeMemPtr().init(BitsAlias.RECORD_BITS0,DISPLAY)
static final TypeMemPtr EMTPTR = make(BitsAlias.EMPTY,TypeObj.UNUSED)
static final TypeMemPtr ISUSED = make(BitsAlias.NZERO ,TypeObj.ISUSED)
static final TypeMemPtr ISUSED0 = make(BitsAlias.FULL ,TypeObj.ISUSED)
static final Type NIL
static final TypeMemPtr NILPTR = make(BitsAlias.NIL,TypeObj.ISUSED)
static final Type NO_DISP = Type.ANY
static final Type NSCALR
static final TypeMemPtr OOP = make(BitsAlias.NZERO ,TypeObj.OBJ)
static final TypeMemPtr OOP0 = make(BitsAlias.FULL ,TypeObj.OBJ)
static final Type REAL
static int RECURSIVE_MEET
static final Type SCALAR
static final TypeMemPtr STR0 = make(BitsAlias.STRBITS0,TypeStr.STR)
static final TypeMemPtr STRPTR = make(BitsAlias.STRBITS ,TypeStr.STR)
static final TypeMemPtr STRUCT = make(BitsAlias.RECORD_BITS ,TypeStruct.ALLSTRUCT)
static final TypeMemPtr STRUCT0 = make(BitsAlias.RECORD_BITS0,TypeStruct.ALLSTRUCT)
static final Type XCTRL
static final Type XNIL
static final Type XNSCALR
static final Type XSCALAR
Protected Member Functions
Type clone ()
T init (byte type, String name)
TypeMemPtr xdual ()
Type xmeet (Type t)
Package Functions
int compute_hash ()
boolean contains (Type t, VBitSet bs)
final Type cross_nil (Type t)
HashMap< Type, Integer > depth ()
final T hashcons_free ()
boolean intern_check1 ()
Type intern_lookup ()
boolean interned ()
boolean is_display ()
final String mtname (Type t, Type mt)
Type not_nil ()
TypeMemPtr rdual ()
TypeStruct repeats_in_cycles (TypeStruct head, VBitSet bs)
final T retern ()
RuntimeException typerr (Type t)
final T untern ()
Static Package Functions
[static initializer]
[static initializer]
static boolean check_name (String n)
static boolean check_startup ()
static void concat (Ary< Type > ts, Type[] ts1)
static Type intern_find (int uid)
static int intern_size ()
static Type make (byte type)
static int max (int alias, HashMap< Type, Integer > ds)
Package Attributes
T _dual
byte _type
Static Package Attributes
static final Type NREAL
static final Pool[] POOLS
static final byte TALL
static final byte TANY
static final byte TARY
static final byte TCTRL
static final byte TFLD
static final byte TFLT
static final byte TFUNPTR
static final byte TFUNSIG
static final byte TINT
static final byte TLAST
static final byte TLIVE
static final byte TMEM
static final byte TMEMPTR
static final byte TNIL
static final byte TNREAL
static final byte TNSCALR
static final byte TOBJ
static final byte TREAL
static final byte TRPC
static final byte TSCALAR
static final byte TSIMPLE
static final byte TSTR
static final byte TSTRUCT
static final byte TTUPLE
static final byte TXCTRL
static final byte TXNIL
static final byte TXNREAL
static final byte TXNSCALR
static final byte TXREAL
static final byte TXSCALAR
static final Type[] TYPES = new Type[]{OOP0,STR0,STRPTR,ABCPTR,STRUCT,EMTPTR,DISPLAY,DISPLAY_PTR}
Private Member Functions
T _set_name (String name)
int _uid ()
boolean check_commute (Type t, Type mt)
boolean check_symmetric (Type t, Type mt)
T hashcons ()
TypeMemPtr init (BitsAlias aliases, TypeObj obj)
boolean intern_check0 (Type v)
boolean is_num ()
boolean is_ptr ()
boolean is_simple ()
Type xmt_name (Type t, Type mt)
Static Private Attributes
static Ary< Type > ALL_TYPES
static int CNT
static final ConcurrentHashMap< Type, Type > INTERN
static final byte[] ISA_SCALAR
static Type[] SCALAR_PRIMS
static final String[] STRS
static final Type XNREAL
static final Type XREAL
Detailed Description
Definition at line 14 of file TypeMemPtr.java.
Member Function Documentation
[static initializer]() [1/2]
com.cliffc.aa.type.TypeMemPtr.[static initializer] static package
[static initializer]() [2/2]
com.cliffc.aa.type.TypeMemPtr.[static initializer] static package
_set_name()
T com.cliffc.aa.type.Type< T extends Type< T >._set_name (String name) private inherited
Definition at line 558 of file Type.java.
{
     POOLS[_type]._clone++;
     T t1 = (T)clone();
     t1._name = name;
     return t1.hashcons_free();
   }
_uid()
int com.cliffc.aa.type.Type< T extends Type< T >._uid private inherited
Definition at line 103 of file Type.java.
 { return CNT++; }
above()
boolean com.cliffc.aa.type.Type< T extends Type< T >.above (Type< TypeMemPtr > t) inherited
Definition at line 625 of file Type.java.
 { return t != this && meet(t)==t; }
above_center()
boolean com.cliffc.aa.type.TypeMemPtr.above_center ()
Definition at line 164 of file TypeMemPtr.java.
{
     return _aliases.above_center();
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, and com.cliffc.aa.type.Bits< B extends Bits< B >.above_center().
Referenced by com.cliffc.aa.type.TypeMemPtr.must_nil().
aliases()
BitsAlias com.cliffc.aa.type.TypeMemPtr.aliases ()
Definition at line 212 of file TypeMemPtr.java.
 { return _aliases; }
References com.cliffc.aa.type.TypeMemPtr._aliases.
Referenced by com.cliffc.aa.type.TypeMemPtr.init(), com.cliffc.aa.type.TypeMemPtr.make(), and com.cliffc.aa.type.TypeMemPtr.xmeet().
ALL_TYPES()
static Ary<Type> com.cliffc.aa.type.Type< T extends Type< T >.ALL_TYPES static inherited
Definition at line 651 of file Type.java.
{
     if( ALL_TYPES != null ) return ALL_TYPES;
     Ary<Type> ts = new Ary<>(new Type[1],0);
     concat(ts,Type      .TYPES);
     concat(ts,TypeFlt   .TYPES);
     concat(ts,TypeFunPtr.TYPES);
     concat(ts,TypeFunSig.TYPES);
     concat(ts,TypeInt   .TYPES);
     concat(ts,TypeLive  .TYPES);
     concat(ts,TypeMem   .TYPES);
     concat(ts,TypeMemPtr.TYPES);
     concat(ts,TypeObj   .TYPES);
     concat(ts,TypeRPC   .TYPES);
     concat(ts,TypeStr   .TYPES);
     concat(ts,TypeStruct.TYPES);
     concat(ts,TypeTuple .TYPES);
     concat(ts,TypeAry   .TYPES);
     // Partial order Sort, makes for easier tests later.  Arrays.sort requires
     // a total order (i.e., the obvious Comparator breaks the sort contract),
     // so we hand-roll a simple bubble sort.
     for( int i=0; i<ts._len; i++ )
       for( int j=i+1; j<ts._len; j++ )
         if( ts._es[j].isa(ts._es[i]) ) { Type tmp = ts._es[i]; ts._es[i] = ts._es[j]; ts._es[j] = tmp; }
     return (ALL_TYPES = ts); // Preserve for tests
   }
ax_meet_nil()
Type com.cliffc.aa.type.TypeMemPtr.ax_meet_nil (Type nil)
Definition at line 203 of file TypeMemPtr.java.
{
     if( _aliases.isa(BitsAlias.XNIL) ) {
       if( _obj.above_center() && nil==XNIL )  return XNIL;
       if( nil==NIL ) return NIL;
     }
     _aliases = _aliases.meet(BitsAlias.NIL);
     return this;
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.above_center(), com.cliffc.aa.type.Bits< B extends Bits< B >.isa(), com.cliffc.aa.type.Bits< B extends Bits< B >.meet(), com.cliffc.aa.type.BitsAlias.NIL, com.cliffc.aa.type.Type< TypeMemPtr >.NIL, com.cliffc.aa.type.BitsAlias.XNIL, and com.cliffc.aa.type.Type< TypeMemPtr >.XNIL.
Referenced by com.cliffc.aa.type.TypeStruct.ax_meet().
check_commute()
boolean com.cliffc.aa.type.Type< T extends Type< T >.check_commute (Type< TypeMemPtr > t, Type< TypeMemPtr > mt) private inherited
Definition at line 593 of file Type.java.
{
     if( t==this ) return true;
     if( is_simple() && !t.is_simple() ) return true; // By design, flipped the only allowed order
     Type mt2 = t.xmeet(this);   // Reverse args and try again
     // Also reverse names.
     Type nmt2 = t.xmt_name(this,mt2);
     if( mt==nmt2 ) return true;
     System.out.println("Meet not commutative: "+this+".meet("+t+")="+mt+",\n but "+t+".meet("+this+")="+nmt2);
     return false;
   }
check_name()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.check_name (String n) static package inherited
Definition at line 548 of file Type.java.
 { return n.isEmpty() || n.charAt(n.length()-1)==':'; }
check_startup()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.check_startup static package inherited
Definition at line 684 of file Type.java.
{
     Type[] ts = ALL_TYPES().asAry();
     // Confirm commutative & complete
     for( Type t0 : ts )
       for( Type t1 : ts ) {
         Type mt = t0.meet(t1);
         assert t0.check_commute  (t1,mt);
         assert t0.check_symmetric(t1,mt);
       }
     // Confirm associative
     int errs=0;
     for( Type t0 : ts )
       for( Type t1 : ts )
         for( Type t2 : ts ) {
           Type t01   = t0 .meet(t1 );
           Type t12   = t1 .meet(t2 );
           Type t01_2 = t01.meet(t2 );
           Type t0_12 = t0 .meet(t12);
           if( t01_2 != t0_12 && errs++ < 10 )
             System.err.println("("+t0+"&"+t1+") & "+t2+" == "+t0+" & ("+t1+" & "+t2+"); "+
                                "("+t01      +") & "+t2+" == "+t0+" & ("+t12        +"); "+
                                t01_2                  +" == "+t0_12);
         }
     assert errs==0 : "Found "+errs+" associative errors";
     // Confirm symmetry.  If A isa B, then A.join(C) isa B.join(C)
     for( Type t0 : ts )
       for( Type t1 : ts ) {
         if( t0.isa(t1) ) {
           for( Type t2 : ts ) {
             Type t02 = t0.join(t2);
             Type t12 = t1.join(t2);
             Type mt  = t02.meet(t12);
             if( mt != t12 && errs++ < 10 ) {
               System.err.println("("+t0+" ^ "+t2+") = "+t02+"; "+
                                  "("+t1+" ^ "+t2+") = "+t12+"; "+
                                  "their meet = "+mt+" which is not "+t12);
             }
           }
         }
       }
     assert errs==0 : "Found "+errs+" non-join-type errors";
     // Check scalar primitives; all are SCALARS and none sub-type each other.
     SCALAR_PRIMS = new Type[] { TypeInt.INT64, TypeFlt.FLT64, TypeMemPtr.OOP0, TypeFunPtr.GENERIC_FUNPTR, TypeRPC.ALL_CALL };
     for( Type t : SCALAR_PRIMS ) assert t.isa(SCALAR);
     for( int i=0; i<SCALAR_PRIMS.length; i++ )
       for( int j=i+1; j<SCALAR_PRIMS.length; j++ )
         assert !SCALAR_PRIMS[i].isa(SCALAR_PRIMS[j]);
     return true;
   }
check_symmetric()
boolean com.cliffc.aa.type.Type< T extends Type< T >.check_symmetric (Type< TypeMemPtr > t, Type< TypeMemPtr > mt) private inherited
Definition at line 608 of file Type.java.
{
     if( t==this ) return true;
     Type ta = mt._dual.meet(t._dual);
     Type tb = mt._dual.meet(  _dual);
     if( ta==t._dual && tb==_dual ) return true;
     System.err.print("("+this+" & "+t+")=="+mt+" but \n("+mt._dual+" & ");
     if( ta!=t._dual ) System.err.println(t._dual+")=="+ta+" \nwhich is not "+t._dual);
     else              System.err.println(  _dual+")=="+tb+" \nwhich is not "+  _dual);
     return false;
   }
clone()
Type com.cliffc.aa.type.Type< T extends Type< T >.clone protected inherited
Definition at line 304 of file Type.java.
{
     try {
       POOLS[_type]._clone++;
       Type t = (Type)super.clone();
       t._uid = _uid();
       t._dual = null;
       t._hash = 0;
       if( t instanceof TypeStruct )
         ((TypeStruct)t)._cyclic = false;
       return t;
     }
     catch( CloneNotSupportedException cns ) { throw new RuntimeException(cns); }
   }
compute_hash()
int com.cliffc.aa.type.TypeMemPtr.compute_hash () package
Definition at line 34 of file TypeMemPtr.java.
{
     assert _obj._hash != 0;
     return (TMEMPTR + _aliases._hash + _obj._hash)|1;
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.Bits< B extends Bits< B >._hash, com.cliffc.aa.type.Type< T extends Type< T >._hash, com.cliffc.aa.type.TypeMemPtr._obj, and com.cliffc.aa.type.Type< TypeMemPtr >.TMEMPTR.
Referenced by com.cliffc.aa.type.TypeStruct._sharp().
concat()
static void com.cliffc.aa.type.Type< T extends Type< T >.concat (Ary< Type< TypeMemPtr > > ts, Type< TypeMemPtr >[] ts1) static package inherited
Definition at line 676 of file Type.java.
{
     for( Type t1 : ts1 ) {
       assert !t1.above_center(); // Always below-center or equal, because we'll dual anyways
       ts.push(t1);
       if( t1!=t1.dual() ) ts.push(t1.dual());
     }
   }
contains() [1/2]
final boolean com.cliffc.aa.type.Type< T extends Type< T >.contains (Type< TypeMemPtr > t) inherited
Definition at line 926 of file Type.java.
 { return contains(t,null); }
contains() [2/2]
boolean com.cliffc.aa.type.Type< T extends Type< T >.contains (Type< TypeMemPtr > t, VBitSet bs) package inherited
Definition at line 927 of file Type.java.
 { return this==t; }
cross_nil()
final Type com.cliffc.aa.type.Type< T extends Type< T >.cross_nil (Type< TypeMemPtr > t) package inherited
Definition at line 865 of file Type.java.
 { return must_nil() || t.must_nil() ? SCALAR : NSCALR; }
cycle_equals()
boolean com.cliffc.aa.type.TypeMemPtr.cycle_equals (Type o)
Definition at line 44 of file TypeMemPtr.java.
{
     if( this==o ) return true;
     if( !(o instanceof TypeMemPtr) ) return false;
     TypeMemPtr t2 = (TypeMemPtr)o;
     if( _aliases != t2._aliases ) return false;
     return _obj == t2._obj || _obj.cycle_equals(t2._obj);
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMemPtr._obj, and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.cycle_equals().
Referenced by com.cliffc.aa.type.TypeMemPtr.equals().
depth()
HashMap<Type,Integer> com.cliffc.aa.type.TypeMemPtr.depth () package
Definition at line 217 of file TypeMemPtr.java.
{
     int alias = _aliases.getbit();
     HashMap<Type,Integer> ds = new HashMap<>();
     Ary<TypeStruct> t0 = new Ary<>(new TypeStruct[]{(TypeStruct)_obj});
     Ary<TypeStruct> t1 = new Ary<>(new TypeStruct[1],0);
     int d=0;                    // Current depth
     while( !t0.isEmpty() ) {
       while( !t0.isEmpty() ) {
         TypeStruct ts = t0.pop();
         if( ds.putIfAbsent(ts,d) == null )
           for( TypeFld fld : ts.flds() ) {
             if( ds.putIfAbsent(fld._t,d) == null &&  // Everything in flds is in the current depth
                 fld._t instanceof TypeMemPtr ) {
               TypeMemPtr tmp = (TypeMemPtr)fld._t;
               if( tmp._obj instanceof TypeStruct )
                 (tmp._aliases.test(alias) ? t1 : t0).push((TypeStruct)tmp._obj);
             }
           }
       }
       Ary<TypeStruct> tmp = t0; t0 = t1; t1 = tmp; // Swap t0,t1
       d++;                                         // Raise depth
     }
     return ds;
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.Bits< B extends Bits< B >.getbit(), com.cliffc.aa.util.Ary< E >.isEmpty(), com.cliffc.aa.util.Ary< E >.pop(), and com.cliffc.aa.type.Bits< B extends Bits< B >.test().
Referenced by com.cliffc.aa.type.TestApprox.testApprox1(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox4(), com.cliffc.aa.type.TestApprox.testApprox5(), and com.cliffc.aa.type.TestType.testRecursive().
dual()
final T com.cliffc.aa.type.Type< T extends Type< T >.dual inherited
Definition at line 361 of file Type.java.
 { return _dual; }
eq()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.eq (Type< TypeMemPtr >[] t0, Type< TypeMemPtr >[] t1) static inherited
Definition at line 136 of file Type.java.
{
     if( t0==t1 ) return true;
     if( t0==null || t1==null ) return false;
     if( t0.length != t1.length ) return false;
     for( int i=0; i<t0.length; i++ )
       if( t0[i] != t1[i] )
         return false;
     return true;
   }
equals()
boolean com.cliffc.aa.type.TypeMemPtr.equals (Object o)
Definition at line 38 of file TypeMemPtr.java.
{
     if( this==o ) return true;
     if( !(o instanceof TypeMemPtr) ) return false;
     TypeMemPtr tf = (TypeMemPtr)o;
     return cycle_equals(tf);
   }
References com.cliffc.aa.type.TypeMemPtr.cycle_equals().
getbit()
int com.cliffc.aa.type.TypeMemPtr.getbit ()
Definition at line 263 of file TypeMemPtr.java.
 { return _aliases.getbit(); }
References com.cliffc.aa.type.TypeMemPtr._aliases, and com.cliffc.aa.type.Bits< B extends Bits< B >.getbit().
Referenced by com.cliffc.aa.TestParse.test_ptr().
getbit0()
int com.cliffc.aa.type.TypeMemPtr.getbit0 ()
Definition at line 264 of file TypeMemPtr.java.
 { return _aliases.strip_nil().getbit(); }
References com.cliffc.aa.type.TypeMemPtr._aliases, and com.cliffc.aa.type.Bits< B extends Bits< B >.strip_nil().
getd()
double com.cliffc.aa.type.Type< T extends Type< T >.getd inherited
Definition at line 804 of file Type.java.
 { if( _type==TNIL || _type==TXNIL ) return 0.0; throw typerr(null); }
getl()
long com.cliffc.aa.type.Type< T extends Type< T >.getl inherited
Definition at line 802 of file Type.java.
 { if( _type==TNIL || _type==TXNIL ) return 0; throw typerr(null); }
getstr()
String com.cliffc.aa.type.Type< T extends Type< T >.getstr inherited
Definition at line 806 of file Type.java.
 { throw typerr(null); }
has_name()
boolean com.cliffc.aa.type.Type< T extends Type< T >.has_name inherited
Definition at line 549 of file Type.java.
 { return !_name.isEmpty(); }
hashCode()
final int com.cliffc.aa.type.Type< T extends Type< T >.hashCode inherited
Definition at line 106 of file Type.java.
 { assert _hash!=0; return _hash; }
hashcons()
T com.cliffc.aa.type.Type< T extends Type< T >.hashcons private inherited
Definition at line 165 of file Type.java.
{
     _hash = compute_hash();     // Set hash
     T t2 = (T)INTERN.get(this); // Lookup
     if( t2!=null ) {            // Found prior
       assert t2._dual != null;  // Prior is complete with dual
       assert this != t2;        // Do not hashcons twice, should not get self back
       return t2;                // Return prior
     }
     if( RECURSIVE_MEET > 0 )    // Mid-building recursive types; do not intern
       return (T)this;
     // Not in type table
     _dual = null;                // No dual yet
     INTERN.put(this,this);       // Put in table without dual
     T d = xdual();               // Compute dual without requiring table lookup, and not setting name
     d._name = _name;             // xdual does not set name either
     d._hash = d.compute_hash();  // Set dual hash
     _dual = d;
     if( this==d ) return d;      // Self-symmetric?  Dual is self
     assert !equals(d);           // Self-symmetric is handled by caller
     assert d._dual==null;        // Else dual-dual not computed yet
     assert INTERN.get(d)==null;
     d._dual = (T)this;
     INTERN.put(d,d);
     return (T)this;
   }
hashcons_free()
final T com.cliffc.aa.type.Type< T extends Type< T >.hashcons_free package inherited
Definition at line 153 of file Type.java.
{
     T t2 = hashcons();
     return this==t2 ? t2 : (T)POOLS[_type].free(this,t2);
   }
high()
Type com.cliffc.aa.type.Type< T extends Type< T >.high inherited
Definition at line 796 of file Type.java.
 { return above_center() ? this : dual(); }
init() [1/2]
TypeMemPtr com.cliffc.aa.type.TypeMemPtr.init (BitsAlias aliases, TypeObj obj) private
Definition at line 28 of file TypeMemPtr.java.
{
     super.init(TMEMPTR,"");
     _aliases = aliases;
     _obj=obj;
     return this;
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.TypeMemPtr.aliases(), com.cliffc.aa.type.TypeMemPtr.init(), and com.cliffc.aa.type.Type< TypeMemPtr >.TMEMPTR.
Referenced by com.cliffc.aa.type.TypeMemPtr.init(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeMemPtr.rdual(), and com.cliffc.aa.type.TypeMemPtr.xdual().
init() [2/2]
T com.cliffc.aa.type.Type< T extends Type< T >.init (byte type, String name) protected inherited
Definition at line 105 of file Type.java.
 { _type=type; _name=name; return (T)this; }
init0()
static void com.cliffc.aa.type.Type< T extends Type< T >.init0 (HashMap< String, Type< TypeMemPtr > > types) static inherited
Definition at line 642 of file Type.java.
{
     types.put("real",REAL);
     types.put("scalar",SCALAR);
     TypeInt.init1(types);
     TypeFlt.init1(types);
     TypeStr.init1(types);
   }
intern_check()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check static inherited
Definition at line 212 of file Type.java.
{
     int errs=0;
     for( Type k : INTERN.keySet() ) {
       Type v = INTERN.get(k);
       if( !k.intern_check0(v) ) {
         System.out.println("INTERN_CHECK FAIL: "+k._uid+":"+k+" vs "+v._uid+":"+v);
         errs++;
       }
     }
     return errs==0;
   }
intern_check0()
boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check0 (Type< TypeMemPtr > v) private inherited
Definition at line 223 of file Type.java.
{
     if( this != v || _dual==null || _dual._dual!=this || compute_hash()!=_hash ) return false;
     return intern_check1();
   }
intern_check1()
boolean com.cliffc.aa.type.TypeMemPtr.intern_check1 () package
Definition at line 299 of file TypeMemPtr.java.
 { return _obj.intern_lookup()!=null; }
References com.cliffc.aa.type.TypeMemPtr._obj, and com.cliffc.aa.type.Type< T extends Type< T >.intern_lookup().
intern_find()
static Type com.cliffc.aa.type.Type< T extends Type< T >.intern_find (int uid) static package inherited
Definition at line 229 of file Type.java.
{
     for( Type k : INTERN.keySet() )
       if( k._uid==uid )
         return k;
     return null;
   }
intern_lookup()
Type com.cliffc.aa.type.Type< T extends Type< T >.intern_lookup package inherited
Definition at line 210 of file Type.java.
 { return INTERN.get(this); }
intern_size()
static int com.cliffc.aa.type.Type< T extends Type< T >.intern_size static package inherited
Definition at line 211 of file Type.java.
 { return INTERN.size(); }
interned()
boolean com.cliffc.aa.type.Type< T extends Type< T >.interned package inherited
Definition at line 209 of file Type.java.
 { return INTERN.get(this)==this; }
is_con()
boolean com.cliffc.aa.type.TypeMemPtr.is_con ()
Definition at line 179 of file TypeMemPtr.java.
 { return _aliases==BitsAlias.NIL || _aliases==BitsAlias.XNIL; } // only nil
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.BitsAlias.NIL, and com.cliffc.aa.type.BitsAlias.XNIL.
is_display()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_display package inherited
Definition at line 942 of file Type.java.
 { return false; }
is_display_ptr()
boolean com.cliffc.aa.type.TypeMemPtr.is_display_ptr ()
Definition at line 108 of file TypeMemPtr.java.
{
     BitsAlias x = _aliases.strip_nil();
     if( x==BitsAlias.EMPTY ) return true; // Just a NIL
     int alias1 = x.abit();                 // Just a single alias
     // The GENERIC function allows the generic record, otherwise must be on the display list
     if( alias1 != -1 )
       return Math.abs(alias1)==BitsAlias.REC || com.cliffc.aa.Env.ALL_DISPLAYS.test_recur(Math.abs(alias1));
     // If closures are being used, can be multiple valid displays
     for( int alias : _aliases )
       if( alias != 0 && !com.cliffc.aa.Env.ALL_DISPLAYS.test_recur(alias) )
         return false;           // This alias is not on the DISPLAYS list
     return true;
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.Bits< B extends Bits< B >.abit(), com.cliffc.aa.Env.ALL_DISPLAYS, com.cliffc.aa.type.BitsAlias.EMPTY, com.cliffc.aa.type.BitsAlias.REC, and com.cliffc.aa.type.Bits< B extends Bits< B >.strip_nil().
is_forward_ref()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_forward_ref inherited
Definition at line 799 of file Type.java.
 { return false; }
is_num()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_num private inherited
Definition at line 353 of file Type.java.
 { byte t = _type;  return t == TREAL || t == TXREAL || t == TNREAL || t == TXNREAL || t == TINT || t == TFLT; }
is_ptr()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_ptr private inherited
Definition at line 352 of file Type.java.
 { byte t = _type;  return t == TFUNPTR || t == TMEMPTR; }
is_simple()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_simple private inherited
Definition at line 351 of file Type.java.
 { return _type < TSIMPLE; }
isa()
boolean com.cliffc.aa.type.Type< T extends Type< T >.isa (Type< TypeMemPtr > t) inherited
Definition at line 623 of file Type.java.
 { return meet(t)==t; }
isa_scalar()
final boolean com.cliffc.aa.type.Type< T extends Type< T >.isa_scalar inherited
Definition at line 356 of file Type.java.
 { assert ISA_SCALAR.length==TLAST; return ISA_SCALAR[_type]!=0; }
isBitShape()
byte com.cliffc.aa.type.TypeMemPtr.isBitShape (Type t)
Definition at line 257 of file TypeMemPtr.java.
{
     if( t == Type.SCALAR ) return 0; // Scalar function arg; generally dead or just passed along blindly.
     return (byte)(t instanceof TypeMemPtr ? 0 : 99);  // Mixing TMP and a non-ptr
   }
References com.cliffc.aa.type.Type< T extends Type< T >.SCALAR.
join()
Type com.cliffc.aa.type.Type< T extends Type< T >.join (Type< TypeMemPtr > t) inherited
Definition at line 619 of file Type.java.
 { return dual().meet(t.dual()).dual(); }
make() [1/3]
static TypeMemPtr com.cliffc.aa.type.TypeMemPtr.make (BitsAlias aliases, TypeObj obj) static
Definition at line 66 of file TypeMemPtr.java.
{
     TypeMemPtr t1 = POOLS[TMEMPTR].malloc();
     return t1.init(aliases,obj).hashcons_free();
   }
References com.cliffc.aa.type.TypeMemPtr.aliases(), com.cliffc.aa.type.Type< T extends Type< T >.hashcons_free(), com.cliffc.aa.type.TypeMemPtr.init(), com.cliffc.aa.type.Type< TypeMemPtr >.POOLS, and com.cliffc.aa.type.Type< TypeMemPtr >.TMEMPTR.
Referenced by com.cliffc.aa.HM.HM9.T2._as_flow(), com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.node.NewNode< TypeStruct >._init(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Pair.apply(), com.cliffc.aa.HM.HM.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Triple.apply(), com.cliffc.aa.HM.HM.Pair.apply(), com.cliffc.aa.HM.HM.Triple.apply(), com.cliffc.aa.HM.HM9.Str.apply(), com.cliffc.aa.HM.HM.Str.apply(), com.cliffc.aa.HM.TestHM.build_cycle(), com.cliffc.aa.HM.TestHM9.build_cycle(), com.cliffc.aa.HM.TestHM.build_cycle2(), com.cliffc.aa.node.IntrinsicNode.convertTypeName(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.node.IntrinsicNode.err(), com.cliffc.aa.node.FunNode.find_type_split(), com.cliffc.aa.node.FunPtrNode.forward_ref(), com.cliffc.aa.node.NewNode< TypeStruct >.kill2(), com.cliffc.aa.type.TypeMemPtr.make_from(), com.cliffc.aa.type.TypeMemPtr.make_nil(), com.cliffc.aa.type.TypeMemPtr.meet_nil(), com.cliffc.aa.type.TypeMemPtr.not_nil(), com.cliffc.aa.node.NewObjNode.promote_forward(), com.cliffc.aa.type.TypeMemPtr.simple_ptr(), com.cliffc.aa.HM.HM9.string(), com.cliffc.aa.HM.HM.string(), com.cliffc.aa.HM.TestHM.test02(), com.cliffc.aa.HM.TestHM9.test02(), com.cliffc.aa.HM.TestHM.test06(), com.cliffc.aa.HM.TestHM9.test06(), com.cliffc.aa.HM.TestHM.test14(), com.cliffc.aa.HM.TestHM9.test14(), com.cliffc.aa.HM.TestHM.test18(), com.cliffc.aa.HM.TestHM9.test18(), com.cliffc.aa.HM.TestHM.test20(), com.cliffc.aa.HM.TestHM9.test20(), com.cliffc.aa.HM.TestHM.test25(), com.cliffc.aa.HM.TestHM9.test25(), com.cliffc.aa.HM.TestHM9.test35(), com.cliffc.aa.HM.TestHM.test35(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.HM.TestHM.test41(), com.cliffc.aa.HM.TestHM9.test41(), com.cliffc.aa.HM.TestHM.test49(), com.cliffc.aa.HM.TestHM9.test49(), com.cliffc.aa.HM.TestHM.test50(), com.cliffc.aa.HM.TestHM9.test50(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.HM.TestHM.test55(), com.cliffc.aa.HM.TestHM.test57(), com.cliffc.aa.type.TestApprox.testApprox1(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox4(), com.cliffc.aa.type.TestApprox.testApprox5(), com.cliffc.aa.type.TestApprox.testApprox7(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.type.TestType.testLoad(), com.cliffc.aa.node.TestNodeSmall.testMemoryArgs(), com.cliffc.aa.type.TestType.testNameCycle(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.TestParse.testParse02(), com.cliffc.aa.TestParse.testParse06(), com.cliffc.aa.TestParse.testParse07(), com.cliffc.aa.TestParse.testParse08(), com.cliffc.aa.TestParse.testParse15(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.type.TestType.testStructTuple(), com.cliffc.aa.type.TestApprox.testTSMeet(), com.cliffc.aa.type.TestType.testType(), com.cliffc.aa.Parse.tstmt(), com.cliffc.aa.Parse.type0(), com.cliffc.aa.Parse.typep(), com.cliffc.aa.HM.HM9.Struct.val(), com.cliffc.aa.HM.HM.Struct.val(), com.cliffc.aa.node.CallNode.value(), com.cliffc.aa.type.TypeMemPtr.widen(), and com.cliffc.aa.type.TypeMemPtr.xmeet().
make() [2/3]
static Type com.cliffc.aa.type.Type< T extends Type< T >.make (byte type) static package inherited
Definition at line 147 of file Type.java.
{
     Pool P = POOLS[type];
     Type t1 = P.malloc();
     return t1.init(type,"").hashcons_free();
   }
make() [3/3]
static TypeMemPtr com.cliffc.aa.type.TypeMemPtr.make (int alias, TypeObj obj) static
Definition at line 71 of file TypeMemPtr.java.
 { return make(BitsAlias.make0(alias),obj); }
References com.cliffc.aa.type.TypeMemPtr.make(), and com.cliffc.aa.type.BitsAlias.make0().
Referenced by com.cliffc.aa.type.TypeMemPtr.make().
make_from() [1/2]
Type com.cliffc.aa.type.TypeMemPtr.make_from (Type head, TypeMem mem, VBitSet visit)
Definition at line 281 of file TypeMemPtr.java.
{
     if( this!=head ) {
       TypeObj[] pubs = mem.alias2objs();
       boolean mapped=true;
       for( int alias : _aliases )
         if( pubs[alias]==null )
           { mapped=false; break; }
       if( mapped ) {
         TypeObj obj = mem.ld(this);
         if( obj!=TypeObj.XOBJ )
           return make_from(obj);
       }
     }
     TypeObj obj = (TypeObj)_obj.make_from(head,mem,visit);
     return obj == null ? this : make_from(obj);
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.TypeMem.alias2objs(), com.cliffc.aa.type.TypeMem.ld(), com.cliffc.aa.type.TypeMemPtr.make_from(), com.cliffc.aa.type.Type< T extends Type< T >.make_from(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.XOBJ.
make_from() [2/2]
TypeMemPtr com.cliffc.aa.type.TypeMemPtr.make_from (TypeObj obj)
Definition at line 73 of file TypeMemPtr.java.
 { return make(_aliases,obj); }
References com.cliffc.aa.type.TypeMemPtr._aliases, and com.cliffc.aa.type.TypeMemPtr.make().
Referenced by com.cliffc.aa.type.TypeStruct._dull(), com.cliffc.aa.type.TypeStruct._sharp(), com.cliffc.aa.type.TypeMemPtr.make_from(), com.cliffc.aa.type.TypeStruct.sharpen(), com.cliffc.aa.node.ConTypeNode.value(), com.cliffc.aa.HM.HM9.T2.walk_types_out(), and com.cliffc.aa.HM.HM.T2.walk_types_out().
make_nil()
static TypeMemPtr com.cliffc.aa.type.TypeMemPtr.make_nil (int alias, TypeObj obj) static
Definition at line 72 of file TypeMemPtr.java.
 { return make(BitsAlias.make0(alias).meet_nil(),obj); }
References com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.BitsAlias.make0(), and com.cliffc.aa.type.Bits< B extends Bits< B >.meet_nil().
Referenced by com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.TestParse.testParse01(), com.cliffc.aa.TestParse.testParse05(), com.cliffc.aa.TestParse.testParse07(), com.cliffc.aa.type.TestType.testRecursive(), and com.cliffc.aa.type.TestType.testStructTuple().
max()
static int com.cliffc.aa.type.TypeMemPtr.max (int alias, HashMap< Type, Integer > ds) static package
Definition at line 243 of file TypeMemPtr.java.
{
     int max = -1;
     for( Type t : ds.keySet() )
       if( (t instanceof TypeMemPtr) && ((TypeMemPtr)t)._aliases.test(alias) )
         max = Math.max(max,ds.get(t));
     return max+1;               // Struct is 1 more depth than TMP
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, and com.cliffc.aa.type.Bits< B extends Bits< B >.test().
Referenced by com.cliffc.aa.type.TestApprox.testApprox1(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox4(), com.cliffc.aa.type.TestApprox.testApprox5(), and com.cliffc.aa.type.TestType.testRecursive().
may_be_con()
boolean com.cliffc.aa.type.TypeMemPtr.may_be_con ()
Definition at line 178 of file TypeMemPtr.java.
 { return may_nil(); }
References com.cliffc.aa.type.TypeMemPtr.may_nil().
may_nil()
boolean com.cliffc.aa.type.TypeMemPtr.may_nil ()
Definition at line 181 of file TypeMemPtr.java.
 { return _aliases.may_nil(); }
References com.cliffc.aa.type.TypeMemPtr._aliases, and com.cliffc.aa.type.Bits< B extends Bits< B >.may_nil().
Referenced by com.cliffc.aa.type.TypeMemPtr.may_be_con().
meet()
final Type com.cliffc.aa.type.Type< T extends Type< T >.meet (Type< TypeMemPtr > t) inherited
Definition at line 412 of file Type.java.
{
     // Short cut for the self case
     if( t == this ) return this;
     // Short-cut for seeing this meet before
     Type mt = Key.get(this,t);
     if( mt != null ) return mt;
     // "Triangulate" the matrix and cut in half the number of cases.
     // Reverse; xmeet 2nd arg is never "is_simple" and never equal to "this".
     // This meet ignores the _name field, and can return any-old name it wants.
     mt = !is_simple() && t.is_simple() ? t.xmeet(this) : xmeet(t);
     // Meet the names.  Subclasses basically ignore the names as they have
     // their own complicated meets to perform, so we meet them here for all.
     Type nmt = xmt_name(t,mt);
     // Quick check on NIL: if either argument is NIL the result is allowed to
     // be NIL...  but nobody in the lattice can make a NIL from whole cloth, or
     // we get the crossing-nil bug.
     assert (nmt != NIL && nmt!=XNIL) || this==NIL || this==XNIL || t==NIL || t==XNIL;
     // Record this meet, to short-cut next time
     if( RECURSIVE_MEET == 0 )   // Only not mid-building recursive types;
       Key.put(this,t,nmt);
     return nmt;
   }
meet_loop()
Type com.cliffc.aa.type.Type< T extends Type< T >.meet_loop (Type< TypeMemPtr > t2) inherited
Definition at line 628 of file Type.java.
 { return meet(t2); }
meet_nil()
Type com.cliffc.aa.type.TypeMemPtr.meet_nil (Type nil)
Definition at line 186 of file TypeMemPtr.java.
{
     assert nil==NIL || nil==XNIL;
     // See testLattice15.  The UNSIGNED NIL tests as a lattice:
     //    [~0]->~obj  ==>  NIL  ==>  [0]-> obj
     // But loses the pointed-at type down to OBJ.
     // So using SIGNED NIL, which also tests as a lattice:
     //    [~0]->~obj ==>  XNIL  ==>  [0]->~obj
     //    [~0]-> obj ==>   NIL  ==>  [0]-> obj
     if( _aliases.isa(BitsAlias.XNIL) ) {
       if( _obj.above_center() && nil==XNIL )  return XNIL;
       if( nil==NIL ) return NIL;
     }
     return make(_aliases.meet(BitsAlias.NIL),_obj);
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.above_center(), com.cliffc.aa.type.Bits< B extends Bits< B >.isa(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.Bits< B extends Bits< B >.meet(), com.cliffc.aa.type.BitsAlias.NIL, com.cliffc.aa.type.Type< TypeMemPtr >.NIL, com.cliffc.aa.type.BitsAlias.XNIL, and com.cliffc.aa.type.Type< TypeMemPtr >.XNIL.
mtname()
final String com.cliffc.aa.type.Type< T extends Type< T >.mtname (Type< TypeMemPtr > t, Type< TypeMemPtr > mt) package inherited
Definition at line 567 of file Type.java.
{
     Type   t0 = this,  t1 = t;
     String s0 = t0._name, s1 = t1._name;
     assert check_name(s0) && check_name(s1);
     if( Util.eq(s0,s1) ) return s0;
     // Sort by name length
     if( s0.length() > s1.length() ) { t1=this; t0=t; s0=t0._name; s1=t1._name; }
     int x = 0, i;  char c;    // Last colon separator index
     // Find split point
     for( i = 0; i < s0.length(); i++ ) {
       if( (c=s0.charAt(i)) != s1.charAt(i) )
         break;
       if( c==':' ) x=i;
     }
     // If s0 is a prefix of s1, and s0 is high then it can cover s1.
     if( i==s0.length() && t0.above_center() && (!t1.above_center() || mt.above_center()) )
       return s1;
     // Keep the common prefix, which might be all of s0
     String s2 = i==s0.length() ? s0 : s0.substring(0, x).intern();
     assert check_name(s2);
     return s2;
   }
must_nil()
boolean com.cliffc.aa.type.TypeMemPtr.must_nil ()
Definition at line 180 of file TypeMemPtr.java.
 { return _aliases.test(0) && !above_center(); }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMemPtr.above_center(), and com.cliffc.aa.type.Bits< B extends Bits< B >.test().
not_nil()
Type com.cliffc.aa.type.TypeMemPtr.not_nil () package
Definition at line 182 of file TypeMemPtr.java.
{
     BitsAlias bits = _aliases.not_nil();
     return bits==_aliases ? this : make(bits,_obj);
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.TypeMemPtr.make(), and com.cliffc.aa.type.Bits< B extends Bits< B >.not_nil().
oob() [1/6]
Type com.cliffc.aa.type.Type< T extends Type< T >.oob inherited
Definition at line 635 of file Type.java.
 { return oob(ALL); }
oob() [2/6]
Type com.cliffc.aa.type.Type< T extends Type< T >.oob (Type< TypeMemPtr > e) inherited
Definition at line 636 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [3/6]
TypeMem com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeMem e) inherited
Definition at line 639 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [4/6]
TypeMemPtr com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeMemPtr e) inherited
Definition at line 640 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [5/6]
TypeObj com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeObj e) inherited
Definition at line 637 of file Type.java.
 { return above_center() ? (TypeObj)e.dual() : e; }
oob() [6/6]
TypeStruct com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeStruct e) inherited
Definition at line 638 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob_deep()
Type com.cliffc.aa.type.Type< T extends Type< T >.oob_deep (Type< TypeMemPtr > t) inherited
Definition at line 632 of file Type.java.
 { return oop_deep_impl(t); }
oop_deep_impl()
Type com.cliffc.aa.type.TypeMemPtr.oop_deep_impl (Type t)
Definition at line 167 of file TypeMemPtr.java.
{
     if( !(t instanceof TypeMemPtr) ) return oob();
     TypeMemPtr tmp = (TypeMemPtr)t;
     // Deep bounds; keep the in-bounds _aliases but bound the _obj.
     if( tmp._aliases.dual().isa(_aliases) && _aliases.isa(tmp._aliases) )
       return _obj.oop_deep_impl(tmp._obj);
     // Aliases OOB
     return oob();
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.Bits< B extends Bits< B >.dual(), com.cliffc.aa.type.Bits< B extends Bits< B >.isa(), com.cliffc.aa.type.Type< TypeMemPtr >.oob(), and com.cliffc.aa.type.Type< T extends Type< T >.oop_deep_impl().
rdual()
TypeMemPtr com.cliffc.aa.type.TypeMemPtr.rdual () package
Definition at line 129 of file TypeMemPtr.java.
{
     if( _dual != null ) return _dual;
     TypeMemPtr dual = _dual = new TypeMemPtr().init(_aliases.dual(),(TypeObj)_obj.rdual());
     dual._dual = this;
     if( _hash != 0 ) dual._hash = dual.compute_hash();
     return dual;
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.Type< TypeMemPtr >._dual, com.cliffc.aa.type.Type< TypeMemPtr >._hash, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.Type< TypeMemPtr >.dual(), com.cliffc.aa.type.Bits< B extends Bits< B >.dual(), com.cliffc.aa.type.TypeMemPtr.init(), and com.cliffc.aa.type.Type< T extends Type< T >.rdual().
remove_name()
final T com.cliffc.aa.type.Type< T extends Type< T >.remove_name inherited
Definition at line 556 of file Type.java.
 { return has_name() ? _set_name("") : (T)this; }
repeats_in_cycles()
TypeStruct com.cliffc.aa.type.Type< T extends Type< T >.repeats_in_cycles (TypeStruct head, VBitSet bs) package inherited
Definition at line 938 of file Type.java.
 { return null; }
retern()
final T com.cliffc.aa.type.Type< T extends Type< T >.retern package inherited
Definition at line 201 of file Type.java.
                     {
     assert _dual._dual == this;
     assert _hash != 0;
     assert INTERN.get(this)==null;
     INTERN.put(this,this);
     assert INTERN.get(this)==this;
     return (T)this;
   }
set_name()
final T com.cliffc.aa.type.Type< T extends Type< T >.set_name (String name) inherited
Definition at line 551 of file Type.java.
{
     assert check_name(name);
     return _set_name(name);
   }
sharptr()
Type com.cliffc.aa.type.Type< T extends Type< T >.sharptr (Type< TypeMemPtr > ptr) inherited
Definition at line 930 of file Type.java.
 { return this==ANY ? TypeMem.ANYMEM.sharptr(ptr) : ptr; }
simple_ptr()
Type com.cliffc.aa.type.TypeMemPtr.simple_ptr ()
Definition at line 160 of file TypeMemPtr.java.
{
     if( _obj==TypeObj.ISUSED || _obj==TypeObj.UNUSED ) return this;
     return make(_aliases,_aliases.above_center() ? TypeObj.UNUSED : TypeObj.ISUSED);
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.Bits< B extends Bits< B >.above_center(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.ISUSED, com.cliffc.aa.type.TypeMemPtr.make(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED.
Referenced by com.cliffc.aa.type.TypeMem.sharpen(), com.cliffc.aa.type.TypeStruct.sharpen(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), and com.cliffc.aa.node.TestNodeSmall.testMemoryArgs().
str()
SB com.cliffc.aa.type.TypeMemPtr.str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
Definition at line 52 of file TypeMemPtr.java.
{
     //if( debug ) sb.p('_').p(_uid);
     if( dups.tset(_uid) ) return sb.p('$'); // Break recursive printing cycle
     //if( _aliases==BitsAlias.NIL || _aliases==BitsAlias.NIL.dual() ) return sb.p(debug ? " 0" : "0");
     TypeObj to = (mem == null || _aliases==BitsAlias.RECORD_BITS) ? _obj : mem.ld(this);
     if( to == TypeObj.XOBJ ) to = _obj;
     sb.p('*');
     if( debug ) _aliases.str(sb);
     to.str(sb,dups,mem,debug);
     if( _aliases.test(0) ) sb.p('?');
     return sb;
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.Type< TypeMemPtr >._uid, com.cliffc.aa.type.TypeMem.ld(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.BitsAlias.RECORD_BITS, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.str(), com.cliffc.aa.type.Bits< B extends Bits< B >.str(), com.cliffc.aa.type.Bits< B extends Bits< B >.test(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.XOBJ.
Referenced by com.cliffc.aa.REPL.go_one().
toString()
final String com.cliffc.aa.type.Type< T extends Type< T >.toString inherited
Definition at line 127 of file Type.java.
 { return str(new SB(),new VBitSet(),null,true).toString(); }
typerr()
RuntimeException com.cliffc.aa.type.Type< T extends Type< T >.typerr (Type< TypeMemPtr > t) package inherited
Definition at line 947 of file Type.java.
{
     throw new RuntimeException("Should not reach here: internal type system error with "+this+(t==null?"":(" and "+t)));
   }
untern()
final T com.cliffc.aa.type.Type< T extends Type< T >.untern package inherited
Definition at line 193 of file Type.java.
                     {
     assert _hash != 0;
     assert INTERN.get(this)==this;
     Type rez = INTERN.remove(this);
     assert rez == this;
     return (T)this;
   }
walk()
void com.cliffc.aa.type.TypeMemPtr.walk (Predicate< Type > p)
Definition at line 262 of file TypeMemPtr.java.
 { if( p.test(this) ) _obj.walk(p); }
References com.cliffc.aa.type.TypeMemPtr._obj, and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.walk().
widen()
TypeMemPtr com.cliffc.aa.type.TypeMemPtr.widen ()
Definition at line 270 of file TypeMemPtr.java.
{
     // Flatten to either all-structs or all-strings, unless both.
     BitsAlias bs = null;
     if( _aliases.isa(BitsAlias.RECORD_BITS0) )  bs = BitsAlias.RECORD_BITS0;
     if( _aliases.isa(BitsAlias.STRBITS0) ) bs = bs==null ? BitsAlias.STRBITS0 : BitsAlias.FULL;
     if( _aliases.isa(BitsAlias.ARYBITS0) ) bs = bs==null ? BitsAlias.ARYBITS0 : BitsAlias.FULL;
     if( bs==null ) return this; // Already plenty wide
     return make(bs,_obj.widen());
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.BitsAlias.ARYBITS0, com.cliffc.aa.type.BitsAlias.FULL, com.cliffc.aa.type.Bits< B extends Bits< B >.isa(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.BitsAlias.RECORD_BITS0, com.cliffc.aa.type.BitsAlias.STRBITS0, and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.widen().
xdual()
TypeMemPtr com.cliffc.aa.type.TypeMemPtr.xdual () protected
Definition at line 122 of file TypeMemPtr.java.
{
     BitsAlias ad = _aliases.dual();
     TypeObj od = (TypeObj)_obj.dual();
     if( ad==_aliases && od==_obj )
       return this;              // Centerline TMP
     return new TypeMemPtr().init(ad,od);
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.Type< T extends Type< T >.dual(), com.cliffc.aa.type.Bits< B extends Bits< B >.dual(), and com.cliffc.aa.type.TypeMemPtr.init().
xmeet()
Type com.cliffc.aa.type.TypeMemPtr.xmeet (Type t) protected
Definition at line 136 of file TypeMemPtr.java.
{
     switch( t._type ) {
     case TMEMPTR:break;
     case TFLT:
     case TINT:
     case TFUNPTR:
     case TRPC:   return cross_nil(t);
     case TFUNSIG:
     case TARY:
     case TLIVE:
     case TOBJ:
     case TSTR:
     case TSTRUCT:
     case TTUPLE:
     case TMEM:   return ALL;
     default: throw typerr(t);   // All else should not happen
     }
     // Meet of aliases
     TypeMemPtr ptr = (TypeMemPtr)t;
     BitsAlias aliases = _aliases.meet(ptr._aliases);
     TypeObj to = (TypeObj)_obj.meet(ptr._obj);
     return make(aliases, to);
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.type.TypeMemPtr.aliases(), com.cliffc.aa.type.Type< TypeMemPtr >.ALL, com.cliffc.aa.type.Type< TypeMemPtr >.cross_nil(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.Bits< B extends Bits< B >.meet(), com.cliffc.aa.type.Type< T extends Type< T >.meet(), com.cliffc.aa.type.Type< TypeMemPtr >.TARY, com.cliffc.aa.type.Type< TypeMemPtr >.TFLT, com.cliffc.aa.type.Type< TypeMemPtr >.TFUNPTR, com.cliffc.aa.type.Type< TypeMemPtr >.TFUNSIG, com.cliffc.aa.type.Type< TypeMemPtr >.TINT, com.cliffc.aa.type.Type< TypeMemPtr >.TLIVE, com.cliffc.aa.type.Type< TypeMemPtr >.TMEM, com.cliffc.aa.type.Type< TypeMemPtr >.TMEMPTR, com.cliffc.aa.type.Type< TypeMemPtr >.TOBJ, com.cliffc.aa.type.Type< TypeMemPtr >.TRPC, com.cliffc.aa.type.Type< TypeMemPtr >.TSTR, com.cliffc.aa.type.Type< TypeMemPtr >.TSTRUCT, com.cliffc.aa.type.Type< TypeMemPtr >.TTUPLE, and com.cliffc.aa.type.Type< TypeMemPtr >.typerr().
xmt_name()
Type com.cliffc.aa.type.Type< T extends Type< T >.xmt_name (Type< TypeMemPtr > t, Type< TypeMemPtr > mt) private inherited
Definition at line 441 of file Type.java.
{
     String n = mtname(t,mt);    // Meet name strings
     // If the names are incompatible and the meet remained high then the
     // mismatched names force a drop.
     if( n.length() < _name.length() && n.length() < t._name.length() && mt.above_center() ) {
       if( mt.interned() ) // recursive type creation?
         mt = mt.dual();   // Force low
     }
     if( mt.is_simple() ) n=""; // No named simple types
     if( mt._type==TOBJ ) n=""; // OBJ splits into strings (arrays) and structs, which can keep their names
     // Inject the name
     if( !Util.eq(mt._name,n) )  // Fast path cutout
       mt = mt.set_name(n);
     return mt;
   }
Member Data Documentation
_aliases
BitsAlias com.cliffc.aa.type.TypeMemPtr._aliases
Definition at line 16 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.type.TypeStruct._dull(), com.cliffc.aa.node.LoadNode._find_previous_store_call(), com.cliffc.aa.type.TypeStruct._sharp(), com.cliffc.aa.type.TypeMemPtr.above_center(), com.cliffc.aa.type.TypeMemPtr.aliases(), com.cliffc.aa.type.TypeStruct.ax_impl_ptr(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.TypeMemPtr.ax_meet_nil(), com.cliffc.aa.type.TestApprox.check_leaf(), com.cliffc.aa.type.TypeMemPtr.compute_hash(), com.cliffc.aa.type.TypeMemPtr.cycle_equals(), com.cliffc.aa.type.TypeMemPtr.depth(), com.cliffc.aa.node.NewNode< TypeStruct >.escapees(), com.cliffc.aa.node.CallNode.escapees(), com.cliffc.aa.node.ScopeNode.get_type(), com.cliffc.aa.type.TypeMemPtr.getbit(), com.cliffc.aa.type.TypeMemPtr.getbit0(), com.cliffc.aa.node.StoreNode.ideal_grow(), com.cliffc.aa.node.LoadNode.ideal_mono(), com.cliffc.aa.node.LoadNode.ideal_reduce(), com.cliffc.aa.node.IntrinsicNode.ideal_reduce(), com.cliffc.aa.type.TypeMemPtr.init(), com.cliffc.aa.type.TypeMemPtr.is_con(), com.cliffc.aa.type.TypeMemPtr.is_display_ptr(), com.cliffc.aa.type.TypeMem.ld(), com.cliffc.aa.type.TypeMemPtr.make_from(), com.cliffc.aa.type.TypeMemPtr.max(), com.cliffc.aa.type.TypeMemPtr.may_nil(), com.cliffc.aa.type.TypeMemPtr.meet_nil(), com.cliffc.aa.type.TypeMemPtr.must_nil(), com.cliffc.aa.type.TypeMemPtr.not_nil(), com.cliffc.aa.type.TypeMemPtr.oop_deep_impl(), com.cliffc.aa.type.TypeMemPtr.rdual(), com.cliffc.aa.type.TypeMemPtr.simple_ptr(), com.cliffc.aa.type.TypeMemPtr.str(), com.cliffc.aa.TestParse.test_ptr0(), com.cliffc.aa.type.TestType.testNameCycle(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.node.StoreNode.unify(), com.cliffc.aa.node.LoadNode.unify(), com.cliffc.aa.node.StoreNode.value(), com.cliffc.aa.node.MemPrimNode.LValueWrite.value(), com.cliffc.aa.node.MemPrimNode.LValueWriteFinal.value(), com.cliffc.aa.node.CallEpiNode.value(), com.cliffc.aa.type.TypeMemPtr.widen(), com.cliffc.aa.type.TypeMemPtr.xdual(), and com.cliffc.aa.type.TypeMemPtr.xmeet().
_dual
T com.cliffc.aa.type.Type< T extends Type< T >._dual package inherited
Definition at line 100 of file Type.java.
_hash
int com.cliffc.aa.type.Type< T extends Type< T >._hash inherited
Definition at line 97 of file Type.java.
_name
String com.cliffc.aa.type.Type< T extends Type< T >._name inherited
Definition at line 99 of file Type.java.
_obj
TypeObj com.cliffc.aa.type.TypeMemPtr._obj
Definition at line 26 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.type.TypeStruct._is_sharp(), com.cliffc.aa.type.TypeStruct._sharp(), com.cliffc.aa.type.TypeStruct.ax_impl_ptr(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.TypeMemPtr.ax_meet_nil(), com.cliffc.aa.type.TestApprox.check_leaf(), com.cliffc.aa.type.TypeMemPtr.compute_hash(), com.cliffc.aa.type.TypeMemPtr.cycle_equals(), com.cliffc.aa.type.TypeMemPtr.depth(), com.cliffc.aa.type.TypeMemPtr.init(), com.cliffc.aa.type.TypeMemPtr.intern_check1(), com.cliffc.aa.type.TypeMemPtr.make_from(), com.cliffc.aa.type.TypeMemPtr.meet_nil(), com.cliffc.aa.type.TypeMemPtr.not_nil(), com.cliffc.aa.type.TypeMemPtr.oop_deep_impl(), com.cliffc.aa.type.TypeMemPtr.rdual(), com.cliffc.aa.type.TypeStruct.sharpen(), com.cliffc.aa.type.TypeStruct.shrink(), com.cliffc.aa.type.TypeMemPtr.simple_ptr(), com.cliffc.aa.type.TypeMemPtr.str(), com.cliffc.aa.type.TestApprox.testApprox1(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox4(), com.cliffc.aa.type.TestType.testNameCycle(), com.cliffc.aa.type.TestApprox.testTSMeet(), com.cliffc.aa.HM.HM9.Field.val(), com.cliffc.aa.HM.HM.Field.val(), com.cliffc.aa.node.ConTypeNode.value(), com.cliffc.aa.node.MemPrimNode.LValueLength.value(), com.cliffc.aa.node.MemPrimNode.LValueRead.value(), com.cliffc.aa.type.TypeMemPtr.walk(), com.cliffc.aa.HM.HM9.T2.walk_types_in(), com.cliffc.aa.HM.HM.T2.walk_types_in(), com.cliffc.aa.HM.HM9.T2.walk_types_out(), com.cliffc.aa.HM.HM.T2.walk_types_out(), com.cliffc.aa.type.TypeMemPtr.widen(), com.cliffc.aa.type.TypeMemPtr.xdual(), and com.cliffc.aa.type.TypeMemPtr.xmeet().
_type
byte com.cliffc.aa.type.Type< T extends Type< T >._type package inherited
Definition at line 98 of file Type.java.
_uid
int com.cliffc.aa.type.Type< T extends Type< T >._uid inherited
Definition at line 96 of file Type.java.
ABC0
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.ABC0 = make(ABCPTR._aliases.meet_nil(),TypeStr.ABC) static
Definition at line 100 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.type.TestType.testOOPsNulls().
ABCPTR
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.ABCPTR = make(BitsAlias.ABC ,TypeStr.ABC) static
Definition at line 99 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.type.TestType.testBits(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.type.TestType.testLoad(), com.cliffc.aa.node.TestNodeSmall.testMemoryArgs(), and com.cliffc.aa.type.TestType.testOOPsNulls().
ALL
final Type com.cliffc.aa.type.Type< T extends Type< T >.ALL static inherited
Definition at line 324 of file Type.java.
ALL_TYPES
Ary<Type> com.cliffc.aa.type.Type< T extends Type< T >.ALL_TYPES static private inherited
Definition at line 650 of file Type.java.
ANY
final Type com.cliffc.aa.type.Type< T extends Type< T >.ANY static inherited
Definition at line 325 of file Type.java.
ARY0
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.ARY0 = make(BitsAlias.ARYBITS0,TypeAry.ARY) static
Definition at line 96 of file TypeMemPtr.java.
ARYPTR
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.ARYPTR = make(BitsAlias.ARYBITS ,TypeAry.ARY) static
Definition at line 95 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.node.MemPrimNode.err().
CNT
int com.cliffc.aa.type.Type< T extends Type< T >.CNT static private inherited
Definition at line 95 of file Type.java.
CTRL
final Type com.cliffc.aa.type.Type< T extends Type< T >.CTRL static inherited
Definition at line 326 of file Type.java.
DISP_FLD
final TypeFld com.cliffc.aa.type.TypeMemPtr.DISP_FLD = TypeFld.malloc("^",Type.NIL,Access.Final,0) static
Definition at line 77 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.TestParse.testParse04(), com.cliffc.aa.TestParse.testParse07(), com.cliffc.aa.TestParse.testParse10(), and com.cliffc.aa.Parse.type0().
DISP_SIMPLE
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.DISP_SIMPLE = make(BitsAlias.RECORD_BITS0,TypeObj.ISUSED) static
Definition at line 105 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.type.TypeFunPtr.meet_nil(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), and com.cliffc.aa.Parse.type0().
DISPLAY
final TypeStruct com.cliffc.aa.type.TypeMemPtr.DISPLAY = TypeStruct.malloc("",false,TypeFlds.ts(DISP_FLD),true) static
Definition at line 78 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.type.TypeStruct.is_display(), com.cliffc.aa.type.TestType.testCrush(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.TestLive.testNewObj(), and com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay().
DISPLAY_PTR
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.DISPLAY_PTR = new TypeMemPtr().init(BitsAlias.RECORD_BITS0,DISPLAY) static
Definition at line 79 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.type.TestApprox.testApprox8().
EMTPTR
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.EMTPTR = make(BitsAlias.EMPTY,TypeObj.UNUSED) static
Definition at line 104 of file TypeMemPtr.java.
INTERN
final ConcurrentHashMap<Type,Type> com.cliffc.aa.type.Type< T extends Type< T >.INTERN static private inherited
Definition at line 162 of file Type.java.
ISA_SCALAR
final byte [] com.cliffc.aa.type.Type< T extends Type< T >.ISA_SCALAR static private inherited
Definition at line 355 of file Type.java.
ISUSED
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.ISUSED = make(BitsAlias.NZERO ,TypeObj.ISUSED) static
Definition at line 92 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.node.MemPrimNode.err(), com.cliffc.aa.Parse.term(), and com.cliffc.aa.TestParse.testParse06().
ISUSED0
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.ISUSED0 = make(BitsAlias.FULL ,TypeObj.ISUSED) static
Definition at line 91 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.node.FreshNode.no_tvar_structure(), and com.cliffc.aa.node.PrimNode.PRIMS().
NIL
final Type com.cliffc.aa.type.Type< T extends Type< T >.NIL static inherited
Definition at line 332 of file Type.java.
NILPTR
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.NILPTR = make(BitsAlias.NIL,TypeObj.ISUSED) static
Definition at line 103 of file TypeMemPtr.java.
NO_DISP
final Type com.cliffc.aa.type.TypeMemPtr.NO_DISP = Type.ANY static
Definition at line 80 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.node.LoadNode.get_fld2(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.type.TypeFunPtr.is_con(), com.cliffc.aa.type.TypeFunPtr.make_no_disp(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.HM.TestHM.test55(), com.cliffc.aa.HM.TestHM.test57(), com.cliffc.aa.TestParse.test_name(), com.cliffc.aa.TestParse.test_struct(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.TestParse.testParse(), com.cliffc.aa.TestParse.testParse04(), com.cliffc.aa.Parse.tuple(), and com.cliffc.aa.node.Node.walk_opt().
NREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.NREAL static package inherited
Definition at line 336 of file Type.java.
NSCALR
final Type com.cliffc.aa.type.Type< T extends Type< T >.NSCALR static inherited
Definition at line 330 of file Type.java.
OOP
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.OOP = make(BitsAlias.NZERO ,TypeObj.OBJ) static
Definition at line 94 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.type.TypeMem.all_reaching_aliases(), com.cliffc.aa.node.ScopeNode.compute_live_mem(), com.cliffc.aa.node.PrimNode.ConvertStrStr.ConvertStrStr(), com.cliffc.aa.node.CallNode.get_alias(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.node.CallNode.tesc(), com.cliffc.aa.type.TestType.testOOPsNulls(), and com.cliffc.aa.TestParse.testParse04().
OOP0
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.OOP0 = make(BitsAlias.FULL ,TypeObj.OBJ) static
Definition at line 93 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.node.FunNode.bad_mem_use(), com.cliffc.aa.type.Type< TypeFlt >.check_startup(), com.cliffc.aa.node.CallEpiNode.esc_out(), com.cliffc.aa.node.ScopeNode.ideal_reduce(), com.cliffc.aa.type.TestType.testBits0(), com.cliffc.aa.type.TestType.testOOPsNulls(), and com.cliffc.aa.TestParse.testParse08().
POOLS
final Pool [] com.cliffc.aa.type.Type< T extends Type< T >.POOLS static package inherited
Definition at line 281 of file Type.java.
REAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.REAL static inherited
Definition at line 334 of file Type.java.
RECURSIVE_MEET
int com.cliffc.aa.type.Type< T extends Type< T >.RECURSIVE_MEET static inherited
Definition at line 163 of file Type.java.
SCALAR
final Type com.cliffc.aa.type.Type< T extends Type< T >.SCALAR static inherited
Definition at line 328 of file Type.java.
SCALAR_PRIMS
Type [] com.cliffc.aa.type.Type< T extends Type< T >.SCALAR_PRIMS static private inherited
Definition at line 349 of file Type.java.
STR0
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.STR0 = make(BitsAlias.STRBITS0,TypeStr.STR) static
Definition at line 98 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.node.NewStrNode.AddStrStr.AddStrStr(), com.cliffc.aa.type.TestType.testBits(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.type.TestType.testOOPsNulls(), and com.cliffc.aa.node.NewStrNode.AddStrStr.value().
STRPTR
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.STRPTR = make(BitsAlias.STRBITS ,TypeStr.STR) static
Definition at line 97 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.HM.HM9.Str.apply(), com.cliffc.aa.HM.HM.Str.apply(), com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM1.HM(), com.cliffc.aa.HM.HM6.hm(), com.cliffc.aa.HM.HM7.hm(), com.cliffc.aa.HM.HM5.hm(), com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM3.hm(), com.cliffc.aa.HM.HM2.hm(), com.cliffc.aa.type.TypeStr.init1(), com.cliffc.aa.HM.HM9.PrimSyn.reset(), com.cliffc.aa.HM.HM.PrimSyn.reset(), com.cliffc.aa.HM.TestHM.test14(), com.cliffc.aa.HM.TestHM9.test14(), com.cliffc.aa.HM.TestHM.test20(), com.cliffc.aa.HM.TestHM9.test20(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.HM.TestHM.test36(), com.cliffc.aa.HM.TestHM.test41(), com.cliffc.aa.HM.TestHM9.test41(), com.cliffc.aa.HM.TestHM.test45(), com.cliffc.aa.HM.TestHM9.test45(), com.cliffc.aa.type.TestType.testBits(), com.cliffc.aa.type.TestType.testLoad(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.type.TestType.testOOPsNulls(), and com.cliffc.aa.TestParse.testParse08().
STRS
final String [] com.cliffc.aa.type.Type< T extends Type< T >.STRS static private inherited
Definition at line 262 of file Type.java.
STRUCT
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.STRUCT = make(BitsAlias.RECORD_BITS ,TypeStruct.ALLSTRUCT) static
Definition at line 101 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.node.IntrinsicNode.convertTypeName(), com.cliffc.aa.type.TestType.testBits(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), and com.cliffc.aa.type.TestType.testOOPsNulls().
STRUCT0
final TypeMemPtr com.cliffc.aa.type.TypeMemPtr.STRUCT0 = make(BitsAlias.RECORD_BITS0,TypeStruct.ALLSTRUCT) static
Definition at line 102 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.type.TestType.testBits0(), com.cliffc.aa.type.TestType.testOOPsNulls(), and com.cliffc.aa.TestParse.testParse07().
TALL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TALL static package inherited
Definition at line 239 of file Type.java.
TANY
final byte com.cliffc.aa.type.Type< T extends Type< T >.TANY static package inherited
Definition at line 240 of file Type.java.
TARY
final byte com.cliffc.aa.type.Type< T extends Type< T >.TARY static package inherited
Definition at line 269 of file Type.java.
TCTRL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TCTRL static package inherited
Definition at line 241 of file Type.java.
TFLD
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFLD static package inherited
Definition at line 271 of file Type.java.
TFLT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFLT static package inherited
Definition at line 264 of file Type.java.
TFUNPTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFUNPTR static package inherited
Definition at line 274 of file Type.java.
TFUNSIG
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFUNSIG static package inherited
Definition at line 275 of file Type.java.
TINT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TINT static package inherited
Definition at line 263 of file Type.java.
TLAST
final byte com.cliffc.aa.type.Type< T extends Type< T >.TLAST static package inherited
Definition at line 277 of file Type.java.
TLIVE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TLIVE static package inherited
Definition at line 276 of file Type.java.
TMEM
final byte com.cliffc.aa.type.Type< T extends Type< T >.TMEM static package inherited
Definition at line 272 of file Type.java.
TMEMPTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TMEMPTR static package inherited
Definition at line 273 of file Type.java.
TNIL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNIL static package inherited
Definition at line 259 of file Type.java.
TNREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNREAL static package inherited
Definition at line 257 of file Type.java.
TNSCALR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNSCALR static package inherited
Definition at line 253 of file Type.java.
TOBJ
final byte com.cliffc.aa.type.Type< T extends Type< T >.TOBJ static package inherited
Definition at line 267 of file Type.java.
TREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TREAL static package inherited
Definition at line 255 of file Type.java.
TRPC
final byte com.cliffc.aa.type.Type< T extends Type< T >.TRPC static package inherited
Definition at line 265 of file Type.java.
TSCALAR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSCALAR static package inherited
Definition at line 246 of file Type.java.
TSIMPLE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSIMPLE static package inherited
Definition at line 261 of file Type.java.
TSTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSTR static package inherited
Definition at line 270 of file Type.java.
TSTRUCT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSTRUCT static package inherited
Definition at line 268 of file Type.java.
TTUPLE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TTUPLE static package inherited
Definition at line 266 of file Type.java.
TXCTRL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXCTRL static package inherited
Definition at line 242 of file Type.java.
TXNIL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNIL static package inherited
Definition at line 260 of file Type.java.
TXNREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNREAL static package inherited
Definition at line 258 of file Type.java.
TXNSCALR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNSCALR static package inherited
Definition at line 254 of file Type.java.
TXREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXREAL static package inherited
Definition at line 256 of file Type.java.
TXSCALAR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXSCALAR static package inherited
Definition at line 247 of file Type.java.
TYPES
final Type [] com.cliffc.aa.type.TypeMemPtr.TYPES = new Type[]{OOP0,STR0,STRPTR,ABCPTR,STRUCT,EMTPTR,DISPLAY,DISPLAY_PTR} static package
Definition at line 106 of file TypeMemPtr.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.ALL_TYPES(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestType.testNameCycle(), and com.cliffc.aa.type.TestApprox.testTSMeet().
XCTRL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XCTRL static inherited
Definition at line 327 of file Type.java.
XNIL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNIL static inherited
Definition at line 333 of file Type.java.
XNREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNREAL static private inherited
Definition at line 337 of file Type.java.
XNSCALR
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNSCALR static inherited
Definition at line 331 of file Type.java.
XREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XREAL static private inherited
Definition at line 335 of file Type.java.
XSCALAR
final Type com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR static inherited
Definition at line 329 of file Type.java.
The documentation for this class was generated from the following file:
TypeMemPtr.java