aa: com.cliffc.aa.REPL Class Reference
com.cliffc.aa.REPL Class Reference abstract
an implementation of language AA
Static Public Member Functions
static String go ()
Static Public Attributes
static final String prompt ="> "
Static Package Functions
static String go_one (String prog, String line)
static void init ()
Detailed Description
an implementation of language AA
Definition at line 11 of file REPL.java.
Member Function Documentation
go()
static String com.cliffc.aa.REPL.go () static
Definition at line 13 of file REPL.java.
{
     String prog = "";
     init();
     Scanner stdin = new Scanner(System.in);
     while( stdin.hasNextLine() )
       prog = go_one(prog,stdin.nextLine());
     return prog;
   }
References com.cliffc.aa.REPL.go_one(), and com.cliffc.aa.REPL.init().
Referenced by com.cliffc.aa.AA.main().
go_one()
static String com.cliffc.aa.REPL.go_one (String prog, String line) static package
Definition at line 27 of file REPL.java.
{
     String prog2 = prog+line+";"+System.lineSeparator();
     TypeEnv te = Exec.go(Env.file_scope(Env.top_scope()),"stdin",prog2);
     if( te._errs == null ) {
       Type t = te._t;
       if( t instanceof TypeMemPtr )
         t = te._tmem.ld((TypeMemPtr)t); // Peek thru pointer
       SB sb = t.str(new SB(),new VBitSet(),te._tmem,false); // Print what we see, with memory
       System.out.println( sb.toString() );
       prog = prog2;
     } else
       System.out.print( te._errs.get(0) );
     System.out.print(prompt);
     System.out.flush();
     return prog;
   }
References com.cliffc.aa.TypeEnv._errs, com.cliffc.aa.TypeEnv._t, com.cliffc.aa.TypeEnv._tmem, com.cliffc.aa.Env.file_scope(), com.cliffc.aa.Exec.go(), com.cliffc.aa.type.TypeMem.ld(), com.cliffc.aa.REPL.prompt, com.cliffc.aa.type.TypeMemPtr.str(), com.cliffc.aa.Env.top_scope(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.REPL.go(), com.cliffc.aa.TestREPL.test(), and com.cliffc.aa.TestREPL.testerr().
init()
static void com.cliffc.aa.REPL.init () static package
Definition at line 22 of file REPL.java.
                      {
     System.out.print(prompt);
     System.out.flush();
   }
References com.cliffc.aa.REPL.prompt.
Referenced by com.cliffc.aa.REPL.go(), and com.cliffc.aa.TestREPL.open_repl().
Member Data Documentation
prompt
final String com.cliffc.aa.REPL.prompt ="> " static
Definition at line 12 of file REPL.java.
Referenced by com.cliffc.aa.REPL.go_one(), com.cliffc.aa.REPL.init(), com.cliffc.aa.TestREPL.open_repl(), com.cliffc.aa.TestREPL.test(), and com.cliffc.aa.TestREPL.testerr().
The documentation for this class was generated from the following file:
REPL.java