aa: com.cliffc.aa.HM.HM8.T2 Class Reference
com.cliffc.aa.HM.HM8.T2 Class Reference
Public Member Functions
String p ()
String toString ()
Package Functions
boolean _cycle_equals (T2 t)
VBitSet _get_dups (VBitSet visit, VBitSet dups)
boolean _nongen_in (VStack nongen)
boolean _occurs_in (Syntax syn)
boolean _occurs_in_type (T2 x)
void add_deps_work (Worklist work)
T2 args (int i)
T2 copy ()
boolean cycle_equals (T2 t)
T2 debug_find ()
T2 find ()
boolean fresh_unify (T2 that, VStack nongen, Worklist work)
VBitSet get_dups (VBitSet dups)
T2 getrec (int alias)
boolean is_base ()
boolean is_err ()
boolean is_fun ()
boolean is_leaf ()
boolean is_mem ()
boolean is_nil ()
boolean is_struct ()
boolean isa (String name)
boolean no_uf ()
boolean nongen_in (VStack syn)
boolean occurs_in (Syntax syn)
boolean occurs_in_type (T2 x)
boolean or0 (T2 that, Worklist work)
String p (VBitSet dups)
T2 push_update (Ary< Syntax > as)
void push_update (Syntax a)
SB str (SB sb, VBitSet visit, VBitSet dups)
boolean unify (T2 that, Worklist work)
boolean unify_rec (int alias, T2 str, Worklist work)
boolean union (T2 that, Worklist work)
Static Package Functions
static T2 make_base (Type con)
static T2 make_err (String s)
static T2 make_fun (T2... args)
static T2 make_leaf ()
static T2 make_mem ()
static T2 make_nil ()
static T2 make_struct (String[] ids, BitsAlias aliases, T2[] flds)
static T2 prim (String name, T2... args)
static void reset ()
Package Attributes
BitsAlias _aliases
T2[] _args
Type _con
Ary< Syntax > _deps
String[] _ids
String _name
final int _uid
Static Package Attributes
static final VBitSet UPDATE_VISIT = new VBitSet()
Private Member Functions
T2 (@NotNull String name, Type con, String[] ids, BitsAlias aliases, T2 @NotNull ... args)
boolean _cycle_equals_struct (T2 t)
T2 _fresh (VStack nongen)
boolean _fresh_unify (T2 that, VStack nongen, Worklist work)
boolean _fresh_unify_struct (T2 that, VStack nongen, Worklist work)
SB _p (SB sb, VBitSet visit, VBitSet dups)
boolean _unify (T2 that, Worklist work)
void add_deps_work_impl (Worklist work)
void add_fld (String id, T2 fld, Worklist work)
long dbl_uid (T2 t)
boolean fresh_base (T2 that, Worklist work)
void push_update_impl (Syntax a)
boolean unify_base (T2 that, Worklist work)
boolean union_err (T2 that, Worklist work, String msg)
boolean vput (T2 that, boolean progress)
Static Private Member Functions
static SB str (SB sb, VBitSet visit, T2 t, VBitSet dups)
Static Private Attributes
static final HashMap< T2, T2 > CDUPS = new HashMap<>()
static int CNT =0
static final HashMap< Long, T2 > DUPS = new HashMap<>()
static final VBitSet ODUPS = new VBitSet()
static final HashMap< T2, T2 > VARS = new HashMap<>()
static int VCNT
static final HashMap< T2, Integer > VNAMES = new HashMap<>()
Detailed Description
Definition at line 721 of file HM8.java.
Constructor & Destructor Documentation
T2()
com.cliffc.aa.HM.HM8.T2.T2 (@NotNull String name, Type con, String[] ids, BitsAlias aliases, T2 @NotNull ... args) private
Definition at line 756 of file HM8.java.
{
       _uid = CNT++;
       _name= name;
       _con = con;
       _ids = ids;
       _aliases = aliases;
       _args= args;
       _deps = null;
     }
References com.cliffc.aa.HM.HM8.T2._aliases, com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._con, com.cliffc.aa.HM.HM8.T2._deps, com.cliffc.aa.HM.HM8.T2._ids, com.cliffc.aa.HM.HM8.T2._name, com.cliffc.aa.HM.HM8.T2._uid, com.cliffc.aa.HM.HM8.T2.args(), and com.cliffc.aa.HM.HM8.T2.CNT.
Referenced by com.cliffc.aa.HM.HM8.T2.copy(), com.cliffc.aa.HM.HM8.T2.make_base(), com.cliffc.aa.HM.HM8.T2.make_err(), com.cliffc.aa.HM.HM8.T2.make_fun(), com.cliffc.aa.HM.HM8.T2.make_leaf(), com.cliffc.aa.HM.HM8.T2.make_mem(), com.cliffc.aa.HM.HM8.T2.make_nil(), com.cliffc.aa.HM.HM8.T2.make_struct(), and com.cliffc.aa.HM.HM8.T2.prim().
Member Function Documentation
_cycle_equals()
boolean com.cliffc.aa.HM.HM8.T2._cycle_equals (T2 t) package
Definition at line 1111 of file HM8.java.
{
       assert no_uf() && t.no_uf();
       if( this==t ) return true;
       if( is_base() && t.is_base() )
         return _con==t._con;    // Base-cases have to be completely identical
       if( !Util.eq(_name,t._name) ||       // Wrong type-var names
           _args.length != t._args.length ) // Mismatched sizes
         return false;
       if( _args==t._args ) return true;
       // Cycles stall the equal/unequal decision until we see a difference.
       T2 tc = CDUPS.get(this);
       if( tc!=null )
         return tc==t; // Cycle check; true if both cycling the same
       CDUPS.put(this,t);
       if( is_struct() )         // Struct equality honors field names without regard to order
         return _cycle_equals_struct(t);
       for( int i=0; i<_args.length; i++ )
         if( !args(i)._cycle_equals(t.args(i)) )
           return false;
       return true;
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._con, com.cliffc.aa.HM.HM8.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM8.T2._name, com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.HM.HM8.T2.CDUPS, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM8.T2.is_base(), com.cliffc.aa.HM.HM8.T2.is_struct(), and com.cliffc.aa.HM.HM8.T2.no_uf().
Referenced by com.cliffc.aa.HM.HM8.T2._cycle_equals_struct(), and com.cliffc.aa.HM.HM8.T2.cycle_equals().
_cycle_equals_struct()
boolean com.cliffc.aa.HM.HM8.T2._cycle_equals_struct (T2 t) private
Definition at line 1133 of file HM8.java.
{
       assert is_struct() && t.is_struct();
       if( _con != t._con ) return false;
       for( int i=0; i<_args.length; i++ ) {
         int idx = Util.find(t._ids,_ids[i]);
         if( idx==-1 || !args(i)._cycle_equals(t.args(idx)) )
           return false;
       }
       return true;
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._con, com.cliffc.aa.HM.HM8.T2._cycle_equals(), com.cliffc.aa.HM.HM8.T2._ids, com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.util.Util.find(), and com.cliffc.aa.HM.HM8.T2.is_struct().
Referenced by com.cliffc.aa.HM.HM8.T2._cycle_equals().
_fresh()
T2 com.cliffc.aa.HM.HM8.T2._fresh (VStack nongen) private
Definition at line 1035 of file HM8.java.
{
       assert no_uf();
       T2 rez = VARS.get(this);
       if( rez!=null ) return rez; // Been there, done that
       if( is_leaf() ) {
         // If occurs_in lexical scope, keep same variable, else make a new leaf
         T2 t = nongen_in(nongen) ? this : T2.make_leaf();
         VARS.put(this,t);
         return t;
       } else {                  // Structure is deep-replicated
         T2 t = copy();
         VARS.put(this,t);       // Stop cyclic structure looping
         for( int i=0; i<_args.length; i++ )
           t._args[i] = args(i)._fresh(nongen);
         return t;
       }
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._fresh(), com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.HM.HM8.T2.copy(), com.cliffc.aa.HM.HM8.T2.is_leaf(), com.cliffc.aa.HM.HM8.T2.make_leaf(), com.cliffc.aa.HM.HM8.T2.no_uf(), com.cliffc.aa.HM.HM8.T2.nongen_in(), and com.cliffc.aa.HM.HM8.T2.VARS.
Referenced by com.cliffc.aa.HM.HM8.T2._fresh(), com.cliffc.aa.HM.HM8.T2._fresh_unify(), and com.cliffc.aa.HM.HM8.T2._fresh_unify_struct().
_fresh_unify()
boolean com.cliffc.aa.HM.HM8.T2._fresh_unify (T2 that, VStack nongen, Worklist work) private
Definition at line 968 of file HM8.java.
{
       assert no_uf() && that.no_uf();
       T2 prior = VARS.get(this);
       if( prior!=null )         // Been there, done that
         return prior.find()._unify(that,work);  // Also 'prior' needs unification with 'that'
       if( cycle_equals(that) ) return vput(that,false);
       if( that.is_err() ) return vput(that,false); // That is an error, ignore 'this' and no progress
       if( this.is_err() ) return vput(that,_unify(that,work));
       // Attempting to pre-compute occurs_in, by computing 'is_fresh' in the
       // Ident.hm() call does NOT work.  The 'is_fresh' is for the top-layer
       // only, not the internal layers.  As soon as we structural recurse down
       // a layer, 'is_fresh' does not correlate with an occurs_in check.
       if( nongen_in(nongen) ) return vput(that,_unify(that,work)); // Famous 'occurs-check', switch to normal unify
       if( this.is_leaf() ) return vput(that,false); // Lazy map LHS tvar to RHS
       if( that.is_leaf() )             // RHS is a tvar; union with a deep copy of LHS
         return work==null || vput(that,that.union(_fresh(nongen),work));
       // Bases MEET cons in RHS
       if( is_base() && that.is_base() ) return vput(that,fresh_base(that,work));
       // Unify struct with nil
       if( is_nil() && that.is_struct() ) return vput(that,or0(that,work));
       if( that.is_nil() && is_struct() )
         return work==null || vput(that,that.or0(_fresh(nongen),work));
       if( !Util.eq(_name,that._name) ||
           (!is_struct() && _args.length != that._args.length) )
         return work == null || vput(that,that._unify(make_err("Cannot unify "+this+" and "+that),work));
       // Structural recursion unification, lazy on LHS
       vput(that,false); // Early set, to stop cycles
       boolean progress = false;
       if( is_struct() )
         progress = _fresh_unify_struct(that,nongen,work);
       else {
         for( int i=0; i<_args.length; i++ ) {
           progress |= args(i)._fresh_unify(that.args(i),nongen,work);
           if( progress && work==null ) return true;
         }
       }
       return progress;
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._fresh(), com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM8.T2._name, com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.HM.HM8.T2.cycle_equals(), com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM8.T2.find(), com.cliffc.aa.HM.HM8.T2.fresh_base(), com.cliffc.aa.HM.HM8.T2.is_base(), com.cliffc.aa.HM.HM8.T2.is_err(), com.cliffc.aa.HM.HM8.T2.is_leaf(), com.cliffc.aa.HM.HM8.T2.is_nil(), com.cliffc.aa.HM.HM8.T2.is_struct(), com.cliffc.aa.HM.HM8.T2.make_err(), com.cliffc.aa.HM.HM8.T2.no_uf(), com.cliffc.aa.HM.HM8.T2.nongen_in(), com.cliffc.aa.HM.HM8.T2.or0(), com.cliffc.aa.HM.HM8.T2.union(), com.cliffc.aa.HM.HM8.T2.VARS, and com.cliffc.aa.HM.HM8.T2.vput().
Referenced by com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._fresh_unify_struct(), and com.cliffc.aa.HM.HM8.T2.fresh_unify().
_fresh_unify_struct()
boolean com.cliffc.aa.HM.HM8.T2._fresh_unify_struct (T2 that, VStack nongen, Worklist work) private
Definition at line 1012 of file HM8.java.
{
       assert is_struct() && that.is_struct();
       if( _con!=null && that._con==null ) {
         if( work==null ) return true; // Will progress
         that._con = Type.NIL;         // Allow nil
       }
       boolean progress = false;
       for( int i=0; i<_args.length; i++ ) {
         int idx = Util.find(that._ids,_ids[i]);
         if( idx == -1 ) {       // Missing field on RHS
           if( work==null ) return true; // Will definitely make progress
           progress = true;
           that.add_fld(_ids[i],args(i)._fresh(nongen), work);
         } else
           progress |= args(i)._fresh_unify(that.args(idx),nongen,work);
         if( progress && work==null ) return true;
       }
       return progress;
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._con, com.cliffc.aa.HM.HM8.T2._fresh(), com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._ids, com.cliffc.aa.HM.HM8.T2.add_fld(), com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM8.T2.is_struct(), and com.cliffc.aa.type.Type< T extends Type< T >.NIL.
Referenced by com.cliffc.aa.HM.HM8.T2._fresh_unify().
_get_dups()
VBitSet com.cliffc.aa.HM.HM8.T2._get_dups (VBitSet visit, VBitSet dups) package
Definition at line 1197 of file HM8.java.
{
       if( visit.tset(_uid) && no_uf() ) dups.set(_uid);
       else
         for( T2 t : _args )
           if( t!=null )
             t._get_dups(visit,dups);
       return dups;
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._uid, com.cliffc.aa.HM.HM8.T2.no_uf(), and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.HM.HM8.T2.get_dups().
_nongen_in()
boolean com.cliffc.aa.HM.HM8.T2._nongen_in (VStack nongen) package
Definition at line 1095 of file HM8.java.
{
       for( T2 t2 : nongen )
         if( _occurs_in_type(t2.find()) )
           return true;
       return false;
     }
References com.cliffc.aa.HM.HM8.T2._occurs_in_type().
Referenced by com.cliffc.aa.HM.HM8.T2.nongen_in().
_occurs_in()
boolean com.cliffc.aa.HM.HM8.T2._occurs_in (Syntax syn) package
Definition at line 1070 of file HM8.java.
{
       for( ; syn!=null; syn=syn._par )
         if( _occurs_in_type(syn.find()) )
           return true;
       return false;
     }
References com.cliffc.aa.HM.HM8.T2._occurs_in_type(), com.cliffc.aa.HM.HM8.Syntax._par, and com.cliffc.aa.HM.HM8.Syntax.find().
Referenced by com.cliffc.aa.HM.HM8.T2.occurs_in().
_occurs_in_type()
boolean com.cliffc.aa.HM.HM8.T2._occurs_in_type (T2 x) package
Definition at line 1077 of file HM8.java.
{
       assert no_uf() && x.no_uf();
       if( x==this ) return true;
       if( ODUPS.tset(x._uid) ) return false; // Been there, done that
       if( !x.is_leaf() )
         for( int i=0; i<x._args.length; i++ )
           if( _occurs_in_type(x.args(i)) )
             return true;
       return false;
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._uid, com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.HM.HM8.T2.is_leaf(), com.cliffc.aa.HM.HM8.T2.no_uf(), com.cliffc.aa.HM.HM8.T2.ODUPS, and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.HM.HM8.T2._nongen_in(), com.cliffc.aa.HM.HM8.T2._occurs_in(), and com.cliffc.aa.HM.HM8.T2.occurs_in_type().
_p()
SB com.cliffc.aa.HM.HM8.T2._p (SB sb, VBitSet visit, VBitSet dups) private
Definition at line 1259 of file HM8.java.
{
       assert no_uf();
       if( is_err () ) return sb.p( _con.getstr() );
       if( is_base() ) return sb.p(_con instanceof TypeMemPtr ? "str" : _con.toString() );
       if( is_leaf() || dups.get(_uid) ) { // Leafs or Duplicates?  Take some effort to pretty-print cycles
         Integer ii = VNAMES.get(this);
         if( ii==null )  VNAMES.put(this,ii=VCNT++);
         // 2nd and later visits use the short form
         boolean later = !is_leaf() && visit.tset(_uid);
         if( later ) sb.p('$');
         char c = (char)('A'+ii);
         if( c<'V' ) sb.p(c); else sb.p("V"+ii);
         if( is_leaf() || later ) return sb;
         // First visit prints the V._uid and the type
         sb.p(':');
       }
       // Special printing for functions: { arg -> body }
       if( is_fun() ) {
         sb.p("{ ");
         for( int i=0; i<_args.length-1; i++ )
           args(i)._p(sb,visit,dups).p(" ");
         return args(_args.length-1)._p(sb.p("-> "),visit,dups).p(" }");
       }
       // Special printing for structures: @{ fld0 = body, fld1 = body, ... }
       if( is_struct() ) {
         _aliases.str(sb.p('*')).p("@{");
         for( int i=0; i<_ids.length; i++ )
           args(i)._p(sb.p(' ').p(_ids[i]).p(" = "),visit,dups).p(',');
         sb.unchar().p("}");
         if( _con==Type.NIL ) sb.p('?');
         return sb;
       }
       // Special printing for memory
       if( is_mem() ) {
         sb.p("[  ");
         for( int i=0; i<_args.length; i++ )
           if( _args[i] != null )
             args(i)._p(sb.p(i).p(':'),visit,dups).p(", ");
         return sb.unchar(2).p("]");
       }
       // Generic structural T2: (fun arg0 arg1...)
       sb.p("(").p(_name).p(" ");
       for( int i=0; i<_args.length; i++ ) args(i)._p(sb,visit,dups).p(" ");
       return sb.unchar().p(")");
     }
References com.cliffc.aa.HM.HM8.T2._aliases, com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._con, com.cliffc.aa.HM.HM8.T2._ids, com.cliffc.aa.HM.HM8.T2._name, com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.T2._uid, com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.type.Type< T extends Type< T >.getstr(), com.cliffc.aa.HM.HM8.T2.is_base(), com.cliffc.aa.HM.HM8.T2.is_err(), com.cliffc.aa.HM.HM8.T2.is_fun(), com.cliffc.aa.HM.HM8.T2.is_leaf(), com.cliffc.aa.HM.HM8.T2.is_mem(), com.cliffc.aa.HM.HM8.T2.is_struct(), com.cliffc.aa.type.Type< T extends Type< T >.NIL, com.cliffc.aa.HM.HM8.T2.no_uf(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.Bits< B extends Bits< B >.str(), com.cliffc.aa.type.Type< T extends Type< T >.toString(), com.cliffc.aa.util.VBitSet.tset(), com.cliffc.aa.util.SB.unchar(), com.cliffc.aa.HM.HM8.T2.VCNT, and com.cliffc.aa.HM.HM8.T2.VNAMES.
Referenced by com.cliffc.aa.HM.HM8.T2._p(), and com.cliffc.aa.HM.HM8.T2.p().
_unify()
boolean com.cliffc.aa.HM.HM8.T2._unify (T2 that, Worklist work) private
Definition at line 852 of file HM8.java.
{
       assert no_uf() && that.no_uf();
       if( this==that ) return false;
       // two errs union in either order, so keep lower uid (actually should merge error strings)
       if( is_err() && that.is_err() && _uid<that._uid ) return that.union(this,work);
       if(      is_err() ) return that.union(this,work);
       if( that.is_err() ) return      union(that,work);
       // two leafs union in either order, so keep lower uid
       if( is_leaf() && that.is_leaf() && _uid<that._uid ) return that.union(this,work);
       if(      is_leaf() ) return      union(that,work);
       if( that.is_leaf() ) return that.union(this,work);
       if( is_base() && that.is_base() ) return unify_base(that,work);
       // Unify struct with nil
       if( is_nil() && that.is_struct() ) return or0(that,work);
       if( that.is_nil() && is_struct() ) return that.or0(this,work);
       // Cycle check
       long luid = dbl_uid(that);    // long-unique-id formed from this and that
       T2 rez = DUPS.get(luid);
       assert rez==null || rez==that;
       if( rez!=null ) return false; // Been there, done that
       DUPS.put(luid,that);          // Close cycles
       if( work==null ) return true; // Here we definitely make progress; bail out early if just testing
       if( !Util.eq(_name,that._name) )
         return union_err(that,work,"Cannot unify "+this+" and "+that);
       assert _args!=that._args; // Not expecting to share _args and not 'this'
       if( !is_struct() && !is_mem() && _args.length != that._args.length )
         return union_err(that,work,"Cannot unify "+this+" and "+that);
       // Structural recursion unification.
       // Structs unify only on matching fields, and add missing fields.
       if( is_struct() ) {
         // Unification for structs is more complicated; args are aligned via
         // field names and not by position.
         for( int i=0; i<_ids.length; i++ ) { // For all fields in LHS
           int idx = Util.find(that._ids,_ids[i]);
           if( idx==-1 ) that.add_fld(_ids[i],args(i), work); // Extend 'that' with matching field from 'this'
           else args(i)._unify(that.args(idx),work);    // Unify matching field
           that = that.find();                          // Recursively, might have already rolled this up
         }
         if( _con!=null && that._con==null ) that._con=Type.NIL;
         that._aliases = that._aliases.meet(this._aliases);
         if( this==that ) return true; // Might have unioned this-into-that recursively, exit now with progress
         // Memory add missing fields
       } else if( is_mem() ) {
         for( int i=0; i<_args.length; i++ ) // For all fields in LHS
           if( _args[i]!=null )
             that.unify_rec(i,args(i),work);
         // Normal structural unification
       } else {
         for( int i=0; i<_args.length; i++ ) // For all fields in LHS
           args(i)._unify(that.args(i),work);
       }
       if( find().is_err() && !that.find().is_err() ) return that.find().union(find(),work); // Preserve errors
       return find().union(that,work);
     }
References com.cliffc.aa.HM.HM8.T2._aliases, com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._con, com.cliffc.aa.HM.HM8.T2._ids, com.cliffc.aa.HM.HM8.T2._name, com.cliffc.aa.HM.HM8.T2._uid, com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.T2.add_fld(), com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.HM.HM8.T2.dbl_uid(), com.cliffc.aa.HM.HM8.T2.DUPS, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM8.T2.find(), com.cliffc.aa.HM.HM8.T2.is_base(), com.cliffc.aa.HM.HM8.T2.is_err(), com.cliffc.aa.HM.HM8.T2.is_leaf(), com.cliffc.aa.HM.HM8.T2.is_mem(), com.cliffc.aa.HM.HM8.T2.is_nil(), com.cliffc.aa.HM.HM8.T2.is_struct(), com.cliffc.aa.type.Bits< B extends Bits< B >.meet(), com.cliffc.aa.type.Type< T extends Type< T >.NIL, com.cliffc.aa.HM.HM8.T2.no_uf(), com.cliffc.aa.HM.HM8.T2.or0(), com.cliffc.aa.HM.HM8.T2.unify_base(), com.cliffc.aa.HM.HM8.T2.unify_rec(), com.cliffc.aa.HM.HM8.T2.union(), and com.cliffc.aa.HM.HM8.T2.union_err().
Referenced by com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._unify(), and com.cliffc.aa.HM.HM8.T2.unify().
add_deps_work()
void com.cliffc.aa.HM.HM8.T2.add_deps_work (Worklist work) package
Definition at line 1181 of file HM8.java.
 { assert UPDATE_VISIT.isEmpty(); add_deps_work_impl(work); UPDATE_VISIT.clear(); }
References com.cliffc.aa.HM.HM8.T2.add_deps_work_impl(), and com.cliffc.aa.HM.HM8.T2.UPDATE_VISIT.
Referenced by com.cliffc.aa.HM.HM8.Ident.add_work().
add_deps_work_impl()
void com.cliffc.aa.HM.HM8.T2.add_deps_work_impl (Worklist work) private
Definition at line 1182 of file HM8.java.
{
       if( is_leaf() || _args.length==0 ) {
         work.addAll(_deps);
       } else {
         if( UPDATE_VISIT.tset(_uid) ) return;
         for( int i=0; i<_args.length; i++ )
           args(i).add_deps_work_impl(work);
       }
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._deps, com.cliffc.aa.HM.HM8.T2._uid, com.cliffc.aa.HM.HM8.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM8.Worklist.addAll(), com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.HM.HM8.T2.is_leaf(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.HM.HM8.T2.UPDATE_VISIT.
Referenced by com.cliffc.aa.HM.HM8.T2.add_deps_work(), and com.cliffc.aa.HM.HM8.T2.add_deps_work_impl().
add_fld()
void com.cliffc.aa.HM.HM8.T2.add_fld (String id, T2 fld, Worklist work) private
Definition at line 916 of file HM8.java.
{
       assert is_struct();
       int len = _ids.length;
       _ids  = Arrays.copyOf( _ids,len+1);
       _args = Arrays.copyOf(_args,len+1);
       _ids [len] = id ;
       _args[len] = fld;
       work.addAll(_deps); //
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._deps, com.cliffc.aa.HM.HM8.T2._ids, com.cliffc.aa.HM.HM8.Worklist.addAll(), com.cliffc.aa.HM.HM8.id(), and com.cliffc.aa.HM.HM8.T2.is_struct().
Referenced by com.cliffc.aa.HM.HM8.T2._fresh_unify_struct(), and com.cliffc.aa.HM.HM8.T2._unify().
args()
T2 com.cliffc.aa.HM.HM8.T2.args (int i) package
Definition at line 796 of file HM8.java.
                    {
       T2 u = _args[i];
       T2 uu = u.find();
       return u==uu ? uu : (_args[i]=uu);
     }
References com.cliffc.aa.HM.HM8.T2._args, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.T2._cycle_equals(), com.cliffc.aa.HM.HM8.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM8.T2._fresh(), com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM8.T2._occurs_in_type(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM8.T2.getrec(), com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.HM.HM8.T2.make_fun(), com.cliffc.aa.HM.HM8.T2.prim(), com.cliffc.aa.HM.HM8.T2.push_update_impl(), com.cliffc.aa.HM.HM8.T2.T2(), and com.cliffc.aa.HM.HM8.T2.unify_rec().
copy()
T2 com.cliffc.aa.HM.HM8.T2.copy () package
Definition at line 754 of file HM8.java.
 { return new T2(_name,_con,_ids,_aliases,new T2[_args.length]); }
References com.cliffc.aa.HM.HM8.T2._aliases, com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._con, com.cliffc.aa.HM.HM8.T2._ids, com.cliffc.aa.HM.HM8.T2._name, and com.cliffc.aa.HM.HM8.T2.T2().
Referenced by com.cliffc.aa.HM.HM8.T2._fresh().
cycle_equals()
boolean com.cliffc.aa.HM.HM8.T2.cycle_equals (T2 t) package
Definition at line 1105 of file HM8.java.
{
       assert CDUPS.isEmpty();
       boolean rez = _cycle_equals(t);
       CDUPS.clear();
       return rez;
     }
References com.cliffc.aa.HM.HM8.T2._cycle_equals(), and com.cliffc.aa.HM.HM8.T2.CDUPS.
Referenced by com.cliffc.aa.HM.HM8.T2._fresh_unify().
dbl_uid()
long com.cliffc.aa.HM.HM8.T2.dbl_uid (T2 t) private
Definition at line 926 of file HM8.java.
 { return ((long)_uid<<32)|t._uid; }
References com.cliffc.aa.HM.HM8.T2._uid.
Referenced by com.cliffc.aa.HM.HM8.T2._unify().
debug_find()
T2 com.cliffc.aa.HM.HM8.T2.debug_find () package
Definition at line 777 of file HM8.java.
                     {// Find, without the roll-up
       if( !is_leaf() ) return this; // Shortcut
       T2 u = _args[0];
       if( u==null ) return this; // Shortcut
       if( u.no_uf() ) return u;  // Shortcut
       // U-F fixup
       while( u.is_leaf() && u._args[0]!=null ) u = u._args[0];
       return u;
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2.is_leaf(), and com.cliffc.aa.HM.HM8.T2.no_uf().
Referenced by com.cliffc.aa.HM.HM8.Syntax.debug_find(), and com.cliffc.aa.HM.HM8.T2.find().
find()
T2 com.cliffc.aa.HM.HM8.T2.find () package
Definition at line 788 of file HM8.java.
               {
       T2 u = debug_find();
       if( u==this || u==_args[0] ) return u;
       T2 v = this, v2;
       while( v.is_leaf() && (v2=v._args[0])!=u ) { v._args[0]=u; v = v2; }
       return u;
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2.debug_find(), and com.cliffc.aa.HM.HM8.T2.is_leaf().
Referenced by com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.Ident.add_work(), com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.HM.HM8.Syntax.find(), com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM8.Ident.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.HM.HM8.T2.p(), com.cliffc.aa.HM.HM8.Syntax.post(), com.cliffc.aa.HM.HM8.Syntax.pre(), com.cliffc.aa.HM.HM8.Lambda.targ(), and com.cliffc.aa.HM.HM8.Let.targ().
fresh_base()
boolean com.cliffc.aa.HM.HM8.T2.fresh_base (T2 that, Worklist work) private
Definition at line 937 of file HM8.java.
{
       Type con = _con.meet(that._con);
       if( con==that._con ) return false; // No progress
       if( work==null ) return true;
       that._con = con;          // Yes progress, but no update if null work
       return true;
     }
References com.cliffc.aa.HM.HM8.T2._con, and com.cliffc.aa.type.Type< T extends Type< T >.meet().
Referenced by com.cliffc.aa.HM.HM8.T2._fresh_unify().
fresh_unify()
boolean com.cliffc.aa.HM.HM8.T2.fresh_unify (T2 that, VStack nongen, Worklist work) package
Definition at line 957 of file HM8.java.
{
       assert VARS.isEmpty() && DUPS.isEmpty();
       int old = CNT;
       boolean progress = _fresh_unify(that,nongen,work);
       VARS.clear();  DUPS.clear();
       if( work==null && old!=CNT && DEBUG_LEAKS )
         throw unimpl("busted, made T2s but just testing");
       return progress;
     }
References com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2.CNT, com.cliffc.aa.HM.HM8.DEBUG_LEAKS, com.cliffc.aa.HM.HM8.T2.DUPS, and com.cliffc.aa.HM.HM8.T2.VARS.
Referenced by com.cliffc.aa.HM.HM8.Ident.hm().
get_dups()
VBitSet com.cliffc.aa.HM.HM8.T2.get_dups (VBitSet dups) package
Definition at line 1196 of file HM8.java.
 { return _get_dups(new VBitSet(),dups); }
References com.cliffc.aa.HM.HM8.T2._get_dups().
Referenced by com.cliffc.aa.HM.HM8.T2.p(), com.cliffc.aa.HM.HM8.Syntax.p0(), and com.cliffc.aa.HM.HM8.T2.toString().
getrec()
T2 com.cliffc.aa.HM.HM8.T2.getrec (int alias) package
Definition at line 1145 of file HM8.java.
{
       assert is_mem();
       if( alias >= _args.length ) return null;
       T2 str = args(alias);
       assert str==null || str.is_struct();
       return str;
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.HM.HM8.T2.is_mem(), and com.cliffc.aa.HM.HM8.T2.str().
is_base()
boolean com.cliffc.aa.HM.HM8.T2.is_base () package
Definition at line 770 of file HM8.java.
 { return isa("Base") && _con!=null; }
References com.cliffc.aa.HM.HM8.T2._con, and com.cliffc.aa.HM.HM8.T2.isa().
Referenced by com.cliffc.aa.HM.HM8.T2._cycle_equals(), com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.T2.occurs_in(), and com.cliffc.aa.HM.HM8.T2.str().
is_err()
boolean com.cliffc.aa.HM.HM8.T2.is_err () package
Definition at line 775 of file HM8.java.
 { return isa("Err"); }
References com.cliffc.aa.HM.HM8.T2.isa().
Referenced by com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Field.hm(), and com.cliffc.aa.HM.HM8.T2.str().
is_fun()
boolean com.cliffc.aa.HM.HM8.T2.is_fun () package
Definition at line 772 of file HM8.java.
 { return isa("->"); }
References com.cliffc.aa.HM.HM8.T2.isa().
Referenced by com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), and com.cliffc.aa.HM.HM8.T2.str().
is_leaf()
boolean com.cliffc.aa.HM.HM8.T2.is_leaf () package
Definition at line 767 of file HM8.java.
 { return _name.charAt(0)=='V' || (isa("Base") && _con==null); }
References com.cliffc.aa.HM.HM8.T2._con, com.cliffc.aa.HM.HM8.T2._name, and com.cliffc.aa.HM.HM8.T2.isa().
Referenced by com.cliffc.aa.HM.HM8.T2._fresh(), com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._occurs_in_type(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM8.T2.debug_find(), com.cliffc.aa.HM.HM8.T2.find(), com.cliffc.aa.HM.HM8.T2.no_uf(), and com.cliffc.aa.HM.HM8.T2.str().
is_mem()
boolean com.cliffc.aa.HM.HM8.T2.is_mem () package
Definition at line 774 of file HM8.java.
 { return isa("[]"); }
References com.cliffc.aa.HM.HM8.T2.isa().
Referenced by com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.T2.getrec(), com.cliffc.aa.HM.HM8.T2.str(), and com.cliffc.aa.HM.HM8.T2.unify_rec().
is_nil()
boolean com.cliffc.aa.HM.HM8.T2.is_nil () package
Definition at line 771 of file HM8.java.
 { return isa("Nil"); }
References com.cliffc.aa.HM.HM8.T2.isa().
Referenced by com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._unify(), and com.cliffc.aa.HM.HM8.T2.or0().
is_struct()
boolean com.cliffc.aa.HM.HM8.T2.is_struct () package
Definition at line 773 of file HM8.java.
 { return isa("@{}"); }
References com.cliffc.aa.HM.HM8.T2.isa().
Referenced by com.cliffc.aa.HM.HM8.T2._cycle_equals(), com.cliffc.aa.HM.HM8.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.T2.add_fld(), com.cliffc.aa.HM.HM8.T2.or0(), and com.cliffc.aa.HM.HM8.T2.str().
isa()
boolean com.cliffc.aa.HM.HM8.T2.isa (String name) package
Definition at line 769 of file HM8.java.
 { return Util.eq(_name,name); }
References com.cliffc.aa.HM.HM8.T2._name, and com.cliffc.aa.util.Util.eq().
Referenced by com.cliffc.aa.HM.HM8.T2.is_base(), com.cliffc.aa.HM.HM8.T2.is_err(), com.cliffc.aa.HM.HM8.T2.is_fun(), com.cliffc.aa.HM.HM8.T2.is_leaf(), com.cliffc.aa.HM.HM8.T2.is_mem(), com.cliffc.aa.HM.HM8.T2.is_nil(), and com.cliffc.aa.HM.HM8.T2.is_struct().
make_base()
static T2 com.cliffc.aa.HM.HM8.T2.make_base (Type con) static package
Definition at line 748 of file HM8.java.
 { return new T2("Base",con,null,null); }
References com.cliffc.aa.HM.HM8.T2.T2().
Referenced by com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), and com.cliffc.aa.HM.HM8.Con.prep_tree().
make_err()
static T2 com.cliffc.aa.HM.HM8.T2.make_err (String s) static package
Definition at line 752 of file HM8.java.
 { return new T2("Err",TypeStr.con(s.intern()),null,null); }
References com.cliffc.aa.type.TypeStr.con(), and com.cliffc.aa.HM.HM8.T2.T2().
Referenced by com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Field.hm(), and com.cliffc.aa.HM.HM8.T2.union_err().
make_fun()
static T2 com.cliffc.aa.HM.HM8.T2.make_fun (T2... args) static package
Definition at line 746 of file HM8.java.
 { return new T2("->",null,null,null,args); }
References com.cliffc.aa.HM.HM8.T2.args(), and com.cliffc.aa.HM.HM8.T2.T2().
Referenced by com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM8.Lambda.hm(), and com.cliffc.aa.HM.HM8.Apply.hm().
make_leaf()
static T2 com.cliffc.aa.HM.HM8.T2.make_leaf () static package
Definition at line 747 of file HM8.java.
 { return new T2("V"+CNT,null,null,null,new T2[1]); }
References com.cliffc.aa.HM.HM8.T2.CNT, and com.cliffc.aa.HM.HM8.T2.T2().
Referenced by com.cliffc.aa.HM.HM8.T2._fresh(), com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM8.Lambda.Lambda(), com.cliffc.aa.HM.HM8.Let.Let(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), com.cliffc.aa.HM.HM8.Lambda.prep_tree(), com.cliffc.aa.HM.HM8.Apply.prep_tree(), and com.cliffc.aa.HM.HM8.Field.prep_tree().
make_mem()
static T2 com.cliffc.aa.HM.HM8.T2.make_mem () static package
Definition at line 751 of file HM8.java.
 { return new T2("[]" ,null,null,null,new T2[1]); }
References com.cliffc.aa.HM.HM8.T2.T2().
Referenced by com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
make_nil()
static T2 com.cliffc.aa.HM.HM8.T2.make_nil () static package
Definition at line 749 of file HM8.java.
 { return new T2("Nil",null,null,null); }
References com.cliffc.aa.HM.HM8.T2.T2().
Referenced by com.cliffc.aa.HM.HM8.hm(), and com.cliffc.aa.HM.HM8.Con.prep_tree().
make_struct()
static T2 com.cliffc.aa.HM.HM8.T2.make_struct (String[] ids, BitsAlias aliases, T2[] flds) static package
Definition at line 750 of file HM8.java.
 { return new T2("@{}", null,ids,aliases,flds); }
References com.cliffc.aa.HM.HM8.T2.T2().
Referenced by com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Field.hm(), and com.cliffc.aa.HM.HM8.Struct.prep_tree().
no_uf()
boolean com.cliffc.aa.HM.HM8.T2.no_uf () package
Definition at line 768 of file HM8.java.
 { return !is_leaf() || _args[0]==null; }
References com.cliffc.aa.HM.HM8.T2._args, and com.cliffc.aa.HM.HM8.T2.is_leaf().
Referenced by com.cliffc.aa.HM.HM8.T2._cycle_equals(), com.cliffc.aa.HM.HM8.T2._fresh(), com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._get_dups(), com.cliffc.aa.HM.HM8.T2._occurs_in_type(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.T2.debug_find(), com.cliffc.aa.HM.HM8.T2.push_update_impl(), and com.cliffc.aa.HM.HM8.T2.union().
nongen_in()
boolean com.cliffc.aa.HM.HM8.T2.nongen_in (VStack syn) package
Definition at line 1088 of file HM8.java.
{
       if( syn==null ) return false;
       assert ODUPS.isEmpty();
       boolean found = _nongen_in(syn);
       ODUPS.clear();
       return found;
     }
References com.cliffc.aa.HM.HM8.T2._nongen_in(), and com.cliffc.aa.HM.HM8.T2.ODUPS.
Referenced by com.cliffc.aa.HM.HM8.T2._fresh(), and com.cliffc.aa.HM.HM8.T2._fresh_unify().
occurs_in()
boolean com.cliffc.aa.HM.HM8.T2.occurs_in (Syntax syn) package
Definition at line 1056 of file HM8.java.
{
       if( syn==null ) return false;
       if( is_base() ) return false;
       assert ODUPS.isEmpty();
       boolean found = _occurs_in(syn);
       ODUPS.clear();
       return found;
     }
References com.cliffc.aa.HM.HM8.T2._occurs_in(), com.cliffc.aa.HM.HM8.T2.is_base(), and com.cliffc.aa.HM.HM8.T2.ODUPS.
Referenced by com.cliffc.aa.HM.HM8.Ident.add_work().
occurs_in_type()
boolean com.cliffc.aa.HM.HM8.T2.occurs_in_type (T2 x) package
Definition at line 1064 of file HM8.java.
{
       assert ODUPS.isEmpty();
       boolean found = _occurs_in_type(x);
       ODUPS.clear();
       return found;
     }
References com.cliffc.aa.HM.HM8.T2._occurs_in_type(), and com.cliffc.aa.HM.HM8.T2.ODUPS.
or0()
boolean com.cliffc.aa.HM.HM8.T2.or0 (T2 that, Worklist work) package
Definition at line 825 of file HM8.java.
{
       assert is_nil() && that.is_struct();
       if( work==null ) return that._con==null; // Progress if moving from not-nil to nilable
       if( that._con == Type.NIL ) return false;// Already nilable
       _args = new T2[1];                       // Room for U-F
       that._con=Type.NIL;
       return union(that,work);
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._con, com.cliffc.aa.HM.HM8.T2.is_nil(), com.cliffc.aa.HM.HM8.T2.is_struct(), and com.cliffc.aa.type.Type< T extends Type< T >.NIL.
Referenced by com.cliffc.aa.HM.HM8.T2._fresh_unify(), and com.cliffc.aa.HM.HM8.T2._unify().
p() [1/2]
String com.cliffc.aa.HM.HM8.T2.p ()
Definition at line 1255 of file HM8.java.
 { return p(get_dups(new VBitSet())); }
References com.cliffc.aa.HM.HM8.T2.get_dups(), and com.cliffc.aa.HM.HM8.T2.p().
Referenced by com.cliffc.aa.HM.HM8.T2.p().
p() [2/2]
String com.cliffc.aa.HM.HM8.T2.p (VBitSet dups) package
Definition at line 1258 of file HM8.java.
 { VCNT=0; VNAMES.clear(); return find()._p(new SB(), new VBitSet(), dups).toString(); }
References com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.T2.find(), com.cliffc.aa.util.SB.toString(), com.cliffc.aa.HM.HM8.T2.VCNT, and com.cliffc.aa.HM.HM8.T2.VNAMES.
prim()
static T2 com.cliffc.aa.HM.HM8.T2.prim (String name, T2... args) static package
Definition at line 753 of file HM8.java.
 { return new T2(name,null,null,null,args); }
References com.cliffc.aa.HM.HM8.T2.args(), and com.cliffc.aa.HM.HM8.T2.T2().
Referenced by com.cliffc.aa.HM.HM8.hm().
push_update() [1/2]
T2 com.cliffc.aa.HM.HM8.T2.push_update (Ary< Syntax > as) package
Definition at line 1169 of file HM8.java.
 { if( as != null ) for( Syntax a : as ) push_update(a);  return this;   }
References com.cliffc.aa.HM.HM8.T2.push_update().
Referenced by com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.HM.HM8.Lambda.prep_lookup_deps(), com.cliffc.aa.HM.HM8.Let.prep_lookup_deps(), and com.cliffc.aa.HM.HM8.T2.push_update().
push_update() [2/2]
void com.cliffc.aa.HM.HM8.T2.push_update (Syntax a) package
Definition at line 1170 of file HM8.java.
 { assert UPDATE_VISIT.isEmpty(); push_update_impl(a); UPDATE_VISIT.clear(); }
References com.cliffc.aa.HM.HM8.T2.push_update_impl(), and com.cliffc.aa.HM.HM8.T2.UPDATE_VISIT.
push_update_impl()
void com.cliffc.aa.HM.HM8.T2.push_update_impl (Syntax a) private
Definition at line 1171 of file HM8.java.
{
       assert no_uf();
       if( UPDATE_VISIT.tset(_uid) ) return;
       if( _deps==null ) _deps = new Ary<>(Syntax.class);
       if( _deps.find(a)==-1 ) _deps.push(a);
       for( int i=0; i<_args.length; i++ )
         if( _args[i]!=null )
           args(i).push_update_impl(a);
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._deps, com.cliffc.aa.HM.HM8.T2._uid, com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.HM.HM8.T2.no_uf(), com.cliffc.aa.HM.HM8.T2.push_update_impl(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.HM.HM8.T2.UPDATE_VISIT.
Referenced by com.cliffc.aa.HM.HM8.T2.push_update(), and com.cliffc.aa.HM.HM8.T2.push_update_impl().
reset()
static void com.cliffc.aa.HM.HM8.T2.reset () static package
Definition at line 1309 of file HM8.java.
 { CNT=0; DUPS.clear(); VARS.clear(); ODUPS.clear(); CDUPS.clear(); UPDATE_VISIT.clear(); }
References com.cliffc.aa.HM.HM8.T2.CDUPS, com.cliffc.aa.HM.HM8.T2.CNT, com.cliffc.aa.HM.HM8.T2.DUPS, com.cliffc.aa.HM.HM8.T2.ODUPS, com.cliffc.aa.HM.HM8.T2.UPDATE_VISIT, and com.cliffc.aa.HM.HM8.T2.VARS.
Referenced by com.cliffc.aa.HM.HM8.reset().
str() [1/2]
static SB com.cliffc.aa.HM.HM8.T2.str (SB sb, VBitSet visit, T2 t, VBitSet dups) static private
Definition at line 1252 of file HM8.java.
 { return t==null ? sb.p("_") : t.str(sb,visit,dups); }
References com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM8.T2.str().
str() [2/2]
SB com.cliffc.aa.HM.HM8.T2.str (SB sb, VBitSet visit, VBitSet dups) package
Definition at line 1209 of file HM8.java.
{
       if( is_err() ) return sb.p(_con.getstr());
       if( is_leaf() || is_base() ) {
         if( is_base() ) sb.p(_con instanceof TypeMemPtr ? "str" : _con.toString()); else sb.p(_name);
         return _args.length==0 || _args[0]==null ? sb : _args[0].str(sb.p(">>"), visit, dups);
       }
       boolean dup = dups.get(_uid);
       if( dup ) sb.p("$V").p(_uid);
       if( visit.tset(_uid) && dup ) return sb;
       if( dup ) sb.p(':');
       // Special printing for functions
       if( is_fun() ) {
         sb.p("{ ");
         for( int i=0; i<_args.length-1; i++ )
           str(sb,visit,_args[i],dups).p(" ");
         return str(sb.p("-> "),visit,_args[_args.length-1],dups).p(" }");
       }
       // Special printing for structures
       if( is_struct() ) {
         _aliases.str(sb.p('*')).p("@{");
         for( int i=0; i<_ids.length; i++ )
           str(sb.p(' ').p(_ids[i]).p(" = "),visit,_args[i],dups).p(',');
         sb.unchar().p("}");
         if( _con==Type.NIL ) sb.p('?');
         return sb;
       }
       // Special printing for memory
       if( is_mem() ) {
         sb.p("[  ");
         for( int i=0; i<_args.length; i++ )
           if( _args[i] != null )
             _args[i].str(sb.p(i).p(':'),visit,dups).p(", ");
         return sb.unchar(2).p("]");
       }
       // Generic structural T2
       sb.p("(").p(_name).p(" ");
       for( T2 t : _args ) str(sb,visit,t,dups).p(" ");
       return sb.unchar().p(")");
     }
References com.cliffc.aa.HM.HM8.T2._aliases, com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._con, com.cliffc.aa.HM.HM8.T2._ids, com.cliffc.aa.HM.HM8.T2._name, com.cliffc.aa.HM.HM8.T2._uid, com.cliffc.aa.type.Type< T extends Type< T >.getstr(), com.cliffc.aa.HM.HM8.T2.is_base(), com.cliffc.aa.HM.HM8.T2.is_err(), com.cliffc.aa.HM.HM8.T2.is_fun(), com.cliffc.aa.HM.HM8.T2.is_leaf(), com.cliffc.aa.HM.HM8.T2.is_mem(), com.cliffc.aa.HM.HM8.T2.is_struct(), com.cliffc.aa.type.Type< T extends Type< T >.NIL, com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.Bits< B extends Bits< B >.str(), com.cliffc.aa.HM.HM8.T2.str(), com.cliffc.aa.type.Type< T extends Type< T >.toString(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.util.SB.unchar().
Referenced by com.cliffc.aa.HM.HM8.T2.getrec(), com.cliffc.aa.HM.HM8.Syntax.p0(), com.cliffc.aa.HM.HM8.VStack.str(), com.cliffc.aa.HM.HM8.T2.str(), com.cliffc.aa.HM.HM8.T2.toString(), and com.cliffc.aa.HM.HM8.T2.unify_rec().
toString()
String com.cliffc.aa.HM.HM8.T2.toString ()
Definition at line 1208 of file HM8.java.
 { return str(new SB(), new VBitSet(), get_dups(new VBitSet()) ).toString(); }
References com.cliffc.aa.HM.HM8.T2.get_dups(), com.cliffc.aa.HM.HM8.T2.str(), and com.cliffc.aa.util.SB.toString().
unify()
boolean com.cliffc.aa.HM.HM8.T2.unify (T2 that, Worklist work) package
Definition at line 841 of file HM8.java.
{
       if( this==that ) return false;
       assert DUPS.isEmpty();
       boolean progress = _unify(that,work);
       DUPS.clear();
       return progress;
     }
References com.cliffc.aa.HM.HM8.T2._unify(), and com.cliffc.aa.HM.HM8.T2.DUPS.
Referenced by com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Field.hm(), and com.cliffc.aa.HM.HM8.T2.unify_rec().
unify_base()
boolean com.cliffc.aa.HM.HM8.T2.unify_base (T2 that, Worklist work) private
Definition at line 928 of file HM8.java.
{
       Type con = _con.meet(that._con);
       if( con==that._con ) return false; // No progress
       if( work==null ) return true;
       that._con = con;          // Yes progress, but no update if null work
       _args = new T2[1];        // Room for a forwarding pointer
       _con=null;                // Flip from 'Base' to 'Leaf'
       return union(that,work);
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._con, and com.cliffc.aa.type.Type< T extends Type< T >.meet().
Referenced by com.cliffc.aa.HM.HM8.T2._unify().
unify_rec()
boolean com.cliffc.aa.HM.HM8.T2.unify_rec (int alias, T2 str, Worklist work) package
Definition at line 1154 of file HM8.java.
{
       assert is_mem() && str.is_struct();
       while( alias >= _args.length )
         _args = Arrays.copyOf(_args,_args.length<<1);
       if( _args[alias] != null ) return args(alias).unify(str,work);
       if( work!=null ) _args[alias] = str;
       return true;
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.HM.HM8.T2.is_mem(), com.cliffc.aa.HM.HM8.T2.str(), and com.cliffc.aa.HM.HM8.T2.unify().
Referenced by com.cliffc.aa.HM.HM8.T2._unify(), and com.cliffc.aa.HM.HM8.Struct.hm().
union()
boolean com.cliffc.aa.HM.HM8.T2.union (T2 that, Worklist work) package
Definition at line 804 of file HM8.java.
{
       assert no_uf(); // Cannot union twice
       if( this==that ) return false;
       if( work==null ) return true; // Report progress without changing
       // Worklist: put updates on the worklist for revisiting
       if( _deps != null ) {
         work.addAll(_deps); // Re-Apply
         // Merge update lists, for future unions
         if( that._deps==null && that.is_leaf() ) that._deps = _deps;
         else
           for( Syntax dep : _deps ) that.push_update(dep);
         _deps = null;
       }
       if( _args.length==0 ) _args = new T2[1];
       _args[0] = that;         // U-F update
       if( _name.charAt(0)!='V' ) _name = "V"+_uid; // Flag as a leaf & unified
       assert !no_uf();
       return true;
     }
References com.cliffc.aa.HM.HM8.T2._args, com.cliffc.aa.HM.HM8.T2._deps, com.cliffc.aa.HM.HM8.T2._name, com.cliffc.aa.HM.HM8.T2._uid, and com.cliffc.aa.HM.HM8.T2.no_uf().
Referenced by com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._unify(), and com.cliffc.aa.HM.HM8.T2.union_err().
union_err()
boolean com.cliffc.aa.HM.HM8.T2.union_err (T2 that, Worklist work, String msg) private
Definition at line 944 of file HM8.java.
{
       union(that,work);
       return that.union(make_err(msg),work);
     }
References com.cliffc.aa.HM.HM8.T2.make_err(), and com.cliffc.aa.HM.HM8.T2.union().
Referenced by com.cliffc.aa.HM.HM8.T2._unify().
vput()
boolean com.cliffc.aa.HM.HM8.T2.vput (T2 that, boolean progress) private
Definition at line 1032 of file HM8.java.
 { VARS.put(this,that); return progress; }
References com.cliffc.aa.HM.HM8.T2.VARS.
Referenced by com.cliffc.aa.HM.HM8.T2._fresh_unify().
Member Data Documentation
_aliases
BitsAlias com.cliffc.aa.HM.HM8.T2._aliases package
Definition at line 740 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.T2.copy(), com.cliffc.aa.HM.HM8.T2.str(), and com.cliffc.aa.HM.HM8.T2.T2().
_args
T2 [] com.cliffc.aa.HM.HM8.T2._args package
Definition at line 731 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._cycle_equals(), com.cliffc.aa.HM.HM8.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM8.T2._fresh(), com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM8.T2._get_dups(), com.cliffc.aa.HM.HM8.T2._occurs_in_type(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM8.T2.add_fld(), com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.HM.HM8.T2.copy(), com.cliffc.aa.HM.HM8.T2.debug_find(), com.cliffc.aa.HM.HM8.T2.find(), com.cliffc.aa.HM.HM8.T2.getrec(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.T2.no_uf(), com.cliffc.aa.HM.HM8.T2.or0(), com.cliffc.aa.HM.HM8.T2.push_update_impl(), com.cliffc.aa.HM.HM8.T2.str(), com.cliffc.aa.HM.HM8.T2.T2(), com.cliffc.aa.HM.HM8.T2.unify_base(), com.cliffc.aa.HM.HM8.T2.unify_rec(), and com.cliffc.aa.HM.HM8.T2.union().
_con
Type com.cliffc.aa.HM.HM8.T2._con package
Definition at line 734 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._cycle_equals(), com.cliffc.aa.HM.HM8.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM8.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.T2.copy(), com.cliffc.aa.HM.HM8.T2.fresh_base(), com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.HM.HM8.T2.is_base(), com.cliffc.aa.HM.HM8.T2.is_leaf(), com.cliffc.aa.HM.HM8.T2.or0(), com.cliffc.aa.HM.HM8.T2.str(), com.cliffc.aa.HM.HM8.T2.T2(), and com.cliffc.aa.HM.HM8.T2.unify_base().
_deps
Ary<Syntax> com.cliffc.aa.HM.HM8.T2._deps package
Definition at line 743 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM8.T2.add_fld(), com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.HM.HM8.T2.push_update_impl(), com.cliffc.aa.HM.HM8.T2.T2(), and com.cliffc.aa.HM.HM8.T2.union().
_ids
String [] com.cliffc.aa.HM.HM8.T2._ids package
Definition at line 737 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM8.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.T2.add_fld(), com.cliffc.aa.HM.HM8.T2.copy(), com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.HM.HM8.T2.str(), and com.cliffc.aa.HM.HM8.T2.T2().
_name
String com.cliffc.aa.HM.HM8.T2._name package
Definition at line 728 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._cycle_equals(), com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.T2.copy(), com.cliffc.aa.HM.HM8.T2.is_leaf(), com.cliffc.aa.HM.HM8.T2.isa(), com.cliffc.aa.HM.HM8.T2.str(), com.cliffc.aa.HM.HM8.T2.T2(), and com.cliffc.aa.HM.HM8.T2.union().
_uid
final int com.cliffc.aa.HM.HM8.T2._uid package
Definition at line 723 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._get_dups(), com.cliffc.aa.HM.HM8.T2._occurs_in_type(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM8.T2.dbl_uid(), com.cliffc.aa.HM.HM8.T2.push_update_impl(), com.cliffc.aa.HM.HM8.T2.str(), com.cliffc.aa.HM.HM8.T2.T2(), and com.cliffc.aa.HM.HM8.T2.union().
CDUPS
final HashMap<T2,T2> com.cliffc.aa.HM.HM8.T2.CDUPS = new HashMap<>() static private
Definition at line 1104 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._cycle_equals(), com.cliffc.aa.HM.HM8.T2.cycle_equals(), and com.cliffc.aa.HM.HM8.T2.reset().
CNT
int com.cliffc.aa.HM.HM8.T2.CNT =0 static private
Definition at line 722 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2.fresh_unify(), com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM8.T2.make_leaf(), com.cliffc.aa.HM.HM8.T2.reset(), and com.cliffc.aa.HM.HM8.T2.T2().
DUPS
final HashMap<Long,T2> com.cliffc.aa.HM.HM8.T2.DUPS = new HashMap<>() static private
Definition at line 840 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM8.T2.fresh_unify(), com.cliffc.aa.HM.HM8.T2.reset(), and com.cliffc.aa.HM.HM8.T2.unify().
ODUPS
final VBitSet com.cliffc.aa.HM.HM8.T2.ODUPS = new VBitSet() static private
Definition at line 1055 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._occurs_in_type(), com.cliffc.aa.HM.HM8.T2.nongen_in(), com.cliffc.aa.HM.HM8.T2.occurs_in(), com.cliffc.aa.HM.HM8.T2.occurs_in_type(), and com.cliffc.aa.HM.HM8.T2.reset().
UPDATE_VISIT
final VBitSet com.cliffc.aa.HM.HM8.T2.UPDATE_VISIT = new VBitSet() static package
Definition at line 1168 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2.add_deps_work(), com.cliffc.aa.HM.HM8.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM8.T2.push_update(), com.cliffc.aa.HM.HM8.T2.push_update_impl(), and com.cliffc.aa.HM.HM8.T2.reset().
VARS
final HashMap<T2,T2> com.cliffc.aa.HM.HM8.T2.VARS = new HashMap<>() static private
Definition at line 956 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._fresh(), com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2.fresh_unify(), com.cliffc.aa.HM.HM8.T2.reset(), and com.cliffc.aa.HM.HM8.T2.vput().
VCNT
int com.cliffc.aa.HM.HM8.T2.VCNT static private
Definition at line 1256 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._p(), and com.cliffc.aa.HM.HM8.T2.p().
VNAMES
final HashMap<T2,Integer> com.cliffc.aa.HM.HM8.T2.VNAMES = new HashMap<>() static private
Definition at line 1257 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._p(), and com.cliffc.aa.HM.HM8.T2.p().
The documentation for this class was generated from the following file:
HM8.java