aa: com.cliffc.aa.type.TypeInt Class Reference
com.cliffc.aa.type.TypeInt Class Reference
Public Member Functions
boolean above (Type t)
boolean above_center ()
final boolean contains (Type t)
boolean cycle_equals (Type o)
final T dual ()
boolean equals (Object o)
double getd ()
long getl ()
String getstr ()
boolean has_name ()
final int hashCode ()
Type high ()
boolean is_con ()
boolean is_display_ptr ()
boolean is_forward_ref ()
boolean isa (Type t)
final boolean isa_scalar ()
byte isBitShape (Type t)
Type join (Type t)
Type make_from (Type head, TypeMem map, VBitSet visit)
TypeInt maxsize (TypeInt ti)
boolean may_be_con ()
boolean may_nil ()
final Type meet (Type t)
Type meet_loop (Type t2)
Type meet_nil (Type nil)
TypeInt minsize (TypeInt ti)
boolean must_nil ()
Type oob ()
Type oob (Type e)
TypeMem oob (TypeMem e)
TypeMemPtr oob (TypeMemPtr e)
TypeObj oob (TypeObj e)
TypeStruct oob (TypeStruct e)
Type oob_deep (Type t)
Type oop_deep_impl (Type t)
final T remove_name ()
final T set_name (String name)
Type sharptr (Type ptr)
Type simple_ptr ()
SB str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
final String toString ()
void walk (Predicate< Type > p)
Type widen ()
Static Public Member Functions
static Ary< Type > ALL_TYPES ()
static TypeInt con (long con)
static boolean eq (Type[] t0, Type[] t1)
static void init0 (HashMap< String, Type > types)
static boolean intern_check ()
static TypeInt make (int x, int z, long con)
Public Attributes
int _hash
String _name
int _uid
byte _z
Static Public Attributes
static final Type ALL
static final Type ANY
static final TypeInt BOOL = make(-2, 1,0)
static final Type CTRL
static final Type FALSE = make(0, 1,0)
static final TypeInt INT32 = make(-2,32,0)
static final TypeInt INT64 = make(-2,64,0)
static final TypeInt INT8 = make(-2, 8,0)
static final Type NIL
static final TypeInt NINT64 = make(-1,64,0)
static final TypeInt NINT8 = make(-1, 8,0)
static final Type NSCALR
static final Type REAL
static int RECURSIVE_MEET
static final Type SCALAR
static final TypeInt TRUE = make(0, 1,1)
static final Type XCTRL
static final TypeInt XINT1 = make(2, 1,0)
static final Type XNIL
static final Type XNSCALR
static final Type XSCALAR
static final TypeInt ZERO = new TypeInt().init(0,1,0).hashcons_free()
Protected Member Functions
Type clone ()
T init (byte type, String name)
TypeInt xdual ()
Type xmeet (Type t)
Package Functions
int compute_hash ()
boolean contains (Type t, VBitSet bs)
final Type cross_nil (Type t)
final T hashcons_free ()
boolean intern_check1 ()
Type intern_lookup ()
boolean interned ()
boolean is_display ()
final String mtname (Type t, Type mt)
Type not_nil ()
T rdual ()
TypeStruct repeats_in_cycles (TypeStruct head, VBitSet bs)
final T retern ()
RuntimeException typerr (Type t)
final T untern ()
Type xmeetf (TypeFlt tf)
Static Package Functions
[static initializer]
static boolean check_name (String n)
static boolean check_startup ()
static void concat (Ary< Type > ts, Type[] ts1)
static void init1 (HashMap< String, Type > types)
static Type intern_find (int uid)
static int intern_size ()
static Type make (byte type)
Package Attributes
T _dual
byte _type
Static Package Attributes
static final TypeInt INT16 = make(-2,16,0)
static final Type NREAL
static final Pool[] POOLS
static final byte TALL
static final byte TANY
static final byte TARY
static final byte TCTRL
static final byte TFLD
static final byte TFLT
static final byte TFUNPTR
static final byte TFUNSIG
static final byte TINT
static final byte TLAST
static final byte TLIVE
static final byte TMEM
static final byte TMEMPTR
static final byte TNIL
static final byte TNREAL
static final byte TNSCALR
static final byte TOBJ
static final byte TREAL
static final byte TRPC
static final byte TSCALAR
static final byte TSIMPLE
static final byte TSTR
static final byte TSTRUCT
static final byte TTUPLE
static final byte TXCTRL
static final byte TXNIL
static final byte TXNREAL
static final byte TXNSCALR
static final byte TXREAL
static final byte TXSCALAR
static final TypeInt[] TYPES = new TypeInt[]{INT64,INT32,INT16,BOOL,TRUE,NINT64}
Private Member Functions
T _set_name (String name)
int _uid ()
boolean check_commute (Type t, Type mt)
boolean check_symmetric (Type t, Type mt)
T hashcons ()
TypeInt init (int x, int z, long con)
boolean intern_check0 (Type v)
boolean is_num ()
boolean is_ptr ()
boolean is_simple ()
int nn ()
Type xmt_name (Type t, Type mt)
Static Private Member Functions
static int log (long con)
Private Attributes
long _con
byte _x
Static Private Attributes
static Ary< Type > ALL_TYPES
static int CNT
static final ConcurrentHashMap< Type, Type > INTERN
static final byte[] ISA_SCALAR
static Type[] SCALAR_PRIMS
static final String[] STRS
static final Type XNREAL
static final Type XREAL
Detailed Description
Definition at line 9 of file TypeInt.java.
Member Function Documentation
[static initializer]()
com.cliffc.aa.type.TypeInt.[static initializer] static package
_set_name()
T com.cliffc.aa.type.Type< T extends Type< T >._set_name (String name) private inherited
Definition at line 558 of file Type.java.
{
     POOLS[_type]._clone++;
     T t1 = (T)clone();
     t1._name = name;
     return t1.hashcons_free();
   }
_uid()
int com.cliffc.aa.type.Type< T extends Type< T >._uid private inherited
Definition at line 103 of file Type.java.
 { return CNT++; }
above()
boolean com.cliffc.aa.type.Type< T extends Type< T >.above (Type< TypeInt > t) inherited
Definition at line 625 of file Type.java.
 { return t != this && meet(t)==t; }
above_center()
boolean com.cliffc.aa.type.TypeInt.above_center ()
Definition at line 179 of file TypeInt.java.
 { return _x>0; }
References com.cliffc.aa.type.TypeInt._x.
Referenced by com.cliffc.aa.type.TypeAry.update().
ALL_TYPES()
static Ary<Type> com.cliffc.aa.type.Type< T extends Type< T >.ALL_TYPES static inherited
Definition at line 651 of file Type.java.
{
     if( ALL_TYPES != null ) return ALL_TYPES;
     Ary<Type> ts = new Ary<>(new Type[1],0);
     concat(ts,Type      .TYPES);
     concat(ts,TypeFlt   .TYPES);
     concat(ts,TypeFunPtr.TYPES);
     concat(ts,TypeFunSig.TYPES);
     concat(ts,TypeInt   .TYPES);
     concat(ts,TypeLive  .TYPES);
     concat(ts,TypeMem   .TYPES);
     concat(ts,TypeMemPtr.TYPES);
     concat(ts,TypeObj   .TYPES);
     concat(ts,TypeRPC   .TYPES);
     concat(ts,TypeStr   .TYPES);
     concat(ts,TypeStruct.TYPES);
     concat(ts,TypeTuple .TYPES);
     concat(ts,TypeAry   .TYPES);
     // Partial order Sort, makes for easier tests later.  Arrays.sort requires
     // a total order (i.e., the obvious Comparator breaks the sort contract),
     // so we hand-roll a simple bubble sort.
     for( int i=0; i<ts._len; i++ )
       for( int j=i+1; j<ts._len; j++ )
         if( ts._es[j].isa(ts._es[i]) ) { Type tmp = ts._es[i]; ts._es[i] = ts._es[j]; ts._es[j] = tmp; }
     return (ALL_TYPES = ts); // Preserve for tests
   }
check_commute()
boolean com.cliffc.aa.type.Type< T extends Type< T >.check_commute (Type< TypeInt > t, Type< TypeInt > mt) private inherited
Definition at line 593 of file Type.java.
{
     if( t==this ) return true;
     if( is_simple() && !t.is_simple() ) return true; // By design, flipped the only allowed order
     Type mt2 = t.xmeet(this);   // Reverse args and try again
     // Also reverse names.
     Type nmt2 = t.xmt_name(this,mt2);
     if( mt==nmt2 ) return true;
     System.out.println("Meet not commutative: "+this+".meet("+t+")="+mt+",\n but "+t+".meet("+this+")="+nmt2);
     return false;
   }
check_name()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.check_name (String n) static package inherited
Definition at line 548 of file Type.java.
 { return n.isEmpty() || n.charAt(n.length()-1)==':'; }
check_startup()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.check_startup static package inherited
Definition at line 684 of file Type.java.
{
     Type[] ts = ALL_TYPES().asAry();
     // Confirm commutative & complete
     for( Type t0 : ts )
       for( Type t1 : ts ) {
         Type mt = t0.meet(t1);
         assert t0.check_commute  (t1,mt);
         assert t0.check_symmetric(t1,mt);
       }
     // Confirm associative
     int errs=0;
     for( Type t0 : ts )
       for( Type t1 : ts )
         for( Type t2 : ts ) {
           Type t01   = t0 .meet(t1 );
           Type t12   = t1 .meet(t2 );
           Type t01_2 = t01.meet(t2 );
           Type t0_12 = t0 .meet(t12);
           if( t01_2 != t0_12 && errs++ < 10 )
             System.err.println("("+t0+"&"+t1+") & "+t2+" == "+t0+" & ("+t1+" & "+t2+"); "+
                                "("+t01      +") & "+t2+" == "+t0+" & ("+t12        +"); "+
                                t01_2                  +" == "+t0_12);
         }
     assert errs==0 : "Found "+errs+" associative errors";
     // Confirm symmetry.  If A isa B, then A.join(C) isa B.join(C)
     for( Type t0 : ts )
       for( Type t1 : ts ) {
         if( t0.isa(t1) ) {
           for( Type t2 : ts ) {
             Type t02 = t0.join(t2);
             Type t12 = t1.join(t2);
             Type mt  = t02.meet(t12);
             if( mt != t12 && errs++ < 10 ) {
               System.err.println("("+t0+" ^ "+t2+") = "+t02+"; "+
                                  "("+t1+" ^ "+t2+") = "+t12+"; "+
                                  "their meet = "+mt+" which is not "+t12);
             }
           }
         }
       }
     assert errs==0 : "Found "+errs+" non-join-type errors";
     // Check scalar primitives; all are SCALARS and none sub-type each other.
     SCALAR_PRIMS = new Type[] { TypeInt.INT64, TypeFlt.FLT64, TypeMemPtr.OOP0, TypeFunPtr.GENERIC_FUNPTR, TypeRPC.ALL_CALL };
     for( Type t : SCALAR_PRIMS ) assert t.isa(SCALAR);
     for( int i=0; i<SCALAR_PRIMS.length; i++ )
       for( int j=i+1; j<SCALAR_PRIMS.length; j++ )
         assert !SCALAR_PRIMS[i].isa(SCALAR_PRIMS[j]);
     return true;
   }
check_symmetric()
boolean com.cliffc.aa.type.Type< T extends Type< T >.check_symmetric (Type< TypeInt > t, Type< TypeInt > mt) private inherited
Definition at line 608 of file Type.java.
{
     if( t==this ) return true;
     Type ta = mt._dual.meet(t._dual);
     Type tb = mt._dual.meet(  _dual);
     if( ta==t._dual && tb==_dual ) return true;
     System.err.print("("+this+" & "+t+")=="+mt+" but \n("+mt._dual+" & ");
     if( ta!=t._dual ) System.err.println(t._dual+")=="+ta+" \nwhich is not "+t._dual);
     else              System.err.println(  _dual+")=="+tb+" \nwhich is not "+  _dual);
     return false;
   }
clone()
Type com.cliffc.aa.type.Type< T extends Type< T >.clone protected inherited
Definition at line 304 of file Type.java.
{
     try {
       POOLS[_type]._clone++;
       Type t = (Type)super.clone();
       t._uid = _uid();
       t._dual = null;
       t._hash = 0;
       if( t instanceof TypeStruct )
         ((TypeStruct)t)._cyclic = false;
       return t;
     }
     catch( CloneNotSupportedException cns ) { throw new RuntimeException(cns); }
   }
compute_hash()
int com.cliffc.aa.type.TypeInt.compute_hash () package
Definition at line 15 of file TypeInt.java.
 { return super.compute_hash()+_x+_z+(int)_con; }
References com.cliffc.aa.type.TypeInt._con, com.cliffc.aa.type.TypeInt._x, and com.cliffc.aa.type.TypeInt._z.
con()
static TypeInt com.cliffc.aa.type.TypeInt.con (long con) static
Definition at line 37 of file TypeInt.java.
 { return make(0,log(con),con); }
References com.cliffc.aa.type.TypeInt.log(), and com.cliffc.aa.type.TypeInt.make().
Referenced by com.cliffc.aa.node.PrimNode.Prim1OpI64.apply(), com.cliffc.aa.node.PrimNode.Prim2OpI64.apply(), com.cliffc.aa.HM.HM9.IsEmpty.apply(), com.cliffc.aa.HM.HM.IsEmpty.apply(), com.cliffc.aa.HM.HM9.Mul.apply(), com.cliffc.aa.HM.HM.Mul.apply(), com.cliffc.aa.HM.HM9.Dec.apply(), com.cliffc.aa.HM.HM.Add.apply(), com.cliffc.aa.HM.HM.Dec.apply(), com.cliffc.aa.Parse.inc(), com.cliffc.aa.type.TypeInt.init(), com.cliffc.aa.type.TypeInt.log(), com.cliffc.aa.type.TypeFlt.make(), com.cliffc.aa.type.TypeInt.make(), com.cliffc.aa.HM.HM6.number(), com.cliffc.aa.HM.HM8.number(), com.cliffc.aa.HM.HM7.number(), com.cliffc.aa.HM.HM9.number(), com.cliffc.aa.HM.HM.number(), com.cliffc.aa.Parse.number(), com.cliffc.aa.node.TestNode.print(), com.cliffc.aa.HM.TestHM6.test01(), com.cliffc.aa.HM.TestHM4.test01(), com.cliffc.aa.HM.TestHM5.test01(), com.cliffc.aa.HM.TestHM2.test01(), com.cliffc.aa.HM.TestHM3.test01(), com.cliffc.aa.HM.TestHM.test01(), com.cliffc.aa.HM.TestHM9.test01(), com.cliffc.aa.HM.TestHM3.test02(), com.cliffc.aa.HM.TestHM4.test02(), com.cliffc.aa.HM.TestHM5.test02(), com.cliffc.aa.HM.TestHM2.test02(), com.cliffc.aa.HM.TestHM.test02(), com.cliffc.aa.HM.TestHM9.test02(), com.cliffc.aa.HM.TestHM4.test03(), com.cliffc.aa.HM.TestHM5.test03(), com.cliffc.aa.HM.TestHM2.test03(), com.cliffc.aa.HM.TestHM3.test03(), com.cliffc.aa.HM.TestHM4.test04(), com.cliffc.aa.HM.TestHM5.test04(), com.cliffc.aa.HM.TestHM2.test04(), com.cliffc.aa.HM.TestHM3.test04(), com.cliffc.aa.HM.TestHM4.test05(), com.cliffc.aa.HM.TestHM5.test05(), com.cliffc.aa.HM.TestHM2.test05(), com.cliffc.aa.HM.TestHM3.test05(), com.cliffc.aa.HM.TestHM3.test05a(), com.cliffc.aa.HM.TestHM.test06(), com.cliffc.aa.HM.TestHM9.test06(), com.cliffc.aa.HM.TestHM2.test07(), com.cliffc.aa.HM.TestHM4.test07(), com.cliffc.aa.HM.TestHM5.test07(), com.cliffc.aa.HM.TestHM3.test07(), com.cliffc.aa.HM.TestHM.test08(), com.cliffc.aa.HM.TestHM9.test08(), com.cliffc.aa.HM.TestHM2.test08(), com.cliffc.aa.HM.TestHM4.test08(), com.cliffc.aa.HM.TestHM5.test08(), com.cliffc.aa.HM.TestHM3.test08(), com.cliffc.aa.HM.TestHM1.test1(), com.cliffc.aa.HM.TestHM2.test10(), com.cliffc.aa.HM.TestHM3.test10(), com.cliffc.aa.HM.TestHM5.test11(), com.cliffc.aa.HM.TestHM4.test11(), com.cliffc.aa.HM.TestHM2.test11(), com.cliffc.aa.HM.TestHM3.test11(), com.cliffc.aa.HM.TestHM.test12(), com.cliffc.aa.HM.TestHM9.test12(), com.cliffc.aa.HM.TestHM4.test12(), com.cliffc.aa.HM.TestHM5.test12(), com.cliffc.aa.HM.TestHM.test13(), com.cliffc.aa.HM.TestHM9.test13(), com.cliffc.aa.HM.TestHM1.test13(), com.cliffc.aa.HM.TestHM4.test13(), com.cliffc.aa.HM.TestHM5.test13(), com.cliffc.aa.HM.TestHM4.test14(), com.cliffc.aa.HM.TestHM5.test14(), com.cliffc.aa.HM.TestHM.test15(), com.cliffc.aa.HM.TestHM9.test15(), com.cliffc.aa.HM.TestHM4.test15(), com.cliffc.aa.HM.TestHM5.test15(), com.cliffc.aa.HM.TestHM4.test16(), com.cliffc.aa.HM.TestHM5.test16(), com.cliffc.aa.HM.TestHM1.test17(), com.cliffc.aa.HM.TestHM4.test17(), com.cliffc.aa.HM.TestHM5.test17(), com.cliffc.aa.HM.TestHM.test18(), com.cliffc.aa.HM.TestHM9.test18(), com.cliffc.aa.HM.TestHM1.test18(), com.cliffc.aa.HM.TestHM4.test18(), com.cliffc.aa.HM.TestHM5.test18(), com.cliffc.aa.HM.TestHM.test19(), com.cliffc.aa.HM.TestHM9.test19(), com.cliffc.aa.HM.TestHM4.test19(), com.cliffc.aa.HM.TestHM5.test19(), com.cliffc.aa.HM.TestHM1.test2(), com.cliffc.aa.HM.TestHM1.test20(), com.cliffc.aa.HM.TestHM4.test20(), com.cliffc.aa.HM.TestHM5.test20(), com.cliffc.aa.HM.TestHM4.test21(), com.cliffc.aa.HM.TestHM5.test21(), com.cliffc.aa.HM.TestHM5.test22(), com.cliffc.aa.HM.TestHM4.test22(), com.cliffc.aa.HM.TestHM1.test23(), com.cliffc.aa.HM.TestHM5.test23(), com.cliffc.aa.HM.TestHM4.test23(), com.cliffc.aa.HM.TestHM.test25(), com.cliffc.aa.HM.TestHM9.test25(), com.cliffc.aa.HM.TestHM.test26(), com.cliffc.aa.HM.TestHM9.test26(), com.cliffc.aa.HM.TestHM1.test3(), com.cliffc.aa.HM.TestHM9.test34(), com.cliffc.aa.HM.TestHM.test34(), com.cliffc.aa.HM.TestHM1.test4(), com.cliffc.aa.HM.TestHM.test47(), com.cliffc.aa.HM.TestHM9.test47(), com.cliffc.aa.HM.TestHM.test49(), com.cliffc.aa.HM.TestHM9.test49(), com.cliffc.aa.HM.TestHM1.test5(), com.cliffc.aa.HM.TestHM9.test50(), com.cliffc.aa.HM.TestHM.test56(), com.cliffc.aa.HM.TestHM1.test7(), com.cliffc.aa.HM.TestHM1.test8(), com.cliffc.aa.type.TestApprox.testApprox1(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox4(), com.cliffc.aa.type.TestApprox.testApprox7(), com.cliffc.aa.TestLive.testBasic(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.TestLive.testNewObj(), com.cliffc.aa.TestParse.testParse(), com.cliffc.aa.TestParse.testParse00(), com.cliffc.aa.TestParse.testParse01(), com.cliffc.aa.TestParse.testParse01a(), com.cliffc.aa.TestParse.testParse02(), com.cliffc.aa.TestParse.testParse03(), com.cliffc.aa.TestParse.testParse04(), com.cliffc.aa.TestParse.testParse06(), com.cliffc.aa.TestParse.testParse07(), com.cliffc.aa.TestParse.testParse09(), com.cliffc.aa.TestParse.testParse10(), com.cliffc.aa.TestParse.testParse11(), com.cliffc.aa.TestParse.testParse12(), com.cliffc.aa.TestParse.testParse13(), com.cliffc.aa.TestParse.testParse14(), com.cliffc.aa.TestParse.testParse15(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.node.PrimNode.AndI64.value(), com.cliffc.aa.node.PrimNode.OrI64.value(), and com.cliffc.aa.type.TypeInt.xmeetf().
concat()
static void com.cliffc.aa.type.Type< T extends Type< T >.concat (Ary< Type< TypeInt > > ts, Type< TypeInt >[] ts1) static package inherited
Definition at line 676 of file Type.java.
{
     for( Type t1 : ts1 ) {
       assert !t1.above_center(); // Always below-center or equal, because we'll dual anyways
       ts.push(t1);
       if( t1!=t1.dual() ) ts.push(t1.dual());
     }
   }
contains() [1/2]
final boolean com.cliffc.aa.type.Type< T extends Type< T >.contains (Type< TypeInt > t) inherited
Definition at line 926 of file Type.java.
 { return contains(t,null); }
contains() [2/2]
boolean com.cliffc.aa.type.Type< T extends Type< T >.contains (Type< TypeInt > t, VBitSet bs) package inherited
Definition at line 927 of file Type.java.
 { return this==t; }
cross_nil()
final Type com.cliffc.aa.type.Type< T extends Type< T >.cross_nil (Type< TypeInt > t) package inherited
Definition at line 865 of file Type.java.
 { return must_nil() || t.must_nil() ? SCALAR : NSCALR; }
cycle_equals()
boolean com.cliffc.aa.type.TypeInt.cycle_equals (Type o)
Definition at line 22 of file TypeInt.java.
 { return equals(o); }
References com.cliffc.aa.type.TypeInt.equals().
dual()
final T com.cliffc.aa.type.Type< T extends Type< T >.dual inherited
Definition at line 361 of file Type.java.
 { return _dual; }
eq()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.eq (Type< TypeInt >[] t0, Type< TypeInt >[] t1) static inherited
Definition at line 136 of file Type.java.
{
     if( t0==t1 ) return true;
     if( t0==null || t1==null ) return false;
     if( t0.length != t1.length ) return false;
     for( int i=0; i<t0.length; i++ )
       if( t0[i] != t1[i] )
         return false;
     return true;
   }
equals()
boolean com.cliffc.aa.type.TypeInt.equals (Object o)
Definition at line 16 of file TypeInt.java.
{
     if( this==o ) return true;
     if( !(o instanceof TypeInt) ) return false;
     TypeInt t2 = (TypeInt)o;
     return super.equals(o) && _x==t2._x && _z==t2._z && _con==t2._con;
   }
References com.cliffc.aa.type.TypeInt._con, com.cliffc.aa.type.TypeInt._x, com.cliffc.aa.type.TypeInt._z, and com.cliffc.aa.type.TypeInt.equals().
Referenced by com.cliffc.aa.type.TypeInt.cycle_equals(), com.cliffc.aa.type.TypeInt.equals(), and com.cliffc.aa.type.TypeInt.xmeet().
getd()
double com.cliffc.aa.type.TypeInt.getd ()
Definition at line 62 of file TypeInt.java.
 { assert is_con() && (long)((double)_con)==_con; return _con; }
References com.cliffc.aa.type.TypeInt._con, and com.cliffc.aa.type.TypeInt.is_con().
getl()
long com.cliffc.aa.type.TypeInt.getl ()
Definition at line 61 of file TypeInt.java.
 { assert is_con(); return _con; }
References com.cliffc.aa.type.TypeInt._con, and com.cliffc.aa.type.TypeInt.is_con().
Referenced by com.cliffc.aa.node.MemPrimNode.err().
getstr()
String com.cliffc.aa.type.Type< T extends Type< T >.getstr inherited
Definition at line 806 of file Type.java.
 { throw typerr(null); }
has_name()
boolean com.cliffc.aa.type.Type< T extends Type< T >.has_name inherited
Definition at line 549 of file Type.java.
 { return !_name.isEmpty(); }
hashCode()
final int com.cliffc.aa.type.Type< T extends Type< T >.hashCode inherited
Definition at line 106 of file Type.java.
 { assert _hash!=0; return _hash; }
hashcons()
T com.cliffc.aa.type.Type< T extends Type< T >.hashcons private inherited
Definition at line 165 of file Type.java.
{
     _hash = compute_hash();     // Set hash
     T t2 = (T)INTERN.get(this); // Lookup
     if( t2!=null ) {            // Found prior
       assert t2._dual != null;  // Prior is complete with dual
       assert this != t2;        // Do not hashcons twice, should not get self back
       return t2;                // Return prior
     }
     if( RECURSIVE_MEET > 0 )    // Mid-building recursive types; do not intern
       return (T)this;
     // Not in type table
     _dual = null;                // No dual yet
     INTERN.put(this,this);       // Put in table without dual
     T d = xdual();               // Compute dual without requiring table lookup, and not setting name
     d._name = _name;             // xdual does not set name either
     d._hash = d.compute_hash();  // Set dual hash
     _dual = d;
     if( this==d ) return d;      // Self-symmetric?  Dual is self
     assert !equals(d);           // Self-symmetric is handled by caller
     assert d._dual==null;        // Else dual-dual not computed yet
     assert INTERN.get(d)==null;
     d._dual = (T)this;
     INTERN.put(d,d);
     return (T)this;
   }
hashcons_free()
final T com.cliffc.aa.type.Type< T extends Type< T >.hashcons_free package inherited
Definition at line 153 of file Type.java.
{
     T t2 = hashcons();
     return this==t2 ? t2 : (T)POOLS[_type].free(this,t2);
   }
high()
Type com.cliffc.aa.type.Type< T extends Type< T >.high inherited
Definition at line 796 of file Type.java.
 { return above_center() ? this : dual(); }
init() [1/2]
T com.cliffc.aa.type.Type< T extends Type< T >.init (byte type, String name) protected inherited
Definition at line 105 of file Type.java.
 { _type=type; _name=name; return (T)this; }
init() [2/2]
TypeInt com.cliffc.aa.type.TypeInt.init (int x, int z, long con) private
Definition at line 13 of file TypeInt.java.
 { super.init(TINT,""); _x=(byte)x; _z=(byte)z; _con = con; return this; }
References com.cliffc.aa.type.TypeInt._con, com.cliffc.aa.type.TypeInt._x, com.cliffc.aa.type.TypeInt._z, com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.type.TypeInt.init(), and com.cliffc.aa.type.Type< TypeInt >.TINT.
Referenced by com.cliffc.aa.type.TypeInt.init(), com.cliffc.aa.type.TypeInt.make(), and com.cliffc.aa.type.TypeInt.xdual().
init0()
static void com.cliffc.aa.type.Type< T extends Type< T >.init0 (HashMap< String, Type< TypeInt > > types) static inherited
Definition at line 642 of file Type.java.
{
     types.put("real",REAL);
     types.put("scalar",SCALAR);
     TypeInt.init1(types);
     TypeFlt.init1(types);
     TypeStr.init1(types);
   }
init1()
static void com.cliffc.aa.type.TypeInt.init1 (HashMap< String, Type > types) static package
Definition at line 51 of file TypeInt.java.
{
     types.put("bool" ,BOOL);
     types.put("int1" ,BOOL);
     types.put("int8" ,INT8);
     types.put("int16",INT16);
     types.put("int32",INT32);
     types.put("int64",INT64);
     types.put("int"  ,INT64);
   }
References com.cliffc.aa.type.TypeInt.BOOL, com.cliffc.aa.type.TypeInt.INT16, com.cliffc.aa.type.TypeInt.INT32, com.cliffc.aa.type.TypeInt.INT64, and com.cliffc.aa.type.TypeInt.INT8.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.init0().
intern_check()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check static inherited
Definition at line 212 of file Type.java.
{
     int errs=0;
     for( Type k : INTERN.keySet() ) {
       Type v = INTERN.get(k);
       if( !k.intern_check0(v) ) {
         System.out.println("INTERN_CHECK FAIL: "+k._uid+":"+k+" vs "+v._uid+":"+v);
         errs++;
       }
     }
     return errs==0;
   }
intern_check0()
boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check0 (Type< TypeInt > v) private inherited
Definition at line 223 of file Type.java.
{
     if( this != v || _dual==null || _dual._dual!=this || compute_hash()!=_hash ) return false;
     return intern_check1();
   }
intern_check1()
boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check1 package inherited
Definition at line 227 of file Type.java.
 { return true; }
intern_find()
static Type com.cliffc.aa.type.Type< T extends Type< T >.intern_find (int uid) static package inherited
Definition at line 229 of file Type.java.
{
     for( Type k : INTERN.keySet() )
       if( k._uid==uid )
         return k;
     return null;
   }
intern_lookup()
Type com.cliffc.aa.type.Type< T extends Type< T >.intern_lookup package inherited
Definition at line 210 of file Type.java.
 { return INTERN.get(this); }
intern_size()
static int com.cliffc.aa.type.Type< T extends Type< T >.intern_size static package inherited
Definition at line 211 of file Type.java.
 { return INTERN.size(); }
interned()
boolean com.cliffc.aa.type.Type< T extends Type< T >.interned package inherited
Definition at line 209 of file Type.java.
 { return INTERN.get(this)==this; }
is_con()
boolean com.cliffc.aa.type.TypeInt.is_con ()
Definition at line 181 of file TypeInt.java.
 { return _x==0; }
References com.cliffc.aa.type.TypeInt._x.
Referenced by com.cliffc.aa.node.MemPrimNode.err(), com.cliffc.aa.type.TypeInt.getd(), and com.cliffc.aa.type.TypeInt.getl().
is_display()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_display package inherited
Definition at line 942 of file Type.java.
 { return false; }
is_display_ptr()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_display_ptr inherited
Definition at line 941 of file Type.java.
 { return _type==TSCALAR || _type==TXSCALAR || _type==TNIL || _type==TXNIL || _type==TANY || _type==TALL; }
is_forward_ref()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_forward_ref inherited
Definition at line 799 of file Type.java.
 { return false; }
is_num()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_num private inherited
Definition at line 353 of file Type.java.
 { byte t = _type;  return t == TREAL || t == TXREAL || t == TNREAL || t == TXNREAL || t == TINT || t == TFLT; }
is_ptr()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_ptr private inherited
Definition at line 352 of file Type.java.
 { byte t = _type;  return t == TFUNPTR || t == TMEMPTR; }
is_simple()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_simple private inherited
Definition at line 351 of file Type.java.
 { return _type < TSIMPLE; }
isa()
boolean com.cliffc.aa.type.Type< T extends Type< T >.isa (Type< TypeInt > t) inherited
Definition at line 623 of file Type.java.
 { return meet(t)==t; }
isa_scalar()
final boolean com.cliffc.aa.type.Type< T extends Type< T >.isa_scalar inherited
Definition at line 356 of file Type.java.
 { assert ISA_SCALAR.length==TLAST; return ISA_SCALAR[_type]!=0; }
isBitShape()
byte com.cliffc.aa.type.TypeInt.isBitShape (Type t)
Definition at line 161 of file TypeInt.java.
{
     // TODO: Allow loss-less conversions (e.g. small float integer constants convert to ints just fine)
     if( t._type == TXSCALAR ) return 0;
     if( t._type == TINT ) return (byte)(_z<=((TypeInt)t)._z ? 0 : 99);
     if( t._type == TFLT ) return 2; // Int->Flt ignores large int overflow issues
     if( t._type == Type.TMEMPTR ) return 99; // No flt->ptr conversion
     if( t._type == Type.TFUNPTR ) return 99; // No flt->ptr conversion
     if( t._type == Type.TALL ) return 99;
     if( t._type == TREAL ) return 1;
     if( t._type == TSCALAR ) return 9; // Might have to autobox
     if( t._type == TSTR ) return 99;
     if( t == NIL || t == XNIL ) return 99; // Cannot not-nil to nil
     throw com.cliffc.aa.AA.unimpl();
   }
References com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.type.TypeInt._z, com.cliffc.aa.type.Type< TypeInt >.NIL, com.cliffc.aa.type.Type< T extends Type< T >.TALL, com.cliffc.aa.type.Type< TypeInt >.TFLT, com.cliffc.aa.type.Type< T extends Type< T >.TFUNPTR, com.cliffc.aa.type.Type< TypeInt >.TINT, com.cliffc.aa.type.Type< T extends Type< T >.TMEMPTR, com.cliffc.aa.type.Type< TypeInt >.TREAL, com.cliffc.aa.type.Type< TypeInt >.TSCALAR, com.cliffc.aa.type.Type< TypeInt >.TSTR, com.cliffc.aa.type.Type< TypeInt >.TXSCALAR, com.cliffc.aa.AA.unimpl(), and com.cliffc.aa.type.Type< TypeInt >.XNIL.
join()
Type com.cliffc.aa.type.Type< T extends Type< T >.join (Type< TypeInt > t) inherited
Definition at line 619 of file Type.java.
 { return dual().meet(t.dual()).dual(); }
log()
static int com.cliffc.aa.type.TypeInt.log (long con) static private
Definition at line 103 of file TypeInt.java.
{
     if(     0 <= con && con <=     1 ) return  1;
     if(  -128 <= con && con <=   127 ) return  8;
     if(-32768 <= con && con <= 32767 ) return 16;
     if(Integer.MIN_VALUE <= con && con <= Integer.MAX_VALUE ) return 32;
     return 64;
   }
References com.cliffc.aa.type.TypeInt.con().
Referenced by com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.type.TypeInt.xmeet(), and com.cliffc.aa.type.TypeInt.xmeetf().
make() [1/2]
static Type com.cliffc.aa.type.Type< T extends Type< T >.make (byte type) static package inherited
Definition at line 147 of file Type.java.
{
     Pool P = POOLS[type];
     Type t1 = P.malloc();
     return t1.init(type,"").hashcons_free();
   }
make() [2/2]
static TypeInt com.cliffc.aa.type.TypeInt.make (int x, int z, long con) static
Definition at line 31 of file TypeInt.java.
{
     if( Math.abs(x)==1 && z==1 && con==0) con=1; // not-null-bool is just a 1
     TypeInt t1 = POOLS[TINT].malloc();
     return t1.init(x,z,con).hashcons_free();
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.type.Type< T extends Type< T >.hashcons_free(), com.cliffc.aa.type.TypeInt.init(), com.cliffc.aa.type.Type< TypeInt >.POOLS, and com.cliffc.aa.type.Type< TypeInt >.TINT.
Referenced by com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.type.TypeInt.maxsize(), com.cliffc.aa.type.TypeInt.meet_nil(), com.cliffc.aa.type.TypeInt.minsize(), com.cliffc.aa.type.TypeInt.not_nil(), com.cliffc.aa.type.TypeInt.xmeet(), and com.cliffc.aa.type.TypeInt.xmeetf().
make_from()
Type com.cliffc.aa.type.Type< T extends Type< T >.make_from (Type< TypeInt > head, TypeMem map, VBitSet visit) inherited
Definition at line 945 of file Type.java.
 { return this; }
maxsize()
TypeInt com.cliffc.aa.type.TypeInt.maxsize (TypeInt ti)
Definition at line 201 of file TypeInt.java.
 { return make(-2,Math.max(_z,ti._z),0);  }
References com.cliffc.aa.type.TypeInt._z, and com.cliffc.aa.type.TypeInt.make().
Referenced by com.cliffc.aa.node.PrimNode.OrI64.value().
may_be_con()
boolean com.cliffc.aa.type.TypeInt.may_be_con ()
Definition at line 180 of file TypeInt.java.
 { return _x>=0; }
References com.cliffc.aa.type.TypeInt._x.
may_nil()
boolean com.cliffc.aa.type.TypeInt.may_nil ()
Definition at line 183 of file TypeInt.java.
 { return _x>0 || (_x==0 && _con==0); }
References com.cliffc.aa.type.TypeInt._con, and com.cliffc.aa.type.TypeInt._x.
meet()
final Type com.cliffc.aa.type.Type< T extends Type< T >.meet (Type< TypeInt > t) inherited
Definition at line 412 of file Type.java.
{
     // Short cut for the self case
     if( t == this ) return this;
     // Short-cut for seeing this meet before
     Type mt = Key.get(this,t);
     if( mt != null ) return mt;
     // "Triangulate" the matrix and cut in half the number of cases.
     // Reverse; xmeet 2nd arg is never "is_simple" and never equal to "this".
     // This meet ignores the _name field, and can return any-old name it wants.
     mt = !is_simple() && t.is_simple() ? t.xmeet(this) : xmeet(t);
     // Meet the names.  Subclasses basically ignore the names as they have
     // their own complicated meets to perform, so we meet them here for all.
     Type nmt = xmt_name(t,mt);
     // Quick check on NIL: if either argument is NIL the result is allowed to
     // be NIL...  but nobody in the lattice can make a NIL from whole cloth, or
     // we get the crossing-nil bug.
     assert (nmt != NIL && nmt!=XNIL) || this==NIL || this==XNIL || t==NIL || t==XNIL;
     // Record this meet, to short-cut next time
     if( RECURSIVE_MEET == 0 )   // Only not mid-building recursive types;
       Key.put(this,t,nmt);
     return nmt;
   }
meet_loop()
Type com.cliffc.aa.type.Type< T extends Type< T >.meet_loop (Type< TypeInt > t2) inherited
Definition at line 628 of file Type.java.
 { return meet(t2); }
meet_nil()
Type com.cliffc.aa.type.TypeInt.meet_nil (Type nil)
Definition at line 194 of file TypeInt.java.
{
     if( _x==2 ) return nil;
     if( _x==0 && _con==0 ) return nil==Type.XNIL ? this : Type.NIL;
     return TypeInt.make(-2,_z,0);
   }
References com.cliffc.aa.type.TypeInt._con, com.cliffc.aa.type.TypeInt._x, com.cliffc.aa.type.TypeInt._z, com.cliffc.aa.type.TypeInt.make(), com.cliffc.aa.type.Type< T extends Type< T >.NIL, and com.cliffc.aa.type.Type< T extends Type< T >.XNIL.
minsize()
TypeInt com.cliffc.aa.type.TypeInt.minsize (TypeInt ti)
Definition at line 200 of file TypeInt.java.
 { return make(-2,Math.min(_z,ti._z),0);  }
References com.cliffc.aa.type.TypeInt._z, and com.cliffc.aa.type.TypeInt.make().
Referenced by com.cliffc.aa.node.PrimNode.AndI64.value().
mtname()
final String com.cliffc.aa.type.Type< T extends Type< T >.mtname (Type< TypeInt > t, Type< TypeInt > mt) package inherited
Definition at line 567 of file Type.java.
{
     Type   t0 = this,  t1 = t;
     String s0 = t0._name, s1 = t1._name;
     assert check_name(s0) && check_name(s1);
     if( Util.eq(s0,s1) ) return s0;
     // Sort by name length
     if( s0.length() > s1.length() ) { t1=this; t0=t; s0=t0._name; s1=t1._name; }
     int x = 0, i;  char c;    // Last colon separator index
     // Find split point
     for( i = 0; i < s0.length(); i++ ) {
       if( (c=s0.charAt(i)) != s1.charAt(i) )
         break;
       if( c==':' ) x=i;
     }
     // If s0 is a prefix of s1, and s0 is high then it can cover s1.
     if( i==s0.length() && t0.above_center() && (!t1.above_center() || mt.above_center()) )
       return s1;
     // Keep the common prefix, which might be all of s0
     String s2 = i==s0.length() ? s0 : s0.substring(0, x).intern();
     assert check_name(s2);
     return s2;
   }
must_nil()
boolean com.cliffc.aa.type.TypeInt.must_nil ()
Definition at line 182 of file TypeInt.java.
 { return _x==-2 || (_x==0 && _con==0); }
References com.cliffc.aa.type.TypeInt._con, and com.cliffc.aa.type.TypeInt._x.
Referenced by com.cliffc.aa.type.TypeInt.xmeetf().
nn()
int com.cliffc.aa.type.TypeInt.nn () private
Definition at line 102 of file TypeInt.java.
 { assert _x <=0; return _con!=0 || _x== -1 ? -1 : -2; }
References com.cliffc.aa.type.TypeInt._con, and com.cliffc.aa.type.TypeInt._x.
Referenced by com.cliffc.aa.type.TypeInt.xmeet().
not_nil()
Type com.cliffc.aa.type.TypeInt.not_nil () package
Definition at line 184 of file TypeInt.java.
{
     // Choice {+0+1} ==> {+1}
     if( this==BOOL.dual() ) return make(1,1,1);
     // {0} ==> {0,1}
     if( this==FALSE ) return BOOL;
     // Choice any-int ==> any-not-nil-int
     if( _x==2 ) return make(1,_z,_con);
     // Never had a nil choice
     return this;
   }
References com.cliffc.aa.type.TypeInt._con, com.cliffc.aa.type.TypeInt._x, com.cliffc.aa.type.TypeInt._z, com.cliffc.aa.type.TypeInt.BOOL, com.cliffc.aa.type.Type< T extends Type< T >.dual(), com.cliffc.aa.type.TypeInt.FALSE, and com.cliffc.aa.type.TypeInt.make().
oob() [1/6]
Type com.cliffc.aa.type.Type< T extends Type< T >.oob inherited
Definition at line 635 of file Type.java.
 { return oob(ALL); }
oob() [2/6]
Type com.cliffc.aa.type.Type< T extends Type< T >.oob (Type< TypeInt > e) inherited
Definition at line 636 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [3/6]
TypeMem com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeMem e) inherited
Definition at line 639 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [4/6]
TypeMemPtr com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeMemPtr e) inherited
Definition at line 640 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [5/6]
TypeObj com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeObj e) inherited
Definition at line 637 of file Type.java.
 { return above_center() ? (TypeObj)e.dual() : e; }
oob() [6/6]
TypeStruct com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeStruct e) inherited
Definition at line 638 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob_deep()
Type com.cliffc.aa.type.Type< T extends Type< T >.oob_deep (Type< TypeInt > t) inherited
Definition at line 632 of file Type.java.
 { return oop_deep_impl(t); }
oop_deep_impl()
Type com.cliffc.aa.type.Type< T extends Type< T >.oop_deep_impl (Type< TypeInt > t) inherited
Definition at line 634 of file Type.java.
 { return oob(); }
rdual()
T com.cliffc.aa.type.Type< T extends Type< T >.rdual package inherited
Definition at line 366 of file Type.java.
 { assert _dual!=null; return _dual; }
remove_name()
final T com.cliffc.aa.type.Type< T extends Type< T >.remove_name inherited
Definition at line 556 of file Type.java.
 { return has_name() ? _set_name("") : (T)this; }
repeats_in_cycles()
TypeStruct com.cliffc.aa.type.Type< T extends Type< T >.repeats_in_cycles (TypeStruct head, VBitSet bs) package inherited
Definition at line 938 of file Type.java.
 { return null; }
retern()
final T com.cliffc.aa.type.Type< T extends Type< T >.retern package inherited
Definition at line 201 of file Type.java.
                     {
     assert _dual._dual == this;
     assert _hash != 0;
     assert INTERN.get(this)==null;
     INTERN.put(this,this);
     assert INTERN.get(this)==this;
     return (T)this;
   }
set_name()
final T com.cliffc.aa.type.Type< T extends Type< T >.set_name (String name) inherited
Definition at line 551 of file Type.java.
{
     assert check_name(name);
     return _set_name(name);
   }
sharptr()
Type com.cliffc.aa.type.Type< T extends Type< T >.sharptr (Type< TypeInt > ptr) inherited
Definition at line 930 of file Type.java.
 { return this==ANY ? TypeMem.ANYMEM.sharptr(ptr) : ptr; }
simple_ptr()
Type com.cliffc.aa.type.Type< T extends Type< T >.simple_ptr inherited
Definition at line 358 of file Type.java.
 { return this; }
str()
SB com.cliffc.aa.type.TypeInt.str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
Definition at line 23 of file TypeInt.java.
{
     sb.p(_name);
     if( _con != 0 ) return sb.p(_x<0 ? "&" : (_x>0 ? "+" : "")).p(_con);
     if( _x==0 ) return sb.p(_con);
     return sb.p(_x>0?"~":"").p(Math.abs(_x)==1?"n":"").p("int").p(_z);
   }
References com.cliffc.aa.type.TypeInt._con, com.cliffc.aa.type.Type< TypeInt >._name, com.cliffc.aa.type.TypeInt._x, com.cliffc.aa.type.TypeInt._z, and com.cliffc.aa.util.SB.p().
toString()
final String com.cliffc.aa.type.Type< T extends Type< T >.toString inherited
Definition at line 127 of file Type.java.
 { return str(new SB(),new VBitSet(),null,true).toString(); }
typerr()
RuntimeException com.cliffc.aa.type.Type< T extends Type< T >.typerr (Type< TypeInt > t) package inherited
Definition at line 947 of file Type.java.
{
     throw new RuntimeException("Should not reach here: internal type system error with "+this+(t==null?"":(" and "+t)));
   }
untern()
final T com.cliffc.aa.type.Type< T extends Type< T >.untern package inherited
Definition at line 193 of file Type.java.
                     {
     assert _hash != 0;
     assert INTERN.get(this)==this;
     Type rez = INTERN.remove(this);
     assert rez == this;
     return (T)this;
   }
walk()
void com.cliffc.aa.type.TypeInt.walk (Predicate< Type > p)
Definition at line 199 of file TypeInt.java.
 { p.test(this); }
widen()
Type com.cliffc.aa.type.TypeInt.widen ()
Definition at line 175 of file TypeInt.java.
{
     assert _x <= 0;
     return INT64;
   }
References com.cliffc.aa.type.TypeInt._x, and com.cliffc.aa.type.TypeInt.INT64.
xdual()
TypeInt com.cliffc.aa.type.TypeInt.xdual () protected
Definition at line 64 of file TypeInt.java.
 { return _x==0 ? this : new TypeInt().init(-_x,_z,_con); }
References com.cliffc.aa.type.TypeInt._con, com.cliffc.aa.type.TypeInt._x, com.cliffc.aa.type.TypeInt._z, and com.cliffc.aa.type.TypeInt.init().
xmeet()
Type com.cliffc.aa.type.TypeInt.xmeet (Type t) protected
Definition at line 65 of file TypeInt.java.
{
     assert t != this;
     switch( t._type ) {
     case TINT:   break;
     case TFLT:   return xmeetf((TypeFlt)t);
     case TFUNPTR:
     case TMEMPTR:
     case TRPC:   return cross_nil(t);
     case TFUNSIG:
     case TARY:
     case TLIVE:
     case TOBJ:
     case TSTR:
     case TSTRUCT:
     case TTUPLE:
     case TMEM:   return ALL;
     default: throw typerr(t);
     }
     TypeInt tt = (TypeInt)t;
     assert !equals(tt);         // Already covered by interning
     int maxz = Math.max(_z,tt._z);
     int minz = Math.min(_z,tt._z);
     if( _x== 0 && tt._x== 0 && _con==tt._con ) return make(0,maxz,_con);
     if( _x<= 0 && tt._x<= 0 ) return make(Math.min(nn(),tt.nn()),maxz,0); // Both bottom, widen size
     if( _x > 0 && tt._x > 0 ) return make(Math.min(  _x,tt._x  ),minz,0); // Both top, narrow size
     if( _x==-2 && tt._x== 2 ) return this; // Top loses to other guy
     if( _x== 2 && tt._x==-2 ) return tt  ; // Top loses to other guy
     // ttop==+1,+2 and that is 0,-1,-2
     TypeInt that = _x>0 ? tt : this;
     TypeInt ttop = _x>0 ? this : tt;
     if( that._x<0 ) return that; // Return low value
     if( log(that._con) <= ttop._z && (that._con!=0 || ttop._x==2) )
       return that;                    // Keep a fitting constant
     return make(that.nn(),that._z,0); // No longer a constant
   }
References com.cliffc.aa.type.TypeInt._con, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.type.TypeInt._x, com.cliffc.aa.type.TypeInt._z, com.cliffc.aa.type.Type< TypeInt >.ALL, com.cliffc.aa.type.Type< TypeInt >.cross_nil(), com.cliffc.aa.type.TypeInt.equals(), com.cliffc.aa.type.TypeInt.log(), com.cliffc.aa.type.TypeInt.make(), com.cliffc.aa.type.TypeInt.nn(), com.cliffc.aa.type.Type< TypeInt >.TARY, com.cliffc.aa.type.Type< TypeInt >.TFLT, com.cliffc.aa.type.Type< TypeInt >.TFUNPTR, com.cliffc.aa.type.Type< TypeInt >.TFUNSIG, com.cliffc.aa.type.Type< TypeInt >.TINT, com.cliffc.aa.type.Type< TypeInt >.TLIVE, com.cliffc.aa.type.Type< TypeInt >.TMEM, com.cliffc.aa.type.Type< TypeInt >.TMEMPTR, com.cliffc.aa.type.Type< TypeInt >.TOBJ, com.cliffc.aa.type.Type< TypeInt >.TRPC, com.cliffc.aa.type.Type< TypeInt >.TSTR, com.cliffc.aa.type.Type< TypeInt >.TSTRUCT, com.cliffc.aa.type.Type< TypeInt >.TTUPLE, com.cliffc.aa.type.Type< TypeInt >.typerr(), and com.cliffc.aa.type.TypeInt.xmeetf().
Referenced by com.cliffc.aa.type.TypeInt.xmeetf().
xmeetf()
Type com.cliffc.aa.type.TypeInt.xmeetf (TypeFlt tf) package
Definition at line 111 of file TypeInt.java.
{
     int tx = _x;
     if( tx > 0 ) {                // Top Int, size 1 to 64
       if( tf._x < 0 ) return tf; // (~Int | Flt) = Flt // choice includes 1 which is in all flts
       if( tf._x > 0 ) // ~Int | ~Flt = ~Int of some type; defaults to Int tossing all the non-integral Flt choices
         return make(Math.min(_x,tf._x),Math.min(tf._z>>1,_z),0); // Choices limited to smaller-ints (to fit in float of same range)
       // Float constant: cast "for free" to Int constant if possible, else fall to same as Flt-bottom
       long con = (long)tf._con;
       // Fits in the int choices, just keep float, but could return the int constant just as well
       if( con == tf._con && log(con) <= _z )  return tf;
       return TypeFlt.make(con==0 ? -2 : -1, tf._z,0);
     }
     if( tx == 0 ) {             // Constant int
       int lg = log(_con);
       if( tf._x< 0) {           // Bottom float/double
         // Wider of (ints-wider-by-1) and floats
         if( (lg<<1) <= tf._z ) return TypeFlt.make((_con!=0 && tf._x==-1) ? -1 : -2, tf._z,0); // Fits in a float
         return REAL;
       }
       if( tf._x== 0 ) {         // Int constant vs Float constant
         if( _con==tf._con ) return this; // Matching int constant wins
         if( ((long)tf._con) == tf._con ) // Float is a integer
           return xmeet(TypeInt.con((long)tf._con)); // Return as-if meeting 2 integers
         return TypeFlt.make(_con==0 || tf._con==0 ? -2 : -1,Math.max(TypeFlt.log(_con),tf._z),0);
       }
       // tf._x > 0 // Can a high float fall to the int constant?
       double dcon = tf._z==32 ? (float)_con : (double)_con;
       if( (long)dcon == _con && (_con!=0 || tf._x == 2) )
         return this;
       tx = _con==0 ? -2 : -1; // Fall from constant
     } // Fall into the bottom-int case
     // Bottom Int or constant did not fit, size 1 to 64
     if( tf._x > 0 ) return make(tx,_z,0); // ( Int | ~Flt) = Int, since can choose 1.0
     // Float constant: cast "for free" to Int if possible, else fall to same as Flt-bottom
     long icon = (long)tf._con;
     if( tf._x== 0 && icon == tf._con )
       return make(-2,Math.max(_z,log(icon)),0);
     if( (_z<<1) <= tf._z ) return TypeFlt.make(Math.min(tx,tf._x),tf._z,0);
     if( (_z<<1) <= 64 ) return TypeFlt.FLT64; // Fits in the float
     return must_nil() || tf.must_nil() ? REAL : NREAL;
   }
References com.cliffc.aa.type.TypeFlt._con, com.cliffc.aa.type.TypeInt._con, com.cliffc.aa.type.TypeInt._x, com.cliffc.aa.type.TypeFlt._x, com.cliffc.aa.type.TypeFlt._z, com.cliffc.aa.type.TypeInt._z, com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.type.TypeFlt.FLT64, com.cliffc.aa.type.TypeFlt.log(), com.cliffc.aa.type.TypeInt.log(), com.cliffc.aa.type.TypeFlt.make(), com.cliffc.aa.type.TypeInt.make(), com.cliffc.aa.type.TypeFlt.must_nil(), com.cliffc.aa.type.TypeInt.must_nil(), com.cliffc.aa.type.Type< TypeInt >.NREAL, com.cliffc.aa.type.Type< TypeInt >.REAL, and com.cliffc.aa.type.TypeInt.xmeet().
Referenced by com.cliffc.aa.type.TypeInt.xmeet().
xmt_name()
Type com.cliffc.aa.type.Type< T extends Type< T >.xmt_name (Type< TypeInt > t, Type< TypeInt > mt) private inherited
Definition at line 441 of file Type.java.
{
     String n = mtname(t,mt);    // Meet name strings
     // If the names are incompatible and the meet remained high then the
     // mismatched names force a drop.
     if( n.length() < _name.length() && n.length() < t._name.length() && mt.above_center() ) {
       if( mt.interned() ) // recursive type creation?
         mt = mt.dual();   // Force low
     }
     if( mt.is_simple() ) n=""; // No named simple types
     if( mt._type==TOBJ ) n=""; // OBJ splits into strings (arrays) and structs, which can keep their names
     // Inject the name
     if( !Util.eq(mt._name,n) )  // Fast path cutout
       mt = mt.set_name(n);
     return mt;
   }
Member Data Documentation
_con
long com.cliffc.aa.type.TypeInt._con private
Definition at line 12 of file TypeInt.java.
Referenced by com.cliffc.aa.type.TypeInt.compute_hash(), com.cliffc.aa.type.TypeInt.equals(), com.cliffc.aa.type.TypeInt.getd(), com.cliffc.aa.type.TypeInt.getl(), com.cliffc.aa.type.TypeInt.init(), com.cliffc.aa.type.TypeInt.may_nil(), com.cliffc.aa.type.TypeInt.meet_nil(), com.cliffc.aa.type.TypeInt.must_nil(), com.cliffc.aa.type.TypeInt.nn(), com.cliffc.aa.type.TypeInt.not_nil(), com.cliffc.aa.type.TypeInt.str(), com.cliffc.aa.type.TypeInt.xdual(), com.cliffc.aa.type.TypeInt.xmeet(), and com.cliffc.aa.type.TypeInt.xmeetf().
_dual
T com.cliffc.aa.type.Type< T extends Type< T >._dual package inherited
Definition at line 100 of file Type.java.
_hash
int com.cliffc.aa.type.Type< T extends Type< T >._hash inherited
Definition at line 97 of file Type.java.
_name
String com.cliffc.aa.type.Type< T extends Type< T >._name inherited
Definition at line 99 of file Type.java.
_type
byte com.cliffc.aa.type.Type< T extends Type< T >._type package inherited
Definition at line 98 of file Type.java.
_uid
int com.cliffc.aa.type.Type< T extends Type< T >._uid inherited
Definition at line 96 of file Type.java.
_x
byte com.cliffc.aa.type.TypeInt._x private
Definition at line 10 of file TypeInt.java.
Referenced by com.cliffc.aa.type.TypeInt.above_center(), com.cliffc.aa.type.TypeInt.compute_hash(), com.cliffc.aa.type.TypeInt.equals(), com.cliffc.aa.type.TypeInt.init(), com.cliffc.aa.type.TypeInt.is_con(), com.cliffc.aa.type.TypeInt.may_be_con(), com.cliffc.aa.type.TypeInt.may_nil(), com.cliffc.aa.type.TypeInt.meet_nil(), com.cliffc.aa.type.TypeInt.must_nil(), com.cliffc.aa.type.TypeInt.nn(), com.cliffc.aa.type.TypeInt.not_nil(), com.cliffc.aa.type.TypeInt.str(), com.cliffc.aa.type.TypeInt.widen(), com.cliffc.aa.type.TypeInt.xdual(), com.cliffc.aa.type.TypeInt.xmeet(), and com.cliffc.aa.type.TypeInt.xmeetf().
_z
byte com.cliffc.aa.type.TypeInt._z
Definition at line 11 of file TypeInt.java.
Referenced by com.cliffc.aa.type.TypeInt.compute_hash(), com.cliffc.aa.type.TypeInt.equals(), com.cliffc.aa.node.MemPrimNode.err(), com.cliffc.aa.type.TypeInt.init(), com.cliffc.aa.type.TypeInt.isBitShape(), com.cliffc.aa.type.TypeInt.maxsize(), com.cliffc.aa.type.TypeInt.meet_nil(), com.cliffc.aa.type.TypeInt.minsize(), com.cliffc.aa.type.TypeInt.not_nil(), com.cliffc.aa.type.TypeInt.str(), com.cliffc.aa.type.TypeInt.xdual(), com.cliffc.aa.type.TypeInt.xmeet(), and com.cliffc.aa.type.TypeInt.xmeetf().
ALL
final Type com.cliffc.aa.type.Type< T extends Type< T >.ALL static inherited
Definition at line 324 of file Type.java.
ALL_TYPES
Ary<Type> com.cliffc.aa.type.Type< T extends Type< T >.ALL_TYPES static private inherited
Definition at line 650 of file Type.java.
ANY
final Type com.cliffc.aa.type.Type< T extends Type< T >.ANY static inherited
Definition at line 325 of file Type.java.
BOOL
final TypeInt com.cliffc.aa.type.TypeInt.BOOL = make(-2, 1,0) static
Definition at line 43 of file TypeInt.java.
Referenced by com.cliffc.aa.HM.HM9.EQ.apply(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM.EQ.apply(), com.cliffc.aa.HM.HM9.IsEmpty.apply(), com.cliffc.aa.HM.HM.EQ0.apply(), com.cliffc.aa.HM.HM.IsEmpty.apply(), com.cliffc.aa.node.PrimNode.EQ_OOP.EQ_OOP(), com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM1.HM(), com.cliffc.aa.HM.HM5.hm(), com.cliffc.aa.HM.HM6.hm(), com.cliffc.aa.HM.HM7.hm(), com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM3.hm(), com.cliffc.aa.HM.HM2.hm(), com.cliffc.aa.type.TypeInt.init1(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.node.PrimNode.NE_OOP.NE_OOP(), com.cliffc.aa.node.PrimNode.Not.Not(), com.cliffc.aa.type.TypeInt.not_nil(), com.cliffc.aa.node.PrimNode.Prim2RelOpF64.Prim2RelOpF64(), com.cliffc.aa.node.PrimNode.Prim2RelOpI64.Prim2RelOpI64(), com.cliffc.aa.HM.HM9.PrimSyn.reset(), com.cliffc.aa.HM.HM.PrimSyn.reset(), com.cliffc.aa.HM.TestHM5.test19(), com.cliffc.aa.HM.TestHM4.test19(), com.cliffc.aa.HM.TestHM.test20(), com.cliffc.aa.HM.TestHM9.test20(), com.cliffc.aa.HM.TestHM.test23(), com.cliffc.aa.HM.TestHM9.test23(), com.cliffc.aa.HM.TestHM.test41(), com.cliffc.aa.HM.TestHM9.test41(), com.cliffc.aa.TestParse.testParse(), com.cliffc.aa.TestParse.testParse01(), com.cliffc.aa.TestParse.testParse02(), com.cliffc.aa.TestParse.testParse05(), com.cliffc.aa.TestParse.testParse13(), com.cliffc.aa.node.IfNode.value(), com.cliffc.aa.node.PrimNode.EQ_OOP.value(), com.cliffc.aa.node.PrimNode.NE_OOP.value(), com.cliffc.aa.node.PrimNode.Not.value(), com.cliffc.aa.node.PrimNode.RandI64.value(), and com.cliffc.aa.node.PrimNode.EQ_OOP.vs_nil().
CNT
int com.cliffc.aa.type.Type< T extends Type< T >.CNT static private inherited
Definition at line 95 of file Type.java.
CTRL
final Type com.cliffc.aa.type.Type< T extends Type< T >.CTRL static inherited
Definition at line 326 of file Type.java.
FALSE
final Type com.cliffc.aa.type.TypeInt.FALSE = make(0, 1,0) static
Definition at line 45 of file TypeInt.java.
Referenced by com.cliffc.aa.node.PrimNode.Prim2RelOpF64.apply(), com.cliffc.aa.node.PrimNode.Prim2RelOpI64.apply(), com.cliffc.aa.HM.HM9.If.apply(), com.cliffc.aa.HM.HM.If.apply(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM.EQ0.apply(), com.cliffc.aa.HM.HM9.If.hm(), com.cliffc.aa.HM.HM.If.hm(), com.cliffc.aa.type.TypeInt.not_nil(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.type.TestType.testNamesInts(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.TestParse.testParse00(), com.cliffc.aa.TestParse.testParse05(), com.cliffc.aa.node.IfNode.value(), com.cliffc.aa.node.PrimNode.EQ_OOP.value(), com.cliffc.aa.node.PrimNode.NE_OOP.value(), and com.cliffc.aa.node.PrimNode.RandI64.value().
INT16
final TypeInt com.cliffc.aa.type.TypeInt.INT16 = make(-2,16,0) static package
Definition at line 41 of file TypeInt.java.
Referenced by com.cliffc.aa.type.TypeInt.init1(), and com.cliffc.aa.type.TestType.testNamesInts().
INT32
final TypeInt com.cliffc.aa.type.TypeInt.INT32 = make(-2,32,0) static
Definition at line 40 of file TypeInt.java.
Referenced by com.cliffc.aa.type.TypeInt.init1(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), and com.cliffc.aa.type.TestType.testNameCycle().
INT64
final TypeInt com.cliffc.aa.type.TypeInt.INT64 = make(-2,64,0) static
Definition at line 39 of file TypeInt.java.
Referenced by com.cliffc.aa.node.NewAryNode.add_libs(), com.cliffc.aa.HM.HM.Mul.apply(), com.cliffc.aa.HM.HM9.Mul.apply(), com.cliffc.aa.HM.HM.Add.apply(), com.cliffc.aa.HM.HM9.Dec.apply(), com.cliffc.aa.HM.HM.Dec.apply(), com.cliffc.aa.type.Type< TypeFlt >.check_startup(), com.cliffc.aa.node.NewStrNode.ConvertI64Str.ConvertI64Str(), com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM1.HM(), com.cliffc.aa.HM.HM5.hm(), com.cliffc.aa.HM.HM6.hm(), com.cliffc.aa.HM.HM7.hm(), com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM3.hm(), com.cliffc.aa.HM.HM2.hm(), com.cliffc.aa.type.TypeInt.init1(), com.cliffc.aa.node.MemPrimNode.LValueLength.LValueLength(), com.cliffc.aa.node.FreshNode.no_tvar_structure(), com.cliffc.aa.node.PrimNode.Prim1OpI64.Prim1OpI64(), com.cliffc.aa.node.PrimNode.Prim2OpI64.Prim2OpI64(), com.cliffc.aa.node.PrimNode.RandI64.RandI64(), com.cliffc.aa.HM.HM9.PrimSyn.reset(), com.cliffc.aa.HM.HM.PrimSyn.reset(), com.cliffc.aa.type.TypeAry.str(), com.cliffc.aa.HM.TestHM.test04(), com.cliffc.aa.HM.TestHM9.test04(), com.cliffc.aa.HM.TestHM.test21(), com.cliffc.aa.HM.TestHM9.test21(), com.cliffc.aa.HM.TestHM.test22(), com.cliffc.aa.HM.TestHM9.test22(), com.cliffc.aa.HM.TestHM.test31(), com.cliffc.aa.HM.TestHM9.test31(), com.cliffc.aa.HM.TestHM.test51(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.node.TestNodeSmall.testMemoryArgs(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.type.TestType.testNameCycle(), com.cliffc.aa.TestParse.testParse03(), com.cliffc.aa.TestParse.testParse07(), com.cliffc.aa.TestParse.testParse08(), com.cliffc.aa.TestParse.testParse09(), com.cliffc.aa.TestParse.testParse13(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.type.TestApprox.testTSMeet(), com.cliffc.aa.type.TestType.testType(), com.cliffc.aa.Parse.type0(), com.cliffc.aa.node.MemPrimNode.LValueLength.value(), com.cliffc.aa.node.PrimNode.AndI64.value(), com.cliffc.aa.node.PrimNode.OrI64.value(), com.cliffc.aa.node.PrimNode.RandI64.value(), and com.cliffc.aa.type.TypeInt.widen().
INT8
final TypeInt com.cliffc.aa.type.TypeInt.INT8 = make(-2, 8,0) static
Definition at line 42 of file TypeInt.java.
Referenced by com.cliffc.aa.type.TypeInt.init1(), com.cliffc.aa.type.TestType.testNamesInts(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.TestParse.testParse01a(), com.cliffc.aa.TestParse.testParse04(), com.cliffc.aa.TestParse.testParse07(), com.cliffc.aa.TestParse.testParse09(), com.cliffc.aa.TestParse.testParse14(), and com.cliffc.aa.TestParse.testParse15().
INTERN
final ConcurrentHashMap<Type,Type> com.cliffc.aa.type.Type< T extends Type< T >.INTERN static private inherited
Definition at line 162 of file Type.java.
ISA_SCALAR
final byte [] com.cliffc.aa.type.Type< T extends Type< T >.ISA_SCALAR static private inherited
Definition at line 355 of file Type.java.
NIL
final Type com.cliffc.aa.type.Type< T extends Type< T >.NIL static inherited
Definition at line 332 of file Type.java.
NINT64
final TypeInt com.cliffc.aa.type.TypeInt.NINT64 = make(-1,64,0) static
Definition at line 48 of file TypeInt.java.
Referenced by com.cliffc.aa.node.TestNodeSmall.testMemoryArgs().
NINT8
final TypeInt com.cliffc.aa.type.TypeInt.NINT8 = make(-1, 8,0) static
Definition at line 47 of file TypeInt.java.
Referenced by com.cliffc.aa.HM.TestHM.test30(), com.cliffc.aa.HM.TestHM9.test30(), com.cliffc.aa.HM.TestHM.test48(), com.cliffc.aa.HM.TestHM9.test48(), com.cliffc.aa.HM.TestHM.test49(), com.cliffc.aa.HM.TestHM9.test49(), com.cliffc.aa.HM.TestHM.test50(), com.cliffc.aa.HM.TestHM9.test50(), com.cliffc.aa.type.TestApprox.testApprox1(), com.cliffc.aa.type.TestApprox.testApprox4(), com.cliffc.aa.TestParse.testParse(), com.cliffc.aa.TestParse.testParse01(), com.cliffc.aa.TestParse.testParse09(), and com.cliffc.aa.TestParse.testParse10().
NREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.NREAL static package inherited
Definition at line 336 of file Type.java.
NSCALR
final Type com.cliffc.aa.type.Type< T extends Type< T >.NSCALR static inherited
Definition at line 330 of file Type.java.
POOLS
final Pool [] com.cliffc.aa.type.Type< T extends Type< T >.POOLS static package inherited
Definition at line 281 of file Type.java.
REAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.REAL static inherited
Definition at line 334 of file Type.java.
RECURSIVE_MEET
int com.cliffc.aa.type.Type< T extends Type< T >.RECURSIVE_MEET static inherited
Definition at line 163 of file Type.java.
SCALAR
final Type com.cliffc.aa.type.Type< T extends Type< T >.SCALAR static inherited
Definition at line 328 of file Type.java.
SCALAR_PRIMS
Type [] com.cliffc.aa.type.Type< T extends Type< T >.SCALAR_PRIMS static private inherited
Definition at line 349 of file Type.java.
STRS
final String [] com.cliffc.aa.type.Type< T extends Type< T >.STRS static private inherited
Definition at line 262 of file Type.java.
TALL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TALL static package inherited
Definition at line 239 of file Type.java.
TANY
final byte com.cliffc.aa.type.Type< T extends Type< T >.TANY static package inherited
Definition at line 240 of file Type.java.
TARY
final byte com.cliffc.aa.type.Type< T extends Type< T >.TARY static package inherited
Definition at line 269 of file Type.java.
TCTRL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TCTRL static package inherited
Definition at line 241 of file Type.java.
TFLD
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFLD static package inherited
Definition at line 271 of file Type.java.
TFLT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFLT static package inherited
Definition at line 264 of file Type.java.
TFUNPTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFUNPTR static package inherited
Definition at line 274 of file Type.java.
TFUNSIG
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFUNSIG static package inherited
Definition at line 275 of file Type.java.
TINT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TINT static package inherited
Definition at line 263 of file Type.java.
TLAST
final byte com.cliffc.aa.type.Type< T extends Type< T >.TLAST static package inherited
Definition at line 277 of file Type.java.
TLIVE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TLIVE static package inherited
Definition at line 276 of file Type.java.
TMEM
final byte com.cliffc.aa.type.Type< T extends Type< T >.TMEM static package inherited
Definition at line 272 of file Type.java.
TMEMPTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TMEMPTR static package inherited
Definition at line 273 of file Type.java.
TNIL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNIL static package inherited
Definition at line 259 of file Type.java.
TNREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNREAL static package inherited
Definition at line 257 of file Type.java.
TNSCALR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNSCALR static package inherited
Definition at line 253 of file Type.java.
TOBJ
final byte com.cliffc.aa.type.Type< T extends Type< T >.TOBJ static package inherited
Definition at line 267 of file Type.java.
TREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TREAL static package inherited
Definition at line 255 of file Type.java.
TRPC
final byte com.cliffc.aa.type.Type< T extends Type< T >.TRPC static package inherited
Definition at line 265 of file Type.java.
TRUE
final TypeInt com.cliffc.aa.type.TypeInt.TRUE = make(0, 1,1) static
Definition at line 44 of file TypeInt.java.
Referenced by com.cliffc.aa.node.PrimNode.Prim2RelOpF64.apply(), com.cliffc.aa.node.PrimNode.Prim2RelOpI64.apply(), com.cliffc.aa.HM.HM9.EQ.apply(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM.EQ.apply(), com.cliffc.aa.HM.HM.EQ0.apply(), com.cliffc.aa.type.TestType.testNamesInts(), com.cliffc.aa.TestParse.testParse00(), com.cliffc.aa.TestParse.testParse01(), com.cliffc.aa.TestParse.testParse03(), com.cliffc.aa.TestParse.testParse04(), com.cliffc.aa.TestParse.testParse05(), com.cliffc.aa.TestParse.testParse06(), com.cliffc.aa.TestParse.testParse09(), com.cliffc.aa.type.TestType.testStructTuple(), com.cliffc.aa.node.PrimNode.EQ_OOP.value(), com.cliffc.aa.node.PrimNode.NE_OOP.value(), and com.cliffc.aa.node.PrimNode.Not.value().
TSCALAR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSCALAR static package inherited
Definition at line 246 of file Type.java.
TSIMPLE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSIMPLE static package inherited
Definition at line 261 of file Type.java.
TSTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSTR static package inherited
Definition at line 270 of file Type.java.
TSTRUCT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSTRUCT static package inherited
Definition at line 268 of file Type.java.
TTUPLE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TTUPLE static package inherited
Definition at line 266 of file Type.java.
TXCTRL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXCTRL static package inherited
Definition at line 242 of file Type.java.
TXNIL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNIL static package inherited
Definition at line 260 of file Type.java.
TXNREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNREAL static package inherited
Definition at line 258 of file Type.java.
TXNSCALR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNSCALR static package inherited
Definition at line 254 of file Type.java.
TXREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXREAL static package inherited
Definition at line 256 of file Type.java.
TXSCALAR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXSCALAR static package inherited
Definition at line 247 of file Type.java.
TYPES
final TypeInt [] com.cliffc.aa.type.TypeInt.TYPES = new TypeInt[]{INT64,INT32,INT16,BOOL,TRUE,NINT64} static package
Definition at line 50 of file TypeInt.java.
XCTRL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XCTRL static inherited
Definition at line 327 of file Type.java.
XINT1
final TypeInt com.cliffc.aa.type.TypeInt.XINT1 = make(2, 1,0) static
Definition at line 46 of file TypeInt.java.
Referenced by com.cliffc.aa.node.IfNode.value().
XNIL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNIL static inherited
Definition at line 333 of file Type.java.
XNREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNREAL static private inherited
Definition at line 337 of file Type.java.
XNSCALR
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNSCALR static inherited
Definition at line 331 of file Type.java.
XREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XREAL static private inherited
Definition at line 335 of file Type.java.
XSCALAR
final Type com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR static inherited
Definition at line 329 of file Type.java.
ZERO
final TypeInt com.cliffc.aa.type.TypeInt.ZERO = new TypeInt().init(0,1,0).hashcons_free() static
Definition at line 49 of file TypeInt.java.
Referenced by com.cliffc.aa.HM.HM.Mul.apply(), com.cliffc.aa.HM.HM9.Mul.apply(), com.cliffc.aa.node.MemPrimNode.LValueRead.value(), com.cliffc.aa.node.MemPrimNode.LValueWrite.value(), com.cliffc.aa.node.MemPrimNode.LValueWriteFinal.value(), and com.cliffc.aa.node.PrimNode.Not.value().
The documentation for this class was generated from the following file:
TypeInt.java