aa: com.cliffc.aa.HM.HM3.Con Class Reference
com.cliffc.aa.HM.HM3.Con Class Reference
Public Member Functions
String toString ()
Protected Member Functions
final void add_work (Worklist work)
Package Functions
Con (Type t)
final void add_neighbors (Worklist work)
final boolean all_kids_ready ()
boolean check_progress (Worklist work)
void get_ids (VStack vstk, Worklist work)
HMType hm (Worklist work)
boolean progress ()
Package Attributes
HMType _hm
Syntax[] _kids
Syntax _par
final Type _t
Detailed Description
Definition at line 156 of file HM3.java.
Constructor & Destructor Documentation
Con()
com.cliffc.aa.HM.HM3.Con.Con (Type t) package
Definition at line 158 of file HM3.java.
 { _t=t; }
References com.cliffc.aa.HM.HM3.Con._t.
Member Function Documentation
add_neighbors()
final void com.cliffc.aa.HM.HM3.Syntax.add_neighbors (Worklist work) package inherited
Definition at line 128 of file HM3.java.
{
       if( _par!=null ) _par.add_work(work);
       if( _kids!=null )
         for( Syntax kid : _kids )
           kid.add_work(work);
     }
References com.cliffc.aa.HM.HM3.Syntax._kids, com.cliffc.aa.HM.HM3.Syntax._par, and com.cliffc.aa.HM.HM3.Syntax.add_work().
Referenced by com.cliffc.aa.HM.HM3.hm().
add_work()
final void com.cliffc.aa.HM.HM3.Syntax.add_work (Worklist work) protected inherited
Definition at line 126 of file HM3.java.
 {  if( all_kids_ready() ) work.push(this);  }
References com.cliffc.aa.HM.HM3.Syntax.all_kids_ready(), and com.cliffc.aa.HM.HM3.Worklist.push().
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.HM.HM3.Con.get_ids(), and com.cliffc.aa.HM.HM3.Ident.get_ids().
all_kids_ready()
final boolean com.cliffc.aa.HM.HM3.Syntax.all_kids_ready () package inherited
Definition at line 135 of file HM3.java.
{
       if( _kids==null ) return true;
       for( Syntax kid : _kids ) if( kid._hm==null ) return false;
       return true;
     }
References com.cliffc.aa.HM.HM3.Syntax._kids.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_work(), and com.cliffc.aa.HM.HM3.Syntax.check_progress().
check_progress()
boolean com.cliffc.aa.HM.HM3.Syntax.check_progress (Worklist work) package inherited
Definition at line 144 of file HM3.java.
{
       if( all_kids_ready() ) // If kids are not ready, then cannot compute hm() so not on worklist
         if( _hm==null || progress() ) // Progress is possible
           if( !work.has(this) )       // Not on worklist?
             return false;             // Fails check
       if( _kids!=null )               // For all kids
         for( Syntax kid : _kids )
           if( !kid.check_progress(work) ) // Recursively check nodes that can make progress on worklist
             return false;
       return true;
     }
References com.cliffc.aa.HM.HM3.Syntax._hm, com.cliffc.aa.HM.HM3.Syntax._kids, com.cliffc.aa.HM.HM3.Syntax.all_kids_ready(), com.cliffc.aa.HM.HM3.Worklist.has(), and com.cliffc.aa.HM.HM3.Syntax.progress().
Referenced by com.cliffc.aa.HM.HM3.hm().
get_ids()
void com.cliffc.aa.HM.HM3.Con.get_ids (VStack vstk, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM3.Syntax.
Definition at line 162 of file HM3.java.
 { add_work(work); }
References com.cliffc.aa.HM.HM3.Syntax.add_work().
hm()
HMType com.cliffc.aa.HM.HM3.Con.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM3.Syntax.
Definition at line 160 of file HM3.java.
 { return _hm==null ? new HMVar(_t) : null; }
References com.cliffc.aa.HM.HM3.Syntax._hm, and com.cliffc.aa.HM.HM3.Con._t.
progress()
boolean com.cliffc.aa.HM.HM3.Con.progress () package
Reimplemented from com.cliffc.aa.HM.HM3.Syntax.
Definition at line 161 of file HM3.java.
 { return false; }
toString()
String com.cliffc.aa.HM.HM3.Con.toString ()
Definition at line 159 of file HM3.java.
 { return _t.toString(); }
References com.cliffc.aa.HM.HM3.Con._t, and com.cliffc.aa.type.Type< T extends Type< T >.toString().
Member Data Documentation
_hm
HMType com.cliffc.aa.HM.HM3.Syntax._hm package inherited
Definition at line 118 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Syntax.check_progress(), com.cliffc.aa.HM.HM3.hm(), com.cliffc.aa.HM.HM3.Con.hm(), com.cliffc.aa.HM.HM3.Ident.hm(), com.cliffc.aa.HM.HM3.Lambda.hm(), com.cliffc.aa.HM.HM3.Let.hm(), com.cliffc.aa.HM.HM3.Apply.hm(), com.cliffc.aa.HM.HM3.Lambda.progress(), com.cliffc.aa.HM.HM3.Let.progress(), and com.cliffc.aa.HM.HM3.Apply.progress().
_kids
Syntax [] com.cliffc.aa.HM.HM3.Syntax._kids package inherited
Definition at line 117 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.HM.HM3.Syntax.all_kids_ready(), com.cliffc.aa.HM.HM3.Apply.Apply(), com.cliffc.aa.HM.HM3.Apply.arg(), com.cliffc.aa.HM.HM3.Lambda.body(), com.cliffc.aa.HM.HM3.Let.body(), com.cliffc.aa.HM.HM3.Syntax.check_progress(), com.cliffc.aa.HM.HM3.Apply.fun(), com.cliffc.aa.HM.HM3.Lambda.Lambda(), com.cliffc.aa.HM.HM3.Let.Let(), and com.cliffc.aa.HM.HM3.Let.use().
_par
Syntax com.cliffc.aa.HM.HM3.Syntax._par package inherited
Definition at line 116 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.HM.HM3.Apply.Apply(), com.cliffc.aa.HM.HM3.Lambda.Lambda(), and com.cliffc.aa.HM.HM3.Let.Let().
_t
final Type com.cliffc.aa.HM.HM3.Con._t package
Definition at line 157 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Con.Con(), com.cliffc.aa.HM.HM3.Con.hm(), and com.cliffc.aa.HM.HM3.Con.toString().
The documentation for this class was generated from the following file:
HM3.java