aa: com.cliffc.aa.HM.HM8.Field Class Reference
com.cliffc.aa.HM.HM8.Field Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Field (String id, Syntax str)
void add_work (Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
T2 lookup (String name)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
T2 post ()
T2 pre ()
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
Package Attributes
final String _id
VStack _nongen
Syntax _par
T2 _post
T2 _pre
final Syntax _rec
T2 _t
Detailed Description
Definition at line 670 of file HM8.java.
Constructor & Destructor Documentation
Field()
com.cliffc.aa.HM.HM8.Field.Field (String id, Syntax str) package
Definition at line 673 of file HM8.java.
 { _id=id; _rec =str; }
References com.cliffc.aa.HM.HM8.Field._id, com.cliffc.aa.HM.HM8.Field._rec, com.cliffc.aa.HM.HM8.id(), and com.cliffc.aa.HM.HM8.Field.str().
Member Function Documentation
add_work()
void com.cliffc.aa.HM.HM8.Field.add_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 699 of file HM8.java.
{
       work.push(_par);
       work.push(_rec);
       _rec.add_work(work);
     }
References com.cliffc.aa.HM.HM8.Syntax._par, com.cliffc.aa.HM.HM8.Field._rec, com.cliffc.aa.HM.HM8.Syntax.add_work(), and com.cliffc.aa.HM.HM8.Worklist.push().
debug_find()
T2 com.cliffc.aa.HM.HM8.Syntax.debug_find () package inherited
Definition at line 249 of file HM8.java.
 { return _t.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM8.Syntax._t, and com.cliffc.aa.HM.HM8.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM8.hm().
find()
T2 com.cliffc.aa.HM.HM8.Syntax.find () package inherited
Definition at line 245 of file HM8.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._t, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.T2._occurs_in(), com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Ident.hm(), com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.HM.HM8.Apply.is_if_nil(), and com.cliffc.aa.HM.HM8.Struct.prep_tree().
hm()
boolean com.cliffc.aa.HM.HM8.Field.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 677 of file HM8.java.
{
       boolean progress = false;
       progress |= pre ().unify(_rec.pre (),work); // Pre -memory unifies with child pre
       progress |= post().unify(_rec.post(),work); // Post-memory unifies with child post
       if( work==null && progress ) return true;
       T2 rec = _rec.find();
       int idx = rec._ids==null ? -1 : Util.find(rec._ids,_id);
       if( idx==-1 ) {           // Not a struct or no field, force it to be one
         if( find().is_err() ) return false;
         if( work==null ) return true;
         if( rec.is_err() ) return find().unify(rec,work);
         progress |= T2.make_struct(new String[]{_id}, BitsAlias.RECORD_BITS.dual(),new T2[]{find().push_update(rec._deps)}).unify(rec, work);
       } else {
         // Unify the field
         progress |= rec.args(idx).unify(find(), work);
         if( find()._con==Type.ALL )
           progress |= T2.make_err("Missing field "+_id+" in "+rec.find()).unify(find(),work);
       }
       return progress;
     }
References com.cliffc.aa.HM.HM8.T2._con, com.cliffc.aa.HM.HM8.T2._deps, com.cliffc.aa.HM.HM8.Field._id, com.cliffc.aa.HM.HM8.T2._ids, com.cliffc.aa.HM.HM8.Field._rec, com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.type.Bits< B extends Bits< B >.dual(), com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM8.Syntax.find(), com.cliffc.aa.HM.HM8.T2.find(), com.cliffc.aa.HM.HM8.T2.is_err(), com.cliffc.aa.HM.HM8.T2.make_err(), com.cliffc.aa.HM.HM8.T2.make_struct(), com.cliffc.aa.HM.HM8.Syntax.post(), com.cliffc.aa.HM.HM8.Syntax.pre(), com.cliffc.aa.HM.HM8.T2.push_update(), com.cliffc.aa.type.BitsAlias.RECORD_BITS, and com.cliffc.aa.HM.HM8.T2.unify().
lookup()
T2 com.cliffc.aa.HM.HM8.Field.lookup (String name) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 698 of file HM8.java.
 { return _par==null ? null : _par.lookup(name); }
References com.cliffc.aa.HM.HM8.Syntax._par, and com.cliffc.aa.HM.HM8.Syntax.lookup().
more_work()
boolean com.cliffc.aa.HM.HM8.Field.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 709 of file HM8.java.
{
       if( !more_work_impl(work) ) return false;
       return _rec.more_work(work);
     }
References com.cliffc.aa.HM.HM8.Field._rec, com.cliffc.aa.HM.HM8.Syntax.more_work(), and com.cliffc.aa.HM.HM8.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM8.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 283 of file HM8.java.
{
       boolean no_more_work = work.has(this) || !hm(null); // Either on worklist, or no-progress
       return no_more_work;
     }
References com.cliffc.aa.HM.HM8.Worklist.has(), and com.cliffc.aa.HM.HM8.Syntax.hm().
Referenced by com.cliffc.aa.HM.HM8.Con.more_work(), com.cliffc.aa.HM.HM8.Ident.more_work(), com.cliffc.aa.HM.HM8.Lambda.more_work(), com.cliffc.aa.HM.HM8.Let.more_work(), com.cliffc.aa.HM.HM8.Apply.more_work(), com.cliffc.aa.HM.HM8.Struct.more_work(), and com.cliffc.aa.HM.HM8.Field.more_work().
p()
String com.cliffc.aa.HM.HM8.Syntax.p () inherited
Definition at line 291 of file HM8.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM8.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM8.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 292 of file HM8.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM8.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM8.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM8.Syntax.p1(), com.cliffc.aa.HM.HM8.Syntax.p2(), and com.cliffc.aa.HM.HM8.T2.str().
Referenced by com.cliffc.aa.HM.HM8.Syntax.p(), com.cliffc.aa.HM.HM8.Lambda.p2(), com.cliffc.aa.HM.HM8.Let.p2(), com.cliffc.aa.HM.HM8.Apply.p2(), com.cliffc.aa.HM.HM8.Struct.p2(), and com.cliffc.aa.HM.HM8.Field.p2().
p1()
SB com.cliffc.aa.HM.HM8.Field.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 675 of file HM8.java.
 { return sb.p(".").p(_id); }
References com.cliffc.aa.HM.HM8.Field._id, and com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM8.Field.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 676 of file HM8.java.
 { return _rec.p0(sb,dups); }
References com.cliffc.aa.HM.HM8.Field._rec, and com.cliffc.aa.HM.HM8.Syntax.p0().
post()
T2 com.cliffc.aa.HM.HM8.Syntax.post () package inherited
Definition at line 254 of file HM8.java.
               {
       T2 t = _post.find();
       return t==_post ? t : (_post=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._post, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), and com.cliffc.aa.HM.HM8.Field.hm().
pre()
T2 com.cliffc.aa.HM.HM8.Syntax.pre () package inherited
Definition at line 250 of file HM8.java.
              {
       T2 t = _pre.find();
       return t==_pre ? t : (_pre=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._pre, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), and com.cliffc.aa.HM.HM8.Field.hm().
prep_lookup_deps()
void com.cliffc.aa.HM.HM8.Field.prep_lookup_deps (Ident id) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 708 of file HM8.java.
 { }
prep_tree()
int com.cliffc.aa.HM.HM8.Field.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 704 of file HM8.java.
{
       prep_tree_impl(par, nongen, work, T2.make_leaf());
       return _rec.prep_tree(this,nongen,work)+1;
     }
References com.cliffc.aa.HM.HM8.Field._rec, com.cliffc.aa.HM.HM8.T2.make_leaf(), com.cliffc.aa.HM.HM8.Syntax.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
prep_tree_impl()
final void com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 267 of file HM8.java.
{
       _par=par;
       _pre = T2.make_mem();
       _t=t;
       _post = T2.make_mem();
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM8.Syntax._nongen, com.cliffc.aa.HM.HM8.Syntax._par, com.cliffc.aa.HM.HM8.Syntax._post, com.cliffc.aa.HM.HM8.Syntax._pre, com.cliffc.aa.HM.HM8.Syntax._t, com.cliffc.aa.HM.HM8.T2.make_mem(), and com.cliffc.aa.HM.HM8.Worklist.push().
Referenced by com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), com.cliffc.aa.HM.HM8.Lambda.prep_tree(), com.cliffc.aa.HM.HM8.Let.prep_tree(), com.cliffc.aa.HM.HM8.Apply.prep_tree(), com.cliffc.aa.HM.HM8.Struct.prep_tree(), and com.cliffc.aa.HM.HM8.Field.prep_tree().
str()
SB com.cliffc.aa.HM.HM8.Field.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 674 of file HM8.java.
 { return _rec.str(sb.p(".").p(_id).p(' ')); }
References com.cliffc.aa.HM.HM8.Field._id, com.cliffc.aa.HM.HM8.Field._rec, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM8.Syntax.str().
Referenced by com.cliffc.aa.HM.HM8.Field.Field().
toString()
final String com.cliffc.aa.HM.HM8.Syntax.toString () inherited
Definition at line 288 of file HM8.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM8.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_id
final String com.cliffc.aa.HM.HM8.Field._id package
Definition at line 671 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Field.Field(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.HM.HM8.Field.p1(), and com.cliffc.aa.HM.HM8.Field.str().
_nongen
VStack com.cliffc.aa.HM.HM8.Syntax._nongen package inherited
Definition at line 241 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Ident.hm(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM8.Syntax._par package inherited
Definition at line 240 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._occurs_in(), com.cliffc.aa.HM.HM8.Con.add_work(), com.cliffc.aa.HM.HM8.Ident.add_work(), com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Apply.add_work(), com.cliffc.aa.HM.HM8.Struct.add_work(), com.cliffc.aa.HM.HM8.Field.add_work(), com.cliffc.aa.HM.HM8.Ident.hm(), com.cliffc.aa.HM.HM8.Lambda.lookup(), com.cliffc.aa.HM.HM8.Let.lookup(), com.cliffc.aa.HM.HM8.Apply.lookup(), com.cliffc.aa.HM.HM8.Struct.lookup(), com.cliffc.aa.HM.HM8.Field.lookup(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_post
T2 com.cliffc.aa.HM.HM8.Syntax._post package inherited
Definition at line 244 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Syntax.post(), com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_pre
T2 com.cliffc.aa.HM.HM8.Syntax._pre package inherited
Definition at line 242 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Syntax.pre(), com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_rec
final Syntax com.cliffc.aa.HM.HM8.Field._rec package
Definition at line 672 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Field.add_work(), com.cliffc.aa.HM.HM8.Field.Field(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.HM.HM8.Field.more_work(), com.cliffc.aa.HM.HM8.Field.p2(), com.cliffc.aa.HM.HM8.Field.prep_tree(), and com.cliffc.aa.HM.HM8.Field.str().
_t
T2 com.cliffc.aa.HM.HM8.Syntax._t package inherited
Definition at line 243 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Syntax.debug_find(), com.cliffc.aa.HM.HM8.Syntax.find(), com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM8.Syntax.p0(), com.cliffc.aa.HM.HM8.Let.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM8.java