aa: com.cliffc.aa.HM.HM1.Syntax Class Reference
com.cliffc.aa.HM.HM1.Syntax Class Reference abstract
Package Functions
abstract HMType hm (HashMap< String, HMType > env, HashSet< HMVar > nongen)
Detailed Description
Definition at line 56 of file HM1.java.
Member Function Documentation
hm()
abstract HMType com.cliffc.aa.HM.HM1.Syntax.hm (HashMap< String, HMType > env, HashSet< HMVar > nongen) abstract package
Reimplemented in com.cliffc.aa.HM.HM1.Apply, com.cliffc.aa.HM.HM1.Let, com.cliffc.aa.HM.HM1.Lambda2, com.cliffc.aa.HM.HM1.Lambda, com.cliffc.aa.HM.HM1.Ident, and com.cliffc.aa.HM.HM1.Con.
Referenced by com.cliffc.aa.HM.HM1.HM(), com.cliffc.aa.HM.HM1.Lambda.hm(), com.cliffc.aa.HM.HM1.Lambda2.hm(), com.cliffc.aa.HM.HM1.Let.hm(), and com.cliffc.aa.HM.HM1.Apply.hm().
The documentation for this class was generated from the following file:
HM1.java