aa: com.cliffc.aa.HM.HM3.Oper Class Reference
com.cliffc.aa.HM.HM3.Oper Class Reference
Public Member Functions
SB _str (SB sb, VBitSet dups, boolean debug)
String str ()
final String toString ()
Package Functions
Oper (String name, HMType... args)
boolean _eq (HMType v, BitSetSparse dups)
HMType _fresh (VStack vstk, HashMap< HMVar, HMVar > vars, HashMap< Oper, Oper > opers)
final boolean eq (HMType v)
HMType find ()
HMType fresh (VStack vstk)
boolean is_top ()
boolean occurs_in (HMType[] args, VBitSet dups)
boolean occurs_in (VStack vstk, VBitSet dups)
boolean occurs_in_type (HMType v, VBitSet dups)
HMType union (HMType that, Worklist work)
Static Package Functions
static Oper fun (HMType... args)
static void reset ()
Package Attributes
final HMType[] _args
Ary< Ident > _ids
final String _name
HMType _u
final int _uid
Static Package Attributes
static final HashMap< HMVar, HMVar > EQS = new HashMap<>()
Static Private Attributes
static int CNT
Detailed Description
Definition at line 394 of file HM3.java.
Constructor & Destructor Documentation
Oper()
com.cliffc.aa.HM.HM3.Oper.Oper (String name, HMType... args) package
Definition at line 397 of file HM3.java.
 { _name=name; _args=args; }
References com.cliffc.aa.HM.HM3.Oper._args, and com.cliffc.aa.HM.HM3.Oper._name.
Referenced by com.cliffc.aa.HM.HM3.Oper._eq(), com.cliffc.aa.HM.HM3.Oper._fresh(), com.cliffc.aa.HM.HM3.Oper.fun(), and com.cliffc.aa.HM.HM3.Oper.union().
Member Function Documentation
_eq()
boolean com.cliffc.aa.HM.HM3.Oper._eq (HMType v, BitSetSparse dups) package
Reimplemented from com.cliffc.aa.HM.HM3.HMType.
Definition at line 432 of file HM3.java.
{
       assert is_top() && v.is_top();
       if( this==v ) return true;
       if( !(v instanceof Oper) ) return false;
       if( dups.tset(_uid,v._uid) )
         return true; // Checked already, something else has to be equal/unequal
       Oper o = (Oper)v;
       if( !_name.equals(o._name) ||
           _args.length!=o._args.length ) return false;
       for( int i=0; i<_args.length; i++ ) {
         HMType h0 =   _args[i];
         HMType h1 = o._args[i];
         if( !h0.is_top() )   _args[i] = h0 = h0.find();
         if( !h1.is_top() ) o._args[i] = h1 = h1.find();
         if( !h0._eq(h1,dups) )
           return false;
       }
       return true;
     }
References com.cliffc.aa.HM.HM3.Oper._args, com.cliffc.aa.HM.HM3.HMType._eq(), com.cliffc.aa.HM.HM3.Oper._name, com.cliffc.aa.HM.HM3.HMType._uid, com.cliffc.aa.HM.HM3.HMType.find(), com.cliffc.aa.HM.HM3.HMType.is_top(), com.cliffc.aa.HM.HM3.Oper.Oper(), and com.cliffc.aa.util.BitSetSparse.tset().
_fresh()
HMType com.cliffc.aa.HM.HM3.Oper._fresh (VStack vstk, HashMap< HMVar, HMVar > vars, HashMap< Oper, Oper > opers) package
Reimplemented from com.cliffc.aa.HM.HM3.HMType.
Definition at line 451 of file HM3.java.
{
       assert is_top();
       Oper op = opers.get(this);
       if( op!=null ) return op;
       HMType[] args = new HMType[_args.length];
       op = new Oper(_name,args);
       opers.put(this,op);       // Stop cyclic structure endless looping
       for( int i=0; i<_args.length; i++ )
         args[i] = _args[i].find()._fresh(vstk,vars,opers);
       return op;
     }
References com.cliffc.aa.HM.HM3.Oper._args, com.cliffc.aa.HM.HM3.HMType._fresh(), com.cliffc.aa.HM.HM3.Oper._name, com.cliffc.aa.HM.HM3.Oper.find(), com.cliffc.aa.HM.HM3.HMType.is_top(), and com.cliffc.aa.HM.HM3.Oper.Oper().
_str()
SB com.cliffc.aa.HM.HM3.Oper._str (SB sb, VBitSet dups, boolean debug)
Reimplemented from com.cliffc.aa.HM.HM3.HMType.
Definition at line 399 of file HM3.java.
{
       if( dups.tset(_uid) ) return sb.p("v").p(_uid).p("$");  // Stop infinite print loops
       if( _name.equals("->") ) {
         if( debug ) sb.p("v").p(_uid).p(":");
         sb.p("{ ");
         _args[0]._str(sb,dups,debug);
         sb.p(" -> ");
         _args[1]._str(sb,dups,debug);
         return sb.p(" }");
       }
       sb.p(_name);
       if( debug ) sb.p(_uid);
       sb.p('(');
       for( HMType t : _args )
         t._str(sb,dups,debug).p(',');
       return sb.unchar().p(')');
     }
References com.cliffc.aa.HM.HM3.Oper._args, com.cliffc.aa.HM.HM3.Oper._name, com.cliffc.aa.HM.HM3.HMType._str(), com.cliffc.aa.HM.HM3.HMType._uid, com.cliffc.aa.util.SB.p(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.util.SB.unchar().
eq()
final boolean com.cliffc.aa.HM.HM3.HMType.eq (HMType v) package inherited
Definition at line 291 of file HM3.java.
 { EQS.clear(); return find()._eq(v, new BitSetSparse()); }
References com.cliffc.aa.HM.HM3.HMType._eq(), com.cliffc.aa.HM.HM3.HMType.EQS, and com.cliffc.aa.HM.HM3.HMType.find().
Referenced by com.cliffc.aa.HM.HM3.Lambda.progress(), com.cliffc.aa.HM.HM3.Let.progress(), and com.cliffc.aa.HM.HM3.Apply.progress().
find()
HMType com.cliffc.aa.HM.HM3.Oper.find () package
Reimplemented from com.cliffc.aa.HM.HM3.HMType.
Definition at line 417 of file HM3.java.
 { return this; }
Referenced by com.cliffc.aa.HM.HM3.Oper._fresh().
fresh()
HMType com.cliffc.aa.HM.HM3.HMType.fresh (VStack vstk) package inherited
Definition at line 294 of file HM3.java.
{
       HashMap<HMVar,HMVar> vars = new HashMap<>();
       HashMap<Oper,Oper> opers = new HashMap<>();
       return find()._fresh(vstk,vars,opers);
     }
References com.cliffc.aa.HM.HM3.HMType._fresh(), and com.cliffc.aa.HM.HM3.HMType.find().
Referenced by com.cliffc.aa.HM.HM3.Ident.hm().
fun()
static Oper com.cliffc.aa.HM.HM3.Oper.fun (HMType... args) static package
Definition at line 398 of file HM3.java.
 { return new Oper("->",args); }
References com.cliffc.aa.HM.HM3.Oper.Oper().
Referenced by com.cliffc.aa.HM.HM3.hm(), com.cliffc.aa.HM.HM3.Lambda.hm(), and com.cliffc.aa.HM.HM3.Apply.hm().
is_top()
boolean com.cliffc.aa.HM.HM3.HMType.is_top () package inherited
Definition at line 289 of file HM3.java.
 { return _u==null; }
References com.cliffc.aa.HM.HM3.HMType._u.
Referenced by com.cliffc.aa.HM.HM3.Oper._eq(), com.cliffc.aa.HM.HM3.HMVar._fresh(), com.cliffc.aa.HM.HM3.Oper._fresh(), com.cliffc.aa.HM.HM3.HMType.occurs_in_type(), and com.cliffc.aa.HM.HM3.HMVar.type().
occurs_in() [1/2]
boolean com.cliffc.aa.HM.HM3.HMType.occurs_in (HMType[] args, VBitSet dups) package inherited
Definition at line 306 of file HM3.java.
{
       for( HMType x : args ) if( occurs_in_type(x,dups) ) return true;
       return false;
     }
References com.cliffc.aa.HM.HM3.HMType.occurs_in_type().
occurs_in() [2/2]
boolean com.cliffc.aa.HM.HM3.HMType.occurs_in (VStack vstk, VBitSet dups) package inherited
Definition at line 301 of file HM3.java.
{
       if( vstk==null ) return false;
       for( HMVar x : vstk ) if( occurs_in_type(x,dups) ) return true;
       return false;
     }
References com.cliffc.aa.HM.HM3.HMType.occurs_in_type().
Referenced by com.cliffc.aa.HM.HM3.HMVar._fresh(), and com.cliffc.aa.HM.HM3.HMType.occurs_in_type().
occurs_in_type()
boolean com.cliffc.aa.HM.HM3.HMType.occurs_in_type (HMType v, VBitSet dups) package inherited
Definition at line 310 of file HM3.java.
{
       assert is_top();
       if( dups.tset(v._uid) )
         return false;           // Been there, done that
       HMType y = v.find();      // Find top
       if( y==this )             // Occurs in type?
         return true;            // Yup, occurs in type right here
       if( y instanceof Oper )   // Structural recursive test
         return occurs_in(((Oper)y)._args,dups);
       return false;
     }
References com.cliffc.aa.HM.HM3.HMType._uid, com.cliffc.aa.HM.HM3.HMType.find(), com.cliffc.aa.HM.HM3.HMType.is_top(), com.cliffc.aa.HM.HM3.HMType.occurs_in(), and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.HM.HM3.HMType.occurs_in(), and com.cliffc.aa.HM.HM3.HMVar.union().
reset()
static void com.cliffc.aa.HM.HM3.HMType.reset () static package inherited
Definition at line 281 of file HM3.java.
 { CNT=1; }
References com.cliffc.aa.HM.HM3.HMType.CNT.
Referenced by com.cliffc.aa.HM.HM3.reset().
str()
String com.cliffc.aa.HM.HM3.HMType.str () inherited
Definition at line 287 of file HM3.java.
 { return _str(new SB(),new VBitSet(),false).toString(); }
References com.cliffc.aa.HM.HM3.HMType._str(), and com.cliffc.aa.util.SB.toString().
toString()
final String com.cliffc.aa.HM.HM3.HMType.toString () inherited
Definition at line 286 of file HM3.java.
 { return _str(new SB(),new VBitSet(),true).toString(); }
References com.cliffc.aa.HM.HM3.HMType._str(), and com.cliffc.aa.util.SB.toString().
union()
HMType com.cliffc.aa.HM.HM3.Oper.union (HMType that, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM3.HMType.
Definition at line 418 of file HM3.java.
{
       if( this==that ) return this;
       if( !(that instanceof Oper) ) return that.union(this,work);
       if( _uid < that._uid ) return that.union(this,work); // Minimize unique CNT values
       Oper op2 = (Oper)that;
       if( !_name.equals(op2._name) ||
           _args.length != op2._args.length )
         throw new RuntimeException("Cannot unify "+this+" and "+that);
       for( int i=0; i<_args.length; i++ )
         _args[i] = _args[i].union(op2._args[i],work); // Both union, and update U-F
       if(      _ids!=null ) { for( Ident id :      _ids ) id._hm=null;  work.addAll(     _ids); }
       if( that._ids!=null ) { for( Ident id : that._ids ) id._hm=null;  work.addAll(that._ids); }
       return that;
     }
References com.cliffc.aa.HM.HM3.Oper._args, com.cliffc.aa.HM.HM3.HMType._ids, com.cliffc.aa.HM.HM3.Oper._name, com.cliffc.aa.HM.HM3.HMType._uid, com.cliffc.aa.HM.HM3.Oper.Oper(), and com.cliffc.aa.HM.HM3.HMType.union().
Member Data Documentation
_args
final HMType [] com.cliffc.aa.HM.HM3.Oper._args package
Definition at line 396 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Oper._eq(), com.cliffc.aa.HM.HM3.Oper._fresh(), com.cliffc.aa.HM.HM3.Oper._str(), com.cliffc.aa.HM.HM3.Oper.Oper(), and com.cliffc.aa.HM.HM3.Oper.union().
_ids
Ary<Ident> com.cliffc.aa.HM.HM3.HMType._ids package inherited
Definition at line 283 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Ident.get_ids(), com.cliffc.aa.HM.HM3.HMVar.union(), and com.cliffc.aa.HM.HM3.Oper.union().
_name
final String com.cliffc.aa.HM.HM3.Oper._name package
Definition at line 395 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Oper._eq(), com.cliffc.aa.HM.HM3.Oper._fresh(), com.cliffc.aa.HM.HM3.Oper._str(), com.cliffc.aa.HM.HM3.Oper.Oper(), and com.cliffc.aa.HM.HM3.Oper.union().
_u
HMType com.cliffc.aa.HM.HM3.HMType._u package inherited
Definition at line 278 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.HMVar._eq(), com.cliffc.aa.HM.HM3.HMVar._str(), com.cliffc.aa.HM.HM3.HMVar.find(), com.cliffc.aa.HM.HM3.HMType.is_top(), and com.cliffc.aa.HM.HM3.HMVar.union().
_uid
final int com.cliffc.aa.HM.HM3.HMType._uid package inherited
Definition at line 279 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Oper._eq(), com.cliffc.aa.HM.HM3.HMVar._str(), com.cliffc.aa.HM.HM3.Oper._str(), com.cliffc.aa.HM.HM3.HMType.HMType(), com.cliffc.aa.HM.HM3.HMType.occurs_in_type(), com.cliffc.aa.HM.HM3.HMVar.union(), and com.cliffc.aa.HM.HM3.Oper.union().
CNT
int com.cliffc.aa.HM.HM3.HMType.CNT static private inherited
Definition at line 280 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.HMType.HMType(), and com.cliffc.aa.HM.HM3.HMType.reset().
EQS
final HashMap<HMVar,HMVar> com.cliffc.aa.HM.HM3.HMType.EQS = new HashMap<>() static package inherited
Definition at line 290 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.HMVar._eq(), and com.cliffc.aa.HM.HM3.HMType.eq().
The documentation for this class was generated from the following file:
HM3.java