aa: com.cliffc.aa.type.TypeFunSig Class Reference
com.cliffc.aa.type.TypeFunSig Class Reference
Public Member Functions
boolean above (Type t)
boolean above_center ()
Type arg (int idx)
final boolean contains (Type t)
boolean cycle_equals (Type o)
Type display ()
final T dual ()
boolean equals (Object o)
double getd ()
long getl ()
String getstr ()
boolean has_name ()
final int hashCode ()
Type high ()
boolean is_con ()
boolean is_display_ptr ()
boolean is_forward_ref ()
boolean isa (Type t)
final boolean isa_scalar ()
byte isBitShape (Type t)
Type join (Type t)
Type make_from (Type head, TypeMem map, VBitSet visit)
TypeFunSig make_from_arg (int idx, Type arg)
boolean may_be_con ()
boolean may_nil ()
final Type meet (Type t)
Type meet_loop (Type t2)
Type meet_nil (Type nil)
boolean must_nil ()
int nargs ()
Type oob ()
Type oob (Type e)
TypeMem oob (TypeMem e)
TypeMemPtr oob (TypeMemPtr e)
TypeObj oob (TypeObj e)
TypeStruct oob (TypeStruct e)
Type oob_deep (Type t)
Type oop_deep_impl (Type t)
final T remove_name ()
final T set_name (String name)
Type sharptr (Type ptr)
Type simple_ptr ()
SB str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
final String toString ()
void walk (Predicate< Type > p)
Type widen ()
Static Public Member Functions
static Ary< Type > ALL_TYPES ()
static boolean eq (Type[] t0, Type[] t1)
static void init0 (HashMap< String, Type > types)
static boolean intern_check ()
static TypeFunSig make (String[] args, TypeTuple formals, TypeTuple ret)
static TypeFunSig make (TypeTuple ret, Type[] ts)
static TypeFunSig make (TypeTuple ret, TypeMemPtr disp, Type arg1)
static TypeFunSig make (TypeTuple ret, TypeMemPtr disp, Type arg1, Type arg2)
static TypeFunSig make (TypeTuple ret, TypeTuple formals)
Public Attributes
String[] _args
TypeTuple _formals
int _hash
String _name
TypeTuple _ret
int _uid
Static Public Attributes
static final Type ALL
static final Type ANY
static final Type CTRL
static final String[] func_names = new String[]{" ctl", " mem", "^" , "arg3", "arg4", "arg5" }
static final TypeFunSig II_I = make(TypeTuple.make_ret(TypeInt.INT64),TypeTuple.INT64_INT64)
static final Type NIL
static final Type NSCALR
static final Type REAL
static int RECURSIVE_MEET
static final Type SCALAR
static final Type XCTRL
static final Type XNIL
static final Type XNSCALR
static final Type XSCALAR
Protected Member Functions
Type clone ()
T init (byte type, String name)
TypeFunSig xdual ()
Type xmeet (Type t)
Package Functions
int compute_hash ()
boolean contains (Type t, VBitSet bs)
final Type cross_nil (Type t)
final T hashcons_free ()
boolean intern_check1 ()
Type intern_lookup ()
boolean interned ()
boolean is_display ()
final String mtname (Type t, Type mt)
Type not_nil ()
T rdual ()
TypeStruct repeats_in_cycles (TypeStruct head, VBitSet bs)
final T retern ()
RuntimeException typerr (Type t)
final T untern ()
Static Package Functions
[static initializer]
static boolean check_name (String n)
static boolean check_startup ()
static void concat (Ary< Type > ts, Type[] ts1)
static Type intern_find (int uid)
static int intern_size ()
static Type make (byte type)
Package Attributes
T _dual
byte _type
Static Package Attributes
static final Type NREAL
static final Pool[] POOLS
static final byte TALL
static final byte TANY
static final byte TARY
static final byte TCTRL
static final byte TFLD
static final byte TFLT
static final byte TFUNPTR
static final byte TFUNSIG
static final byte TINT
static final byte TLAST
static final byte TLIVE
static final byte TMEM
static final byte TMEMPTR
static final byte TNIL
static final byte TNREAL
static final byte TNSCALR
static final byte TOBJ
static final byte TREAL
static final byte TRPC
static final byte TSCALAR
static final byte TSIMPLE
static final byte TSTR
static final byte TSTRUCT
static final byte TTUPLE
static final byte TXCTRL
static final byte TXNIL
static final byte TXNREAL
static final byte TXNSCALR
static final byte TXREAL
static final byte TXSCALAR
static final TypeFunSig[] TYPES = new TypeFunSig[]{II_I}
Private Member Functions
T _set_name (String name)
int _uid ()
boolean check_commute (Type t, Type mt)
boolean check_symmetric (Type t, Type mt)
T hashcons ()
TypeFunSig init (String[] args, TypeTuple formals, TypeTuple ret)
boolean intern_check0 (Type v)
boolean is_num ()
boolean is_ptr ()
boolean is_simple ()
Type xmt_name (Type t, Type mt)
Static Private Attributes
static Ary< Type > ALL_TYPES
static int CNT
static final ConcurrentHashMap< Type, Type > INTERN
static final byte[] ISA_SCALAR
static Type[] SCALAR_PRIMS
static final String[] STRS
static final Type XNREAL
static final Type XREAL
Detailed Description
Definition at line 10 of file TypeFunSig.java.
Member Function Documentation
[static initializer]()
com.cliffc.aa.type.TypeFunSig.[static initializer] static package
_set_name()
T com.cliffc.aa.type.Type< T extends Type< T >._set_name (String name) private inherited
Definition at line 558 of file Type.java.
{
     POOLS[_type]._clone++;
     T t1 = (T)clone();
     t1._name = name;
     return t1.hashcons_free();
   }
_uid()
int com.cliffc.aa.type.Type< T extends Type< T >._uid private inherited
Definition at line 103 of file Type.java.
 { return CNT++; }
above()
boolean com.cliffc.aa.type.Type< T extends Type< T >.above (Type< TypeFunSig > t) inherited
Definition at line 625 of file Type.java.
 { return t != this && meet(t)==t; }
above_center()
boolean com.cliffc.aa.type.TypeFunSig.above_center ()
Definition at line 115 of file TypeFunSig.java.
 { return _formals.above_center(); }
References com.cliffc.aa.type.TypeFunSig._formals, and com.cliffc.aa.type.TypeTuple.above_center().
Referenced by com.cliffc.aa.type.TypeFunSig.may_be_con().
ALL_TYPES()
static Ary<Type> com.cliffc.aa.type.Type< T extends Type< T >.ALL_TYPES static inherited
Definition at line 651 of file Type.java.
{
     if( ALL_TYPES != null ) return ALL_TYPES;
     Ary<Type> ts = new Ary<>(new Type[1],0);
     concat(ts,Type      .TYPES);
     concat(ts,TypeFlt   .TYPES);
     concat(ts,TypeFunPtr.TYPES);
     concat(ts,TypeFunSig.TYPES);
     concat(ts,TypeInt   .TYPES);
     concat(ts,TypeLive  .TYPES);
     concat(ts,TypeMem   .TYPES);
     concat(ts,TypeMemPtr.TYPES);
     concat(ts,TypeObj   .TYPES);
     concat(ts,TypeRPC   .TYPES);
     concat(ts,TypeStr   .TYPES);
     concat(ts,TypeStruct.TYPES);
     concat(ts,TypeTuple .TYPES);
     concat(ts,TypeAry   .TYPES);
     // Partial order Sort, makes for easier tests later.  Arrays.sort requires
     // a total order (i.e., the obvious Comparator breaks the sort contract),
     // so we hand-roll a simple bubble sort.
     for( int i=0; i<ts._len; i++ )
       for( int j=i+1; j<ts._len; j++ )
         if( ts._es[j].isa(ts._es[i]) ) { Type tmp = ts._es[i]; ts._es[i] = ts._es[j]; ts._es[j] = tmp; }
     return (ALL_TYPES = ts); // Preserve for tests
   }
arg()
Type com.cliffc.aa.type.TypeFunSig.arg (int idx)
Definition at line 88 of file TypeFunSig.java.
 { return _formals._ts[idx]; }
References com.cliffc.aa.type.TypeFunSig._formals, and com.cliffc.aa.type.TypeTuple._ts.
Referenced by com.cliffc.aa.node.PrimNode.ConvertTypeName.apply(), com.cliffc.aa.node.MemPrimNode.ReadPrimNode.as_fun(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.as_fun(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun(), com.cliffc.aa.type.TypeFunSig.display(), com.cliffc.aa.node.PrimNode.err(), com.cliffc.aa.node.PrimNode.ConvertTypeName.err(), com.cliffc.aa.node.FunNode.formal(), com.cliffc.aa.type.TypeFunSig.make_from_arg(), com.cliffc.aa.type.TypeFunSig.str(), and com.cliffc.aa.node.PrimNode.value().
check_commute()
boolean com.cliffc.aa.type.Type< T extends Type< T >.check_commute (Type< TypeFunSig > t, Type< TypeFunSig > mt) private inherited
Definition at line 593 of file Type.java.
{
     if( t==this ) return true;
     if( is_simple() && !t.is_simple() ) return true; // By design, flipped the only allowed order
     Type mt2 = t.xmeet(this);   // Reverse args and try again
     // Also reverse names.
     Type nmt2 = t.xmt_name(this,mt2);
     if( mt==nmt2 ) return true;
     System.out.println("Meet not commutative: "+this+".meet("+t+")="+mt+",\n but "+t+".meet("+this+")="+nmt2);
     return false;
   }
check_name()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.check_name (String n) static package inherited
Definition at line 548 of file Type.java.
 { return n.isEmpty() || n.charAt(n.length()-1)==':'; }
check_startup()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.check_startup static package inherited
Definition at line 684 of file Type.java.
{
     Type[] ts = ALL_TYPES().asAry();
     // Confirm commutative & complete
     for( Type t0 : ts )
       for( Type t1 : ts ) {
         Type mt = t0.meet(t1);
         assert t0.check_commute  (t1,mt);
         assert t0.check_symmetric(t1,mt);
       }
     // Confirm associative
     int errs=0;
     for( Type t0 : ts )
       for( Type t1 : ts )
         for( Type t2 : ts ) {
           Type t01   = t0 .meet(t1 );
           Type t12   = t1 .meet(t2 );
           Type t01_2 = t01.meet(t2 );
           Type t0_12 = t0 .meet(t12);
           if( t01_2 != t0_12 && errs++ < 10 )
             System.err.println("("+t0+"&"+t1+") & "+t2+" == "+t0+" & ("+t1+" & "+t2+"); "+
                                "("+t01      +") & "+t2+" == "+t0+" & ("+t12        +"); "+
                                t01_2                  +" == "+t0_12);
         }
     assert errs==0 : "Found "+errs+" associative errors";
     // Confirm symmetry.  If A isa B, then A.join(C) isa B.join(C)
     for( Type t0 : ts )
       for( Type t1 : ts ) {
         if( t0.isa(t1) ) {
           for( Type t2 : ts ) {
             Type t02 = t0.join(t2);
             Type t12 = t1.join(t2);
             Type mt  = t02.meet(t12);
             if( mt != t12 && errs++ < 10 ) {
               System.err.println("("+t0+" ^ "+t2+") = "+t02+"; "+
                                  "("+t1+" ^ "+t2+") = "+t12+"; "+
                                  "their meet = "+mt+" which is not "+t12);
             }
           }
         }
       }
     assert errs==0 : "Found "+errs+" non-join-type errors";
     // Check scalar primitives; all are SCALARS and none sub-type each other.
     SCALAR_PRIMS = new Type[] { TypeInt.INT64, TypeFlt.FLT64, TypeMemPtr.OOP0, TypeFunPtr.GENERIC_FUNPTR, TypeRPC.ALL_CALL };
     for( Type t : SCALAR_PRIMS ) assert t.isa(SCALAR);
     for( int i=0; i<SCALAR_PRIMS.length; i++ )
       for( int j=i+1; j<SCALAR_PRIMS.length; j++ )
         assert !SCALAR_PRIMS[i].isa(SCALAR_PRIMS[j]);
     return true;
   }
check_symmetric()
boolean com.cliffc.aa.type.Type< T extends Type< T >.check_symmetric (Type< TypeFunSig > t, Type< TypeFunSig > mt) private inherited
Definition at line 608 of file Type.java.
{
     if( t==this ) return true;
     Type ta = mt._dual.meet(t._dual);
     Type tb = mt._dual.meet(  _dual);
     if( ta==t._dual && tb==_dual ) return true;
     System.err.print("("+this+" & "+t+")=="+mt+" but \n("+mt._dual+" & ");
     if( ta!=t._dual ) System.err.println(t._dual+")=="+ta+" \nwhich is not "+t._dual);
     else              System.err.println(  _dual+")=="+tb+" \nwhich is not "+  _dual);
     return false;
   }
clone()
Type com.cliffc.aa.type.Type< T extends Type< T >.clone protected inherited
Definition at line 304 of file Type.java.
{
     try {
       POOLS[_type]._clone++;
       Type t = (Type)super.clone();
       t._uid = _uid();
       t._dual = null;
       t._hash = 0;
       if( t instanceof TypeStruct )
         ((TypeStruct)t)._cyclic = false;
       return t;
     }
     catch( CloneNotSupportedException cns ) { throw new RuntimeException(cns); }
   }
compute_hash()
int com.cliffc.aa.type.TypeFunSig.compute_hash () package
Definition at line 30 of file TypeFunSig.java.
{
     assert _formals._hash != 0;
     int hash=TFUNSIG + _formals._hash + _ret._hash;
     for( int i=0; i<_args.length; i++ ) i+=_args[i].hashCode();
     return hash==0 ? 3 : hash;
   }
References com.cliffc.aa.type.TypeFunSig._args, com.cliffc.aa.type.TypeFunSig._formals, com.cliffc.aa.type.Type< T extends Type< T >._hash, com.cliffc.aa.type.TypeFunSig._ret, com.cliffc.aa.type.Type< TypeFunSig >.hashCode(), and com.cliffc.aa.type.Type< TypeFunSig >.TFUNSIG.
concat()
static void com.cliffc.aa.type.Type< T extends Type< T >.concat (Ary< Type< TypeFunSig > > ts, Type< TypeFunSig >[] ts1) static package inherited
Definition at line 676 of file Type.java.
{
     for( Type t1 : ts1 ) {
       assert !t1.above_center(); // Always below-center or equal, because we'll dual anyways
       ts.push(t1);
       if( t1!=t1.dual() ) ts.push(t1.dual());
     }
   }
contains() [1/2]
final boolean com.cliffc.aa.type.Type< T extends Type< T >.contains (Type< TypeFunSig > t) inherited
Definition at line 926 of file Type.java.
 { return contains(t,null); }
contains() [2/2]
boolean com.cliffc.aa.type.Type< T extends Type< T >.contains (Type< TypeFunSig > t, VBitSet bs) package inherited
Definition at line 927 of file Type.java.
 { return this==t; }
cross_nil()
final Type com.cliffc.aa.type.Type< T extends Type< T >.cross_nil (Type< TypeFunSig > t) package inherited
Definition at line 865 of file Type.java.
 { return must_nil() || t.must_nil() ? SCALAR : NSCALR; }
cycle_equals()
boolean com.cliffc.aa.type.TypeFunSig.cycle_equals (Type o)
Definition at line 48 of file TypeFunSig.java.
 { return equals(o); }
References com.cliffc.aa.type.TypeFunSig.equals().
display()
Type com.cliffc.aa.type.TypeFunSig.display ()
Definition at line 89 of file TypeFunSig.java.
 { return arg(DSP_IDX); }
References com.cliffc.aa.type.TypeFunSig.arg().
Referenced by com.cliffc.aa.node.FunNode.find_type_split().
dual()
final T com.cliffc.aa.type.Type< T extends Type< T >.dual inherited
Definition at line 361 of file Type.java.
 { return _dual; }
eq()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.eq (Type< TypeFunSig >[] t0, Type< TypeFunSig >[] t1) static inherited
Definition at line 136 of file Type.java.
{
     if( t0==t1 ) return true;
     if( t0==null || t1==null ) return false;
     if( t0.length != t1.length ) return false;
     for( int i=0; i<t0.length; i++ )
       if( t0[i] != t1[i] )
         return false;
     return true;
   }
equals()
boolean com.cliffc.aa.type.TypeFunSig.equals (Object o)
Definition at line 37 of file TypeFunSig.java.
{
     if( this==o ) return true;
     if( !(o instanceof TypeFunSig) ) return false;
     TypeFunSig tf = (TypeFunSig)o;
     if( _formals!=tf._formals || _ret!=tf._ret || _args.length!=tf._args.length ) return false;
     if( _args == tf._args ) return true;
     for( int i=0; i<_args.length; i++ )
       if( !Util.eq(_args[i],tf._args[i]) )
         return false;
     return true;
   }
References com.cliffc.aa.type.TypeFunSig._args, com.cliffc.aa.type.TypeFunSig._formals, com.cliffc.aa.type.TypeFunSig._ret, and com.cliffc.aa.util.Util.eq().
Referenced by com.cliffc.aa.type.TypeFunSig.cycle_equals().
getd()
double com.cliffc.aa.type.Type< T extends Type< T >.getd inherited
Definition at line 804 of file Type.java.
 { if( _type==TNIL || _type==TXNIL ) return 0.0; throw typerr(null); }
getl()
long com.cliffc.aa.type.Type< T extends Type< T >.getl inherited
Definition at line 802 of file Type.java.
 { if( _type==TNIL || _type==TXNIL ) return 0; throw typerr(null); }
getstr()
String com.cliffc.aa.type.Type< T extends Type< T >.getstr inherited
Definition at line 806 of file Type.java.
 { throw typerr(null); }
has_name()
boolean com.cliffc.aa.type.Type< T extends Type< T >.has_name inherited
Definition at line 549 of file Type.java.
 { return !_name.isEmpty(); }
hashCode()
final int com.cliffc.aa.type.Type< T extends Type< T >.hashCode inherited
Definition at line 106 of file Type.java.
 { assert _hash!=0; return _hash; }
hashcons()
T com.cliffc.aa.type.Type< T extends Type< T >.hashcons private inherited
Definition at line 165 of file Type.java.
{
     _hash = compute_hash();     // Set hash
     T t2 = (T)INTERN.get(this); // Lookup
     if( t2!=null ) {            // Found prior
       assert t2._dual != null;  // Prior is complete with dual
       assert this != t2;        // Do not hashcons twice, should not get self back
       return t2;                // Return prior
     }
     if( RECURSIVE_MEET > 0 )    // Mid-building recursive types; do not intern
       return (T)this;
     // Not in type table
     _dual = null;                // No dual yet
     INTERN.put(this,this);       // Put in table without dual
     T d = xdual();               // Compute dual without requiring table lookup, and not setting name
     d._name = _name;             // xdual does not set name either
     d._hash = d.compute_hash();  // Set dual hash
     _dual = d;
     if( this==d ) return d;      // Self-symmetric?  Dual is self
     assert !equals(d);           // Self-symmetric is handled by caller
     assert d._dual==null;        // Else dual-dual not computed yet
     assert INTERN.get(d)==null;
     d._dual = (T)this;
     INTERN.put(d,d);
     return (T)this;
   }
hashcons_free()
final T com.cliffc.aa.type.Type< T extends Type< T >.hashcons_free package inherited
Definition at line 153 of file Type.java.
{
     T t2 = hashcons();
     return this==t2 ? t2 : (T)POOLS[_type].free(this,t2);
   }
high()
Type com.cliffc.aa.type.Type< T extends Type< T >.high inherited
Definition at line 796 of file Type.java.
 { return above_center() ? this : dual(); }
init() [1/2]
T com.cliffc.aa.type.Type< T extends Type< T >.init (byte type, String name) protected inherited
Definition at line 105 of file Type.java.
 { _type=type; _name=name; return (T)this; }
init() [2/2]
TypeFunSig com.cliffc.aa.type.TypeFunSig.init (String[] args, TypeTuple formals, TypeTuple ret) private
Definition at line 18 of file TypeFunSig.java.
{
     super.init(TFUNSIG,"");
     assert args.length>=formals.len();
     assert (args[CTL_IDX]==null || Util.eq(args[CTL_IDX]," ctl")) && (formals.at(CTL_IDX)==Type.CTRL || formals.at(CTL_IDX)==Type.XCTRL);
     assert (args[MEM_IDX]==null || Util.eq(args[MEM_IDX]," mem")) && (formals.at(MEM_IDX) instanceof TypeMem || formals.at(MEM_IDX)==Type.ALL || formals.at(MEM_IDX)==Type.ANY);
     assert (args[DSP_IDX]==null || Util.eq(args[DSP_IDX],"^"   )) &&  formals.at(DSP_IDX).is_display_ptr();
     assert ret.len()==3 && ret.at(MEM_IDX) instanceof TypeMem;
     _args=args;
     _formals=formals;
     _ret=ret;
     return this;
   }
References com.cliffc.aa.type.TypeFunSig._args, com.cliffc.aa.type.TypeFunSig._formals, com.cliffc.aa.type.TypeFunSig._ret, com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.type.TypeTuple.at(), com.cliffc.aa.type.Type< T extends Type< T >.CTRL, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.type.TypeFunSig.init(), com.cliffc.aa.type.Type< T extends Type< T >.is_display_ptr(), com.cliffc.aa.type.TypeTuple.len(), com.cliffc.aa.type.Type< TypeFunSig >.TFUNSIG, and com.cliffc.aa.type.Type< T extends Type< T >.XCTRL.
Referenced by com.cliffc.aa.type.TypeFunSig.init(), com.cliffc.aa.type.TypeFunSig.make(), and com.cliffc.aa.type.TypeFunSig.xdual().
init0()
static void com.cliffc.aa.type.Type< T extends Type< T >.init0 (HashMap< String, Type< TypeFunSig > > types) static inherited
Definition at line 642 of file Type.java.
{
     types.put("real",REAL);
     types.put("scalar",SCALAR);
     TypeInt.init1(types);
     TypeFlt.init1(types);
     TypeStr.init1(types);
   }
intern_check()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check static inherited
Definition at line 212 of file Type.java.
{
     int errs=0;
     for( Type k : INTERN.keySet() ) {
       Type v = INTERN.get(k);
       if( !k.intern_check0(v) ) {
         System.out.println("INTERN_CHECK FAIL: "+k._uid+":"+k+" vs "+v._uid+":"+v);
         errs++;
       }
     }
     return errs==0;
   }
intern_check0()
boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check0 (Type< TypeFunSig > v) private inherited
Definition at line 223 of file Type.java.
{
     if( this != v || _dual==null || _dual._dual!=this || compute_hash()!=_hash ) return false;
     return intern_check1();
   }
intern_check1()
boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check1 package inherited
Definition at line 227 of file Type.java.
 { return true; }
intern_find()
static Type com.cliffc.aa.type.Type< T extends Type< T >.intern_find (int uid) static package inherited
Definition at line 229 of file Type.java.
{
     for( Type k : INTERN.keySet() )
       if( k._uid==uid )
         return k;
     return null;
   }
intern_lookup()
Type com.cliffc.aa.type.Type< T extends Type< T >.intern_lookup package inherited
Definition at line 210 of file Type.java.
 { return INTERN.get(this); }
intern_size()
static int com.cliffc.aa.type.Type< T extends Type< T >.intern_size static package inherited
Definition at line 211 of file Type.java.
 { return INTERN.size(); }
interned()
boolean com.cliffc.aa.type.Type< T extends Type< T >.interned package inherited
Definition at line 209 of file Type.java.
 { return INTERN.get(this)==this; }
is_con()
boolean com.cliffc.aa.type.TypeFunSig.is_con ()
Definition at line 117 of file TypeFunSig.java.
 { return false; }
is_display()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_display package inherited
Definition at line 942 of file Type.java.
 { return false; }
is_display_ptr()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_display_ptr inherited
Definition at line 941 of file Type.java.
 { return _type==TSCALAR || _type==TXSCALAR || _type==TNIL || _type==TXNIL || _type==TANY || _type==TALL; }
is_forward_ref()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_forward_ref inherited
Definition at line 799 of file Type.java.
 { return false; }
is_num()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_num private inherited
Definition at line 353 of file Type.java.
 { byte t = _type;  return t == TREAL || t == TXREAL || t == TNREAL || t == TXNREAL || t == TINT || t == TFLT; }
is_ptr()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_ptr private inherited
Definition at line 352 of file Type.java.
 { byte t = _type;  return t == TFUNPTR || t == TMEMPTR; }
is_simple()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_simple private inherited
Definition at line 351 of file Type.java.
 { return _type < TSIMPLE; }
isa()
boolean com.cliffc.aa.type.Type< T extends Type< T >.isa (Type< TypeFunSig > t) inherited
Definition at line 623 of file Type.java.
 { return meet(t)==t; }
isa_scalar()
final boolean com.cliffc.aa.type.Type< T extends Type< T >.isa_scalar inherited
Definition at line 356 of file Type.java.
 { assert ISA_SCALAR.length==TLAST; return ISA_SCALAR[_type]!=0; }
isBitShape()
byte com.cliffc.aa.type.TypeFunSig.isBitShape (Type t)
Definition at line 122 of file TypeFunSig.java.
 { return 99; }
join()
Type com.cliffc.aa.type.Type< T extends Type< T >.join (Type< TypeFunSig > t) inherited
Definition at line 619 of file Type.java.
 { return dual().meet(t.dual()).dual(); }
make() [1/6]
static Type com.cliffc.aa.type.Type< T extends Type< T >.make (byte type) static package inherited
Definition at line 147 of file Type.java.
{
     Pool P = POOLS[type];
     Type t1 = P.malloc();
     return t1.init(type,"").hashcons_free();
   }
make() [2/6]
static TypeFunSig com.cliffc.aa.type.TypeFunSig.make (String[] args, TypeTuple formals, TypeTuple ret) static
Definition at line 71 of file TypeFunSig.java.
{
     TypeFunSig t1 = POOLS[TFUNSIG].malloc();
     return t1.init(args,formals,ret).hashcons_free();
   }
References com.cliffc.aa.type.Type< T extends Type< T >.hashcons_free(), com.cliffc.aa.type.TypeFunSig.init(), com.cliffc.aa.type.Type< TypeFunSig >.POOLS, and com.cliffc.aa.type.Type< TypeFunSig >.TFUNSIG.
Referenced by com.cliffc.aa.HM.HM9.Root.add_sig(), com.cliffc.aa.HM.HM.Root.add_sig(), com.cliffc.aa.node.IntrinsicNode.convertTypeName(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.node.FunNode.FunNode(), com.cliffc.aa.type.TypeFunSig.make_from_arg(), com.cliffc.aa.node.FunNode.make_new_fun(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.NewPrimNode(), com.cliffc.aa.node.PrimNode.PrimNode(), com.cliffc.aa.node.TestNodeSmall.testMemoryArgs(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.HM.TestHM.tfs(), com.cliffc.aa.HM.TestHM9.tfs(), com.cliffc.aa.Parse.type0(), and com.cliffc.aa.type.TypeFunSig.xmeet().
make() [3/6]
static TypeFunSig com.cliffc.aa.type.TypeFunSig.make (TypeTuple ret, Type[] ts) static
Definition at line 76 of file TypeFunSig.java.
 { return make(func_names,TypeTuple.make_args(ts),ret); }
References com.cliffc.aa.type.TypeFunSig.func_names, com.cliffc.aa.type.TypeFunSig.make(), and com.cliffc.aa.type.TypeTuple.make_args().
Referenced by com.cliffc.aa.type.TypeFunSig.make().
make() [4/6]
static TypeFunSig com.cliffc.aa.type.TypeFunSig.make (TypeTuple ret, TypeMemPtr disp, Type arg1) static
Definition at line 77 of file TypeFunSig.java.
 { return make(ret,Types.ts(disp,arg1)); }
References com.cliffc.aa.type.TypeFunSig.make(), and com.cliffc.aa.type.Types.ts().
Referenced by com.cliffc.aa.type.TypeFunSig.make().
make() [5/6]
static TypeFunSig com.cliffc.aa.type.TypeFunSig.make (TypeTuple ret, TypeMemPtr disp, Type arg1, Type arg2) static
Definition at line 78 of file TypeFunSig.java.
 { return make(ret,Types.ts(disp,arg1,arg2)); }
References com.cliffc.aa.type.TypeFunSig.make(), and com.cliffc.aa.type.Types.ts().
Referenced by com.cliffc.aa.type.TypeFunSig.make().
make() [6/6]
static TypeFunSig com.cliffc.aa.type.TypeFunSig.make (TypeTuple ret, TypeTuple formals) static
Definition at line 79 of file TypeFunSig.java.
 { return make(func_names,formals,ret); }
References com.cliffc.aa.type.TypeFunSig.func_names, and com.cliffc.aa.type.TypeFunSig.make().
Referenced by com.cliffc.aa.type.TypeFunSig.make().
make_from()
Type com.cliffc.aa.type.Type< T extends Type< T >.make_from (Type< TypeFunSig > head, TypeMem map, VBitSet visit) inherited
Definition at line 945 of file Type.java.
 { return this; }
make_from_arg()
TypeFunSig com.cliffc.aa.type.TypeFunSig.make_from_arg (int idx, Type arg)
Definition at line 80 of file TypeFunSig.java.
 { return make(_args,_formals.make_from_arg(idx,arg),_ret); }
References com.cliffc.aa.type.TypeFunSig._args, com.cliffc.aa.type.TypeFunSig._formals, com.cliffc.aa.type.TypeFunSig._ret, com.cliffc.aa.type.TypeFunSig.arg(), com.cliffc.aa.type.TypeFunSig.make(), and com.cliffc.aa.type.TypeTuple.make_from_arg().
Referenced by com.cliffc.aa.node.FunNode.ideal_reduce().
may_be_con()
boolean com.cliffc.aa.type.TypeFunSig.may_be_con ()
Definition at line 116 of file TypeFunSig.java.
 { return above_center(); }
References com.cliffc.aa.type.TypeFunSig.above_center().
may_nil()
boolean com.cliffc.aa.type.TypeFunSig.may_nil ()
Definition at line 119 of file TypeFunSig.java.
 { return false; }
meet()
final Type com.cliffc.aa.type.Type< T extends Type< T >.meet (Type< TypeFunSig > t) inherited
Definition at line 412 of file Type.java.
{
     // Short cut for the self case
     if( t == this ) return this;
     // Short-cut for seeing this meet before
     Type mt = Key.get(this,t);
     if( mt != null ) return mt;
     // "Triangulate" the matrix and cut in half the number of cases.
     // Reverse; xmeet 2nd arg is never "is_simple" and never equal to "this".
     // This meet ignores the _name field, and can return any-old name it wants.
     mt = !is_simple() && t.is_simple() ? t.xmeet(this) : xmeet(t);
     // Meet the names.  Subclasses basically ignore the names as they have
     // their own complicated meets to perform, so we meet them here for all.
     Type nmt = xmt_name(t,mt);
     // Quick check on NIL: if either argument is NIL the result is allowed to
     // be NIL...  but nobody in the lattice can make a NIL from whole cloth, or
     // we get the crossing-nil bug.
     assert (nmt != NIL && nmt!=XNIL) || this==NIL || this==XNIL || t==NIL || t==XNIL;
     // Record this meet, to short-cut next time
     if( RECURSIVE_MEET == 0 )   // Only not mid-building recursive types;
       Key.put(this,t,nmt);
     return nmt;
   }
meet_loop()
Type com.cliffc.aa.type.Type< T extends Type< T >.meet_loop (Type< TypeFunSig > t2) inherited
Definition at line 628 of file Type.java.
 { return meet(t2); }
meet_nil()
Type com.cliffc.aa.type.TypeFunSig.meet_nil (Type nil)
Definition at line 121 of file TypeFunSig.java.
 { return Type.SCALAR; }
References com.cliffc.aa.type.Type< T extends Type< T >.SCALAR.
mtname()
final String com.cliffc.aa.type.Type< T extends Type< T >.mtname (Type< TypeFunSig > t, Type< TypeFunSig > mt) package inherited
Definition at line 567 of file Type.java.
{
     Type   t0 = this,  t1 = t;
     String s0 = t0._name, s1 = t1._name;
     assert check_name(s0) && check_name(s1);
     if( Util.eq(s0,s1) ) return s0;
     // Sort by name length
     if( s0.length() > s1.length() ) { t1=this; t0=t; s0=t0._name; s1=t1._name; }
     int x = 0, i;  char c;    // Last colon separator index
     // Find split point
     for( i = 0; i < s0.length(); i++ ) {
       if( (c=s0.charAt(i)) != s1.charAt(i) )
         break;
       if( c==':' ) x=i;
     }
     // If s0 is a prefix of s1, and s0 is high then it can cover s1.
     if( i==s0.length() && t0.above_center() && (!t1.above_center() || mt.above_center()) )
       return s1;
     // Keep the common prefix, which might be all of s0
     String s2 = i==s0.length() ? s0 : s0.substring(0, x).intern();
     assert check_name(s2);
     return s2;
   }
must_nil()
boolean com.cliffc.aa.type.TypeFunSig.must_nil ()
Definition at line 118 of file TypeFunSig.java.
 { return false; }
nargs()
int com.cliffc.aa.type.TypeFunSig.nargs ()
Definition at line 87 of file TypeFunSig.java.
 { return _formals._ts.length; }
References com.cliffc.aa.type.TypeFunSig._formals, and com.cliffc.aa.type.TypeTuple._ts.
Referenced by com.cliffc.aa.node.MemPrimNode.ReadPrimNode.as_fun(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.as_fun(), com.cliffc.aa.node.PrimNode.as_fun(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.FunNode.nargs(), com.cliffc.aa.type.TypeFunSig.str(), and com.cliffc.aa.node.TestNode.test1monotonic_prim().
not_nil()
Type com.cliffc.aa.type.TypeFunSig.not_nil () package
Definition at line 120 of file TypeFunSig.java.
 { return this; }
oob() [1/6]
Type com.cliffc.aa.type.Type< T extends Type< T >.oob inherited
Definition at line 635 of file Type.java.
 { return oob(ALL); }
oob() [2/6]
Type com.cliffc.aa.type.Type< T extends Type< T >.oob (Type< TypeFunSig > e) inherited
Definition at line 636 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [3/6]
TypeMem com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeMem e) inherited
Definition at line 639 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [4/6]
TypeMemPtr com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeMemPtr e) inherited
Definition at line 640 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [5/6]
TypeObj com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeObj e) inherited
Definition at line 637 of file Type.java.
 { return above_center() ? (TypeObj)e.dual() : e; }
oob() [6/6]
TypeStruct com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeStruct e) inherited
Definition at line 638 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob_deep()
Type com.cliffc.aa.type.Type< T extends Type< T >.oob_deep (Type< TypeFunSig > t) inherited
Definition at line 632 of file Type.java.
 { return oop_deep_impl(t); }
oop_deep_impl()
Type com.cliffc.aa.type.Type< T extends Type< T >.oop_deep_impl (Type< TypeFunSig > t) inherited
Definition at line 634 of file Type.java.
 { return oob(); }
rdual()
T com.cliffc.aa.type.Type< T extends Type< T >.rdual package inherited
Definition at line 366 of file Type.java.
 { assert _dual!=null; return _dual; }
remove_name()
final T com.cliffc.aa.type.Type< T extends Type< T >.remove_name inherited
Definition at line 556 of file Type.java.
 { return has_name() ? _set_name("") : (T)this; }
repeats_in_cycles()
TypeStruct com.cliffc.aa.type.Type< T extends Type< T >.repeats_in_cycles (TypeStruct head, VBitSet bs) package inherited
Definition at line 938 of file Type.java.
 { return null; }
retern()
final T com.cliffc.aa.type.Type< T extends Type< T >.retern package inherited
Definition at line 201 of file Type.java.
                     {
     assert _dual._dual == this;
     assert _hash != 0;
     assert INTERN.get(this)==null;
     INTERN.put(this,this);
     assert INTERN.get(this)==this;
     return (T)this;
   }
set_name()
final T com.cliffc.aa.type.Type< T extends Type< T >.set_name (String name) inherited
Definition at line 551 of file Type.java.
{
     assert check_name(name);
     return _set_name(name);
   }
sharptr()
Type com.cliffc.aa.type.Type< T extends Type< T >.sharptr (Type< TypeFunSig > ptr) inherited
Definition at line 930 of file Type.java.
 { return this==ANY ? TypeMem.ANYMEM.sharptr(ptr) : ptr; }
simple_ptr()
Type com.cliffc.aa.type.Type< T extends Type< T >.simple_ptr inherited
Definition at line 358 of file Type.java.
 { return this; }
str()
SB com.cliffc.aa.type.TypeFunSig.str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
Definition at line 50 of file TypeFunSig.java.
{
     if( debug ) sb.p('_').p(_uid);
     sb.p(_name);
     sb.p('{');
     boolean field_sep=false;
     for( int i=0; i<nargs(); i++ ) {
       if( !debug && i==CTL_IDX && Util.eq(_args[CTL_IDX]," ctl") ) continue; // Do not print the Control
       if( !debug && i==MEM_IDX && Util.eq(_args[MEM_IDX]," mem") ) continue; // Do not print the memory
       if( !debug && i==DSP_IDX && Util.eq(_args[DSP_IDX],"^"   ) ) continue; // Do not print the ever-present display
       sb.p(_args[i]);
       if( arg(i) != Type.SCALAR )
         arg(i).str(sb.p(':'),dups,mem,debug);
       sb.p(" ");  field_sep=true;
     }
     if( field_sep ) sb.unchar();
     sb.p(" -> ");
     if( _ret != Type.SCALAR ) _ret.str(sb,dups,mem,debug);
     return sb.p('}');
   }
References com.cliffc.aa.type.TypeFunSig._args, com.cliffc.aa.type.Type< TypeFunSig >._name, com.cliffc.aa.type.TypeFunSig._ret, com.cliffc.aa.type.Type< TypeFunSig >._uid, com.cliffc.aa.type.TypeFunSig.arg(), com.cliffc.aa.util.Util.eq(), com.cliffc.aa.type.TypeFunSig.nargs(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, com.cliffc.aa.type.TypeTuple.str(), com.cliffc.aa.type.Type< T extends Type< T >.str(), and com.cliffc.aa.util.SB.unchar().
Referenced by com.cliffc.aa.node.FunNode.str().
toString()
final String com.cliffc.aa.type.Type< T extends Type< T >.toString inherited
Definition at line 127 of file Type.java.
 { return str(new SB(),new VBitSet(),null,true).toString(); }
typerr()
RuntimeException com.cliffc.aa.type.Type< T extends Type< T >.typerr (Type< TypeFunSig > t) package inherited
Definition at line 947 of file Type.java.
{
     throw new RuntimeException("Should not reach here: internal type system error with "+this+(t==null?"":(" and "+t)));
   }
untern()
final T com.cliffc.aa.type.Type< T extends Type< T >.untern package inherited
Definition at line 193 of file Type.java.
                     {
     assert _hash != 0;
     assert INTERN.get(this)==this;
     Type rez = INTERN.remove(this);
     assert rez == this;
     return (T)this;
   }
walk()
void com.cliffc.aa.type.Type< T extends Type< T >.walk (Predicate< Type< TypeFunSig > > p) inherited
Definition at line 936 of file Type.java.
 { assert is_simple(); p.test(this); }
widen()
Type com.cliffc.aa.type.Type< T extends Type< T >.widen inherited
Definition at line 828 of file Type.java.
                       {
     switch( _type ) {
     case TREAL:   case TXREAL:
     case TSCALAR: case TXSCALAR:
     case TNSCALR: case TXNSCALR:
     case TNIL:    case TXNIL:
       return SCALAR;
     case TANY : case TALL  :
       return this;
     case TCTRL: case TXCTRL:
       return Type.CTRL;
     default: throw typerr(null); // Overridden in subclass
     }
   }
xdual()
TypeFunSig com.cliffc.aa.type.TypeFunSig.xdual () protected
Definition at line 91 of file TypeFunSig.java.
 { return new TypeFunSig().init(_args,_formals.dual(),_ret.dual()); }
References com.cliffc.aa.type.TypeFunSig._args, com.cliffc.aa.type.TypeFunSig._formals, com.cliffc.aa.type.TypeFunSig._ret, com.cliffc.aa.type.Type< T extends Type< T >.dual(), and com.cliffc.aa.type.TypeFunSig.init().
xmeet()
Type com.cliffc.aa.type.TypeFunSig.xmeet (Type t) protected
Definition at line 92 of file TypeFunSig.java.
{
     switch( t._type ) {
     case TFUNSIG: break;
     case TFUNPTR:
       return ALL;               // Not supposed to mix TypeFunPtr and TypeFunSig
     case TARY:
     case TFLT:
     case TINT:
     case TLIVE:
     case TMEM:
     case TMEMPTR:
     case TOBJ:
     case TRPC:
     case TSTR:
     case TSTRUCT:
     case TTUPLE:
       return ALL;
     default: throw typerr(t);   // All else should not happen
     }
     TypeFunSig tf = (TypeFunSig)t;
     return make((TypeTuple)_ret.meet(tf._ret),(TypeTuple)_formals.meet(tf._formals));
   }
References com.cliffc.aa.type.TypeFunSig._formals, com.cliffc.aa.type.TypeFunSig._ret, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.type.Type< TypeFunSig >.ALL, com.cliffc.aa.type.TypeFunSig.make(), com.cliffc.aa.type.Type< T extends Type< T >.meet(), com.cliffc.aa.type.Type< TypeFunSig >.TARY, com.cliffc.aa.type.Type< TypeFunSig >.TFLT, com.cliffc.aa.type.Type< TypeFunSig >.TFUNPTR, com.cliffc.aa.type.Type< TypeFunSig >.TFUNSIG, com.cliffc.aa.type.Type< TypeFunSig >.TINT, com.cliffc.aa.type.Type< TypeFunSig >.TLIVE, com.cliffc.aa.type.Type< TypeFunSig >.TMEM, com.cliffc.aa.type.Type< TypeFunSig >.TMEMPTR, com.cliffc.aa.type.Type< TypeFunSig >.TOBJ, com.cliffc.aa.type.Type< TypeFunSig >.TRPC, com.cliffc.aa.type.Type< TypeFunSig >.TSTR, com.cliffc.aa.type.Type< TypeFunSig >.TSTRUCT, com.cliffc.aa.type.Type< TypeFunSig >.TTUPLE, and com.cliffc.aa.type.Type< TypeFunSig >.typerr().
xmt_name()
Type com.cliffc.aa.type.Type< T extends Type< T >.xmt_name (Type< TypeFunSig > t, Type< TypeFunSig > mt) private inherited
Definition at line 441 of file Type.java.
{
     String n = mtname(t,mt);    // Meet name strings
     // If the names are incompatible and the meet remained high then the
     // mismatched names force a drop.
     if( n.length() < _name.length() && n.length() < t._name.length() && mt.above_center() ) {
       if( mt.interned() ) // recursive type creation?
         mt = mt.dual();   // Force low
     }
     if( mt.is_simple() ) n=""; // No named simple types
     if( mt._type==TOBJ ) n=""; // OBJ splits into strings (arrays) and structs, which can keep their names
     // Inject the name
     if( !Util.eq(mt._name,n) )  // Fast path cutout
       mt = mt.set_name(n);
     return mt;
   }
Member Data Documentation
_args
String [] com.cliffc.aa.type.TypeFunSig._args
Definition at line 14 of file TypeFunSig.java.
Referenced by com.cliffc.aa.node.MemPrimNode.ReadPrimNode.as_fun(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.as_fun(), com.cliffc.aa.node.PrimNode.as_fun(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun(), com.cliffc.aa.type.TypeFunSig.compute_hash(), com.cliffc.aa.type.TypeFunSig.equals(), com.cliffc.aa.type.TypeFunSig.init(), com.cliffc.aa.type.TypeFunSig.make_from_arg(), com.cliffc.aa.node.FunNode.make_new_fun(), com.cliffc.aa.type.TypeFunSig.str(), and com.cliffc.aa.type.TypeFunSig.xdual().
_dual
T com.cliffc.aa.type.Type< T extends Type< T >._dual package inherited
Definition at line 100 of file Type.java.
_formals
TypeTuple com.cliffc.aa.type.TypeFunSig._formals
Definition at line 15 of file TypeFunSig.java.
Referenced by com.cliffc.aa.type.TypeFunSig.above_center(), com.cliffc.aa.type.TypeFunSig.arg(), com.cliffc.aa.node.FunNode.bad_mem_use(), com.cliffc.aa.type.TypeFunSig.compute_hash(), com.cliffc.aa.type.TypeFunSig.equals(), com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.node.CEProjNode.good_call(), com.cliffc.aa.node.FunNode.ideal_inline(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.FunNode.ideal_reduce(), com.cliffc.aa.type.TypeFunSig.init(), com.cliffc.aa.node.CallNode.least_cost(), com.cliffc.aa.type.TypeFunSig.make_from_arg(), com.cliffc.aa.type.TypeFunSig.nargs(), com.cliffc.aa.node.FunNode.type_special(), com.cliffc.aa.type.TypeFunSig.xdual(), com.cliffc.aa.type.TypeFunSig.xmeet(), and com.cliffc.aa.node.PrimNode.xstr().
_hash
int com.cliffc.aa.type.Type< T extends Type< T >._hash inherited
Definition at line 97 of file Type.java.
_name
String com.cliffc.aa.type.Type< T extends Type< T >._name inherited
Definition at line 99 of file Type.java.
_ret
TypeTuple com.cliffc.aa.type.TypeFunSig._ret
Definition at line 16 of file TypeFunSig.java.
Referenced by com.cliffc.aa.node.PrimNode.ConvertTypeName.apply(), com.cliffc.aa.type.TypeFunSig.compute_hash(), com.cliffc.aa.type.TypeFunSig.equals(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.FunNode.ideal_inline(), com.cliffc.aa.type.TypeFunSig.init(), com.cliffc.aa.type.TypeFunSig.make_from_arg(), com.cliffc.aa.node.FunNode.make_new_fun(), com.cliffc.aa.type.TypeFunSig.str(), com.cliffc.aa.node.PrimNode.value(), com.cliffc.aa.type.TypeFunSig.xdual(), and com.cliffc.aa.type.TypeFunSig.xmeet().
_type
byte com.cliffc.aa.type.Type< T extends Type< T >._type package inherited
Definition at line 98 of file Type.java.
_uid
int com.cliffc.aa.type.Type< T extends Type< T >._uid inherited
Definition at line 96 of file Type.java.
ALL
final Type com.cliffc.aa.type.Type< T extends Type< T >.ALL static inherited
Definition at line 324 of file Type.java.
ALL_TYPES
Ary<Type> com.cliffc.aa.type.Type< T extends Type< T >.ALL_TYPES static private inherited
Definition at line 650 of file Type.java.
ANY
final Type com.cliffc.aa.type.Type< T extends Type< T >.ANY static inherited
Definition at line 325 of file Type.java.
CNT
int com.cliffc.aa.type.Type< T extends Type< T >.CNT static private inherited
Definition at line 95 of file Type.java.
CTRL
final Type com.cliffc.aa.type.Type< T extends Type< T >.CTRL static inherited
Definition at line 326 of file Type.java.
func_names
final String [] com.cliffc.aa.type.TypeFunSig.func_names = new String[]{" ctl", " mem", "^" , "arg3", "arg4", "arg5" } static
Definition at line 82 of file TypeFunSig.java.
Referenced by com.cliffc.aa.type.TypeFunSig.make(), and com.cliffc.aa.node.PrimNode.PrimNode().
II_I
final TypeFunSig com.cliffc.aa.type.TypeFunSig.II_I = make(TypeTuple.make_ret(TypeInt.INT64),TypeTuple.INT64_INT64) static
Definition at line 84 of file TypeFunSig.java.
INTERN
final ConcurrentHashMap<Type,Type> com.cliffc.aa.type.Type< T extends Type< T >.INTERN static private inherited
Definition at line 162 of file Type.java.
ISA_SCALAR
final byte [] com.cliffc.aa.type.Type< T extends Type< T >.ISA_SCALAR static private inherited
Definition at line 355 of file Type.java.
NIL
final Type com.cliffc.aa.type.Type< T extends Type< T >.NIL static inherited
Definition at line 332 of file Type.java.
NREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.NREAL static package inherited
Definition at line 336 of file Type.java.
NSCALR
final Type com.cliffc.aa.type.Type< T extends Type< T >.NSCALR static inherited
Definition at line 330 of file Type.java.
POOLS
final Pool [] com.cliffc.aa.type.Type< T extends Type< T >.POOLS static package inherited
Definition at line 281 of file Type.java.
REAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.REAL static inherited
Definition at line 334 of file Type.java.
RECURSIVE_MEET
int com.cliffc.aa.type.Type< T extends Type< T >.RECURSIVE_MEET static inherited
Definition at line 163 of file Type.java.
SCALAR
final Type com.cliffc.aa.type.Type< T extends Type< T >.SCALAR static inherited
Definition at line 328 of file Type.java.
SCALAR_PRIMS
Type [] com.cliffc.aa.type.Type< T extends Type< T >.SCALAR_PRIMS static private inherited
Definition at line 349 of file Type.java.
STRS
final String [] com.cliffc.aa.type.Type< T extends Type< T >.STRS static private inherited
Definition at line 262 of file Type.java.
TALL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TALL static package inherited
Definition at line 239 of file Type.java.
TANY
final byte com.cliffc.aa.type.Type< T extends Type< T >.TANY static package inherited
Definition at line 240 of file Type.java.
TARY
final byte com.cliffc.aa.type.Type< T extends Type< T >.TARY static package inherited
Definition at line 269 of file Type.java.
TCTRL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TCTRL static package inherited
Definition at line 241 of file Type.java.
TFLD
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFLD static package inherited
Definition at line 271 of file Type.java.
TFLT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFLT static package inherited
Definition at line 264 of file Type.java.
TFUNPTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFUNPTR static package inherited
Definition at line 274 of file Type.java.
TFUNSIG
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFUNSIG static package inherited
Definition at line 275 of file Type.java.
TINT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TINT static package inherited
Definition at line 263 of file Type.java.
TLAST
final byte com.cliffc.aa.type.Type< T extends Type< T >.TLAST static package inherited
Definition at line 277 of file Type.java.
TLIVE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TLIVE static package inherited
Definition at line 276 of file Type.java.
TMEM
final byte com.cliffc.aa.type.Type< T extends Type< T >.TMEM static package inherited
Definition at line 272 of file Type.java.
TMEMPTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TMEMPTR static package inherited
Definition at line 273 of file Type.java.
TNIL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNIL static package inherited
Definition at line 259 of file Type.java.
TNREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNREAL static package inherited
Definition at line 257 of file Type.java.
TNSCALR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNSCALR static package inherited
Definition at line 253 of file Type.java.
TOBJ
final byte com.cliffc.aa.type.Type< T extends Type< T >.TOBJ static package inherited
Definition at line 267 of file Type.java.
TREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TREAL static package inherited
Definition at line 255 of file Type.java.
TRPC
final byte com.cliffc.aa.type.Type< T extends Type< T >.TRPC static package inherited
Definition at line 265 of file Type.java.
TSCALAR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSCALAR static package inherited
Definition at line 246 of file Type.java.
TSIMPLE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSIMPLE static package inherited
Definition at line 261 of file Type.java.
TSTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSTR static package inherited
Definition at line 270 of file Type.java.
TSTRUCT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSTRUCT static package inherited
Definition at line 268 of file Type.java.
TTUPLE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TTUPLE static package inherited
Definition at line 266 of file Type.java.
TXCTRL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXCTRL static package inherited
Definition at line 242 of file Type.java.
TXNIL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNIL static package inherited
Definition at line 260 of file Type.java.
TXNREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNREAL static package inherited
Definition at line 258 of file Type.java.
TXNSCALR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNSCALR static package inherited
Definition at line 254 of file Type.java.
TXREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXREAL static package inherited
Definition at line 256 of file Type.java.
TXSCALAR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXSCALAR static package inherited
Definition at line 247 of file Type.java.
TYPES
final TypeFunSig [] com.cliffc.aa.type.TypeFunSig.TYPES = new TypeFunSig[]{II_I} static package
Definition at line 85 of file TypeFunSig.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.ALL_TYPES().
XCTRL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XCTRL static inherited
Definition at line 327 of file Type.java.
XNIL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNIL static inherited
Definition at line 333 of file Type.java.
XNREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNREAL static private inherited
Definition at line 337 of file Type.java.
XNSCALR
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNSCALR static inherited
Definition at line 331 of file Type.java.
XREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XREAL static private inherited
Definition at line 335 of file Type.java.
XSCALAR
final Type com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR static inherited
Definition at line 329 of file Type.java.
The documentation for this class was generated from the following file:
TypeFunSig.java