aa: com.cliffc.aa.HM.HM6.Apply Class Reference
com.cliffc.aa.HM.HM6.Apply Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Apply (Syntax fun, Syntax... args)
void add_kids (Worklist work)
void add_occurs (Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
T2 lookup (String name)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
Package Attributes
final Syntax[] _args
final Syntax _fun
VStack _nongen
Syntax _par
T2 _t
Detailed Description
Definition at line 431 of file HM6.java.
Constructor & Destructor Documentation
Apply()
com.cliffc.aa.HM.HM6.Apply.Apply (Syntax fun, Syntax... args) package
Definition at line 434 of file HM6.java.
 { _fun = fun; _args = args; }
References com.cliffc.aa.HM.HM6.Apply._args, and com.cliffc.aa.HM.HM6.Apply._fun.
Member Function Documentation
add_kids()
void com.cliffc.aa.HM.HM6.Apply.add_kids (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 481 of file HM6.java.
 { for( Syntax arg : _args ) work.push(arg); }
References com.cliffc.aa.HM.HM6.Apply._args, and com.cliffc.aa.HM.HM6.Worklist.push().
add_occurs()
void com.cliffc.aa.HM.HM6.Syntax.add_occurs (Worklist work) package inherited
Reimplemented in com.cliffc.aa.HM.HM6.Let, com.cliffc.aa.HM.HM6.Lambda2, com.cliffc.aa.HM.HM6.Lambda, and com.cliffc.aa.HM.HM6.Ident.
Definition at line 234 of file HM6.java.
 {}
Referenced by com.cliffc.aa.HM.HM6.hm().
debug_find()
T2 com.cliffc.aa.HM.HM6.Syntax.debug_find () package inherited
Definition at line 218 of file HM6.java.
 { return _t.find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM6.Syntax._t, and com.cliffc.aa.HM.HM6.T2.find().
Referenced by com.cliffc.aa.HM.HM6.hm().
find()
T2 com.cliffc.aa.HM.HM6.Syntax.find () package inherited
Definition at line 214 of file HM6.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM6.Syntax._t, and com.cliffc.aa.HM.HM6.T2.find().
Referenced by com.cliffc.aa.HM.HM6.T2._occurs_in(), com.cliffc.aa.HM.HM6.Lambda.add_occurs(), com.cliffc.aa.HM.HM6.Lambda2.add_occurs(), com.cliffc.aa.HM.HM6.Let.add_occurs(), com.cliffc.aa.HM.HM6.Con.hm(), com.cliffc.aa.HM.HM6.Ident.hm(), com.cliffc.aa.HM.HM6.Lambda.hm(), com.cliffc.aa.HM.HM6.Lambda2.hm(), com.cliffc.aa.HM.HM6.Let.hm(), and com.cliffc.aa.HM.HM6.Apply.hm().
hm()
boolean com.cliffc.aa.HM.HM6.Apply.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 448 of file HM6.java.
{
       // Unifiying these: make_fun(this.arg0 this.arg1 -> new     )
       //                      _fun{_fun.arg0 _fun.arg1 -> _fun.rez}
       // Progress if:
       //   _fun is not a function
       //   any arg-pair-unifies make progress
       //   this-unify-_fun.return makes progress
       T2 tfun = _fun.find();
       if( !tfun.is_fun() ) {
         if( work==null ) return true; // Will-progress & just-testing
         T2[] targs = new T2[_args.length+1];
         for( int i=0; i<_args.length; i++ )
           targs[i] = _args[i].find();
         targs[_args.length] = find(); // Return
         T2 nfun = T2.make_fun(targs);
         tfun.unify(nfun,work);
         return true;        // Always progress (since forcing tfun to be a fun)
       }
       if( tfun._args.length != _args.length+1 )
         throw new RuntimeException("Mismatched argument lengths");
       // Check for progress amongst arg pairs
       boolean progress = false;
       for( int i=0; i<_args.length; i++ ) {
         progress |= tfun.args(i).unify(_args[i].find(),work);
         if( progress && work==null )
           return true;          // Will-progress & just-testing early exit
       }
       progress |= tfun.args(_args.length).unify(find(),work);
       return progress;
     }
References com.cliffc.aa.HM.HM6.Apply._args, com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.Apply._fun, com.cliffc.aa.HM.HM6.T2.args(), com.cliffc.aa.HM.HM6.Syntax.find(), com.cliffc.aa.HM.HM6.T2.is_fun(), com.cliffc.aa.HM.HM6.T2.make_fun(), and com.cliffc.aa.HM.HM6.T2.unify().
lookup()
T2 com.cliffc.aa.HM.HM6.Apply.lookup (String name) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 480 of file HM6.java.
 { return _par==null ? null : _par.lookup(name); }
References com.cliffc.aa.HM.HM6.Syntax._par, and com.cliffc.aa.HM.HM6.Syntax.lookup().
more_work()
boolean com.cliffc.aa.HM.HM6.Apply.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 489 of file HM6.java.
{
       if( !more_work_impl(work) ) return false;
       if( !_fun.more_work(work) ) return false;
       for( Syntax arg : _args ) if( !arg.more_work(work) ) return false;
       return true;
     }
References com.cliffc.aa.HM.HM6.Apply._args, com.cliffc.aa.HM.HM6.Apply._fun, com.cliffc.aa.HM.HM6.Syntax.more_work(), and com.cliffc.aa.HM.HM6.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM6.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 238 of file HM6.java.
{
       return work.has(this) || !hm(null); // Either on worklist, or no-progress
     }
References com.cliffc.aa.HM.HM6.Worklist.has(), and com.cliffc.aa.HM.HM6.Syntax.hm().
Referenced by com.cliffc.aa.HM.HM6.Con.more_work(), com.cliffc.aa.HM.HM6.Ident.more_work(), com.cliffc.aa.HM.HM6.Lambda.more_work(), com.cliffc.aa.HM.HM6.Lambda2.more_work(), com.cliffc.aa.HM.HM6.Let.more_work(), and com.cliffc.aa.HM.HM6.Apply.more_work().
p()
String com.cliffc.aa.HM.HM6.Syntax.p () inherited
Definition at line 245 of file HM6.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM6.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM6.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 246 of file HM6.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM6.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM6.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM6.Syntax.p1(), com.cliffc.aa.HM.HM6.Syntax.p2(), and com.cliffc.aa.HM.HM6.T2.str().
Referenced by com.cliffc.aa.HM.HM6.Syntax.p(), com.cliffc.aa.HM.HM6.Lambda.p2(), com.cliffc.aa.HM.HM6.Lambda2.p2(), com.cliffc.aa.HM.HM6.Let.p2(), and com.cliffc.aa.HM.HM6.Apply.p2().
p1()
SB com.cliffc.aa.HM.HM6.Apply.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 441 of file HM6.java.
 { return sb.p("(...)"); }
References com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM6.Apply.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 442 of file HM6.java.
{
       _fun.p0(sb,dups);
       for( Syntax arg : _args ) arg.p0(sb,dups);
       return sb;
     }
References com.cliffc.aa.HM.HM6.Apply._args, com.cliffc.aa.HM.HM6.Apply._fun, and com.cliffc.aa.HM.HM6.Syntax.p0().
prep_lookup_deps()
void com.cliffc.aa.HM.HM6.Apply.prep_lookup_deps (Ident id) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 488 of file HM6.java.
 { }
prep_tree()
int com.cliffc.aa.HM.HM6.Apply.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 482 of file HM6.java.
{
       prep_tree_impl(par,nongen,work,T2.make_leaf());
       int cnt = _fun.prep_tree(this,nongen,work);
       for( Syntax arg : _args ) cnt += arg.prep_tree(this,nongen,work);
       return cnt;
     }
References com.cliffc.aa.HM.HM6.Apply._args, com.cliffc.aa.HM.HM6.Apply._fun, com.cliffc.aa.HM.HM6.T2.make_leaf(), com.cliffc.aa.HM.HM6.Syntax.prep_tree(), and com.cliffc.aa.HM.HM6.Syntax.prep_tree_impl().
prep_tree_impl()
final void com.cliffc.aa.HM.HM6.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 228 of file HM6.java.
 { _par=par; _t=t; _nongen = nongen; work.push(this); }
References com.cliffc.aa.HM.HM6.Syntax._nongen, com.cliffc.aa.HM.HM6.Syntax._par, com.cliffc.aa.HM.HM6.Syntax._t, and com.cliffc.aa.HM.HM6.Worklist.push().
Referenced by com.cliffc.aa.HM.HM6.Con.prep_tree(), com.cliffc.aa.HM.HM6.Ident.prep_tree(), com.cliffc.aa.HM.HM6.Lambda.prep_tree(), com.cliffc.aa.HM.HM6.Lambda2.prep_tree(), com.cliffc.aa.HM.HM6.Let.prep_tree(), and com.cliffc.aa.HM.HM6.Apply.prep_tree().
str()
SB com.cliffc.aa.HM.HM6.Apply.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 435 of file HM6.java.
{
       _fun.str(sb.p("(")).p(" ");
       for( Syntax arg : _args )
         arg.str(sb).p(" ");
       return sb.unchar().p(")");
     }
References com.cliffc.aa.HM.HM6.Apply._args, com.cliffc.aa.HM.HM6.Apply._fun, com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM6.Syntax.str(), and com.cliffc.aa.util.SB.unchar().
toString()
final String com.cliffc.aa.HM.HM6.Syntax.toString () inherited
Definition at line 242 of file HM6.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM6.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_args
final Syntax [] com.cliffc.aa.HM.HM6.Apply._args package
Definition at line 433 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.Apply.add_kids(), com.cliffc.aa.HM.HM6.Apply.Apply(), com.cliffc.aa.HM.HM6.Apply.hm(), com.cliffc.aa.HM.HM6.Apply.more_work(), com.cliffc.aa.HM.HM6.Apply.p2(), com.cliffc.aa.HM.HM6.Apply.prep_tree(), and com.cliffc.aa.HM.HM6.Apply.str().
_fun
final Syntax com.cliffc.aa.HM.HM6.Apply._fun package
Definition at line 432 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.Apply.Apply(), com.cliffc.aa.HM.HM6.Apply.hm(), com.cliffc.aa.HM.HM6.Apply.more_work(), com.cliffc.aa.HM.HM6.Apply.p2(), com.cliffc.aa.HM.HM6.Apply.prep_tree(), and com.cliffc.aa.HM.HM6.Apply.str().
_nongen
VStack com.cliffc.aa.HM.HM6.Syntax._nongen package inherited
Definition at line 212 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.Ident.hm(), and com.cliffc.aa.HM.HM6.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM6.Syntax._par package inherited
Definition at line 211 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.T2._occurs_in(), com.cliffc.aa.HM.HM6.Ident.add_occurs(), com.cliffc.aa.HM.HM6.hm(), com.cliffc.aa.HM.HM6.Ident.hm(), com.cliffc.aa.HM.HM6.Lambda.lookup(), com.cliffc.aa.HM.HM6.Lambda2.lookup(), com.cliffc.aa.HM.HM6.Let.lookup(), com.cliffc.aa.HM.HM6.Apply.lookup(), com.cliffc.aa.HM.HM6.Ident.prep_tree(), and com.cliffc.aa.HM.HM6.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM6.Syntax._t package inherited
Definition at line 213 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.Syntax.debug_find(), com.cliffc.aa.HM.HM6.Syntax.find(), com.cliffc.aa.HM.HM6.hm(), com.cliffc.aa.HM.HM6.Syntax.p0(), com.cliffc.aa.HM.HM6.Let.prep_tree(), and com.cliffc.aa.HM.HM6.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM6.java