aa: com.cliffc.aa.AbstractBuildVersion Class Reference
com.cliffc.aa.AbstractBuildVersion Class Reference abstract
Public Member Functions
abstract String branchName ()
abstract String compiledBy ()
abstract String compiledOn ()
abstract String describe ()
abstract String lastCommitHash ()
abstract String projectVersion ()
String toString ()
Detailed Description
Definition at line 5 of file AbstractBuildVersion.java.
Member Function Documentation
branchName()
abstract String com.cliffc.aa.AbstractBuildVersion.branchName () abstract
Referenced by com.cliffc.aa.AbstractBuildVersion.toString().
compiledBy()
abstract String com.cliffc.aa.AbstractBuildVersion.compiledBy () abstract
Referenced by com.cliffc.aa.AbstractBuildVersion.toString().
compiledOn()
abstract String com.cliffc.aa.AbstractBuildVersion.compiledOn () abstract
Referenced by com.cliffc.aa.AbstractBuildVersion.toString().
describe()
abstract String com.cliffc.aa.AbstractBuildVersion.describe () abstract
lastCommitHash()
abstract String com.cliffc.aa.AbstractBuildVersion.lastCommitHash () abstract
Referenced by com.cliffc.aa.AbstractBuildVersion.toString().
projectVersion()
abstract String com.cliffc.aa.AbstractBuildVersion.projectVersion () abstract
Referenced by com.cliffc.aa.AbstractBuildVersion.toString().
toString()
String com.cliffc.aa.AbstractBuildVersion.toString ()
Definition at line 12 of file AbstractBuildVersion.java.
{
     SB sb = new SB().p("aa v").p(projectVersion()).p('\n');
     sb.p(compiledBy()).p(" ").p(branchName()).p(" ").p(lastCommitHash()).p(" on ").p(compiledOn());
     return sb.toString();
   }
References com.cliffc.aa.AbstractBuildVersion.branchName(), com.cliffc.aa.AbstractBuildVersion.compiledBy(), com.cliffc.aa.AbstractBuildVersion.compiledOn(), com.cliffc.aa.AbstractBuildVersion.lastCommitHash(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.AbstractBuildVersion.projectVersion(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.AA.main().
The documentation for this class was generated from the following file:
AbstractBuildVersion.java