aa: com.cliffc.aa.node.NewObjNode Class Reference
com.cliffc.aa.node.NewObjNode Class Reference
Public Member Functions
NewObjNode (boolean is_closure, int alias, TypeStruct ts, Node clo)
NewObjNode (boolean is_closure, TypeStruct disp, Node clo)
void add_flow_def_extra (Node chg)
void add_flow_extra (Type old)
FunPtrNode add_fun (Parse bad, String name, FunPtrNode ptr)
void add_reduce_extra ()
TypeMem all_live ()
NewNode copy (boolean copy_edges)
void create (String name, Node val, Access mutable)
void create_active (String name, Node val, Access mutable)
boolean equals (Object o)
boolean exists (String name)
Node get (String name)
int hashCode ()
Node ideal_mono ()
Node ideal_reduce ()
boolean is_mutable (String name)
TypeMem live_use (GVNGCM.Mode opt_mode, Node def)
MrgProjNode mrg ()
void no_more_fields ()
void promote_forward (NewObjNode parent)
final void sets (T ts)
final void setsm (T ts)
void update (int fidx, Access mutable, Node val)
void update (String tok, Access mutable, Node val)
Type value (GVNGCM.Mode opt_mode)
String xstr ()
Public Attributes
int _alias
Parse[] _fld_starts
final boolean _is_closure
TypeMemPtr _tptr
T _ts
Package Functions
TypeStruct dead_type ()
BitsAlias escapees ()
Node fld (int fld)
boolean is_unused ()
void kill2 ()
ProjNode ptr ()
void set_name (TypeStruct name)
String str ()
TypeObj valueobj ()
Static Package Functions
static int def_idx (int fld)
Package Attributes
TypeObj _crushed
Private Member Functions
void _init (int alias, T ts)
boolean captured ()
Detailed Description
Definition at line 20 of file NewObjNode.java.
Constructor & Destructor Documentation
NewObjNode() [1/2]
com.cliffc.aa.node.NewObjNode.NewObjNode (boolean is_closure, TypeStruct disp, Node clo)
Definition at line 25 of file NewObjNode.java.
{
     super(OP_NEWOBJ,BitsAlias.REC,disp);
     add_def(clo);
     _is_closure = is_closure;
     assert disp.fld(0).is_display_ptr();
   }
References com.cliffc.aa.node.NewObjNode._is_closure, com.cliffc.aa.type.TypeStruct.fld(), com.cliffc.aa.type.TypeFld.is_display_ptr(), and com.cliffc.aa.type.BitsAlias.REC.
NewObjNode() [2/2]
com.cliffc.aa.node.NewObjNode.NewObjNode (boolean is_closure, int alias, TypeStruct ts, Node clo)
Definition at line 32 of file NewObjNode.java.
{
     super(OP_NEWOBJ,alias,ts,clo);
     _is_closure = is_closure;
     assert ts.fld(0).is_display_ptr();
   }
References com.cliffc.aa.node.NewObjNode._is_closure, com.cliffc.aa.type.TypeStruct.fld(), and com.cliffc.aa.type.TypeFld.is_display_ptr().
Member Function Documentation
_init()
void com.cliffc.aa.node.NewNode< T extends TypeObj< T >._init (int alias, T ts) private inherited
Definition at line 43 of file NewNode.java.
{
     if( _elock ) unelock();    // Unlock before changing hash
     _alias = alias;
     _tptr = TypeMemPtr.make(BitsAlias.make0(alias),TypeObj.ISUSED);
     sets(ts);
   }
add_flow_def_extra()
void com.cliffc.aa.node.NewNode< T extends TypeObj< T >.add_flow_def_extra (Node chg) inherited
Definition at line 72 of file NewNode.java.
{
     if( chg instanceof MrgProjNode && chg._live.at(_alias)==TypeObj.UNUSED )
       Env.GVN.add_reduce(chg);
   }
add_flow_extra()
void com.cliffc.aa.node.NewObjNode.add_flow_extra (Type old)
Definition at line 133 of file NewObjNode.java.
{
     Env.GVN.add_mono(this); // Can update crushed
   }
References com.cliffc.aa.GVNGCM.add_mono(), and com.cliffc.aa.Env.GVN.
add_fun()
FunPtrNode com.cliffc.aa.node.NewObjNode.add_fun (Parse bad, String name, FunPtrNode ptr)
Definition at line 76 of file NewObjNode.java.
{
     int fidx = _ts.fld_find(name);
     if( fidx == -1 ) {
       create_active(name,ptr,Access.Final);
     } else {
       Node n = _defs.at(def_idx(fidx));
       if( n instanceof UnresolvedNode ) n.add_def(ptr);
       else n = new UnresolvedNode(bad,n,ptr);
       n.xval(); // Update the input type, so the _ts field updates
       update(fidx,Access.Final,n);
     }
     return ptr;
   }
References com.cliffc.aa.node.NewNode< TypeStruct >._ts, com.cliffc.aa.node.Node.add_def(), com.cliffc.aa.node.NewObjNode.create_active(), com.cliffc.aa.node.NewNode< TypeStruct >.def_idx(), com.cliffc.aa.type.TypeFld.Access.Final, com.cliffc.aa.node.NewNode< TypeStruct >.ptr(), com.cliffc.aa.node.NewObjNode.update(), and com.cliffc.aa.node.Node.xval().
Referenced by com.cliffc.aa.Env.add_fun(), and com.cliffc.aa.Env.top_scope().
add_reduce_extra()
void com.cliffc.aa.node.NewNode< T extends TypeObj< T >.add_reduce_extra inherited
Definition at line 77 of file NewNode.java.
{
     Env.GVN.add_flow(Env.DEFMEM);
   }
all_live()
TypeMem com.cliffc.aa.node.NewNode< T extends TypeObj< T >.all_live inherited
Definition at line 86 of file NewNode.java.
 { return TypeMem.ALLMEM; }
captured()
boolean com.cliffc.aa.node.NewNode< T extends TypeObj< T >.captured private inherited
Definition at line 116 of file NewNode.java.
{
     if( _keep > 0 ) return false;
     if( _uses._len==0 ) return false; // Dead or being created
     Node mem = _uses.at(0);
     // If only either address or memory remains, then memory contents are dead
     if( _uses._len==1 ) {
       if( mem instanceof MrgProjNode ) return true; // No pointer, just dead memory
       // Just a pointer; currently on Strings become memory constants and
       // constant-fold - leaving the allocation dead.
       return !(val(1) instanceof TypeStr);
     }
     Node ptr = _uses.at(1);
     if( ptr instanceof MrgProjNode ) ptr = _uses.at(0); // Get ptr not mem
     if( ptr._keep>0 ) return false;
     // Scan for memory contents being unreachable.
     // Really stupid!
     for( Node use : ptr._uses )
       if( !(use instanceof IfNode) )
         return false;
     // Only used to nil-check (always not-nil) and equality (always unequal to
     // other aliases).
     return true;
   }
copy()
NewNode com.cliffc.aa.node.NewNode< T extends TypeObj< T >.copy (boolean copy_edges) inherited
Definition at line 143 of file NewNode.java.
{
     // Split the original '_alias' class into 2 sub-aliases
     NewNode<T> nnn = (NewNode<T>)super.copy(copy_edges);
     nnn._init(BitsAlias.new_alias(_alias),_ts);      // Children alias classes, split from parent
     _init(BitsAlias.new_alias(_alias),_ts); // The original NewNode also splits from the parent alias
     Env.GVN.add_flow(this);     // Alias changes flow
     return nnn;
   }
create()
void com.cliffc.aa.node.NewObjNode.create (String name, Node val, Access mutable)
Definition at line 51 of file NewObjNode.java.
{
     assert !Util.eq(name,"^"); // Closure field created on init
     create_active(name,val,mutable);
   }
References com.cliffc.aa.node.NewObjNode.create_active(), and com.cliffc.aa.util.Util.eq().
Referenced by com.cliffc.aa.Parse.create(), com.cliffc.aa.Parse.fact(), com.cliffc.aa.node.NewObjNode.promote_forward(), and com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay().
create_active()
void com.cliffc.aa.node.NewObjNode.create_active (String name, Node val, Access mutable)
Definition at line 57 of file NewObjNode.java.
{
     assert def_idx(_ts.len())== _defs._len;
     assert _ts.fld_find(name) == -1; // No dups
     add_def(val);
     setsm(_ts.add_fld(name,mutable,mutable==Access.Final ? val._val : Type.SCALAR));
     Env.GVN.add_flow(this);
   }
References com.cliffc.aa.node.NewNode< TypeStruct >._ts, com.cliffc.aa.node.Node._val, com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.node.NewNode< TypeStruct >.def_idx(), com.cliffc.aa.type.TypeFld.Access.Final, com.cliffc.aa.Env.GVN, com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.node.NewNode< TypeStruct >.setsm().
Referenced by com.cliffc.aa.node.NewObjNode.add_fun(), com.cliffc.aa.node.NewObjNode.create(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.TestLive.testNewObj(), com.cliffc.aa.Env.top_scope(), and com.cliffc.aa.Parse.tuple().
dead_type()
TypeStruct com.cliffc.aa.node.NewObjNode.dead_type () package
Definition at line 144 of file NewObjNode.java.
 { return TypeStruct.ANYSTRUCT; }
References com.cliffc.aa.type.TypeStruct.ANYSTRUCT.
def_idx()
static int com.cliffc.aa.node.NewNode< T extends TypeObj< T >.def_idx (int fld) static package inherited
Definition at line 52 of file NewNode.java.
 { return fld+1; } // Skip ctl in slot 0
equals()
boolean com.cliffc.aa.node.NewNode< T extends TypeObj< T >.equals (Object o) inherited
Definition at line 157 of file NewNode.java.
 {  return this==o; }
escapees()
BitsAlias com.cliffc.aa.node.NewNode< T extends TypeObj< T >.escapees package inherited
Definition at line 98 of file NewNode.java.
 { return _tptr._aliases; }
exists()
boolean com.cliffc.aa.node.NewObjNode.exists (String name)
Definition at line 38 of file NewObjNode.java.
 { return _ts.fld_find(name)!=-1; }
References com.cliffc.aa.node.NewNode< TypeStruct >._ts.
Referenced by com.cliffc.aa.Env.lookup_scope().
fld()
Node com.cliffc.aa.node.NewNode< T extends TypeObj< T >.fld (int fld) package inherited
Definition at line 53 of file NewNode.java.
 { return in(def_idx(fld)); } // Node for field#
get()
Node com.cliffc.aa.node.NewObjNode.get (String name)
Definition at line 37 of file NewObjNode.java.
 { int idx = _ts.fld_find(name);  assert idx >= 0; return fld(idx); }
References com.cliffc.aa.node.NewNode< TypeStruct >._ts, and com.cliffc.aa.node.NewNode< TypeStruct >.fld().
Referenced by com.cliffc.aa.node.ScopeNode.get(), and com.cliffc.aa.Parse.stmt().
hashCode()
int com.cliffc.aa.node.NewNode< T extends TypeObj< T >.hashCode inherited
Definition at line 152 of file NewNode.java.
 { return super.hashCode()+ _alias; }
ideal_mono()
Node com.cliffc.aa.node.NewObjNode.ideal_mono ()
Definition at line 116 of file NewObjNode.java.
{
     // If the value lifts a final field, so does the default lift.
     if( _val instanceof TypeTuple ) {
       TypeObj ts3 = (TypeObj)((TypeTuple)_val).at(MEM_IDX);
       if( ts3 != TypeObj.UNUSED ) {
         TypeStruct ts4 = _ts.make_from_flds((TypeStruct)ts3);
         TypeStruct ts5 = ts4.crush();
         assert ts4.isa(ts5);
         if( ts5 != _crushed && ts5.isa(_crushed) ) {
           setsm(ts4);
           Env.GVN.add_flow(Env.DEFMEM);
           return this;
         }
       }
     }
     return null;
   }
References com.cliffc.aa.node.NewNode< TypeStruct >._crushed, com.cliffc.aa.node.NewNode< TypeStruct >._ts, com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.type.TypeStruct.crush(), com.cliffc.aa.Env.DEFMEM, com.cliffc.aa.Env.GVN, com.cliffc.aa.node.NewNode< TypeStruct >.setsm(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED.
ideal_reduce()
Node com.cliffc.aa.node.NewNode< T extends TypeObj< T >.ideal_reduce inherited
Definition at line 64 of file NewNode.java.
{
     // If either the address or memory is not looked at then the memory
     // contents are dead.  The object might remain as a 'gensym' or 'sentinel'
     // for identity tests.
     if( _defs._len > 1 && captured() ) { kill2(); return this; }
     return null;
   }
is_mutable()
boolean com.cliffc.aa.node.NewObjNode.is_mutable (String name)
Definition at line 39 of file NewObjNode.java.
{
     return _ts.fld(_ts.fld_find(name))._access==Access.RW;
   }
References com.cliffc.aa.node.NewNode< TypeStruct >._ts, and com.cliffc.aa.type.TypeFld.Access.RW.
Referenced by com.cliffc.aa.node.ScopeNode.is_mutable(), and com.cliffc.aa.Parse.stmt().
is_unused()
boolean com.cliffc.aa.node.NewNode< T extends TypeObj< T >.is_unused package inherited
Definition at line 100 of file NewNode.java.
 { return _ts==dead_type(); }
kill2()
void com.cliffc.aa.node.NewNode< T extends TypeObj< T >.kill2 package inherited
Definition at line 102 of file NewNode.java.
                {
     unelock();
     while( !is_dead() && _defs._len > 1 )
       pop();                    // Kill all fields except memory
     _crushed = _ts = dead_type();
     _tptr = TypeMemPtr.make(BitsAlias.make0(_alias),TypeObj.UNUSED);
     Env.DEFMEM.set_def(_alias,Node.con(TypeObj.UNUSED));
     Env.GVN.revalive(this,ProjNode.proj(this,0),Env.DEFMEM);
     if( is_dead() ) return;
     for( Node use : _uses )
       Env.GVN.add_flow_uses(use); // Get FPtrs from MrgProj, and dead Ptrs into New
   }
live_use()
TypeMem com.cliffc.aa.node.NewObjNode.live_use (GVNGCM.Mode opt_mode, Node def)
Definition at line 147 of file NewObjNode.java.
{
     TypeObj to = _live.at(_alias);
     if( !(to instanceof TypeStruct) ) return to.above_center() ? TypeMem.DEAD : TypeMem.ESCAPE;
     int idx = _defs.find(def)-1;
     Type t = ((TypeStruct)to).at(idx);
     return t.above_center() ? TypeMem.DEAD : (t==Type.NSCALR ? TypeMem.LESC_NO_DISP : TypeMem.ESCAPE);
   }
References com.cliffc.aa.node.NewNode< TypeStruct >._alias, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.above_center(), com.cliffc.aa.type.Type< T extends Type< T >.above_center(), com.cliffc.aa.type.TypeMem.DEAD, com.cliffc.aa.type.TypeMem.ESCAPE, com.cliffc.aa.type.TypeMem.LESC_NO_DISP, and com.cliffc.aa.type.Type< T extends Type< T >.NSCALR.
mrg()
MrgProjNode com.cliffc.aa.node.NewNode< T extends TypeObj< T >.mrg inherited
Definition at line 158 of file NewNode.java.
{
     Node ptr = _uses.at(0);
     if( !(ptr instanceof MrgProjNode) ) ptr = _uses.at(1);
     return (MrgProjNode)ptr;
   }
no_more_fields()
void com.cliffc.aa.node.NewObjNode.no_more_fields ()
Definition at line 48 of file NewObjNode.java.
 { setsm(_ts.close()); }
References com.cliffc.aa.node.NewNode< TypeStruct >._ts, and com.cliffc.aa.node.NewNode< TypeStruct >.setsm().
Referenced by com.cliffc.aa.Env.close_display(), com.cliffc.aa.TestLive.testNewObj(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.Env.top_scope(), and com.cliffc.aa.Parse.tuple().
promote_forward()
void com.cliffc.aa.node.NewObjNode.promote_forward (NewObjNode parent)
Definition at line 94 of file NewObjNode.java.
{
     assert parent != null;
     TypeStruct ts = _ts;
     for( int i=0; i<ts.len(); i++ ) {
       Node n = fld(i);
       if( n != null && n.is_forward_ref() ) {
         // Remove current display from forward-refs display choices.
         assert Env.LEX_DISPLAYS.test(_alias);
         TypeMemPtr tdisp = TypeMemPtr.make(Env.LEX_DISPLAYS.clear(_alias),TypeObj.ISUSED);
         n.set_def(1,Node.con(tdisp)); // TODO: BUGGY?  NEEDS TO CRAWL THE DISPLAY 1 LEVEL?
         n.xval();
         // Make field in the parent
         TypeFld fld = ts.fld(i);
         parent.create(fld._fld,n,fld._access);
         // Stomp field locally to ANY
         set_def(def_idx(i),Env.ANY);
         setsm(_ts.set_fld(i,Type.ANY,Access.Final));
         Env.GVN.add_flow_uses(n);
       }
     }
   }
References com.cliffc.aa.node.NewNode< TypeStruct >._alias, com.cliffc.aa.node.NewNode< TypeStruct >._ts, com.cliffc.aa.GVNGCM.add_flow_uses(), com.cliffc.aa.Env.ANY, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.type.Bits< B extends Bits< B >.clear(), com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.NewObjNode.create(), com.cliffc.aa.node.NewNode< TypeStruct >.def_idx(), com.cliffc.aa.type.TypeFld.Access.Final, com.cliffc.aa.node.NewNode< TypeStruct >.fld(), com.cliffc.aa.type.TypeStruct.fld(), com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.is_forward_ref(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.ISUSED, com.cliffc.aa.type.TypeStruct.len(), com.cliffc.aa.Env.LEX_DISPLAYS, com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.node.Node.set_def(), com.cliffc.aa.node.NewNode< TypeStruct >.setsm(), com.cliffc.aa.type.Bits< B extends Bits< B >.test(), and com.cliffc.aa.node.Node.xval().
Referenced by com.cliffc.aa.Env.close().
ptr()
ProjNode com.cliffc.aa.node.NewNode< T extends TypeObj< T >.ptr package inherited
Definition at line 163 of file NewNode.java.
                  {
     Node ptr = _uses.at(0);
     if( ptr instanceof MrgProjNode ) ptr = _uses.at(1);
     return (ProjNode)ptr;
   }
set_name()
void com.cliffc.aa.node.NewObjNode.set_name (TypeStruct name) package
Definition at line 45 of file NewObjNode.java.
 { assert !name.above_center();  setsm(name); }
References com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.above_center(), and com.cliffc.aa.node.NewNode< TypeStruct >.setsm().
Referenced by com.cliffc.aa.node.IntrinsicNode.ideal_reduce().
sets()
final void com.cliffc.aa.node.NewNode< T extends TypeObj< T >.sets (T ts) inherited
Definition at line 57 of file NewNode.java.
{
     _ts = ts;
     _crushed = ts.crush();
   }
setsm()
final void com.cliffc.aa.node.NewNode< T extends TypeObj< T >.setsm (T ts) inherited
Definition at line 62 of file NewNode.java.
 { assert ts.isa(_ts); sets(ts); }
str()
String com.cliffc.aa.node.NewNode< T extends TypeObj< T >.str package inherited
Definition at line 50 of file NewNode.java.
 { return "New"+_ts; } // Inline less-short name
update() [1/2]
void com.cliffc.aa.node.NewObjNode.update (int fidx, Access mutable, Node val)
Definition at line 66 of file NewObjNode.java.
{
     assert def_idx(_ts.len())== _defs._len;
     set_def(def_idx(fidx),val);
     sets(_ts.set_fld(fidx,mutable==Access.Final ? val._val : Type.SCALAR,mutable));
     xval();
     Env.GVN.add_flow_uses(this);
   }
References com.cliffc.aa.node.NewNode< TypeStruct >._ts, com.cliffc.aa.node.Node._val, com.cliffc.aa.GVNGCM.add_flow_uses(), com.cliffc.aa.node.NewNode< TypeStruct >.def_idx(), com.cliffc.aa.type.TypeFld.Access.Final, com.cliffc.aa.Env.GVN, com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.node.NewNode< TypeStruct >.sets().
update() [2/2]
void com.cliffc.aa.node.NewObjNode.update (String tok, Access mutable, Node val)
Definition at line 64 of file NewObjNode.java.
 { update(_ts.fld_find(tok),mutable,val); }
References com.cliffc.aa.node.NewNode< TypeStruct >._ts, and com.cliffc.aa.node.NewObjNode.update().
Referenced by com.cliffc.aa.node.NewObjNode.add_fun(), com.cliffc.aa.Parse.func(), com.cliffc.aa.node.StoreNode.ideal_reduce(), and com.cliffc.aa.node.NewObjNode.update().
value()
Type com.cliffc.aa.node.NewNode< T extends TypeObj< T >.value (GVNGCM.Mode opt_mode) inherited
Definition at line 81 of file NewNode.java.
{
     return TypeTuple.make(Type.CTRL, is_unused() ? TypeObj.UNUSED : valueobj(),_tptr);   // Complex obj, simple ptr.
   }
valueobj()
TypeObj com.cliffc.aa.node.NewObjNode.valueobj () package
Definition at line 137 of file NewObjNode.java.
{
     // Gather args and produce a TypeStruct
     TypeFld[] ts = TypeFlds.get(_ts.len());
     for( int i=0; i<ts.length; i++ )
       ts[i] = _ts.fld(i).make_from((_ts._open && i>0) ? Type.ALL : fld(i)._val);
     return _ts.make_from(ts);  // Pick up field names and mods
   }
References com.cliffc.aa.node.NewNode< TypeStruct >._ts, com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.node.NewNode< TypeStruct >.fld(), and com.cliffc.aa.type.TypeFlds.get().
xstr()
String com.cliffc.aa.node.NewNode< T extends TypeObj< T >.xstr inherited
Definition at line 49 of file NewNode.java.
 { return "New"+"*"+_alias; } // Self short name
Member Data Documentation
_alias
int com.cliffc.aa.node.NewNode< T extends TypeObj< T >._alias inherited
Definition at line 20 of file NewNode.java.
_crushed
TypeObj com.cliffc.aa.node.NewNode< T extends TypeObj< T >._crushed package inherited
Definition at line 31 of file NewNode.java.
_fld_starts
Parse [] com.cliffc.aa.node.NewObjNode._fld_starts
Definition at line 22 of file NewObjNode.java.
Referenced by com.cliffc.aa.Parse.tuple().
_is_closure
final boolean com.cliffc.aa.node.NewObjNode._is_closure
Definition at line 21 of file NewObjNode.java.
Referenced by com.cliffc.aa.node.NewObjNode.NewObjNode().
_tptr
TypeMemPtr com.cliffc.aa.node.NewNode< T extends TypeObj< T >._tptr inherited
Definition at line 34 of file NewNode.java.
_ts
T com.cliffc.aa.node.NewNode< T extends TypeObj< T >._ts inherited
Definition at line 25 of file NewNode.java.
The documentation for this class was generated from the following file:
NewObjNode.java