aa: com.cliffc.aa.HM.HM4.Let Class Reference
com.cliffc.aa.HM.HM4.Let Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Let (String arg0, Syntax body, Syntax use)
T2 find ()
T2 hm (Ary< Syntax > work)
void live (IBitSet visit)
boolean more_work (Ary< Syntax > work)
final boolean more_work_impl (Ary< Syntax > work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_tree (Syntax par, Ary< Syntax > work)
void prep_tree_impl (Syntax par, T2 t, Ary< Syntax > work)
T2 prep_tree_lookup (String name, Syntax prior)
SB str (SB sb)
T2 targ ()
Package Attributes
final String _arg0
final Syntax _body
Syntax _par
T2 _t
T2 _targ
final Syntax _use
Detailed Description
Definition at line 229 of file HM4.java.
Constructor & Destructor Documentation
Let()
com.cliffc.aa.HM.HM4.Let.Let (String arg0, Syntax body, Syntax use) package
Definition at line 233 of file HM4.java.
 { _arg0=arg0; _body=body; _use=use; _targ=T2.tnew(); }
References com.cliffc.aa.HM.HM4.Let._arg0, com.cliffc.aa.HM.HM4.Let._body, com.cliffc.aa.HM.HM4.Let._targ, com.cliffc.aa.HM.HM4.Let._use, and com.cliffc.aa.HM.HM4.T2.tnew().
Member Function Documentation
find()
T2 com.cliffc.aa.HM.HM4.Syntax.find () package inherited
Definition at line 77 of file HM4.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM4.Syntax._t, and com.cliffc.aa.HM.HM4.T2.find().
Referenced by com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Con.hm(), com.cliffc.aa.HM.HM4.Ident.hm(), com.cliffc.aa.HM.HM4.Lambda.hm(), com.cliffc.aa.HM.HM4.Lambda2.hm(), com.cliffc.aa.HM.HM4.Let.hm(), com.cliffc.aa.HM.HM4.Apply.hm(), and com.cliffc.aa.HM.HM4.Syntax.more_work_impl().
hm()
T2 com.cliffc.aa.HM.HM4.Let.hm (Ary< Syntax > work) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 238 of file HM4.java.
{
       _use.find().push_update(this);
       targ().unify(_body.find(),work);
       return _use.find();
     }
References com.cliffc.aa.HM.HM4.Let._body, com.cliffc.aa.HM.HM4.Let._use, com.cliffc.aa.HM.HM4.Syntax.find(), com.cliffc.aa.HM.HM4.T2.push_update(), com.cliffc.aa.HM.HM4.Let.targ(), and com.cliffc.aa.HM.HM4.T2.unify().
live()
void com.cliffc.aa.HM.HM4.Let.live (IBitSet visit) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 259 of file HM4.java.
{
       if( _t!=null ) _t.live(visit);
       _targ.live(visit);
       _body.live(visit);
       _use .live(visit);
     }
References com.cliffc.aa.HM.HM4.Let._body, com.cliffc.aa.HM.HM4.Syntax._t, com.cliffc.aa.HM.HM4.Let._targ, com.cliffc.aa.HM.HM4.Let._use, com.cliffc.aa.HM.HM4.Syntax.live(), and com.cliffc.aa.HM.HM4.T2.live().
more_work()
boolean com.cliffc.aa.HM.HM4.Let.more_work (Ary< Syntax > work) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 255 of file HM4.java.
{
       if( !more_work_impl(work) ) return false;
       return _body.more_work(work) && _use.more_work(work);
     }
References com.cliffc.aa.HM.HM4.Let._body, com.cliffc.aa.HM.HM4.Let._use, com.cliffc.aa.HM.HM4.Syntax.more_work(), and com.cliffc.aa.HM.HM4.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM4.Syntax.more_work_impl (Ary< Syntax > work) package inherited
Definition at line 91 of file HM4.java.
{
       if( work.find(this)!=-1 ) return true; // On worklist, so ok
       // Check does not make progress
       int old = T2.CNT;  int olen = work._len;
       boolean more_work;
       try {
         T2 t = find();
         Type con = t._con;
         T2 hm = hm(null);       // Run H-M, with null work, looking for progress
         T2 un = find().unify(hm,null);
         more_work = t!=un || con!=un._con || work._len!=olen; // Something happened?
         assert !more_work;
       } catch( RuntimeException no_unify ) { more_work=true; } // Fail to unify assert is progress
       if( !more_work ) T2.CNT=old;  // Reset if no error; prevents assert from endlessly raising CNT
       return !more_work;
     }
References com.cliffc.aa.HM.HM4.T2._con, com.cliffc.aa.util.Ary< E >._len, com.cliffc.aa.HM.HM4.T2.CNT, com.cliffc.aa.HM.HM4.Syntax.find(), com.cliffc.aa.util.Ary< E >.find(), com.cliffc.aa.HM.HM4.Syntax.hm(), com.cliffc.aa.HM.HM4.Syntax.more_work(), and com.cliffc.aa.HM.HM4.T2.unify().
Referenced by com.cliffc.aa.HM.HM4.Con.more_work(), com.cliffc.aa.HM.HM4.Ident.more_work(), com.cliffc.aa.HM.HM4.Lambda.more_work(), com.cliffc.aa.HM.HM4.Lambda2.more_work(), com.cliffc.aa.HM.HM4.Let.more_work(), and com.cliffc.aa.HM.HM4.Apply.more_work().
p()
String com.cliffc.aa.HM.HM4.Syntax.p () inherited
Definition at line 111 of file HM4.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM4.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM4.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 112 of file HM4.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM4.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM4.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM4.Syntax.p1(), com.cliffc.aa.HM.HM4.Syntax.p2(), and com.cliffc.aa.HM.HM4.T2.str().
Referenced by com.cliffc.aa.HM.HM4.Syntax.p(), com.cliffc.aa.HM.HM4.Lambda.p2(), com.cliffc.aa.HM.HM4.Lambda2.p2(), com.cliffc.aa.HM.HM4.Let.p2(), and com.cliffc.aa.HM.HM4.Apply.p2().
p1()
SB com.cliffc.aa.HM.HM4.Let.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 235 of file HM4.java.
 { return sb.p("let ").p(_arg0).p(" = ... in ..."); }
References com.cliffc.aa.HM.HM4.Let._arg0, and com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM4.Let.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 236 of file HM4.java.
 { _body.p0(sb,dups); return _use.p0(sb,dups); }
References com.cliffc.aa.HM.HM4.Let._body, com.cliffc.aa.HM.HM4.Let._use, and com.cliffc.aa.HM.HM4.Syntax.p0().
prep_tree()
void com.cliffc.aa.HM.HM4.Let.prep_tree (Syntax par, Ary< Syntax > work) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 243 of file HM4.java.
{
       prep_tree_impl(par,T2.tnew(),work);
       _body.prep_tree(this,work);
       _use .prep_tree(this,work);
     }
References com.cliffc.aa.HM.HM4.Let._body, com.cliffc.aa.HM.HM4.Let._use, com.cliffc.aa.HM.HM4.Syntax.prep_tree(), com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM4.T2.tnew().
prep_tree_impl()
void com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl (Syntax par, T2 t, Ary< Syntax > work) package inherited
Definition at line 86 of file HM4.java.
 { _par=par; _t=t; work.push(this); }
References com.cliffc.aa.HM.HM4.Syntax._par, com.cliffc.aa.HM.HM4.Syntax._t, and com.cliffc.aa.util.Ary< E >.push().
Referenced by com.cliffc.aa.HM.HM4.Con.prep_tree(), com.cliffc.aa.HM.HM4.Ident.prep_tree(), com.cliffc.aa.HM.HM4.Lambda.prep_tree(), com.cliffc.aa.HM.HM4.Lambda2.prep_tree(), com.cliffc.aa.HM.HM4.Let.prep_tree(), and com.cliffc.aa.HM.HM4.Apply.prep_tree().
prep_tree_lookup()
T2 com.cliffc.aa.HM.HM4.Let.prep_tree_lookup (String name, Syntax prior) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 248 of file HM4.java.
{
       return Util.eq(_arg0,name)
         // Let _body, NOT fresh; Let _use, YES fresh
         ? (prior==_use ? T2.fresh(name,_targ) : _targ)
         : null;                 // Missed on name
     }
References com.cliffc.aa.HM.HM4.Let._arg0, com.cliffc.aa.HM.HM4.Let._targ, com.cliffc.aa.HM.HM4.Let._use, com.cliffc.aa.util.Util.eq(), and com.cliffc.aa.HM.HM4.T2.fresh().
str()
SB com.cliffc.aa.HM.HM4.Let.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM4.Syntax.
Definition at line 234 of file HM4.java.
 { return _use.str(_body.str(sb.p("let ").p(_arg0).p(" = ")).p(" in ")); }
References com.cliffc.aa.HM.HM4.Let._arg0, com.cliffc.aa.HM.HM4.Let._body, com.cliffc.aa.HM.HM4.Let._use, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM4.Syntax.str().
targ()
T2 com.cliffc.aa.HM.HM4.Let.targ () package
Definition at line 237 of file HM4.java.
 { T2 targ = _targ.find(); return targ==_targ ? targ : (_targ=targ); }
References com.cliffc.aa.HM.HM4.Let._targ, com.cliffc.aa.HM.HM4.T2.find(), and com.cliffc.aa.HM.HM4.Let.targ().
Referenced by com.cliffc.aa.HM.HM4.Let.hm(), and com.cliffc.aa.HM.HM4.Let.targ().
toString()
final String com.cliffc.aa.HM.HM4.Syntax.toString () inherited
Definition at line 108 of file HM4.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM4.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_arg0
final String com.cliffc.aa.HM.HM4.Let._arg0 package
Definition at line 230 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Let.Let(), com.cliffc.aa.HM.HM4.Let.p1(), com.cliffc.aa.HM.HM4.Let.prep_tree_lookup(), and com.cliffc.aa.HM.HM4.Let.str().
_body
final Syntax com.cliffc.aa.HM.HM4.Let._body package
Definition at line 231 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Let.hm(), com.cliffc.aa.HM.HM4.Let.Let(), com.cliffc.aa.HM.HM4.Let.live(), com.cliffc.aa.HM.HM4.Let.more_work(), com.cliffc.aa.HM.HM4.Let.p2(), com.cliffc.aa.HM.HM4.Let.prep_tree(), and com.cliffc.aa.HM.HM4.Let.str().
_par
Syntax com.cliffc.aa.HM.HM4.Syntax._par package inherited
Definition at line 75 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Ident.prep_tree(), and com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM4.Syntax._t package inherited
Definition at line 76 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Syntax.find(), com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Con.live(), com.cliffc.aa.HM.HM4.Ident.live(), com.cliffc.aa.HM.HM4.Lambda.live(), com.cliffc.aa.HM.HM4.Lambda2.live(), com.cliffc.aa.HM.HM4.Let.live(), com.cliffc.aa.HM.HM4.Apply.live(), com.cliffc.aa.HM.HM4.Syntax.p0(), and com.cliffc.aa.HM.HM4.Syntax.prep_tree_impl().
_targ
T2 com.cliffc.aa.HM.HM4.Let._targ package
Definition at line 232 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Let.Let(), com.cliffc.aa.HM.HM4.Let.live(), com.cliffc.aa.HM.HM4.Let.prep_tree_lookup(), and com.cliffc.aa.HM.HM4.Let.targ().
_use
final Syntax com.cliffc.aa.HM.HM4.Let._use package
Definition at line 231 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Let.hm(), com.cliffc.aa.HM.HM4.Let.Let(), com.cliffc.aa.HM.HM4.Let.live(), com.cliffc.aa.HM.HM4.Let.more_work(), com.cliffc.aa.HM.HM4.Let.p2(), com.cliffc.aa.HM.HM4.Let.prep_tree(), com.cliffc.aa.HM.HM4.Let.prep_tree_lookup(), and com.cliffc.aa.HM.HM4.Let.str().
The documentation for this class was generated from the following file:
HM4.java