aa: com.cliffc.aa.type.BitsAlias Class Reference
com.cliffc.aa.type.BitsAlias Class Reference
Public Member Functions
int abit ()
boolean above_center ()
BitsAlias ALL ()
BitsAlias ANY ()
int bitCount ()
IBitSet bitset ()
B clear (int bit)
B dual ()
BitsAlias EMPTY ()
boolean equals (Object o)
int getbit ()
int hashCode ()
boolean is_con ()
boolean is_empty ()
boolean is_nil ()
boolean isa (B bs)
Iterator< Integer > iterator ()
Bits< B > join (Bits< B > bs)
final B make (int... bits)
int max ()
B meet (final B bs)
B meet_nil ()
TypeObj oob (TypeObj t)
BitsAlias or (int bit)
boolean overlaps (Bits< B > bs)
B set (int bit)
SB str (SB sb)
B strip_nil ()
Bits< B > subtract (Bits< B > bs)
boolean test (int i)
boolean test_recur (int i)
String toString ()
Tree< BitsAlias > tree ()
Static Public Member Functions
static int[] get_kids (int par)
static void init0 ()
static boolean is_parent (int idx)
static boolean is_parent (int par, int kid)
static BitsAlias make0 (int bit)
static int new_alias (int par)
static int next_kid (int alias, int kid)
static int parent (int kid)
static void reset_to_init0 ()
static int type_alias (int par)
Static Public Attributes
static final int ALL
static BitsAlias FULL
static BitsAlias RECORD_BITS
Package Functions
void init (int con, long[] bits)
final B make (int bit)
BitsAlias make_impl (int con, long[] bits)
boolean may_nil ()
B not_nil ()
Static Package Functions
[static initializer]
Package Attributes
long[] _bits
int _con
int _hash
Static Package Attributes
static final int AARY
static final int ABC
static BitsAlias ANY
static final int ARY
static BitsAlias ARYBITS
static BitsAlias ARYBITS0
static BitsAlias EMPTY
static BitsAlias NIL
static BitsAlias NZERO
static final int REC
static BitsAlias RECORD_BITS0
static final int STR
static BitsAlias STRBITS
static BitsAlias STRBITS0
static final Bits.Tree< BitsAlias > TREE = new Bits.Tree<>()
static BitsAlias XNIL
Private Member Functions
boolean check ()
B make (boolean any, long[] bits)
Static Private Member Functions
static void and (long[] bits, long con)
static long[] bits (int b)
static boolean check_multi_bits (long[] bits)
static int idx (long i)
static void join (Tree tree, long[] bits0, long[] bits1, long[] bits2)
static long mask (long i)
static int set_alias (int par)
static boolean test (long[] bits, int i)
Static Private Attributes
static BitsAlias FREE =null
static final HashMap< BitsAlias, BitsAlias > INTERN = new HashMap<>()
Detailed Description
Definition at line 8 of file BitsAlias.java.
Member Function Documentation
[static initializer]()
com.cliffc.aa.type.BitsAlias.[static initializer] static package
abit()
int com.cliffc.aa.type.Bits< B extends Bits< B >.abit inherited
Definition at line 203 of file Bits.java.
 { return _bits==null&&_con!=0 ? _con : -1; }
above_center()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.above_center inherited
Definition at line 204 of file Bits.java.
 { return _con<0; }
ALL()
BitsAlias com.cliffc.aa.type.BitsAlias.ALL ()
Definition at line 68 of file BitsAlias.java.
 { return FULL; }
References com.cliffc.aa.type.BitsAlias.FULL.
and()
static void com.cliffc.aa.type.Bits< B extends Bits< B >.and (long[] bits, long con) static private inherited
Definition at line 282 of file Bits.java.
 { bits[idx(con)] &= ~mask(con); }
ANY()
BitsAlias com.cliffc.aa.type.BitsAlias.ANY ()
Definition at line 69 of file BitsAlias.java.
 { return ANY ; }
References com.cliffc.aa.type.BitsAlias.ANY().
Referenced by com.cliffc.aa.type.BitsAlias.ANY().
bitCount()
int com.cliffc.aa.type.Bits< B extends Bits< B >.bitCount inherited
Definition at line 113 of file Bits.java.
{
     if( _bits==null ) return _con==0 ? 0 : 1;
     int sum=0;
     for( long b : _bits )
       sum += Long.bitCount(b);
     return sum;
   }
bits()
static long [] com.cliffc.aa.type.Bits< B extends Bits< B >.bits (int b) static private inherited
Definition at line 283 of file Bits.java.
 { return new long[idx(b)+1]; }
bitset()
IBitSet com.cliffc.aa.type.Bits< B extends Bits< B >.bitset inherited
Definition at line 391 of file Bits.java.
{
     IBitSet bs = new IBitSet();
     for( int alias : this )
       bs.set(alias);
     return bs;
   }
check()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.check private inherited
Definition at line 89 of file Bits.java.
{
     if( _bits==null ) return true;  // Must be a single bit#
     if( _con != 1 && _con != -1 ) return false;
     if( _bits.length==0 ) return false;  // Empty bits replaced by a con
     if( _bits.length==1 && _bits[0]== 0 ) return false; // NO bits is bad, use EMPTY instead
     if( _bits[_bits.length-1]==0 ) return false; // Array is "tight"
     if( _bits.length==1 && _bits[0]==1 ) return true; // NIL
     // No set bit has a parent bit set, because the parent overrides
     Tree<B> tree = tree();
     for( int i : this )
       while( (i = tree.parent(i)) != 0 )
         if( test(i) )
           return false;
     // For efficiency, 1 bit set uses 'con' instead of 'bits'
     return check_multi_bits(_bits); // Found multiple bits
   }
check_multi_bits()
static boolean com.cliffc.aa.type.Bits< B extends Bits< B >.check_multi_bits (long[] bits) static private inherited
Definition at line 105 of file Bits.java.
{
     int len = bits.length;
     long b = bits[len-1];             // Last word
     if( (b & (b-1))!=0 ) return true; // Last word has multiple bits
     // Check multiple bits spread over multiple words
     for( int i=0; i<len-1; i++ ) if( bits[i] != 0 ) return true;
     return false;                // Found a single bit in last word
   }
clear()
B com.cliffc.aa.type.Bits< B extends Bits< B >.clear (int bit) inherited
Definition at line 255 of file Bits.java.
{
     if( !test(bit) ) return (B)this;
     if( _bits == null ) return EMPTY();
     long[] bs = _bits.clone();
     and(bs,bit);
     return make(_con==-1,bs);
   }
dual()
B com.cliffc.aa.type.Bits< B extends Bits< B >.dual inherited
Definition at line 368 of file Bits.java.
 { return make_impl(-_con,_bits); }
EMPTY()
BitsAlias com.cliffc.aa.type.BitsAlias.EMPTY ()
Definition at line 70 of file BitsAlias.java.
 { return EMPTY ; }
References com.cliffc.aa.type.BitsAlias.EMPTY().
Referenced by com.cliffc.aa.type.BitsAlias.EMPTY().
equals()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.equals (Object o) inherited
Definition at line 121 of file Bits.java.
{
     if( this==o ) return true;
     if( !(o instanceof Bits) ) return false;
     Bits bs = (Bits)o;
     if( _con != bs._con || _hash != bs._hash ) return false;
     if( _bits == bs._bits ) return true;
     if( _bits ==null || bs._bits==null ) return false;
     if( _bits.length != bs._bits.length ) return false;
     for( int i=0; i<_bits.length; i++ )
       if( _bits[i]!=bs._bits[i] ) return false;
     return true;
   }
get_kids()
static int [] com.cliffc.aa.type.BitsAlias.get_kids (int par) static
Definition at line 61 of file BitsAlias.java.
 { return TREE.get_kids(par); }
References com.cliffc.aa.type.BitsAlias.TREE.
Referenced by com.cliffc.aa.node.MemSplitNode.split_alias().
getbit()
int com.cliffc.aa.type.Bits< B extends Bits< B >.getbit inherited
Definition at line 202 of file Bits.java.
 { assert _bits==null && _con!=0; return _con; }
hashCode()
int com.cliffc.aa.type.Bits< B extends Bits< B >.hashCode inherited
Definition at line 120 of file Bits.java.
 { return _hash; }
idx()
static int com.cliffc.aa.type.Bits< B extends Bits< B >.idx (long i) static private inherited
Definition at line 199 of file Bits.java.
 { return (int)(i>>6); }
init()
void com.cliffc.aa.type.Bits< B extends Bits< B >.init (int con, long[] bits) package inherited
Definition at line 80 of file Bits.java.
{
     _con = con;
     _bits=bits;
     long sum=_con;
     if( _bits != null ) for( long l : _bits ) sum += l;
     _hash = (int)((sum>>32)+sum);
     if( _hash==0 ) _hash=1;
     assert check();
   }
init0()
static void com.cliffc.aa.type.BitsAlias.init0 () static
Definition at line 63 of file BitsAlias.java.
 { TREE.init0(); }
References com.cliffc.aa.type.BitsAlias.TREE.
Referenced by com.cliffc.aa.Env.record_for_top_reset1().
is_con()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.is_con inherited
Definition at line 206 of file Bits.java.
 { return is_nil() || is_empty(); }
is_empty()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.is_empty inherited
Definition at line 207 of file Bits.java.
 { return _bits==null && _con==0; }
is_nil()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.is_nil inherited
Definition at line 208 of file Bits.java.
 { return _bits!=null && _bits.length==1 && _bits[0]==1; }
is_parent() [1/2]
static boolean com.cliffc.aa.type.BitsAlias.is_parent (int idx) static
Definition at line 57 of file BitsAlias.java.
 { return TREE.is_parent(idx); }
References com.cliffc.aa.type.Bits< BitsAlias >.idx(), and com.cliffc.aa.type.BitsAlias.TREE.
is_parent() [2/2]
static boolean com.cliffc.aa.type.BitsAlias.is_parent (int par, int kid) static
Definition at line 55 of file BitsAlias.java.
 { return TREE.is_parent(par,kid); }
References com.cliffc.aa.type.BitsAlias.TREE.
isa()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.isa (B bs) inherited
Definition at line 372 of file Bits.java.
 { return meet(bs) == bs; }
iterator()
Iterator<Integer> com.cliffc.aa.type.Bits< B extends Bits< B >.iterator inherited
Returns
an iterator
Definition at line 523 of file Bits.java.
 { return new Iter(); }
join() [1/2]
Bits<B> com.cliffc.aa.type.Bits< B extends Bits< B >.join (Bits< B > bs) inherited
Definition at line 370 of file Bits.java.
 { return dual().meet(bs.dual()).dual(); }
join() [2/2]
static void com.cliffc.aa.type.Bits< B extends Bits< B >.join (Tree tree, long[] bits0, long[] bits1, long[] bits2) static private inherited
Definition at line 349 of file Bits.java.
{
     // If a 'parent' bit is set, then no need to have any child bits set.
     for( int i=0; i<bits0.length; i++ ) { // For all words
       long l = bits0[i];
       if( l!=0 ) {
         // TODO: Use Long.numberOfTrailingZeros (or LeadingZeros probably) to
         // do this only once-per-set-bit.
         for( int j=0; j<64; j++ ) // For all bits in word
           if( (mask(j)&l) != 0 ) {
             for( int par = (i<<6)+j; par!=0; par = tree.parent(par) ) // Walk parent chain
               if( test(bits1,par) )                // If parent set
                 { bits2[i]|=mask(j); break; }      // then set kid
           }
       }
     }
   }
make() [1/3]
B com.cliffc.aa.type.Bits< B extends Bits< B >.make (boolean any, long[] bits) private inherited
Definition at line 154 of file Bits.java.
{
     // If a 'parent' bit is set, then no need to have any child bits set.
     Tree<B> tree = tree();
     // TODO: Run this loop backwards, avoids most tree-walks; lowers O(n log n) to O(n).
     for( int i=0; i<bits.length; i++ ) { // For all words
       long l = bits[i];
       if( l!=0 ) {
         for( int j=0; j<64; j++ ) // For all bits in word
           if( (mask(j)&l) != 0 ) {
             int par = (i<<6)+j; // Kid index
             while( (par = tree.parent(par)) != 0 ) // Walk parent chain
               if( test(bits,par) )                 // If parent set
                 { bits[i]&=~mask(j); break; }      // then clear kid
           }
       }
     }
     // Remove any trailing empty words
     int len = bits.length;
     while( len > 1 && bits[len-1]==0 ) len--;
     if( bits.length != len ) bits = Arrays.copyOf(bits,len);
     // Check for a single bit or NO bits
     if( check_multi_bits(bits) ) return make_impl(any ? -1 : 1,bits);
     // Special check for +/-0
     if( len==1 && bits[0]==1 ) return make_impl(any ? -1 : 1,bits);
     // Empty is self-dual, ignores 'any'
     if( len==1 && bits[0]==0 ) return make_impl(0,null);
     // Single bit
     int bnum0 = 63 - Long.numberOfLeadingZeros(bits[len-1]);
     int bnum = bnum0 + ((len-1)<<6);
     if( any ) bnum = -bnum;
     return make_impl(bnum,null);
   }
make() [2/3]
final B com.cliffc.aa.type.Bits< B extends Bits< B >.make (int bit) package inherited
Definition at line 189 of file Bits.java.
 { return bit==0 ? make_impl(1,new long[]{1}) : make_impl(bit,null); }
make() [3/3]
final B com.cliffc.aa.type.Bits< B extends Bits< B >.make (int... bits) inherited
Definition at line 191 of file Bits.java.
{
     int max= 0;                // Find max bit
     for( int bit : bits ) max=Math.max(max,bit);
     long[] ls = bits(max);  // Big enuf bits
     for( int bit : bits ) or(ls,bit);
     return make(false,ls);
   }
make0()
static BitsAlias com.cliffc.aa.type.BitsAlias.make0 (int bit) static
Definition at line 72 of file BitsAlias.java.
 { return NZERO.make(bit); }
References com.cliffc.aa.type.Bits< B extends Bits< B >.make(), and com.cliffc.aa.type.BitsAlias.NZERO.
Referenced by com.cliffc.aa.node.NewNode< TypeStruct >._init(), com.cliffc.aa.HM.TestHM.build_cycle(), com.cliffc.aa.HM.TestHM9.build_cycle(), com.cliffc.aa.HM.TestHM.build_cycle2(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.HM.HM9.Struct.hm(), com.cliffc.aa.HM.HM.Struct.hm(), com.cliffc.aa.node.NewNode< TypeStruct >.kill2(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeMemPtr.make_nil(), com.cliffc.aa.HM.HM9.Pair.Pair(), com.cliffc.aa.HM.HM.Pair.Pair(), com.cliffc.aa.HM.HM9.Pair1.Pair1(), com.cliffc.aa.HM.HM.Pair1.Pair1(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.Pair1X(), com.cliffc.aa.HM.HM.Pair1.Pair1X.Pair1X(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM.Struct.prep_tree(), com.cliffc.aa.HM.HM8.Struct.Struct(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox7(), com.cliffc.aa.TestParse.testParse02(), com.cliffc.aa.TestParse.testParse15(), com.cliffc.aa.HM.HM9.Triple.Triple(), and com.cliffc.aa.HM.HM.Triple.Triple().
make_impl()
BitsAlias com.cliffc.aa.type.BitsAlias.make_impl (int con, long[] bits) package
Definition at line 13 of file BitsAlias.java.
{
     BitsAlias b1 = FREE;
     if( b1 == null ) b1 = new BitsAlias();
     else FREE = null;
     b1.init(con,bits);
     BitsAlias b2 = INTERN.get(b1);
     if( b2 != null ) { FREE = b1; return b2; }
     else { INTERN.put(b1,b1); return b1; }
   }
References com.cliffc.aa.type.Bits< BitsAlias >.bits(), com.cliffc.aa.type.BitsAlias.FREE, com.cliffc.aa.type.Bits< B extends Bits< B >.init(), and com.cliffc.aa.type.BitsAlias.INTERN.
mask()
static long com.cliffc.aa.type.Bits< B extends Bits< B >.mask (long i) static private inherited
Definition at line 200 of file Bits.java.
 { return 1L<<(i&63); }
max()
int com.cliffc.aa.type.Bits< B extends Bits< B >.max inherited
Definition at line 284 of file Bits.java.
                     {
     return _bits==null ? Math.abs(_con) : (63 - Long.numberOfLeadingZeros(_bits[_bits.length-1]))+((_bits.length-1)<<6);
   }
may_nil()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.may_nil package inherited
Definition at line 209 of file Bits.java.
 { return _con==-1 && _bits != null && ((_bits[0]&1) == 1); }
meet()
B com.cliffc.aa.type.Bits< B extends Bits< B >.meet (final B bs) inherited
Definition at line 298 of file Bits.java.
{
     if( this==bs ) return (B)this;
     B full = ALL();             // Subclass-specific version of full
     if( this==full || bs==full ) return full;
     B any  = ANY();             // Subclass-specific version of any
     if( this==any ) return bs;
     if( bs  ==any ) return (B)this;
     // Empty is a little odd; similar to meeting two JOIN sets with nothing in
     // common - it is on the center, and forces above values to fall, and
     // itself falls to below values.
     if( is_empty() ) return bs.above_center() ? (B)this : bs;
     if( bs.is_empty() ) return above_center() ? bs : (B)this;
     long[] bits0 = _bits, bits1 = bs._bits;
     int con0 = Math.abs(_con), con1 = Math.abs(bs._con);
     // Expand any single bits
     if( bits0==null ) or(bits0=bits(con0), con0);
     if( bits1==null ) or(bits1=bits(con1), con1);
     con0 =    _con < 0 ? -1 : 1;
     con1 = bs._con < 0 ? -1 : 1;
     // Bigger in bits0
     if( bits0.length < bits1.length ) { long[] tmp=bits0; bits0=bits1; bits1=tmp; int t=con0; con0=con1; con1=t; }
     // Both meets?  Set-union
     if( con0 == 1 && con1 == 1 ) {
       long[] bits = bits0.clone();        // Clone larger
       for( int i=0; i<bits1.length; i++ ) // OR in smaller bits
         bits[i] |= bits1[i];
       return make(false,bits);  // This will remove parent/child dups
     }
     // Both joins?  Set-intersection
     Tree<B> tree = tree();
     if( con0 == -1 && con1 == -1 ) {
       long[] bits = new long[bits0.length];// Result array
       join(tree,bits0,bits1,bits);         // Merge left into right
       join(tree,bits1,bits0,bits);         // Merge right into left
       // Nil is not part of the parent tree, so needs to be set explicitly
       if( (bits0[0]&1)==1 && (bits1[0]&1)==1 )  bits[0]|=1;
       // Just the intersection, which may be empty.
       return make(true,bits);
     }
     // Mixed meet/join.  Toss away the join, keep only the meet bits.
     return above_center() ? bs : (B)this;
   }
meet_nil()
B com.cliffc.aa.type.Bits< B extends Bits< B >.meet_nil inherited
Definition at line 212 of file Bits.java.
                       {
     if( above_center() ) return make(0); // Crossing centerline, drop all above bits, just [0]
     if( test(0) ) return (B)this;// Already has nil
     long[] bs = _bits;
     if( bs==null )              // Is a single compressed bit
       or(bs = bits(Math.abs(_con)),Math.abs(_con)); // Decompress single bit into array
     else bs = _bits.clone();    // Make a private set
     bs[0] |= 1;                 // Set nil
     return make(false,bs);      // Its below center now, even if the original was above
   }
new_alias()
static int com.cliffc.aa.type.BitsAlias.new_alias (int par) static
Definition at line 75 of file BitsAlias.java.
 { return set_alias(par); }
References com.cliffc.aa.type.BitsAlias.set_alias().
Referenced by com.cliffc.aa.node.NewNode< TypeStruct >.copy(), com.cliffc.aa.node.NewNode< TypeStruct >.NewNode(), com.cliffc.aa.HM.HM9.PrimSyn.reset(), com.cliffc.aa.HM.HM.PrimSyn.reset(), com.cliffc.aa.HM.HM8.Struct.Struct(), com.cliffc.aa.HM.HM9.Struct.Struct(), com.cliffc.aa.HM.HM.Struct.Struct(), com.cliffc.aa.type.TestApprox.testApprox1(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox4(), com.cliffc.aa.type.TestApprox.testApprox5(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestApprox.testApprox7(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.node.TestNodeSmall.testMemoryArgs(), com.cliffc.aa.type.TestType.testRecursive(), and com.cliffc.aa.type.TestApprox.testTSMeet().
next_kid()
static int com.cliffc.aa.type.BitsAlias.next_kid (int alias, int kid) static
Definition at line 66 of file BitsAlias.java.
 { return TREE.next_kid(alias,kid); }
References com.cliffc.aa.type.BitsAlias.TREE.
Referenced by com.cliffc.aa.type.TypeStruct._dull(), com.cliffc.aa.type.TypeMem.all_reaching_aliases(), com.cliffc.aa.type.TypeMem.ld(), and com.cliffc.aa.type.TypeMem.update().
not_nil()
B com.cliffc.aa.type.Bits< B extends Bits< B >.not_nil package inherited
Definition at line 246 of file Bits.java.
               {
     if( !above_center() || _bits == null ) return (B)this;  // Some constant not-nil
     if( !test(_bits,0) ) return (B)this; // No nil choice
     long[] bs = _bits.clone();           // Keep all other bits
     and(bs,0);                           // remove nil choice
     return make(true,bs);                // Choices without nil
   }
oob()
TypeObj com.cliffc.aa.type.Bits< B extends Bits< B >.oob (TypeObj t) inherited
Definition at line 397 of file Bits.java.
 { return above_center() ? (TypeObj)t.dual() : t; }
or()
BitsAlias com.cliffc.aa.type.BitsAlias.or (int bit)
Definition at line 73 of file BitsAlias.java.
 { return set(bit); }
overlaps()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.overlaps (Bits< B > bs) inherited
Definition at line 382 of file Bits.java.
{
     for( int alias : this )
       for( int kid=alias; kid!=0; kid = tree().next_kid(alias,kid) )
         if( bs.test_recur(kid) )
           return true;
     return false;
   }
parent()
static int com.cliffc.aa.type.BitsAlias.parent (int kid) static
Definition at line 59 of file BitsAlias.java.
 { return TREE.parent(kid); }
References com.cliffc.aa.type.BitsAlias.TREE.
Referenced by com.cliffc.aa.node.FunNode.split_callers().
reset_to_init0()
static void com.cliffc.aa.type.BitsAlias.reset_to_init0 () static
Definition at line 64 of file BitsAlias.java.
 { TREE.reset_to_init0(); }
References com.cliffc.aa.type.BitsAlias.TREE.
Referenced by com.cliffc.aa.HM.HM8.reset(), com.cliffc.aa.HM.HM9.reset(), com.cliffc.aa.HM.HM.reset(), and com.cliffc.aa.Env.top_reset().
set()
B com.cliffc.aa.type.Bits< B extends Bits< B >.set (int bit) inherited
Definition at line 264 of file Bits.java.
{
     if( test(bit) ) return (B)this;
     B b = make(bit);
     if( this == EMPTY() ) return b;
     return meet(b);
   }
set_alias()
static int com.cliffc.aa.type.BitsAlias.set_alias (int par) static private
Definition at line 77 of file BitsAlias.java.
 { return TREE.split(par); }
References com.cliffc.aa.type.BitsAlias.TREE.
Referenced by com.cliffc.aa.type.BitsAlias.new_alias(), and com.cliffc.aa.type.BitsAlias.type_alias().
str()
SB com.cliffc.aa.type.Bits< B extends Bits< B >.str (SB sb) inherited
Definition at line 134 of file Bits.java.
{
     if( _bits==null ) {
       if( _con== 0 ) return sb.p("[]"); // EMPTY
       if( _con== 1 ) return sb.p("[ALL]");
       if( _con==-1 ) return sb.p("[ANY]");
       return sb.p('[').p(_con).p(']');
     }
     sb.p('[');
     if( above_center() ) sb.p('~');
     char sep = above_center()?'+':',';
     if( test(_bits,1) ) {
       if( test(_bits,0) ) sb.p('0').p(sep);
       return sb.p(above_center() ? "ANY]" : "ALL]");
     }
     for( Integer idx : this ) sb.p(idx).p(sep);
     return sb.unchar().p(']');
   }
strip_nil()
B com.cliffc.aa.type.Bits< B extends Bits< B >.strip_nil inherited
Definition at line 273 of file Bits.java.
{
     if( _bits == null ) return (B)this; // Should not be a nil to remove
     if( (_bits[0] &1)==0 ) return (B) this; // No nil
     long[] bs = _bits.clone();
     bs[0] &= ~1;                // Strip nil
     return make(_con==-1,bs);
   }
subtract()
Bits<B> com.cliffc.aa.type.Bits< B extends Bits< B >.subtract (Bits< B > bs) inherited
Definition at line 374 of file Bits.java.
{
     Bits<B> bs0 = this;
     for( int alias : this )
       for( int kid=alias; kid!=0; kid = tree().next_kid(alias,kid) )
         if( bs.test_recur(kid) )
           bs0 = bs0.clear(kid);
     return bs0;
   }
test() [1/2]
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.test (int i) inherited
Definition at line 226 of file Bits.java.
{
     if( _bits==null ) return i!=0 && i==Math.abs(_con);
     int idx = idx(i);
     return idx < _bits.length && test(_bits, i);
   }
test() [2/2]
static boolean com.cliffc.aa.type.Bits< B extends Bits< B >.test (long[] bits, int i) static private inherited
Definition at line 224 of file Bits.java.
 { return idx(i) < bits.length && (bits[idx(i)]&mask(i))!=0; }
test_recur()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.test_recur (int i) inherited
Definition at line 232 of file Bits.java.
{
     if( test(i) ) return true;
     Tree<B> tree = tree();
     while( (i = tree.parent(i)) != 0 )
       if( test(i) )
         return true;
     return false;
   }
toString()
String com.cliffc.aa.type.Bits< B extends Bits< B >.toString inherited
Definition at line 133 of file Bits.java.
 { return str(new SB()).toString(); }
tree()
Tree<BitsAlias> com.cliffc.aa.type.BitsAlias.tree ()
Definition at line 24 of file BitsAlias.java.
 { return TREE; }
References com.cliffc.aa.type.BitsAlias.TREE.
type_alias()
static int com.cliffc.aa.type.BitsAlias.type_alias (int par) static
Definition at line 76 of file BitsAlias.java.
 { return set_alias(par); }
References com.cliffc.aa.type.BitsAlias.set_alias().
Referenced by com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.type.TestType.testStructTuple(), com.cliffc.aa.Parse.tstmt(), and com.cliffc.aa.Parse.type0().
Member Data Documentation
_bits
long [] com.cliffc.aa.type.Bits< B extends Bits< B >._bits package inherited
Definition at line 68 of file Bits.java.
_con
int com.cliffc.aa.type.Bits< B extends Bits< B >._con package inherited
Definition at line 69 of file Bits.java.
_hash
int com.cliffc.aa.type.Bits< B extends Bits< B >._hash package inherited
Definition at line 70 of file Bits.java.
AARY
final int com.cliffc.aa.type.BitsAlias.AARY static package
Definition at line 25 of file BitsAlias.java.
Referenced by com.cliffc.aa.node.NewAryNode.NewAryNode(), com.cliffc.aa.node.TestNodeSmall.tmem(), com.cliffc.aa.Parse.typep(), com.cliffc.aa.node.LoadNode.unify(), and com.cliffc.aa.tvar.TV2.unify_alias_fld().
ABC
final int com.cliffc.aa.type.BitsAlias.ABC static package
Definition at line 25 of file BitsAlias.java.
Referenced by com.cliffc.aa.node.TestNodeSmall.tmem().
ALL
final int com.cliffc.aa.type.BitsAlias.ALL static
Definition at line 25 of file BitsAlias.java.
Referenced by com.cliffc.aa.type.TestType.testStructTuple(), and com.cliffc.aa.node.TestNodeSmall.tmem().
ANY
BitsAlias com.cliffc.aa.type.BitsAlias.ANY static package
Definition at line 27 of file BitsAlias.java.
ARY
final int com.cliffc.aa.type.BitsAlias.ARY static package
Definition at line 25 of file BitsAlias.java.
ARYBITS
BitsAlias com.cliffc.aa.type.BitsAlias.ARYBITS static package
Definition at line 27 of file BitsAlias.java.
ARYBITS0
BitsAlias com.cliffc.aa.type.BitsAlias.ARYBITS0 static package
Definition at line 26 of file BitsAlias.java.
Referenced by com.cliffc.aa.type.TypeMemPtr.widen().
EMPTY
BitsAlias com.cliffc.aa.type.BitsAlias.EMPTY static package
Definition at line 27 of file BitsAlias.java.
Referenced by com.cliffc.aa.node.LoadNode._find_previous_store_call(), com.cliffc.aa.node.MemSplitNode.add_alias(), com.cliffc.aa.type.TypeMem.aliases(), com.cliffc.aa.type.TypeMem.all_reaching_aliases(), com.cliffc.aa.type.TypeMem.and_unused(), com.cliffc.aa.node.MemJoinNode.can_bypass(), com.cliffc.aa.node.CallEpiNode.esc_out(), com.cliffc.aa.node.StoreNode.escapees(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.escapees(), com.cliffc.aa.node.LoadNode.find_previous_store(), com.cliffc.aa.node.CallNode.get_alias(), com.cliffc.aa.HM.HM9.Field.hm(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.type.TypeMemPtr.is_display_ptr(), com.cliffc.aa.type.TypeMem.ld(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.type.TypeMem.remove(), com.cliffc.aa.Env.top_reset(), and com.cliffc.aa.node.CallNode.value().
FREE
BitsAlias com.cliffc.aa.type.BitsAlias.FREE =null static private
Definition at line 12 of file BitsAlias.java.
Referenced by com.cliffc.aa.type.BitsAlias.make_impl().
FULL
BitsAlias com.cliffc.aa.type.BitsAlias.FULL static
Definition at line 27 of file BitsAlias.java.
Referenced by com.cliffc.aa.type.BitsAlias.ALL(), com.cliffc.aa.type.TypeMem.all_reaching_aliases(), com.cliffc.aa.node.PhiNode.escapees(), com.cliffc.aa.node.StoreNode.escapees(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.escapees(), com.cliffc.aa.node.MemSplitNode.escapees(), com.cliffc.aa.node.MemJoinNode.escapees(), com.cliffc.aa.node.CallEpiNode.escapees(), com.cliffc.aa.node.FunNode.find_type_split(), com.cliffc.aa.node.CallNode.get_alias(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.type.TypeMem.remove(), com.cliffc.aa.type.TypeMem.slice_reaching_aliases(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.HM.TestHM.test55(), com.cliffc.aa.HM.TestHM.test57(), and com.cliffc.aa.type.TypeMemPtr.widen().
INTERN
final HashMap<BitsAlias,BitsAlias> com.cliffc.aa.type.BitsAlias.INTERN = new HashMap<>() static private
Definition at line 11 of file BitsAlias.java.
Referenced by com.cliffc.aa.type.BitsAlias.make_impl().
NIL
BitsAlias com.cliffc.aa.type.BitsAlias.NIL static package
Definition at line 27 of file BitsAlias.java.
Referenced by com.cliffc.aa.HM.HM9.T2._fresh_unify(), com.cliffc.aa.type.TypeMem.all_reaching_aliases(), com.cliffc.aa.type.TypeMemPtr.ax_meet_nil(), com.cliffc.aa.node.StoreNode.ideal_grow(), com.cliffc.aa.type.TypeMemPtr.is_con(), com.cliffc.aa.type.TypeMem.ld(), and com.cliffc.aa.type.TypeMemPtr.meet_nil().
NZERO
BitsAlias com.cliffc.aa.type.BitsAlias.NZERO static package
Definition at line 27 of file BitsAlias.java.
Referenced by com.cliffc.aa.type.TypeMem.aliases(), com.cliffc.aa.node.CallEpiNode.esc_out(), and com.cliffc.aa.type.BitsAlias.make0().
REC
final int com.cliffc.aa.type.BitsAlias.REC static package
Definition at line 25 of file BitsAlias.java.
Referenced by com.cliffc.aa.node.IntrinsicNode.err(), com.cliffc.aa.type.TypeMemPtr.is_display_ptr(), com.cliffc.aa.node.NewObjNode.NewObjNode(), com.cliffc.aa.HM.HM9.PrimSyn.reset(), com.cliffc.aa.HM.HM.PrimSyn.reset(), com.cliffc.aa.HM.HM8.Struct.Struct(), com.cliffc.aa.HM.HM9.Struct.Struct(), com.cliffc.aa.HM.HM.Struct.Struct(), com.cliffc.aa.type.TestApprox.testApprox1(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox4(), com.cliffc.aa.type.TestApprox.testApprox5(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestApprox.testApprox7(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.node.TestNodeSmall.testMemoryArgs(), com.cliffc.aa.type.TestType.testNameCycle(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.type.TestType.testStructTuple(), com.cliffc.aa.type.TestApprox.testTSMeet(), com.cliffc.aa.node.TestNodeSmall.tmem(), com.cliffc.aa.Parse.tstmt(), com.cliffc.aa.Parse.type0(), and com.cliffc.aa.Parse.typep().
RECORD_BITS
BitsAlias com.cliffc.aa.type.BitsAlias.RECORD_BITS static
Definition at line 26 of file BitsAlias.java.
Referenced by com.cliffc.aa.node.IntrinsicNode.convertTypeName(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.type.TypeMemPtr.str(), and com.cliffc.aa.type.TestType.testNameCycle().
RECORD_BITS0
BitsAlias com.cliffc.aa.type.BitsAlias.RECORD_BITS0 static package
Definition at line 27 of file BitsAlias.java.
Referenced by com.cliffc.aa.type.TestApprox.testApprox7(), com.cliffc.aa.TestParse.testParse08(), and com.cliffc.aa.type.TypeMemPtr.widen().
STR
final int com.cliffc.aa.type.BitsAlias.STR static package
Definition at line 25 of file BitsAlias.java.
Referenced by com.cliffc.aa.node.NewStrNode.NewStrNode(), com.cliffc.aa.node.TestNodeSmall.tmem(), and com.cliffc.aa.Parse.typep().
STRBITS
BitsAlias com.cliffc.aa.type.BitsAlias.STRBITS static package
Definition at line 27 of file BitsAlias.java.
Referenced by com.cliffc.aa.HM.HM9.T2._as_flow(), com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM9.Str.apply(), com.cliffc.aa.HM.HM.Str.apply(), com.cliffc.aa.HM.HM9.string(), and com.cliffc.aa.HM.HM.string().
STRBITS0
BitsAlias com.cliffc.aa.type.BitsAlias.STRBITS0 static package
Definition at line 26 of file BitsAlias.java.
Referenced by com.cliffc.aa.type.TypeMemPtr.widen().
TREE
final Bits.Tree<BitsAlias> com.cliffc.aa.type.BitsAlias.TREE = new Bits.Tree<>() static package
Definition at line 23 of file BitsAlias.java.
Referenced by com.cliffc.aa.type.TypeMem._make1(), com.cliffc.aa.type.TypeMem.at_idx(), com.cliffc.aa.type.TypeMem.check(), com.cliffc.aa.type.BitsAlias.get_kids(), com.cliffc.aa.type.BitsAlias.init0(), com.cliffc.aa.type.BitsAlias.is_parent(), com.cliffc.aa.type.BitsAlias.next_kid(), com.cliffc.aa.type.BitsAlias.parent(), com.cliffc.aa.type.BitsAlias.reset_to_init0(), com.cliffc.aa.type.BitsAlias.set_alias(), and com.cliffc.aa.type.BitsAlias.tree().
XNIL
BitsAlias com.cliffc.aa.type.BitsAlias.XNIL static package
Definition at line 27 of file BitsAlias.java.
Referenced by com.cliffc.aa.type.TypeMemPtr.ax_meet_nil(), com.cliffc.aa.type.TypeMemPtr.is_con(), and com.cliffc.aa.type.TypeMemPtr.meet_nil().
The documentation for this class was generated from the following file:
BitsAlias.java