aa: com.cliffc.aa.HM.HM1.HMType Class Reference
com.cliffc.aa.HM.HM1.HMType Class Reference abstract
Public Member Functions
String str ()
final String toString ()
Package Functions
HMType _fresh (HashSet< HMVar > nongen, HashMap< HMType, HMType > vars)
abstract SB _str (SB sb, VBitSet vbs, boolean debug)
abstract HMType find ()
HMType fresh (HashSet< HMVar > nongen)
boolean is_top ()
boolean occurs_in (HashSet< HMVar >nongen)
boolean occurs_in (HMType[] args)
boolean occurs_in_type (HMType v)
abstract HMType union (HMType t)
Package Attributes
HMType _u
Detailed Description
Definition at line 158 of file HM1.java.
Member Function Documentation
_fresh()
HMType com.cliffc.aa.HM.HM1.HMType._fresh (HashSet< HMVar > nongen, HashMap< HMType, HMType > vars) package
Definition at line 171 of file HM1.java.
{
       HMType t2 = find();
       if( t2 instanceof HMVar ) {
         return t2.occurs_in(nongen) //
           ? t2                      // Keep same var
           : vars.computeIfAbsent(t2, e -> new HMVar(((HMVar)t2)._t));
       } else {
         Oper op = (Oper)t2;
         HMType[] args = new HMType[op._args.length];
         for( int i=0; i<args.length; i++ )
           args[i] = op._args[i]._fresh(nongen,vars);
         return new Oper(op._name,args);
       }
     }
References com.cliffc.aa.HM.HM1.Oper._args, com.cliffc.aa.HM.HM1.HMType._fresh(), com.cliffc.aa.HM.HM1.Oper._name, com.cliffc.aa.HM.HM1.HMType.find(), and com.cliffc.aa.HM.HM1.HMType.occurs_in().
Referenced by com.cliffc.aa.HM.HM1.HMType._fresh(), and com.cliffc.aa.HM.HM1.HMType.fresh().
_str()
abstract SB com.cliffc.aa.HM.HM1.HMType._str (SB sb, VBitSet vbs, boolean debug) abstract package
Reimplemented in com.cliffc.aa.HM.HM1.Oper, and com.cliffc.aa.HM.HM1.HMVar.
Referenced by com.cliffc.aa.HM.HM1.HMVar._str(), com.cliffc.aa.HM.HM1.Oper._str(), com.cliffc.aa.HM.HM1.HMType.str(), and com.cliffc.aa.HM.HM1.HMType.toString().
find()
abstract HMType com.cliffc.aa.HM.HM1.HMType.find () abstract package
Reimplemented in com.cliffc.aa.HM.HM1.Oper, and com.cliffc.aa.HM.HM1.HMVar.
Referenced by com.cliffc.aa.HM.HM1.HMType._fresh(), com.cliffc.aa.HM.HM1.HMType.occurs_in_type(), and com.cliffc.aa.HM.HM1.HMVar.union().
fresh()
HMType com.cliffc.aa.HM.HM1.HMType.fresh (HashSet< HMVar > nongen) package
Definition at line 167 of file HM1.java.
{
       HashMap<HMType,HMType> vars = new HashMap<>();
       return _fresh(nongen,vars);
     }
References com.cliffc.aa.HM.HM1.HMType._fresh().
Referenced by com.cliffc.aa.HM.HM1.Ident.hm().
is_top()
boolean com.cliffc.aa.HM.HM1.HMType.is_top () package
Definition at line 165 of file HM1.java.
 { return _u==null; }
References com.cliffc.aa.HM.HM1.HMType._u.
Referenced by com.cliffc.aa.HM.HM1.HMType.occurs_in_type(), and com.cliffc.aa.HM.HM1.HMVar.type().
occurs_in() [1/2]
boolean com.cliffc.aa.HM.HM1.HMType.occurs_in (HashSet< HMVar > nongen) package
Definition at line 186 of file HM1.java.
{
       for( HMVar x : nongen ) if( occurs_in_type(x) ) return true;
       return false;
     }
References com.cliffc.aa.HM.HM1.HMType.occurs_in_type().
Referenced by com.cliffc.aa.HM.HM1.HMType._fresh(), and com.cliffc.aa.HM.HM1.HMType.occurs_in_type().
occurs_in() [2/2]
boolean com.cliffc.aa.HM.HM1.HMType.occurs_in (HMType[] args) package
Definition at line 190 of file HM1.java.
{
       for( HMType x : args ) if( occurs_in_type(x) ) return true;
       return false;
     }
References com.cliffc.aa.HM.HM1.HMType.occurs_in_type().
occurs_in_type()
boolean com.cliffc.aa.HM.HM1.HMType.occurs_in_type (HMType v) package
Definition at line 194 of file HM1.java.
{
       assert is_top();
       HMType y = v.find();
       if( y==this )
         return true;
       if( y instanceof Oper )
         return occurs_in(((Oper)y)._args);
       return false;
     }
References com.cliffc.aa.HM.HM1.HMType.find(), com.cliffc.aa.HM.HM1.HMType.is_top(), and com.cliffc.aa.HM.HM1.HMType.occurs_in().
Referenced by com.cliffc.aa.HM.HM1.HMType.occurs_in(), and com.cliffc.aa.HM.HM1.HMVar.union().
str()
String com.cliffc.aa.HM.HM1.HMType.str ()
Definition at line 163 of file HM1.java.
 { return _str(new SB(),new VBitSet(),false).toString(); }
References com.cliffc.aa.HM.HM1.HMType._str(), and com.cliffc.aa.util.SB.toString().
toString()
final String com.cliffc.aa.HM.HM1.HMType.toString ()
Definition at line 162 of file HM1.java.
 { return _str(new SB(),new VBitSet(),true).toString(); }
References com.cliffc.aa.HM.HM1.HMType._str(), and com.cliffc.aa.util.SB.toString().
union()
abstract HMType com.cliffc.aa.HM.HM1.HMType.union (HMType t) abstract package
Reimplemented in com.cliffc.aa.HM.HM1.Oper, and com.cliffc.aa.HM.HM1.HMVar.
Referenced by com.cliffc.aa.HM.HM1.Apply.hm(), com.cliffc.aa.HM.HM1.HMVar.union(), and com.cliffc.aa.HM.HM1.Oper.union().
Member Data Documentation
_u
HMType com.cliffc.aa.HM.HM1.HMType._u package
Definition at line 159 of file HM1.java.
Referenced by com.cliffc.aa.HM.HM1.HMVar._str(), com.cliffc.aa.HM.HM1.HMVar.find(), com.cliffc.aa.HM.HM1.HMType.is_top(), and com.cliffc.aa.HM.HM1.HMVar.union().
The documentation for this class was generated from the following file:
HM1.java