aa: com.cliffc.aa.type.TypeTuple Class Reference
com.cliffc.aa.type.TypeTuple Class Reference
Public Member Functions
boolean above (Type t)
boolean above_center ()
Type at (int idx)
int compute_hash ()
final boolean contains (Type t)
boolean cycle_equals (Type o)
final T dual ()
boolean equals (Object o)
double getd ()
long getl ()
String getstr ()
boolean has_name ()
final int hashCode ()
Type high ()
boolean is_con ()
boolean is_display_ptr ()
boolean is_forward_ref ()
boolean isa (Type t)
final boolean isa_scalar ()
byte isBitShape (Type t)
Type join (Type t)
int len ()
Type make_from (Type head, TypeMem map, VBitSet visit)
TypeTuple make_from_arg (int idx, Type arg)
boolean may_be_con ()
boolean may_nil ()
final Type meet (Type t)
Type meet_loop (Type t2)
Type meet_nil (Type t)
boolean must_nil ()
Type oob ()
Type oob (Type e)
TypeMem oob (TypeMem e)
TypeMemPtr oob (TypeMemPtr e)
TypeObj oob (TypeObj e)
TypeStruct oob (TypeStruct e)
Type oob_deep (Type t)
Type oop_deep_impl (Type t)
final T remove_name ()
TypeTuple set (int idx, Type t)
final T set_name (String name)
Type sharptr (Type ptr)
TypeTuple sharptr (TypeMem mem)
Type simple_ptr ()
SB str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
final String toString ()
void walk (Predicate< Type > p)
TypeTuple widen ()
Static Public Member Functions
static Ary< Type > ALL_TYPES ()
static boolean eq (Type[] t0, Type[] t1)
static void init0 (HashMap< String, Type > types)
static boolean intern_check ()
static TypeTuple make ()
static TypeTuple make (Type t0, Type t1)
static TypeTuple make (Type t0, Type t1, Type t2)
static TypeTuple make (Type t0, Type t1, Type t2, Type t3)
static TypeTuple make (Type t0, Type t1, Type t2, Type t3, Type t4)
static TypeTuple make (Type t0, Type t1, Type t2, Type t3, Type t4, Type t5)
static TypeTuple make (Type[] ts)
static TypeTuple make (TypeStruct ts)
static TypeTuple make0 (boolean any, Type[] ts)
static TypeTuple make_args ()
static TypeTuple make_args (Type t2)
static TypeTuple make_args (Type t2, Type t3)
static TypeTuple make_args (Type t2, Type t3, Type t4)
static TypeTuple make_args (Type[] ts)
static TypeTuple make_ret (Type trez)
Public Attributes
int _hash
String _name
Type[] _ts
int _uid
Static Public Attributes
static final Type ALL
static final Type ANY
static final TypeTuple CALLE = make(CTRL, TypeMem.ALLMEM, ALL)
static final Type CTRL
static final TypeTuple FLT64 = make_args(TypeFlt.FLT64)
static final TypeTuple FLT64_FLT64 = make_args(TypeFlt.FLT64,TypeFlt.FLT64)
static final TypeTuple IF_ALL = make(CTRL ,CTRL)
static final TypeTuple IF_ANY = IF_ALL.dual()
static final TypeTuple IF_FALSE = make(CTRL ,XCTRL)
static final TypeTuple IF_TRUE = make(XCTRL,CTRL)
static final TypeTuple INT64 = make_args(TypeInt.INT64)
static final TypeTuple INT64_INT64 = make_args(TypeInt.INT64,TypeInt.INT64)
static final TypeTuple LVAL_LEN = make_args(TypeMemPtr.ARYPTR)
static final TypeTuple LVAL_RD = make_args(TypeMemPtr.ARYPTR,TypeInt.INT64)
static final TypeTuple LVAL_WR = make_args(TypeMemPtr.ARYPTR,TypeInt.INT64,Type.SCALAR)
static final Type NIL
static final TypeTuple NO_ARGS = make_args()
static final Type NSCALR
static final TypeTuple OOP_OOP = make_args(TypeMemPtr.ISUSED0,TypeMemPtr.ISUSED0)
static final Type REAL
static int RECURSIVE_MEET
static final TypeTuple RET = make(CTRL, TypeMem.ALLMEM, ALL)
static final Type SCALAR
static final TypeTuple SCALAR1 = make_args(SCALAR)
static final TypeTuple START_STATE = make(CTRL, TypeMem.EMPTY)
static final TypeTuple STRPTR = make_args(TypeMemPtr.STRPTR)
static final TypeTuple TEST0 = make(CTRL, TypeMem.MEM , TypeFunPtr.GENERIC_FUNPTR, SCALAR)
static final TypeTuple TEST1 = make(CTRL, TypeMem.EMPTY, TypeFunPtr.GENERIC_FUNPTR, SCALAR)
static final Type XCTRL
static final Type XNIL
static final Type XNSCALR
static final Type XSCALAR
Protected Member Functions
Type clone ()
TypeTuple init (boolean any, Type[] ts)
T init (byte type, String name)
TypeTuple xdual ()
Type xmeet (Type t)
Package Functions
boolean contains (Type t, VBitSet bs)
final Type cross_nil (Type t)
final T hashcons_free ()
boolean intern_check1 ()
Type intern_lookup ()
boolean interned ()
boolean is_display ()
final String mtname (Type t, Type mt)
Type not_nil ()
T rdual ()
TypeStruct repeats_in_cycles (TypeStruct head, VBitSet bs)
final T retern ()
RuntimeException typerr (Type t)
final T untern ()
Static Package Functions
[static initializer]
static boolean check_name (String n)
static boolean check_startup ()
static void concat (Ary< Type > ts, Type[] ts1)
static Type intern_find (int uid)
static int intern_size ()
static Type make (byte type)
Package Attributes
boolean _any
T _dual
byte _type
Static Package Attributes
static final Type NREAL
static final Pool[] POOLS
static final byte TALL
static final byte TANY
static final byte TARY
static final byte TCTRL
static final byte TFLD
static final byte TFLT
static final byte TFUNPTR
static final byte TFUNSIG
static final byte TINT
static final byte TLAST
static final byte TLIVE
static final byte TMEM
static final byte TMEMPTR
static final byte TNIL
static final byte TNREAL
static final byte TNSCALR
static final byte TOBJ
static final byte TREAL
static final byte TRPC
static final byte TSCALAR
static final byte TSIMPLE
static final byte TSTR
static final byte TSTRUCT
static final byte TTUPLE
static final byte TXCTRL
static final byte TXNIL
static final byte TXNREAL
static final byte TXNSCALR
static final byte TXREAL
static final byte TXSCALAR
static final TypeTuple[] TYPES
Private Member Functions
T _set_name (String name)
int _uid ()
boolean check_commute (Type t, Type mt)
boolean check_symmetric (Type t, Type mt)
T hashcons ()
boolean intern_check0 (Type v)
boolean is_num ()
boolean is_ptr ()
boolean is_simple ()
TypeTuple xmeet1 (TypeTuple tmax)
Type xmt_name (Type t, Type mt)
Static Private Member Functions
static TypeTuple make (boolean any, Type[] ts)
static int rot (int x, int k)
Static Private Attributes
static Ary< Type > ALL_TYPES
static int CNT
static final ConcurrentHashMap< Type, Type > INTERN
static final byte[] ISA_SCALAR
static Type[] SCALAR_PRIMS
static final String[] STRS
static final Type XNREAL
static final Type XREAL
Detailed Description
Definition at line 11 of file TypeTuple.java.
Member Function Documentation
[static initializer]()
com.cliffc.aa.type.TypeTuple.[static initializer] static package
_set_name()
T com.cliffc.aa.type.Type< T extends Type< T >._set_name (String name) private inherited
Definition at line 558 of file Type.java.
{
     POOLS[_type]._clone++;
     T t1 = (T)clone();
     t1._name = name;
     return t1.hashcons_free();
   }
_uid()
int com.cliffc.aa.type.Type< T extends Type< T >._uid private inherited
Definition at line 103 of file Type.java.
 { return CNT++; }
above()
boolean com.cliffc.aa.type.Type< T extends Type< T >.above (Type< TypeTuple > t) inherited
Definition at line 625 of file Type.java.
 { return t != this && meet(t)==t; }
above_center()
boolean com.cliffc.aa.type.TypeTuple.above_center ()
Definition at line 193 of file TypeTuple.java.
 { return _any; }
References com.cliffc.aa.type.TypeTuple._any.
Referenced by com.cliffc.aa.type.TypeFunSig.above_center().
ALL_TYPES()
static Ary<Type> com.cliffc.aa.type.Type< T extends Type< T >.ALL_TYPES static inherited
Definition at line 651 of file Type.java.
{
     if( ALL_TYPES != null ) return ALL_TYPES;
     Ary<Type> ts = new Ary<>(new Type[1],0);
     concat(ts,Type      .TYPES);
     concat(ts,TypeFlt   .TYPES);
     concat(ts,TypeFunPtr.TYPES);
     concat(ts,TypeFunSig.TYPES);
     concat(ts,TypeInt   .TYPES);
     concat(ts,TypeLive  .TYPES);
     concat(ts,TypeMem   .TYPES);
     concat(ts,TypeMemPtr.TYPES);
     concat(ts,TypeObj   .TYPES);
     concat(ts,TypeRPC   .TYPES);
     concat(ts,TypeStr   .TYPES);
     concat(ts,TypeStruct.TYPES);
     concat(ts,TypeTuple .TYPES);
     concat(ts,TypeAry   .TYPES);
     // Partial order Sort, makes for easier tests later.  Arrays.sort requires
     // a total order (i.e., the obvious Comparator breaks the sort contract),
     // so we hand-roll a simple bubble sort.
     for( int i=0; i<ts._len; i++ )
       for( int j=i+1; j<ts._len; j++ )
         if( ts._es[j].isa(ts._es[i]) ) { Type tmp = ts._es[i]; ts._es[i] = ts._es[j]; ts._es[j] = tmp; }
     return (ALL_TYPES = ts); // Preserve for tests
   }
at()
Type com.cliffc.aa.type.TypeTuple.at (int idx)
Definition at line 182 of file TypeTuple.java.
 { return _ts[idx]; } // Must be in-size
References com.cliffc.aa.type.TypeTuple._ts.
Referenced by com.cliffc.aa.tvar.TV2._find_tvar(), com.cliffc.aa.node.TestNodeSmall._testMonotonicChain(), com.cliffc.aa.node.PrimNode.ConvertTypeName.apply(), com.cliffc.aa.node.FunNode.bad_mem_use(), com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.node.CallNode.escapees(), com.cliffc.aa.node.CEProjNode.good_call(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.IntrinsicNode.ideal_reduce(), com.cliffc.aa.node.FunNode.ideal_reduce(), com.cliffc.aa.type.TypeFunSig.init(), com.cliffc.aa.node.CallNode.least_cost(), com.cliffc.aa.node.PrimNode.PrimNode(), com.cliffc.aa.GVNGCM.retype_mem(), com.cliffc.aa.node.CallNode.tesc(), com.cliffc.aa.node.CallNode.ttfp(), com.cliffc.aa.node.CallNode.ttfpx(), com.cliffc.aa.node.MProjNode.value(), com.cliffc.aa.node.PrimNode.value(), and com.cliffc.aa.node.PrimNode.xstr().
check_commute()
boolean com.cliffc.aa.type.Type< T extends Type< T >.check_commute (Type< TypeTuple > t, Type< TypeTuple > mt) private inherited
Definition at line 593 of file Type.java.
{
     if( t==this ) return true;
     if( is_simple() && !t.is_simple() ) return true; // By design, flipped the only allowed order
     Type mt2 = t.xmeet(this);   // Reverse args and try again
     // Also reverse names.
     Type nmt2 = t.xmt_name(this,mt2);
     if( mt==nmt2 ) return true;
     System.out.println("Meet not commutative: "+this+".meet("+t+")="+mt+",\n but "+t+".meet("+this+")="+nmt2);
     return false;
   }
check_name()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.check_name (String n) static package inherited
Definition at line 548 of file Type.java.
 { return n.isEmpty() || n.charAt(n.length()-1)==':'; }
check_startup()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.check_startup static package inherited
Definition at line 684 of file Type.java.
{
     Type[] ts = ALL_TYPES().asAry();
     // Confirm commutative & complete
     for( Type t0 : ts )
       for( Type t1 : ts ) {
         Type mt = t0.meet(t1);
         assert t0.check_commute  (t1,mt);
         assert t0.check_symmetric(t1,mt);
       }
     // Confirm associative
     int errs=0;
     for( Type t0 : ts )
       for( Type t1 : ts )
         for( Type t2 : ts ) {
           Type t01   = t0 .meet(t1 );
           Type t12   = t1 .meet(t2 );
           Type t01_2 = t01.meet(t2 );
           Type t0_12 = t0 .meet(t12);
           if( t01_2 != t0_12 && errs++ < 10 )
             System.err.println("("+t0+"&"+t1+") & "+t2+" == "+t0+" & ("+t1+" & "+t2+"); "+
                                "("+t01      +") & "+t2+" == "+t0+" & ("+t12        +"); "+
                                t01_2                  +" == "+t0_12);
         }
     assert errs==0 : "Found "+errs+" associative errors";
     // Confirm symmetry.  If A isa B, then A.join(C) isa B.join(C)
     for( Type t0 : ts )
       for( Type t1 : ts ) {
         if( t0.isa(t1) ) {
           for( Type t2 : ts ) {
             Type t02 = t0.join(t2);
             Type t12 = t1.join(t2);
             Type mt  = t02.meet(t12);
             if( mt != t12 && errs++ < 10 ) {
               System.err.println("("+t0+" ^ "+t2+") = "+t02+"; "+
                                  "("+t1+" ^ "+t2+") = "+t12+"; "+
                                  "their meet = "+mt+" which is not "+t12);
             }
           }
         }
       }
     assert errs==0 : "Found "+errs+" non-join-type errors";
     // Check scalar primitives; all are SCALARS and none sub-type each other.
     SCALAR_PRIMS = new Type[] { TypeInt.INT64, TypeFlt.FLT64, TypeMemPtr.OOP0, TypeFunPtr.GENERIC_FUNPTR, TypeRPC.ALL_CALL };
     for( Type t : SCALAR_PRIMS ) assert t.isa(SCALAR);
     for( int i=0; i<SCALAR_PRIMS.length; i++ )
       for( int j=i+1; j<SCALAR_PRIMS.length; j++ )
         assert !SCALAR_PRIMS[i].isa(SCALAR_PRIMS[j]);
     return true;
   }
check_symmetric()
boolean com.cliffc.aa.type.Type< T extends Type< T >.check_symmetric (Type< TypeTuple > t, Type< TypeTuple > mt) private inherited
Definition at line 608 of file Type.java.
{
     if( t==this ) return true;
     Type ta = mt._dual.meet(t._dual);
     Type tb = mt._dual.meet(  _dual);
     if( ta==t._dual && tb==_dual ) return true;
     System.err.print("("+this+" & "+t+")=="+mt+" but \n("+mt._dual+" & ");
     if( ta!=t._dual ) System.err.println(t._dual+")=="+ta+" \nwhich is not "+t._dual);
     else              System.err.println(  _dual+")=="+tb+" \nwhich is not "+  _dual);
     return false;
   }
clone()
Type com.cliffc.aa.type.Type< T extends Type< T >.clone protected inherited
Definition at line 304 of file Type.java.
{
     try {
       POOLS[_type]._clone++;
       Type t = (Type)super.clone();
       t._uid = _uid();
       t._dual = null;
       t._hash = 0;
       if( t instanceof TypeStruct )
         ((TypeStruct)t)._cyclic = false;
       return t;
     }
     catch( CloneNotSupportedException cns ) { throw new RuntimeException(cns); }
   }
compute_hash()
int com.cliffc.aa.type.TypeTuple.compute_hash ()
Definition at line 25 of file TypeTuple.java.
{
     int hash = TTUPLE+(_any?0:1);
     // Copied from http://burtleburtle.net/bob/c/lookup3.c
     int i,a,b,c;
     a = b = c = 0xdeadbeef + (_ts.length<<2) + hash;
     for( i=0; i+2<_ts.length; i+=3 ) {
       a += _ts[i+0]._hash;
       b += _ts[i+1]._hash;
       c += _ts[i+2]._hash;
       a -= c;  a ^= rot(c, 4);  c += b;
       b -= a;  b ^= rot(a, 6);  a += c;
       c -= b;  c ^= rot(b, 8);  b += a;
       a -= c;  a ^= rot(c,16);  c += b;
       b -= a;  b ^= rot(a,19);  a += c;
       c -= b;  c ^= rot(b, 4);  b += a;
     }
     switch(_ts.length-i) {
     case 3: c += _ts[i+2]._hash;
     case 2: b += _ts[i+1]._hash;
     case 1: a += _ts[i+0]._hash;
       c ^= b; c -= rot(b,14);
       a ^= c; a -= rot(c,11);
       b ^= a; b -= rot(a,25);
       c ^= b; c -= rot(b,16);
       a ^= c; a -= rot(c, 4);
       b ^= a; b -= rot(a,14);
       c ^= b; c -= rot(b,24);
     case 0:
       break;
     }
     return c;
   }
References com.cliffc.aa.type.TypeTuple._any, com.cliffc.aa.type.Type< T extends Type< T >._hash, com.cliffc.aa.type.TypeTuple._ts, com.cliffc.aa.type.TypeTuple.rot(), and com.cliffc.aa.type.Type< TypeTuple >.TTUPLE.
concat()
static void com.cliffc.aa.type.Type< T extends Type< T >.concat (Ary< Type< TypeTuple > > ts, Type< TypeTuple >[] ts1) static package inherited
Definition at line 676 of file Type.java.
{
     for( Type t1 : ts1 ) {
       assert !t1.above_center(); // Always below-center or equal, because we'll dual anyways
       ts.push(t1);
       if( t1!=t1.dual() ) ts.push(t1.dual());
     }
   }
contains() [1/2]
final boolean com.cliffc.aa.type.Type< T extends Type< T >.contains (Type< TypeTuple > t) inherited
Definition at line 926 of file Type.java.
 { return contains(t,null); }
contains() [2/2]
boolean com.cliffc.aa.type.Type< T extends Type< T >.contains (Type< TypeTuple > t, VBitSet bs) package inherited
Definition at line 927 of file Type.java.
 { return this==t; }
cross_nil()
final Type com.cliffc.aa.type.Type< T extends Type< T >.cross_nil (Type< TypeTuple > t) package inherited
Definition at line 865 of file Type.java.
 { return must_nil() || t.must_nil() ? SCALAR : NSCALR; }
cycle_equals()
boolean com.cliffc.aa.type.TypeTuple.cycle_equals (Type o)
Definition at line 64 of file TypeTuple.java.
 { return equals(o); }
References com.cliffc.aa.type.TypeTuple.equals().
dual()
final T com.cliffc.aa.type.Type< T extends Type< T >.dual inherited
Definition at line 361 of file Type.java.
 { return _dual; }
eq()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.eq (Type< TypeTuple >[] t0, Type< TypeTuple >[] t1) static inherited
Definition at line 136 of file Type.java.
{
     if( t0==t1 ) return true;
     if( t0==null || t1==null ) return false;
     if( t0.length != t1.length ) return false;
     for( int i=0; i<t0.length; i++ )
       if( t0[i] != t1[i] )
         return false;
     return true;
   }
equals()
boolean com.cliffc.aa.type.TypeTuple.equals (Object o)
Definition at line 57 of file TypeTuple.java.
{
     if( this==o ) return true;
     if( !(o instanceof TypeTuple) ) return false;
     TypeTuple t = (TypeTuple)o;
     return _any==t._any && _hash == t._hash && Types.eq(_ts,t._ts);
   }
References com.cliffc.aa.type.TypeTuple._any, com.cliffc.aa.type.Type< TypeTuple >._hash, com.cliffc.aa.type.Type< T extends Type< T >._hash, com.cliffc.aa.type.TypeTuple._ts, and com.cliffc.aa.type.Types.eq().
Referenced by com.cliffc.aa.type.TypeTuple.cycle_equals().
getd()
double com.cliffc.aa.type.Type< T extends Type< T >.getd inherited
Definition at line 804 of file Type.java.
 { if( _type==TNIL || _type==TXNIL ) return 0.0; throw typerr(null); }
getl()
long com.cliffc.aa.type.Type< T extends Type< T >.getl inherited
Definition at line 802 of file Type.java.
 { if( _type==TNIL || _type==TXNIL ) return 0; throw typerr(null); }
getstr()
String com.cliffc.aa.type.Type< T extends Type< T >.getstr inherited
Definition at line 806 of file Type.java.
 { throw typerr(null); }
has_name()
boolean com.cliffc.aa.type.Type< T extends Type< T >.has_name inherited
Definition at line 549 of file Type.java.
 { return !_name.isEmpty(); }
hashCode()
final int com.cliffc.aa.type.Type< T extends Type< T >.hashCode inherited
Definition at line 106 of file Type.java.
 { assert _hash!=0; return _hash; }
hashcons()
T com.cliffc.aa.type.Type< T extends Type< T >.hashcons private inherited
Definition at line 165 of file Type.java.
{
     _hash = compute_hash();     // Set hash
     T t2 = (T)INTERN.get(this); // Lookup
     if( t2!=null ) {            // Found prior
       assert t2._dual != null;  // Prior is complete with dual
       assert this != t2;        // Do not hashcons twice, should not get self back
       return t2;                // Return prior
     }
     if( RECURSIVE_MEET > 0 )    // Mid-building recursive types; do not intern
       return (T)this;
     // Not in type table
     _dual = null;                // No dual yet
     INTERN.put(this,this);       // Put in table without dual
     T d = xdual();               // Compute dual without requiring table lookup, and not setting name
     d._name = _name;             // xdual does not set name either
     d._hash = d.compute_hash();  // Set dual hash
     _dual = d;
     if( this==d ) return d;      // Self-symmetric?  Dual is self
     assert !equals(d);           // Self-symmetric is handled by caller
     assert d._dual==null;        // Else dual-dual not computed yet
     assert INTERN.get(d)==null;
     d._dual = (T)this;
     INTERN.put(d,d);
     return (T)this;
   }
hashcons_free()
final T com.cliffc.aa.type.Type< T extends Type< T >.hashcons_free package inherited
Definition at line 153 of file Type.java.
{
     T t2 = hashcons();
     return this==t2 ? t2 : (T)POOLS[_type].free(this,t2);
   }
high()
Type com.cliffc.aa.type.Type< T extends Type< T >.high inherited
Definition at line 796 of file Type.java.
 { return above_center() ? this : dual(); }
init() [1/2]
TypeTuple com.cliffc.aa.type.TypeTuple.init (boolean any, Type[] ts) protected
Definition at line 14 of file TypeTuple.java.
{
     super.init(TTUPLE,"");
     _any = any;
     _ts = ts;
     return this;
   }
References com.cliffc.aa.type.TypeTuple._any, com.cliffc.aa.type.TypeTuple._ts, com.cliffc.aa.type.TypeTuple.init(), and com.cliffc.aa.type.Type< TypeTuple >.TTUPLE.
Referenced by com.cliffc.aa.type.TypeTuple.init(), com.cliffc.aa.type.TypeTuple.make(), and com.cliffc.aa.type.TypeTuple.xdual().
init() [2/2]
T com.cliffc.aa.type.Type< T extends Type< T >.init (byte type, String name) protected inherited
Definition at line 105 of file Type.java.
 { _type=type; _name=name; return (T)this; }
init0()
static void com.cliffc.aa.type.Type< T extends Type< T >.init0 (HashMap< String, Type< TypeTuple > > types) static inherited
Definition at line 642 of file Type.java.
{
     types.put("real",REAL);
     types.put("scalar",SCALAR);
     TypeInt.init1(types);
     TypeFlt.init1(types);
     TypeStr.init1(types);
   }
intern_check()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check static inherited
Definition at line 212 of file Type.java.
{
     int errs=0;
     for( Type k : INTERN.keySet() ) {
       Type v = INTERN.get(k);
       if( !k.intern_check0(v) ) {
         System.out.println("INTERN_CHECK FAIL: "+k._uid+":"+k+" vs "+v._uid+":"+v);
         errs++;
       }
     }
     return errs==0;
   }
intern_check0()
boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check0 (Type< TypeTuple > v) private inherited
Definition at line 223 of file Type.java.
{
     if( this != v || _dual==null || _dual._dual!=this || compute_hash()!=_hash ) return false;
     return intern_check1();
   }
intern_check1()
boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check1 package inherited
Definition at line 227 of file Type.java.
 { return true; }
intern_find()
static Type com.cliffc.aa.type.Type< T extends Type< T >.intern_find (int uid) static package inherited
Definition at line 229 of file Type.java.
{
     for( Type k : INTERN.keySet() )
       if( k._uid==uid )
         return k;
     return null;
   }
intern_lookup()
Type com.cliffc.aa.type.Type< T extends Type< T >.intern_lookup package inherited
Definition at line 210 of file Type.java.
 { return INTERN.get(this); }
intern_size()
static int com.cliffc.aa.type.Type< T extends Type< T >.intern_size static package inherited
Definition at line 211 of file Type.java.
 { return INTERN.size(); }
interned()
boolean com.cliffc.aa.type.Type< T extends Type< T >.interned package inherited
Definition at line 209 of file Type.java.
 { return INTERN.get(this)==this; }
is_con()
boolean com.cliffc.aa.type.TypeTuple.is_con ()
Definition at line 200 of file TypeTuple.java.
{
     for( Type _t : _ts ) if( !_t.is_con() ) return false;
     return true;
   }
References com.cliffc.aa.type.TypeTuple._ts.
is_display()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_display package inherited
Definition at line 942 of file Type.java.
 { return false; }
is_display_ptr()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_display_ptr inherited
Definition at line 941 of file Type.java.
 { return _type==TSCALAR || _type==TXSCALAR || _type==TNIL || _type==TXNIL || _type==TANY || _type==TALL; }
is_forward_ref()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_forward_ref inherited
Definition at line 799 of file Type.java.
 { return false; }
is_num()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_num private inherited
Definition at line 353 of file Type.java.
 { byte t = _type;  return t == TREAL || t == TXREAL || t == TNREAL || t == TXNREAL || t == TINT || t == TFLT; }
is_ptr()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_ptr private inherited
Definition at line 352 of file Type.java.
 { byte t = _type;  return t == TFUNPTR || t == TMEMPTR; }
is_simple()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_simple private inherited
Definition at line 351 of file Type.java.
 { return _type < TSIMPLE; }
isa()
boolean com.cliffc.aa.type.Type< T extends Type< T >.isa (Type< TypeTuple > t) inherited
Definition at line 623 of file Type.java.
 { return meet(t)==t; }
isa_scalar()
final boolean com.cliffc.aa.type.Type< T extends Type< T >.isa_scalar inherited
Definition at line 356 of file Type.java.
 { assert ISA_SCALAR.length==TLAST; return ISA_SCALAR[_type]!=0; }
isBitShape()
byte com.cliffc.aa.type.TypeTuple.isBitShape (Type t)
Definition at line 229 of file TypeTuple.java.
{
     if( isa(t) ) return 0; // Can choose compatible format
     if( t instanceof TypeTuple ) {
       TypeTuple tt = (TypeTuple)t;
       if( tt._ts.length != _ts.length ) return 99;
       byte x;
       for( int i=0; i<_ts.length; i++ )
         if( (x=_ts[i].isBitShape(tt._ts[i])) != 0 )
           return x;
       return 0;
     }
     return 99;
   }
References com.cliffc.aa.type.TypeTuple._ts, and com.cliffc.aa.type.Type< TypeTuple >.isa().
join()
Type com.cliffc.aa.type.Type< T extends Type< T >.join (Type< TypeTuple > t) inherited
Definition at line 619 of file Type.java.
 { return dual().meet(t.dual()).dual(); }
len()
int com.cliffc.aa.type.TypeTuple.len ()
Definition at line 183 of file TypeTuple.java.
 { return _ts.length; }
References com.cliffc.aa.type.TypeTuple._ts.
Referenced by com.cliffc.aa.tvar.TV2._find_tvar(), com.cliffc.aa.node.CEProjNode.good_call(), com.cliffc.aa.type.TypeFunSig.init(), com.cliffc.aa.node.CallNode.set_ttfp(), com.cliffc.aa.node.CallNode.tesc(), com.cliffc.aa.node.CallNode.ttfp(), com.cliffc.aa.node.CallNode.ttfpx(), and com.cliffc.aa.type.TypeTuple.xmeet1().
make() [1/10]
static TypeTuple com.cliffc.aa.type.TypeTuple.make () static
Definition at line 89 of file TypeTuple.java.
 { return make0(false,Types.get(0)); }
References com.cliffc.aa.type.Types.get(), and com.cliffc.aa.type.TypeTuple.make0().
Referenced by com.cliffc.aa.type.TypeTuple.make(), com.cliffc.aa.type.TypeTuple.make0(), com.cliffc.aa.type.TypeTuple.make_args(), com.cliffc.aa.type.TypeTuple.make_ret(), com.cliffc.aa.type.TypeTuple.set(), and com.cliffc.aa.type.TypeTuple.widen().
make() [2/10]
static TypeTuple com.cliffc.aa.type.TypeTuple.make (boolean any, Type[] ts) static private
Definition at line 82 of file TypeTuple.java.
{
     TypeTuple t1 = POOLS[TTUPLE].malloc();
     return t1.init(any,ts).hashcons_free();
   }
References com.cliffc.aa.type.Type< T extends Type< T >.hashcons_free(), com.cliffc.aa.type.TypeTuple.init(), com.cliffc.aa.type.Type< TypeTuple >.POOLS, and com.cliffc.aa.type.Type< TypeTuple >.TTUPLE.
Referenced by com.cliffc.aa.node.NewStrNode.AddStrStr._value(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.node.MemSplitNode.value(), com.cliffc.aa.node.NewStrNode.AddStrStr.value(), com.cliffc.aa.node.NewNode< TypeStruct >.value(), com.cliffc.aa.node.RetNode.value(), com.cliffc.aa.node.CallEpiNode.value(), and com.cliffc.aa.node.CallNode.value().
make() [3/10]
static Type com.cliffc.aa.type.Type< T extends Type< T >.make (byte type) static package inherited
Definition at line 147 of file Type.java.
{
     Pool P = POOLS[type];
     Type t1 = P.malloc();
     return t1.init(type,"").hashcons_free();
   }
make() [4/10]
static TypeTuple com.cliffc.aa.type.TypeTuple.make (Type t0, Type t1) static
Definition at line 90 of file TypeTuple.java.
 { return make0(false,Types.ts(t0,t1)); }
References com.cliffc.aa.type.TypeTuple.make0(), and com.cliffc.aa.type.Types.ts().
make() [5/10]
static TypeTuple com.cliffc.aa.type.TypeTuple.make (Type t0, Type t1, Type t2) static
Definition at line 91 of file TypeTuple.java.
 { return make0(false,Types.ts(t0,t1,t2)); }
References com.cliffc.aa.type.TypeTuple.make0(), and com.cliffc.aa.type.Types.ts().
make() [6/10]
static TypeTuple com.cliffc.aa.type.TypeTuple.make (Type t0, Type t1, Type t2, Type t3) static
Definition at line 92 of file TypeTuple.java.
 { return make0(false,Types.ts(t0,t1,t2,t3)); }
References com.cliffc.aa.type.TypeTuple.make0(), and com.cliffc.aa.type.Types.ts().
make() [7/10]
static TypeTuple com.cliffc.aa.type.TypeTuple.make (Type t0, Type t1, Type t2, Type t3, Type t4) static
Definition at line 93 of file TypeTuple.java.
 { return make0(false,Types.ts(t0,t1,t2,t3,t4)); }
References com.cliffc.aa.type.TypeTuple.make0(), and com.cliffc.aa.type.Types.ts().
make() [8/10]
static TypeTuple com.cliffc.aa.type.TypeTuple.make (Type t0, Type t1, Type t2, Type t3, Type t4, Type t5) static
Definition at line 94 of file TypeTuple.java.
 { return make0(false,Types.ts(t0,t1,t2,t3,t4,t5)); }
References com.cliffc.aa.type.TypeTuple.make0(), and com.cliffc.aa.type.Types.ts().
make() [9/10]
static TypeTuple com.cliffc.aa.type.TypeTuple.make (Type[] ts) static
Definition at line 88 of file TypeTuple.java.
 { return make0(false,ts); }
References com.cliffc.aa.type.TypeTuple.make0().
make() [10/10]
static TypeTuple com.cliffc.aa.type.TypeTuple.make (TypeStruct ts) static
Definition at line 97 of file TypeTuple.java.
{
     // TypeStruct includes a display/DSP_IDX, but what comes before
     Type[] ts2 = Types.get(ts.len()+DSP_IDX);
     ts2[CTL_IDX] = Type.CTRL;
     ts2[MEM_IDX] = TypeMem.ALLMEM;
     for( int i=0; i<ts.len(); i++ )
       ts2[DSP_IDX+i] = ts.at(i);
     return make(ts2);
   }
References com.cliffc.aa.type.TypeMem.ALLMEM, com.cliffc.aa.type.TypeStruct.at(), com.cliffc.aa.type.Type< T extends Type< T >.CTRL, com.cliffc.aa.type.Types.get(), com.cliffc.aa.type.TypeStruct.len(), and com.cliffc.aa.type.TypeTuple.make().
make0()
static TypeTuple com.cliffc.aa.type.TypeTuple.make0 (boolean any, Type[] ts) static
Definition at line 87 of file TypeTuple.java.
 { return make(any,Types.hash_cons(ts)); }
References com.cliffc.aa.type.Types.hash_cons(), and com.cliffc.aa.type.TypeTuple.make().
Referenced by com.cliffc.aa.type.TypeTuple.make(), com.cliffc.aa.type.TypeTuple.make_from_arg(), com.cliffc.aa.type.TypeTuple.sharptr(), com.cliffc.aa.type.TypeTuple.simple_ptr(), and com.cliffc.aa.type.TypeTuple.xmeet1().
make_args() [1/5]
static TypeTuple com.cliffc.aa.type.TypeTuple.make_args () static
Definition at line 116 of file TypeTuple.java.
 { return make(Type.CTRL,TypeMem.ALLMEM,Type.ALL ); }
References com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.type.TypeMem.ALLMEM, com.cliffc.aa.type.Type< T extends Type< T >.CTRL, and com.cliffc.aa.type.TypeTuple.make().
make_args() [2/5]
static TypeTuple com.cliffc.aa.type.TypeTuple.make_args (Type t2) static
Definition at line 117 of file TypeTuple.java.
 { return make(Type.CTRL,TypeMem.ALLMEM,Type.ALL,t2); }
References com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.type.TypeMem.ALLMEM, com.cliffc.aa.type.Type< T extends Type< T >.CTRL, and com.cliffc.aa.type.TypeTuple.make().
make_args() [3/5]
static TypeTuple com.cliffc.aa.type.TypeTuple.make_args (Type t2, Type t3) static
Definition at line 118 of file TypeTuple.java.
 { return make(Type.CTRL,TypeMem.ALLMEM,Type.ALL,t2,t3); }
References com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.type.TypeMem.ALLMEM, com.cliffc.aa.type.Type< T extends Type< T >.CTRL, and com.cliffc.aa.type.TypeTuple.make().
make_args() [4/5]
static TypeTuple com.cliffc.aa.type.TypeTuple.make_args (Type t2, Type t3, Type t4) static
Definition at line 119 of file TypeTuple.java.
 { return make(Type.CTRL,TypeMem.ALLMEM,Type.ALL,t2,t3,t4); }
References com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.type.TypeMem.ALLMEM, com.cliffc.aa.type.Type< T extends Type< T >.CTRL, and com.cliffc.aa.type.TypeTuple.make().
make_args() [5/5]
static TypeTuple com.cliffc.aa.type.TypeTuple.make_args (Type[] ts) static
Definition at line 106 of file TypeTuple.java.
{
     assert ts[MEM_IDX] instanceof TypeMem && ts[DSP_IDX].is_display_ptr();
     return make(ts);
   }
References com.cliffc.aa.type.Type< T extends Type< T >.is_display_ptr(), and com.cliffc.aa.type.TypeTuple.make().
Referenced by com.cliffc.aa.HM.HM9.Root.add_sig(), com.cliffc.aa.HM.HM.Root.add_sig(), com.cliffc.aa.node.IntrinsicNode.convertTypeName(), com.cliffc.aa.node.PrimNode.ConvertTypeName.ConvertTypeName(), com.cliffc.aa.node.FunNode.FunNode(), com.cliffc.aa.node.PrimNode.Id.Id(), com.cliffc.aa.type.TypeFunSig.make(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.NewPrimNode(), com.cliffc.aa.node.TestNodeSmall.testMemoryArgs(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.HM.TestHM.tfs(), com.cliffc.aa.HM.TestHM9.tfs(), com.cliffc.aa.Parse.type0(), and com.cliffc.aa.node.FunNode.type_special().
make_from()
Type com.cliffc.aa.type.Type< T extends Type< T >.make_from (Type< TypeTuple > head, TypeMem map, VBitSet visit) inherited
Definition at line 945 of file Type.java.
 { return this; }
make_from_arg()
TypeTuple com.cliffc.aa.type.TypeTuple.make_from_arg (int idx, Type arg)
Definition at line 110 of file TypeTuple.java.
{
     Type[] ts = Types.clone(_ts);
     ts[idx]=arg;
     return make0(_any,ts);
   }
References com.cliffc.aa.type.TypeTuple._any, com.cliffc.aa.type.TypeTuple._ts, com.cliffc.aa.type.Types.clone(), and com.cliffc.aa.type.TypeTuple.make0().
Referenced by com.cliffc.aa.type.TypeFunSig.make_from_arg().
make_ret()
static TypeTuple com.cliffc.aa.type.TypeTuple.make_ret (Type trez) static
Definition at line 120 of file TypeTuple.java.
 { return make(Type.CTRL,TypeMem.ANYMEM,trez); }
References com.cliffc.aa.type.TypeMem.ANYMEM, com.cliffc.aa.type.Type< T extends Type< T >.CTRL, and com.cliffc.aa.type.TypeTuple.make().
Referenced by com.cliffc.aa.HM.HM9.Root.add_sig(), com.cliffc.aa.HM.HM.Root.add_sig(), com.cliffc.aa.node.IntrinsicNode.convertTypeName(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.node.PrimNode.PrimNode(), com.cliffc.aa.HM.TestHM.tfs(), com.cliffc.aa.HM.TestHM9.tfs(), and com.cliffc.aa.Parse.type0().
may_be_con()
boolean com.cliffc.aa.type.TypeTuple.may_be_con ()
Definition at line 195 of file TypeTuple.java.
{
     for( Type _t : _ts ) if( !_t.may_be_con() ) return false;
     return true;
   }
References com.cliffc.aa.type.TypeTuple._ts.
may_nil()
boolean com.cliffc.aa.type.Type< T extends Type< T >.may_nil inherited
Definition at line 869 of file Type.java.
{
     switch(_type) {
     case TALL:
     case TREAL:
     case TSCALAR:
     case TXNSCALR: case TNSCALR:
     case TXNREAL:  case TNREAL:
     case TTUPLE:
       return false;
     case TANY:
     case TXREAL:
     case TXSCALAR:
     case TCTRL:  // Nonsense, only for IfNode.value test
     case TXCTRL: // Nonsense, only for IfNode.value test
     case TMEM:   // Nonsense, only for IfNode.value test
       return true;
     default: throw typerr(null); // Overridden in subclass
     }
   }
meet()
final Type com.cliffc.aa.type.Type< T extends Type< T >.meet (Type< TypeTuple > t) inherited
Definition at line 412 of file Type.java.
{
     // Short cut for the self case
     if( t == this ) return this;
     // Short-cut for seeing this meet before
     Type mt = Key.get(this,t);
     if( mt != null ) return mt;
     // "Triangulate" the matrix and cut in half the number of cases.
     // Reverse; xmeet 2nd arg is never "is_simple" and never equal to "this".
     // This meet ignores the _name field, and can return any-old name it wants.
     mt = !is_simple() && t.is_simple() ? t.xmeet(this) : xmeet(t);
     // Meet the names.  Subclasses basically ignore the names as they have
     // their own complicated meets to perform, so we meet them here for all.
     Type nmt = xmt_name(t,mt);
     // Quick check on NIL: if either argument is NIL the result is allowed to
     // be NIL...  but nobody in the lattice can make a NIL from whole cloth, or
     // we get the crossing-nil bug.
     assert (nmt != NIL && nmt!=XNIL) || this==NIL || this==XNIL || t==NIL || t==XNIL;
     // Record this meet, to short-cut next time
     if( RECURSIVE_MEET == 0 )   // Only not mid-building recursive types;
       Key.put(this,t,nmt);
     return nmt;
   }
meet_loop()
Type com.cliffc.aa.type.Type< T extends Type< T >.meet_loop (Type< TypeTuple > t2) inherited
Definition at line 628 of file Type.java.
 { return meet(t2); }
meet_nil()
Type com.cliffc.aa.type.TypeTuple.meet_nil (Type t)
Definition at line 206 of file TypeTuple.java.
 { throw unimpl(); }
mtname()
final String com.cliffc.aa.type.Type< T extends Type< T >.mtname (Type< TypeTuple > t, Type< TypeTuple > mt) package inherited
Definition at line 567 of file Type.java.
{
     Type   t0 = this,  t1 = t;
     String s0 = t0._name, s1 = t1._name;
     assert check_name(s0) && check_name(s1);
     if( Util.eq(s0,s1) ) return s0;
     // Sort by name length
     if( s0.length() > s1.length() ) { t1=this; t0=t; s0=t0._name; s1=t1._name; }
     int x = 0, i;  char c;    // Last colon separator index
     // Find split point
     for( i = 0; i < s0.length(); i++ ) {
       if( (c=s0.charAt(i)) != s1.charAt(i) )
         break;
       if( c==':' ) x=i;
     }
     // If s0 is a prefix of s1, and s0 is high then it can cover s1.
     if( i==s0.length() && t0.above_center() && (!t1.above_center() || mt.above_center()) )
       return s1;
     // Keep the common prefix, which might be all of s0
     String s2 = i==s0.length() ? s0 : s0.substring(0, x).intern();
     assert check_name(s2);
     return s2;
   }
must_nil()
boolean com.cliffc.aa.type.TypeTuple.must_nil ()
Definition at line 204 of file TypeTuple.java.
 { return false; }
not_nil()
Type com.cliffc.aa.type.TypeTuple.not_nil () package
Definition at line 205 of file TypeTuple.java.
 { return this; }
oob() [1/6]
Type com.cliffc.aa.type.Type< T extends Type< T >.oob inherited
Definition at line 635 of file Type.java.
 { return oob(ALL); }
oob() [2/6]
Type com.cliffc.aa.type.Type< T extends Type< T >.oob (Type< TypeTuple > e) inherited
Definition at line 636 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [3/6]
TypeMem com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeMem e) inherited
Definition at line 639 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [4/6]
TypeMemPtr com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeMemPtr e) inherited
Definition at line 640 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [5/6]
TypeObj com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeObj e) inherited
Definition at line 637 of file Type.java.
 { return above_center() ? (TypeObj)e.dual() : e; }
oob() [6/6]
TypeStruct com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeStruct e) inherited
Definition at line 638 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob_deep()
Type com.cliffc.aa.type.Type< T extends Type< T >.oob_deep (Type< TypeTuple > t) inherited
Definition at line 632 of file Type.java.
 { return oop_deep_impl(t); }
oop_deep_impl()
Type com.cliffc.aa.type.Type< T extends Type< T >.oop_deep_impl (Type< TypeTuple > t) inherited
Definition at line 634 of file Type.java.
 { return oob(); }
rdual()
T com.cliffc.aa.type.Type< T extends Type< T >.rdual package inherited
Definition at line 366 of file Type.java.
 { assert _dual!=null; return _dual; }
remove_name()
final T com.cliffc.aa.type.Type< T extends Type< T >.remove_name inherited
Definition at line 556 of file Type.java.
 { return has_name() ? _set_name("") : (T)this; }
repeats_in_cycles()
TypeStruct com.cliffc.aa.type.Type< T extends Type< T >.repeats_in_cycles (TypeStruct head, VBitSet bs) package inherited
Definition at line 938 of file Type.java.
 { return null; }
retern()
final T com.cliffc.aa.type.Type< T extends Type< T >.retern package inherited
Definition at line 201 of file Type.java.
                     {
     assert _dual._dual == this;
     assert _hash != 0;
     assert INTERN.get(this)==null;
     INTERN.put(this,this);
     assert INTERN.get(this)==this;
     return (T)this;
   }
rot()
static int com.cliffc.aa.type.TypeTuple.rot (int x, int k) static private
Definition at line 23 of file TypeTuple.java.
 { return (x<<k) | (x>>(32-k)); }
Referenced by com.cliffc.aa.type.TypeTuple.compute_hash().
set()
TypeTuple com.cliffc.aa.type.TypeTuple.set (int idx, Type t)
Definition at line 186 of file TypeTuple.java.
{
     Type[] ts = Types.clone(_ts);
     ts[idx]=t;
     return make(ts);
   }
References com.cliffc.aa.type.TypeTuple._ts, com.cliffc.aa.type.Types.clone(), and com.cliffc.aa.type.TypeTuple.make().
Referenced by com.cliffc.aa.node.CallNode.set_ttfp().
set_name()
final T com.cliffc.aa.type.Type< T extends Type< T >.set_name (String name) inherited
Definition at line 551 of file Type.java.
{
     assert check_name(name);
     return _set_name(name);
   }
sharptr() [1/2]
Type com.cliffc.aa.type.Type< T extends Type< T >.sharptr (Type< TypeTuple > ptr) inherited
Definition at line 930 of file Type.java.
 { return this==ANY ? TypeMem.ANYMEM.sharptr(ptr) : ptr; }
sharptr() [2/2]
TypeTuple com.cliffc.aa.type.TypeTuple.sharptr (TypeMem mem)
Definition at line 208 of file TypeTuple.java.
{
     Type[] ts = Types.clone(_ts);
     for( int i=0; i<ts.length; i++ )
       ts[i] = mem.sharptr(ts[i]);
     return make0(_any,ts);
   }
References com.cliffc.aa.type.TypeTuple._any, com.cliffc.aa.type.TypeTuple._ts, com.cliffc.aa.type.Types.clone(), com.cliffc.aa.type.TypeTuple.make0(), and com.cliffc.aa.type.TypeMem.sharptr().
Referenced by com.cliffc.aa.type.TypeMem.sharptr().
simple_ptr()
Type com.cliffc.aa.type.TypeTuple.simple_ptr ()
Definition at line 214 of file TypeTuple.java.
{
     Type[] ts = Types.clone(_ts);
     for( int i=0; i<ts.length; i++ )
       ts[i] = ts[i].simple_ptr();
     return make0(_any,ts);
   }
References com.cliffc.aa.type.TypeTuple._any, com.cliffc.aa.type.TypeTuple._ts, com.cliffc.aa.type.Types.clone(), and com.cliffc.aa.type.TypeTuple.make0().
str()
SB com.cliffc.aa.type.TypeTuple.str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
Definition at line 65 of file TypeTuple.java.
{
     if( _any ) sb.p('~');
     sb.p('(');
     if( _ts!=null && _ts.length>0 ) { // No commas for zero-length
       int j = _ts.length-1;     // Find length of trailing equal parts
       Type last = _ts[j];       // Last type
       for( j--; j>0; j-- ) if( _ts[j] != last )  break;
       _ts[0].str(sb,dups,mem,debug);    // First type
       for( int i=1; i<=j+1; i++ ) // All types up to trailing equal parts
         _ts[i].str(sb.p(','),dups,mem,debug);
       if( j+2<_ts.length-1 )  sb.p("..."); // Abbreviate tail
       if( _ts.length> j+2 ) last.str(sb.p(','),dups,mem,debug);
     }
     return sb.p(')');
   }
References com.cliffc.aa.type.TypeTuple._any, com.cliffc.aa.type.TypeTuple._ts, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.type.Type< T extends Type< T >.str().
Referenced by com.cliffc.aa.type.TypeFunSig.str().
toString()
final String com.cliffc.aa.type.Type< T extends Type< T >.toString inherited
Definition at line 127 of file Type.java.
 { return str(new SB(),new VBitSet(),null,true).toString(); }
typerr()
RuntimeException com.cliffc.aa.type.Type< T extends Type< T >.typerr (Type< TypeTuple > t) package inherited
Definition at line 947 of file Type.java.
{
     throw new RuntimeException("Should not reach here: internal type system error with "+this+(t==null?"":(" and "+t)));
   }
untern()
final T com.cliffc.aa.type.Type< T extends Type< T >.untern package inherited
Definition at line 193 of file Type.java.
                     {
     assert _hash != 0;
     assert INTERN.get(this)==this;
     Type rez = INTERN.remove(this);
     assert rez == this;
     return (T)this;
   }
walk()
void com.cliffc.aa.type.Type< T extends Type< T >.walk (Predicate< Type< TypeTuple > > p) inherited
Definition at line 936 of file Type.java.
 { assert is_simple(); p.test(this); }
widen()
TypeTuple com.cliffc.aa.type.TypeTuple.widen ()
Definition at line 221 of file TypeTuple.java.
{
     Type[] ts = Types.get(_ts.length);
     for( int i=0; i<ts.length; i++ )
       ts[i] = _ts[i].widen();
     return make(ts);
   }
References com.cliffc.aa.type.TypeTuple._ts, com.cliffc.aa.type.Types.get(), and com.cliffc.aa.type.TypeTuple.make().
xdual()
TypeTuple com.cliffc.aa.type.TypeTuple.xdual () protected
Definition at line 155 of file TypeTuple.java.
{
     Type[] ts = Types.get(_ts.length);
     for( int i=0; i<_ts.length; i++ ) ts[i] = _ts[i].dual();
     ts = Types.hash_cons(ts);
     return new TypeTuple().init(!_any, ts);
   }
References com.cliffc.aa.type.TypeTuple._any, com.cliffc.aa.type.TypeTuple._ts, com.cliffc.aa.type.Type< TypeTuple >.dual(), com.cliffc.aa.type.Types.get(), com.cliffc.aa.type.Types.hash_cons(), and com.cliffc.aa.type.TypeTuple.init().
xmeet()
Type com.cliffc.aa.type.TypeTuple.xmeet (Type t) protected
Definition at line 163 of file TypeTuple.java.
{
     if( t._type != TTUPLE ) return ALL; // Tuples are internal types only, not user exposed
     TypeTuple tt = (TypeTuple)t;
     return _ts.length < tt._ts.length ? xmeet1(tt) : tt.xmeet1(this);
   }
References com.cliffc.aa.type.TypeTuple._ts, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.type.Type< TypeTuple >.ALL, com.cliffc.aa.type.Type< TypeTuple >.TTUPLE, and com.cliffc.aa.type.TypeTuple.xmeet1().
xmeet1()
TypeTuple com.cliffc.aa.type.TypeTuple.xmeet1 (TypeTuple tmax) private
Definition at line 170 of file TypeTuple.java.
{
     // Short is high; short extended by ANY so tail is a copy of long.
     // Short is low ; short extended by ALL so tail is ALL so trimmed to short.
     int len = _any ? tmax._ts.length : _ts.length;
     // Meet of common elements
     Type[] ts = Types.get(len);
     for( int i=0; i<_ts.length; i++ )  ts[i] = _ts[i].meet(tmax._ts[i]);
     // Elements only in the longer tuple.
     if( len > _ts.length ) System.arraycopy(tmax._ts, _ts.length, ts, _ts.length, len - _ts.length);
     return make0(_any&tmax._any,ts);
   }
References com.cliffc.aa.type.TypeTuple._any, com.cliffc.aa.type.TypeTuple._ts, com.cliffc.aa.type.Types.get(), com.cliffc.aa.type.TypeTuple.len(), com.cliffc.aa.type.TypeTuple.make0(), and com.cliffc.aa.type.Type< TypeTuple >.meet().
Referenced by com.cliffc.aa.type.TypeTuple.xmeet().
xmt_name()
Type com.cliffc.aa.type.Type< T extends Type< T >.xmt_name (Type< TypeTuple > t, Type< TypeTuple > mt) private inherited
Definition at line 441 of file Type.java.
{
     String n = mtname(t,mt);    // Meet name strings
     // If the names are incompatible and the meet remained high then the
     // mismatched names force a drop.
     if( n.length() < _name.length() && n.length() < t._name.length() && mt.above_center() ) {
       if( mt.interned() ) // recursive type creation?
         mt = mt.dual();   // Force low
     }
     if( mt.is_simple() ) n=""; // No named simple types
     if( mt._type==TOBJ ) n=""; // OBJ splits into strings (arrays) and structs, which can keep their names
     // Inject the name
     if( !Util.eq(mt._name,n) )  // Fast path cutout
       mt = mt.set_name(n);
     return mt;
   }
Member Data Documentation
_any
boolean com.cliffc.aa.type.TypeTuple._any package
Definition at line 12 of file TypeTuple.java.
Referenced by com.cliffc.aa.type.TypeTuple.above_center(), com.cliffc.aa.type.TypeTuple.compute_hash(), com.cliffc.aa.type.TypeTuple.equals(), com.cliffc.aa.type.TypeTuple.init(), com.cliffc.aa.type.TypeTuple.make_from_arg(), com.cliffc.aa.type.TypeTuple.sharptr(), com.cliffc.aa.type.TypeTuple.simple_ptr(), com.cliffc.aa.type.TypeTuple.str(), com.cliffc.aa.type.TypeTuple.xdual(), and com.cliffc.aa.type.TypeTuple.xmeet1().
_dual
T com.cliffc.aa.type.Type< T extends Type< T >._dual package inherited
Definition at line 100 of file Type.java.
_hash
int com.cliffc.aa.type.Type< T extends Type< T >._hash inherited
Definition at line 97 of file Type.java.
_name
String com.cliffc.aa.type.Type< T extends Type< T >._name inherited
Definition at line 99 of file Type.java.
_ts
Type [] com.cliffc.aa.type.TypeTuple._ts
Definition at line 13 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.TestNodeSmall._testMonotonicChain(), com.cliffc.aa.type.TypeFunSig.arg(), com.cliffc.aa.type.TypeTuple.at(), com.cliffc.aa.type.TypeTuple.compute_hash(), com.cliffc.aa.type.TypeTuple.equals(), com.cliffc.aa.type.TypeTuple.init(), com.cliffc.aa.type.TypeTuple.is_con(), com.cliffc.aa.type.TypeTuple.isBitShape(), com.cliffc.aa.node.CallNode.least_cost(), com.cliffc.aa.type.TypeTuple.len(), com.cliffc.aa.type.TypeTuple.make_from_arg(), com.cliffc.aa.type.TypeTuple.may_be_con(), com.cliffc.aa.type.TypeFunSig.nargs(), com.cliffc.aa.type.TypeTuple.set(), com.cliffc.aa.type.TypeTuple.sharptr(), com.cliffc.aa.type.TypeTuple.simple_ptr(), com.cliffc.aa.type.TypeTuple.str(), com.cliffc.aa.node.ProjNode.value(), com.cliffc.aa.node.MProjNode.value(), com.cliffc.aa.node.CallEpiNode.value(), com.cliffc.aa.type.TypeTuple.widen(), com.cliffc.aa.type.TypeTuple.xdual(), com.cliffc.aa.type.TypeTuple.xmeet(), and com.cliffc.aa.type.TypeTuple.xmeet1().
_type
byte com.cliffc.aa.type.Type< T extends Type< T >._type package inherited
Definition at line 98 of file Type.java.
_uid
int com.cliffc.aa.type.Type< T extends Type< T >._uid inherited
Definition at line 96 of file Type.java.
ALL
final Type com.cliffc.aa.type.Type< T extends Type< T >.ALL static inherited
Definition at line 324 of file Type.java.
ALL_TYPES
Ary<Type> com.cliffc.aa.type.Type< T extends Type< T >.ALL_TYPES static private inherited
Definition at line 650 of file Type.java.
ANY
final Type com.cliffc.aa.type.Type< T extends Type< T >.ANY static inherited
Definition at line 325 of file Type.java.
CALLE
final TypeTuple com.cliffc.aa.type.TypeTuple.CALLE = make(CTRL, TypeMem.ALLMEM, ALL) static
Definition at line 131 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.CallNode.escapees(), com.cliffc.aa.node.TestNode.testMonotonic(), and com.cliffc.aa.node.CallEpiNode.value().
CNT
int com.cliffc.aa.type.Type< T extends Type< T >.CNT static private inherited
Definition at line 95 of file Type.java.
CTRL
final Type com.cliffc.aa.type.Type< T extends Type< T >.CTRL static inherited
Definition at line 326 of file Type.java.
FLT64
final TypeTuple com.cliffc.aa.type.TypeTuple.FLT64 = make_args(TypeFlt.FLT64) static
Definition at line 137 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.PrimNode.Prim1OpF64.Prim1OpF64().
FLT64_FLT64
final TypeTuple com.cliffc.aa.type.TypeTuple.FLT64_FLT64 = make_args(TypeFlt.FLT64,TypeFlt.FLT64) static
Definition at line 140 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.PrimNode.Prim2OpF64.Prim2OpF64(), and com.cliffc.aa.node.PrimNode.Prim2RelOpF64.Prim2RelOpF64().
IF_ALL
final TypeTuple com.cliffc.aa.type.TypeTuple.IF_ALL = make(CTRL ,CTRL) static
Definition at line 123 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.IfNode.value().
IF_ANY
final TypeTuple com.cliffc.aa.type.TypeTuple.IF_ANY = IF_ALL.dual() static
Definition at line 124 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.IfNode.is_copy(), and com.cliffc.aa.node.IfNode.value().
IF_FALSE
final TypeTuple com.cliffc.aa.type.TypeTuple.IF_FALSE = make(CTRL ,XCTRL) static
Definition at line 126 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.IfNode.is_copy(), and com.cliffc.aa.node.IfNode.value().
IF_TRUE
final TypeTuple com.cliffc.aa.type.TypeTuple.IF_TRUE = make(XCTRL,CTRL) static
Definition at line 125 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.IfNode.is_copy(), and com.cliffc.aa.node.IfNode.value().
INT64
final TypeTuple com.cliffc.aa.type.TypeTuple.INT64 = make_args(TypeInt.INT64) static
Definition at line 136 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.PrimNode.ConvertInt64F64.ConvertInt64F64(), com.cliffc.aa.node.PrimNode.Prim1OpI64.Prim1OpI64(), and com.cliffc.aa.node.PrimNode.RandI64.RandI64().
INT64_INT64
final TypeTuple com.cliffc.aa.type.TypeTuple.INT64_INT64 = make_args(TypeInt.INT64,TypeInt.INT64) static
Definition at line 139 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.PrimNode.Prim2OpI64.Prim2OpI64(), and com.cliffc.aa.node.PrimNode.Prim2RelOpI64.Prim2RelOpI64().
INTERN
final ConcurrentHashMap<Type,Type> com.cliffc.aa.type.Type< T extends Type< T >.INTERN static private inherited
Definition at line 162 of file Type.java.
ISA_SCALAR
final byte [] com.cliffc.aa.type.Type< T extends Type< T >.ISA_SCALAR static private inherited
Definition at line 355 of file Type.java.
LVAL_LEN
final TypeTuple com.cliffc.aa.type.TypeTuple.LVAL_LEN = make_args(TypeMemPtr.ARYPTR) static
Definition at line 143 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.MemPrimNode.LValueLength.LValueLength().
LVAL_RD
final TypeTuple com.cliffc.aa.type.TypeTuple.LVAL_RD = make_args(TypeMemPtr.ARYPTR,TypeInt.INT64) static
Definition at line 144 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.MemPrimNode.LValueRead.LValueRead().
LVAL_WR
final TypeTuple com.cliffc.aa.type.TypeTuple.LVAL_WR = make_args(TypeMemPtr.ARYPTR,TypeInt.INT64,Type.SCALAR) static
Definition at line 145 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.MemPrimNode.LValueWrite.LValueWrite(), and com.cliffc.aa.node.MemPrimNode.LValueWriteFinal.LValueWriteFinal().
NIL
final Type com.cliffc.aa.type.Type< T extends Type< T >.NIL static inherited
Definition at line 332 of file Type.java.
NO_ARGS
final TypeTuple com.cliffc.aa.type.TypeTuple.NO_ARGS = make_args() static
Definition at line 135 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.FunNode.FunNode().
NREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.NREAL static package inherited
Definition at line 336 of file Type.java.
NSCALR
final Type com.cliffc.aa.type.Type< T extends Type< T >.NSCALR static inherited
Definition at line 330 of file Type.java.
OOP_OOP
final TypeTuple com.cliffc.aa.type.TypeTuple.OOP_OOP = make_args(TypeMemPtr.ISUSED0,TypeMemPtr.ISUSED0) static
Definition at line 141 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.PrimNode.EQ_OOP.EQ_OOP(), and com.cliffc.aa.node.PrimNode.NE_OOP.NE_OOP().
POOLS
final Pool [] com.cliffc.aa.type.Type< T extends Type< T >.POOLS static package inherited
Definition at line 281 of file Type.java.
REAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.REAL static inherited
Definition at line 334 of file Type.java.
RECURSIVE_MEET
int com.cliffc.aa.type.Type< T extends Type< T >.RECURSIVE_MEET static inherited
Definition at line 163 of file Type.java.
RET
final TypeTuple com.cliffc.aa.type.TypeTuple.RET = make(CTRL, TypeMem.ALLMEM, ALL) static
Definition at line 130 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.FunNode.FunNode(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.NewPrimNode(), com.cliffc.aa.node.FunNode.split_size(), com.cliffc.aa.node.TestNodeSmall.testMemoryArgs(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.node.ThretNode.value(), com.cliffc.aa.node.RetNode.value(), com.cliffc.aa.node.CallEpiNode.value(), com.cliffc.aa.node.PrimNode.AndThen.value(), and com.cliffc.aa.node.PrimNode.OrElse.value().
SCALAR
final Type com.cliffc.aa.type.Type< T extends Type< T >.SCALAR static inherited
Definition at line 328 of file Type.java.
SCALAR1
final TypeTuple com.cliffc.aa.type.TypeTuple.SCALAR1 = make_args(SCALAR) static
Definition at line 142 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.PrimNode.Not.Not().
SCALAR_PRIMS
Type [] com.cliffc.aa.type.Type< T extends Type< T >.SCALAR_PRIMS static private inherited
Definition at line 349 of file Type.java.
START_STATE
final TypeTuple com.cliffc.aa.type.TypeTuple.START_STATE = make(CTRL, TypeMem.EMPTY) static
Definition at line 129 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.StartNode.value().
STRPTR
final TypeTuple com.cliffc.aa.type.TypeTuple.STRPTR = make_args(TypeMemPtr.STRPTR) static
Definition at line 138 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.PrimNode.ConvertStrStr.ConvertStrStr().
STRS
final String [] com.cliffc.aa.type.Type< T extends Type< T >.STRS static private inherited
Definition at line 262 of file Type.java.
TALL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TALL static package inherited
Definition at line 239 of file Type.java.
TANY
final byte com.cliffc.aa.type.Type< T extends Type< T >.TANY static package inherited
Definition at line 240 of file Type.java.
TARY
final byte com.cliffc.aa.type.Type< T extends Type< T >.TARY static package inherited
Definition at line 269 of file Type.java.
TCTRL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TCTRL static package inherited
Definition at line 241 of file Type.java.
TEST0
final TypeTuple com.cliffc.aa.type.TypeTuple.TEST0 = make(CTRL, TypeMem.MEM , TypeFunPtr.GENERIC_FUNPTR, SCALAR) static
Definition at line 132 of file TypeTuple.java.
Referenced by com.cliffc.aa.node.TestNode.testMonotonic().
TEST1
final TypeTuple com.cliffc.aa.type.TypeTuple.TEST1 = make(CTRL, TypeMem.EMPTY, TypeFunPtr.GENERIC_FUNPTR, SCALAR) static
Definition at line 133 of file TypeTuple.java.
TFLD
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFLD static package inherited
Definition at line 271 of file Type.java.
TFLT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFLT static package inherited
Definition at line 264 of file Type.java.
TFUNPTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFUNPTR static package inherited
Definition at line 274 of file Type.java.
TFUNSIG
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFUNSIG static package inherited
Definition at line 275 of file Type.java.
TINT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TINT static package inherited
Definition at line 263 of file Type.java.
TLAST
final byte com.cliffc.aa.type.Type< T extends Type< T >.TLAST static package inherited
Definition at line 277 of file Type.java.
TLIVE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TLIVE static package inherited
Definition at line 276 of file Type.java.
TMEM
final byte com.cliffc.aa.type.Type< T extends Type< T >.TMEM static package inherited
Definition at line 272 of file Type.java.
TMEMPTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TMEMPTR static package inherited
Definition at line 273 of file Type.java.
TNIL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNIL static package inherited
Definition at line 259 of file Type.java.
TNREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNREAL static package inherited
Definition at line 257 of file Type.java.
TNSCALR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNSCALR static package inherited
Definition at line 253 of file Type.java.
TOBJ
final byte com.cliffc.aa.type.Type< T extends Type< T >.TOBJ static package inherited
Definition at line 267 of file Type.java.
TREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TREAL static package inherited
Definition at line 255 of file Type.java.
TRPC
final byte com.cliffc.aa.type.Type< T extends Type< T >.TRPC static package inherited
Definition at line 265 of file Type.java.
TSCALAR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSCALAR static package inherited
Definition at line 246 of file Type.java.
TSIMPLE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSIMPLE static package inherited
Definition at line 261 of file Type.java.
TSTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSTR static package inherited
Definition at line 270 of file Type.java.
TSTRUCT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSTRUCT static package inherited
Definition at line 268 of file Type.java.
TTUPLE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TTUPLE static package inherited
Definition at line 266 of file Type.java.
TXCTRL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXCTRL static package inherited
Definition at line 242 of file Type.java.
TXNIL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNIL static package inherited
Definition at line 260 of file Type.java.
TXNREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNREAL static package inherited
Definition at line 258 of file Type.java.
TXNSCALR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNSCALR static package inherited
Definition at line 254 of file Type.java.
TXREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXREAL static package inherited
Definition at line 256 of file Type.java.
TXSCALAR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXSCALAR static package inherited
Definition at line 247 of file Type.java.
TYPES
final TypeTuple [] com.cliffc.aa.type.TypeTuple.TYPES static package
Initial value:
= new TypeTuple[]{
    CALLE,START_STATE,IF_ALL, IF_TRUE, IF_FALSE, TEST0, TEST1,
    NO_ARGS, INT64, FLT64, STRPTR, INT64_INT64, FLT64_FLT64, OOP_OOP
  }
Definition at line 148 of file TypeTuple.java.
XCTRL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XCTRL static inherited
Definition at line 327 of file Type.java.
XNIL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNIL static inherited
Definition at line 333 of file Type.java.
XNREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNREAL static private inherited
Definition at line 337 of file Type.java.
XNSCALR
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNSCALR static inherited
Definition at line 331 of file Type.java.
XREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XREAL static private inherited
Definition at line 335 of file Type.java.
XSCALAR
final Type com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR static inherited
Definition at line 329 of file Type.java.
The documentation for this class was generated from the following file:
TypeTuple.java