aa: com.cliffc.aa.HM.HM8.Let Class Reference
com.cliffc.aa.HM.HM8.Let Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Let (String arg0, Syntax def, Syntax body)
void add_work (Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
T2 lookup (String name)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
T2 post ()
T2 pre ()
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
T2 targ ()
Package Attributes
final String _arg0
final Syntax _body
final Syntax _def
VStack _nongen
Syntax _par
T2 _post
T2 _pre
T2 _t
T2 _targ
Detailed Description
Definition at line 430 of file HM8.java.
Constructor & Destructor Documentation
Let()
com.cliffc.aa.HM.HM8.Let.Let (String arg0, Syntax def, Syntax body) package
Definition at line 434 of file HM8.java.
 { _arg0=arg0; _body=body; _def=def; _targ=T2.make_leaf(); }
References com.cliffc.aa.HM.HM8.Let._arg0, com.cliffc.aa.HM.HM8.Let._body, com.cliffc.aa.HM.HM8.Let._def, com.cliffc.aa.HM.HM8.Let._targ, and com.cliffc.aa.HM.HM8.T2.make_leaf().
Member Function Documentation
add_work()
void com.cliffc.aa.HM.HM8.Let.add_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 453 of file HM8.java.
{
       work.push(_par);
       work.push(_body);
       work.push(_def);
       if( targ().occurs_in_type(_def.find()) ) work.addAll(_targ._deps);
     }
References com.cliffc.aa.HM.HM8.Let._body, com.cliffc.aa.HM.HM8.Let._def, com.cliffc.aa.HM.HM8.T2._deps, com.cliffc.aa.HM.HM8.Syntax._par, com.cliffc.aa.HM.HM8.Let._targ, com.cliffc.aa.HM.HM8.Worklist.addAll(), com.cliffc.aa.HM.HM8.Syntax.find(), com.cliffc.aa.HM.HM8.Worklist.push(), and com.cliffc.aa.HM.HM8.Let.targ().
debug_find()
T2 com.cliffc.aa.HM.HM8.Syntax.debug_find () package inherited
Definition at line 249 of file HM8.java.
 { return _t.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM8.Syntax._t, and com.cliffc.aa.HM.HM8.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM8.hm().
find()
T2 com.cliffc.aa.HM.HM8.Syntax.find () package inherited
Definition at line 245 of file HM8.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._t, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.T2._occurs_in(), com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Ident.hm(), com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.HM.HM8.Apply.is_if_nil(), and com.cliffc.aa.HM.HM8.Struct.prep_tree().
hm()
boolean com.cliffc.aa.HM.HM8.Let.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 439 of file HM8.java.
{
       boolean progress = false;
       // Let memory: pre-memory unifies with body-pre, post-memory unifies with post-body.
       progress |=       pre ().unify(_def .pre (),work);
       progress |= _def .post().unify(_body.pre (),work);
       progress |= _body.post().unify(      post(),work);
       if( work==null && progress ) return true;
       return targ().unify(_def.find(),work);
     }
References com.cliffc.aa.HM.HM8.Let._body, com.cliffc.aa.HM.HM8.Let._def, com.cliffc.aa.HM.HM8.Syntax.find(), com.cliffc.aa.HM.HM8.Syntax.post(), com.cliffc.aa.HM.HM8.Syntax.pre(), com.cliffc.aa.HM.HM8.Let.targ(), and com.cliffc.aa.HM.HM8.T2.unify().
lookup()
T2 com.cliffc.aa.HM.HM8.Let.lookup (String name) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 449 of file HM8.java.
{
       if( Util.eq(_arg0,name) ) return targ();
       return _par==null ? null : _par.lookup(name);
     }
References com.cliffc.aa.HM.HM8.Let._arg0, com.cliffc.aa.HM.HM8.Syntax._par, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM8.Syntax.lookup(), and com.cliffc.aa.HM.HM8.Let.targ().
more_work()
boolean com.cliffc.aa.HM.HM8.Let.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 469 of file HM8.java.
{
       if( !more_work_impl(work) ) return false;
       return _body.more_work(work) && _def.more_work(work);
     }
References com.cliffc.aa.HM.HM8.Let._body, com.cliffc.aa.HM.HM8.Let._def, com.cliffc.aa.HM.HM8.Syntax.more_work(), and com.cliffc.aa.HM.HM8.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM8.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 283 of file HM8.java.
{
       boolean no_more_work = work.has(this) || !hm(null); // Either on worklist, or no-progress
       return no_more_work;
     }
References com.cliffc.aa.HM.HM8.Worklist.has(), and com.cliffc.aa.HM.HM8.Syntax.hm().
Referenced by com.cliffc.aa.HM.HM8.Con.more_work(), com.cliffc.aa.HM.HM8.Ident.more_work(), com.cliffc.aa.HM.HM8.Lambda.more_work(), com.cliffc.aa.HM.HM8.Let.more_work(), com.cliffc.aa.HM.HM8.Apply.more_work(), com.cliffc.aa.HM.HM8.Struct.more_work(), and com.cliffc.aa.HM.HM8.Field.more_work().
p()
String com.cliffc.aa.HM.HM8.Syntax.p () inherited
Definition at line 291 of file HM8.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM8.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM8.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 292 of file HM8.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM8.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM8.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM8.Syntax.p1(), com.cliffc.aa.HM.HM8.Syntax.p2(), and com.cliffc.aa.HM.HM8.T2.str().
Referenced by com.cliffc.aa.HM.HM8.Syntax.p(), com.cliffc.aa.HM.HM8.Lambda.p2(), com.cliffc.aa.HM.HM8.Let.p2(), com.cliffc.aa.HM.HM8.Apply.p2(), com.cliffc.aa.HM.HM8.Struct.p2(), and com.cliffc.aa.HM.HM8.Field.p2().
p1()
SB com.cliffc.aa.HM.HM8.Let.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 436 of file HM8.java.
 { return sb.p(_arg0).p(" = ... ; ..."); }
References com.cliffc.aa.HM.HM8.Let._arg0, and com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM8.Let.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 437 of file HM8.java.
 { _body.p0(sb,dups); return _def.p0(sb,dups); }
References com.cliffc.aa.HM.HM8.Let._body, com.cliffc.aa.HM.HM8.Let._def, and com.cliffc.aa.HM.HM8.Syntax.p0().
post()
T2 com.cliffc.aa.HM.HM8.Syntax.post () package inherited
Definition at line 254 of file HM8.java.
               {
       T2 t = _post.find();
       return t==_post ? t : (_post=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._post, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), and com.cliffc.aa.HM.HM8.Field.hm().
pre()
T2 com.cliffc.aa.HM.HM8.Syntax.pre () package inherited
Definition at line 250 of file HM8.java.
              {
       T2 t = _pre.find();
       return t==_pre ? t : (_pre=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._pre, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), and com.cliffc.aa.HM.HM8.Field.hm().
prep_lookup_deps()
void com.cliffc.aa.HM.HM8.Let.prep_lookup_deps (Ident id) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 466 of file HM8.java.
{
       if( Util.eq(id._name,_arg0) ) _targ.push_update(id);
     }
References com.cliffc.aa.HM.HM8.Let._arg0, com.cliffc.aa.HM.HM8.Let._targ, com.cliffc.aa.util.Util.eq(), and com.cliffc.aa.HM.HM8.T2.push_update().
prep_tree()
int com.cliffc.aa.HM.HM8.Let.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 459 of file HM8.java.
{
       prep_tree_impl(par,nongen,work,_body._t);
       int cnt = _body.prep_tree(this,           nongen       ,work) +
                 _def .prep_tree(this,new VStack(nongen,_targ),work);
       _t = _body._t;            // Unify 'Let._t' with the '_body'
       return cnt+1;
     }
References com.cliffc.aa.HM.HM8.Let._body, com.cliffc.aa.HM.HM8.Let._def, com.cliffc.aa.HM.HM8.Syntax._t, com.cliffc.aa.HM.HM8.Let._targ, com.cliffc.aa.HM.HM8.Syntax.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
prep_tree_impl()
final void com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 267 of file HM8.java.
{
       _par=par;
       _pre = T2.make_mem();
       _t=t;
       _post = T2.make_mem();
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM8.Syntax._nongen, com.cliffc.aa.HM.HM8.Syntax._par, com.cliffc.aa.HM.HM8.Syntax._post, com.cliffc.aa.HM.HM8.Syntax._pre, com.cliffc.aa.HM.HM8.Syntax._t, com.cliffc.aa.HM.HM8.T2.make_mem(), and com.cliffc.aa.HM.HM8.Worklist.push().
Referenced by com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), com.cliffc.aa.HM.HM8.Lambda.prep_tree(), com.cliffc.aa.HM.HM8.Let.prep_tree(), com.cliffc.aa.HM.HM8.Apply.prep_tree(), com.cliffc.aa.HM.HM8.Struct.prep_tree(), and com.cliffc.aa.HM.HM8.Field.prep_tree().
str()
SB com.cliffc.aa.HM.HM8.Let.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 435 of file HM8.java.
 { return _body.str(_def.str(sb.p(_arg0).p(" = ")).p("; ")); }
References com.cliffc.aa.HM.HM8.Let._arg0, com.cliffc.aa.HM.HM8.Let._body, com.cliffc.aa.HM.HM8.Let._def, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM8.Syntax.str().
targ()
T2 com.cliffc.aa.HM.HM8.Let.targ () package
Definition at line 438 of file HM8.java.
 { T2 targ = _targ.find(); return targ==_targ ? targ : (_targ=targ); }
References com.cliffc.aa.HM.HM8.Let._targ, com.cliffc.aa.HM.HM8.T2.find(), and com.cliffc.aa.HM.HM8.Let.targ().
Referenced by com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Let.lookup(), and com.cliffc.aa.HM.HM8.Let.targ().
toString()
final String com.cliffc.aa.HM.HM8.Syntax.toString () inherited
Definition at line 288 of file HM8.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM8.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_arg0
final String com.cliffc.aa.HM.HM8.Let._arg0 package
Definition at line 431 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Let.Let(), com.cliffc.aa.HM.HM8.Let.lookup(), com.cliffc.aa.HM.HM8.Let.p1(), com.cliffc.aa.HM.HM8.Let.prep_lookup_deps(), and com.cliffc.aa.HM.HM8.Let.str().
_body
final Syntax com.cliffc.aa.HM.HM8.Let._body package
Definition at line 432 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Let.Let(), com.cliffc.aa.HM.HM8.Let.more_work(), com.cliffc.aa.HM.HM8.Let.p2(), com.cliffc.aa.HM.HM8.Let.prep_tree(), and com.cliffc.aa.HM.HM8.Let.str().
_def
final Syntax com.cliffc.aa.HM.HM8.Let._def package
Definition at line 432 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Let.Let(), com.cliffc.aa.HM.HM8.Let.more_work(), com.cliffc.aa.HM.HM8.Let.p2(), com.cliffc.aa.HM.HM8.Let.prep_tree(), and com.cliffc.aa.HM.HM8.Let.str().
_nongen
VStack com.cliffc.aa.HM.HM8.Syntax._nongen package inherited
Definition at line 241 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Ident.hm(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM8.Syntax._par package inherited
Definition at line 240 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._occurs_in(), com.cliffc.aa.HM.HM8.Con.add_work(), com.cliffc.aa.HM.HM8.Ident.add_work(), com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Apply.add_work(), com.cliffc.aa.HM.HM8.Struct.add_work(), com.cliffc.aa.HM.HM8.Field.add_work(), com.cliffc.aa.HM.HM8.Ident.hm(), com.cliffc.aa.HM.HM8.Lambda.lookup(), com.cliffc.aa.HM.HM8.Let.lookup(), com.cliffc.aa.HM.HM8.Apply.lookup(), com.cliffc.aa.HM.HM8.Struct.lookup(), com.cliffc.aa.HM.HM8.Field.lookup(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_post
T2 com.cliffc.aa.HM.HM8.Syntax._post package inherited
Definition at line 244 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Syntax.post(), com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_pre
T2 com.cliffc.aa.HM.HM8.Syntax._pre package inherited
Definition at line 242 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Syntax.pre(), com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM8.Syntax._t package inherited
Definition at line 243 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Syntax.debug_find(), com.cliffc.aa.HM.HM8.Syntax.find(), com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM8.Syntax.p0(), com.cliffc.aa.HM.HM8.Let.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_targ
T2 com.cliffc.aa.HM.HM8.Let._targ package
Definition at line 433 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Let.Let(), com.cliffc.aa.HM.HM8.Let.prep_lookup_deps(), com.cliffc.aa.HM.HM8.Let.prep_tree(), and com.cliffc.aa.HM.HM8.Let.targ().
The documentation for this class was generated from the following file:
HM8.java