aa: com.cliffc.aa.HM.HM5.VStack Class Reference
com.cliffc.aa.HM.HM5.VStack Class Reference
Classes
class Iter
Public Member Functions
Iterator< T2 > iterator ()
String toString ()
Package Functions
VStack (VStack par, T2 nongen)
SB str (SB sb)
Package Attributes
final T2 _nongen
final VStack _par
Detailed Description
Definition at line 100 of file HM5.java.
Constructor & Destructor Documentation
VStack()
com.cliffc.aa.HM.HM5.VStack.VStack (VStack par, T2 nongen) package
Definition at line 103 of file HM5.java.
 { _par=par; _nongen=nongen; }
References com.cliffc.aa.HM.HM5.VStack._nongen, and com.cliffc.aa.HM.HM5.VStack._par.
Member Function Documentation
iterator()
Iterator<T2> com.cliffc.aa.HM.HM5.VStack.iterator ()
Definition at line 110 of file HM5.java.
 { return new Iter(); }
str()
SB com.cliffc.aa.HM.HM5.VStack.str (SB sb) package
Definition at line 105 of file HM5.java.
                   {
       _nongen.str(sb,new VBitSet(),new VBitSet());
       if( _par!=null ) _par.str(sb.p(" >> "));
       return sb;
     }
References com.cliffc.aa.HM.HM5.VStack._nongen, com.cliffc.aa.HM.HM5.VStack._par, com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM5.VStack.str(), and com.cliffc.aa.HM.HM5.T2.str().
Referenced by com.cliffc.aa.HM.HM5.VStack.str(), and com.cliffc.aa.HM.HM5.VStack.toString().
toString()
String com.cliffc.aa.HM.HM5.VStack.toString ()
Definition at line 104 of file HM5.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM5.VStack.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_nongen
final T2 com.cliffc.aa.HM.HM5.VStack._nongen package
Definition at line 102 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.VStack.Iter.next(), com.cliffc.aa.HM.HM5.VStack.str(), and com.cliffc.aa.HM.HM5.VStack.VStack().
_par
final VStack com.cliffc.aa.HM.HM5.VStack._par package
Definition at line 101 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.VStack.Iter.next(), com.cliffc.aa.HM.HM5.VStack.str(), and com.cliffc.aa.HM.HM5.VStack.VStack().
The documentation for this class was generated from the following file:
HM5.java