aa: com.cliffc.aa.util.Util Class Reference
com.cliffc.aa.util.Util Class Reference
Static Public Member Functions
static boolean eq (String s0, String s1)
static< E > int find (E[] es, E e)
static int find (int[] es, int e)
static void hash_quality_check (ConcurrentMap map)
static void hash_quality_check_per (ConcurrentMap map)
Detailed Description
Definition at line 5 of file Util.java.
Member Function Documentation
eq()
static boolean com.cliffc.aa.util.Util.eq (String s0, String s1) static
Definition at line 16 of file Util.java.
{
     if( s0==s1 ) return true;
     if( s0==null || s1==null ) return false;
     assert !s0.equals(s1) : "Not interned: "+s0;
     return false;
   }
Referenced by com.cliffc.aa.HM.HM4.T2._cycle_equals(), com.cliffc.aa.tvar.TV2._cycle_equals(), com.cliffc.aa.HM.HM5.T2._cycle_equals(), com.cliffc.aa.HM.HM6.T2._cycle_equals(), com.cliffc.aa.HM.HM7.T2._cycle_equals(), com.cliffc.aa.HM.HM8.T2._cycle_equals(), com.cliffc.aa.HM.HM9.T2._cycle_equals(), com.cliffc.aa.HM.HM.T2._cycle_equals(), com.cliffc.aa.tvar.TV2._eq(), com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.HM.HM5.T2._fresh_unify(), com.cliffc.aa.HM.HM6.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM8.T2._fresh_unify(), com.cliffc.aa.HM.HM9.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM4.T2._fresh_unify_impl(), com.cliffc.aa.Parse._good_prec_tok(), com.cliffc.aa.tvar.TV2._unify(), com.cliffc.aa.HM.HM4.T2._unify(), com.cliffc.aa.HM.HM5.T2._unify(), com.cliffc.aa.HM.HM6.T2._unify(), com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM9.T2._unify(), com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.node.UnresolvedNode.add_def_unresolved(), com.cliffc.aa.type.TypeStruct.add_fld(), com.cliffc.aa.type.TypeStruct.cmp(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.node.NewObjNode.create(), com.cliffc.aa.type.TypeFld.cycle_equals(), com.cliffc.aa.type.Type< TypeFlt >.cycle_equals(), com.cliffc.aa.type.TypeStr.equals(), com.cliffc.aa.type.TypeFld.equals(), com.cliffc.aa.type.TypeFunSig.equals(), com.cliffc.aa.node.ConTypeNode.equals(), com.cliffc.aa.type.Type< TypeFlt >.equals(), com.cliffc.aa.node.StoreNode.equals(), com.cliffc.aa.node.LoadNode.equals(), com.cliffc.aa.Parse.fact(), com.cliffc.aa.node.LoadNode.find_previous_store(), com.cliffc.aa.type.TypeFld.fld_find(), com.cliffc.aa.type.TypeStruct.fld_find(), com.cliffc.aa.HM.HM9.T2.fresh_base(), com.cliffc.aa.HM.HM.T2.fresh_base(), com.cliffc.aa.Parse.func(), com.cliffc.aa.HM.HM4.T2.get_fresh(), com.cliffc.aa.HM.HM4.Apply.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.node.LoadNode.ideal_mono(), com.cliffc.aa.type.TypeFunSig.init(), com.cliffc.aa.type.TypeFld.is_display_ptr(), com.cliffc.aa.HM.HM7.Apply.is_if_nil(), com.cliffc.aa.HM.HM8.Apply.is_if_nil(), com.cliffc.aa.tvar.TV2.isa(), com.cliffc.aa.HM.HM5.T2.isa(), com.cliffc.aa.HM.HM6.T2.isa(), com.cliffc.aa.HM.HM7.T2.isa(), com.cliffc.aa.HM.HM8.T2.isa(), com.cliffc.aa.HM.HM9.T2.isa(), com.cliffc.aa.HM.HM.T2.isa(), com.cliffc.aa.HM.HM5.Lambda.lookup(), com.cliffc.aa.HM.HM5.Lambda2.lookup(), com.cliffc.aa.HM.HM5.Let.lookup(), com.cliffc.aa.HM.HM6.Lambda.lookup(), com.cliffc.aa.HM.HM6.Lambda2.lookup(), com.cliffc.aa.HM.HM7.Lambda.lookup(), com.cliffc.aa.HM.HM8.Lambda.lookup(), com.cliffc.aa.HM.HM6.Let.lookup(), com.cliffc.aa.HM.HM7.Let.lookup(), com.cliffc.aa.HM.HM8.Let.lookup(), com.cliffc.aa.type.Type< TypeFlt >.mtname(), com.cliffc.aa.node.FunNode.names(), com.cliffc.aa.HM.HM5.Lambda.prep_lookup_deps(), com.cliffc.aa.HM.HM5.Lambda2.prep_lookup_deps(), com.cliffc.aa.HM.HM5.Let.prep_lookup_deps(), com.cliffc.aa.HM.HM6.Lambda.prep_lookup_deps(), com.cliffc.aa.HM.HM6.Lambda2.prep_lookup_deps(), com.cliffc.aa.HM.HM7.Lambda.prep_lookup_deps(), com.cliffc.aa.HM.HM8.Lambda.prep_lookup_deps(), com.cliffc.aa.HM.HM6.Let.prep_lookup_deps(), com.cliffc.aa.HM.HM7.Let.prep_lookup_deps(), com.cliffc.aa.HM.HM8.Let.prep_lookup_deps(), com.cliffc.aa.HM.HM9.Lambda.prep_lookup_deps(), com.cliffc.aa.HM.HM.Lambda.prep_lookup_deps(), com.cliffc.aa.HM.HM9.Let.prep_lookup_deps(), com.cliffc.aa.HM.HM.Let.prep_lookup_deps(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), com.cliffc.aa.HM.HM.Ident.prep_tree(), com.cliffc.aa.HM.HM4.Lambda.prep_tree_lookup(), com.cliffc.aa.HM.HM4.Lambda2.prep_tree_lookup(), com.cliffc.aa.HM.HM4.Let.prep_tree_lookup(), com.cliffc.aa.HM.HM4.T2.progress(), com.cliffc.aa.type.TypeFld.sdual(), com.cliffc.aa.type.TypeFld.smeet(), com.cliffc.aa.type.TypeFunSig.str(), com.cliffc.aa.type.TypeStruct.str(), com.cliffc.aa.Parse.type0(), com.cliffc.aa.HM.HM9.T2.union(), com.cliffc.aa.HM.HM.T2.union(), com.cliffc.aa.type.TypeStr.xmeet(), and com.cliffc.aa.type.Type< TypeFlt >.xmt_name().
find() [1/2]
static <E> int com.cliffc.aa.util.Util.find (E[] es, E e) static
Definition at line 10 of file Util.java.
{
     for( int i=0; i<es.length; i++ ) if( es[i]==e ) return i;
     return -1;
   }
find() [2/2]
static int com.cliffc.aa.util.Util.find (int[] es, int e) static
Definition at line 6 of file Util.java.
{
     for( int i=0; i<es.length; i++ ) if( es[i]==e ) return i;
     return -1;
   }
Referenced by com.cliffc.aa.HM.HM7.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM8.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM9.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM7.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM8.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM9.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM9.T2._p(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM9.T2._unify_struct(), com.cliffc.aa.HM.HM.T2._unify_struct(), com.cliffc.aa.HM.HM7.Struct.hm(), com.cliffc.aa.HM.HM7.Field.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.HM.HM9.Struct.hm(), com.cliffc.aa.HM.HM.Struct.hm(), com.cliffc.aa.HM.HM9.Field.hm(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM9.NotNil.hm(), com.cliffc.aa.node.TestNode.make_minimal_graph(), com.cliffc.aa.HM.HM9.T2.meet_ids(), com.cliffc.aa.HM.HM.T2.meet_ids(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), and com.cliffc.aa.HM.HM.Ident.prep_tree().
hash_quality_check()
static void com.cliffc.aa.util.Util.hash_quality_check (ConcurrentMap map) static
Definition at line 29 of file Util.java.
{
     NonBlockingHashMapLong<Integer> hashs = new NonBlockingHashMapLong<>();
     for( Object k : map.keySet() ) {
       int hash = k.hashCode();
       Integer ii = hashs.get(hash);
       hashs.put(hash,ii==null ? 1 : ii+1);
     }
     int[] hist = new int[16];
     int maxval=0;
     long maxkey=-1;
     for( long l : hashs.keySet() ) {
       int reps = hashs.get(l);
       if( reps > maxval ) { maxval=reps; maxkey=l; }
       if( reps < hist.length ) hist[reps]++;
       else System.out.println("hash "+l+" repeats "+reps);
     }
     for( int i=0; i<hist.length; i++ )
       if( hist[i] > 0 )
         System.out.println("Number of hashes with "+i+" repeats: "+hist[i]);
     System.out.println("Max repeat key "+maxkey+" repeats: "+maxval);
   }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.get(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.keySet(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.put().
Referenced by com.cliffc.aa.util.Util.hash_quality_check_per().
hash_quality_check_per()
static void com.cliffc.aa.util.Util.hash_quality_check_per (ConcurrentMap map) static
Definition at line 24 of file Util.java.
{
     if( (map.size() & ((1L<<16)-1)) == 0 ) // Reports every 2^16 == 65536 puts
       hash_quality_check(map);
   }
References com.cliffc.aa.util.Util.hash_quality_check().
The documentation for this class was generated from the following file:
Util.java