aa: com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B > Class Template Reference
com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B > Class Template Reference
Public Member Functions
int[] get_kids (int par)
boolean is_parent (int idx)
int next_kid (int alias, int kid)
VBitSet plus_kids (Bits< B > bits)
String toString ()
Package Functions
void _plus_kids (VBitSet bs, int i)
void init0 ()
boolean is_parent (int par, int kid)
int parent (int kid)
int peek ()
void reset_to_init0 ()
int split (int par)
Package Attributes
int _cnt = 1
int[] _init
int[][] _kids = new int[2][]
int[] _pars = new int[2]
Private Member Functions
SB toString (SB sb, int i)
Detailed Description
Definition at line 402 of file Bits.java.
Member Function Documentation
_plus_kids()
void com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._plus_kids (VBitSet bs, int i) package
Definition at line 490 of file Bits.java.
{
       bs.set(i);
       int nkids = i >= _kids.length || _kids[i]==null ? 0 : _kids[i][0];
       for( int kid=1; kid<nkids; kid++ )
         _plus_kids(bs,_kids[i][kid]);
     }
References com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._kids.
Referenced by com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.plus_kids().
get_kids()
int [] com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.get_kids (int par)
Definition at line 412 of file Bits.java.
 { assert _kids[par][0]==3; return _kids[par]; }
References com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._kids.
init0()
void com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.init0 () package
Definition at line 469 of file Bits.java.
                  {
       _init = new int[_kids.length];
       for( int i=0; i<_kids.length; i++ )
         _init[i] = _kids[i]==null ? 1 : _kids[i][0];
     }
References com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._init, and com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._kids.
is_parent() [1/2]
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.is_parent (int idx)
Definition at line 410 of file Bits.java.
 { return idx<_kids.length && _kids[idx]!=null &&_kids[idx][0]>1; }
References com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._kids, and com.cliffc.aa.type.Bits< B extends Bits< B >.idx().
Referenced by com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.next_kid(), and com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.toString().
is_parent() [2/2]
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.is_parent (int par, int kid) package
Definition at line 414 of file Bits.java.
{
       for( ; par <= kid; kid = parent(kid) )
         if( par==kid ) return true;
       return false;             // Kid will be a larger number
     }
References com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.parent().
next_kid()
int com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.next_kid (int alias, int kid)
Definition at line 500 of file Bits.java.
{
       if( kid==0 ) return 0;
       boolean is_par = is_parent(kid);
       if( kid==alias && !is_par ) return 0; // Singleton bit
       // Find kid in the alias-tree
       if( is_par ) {            // Go deeper
         return _kids[kid][1];   // First child one layer deeper
       } else {                  // Leaf, unwind & find sibling
         while(kid!=alias) {
           int par = _pars[kid];    // Parent
           int[] kids = _kids[par]; // All the parents' children
           for( int i=1; i<kids[0]-1; i++ )
             if( kids[i]==kid )
               return kids[i+1]; // Return sibling
           kid=par;              // Up-parent & go again
         }
         return 0;               // Last child visited
       }
     }
References com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._kids, com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._pars, and com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.is_parent().
parent()
int com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.parent (int kid) package
Definition at line 409 of file Bits.java.
 { return _pars[kid]; }
References com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._pars.
Referenced by com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.is_parent().
peek()
int com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.peek () package
Definition at line 480 of file Bits.java.
 { return _kids[1][_kids[1][0]]; } // for testing
References com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._kids.
plus_kids()
VBitSet com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.plus_kids (Bits< B > bits)
Definition at line 483 of file Bits.java.
{
       VBitSet bs = new VBitSet();
       for( int i : bits )
         if( i != 0 )
           _plus_kids(bs,i);
       return bs;
     }
References com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._plus_kids(), and com.cliffc.aa.type.Bits< B extends Bits< B >.bits().
reset_to_init0()
void com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.reset_to_init0 () package
Definition at line 475 of file Bits.java.
{
       for( int i=0; i<_kids.length; i++ )
         if( _kids[i] != null )
           _kids[i][0] = i<_init.length ? _init[i] : 1;
     }
References com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._init, and com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._kids.
split()
int com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.split (int par) package
Definition at line 433 of file Bits.java.
{
       // See if we have an existing bit
       if( par < _kids.length ) { // This parent has kids already
         int[] kids = _kids[par]; //
         if( kids != null ) {
           int klen = kids[0];        // Number of kids already, 1-based
           if( klen < kids.length ) { // Room for more in array?
             int bit = kids[klen];
             if( bit != 0 ) {            // Pre-allocated kid from prior test?
               assert _pars[bit] == par; // Then parent must already be preallocated
               kids[0] = klen+1;
               return bit;
             }
           }
         }
       }
       // Need a new bit
       int bit = _cnt++; // Next available bit number
       // Make space in the parents array to hold the parent of 'bit'
       while( bit >= _pars.length ) _pars = Arrays.copyOf(_pars,_pars.length<<1);
       assert _pars[bit]==0;
       _pars[bit] = par;
       // Make space in the kids array to hold the children of 'par'
       while( par >= _kids.length ) _kids = Arrays.copyOf(_kids,_kids.length<<1);
       int[] kids = _kids[par];  // All the children of 'par'
       if( kids==null ) _kids[par] = kids = new int[]{1};
       int klen = kids[0];       // 1-based number of children.  '1' means 'no children'
       if( klen == kids.length ) // Make space as needed
         _kids[par] = kids = Arrays.copyOf(kids,klen<<1);
       kids[klen] = bit;         // Insert new child of parent
       kids[0] = klen+1;         // Bump count of children
       return bit;
     }
References com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._cnt, com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._kids, and com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._pars.
toString() [1/2]
String com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.toString ()
Definition at line 420 of file Bits.java.
 { return toString(new SB(),1).toString(); }
References com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.toString().
Referenced by com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.toString().
toString() [2/2]
SB com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.toString (SB sb, int i) private
Definition at line 421 of file Bits.java.
{
       sb.i().p(i).nl();
       if( is_parent(i) ) {
         sb.ii(1);
         for( int j=1; j<_kids[i][0]; j++ )
           toString(sb,_kids[i][j]);
         sb.di(1);
       }
       return sb;
     }
References com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._kids, com.cliffc.aa.util.SB.di(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.is_parent(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), and com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.toString().
Member Data Documentation
_cnt
int com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._cnt = 1 package
Definition at line 403 of file Bits.java.
Referenced by com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.split().
_init
int [] com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._init package
Definition at line 407 of file Bits.java.
Referenced by com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.init0(), and com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.reset_to_init0().
_kids
int [][] com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._kids = new int[2][] package
Definition at line 406 of file Bits.java.
Referenced by com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._plus_kids(), com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.get_kids(), com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.init0(), com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.is_parent(), com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.next_kid(), com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.peek(), com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.reset_to_init0(), com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.split(), and com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.toString().
_pars
int [] com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >._pars = new int[2] package
Definition at line 405 of file Bits.java.
Referenced by com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.next_kid(), com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.parent(), and com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.split().
The documentation for this class was generated from the following file:
Bits.java