aa: com.cliffc.aa.HM.HM4 Class Reference
com.cliffc.aa.HM.HM4 Class Reference
Classes
class Apply
class Con
class Ident
class Lambda
class Lambda2
class Let
class Syntax
class T2
Static Public Member Functions
static T2 hm (Syntax prog)
Static Package Functions
static void reset ()
Static Package Attributes
static final HashMap< String, T2 > PRIMS = new HashMap<>()
Detailed Description
Definition at line 19 of file HM4.java.
Member Function Documentation
hm()
static T2 com.cliffc.aa.HM.HM4.hm (Syntax prog) static
Definition at line 22 of file HM4.java.
{
     Ary<Syntax> work = new Ary<>(Syntax.class);
     // Simple types
     T2 bool  = T2.base(TypeInt.BOOL);
     T2 int64 = T2.base(TypeInt.INT64);
     T2 flt64 = T2.base(TypeFlt.FLT64);
     T2 strp  = T2.base(TypeMemPtr.STRPTR);
     // Primitives
     T2 var1 = T2.tnew();
     T2 var2 = T2.tnew();
     PRIMS.put("pair" ,T2.fresh("TOP",T2.fun(var1, T2.fun(var2, T2.prim("pair" ,var1,var2)))));
     PRIMS.put("pair2",T2.fresh("TOP",T2.fun(var1,        var2, T2.prim("pair2",var1,var2) )));
     //PRIMS.put("if/else" ,new HMT(T2.fun(bool,T2.fun(var1,T2.fun(var1,var1)))));
     PRIMS.put("if/else3",T2.fresh("TOP",T2.fun(bool,var1,var1,var1)));
     PRIMS.put("dec",T2.fresh("TOP",T2.fun(int64,int64)));
     PRIMS.put("*"  ,T2.fresh("TOP",T2.fun(int64,T2.fun(int64,int64))));
     PRIMS.put("*2" ,T2.fresh("TOP",T2.fun(int64,int64,int64)));
     PRIMS.put("==0",T2.fresh("TOP",T2.fun(int64,bool)));
     PRIMS.put("isempty",T2.fresh("TOP",T2.fun(strp,bool)));
     // Print a string; int->str
     PRIMS.put("str",T2.fresh("TOP",T2.fun(int64,strp)));
     // Factor; FP div/mod-like operation
     PRIMS.put("factor",T2.fresh("TOP",T2.fun(flt64,T2.prim("divmod",flt64,flt64))));
     // Prep for SSA: pre-gather all the (unique) ids
     prog.prep_tree(null,work);
     int cnt=0;
     while( !work.isEmpty() ) {  // While work
       Syntax syn = work.del(cnt%work._len);  // Get work
       T2 t = syn.hm(work);      // Get work results
       T2 tsyn = syn.find();
       if( t!=tsyn ) {             // Progress?
         assert !t.progress(tsyn); // monotonic: unifying with the result is no-progress
         syn._t=t;                 // Progress!
         if( syn._par !=null ) work.push(syn._par); // Parent updates
       }
       // VERY EXPENSIVE ASSERT: O(n^2).  Every Syntax that makes progress is on the worklist
       //assert prog.more_work(work);
       cnt++;
     }
     assert prog.more_work(work);
     return prog._t;
   }
References com.cliffc.aa.util.Ary< E >._len, com.cliffc.aa.HM.HM4.Syntax._par, com.cliffc.aa.HM.HM4.Syntax._t, com.cliffc.aa.HM.HM4.T2.base(), com.cliffc.aa.type.TypeInt.BOOL, com.cliffc.aa.util.Ary< E >.del(), com.cliffc.aa.HM.HM4.Syntax.find(), com.cliffc.aa.type.TypeFlt.FLT64, com.cliffc.aa.HM.HM4.T2.fresh(), com.cliffc.aa.HM.HM4.T2.fun(), com.cliffc.aa.HM.HM4.Syntax.hm(), com.cliffc.aa.type.TypeInt.INT64, com.cliffc.aa.util.Ary< E >.isEmpty(), com.cliffc.aa.HM.HM4.Syntax.more_work(), com.cliffc.aa.HM.HM4.Syntax.prep_tree(), com.cliffc.aa.HM.HM4.T2.prim(), com.cliffc.aa.HM.HM4.PRIMS, com.cliffc.aa.HM.HM4.T2.progress(), com.cliffc.aa.util.Ary< E >.push(), com.cliffc.aa.type.TypeMemPtr.STRPTR, and com.cliffc.aa.HM.HM4.T2.tnew().
Referenced by com.cliffc.aa.HM.TestHM4.test00(), com.cliffc.aa.HM.TestHM4.test01(), com.cliffc.aa.HM.TestHM4.test02(), com.cliffc.aa.HM.TestHM4.test03(), com.cliffc.aa.HM.TestHM4.test04(), com.cliffc.aa.HM.TestHM4.test05(), com.cliffc.aa.HM.TestHM4.test06(), com.cliffc.aa.HM.TestHM4.test07(), com.cliffc.aa.HM.TestHM4.test08(), com.cliffc.aa.HM.TestHM4.test09(), com.cliffc.aa.HM.TestHM4.test10(), com.cliffc.aa.HM.TestHM4.test11(), com.cliffc.aa.HM.TestHM4.test12(), com.cliffc.aa.HM.TestHM4.test13(), com.cliffc.aa.HM.TestHM4.test14(), com.cliffc.aa.HM.TestHM4.test15(), com.cliffc.aa.HM.TestHM4.test16(), com.cliffc.aa.HM.TestHM4.test17(), com.cliffc.aa.HM.TestHM4.test18(), com.cliffc.aa.HM.TestHM4.test19(), com.cliffc.aa.HM.TestHM4.test20(), com.cliffc.aa.HM.TestHM4.test21(), com.cliffc.aa.HM.TestHM4.test22(), and com.cliffc.aa.HM.TestHM4.test23().
reset()
static void com.cliffc.aa.HM.HM4.reset () static package
Definition at line 72 of file HM4.java.
 { PRIMS.clear(); T2.reset(); }
References com.cliffc.aa.HM.HM4.PRIMS, and com.cliffc.aa.HM.HM4.T2.reset().
Referenced by com.cliffc.aa.HM.TestHM4.reset().
Member Data Documentation
PRIMS
final HashMap<String,T2> com.cliffc.aa.HM.HM4.PRIMS = new HashMap<>() static package
Definition at line 20 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Ident.prep_tree(), and com.cliffc.aa.HM.HM4.reset().
The documentation for this class was generated from the following file:
HM4.java