aa: com.cliffc.aa.HM.HM6 Class Reference
com.cliffc.aa.HM.HM6 Class Reference
Classes
class Apply
class Con
class Ident
class Lambda
class Lambda2
class Let
class Syntax
class T2
class VStack
class Worklist
Public Member Functions
String toString ()
Static Public Member Functions
static T2 hm (String sprog)
Static Package Functions
static Syntax parse (String s)
static void reset ()
static Syntax term ()
Static Package Attributes
static boolean DEBUG_LEAKS =false
static final HashMap< String, T2 > PRIMS = new HashMap<>()
Static Private Member Functions
static String id ()
static boolean isAlpha0 (byte c)
static boolean isAlpha1 (byte c)
static boolean isDigit (byte c)
static boolean isWS (byte c)
static Syntax number ()
static< T > T require (char c, T t)
static void require (String s)
static byte skipWS ()
static Syntax string ()
Static Private Attributes
static byte[] BUF
static final SB ID = new SB()
static int X
Detailed Description
Definition at line 23 of file HM6.java.
Member Function Documentation
hm()
static T2 com.cliffc.aa.HM.HM6.hm (String sprog) static
Definition at line 27 of file HM6.java.
{
     Worklist work = new Worklist();
     // Simple types
     T2 bool  = T2.make_base(TypeInt.BOOL);
     T2 int64 = T2.make_base(TypeInt.INT64);
     T2 flt64 = T2.make_base(TypeFlt.FLT64);
     T2 strp  = T2.make_base(TypeMemPtr.STRPTR);
     // Primitives
     T2 var1 = T2.make_leaf();
     T2 var2 = T2.make_leaf();
     PRIMS.put("pair1",T2.make_fun(var1, T2.make_fun(var2, T2.prim("pair",var1,var2) )));
     PRIMS.put("pair",T2.make_fun(var1, var2, T2.prim("pair",var1,var2) ));
     PRIMS.put("if/else",T2.make_fun(bool,var1,var1,var1));
     PRIMS.put("dec",T2.make_fun(int64,int64));
     PRIMS.put("*"  ,T2.make_fun(int64,int64,int64));
     PRIMS.put("==0",T2.make_fun(int64,bool));
     PRIMS.put("isempty",T2.make_fun(strp,bool));
     // Print a string; int->str
     PRIMS.put("str",T2.make_fun(int64,strp));
     // Factor; FP div/mod-like operation
     PRIMS.put("factor",T2.make_fun(flt64,T2.prim("divmod",flt64,flt64)));
     // Parse
     Syntax prog = parse( sprog );
     // Prep for SSA: pre-gather all the (unique) ids
     int cnt_syns = prog.prep_tree(null,null,work);
     int init_T2s = T2.CNT;
     int cnt=0, DEBUG_CNT=-1;
     while( work.len()>0 ) {     // While work
       int oldcnt = T2.CNT;      // Used for cost-check when no-progress
       Syntax syn = work.pop();  // Get work
       T2 old = syn._t;          // Old value for progress assert
       if( cnt==DEBUG_CNT )
         System.out.println("break here");
       if( syn.hm(work) ) {      // Compute a new HM type and check for progress
         assert !syn.debug_find().unify(old.find(),null);// monotonic: unifying with the result is no-progress
         syn.add_kids(work);     // Push children on worklist
         syn.add_occurs(work);   // Push occurs-check ids on worklist
         if( syn._par !=null ) work.push(syn._par); // Parent updates
       } else {
         assert !DEBUG_LEAKS || oldcnt==T2.CNT;  // No-progress consumes no-new-T2s
       }
       // VERY EXPENSIVE ASSERT: O(n^2).  Every Syntax that makes progress is on the worklist
       //assert prog.more_work(work);
       cnt++;
     }
     assert prog.more_work(work);
     //System.out.println("Initial T2s: "+init_T2s+", Prog size: "+cnt_syns+", worklist iters: "+cnt+", T2s: "+T2.CNT);
     return prog._t;
   }
References com.cliffc.aa.HM.HM6.Syntax._par, com.cliffc.aa.HM.HM6.Syntax._t, com.cliffc.aa.HM.HM6.Syntax.add_kids(), com.cliffc.aa.HM.HM6.Syntax.add_occurs(), com.cliffc.aa.type.TypeInt.BOOL, com.cliffc.aa.HM.HM6.T2.CNT, com.cliffc.aa.HM.HM6.Syntax.debug_find(), com.cliffc.aa.HM.HM6.DEBUG_LEAKS, com.cliffc.aa.HM.HM6.T2.find(), com.cliffc.aa.type.TypeFlt.FLT64, com.cliffc.aa.HM.HM6.Syntax.hm(), com.cliffc.aa.type.TypeInt.INT64, com.cliffc.aa.HM.HM6.Worklist.len(), com.cliffc.aa.HM.HM6.T2.make_base(), com.cliffc.aa.HM.HM6.T2.make_fun(), com.cliffc.aa.HM.HM6.T2.make_leaf(), com.cliffc.aa.HM.HM6.Syntax.more_work(), com.cliffc.aa.HM.HM6.parse(), com.cliffc.aa.HM.HM6.Worklist.pop(), com.cliffc.aa.HM.HM6.Syntax.prep_tree(), com.cliffc.aa.HM.HM6.T2.prim(), com.cliffc.aa.HM.HM6.PRIMS, com.cliffc.aa.HM.HM6.Worklist.push(), com.cliffc.aa.type.TypeMemPtr.STRPTR, and com.cliffc.aa.HM.HM6.T2.unify().
Referenced by com.cliffc.aa.HM.TestHM6.test00(), com.cliffc.aa.HM.TestHM6.test01(), com.cliffc.aa.HM.TestHM6.test02(), com.cliffc.aa.HM.TestHM6.test03(), com.cliffc.aa.HM.TestHM6.test04(), com.cliffc.aa.HM.TestHM6.test05(), com.cliffc.aa.HM.TestHM6.test06(), com.cliffc.aa.HM.TestHM6.test07(), com.cliffc.aa.HM.TestHM6.test08(), com.cliffc.aa.HM.TestHM6.test09(), com.cliffc.aa.HM.TestHM6.test10(), com.cliffc.aa.HM.TestHM6.test11(), com.cliffc.aa.HM.TestHM6.test12(), com.cliffc.aa.HM.TestHM6.test13(), com.cliffc.aa.HM.TestHM6.test14(), com.cliffc.aa.HM.TestHM6.test15(), com.cliffc.aa.HM.TestHM6.test16(), com.cliffc.aa.HM.TestHM6.test17(), com.cliffc.aa.HM.TestHM6.test18(), com.cliffc.aa.HM.TestHM6.test19(), com.cliffc.aa.HM.TestHM6.test20(), com.cliffc.aa.HM.TestHM6.test21(), com.cliffc.aa.HM.TestHM6.test22(), and com.cliffc.aa.HM.TestHM6.test23().
id()
static String com.cliffc.aa.HM.HM6.id () static private
Definition at line 135 of file HM6.java.
{
     ID.clear();
     while( X<BUF.length && isAlpha1(BUF[X]) )
       ID.p((char)BUF[X++]);
     return ID.toString().intern();
   }
References com.cliffc.aa.HM.HM6.BUF, com.cliffc.aa.util.SB.clear(), com.cliffc.aa.HM.HM6.ID, com.cliffc.aa.HM.HM6.isAlpha1(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.util.SB.toString(), and com.cliffc.aa.HM.HM6.X.
Referenced by com.cliffc.aa.HM.HM6.term().
isAlpha0()
static boolean com.cliffc.aa.HM.HM6.isAlpha0 (byte c) static private
Definition at line 162 of file HM6.java.
 { return ('a'<=c && c <= 'z') || ('A'<=c && c <= 'Z') || (c=='_') || (c=='*') || (c=='='); }
Referenced by com.cliffc.aa.HM.HM6.isAlpha1(), and com.cliffc.aa.HM.HM6.term().
isAlpha1()
static boolean com.cliffc.aa.HM.HM6.isAlpha1 (byte c) static private
Definition at line 163 of file HM6.java.
 { return isAlpha0(c) || ('0'<=c && c <= '9') || (c=='/'); }
References com.cliffc.aa.HM.HM6.isAlpha0().
Referenced by com.cliffc.aa.HM.HM6.id().
isDigit()
static boolean com.cliffc.aa.HM.HM6.isDigit (byte c) static private
Definition at line 161 of file HM6.java.
 { return '0' <= c && c <= '9'; }
Referenced by com.cliffc.aa.HM.HM6.number(), and com.cliffc.aa.HM.HM6.term().
isWS()
static boolean com.cliffc.aa.HM.HM6.isWS (byte c) static private
Definition at line 160 of file HM6.java.
 { return c == ' ' || c == '\t' || c == '\n' || c == '\r'; }
Referenced by com.cliffc.aa.HM.HM6.skipWS().
number()
static Syntax com.cliffc.aa.HM.HM6.number () static private
Definition at line 141 of file HM6.java.
{
     int sum=0;
     while( X<BUF.length && isDigit(BUF[X]) )
       sum = sum*10+BUF[X++]-'0';
     if( X>= BUF.length || BUF[X]!='.' ) return new Con(TypeInt.con(sum));
     X++;
     float f = (float)sum;
     f = f + (BUF[X++]-'0')/10.0f;
     return new Con(TypeFlt.con(f));
   }
References com.cliffc.aa.HM.HM6.BUF, com.cliffc.aa.type.TypeFlt.con(), com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM6.isDigit(), and com.cliffc.aa.HM.HM6.X.
Referenced by com.cliffc.aa.HM.HM6.term().
parse()
static Syntax com.cliffc.aa.HM.HM6.parse (String s) static package
Definition at line 93 of file HM6.java.
{
     X = 0;
     BUF = s.getBytes();
     Syntax prog = term();
     if( skipWS() != -1 ) throw unimpl("Junk at end of program: "+new String(BUF,X,BUF.length-X));
     return prog;
   }
References com.cliffc.aa.HM.HM6.BUF, com.cliffc.aa.HM.HM6.skipWS(), com.cliffc.aa.HM.HM6.term(), and com.cliffc.aa.HM.HM6.X.
Referenced by com.cliffc.aa.HM.HM6.hm().
require() [1/2]
static <T> T com.cliffc.aa.HM.HM6.require (char c, T t) static private
Definition at line 164 of file HM6.java.
 { if( skipWS()!=c ) throw unimpl("Missing '"+c+"'"); X++; return t; }
References com.cliffc.aa.HM.HM6.skipWS(), and com.cliffc.aa.HM.HM6.X.
Referenced by com.cliffc.aa.HM.HM6.string(), and com.cliffc.aa.HM.HM6.term().
require() [2/2]
static void com.cliffc.aa.HM.HM6.require (String s) static private
Definition at line 165 of file HM6.java.
{
     skipWS();
     for( int i=0; i<s.length(); i++ )
       if( X+i >= BUF.length || BUF[X+i]!=s.charAt(i) )
         throw unimpl("Missing '"+s+"'");
     X+=s.length();
   }
References com.cliffc.aa.HM.HM6.BUF, com.cliffc.aa.HM.HM6.skipWS(), and com.cliffc.aa.HM.HM6.X.
reset()
static void com.cliffc.aa.HM.HM6.reset () static package
Definition at line 86 of file HM6.java.
 { PRIMS.clear(); T2.reset(); }
References com.cliffc.aa.HM.HM6.PRIMS, and com.cliffc.aa.HM.HM6.T2.reset().
skipWS()
static byte com.cliffc.aa.HM.HM6.skipWS () static private
Definition at line 156 of file HM6.java.
{
     while( X<BUF.length && isWS(BUF[X]) ) X++;
     return X==BUF.length ? -1 : BUF[X];
   }
References com.cliffc.aa.HM.HM6.BUF, com.cliffc.aa.HM.HM6.isWS(), and com.cliffc.aa.HM.HM6.X.
Referenced by com.cliffc.aa.HM.HM6.parse(), com.cliffc.aa.HM.HM6.require(), and com.cliffc.aa.HM.HM6.term().
string()
static Syntax com.cliffc.aa.HM.HM6.string () static private
Definition at line 151 of file HM6.java.
{
     int start = ++X;
     while( X<BUF.length && BUF[X]!='"' ) X++;
     return require('"', new Con(TypeStr.con(new String(BUF,start,X-start).intern())));
   }
References com.cliffc.aa.HM.HM6.BUF, com.cliffc.aa.type.TypeStr.con(), com.cliffc.aa.HM.HM6.require(), and com.cliffc.aa.HM.HM6.X.
Referenced by com.cliffc.aa.HM.HM6.term().
term()
static Syntax com.cliffc.aa.HM.HM6.term () static package
Definition at line 100 of file HM6.java.
{
     if( skipWS()==-1 ) return null;
     if( isDigit(BUF[X]) ) return number();
     if( BUF[X]=='"' ) return string();
     if( BUF[X]=='(' ) {         // Parse an Apply
       X++;                      // Skip paren
       Syntax fun = term();
       Ary<Syntax> ARGS = new Ary<>(new Syntax[1],0);
       while( skipWS()!= ')' && X<BUF.length ) ARGS.push(term());
       return new Apply(fun,require(')',ARGS.asAry()));
     }
     if( BUF[X]=='{' ) {         // Lambda of 1 or 2 args
       X++;                      // Skip paren
       skipWS();
       String arg0 = id(), arg1=null;
       if( skipWS()!='-' ) arg1 = id();
       require("->");
       Syntax body = require('}',term());
       return arg1==null
         ? new Lambda (arg0,     body)
         : new Lambda2(arg0,arg1,body);
     }
     // Let or Id
     if( isAlpha0(BUF[X]) ) {
       String id = id();
       if( skipWS()!='=' )  return new Ident(id);
       // Let expression; "id = term(); term..."
       X++;                      // Skip '='
       Syntax def = require(';',term());
       return new Let(id,def,term());
     }
     throw unimpl();
   }
References com.cliffc.aa.util.Ary< E >.asAry(), com.cliffc.aa.HM.HM6.BUF, com.cliffc.aa.HM.HM6.id(), com.cliffc.aa.HM.HM6.isAlpha0(), com.cliffc.aa.HM.HM6.isDigit(), com.cliffc.aa.HM.HM6.number(), com.cliffc.aa.util.Ary< E >.push(), com.cliffc.aa.HM.HM6.require(), com.cliffc.aa.HM.HM6.skipWS(), com.cliffc.aa.HM.HM6.string(), and com.cliffc.aa.HM.HM6.X.
Referenced by com.cliffc.aa.HM.HM6.parse().
toString()
String com.cliffc.aa.HM.HM6.toString ()
Definition at line 92 of file HM6.java.
 { return new String(BUF,X,BUF.length-X); }
References com.cliffc.aa.HM.HM6.BUF, and com.cliffc.aa.HM.HM6.X.
Member Data Documentation
BUF
byte [] com.cliffc.aa.HM.HM6.BUF static private
Definition at line 91 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.id(), com.cliffc.aa.HM.HM6.number(), com.cliffc.aa.HM.HM6.parse(), com.cliffc.aa.HM.HM6.require(), com.cliffc.aa.HM.HM6.skipWS(), com.cliffc.aa.HM.HM6.string(), com.cliffc.aa.HM.HM6.term(), and com.cliffc.aa.HM.HM6.toString().
DEBUG_LEAKS
boolean com.cliffc.aa.HM.HM6.DEBUG_LEAKS =false static package
Definition at line 25 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.T2.fresh_unify(), and com.cliffc.aa.HM.HM6.hm().
ID
final SB com.cliffc.aa.HM.HM6.ID = new SB() static private
Definition at line 134 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.id().
PRIMS
final HashMap<String,T2> com.cliffc.aa.HM.HM6.PRIMS = new HashMap<>() static package
Definition at line 24 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.Ident.add_occurs(), com.cliffc.aa.HM.HM6.hm(), com.cliffc.aa.HM.HM6.Ident.hm(), and com.cliffc.aa.HM.HM6.reset().
X
int com.cliffc.aa.HM.HM6.X static private
Definition at line 90 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.id(), com.cliffc.aa.HM.HM6.number(), com.cliffc.aa.HM.HM6.parse(), com.cliffc.aa.HM.HM6.require(), com.cliffc.aa.HM.HM6.skipWS(), com.cliffc.aa.HM.HM6.string(), com.cliffc.aa.HM.HM6.term(), and com.cliffc.aa.HM.HM6.toString().
The documentation for this class was generated from the following file:
HM6.java