aa: com.cliffc.aa.tvar.TV2 Class Reference
com.cliffc.aa.tvar.TV2 Class Reference
Classes
class ACnts
Public Member Functions
void args_put (Comparable key, TV2 tv)
boolean eq (Node[] args)
final boolean eq (TV2 that)
TV2 find ()
final int find_dups (VBitSet bs, NonBlockingHashMapLong< String > dups, int scnt)
Type find_tvar (Type t, TV2 tv)
void free ()
boolean fresh_unify (TV2 that, TV2[] vs, boolean test)
TV2 get (Comparable key)
TV2 get_unified ()
boolean is_base ()
boolean is_dead ()
boolean is_err ()
boolean is_free ()
boolean is_leaf ()
boolean is_nil ()
boolean is_tvar ()
boolean is_unified ()
boolean isa (String s)
String name ()
TV2 push_dep (CallEpiNode dep)
TV2 repl_rename (TV2[]vs, HashMap< Node, Node > map)
void reset (Node n)
void reset_at (Object o)
final String str (int d)
final SB str (SB sb, VBitSet bs, NonBlockingHashMapLong< String > dups, boolean debug, int d, int max)
final String toString ()
boolean unify (TV2 that, boolean test)
boolean unify_alias (BitsAlias aliases, TV2 mem, boolean test)
boolean unify_alias_fld (Node ldst, BitsAlias aliases, String fld, TV2 tv, boolean test, String alloc_site)
boolean unify_at (Comparable key, TV2 tv2, boolean test)
boolean union (TV2 that)
Static Public Member Functions
static TV2 get (TV2[] vs, int i)
static TV2 make (@NotNull String name, Node n, @NotNull String alloc_site)
static TV2 make (@NotNull String name, Node n, @NotNull String alloc_site, Node... ntvs)
static TV2 make (@NotNull String name, Node n, @NotNull String alloc_site, NonBlockingHashMap< Comparable, TV2 > args)
static TV2 make (@NotNull String name, UQNodes ns, @NotNull String alloc_site)
static TV2 make_base (Node n, Type type, @NotNull String alloc_site)
static TV2 make_err (Node n, String msg, @NotNull String alloc_site)
static TV2 make_leaf (Node n, @NotNull String alloc_site)
static TV2 make_leaf_ns (UQNodes ns, @NotNull String alloc_site)
static TV2 make_mem (Node n, @NotNull String alloc_site)
static void reset_to_init0 ()
Public Attributes
String _alloc_site
NonBlockingHashMap< Comparable, TV2 > _args
UQNodes _deps
UQNodes _ns
Type _type
final int _uid
Static Public Attributes
static TV2 DEAD = new TV2("Dead",null,null,null,"static")
static TV2 NIL = new TV2("Nil" ,null,null,null,"static")
Package Functions
boolean _cycle_equals (TV2 that)
boolean _occurs_in (TV2[] vs)
boolean _occurs_in_type (TV2 x)
boolean cycle_equals (TV2 that)
boolean is_prim ()
boolean occurs_in (TV2[] vs)
Static Package Attributes
static final VBitSet DEPS_VISIT = new VBitSet()
Private Member Functions
TV2 (@NotNull String name, NonBlockingHashMap< Comparable, TV2 > args, Type type, UQNodes ns, @NotNull String alloc_site)
boolean _eq (TV2 that)
Type _find_tvar (Type t, TV2 tv, Type rez)
boolean _fresh_unify (TV2 that, TV2[] vs, boolean test)
void _push_update (CallEpiNode dep)
void _rename (TV2 tv, HashMap< Node, Node > map)
boolean _unify (TV2 that, boolean test)
TV2 _union (TV2 that)
boolean fresh_base (TV2 that, boolean test)
void merge_deps (TV2 that)
void merge_ns (TV2 that)
TV2 repl (TV2[] vs)
boolean unify_base (TV2 that)
boolean union_err (TV2 that, String msg)
TV2 vput (TV2 that)
boolean vput (TV2 that, boolean progress)
Private Attributes
String _name
TV2 _unified
Static Private Attributes
static final HashMap< String, ACnts > ALLOCS = new HashMap<>()
static final HashMap< TV2, TV2 > CDUPS = new HashMap<>()
static final NonBlockingHashMapLong< TV2 > DUPS = new NonBlockingHashMapLong<>()
static final VBitSet ODUPS = new VBitSet()
static int UID =1
static final HashMap< TV2, TV2 > VARS = new HashMap<>()
Detailed Description
Definition at line 23 of file TV2.java.
Constructor & Destructor Documentation
TV2()
com.cliffc.aa.tvar.TV2.TV2 (@NotNull String name, NonBlockingHashMap< Comparable, TV2 > args, Type type, UQNodes ns, @NotNull String alloc_site) private
Definition at line 63 of file TV2.java.
{
     _uid = UID++;
     _name = name;
     _args = args;
     _type = type;
     _deps = null;               // Lazy added
     _ns = ns;
     _alloc_site = alloc_site;
     ACnts ac = ALLOCS.computeIfAbsent(alloc_site,e -> new ACnts());
     ac._malloc++;
   }
References com.cliffc.aa.tvar.TV2._alloc_site, com.cliffc.aa.tvar.TV2._args, com.cliffc.aa.tvar.TV2._deps, com.cliffc.aa.tvar.TV2.ACnts._malloc, com.cliffc.aa.tvar.TV2._name, com.cliffc.aa.tvar.TV2._ns, com.cliffc.aa.tvar.TV2._type, com.cliffc.aa.tvar.TV2._uid, com.cliffc.aa.tvar.TV2.ALLOCS, com.cliffc.aa.tvar.TV2.name(), and com.cliffc.aa.tvar.TV2.UID.
Referenced by com.cliffc.aa.tvar.TV2.make(), com.cliffc.aa.tvar.TV2.make_base(), com.cliffc.aa.tvar.TV2.make_err(), com.cliffc.aa.tvar.TV2.make_leaf_ns(), and com.cliffc.aa.tvar.TV2.repl().
Member Function Documentation
_cycle_equals()
boolean com.cliffc.aa.tvar.TV2._cycle_equals (TV2 that) package
Definition at line 646 of file TV2.java.
{
     assert !is_unified() && !that.is_unified();
     if( this==that ) return true;
     if( is_base() && that.is_base() )
       return _type==that._type; // Base-cases have to be completely identical
     if( !Util.eq(_name,that._name) ) return false; // Wrong type-var names
     if( is_leaf() || that.is_leaf() ) return false;       // Unequal leaves are unequal
     if( _args==that._args && !is_leaf() ) return true;    // Both null is OK
     if( _args.size() != that._args.size() ) return false; // Mismatched sizes
     // Cycles stall the equal/unequal decision until we see a difference.
     TV2 tc = CDUPS.get(this);
     if( tc!=null )
       return tc==that; // Cycle check; true if both cycling the same
     CDUPS.put(this,that);
     for( Comparable key : _args.keySet() ) {
       TV2 lhs =      get(key);  assert lhs!=null;
       TV2 rhs = that.get(key);
       if( rhs==null || !lhs._cycle_equals(rhs) ) return false;
     }
     return true;
   }
References com.cliffc.aa.tvar.TV2._args, com.cliffc.aa.tvar.TV2._cycle_equals(), com.cliffc.aa.tvar.TV2._name, com.cliffc.aa.tvar.TV2._type, com.cliffc.aa.tvar.TV2.CDUPS, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.tvar.TV2.get(), com.cliffc.aa.tvar.TV2.is_base(), com.cliffc.aa.tvar.TV2.is_leaf(), and com.cliffc.aa.tvar.TV2.is_unified().
Referenced by com.cliffc.aa.tvar.TV2._cycle_equals(), and com.cliffc.aa.tvar.TV2.cycle_equals().
_eq()
boolean com.cliffc.aa.tvar.TV2._eq (TV2 that) private
Definition at line 207 of file TV2.java.
{
     if( this==that ) return true;
     assert !is_unified() && !that.is_unified();
     if( !Util.eq(_name,that._name) ) return false;
     if( is_base() ) return _type==that._type; // Base types are equal if base _types are equal
     if( is_leaf() ) {                         // Leafs are equal if they always map the same
       TV2 eq2 = VARS.computeIfAbsent(this,k -> that);
       return that==eq2;
     }
     if( _args.size() != that._args.size() ) return false;
     // Cyclic check
     long luid = ((long)_uid<<32)|that._uid; // Make a unique id for the pair
     if( DUPS.get(luid)!=null ) return true; // Cyclic, wrapped.  Something else determines eq/ne
     DUPS.put(luid,this);                    // Mark for cycle
     // Structural recursion
     for( Comparable key : _args.keySet() )
       if( !get(key)._eq(that.get(key)) )
         return false;
     return true;
   }
References com.cliffc.aa.tvar.TV2._args, com.cliffc.aa.tvar.TV2._name, com.cliffc.aa.tvar.TV2._type, com.cliffc.aa.tvar.TV2._uid, com.cliffc.aa.tvar.TV2.DUPS, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.tvar.TV2.get(), com.cliffc.aa.tvar.TV2.is_base(), com.cliffc.aa.tvar.TV2.is_leaf(), com.cliffc.aa.tvar.TV2.is_unified(), and com.cliffc.aa.tvar.TV2.VARS.
Referenced by com.cliffc.aa.tvar.TV2.eq().
_find_tvar()
Type com.cliffc.aa.tvar.TV2._find_tvar (Type t, TV2 tv, Type rez) private
Definition at line 541 of file TV2.java.
{
     if( tv.is_dead() ) return rez;
     if( t==Type.ALL ) return rez; // Join against 'ALL' never changes anything
     if( tv==this ) {
       rez = rez.join(t);
       return rez;
     }
     switch(_name) {
     case "Mem":
       if( t ==Type.ANY ) return rez; // No substructure in type
       TypeMem tmem = (TypeMem)t;
       for( Comparable key : _args.keySet() ) {
         TypeObj to = tmem.at((Integer) key);
         TV2 obj = get(key);
         if( obj!=null )
           rez = obj._find_tvar(to,tv,rez);
       }
       return rez;
     case "Obj":
       if( t==TypeObj.UNUSED || t==TypeObj.ISUSED )
         return rez; // No substructure in type
       if( t instanceof TypeStr || t instanceof TypeAry )
         return rez; // TODO: Handle These
       TypeStruct ts = (TypeStruct)t; //
       for( Comparable key : _args.keySet() ) {
         //int idx = ts.find((String)key);
         //if( idx!= -1 )          // If field exists
         //  rez = get(key)._find_tvar(ts.at(idx),tv,rez);
         throw unimpl();
       }
       return rez;
     case "Fun":
       if( t.is_forward_ref() ) return rez;
       if( !(t instanceof TypeFunPtr) ) return rez;
       // TypeFunPtrs carry only a set of FIDXS & a DISPLAY.
       // Hence no other Type is available here for lifting.
       return rez;
     case "Ret":
       TypeTuple tt = (TypeTuple)t;
       for( int i=0; i<tt.len(); i++ )
         rez = get(i)._find_tvar(tt.at(i),tv,rez);
       return rez;
     case "Ptr":
       if( !(t instanceof TypeMemPtr) ) return rez;
       return get(0)._find_tvar(((TypeMemPtr)t)._obj,tv,rez);
     case "Base":
     case "Dead":
     case "Err":
     case "Leaf":
     case "Nil":
       return rez; // No substructure in TV2 and not equal already
     default: throw com.cliffc.aa.AA.unimpl();
     }
   }
References com.cliffc.aa.tvar.TV2._args, com.cliffc.aa.tvar.TV2._find_tvar(), com.cliffc.aa.tvar.TV2._name, com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.type.TypeTuple.at(), com.cliffc.aa.tvar.TV2.is_dead(), com.cliffc.aa.type.Type< T extends Type< T >.is_forward_ref(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.ISUSED, com.cliffc.aa.type.Type< T extends Type< T >.join(), com.cliffc.aa.type.TypeTuple.len(), com.cliffc.aa.AA.unimpl(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED.
Referenced by com.cliffc.aa.tvar.TV2._find_tvar(), and com.cliffc.aa.tvar.TV2.find_tvar().
_fresh_unify()
boolean com.cliffc.aa.tvar.TV2._fresh_unify (TV2 that, TV2[] vs, boolean test) private
Definition at line 384 of file TV2.java.
{
     assert !is_unified() && !that.is_unified();
     // Several trivial cases that do not really do any work
     if( this==that ) return false;
     if( that.is_dead() ) return false;
     if( this.is_dead() ) return that.union(this); // Kill 'that', same as LHS
     if( this.is_nil() || that.is_nil() ) return false;
     // Check for closing cycles
     TV2 prior = VARS.get(this);
     if( prior!=null )           // Been there, done that?  Return prior mapping
       return prior.find()._unify(that, test);
     if( cycle_equals(that) ) return vput(that,false);
     if( that.is_err() ) return vput(that,false); // That is an error, ignore 'this' and no progress
     if( this.is_err() ) return vput(that,_unify(that,test));
     // Famous 'occurs-check', switch to normal unify
     if( occurs_in( vs ) ) return vput(that,_unify(that,test));
     // Either side is a Leaf, unify to the other (perhaps with a fresh copy)
     if( this.is_leaf() ) return vput(that,false); // Lazy map LHS tvar to RHS
     if( that.is_leaf() )          // RHS is a leaf tvar; union with a copy of LHS
       return test || vput(that,that.union(repl(vs)));
     // Bases MEET cons in RHS
     if( is_base() && that.is_base() ) return vput(that,fresh_base(that,test));
     // Should be structurally equal now
     if( !Util.eq(_name,that._name) )
       throw com.cliffc.aa.AA.unimpl(); // unification error
     // Structural recursion unification, lazy on LHS
     boolean progress = vput(that,false); // Early set, to stop cycles
     for( Comparable key : _args.keySet() ) {
       TV2 lhs =      get(key);  assert lhs!=null;
       TV2 rhs = that.get(key);
       if( rhs==null ) {         // No RHS to unify against
         if( !test ) {           // RHS is a fresh copy of the LHS
           that.args_put(key,lhs.repl(vs));
           Env.GVN.add_flow(that._deps); // Re-CallEpi
         }
         progress = true;
       } else {
         progress |= lhs._fresh_unify(rhs,vs,test);
       }
       if( progress && test ) return true;
     }
     return progress;
   }
References com.cliffc.aa.tvar.TV2._args, com.cliffc.aa.tvar.TV2._deps, com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.tvar.TV2._name, com.cliffc.aa.tvar.TV2._unify(), com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.tvar.TV2.args_put(), com.cliffc.aa.tvar.TV2.cycle_equals(), com.cliffc.aa.util.Util.eq(), com.cliffc.aa.tvar.TV2.find(), com.cliffc.aa.tvar.TV2.fresh_base(), com.cliffc.aa.tvar.TV2.get(), com.cliffc.aa.Env.GVN, com.cliffc.aa.tvar.TV2.is_base(), com.cliffc.aa.tvar.TV2.is_dead(), com.cliffc.aa.tvar.TV2.is_err(), com.cliffc.aa.tvar.TV2.is_leaf(), com.cliffc.aa.tvar.TV2.is_nil(), com.cliffc.aa.tvar.TV2.is_unified(), com.cliffc.aa.tvar.TV2.occurs_in(), com.cliffc.aa.tvar.TV2.repl(), com.cliffc.aa.AA.unimpl(), com.cliffc.aa.tvar.TV2.union(), com.cliffc.aa.tvar.TV2.VARS, and com.cliffc.aa.tvar.TV2.vput().
Referenced by com.cliffc.aa.tvar.TV2._fresh_unify().
_occurs_in()
boolean com.cliffc.aa.tvar.TV2._occurs_in (TV2[] vs) package
Definition at line 611 of file TV2.java.
{
     // Can NOT modify 'vs' for U-F, because blows FreshNode hash.
     for( TV2 v : vs )
       if( _occurs_in_type(v.find()) )
         return true;
     return false;
   }
References com.cliffc.aa.tvar.TV2._occurs_in_type().
Referenced by com.cliffc.aa.tvar.TV2.occurs_in().
_occurs_in_type()
boolean com.cliffc.aa.tvar.TV2._occurs_in_type (TV2 x) package
Definition at line 619 of file TV2.java.
{
     assert !is_unified() && !x.is_unified();
     if( x==this ) return true;
     if( ODUPS.tset(x._uid) ) return false; // Been there, done that
     if( !x.is_leaf() && x._args!=null )
       for( Comparable key : x._args.keySet() )
         if( _occurs_in_type(x.get(key)) )
           return true;
     return false;
   }
References com.cliffc.aa.tvar.TV2._args, com.cliffc.aa.tvar.TV2._uid, com.cliffc.aa.tvar.TV2.get(), com.cliffc.aa.tvar.TV2.is_leaf(), com.cliffc.aa.tvar.TV2.is_unified(), com.cliffc.aa.tvar.TV2.ODUPS, and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.tvar.TV2._occurs_in().
_push_update()
void com.cliffc.aa.tvar.TV2._push_update (CallEpiNode dep) private
Definition at line 680 of file TV2.java.
{
     assert !is_unified();
     if( DEPS_VISIT.tset(_uid) ) return;
     if( _deps!=null && _deps.get(dep._uid)!=null ) return; // Already here and in all children
     if( isa("Dead") ) return;
     _deps = _deps==null ? UQNodes.make(dep) : _deps.add(dep);
     if( _args!=null )
       for( Comparable key : _args.keySet() ) // Structural recursion on a complex TV2
         get(key)._push_update(dep);
   }
References com.cliffc.aa.tvar.TV2._args, com.cliffc.aa.tvar.TV2._deps, com.cliffc.aa.tvar.TV2._uid, com.cliffc.aa.node.Node._uid, com.cliffc.aa.tvar.UQNodes.add(), com.cliffc.aa.tvar.TV2.DEPS_VISIT, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.get(), com.cliffc.aa.tvar.TV2.is_unified(), com.cliffc.aa.tvar.TV2.isa(), com.cliffc.aa.tvar.UQNodes.make(), and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.tvar.TV2.push_dep().
_rename()
void com.cliffc.aa.tvar.TV2._rename (TV2 tv, HashMap< Node, Node > map) private
Definition at line 468 of file TV2.java.
{
     if( DUPS.get(_uid) != null ) return; // Been there, remapped this
     DUPS.put(_uid,this);                 // Only remap once
     if( this==tv ) return;               // Using the same TVar
     assert tv._ns==null && tv._deps==null;
     tv._deps= _deps==null ? null : _deps.rename(map);
     tv._ns  = _ns  ==null ? null : _ns  .rename(map);
     if( _args != null )
       for( Comparable key : _args.keySet() )
         _args.get(key)._rename(tv.get(key),map);
   }
References com.cliffc.aa.tvar.TV2._args, com.cliffc.aa.tvar.TV2._deps, com.cliffc.aa.tvar.TV2._ns, com.cliffc.aa.tvar.TV2._uid, com.cliffc.aa.tvar.TV2.DUPS, com.cliffc.aa.tvar.TV2.get(), and com.cliffc.aa.tvar.UQNodes.rename().
Referenced by com.cliffc.aa.tvar.TV2.repl_rename().
_unify()
boolean com.cliffc.aa.tvar.TV2._unify (TV2 that, boolean test) private
Definition at line 300 of file TV2.java.
{
     assert !is_unified() && !that.is_unified();
     if( this==that ) return false;
     // Check for simple, non-recursive, unification.
     // NIL always loses and makes no progress (no structure implications)
     if( this.is_nil () ) return false;
     if( that.is_nil () ) return false;
     // All remaining paths make progress and return true.
     if( test ) return true;
     // Dead wins all
     if( this.is_dead() ) return that.union(this);
     if( that.is_dead() ) return this.union(that);
     // two errs union in either order, so keep lower uid (actually should merge error strings)
     if( is_err() && that.is_err() && _uid<that._uid ) return that.union(this);
     if(      is_err() ) return that.union(this);
     if( that.is_err() ) return      union(that);
     // Two leafs union in either order, so keep lower uid
     if( this.is_leaf() && that.is_leaf() && _uid < that._uid ) return that.union(this);
     if( this.is_leaf() ) return this.union(that);
     if( that.is_leaf() ) return that.union(this);
     // Bases unify constants also
     if( this.is_base() && that.is_base() ) return unify_base(that);
     // Cycle check.
     long luid = ((long)_uid<<32)|that._uid; // Make a unique id for the pair
     TV2 rez = DUPS.get(luid);
     if( rez!=null ) return false; // Been there, done that
     DUPS.put(luid,that);          // Close cycles
     // Errors
     if( !Util.eq(_name,that._name) )
       return union_err(that,"Cannot unify "+this+" and "+that);
     assert _args!=that._args; // Efficiency hack elsewhere if this is true here
     // Structural recursion unification, this into that.
     for( Comparable key : _args.keySet() ) {
       TV2 vthis =       get(key);  assert vthis!=null;
       TV2 vthat =  that.get(key);
       if( vthat==null ) that.args_put(key,vthis);
       else              { vthis._unify(vthat,test); that = that.find(); }
       assert !that.is_unified();
     }
     // TODO: Check for being equal, cyclic-ly, and return a prior if possible.
     return find().union(that);
   }
References com.cliffc.aa.tvar.TV2._args, com.cliffc.aa.tvar.TV2._name, com.cliffc.aa.tvar.TV2._uid, com.cliffc.aa.tvar.TV2._unify(), com.cliffc.aa.tvar.TV2.args_put(), com.cliffc.aa.tvar.TV2.DUPS, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.tvar.TV2.find(), com.cliffc.aa.tvar.TV2.get(), com.cliffc.aa.tvar.TV2.is_base(), com.cliffc.aa.tvar.TV2.is_dead(), com.cliffc.aa.tvar.TV2.is_err(), com.cliffc.aa.tvar.TV2.is_leaf(), com.cliffc.aa.tvar.TV2.is_nil(), com.cliffc.aa.tvar.TV2.is_unified(), com.cliffc.aa.tvar.TV2.unify_base(), com.cliffc.aa.tvar.TV2.union(), and com.cliffc.aa.tvar.TV2.union_err().
Referenced by com.cliffc.aa.tvar.TV2._fresh_unify(), and com.cliffc.aa.tvar.TV2._unify().
_union()
TV2 com.cliffc.aa.tvar.TV2._union (TV2 that) private
Definition at line 270 of file TV2.java.
{
     TV2 old = _unified;
     _unified=that;
     assert is_unified();
     merge_deps(that);           // Merge update lists, for future unions
     merge_ns  (that);           // Merge Node list, for easier debugging
     _deps = null;
     _ns   = null;
     return old;
   }
References com.cliffc.aa.tvar.TV2._deps, com.cliffc.aa.tvar.TV2._ns, com.cliffc.aa.tvar.TV2._unified, com.cliffc.aa.tvar.TV2.is_unified(), com.cliffc.aa.tvar.TV2.merge_deps(), and com.cliffc.aa.tvar.TV2.merge_ns().
Referenced by com.cliffc.aa.tvar.TV2.find(), and com.cliffc.aa.tvar.TV2.union().
args_put()
void com.cliffc.aa.tvar.TV2.args_put (Comparable key, TV2 tv)
Definition at line 99 of file TV2.java.
{
     _args.put(key,tv);          // Pick up a key->tv mapping
     merge_deps(tv);             // tv gets all deps that 'this' has
   }
References com.cliffc.aa.tvar.TV2._args, and com.cliffc.aa.tvar.TV2.merge_deps().
Referenced by com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.tvar.TV2._unify(), com.cliffc.aa.tvar.TV2.get(), com.cliffc.aa.tvar.TV2.repl(), com.cliffc.aa.node.LoadNode.unify(), com.cliffc.aa.tvar.TV2.unify_alias_fld(), and com.cliffc.aa.tvar.TV2.unify_at().
cycle_equals()
boolean com.cliffc.aa.tvar.TV2.cycle_equals (TV2 that) package
Definition at line 640 of file TV2.java.
{
     assert CDUPS.isEmpty();
     boolean rez = _cycle_equals(that);
     CDUPS.clear();
     return rez;
   }
References com.cliffc.aa.tvar.TV2._cycle_equals(), and com.cliffc.aa.tvar.TV2.CDUPS.
Referenced by com.cliffc.aa.tvar.TV2._fresh_unify().
eq() [1/2]
boolean com.cliffc.aa.tvar.TV2.eq (Node[] args)
Definition at line 231 of file TV2.java.
{
     for( int i=0; i<args.length; i++ )
       if( args[i]!=null && args[i].tvar()!=get(i) )
         return false;
     return true;
   }
eq() [2/2]
final boolean com.cliffc.aa.tvar.TV2.eq (TV2 that)
Definition at line 200 of file TV2.java.
{
     if( that==null ) return false;
     assert VARS.isEmpty() && DUPS.isEmpty();
     boolean eq = _eq(that);
     VARS.clear();  DUPS.clear();
     return eq;
   }
References com.cliffc.aa.tvar.TV2._eq(), com.cliffc.aa.tvar.TV2.DUPS, and com.cliffc.aa.tvar.TV2.VARS.
find()
TV2 com.cliffc.aa.tvar.TV2.find ()
Definition at line 240 of file TV2.java.
                     {
     if( !is_unified() ) return this;
     TV2 top = get_unified();
     if( !top.is_unified() ) return top;
     // Find U-F top
     int cnt=0;
     while( top.is_unified() && cnt++<100 ) top = top.get_unified();
     assert cnt<100;             // Infinite roll-up loop
     TV2 v = this;               // Rerun, rolling up to top
     while( v != top ) v = v._union(top);
     return top;
   }
References com.cliffc.aa.tvar.TV2._union(), com.cliffc.aa.tvar.TV2.get_unified(), and com.cliffc.aa.tvar.TV2.is_unified().
Referenced by com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.tvar.TV2._unify(), com.cliffc.aa.tvar.TV2.get(), com.cliffc.aa.node.Node.tvar(), com.cliffc.aa.node.LoadNode.unify(), and com.cliffc.aa.tvar.TV2.unify_alias_fld().
find_dups()
final int com.cliffc.aa.tvar.TV2.find_dups (VBitSet bs, NonBlockingHashMapLong< String > dups, int scnt)
Definition at line 720 of file TV2.java.
{
     if( bs.tset(_uid) ) {
       if( is_dead() || is_nil() ) return scnt;
       if( dups.containsKey(_uid) ) return scnt; // Already has a dup name
       dups.put(_uid,new String(new char[]{(char)('A'+scnt)}));
       return scnt+1;
     }
     if( is_unified() )
       return get_unified().find_dups(bs,dups,scnt);
     if( _args!=null )
       for( TV2 tv : _args.values() )
         if( !is_prim() )
           scnt = tv.find_dups(bs,dups,scnt);
     return scnt;
   }
References com.cliffc.aa.tvar.TV2._args, com.cliffc.aa.tvar.TV2._uid, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.containsKey(), com.cliffc.aa.tvar.TV2.find_dups(), com.cliffc.aa.tvar.TV2.get_unified(), com.cliffc.aa.tvar.TV2.is_dead(), com.cliffc.aa.tvar.TV2.is_nil(), com.cliffc.aa.tvar.TV2.is_prim(), com.cliffc.aa.tvar.TV2.is_unified(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.put(), and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.tvar.TV2.find_dups(), com.cliffc.aa.tvar.TV2.str(), com.cliffc.aa.Env.VStack.toString(), and com.cliffc.aa.tvar.TV2.toString().
find_tvar()
Type com.cliffc.aa.tvar.TV2.find_tvar (Type t, TV2 tv)
Definition at line 535 of file TV2.java.
{
     assert DUPS.isEmpty();
     Type rez = _find_tvar(t,tv,Type.ALL);
     DUPS.clear();
     return rez;
   }
References com.cliffc.aa.tvar.TV2._find_tvar(), com.cliffc.aa.type.Type< T extends Type< T >.ALL, and com.cliffc.aa.tvar.TV2.DUPS.
free()
void com.cliffc.aa.tvar.TV2.free ()
Definition at line 189 of file TV2.java.
                      {
     if( !is_unified() ) ALLOCS.get(_alloc_site)._free++;
     _name = "Free";
     _args = null;
     _type = null;
     _deps = null;
     _ns   = null;
   }
References com.cliffc.aa.tvar.TV2._alloc_site, com.cliffc.aa.tvar.TV2._args, com.cliffc.aa.tvar.TV2._deps, com.cliffc.aa.tvar.TV2._name, com.cliffc.aa.tvar.TV2._ns, com.cliffc.aa.tvar.TV2._type, com.cliffc.aa.tvar.TV2.ALLOCS, and com.cliffc.aa.tvar.TV2.is_unified().
fresh_base()
boolean com.cliffc.aa.tvar.TV2.fresh_base (TV2 that, boolean test) private
Definition at line 357 of file TV2.java.
{
     Type con = _type.meet(that._type);
     if( con==that._type ) return false; // No progress
     if( !test ) that._type = con;  // Yes progress, but no update if testing
     return true;
   }
References com.cliffc.aa.tvar.TV2._type, and com.cliffc.aa.type.Type< T extends Type< T >.meet().
Referenced by com.cliffc.aa.tvar.TV2._fresh_unify().
fresh_unify()
boolean com.cliffc.aa.tvar.TV2.fresh_unify (TV2 that, TV2[] vs, boolean test)
Definition at line 374 of file TV2.java.
{
     //assert VARS.isEmpty() && DUPS.isEmpty();
     //boolean progress = _fresh_unify(that,vs,test);
     //VARS.clear();  DUPS.clear();
     //return progress;
     throw unimpl();
   }
Referenced by com.cliffc.aa.node.FreshNode.unify().
get() [1/2]
TV2 com.cliffc.aa.tvar.TV2.get (Comparable key)
Definition at line 89 of file TV2.java.
{
     if( _args==null ) return null;
     TV2 tv = _args.get(key);
     if( tv==null ) return null;
     TV2 tv2 = tv.find();
     if( tv!=tv2 ) args_put(key,tv2);
     return tv2;
   }
References com.cliffc.aa.tvar.TV2._args, com.cliffc.aa.tvar.TV2.args_put(), and com.cliffc.aa.tvar.TV2.find().
Referenced by com.cliffc.aa.tvar.TV2._cycle_equals(), com.cliffc.aa.tvar.TV2._eq(), com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.tvar.TV2._occurs_in_type(), com.cliffc.aa.tvar.TV2._rename(), com.cliffc.aa.tvar.TV2._unify(), and com.cliffc.aa.tvar.TV2.unify_alias().
get() [2/2]
static TV2 com.cliffc.aa.tvar.TV2.get (TV2[] vs, int i) static
Definition at line 631 of file TV2.java.
{
     TV2 tv = vs[i].find();
     return vs[i]==tv ? tv : (vs[i]=tv); // U-F rollup
   }
References com.cliffc.aa.tvar.TV2.find().
get_unified()
TV2 com.cliffc.aa.tvar.TV2.get_unified ()
Definition at line 85 of file TV2.java.
 { assert is_unified(); return _unified; }
References com.cliffc.aa.tvar.TV2._unified, and com.cliffc.aa.tvar.TV2.is_unified().
Referenced by com.cliffc.aa.tvar.TV2.find(), and com.cliffc.aa.tvar.TV2.find_dups().
is_base()
boolean com.cliffc.aa.tvar.TV2.is_base ()
Definition at line 79 of file TV2.java.
 { return !is_unified() && isa("Base"   ); }
References com.cliffc.aa.tvar.TV2.is_unified(), and com.cliffc.aa.tvar.TV2.isa().
Referenced by com.cliffc.aa.tvar.TV2._cycle_equals(), com.cliffc.aa.tvar.TV2._eq(), com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.tvar.TV2._unify(), com.cliffc.aa.tvar.TV2.make(), com.cliffc.aa.tvar.TV2.make_base(), com.cliffc.aa.tvar.TV2.make_err(), com.cliffc.aa.tvar.TV2.make_leaf_ns(), com.cliffc.aa.tvar.TV2.repl(), com.cliffc.aa.tvar.TV2.str(), and com.cliffc.aa.node.ProjNode.unify().
is_dead()
boolean com.cliffc.aa.tvar.TV2.is_dead ()
Definition at line 81 of file TV2.java.
 { return !is_unified() && isa("Dead"   ); }
References com.cliffc.aa.tvar.TV2.is_unified(), and com.cliffc.aa.tvar.TV2.isa().
Referenced by com.cliffc.aa.tvar.TV2._find_tvar(), com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.tvar.TV2._unify(), com.cliffc.aa.tvar.TV2.find_dups(), com.cliffc.aa.tvar.TV2.repl(), com.cliffc.aa.tvar.TV2.reset_at(), com.cliffc.aa.tvar.TV2.str(), com.cliffc.aa.node.NewStrNode.unify(), com.cliffc.aa.tvar.TV2.unify_alias(), com.cliffc.aa.tvar.TV2.unify_alias_fld(), com.cliffc.aa.tvar.TV2.unify_at(), and com.cliffc.aa.tvar.TV2.union().
is_err()
boolean com.cliffc.aa.tvar.TV2.is_err ()
Definition at line 83 of file TV2.java.
 { return !is_unified() && isa("Err"    ); }
References com.cliffc.aa.tvar.TV2.is_unified(), and com.cliffc.aa.tvar.TV2.isa().
Referenced by com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.tvar.TV2._unify(), com.cliffc.aa.tvar.TV2.make_err(), and com.cliffc.aa.tvar.TV2.str().
is_free()
boolean com.cliffc.aa.tvar.TV2.is_free ()
Definition at line 82 of file TV2.java.
 { return !is_unified() && isa("Free"   ); }
References com.cliffc.aa.tvar.TV2.is_unified(), and com.cliffc.aa.tvar.TV2.isa().
is_leaf()
boolean com.cliffc.aa.tvar.TV2.is_leaf ()
Definition at line 78 of file TV2.java.
 { return !is_unified() && isa("Leaf"   ); }
References com.cliffc.aa.tvar.TV2.is_unified(), and com.cliffc.aa.tvar.TV2.isa().
Referenced by com.cliffc.aa.tvar.TV2._cycle_equals(), com.cliffc.aa.tvar.TV2._eq(), com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.tvar.TV2._occurs_in_type(), com.cliffc.aa.tvar.TV2._unify(), com.cliffc.aa.tvar.TV2.make(), com.cliffc.aa.tvar.TV2.make_base(), com.cliffc.aa.tvar.TV2.make_err(), com.cliffc.aa.tvar.TV2.make_leaf_ns(), and com.cliffc.aa.tvar.TV2.repl().
is_nil()
boolean com.cliffc.aa.tvar.TV2.is_nil ()
Definition at line 80 of file TV2.java.
 { return !is_unified() && isa("Nil"    ); }
References com.cliffc.aa.tvar.TV2.is_unified(), and com.cliffc.aa.tvar.TV2.isa().
Referenced by com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.tvar.TV2._unify(), com.cliffc.aa.tvar.TV2.find_dups(), and com.cliffc.aa.tvar.TV2.str().
is_prim()
boolean com.cliffc.aa.tvar.TV2.is_prim () package
Definition at line 714 of file TV2.java.
                     {
     return isa("Obj") && _args!=null && _args.containsKey("!");
   }
References com.cliffc.aa.tvar.TV2._args, and com.cliffc.aa.tvar.TV2.isa().
Referenced by com.cliffc.aa.tvar.TV2.find_dups(), and com.cliffc.aa.tvar.TV2.str().
is_tvar()
boolean com.cliffc.aa.tvar.TV2.is_tvar ()
Definition at line 84 of file TV2.java.
 { return !is_unified() && _args!=null; } // Excludes unified,base,dead,nil,free
References com.cliffc.aa.tvar.TV2._args, and com.cliffc.aa.tvar.TV2.is_unified().
Referenced by com.cliffc.aa.tvar.TV2.unify_at().
is_unified()
boolean com.cliffc.aa.tvar.TV2.is_unified ()
Definition at line 76 of file TV2.java.
 { return _unified!=null; }
References com.cliffc.aa.tvar.TV2._unified.
Referenced by com.cliffc.aa.tvar.TV2._cycle_equals(), com.cliffc.aa.tvar.TV2._eq(), com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.tvar.TV2._occurs_in_type(), com.cliffc.aa.tvar.TV2._push_update(), com.cliffc.aa.tvar.TV2._unify(), com.cliffc.aa.tvar.TV2._union(), com.cliffc.aa.tvar.TV2.find(), com.cliffc.aa.tvar.TV2.find_dups(), com.cliffc.aa.tvar.TV2.free(), com.cliffc.aa.tvar.TV2.get_unified(), com.cliffc.aa.tvar.TV2.is_base(), com.cliffc.aa.tvar.TV2.is_dead(), com.cliffc.aa.tvar.TV2.is_err(), com.cliffc.aa.tvar.TV2.is_free(), com.cliffc.aa.tvar.TV2.is_leaf(), com.cliffc.aa.tvar.TV2.is_nil(), com.cliffc.aa.tvar.TV2.is_tvar(), com.cliffc.aa.tvar.TV2.isa(), com.cliffc.aa.tvar.TV2.repl(), com.cliffc.aa.tvar.TV2.str(), com.cliffc.aa.tvar.TV2.unify_alias_fld(), com.cliffc.aa.tvar.TV2.unify_at(), and com.cliffc.aa.tvar.TV2.union().
isa()
boolean com.cliffc.aa.tvar.TV2.isa (String s)
Definition at line 77 of file TV2.java.
 { return !is_unified() && Util.eq(_name,s); }
References com.cliffc.aa.tvar.TV2._name, com.cliffc.aa.util.Util.eq(), and com.cliffc.aa.tvar.TV2.is_unified().
Referenced by com.cliffc.aa.tvar.TV2._push_update(), com.cliffc.aa.tvar.TV2.is_base(), com.cliffc.aa.tvar.TV2.is_dead(), com.cliffc.aa.tvar.TV2.is_err(), com.cliffc.aa.tvar.TV2.is_free(), com.cliffc.aa.tvar.TV2.is_leaf(), com.cliffc.aa.tvar.TV2.is_nil(), com.cliffc.aa.tvar.TV2.is_prim(), com.cliffc.aa.tvar.TV2.merge_deps(), com.cliffc.aa.tvar.TV2.merge_ns(), com.cliffc.aa.node.NewStrNode.unify(), com.cliffc.aa.node.MemSplitNode.unify(), com.cliffc.aa.node.StoreNode.unify(), com.cliffc.aa.node.LoadNode.unify(), com.cliffc.aa.tvar.TV2.unify_alias(), and com.cliffc.aa.tvar.TV2.unify_alias_fld().
make() [1/4]
static TV2 com.cliffc.aa.tvar.TV2.make (@NotNull String name, Node n, @NotNull String alloc_site) static
Definition at line 154 of file TV2.java.
 { return make(name,n,alloc_site,new NonBlockingHashMap<>()); }
References com.cliffc.aa.tvar.TV2.make(), and com.cliffc.aa.tvar.TV2.name().
Referenced by com.cliffc.aa.tvar.TV2.make(), com.cliffc.aa.tvar.TV2.make_base(), com.cliffc.aa.tvar.TV2.make_mem(), com.cliffc.aa.node.ProjNode.unify(), com.cliffc.aa.node.MemSplitNode.unify(), com.cliffc.aa.node.LoadNode.unify(), and com.cliffc.aa.tvar.TV2.unify_alias_fld().
make() [2/4]
static TV2 com.cliffc.aa.tvar.TV2.make (@NotNull String name, Node n, @NotNull String alloc_site, Node... ntvs) static
Definition at line 163 of file TV2.java.
{
     assert ntvs!=null;          // Must have some structure
     NonBlockingHashMap<Comparable,TV2> args = new NonBlockingHashMap<>();
     for( int i=0; i<ntvs.length; i++ )
       if( ntvs[i]!=null )
         args.put(i,ntvs[i].tvar());
     return make(name,n,alloc_site,args);
   }
References com.cliffc.aa.tvar.TV2.make(), com.cliffc.aa.tvar.TV2.name(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.put().
make() [3/4]
static TV2 com.cliffc.aa.tvar.TV2.make (@NotNull String name, Node n, @NotNull String alloc_site, NonBlockingHashMap< Comparable, TV2 > args) static
Definition at line 156 of file TV2.java.
{
     assert args!=null;          // Must have some structure
     TV2 tv2 = new TV2(name,args,null,UQNodes.make(n),alloc_site);
     assert !tv2.is_base() && !tv2.is_leaf();
     return tv2;
   }
References com.cliffc.aa.tvar.TV2.is_base(), com.cliffc.aa.tvar.TV2.is_leaf(), com.cliffc.aa.tvar.UQNodes.make(), com.cliffc.aa.tvar.TV2.name(), and com.cliffc.aa.tvar.TV2.TV2().
make() [4/4]
static TV2 com.cliffc.aa.tvar.TV2.make (@NotNull String name, UQNodes ns, @NotNull String alloc_site) static
Definition at line 171 of file TV2.java.
{
     TV2 tv2 = new TV2(name, new NonBlockingHashMap<>(),null,ns,alloc_site);
     assert !tv2.is_base() && !tv2.is_leaf();
     return tv2;
   }
References com.cliffc.aa.tvar.TV2.is_base(), com.cliffc.aa.tvar.TV2.is_leaf(), com.cliffc.aa.tvar.TV2.name(), and com.cliffc.aa.tvar.TV2.TV2().
make_base()
static TV2 com.cliffc.aa.tvar.TV2.make_base (Node n, Type type, @NotNull String alloc_site) static
Definition at line 136 of file TV2.java.
{
     if( type instanceof TypeObj ) { // Constant object?
       return make("Obj",n,alloc_site); // Empty object constant
     }
     UQNodes ns = n==null ? null : UQNodes.make(n);
     type = type.widen();
     TV2 tv2 = new TV2("Base",null,type,ns,alloc_site);
     assert tv2.is_base() && !tv2.is_leaf();
     return tv2;
   }
References com.cliffc.aa.tvar.TV2.is_base(), com.cliffc.aa.tvar.TV2.is_leaf(), com.cliffc.aa.tvar.UQNodes.make(), com.cliffc.aa.tvar.TV2.make(), com.cliffc.aa.tvar.TV2.TV2(), and com.cliffc.aa.type.Type< T extends Type< T >.widen().
Referenced by com.cliffc.aa.tvar.TV2.repl().
make_err()
static TV2 com.cliffc.aa.tvar.TV2.make_err (Node n, String msg, @NotNull String alloc_site) static
Definition at line 147 of file TV2.java.
{
     UQNodes ns = n==null ? null : UQNodes.make(n);
     TV2 tv2 = new TV2("Err",null,TypeStr.con(msg.intern()),ns,alloc_site);
     assert tv2.is_err() && !tv2.is_leaf() && !tv2.is_base();
     return tv2;
   }
References com.cliffc.aa.type.TypeStr.con(), com.cliffc.aa.tvar.TV2.is_base(), com.cliffc.aa.tvar.TV2.is_err(), com.cliffc.aa.tvar.TV2.is_leaf(), com.cliffc.aa.tvar.UQNodes.make(), and com.cliffc.aa.tvar.TV2.TV2().
Referenced by com.cliffc.aa.tvar.TV2.union_err().
make_leaf()
static TV2 com.cliffc.aa.tvar.TV2.make_leaf (Node n, @NotNull String alloc_site) static
Definition at line 126 of file TV2.java.
{
     UQNodes ns = n==null ? null : UQNodes.make(n);
     return make_leaf_ns(ns,alloc_site);
   }
References com.cliffc.aa.tvar.UQNodes.make(), and com.cliffc.aa.tvar.TV2.make_leaf_ns().
Referenced by com.cliffc.aa.node.Node.new_tvar().
make_leaf_ns()
static TV2 com.cliffc.aa.tvar.TV2.make_leaf_ns (UQNodes ns, @NotNull String alloc_site) static
Definition at line 130 of file TV2.java.
{
     TV2 tv2 = new TV2("Leaf",null,null,ns,alloc_site);
     assert tv2.is_leaf() && !tv2.is_base();
     return tv2;
   }
References com.cliffc.aa.tvar.TV2.is_base(), com.cliffc.aa.tvar.TV2.is_leaf(), and com.cliffc.aa.tvar.TV2.TV2().
Referenced by com.cliffc.aa.tvar.TV2.make_leaf(), com.cliffc.aa.tvar.TV2.repl(), and com.cliffc.aa.Parse.stmt().
make_mem()
static TV2 com.cliffc.aa.tvar.TV2.make_mem (Node n, @NotNull String alloc_site) static
Definition at line 178 of file TV2.java.
 { return make("Mem",n,alloc_site,new NonBlockingHashMap<>()); }
References com.cliffc.aa.tvar.TV2.make().
merge_deps()
void com.cliffc.aa.tvar.TV2.merge_deps (TV2 that) private
Definition at line 693 of file TV2.java.
 { if( !that.isa("Dead") ) that._deps = that._deps==null ? _deps : that._deps.addAll(_deps); }
References com.cliffc.aa.tvar.TV2._deps, com.cliffc.aa.tvar.UQNodes.addAll(), and com.cliffc.aa.tvar.TV2.isa().
Referenced by com.cliffc.aa.tvar.TV2._union(), and com.cliffc.aa.tvar.TV2.args_put().
merge_ns()
void com.cliffc.aa.tvar.TV2.merge_ns (TV2 that) private
Definition at line 696 of file TV2.java.
 { if( !that.isa("Dead") ) that._ns   = that._ns  ==null ? _ns   : that._ns  .addAll(_ns  ); }
References com.cliffc.aa.tvar.TV2._ns, com.cliffc.aa.tvar.UQNodes.addAll(), and com.cliffc.aa.tvar.TV2.isa().
Referenced by com.cliffc.aa.tvar.TV2._union().
name()
String com.cliffc.aa.tvar.TV2.name ()
Definition at line 86 of file TV2.java.
 { return _name; }
References com.cliffc.aa.tvar.TV2._name.
Referenced by com.cliffc.aa.tvar.TV2.make(), and com.cliffc.aa.tvar.TV2.TV2().
occurs_in()
boolean com.cliffc.aa.tvar.TV2.occurs_in (TV2[] vs) package
Definition at line 599 of file TV2.java.
{
     if( vs==null ) return false;
     assert ODUPS.isEmpty();
     boolean found = _occurs_in(vs);
     ODUPS.clear();
     return found;
   }
References com.cliffc.aa.tvar.TV2._occurs_in(), and com.cliffc.aa.tvar.TV2.ODUPS.
Referenced by com.cliffc.aa.tvar.TV2._fresh_unify(), and com.cliffc.aa.tvar.TV2.repl().
push_dep()
TV2 com.cliffc.aa.tvar.TV2.push_dep (CallEpiNode dep)
Definition at line 674 of file TV2.java.
{
     assert DEPS_VISIT.isEmpty();
     _push_update(dep);
     DEPS_VISIT.clear();
     return this;
   }
References com.cliffc.aa.tvar.TV2._push_update(), and com.cliffc.aa.tvar.TV2.DEPS_VISIT.
repl()
TV2 com.cliffc.aa.tvar.TV2.repl (TV2[] vs) private
Definition at line 438 of file TV2.java.
{
     assert !is_unified();        // Already chased these down
     if( is_dead() ) return this; // Dead always unifies and wins
     TV2 t = VARS.get(this);      // Prior answer?
     if( t!=null ) return t;      // Been there, done that, return prior answer
     if( is_leaf() ) // If occurs_in lexical scope, keep same variable, else make a new leaf
       return vput( occurs_in(vs) ? this : make_leaf_ns(null,"TV2_repl_leaf") );
     // Must replicate Base's, like a Mem or Obj.
     if( is_base() ) return vput(make_base(null,_type,"TV2_repl_base"));
     // A few no-arg variants (Nil, Fresh)
     if( _args==null ) return vput(new TV2(_name,null,null,null,"TV2_repl_shallow"));
     // Structural recursion replicate
     TV2 rez = new TV2(_name, new NonBlockingHashMap<>(),null,null,"TV2_repl_deep");
     VARS.put(this,rez); // Insert in dups BEFORE structural recursion, to stop cycles
     for( Comparable key : _args.keySet() )
       rez.args_put(key,get(key).repl(vs));
     return rez;
   }
References com.cliffc.aa.tvar.TV2._args, com.cliffc.aa.tvar.TV2._name, com.cliffc.aa.tvar.TV2._type, com.cliffc.aa.tvar.TV2.args_put(), com.cliffc.aa.tvar.TV2.is_base(), com.cliffc.aa.tvar.TV2.is_dead(), com.cliffc.aa.tvar.TV2.is_leaf(), com.cliffc.aa.tvar.TV2.is_unified(), com.cliffc.aa.tvar.TV2.make_base(), com.cliffc.aa.tvar.TV2.make_leaf_ns(), com.cliffc.aa.tvar.TV2.occurs_in(), com.cliffc.aa.tvar.TV2.TV2(), com.cliffc.aa.tvar.TV2.VARS, and com.cliffc.aa.tvar.TV2.vput().
Referenced by com.cliffc.aa.tvar.TV2._fresh_unify(), and com.cliffc.aa.tvar.TV2.repl_rename().
repl_rename()
TV2 com.cliffc.aa.tvar.TV2.repl_rename (TV2[] vs, HashMap< Node, Node > map)
Definition at line 461 of file TV2.java.
{
     assert VARS.isEmpty() && DUPS.isEmpty();
     TV2 tv = repl(vs);
     _rename(tv,map);
     VARS.clear();  DUPS.clear();
     return tv;
   }
References com.cliffc.aa.tvar.TV2._rename(), com.cliffc.aa.tvar.TV2.DUPS, com.cliffc.aa.tvar.TV2.repl(), and com.cliffc.aa.tvar.TV2.VARS.
reset()
void com.cliffc.aa.tvar.TV2.reset (Node n)
Definition at line 187 of file TV2.java.
 { if( _ns!=null ) _ns.remove(n._uid); }
References com.cliffc.aa.tvar.TV2._ns, com.cliffc.aa.node.Node._uid, and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.remove().
reset_at()
void com.cliffc.aa.tvar.TV2.reset_at (Object o)
Definition at line 118 of file TV2.java.
{
     if( !is_dead() )
       _args.remove(o);
   }
References com.cliffc.aa.tvar.TV2._args, and com.cliffc.aa.tvar.TV2.is_dead().
reset_to_init0()
static void com.cliffc.aa.tvar.TV2.reset_to_init0 () static
Definition at line 183 of file TV2.java.
{
     NIL._deps = DEAD._deps = null;
     NIL._ns   = DEAD._ns   = null;
   }
References com.cliffc.aa.tvar.TV2._deps, com.cliffc.aa.tvar.TV2._ns, com.cliffc.aa.tvar.TV2.DEAD, and com.cliffc.aa.tvar.TV2.NIL.
Referenced by com.cliffc.aa.Env.top_reset().
str() [1/2]
final String com.cliffc.aa.tvar.TV2.str (int d)
Definition at line 707 of file TV2.java.
{
     NonBlockingHashMapLong<String> dups = new NonBlockingHashMapLong<>();
     VBitSet bs = new VBitSet();
     find_dups(bs,dups,0);
     return str(new SB(),bs.clr(),dups,true,0,d).toString();
   }
References com.cliffc.aa.util.VBitSet.clr(), and com.cliffc.aa.tvar.TV2.find_dups().
Referenced by com.cliffc.aa.tvar.TV2.str(), com.cliffc.aa.Env.VStack.toString(), and com.cliffc.aa.tvar.TV2.toString().
str() [2/2]
final SB com.cliffc.aa.tvar.TV2.str (SB sb, VBitSet bs, NonBlockingHashMapLong< String > dups, boolean debug, int d, int max)
Definition at line 738 of file TV2.java.
{
     if( is_dead() ) return sb.p("Dead"); // Do not print NS
     if( is_nil()  ) return sb.p("Nil" ); // Do not print NS
     if( is_err()  ) return sb.p(_type.getstr());
     String stv = dups.get(_uid);
     if( stv!=null ) {
       sb.p('$').p(stv);
       if( bs.tset(_uid) ) return sb;
       sb.p(':');
     }
     // Explicit U-F chain
     if( is_unified() ) {
       if( debug ) sb.p("V").p(_uid).p(">>");
       return _unified.str(sb,bs,dups,debug,d,max);
     }
     (is_base() ? sb.p(_type) : sb.p(_name)).p(':');
     // Print all unioned nodes
     if( _ns!=null && _ns.size() != 0 ) { // Have any
       for( Node tn : _ns.values() )      // For all unioned
         if( !tn.is_dead() ) { // Dead lazily cleared out, do not bother to print
           sb.p('N').p(tn._uid).p(':');
           if( !debug ) break; // Debug, see them all; non-debug just the first
         }
     } else                      // No unioned nodes
       sb.p("V").p(_uid);        // So just the _uid
     if( is_prim() ) return sb.p(":PRIMS");
     // Structural contents
     if( _args != null ) {
       final int min = Math.min(d+1,max);
       switch(_name) {
       case "Fun":
         sb.p(":{ ");
         if( d < max ) sb.nl().i(min);
         TV2 args = _args.get("Args");
         if( args==null ) sb.p("Args");
         else args.str(sb,bs,dups,debug,d+1,max);
         if( d < max ) sb.nl().i(min);
         sb.p(" -> ");
         if( d < max ) sb.nl().i(min);
         TV2 ret = _args.get("Ret");
         if( ret ==null ) sb.p("Ret" );
         else ret .str(sb,bs,dups,debug,d+1,max);
         if( d < max ) sb.nl().i(d);
         sb.p(" }");
         break;
       default:
         sb.p(":[ ");
         Ary<Comparable> keys = new Ary<>(_args.keySet().toArray(new Comparable[_args.size()]));
           keys.sort_update((x,y)-> {
             if( x==y ) return 0;
             if( x=="^" ) return -1;
             if( y=="^" ) return -1;
             return x.compareTo(y);
           });
         for( Comparable key : keys ) {
           if( d < max ) sb.nl().i(min);
           sb.p(key.toString()).p(':');
           _args.get(key).str(sb,bs,dups,debug,d+1,max);
           sb.p(' ');
         }
         if( d < max ) sb.nl().i(d);
         sb.p("]");
       }
     }
     return sb;
   }
References com.cliffc.aa.tvar.TV2._args, com.cliffc.aa.tvar.TV2._name, com.cliffc.aa.tvar.TV2._ns, com.cliffc.aa.tvar.TV2._type, com.cliffc.aa.tvar.TV2._uid, com.cliffc.aa.tvar.TV2._unified, com.cliffc.aa.type.Type< T extends Type< T >.getstr(), com.cliffc.aa.tvar.TV2.is_base(), com.cliffc.aa.tvar.TV2.is_dead(), com.cliffc.aa.tvar.TV2.is_err(), com.cliffc.aa.tvar.TV2.is_nil(), com.cliffc.aa.tvar.TV2.is_prim(), com.cliffc.aa.tvar.TV2.is_unified(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.size(), com.cliffc.aa.util.Ary< E >.sort_update(), com.cliffc.aa.tvar.TV2.str(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.values().
toString()
final String com.cliffc.aa.tvar.TV2.toString ()
Definition at line 701 of file TV2.java.
{
     NonBlockingHashMapLong<String> dups = new NonBlockingHashMapLong<>();
     VBitSet bs = new VBitSet();
     find_dups(bs,dups,0);
     return str(new SB(),bs.clr(),dups,true,0,0).toString();
   }
References com.cliffc.aa.util.VBitSet.clr(), com.cliffc.aa.tvar.TV2.find_dups(), and com.cliffc.aa.tvar.TV2.str().
unify()
boolean com.cliffc.aa.tvar.TV2.unify (TV2 that, boolean test)
Definition at line 288 of file TV2.java.
{
     //assert !this.is_unified() && !that.is_unified();
     //if( this==that ) return false;
     //assert DUPS.isEmpty();
     //boolean progress = _unify(that,test);
     //DUPS.clear();
     //return progress;
     throw unimpl();
   }
Referenced by com.cliffc.aa.node.ProjNode.unify(), com.cliffc.aa.node.MemSplitNode.unify(), com.cliffc.aa.node.CastNode.unify(), com.cliffc.aa.node.MemJoinNode.unify(), com.cliffc.aa.node.StoreNode.unify(), com.cliffc.aa.node.LoadNode.unify(), com.cliffc.aa.tvar.TV2.unify_alias_fld(), and com.cliffc.aa.tvar.TV2.unify_at().
unify_alias()
boolean com.cliffc.aa.tvar.TV2.unify_alias (BitsAlias aliases, TV2 mem, boolean test)
Definition at line 515 of file TV2.java.
{
     if( this==mem ) return false; // Already unified, no progress
     assert (isa("Mem") || is_dead()) && mem.isa("Mem");
     boolean progress = false;
     TV2 tobj=null;              // For asserts
     for( int alias : aliases ) {
       TV2 tv = mem.get(alias);  // Get prior mem idea of this alias
       if( tv==null ) continue;  // No idea (yet) from prior mem, nothing to unify
       if( tobj==null ) tobj=tv; // All objects in this set of aliases are already unified
       else assert tobj==tv;
       progress |= unify_at(alias,tv,test); // Overwrite the default for alias
       if( progress && test ) return true;
     }
     return progress;
   }
References com.cliffc.aa.tvar.TV2.get(), com.cliffc.aa.tvar.TV2.is_dead(), com.cliffc.aa.tvar.TV2.isa(), and com.cliffc.aa.tvar.TV2.unify_at().
Referenced by com.cliffc.aa.node.MemJoinNode.unify().
unify_alias_fld()
boolean com.cliffc.aa.tvar.TV2.unify_alias_fld (Node ldst, BitsAlias aliases, String fld, TV2 tv, boolean test, String alloc_site)
Definition at line 488 of file TV2.java.
{
     assert isa("Mem");
     assert !tv.is_unified();
     boolean progress=false;
     for( int alias : aliases ) {
       // TODO: Probably wrong, as no reason to believe that as soon as alias
       // sharpens above AARY that it has hit its best sane value.
       if( alias <= BitsAlias.AARY ) return false; // No unify on parser-specific values
       TV2 tobj = get(alias);
       if( tobj == null ) {      // Missing, act as a fresh TV2 and lazily manifest
         if( test ) return true; // Definitely will be progress
         progress = true;
         TV2 tvo = make("Obj",ldst,alloc_site);
         args_put(alias,tvo);
         tvo.args_put(fld,tv);
       } else if( tobj.isa("Obj") ) {
         progress = tobj.unify_at(fld,tv.find(),test);
       } else if( tobj.is_dead() || tobj.isa("Err") ) {
         tobj.unify(tv.find(),test);
       } else
         throw com.cliffc.aa.AA.unimpl();
       if( progress && test ) return progress; // Shortcut
     }
     return progress;
   }
References com.cliffc.aa.type.BitsAlias.AARY, com.cliffc.aa.tvar.TV2.args_put(), com.cliffc.aa.tvar.TV2.find(), com.cliffc.aa.tvar.TV2.is_dead(), com.cliffc.aa.tvar.TV2.is_unified(), com.cliffc.aa.tvar.TV2.isa(), com.cliffc.aa.tvar.TV2.make(), com.cliffc.aa.tvar.TV2.unify(), com.cliffc.aa.tvar.TV2.unify_at(), and com.cliffc.aa.AA.unimpl().
Referenced by com.cliffc.aa.node.StoreNode.unify(), and com.cliffc.aa.node.LoadNode.unify().
unify_at()
boolean com.cliffc.aa.tvar.TV2.unify_at (Comparable key, TV2 tv2, boolean test)
Definition at line 105 of file TV2.java.
{
     if( is_dead() ) return unify(tv2,test);
     assert is_tvar() && _args!=null && !tv2.is_unified();
     TV2 old = get(key);
     if( old!=null )
       return old.unify(tv2,test);
     if( test ) return true;
     args_put(key,tv2);
     Env.GVN.add_flow(_deps);    // Re-CallEpi
     return true;
   }
References com.cliffc.aa.tvar.TV2._args, com.cliffc.aa.tvar.TV2._deps, com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.tvar.TV2.args_put(), com.cliffc.aa.Env.GVN, com.cliffc.aa.tvar.TV2.is_dead(), com.cliffc.aa.tvar.TV2.is_tvar(), com.cliffc.aa.tvar.TV2.is_unified(), and com.cliffc.aa.tvar.TV2.unify().
Referenced by com.cliffc.aa.node.ProjNode.unify(), com.cliffc.aa.node.LoadNode.unify(), com.cliffc.aa.tvar.TV2.unify_alias(), and com.cliffc.aa.tvar.TV2.unify_alias_fld().
unify_base()
boolean com.cliffc.aa.tvar.TV2.unify_base (TV2 that) private
Definition at line 353 of file TV2.java.
{
     that._type = _type.meet(that._type);
     return union(that);
   }
References com.cliffc.aa.tvar.TV2._type, and com.cliffc.aa.type.Type< T extends Type< T >.meet().
Referenced by com.cliffc.aa.tvar.TV2._unify().
union()
boolean com.cliffc.aa.tvar.TV2.union (TV2 that)
Definition at line 255 of file TV2.java.
{
     if( this==that ) return true;
     assert !is_unified() && !is_dead();
     // Worklist: put updates on the worklist for revisiting
     Env.GVN.add_flow(_deps); // Re-CallEpi
     // TODO: REMOVE THIS BACKDOORS HACK
     if( _ns!=null && that._ns!=null && _ns.size()==1 ) {
       Node val=null; for( Node xval : _ns.values() ) { val=xval; break; }
       if( val instanceof FreshNode && that._ns.containsKey(((FreshNode)val).in(1)._uid) )
         Env.GVN.add_reduce(val);
     }
     _union(that);
     ALLOCS.get(_alloc_site)._free++;
     return true;
   }
References com.cliffc.aa.tvar.TV2._alloc_site, com.cliffc.aa.tvar.TV2._deps, com.cliffc.aa.tvar.TV2._ns, com.cliffc.aa.tvar.TV2._union(), com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.GVNGCM.add_reduce(), com.cliffc.aa.tvar.TV2.ALLOCS, com.cliffc.aa.Env.GVN, com.cliffc.aa.tvar.TV2.is_dead(), com.cliffc.aa.tvar.TV2.is_unified(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.size(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.values().
Referenced by com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.tvar.TV2._unify(), and com.cliffc.aa.tvar.TV2.union_err().
union_err()
boolean com.cliffc.aa.tvar.TV2.union_err (TV2 that, String msg) private
Definition at line 348 of file TV2.java.
{
     union(that);
     return that.union(make_err(null,msg,"TV2.unify_err"));
   }
References com.cliffc.aa.tvar.TV2.make_err(), and com.cliffc.aa.tvar.TV2.union().
Referenced by com.cliffc.aa.tvar.TV2._unify().
vput() [1/2]
TV2 com.cliffc.aa.tvar.TV2.vput (TV2 that) private
Definition at line 435 of file TV2.java.
 { VARS.put(this,that); return that; }
References com.cliffc.aa.tvar.TV2.VARS.
vput() [2/2]
boolean com.cliffc.aa.tvar.TV2.vput (TV2 that, boolean progress) private
Definition at line 434 of file TV2.java.
 { VARS.put(this,that); return progress; }
References com.cliffc.aa.tvar.TV2.VARS.
Referenced by com.cliffc.aa.tvar.TV2._fresh_unify(), and com.cliffc.aa.tvar.TV2.repl().
Member Data Documentation
_alloc_site
String com.cliffc.aa.tvar.TV2._alloc_site
Definition at line 56 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2.free(), com.cliffc.aa.tvar.TV2.TV2(), and com.cliffc.aa.tvar.TV2.union().
_args
NonBlockingHashMap<Comparable,TV2> com.cliffc.aa.tvar.TV2._args
Definition at line 42 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2._cycle_equals(), com.cliffc.aa.tvar.TV2._eq(), com.cliffc.aa.tvar.TV2._find_tvar(), com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.tvar.TV2._occurs_in_type(), com.cliffc.aa.tvar.TV2._push_update(), com.cliffc.aa.tvar.TV2._rename(), com.cliffc.aa.tvar.TV2._unify(), com.cliffc.aa.tvar.TV2.args_put(), com.cliffc.aa.tvar.TV2.find_dups(), com.cliffc.aa.tvar.TV2.free(), com.cliffc.aa.tvar.TV2.get(), com.cliffc.aa.tvar.TV2.is_prim(), com.cliffc.aa.tvar.TV2.is_tvar(), com.cliffc.aa.tvar.TV2.repl(), com.cliffc.aa.tvar.TV2.reset_at(), com.cliffc.aa.tvar.TV2.str(), com.cliffc.aa.tvar.TV2.TV2(), com.cliffc.aa.node.ProjNode.unify(), com.cliffc.aa.node.MemSplitNode.unify(), and com.cliffc.aa.tvar.TV2.unify_at().
_deps
UQNodes com.cliffc.aa.tvar.TV2._deps
Definition at line 52 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.tvar.TV2._push_update(), com.cliffc.aa.tvar.TV2._rename(), com.cliffc.aa.tvar.TV2._union(), com.cliffc.aa.tvar.TV2.free(), com.cliffc.aa.tvar.TV2.merge_deps(), com.cliffc.aa.tvar.TV2.reset_to_init0(), com.cliffc.aa.tvar.TV2.TV2(), com.cliffc.aa.tvar.TV2.unify_at(), and com.cliffc.aa.tvar.TV2.union().
_name
String com.cliffc.aa.tvar.TV2._name private
Definition at line 38 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2._cycle_equals(), com.cliffc.aa.tvar.TV2._eq(), com.cliffc.aa.tvar.TV2._find_tvar(), com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.tvar.TV2._unify(), com.cliffc.aa.tvar.TV2.free(), com.cliffc.aa.tvar.TV2.isa(), com.cliffc.aa.tvar.TV2.name(), com.cliffc.aa.tvar.TV2.repl(), com.cliffc.aa.tvar.TV2.str(), and com.cliffc.aa.tvar.TV2.TV2().
_ns
UQNodes com.cliffc.aa.tvar.TV2._ns
Definition at line 55 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2._rename(), com.cliffc.aa.tvar.TV2._union(), com.cliffc.aa.tvar.TV2.free(), com.cliffc.aa.tvar.TV2.merge_ns(), com.cliffc.aa.tvar.TV2.reset(), com.cliffc.aa.tvar.TV2.reset_to_init0(), com.cliffc.aa.tvar.TV2.str(), com.cliffc.aa.tvar.TV2.TV2(), and com.cliffc.aa.tvar.TV2.union().
_type
Type com.cliffc.aa.tvar.TV2._type
Definition at line 49 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2._cycle_equals(), com.cliffc.aa.tvar.TV2._eq(), com.cliffc.aa.tvar.TV2.free(), com.cliffc.aa.tvar.TV2.fresh_base(), com.cliffc.aa.tvar.TV2.repl(), com.cliffc.aa.tvar.TV2.str(), com.cliffc.aa.tvar.TV2.TV2(), com.cliffc.aa.node.ProjNode.unify(), and com.cliffc.aa.tvar.TV2.unify_base().
_uid
final int com.cliffc.aa.tvar.TV2._uid
Definition at line 26 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2._eq(), com.cliffc.aa.tvar.TV2._occurs_in_type(), com.cliffc.aa.tvar.TV2._push_update(), com.cliffc.aa.tvar.TV2._rename(), com.cliffc.aa.tvar.TV2._unify(), com.cliffc.aa.tvar.TV2.find_dups(), com.cliffc.aa.tvar.TV2.str(), and com.cliffc.aa.tvar.TV2.TV2().
_unified
TV2 com.cliffc.aa.tvar.TV2._unified private
Definition at line 46 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2._union(), com.cliffc.aa.tvar.TV2.get_unified(), com.cliffc.aa.tvar.TV2.is_unified(), and com.cliffc.aa.tvar.TV2.str().
ALLOCS
final HashMap<String,ACnts> com.cliffc.aa.tvar.TV2.ALLOCS = new HashMap<>() static private
Definition at line 60 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2.free(), com.cliffc.aa.tvar.TV2.TV2(), and com.cliffc.aa.tvar.TV2.union().
CDUPS
final HashMap<TV2,TV2> com.cliffc.aa.tvar.TV2.CDUPS = new HashMap<>() static private
Definition at line 639 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2._cycle_equals(), and com.cliffc.aa.tvar.TV2.cycle_equals().
DEAD
TV2 com.cliffc.aa.tvar.TV2.DEAD = new TV2("Dead",null,null,null,"static") static
Definition at line 180 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2.reset_to_init0().
DEPS_VISIT
final VBitSet com.cliffc.aa.tvar.TV2.DEPS_VISIT = new VBitSet() static package
Definition at line 673 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2._push_update(), and com.cliffc.aa.tvar.TV2.push_dep().
DUPS
final NonBlockingHashMapLong<TV2> com.cliffc.aa.tvar.TV2.DUPS = new NonBlockingHashMapLong<>() static private
Definition at line 284 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2._eq(), com.cliffc.aa.tvar.TV2._rename(), com.cliffc.aa.tvar.TV2._unify(), com.cliffc.aa.tvar.TV2.eq(), com.cliffc.aa.tvar.TV2.find_tvar(), and com.cliffc.aa.tvar.TV2.repl_rename().
NIL
TV2 com.cliffc.aa.tvar.TV2.NIL = new TV2("Nil" ,null,null,null,"static") static
Definition at line 181 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2.reset_to_init0().
ODUPS
final VBitSet com.cliffc.aa.tvar.TV2.ODUPS = new VBitSet() static private
Definition at line 598 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2._occurs_in_type(), and com.cliffc.aa.tvar.TV2.occurs_in().
UID
int com.cliffc.aa.tvar.TV2.UID =1 static private
Definition at line 25 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2.TV2().
VARS
final HashMap<TV2,TV2> com.cliffc.aa.tvar.TV2.VARS = new HashMap<>() static private
Definition at line 366 of file TV2.java.
Referenced by com.cliffc.aa.tvar.TV2._eq(), com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.tvar.TV2.eq(), com.cliffc.aa.tvar.TV2.repl(), com.cliffc.aa.tvar.TV2.repl_rename(), and com.cliffc.aa.tvar.TV2.vput().
The documentation for this class was generated from the following file:
TV2.java