aa: com.cliffc.aa.HM.HM.Worklist Class Reference
com.cliffc.aa.HM.HM.Worklist Class Reference
Public Member Functions
void addAll (Ary<? extends Syntax > ss)
void clear ()
boolean has (Syntax s)
int len ()
Syntax pop ()
void push (Syntax s)
String toString ()
Public Attributes
int _cnt
Private Attributes
final Ary< Syntax > _ary = new Ary<>(Syntax.class)
final HashSet< Syntax > _work = new HashSet<>()
Detailed Description
Definition at line 288 of file HM.java.
Member Function Documentation
addAll()
void com.cliffc.aa.HM.HM.Worklist.addAll (Ary<? extends Syntax > ss)
Definition at line 297 of file HM.java.
 { if( ss != null ) for( Syntax s : ss ) push(s); }
References com.cliffc.aa.HM.HM.Worklist.push().
Referenced by com.cliffc.aa.HM.HM.T2._union(), com.cliffc.aa.HM.HM.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM.T2.add_fld(), com.cliffc.aa.HM.HM.Lambda.add_hm_work(), com.cliffc.aa.HM.HM.Let.add_hm_work(), com.cliffc.aa.HM.HM.Lambda.add_val_work(), com.cliffc.aa.HM.HM.Let.add_val_work(), com.cliffc.aa.HM.HM.Apply.add_val_work(), and com.cliffc.aa.HM.HM.Root.val().
clear()
void com.cliffc.aa.HM.HM.Worklist.clear ()
Definition at line 298 of file HM.java.
{
       _cnt=0;
       _ary.clear();
       _work.clear();
     }
References com.cliffc.aa.HM.HM.Worklist._ary, com.cliffc.aa.HM.HM.Worklist._cnt, and com.cliffc.aa.HM.HM.Worklist._work.
has()
boolean com.cliffc.aa.HM.HM.Worklist.has (Syntax s)
Definition at line 296 of file HM.java.
 { return _work.contains(s); }
References com.cliffc.aa.HM.HM.Worklist._work.
Referenced by com.cliffc.aa.HM.HM.Syntax.more_work_impl().
len()
int com.cliffc.aa.HM.HM.Worklist.len ()
Definition at line 292 of file HM.java.
 { return _ary.len(); }
References com.cliffc.aa.HM.HM.Worklist._ary.
Referenced by com.cliffc.aa.HM.HM.hm().
pop()
Syntax com.cliffc.aa.HM.HM.Worklist.pop ()
Definition at line 294 of file HM.java.
 { Syntax s = _ary.pop();_cnt++;            _work.remove(s); return s; }
References com.cliffc.aa.HM.HM.Worklist._ary, com.cliffc.aa.HM.HM.Worklist._cnt, and com.cliffc.aa.HM.HM.Worklist._work.
Referenced by com.cliffc.aa.HM.HM.hm().
push()
void com.cliffc.aa.HM.HM.Worklist.push (Syntax s)
Definition at line 293 of file HM.java.
 { if( s!=null && !_work.contains(s) ) _work.add(_ary.push(s)); }
References com.cliffc.aa.HM.HM.Worklist._ary, and com.cliffc.aa.HM.HM.Worklist._work.
Referenced by com.cliffc.aa.HM.HM.Ident.add_hm_work(), com.cliffc.aa.HM.HM.Lambda.add_hm_work(), com.cliffc.aa.HM.HM.Let.add_hm_work(), com.cliffc.aa.HM.HM.Apply.add_hm_work(), com.cliffc.aa.HM.HM.Struct.add_hm_work(), com.cliffc.aa.HM.HM.Field.add_hm_work(), com.cliffc.aa.HM.HM.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM.Worklist.addAll(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM.Root.val().
toString()
String com.cliffc.aa.HM.HM.Worklist.toString ()
Definition at line 303 of file HM.java.
 { return _ary.toString(); }
References com.cliffc.aa.HM.HM.Worklist._ary.
Member Data Documentation
_ary
final Ary<Syntax> com.cliffc.aa.HM.HM.Worklist._ary = new Ary<>(Syntax.class) private
Definition at line 290 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Worklist.clear(), com.cliffc.aa.HM.HM.Worklist.len(), com.cliffc.aa.HM.HM.Worklist.pop(), com.cliffc.aa.HM.HM.Worklist.push(), and com.cliffc.aa.HM.HM.Worklist.toString().
_cnt
int com.cliffc.aa.HM.HM.Worklist._cnt
Definition at line 289 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Worklist.clear(), com.cliffc.aa.HM.HM.hm(), and com.cliffc.aa.HM.HM.Worklist.pop().
_work
final HashSet<Syntax> com.cliffc.aa.HM.HM.Worklist._work = new HashSet<>() private
Definition at line 291 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Worklist.clear(), com.cliffc.aa.HM.HM.Worklist.has(), com.cliffc.aa.HM.HM.Worklist.pop(), and com.cliffc.aa.HM.HM.Worklist.push().
The documentation for this class was generated from the following file:
HM.java