aa: com.cliffc.aa.HM.HM7.Field Class Reference
com.cliffc.aa.HM.HM7.Field Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Field (String id, Syntax str)
void add_kids (Worklist work)
void add_occurs (Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
T2 lookup (String name)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
Package Attributes
final String _id
VStack _nongen
Syntax _par
final Syntax _str
T2 _t
Detailed Description
Definition at line 585 of file HM7.java.
Constructor & Destructor Documentation
Field()
com.cliffc.aa.HM.HM7.Field.Field (String id, Syntax str) package
Definition at line 588 of file HM7.java.
 { _id=id; _str=str; }
References com.cliffc.aa.HM.HM7.Field._id, com.cliffc.aa.HM.HM7.Field._str, com.cliffc.aa.HM.HM7.id(), and com.cliffc.aa.HM.HM7.Field.str().
Member Function Documentation
add_kids()
void com.cliffc.aa.HM.HM7.Field.add_kids (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 602 of file HM7.java.
 { work.push(_str); }
References com.cliffc.aa.HM.HM7.Field._str, and com.cliffc.aa.HM.HM7.Worklist.push().
add_occurs()
void com.cliffc.aa.HM.HM7.Field.add_occurs (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 603 of file HM7.java.
 { _str.add_occurs(work); }
References com.cliffc.aa.HM.HM7.Field._str, and com.cliffc.aa.HM.HM7.Syntax.add_occurs().
debug_find()
T2 com.cliffc.aa.HM.HM7.Syntax.debug_find () package inherited
Definition at line 250 of file HM7.java.
 { return _t.find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM7.Syntax._t, and com.cliffc.aa.HM.HM7.T2.find().
Referenced by com.cliffc.aa.HM.HM7.hm().
find()
T2 com.cliffc.aa.HM.HM7.Syntax.find () package inherited
Definition at line 246 of file HM7.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM7.Syntax._t, and com.cliffc.aa.HM.HM7.T2.find().
Referenced by com.cliffc.aa.HM.HM7.T2._occurs_in(), com.cliffc.aa.HM.HM7.Lambda.add_occurs(), com.cliffc.aa.HM.HM7.Let.add_occurs(), com.cliffc.aa.HM.HM7.Ident.hm(), com.cliffc.aa.HM.HM7.Lambda.hm(), com.cliffc.aa.HM.HM7.Let.hm(), com.cliffc.aa.HM.HM7.Apply.hm(), com.cliffc.aa.HM.HM7.Struct.hm(), com.cliffc.aa.HM.HM7.Field.hm(), com.cliffc.aa.HM.HM7.Apply.is_if_nil(), and com.cliffc.aa.HM.HM7.Struct.prep_tree().
hm()
boolean com.cliffc.aa.HM.HM7.Field.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 592 of file HM7.java.
{
       T2 str = _str.find();
       int idx = str._ids==null ? -1 : Util.find(str._ids,_id);
       if( idx==-1 )             // Not a struct or no field, force it to be one
         return work==null || T2.make_struct(new String[]{_id}, new T2[]{find().push_update(str._deps)}).unify(str, work);
       // Unify the field
       return str.args(idx).unify(find(),work);
     }
References com.cliffc.aa.HM.HM7.Field._id, com.cliffc.aa.HM.HM7.Field._str, com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM7.Syntax.find(), com.cliffc.aa.HM.HM7.T2.make_struct(), com.cliffc.aa.HM.HM7.T2.push_update(), and com.cliffc.aa.HM.HM7.Field.str().
lookup()
T2 com.cliffc.aa.HM.HM7.Field.lookup (String name) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 601 of file HM7.java.
 { return _par==null ? null : _par.lookup(name); }
References com.cliffc.aa.HM.HM7.Syntax._par, and com.cliffc.aa.HM.HM7.Syntax.lookup().
more_work()
boolean com.cliffc.aa.HM.HM7.Field.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 609 of file HM7.java.
{
       if( !more_work_impl(work) ) return false;
       return _str.more_work(work);
     }
References com.cliffc.aa.HM.HM7.Field._str, com.cliffc.aa.HM.HM7.Syntax.more_work(), and com.cliffc.aa.HM.HM7.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM7.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 270 of file HM7.java.
{
       boolean no_more_work = work.has(this) || !hm(null); // Either on worklist, or no-progress
       return no_more_work;
     }
References com.cliffc.aa.HM.HM7.Worklist.has(), and com.cliffc.aa.HM.HM7.Syntax.hm().
Referenced by com.cliffc.aa.HM.HM7.Con.more_work(), com.cliffc.aa.HM.HM7.Ident.more_work(), com.cliffc.aa.HM.HM7.Lambda.more_work(), com.cliffc.aa.HM.HM7.Let.more_work(), com.cliffc.aa.HM.HM7.Apply.more_work(), com.cliffc.aa.HM.HM7.Struct.more_work(), and com.cliffc.aa.HM.HM7.Field.more_work().
p()
String com.cliffc.aa.HM.HM7.Syntax.p () inherited
Definition at line 278 of file HM7.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM7.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM7.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 279 of file HM7.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM7.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM7.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM7.Syntax.p1(), com.cliffc.aa.HM.HM7.Syntax.p2(), and com.cliffc.aa.HM.HM7.T2.str().
Referenced by com.cliffc.aa.HM.HM7.Syntax.p(), com.cliffc.aa.HM.HM7.Lambda.p2(), com.cliffc.aa.HM.HM7.Let.p2(), com.cliffc.aa.HM.HM7.Apply.p2(), com.cliffc.aa.HM.HM7.Struct.p2(), and com.cliffc.aa.HM.HM7.Field.p2().
p1()
SB com.cliffc.aa.HM.HM7.Field.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 590 of file HM7.java.
 { return sb.p(".").p(_id); }
References com.cliffc.aa.HM.HM7.Field._id, and com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM7.Field.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 591 of file HM7.java.
 { return _str.p0(sb,dups); }
References com.cliffc.aa.HM.HM7.Field._str, and com.cliffc.aa.HM.HM7.Syntax.p0().
prep_lookup_deps()
void com.cliffc.aa.HM.HM7.Field.prep_lookup_deps (Ident id) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 608 of file HM7.java.
 { }
prep_tree()
int com.cliffc.aa.HM.HM7.Field.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 604 of file HM7.java.
{
       prep_tree_impl(par, nongen, work, T2.make_leaf());
       return _str.prep_tree(this,nongen,work)+1;
     }
References com.cliffc.aa.HM.HM7.Field._str, com.cliffc.aa.HM.HM7.T2.make_leaf(), com.cliffc.aa.HM.HM7.Syntax.prep_tree(), and com.cliffc.aa.HM.HM7.Syntax.prep_tree_impl().
prep_tree_impl()
final void com.cliffc.aa.HM.HM7.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 260 of file HM7.java.
 { _par=par; _t=t; _nongen = nongen; work.push(this); }
References com.cliffc.aa.HM.HM7.Syntax._nongen, com.cliffc.aa.HM.HM7.Syntax._par, com.cliffc.aa.HM.HM7.Syntax._t, and com.cliffc.aa.HM.HM7.Worklist.push().
Referenced by com.cliffc.aa.HM.HM7.Con.prep_tree(), com.cliffc.aa.HM.HM7.Ident.prep_tree(), com.cliffc.aa.HM.HM7.Lambda.prep_tree(), com.cliffc.aa.HM.HM7.Let.prep_tree(), com.cliffc.aa.HM.HM7.Apply.prep_tree(), com.cliffc.aa.HM.HM7.Struct.prep_tree(), and com.cliffc.aa.HM.HM7.Field.prep_tree().
str()
SB com.cliffc.aa.HM.HM7.Field.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 589 of file HM7.java.
 { return _str.str(sb.p(".").p(_id).p(' ')); }
References com.cliffc.aa.HM.HM7.Field._id, com.cliffc.aa.HM.HM7.Field._str, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM7.Syntax.str().
Referenced by com.cliffc.aa.HM.HM7.Field.Field(), and com.cliffc.aa.HM.HM7.Field.hm().
toString()
final String com.cliffc.aa.HM.HM7.Syntax.toString () inherited
Definition at line 275 of file HM7.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM7.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_id
final String com.cliffc.aa.HM.HM7.Field._id package
Definition at line 586 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.Field.Field(), com.cliffc.aa.HM.HM7.Field.hm(), com.cliffc.aa.HM.HM7.Field.p1(), and com.cliffc.aa.HM.HM7.Field.str().
_nongen
VStack com.cliffc.aa.HM.HM7.Syntax._nongen package inherited
Definition at line 244 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.Ident.hm(), and com.cliffc.aa.HM.HM7.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM7.Syntax._par package inherited
Definition at line 243 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2._occurs_in(), com.cliffc.aa.HM.HM7.Ident.add_occurs(), com.cliffc.aa.HM.HM7.hm(), com.cliffc.aa.HM.HM7.Ident.hm(), com.cliffc.aa.HM.HM7.Lambda.lookup(), com.cliffc.aa.HM.HM7.Let.lookup(), com.cliffc.aa.HM.HM7.Apply.lookup(), com.cliffc.aa.HM.HM7.Struct.lookup(), com.cliffc.aa.HM.HM7.Field.lookup(), com.cliffc.aa.HM.HM7.Ident.prep_tree(), and com.cliffc.aa.HM.HM7.Syntax.prep_tree_impl().
_str
final Syntax com.cliffc.aa.HM.HM7.Field._str package
Definition at line 587 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.Field.add_kids(), com.cliffc.aa.HM.HM7.Field.add_occurs(), com.cliffc.aa.HM.HM7.Field.Field(), com.cliffc.aa.HM.HM7.Field.hm(), com.cliffc.aa.HM.HM7.Field.more_work(), com.cliffc.aa.HM.HM7.Field.p2(), com.cliffc.aa.HM.HM7.Field.prep_tree(), and com.cliffc.aa.HM.HM7.Field.str().
_t
T2 com.cliffc.aa.HM.HM7.Syntax._t package inherited
Definition at line 245 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.Syntax.debug_find(), com.cliffc.aa.HM.HM7.Syntax.find(), com.cliffc.aa.HM.HM7.hm(), com.cliffc.aa.HM.HM7.Syntax.p0(), com.cliffc.aa.HM.HM7.Let.prep_tree(), and com.cliffc.aa.HM.HM7.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM7.java