aa: com.cliffc.aa.type.TypeLive Class Reference
com.cliffc.aa.type.TypeLive Class Reference
Public Member Functions
boolean above_center ()
TypeObj crush ()
boolean cycle_equals (Type o)
boolean equals (Object o)
boolean is_con ()
boolean is_escape ()
boolean is_ret ()
TypeLive lmeet (TypeLive lv)
boolean may_be_con ()
boolean may_nil ()
Type meet_nil (Type t)
boolean must_nil ()
SB str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
TypeObj update (Access fin, String fld, Type val)
TypeObj update (TypeInt idx, Type val)
void walk (Predicate< Type > p)
TypeObj widen ()
Static Public Attributes
static final TypeLive DEAD = LIVE_BOT.dual()
static final TypeObj ISUSED
static final TypeLive LIVE_BOT =make(false,FLAG_ESCAPE+FLAG_WITH_DISP)
static final TypeObj OBJ
static final TypeObj UNUSED
static final TypeObj XOBJ
Protected Member Functions
O init (byte type, String name, boolean any, boolean use)
TypeLive xdual ()
Type xmeet (Type t)
Package Functions
int compute_hash ()
TypeObj flatten_fields ()
boolean is_display ()
TypeObj remove_other_flds (String fld, Type live)
Static Package Functions
[static initializer]
Package Attributes
boolean _any
int _flags
boolean _use
Static Package Attributes
static final TypeLive ESC_DISP =make(false,FLAG_ESCAPE)
static final TypeLive ESCAPE = make(false,FLAG_ESCAPE+FLAG_WITH_DISP)
static final TypeLive LIVE = make(false,FLAG_WITH_DISP)
static final TypeLive NO_DISP = make(false,0)
static final TypeObj[] TYPES
Private Member Functions
TypeLive init (boolean any, int flags)
Static Private Member Functions
static TypeLive make (boolean any, int flags)
Static Private Attributes
static final int FLAG_ESCAPE =1
static final int FLAG_WITH_DISP =2
static final TypeLive[] LIVES = new TypeLive[]{NO_DISP,ESC_DISP,LIVE,ESCAPE}
static final String[] STRS = new String[]{"!dsp","esc!dsp","live","escp"}
Detailed Description
Definition at line 19 of file TypeLive.java.
Member Function Documentation
[static initializer]()
com.cliffc.aa.type.TypeLive.[static initializer] static package
above_center()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.above_center inherited
Definition at line 77 of file TypeObj.java.
 { return _any; }
compute_hash()
int com.cliffc.aa.type.TypeLive.compute_hash () package
Definition at line 26 of file TypeLive.java.
 { return super.compute_hash() + _flags;  }
References com.cliffc.aa.type.TypeLive._flags.
crush()
TypeObj com.cliffc.aa.type.TypeLive.crush ()
Definition at line 94 of file TypeLive.java.
 { return this; }
cycle_equals()
boolean com.cliffc.aa.type.TypeLive.cycle_equals (Type o)
Definition at line 32 of file TypeLive.java.
 { return equals(o); }
References com.cliffc.aa.type.TypeLive.equals().
equals()
boolean com.cliffc.aa.type.TypeLive.equals (Object o)
Definition at line 27 of file TypeLive.java.
{
     if( this==o ) return true;
     if( !(o instanceof TypeLive) || !super.equals(o) ) return false;
     return _flags==((TypeLive)o)._flags;
   }
References com.cliffc.aa.type.TypeLive._flags.
Referenced by com.cliffc.aa.type.TypeLive.cycle_equals().
flatten_fields()
TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.flatten_fields package inherited
Definition at line 74 of file TypeObj.java.
 { return this; }
init() [1/2]
TypeLive com.cliffc.aa.type.TypeLive.init (boolean any, int flags) private
Definition at line 21 of file TypeLive.java.
{
     super.init(TLIVE,"",any,any);
     _flags = flags;
     return this;
   }
References com.cliffc.aa.type.TypeLive._flags, and com.cliffc.aa.type.TypeLive.init().
Referenced by com.cliffc.aa.type.TypeLive.init(), com.cliffc.aa.type.TypeLive.make(), and com.cliffc.aa.type.TypeLive.xdual().
init() [2/2]
O com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.init (byte type, String name, boolean any, boolean use) protected inherited
Definition at line 19 of file TypeObj.java.
{
     super.init(type,name);
     _any=any;
     _use=use;
     return (O)this;
   }
is_con()
boolean com.cliffc.aa.type.TypeLive.is_con ()
Definition at line 97 of file TypeLive.java.
 { return false; }
is_display()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.is_display package inherited
Definition at line 50 of file TypeObj.java.
 { return false; }
is_escape()
boolean com.cliffc.aa.type.TypeLive.is_escape ()
Definition at line 48 of file TypeLive.java.
 { return (_flags&FLAG_ESCAPE)!=0; }
References com.cliffc.aa.type.TypeLive._flags, and com.cliffc.aa.type.TypeLive.FLAG_ESCAPE.
Referenced by com.cliffc.aa.node.CallNode.ideal_reduce().
is_ret()
boolean com.cliffc.aa.type.TypeLive.is_ret ()
Definition at line 51 of file TypeLive.java.
 { return (_flags&FLAG_WITH_DISP)!=0; }
References com.cliffc.aa.type.TypeLive._flags, and com.cliffc.aa.type.TypeLive.FLAG_WITH_DISP.
lmeet()
TypeLive com.cliffc.aa.type.TypeLive.lmeet (TypeLive lv)
Definition at line 88 of file TypeLive.java.
{
     if( this.above_center() ) return lv.above_center() ? (TypeLive)xmeet(lv) : lv;
     if( lv  .above_center() ) return this;
     return LIVES[_flags|lv._flags];
   }
References com.cliffc.aa.type.TypeLive._flags, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.above_center(), com.cliffc.aa.type.TypeObj< TypeLive >.above_center(), com.cliffc.aa.type.TypeLive.LIVES, and com.cliffc.aa.type.TypeLive.xmeet().
make()
static TypeLive com.cliffc.aa.type.TypeLive.make (boolean any, int flags) static private
Definition at line 40 of file TypeLive.java.
{
     TypeLive t1 = POOLS[TLIVE].malloc();
     return t1.init(any,flags).hashcons_free();
   }
References com.cliffc.aa.type.TypeLive.init().
Referenced by com.cliffc.aa.type.TypeLive.xmeet().
may_be_con()
boolean com.cliffc.aa.type.TypeLive.may_be_con ()
Definition at line 96 of file TypeLive.java.
 { return false; }
may_nil()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.may_nil inherited
Definition at line 81 of file TypeObj.java.
 { return false; }
meet_nil()
Type com.cliffc.aa.type.TypeLive.meet_nil (Type t)
Definition at line 98 of file TypeLive.java.
 { return this; }
must_nil()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.must_nil inherited
Definition at line 80 of file TypeObj.java.
 { return false; }
remove_other_flds()
TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.remove_other_flds (String fld, Type live) package inherited
Definition at line 75 of file TypeObj.java.
 { return UNUSED; }
str()
SB com.cliffc.aa.type.TypeLive.str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
Definition at line 33 of file TypeLive.java.
{
     if( this==DEAD ) return sb.p("DEAD");
     if( _any ) sb.p('~');
     return sb.p(STRS[_flags]);
   }
References com.cliffc.aa.type.TypeObj< TypeLive >._any, com.cliffc.aa.type.TypeLive._flags, com.cliffc.aa.type.TypeLive.DEAD, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.type.TypeLive.STRS.
update() [1/2]
TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.update (Access fin, String fld, Type val) inherited
Definition at line 67 of file TypeObj.java.
 { return this; }
update() [2/2]
TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.update (TypeInt idx, Type val) inherited
Definition at line 69 of file TypeObj.java.
{
     if( this==ISUSED || this==OBJ ) return this;
     return TypeAry.ARY.dual().update(idx,val);
   }
walk()
void com.cliffc.aa.type.TypeLive.walk (Predicate< Type > p)
Definition at line 99 of file TypeLive.java.
 { p.test(this); }
widen()
TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.widen inherited
Definition at line 76 of file TypeObj.java.
 { return ISUSED; }
xdual()
TypeLive com.cliffc.aa.type.TypeLive.xdual () protected
Definition at line 61 of file TypeLive.java.
 { return new TypeLive().init(!_any,_flags); }
References com.cliffc.aa.type.TypeObj< TypeLive >._any, com.cliffc.aa.type.TypeLive._flags, and com.cliffc.aa.type.TypeLive.init().
xmeet()
Type com.cliffc.aa.type.TypeLive.xmeet (Type t) protected
Definition at line 62 of file TypeLive.java.
{
     switch( t._type ) {
     case TLIVE:   break;
     case TARY:
     case TSTR:
     case TSTRUCT:return OBJ;
     case TOBJ:   return t.xmeet(this);
     case TFUNSIG:
     case TTUPLE:
     case TFUNPTR:
     case TMEMPTR:
     case TFLT:
     case TINT:
     case TRPC:
     case TMEM:   return ALL;
     default: throw typerr(t);
     }
     TypeLive ts = (TypeLive)t;
     boolean any = _any&ts._any;
     int f0 =    _any ? 0 :    _flags;
     int f1 = ts._any ? 0 : ts._flags;
     int flags = any ? (_flags&ts._flags) : (f0|f1);
     return make(any,flags);
   }
References com.cliffc.aa.type.TypeObj< TypeLive >._any, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >._any, com.cliffc.aa.type.TypeLive._flags, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.type.TypeLive.make(), com.cliffc.aa.type.TypeObj< TypeLive >.OBJ, and com.cliffc.aa.type.Type< T extends Type< T >.xmeet().
Referenced by com.cliffc.aa.type.TypeLive.lmeet().
Member Data Documentation
_any
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >._any package inherited
Definition at line 16 of file TypeObj.java.
_flags
int com.cliffc.aa.type.TypeLive._flags package
Definition at line 20 of file TypeLive.java.
Referenced by com.cliffc.aa.type.TypeLive.compute_hash(), com.cliffc.aa.type.TypeLive.equals(), com.cliffc.aa.type.TypeLive.init(), com.cliffc.aa.type.TypeLive.is_escape(), com.cliffc.aa.type.TypeLive.is_ret(), com.cliffc.aa.type.TypeLive.lmeet(), com.cliffc.aa.type.TypeLive.str(), com.cliffc.aa.type.TypeLive.xdual(), and com.cliffc.aa.type.TypeLive.xmeet().
_use
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >._use package inherited
Definition at line 17 of file TypeObj.java.
DEAD
final TypeLive com.cliffc.aa.type.TypeLive.DEAD = LIVE_BOT.dual() static
Definition at line 59 of file TypeLive.java.
Referenced by com.cliffc.aa.type.TypeMem.is_live(), com.cliffc.aa.node.ConNode< T extends Type >.live(), com.cliffc.aa.type.TypeLive.str(), and com.cliffc.aa.type.TypeMem.str().
ESC_DISP
final TypeLive com.cliffc.aa.type.TypeLive.ESC_DISP =make(false,FLAG_ESCAPE) static package
Definition at line 54 of file TypeLive.java.
ESCAPE
final TypeLive com.cliffc.aa.type.TypeLive.ESCAPE = make(false,FLAG_ESCAPE+FLAG_WITH_DISP) static package
Definition at line 56 of file TypeLive.java.
FLAG_ESCAPE
final int com.cliffc.aa.type.TypeLive.FLAG_ESCAPE =1 static private
Definition at line 47 of file TypeLive.java.
Referenced by com.cliffc.aa.type.TypeLive.is_escape().
FLAG_WITH_DISP
final int com.cliffc.aa.type.TypeLive.FLAG_WITH_DISP =2 static private
Definition at line 50 of file TypeLive.java.
Referenced by com.cliffc.aa.type.TypeLive.is_ret().
ISUSED
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.ISUSED static inherited
Definition at line 45 of file TypeObj.java.
LIVE
final TypeLive com.cliffc.aa.type.TypeLive.LIVE = make(false,FLAG_WITH_DISP) static package
Definition at line 55 of file TypeLive.java.
Referenced by com.cliffc.aa.type.TypeMem.is_live(), and com.cliffc.aa.type.TypeMem.make0().
LIVE_BOT
final TypeLive com.cliffc.aa.type.TypeLive.LIVE_BOT =make(false,FLAG_ESCAPE+FLAG_WITH_DISP) static
Definition at line 58 of file TypeLive.java.
LIVES
final TypeLive [] com.cliffc.aa.type.TypeLive.LIVES = new TypeLive[]{NO_DISP,ESC_DISP,LIVE,ESCAPE} static private
Definition at line 86 of file TypeLive.java.
Referenced by com.cliffc.aa.type.TypeLive.lmeet().
NO_DISP
final TypeLive com.cliffc.aa.type.TypeLive.NO_DISP = make(false,0) static package
Definition at line 53 of file TypeLive.java.
OBJ
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.OBJ static inherited
Definition at line 44 of file TypeObj.java.
STRS
final String [] com.cliffc.aa.type.TypeLive.STRS = new String[]{"!dsp","esc!dsp","live","escp"} static private
Definition at line 87 of file TypeLive.java.
Referenced by com.cliffc.aa.type.TypeLive.str().
TYPES
final TypeObj [] com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.TYPES static package inherited
Definition at line 48 of file TypeObj.java.
UNUSED
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED static inherited
Definition at line 46 of file TypeObj.java.
XOBJ
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.XOBJ static inherited
Definition at line 47 of file TypeObj.java.
The documentation for this class was generated from the following file:
TypeLive.java