aa: com.cliffc.aa.HM.HM3.Apply Class Reference
com.cliffc.aa.HM.HM3.Apply Class Reference
Public Member Functions
String toString ()
Protected Member Functions
final void add_work (Worklist work)
Package Functions
Apply (Syntax fun, Syntax arg)
final void add_neighbors (Worklist work)
final boolean all_kids_ready ()
boolean check_progress (Worklist work)
void get_ids (VStack vstk, Worklist work)
HMType hm (Worklist work)
boolean progress ()
Package Attributes
HMType _hm
Syntax[] _kids
Syntax _par
Private Member Functions
Syntax arg ()
Syntax fun ()
Detailed Description
Definition at line 247 of file HM3.java.
Constructor & Destructor Documentation
Apply()
com.cliffc.aa.HM.HM3.Apply.Apply (Syntax fun, Syntax arg) package
Definition at line 248 of file HM3.java.
 { _kids=new Syntax[]{fun,arg}; fun._par=arg._par=this; }
References com.cliffc.aa.HM.HM3.Syntax._kids, com.cliffc.aa.HM.HM3.Syntax._par, com.cliffc.aa.HM.HM3.Apply.arg(), and com.cliffc.aa.HM.HM3.Apply.fun().
Member Function Documentation
add_neighbors()
final void com.cliffc.aa.HM.HM3.Syntax.add_neighbors (Worklist work) package inherited
Definition at line 128 of file HM3.java.
{
       if( _par!=null ) _par.add_work(work);
       if( _kids!=null )
         for( Syntax kid : _kids )
           kid.add_work(work);
     }
References com.cliffc.aa.HM.HM3.Syntax._kids, com.cliffc.aa.HM.HM3.Syntax._par, and com.cliffc.aa.HM.HM3.Syntax.add_work().
Referenced by com.cliffc.aa.HM.HM3.hm().
add_work()
final void com.cliffc.aa.HM.HM3.Syntax.add_work (Worklist work) protected inherited
Definition at line 126 of file HM3.java.
 {  if( all_kids_ready() ) work.push(this);  }
References com.cliffc.aa.HM.HM3.Syntax.all_kids_ready(), and com.cliffc.aa.HM.HM3.Worklist.push().
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.HM.HM3.Con.get_ids(), and com.cliffc.aa.HM.HM3.Ident.get_ids().
all_kids_ready()
final boolean com.cliffc.aa.HM.HM3.Syntax.all_kids_ready () package inherited
Definition at line 135 of file HM3.java.
{
       if( _kids==null ) return true;
       for( Syntax kid : _kids ) if( kid._hm==null ) return false;
       return true;
     }
References com.cliffc.aa.HM.HM3.Syntax._kids.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_work(), and com.cliffc.aa.HM.HM3.Syntax.check_progress().
arg()
Syntax com.cliffc.aa.HM.HM3.Apply.arg () private
Definition at line 250 of file HM3.java.
 { return _kids[1]; }
References com.cliffc.aa.HM.HM3.Syntax._kids.
Referenced by com.cliffc.aa.HM.HM3.Apply.Apply(), com.cliffc.aa.HM.HM3.Apply.get_ids(), com.cliffc.aa.HM.HM3.Apply.hm(), com.cliffc.aa.HM.HM3.Apply.progress(), and com.cliffc.aa.HM.HM3.Apply.toString().
check_progress()
boolean com.cliffc.aa.HM.HM3.Syntax.check_progress (Worklist work) package inherited
Definition at line 144 of file HM3.java.
{
       if( all_kids_ready() ) // If kids are not ready, then cannot compute hm() so not on worklist
         if( _hm==null || progress() ) // Progress is possible
           if( !work.has(this) )       // Not on worklist?
             return false;             // Fails check
       if( _kids!=null )               // For all kids
         for( Syntax kid : _kids )
           if( !kid.check_progress(work) ) // Recursively check nodes that can make progress on worklist
             return false;
       return true;
     }
References com.cliffc.aa.HM.HM3.Syntax._hm, com.cliffc.aa.HM.HM3.Syntax._kids, com.cliffc.aa.HM.HM3.Syntax.all_kids_ready(), com.cliffc.aa.HM.HM3.Worklist.has(), and com.cliffc.aa.HM.HM3.Syntax.progress().
Referenced by com.cliffc.aa.HM.HM3.hm().
fun()
Syntax com.cliffc.aa.HM.HM3.Apply.fun () private
Definition at line 249 of file HM3.java.
 { return _kids[0]; }
References com.cliffc.aa.HM.HM3.Syntax._kids.
Referenced by com.cliffc.aa.HM.HM3.Apply.Apply(), com.cliffc.aa.HM.HM3.Apply.get_ids(), com.cliffc.aa.HM.HM3.Apply.hm(), com.cliffc.aa.HM.HM3.Apply.progress(), and com.cliffc.aa.HM.HM3.Apply.toString().
get_ids()
void com.cliffc.aa.HM.HM3.Apply.get_ids (VStack vstk, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM3.Syntax.
Definition at line 272 of file HM3.java.
 { fun().get_ids(vstk,work); arg().get_ids(vstk,work); }
References com.cliffc.aa.HM.HM3.Apply.arg(), com.cliffc.aa.HM.HM3.Apply.fun(), and com.cliffc.aa.HM.HM3.Syntax.get_ids().
hm()
HMType com.cliffc.aa.HM.HM3.Apply.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM3.Syntax.
Definition at line 252 of file HM3.java.
{
       if( _hm!=null && !progress() ) return null;
       HMType tfun = fun()._hm.find();
       HMType targ = arg()._hm.find();
       HMType trez = new HMVar();
       HMType nfun = Oper.fun(targ,trez);
       nfun.union(tfun,work);
       if( _hm!=null ) _hm.union(trez.find(),work);
       return trez.find();
     }
References com.cliffc.aa.HM.HM3.Syntax._hm, com.cliffc.aa.HM.HM3.Apply.arg(), com.cliffc.aa.HM.HM3.HMType.find(), com.cliffc.aa.HM.HM3.Apply.fun(), com.cliffc.aa.HM.HM3.Oper.fun(), com.cliffc.aa.HM.HM3.Apply.progress(), and com.cliffc.aa.HM.HM3.HMType.union().
progress()
boolean com.cliffc.aa.HM.HM3.Apply.progress () package
Reimplemented from com.cliffc.aa.HM.HM3.Syntax.
Definition at line 262 of file HM3.java.
{
       // Progress if tfun is not a Oper.fun, OR
       // tfun[0] != targ (they get unioned)
       HMType tfun = fun()._hm.find();
       HMType targ = arg()._hm.find();
       if( !(tfun instanceof Oper) ) return true;
       if( !((Oper)tfun)._name.equals("->") ) return true;
       HMType arg0 = ((Oper)tfun)._args[0].find();
       return !arg0.eq(targ);
     }
References com.cliffc.aa.HM.HM3.Syntax._hm, com.cliffc.aa.HM.HM3.Apply.arg(), com.cliffc.aa.HM.HM3.HMType.eq(), com.cliffc.aa.HM.HM3.HMType.find(), and com.cliffc.aa.HM.HM3.Apply.fun().
Referenced by com.cliffc.aa.HM.HM3.Apply.hm().
toString()
String com.cliffc.aa.HM.HM3.Apply.toString ()
Definition at line 251 of file HM3.java.
 { return "("+fun()+" "+arg()+")"; }
References com.cliffc.aa.HM.HM3.Apply.arg(), and com.cliffc.aa.HM.HM3.Apply.fun().
Member Data Documentation
_hm
HMType com.cliffc.aa.HM.HM3.Syntax._hm package inherited
Definition at line 118 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Syntax.check_progress(), com.cliffc.aa.HM.HM3.hm(), com.cliffc.aa.HM.HM3.Con.hm(), com.cliffc.aa.HM.HM3.Ident.hm(), com.cliffc.aa.HM.HM3.Lambda.hm(), com.cliffc.aa.HM.HM3.Let.hm(), com.cliffc.aa.HM.HM3.Apply.hm(), com.cliffc.aa.HM.HM3.Lambda.progress(), com.cliffc.aa.HM.HM3.Let.progress(), and com.cliffc.aa.HM.HM3.Apply.progress().
_kids
Syntax [] com.cliffc.aa.HM.HM3.Syntax._kids package inherited
Definition at line 117 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.HM.HM3.Syntax.all_kids_ready(), com.cliffc.aa.HM.HM3.Apply.Apply(), com.cliffc.aa.HM.HM3.Apply.arg(), com.cliffc.aa.HM.HM3.Lambda.body(), com.cliffc.aa.HM.HM3.Let.body(), com.cliffc.aa.HM.HM3.Syntax.check_progress(), com.cliffc.aa.HM.HM3.Apply.fun(), com.cliffc.aa.HM.HM3.Lambda.Lambda(), com.cliffc.aa.HM.HM3.Let.Let(), and com.cliffc.aa.HM.HM3.Let.use().
_par
Syntax com.cliffc.aa.HM.HM3.Syntax._par package inherited
Definition at line 116 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.HM.HM3.Apply.Apply(), com.cliffc.aa.HM.HM3.Lambda.Lambda(), and com.cliffc.aa.HM.HM3.Let.Let().
The documentation for this class was generated from the following file:
HM3.java