aa: com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV > Class Template Reference
com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV > Class Template Reference
A lock-free alternate implementation of java.util.concurrent.ConcurrentHashMap with better scaling properties and generally lower costs to mutate the Map.
Classes
class CHM
class NBHMEntry
class Prime
class SnapshotE
class SnapshotK
class SnapshotV
Public Member Functions
NonBlockingHashMap ()
Create a new NonBlockingHashMap with default minimum size (currently set to 8 K/V pairs or roughly 84 bytes on a standard 32-bit JVM).
NonBlockingHashMap (final int initial_sz)
Create a new NonBlockingHashMap with initial room for the given number of elements, thus avoiding internal resizing operations to reach an appropriate size.
void clear ()
Removes all of the mappings from this map.
Object clone ()
Creates a shallow copy of this hashtable.
boolean contains (Object val)
Legacy method testing if some key maps into the specified value in this table.
boolean containsKey (Object key)
Tests if the key in the table using the equals method.
boolean containsValue (final Object val)
Returns true if this Map maps one or more keys to the specified value.
Enumeration< TypeV > elements ()
Returns an enumeration of the values in this table.
Set< Map.Entry< TypeK, TypeV > > entrySet ()
Returns a Set view of the mappings contained in this map.
TypeV get (Object key)
Returns the value to which the specified key is mapped, or.
TypeK getk (TypeK key)
Returns the Key to which the specified key is mapped, or.
TypeK getKey ()
boolean isEmpty ()
Returns size() == 0.
Enumeration< TypeK > keys ()
Returns an enumeration of the keys in this table.
Set< TypeK > keySet ()
Returns a Set view of the keys contained in this map.
final void print ()
Verbose printout of table internals, useful for debugging.
TypeV put (TypeK key, TypeV val)
Maps the specified key to the specified value in the table.
void putAll (Map<? extends TypeK, ? extends TypeV > m)
Copies all of the mappings from the specified map to this one, replacing any existing mappings.
TypeV putIfAbsent (TypeK key, TypeV val)
Atomically, do a put if-and-only-if the key is not mapped.
final TypeV putIfMatchAllowNull (Object key, Object newVal, Object oldVal)
Object[] raw_array ()
TypeV remove (Object key)
Removes the key (and its corresponding value) from this map.
boolean remove (Object key, Object val)
Atomically do a remove(Object) if-and-only-if the key is mapped to a value which is equals to the given value.
boolean replace (TypeK key, TypeV oldValue, TypeV newValue)
Atomically do a put(key,newValue) if-and-only-if the key is mapped a value which is equals to oldValue.
TypeV replace (TypeK key, TypeV val)
Atomically do a put(key,val) if-and-only-if the key is mapped to some value already.
long reprobes ()
Get and clear the current count of reprobes.
int size ()
Returns the number of key-value mappings in this map.
String toString ()
Returns a string representation of this map.
Collection< TypeV > values ()
Returns a Collection view of the values contained in this map.
Static Public Attributes
static final Object TOMBSTONE = new Object()
Protected Member Functions
final void initialize ()
void rehash ()
Static Package Functions
[static initializer]
Static Package Attributes
static volatile int DUMMY_VOLATILE
Private Member Functions
boolean CAS_kvs (final Object[] oldkvs, final Object[] newkvs)
final Object[] help_copy (Object[] helper)
final void initialize (int initial_sz)
final void print (Object[] kvs)
final void print2 (Object[] kvs)
final TypeV putIfMatch (Object key, Object newVal, Object oldVal)
void readObject (java.io.ObjectInputStream s) throws IOException, ClassNotFoundException
void writeObject (java.io.ObjectOutputStream s) throws IOException
Static Private Member Functions
static Object _getKey (Object[] kvs)
static final boolean CAS_key (Object[] kvs, int idx, Object old, Object key)
static final boolean CAS_val (Object[] kvs, int idx, Object old, Object val)
static final CHM chm (Object[] kvs)
static Object get_impl (final NonBlockingHashMap topmap, final Object[] kvs, final Object key)
static final Object getk_impl (final NonBlockingHashMap topmap, final Object[] kvs, final Object key)
static int hash (final Object key)
static final int[] hashes (Object[] kvs)
static final Object key (Object[] kvs, int idx)
static boolean keyeq (Object K, Object key, int[] hashes, int hash, int fullhash)
static final int len (Object[] kvs)
static final Object putIfMatch (final NonBlockingHashMap topmap, final Object[] kvs, final Object key, final Object putval, final Object expVal)
static long rawIndex (final Object[] ary, final int idx)
static final int reprobe_limit (int len)
static final Object val (Object[] kvs, int idx)
Private Attributes
transient Object[] _kvs
transient long _last_resize_milli
transient ConcurrentAutoTable _reprobes = new ConcurrentAutoTable()
Static Private Attributes
static final long _kvs_offset
static final int _Obase = _unsafe.arrayBaseOffset(Object[].class)
static final int _Olog = _Oscale==4?2:(_Oscale==8?3:9999)
static final int _Oscale = _unsafe.arrayIndexScale(Object[].class)
static final Unsafe _unsafe = UtilUnsafe.getUnsafe()
static final Object MATCH_ANY = new Object()
static final int MIN_SIZE =(1<<MIN_SIZE_LOG)
static final int MIN_SIZE_LOG =3
static final Object NO_MATCH_OLD = new Object()
static final int REPROBE_LIMIT =10
static final long serialVersionUID = 1234123412341234123L
static final Prime TOMBPRIME = new Prime(TOMBSTONE)
Detailed Description
A lock-free alternate implementation of java.util.concurrent.ConcurrentHashMap with better scaling properties and generally lower costs to mutate the Map.
It provides identical correctness properties as ConcurrentHashMap. All operations are non-blocking and multi-thread safe, including all update operations. NonBlockingHashMap scales substantially better than java.util.concurrent.ConcurrentHashMap for high update rates, even with a large concurrency factor. Scaling is linear up to 768 CPUs on a 768-CPU Azul box, even with 100% updates or 100% reads or any fraction in-between. Linear scaling up to all cpus has been observed on a 32-way Sun US2 box, 32-way Sun Niagara box, 8-way Intel box and a 4-way Power box.
This class obeys the same functional specification as {}, and includes versions of methods corresponding to each method of Hashtable. However, even though all operations are thread-safe, operations do not entail locking and there is not any support for locking the entire table in a way that prevents all access. This class is fully interoperable with Hashtable in programs that rely on its thread safety but not on its synchronization details. Operations (including put) generally do not block, so may overlap with other update operations (including other puts and removes). Retrievals reflect the results of the most recently completed update operations holding upon their onset. For aggregate operations such as putAll, concurrent retrievals may reflect insertion or removal of only some entries. Similarly, Iterators and Enumerations return elements reflecting the state of the hash table at some point at or since the creation of the iterator/enumeration. They do not throw ConcurrentModificationException. However, iterators are designed to be used by only one thread at a time.
Very full tables, or tables with high reprobe rates may trigger an internal resize operation to move into a larger table. Resizing is not terribly expensive, but it is not free either; during resize operations table throughput may drop somewhat. All threads that visit the table during a resize will 'help' the resizing but will still be allowed to complete their operation before the resize is finished (i.e., a simple 'get' operation on a million-entry table undergoing resizing will not need to block until the entire million entries are copied).
This class and its views and iterators implement all of the optional methods of the Map and Iterator interfaces.
Like Hashtable but unlike HashMap, this class does not allow null to be used as a key or value.
Since
1.5
Author
Cliff Click
Parameters
<TypeK> the type of keys maintained by this map
<TypeV> the type of mapped values
Definition at line 73 of file NonBlockingHashMap.java.
Constructor & Destructor Documentation
NonBlockingHashMap() [1/2]
com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.NonBlockingHashMap ()
Create a new NonBlockingHashMap with default minimum size (currently set to 8 K/V pairs or roughly 84 bytes on a standard 32-bit JVM).
Definition at line 251 of file NonBlockingHashMap.java.
 { this(MIN_SIZE); }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.clear().
NonBlockingHashMap() [2/2]
com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.NonBlockingHashMap (final int initial_sz)
Create a new NonBlockingHashMap with initial room for the given number of elements, thus avoiding internal resizing operations to reach an appropriate size.
Large numbers here when used with a small count of elements will sacrifice space for a small amount of time gained. The initial size will be rounded up internally to the next larger power of 2.
Definition at line 258 of file NonBlockingHashMap.java.
 { initialize(initial_sz); }
Member Function Documentation
[static initializer]()
com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.[static initializer] static package
_getKey()
static Object com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >._getKey (Object[] kvs) static private
Definition at line 478 of file NonBlockingHashMap.java.
{
     for( int i=0; i<len(kvs); i++ ) {
       Object key = key(kvs,i);
       Object val = val(kvs,i);
       Object U = Prime.unbox(val);
       if( key != null && key != TOMBSTONE &&  // key is sane
           val != null && U   != TOMBSTONE )   // val is sane
         return key;
     }
     Object[] newkvs = chm(kvs)._newkvs; // New table, if any
     return newkvs == null ? null : _getKey(newkvs);
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >._getKey(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.getKey().
CAS_key()
static final boolean com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CAS_key (Object[] kvs, int idx, Object old, Object key) static private
Definition at line 174 of file NonBlockingHashMap.java.
{
     return _unsafe.compareAndSwapObject( kvs, rawIndex(kvs,(idx<<1)+2), old, key );
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.copy_slot(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch().
CAS_kvs()
boolean com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CAS_kvs (final Object[] oldkvs, final Object[] newkvs) private
Definition at line 101 of file NonBlockingHashMap.java.
{
     return _unsafe.compareAndSwapObject(this, _kvs_offset, oldkvs, newkvs );
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.clear(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.copy_check_and_promote().
CAS_val()
static final boolean com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CAS_val (Object[] kvs, int idx, Object old, Object val) static private
Definition at line 177 of file NonBlockingHashMap.java.
{
     return _unsafe.compareAndSwapObject( kvs, rawIndex(kvs,(idx<<1)+3), old, val );
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.copy_slot(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch().
chm()
static final CHM com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.chm (Object[] kvs) static private
Definition at line 135 of file NonBlockingHashMap.java.
 { return (CHM  )kvs[0]; }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >._getKey(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.copy_check_and_promote(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.copy_slot_and_check(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.get_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.getk_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.help_copy(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.help_copy_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.print(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.print2(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.resize(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.size(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.SnapshotV().
clear()
void com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.clear ()
Removes all of the mappings from this map.
Definition at line 381 of file NonBlockingHashMap.java.
                       {         // Smack a new empty table down
     Object[] newkvs = new NonBlockingHashMap(MIN_SIZE)._kvs;
     while( !CAS_kvs(_kvs,newkvs) ) // Spin until the clear works
       ;
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.clone(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.entrySet(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.keySet(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.values().
clone()
Object com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.clone ()
Creates a shallow copy of this hashtable.
All the structure of the hashtable itself is copied, but the keys and values are not cloned. This is a relatively expensive operation.
Returns
a clone of the hashtable.
Definition at line 417 of file NonBlockingHashMap.java.
{
     try {
       // Must clone, to get the class right; NBHM might have been
       // extended so it would be wrong to just make a new NBHM.
       NonBlockingHashMap<TypeK,TypeV> t = (NonBlockingHashMap<TypeK,TypeV>) super.clone();
       // But I don't have an atomic clone operation - the underlying _kvs
       // structure is undergoing rapid change.  If I just clone the _kvs
       // field, the CHM in _kvs[0] won't be in sync.
       //
       // Wipe out the cloned array (it was shallow anyways).
       t.clear();
       // Now copy sanely
       for( TypeK K : keySet() ) {
         final TypeV V = get(K);  // Do an official 'get'
         t.put(K,V);
       }
       return t;
     } catch (CloneNotSupportedException e) {
       // this shouldn't happen, since we are Cloneable
       throw new InternalError();
     }
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.clone().
contains()
boolean com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.contains (Object val)
Legacy method testing if some key maps into the specified value in this table.
This method is identical in functionality to {}, and exists solely to ensure full compatibility with class java.util.Hashtable}, which supported this method prior to introduction of the Java Collections framework. val a value to search for true if this map maps one or more keys to the specified value NullPointerException if the specified value is null
Definition at line 298 of file NonBlockingHashMap.java.
 { return containsValue(val); }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.entrySet(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.keySet(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.values().
containsKey()
boolean com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.containsKey (Object key)
Tests if the key in the table using the equals method.
Returns
true if the key is in the table using the equals method
Exceptions
NullPointerException if the specified key is null
Definition at line 288 of file NonBlockingHashMap.java.
 { return get(key) != null; }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.keySet().
containsValue()
boolean com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.containsValue (final Object val)
Returns true if this Map maps one or more keys to the specified value.
Note: This method requires a full internal traversal of the hash table and is much slower than containsKey.
Parameters
val value whose presence in this map is to be tested
Returns
true if this map maps one or more keys to the specified value
Exceptions
NullPointerException if the specified value is null
Definition at line 394 of file NonBlockingHashMap.java.
{
     if( val == null ) throw new NullPointerException();
     for( TypeV V : values() )
       if( V == val || V.equals(val) )
         return true;
     return false;
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.contains(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.values().
elements()
Enumeration<TypeV> com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.elements ()
Returns an enumeration of the values in this table.
Returns
an enumeration of the values in this table
See also
values()
Definition at line 1248 of file NonBlockingHashMap.java.
 { return new SnapshotV(); }
entrySet()
Set<Map.Entry<TypeK,TypeV> > com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.entrySet ()
Returns a Set view of the mappings contained in this map.
The set is backed by the map, so changes to the map are reflected in the set, and vice-versa. The set supports element removal, which removes the corresponding mapping from the map, via the Iterator.remove, Set.remove, removeAll, retainAll, and clear operations. It does not support the add or addAll operations.
The view's iterator is a "weakly consistent" iterator that will never throw ConcurrentModificationException, and guarantees to traverse elements as they existed upon construction of the iterator, and may (but is not guaranteed to) reflect any modifications subsequent to construction.
Warning: the iterator associated with this Set requires the creation of java.util.Map.Entry objects with each iteration. The NonBlockingHashMap does not normally create or using java.util.Map.Entry objects so they will be created soley to support this iteration. Iterating using keySet or {} will be more efficient.
Definition at line 1358 of file NonBlockingHashMap.java.
{
     return new AbstractSet<Map.Entry<TypeK,TypeV>>() {
       @Override public void    clear   (          ) {        NonBlockingHashMap.this.clear( ); }
       @Override public int     size    (          ) { return NonBlockingHashMap.this.size ( ); }
       @Override public boolean remove( final Object o ) {
         if( !(o instanceof Map.Entry)) return false;
         final Map.Entry<?,?> e = (Map.Entry<?,?>)o;
         return NonBlockingHashMap.this.remove(e.getKey(), e.getValue());
       }
       @Override public boolean contains(final Object o) {
         if( !(o instanceof Map.Entry)) return false;
         final Map.Entry<?,?> e = (Map.Entry<?,?>)o;
         TypeV v = get(e.getKey());
         return v.equals(e.getValue());
       }
       @Override public Iterator<Map.Entry<TypeK,TypeV>> iterator() { return new SnapshotE(); }
     };
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.toString().
get()
TypeV com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.get (Object key)
Returns the value to which the specified key is mapped, or.
null
if this map contains no mapping for the key.
More formally, if this map contains a mapping from a key
k
to a value
v
such that
key.equals(k)
, then this method returns
v
; otherwise it returns
null
. (There can be at most one such mapping.)
Exceptions
NullPointerException if the specified key is null
Definition at line 524 of file NonBlockingHashMap.java.
{
     final Object V = get_impl(this,_kvs,key);
     assert !(V instanceof Prime); // Never return a Prime
     assert V != TOMBSTONE;
     return (TypeV)V;
   }
get_impl()
static Object com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.get_impl (final NonBlockingHashMap< TypeK, TypeV > topmap, final Object[] kvs, final Object key) static private
Definition at line 531 of file NonBlockingHashMap.java.
{
     final int fullhash= hash (key); // throws NullPointerException if key is null
     final int len     = len  (kvs); // Count of key/value pairs, reads kvs.length
     final CHM chm     = chm  (kvs); // The CHM, for a volatile read below; reads slot 0 of kvs
     final int[] hashes=hashes(kvs); // The memoized hashes; reads slot 1 of kvs
     int idx = fullhash & (len-1); // First key hash
     // Main spin/reprobe loop, looking for a Key hit
     int reprobe_cnt=0;
     while( true ) {
       // Probe table.  Each read of 'val' probably misses in cache in a big
       // table; hopefully the read of 'key' then hits in cache.
       final Object K = key(kvs,idx); // Get key   before volatile read, could be null
       final Object V = val(kvs,idx); // Get value before volatile read, could be null or Tombstone or Prime
       if( K == null ) return null;   // A clear miss
       // We need a volatile-read here to preserve happens-before semantics on
       // newly inserted Keys.  If the Key body was written just before inserting
       // into the table a Key-compare here might read the uninitialized Key body.
       // Annoyingly this means we have to volatile-read before EACH key compare.
       // .
       // We also need a volatile-read between reading a newly inserted Value
       // and returning the Value (so the user might end up reading the stale
       // Value contents).  Same problem as with keys - and the one volatile
       // read covers both.
       final Object[] newkvs = chm._newkvs; // VOLATILE READ before key compare
       // Key-compare
       if( keyeq(K,key,hashes,idx,fullhash) ) {
         // Key hit!  Check for no table-copy-in-progress
         if( !(V instanceof Prime) ) // No copy?
           return (V == TOMBSTONE) ? null : V; // Return the value
         // Key hit - but slot is (possibly partially) copied to the new table.
         // Finish the copy & retry in the new table.
         return get_impl(topmap,chm.copy_slot_and_check(topmap,kvs,idx,key),key); // Retry in the new table
       }
       // get and put must have the same key lookup logic!  But only 'put'
       // needs to force a table-resize for a too-long key-reprobe sequence.
       // Check for too-many-reprobes on get - and flip to the new table.
       if( ++reprobe_cnt >= reprobe_limit(len) || // too many probes
           K == TOMBSTONE ) // found a TOMBSTONE key, means no more keys in this table
         return newkvs == null ? null : get_impl(topmap,topmap.help_copy(newkvs),key); // Retry in the new table
       idx = (idx+1)&(len-1);    // Reprobe by 1!  (could now prefetch)
     }
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.get(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.get_impl().
getk()
TypeK com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.getk (TypeK key)
Returns the Key to which the specified key is mapped, or.
null
if this map contains no mapping for the key.
Exceptions
NullPointerException if the specified key is null
Definition at line 585 of file NonBlockingHashMap.java.
{
     return (TypeK)getk_impl(this,_kvs,key);
   }
getk_impl()
static final Object com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.getk_impl (final NonBlockingHashMap< TypeK, TypeV > topmap, final Object[] kvs, final Object key) static private
Definition at line 589 of file NonBlockingHashMap.java.
{
     final int fullhash= hash (key); // throws NullPointerException if key is null
     final int len     = len  (kvs); // Count of key/value pairs, reads kvs.length
     final CHM chm     = chm  (kvs); // The CHM, for a volatile read below; reads slot 0 of kvs
     final int[] hashes=hashes(kvs); // The memoized hashes; reads slot 1 of kvs
     int idx = fullhash & (len-1); // First key hash
     // Main spin/reprobe loop, looking for a Key hit
     int reprobe_cnt=0;
     while( true ) {
       // Probe table.
       final Object K = key(kvs,idx); // Get key before volatile read, could be null
       if( K == null ) return null;   // A clear miss
       // We need a volatile-read here to preserve happens-before semantics on
       // newly inserted Keys.  If the Key body was written just before inserting
       // into the table a Key-compare here might read the uninitialized Key body.
       // Annoyingly this means we have to volatile-read before EACH key compare.
       // .
       // We also need a volatile-read between reading a newly inserted Value
       // and returning the Value (so the user might end up reading the stale
       // Value contents).  Same problem as with keys - and the one volatile
       // read covers both.
       final Object[] newkvs = chm._newkvs; // VOLATILE READ before key compare
       // Key-compare
       if( keyeq(K,key,hashes,idx,fullhash) )
         return K;              // Return existing Key!
       // get and put must have the same key lookup logic!  But only 'put'
       // needs to force a table-resize for a too-long key-reprobe sequence.
       // Check for too-many-reprobes on get - and flip to the new table.
       if( ++reprobe_cnt >= reprobe_limit(len) || // too many probes
           K == TOMBSTONE ) { // found a TOMBSTONE key, means no more keys in this table
         return newkvs == null ? null : getk_impl(topmap,topmap.help_copy(newkvs),key); // Retry in the new table
       }
       idx = (idx+1)&(len-1);    // Reprobe by 1!  (could now prefetch)
     }
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.getk(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.getk_impl().
getKey()
TypeK com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.getKey ()
Definition at line 477 of file NonBlockingHashMap.java.
 { return (TypeK)_getKey(_kvs); }
hash()
static int com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.hash (final Object key) static private
Definition at line 114 of file NonBlockingHashMap.java.
{
     int h = key.hashCode();     // The real hashCode call
     h ^= (h>>>20) ^ (h>>>12);
     h ^= (h>>> 7) ^ (h>>> 4);
     return h;
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.get_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.getk_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.keyeq(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch().
hashes()
static final int [] com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.hashes (Object[] kvs) static private
Definition at line 136 of file NonBlockingHashMap.java.
 { return (int[])kvs[1]; }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.get_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.getk_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.keyeq(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch().
help_copy()
final Object [] com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.help_copy (Object[] helper) private
Definition at line 788 of file NonBlockingHashMap.java.
{
     // Read the top-level KVS only once.  We'll try to help this copy along,
     // even if it gets promoted out from under us (i.e., the copy completes
     // and another KVS becomes the top-level copy).
     Object[] topkvs = _kvs;
     CHM topchm = chm(topkvs);
     if( topchm._newkvs == null ) return helper; // No copy in-progress
     topchm.help_copy_impl(this,topkvs,false);
     return helper;
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.copy_slot_and_check(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.get_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.getk_impl(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch().
initialize() [1/2]
final void com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.initialize () protected
Definition at line 271 of file NonBlockingHashMap.java.
 { initialize(MIN_SIZE); }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.initialize(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.NonBlockingHashMap(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.readObject().
initialize() [2/2]
final void com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.initialize (int initial_sz) private
Definition at line 259 of file NonBlockingHashMap.java.
{
     if( initial_sz < 0 ) throw new IllegalArgumentException();
     int i;                      // Convert to next largest power-of-2
     if( initial_sz > 1024*1024 ) initial_sz = 1024*1024;
     for( i=MIN_SIZE_LOG; (1<<i) < (initial_sz<<2); i++ ) ;
     // Double size for K,V pairs, add 1 for CHM and 1 for hashes
     _kvs = new Object[((1<<i)<<1)+2];
     _kvs[0] = new CHM(new ConcurrentAutoTable()); // CHM in slot 0
     _kvs[1] = new int[1<<i];          // Matching hash entries
     _last_resize_milli = System.currentTimeMillis();
   }
isEmpty()
boolean com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.isEmpty ()
Returns size() == 0.
Returns
size() == 0
Definition at line 282 of file NonBlockingHashMap.java.
 { return size() == 0;      }
key()
static final Object com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.key (Object[] kvs, int idx) static private
Definition at line 172 of file NonBlockingHashMap.java.
 { return kvs[(idx<<1)+2]; }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >._getKey(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.CAS_key(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.containsKey(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.copy_slot(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.get(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.get_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.getk(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.getk_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.hash(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.key(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.keyeq(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.print(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.print2(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.put(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfAbsent(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatchAllowNull(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.remove(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.replace(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.toString().
keyeq()
static boolean com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.keyeq (Object K, Object key, int[] hashes, int hash, int fullhash) static private
Definition at line 495 of file NonBlockingHashMap.java.
{
     return
       K==key ||                 // Either keys match exactly OR
       // hash exists and matches?  hash can be zero during the install of a
       // new key/value pair.
       ((hashes[hash] == 0 || hashes[hash] == fullhash) &&
        // Do not call the users' "equals()" call with a Tombstone, as this can
        // surprise poorly written "equals()" calls that throw exceptions
        // instead of simply returning false.
        K != TOMBSTONE &&        // Do not call users' equals call with a Tombstone
        // Do the match the hard way - with the users' key being the loop-
        // invariant "this" pointer.  I could have flipped the order of
        // operands (since equals is commutative), but I'm making mega-morphic
        // v-calls in a reprobing loop and nailing down the 'this' argument
        // gives both the JIT and the hardware a chance to prefetch the call target.
        key.equals(K));          // Finally do the hard match
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.get_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.getk_impl(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch().
keys()
Enumeration<TypeK> com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.keys ()
Returns an enumeration of the keys in this table.
Returns
an enumeration of the keys in this table
See also
keySet()
Definition at line 1289 of file NonBlockingHashMap.java.
 { return new SnapshotK(); }
keySet()
Set<TypeK> com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.keySet ()
Returns a Set view of the keys contained in this map.
The set is backed by the map, so changes to the map are reflected in the set, and vice-versa. The set supports element removal, which removes the corresponding mapping from this map, via the Iterator.remove, Set.remove, removeAll, retainAll, and clear operations. It does not support the add or addAll operations.
The view's iterator is a "weakly consistent" iterator that will never throw ConcurrentModificationException, and guarantees to traverse elements as they existed upon construction of the iterator, and may (but is not guaranteed to) reflect any modifications subsequent to construction.
Definition at line 1305 of file NonBlockingHashMap.java.
{
     return new AbstractSet<TypeK> () {
       @Override public void    clear   (          ) {        NonBlockingHashMap.this.clear   ( ); }
       @Override public int     size    (          ) { return NonBlockingHashMap.this.size    ( ); }
       @Override public boolean contains( Object k ) { return NonBlockingHashMap.this.containsKey(k); }
       @Override public boolean remove  ( Object k ) { return NonBlockingHashMap.this.remove  (k) != null; }
       @Override public Iterator<TypeK> iterator()   { return new SnapshotK(); }
     };
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.clone(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.writeObject().
len()
static final int com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.len (Object[] kvs) static private
Definition at line 138 of file NonBlockingHashMap.java.
 { return (kvs.length-2)>>1; }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >._getKey(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.copy_check_and_promote(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.get_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.getk_impl(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.help_copy_impl(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.length(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.print(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.print2(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.reprobe_limit(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.resize(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.tableFull().
print() [1/2]
final void com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.print ()
Verbose printout of table internals, useful for debugging.
Definition at line 184 of file NonBlockingHashMap.java.
{
     System.out.println("=========");
     print2(_kvs);
     System.out.println("=========");
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.print().
print() [2/2]
final void com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.print (Object[] kvs) private
Definition at line 190 of file NonBlockingHashMap.java.
{
     for( int i=0; i<len(kvs); i++ ) {
       Object K = key(kvs,i);
       if( K != null ) {
         String KS = (K == TOMBSTONE) ? "XXX" : K.toString();
         Object V = val(kvs,i);
         Object U = Prime.unbox(V);
         String p = (V==U) ? "" : "prime_";
         String US = (U == TOMBSTONE) ? "tombstone" : U.toString();
         System.out.println(""+i+" ("+KS+","+p+US+")");
       }
     }
     Object[] newkvs = chm(kvs)._newkvs; // New table, if any
     if( newkvs != null ) {
       System.out.println("----");
       print(newkvs);
     }
   }
print2()
final void com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.print2 (Object[] kvs) private
Definition at line 209 of file NonBlockingHashMap.java.
{
     for( int i=0; i<len(kvs); i++ ) {
       Object key = key(kvs,i);
       Object val = val(kvs,i);
       Object U = Prime.unbox(val);
       if( key != null && key != TOMBSTONE &&  // key is sane
           val != null && U   != TOMBSTONE ) { // val is sane
         String p = (val==U) ? "" : "prime_";
         System.out.println(""+i+" ("+key+","+p+val+")");
       }
     }
     Object[] newkvs = chm(kvs)._newkvs; // New table, if any
     if( newkvs != null ) {
       System.out.println("----");
       print2(newkvs);
     }
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.print(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.print2().
put()
TypeV com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.put (TypeK key, TypeV val)
Maps the specified key to the specified value in the table.
Neither key nor value can be null.
The value can be retrieved by calling get with a key that is equal to the original key.
Parameters
key key with which the specified value is to be associated
val value to be associated with the specified key
Returns
the previous value associated with key, or null if there was no mapping for key
Exceptions
NullPointerException if the specified key or value is null
Definition at line 310 of file NonBlockingHashMap.java.
 { return putIfMatch( key,      val, NO_MATCH_OLD); }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.clone(), com.cliffc.aa.tvar.TV2.make(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putAll(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.readObject(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.NBHMEntry.setValue().
putAll()
void com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.putAll (Map<? extends TypeK, ? extends TypeV > m)
Copies all of the mappings from the specified map to this one, replacing any existing mappings.
Parameters
m mappings to be stored in this map
Definition at line 374 of file NonBlockingHashMap.java.
{
     for (Map.Entry<? extends TypeK, ? extends TypeV> e : m.entrySet())
       put(e.getKey(), e.getValue());
   }
putIfAbsent()
TypeV com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.putIfAbsent (TypeK key, TypeV val)
Atomically, do a put if-and-only-if the key is not mapped.
Useful to ensure that only a single mapping for the key exists, even if many threads are trying to create the mapping in parallel.
Returns
the previous value associated with the specified key, or null if there was no mapping for the key
Exceptions
NullPointerException if the specified key or value is null
Definition at line 318 of file NonBlockingHashMap.java.
 { return putIfMatch( key,      val, TOMBSTONE   ); }
putIfMatch() [1/2]
static final Object com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.putIfMatch (final NonBlockingHashMap< TypeK, TypeV > topmap, final Object[] kvs, final Object key, final Object putval, final Object expVal) static private
Definition at line 638 of file NonBlockingHashMap.java.
{
     assert putval != null;
     assert !(putval instanceof Prime);
     assert !(expVal instanceof Prime);
     final int fullhash = hash  (key); // throws NullPointerException if key null
     final int len      = len   (kvs); // Count of key/value pairs, reads kvs.length
     final CHM chm      = chm   (kvs); // Reads kvs[0]
     final int[] hashes = hashes(kvs); // Reads kvs[1], read before kvs[0]
     int idx = fullhash & (len-1);
     // ---
     // Key-Claim stanza: spin till we can claim a Key (or force a resizing).
     int reprobe_cnt=0;
     Object K=null, V=null;
     Object[] newkvs=null;
     while( true ) {             // Spin till we get a Key slot
       V = val(kvs,idx);         // Get old value (before volatile read below!)
       K = key(kvs,idx);         // Get current key
       if( K == null ) {         // Slot is free?
         // Found an empty Key slot - which means this Key has never been in
         // this table.  No need to put a Tombstone - the Key is not here!
         if( putval == TOMBSTONE ) return putval; // Not-now & never-been in this table
         if( expVal == MATCH_ANY ) return null;   // Will not match, even after K inserts
         // Claim the null key-slot
         if( CAS_key(kvs,idx, null, key ) ) { // Claim slot for Key
           chm._slots.add(1);      // Raise key-slots-used count
           hashes[idx] = fullhash; // Memoize fullhash
           break;                  // Got it!
         }
         // CAS to claim the key-slot failed.
         //
         // This re-read of the Key points out an annoying short-coming of Java
         // CAS.  Most hardware CAS's report back the existing value - so that
         // if you fail you have a *witness* - the value which caused the CAS to
         // fail.  The Java API turns this into a boolean destroying the
         // witness.  Re-reading does not recover the witness because another
         // thread can write over the memory after the CAS.  Hence we can be in
         // the unfortunate situation of having a CAS fail *for cause* but
         // having that cause removed by a later store.  This turns a
         // non-spurious-failure CAS (such as Azul has) into one that can
         // apparently spuriously fail - and we avoid apparent spurious failure
         // by not allowing Keys to ever change.
         // Volatile read, to force loads of K to retry despite JIT, otherwise
         // it is legal to e.g. haul the load of "K = key(kvs,idx);" outside of
         // this loop (since failed CAS ops have no memory ordering semantics).
         int dummy = DUMMY_VOLATILE;
         continue;
       }
       // Key slot was not null, there exists a Key here
       // We need a volatile-read here to preserve happens-before semantics on
       // newly inserted Keys.  If the Key body was written just before inserting
       // into the table a Key-compare here might read the uninitialized Key body.
       // Annoyingly this means we have to volatile-read before EACH key compare.
       newkvs = chm._newkvs;     // VOLATILE READ before key compare
       if( keyeq(K,key,hashes,idx,fullhash) )
         break;                  // Got it!
       // get and put must have the same key lookup logic!  Lest 'get' give
       // up looking too soon.
       //topmap._reprobes.add(1);
       if( ++reprobe_cnt >= reprobe_limit(len) || // too many probes or
           K == TOMBSTONE ) { // found a TOMBSTONE key, means no more keys
         // We simply must have a new table to do a 'put'.  At this point a
         // 'get' will also go to the new table (if any).  We do not need
         // to claim a key slot (indeed, we cannot find a free one to claim!).
         newkvs = chm.resize(topmap,kvs);
         if( expVal != null ) topmap.help_copy(newkvs); // help along an existing copy
         return putIfMatch(topmap,newkvs,key,putval,expVal);
       }
       idx = (idx+1)&(len-1); // Reprobe!
     } // End of spinning till we get a Key slot
     // ---
     // Found the proper Key slot, now update the matching Value slot.  We
     // never put a null, so Value slots monotonically move from null to
     // not-null (deleted Values use Tombstone).  Thus if 'V' is null we
     // fail this fast cutout and fall into the check for table-full.
     if( putval == V ) return V; // Fast cutout for no-change
     // See if we want to move to a new table (to avoid high average re-probe
     // counts).  We only check on the initial set of a Value from null to
     // not-null (i.e., once per key-insert).  Of course we got a 'free' check
     // of newkvs once per key-compare (not really free, but paid-for by the
     // time we get here).
     if( newkvs == null &&       // New table-copy already spotted?
         // Once per fresh key-insert check the hard way
         ((V == null && chm.tableFull(reprobe_cnt,len)) ||
          // Or we found a Prime, but the JMM allowed reordering such that we
          // did not spot the new table (very rare race here: the writing
          // thread did a CAS of _newkvs then a store of a Prime.  This thread
          // reads the Prime, then reads _newkvs - but the read of Prime was so
          // delayed (or the read of _newkvs was so accelerated) that they
          // swapped and we still read a null _newkvs.  The resize call below
          // will do a CAS on _newkvs forcing the read.
          V instanceof Prime) )
       newkvs = chm.resize(topmap,kvs); // Force the new table copy to start
     // See if we are moving to a new table.
     // If so, copy our slot and retry in the new table.
     if( newkvs != null )
       return putIfMatch(topmap,chm.copy_slot_and_check(topmap,kvs,idx,expVal),key,putval,expVal);
     // ---
     // We are finally prepared to update the existing table
     assert !(V instanceof Prime);
     // Must match old, and we do not?  Then bail out now.  Note that either V
     // or expVal might be TOMBSTONE.  Also V can be null, if we've never
     // inserted a value before.  expVal can be null if we are called from
     // copy_slot.
     if( expVal != NO_MATCH_OLD && // Do we care about expected-Value at all?
         V != expVal &&            // No instant match already?
         (expVal != MATCH_ANY || V == TOMBSTONE || V == null) &&
         !(V==null && expVal == TOMBSTONE) &&    // Match on null/TOMBSTONE combo
         (expVal == null || !expVal.equals(V)) ) // Expensive equals check at the last
       return V;                                 // Do not update!
     // Actually change the Value in the Key,Value pair
     if( CAS_val(kvs, idx, V, putval ) ) {
       // CAS succeeded - we did the update!
       // Both normal put's and table-copy calls putIfMatch, but table-copy
       // does not (effectively) increase the number of live k/v pairs.
       if( expVal != null ) {
         // Adjust sizes - a striped counter
         if(  (V == null || V == TOMBSTONE) && putval != TOMBSTONE ) chm._size.add( 1);
         if( !(V == null || V == TOMBSTONE) && putval == TOMBSTONE ) chm._size.add(-1);
       }
     } else {                    // Else CAS failed
       V = val(kvs,idx);         // Get new value
       // If a Prime'd value got installed, we need to re-run the put on the
       // new table.  Otherwise we lost the CAS to another racing put.
       // Simply retry from the start.
       if( V instanceof Prime )
         return putIfMatch(topmap,chm.copy_slot_and_check(topmap,kvs,idx,expVal),key,putval,expVal);
     }
     // Win or lose the CAS, we are done.  If we won then we know the update
     // happened as expected.  If we lost, it means "we won but another thread
     // immediately stomped our update with no chance of a reader reading".
     return (V==null && expVal!=null) ? TOMBSTONE : V;
   }
putIfMatch() [2/2]
final TypeV com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.putIfMatch (Object key, Object newVal, Object oldVal) private
Definition at line 361 of file NonBlockingHashMap.java.
{
     if (oldVal == null || newVal == null) throw new NullPointerException();
     final Object res = putIfMatch( this, _kvs, key, newVal, oldVal );
     assert !(res instanceof Prime);
     assert res != null;
     return res == TOMBSTONE ? null : (TypeV)res;
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.copy_slot(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.put(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfAbsent(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatchAllowNull(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.remove(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.remove(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.replace().
putIfMatchAllowNull()
final TypeV com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.putIfMatchAllowNull (Object key, Object newVal, Object oldVal)
Definition at line 351 of file NonBlockingHashMap.java.
{
     if( oldVal == null ) oldVal = TOMBSTONE;
     if( newVal == null ) newVal = TOMBSTONE;
     final TypeV res = (TypeV)putIfMatch( this, _kvs, key, newVal, oldVal );
     assert !(res instanceof Prime);
     //assert res != null;
     return res == TOMBSTONE ? null : res;
   }
raw_array()
Object [] com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.raw_array ()
Definition at line 1243 of file NonBlockingHashMap.java.
 { return new SnapshotV()._sskvs; }
rawIndex()
static long com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.rawIndex (final Object[] ary, final int idx) static private
Definition at line 86 of file NonBlockingHashMap.java.
{
     assert idx >= 0 && idx < ary.length;
     // Note the long-math requirement, to handle arrays of more than 2^31 bytes
     // - or 2^28 - or about 268M - 8-byte pointer elements.
     return _Obase + ((long)idx << _Olog);
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.CAS_key(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.CAS_val().
readObject()
void com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.readObject (java.io.ObjectInputStream s) throws IOException, ClassNotFoundException private
Definition at line 1393 of file NonBlockingHashMap.java.
{
     s.defaultReadObject();      // Read nothing
     initialize(MIN_SIZE);
     for(;;) {
       final TypeK K = (TypeK) s.readObject();
       final TypeV V = (TypeV) s.readObject();
       if( K == null ) break;
       put(K,V);                 // Insert with an offical put
     }
   }
rehash()
void com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.rehash () protected
Definition at line 405 of file NonBlockingHashMap.java.
{
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.resize().
remove() [1/2]
TypeV com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.remove (Object key)
Removes the key (and its corresponding value) from this map.
This method does nothing if the key is not in the map.
Returns
the previous value associated with key, or null if there was no mapping for key
Exceptions
NullPointerException if the specified key is null
Definition at line 326 of file NonBlockingHashMap.java.
 { return putIfMatch( key,TOMBSTONE, NO_MATCH_OLD); }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.entrySet(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.keySet().
remove() [2/2]
boolean com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.remove (Object key, Object val)
Atomically do a remove(Object) if-and-only-if the key is mapped to a value which is equals to the given value.
Exceptions
NullPointerException if the specified key or value is null
Definition at line 331 of file NonBlockingHashMap.java.
 { return putIfMatch( key,TOMBSTONE, val ) == val; }
replace() [1/2]
boolean com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.replace (TypeK key, TypeV oldValue, TypeV newValue)
Atomically do a put(key,newValue) if-and-only-if the key is mapped a value which is equals to oldValue.
Exceptions
NullPointerException if the specified key or value is null
Definition at line 341 of file NonBlockingHashMap.java.
{
     return putIfMatch( key, newValue, oldValue ) == oldValue;
   }
replace() [2/2]
TypeV com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.replace (TypeK key, TypeV val)
Atomically do a put(key,val) if-and-only-if the key is mapped to some value already.
Exceptions
NullPointerException if the specified key or value is null
Definition at line 336 of file NonBlockingHashMap.java.
 { return putIfMatch( key,      val,MATCH_ANY   ); }
reprobe_limit()
static final int com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.reprobe_limit (int len) static private
Definition at line 242 of file NonBlockingHashMap.java.
{
     return REPROBE_LIMIT + (len>>4);
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.get_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.getk_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.tableFull().
reprobes()
long com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.reprobes ()
Get and clear the current count of reprobes.
Reprobes happen on key collisions, and a high reprobe rate may indicate a poor hash function or weaknesses in the table resizing function.
Returns
the count of reprobes since the last call to reprobes or since the table was created.
Definition at line 234 of file NonBlockingHashMap.java.
 { long r = _reprobes.get(); _reprobes = new ConcurrentAutoTable(); return r; }
size()
int com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.size ()
Returns the number of key-value mappings in this map.
Returns
the number of key-value mappings in this map
Definition at line 278 of file NonBlockingHashMap.java.
 { return chm(_kvs).size(); }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.entrySet(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.isEmpty(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.keySet(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.values().
toString()
String com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.toString ()
Returns a string representation of this map.
The string representation consists of a list of key-value mappings in the order returned by the map's entrySet view's iterator, enclosed in braces ("{}"). Adjacent mappings are separated by the characters ", " (comma and space). Each key-value mapping is rendered as the key followed by an equals sign ("=") followed by the associated value. Keys and values are converted to strings as by String#valueOf(Object).
Returns
a string representation of this map
Definition at line 453 of file NonBlockingHashMap.java.
{
     Iterator<Entry<TypeK,TypeV>> i = entrySet().iterator();
     if( !i.hasNext())
       return "{}";
     StringBuilder sb = new StringBuilder();
     sb.append('{');
     for (;;) {
       Entry<TypeK,TypeV> e = i.next();
       TypeK key = e.getKey();
       TypeV value = e.getValue();
       sb.append(key   == this ? "(this Map)" : key);
       sb.append('=');
       sb.append(value == this ? "(this Map)" : value);
       if( !i.hasNext())
         return sb.append('}').toString();
       sb.append(", ");
     }
   }
val()
static final Object com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.val (Object[] kvs, int idx) static private
Definition at line 173 of file NonBlockingHashMap.java.
 { return kvs[(idx<<1)+3]; }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >._getKey(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.CAS_val(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.contains(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.containsValue(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.copy_slot(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.get_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.print(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.print2(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.put(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfAbsent(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.remove(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.replace(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.NBHMEntry.setValue(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.val().
values()
Collection<TypeV> com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.values ()
Returns a Collection view of the values contained in this map.
The collection is backed by the map, so changes to the map are reflected in the collection, and vice-versa. The collection supports element removal, which removes the corresponding mapping from this map, via the Iterator.remove, Collection.remove, removeAll, retainAll, and clear operations. It does not support the add or addAll operations.
The view's iterator is a "weakly consistent" iterator that will never throw ConcurrentModificationException, and guarantees to traverse elements as they existed upon construction of the iterator, and may (but is not guaranteed to) reflect any modifications subsequent to construction.
Definition at line 1265 of file NonBlockingHashMap.java.
{
     return new AbstractCollection<TypeV>() {
       @Override public void    clear   (          ) {        NonBlockingHashMap.this.clear        ( ); }
       @Override public int     size    (          ) { return NonBlockingHashMap.this.size         ( ); }
       @Override public boolean contains( Object v ) { return NonBlockingHashMap.this.containsValue(v); }
       @Override public Iterator<TypeV> iterator()   { return new SnapshotV(); }
     };
   }
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.containsValue().
writeObject()
void com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.writeObject (java.io.ObjectOutputStream s) throws IOException private
Definition at line 1379 of file NonBlockingHashMap.java.
{
     s.defaultWriteObject();     // Nothing to write
     for( Object K : keySet() ) {
       final Object V = get(K);  // Do an official 'get'
       s.writeObject(K);         // Write the <TypeK,TypeV> pair
       s.writeObject(V);
     }
     s.writeObject(null);        // Sentinel to indicate end-of-data
     s.writeObject(null);
   }
Member Data Documentation
_kvs
transient Object [] com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >._kvs private
Definition at line 134 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.clear(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.copy_check_and_promote(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.get(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.getk(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.getKey(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.help_copy(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.initialize(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.print(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatchAllowNull(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.size(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.SnapshotV().
_kvs_offset
final long com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >._kvs_offset static private
Definition at line 94 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.CAS_kvs().
_last_resize_milli
transient long com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >._last_resize_milli private
Definition at line 141 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.copy_check_and_promote(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.initialize(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.resize().
_Obase
final int com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >._Obase = _unsafe.arrayBaseOffset(Object[].class) static private
Definition at line 83 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.rawIndex().
_Olog
final int com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >._Olog = _Oscale==4?2:(_Oscale==8?3:9999) static private
Definition at line 85 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.rawIndex().
_Oscale
final int com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >._Oscale = _unsafe.arrayIndexScale(Object[].class) static private
Definition at line 84 of file NonBlockingHashMap.java.
_reprobes
transient ConcurrentAutoTable com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >._reprobes = new ConcurrentAutoTable() private
Definition at line 228 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.reprobes().
_unsafe
final Unsafe com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >._unsafe = UtilUnsafe.getUnsafe() static private
Definition at line 82 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.CAS_key(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.CAS_kvs(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.CAS_val().
DUMMY_VOLATILE
volatile int com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.DUMMY_VOLATILE static package
Definition at line 637 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch().
MATCH_ANY
final Object com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.MATCH_ANY = new Object() static private
Definition at line 155 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.replace().
MIN_SIZE
final int com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.MIN_SIZE =(1<<MIN_SIZE_LOG) static private
Definition at line 147 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.clear(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.initialize(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.NonBlockingHashMap(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.readObject().
MIN_SIZE_LOG
final int com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.MIN_SIZE_LOG =3 static private
Definition at line 146 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.initialize(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.resize().
NO_MATCH_OLD
final Object com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.NO_MATCH_OLD = new Object() static private
Definition at line 152 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.put(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch(), and com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.remove().
REPROBE_LIMIT
final int com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.REPROBE_LIMIT =10 static private
Definition at line 79 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.reprobe_limit(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.tableFull().
serialVersionUID
final long com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.serialVersionUID = 1234123412341234123L static private
Definition at line 77 of file NonBlockingHashMap.java.
TOMBPRIME
final Prime com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.TOMBPRIME = new Prime(TOMBSTONE) static private
Definition at line 163 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.copy_slot().
TOMBSTONE
final Object com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.TOMBSTONE = new Object() static
Definition at line 158 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >._getKey(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.copy_slot(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.get(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.get_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.getk_impl(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.keyeq(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.next(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.print(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.print2(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfAbsent(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatch(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.putIfMatchAllowNull(), com.cliffc.aa.util.NonBlockingHashMap< com.cliffc.aa.type.Type.Key, com.cliffc.aa.type.Type >.remove(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.remove().
The documentation for this class was generated from the following file:
NonBlockingHashMap.java