aa: com.cliffc.aa.HM.HM5.Let Class Reference
com.cliffc.aa.HM.HM5.Let Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Let (String arg0, Syntax def, Syntax body)
void add_kids (Worklist work)
void add_occurs (Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
T2 lookup (String name)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
T2 targ ()
Package Attributes
final String _arg0
final Syntax _body
final Syntax _def
VStack _nongen
Syntax _par
T2 _t
T2 _targ
Detailed Description
Definition at line 304 of file HM5.java.
Constructor & Destructor Documentation
Let()
com.cliffc.aa.HM.HM5.Let.Let (String arg0, Syntax def, Syntax body) package
Definition at line 308 of file HM5.java.
 { _arg0=arg0; _body=body; _def=def; _targ=T2.make_leaf(); }
References com.cliffc.aa.HM.HM5.Let._arg0, com.cliffc.aa.HM.HM5.Let._body, com.cliffc.aa.HM.HM5.Let._def, com.cliffc.aa.HM.HM5.Let._targ, and com.cliffc.aa.HM.HM5.T2.make_leaf().
Member Function Documentation
add_kids()
void com.cliffc.aa.HM.HM5.Let.add_kids (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 320 of file HM5.java.
 { work.push(_body); work.push(_def); }
References com.cliffc.aa.HM.HM5.Let._body, com.cliffc.aa.HM.HM5.Let._def, and com.cliffc.aa.HM.HM5.Worklist.push().
add_occurs()
void com.cliffc.aa.HM.HM5.Let.add_occurs (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 321 of file HM5.java.
{
       if( targ().occurs_in_type(find()) ) work.addAll(_targ._deps);
     }
References com.cliffc.aa.HM.HM5.T2._deps, com.cliffc.aa.HM.HM5.Let._targ, com.cliffc.aa.HM.HM5.Worklist.addAll(), com.cliffc.aa.HM.HM5.Syntax.find(), and com.cliffc.aa.HM.HM5.Let.targ().
debug_find()
T2 com.cliffc.aa.HM.HM5.Syntax.debug_find () package inherited
Definition at line 127 of file HM5.java.
 { return _t.find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM5.Syntax._t, and com.cliffc.aa.HM.HM5.T2.find().
Referenced by com.cliffc.aa.HM.HM5.hm().
find()
T2 com.cliffc.aa.HM.HM5.Syntax.find () package inherited
Definition at line 123 of file HM5.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM5.Syntax._t, and com.cliffc.aa.HM.HM5.T2.find().
Referenced by com.cliffc.aa.HM.HM5.T2._occurs_in(), com.cliffc.aa.HM.HM5.Lambda.add_occurs(), com.cliffc.aa.HM.HM5.Lambda2.add_occurs(), com.cliffc.aa.HM.HM5.Let.add_occurs(), com.cliffc.aa.HM.HM5.Con.hm(), com.cliffc.aa.HM.HM5.Ident.hm(), com.cliffc.aa.HM.HM5.Lambda.hm(), com.cliffc.aa.HM.HM5.Lambda2.hm(), com.cliffc.aa.HM.HM5.Let.hm(), and com.cliffc.aa.HM.HM5.Apply.hm().
hm()
boolean com.cliffc.aa.HM.HM5.Let.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 313 of file HM5.java.
{
       return targ().unify(_def.find(),work);
     }
References com.cliffc.aa.HM.HM5.Let._def, com.cliffc.aa.HM.HM5.Syntax.find(), com.cliffc.aa.HM.HM5.Let.targ(), and com.cliffc.aa.HM.HM5.T2.unify().
lookup()
T2 com.cliffc.aa.HM.HM5.Let.lookup (String name) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 316 of file HM5.java.
{
       if( Util.eq(_arg0,name) ) return targ();
       return _par==null ? null : _par.lookup(name);
     }
References com.cliffc.aa.HM.HM5.Let._arg0, com.cliffc.aa.HM.HM5.Syntax._par, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM5.Syntax.lookup(), and com.cliffc.aa.HM.HM5.Let.targ().
more_work()
boolean com.cliffc.aa.HM.HM5.Let.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 334 of file HM5.java.
{
       if( !more_work_impl(work) ) return false;
       return _body.more_work(work) && _def.more_work(work);
     }
References com.cliffc.aa.HM.HM5.Let._body, com.cliffc.aa.HM.HM5.Let._def, com.cliffc.aa.HM.HM5.Syntax.more_work(), and com.cliffc.aa.HM.HM5.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM5.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 147 of file HM5.java.
{
       return work.has(this) || !hm(null); // Either on worklist, or no-progress
     }
References com.cliffc.aa.HM.HM5.Worklist.has(), and com.cliffc.aa.HM.HM5.Syntax.hm().
Referenced by com.cliffc.aa.HM.HM5.Con.more_work(), com.cliffc.aa.HM.HM5.Ident.more_work(), com.cliffc.aa.HM.HM5.Lambda.more_work(), com.cliffc.aa.HM.HM5.Lambda2.more_work(), com.cliffc.aa.HM.HM5.Let.more_work(), and com.cliffc.aa.HM.HM5.Apply.more_work().
p()
String com.cliffc.aa.HM.HM5.Syntax.p () inherited
Definition at line 154 of file HM5.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM5.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM5.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 155 of file HM5.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM5.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM5.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM5.Syntax.p1(), com.cliffc.aa.HM.HM5.Syntax.p2(), and com.cliffc.aa.HM.HM5.T2.str().
Referenced by com.cliffc.aa.HM.HM5.Syntax.p(), com.cliffc.aa.HM.HM5.Lambda.p2(), com.cliffc.aa.HM.HM5.Lambda2.p2(), com.cliffc.aa.HM.HM5.Let.p2(), and com.cliffc.aa.HM.HM5.Apply.p2().
p1()
SB com.cliffc.aa.HM.HM5.Let.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 310 of file HM5.java.
 { return sb.p("let ").p(_arg0).p(" = ... in ..."); }
References com.cliffc.aa.HM.HM5.Let._arg0, and com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM5.Let.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 311 of file HM5.java.
 { _body.p0(sb,dups); return _def.p0(sb,dups); }
References com.cliffc.aa.HM.HM5.Let._body, com.cliffc.aa.HM.HM5.Let._def, and com.cliffc.aa.HM.HM5.Syntax.p0().
prep_lookup_deps()
void com.cliffc.aa.HM.HM5.Let.prep_lookup_deps (Ident id) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 331 of file HM5.java.
{
       if( Util.eq(id._name,_arg0) ) _targ.push_update(id);
     }
References com.cliffc.aa.HM.HM5.Let._arg0, com.cliffc.aa.HM.HM5.Let._targ, com.cliffc.aa.util.Util.eq(), and com.cliffc.aa.HM.HM5.T2.push_update().
prep_tree()
int com.cliffc.aa.HM.HM5.Let.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 324 of file HM5.java.
{
       prep_tree_impl(par,nongen,work,_body._t);
       int cnt = _body.prep_tree(this,           nongen       ,work) +
                 _def .prep_tree(this,new VStack(nongen,_targ),work);
       _t = _body._t;            // Unify 'Let._t' with the '_body'
       return cnt;
     }
References com.cliffc.aa.HM.HM5.Let._body, com.cliffc.aa.HM.HM5.Let._def, com.cliffc.aa.HM.HM5.Syntax._t, com.cliffc.aa.HM.HM5.Let._targ, com.cliffc.aa.HM.HM5.Syntax.prep_tree(), and com.cliffc.aa.HM.HM5.Syntax.prep_tree_impl().
prep_tree_impl()
final void com.cliffc.aa.HM.HM5.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 137 of file HM5.java.
 { _par=par; _t=t; _nongen = nongen; work.push(this); }
References com.cliffc.aa.HM.HM5.Syntax._nongen, com.cliffc.aa.HM.HM5.Syntax._par, com.cliffc.aa.HM.HM5.Syntax._t, and com.cliffc.aa.HM.HM5.Worklist.push().
Referenced by com.cliffc.aa.HM.HM5.Con.prep_tree(), com.cliffc.aa.HM.HM5.Ident.prep_tree(), com.cliffc.aa.HM.HM5.Lambda.prep_tree(), com.cliffc.aa.HM.HM5.Lambda2.prep_tree(), com.cliffc.aa.HM.HM5.Let.prep_tree(), and com.cliffc.aa.HM.HM5.Apply.prep_tree().
str()
SB com.cliffc.aa.HM.HM5.Let.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 309 of file HM5.java.
 { return _body.str(_def.str(sb.p("let ").p(_arg0).p(" = ")).p(" in ")); }
References com.cliffc.aa.HM.HM5.Let._arg0, com.cliffc.aa.HM.HM5.Let._body, com.cliffc.aa.HM.HM5.Let._def, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM5.Syntax.str().
targ()
T2 com.cliffc.aa.HM.HM5.Let.targ () package
Definition at line 312 of file HM5.java.
 { T2 targ = _targ.find(); return targ==_targ ? targ : (_targ=targ); }
References com.cliffc.aa.HM.HM5.Let._targ, com.cliffc.aa.HM.HM5.T2.find(), and com.cliffc.aa.HM.HM5.Let.targ().
Referenced by com.cliffc.aa.HM.HM5.Let.add_occurs(), com.cliffc.aa.HM.HM5.Let.hm(), com.cliffc.aa.HM.HM5.Let.lookup(), and com.cliffc.aa.HM.HM5.Let.targ().
toString()
final String com.cliffc.aa.HM.HM5.Syntax.toString () inherited
Definition at line 151 of file HM5.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM5.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_arg0
final String com.cliffc.aa.HM.HM5.Let._arg0 package
Definition at line 305 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Let.Let(), com.cliffc.aa.HM.HM5.Let.lookup(), com.cliffc.aa.HM.HM5.Let.p1(), com.cliffc.aa.HM.HM5.Let.prep_lookup_deps(), and com.cliffc.aa.HM.HM5.Let.str().
_body
final Syntax com.cliffc.aa.HM.HM5.Let._body package
Definition at line 306 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Let.add_kids(), com.cliffc.aa.HM.HM5.Let.Let(), com.cliffc.aa.HM.HM5.Let.more_work(), com.cliffc.aa.HM.HM5.Let.p2(), com.cliffc.aa.HM.HM5.Let.prep_tree(), and com.cliffc.aa.HM.HM5.Let.str().
_def
final Syntax com.cliffc.aa.HM.HM5.Let._def package
Definition at line 306 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Let.add_kids(), com.cliffc.aa.HM.HM5.Let.hm(), com.cliffc.aa.HM.HM5.Let.Let(), com.cliffc.aa.HM.HM5.Let.more_work(), com.cliffc.aa.HM.HM5.Let.p2(), com.cliffc.aa.HM.HM5.Let.prep_tree(), and com.cliffc.aa.HM.HM5.Let.str().
_nongen
VStack com.cliffc.aa.HM.HM5.Syntax._nongen package inherited
Definition at line 121 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Ident.hm(), and com.cliffc.aa.HM.HM5.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM5.Syntax._par package inherited
Definition at line 120 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.T2._occurs_in(), com.cliffc.aa.HM.HM5.Ident.add_occurs(), com.cliffc.aa.HM.HM5.hm(), com.cliffc.aa.HM.HM5.Ident.hm(), com.cliffc.aa.HM.HM5.Lambda.lookup(), com.cliffc.aa.HM.HM5.Lambda2.lookup(), com.cliffc.aa.HM.HM5.Let.lookup(), com.cliffc.aa.HM.HM5.Apply.lookup(), com.cliffc.aa.HM.HM5.Ident.prep_tree(), and com.cliffc.aa.HM.HM5.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM5.Syntax._t package inherited
Definition at line 122 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Syntax.debug_find(), com.cliffc.aa.HM.HM5.Syntax.find(), com.cliffc.aa.HM.HM5.hm(), com.cliffc.aa.HM.HM5.Syntax.p0(), com.cliffc.aa.HM.HM5.Let.prep_tree(), and com.cliffc.aa.HM.HM5.Syntax.prep_tree_impl().
_targ
T2 com.cliffc.aa.HM.HM5.Let._targ package
Definition at line 307 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Let.add_occurs(), com.cliffc.aa.HM.HM5.Let.Let(), com.cliffc.aa.HM.HM5.Let.prep_lookup_deps(), com.cliffc.aa.HM.HM5.Let.prep_tree(), and com.cliffc.aa.HM.HM5.Let.targ().
The documentation for this class was generated from the following file:
HM5.java