aa: com.cliffc.aa.node.NewStrNode.ConvertF64Str Class Reference
com.cliffc.aa.node.NewStrNode.ConvertF64Str Class Reference
Public Member Functions
ConvertF64Str ()
FunPtrNode as_fun (GVNGCM gvn)
TypeMem live_use (GVNGCM.Mode opt_mode, Node def)
boolean unify (boolean test)
Static Public Member Functions
static Ary< NewPrimNode > INTRINSICS ()
static void reset ()
Public Attributes
final String _name
Static Protected Member Functions
static void add_libs (Ary< NewPrimNode > INTRINSICS)
Package Functions
String bal_close ()
TypeStr dead_type ()
TypeObj valueobj ()
Static Package Functions
[static initializer]
Package Attributes
final int _op_prec
final boolean _reads
final TypeFunSig _sig
Static Private Attributes
static final Ary< NewPrimNode > INTRINSICS
Detailed Description
Definition at line 52 of file NewStrNode.java.
Constructor & Destructor Documentation
ConvertF64Str()
com.cliffc.aa.node.NewStrNode.ConvertF64Str.ConvertF64Str ()
Definition at line 53 of file NewStrNode.java.
 { super(TypeStr.STR,"str",false,-1,Type.CTRL,TypeMem.ALLMEM,null,TypeFlt.FLT64); }
References com.cliffc.aa.type.TypeMem.ALLMEM, com.cliffc.aa.type.Type< T extends Type< T >.CTRL, com.cliffc.aa.type.TypeFlt.FLT64, and com.cliffc.aa.type.TypeStr.STR.
Member Function Documentation
[static initializer]()
com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.[static initializer] static package inherited
add_libs()
static void com.cliffc.aa.node.NewStrNode.add_libs (Ary< NewPrimNode > INTRINSICS) static protected inherited
Definition at line 25 of file NewStrNode.java.
{
     INTRINSICS.push(new ConvertI64Str());
     INTRINSICS.push(new ConvertF64Str());
     INTRINSICS.push(new AddStrStr());
   }
References com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeStr >.INTRINSICS.
Referenced by com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.INTRINSICS().
as_fun()
FunPtrNode com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.as_fun (GVNGCM gvn) inherited
Definition at line 198 of file NewNode.java.
{
       try(GVNGCM.Build<FunPtrNode> X = gvn.new Build<>()) {
         assert in(0)==null && _uses._len==0;
         FunNode  fun = ( FunNode) X.xform(new  FunNode(this).add_def(Env.ALL_CTRL));
         ParmNode rpc = (ParmNode) X.xform(new ParmNode(0,"rpc",fun,Env.ALL_CALL,null));
         Node memp= X.xform(new ParmNode(MEM_IDX,_sig._args[MEM_IDX],fun, TypeMem.MEM, Env.DEFMEM,null));
         fun._bal_close = bal_close();
         // Add input edges to the intrinsic
         add_def(_reads ? memp : null); // Memory  for the primitive in slot MEM_IDX
         add_def(null);                 // Closure for the primitive in slot DSP_IDX
         for( int i=ARG_IDX; i<_sig.nargs(); i++ ) // Args follow
           add_def( X.xform(new ParmNode(i,_sig._args[i],fun, (ConNode)Node.con(_sig.arg(i).simple_ptr()),null)));
         NewNode nnn = (NewNode)X.xform(this);
         Node mem = Env.DEFMEM.make_mem_proj(nnn,memp);
         Node ptr = X.xform(new ProjNode(nnn,REZ_IDX));
         RetNode ret = (RetNode)X.xform(new RetNode(fun,mem,ptr,rpc,fun));
         return (X._ret = new FunPtrNode(_name,ret));
       }
     }
bal_close()
String com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.bal_close () package inherited
Definition at line 184 of file NewNode.java.
 { return null; }
dead_type()
TypeStr com.cliffc.aa.node.NewStrNode.dead_type () package inherited
Definition at line 24 of file NewStrNode.java.
 { return TypeStr.XSTR; }
References com.cliffc.aa.type.TypeStr.XSTR.
INTRINSICS()
static Ary<NewPrimNode> com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.INTRINSICS () static inherited
Definition at line 189 of file NewNode.java.
{
       if( INTRINSICS.isEmpty() ) {
         NewAryNode.add_libs(INTRINSICS);
         NewStrNode.add_libs(INTRINSICS);
       }
       return INTRINSICS;
     }
live_use()
TypeMem com.cliffc.aa.node.NewStrNode.ConvertF64Str.live_use (GVNGCM.Mode opt_mode, Node def)
Definition at line 60 of file NewStrNode.java.
 { return TypeMem.ALIVE; }
References com.cliffc.aa.type.TypeMem.ALIVE.
reset()
static void com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.reset () static inherited
Definition at line 188 of file NewNode.java.
 { INTRINSICS.clear(); }
unify()
boolean com.cliffc.aa.node.NewStrNode.unify (boolean test) inherited
Definition at line 15 of file NewStrNode.java.
{
     // Self should always should be a TObj
     TV2 tvar = tvar();
     if( tvar.is_dead() ) return false;
     assert tvar.isa("Obj");
     // TODO: Structural unification on all fields
     return false;
   }
References com.cliffc.aa.tvar.TV2.is_dead(), and com.cliffc.aa.tvar.TV2.isa().
valueobj()
TypeObj com.cliffc.aa.node.NewStrNode.ConvertF64Str.valueobj () package
Definition at line 54 of file NewStrNode.java.
{
       Type t = val(3);
       if( t.above_center() || !(t instanceof TypeFlt) ) return t.oob(TypeStr.STR);
       if( !t.is_con() ) return TypeStr.STR;
       return TypeStr.make(false,Double.toString(t.getd()).intern());
     }
References com.cliffc.aa.type.Type< T extends Type< T >.above_center(), com.cliffc.aa.type.Type< T extends Type< T >.getd(), com.cliffc.aa.type.Type< T extends Type< T >.is_con(), com.cliffc.aa.type.TypeStr.make(), com.cliffc.aa.type.Type< T extends Type< T >.oob(), and com.cliffc.aa.type.TypeStr.STR.
Member Data Documentation
_name
final String com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >._name inherited
Definition at line 171 of file NewNode.java.
_op_prec
final int com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >._op_prec package inherited
Definition at line 174 of file NewNode.java.
_reads
final boolean com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >._reads package inherited
Definition at line 173 of file NewNode.java.
_sig
final TypeFunSig com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >._sig package inherited
Definition at line 172 of file NewNode.java.
INTRINSICS
final Ary<NewPrimNode> com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.INTRINSICS static private inherited
Definition at line 186 of file NewNode.java.
The documentation for this class was generated from the following file:
NewStrNode.java