aa: com.cliffc.aa.type.Type< T extends Type< T >.Pool Class Reference
com.cliffc.aa.type.Type< T extends Type< T >.Pool Class Reference
Package Functions
Pool (byte t, Type gold)
< T extends Type > T free (T t1, T t2)
< T extends Type > T malloc ()
Package Attributes
int _clone
int _free
int _pool
Private Attributes
final Ary< Type > _frees
final Type _gold
int _malloc
Detailed Description
Definition at line 283 of file Type.java.
Constructor & Destructor Documentation
Pool()
com.cliffc.aa.type.Type< T extends Type< T >.Pool.Pool (byte t, Type gold) package
Definition at line 287 of file Type.java.
{
       gold._type = t;
       _gold=gold;
       _frees= new Ary<>(new Type[1],0);
       POOLS[t] = this;
     }
References com.cliffc.aa.type.Type< T extends Type< T >._type, and com.cliffc.aa.type.Type< T extends Type< T >.POOLS.
Member Function Documentation
free()
<T extends Type> T com.cliffc.aa.type.Type< T extends Type< T >.Pool.free (T t1, T t2) package
Definition at line 297 of file Type.java.
{
       _frees.push(t1);
       _free++;
       return t2;
     }
References com.cliffc.aa.util.Ary< E >.push().
malloc()
<T extends Type> T com.cliffc.aa.type.Type< T extends Type< T >.Pool.malloc () package
Definition at line 293 of file Type.java.
{
       if( _frees.isEmpty() ) { _malloc++; _clone--; return (T)_gold.clone(); }
       else                   { _pool  ++; return (T)_frees.pop();  }
     }
References com.cliffc.aa.type.Type< T extends Type< T >.clone(), com.cliffc.aa.util.Ary< E >.isEmpty(), and com.cliffc.aa.util.Ary< E >.pop().
Member Data Documentation
_clone
int com.cliffc.aa.type.Type< T extends Type< T >.Pool._clone package
Definition at line 284 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >._set_name(), and com.cliffc.aa.type.Type< TypeFlt >.clone().
_free
int com.cliffc.aa.type.Type< T extends Type< T >.Pool._free package
Definition at line 284 of file Type.java.
_frees
final Ary<Type> com.cliffc.aa.type.Type< T extends Type< T >.Pool._frees private
Definition at line 285 of file Type.java.
_gold
final Type com.cliffc.aa.type.Type< T extends Type< T >.Pool._gold private
Definition at line 286 of file Type.java.
_malloc
int com.cliffc.aa.type.Type< T extends Type< T >.Pool._malloc private
Definition at line 284 of file Type.java.
_pool
int com.cliffc.aa.type.Type< T extends Type< T >.Pool._pool package
Definition at line 284 of file Type.java.
The documentation for this class was generated from the following file:
Type.java