aa: com.cliffc.aa.HM.HM3.VStack Class Reference
com.cliffc.aa.HM.HM3.VStack Class Reference
Classes
class Iter
Public Member Functions
Iterator< HMVar > iterator ()
String toString ()
Package Functions
VStack (VStack par, HMVar nongen)
SB str (SB sb)
Package Attributes
final HMVar _nongen
final VStack _par
Detailed Description
Definition at line 83 of file HM3.java.
Constructor & Destructor Documentation
VStack()
com.cliffc.aa.HM.HM3.VStack.VStack (VStack par, HMVar nongen) package
Definition at line 86 of file HM3.java.
 { _par=par; _nongen=nongen; }
References com.cliffc.aa.HM.HM3.VStack._nongen, and com.cliffc.aa.HM.HM3.VStack._par.
Member Function Documentation
iterator()
Iterator<HMVar> com.cliffc.aa.HM.HM3.VStack.iterator ()
Definition at line 93 of file HM3.java.
 { return new Iter(); }
str()
SB com.cliffc.aa.HM.HM3.VStack.str (SB sb) package
Definition at line 88 of file HM3.java.
                   {
       _nongen._str(sb,new VBitSet(),false);
       if( _par!=null ) _par.str(sb.p(" >> "));
       return sb;
     }
References com.cliffc.aa.HM.HM3.VStack._nongen, com.cliffc.aa.HM.HM3.VStack._par, com.cliffc.aa.HM.HM3.HMVar._str(), com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM3.VStack.str().
Referenced by com.cliffc.aa.HM.HM3.VStack.str(), and com.cliffc.aa.HM.HM3.VStack.toString().
toString()
String com.cliffc.aa.HM.HM3.VStack.toString ()
Definition at line 87 of file HM3.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM3.VStack.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_nongen
final HMVar com.cliffc.aa.HM.HM3.VStack._nongen package
Definition at line 85 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.VStack.Iter.next(), com.cliffc.aa.HM.HM3.VStack.str(), and com.cliffc.aa.HM.HM3.VStack.VStack().
_par
final VStack com.cliffc.aa.HM.HM3.VStack._par package
Definition at line 84 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.VStack.Iter.next(), com.cliffc.aa.HM.HM3.VStack.str(), and com.cliffc.aa.HM.HM3.VStack.VStack().
The documentation for this class was generated from the following file:
HM3.java