aa: com.cliffc.aa.HM.HM3.Lambda Class Reference
com.cliffc.aa.HM.HM3.Lambda Class Reference
Public Member Functions
String toString ()
Protected Member Functions
final void add_work (Worklist work)
Package Functions
Lambda (String arg0, Syntax body)
final void add_neighbors (Worklist work)
final boolean all_kids_ready ()
boolean check_progress (Worklist work)
void get_ids (VStack vstk, Worklist work)
HMType hm (Worklist work)
boolean progress ()
Package Attributes
final String _arg0
HMType _hm
Syntax[] _kids
Syntax _par
Private Member Functions
Syntax body ()
Detailed Description
Definition at line 189 of file HM3.java.
Constructor & Destructor Documentation
Lambda()
com.cliffc.aa.HM.HM3.Lambda.Lambda (String arg0, Syntax body) package
Definition at line 191 of file HM3.java.
 { _kids=new Syntax[]{body}; body._par=this; _arg0=arg0; }
References com.cliffc.aa.HM.HM3.Lambda._arg0, com.cliffc.aa.HM.HM3.Syntax._kids, com.cliffc.aa.HM.HM3.Syntax._par, and com.cliffc.aa.HM.HM3.Lambda.body().
Member Function Documentation
add_neighbors()
final void com.cliffc.aa.HM.HM3.Syntax.add_neighbors (Worklist work) package inherited
Definition at line 128 of file HM3.java.
{
       if( _par!=null ) _par.add_work(work);
       if( _kids!=null )
         for( Syntax kid : _kids )
           kid.add_work(work);
     }
References com.cliffc.aa.HM.HM3.Syntax._kids, com.cliffc.aa.HM.HM3.Syntax._par, and com.cliffc.aa.HM.HM3.Syntax.add_work().
Referenced by com.cliffc.aa.HM.HM3.hm().
add_work()
final void com.cliffc.aa.HM.HM3.Syntax.add_work (Worklist work) protected inherited
Definition at line 126 of file HM3.java.
 {  if( all_kids_ready() ) work.push(this);  }
References com.cliffc.aa.HM.HM3.Syntax.all_kids_ready(), and com.cliffc.aa.HM.HM3.Worklist.push().
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.HM.HM3.Con.get_ids(), and com.cliffc.aa.HM.HM3.Ident.get_ids().
all_kids_ready()
final boolean com.cliffc.aa.HM.HM3.Syntax.all_kids_ready () package inherited
Definition at line 135 of file HM3.java.
{
       if( _kids==null ) return true;
       for( Syntax kid : _kids ) if( kid._hm==null ) return false;
       return true;
     }
References com.cliffc.aa.HM.HM3.Syntax._kids.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_work(), and com.cliffc.aa.HM.HM3.Syntax.check_progress().
body()
Syntax com.cliffc.aa.HM.HM3.Lambda.body () private
Definition at line 192 of file HM3.java.
 { return _kids[0]; }
References com.cliffc.aa.HM.HM3.Syntax._kids.
Referenced by com.cliffc.aa.HM.HM3.Lambda.get_ids(), com.cliffc.aa.HM.HM3.Lambda.hm(), com.cliffc.aa.HM.HM3.Lambda.Lambda(), com.cliffc.aa.HM.HM3.Lambda.progress(), and com.cliffc.aa.HM.HM3.Lambda.toString().
check_progress()
boolean com.cliffc.aa.HM.HM3.Syntax.check_progress (Worklist work) package inherited
Definition at line 144 of file HM3.java.
{
       if( all_kids_ready() ) // If kids are not ready, then cannot compute hm() so not on worklist
         if( _hm==null || progress() ) // Progress is possible
           if( !work.has(this) )       // Not on worklist?
             return false;             // Fails check
       if( _kids!=null )               // For all kids
         for( Syntax kid : _kids )
           if( !kid.check_progress(work) ) // Recursively check nodes that can make progress on worklist
             return false;
       return true;
     }
References com.cliffc.aa.HM.HM3.Syntax._hm, com.cliffc.aa.HM.HM3.Syntax._kids, com.cliffc.aa.HM.HM3.Syntax.all_kids_ready(), com.cliffc.aa.HM.HM3.Worklist.has(), and com.cliffc.aa.HM.HM3.Syntax.progress().
Referenced by com.cliffc.aa.HM.HM3.hm().
get_ids()
void com.cliffc.aa.HM.HM3.Lambda.get_ids (VStack vstk, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM3.Syntax.
Definition at line 211 of file HM3.java.
{
       HMVar var = new HMVar();
       ENV.put(_arg0, var);
       body().get_ids(new VStack(vstk,var),work);
     }
References com.cliffc.aa.HM.HM3.Lambda._arg0, com.cliffc.aa.HM.HM3.Lambda.body(), com.cliffc.aa.HM.HM3.ENV, and com.cliffc.aa.HM.HM3.Syntax.get_ids().
hm()
HMType com.cliffc.aa.HM.HM3.Lambda.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM3.Syntax.
Definition at line 194 of file HM3.java.
{
       if( _hm!=null && !progress() ) return null;
       HMType tnew = ENV.get(_arg0).find();
       HMType trez = body()._hm.find();
       return Oper.fun(tnew,trez);
     }
References com.cliffc.aa.HM.HM3.Lambda._arg0, com.cliffc.aa.HM.HM3.Syntax._hm, com.cliffc.aa.HM.HM3.Lambda.body(), com.cliffc.aa.HM.HM3.ENV, com.cliffc.aa.HM.HM3.HMType.find(), com.cliffc.aa.HM.HM3.Oper.fun(), and com.cliffc.aa.HM.HM3.Lambda.progress().
progress()
boolean com.cliffc.aa.HM.HM3.Lambda.progress () package
Reimplemented from com.cliffc.aa.HM.HM3.Syntax.
Definition at line 200 of file HM3.java.
{
       HMType tnew = ENV.get(_arg0).find();
       HMType trez = body()._hm.find();
       // Progress if _hm is NOT a Oper.fun, OR
       // !_hm[0].eq(tnew) || _hm[1].eq(trez);
       if( !(_hm instanceof Oper) ) return true;
       if( !((Oper)_hm)._name.equals("->") ) return true;
       HMType fcn = ((Oper)_hm)._args[0].find();
       HMType rez = ((Oper)_hm)._args[1].find();
       return !fcn.eq(tnew) || !rez.eq(trez);
     }
References com.cliffc.aa.HM.HM3.Lambda._arg0, com.cliffc.aa.HM.HM3.Syntax._hm, com.cliffc.aa.HM.HM3.Lambda.body(), com.cliffc.aa.HM.HM3.ENV, com.cliffc.aa.HM.HM3.HMType.eq(), and com.cliffc.aa.HM.HM3.HMType.find().
Referenced by com.cliffc.aa.HM.HM3.Lambda.hm().
toString()
String com.cliffc.aa.HM.HM3.Lambda.toString ()
Definition at line 193 of file HM3.java.
 { return "{ "+_arg0+" -> "+body()+" }"; }
References com.cliffc.aa.HM.HM3.Lambda._arg0, and com.cliffc.aa.HM.HM3.Lambda.body().
Member Data Documentation
_arg0
final String com.cliffc.aa.HM.HM3.Lambda._arg0 package
Definition at line 190 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Lambda.get_ids(), com.cliffc.aa.HM.HM3.Lambda.hm(), com.cliffc.aa.HM.HM3.Lambda.Lambda(), com.cliffc.aa.HM.HM3.Lambda.progress(), and com.cliffc.aa.HM.HM3.Lambda.toString().
_hm
HMType com.cliffc.aa.HM.HM3.Syntax._hm package inherited
Definition at line 118 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Syntax.check_progress(), com.cliffc.aa.HM.HM3.hm(), com.cliffc.aa.HM.HM3.Con.hm(), com.cliffc.aa.HM.HM3.Ident.hm(), com.cliffc.aa.HM.HM3.Lambda.hm(), com.cliffc.aa.HM.HM3.Let.hm(), com.cliffc.aa.HM.HM3.Apply.hm(), com.cliffc.aa.HM.HM3.Lambda.progress(), com.cliffc.aa.HM.HM3.Let.progress(), and com.cliffc.aa.HM.HM3.Apply.progress().
_kids
Syntax [] com.cliffc.aa.HM.HM3.Syntax._kids package inherited
Definition at line 117 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.HM.HM3.Syntax.all_kids_ready(), com.cliffc.aa.HM.HM3.Apply.Apply(), com.cliffc.aa.HM.HM3.Apply.arg(), com.cliffc.aa.HM.HM3.Lambda.body(), com.cliffc.aa.HM.HM3.Let.body(), com.cliffc.aa.HM.HM3.Syntax.check_progress(), com.cliffc.aa.HM.HM3.Apply.fun(), com.cliffc.aa.HM.HM3.Lambda.Lambda(), com.cliffc.aa.HM.HM3.Let.Let(), and com.cliffc.aa.HM.HM3.Let.use().
_par
Syntax com.cliffc.aa.HM.HM3.Syntax._par package inherited
Definition at line 116 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.HM.HM3.Apply.Apply(), com.cliffc.aa.HM.HM3.Lambda.Lambda(), and com.cliffc.aa.HM.HM3.Let.Let().
The documentation for this class was generated from the following file:
HM3.java