aa: com.cliffc.aa.AA Class Reference
com.cliffc.aa.AA Class Reference abstract
an implementation of language AA
Static Public Member Functions
static Node f (int uid)
static void main (String[] args)
static String p ()
static< T > T p (T x, String s)
static String plive ()
static RuntimeException unimpl ()
static RuntimeException unimpl (String msg)
Static Public Attributes
static final int ARG_IDX =3
static final int CTL_IDX =0
static boolean DEBUG = true
static final int DSP_IDX =2
static final int MEM_IDX =1
static final int REZ_IDX =2
static int UID =-1
Static Package Functions
[static initializer]
Static Private Attributes
static final AbstractBuildVersion ABV
Detailed Description
an implementation of language AA
Definition at line 9 of file AA.java.
Member Function Documentation
[static initializer]()
com.cliffc.aa.AA.[static initializer] static package
f()
static Node com.cliffc.aa.AA.f (int uid) static
Definition at line 42 of file AA.java.
 { return Env.START.find(uid); }        // Debugging hook
References com.cliffc.aa.Env.START.
main()
static void com.cliffc.aa.AA.main (String[] args) static
Definition at line 29 of file AA.java.
{
     System.out.println(ABV.toString());
     if( args.length > 0 ) System.out.println(Exec.go(Env.file_scope(Env.top_scope()),"args",String.join(" ",args))._t.toString());
     else REPL.go();
   }
References com.cliffc.aa.TypeEnv._t, com.cliffc.aa.Env.file_scope(), com.cliffc.aa.Exec.go(), com.cliffc.aa.REPL.go(), com.cliffc.aa.Env.top_scope(), com.cliffc.aa.AbstractBuildVersion.toString(), and com.cliffc.aa.type.Type< T extends Type< T >.toString().
p() [1/2]
static String com.cliffc.aa.AA.p () static
Definition at line 40 of file AA.java.
 { return Env.START.dumprpo(false,false); }  // Debugging hook
References com.cliffc.aa.Env.START.
p() [2/2]
static <T> T com.cliffc.aa.AA.p (T x, String s) static
Definition at line 35 of file AA.java.
{
     if( !AA.DEBUG ) return x;
     System.err.println(s);
     return x;
   }
References com.cliffc.aa.AA.DEBUG.
plive()
static String com.cliffc.aa.AA.plive () static
Definition at line 41 of file AA.java.
 { return Env.START.dumprpo(false,true ); }  // Debugging hook
References com.cliffc.aa.Env.START.
unimpl() [1/2]
static RuntimeException com.cliffc.aa.AA.unimpl () static
Definition at line 10 of file AA.java.
 { return unimpl("unimplemented"); }
References com.cliffc.aa.AA.unimpl().
Referenced by com.cliffc.aa.tvar.TV2._find_tvar(), com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.HM.HM4.T2._fresh_unify_impl(), com.cliffc.aa.HM.HM4.T2._unify(), com.cliffc.aa.node.PrimNode.ConvertStrStr.apply(), com.cliffc.aa.node.PrimNode.EQ_OOP.apply(), com.cliffc.aa.node.PrimNode.NE_OOP.apply(), com.cliffc.aa.node.PrimNode.Not.apply(), com.cliffc.aa.node.PrimNode.RandI64.apply(), com.cliffc.aa.node.PrimNode.Id.apply(), com.cliffc.aa.node.PrimNode.AndThen.apply(), com.cliffc.aa.node.PrimNode.OrElse.apply(), com.cliffc.aa.type.TypeStruct.ax_impl_ptr(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.TypeFunPtr.ax_meet_nil(), com.cliffc.aa.node.MemSplitNode.find_alias_index(), com.cliffc.aa.node.LoadNode.find_previous_store(), com.cliffc.aa.node.MemJoinNode.find_sese_head(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.IfNode.ideal_reduce(), com.cliffc.aa.node.UnresolvedNode.ideal_reduce(), com.cliffc.aa.type.TypeStruct.install_cyclic(), com.cliffc.aa.node.ThunkNode.is_copy(), com.cliffc.aa.node.RetNode.is_copy(), com.cliffc.aa.type.TypeFlt.isBitShape(), com.cliffc.aa.type.TypeInt.isBitShape(), com.cliffc.aa.type.Type< TypeFlt >.isBitShape(), com.cliffc.aa.node.ThretNode.live_use(), com.cliffc.aa.node.NewStrNode.ConStr.live_use(), com.cliffc.aa.node.StoreNode.live_use(), com.cliffc.aa.type.TypeMem.remove(), com.cliffc.aa.tvar.TV2.unify_alias_fld(), com.cliffc.aa.AA.unimpl(), com.cliffc.aa.HM.HM4.T2.union(), com.cliffc.aa.node.UnresolvedNode.value(), com.cliffc.aa.node.IfNode.value(), and com.cliffc.aa.node.NewStrNode.AddStrStr.valueobj().
unimpl() [2/2]
static RuntimeException com.cliffc.aa.AA.unimpl (String msg) static
Definition at line 11 of file AA.java.
 { throw new RuntimeException(msg); }
Member Data Documentation
ABV
final AbstractBuildVersion com.cliffc.aa.AA.ABV static private
Definition at line 19 of file AA.java.
ARG_IDX
final int com.cliffc.aa.AA.ARG_IDX =3 static
Definition at line 17 of file AA.java.
Referenced by com.cliffc.aa.node.UnresolvedNode.add_def_unresolved().
CTL_IDX
final int com.cliffc.aa.AA.CTL_IDX =0 static
Definition at line 13 of file AA.java.
Referenced by com.cliffc.aa.node.CProjNode.CProjNode().
DEBUG
boolean com.cliffc.aa.AA.DEBUG = true static
Definition at line 34 of file AA.java.
Referenced by com.cliffc.aa.AA.p().
DSP_IDX
final int com.cliffc.aa.AA.DSP_IDX =2 static
Definition at line 15 of file AA.java.
MEM_IDX
final int com.cliffc.aa.AA.MEM_IDX =1 static
Definition at line 14 of file AA.java.
REZ_IDX
final int com.cliffc.aa.AA.REZ_IDX =2 static
Definition at line 16 of file AA.java.
Referenced by com.cliffc.aa.node.PrimNode.as_fun(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.PrimNode.AndThen.ideal_grow(), com.cliffc.aa.node.PrimNode.OrElse.ideal_grow(), and com.cliffc.aa.Env.init().
UID
int com.cliffc.aa.AA.UID =-1 static
Definition at line 43 of file AA.java.
Referenced by com.cliffc.aa.node.Node.newuid().
The documentation for this class was generated from the following file:
AA.java