aa: com.cliffc.aa.HM.HM6.Worklist Class Reference
com.cliffc.aa.HM.HM6.Worklist Class Reference
Public Member Functions
void addAll (Ary<? extends Syntax > ss)
boolean has (Syntax s)
int len ()
Syntax pop ()
void push (Syntax s)
String toString ()
Public Attributes
int _cnt
Private Attributes
final Ary< Syntax > _ary = new Ary<>(Syntax.class)
final HashSet< Syntax > _work = new HashSet<>()
Detailed Description
Definition at line 175 of file HM6.java.
Member Function Documentation
addAll()
void com.cliffc.aa.HM.HM6.Worklist.addAll (Ary<? extends Syntax > ss)
Definition at line 184 of file HM6.java.
 { if( ss != null ) for( Syntax s : ss ) push(s); }
References com.cliffc.aa.HM.HM6.Worklist.push().
Referenced by com.cliffc.aa.HM.HM6.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM6.Lambda.add_occurs(), com.cliffc.aa.HM.HM6.Lambda2.add_occurs(), and com.cliffc.aa.HM.HM6.Let.add_occurs().
has()
boolean com.cliffc.aa.HM.HM6.Worklist.has (Syntax s)
Definition at line 183 of file HM6.java.
 { return _work.contains(s); }
References com.cliffc.aa.HM.HM6.Worklist._work.
Referenced by com.cliffc.aa.HM.HM6.Syntax.more_work_impl().
len()
int com.cliffc.aa.HM.HM6.Worklist.len ()
Definition at line 179 of file HM6.java.
 { return _ary.len(); }
References com.cliffc.aa.HM.HM6.Worklist._ary.
Referenced by com.cliffc.aa.HM.HM6.hm().
pop()
Syntax com.cliffc.aa.HM.HM6.Worklist.pop ()
Definition at line 182 of file HM6.java.
 { Syntax s = _ary.del(  _cnt++%_ary._len); _work.remove(s); return s; }
References com.cliffc.aa.HM.HM6.Worklist._ary, com.cliffc.aa.HM.HM6.Worklist._cnt, and com.cliffc.aa.HM.HM6.Worklist._work.
Referenced by com.cliffc.aa.HM.HM6.hm().
push()
void com.cliffc.aa.HM.HM6.Worklist.push (Syntax s)
Definition at line 180 of file HM6.java.
 { if( !_work.contains(s) ) _work.add(_ary.push(s)); }
References com.cliffc.aa.HM.HM6.Worklist._ary, and com.cliffc.aa.HM.HM6.Worklist._work.
Referenced by com.cliffc.aa.HM.HM6.Lambda.add_kids(), com.cliffc.aa.HM.HM6.Lambda2.add_kids(), com.cliffc.aa.HM.HM6.Let.add_kids(), com.cliffc.aa.HM.HM6.Apply.add_kids(), com.cliffc.aa.HM.HM6.Worklist.addAll(), com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM6.Syntax.prep_tree_impl().
toString()
String com.cliffc.aa.HM.HM6.Worklist.toString ()
Definition at line 185 of file HM6.java.
 { return _ary.toString(); }
References com.cliffc.aa.HM.HM6.Worklist._ary.
Member Data Documentation
_ary
final Ary<Syntax> com.cliffc.aa.HM.HM6.Worklist._ary = new Ary<>(Syntax.class) private
Definition at line 177 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.Worklist.len(), com.cliffc.aa.HM.HM6.Worklist.pop(), com.cliffc.aa.HM.HM6.Worklist.push(), and com.cliffc.aa.HM.HM6.Worklist.toString().
_cnt
int com.cliffc.aa.HM.HM6.Worklist._cnt
Definition at line 176 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.Worklist.pop().
_work
final HashSet<Syntax> com.cliffc.aa.HM.HM6.Worklist._work = new HashSet<>() private
Definition at line 178 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.Worklist.has(), com.cliffc.aa.HM.HM6.Worklist.pop(), and com.cliffc.aa.HM.HM6.Worklist.push().
The documentation for this class was generated from the following file:
HM6.java