aa: com.cliffc.aa.node.NewStrNode.AddStrStr Class Reference
com.cliffc.aa.node.NewStrNode.AddStrStr Class Reference
Public Member Functions
AddStrStr ()
void add_flow_use_extra (Node chg)
FunPtrNode as_fun (GVNGCM gvn)
TypeMem live_use (GVNGCM.Mode opt_mode, Node def)
byte op_prec ()
boolean unify (boolean test)
Type value (GVNGCM.Mode opt_mode)
Static Public Member Functions
static Ary< NewPrimNode > INTRINSICS ()
static void reset ()
Public Attributes
final String _name
Static Protected Member Functions
static void add_libs (Ary< NewPrimNode > INTRINSICS)
Package Functions
TypeTuple _value (TypeObj tobj)
String bal_close ()
TypeStr dead_type ()
TypeObj valueobj ()
Static Package Functions
[static initializer]
Package Attributes
final int _op_prec
final boolean _reads
final TypeFunSig _sig
Static Private Attributes
static final Ary< NewPrimNode > INTRINSICS
static int OP_PREC =7
Detailed Description
Definition at line 67 of file NewStrNode.java.
Constructor & Destructor Documentation
AddStrStr()
com.cliffc.aa.node.NewStrNode.AddStrStr.AddStrStr ()
Definition at line 69 of file NewStrNode.java.
 { super(TypeStr.STR,"+",true,OP_PREC,Type.CTRL,TypeMem.MEM_STR,null,TypeMemPtr.STR0,TypeMemPtr.STR0); }
References com.cliffc.aa.type.Type< T extends Type< T >.CTRL, com.cliffc.aa.type.TypeMem.MEM_STR, com.cliffc.aa.node.NewStrNode.AddStrStr.OP_PREC, com.cliffc.aa.type.TypeStr.STR, and com.cliffc.aa.type.TypeMemPtr.STR0.
Member Function Documentation
[static initializer]()
com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.[static initializer] static package inherited
_value()
TypeTuple com.cliffc.aa.node.NewStrNode.AddStrStr._value (TypeObj tobj) package
Definition at line 91 of file NewStrNode.java.
 { return TypeTuple.make(Type.CTRL,tobj,_tptr); }
References com.cliffc.aa.type.Type< T extends Type< T >.CTRL, and com.cliffc.aa.type.TypeTuple.make().
Referenced by com.cliffc.aa.node.NewStrNode.AddStrStr.value().
add_flow_use_extra()
void com.cliffc.aa.node.NewStrNode.AddStrStr.add_flow_use_extra (Node chg)
Definition at line 108 of file NewStrNode.java.
{
       if( chg==in(3) || chg==in(4) ) Env.GVN.add_flow(in(1));  // Address into a Load changes, the Memory can be more alive.
     }
References com.cliffc.aa.GVNGCM.add_flow(), and com.cliffc.aa.Env.GVN.
add_libs()
static void com.cliffc.aa.node.NewStrNode.add_libs (Ary< NewPrimNode > INTRINSICS) static protected inherited
Definition at line 25 of file NewStrNode.java.
{
     INTRINSICS.push(new ConvertI64Str());
     INTRINSICS.push(new ConvertF64Str());
     INTRINSICS.push(new AddStrStr());
   }
References com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeStr >.INTRINSICS.
Referenced by com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.INTRINSICS().
as_fun()
FunPtrNode com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.as_fun (GVNGCM gvn) inherited
Definition at line 198 of file NewNode.java.
{
       try(GVNGCM.Build<FunPtrNode> X = gvn.new Build<>()) {
         assert in(0)==null && _uses._len==0;
         FunNode  fun = ( FunNode) X.xform(new  FunNode(this).add_def(Env.ALL_CTRL));
         ParmNode rpc = (ParmNode) X.xform(new ParmNode(0,"rpc",fun,Env.ALL_CALL,null));
         Node memp= X.xform(new ParmNode(MEM_IDX,_sig._args[MEM_IDX],fun, TypeMem.MEM, Env.DEFMEM,null));
         fun._bal_close = bal_close();
         // Add input edges to the intrinsic
         add_def(_reads ? memp : null); // Memory  for the primitive in slot MEM_IDX
         add_def(null);                 // Closure for the primitive in slot DSP_IDX
         for( int i=ARG_IDX; i<_sig.nargs(); i++ ) // Args follow
           add_def( X.xform(new ParmNode(i,_sig._args[i],fun, (ConNode)Node.con(_sig.arg(i).simple_ptr()),null)));
         NewNode nnn = (NewNode)X.xform(this);
         Node mem = Env.DEFMEM.make_mem_proj(nnn,memp);
         Node ptr = X.xform(new ProjNode(nnn,REZ_IDX));
         RetNode ret = (RetNode)X.xform(new RetNode(fun,mem,ptr,rpc,fun));
         return (X._ret = new FunPtrNode(_name,ret));
       }
     }
bal_close()
String com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.bal_close () package inherited
Definition at line 184 of file NewNode.java.
 { return null; }
dead_type()
TypeStr com.cliffc.aa.node.NewStrNode.dead_type () package inherited
Definition at line 24 of file NewStrNode.java.
 { return TypeStr.XSTR; }
References com.cliffc.aa.type.TypeStr.XSTR.
INTRINSICS()
static Ary<NewPrimNode> com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.INTRINSICS () static inherited
Definition at line 189 of file NewNode.java.
{
       if( INTRINSICS.isEmpty() ) {
         NewAryNode.add_libs(INTRINSICS);
         NewStrNode.add_libs(INTRINSICS);
       }
       return INTRINSICS;
     }
live_use()
TypeMem com.cliffc.aa.node.NewStrNode.AddStrStr.live_use (GVNGCM.Mode opt_mode, Node def)
Definition at line 94 of file NewStrNode.java.
{
       if( def==in(3) || def==in(4) ) return TypeMem.ALIVE;
       assert def==in(1);
       // Memory for aliases is alive, as-if a READ/LOAD
       Type tmem = val(1);
       Type tptr0= val(3);
       Type tptr1= val(4);
       if( !(tmem  instanceof TypeMem   ) ) return tmem .oob(TypeMem.ALLMEM); // Not a memory?
       if( !(tptr0 instanceof TypeMemPtr) ) return tptr0.oob(TypeMem.ALLMEM); // Not a pointer?
       if( !(tptr1 instanceof TypeMemPtr) ) return tptr1.oob(TypeMem.ALLMEM); // Not a pointer?
       TypeMem esc0 = ((TypeMem)tmem).remove_no_escapes(((TypeMemPtr)tptr0)._aliases,"",Type.SCALAR);
       TypeMem esc1 = ((TypeMem)tmem).remove_no_escapes(((TypeMemPtr)tptr1)._aliases,"",Type.SCALAR);
       return (TypeMem)esc0.meet(esc1);
     }
References com.cliffc.aa.type.TypeMem.ALIVE, com.cliffc.aa.type.TypeMem.ALLMEM, com.cliffc.aa.type.Type< T extends Type< T >.meet(), com.cliffc.aa.type.Type< T extends Type< T >.oob(), com.cliffc.aa.type.TypeMem.remove_no_escapes(), and com.cliffc.aa.type.Type< T extends Type< T >.SCALAR.
op_prec()
byte com.cliffc.aa.node.NewStrNode.AddStrStr.op_prec ()
Definition at line 93 of file NewStrNode.java.
 { return (byte)OP_PREC; }
References com.cliffc.aa.node.NewStrNode.AddStrStr.OP_PREC.
reset()
static void com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.reset () static inherited
Definition at line 188 of file NewNode.java.
 { INTRINSICS.clear(); }
unify()
boolean com.cliffc.aa.node.NewStrNode.unify (boolean test) inherited
Definition at line 15 of file NewStrNode.java.
{
     // Self should always should be a TObj
     TV2 tvar = tvar();
     if( tvar.is_dead() ) return false;
     assert tvar.isa("Obj");
     // TODO: Structural unification on all fields
     return false;
   }
References com.cliffc.aa.tvar.TV2.is_dead(), and com.cliffc.aa.tvar.TV2.isa().
value()
Type com.cliffc.aa.node.NewStrNode.AddStrStr.value (GVNGCM.Mode opt_mode)
Definition at line 70 of file NewStrNode.java.
{
       if( is_unused() ) return Type.ANY;
       Type m   = val(1);
       Type sp0 = val(3);
       Type sp1 = val(4);
       if( !(m instanceof TypeMem)   ) return m.oob();
       if( sp0==Type.XNIL && sp1==Type.XNIL ) return TypeTuple.make(TypeObj.UNUSED,Type.XNIL);
       if( !sp0.isa(TypeMemPtr.STR0) ) return _value(TypeStr.STR);
       if( !sp1.isa(TypeMemPtr.STR0) ) return _value(TypeStr.STR);
       if( sp0.above_center() || sp1.above_center() ) return Type.ANY;
       TypeMem mem = (TypeMem)m;
       TypeObj s0 = sp0==Type.XNIL ? TypeObj.UNUSED : mem.ld((TypeMemPtr)sp0);
       TypeObj s1 = sp1==Type.XNIL ? TypeObj.UNUSED : mem.ld((TypeMemPtr)sp1);
       if( sp0==Type.XNIL ) return _value(s1);
       if( sp1==Type.XNIL ) return _value(s0);
       if( !(s0 instanceof TypeStr) || !(s1 instanceof TypeStr) ) return _value(TypeStr.STR);
       TypeStr str0 = (TypeStr)s0;
       TypeStr str1 = (TypeStr)s1;
       if( !str0.is_con() || !str1.is_con() ) return _value(TypeStr.STR);
       return _value(TypeStr.make(false,(str0.getstr()+str1.getstr()).intern()));
     }
References com.cliffc.aa.node.NewStrNode.AddStrStr._value(), com.cliffc.aa.type.Type< T extends Type< T >.above_center(), com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.type.TypeStr.getstr(), com.cliffc.aa.type.TypeStr.is_con(), com.cliffc.aa.type.Type< T extends Type< T >.isa(), com.cliffc.aa.type.TypeMem.ld(), com.cliffc.aa.type.TypeStr.make(), com.cliffc.aa.type.TypeTuple.make(), com.cliffc.aa.type.Type< T extends Type< T >.oob(), com.cliffc.aa.type.TypeStr.STR, com.cliffc.aa.type.TypeMemPtr.STR0, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED, and com.cliffc.aa.type.Type< T extends Type< T >.XNIL.
valueobj()
TypeObj com.cliffc.aa.node.NewStrNode.AddStrStr.valueobj () package
Definition at line 92 of file NewStrNode.java.
 { throw com.cliffc.aa.AA.unimpl(); }
References com.cliffc.aa.AA.unimpl().
Member Data Documentation
_name
final String com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >._name inherited
Definition at line 171 of file NewNode.java.
_op_prec
final int com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >._op_prec package inherited
Definition at line 174 of file NewNode.java.
_reads
final boolean com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >._reads package inherited
Definition at line 173 of file NewNode.java.
_sig
final TypeFunSig com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >._sig package inherited
Definition at line 172 of file NewNode.java.
INTRINSICS
final Ary<NewPrimNode> com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.INTRINSICS static private inherited
Definition at line 186 of file NewNode.java.
OP_PREC
int com.cliffc.aa.node.NewStrNode.AddStrStr.OP_PREC =7 static private
Definition at line 68 of file NewStrNode.java.
Referenced by com.cliffc.aa.node.NewStrNode.AddStrStr.AddStrStr(), and com.cliffc.aa.node.NewStrNode.AddStrStr.op_prec().
The documentation for this class was generated from the following file:
NewStrNode.java