aa: com.cliffc.aa.HM.HM9.Let Class Reference
com.cliffc.aa.HM.HM9.Let Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Let (String arg0, Syntax def, Syntax body)
void add_hm_work (Worklist work)
void add_val_work (Syntax child, Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
Type val (Worklist work)
Package Attributes
final String _arg0
final Syntax _body
final Syntax _def
Type _flow
T2 _hmt
VStack _nongen
Syntax _par
T2 _targ
Detailed Description
Definition at line 543 of file HM9.java.
Constructor & Destructor Documentation
Let()
com.cliffc.aa.HM.HM9.Let.Let (String arg0, Syntax def, Syntax body) package
Definition at line 547 of file HM9.java.
 { _arg0=arg0; _body=body; _def=def; _targ=T2.make_leaf(); }
References com.cliffc.aa.HM.HM9.Let._arg0, com.cliffc.aa.HM.HM9.Let._body, com.cliffc.aa.HM.HM9.Let._def, com.cliffc.aa.HM.HM9.Let._targ, and com.cliffc.aa.HM.HM9.T2.make_leaf().
Member Function Documentation
add_hm_work()
void com.cliffc.aa.HM.HM9.Let.add_hm_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 552 of file HM9.java.
{
       work.push(_par);
       work.push(_body);
       work.push(_def);
       work.addAll(_def.find()._deps);
     }
References com.cliffc.aa.HM.HM9.Let._body, com.cliffc.aa.HM.HM9.Let._def, com.cliffc.aa.HM.HM9.T2._deps, com.cliffc.aa.HM.HM9.Syntax._par, com.cliffc.aa.HM.HM9.Worklist.addAll(), com.cliffc.aa.HM.HM9.Syntax.find(), and com.cliffc.aa.HM.HM9.Worklist.push().
add_val_work()
void com.cliffc.aa.HM.HM9.Let.add_val_work (Syntax child, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 559 of file HM9.java.
{
       if( child==_def )
         work.addAll(_def.find()._deps);
     }
References com.cliffc.aa.HM.HM9.Let._def, com.cliffc.aa.HM.HM9.T2._deps, com.cliffc.aa.HM.HM9.Worklist.addAll(), and com.cliffc.aa.HM.HM9.Syntax.find().
debug_find()
T2 com.cliffc.aa.HM.HM9.Syntax.debug_find () package inherited
Definition at line 329 of file HM9.java.
 { return _hmt.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM9.Syntax._hmt, and com.cliffc.aa.HM.HM9.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM9.hm().
find()
T2 com.cliffc.aa.HM.HM9.Syntax.find () package inherited
Definition at line 325 of file HM9.java.
               {                 // U-F find
       T2 t = _hmt.find();
       return t== _hmt ? t : (_hmt =t);
     }
References com.cliffc.aa.HM.HM9.Syntax._hmt, and com.cliffc.aa.HM.HM9.T2.find().
Referenced by com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_val_work(), com.cliffc.aa.HM.HM9.Let.add_val_work(), com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Ident.hm(), com.cliffc.aa.HM.HM9.Lambda.hm(), com.cliffc.aa.HM.HM9.Apply.hm(), com.cliffc.aa.HM.HM9.Root.hm(), com.cliffc.aa.HM.HM9.Struct.hm(), com.cliffc.aa.HM.HM9.Field.hm(), com.cliffc.aa.HM.HM9.PrimSyn.hm(), com.cliffc.aa.HM.HM9.If.hm(), com.cliffc.aa.HM.HM9.NotNil.hm(), com.cliffc.aa.HM.HM9.Apply.is_if_nil(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.NotNil.prep_tree(), com.cliffc.aa.HM.HM9.Apply.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
hm()
boolean com.cliffc.aa.HM.HM9.Let.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 551 of file HM9.java.
 { return false;  }
more_work()
boolean com.cliffc.aa.HM.HM9.Let.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 575 of file HM9.java.
{
       if( !more_work_impl(work) ) return false;
       return _body.more_work(work) && _def.more_work(work);
     }
References com.cliffc.aa.HM.HM9.Let._body, com.cliffc.aa.HM.HM9.Let._def, com.cliffc.aa.HM.HM9.Syntax.more_work(), and com.cliffc.aa.HM.HM9.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM9.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 362 of file HM9.java.
{
       if( work.has(this) ) return true;
       if( DO_HM && hm(null) )   // Any more HM work?
         return false;           // Found HM work not on worklist
       if( DO_GCP && val(null)!=_flow )
         return false;           // Found GCP work not on worklist
       return true;
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.DO_GCP, com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.Worklist.has(), com.cliffc.aa.HM.HM9.Syntax.hm(), and com.cliffc.aa.HM.HM9.Syntax.val().
Referenced by com.cliffc.aa.HM.HM9.Con.more_work(), com.cliffc.aa.HM.HM9.Ident.more_work(), com.cliffc.aa.HM.HM9.Lambda.more_work(), com.cliffc.aa.HM.HM9.Let.more_work(), com.cliffc.aa.HM.HM9.Apply.more_work(), com.cliffc.aa.HM.HM9.Struct.more_work(), com.cliffc.aa.HM.HM9.Field.more_work(), and com.cliffc.aa.HM.HM9.PrimSyn.more_work().
p()
String com.cliffc.aa.HM.HM9.Syntax.p () inherited
Definition at line 374 of file HM9.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM9.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM9.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 375 of file HM9.java.
{
       _hmt.get_dups(dups);
       VBitSet visit = new VBitSet();
       p1(sb.i());
       if( DO_HM  ) _hmt .str(sb.p(", HM="), visit,dups);
       if( DO_GCP ) _flow.str(sb.p(", CCP="),visit.clr(),null,false);
       sb.nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.util.VBitSet.clr(), com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM9.DO_GCP, com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM9.Syntax.p1(), com.cliffc.aa.HM.HM9.Syntax.p2(), com.cliffc.aa.type.Type< T extends Type< T >.str(), and com.cliffc.aa.HM.HM9.T2.str().
Referenced by com.cliffc.aa.HM.HM9.Syntax.p(), com.cliffc.aa.HM.HM9.Lambda.p2(), com.cliffc.aa.HM.HM9.Let.p2(), com.cliffc.aa.HM.HM9.Apply.p2(), com.cliffc.aa.HM.HM9.Struct.p2(), and com.cliffc.aa.HM.HM9.Field.p2().
p1()
SB com.cliffc.aa.HM.HM9.Let.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 549 of file HM9.java.
 { return sb.p(_arg0).p(" = ... ; ..."); }
References com.cliffc.aa.HM.HM9.Let._arg0, and com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM9.Let.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 550 of file HM9.java.
 { _def.p0(sb,dups); return _body.p0(sb,dups); }
References com.cliffc.aa.HM.HM9.Let._body, com.cliffc.aa.HM.HM9.Let._def, and com.cliffc.aa.HM.HM9.Syntax.p0().
prep_lookup_deps()
void com.cliffc.aa.HM.HM9.Let.prep_lookup_deps (Ident id) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 572 of file HM9.java.
{
       if( Util.eq(id._name,_arg0) ) _targ.push_update(id);
     }
References com.cliffc.aa.HM.HM9.Let._arg0, com.cliffc.aa.HM.HM9.Let._targ, com.cliffc.aa.util.Util.eq(), and com.cliffc.aa.HM.HM9.T2.push_update().
prep_tree()
int com.cliffc.aa.HM.HM9.Let.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 564 of file HM9.java.
{
       prep_tree_impl(par,nongen,work,_body._hmt);
       int cnt = _body.prep_tree(this,           nongen       ,work) +
                 _def .prep_tree(this,new VStack(nongen,_targ),work);
       _hmt = _body._hmt;            // Unify 'Let._hmt' with the '_body'
       _targ.unify(_def.find(),work);
       return cnt+1;
     }
References com.cliffc.aa.HM.HM9.Let._body, com.cliffc.aa.HM.HM9.Let._def, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.HM.HM9.Let._targ, com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.HM.HM9.Syntax.prep_tree(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM9.T2.unify().
prep_tree_impl()
final void com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 351 of file HM9.java.
{
       _par = par;
       _hmt = t;
       _flow= Type.XSCALAR;
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.HM.HM9.Syntax._nongen, com.cliffc.aa.HM.HM9.Syntax._par, com.cliffc.aa.HM.HM9.Worklist.push(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Referenced by com.cliffc.aa.HM.HM9.Con.prep_tree(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), com.cliffc.aa.HM.HM9.Lambda.prep_tree(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Apply.prep_tree(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.Field.prep_tree(), and com.cliffc.aa.HM.HM9.PrimSyn.prep_tree().
str()
SB com.cliffc.aa.HM.HM9.Let.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 548 of file HM9.java.
 { return _body.str(_def.str(sb.p(_arg0).p(" = ")).p("; ")); }
References com.cliffc.aa.HM.HM9.Let._arg0, com.cliffc.aa.HM.HM9.Let._body, com.cliffc.aa.HM.HM9.Let._def, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM9.Syntax.str().
toString()
final String com.cliffc.aa.HM.HM9.Syntax.toString () inherited
Definition at line 371 of file HM9.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM9.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.HM.HM9.Lambda.p1().
val()
Type com.cliffc.aa.HM.HM9.Let.val (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 558 of file HM9.java.
 { return _body._flow; }
References com.cliffc.aa.HM.HM9.Let._body, and com.cliffc.aa.HM.HM9.Syntax._flow.
Member Data Documentation
_arg0
final String com.cliffc.aa.HM.HM9.Let._arg0 package
Definition at line 544 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Let.Let(), com.cliffc.aa.HM.HM9.Let.p1(), com.cliffc.aa.HM.HM9.Let.prep_lookup_deps(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), and com.cliffc.aa.HM.HM9.Let.str().
_body
final Syntax com.cliffc.aa.HM.HM9.Let._body package
Definition at line 545 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.Let.Let(), com.cliffc.aa.HM.HM9.Let.more_work(), com.cliffc.aa.HM.HM9.Let.p2(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Let.str(), and com.cliffc.aa.HM.HM9.Let.val().
_def
final Syntax com.cliffc.aa.HM.HM9.Let._def package
Definition at line 545 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_val_work(), com.cliffc.aa.HM.HM9.Let.Let(), com.cliffc.aa.HM.HM9.Let.more_work(), com.cliffc.aa.HM.HM9.Let.p2(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Let.str(), and com.cliffc.aa.HM.HM9.Ident.val().
_flow
Type com.cliffc.aa.HM.HM9.Syntax._flow package inherited
Definition at line 332 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Lambda.apply(), com.cliffc.aa.HM.HM9.Pair1.apply(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Pair.apply(), com.cliffc.aa.HM.HM9.Triple.apply(), com.cliffc.aa.HM.HM9.If.apply(), com.cliffc.aa.HM.HM9.EQ.apply(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM9.IsEmpty.apply(), com.cliffc.aa.HM.HM9.NotNil.apply(), com.cliffc.aa.HM.HM9.Mul.apply(), com.cliffc.aa.HM.HM9.Dec.apply(), com.cliffc.aa.HM.HM9.Str.apply(), com.cliffc.aa.HM.HM9.Factor.apply(), com.cliffc.aa.HM.HM9.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Lambda.Lambda(), com.cliffc.aa.HM.HM9.Syntax.more_work_impl(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM9.Ident.val(), com.cliffc.aa.HM.HM9.Let.val(), com.cliffc.aa.HM.HM9.Apply.val(), com.cliffc.aa.HM.HM9.Root.val(), com.cliffc.aa.HM.HM9.Struct.val(), com.cliffc.aa.HM.HM9.Field.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
_hmt
T2 com.cliffc.aa.HM.HM9.Syntax._hmt package inherited
Definition at line 324 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Syntax.debug_find(), com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.PrimSyn.prep_tree(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM9.PrimSyn.PrimSyn().
_nongen
VStack com.cliffc.aa.HM.HM9.Syntax._nongen package inherited
Definition at line 323 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.add_hm_work(), com.cliffc.aa.HM.HM9.Ident.hm(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM9.Syntax._par package inherited
Definition at line 322 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.Apply.add_hm_work(), com.cliffc.aa.HM.HM9.Struct.add_hm_work(), com.cliffc.aa.HM.HM9.Field.add_hm_work(), com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
_targ
T2 com.cliffc.aa.HM.HM9.Let._targ package
Definition at line 546 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Let.Let(), com.cliffc.aa.HM.HM9.Let.prep_lookup_deps(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), and com.cliffc.aa.HM.HM9.Let.prep_tree().
The documentation for this class was generated from the following file:
HM9.java