aa: com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong Class Reference
com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong Class Reference
A class which implements the Iterator and Enumeration interfaces, generified to the Long class and supporting a non-auto-boxing nextLong function.
Public Member Functions
IteratorLong ()
A new IteratorLong.
boolean hasMoreElements ()
True if there are more keys to iterate over.
boolean hasNext ()
True if there are more keys to iterate over.
Long next ()
Auto-box and return the next key.
Long nextElement ()
Auto-box and return the next key.
long nextLong ()
Return the next key as a primitive.
void remove ()
Remove last key returned by next or nextLong.
Private Attributes
final SnapshotV _ss
Detailed Description
A class which implements the Iterator and Enumeration interfaces, generified to the Long class and supporting a non-auto-boxing nextLong function.
Definition at line 1131 of file NonBlockingHashMapLong.java.
Constructor & Destructor Documentation
IteratorLong()
com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.IteratorLong ()
A new IteratorLong.
Definition at line 1134 of file NonBlockingHashMapLong.java.
 { _ss = new SnapshotV(); }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong._ss.
Member Function Documentation
hasMoreElements()
boolean com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.hasMoreElements ()
True if there are more keys to iterate over.
Definition at line 1146 of file NonBlockingHashMapLong.java.
 { return hasNext(); }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.hasNext().
hasNext()
boolean com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.hasNext ()
True if there are more keys to iterate over.
Definition at line 1142 of file NonBlockingHashMapLong.java.
 { return _ss.hasNext(); }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong._ss, and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.hasNext().
Referenced by com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.hasMoreElements().
next()
Long com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.next ()
Auto-box and return the next key.
Definition at line 1138 of file NonBlockingHashMapLong.java.
 { _ss.next(); return _ss._prevK; }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._prevK, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong._ss, and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.next().
Referenced by com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.nextElement().
nextElement()
Long com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.nextElement ()
Auto-box and return the next key.
Definition at line 1144 of file NonBlockingHashMapLong.java.
 { return next(); }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.next().
nextLong()
long com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.nextLong ()
Return the next key as a primitive.
long
.
Definition at line 1140 of file NonBlockingHashMapLong.java.
 { _ss.next(); return _ss._prevK; }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._prevK, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong._ss, and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.next().
remove()
void com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.remove ()
Remove last key returned by next or nextLong.
Definition at line 1136 of file NonBlockingHashMapLong.java.
 { _ss.removeKey(); }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong._ss, and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.removeKey().
Member Data Documentation
_ss
final SnapshotV com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong._ss private
Definition at line 1132 of file NonBlockingHashMapLong.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.hasNext(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.IteratorLong(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.next(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.nextLong(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.remove().
The documentation for this class was generated from the following file:
NonBlockingHashMapLong.java