aa: com.cliffc.aa.HM.HM8.Worklist Class Reference
com.cliffc.aa.HM.HM8.Worklist Class Reference
Public Member Functions
void addAll (Ary<? extends Syntax > ss)
boolean has (Syntax s)
int len ()
Syntax pop ()
void push (Syntax s)
String toString ()
Public Attributes
int _cnt
Private Attributes
final Ary< Syntax > _ary = new Ary<>(Syntax.class)
final HashSet< Syntax > _work = new HashSet<>()
Detailed Description
Definition at line 197 of file HM8.java.
Member Function Documentation
addAll()
void com.cliffc.aa.HM.HM8.Worklist.addAll (Ary<? extends Syntax > ss)
Definition at line 206 of file HM8.java.
 { if( ss != null ) for( Syntax s : ss ) push(s); }
References com.cliffc.aa.HM.HM8.Worklist.push().
Referenced by com.cliffc.aa.HM.HM8.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM8.T2.add_fld(), com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Let.add_work(), and com.cliffc.aa.HM.HM8.Apply.hm().
has()
boolean com.cliffc.aa.HM.HM8.Worklist.has (Syntax s)
Definition at line 205 of file HM8.java.
 { return _work.contains(s); }
References com.cliffc.aa.HM.HM8.Worklist._work.
Referenced by com.cliffc.aa.HM.HM8.Syntax.more_work_impl().
len()
int com.cliffc.aa.HM.HM8.Worklist.len ()
Definition at line 201 of file HM8.java.
 { return _ary.len(); }
References com.cliffc.aa.HM.HM8.Worklist._ary.
Referenced by com.cliffc.aa.HM.HM8.hm().
pop()
Syntax com.cliffc.aa.HM.HM8.Worklist.pop ()
Definition at line 203 of file HM8.java.
 { Syntax s = _ary.pop();_cnt++;            _work.remove(s); return s; }
References com.cliffc.aa.HM.HM8.Worklist._ary, com.cliffc.aa.HM.HM8.Worklist._cnt, and com.cliffc.aa.HM.HM8.Worklist._work.
Referenced by com.cliffc.aa.HM.HM8.hm().
push()
void com.cliffc.aa.HM.HM8.Worklist.push (Syntax s)
Definition at line 202 of file HM8.java.
 { if( s!=null && !_work.contains(s) ) _work.add(_ary.push(s)); }
References com.cliffc.aa.HM.HM8.Worklist._ary, and com.cliffc.aa.HM.HM8.Worklist._work.
Referenced by com.cliffc.aa.HM.HM8.Con.add_work(), com.cliffc.aa.HM.HM8.Ident.add_work(), com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Apply.add_work(), com.cliffc.aa.HM.HM8.Struct.add_work(), com.cliffc.aa.HM.HM8.Field.add_work(), com.cliffc.aa.HM.HM8.Worklist.addAll(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
toString()
String com.cliffc.aa.HM.HM8.Worklist.toString ()
Definition at line 207 of file HM8.java.
 { return _ary.toString(); }
References com.cliffc.aa.HM.HM8.Worklist._ary.
Member Data Documentation
_ary
final Ary<Syntax> com.cliffc.aa.HM.HM8.Worklist._ary = new Ary<>(Syntax.class) private
Definition at line 199 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Worklist.len(), com.cliffc.aa.HM.HM8.Worklist.pop(), com.cliffc.aa.HM.HM8.Worklist.push(), and com.cliffc.aa.HM.HM8.Worklist.toString().
_cnt
int com.cliffc.aa.HM.HM8.Worklist._cnt
Definition at line 198 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Worklist.pop().
_work
final HashSet<Syntax> com.cliffc.aa.HM.HM8.Worklist._work = new HashSet<>() private
Definition at line 200 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Worklist.has(), com.cliffc.aa.HM.HM8.Worklist.pop(), and com.cliffc.aa.HM.HM8.Worklist.push().
The documentation for this class was generated from the following file:
HM8.java