aa: com.cliffc.aa.node.TestNode Class Reference
com.cliffc.aa.node.TestNode Class Reference
Public Member Functions
void testMonotonic ()
void testNode ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
Type get (long h)
Type get_value_type (long xx)
int[][] make_minimal_graph ()
int[][] make_subtypes ()
long pop ()
void print (int x, int d)
void push (long x)
Type put (long h, Type t)
void redo_ (Node n, int idx, int xidx, int yx, Type[] all)
void set_type (int idx, Type tyx)
void set_value_type (Node n, Type vn, long xx, long xxx, int idx, int yx, Type[] all)
int[] stx (final Node n, long xx, int i)
Type test1jig (final Node n, Type t0, Type t1, Type t2, Type t3)
void test1monotonic (Node n)
void test1monotonic_init (final Node n)
void test1monotonic_intrinsic (NewNode.NewPrimNode prim)
void test1monotonic_prim (PrimNode prim, Node mem)
Static Private Member Functions
static long hash (long h)
static long xx (int i0, int i1, int i2, int i3)
static int xx (long xx, int i)
Private Attributes
Type[] _alltypes
int _errs
GVNGCM _gvn
Node[] _ins
int[][] _min_subtypes
int[][] _subtypes
NonBlockingHashMapLong< Type > _values
long[] _work = new long[1]
int _work_len
Static Private Attributes
static final int[] stx_any = new int[]{}
Detailed Description
Definition at line 16 of file TestNode.java.
Member Function Documentation
get()
Type com.cliffc.aa.node.TestNode.get (long h) private
Definition at line 45 of file TestNode.java.
 { return _values.get(hash(h)); }
References com.cliffc.aa.node.TestNode._values, and com.cliffc.aa.node.TestNode.hash().
get_value_type()
Type com.cliffc.aa.node.TestNode.get_value_type (long xx) private
Definition at line 407 of file TestNode.java.
{
     Type vt = get(xx);
     assert vt!=null;
     return vt;
   }
References com.cliffc.aa.node.TestNode.xx().
Referenced by com.cliffc.aa.node.TestNode.test1monotonic_init().
hash()
static long com.cliffc.aa.node.TestNode.hash (long h) static private
Definition at line 39 of file TestNode.java.
{
     h ^= (h>>>20) ^ (h>>>12);
     h ^= (h>>> 7) ^ (h>>> 4);
     h += h<<7; // smear low bits up high, for hashcodes that only differ by 1
     return h;
   }
Referenced by com.cliffc.aa.node.TestNode.get(), and com.cliffc.aa.node.TestNode.put().
main()
static void com.cliffc.aa.node.TestNode.main (String[] args) static
Definition at line 157 of file TestNode.java.
 { new TestNode().testMonotonic();  }
References com.cliffc.aa.node.TestNode.testMonotonic().
make_minimal_graph()
int [][] com.cliffc.aa.node.TestNode.make_minimal_graph () private
Definition at line 87 of file TestNode.java.
{
     int[][] subs = new int[_subtypes.length][];
     for( int i=0; i<subs.length; i++ )
       subs[i] = _subtypes[i].clone();
     // For all types
     for( int i=0; i<subs.length; i++ ) {
       int[] subis = subs[i];
       // For all 'i' subtypes
       for( int j=0; j<subis.length && subis[j] != -1; j++ ) {
         int[] subjs = subs[subis[j]];
         // Pull out of subis all things found in subjs.  We have a subtype isa
         // path from i->j by design of _subtypes, and the j->k list in subjs.
         // Remove any i->k as being redundant.
         int ix = j+1, ixx = j+1; // Index to read, index to keep non-dups
         int jx = 0; // Index to read the k's
         while( ix<subis.length && jx<subjs.length ) {
           int six = subis[ix];
           int sjx = subjs[jx];
           assert sjx != -1;
           if( six==-1 ) break; // Hit end-of-array sentinel
           if( six==sjx ) { ix++; jx++; } // i->j and j->sjx and i->sjx, skip both forward
           else if( six < sjx ) subis[ixx++] = subis[ix++]; // Keep and advance
           else jx++;                                       // Advance
         }
         while( ixx < ix ) subis[ixx++] = -1; // Sentinel remaining unused elements
       }
       int ix = Util.find(subs[i],-1);
       if( ix != -1 ) subs[i] = Arrays.copyOfRange(subs[i],0,ix); // Compress extra elements
     }
     return subs;
   }
References com.cliffc.aa.node.TestNode._subtypes, and com.cliffc.aa.util.Util.find().
Referenced by com.cliffc.aa.node.TestNode.testMonotonic().
make_subtypes()
int [][] com.cliffc.aa.node.TestNode.make_subtypes () private
Definition at line 63 of file TestNode.java.
{
     // First simplify alltype ptrs - nodes can only produce and consume simple ptr types.
     for( int i=0; i<_alltypes.length; i++ ) {
       _alltypes[i] = _alltypes[i].simple_ptr();
       assert i==0 || _alltypes[i] != _alltypes[i-1]; // Quick check for dups
     }
     int[][] subs = new int[_alltypes.length][];
     int[] tmp = new int[_alltypes.length];
     for( int i=0; i<subs.length; i++ ) {
       int len=0;
       for( int j=0; j<subs.length; j++ )
         if( i!=j && _alltypes[i].isa(_alltypes[j]) )
           tmp[len++]=j;         // isa numbers are sorted by increasing 'j'
       subs[i] = Arrays.copyOfRange(tmp,0,len);
     }
     return subs;
   }
References com.cliffc.aa.node.TestNode._alltypes, and com.cliffc.aa.type.Type< T extends Type< T >.simple_ptr().
Referenced by com.cliffc.aa.node.TestNode.testMonotonic().
pop()
long com.cliffc.aa.node.TestNode.pop () private
Definition at line 128 of file TestNode.java.
 { return _work[--_work_len]; }
References com.cliffc.aa.node.TestNode._work, and com.cliffc.aa.node.TestNode._work_len.
Referenced by com.cliffc.aa.node.TestNode.test1monotonic_init().
print()
void com.cliffc.aa.node.TestNode.print (int x, int d) private
Definition at line 131 of file TestNode.java.
{
     Type dt = get(x);
     if( dt==null ) {
       put(x,dt=TypeInt.con(d));
       int[] subs = _min_subtypes[x];
       for( int sub : subs )
         print(sub,d+1);
       System.out.println("#"+x+" = "+_alltypes[x]+" "+d+" "+dt.getl());
     } else if( d < dt.getl() ) {
       put(x,TypeInt.con(d));
       System.out.println("Shrink #"+x+" = "+_alltypes[x]+" "+d+" "+dt.getl());
     }
   }
References com.cliffc.aa.node.TestNode._alltypes, com.cliffc.aa.node.TestNode._min_subtypes, com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.type.Type< T extends Type< T >.getl(), and com.cliffc.aa.node.TestNode.put().
push()
void com.cliffc.aa.node.TestNode.push (long x) private
Definition at line 122 of file TestNode.java.
{
     if( _work_len == _work.length )
       _work = Arrays.copyOf(_work,_work_len<<1);
     _work[_work_len++] = x;
   }
References com.cliffc.aa.node.TestNode._work, and com.cliffc.aa.node.TestNode._work_len.
Referenced by com.cliffc.aa.node.TestNode.set_value_type(), and com.cliffc.aa.node.TestNode.test1monotonic_init().
put()
Type com.cliffc.aa.node.TestNode.put (long h, Type t) private
Definition at line 46 of file TestNode.java.
 { return _values.put(hash(h),t); }
References com.cliffc.aa.node.TestNode._values, and com.cliffc.aa.node.TestNode.hash().
Referenced by com.cliffc.aa.node.TestNode.print(), com.cliffc.aa.node.TestNode.set_value_type(), and com.cliffc.aa.node.TestNode.test1monotonic_init().
redo_()
void com.cliffc.aa.node.TestNode.redo_ (Node n, int idx, int xidx, int yx, Type[] all) private
Definition at line 384 of file TestNode.java.
{
     set_type(idx,all[xidx]);
     Type err_n = n.value(_gvn._opt_mode);
     set_type(idx,all[yx]);
     Type err_m = n.value(_gvn._opt_mode);
     assert err_n.isa(err_m);
   }
References com.cliffc.aa.node.TestNode._gvn, com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.type.Type< T extends Type< T >.isa(), com.cliffc.aa.node.TestNode.set_type(), and com.cliffc.aa.node.Node.value().
Referenced by com.cliffc.aa.node.TestNode.set_value_type().
set_type()
void com.cliffc.aa.node.TestNode.set_type (int idx, Type tyx) private
Definition at line 395 of file TestNode.java.
{
     if( idx > 0 ) ((ConNode)_ins[idx])._t = tyx;
     _ins[idx]._val = tyx;
   }
References com.cliffc.aa.node.TestNode._ins, and com.cliffc.aa.node.Node._val.
Referenced by com.cliffc.aa.node.TestNode.redo_(), com.cliffc.aa.node.TestNode.set_value_type(), com.cliffc.aa.node.TestNode.test1monotonic_init(), and com.cliffc.aa.node.TestNode.testMonotonic().
set_value_type()
void com.cliffc.aa.node.TestNode.set_value_type (Node n, Type vn, long xx, long xxx, int idx, int yx, Type[] all) private
Definition at line 363 of file TestNode.java.
{
     Type vm = get(xxx);
     if( vm == null ) {
       set_type(idx,all[yx]);
       vm = n.value(_gvn._opt_mode);
       Type old = put(xxx,vm);
       assert old==null;
       push(xxx);            // Now visit all children
     }
     // The major monotonicity assert
     int x1 = xx(xx,1);
     int y1 = idx==1 ? yx : x1;
     if( vn!= vm && !vn.isa(vm) ) {
       int x0 = xx(xx,0), x2 = xx(xx,2), x3 = xx(xx,3);
       System.out.println(n.xstr()+"("+all[x0]+","+all[x1]+","+all[x2]+","+all[x3]+") = "+vn);
       System.out.println(n.xstr()+"("+all[idx==0?yx:x0]+","+all[idx==1?yx:x1]+","+all[idx==2?yx:x2]+","+all[idx==3?yx:x3]+") = "+vm);
       _errs++;
       redo_(n,idx, xx(xx,idx),yx,all);
     }
   }
References com.cliffc.aa.node.TestNode._errs, com.cliffc.aa.node.TestNode._gvn, com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.type.Type< T extends Type< T >.isa(), com.cliffc.aa.node.TestNode.push(), com.cliffc.aa.node.TestNode.put(), com.cliffc.aa.node.TestNode.redo_(), com.cliffc.aa.node.TestNode.set_type(), com.cliffc.aa.node.Node.value(), com.cliffc.aa.node.Node.xstr(), and com.cliffc.aa.node.TestNode.xx().
Referenced by com.cliffc.aa.node.TestNode.test1monotonic_init().
stx()
int [] com.cliffc.aa.node.TestNode.stx (final Node n, long xx, int i) private
Definition at line 401 of file TestNode.java.
{
     if( i >= n._defs._len || n.in(i) == null ) return stx_any;
     return _min_subtypes[xx(xx,i)];
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.TestNode._min_subtypes, com.cliffc.aa.node.Node.in(), com.cliffc.aa.node.TestNode.stx_any, and com.cliffc.aa.node.TestNode.xx().
Referenced by com.cliffc.aa.node.TestNode.test1monotonic_init().
test1jig()
Type com.cliffc.aa.node.TestNode.test1jig (final Node n, Type t0, Type t1, Type t2, Type t3) private
Definition at line 271 of file TestNode.java.
{
     // Prep graph edges
     _ins[0]._val = t0;
     _ins[1]._val = ((ConNode)_ins[1])._t = t1;
     _ins[2]._val = ((ConNode)_ins[2])._t = t2;
     _ins[3]._val = ((ConNode)_ins[3])._t = t3;
     return n.value(_gvn._opt_mode);
   }
References com.cliffc.aa.node.TestNode._gvn, com.cliffc.aa.node.TestNode._ins, com.cliffc.aa.GVNGCM._opt_mode, and com.cliffc.aa.node.Node._val.
Referenced by com.cliffc.aa.node.TestNode.testMonotonic().
test1monotonic()
void com.cliffc.aa.node.TestNode.test1monotonic (Node n) private
Definition at line 280 of file TestNode.java.
{
     assert n._defs._len>0;
     test1monotonic_init(n);
   }
References com.cliffc.aa.node.Node._defs, and com.cliffc.aa.node.TestNode.test1monotonic_init().
Referenced by com.cliffc.aa.node.TestNode.testMonotonic().
test1monotonic_init()
void com.cliffc.aa.node.TestNode.test1monotonic_init (final Node n) private
Definition at line 309 of file TestNode.java.
{
     System.out.println(n.xstr());
     _values.clear(true);
     put(0,Type.ANY);            // First args are all ANY, so is result
     push(0);                    // Init worklist
     Type[] all = _alltypes;
     long t0 = System.currentTimeMillis(), t2=t0;
     long nprobes = 0, nprobes1=0;
     while( _work_len > 0 ) {
       long xx = pop();
       Type vn = get_value_type(xx);
       int x0 = xx(xx,0), x1 = xx(xx,1), x2 = xx(xx,2), x3 = xx(xx,3);
       // Prep graph edges
       _ins[0]._val = all[x0];
       _ins[1]._val = ((ConNode)_ins[1])._t = all[x1];
       _ins[2]._val = ((ConNode)_ins[2])._t = all[x2];
       _ins[3]._val = ((ConNode)_ins[3])._t = all[x3];
       // Subtypes in 4 node input directions
       int[] stx0 = stx(n,xx,0);
       for( int y0 : stx0 )
         set_value_type(n, vn, xx, xx(y0,x1,x2,x3), 0, y0, all );
       set_type(0,all[x0]);
       int[] stx1 = stx(n,xx,1);
       for( int y1 : stx1 )
         set_value_type(n, vn, xx, xx(x0,y1,x2,x3), 1, y1, all );
       set_type(1,all[x1]);
       int[] stx2 = stx(n,xx,2);
       for( int y2 : stx2 )
         set_value_type(n, vn, xx, xx(x0,x1,y2,x3), 2, y2, all );
       set_type(2,all[x2]);
       int[] stx3 = stx(n,xx,3);
       for( int y3 : stx3 )
         set_value_type(n, vn, xx, xx(x0,x1,x2,y3), 3, y3, all );
       set_type(3,all[x3]);
       nprobes1 += stx0.length+stx1.length+stx2.length+stx3.length;
       long t1 = System.currentTimeMillis();
       if( t1-t0 >= 1000 ) {
         nprobes += nprobes1;
         System.out.println("Did "+nprobes1+" in "+(t1-t0)+"msecs, worklist has "+_work_len+" states, total probes "+nprobes+", values="+_values.size());
         nprobes1=0;
         t0=t1;
       }
     }
     nprobes += nprobes1;
     System.out.println("Total probes "+nprobes+" in "+(t0-t2)+"msecs, values="+_values.size());
   }
References com.cliffc.aa.node.TestNode._alltypes, com.cliffc.aa.node.TestNode._ins, com.cliffc.aa.node.Node._val, com.cliffc.aa.node.TestNode._values, com.cliffc.aa.node.TestNode._work_len, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.node.TestNode.get_value_type(), com.cliffc.aa.node.TestNode.pop(), com.cliffc.aa.node.TestNode.push(), com.cliffc.aa.node.TestNode.put(), com.cliffc.aa.node.TestNode.set_type(), com.cliffc.aa.node.TestNode.set_value_type(), com.cliffc.aa.node.TestNode.stx(), and com.cliffc.aa.node.TestNode.xx().
Referenced by com.cliffc.aa.node.TestNode.test1monotonic(), com.cliffc.aa.node.TestNode.test1monotonic_intrinsic(), and com.cliffc.aa.node.TestNode.test1monotonic_prim().
test1monotonic_intrinsic()
void com.cliffc.aa.node.TestNode.test1monotonic_intrinsic (NewNode.NewPrimNode prim) private
Definition at line 297 of file TestNode.java.
{
     NewNode.NewPrimNode n = (NewNode.NewPrimNode)prim.copy(false);
     assert n._defs._len==0;
     n.add_def( null  );
     n.add_def(_ins[1]);         // memory
     n.add_def(null);            // display
     n.add_def(_ins[2]);         // arg#1
     if( n._sig.nargs() >= 2 ) n.add_def(_ins[3]);
     test1monotonic_init(n);
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.TestNode._ins, com.cliffc.aa.node.NewNode< T extends TypeObj< T >.copy(), and com.cliffc.aa.node.TestNode.test1monotonic_init().
Referenced by com.cliffc.aa.node.TestNode.testMonotonic().
test1monotonic_prim()
void com.cliffc.aa.node.TestNode.test1monotonic_prim (PrimNode prim, Node mem) private
Definition at line 286 of file TestNode.java.
{
     PrimNode n = (PrimNode)prim.copy(false);
     assert n._defs._len==0;
     n.add_def( null  );
     n.add_def(_ins[n._defs._len]);
     if( n instanceof MemPrimNode ) n.add_def(mem);
     if( n._sig.nargs() >= 3 )      n.add_def(_ins[n._defs._len-1]);
     if( n._sig.nargs() >= 4 )      n.add_def(_ins[n._defs._len-1]);
     test1monotonic_init(n);
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.TestNode._ins, com.cliffc.aa.node.PrimNode._sig, com.cliffc.aa.node.Node.add_def(), com.cliffc.aa.node.Node.copy(), com.cliffc.aa.type.TypeFunSig.nargs(), and com.cliffc.aa.node.TestNode.test1monotonic_init().
Referenced by com.cliffc.aa.node.TestNode.testMonotonic().
testMonotonic()
void com.cliffc.aa.node.TestNode.testMonotonic ()
Definition at line 159 of file TestNode.java.
{
     Env top = Env.top_scope();
     Env.file_scope(top);
     assert _errs == 0;          // Start with no errors
     // Types we are testing
     _alltypes = Type.ALL_TYPES().asAry();
     // A subset used to help diagnose this algorithm.
     //Type[] ts = new Type[] {
     //  Type.ALL,Type.ANY,Type.CTRL,Type.XCTRL, Type.SCALAR, Type.XSCALAR, Type.NSCALR, Type.XNSCALR,
     //  Type.NUM, Type.XNUM, Type.NIL
     //};
     //for( int i=0; i<ts.length; i++ )
     //  for( int j=i+1; j<ts.length; j++ )
     //    if( ts[j].isa(ts[i]) ) { Type tmp = ts[i]; ts[i] = ts[j]; ts[j] = tmp; }
     //_alltypes = ts;
     // All The Types we care to reason about.  There's an infinite number of
     // Types, but mostly are extremely similar - so we limit ourselves to a
     // subset which has at least one of unique subtype, plus some variations
     // inside the more complex Types.
     _subtypes = make_subtypes();
     // Build a minimal spanning sub-Type tree from the set of sample types.
     // We'll use this to know which other types sub-Type this type... and thus be
     // more efficient in testing all Types which subtype another Type.
     _min_subtypes = make_minimal_graph();
     // Per-node-type cached value() results
     _values = new NonBlockingHashMapLong<Type>(128*1024*1024,false);
     // Print the types and subtypes in a RPO
     //print(0,0);
     //_values.clear(true);
     // Setup to compute a value() call: we need a tiny chunk of Node graph with
     // known inputs.
     _gvn = Env.GVN;
     _ins = new Node[4];
     _ins[0] = new RegionNode(null,new ConNode<>(Type.CTRL),new ConNode<>(Type.CTRL));
     for( int i=1; i<_ins.length; i++ )
       _ins[i] = new ConNode<>(Type.SCALAR);
     Node mem = new ConNode<Type>(TypeMem.MEM);
     mem._val = TypeMem.MEM;
     FunNode fun_forward_ref = new FunNode("some_fcn");
     Env.DEFMEM._val = TypeMem.MEM;
     Node unr = top.lookup("+"); // All the "+" functions
     FunNode fun_plus = ((FunPtrNode)unr.in(1)).fun();
     RetNode ret = fun_plus.ret();
     CallNode call = new CallNode(false,null,_ins[0],unr,mem);
     call._val = TypeTuple.CALLE;
     TypeStruct tname = TypeStruct.NAMEPT;
     // Testing 1 set of types into a value call.
     // Comment out when not debugging.
     CallEpiNode cepi = new CallEpiNode(call,Env.DEFMEM,_ins[2]);
     Type rez0 = test1jig(cepi, TypeTuple.TEST0,TypeTuple.RET, Type.ANY, Type.ANY);
     // All the Nodes, all Values, all Types
     test1monotonic(new   CallNode(false,null,_ins[0],  unr  ,mem,_ins[2],_ins[3]));
     test1monotonic(new   CallNode(false,null,_ins[0],_ins[1],mem,_ins[2],_ins[3]));
     test1monotonic(new CallEpiNode(call,Env.DEFMEM,_ins[2])); // CallNode, then some count of RetNode, not flowing
     test1monotonic(new    ConNode<Type>(          TypeInt.FALSE));
     test1monotonic(new    ConNode<Type>(          TypeStr.ABC  ));
     test1monotonic(new    ConNode<Type>(          TypeFlt.FLT64));
     // Cannot cast-to-NIL - can only move away from NIL
     //test1monotonic(new   CastNode(_ins[0],_ins[1],TypeInt.FALSE));
     test1monotonic(new   CastNode(_ins[0],_ins[1],Type.NSCALR));
     test1monotonic(new   CastNode(_ins[0],_ins[1],TypeFlt.FLT64));
     test1monotonic(new   CastNode(_ins[0],_ins[1],TypeMemPtr.STRPTR));
     test1monotonic(new   CastNode(_ins[0],_ins[1],TypeMemPtr.STR0));
     test1monotonic(new  CProjNode(_ins[0],0));
     test1monotonic(new    ErrNode(_ins[0],null,"\nerr\n"));
     test1monotonic(new    FunNode(new String[]{"^","x"},new Type[]{TypeMemPtr.DISP_SIMPLE,TypeInt.INT64}));
     test1monotonic(new FunPtrNode("anon",ret,null));
     test1monotonic(new FP2DispNode(_ins[1])); // Only takes in a TFP
     test1monotonic(new     IfNode(_ins[0],_ins[1]));
     for( NewNode.NewPrimNode prim : NewNode.NewPrimNode.INTRINSICS() )
       test1monotonic_intrinsic(prim);
     test1monotonic(new IntrinsicNode(tname,null,null,mem,_ins[2]));
     test1monotonic(new   LoadNode(_ins[1],_ins[2],"x",null));
     NewObjNode nnn1 = new NewObjNode(false,TypeMemPtr.DISPLAY,Node.con(Type.NIL));
     set_type(1,Type.SCALAR);  nnn1.create_active("x",_ins[1],Access.Final);
     set_type(2,Type.SCALAR);  nnn1.create_active("y",_ins[2],Access.Final);
     test1monotonic(nnn1);
     NewObjNode nnn2 = new NewObjNode(false,TypeMemPtr.DISPLAY,Node.con(Type.NIL));
     set_type(1,Type.SCALAR);  nnn2.create_active("x",_ins[1],Access.Final);
     set_type(2,Type.SCALAR);  nnn2.create_active("y",_ins[2],Access.Final);
     nnn2.sets(tname);
     test1monotonic(nnn2);
     ((ConNode<Type>)_ins[1])._t = Type.SCALAR; // ParmNode reads this for _alltype
     test1monotonic(new   ParmNode( 1, "x",_ins[0],(ConNode)_ins[1],null).add_def(_ins[2]));
     test1monotonic(new    PhiNode(Type.SCALAR,null,_ins[0],_ins[1],_ins[2]));
     for( PrimNode prim : PrimNode.PRIMS() )
       test1monotonic_prim(prim,mem);
     test1monotonic(new   ProjNode(1, _ins[0]));
     test1monotonic(new RegionNode(null,_ins[1],_ins[2]));
     test1monotonic(new    RetNode(_ins[0],mem,_ins[1],_ins[2],fun_plus)); // ctl,mem,val,rpc,fun
     test1monotonic(new  StoreNode(_ins[1],_ins[2],_ins[3],Access.RW   ,"x",null));
     test1monotonic(new  StoreNode(_ins[1],_ins[2],_ins[3],Access.Final,"x",null));
     //                  ScopeNode has no inputs, and value() call is monotonic
     test1monotonic(new AssertNode(_ins[1],_ins[2],TypeInt.FALSE    ,null, null));
     test1monotonic(new AssertNode(_ins[1],_ins[2],TypeMemPtr.STRPTR,null, null));
     test1monotonic(new AssertNode(_ins[1],_ins[2],TypeFlt.FLT64    ,null, null));
     _gvn._opt_mode=GVNGCM.Mode.PesiNoCG;  test1monotonic(new UnresolvedNode(null,_ins[1],_ins[2]));  _gvn._opt_mode=GVNGCM.Mode.Parse;
     _gvn._opt_mode=GVNGCM.Mode.PesiCG  ;  test1monotonic(new UnresolvedNode(null,_ins[1],_ins[2]));  _gvn._opt_mode=GVNGCM.Mode.Parse;
     assertEquals(0,_errs);
   }
References com.cliffc.aa.node.TestNode._alltypes, com.cliffc.aa.node.TestNode._errs, com.cliffc.aa.node.TestNode._gvn, com.cliffc.aa.node.TestNode._ins, com.cliffc.aa.node.TestNode._min_subtypes, com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.node.TestNode._subtypes, com.cliffc.aa.node.Node._val, com.cliffc.aa.node.TestNode._values, com.cliffc.aa.type.TypeStr.ABC, com.cliffc.aa.type.Type< T extends Type< T >.ALL_TYPES, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.type.TypeTuple.CALLE, com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.NewObjNode.create_active(), com.cliffc.aa.type.Type< T extends Type< T >.CTRL, com.cliffc.aa.Env.DEFMEM, com.cliffc.aa.type.TypeMemPtr.DISP_SIMPLE, com.cliffc.aa.type.TypeMemPtr.DISPLAY, com.cliffc.aa.type.TypeInt.FALSE, com.cliffc.aa.Env.file_scope(), com.cliffc.aa.type.TypeFld.Access.Final, com.cliffc.aa.type.TypeFlt.FLT64, com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.in(), com.cliffc.aa.type.TypeInt.INT64, com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.INTRINSICS, com.cliffc.aa.Env.lookup(), com.cliffc.aa.node.TestNode.make_minimal_graph(), com.cliffc.aa.node.TestNode.make_subtypes(), com.cliffc.aa.type.TypeMem.MEM, com.cliffc.aa.type.TypeStruct.NAMEPT, com.cliffc.aa.type.Type< T extends Type< T >.NIL, com.cliffc.aa.type.Type< T extends Type< T >.NSCALR, com.cliffc.aa.GVNGCM.Mode.Parse, com.cliffc.aa.GVNGCM.Mode.PesiCG, com.cliffc.aa.GVNGCM.Mode.PesiNoCG, com.cliffc.aa.node.PrimNode.PRIMS, com.cliffc.aa.type.TypeTuple.RET, com.cliffc.aa.node.FunNode.ret(), com.cliffc.aa.type.TypeFld.Access.RW, com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, com.cliffc.aa.node.TestNode.set_type(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.sets(), com.cliffc.aa.type.TypeMemPtr.STR0, com.cliffc.aa.type.TypeMemPtr.STRPTR, com.cliffc.aa.type.TypeTuple.TEST0, com.cliffc.aa.node.TestNode.test1jig(), com.cliffc.aa.node.TestNode.test1monotonic(), com.cliffc.aa.node.TestNode.test1monotonic_intrinsic(), com.cliffc.aa.node.TestNode.test1monotonic_prim(), and com.cliffc.aa.Env.top_scope().
Referenced by com.cliffc.aa.node.TestNode.main().
testNode()
void com.cliffc.aa.node.TestNode.testNode ()
Definition at line 55 of file TestNode.java.
{
     Env.file_scope(Env.top_scope());
   }
References com.cliffc.aa.Env.file_scope(), and com.cliffc.aa.Env.top_scope().
xx() [1/2]
static long com.cliffc.aa.node.TestNode.xx (int i0, int i1, int i2, int i3) static private
Definition at line 413 of file TestNode.java.
{
     return i0+(i1<<8)+(i2<<16)+(i3<<24);
   }
Referenced by com.cliffc.aa.node.TestNode.get_value_type(), com.cliffc.aa.node.TestNode.set_value_type(), com.cliffc.aa.node.TestNode.stx(), com.cliffc.aa.node.TestNode.test1monotonic_init(), and com.cliffc.aa.node.TestNode.xx().
xx() [2/2]
static int com.cliffc.aa.node.TestNode.xx (long xx, int i) static private
Definition at line 416 of file TestNode.java.
 { return (int)((xx>>(i<<3)) & 0xffL); }
References com.cliffc.aa.node.TestNode.xx().
Member Data Documentation
_alltypes
Type [] com.cliffc.aa.node.TestNode._alltypes private
Definition at line 24 of file TestNode.java.
Referenced by com.cliffc.aa.node.TestNode.make_subtypes(), com.cliffc.aa.node.TestNode.print(), com.cliffc.aa.node.TestNode.test1monotonic_init(), and com.cliffc.aa.node.TestNode.testMonotonic().
_errs
int com.cliffc.aa.node.TestNode._errs private
Definition at line 52 of file TestNode.java.
Referenced by com.cliffc.aa.node.TestNode.set_value_type(), and com.cliffc.aa.node.TestNode.testMonotonic().
_gvn
GVNGCM com.cliffc.aa.node.TestNode._gvn private
Definition at line 21 of file TestNode.java.
Referenced by com.cliffc.aa.node.TestNode.redo_(), com.cliffc.aa.node.TestNode.set_value_type(), com.cliffc.aa.node.TestNode.test1jig(), and com.cliffc.aa.node.TestNode.testMonotonic().
_ins
Node [] com.cliffc.aa.node.TestNode._ins private
Definition at line 19 of file TestNode.java.
Referenced by com.cliffc.aa.node.TestNode.set_type(), com.cliffc.aa.node.TestNode.test1jig(), com.cliffc.aa.node.TestNode.test1monotonic_init(), com.cliffc.aa.node.TestNode.test1monotonic_intrinsic(), com.cliffc.aa.node.TestNode.test1monotonic_prim(), and com.cliffc.aa.node.TestNode.testMonotonic().
_min_subtypes
int [][] com.cliffc.aa.node.TestNode._min_subtypes private
Definition at line 36 of file TestNode.java.
Referenced by com.cliffc.aa.node.TestNode.print(), com.cliffc.aa.node.TestNode.stx(), and com.cliffc.aa.node.TestNode.testMonotonic().
_subtypes
int [][] com.cliffc.aa.node.TestNode._subtypes private
Definition at line 29 of file TestNode.java.
Referenced by com.cliffc.aa.node.TestNode.make_minimal_graph(), and com.cliffc.aa.node.TestNode.testMonotonic().
_values
NonBlockingHashMapLong<Type> com.cliffc.aa.node.TestNode._values private
Definition at line 38 of file TestNode.java.
Referenced by com.cliffc.aa.node.TestNode.get(), com.cliffc.aa.node.TestNode.put(), com.cliffc.aa.node.TestNode.test1monotonic_init(), and com.cliffc.aa.node.TestNode.testMonotonic().
_work
long [] com.cliffc.aa.node.TestNode._work = new long[1] private
Definition at line 49 of file TestNode.java.
Referenced by com.cliffc.aa.node.TestNode.pop(), and com.cliffc.aa.node.TestNode.push().
_work_len
int com.cliffc.aa.node.TestNode._work_len private
Definition at line 50 of file TestNode.java.
Referenced by com.cliffc.aa.node.TestNode.pop(), com.cliffc.aa.node.TestNode.push(), and com.cliffc.aa.node.TestNode.test1monotonic_init().
stx_any
final int [] com.cliffc.aa.node.TestNode.stx_any = new int[]{} static private
Definition at line 400 of file TestNode.java.
Referenced by com.cliffc.aa.node.TestNode.stx().
The documentation for this class was generated from the following file:
TestNode.java