aa: com.cliffc.aa.HM.HM3.HMVar Class Reference
com.cliffc.aa.HM.HM3.HMVar Class Reference
Public Member Functions
SB _str (SB sb, VBitSet dups, boolean debug)
String str ()
final String toString ()
Type type ()
Package Functions
HMVar ()
HMVar (Type t)
boolean _eq (HMType v, BitSetSparse dups)
HMType _fresh (VStack vstk, HashMap< HMVar, HMVar > vars, HashMap< Oper, Oper > opers)
final boolean eq (HMType v)
HMType find ()
HMType fresh (VStack vstk)
boolean is_top ()
boolean occurs_in (HMType[] args, VBitSet dups)
boolean occurs_in (VStack vstk, VBitSet dups)
boolean occurs_in_type (HMType v, VBitSet dups)
HMType union (HMType that, Worklist work)
Static Package Functions
static void reset ()
Package Attributes
Ary< Ident > _ids
HMType _u
final int _uid
Static Package Attributes
static final HashMap< HMVar, HMVar > EQS = new HashMap<>()
Private Attributes
Type _t
Static Private Attributes
static int CNT
Detailed Description
Definition at line 323 of file HM3.java.
Constructor & Destructor Documentation
HMVar() [1/2]
com.cliffc.aa.HM.HM3.HMVar.HMVar () package
Definition at line 325 of file HM3.java.
 { this(Type.ANY); }
References com.cliffc.aa.type.Type< T extends Type< T >.ANY.
Referenced by com.cliffc.aa.HM.HM3.HMVar._fresh(), and com.cliffc.aa.HM.HM3.HMVar.union().
HMVar() [2/2]
com.cliffc.aa.HM.HM3.HMVar.HMVar (Type t) package
Definition at line 326 of file HM3.java.
 { _t=t; }
References com.cliffc.aa.HM.HM3.HMVar._t.
Member Function Documentation
_eq()
boolean com.cliffc.aa.HM.HM3.HMVar._eq (HMType v, BitSetSparse dups) package
Reimplemented from com.cliffc.aa.HM.HM3.HMType.
Definition at line 375 of file HM3.java.
{
       if( this==v ) return true;
       if( v==null ) return false;
       HMType v2 = v.find();
       if( !(v2 instanceof HMVar) ) return false;
       assert _u==null && v2._u==null;
       if( _t != ((HMVar)v2)._t) return false;
       HMVar v3 = EQS.computeIfAbsent(this,k -> (HMVar)v2);
       return v2 == v3;
     }
References com.cliffc.aa.HM.HM3.HMVar._t, com.cliffc.aa.HM.HM3.HMType._u, com.cliffc.aa.HM.HM3.HMType.EQS, and com.cliffc.aa.HM.HM3.HMType.find().
_fresh()
HMType com.cliffc.aa.HM.HM3.HMVar._fresh (VStack vstk, HashMap< HMVar, HMVar > vars, HashMap< Oper, Oper > opers) package
Reimplemented from com.cliffc.aa.HM.HM3.HMType.
Definition at line 386 of file HM3.java.
{
       assert is_top();
       return occurs_in(vstk, new VBitSet()) // If in the lexical Stack
         ? this                      // Keep same var
         : vars.computeIfAbsent(this, e -> new HMVar(_t));
     }
References com.cliffc.aa.HM.HM3.HMVar._t, com.cliffc.aa.HM.HM3.HMVar.HMVar(), com.cliffc.aa.HM.HM3.HMType.is_top(), and com.cliffc.aa.HM.HM3.HMType.occurs_in().
_str()
SB com.cliffc.aa.HM.HM3.HMVar._str (SB sb, VBitSet dups, boolean debug)
Reimplemented from com.cliffc.aa.HM.HM3.HMType.
Definition at line 328 of file HM3.java.
{
       if( _u!=null && !debug ) return _u._str(sb,dups,debug); // Clean print; skip to U-F root & print
       sb.p("v").p(_uid);
       if( dups.tset(_uid) ) return sb.p("$");  // Stop infinite print loops
       if( _t!=Type.ANY ) _t.str(sb.p(":"),dups,null,false);
       if( _u!=null ) _u._str(sb.p(">>"),dups,debug);
       return sb;
      }
References com.cliffc.aa.HM.HM3.HMType._str(), com.cliffc.aa.HM.HM3.HMVar._t, com.cliffc.aa.HM.HM3.HMType._u, com.cliffc.aa.HM.HM3.HMType._uid, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.Type< T extends Type< T >.str(), and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.HM.HM3.VStack.str().
eq()
final boolean com.cliffc.aa.HM.HM3.HMType.eq (HMType v) package inherited
Definition at line 291 of file HM3.java.
 { EQS.clear(); return find()._eq(v, new BitSetSparse()); }
References com.cliffc.aa.HM.HM3.HMType._eq(), com.cliffc.aa.HM.HM3.HMType.EQS, and com.cliffc.aa.HM.HM3.HMType.find().
Referenced by com.cliffc.aa.HM.HM3.Lambda.progress(), com.cliffc.aa.HM.HM3.Let.progress(), and com.cliffc.aa.HM.HM3.Apply.progress().
find()
HMType com.cliffc.aa.HM.HM3.HMVar.find () package
Reimplemented from com.cliffc.aa.HM.HM3.HMType.
Definition at line 337 of file HM3.java.
{
       HMType u = _u;
       if( u==null ) return this; // Top of union tree
       if( u._u==null ) return u; // One-step from top
       // Classic U-F rollup
       while( u._u!=null ) u = u._u; // Find the top
       HMType x = this;              // Collapse all to top
       while( x._u!=u ) { HMType tmp = x._u; x._u=u; x=tmp;}
       return u;
     }
References com.cliffc.aa.HM.HM3.HMType._u.
Referenced by com.cliffc.aa.HM.HM3.HMVar.union().
fresh()
HMType com.cliffc.aa.HM.HM3.HMType.fresh (VStack vstk) package inherited
Definition at line 294 of file HM3.java.
{
       HashMap<HMVar,HMVar> vars = new HashMap<>();
       HashMap<Oper,Oper> opers = new HashMap<>();
       return find()._fresh(vstk,vars,opers);
     }
References com.cliffc.aa.HM.HM3.HMType._fresh(), and com.cliffc.aa.HM.HM3.HMType.find().
Referenced by com.cliffc.aa.HM.HM3.Ident.hm().
is_top()
boolean com.cliffc.aa.HM.HM3.HMType.is_top () package inherited
Definition at line 289 of file HM3.java.
 { return _u==null; }
References com.cliffc.aa.HM.HM3.HMType._u.
Referenced by com.cliffc.aa.HM.HM3.Oper._eq(), com.cliffc.aa.HM.HM3.HMVar._fresh(), com.cliffc.aa.HM.HM3.Oper._fresh(), com.cliffc.aa.HM.HM3.HMType.occurs_in_type(), and com.cliffc.aa.HM.HM3.HMVar.type().
occurs_in() [1/2]
boolean com.cliffc.aa.HM.HM3.HMType.occurs_in (HMType[] args, VBitSet dups) package inherited
Definition at line 306 of file HM3.java.
{
       for( HMType x : args ) if( occurs_in_type(x,dups) ) return true;
       return false;
     }
References com.cliffc.aa.HM.HM3.HMType.occurs_in_type().
occurs_in() [2/2]
boolean com.cliffc.aa.HM.HM3.HMType.occurs_in (VStack vstk, VBitSet dups) package inherited
Definition at line 301 of file HM3.java.
{
       if( vstk==null ) return false;
       for( HMVar x : vstk ) if( occurs_in_type(x,dups) ) return true;
       return false;
     }
References com.cliffc.aa.HM.HM3.HMType.occurs_in_type().
Referenced by com.cliffc.aa.HM.HM3.HMVar._fresh(), and com.cliffc.aa.HM.HM3.HMType.occurs_in_type().
occurs_in_type()
boolean com.cliffc.aa.HM.HM3.HMType.occurs_in_type (HMType v, VBitSet dups) package inherited
Definition at line 310 of file HM3.java.
{
       assert is_top();
       if( dups.tset(v._uid) )
         return false;           // Been there, done that
       HMType y = v.find();      // Find top
       if( y==this )             // Occurs in type?
         return true;            // Yup, occurs in type right here
       if( y instanceof Oper )   // Structural recursive test
         return occurs_in(((Oper)y)._args,dups);
       return false;
     }
References com.cliffc.aa.HM.HM3.HMType._uid, com.cliffc.aa.HM.HM3.HMType.find(), com.cliffc.aa.HM.HM3.HMType.is_top(), com.cliffc.aa.HM.HM3.HMType.occurs_in(), and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.HM.HM3.HMType.occurs_in(), and com.cliffc.aa.HM.HM3.HMVar.union().
reset()
static void com.cliffc.aa.HM.HM3.HMType.reset () static package inherited
Definition at line 281 of file HM3.java.
 { CNT=1; }
References com.cliffc.aa.HM.HM3.HMType.CNT.
Referenced by com.cliffc.aa.HM.HM3.reset().
str()
String com.cliffc.aa.HM.HM3.HMType.str () inherited
Definition at line 287 of file HM3.java.
 { return _str(new SB(),new VBitSet(),false).toString(); }
References com.cliffc.aa.HM.HM3.HMType._str(), and com.cliffc.aa.util.SB.toString().
toString()
final String com.cliffc.aa.HM.HM3.HMType.toString () inherited
Definition at line 286 of file HM3.java.
 { return _str(new SB(),new VBitSet(),true).toString(); }
References com.cliffc.aa.HM.HM3.HMType._str(), and com.cliffc.aa.util.SB.toString().
type()
Type com.cliffc.aa.HM.HM3.HMVar.type ()
Definition at line 327 of file HM3.java.
 { assert is_top(); return _t; }
References com.cliffc.aa.HM.HM3.HMVar._t, and com.cliffc.aa.HM.HM3.HMType.is_top().
union()
HMType com.cliffc.aa.HM.HM3.HMVar.union (HMType that, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM3.HMType.
Definition at line 347 of file HM3.java.
{
       if( _u!=null ) return find().union(that,work);
       if( that instanceof HMVar ) that = that.find();
       if( this==that ) return this; // Do nothing
       if( occurs_in_type(that, new VBitSet()) )
         //throw new RuntimeException("recursive unification");
         System.out.println("recursive unification");
       if( that instanceof HMVar ) {
         HMVar v2 = (HMVar)that;
         // Order, so keep smaller _uids by default
         if( _uid < v2._uid ) return that.union(this,work);
         v2._t = _t.meet(v2._t); // Lattice MEET instead of unification failure
       }
       else if( _t!=Type.ANY )   // Else this var is un-MEETd with any Con
         throw new RuntimeException("Cannot unify "+this+" and "+that);
       if( _ids!=null ) {        // Move this ids into that ids
         if( that._ids==null ) that._ids = _ids;
         else that._ids.addAll(_ids);
         _ids=null;              // No longer here
       }
       if( that._ids!=null ) {   // All that ids onto worklist
         for( Ident id : that._ids ) id._hm=null; // Flag as 1-shot re-freshen
         work.addAll(that._ids); // On to worklist
       }
       return _u = that;         // Classic U-F union this into that.
     }
References com.cliffc.aa.HM.HM3.HMType._ids, com.cliffc.aa.HM.HM3.HMVar._t, com.cliffc.aa.HM.HM3.HMType._u, com.cliffc.aa.HM.HM3.HMType._uid, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.HM.HM3.HMType.find(), com.cliffc.aa.HM.HM3.HMVar.find(), com.cliffc.aa.HM.HM3.HMVar.HMVar(), com.cliffc.aa.type.Type< T extends Type< T >.meet(), com.cliffc.aa.HM.HM3.HMType.occurs_in_type(), com.cliffc.aa.HM.HM3.HMType.union(), and com.cliffc.aa.HM.HM3.HMVar.union().
Referenced by com.cliffc.aa.HM.HM3.HMVar.union().
Member Data Documentation
_ids
Ary<Ident> com.cliffc.aa.HM.HM3.HMType._ids package inherited
Definition at line 283 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Ident.get_ids(), com.cliffc.aa.HM.HM3.HMVar.union(), and com.cliffc.aa.HM.HM3.Oper.union().
_t
Type com.cliffc.aa.HM.HM3.HMVar._t private
Definition at line 324 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.HMVar._eq(), com.cliffc.aa.HM.HM3.HMVar._fresh(), com.cliffc.aa.HM.HM3.HMVar._str(), com.cliffc.aa.HM.HM3.HMVar.HMVar(), com.cliffc.aa.HM.HM3.HMVar.type(), and com.cliffc.aa.HM.HM3.HMVar.union().
_u
HMType com.cliffc.aa.HM.HM3.HMType._u package inherited
Definition at line 278 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.HMVar._eq(), com.cliffc.aa.HM.HM3.HMVar._str(), com.cliffc.aa.HM.HM3.HMVar.find(), com.cliffc.aa.HM.HM3.HMType.is_top(), and com.cliffc.aa.HM.HM3.HMVar.union().
_uid
final int com.cliffc.aa.HM.HM3.HMType._uid package inherited
Definition at line 279 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Oper._eq(), com.cliffc.aa.HM.HM3.HMVar._str(), com.cliffc.aa.HM.HM3.Oper._str(), com.cliffc.aa.HM.HM3.HMType.HMType(), com.cliffc.aa.HM.HM3.HMType.occurs_in_type(), com.cliffc.aa.HM.HM3.HMVar.union(), and com.cliffc.aa.HM.HM3.Oper.union().
CNT
int com.cliffc.aa.HM.HM3.HMType.CNT static private inherited
Definition at line 280 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.HMType.HMType(), and com.cliffc.aa.HM.HM3.HMType.reset().
EQS
final HashMap<HMVar,HMVar> com.cliffc.aa.HM.HM3.HMType.EQS = new HashMap<>() static package inherited
Definition at line 290 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.HMVar._eq(), and com.cliffc.aa.HM.HM3.HMType.eq().
The documentation for this class was generated from the following file:
HM3.java