aa: com.cliffc.aa.HM.HM9 Class Reference
com.cliffc.aa.HM.HM9 Class Reference
Classes
class Apply
class Con
class Dec
class EQ
class EQ0
class Factor
class Field
class Ident
class If
class IsEmpty
class Lambda
class Let
class Mul
class NotNil
class Pair
class Pair1
class PrimSyn
class Root
class Str
class Struct
class Syntax
class T2
class Triple
class VStack
class Worklist
Public Member Functions
String toString ()
Static Public Member Functions
static Root hm (String sprog)
Static Package Functions
[static initializer]
static Root parse (String s)
static void reset ()
static Syntax term ()
Static Package Attributes
static final boolean DEBUG_LEAKS =false
static final boolean DO_GCP = true
static final boolean DO_HM = true
static final HashMap< String, PrimSyn > PRIMSYNS = new HashMap<>()
Static Private Member Functions
static String id ()
static boolean isAlpha0 (byte c)
static boolean isAlpha1 (byte c)
static boolean isDigit (byte c)
static boolean isWS (byte c)
static Syntax number ()
static void require (char c)
static< T > T require (char c, T t)
static void require (String s)
static byte skipWS ()
static Syntax string ()
Static Private Attributes
static byte[] BUF
static final SB ID = new SB()
static int X
Detailed Description
Definition at line 71 of file HM9.java.
Member Function Documentation
[static initializer]()
com.cliffc.aa.HM.HM9.[static initializer] static package
hm()
static Root com.cliffc.aa.HM.HM9.hm (String sprog) static
Definition at line 81 of file HM9.java.
{
     Worklist work = new Worklist();
     PrimSyn.WORK=work;
     for( PrimSyn prim : new PrimSyn[]{new If(), new Pair1(), new Pair(), new EQ(), new EQ0(), new Mul(), new Dec(), new Str(), new Triple(), new Factor(), new IsEmpty(), new NotNil()} )
       PRIMSYNS.put(prim.name(),prim);
     // Parse
     Root prog = parse( sprog );
     // Prep for SSA: pre-gather all the (unique) ids
     int cnt_syns = prog.prep_tree(null,null,work);
     int init_T2s = T2.CNT;
     while( work.len()>0 ) {     // While work
       int oldcnt = T2.CNT;      // Used for cost-check when no-progress
       assert work._cnt<1000;
       Syntax syn = work.pop();  // Get work
       if( DO_HM ) {
         T2 old = syn._hmt;        // Old value for progress assert
         if( syn.hm(work) ) {
           assert !syn.debug_find().unify(old.find(),null);// monotonic: unifying with the result is no-progress
           syn.add_hm_work(work);     // Push affected neighbors on worklist
         } else {
           assert !DEBUG_LEAKS || oldcnt==T2.CNT;  // No-progress consumes no-new-T2s
         }
       }
       if( DO_GCP ) {
         Type old = syn._flow;
         Type t = syn.val(work);
         if( t!=old ) {           // Progress
           assert old.isa(t);     // Monotonic falling
           syn._flow = t;         // Update type
           if( syn._par!=null ) { // Generally, parent needs revisit
             work.push(syn._par); // Assume parent needs revisit
             syn._par.add_val_work(syn,work); // Push affected neighbors on worklist
           }
         }
       }
       // VERY EXPENSIVE ASSERT: O(n^2).  Every Syntax that makes progress is on the worklist
       assert prog.more_work(work);
     }
     assert prog.more_work(work);
     System.out.println("Initial T2s: "+init_T2s+", Prog size: "+cnt_syns+", worklist iters: "+work._cnt+", T2s: "+T2.CNT);
     return prog;
   }
References com.cliffc.aa.HM.HM9.Worklist._cnt, com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.HM.HM9.Syntax._par, com.cliffc.aa.HM.HM9.Syntax.add_hm_work(), com.cliffc.aa.HM.HM9.Syntax.add_val_work(), com.cliffc.aa.HM.HM9.T2.CNT, com.cliffc.aa.HM.HM9.Syntax.debug_find(), com.cliffc.aa.HM.HM9.DEBUG_LEAKS, com.cliffc.aa.HM.HM9.DO_GCP, com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.T2.find(), com.cliffc.aa.HM.HM9.Syntax.hm(), com.cliffc.aa.type.Type< T extends Type< T >.isa(), com.cliffc.aa.HM.HM9.Worklist.len(), com.cliffc.aa.HM.HM9.Apply.more_work(), com.cliffc.aa.HM.HM9.parse(), com.cliffc.aa.HM.HM9.Worklist.pop(), com.cliffc.aa.HM.HM9.Apply.prep_tree(), com.cliffc.aa.HM.HM9.PRIMSYNS, com.cliffc.aa.HM.HM9.Worklist.push(), com.cliffc.aa.HM.HM9.T2.unify(), com.cliffc.aa.HM.HM9.Syntax.val(), and com.cliffc.aa.HM.HM9.PrimSyn.WORK.
Referenced by com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.HM.TestHM9.test05(), com.cliffc.aa.HM.TestHM9.test06(), com.cliffc.aa.HM.TestHM9.test14(), com.cliffc.aa.HM.TestHM9.test18(), com.cliffc.aa.HM.TestHM9.test20(), com.cliffc.aa.HM.TestHM9.test32(), com.cliffc.aa.HM.TestHM9.test33(), com.cliffc.aa.HM.TestHM9.test34(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.HM.TestHM9.test39(), com.cliffc.aa.HM.TestHM9.test40(), com.cliffc.aa.HM.TestHM9.test41(), com.cliffc.aa.HM.TestHM9.test42(), com.cliffc.aa.HM.TestHM9.test43(), com.cliffc.aa.HM.TestHM9.test44(), com.cliffc.aa.HM.TestHM9.test45(), com.cliffc.aa.HM.TestHM9.test49(), and com.cliffc.aa.HM.TestHM9.test50().
id()
static String com.cliffc.aa.HM.HM9.id () static private
Definition at line 224 of file HM9.java.
{
     ID.clear();
     while( X<BUF.length && isAlpha1(BUF[X]) )
       ID.p((char)BUF[X++]);
     String s = ID.toString().intern();
     if( s.length()==0 ) throw unimpl("Missing id");
     return s;
   }
References com.cliffc.aa.HM.HM9.BUF, com.cliffc.aa.util.SB.clear(), com.cliffc.aa.HM.HM9.ID, com.cliffc.aa.HM.HM9.isAlpha1(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.util.SB.toString(), and com.cliffc.aa.HM.HM9.X.
Referenced by com.cliffc.aa.HM.HM9.T2.add_fld(), com.cliffc.aa.HM.HM9.Field.Field(), and com.cliffc.aa.HM.HM9.term().
isAlpha0()
static boolean com.cliffc.aa.HM.HM9.isAlpha0 (byte c) static private
Definition at line 255 of file HM9.java.
 { return ('a'<=c && c <= 'z') || ('A'<=c && c <= 'Z') || (c=='_') || (c=='*') || (c=='?'); }
Referenced by com.cliffc.aa.HM.HM9.isAlpha1(), and com.cliffc.aa.HM.HM9.term().
isAlpha1()
static boolean com.cliffc.aa.HM.HM9.isAlpha1 (byte c) static private
Definition at line 256 of file HM9.java.
 { return isAlpha0(c) || ('0'<=c && c <= '9') || (c=='/'); }
References com.cliffc.aa.HM.HM9.isAlpha0().
Referenced by com.cliffc.aa.HM.HM9.id().
isDigit()
static boolean com.cliffc.aa.HM.HM9.isDigit (byte c) static private
Definition at line 254 of file HM9.java.
 { return '0' <= c && c <= '9'; }
Referenced by com.cliffc.aa.HM.HM9.T2.is_tuple(), com.cliffc.aa.HM.HM9.number(), and com.cliffc.aa.HM.HM9.term().
isWS()
static boolean com.cliffc.aa.HM.HM9.isWS (byte c) static private
Definition at line 253 of file HM9.java.
 { return c == ' ' || c == '\t' || c == '\n' || c == '\r'; }
Referenced by com.cliffc.aa.HM.HM9.skipWS().
number()
static Syntax com.cliffc.aa.HM.HM9.number () static private
Definition at line 232 of file HM9.java.
{
     if( BUF[X]=='0' ) { X++; return new Con(Type.XNIL); }
     int sum=0;
     while( X<BUF.length && isDigit(BUF[X]) )
       sum = sum*10+BUF[X++]-'0';
     if( X>= BUF.length || BUF[X]!='.' )
       return new Con(TypeInt.con(sum));
     X++;
     float f = (float)sum;
     f = f + (BUF[X++]-'0')/10.0f;
     return new Con(TypeFlt.con(f));
   }
References com.cliffc.aa.HM.HM9.BUF, com.cliffc.aa.type.TypeFlt.con(), com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM9.isDigit(), com.cliffc.aa.HM.HM9.X, and com.cliffc.aa.type.Type< T extends Type< T >.XNIL.
Referenced by com.cliffc.aa.HM.HM9.term().
parse()
static Root com.cliffc.aa.HM.HM9.parse (String s) static package
Definition at line 145 of file HM9.java.
{
     X = 0;
     BUF = s.getBytes();
     Syntax prog = term();
     if( skipWS() != -1 ) throw unimpl("Junk at end of program: "+new String(BUF,X,BUF.length-X));
     // Inject IF at root
     return new Root(prog);
   }
References com.cliffc.aa.HM.HM9.BUF, com.cliffc.aa.HM.HM9.skipWS(), com.cliffc.aa.HM.HM9.term(), and com.cliffc.aa.HM.HM9.X.
Referenced by com.cliffc.aa.HM.HM9.hm().
require() [1/3]
static void com.cliffc.aa.HM.HM9.require (char c) static private
Definition at line 257 of file HM9.java.
 { if( skipWS()!=c ) throw unimpl("Missing '"+c+"'"); X++; }
References com.cliffc.aa.HM.HM9.skipWS(), and com.cliffc.aa.HM.HM9.X.
Referenced by com.cliffc.aa.HM.HM9.string(), and com.cliffc.aa.HM.HM9.term().
require() [2/3]
static <T> T com.cliffc.aa.HM.HM9.require (char c, T t) static private
Definition at line 258 of file HM9.java.
 { require(c); return t; }
References com.cliffc.aa.HM.HM9.require().
Referenced by com.cliffc.aa.HM.HM9.require().
require() [3/3]
static void com.cliffc.aa.HM.HM9.require (String s) static private
Definition at line 259 of file HM9.java.
{
     skipWS();
     for( int i=0; i<s.length(); i++ )
       if( X+i >= BUF.length || BUF[X+i]!=s.charAt(i) )
         throw unimpl("Missing '"+s+"'");
     X+=s.length();
   }
References com.cliffc.aa.HM.HM9.BUF, com.cliffc.aa.HM.HM9.skipWS(), and com.cliffc.aa.HM.HM9.X.
reset()
static void com.cliffc.aa.HM.HM9.reset () static package
Definition at line 130 of file HM9.java.
                       {
     BitsAlias.reset_to_init0();
     BitsFun.reset_to_init0();
     PRIMSYNS.clear();
     Pair1.PAIR1S.clear();
     Lambda.FUNS.clear();
     T2.reset();
     PrimSyn.reset();
   }
References com.cliffc.aa.HM.HM9.Lambda.FUNS, com.cliffc.aa.HM.HM9.Pair1.PAIR1S, com.cliffc.aa.HM.HM9.PRIMSYNS, com.cliffc.aa.HM.HM9.PrimSyn.reset(), com.cliffc.aa.HM.HM9.T2.reset(), com.cliffc.aa.type.BitsFun.reset_to_init0(), and com.cliffc.aa.type.BitsAlias.reset_to_init0().
skipWS()
static byte com.cliffc.aa.HM.HM9.skipWS () static private
Definition at line 249 of file HM9.java.
{
     while( X<BUF.length && isWS(BUF[X]) ) X++;
     return X==BUF.length ? -1 : BUF[X];
   }
References com.cliffc.aa.HM.HM9.BUF, com.cliffc.aa.HM.HM9.isWS(), and com.cliffc.aa.HM.HM9.X.
Referenced by com.cliffc.aa.HM.HM9.parse(), com.cliffc.aa.HM.HM9.require(), and com.cliffc.aa.HM.HM9.term().
string()
static Syntax com.cliffc.aa.HM.HM9.string () static private
Definition at line 244 of file HM9.java.
{
     int start = ++X;
     while( X<BUF.length && BUF[X]!='"' ) X++;
     return require('"', new Con(TypeMemPtr.make(BitsAlias.STRBITS,TypeStr.con(new String(BUF,start,X-start).intern()))));
   }
References com.cliffc.aa.HM.HM9.BUF, com.cliffc.aa.type.TypeStr.con(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.HM.HM9.require(), com.cliffc.aa.type.BitsAlias.STRBITS, and com.cliffc.aa.HM.HM9.X.
Referenced by com.cliffc.aa.HM.HM9.term().
term()
static Syntax com.cliffc.aa.HM.HM9.term () static package
Definition at line 153 of file HM9.java.
{
     if( skipWS()==-1 ) return null;
     if( isDigit(BUF[X]) ) return number();
     if( BUF[X]=='"' ) return string();
     if( BUF[X]=='(' ) {         // Parse an Apply
       X++;                      // Skip paren
       Syntax fun = term();
       Ary<Syntax> args = new Ary<>(new Syntax[1],0);
       while( skipWS()!= ')' && X<BUF.length ) args.push(term());
       require(')');
       // Guarding if-nil test inserts an upcast.  This is a syntatic transform only.
       if( fun instanceof If &&
           args.at(0) instanceof Ident ) {
         Ident id = (Ident)args.at(0);
         args.set(1,new Apply(new Lambda(args.at(1), id._name),
                              new Apply(new NotNil(),new Ident(id._name))));
       }
       return new Apply(fun,args.asAry());
     }
     if( BUF[X]=='{' ) {         // Lambda of 1 or 2 args
       X++;                      // Skip paren
       Ary<String> args = new Ary<>(new String[1],0);
       while( skipWS()!='-' ) args.push(id());
       require("->");
       Syntax body = term();
       require('}');
       return new Lambda(body,args.asAry());
     }
     // Let or Id
     if( isAlpha0(BUF[X]) ) {
       String id = id();
       if( skipWS()!='=' ) {
         PrimSyn prim = PRIMSYNS.get(id); // No shadowing primitives or this lookup returns the prim instead of the shadow
         return prim==null ? new Ident(id) : prim.make(); // Make a prim copy with fresh HM variables
       }
       // Let expression; "id = term(); term..."
       X++;                      // Skip '='
       Syntax def = term();
       require(';');
       return new Let(id,def,term());
     }
     // Structure
     if( BUF[X]=='@' ) {
       X++;
       require('{');
       Ary<String>  ids = new Ary<>(String.class);
       Ary<Syntax> flds = new Ary<>(Syntax.class);
       while( skipWS()!='}' && X < BUF.length ) {
         String id = require('=',id());
         Syntax fld = term();
         if( fld==null ) throw unimpl("Missing term for field "+id);
         ids .push( id);
         flds.push(fld);
         if( skipWS()==',' ) X++;
       }
       require('}');
       return new Struct(ids.asAry(),flds.asAry());
     }
     // Field lookup is prefix or backwards: ".x term" instead of "term.x"
     if( BUF[X]=='.' ) {
       X++;
       return new Field(id(),term());
     }
     throw unimpl("Unknown syntax");
   }
References com.cliffc.aa.util.Ary< E >.asAry(), com.cliffc.aa.util.Ary< E >.at(), com.cliffc.aa.HM.HM9.BUF, com.cliffc.aa.HM.HM9.id(), com.cliffc.aa.HM.HM9.isAlpha0(), com.cliffc.aa.HM.HM9.isDigit(), com.cliffc.aa.HM.HM9.PrimSyn.make(), com.cliffc.aa.HM.HM9.number(), com.cliffc.aa.HM.HM9.PRIMSYNS, com.cliffc.aa.util.Ary< E >.push(), com.cliffc.aa.HM.HM9.require(), com.cliffc.aa.util.Ary< E >.set(), com.cliffc.aa.HM.HM9.skipWS(), com.cliffc.aa.HM.HM9.string(), and com.cliffc.aa.HM.HM9.X.
Referenced by com.cliffc.aa.HM.HM9.parse().
toString()
String com.cliffc.aa.HM.HM9.toString ()
Definition at line 144 of file HM9.java.
 { return new String(BUF,X,BUF.length-X); }
References com.cliffc.aa.HM.HM9.BUF, and com.cliffc.aa.HM.HM9.X.
Member Data Documentation
BUF
byte [] com.cliffc.aa.HM.HM9.BUF static private
Definition at line 143 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.id(), com.cliffc.aa.HM.HM9.number(), com.cliffc.aa.HM.HM9.parse(), com.cliffc.aa.HM.HM9.require(), com.cliffc.aa.HM.HM9.skipWS(), com.cliffc.aa.HM.HM9.string(), com.cliffc.aa.HM.HM9.term(), and com.cliffc.aa.HM.HM9.toString().
DEBUG_LEAKS
final boolean com.cliffc.aa.HM.HM9.DEBUG_LEAKS =false static package
Definition at line 75 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.T2.fresh_unify(), and com.cliffc.aa.HM.HM9.hm().
DO_GCP
final boolean com.cliffc.aa.HM.HM9.DO_GCP = true static package
Definition at line 79 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.If.hm(), com.cliffc.aa.HM.HM9.Syntax.more_work_impl(), com.cliffc.aa.HM.HM9.Syntax.p0(), and com.cliffc.aa.HM.HM9.Lambda.p1().
DO_HM
final boolean com.cliffc.aa.HM.HM9.DO_HM = true static package
Definition at line 78 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Syntax.more_work_impl(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM9.Lambda.p1(), and com.cliffc.aa.HM.HM9.Apply.val().
ID
final SB com.cliffc.aa.HM.HM9.ID = new SB() static private
Definition at line 223 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.id().
PRIMSYNS
final HashMap<String,PrimSyn> com.cliffc.aa.HM.HM9.PRIMSYNS = new HashMap<>() static package
Definition at line 73 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.reset(), and com.cliffc.aa.HM.HM9.term().
X
int com.cliffc.aa.HM.HM9.X static private
Definition at line 142 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.id(), com.cliffc.aa.HM.HM9.number(), com.cliffc.aa.HM.HM9.parse(), com.cliffc.aa.HM.HM9.require(), com.cliffc.aa.HM.HM9.skipWS(), com.cliffc.aa.HM.HM9.string(), com.cliffc.aa.HM.HM9.term(), and com.cliffc.aa.HM.HM9.toString().
The documentation for this class was generated from the following file:
HM9.java