aa: com.cliffc.aa.HM.HM9.Struct Class Reference
com.cliffc.aa.HM.HM9.Struct Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Struct (String[] ids, Syntax[] flds)
void add_hm_work (Worklist work)
void add_val_work (Syntax child, Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
Type val (Worklist work)
Package Attributes
final int _alias
final Syntax[] _flds
Type _flow
T2 _hmt
final String[] _ids
VStack _nongen
Syntax _par
Detailed Description
Definition at line 771 of file HM9.java.
Constructor & Destructor Documentation
Struct()
com.cliffc.aa.HM.HM9.Struct.Struct (String[] ids, Syntax[] flds) package
Definition at line 775 of file HM9.java.
{
       _ids=ids;
       _flds=flds;
       // Make a TMP
       _alias = BitsAlias.new_alias(BitsAlias.REC);
     }
References com.cliffc.aa.HM.HM9.Struct._alias, com.cliffc.aa.HM.HM9.Struct._flds, com.cliffc.aa.HM.HM9.Struct._ids, com.cliffc.aa.type.BitsAlias.new_alias(), and com.cliffc.aa.type.BitsAlias.REC.
Member Function Documentation
add_hm_work()
void com.cliffc.aa.HM.HM9.Struct.add_hm_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 835 of file HM9.java.
{
       work.push(_par);
       for( Syntax fld : _flds ) work.push(fld);
     }
References com.cliffc.aa.HM.HM9.Struct._flds, com.cliffc.aa.HM.HM9.Syntax._par, and com.cliffc.aa.HM.HM9.Worklist.push().
add_val_work()
void com.cliffc.aa.HM.HM9.Syntax.add_val_work (Syntax child, Worklist work) package inherited
Reimplemented in com.cliffc.aa.HM.HM9.PrimSyn, com.cliffc.aa.HM.HM9.Apply, com.cliffc.aa.HM.HM9.Let, and com.cliffc.aa.HM.HM9.Lambda.
Definition at line 346 of file HM9.java.
 {} // Add affected neighbors to worklist
Referenced by com.cliffc.aa.HM.HM9.hm().
debug_find()
T2 com.cliffc.aa.HM.HM9.Syntax.debug_find () package inherited
Definition at line 329 of file HM9.java.
 { return _hmt.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM9.Syntax._hmt, and com.cliffc.aa.HM.HM9.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM9.hm().
find()
T2 com.cliffc.aa.HM.HM9.Syntax.find () package inherited
Definition at line 325 of file HM9.java.
               {                 // U-F find
       T2 t = _hmt.find();
       return t== _hmt ? t : (_hmt =t);
     }
References com.cliffc.aa.HM.HM9.Syntax._hmt, and com.cliffc.aa.HM.HM9.T2.find().
Referenced by com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_val_work(), com.cliffc.aa.HM.HM9.Let.add_val_work(), com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Ident.hm(), com.cliffc.aa.HM.HM9.Lambda.hm(), com.cliffc.aa.HM.HM9.Apply.hm(), com.cliffc.aa.HM.HM9.Root.hm(), com.cliffc.aa.HM.HM9.Struct.hm(), com.cliffc.aa.HM.HM9.Field.hm(), com.cliffc.aa.HM.HM9.PrimSyn.hm(), com.cliffc.aa.HM.HM9.If.hm(), com.cliffc.aa.HM.HM9.NotNil.hm(), com.cliffc.aa.HM.HM9.Apply.is_if_nil(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.NotNil.prep_tree(), com.cliffc.aa.HM.HM9.Apply.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
hm()
boolean com.cliffc.aa.HM.HM9.Struct.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 796 of file HM9.java.
{
       boolean progress = false, must_alloc=false;
       // Force result to be a struct with at least these fields.
       // Do not allocate a T2 unless we need to pick up fields.
       T2 rec = find();
       if( rec.is_err() ) return false;
       for( String id : _ids )
         if( Util.find(rec._ids, id) == -1 )
           { must_alloc = true; break; }
       if( must_alloc ) {              // Must allocate.
         if( work==null ) return true; // Will progress
         T2[] t2s = new T2[_ids.length];
         for( int i=0; i<_ids.length; i++ )
           t2s[i] = _flds[i].find();
         T2.make_struct(BitsAlias.make0(_alias),_ids,t2s).unify(rec,work);
         rec=find();
         progress = true;
       }
       // Extra fields are unified with ERR since they are not created here:
       // error to load from a non-existing field
       for( int i=0; i<rec._ids.length; i++ ) {
         if( Util.find(_ids,rec._ids[i])== -1 && !rec.args(i).is_err() ) {
           if( work==null ) return true;
           progress |= rec.args(i).unify(find().miss_field(rec._ids[i]),work);
         }
       }
       // Unify existing fields.  Ignore extras on either side.
       for( int i=0; i<_ids.length; i++ ) {
         int idx = Util.find(rec._ids,_ids[i]);
         if( idx!= -1 ) progress |= rec.args(idx).unify(_flds[i].find(),work);
         if( work==null && progress ) return true;
       }
       rec.push_update(this);
       return progress;
     }
References com.cliffc.aa.HM.HM9.Struct._alias, com.cliffc.aa.HM.HM9.Struct._flds, com.cliffc.aa.HM.HM9.Struct._ids, com.cliffc.aa.HM.HM9.T2._ids, com.cliffc.aa.HM.HM9.T2.args(), com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.HM.HM9.T2.is_err(), com.cliffc.aa.type.BitsAlias.make0(), com.cliffc.aa.HM.HM9.T2.make_struct(), com.cliffc.aa.HM.HM9.T2.push_update(), and com.cliffc.aa.HM.HM9.T2.unify().
more_work()
boolean com.cliffc.aa.HM.HM9.Struct.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 859 of file HM9.java.
{
       if( !more_work_impl(work) ) return false;
       for( Syntax fld : _flds )
         if( !fld.more_work(work) )
           return false;
       return true;
     }
References com.cliffc.aa.HM.HM9.Struct._flds, and com.cliffc.aa.HM.HM9.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM9.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 362 of file HM9.java.
{
       if( work.has(this) ) return true;
       if( DO_HM && hm(null) )   // Any more HM work?
         return false;           // Found HM work not on worklist
       if( DO_GCP && val(null)!=_flow )
         return false;           // Found GCP work not on worklist
       return true;
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.DO_GCP, com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.Worklist.has(), com.cliffc.aa.HM.HM9.Syntax.hm(), and com.cliffc.aa.HM.HM9.Syntax.val().
Referenced by com.cliffc.aa.HM.HM9.Con.more_work(), com.cliffc.aa.HM.HM9.Ident.more_work(), com.cliffc.aa.HM.HM9.Lambda.more_work(), com.cliffc.aa.HM.HM9.Let.more_work(), com.cliffc.aa.HM.HM9.Apply.more_work(), com.cliffc.aa.HM.HM9.Struct.more_work(), com.cliffc.aa.HM.HM9.Field.more_work(), and com.cliffc.aa.HM.HM9.PrimSyn.more_work().
p()
String com.cliffc.aa.HM.HM9.Syntax.p () inherited
Definition at line 374 of file HM9.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM9.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM9.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 375 of file HM9.java.
{
       _hmt.get_dups(dups);
       VBitSet visit = new VBitSet();
       p1(sb.i());
       if( DO_HM  ) _hmt .str(sb.p(", HM="), visit,dups);
       if( DO_GCP ) _flow.str(sb.p(", CCP="),visit.clr(),null,false);
       sb.nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.util.VBitSet.clr(), com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM9.DO_GCP, com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM9.Syntax.p1(), com.cliffc.aa.HM.HM9.Syntax.p2(), com.cliffc.aa.type.Type< T extends Type< T >.str(), and com.cliffc.aa.HM.HM9.T2.str().
Referenced by com.cliffc.aa.HM.HM9.Syntax.p(), com.cliffc.aa.HM.HM9.Lambda.p2(), com.cliffc.aa.HM.HM9.Let.p2(), com.cliffc.aa.HM.HM9.Apply.p2(), com.cliffc.aa.HM.HM9.Struct.p2(), and com.cliffc.aa.HM.HM9.Field.p2().
p1()
SB com.cliffc.aa.HM.HM9.Struct.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 790 of file HM9.java.
 { return sb.p("@{").p(_alias).p(" ... } "); }
References com.cliffc.aa.HM.HM9.Struct._alias, and com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM9.Struct.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 791 of file HM9.java.
{
       for( int i=0; i<_ids.length; i++ )
         _flds[i].p0(sb.i().p(_ids[i]).p(" = ").nl(),dups);
       return sb;
     }
References com.cliffc.aa.HM.HM9.Struct._flds, com.cliffc.aa.HM.HM9.Struct._ids, com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM9.Syntax.p0().
prep_lookup_deps()
void com.cliffc.aa.HM.HM9.Syntax.prep_lookup_deps (Ident id) package inherited
Reimplemented in com.cliffc.aa.HM.HM9.Let, and com.cliffc.aa.HM.HM9.Lambda.
Definition at line 358 of file HM9.java.
 {}
prep_tree()
int com.cliffc.aa.HM.HM9.Struct.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 849 of file HM9.java.
{
       T2[] t2s = new T2[_ids.length];
       prep_tree_impl(par, nongen, work, T2.make_struct(BitsAlias.make0(_alias),_ids,t2s));
       int cnt = 1;              // One for self
       for( int i=0; i<_flds.length; i++ ) { // Prep all sub-fields
         cnt += _flds[i].prep_tree(this,nongen,work);
         t2s[i] = _flds[i].find();
       }
       return cnt;
     }
References com.cliffc.aa.HM.HM9.Struct._alias, com.cliffc.aa.HM.HM9.Struct._flds, com.cliffc.aa.HM.HM9.Struct._ids, com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.type.BitsAlias.make0(), com.cliffc.aa.HM.HM9.T2.make_struct(), com.cliffc.aa.HM.HM9.Syntax.prep_tree(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
prep_tree_impl()
final void com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 351 of file HM9.java.
{
       _par = par;
       _hmt = t;
       _flow= Type.XSCALAR;
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.HM.HM9.Syntax._nongen, com.cliffc.aa.HM.HM9.Syntax._par, com.cliffc.aa.HM.HM9.Worklist.push(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Referenced by com.cliffc.aa.HM.HM9.Con.prep_tree(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), com.cliffc.aa.HM.HM9.Lambda.prep_tree(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Apply.prep_tree(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.Field.prep_tree(), and com.cliffc.aa.HM.HM9.PrimSyn.prep_tree().
str()
SB com.cliffc.aa.HM.HM9.Struct.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 781 of file HM9.java.
{
       sb.p("@{").p(_alias);
       for( int i=0; i<_ids.length; i++ ) {
         sb.p(' ').p(_ids[i]).p(" = ");
         _flds[i].str(sb);
         if( i < _ids.length-1 ) sb.p(',');
       }
       return sb.p("}");
     }
References com.cliffc.aa.HM.HM9.Struct._alias, com.cliffc.aa.HM.HM9.Struct._flds, com.cliffc.aa.HM.HM9.Struct._ids, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM9.Syntax.str().
toString()
final String com.cliffc.aa.HM.HM9.Syntax.toString () inherited
Definition at line 371 of file HM9.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM9.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.HM.HM9.Lambda.p1().
val()
Type com.cliffc.aa.HM.HM9.Struct.val (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 839 of file HM9.java.
{
       TypeFld[] ts = TypeFlds.get(_flds.length+1);
       ts[0] = TypeFld.NO_DISP;
       for( int i=0; i<_flds.length; i++ )
         ts[i+1] = TypeFld.make(_ids[i],_flds[i]._flow,Access.Final,i+1);
       TypeStruct tstr = TypeStruct.make(ts);
       TypeStruct t2 = tstr.approx(1,_alias);
       return TypeMemPtr.make(_alias,t2);
     }
References com.cliffc.aa.HM.HM9.Struct._alias, com.cliffc.aa.HM.HM9.Struct._flds, com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Struct._ids, com.cliffc.aa.type.TypeStruct.approx(), com.cliffc.aa.type.TypeFld.Access.Final, com.cliffc.aa.type.TypeFlds.get(), com.cliffc.aa.type.TypeFld.make(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeStruct.make(), and com.cliffc.aa.type.TypeFld.NO_DISP.
Member Data Documentation
_alias
final int com.cliffc.aa.HM.HM9.Struct._alias package
Definition at line 772 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Struct.hm(), com.cliffc.aa.HM.HM9.Struct.p1(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.Struct.str(), com.cliffc.aa.HM.HM9.Struct.Struct(), and com.cliffc.aa.HM.HM9.Struct.val().
_flds
final Syntax [] com.cliffc.aa.HM.HM9.Struct._flds package
Definition at line 774 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Struct.add_hm_work(), com.cliffc.aa.HM.HM9.Struct.hm(), com.cliffc.aa.HM.HM9.Struct.more_work(), com.cliffc.aa.HM.HM9.Struct.p2(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.Struct.str(), com.cliffc.aa.HM.HM9.Struct.Struct(), and com.cliffc.aa.HM.HM9.Struct.val().
_flow
Type com.cliffc.aa.HM.HM9.Syntax._flow package inherited
Definition at line 332 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Lambda.apply(), com.cliffc.aa.HM.HM9.Pair1.apply(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Pair.apply(), com.cliffc.aa.HM.HM9.Triple.apply(), com.cliffc.aa.HM.HM9.If.apply(), com.cliffc.aa.HM.HM9.EQ.apply(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM9.IsEmpty.apply(), com.cliffc.aa.HM.HM9.NotNil.apply(), com.cliffc.aa.HM.HM9.Mul.apply(), com.cliffc.aa.HM.HM9.Dec.apply(), com.cliffc.aa.HM.HM9.Str.apply(), com.cliffc.aa.HM.HM9.Factor.apply(), com.cliffc.aa.HM.HM9.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Lambda.Lambda(), com.cliffc.aa.HM.HM9.Syntax.more_work_impl(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM9.Ident.val(), com.cliffc.aa.HM.HM9.Let.val(), com.cliffc.aa.HM.HM9.Apply.val(), com.cliffc.aa.HM.HM9.Root.val(), com.cliffc.aa.HM.HM9.Struct.val(), com.cliffc.aa.HM.HM9.Field.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
_hmt
T2 com.cliffc.aa.HM.HM9.Syntax._hmt package inherited
Definition at line 324 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Syntax.debug_find(), com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.PrimSyn.prep_tree(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM9.PrimSyn.PrimSyn().
_ids
final String [] com.cliffc.aa.HM.HM9.Struct._ids package
Definition at line 773 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Struct.hm(), com.cliffc.aa.HM.HM9.Struct.p2(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.Struct.str(), com.cliffc.aa.HM.HM9.Struct.Struct(), and com.cliffc.aa.HM.HM9.Struct.val().
_nongen
VStack com.cliffc.aa.HM.HM9.Syntax._nongen package inherited
Definition at line 323 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.add_hm_work(), com.cliffc.aa.HM.HM9.Ident.hm(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM9.Syntax._par package inherited
Definition at line 322 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.Apply.add_hm_work(), com.cliffc.aa.HM.HM9.Struct.add_hm_work(), com.cliffc.aa.HM.HM9.Field.add_hm_work(), com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM9.java