aa: com.cliffc.aa.TestLive Class Reference
com.cliffc.aa.TestLive Class Reference
Public Member Functions
void testBasic ()
void testNewObj ()
Detailed Description
Definition at line 12 of file TestLive.java.
Member Function Documentation
testBasic()
void com.cliffc.aa.TestLive.testBasic ()
Definition at line 13 of file TestLive.java.
{
     GVNGCM gvn = new GVNGCM();
     gvn._opt_mode = GVNGCM.Mode.PesiNoCG;
     // Liveness is a backwards flow.  Scope always demands all return results.
     ScopeNode scope = new ScopeNode(null,false);
     Node fullmem = new ConNode<>(TypeMem.FULL);
     fullmem._val = TypeMem.FULL;
     scope.set_mem(fullmem);
     // Return the number '5' - should be alive with no special memory.
     Node rez = new ConNode<>(TypeInt.con(5));
     rez._val = TypeInt.con(5);
     scope.set_rez(rez);
     // Check liveness base case
     scope.xliv(gvn._opt_mode);
     assertEquals(TypeMem.ANYMEM,scope._live);
     // Check liveness recursive back one step
     rez.xliv(GVNGCM.Mode.PesiCG);
     assertEquals(TypeMem.ESCAPE,rez._live);
   }
References com.cliffc.aa.node.Node._live, com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.node.Node._val, com.cliffc.aa.type.TypeMem.ANYMEM, com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.type.TypeMem.ESCAPE, com.cliffc.aa.type.TypeMem.FULL, com.cliffc.aa.GVNGCM.Mode.PesiCG, com.cliffc.aa.GVNGCM.Mode.PesiNoCG, com.cliffc.aa.node.ScopeNode.set_mem(), com.cliffc.aa.node.ScopeNode.set_rez(), and com.cliffc.aa.node.Node.xliv().
testNewObj()
void com.cliffc.aa.TestLive.testNewObj ()
Definition at line 39 of file TestLive.java.
{
     Env env = Env.top_scope();
     GVNGCM gvn = Env.GVN;
     Node._INIT0_CNT = 1; // No prims
     // Always memory for the NewObj
     Node mmm = new ConNode<>(TypeMem.ANYMEM).keep();
     mmm._val = TypeMem.ANYMEM;
     // Fields
     Type ti5 = TypeInt.con(5);
     ConNode fdx = new ConNode(ti5);
     fdx._val = ti5;
     Type ti9 = TypeInt.con(9);
     ConNode<Type> fdy = new ConNode<>(ti9);
     fdy._val = ti9;
     // New object, fields x,y holding ints
     NewObjNode nnn = new NewObjNode(false,TypeMemPtr.DISPLAY,Node.con(Type.NIL));
     nnn.create_active("x",fdx,Access.Final);
     nnn.create_active("y",fdy,Access.Final);
     nnn._val = Type.ANY;
     nnn.no_more_fields();
     nnn.xval();
     nnn._live = TypeMem.LIVE_BOT;
     // Proj, OProj
     Node mem = new MrgProjNode(nnn,mmm);
     mem.xval();
     Node ptr = new  ProjNode(REZ_IDX, nnn);
     ptr.xval();
     // Use the object for scope exit
     ScopeNode scope = new ScopeNode(null,false);
     scope.set_mem(mem);
     scope.set_rez(ptr);
     scope._val = Type.ALL;
     // Check 'live' is stable on creation, except for mem & scope
     // which are 'turning around' liveness.
     // Value was computed in a forwards flow.
     for( Node n : new Node[]{mmm,fdx,fdy,nnn,mem,ptr,scope} ) {
       if( n != mem && n != scope )
         assertTrue(n.live(gvn._opt_mode).isa(n._live));
       assertEquals(n._val,n.value(gvn._opt_mode));
     }
     // Check liveness base case
     scope.xliv(GVNGCM.Mode.PesiNoCG);
     // Since simple forwards-flow, the default memory is known UNUSED.
     // However, we got provided at least one object.
     TypeMem expected_live = ((TypeMem) mem._val).flatten_fields();
     assertEquals(scope._live,expected_live);
     // Check liveness recursive back one step
     ptr.xliv(GVNGCM.Mode.PesiNoCG);
     assertEquals(TypeMem.ESCAPE,ptr._live); // Ptr is all_type, conservative so all memory alive
     mem.xliv(GVNGCM.Mode.PesiNoCG);
     assertEquals(mem._live,expected_live); // Object demands of OProj, but OProj passes along request to NewObj
     nnn.xliv(GVNGCM.Mode.PesiNoCG);
     assertEquals(expected_live,nnn._live); // NewObj supplies object, needs what its input needs
     mmm.xliv(GVNGCM.Mode.PesiNoCG);
     assertEquals(TypeMem.ALIVE,mmm._live); // Since ptr is scalar, all memory is alive
     fdx.xliv(GVNGCM.Mode.PesiNoCG);
     assertEquals(TypeMem.ESCAPE,fdx._live); // Since ptr is scalar, all memory is alive
   }
References com.cliffc.aa.node.Node._INIT0_CNT, com.cliffc.aa.node.Node._live, com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.node.Node._val, com.cliffc.aa.type.TypeMem.ALIVE, com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.type.TypeMem.ANYMEM, com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.NewObjNode.create_active(), com.cliffc.aa.type.TypeMemPtr.DISPLAY, com.cliffc.aa.type.TypeMem.ESCAPE, com.cliffc.aa.type.TypeFld.Access.Final, com.cliffc.aa.type.TypeMem.flatten_fields(), com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.keep(), com.cliffc.aa.type.TypeMem.LIVE_BOT, com.cliffc.aa.type.Type< T extends Type< T >.NIL, com.cliffc.aa.node.NewObjNode.no_more_fields(), com.cliffc.aa.GVNGCM.Mode.PesiNoCG, com.cliffc.aa.node.ScopeNode.set_mem(), com.cliffc.aa.node.ScopeNode.set_rez(), com.cliffc.aa.Env.top_scope(), com.cliffc.aa.node.Node.xliv(), and com.cliffc.aa.node.Node.xval().
The documentation for this class was generated from the following file:
TestLive.java