aa: com.cliffc.aa.TestLattice.N Class Reference
com.cliffc.aa.TestLattice.N Class Reference
Public Member Functions
String toString ()
Package Functions
N (String t, N... subs)
void set_dual (N d)
boolean walk_dual (BitSet bs)
boolean walk_min_edge (int[] vs, N sup)
void walk_print (BitSet bs, int indent)
void walk_set_sup (BitSet bs)
Static Package Functions
static void reset ()
Package Attributes
int _cnt
N _dual
final int _id
final BitSet _reaches
final Ary< N > _subs
final Ary< N > _sups
final String _t
Static Package Attributes
static Ary< N > NS =new Ary<>(new N[1],0)
Static Private Attributes
static int ID =0
Detailed Description
Definition at line 80 of file TestLattice.java.
Constructor & Destructor Documentation
N()
com.cliffc.aa.TestLattice.N.N (String t, N... subs) package
Definition at line 91 of file TestLattice.java.
{
       _id = ID++;
       _t=t;
       _subs = new Ary<>(subs);
       _sups = new Ary<>(new N[1],0); // Fill in later
       _reaches = new BitSet();
       _dual = this;
       NS.add(this);
     }
References com.cliffc.aa.TestLattice.N._dual, com.cliffc.aa.TestLattice.N._id, com.cliffc.aa.TestLattice.N._reaches, com.cliffc.aa.TestLattice.N._subs, com.cliffc.aa.TestLattice.N._sups, com.cliffc.aa.TestLattice.N._t, com.cliffc.aa.TestLattice.N.ID, and com.cliffc.aa.TestLattice.N.NS.
Member Function Documentation
reset()
static void com.cliffc.aa.TestLattice.N.reset () static package
Definition at line 83 of file TestLattice.java.
 { NS.clear(); ID=0; }
References com.cliffc.aa.TestLattice.N.ID, and com.cliffc.aa.TestLattice.N.NS.
Referenced by com.cliffc.aa.TestLattice.testLattice0(), com.cliffc.aa.TestLattice.testLattice1(), com.cliffc.aa.TestLattice.testLattice10(), com.cliffc.aa.TestLattice.testLattice11(), com.cliffc.aa.TestLattice.testLattice12(), com.cliffc.aa.TestLattice.testLattice12a(), com.cliffc.aa.TestLattice.testLattice12b(), com.cliffc.aa.TestLattice.testLattice12d(), com.cliffc.aa.TestLattice.testLattice13(), com.cliffc.aa.TestLattice.testLattice14(), com.cliffc.aa.TestLattice.testLattice15(), com.cliffc.aa.TestLattice.testLattice16(), com.cliffc.aa.TestLattice.testLattice17(), com.cliffc.aa.TestLattice.testLattice2(), com.cliffc.aa.TestLattice.testLattice3(), com.cliffc.aa.TestLattice.testLattice4(), com.cliffc.aa.TestLattice.testLattice5(), com.cliffc.aa.TestLattice.testLattice6(), com.cliffc.aa.TestLattice.testLattice6_1(), com.cliffc.aa.TestLattice.testLattice7(), com.cliffc.aa.TestLattice.testLattice8(), and com.cliffc.aa.TestLattice.testLattice9().
set_dual()
void com.cliffc.aa.TestLattice.N.set_dual (N d) package
Definition at line 100 of file TestLattice.java.
{
       assert _dual==this && d._dual==d;
       _dual=d; d._dual=this;
     }
References com.cliffc.aa.TestLattice.N._dual.
Referenced by com.cliffc.aa.TestLattice.testLattice0(), com.cliffc.aa.TestLattice.testLattice1(), com.cliffc.aa.TestLattice.testLattice10(), com.cliffc.aa.TestLattice.testLattice11(), com.cliffc.aa.TestLattice.testLattice12(), com.cliffc.aa.TestLattice.testLattice12a(), com.cliffc.aa.TestLattice.testLattice12b(), com.cliffc.aa.TestLattice.testLattice12d(), com.cliffc.aa.TestLattice.testLattice13(), com.cliffc.aa.TestLattice.testLattice14(), com.cliffc.aa.TestLattice.testLattice15(), com.cliffc.aa.TestLattice.testLattice16(), com.cliffc.aa.TestLattice.testLattice17(), com.cliffc.aa.TestLattice.testLattice2(), com.cliffc.aa.TestLattice.testLattice3(), com.cliffc.aa.TestLattice.testLattice4(), com.cliffc.aa.TestLattice.testLattice5(), com.cliffc.aa.TestLattice.testLattice6(), com.cliffc.aa.TestLattice.testLattice6_1(), com.cliffc.aa.TestLattice.testLattice7(), com.cliffc.aa.TestLattice.testLattice8(), and com.cliffc.aa.TestLattice.testLattice9().
toString()
String com.cliffc.aa.TestLattice.N.toString ()
Definition at line 118 of file TestLattice.java.
{
       SB sb = new SB().p(_t).p(" -> ");
       for( N sub : _subs ) sb.p(sub._t).p(" ");
       return sb.toString();
     }
References com.cliffc.aa.TestLattice.N._subs, com.cliffc.aa.TestLattice.N._t, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.TestLattice.N.walk_print().
walk_dual()
boolean com.cliffc.aa.TestLattice.N.walk_dual (BitSet bs) package
Definition at line 140 of file TestLattice.java.
{
       if( bs.get(_id) ) return true;
       bs.set(_id);
       boolean x=true;
       for( N sub : _subs ) {
         if( sub._dual._subs.find(_dual) == -1 ) {
           System.out.println(""+_t+" -> "+sub._t+"; expect "+sub._dual._t+" -> "+_dual._t);
           x = false;
         }
       }
       for( N sub : _subs ) if( !sub.walk_dual(bs) ) x=false;
       return x;
     }
References com.cliffc.aa.TestLattice.N._dual, com.cliffc.aa.TestLattice.N._id, com.cliffc.aa.TestLattice.N._subs, and com.cliffc.aa.TestLattice.N._t.
Referenced by com.cliffc.aa.TestLattice.test().
walk_min_edge()
boolean com.cliffc.aa.TestLattice.N.walk_min_edge (int[] vs, N sup) package
Definition at line 124 of file TestLattice.java.
{
       vs[_id]++;
       if( sup != null ) {
         for( N sup0 : _sups )
           if( sup._reaches.get(sup0._id) ) {
             System.out.println("Edge "+sup0._t+" -> "+_t+" and also path "+sup0._t+" ... -> "+sup._t+" -> "+_t);
             return false;
           }
         _reaches.or(sup._reaches);
       }
       if( vs[_id]<_sups._len ) return true; // Pre-order still; return
       for( N sup0 : _sups ) _reaches.set(sup0._id); // Post-order: add all supers in
       for( N sub : _subs ) if( !sub.walk_min_edge(vs,this) ) return false;
       return true;
     }
References com.cliffc.aa.TestLattice.N._id, com.cliffc.aa.TestLattice.N._reaches, com.cliffc.aa.TestLattice.N._subs, com.cliffc.aa.TestLattice.N._sups, and com.cliffc.aa.TestLattice.N._t.
Referenced by com.cliffc.aa.TestLattice.test().
walk_print()
void com.cliffc.aa.TestLattice.N.walk_print (BitSet bs, int indent) package
Definition at line 112 of file TestLattice.java.
{
       if( bs.get(_id) ) return;
       bs.set(_id);
       System.out.println(new SB().i(indent).toString()+toString());
       for( N sub : _subs ) sub.walk_print(bs,indent+1);
     }
References com.cliffc.aa.TestLattice.N._id, com.cliffc.aa.TestLattice.N._subs, and com.cliffc.aa.TestLattice.N.toString().
Referenced by com.cliffc.aa.TestLattice.test().
walk_set_sup()
void com.cliffc.aa.TestLattice.N.walk_set_sup (BitSet bs) package
Definition at line 105 of file TestLattice.java.
{
       if( bs.get(_id) ) return;
       bs.set(_id);
       for( N sub : _subs ) sub._sups.add(this);
       for( N sub : _subs ) sub.walk_set_sup(bs);
     }
References com.cliffc.aa.TestLattice.N._id, and com.cliffc.aa.TestLattice.N._subs.
Referenced by com.cliffc.aa.TestLattice.test().
Member Data Documentation
_cnt
int com.cliffc.aa.TestLattice.N._cnt package
Definition at line 89 of file TestLattice.java.
Referenced by com.cliffc.aa.TestLattice.test().
_dual
N com.cliffc.aa.TestLattice.N._dual package
Definition at line 90 of file TestLattice.java.
Referenced by com.cliffc.aa.TestLattice.N.N(), com.cliffc.aa.TestLattice.N.set_dual(), and com.cliffc.aa.TestLattice.N.walk_dual().
_id
final int com.cliffc.aa.TestLattice.N._id package
Definition at line 84 of file TestLattice.java.
Referenced by com.cliffc.aa.TestLattice.N.N(), com.cliffc.aa.TestLattice.test(), com.cliffc.aa.TestLattice.N.walk_dual(), com.cliffc.aa.TestLattice.N.walk_min_edge(), com.cliffc.aa.TestLattice.N.walk_print(), and com.cliffc.aa.TestLattice.N.walk_set_sup().
_reaches
final BitSet com.cliffc.aa.TestLattice.N._reaches package
Definition at line 88 of file TestLattice.java.
Referenced by com.cliffc.aa.TestLattice.N.N(), com.cliffc.aa.TestLattice.test(), and com.cliffc.aa.TestLattice.N.walk_min_edge().
_subs
final Ary<N> com.cliffc.aa.TestLattice.N._subs package
Definition at line 86 of file TestLattice.java.
Referenced by com.cliffc.aa.TestLattice.N.N(), com.cliffc.aa.TestLattice.test(), com.cliffc.aa.TestLattice.N.toString(), com.cliffc.aa.TestLattice.N.walk_dual(), com.cliffc.aa.TestLattice.N.walk_min_edge(), com.cliffc.aa.TestLattice.N.walk_print(), and com.cliffc.aa.TestLattice.N.walk_set_sup().
_sups
final Ary<N> com.cliffc.aa.TestLattice.N._sups package
Definition at line 87 of file TestLattice.java.
Referenced by com.cliffc.aa.TestLattice.N.N(), and com.cliffc.aa.TestLattice.N.walk_min_edge().
_t
final String com.cliffc.aa.TestLattice.N._t package
Definition at line 85 of file TestLattice.java.
Referenced by com.cliffc.aa.TestLattice.N.N(), com.cliffc.aa.TestLattice.test(), com.cliffc.aa.TestLattice.N.toString(), com.cliffc.aa.TestLattice.N.walk_dual(), and com.cliffc.aa.TestLattice.N.walk_min_edge().
ID
int com.cliffc.aa.TestLattice.N.ID =0 static private
Definition at line 81 of file TestLattice.java.
Referenced by com.cliffc.aa.TestLattice.N.N(), com.cliffc.aa.TestLattice.N.reset(), and com.cliffc.aa.TestLattice.test().
NS
Ary<N> com.cliffc.aa.TestLattice.N.NS =new Ary<>(new N[1],0) static package
Definition at line 82 of file TestLattice.java.
Referenced by com.cliffc.aa.TestLattice.N.N(), com.cliffc.aa.TestLattice.N.reset(), and com.cliffc.aa.TestLattice.test().
The documentation for this class was generated from the following file:
TestLattice.java