aa: com.cliffc.aa.type.Type< T extends Type< T > Class Template Reference
com.cliffc.aa.type.Type< T extends Type< T > Class Template Reference
an implementation of language AA
Classes
class Key
class Pool
Public Member Functions
boolean above (Type t)
boolean above_center ()
final boolean contains (Type t)
boolean cycle_equals (Type t)
final T dual ()
boolean equals (Object o)
double getd ()
long getl ()
String getstr ()
boolean has_name ()
final int hashCode ()
Type high ()
boolean is_con ()
boolean is_display_ptr ()
boolean is_forward_ref ()
boolean isa (Type t)
final boolean isa_scalar ()
byte isBitShape (Type t)
Type join (Type t)
Type make_from (Type head, TypeMem map, VBitSet visit)
boolean may_be_con ()
boolean may_nil ()
final Type meet (Type t)
Type meet_loop (Type t2)
Type meet_nil (Type nil)
boolean must_nil ()
Type oob ()
Type oob (Type e)
TypeMem oob (TypeMem e)
TypeMemPtr oob (TypeMemPtr e)
TypeObj oob (TypeObj e)
TypeStruct oob (TypeStruct e)
Type oob_deep (Type t)
Type oop_deep_impl (Type t)
final T remove_name ()
final T set_name (String name)
Type sharptr (Type ptr)
Type simple_ptr ()
SB str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
final String toString ()
void walk (Predicate< Type > p)
Type widen ()
Static Public Member Functions
static Ary< Type > ALL_TYPES ()
static boolean eq (Type[] t0, Type[] t1)
static void init0 (HashMap< String, Type > types)
static boolean intern_check ()
Public Attributes
int _hash
String _name
int _uid
Static Public Attributes
static final Type ALL = make(TALL)
static final Type ANY = make(TANY)
static final Type CTRL = make(TCTRL)
static final Type NIL = make(TNIL)
static final Type NSCALR = make(TNSCALR)
static final Type REAL = make(TREAL)
static int RECURSIVE_MEET
static final Type SCALAR = make(TSCALAR)
static final Type XCTRL = make(TXCTRL)
static final Type XNIL = make(TXNIL)
static final Type XNSCALR = make(TXNSCALR)
static final Type XSCALAR = make(TXSCALAR)
Protected Member Functions
Type ()
Type clone ()
T init (byte type, String name)
Type xmeet (Type t)
Package Functions
int compute_hash ()
boolean contains (Type t, VBitSet bs)
final Type cross_nil (Type t)
final T hashcons_free ()
boolean intern_check1 ()
Type intern_lookup ()
boolean interned ()
boolean is_display ()
final String mtname (Type t, Type mt)
Type not_nil ()
T rdual ()
TypeStruct repeats_in_cycles (TypeStruct head, VBitSet bs)
final T retern ()
RuntimeException typerr (Type t)
final T untern ()
T xdual ()
Static Package Functions
[static initializer]
static boolean check_name (String n)
static boolean check_startup ()
static void concat (Ary< Type > ts, Type[] ts1)
static Type intern_find (int uid)
static int intern_size ()
static Type make (byte type)
Package Attributes
T _dual
byte _type
Static Package Attributes
static final Type NREAL = make(TNREAL)
static final Pool[] POOLS = new Pool[TLAST]
static final byte TALL = 0
static final byte TANY = 1
static final byte TARY =21
static final byte TCTRL = 2
static final byte TFLD =23
static final byte TFLT =16
static final byte TFUNPTR =26
static final byte TFUNSIG =27
static final byte TINT =15
static final byte TLAST =29
static final byte TLIVE =28
static final byte TMEM =24
static final byte TMEMPTR =25
static final byte TNIL =12
static final byte TNREAL =10
static final byte TNSCALR = 6
static final byte TOBJ =19
static final byte TREAL = 8
static final byte TRPC =17
static final byte TSCALAR = 4
static final byte TSIMPLE =14
static final byte TSTR =22
static final byte TSTRUCT =20
static final byte TTUPLE =18
static final byte TXCTRL = 3
static final byte TXNIL =13
static final byte TXNREAL =11
static final byte TXNSCALR = 7
static final byte TXREAL = 9
static final byte TXSCALAR = 5
Private Member Functions
T _set_name (String name)
int _uid ()
boolean check_commute (Type t, Type mt)
boolean check_symmetric (Type t, Type mt)
T hashcons ()
boolean intern_check0 (Type v)
boolean is_num ()
boolean is_ptr ()
boolean is_simple ()
Type xmt_name (Type t, Type mt)
Static Private Attributes
static Ary< Type > ALL_TYPES
static int CNT =1
static final ConcurrentHashMap< Type, Type > INTERN = new ConcurrentHashMap<>()
static final byte[] ISA_SCALAR = new byte[]{0,0,0,0,1,1,1,1,1,1,1,1,1,1,0, 1,1,1,0,0,0,0,0,0,0,1,1,0,0}
static Type[] SCALAR_PRIMS
static final String[] STRS = new String[]{"all","any","Ctrl","~Ctrl","Scalar","~Scalar","nScalar","~nScalar","Real","~Real","nReal","~nReal","nil","0"}
static final Type[] TYPES = new Type[]{ALL,CTRL,SCALAR,NSCALR,REAL,NREAL}
static final Type XNREAL = make(TXNREAL)
static final Type XREAL = make(TXREAL)
Detailed Description
an implementation of language AA
Definition at line 94 of file Type.java.
Constructor & Destructor Documentation
Type()
com.cliffc.aa.type.Type< T extends Type< T >.Type () protected
Definition at line 102 of file Type.java.
 { _uid = _uid(); }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.clone(), com.cliffc.aa.type.Type< TypeFlt >.equals(), and com.cliffc.aa.type.Type< TypeFlt >.xdual().
Member Function Documentation
[static initializer]()
com.cliffc.aa.type.Type< T extends Type< T >.[static initializer] static package
_set_name()
T com.cliffc.aa.type.Type< T extends Type< T >._set_name (String name) private
Definition at line 558 of file Type.java.
{
     POOLS[_type]._clone++;
     T t1 = (T)clone();
     t1._name = name;
     return t1.hashcons_free();
   }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.remove_name(), and com.cliffc.aa.type.Type< TypeFlt >.set_name().
_uid()
int com.cliffc.aa.type.Type< T extends Type< T >._uid () private
Definition at line 103 of file Type.java.
 { return CNT++; }
above()
boolean com.cliffc.aa.type.Type< T extends Type< T >.above (Type< T extends Type< T > t)
Definition at line 625 of file Type.java.
 { return t != this && meet(t)==t; }
above_center()
boolean com.cliffc.aa.type.Type< T extends Type< T >.above_center ()
Definition at line 741 of file Type.java.
{
     switch( _type ) {
     case TALL:
     case TCTRL:
     case TREAL:   case TNREAL:
     case TSCALAR: case TNSCALR:
     case TNIL:
       return false;             // These are all below center
     case TANY:
     case TXCTRL:
     case TXREAL:   case TXNREAL:
     case TXSCALAR: case TXNSCALR:
     case TXNIL:
       return true;              // These are all above center
     default: throw typerr(null);// Overridden in subclass
     }
   }
Referenced by com.cliffc.aa.node.MemPrimNode.LValueLength._live_use(), com.cliffc.aa.node.LoadNode._live_use(), com.cliffc.aa.type.TypeFunPtr.above_center(), com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM9.If.apply(), com.cliffc.aa.HM.HM.If.apply(), com.cliffc.aa.HM.HM9.EQ.apply(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM.EQ.apply(), com.cliffc.aa.HM.HM9.IsEmpty.apply(), com.cliffc.aa.HM.HM.EQ0.apply(), com.cliffc.aa.HM.HM.IsEmpty.apply(), com.cliffc.aa.HM.HM9.Mul.apply(), com.cliffc.aa.HM.HM.Mul.apply(), com.cliffc.aa.HM.HM.Add.apply(), com.cliffc.aa.HM.HM9.Dec.apply(), com.cliffc.aa.HM.HM9.Str.apply(), com.cliffc.aa.HM.HM.Dec.apply(), com.cliffc.aa.HM.HM9.Factor.apply(), com.cliffc.aa.HM.HM.Str.apply(), com.cliffc.aa.HM.HM.Factor.apply(), com.cliffc.aa.node.ScopeNode.compute_live_mem(), com.cliffc.aa.node.FunNode.find_type_split_index(), com.cliffc.aa.node.CEProjNode.good_call(), com.cliffc.aa.type.Type< TypeFlt >.high(), com.cliffc.aa.HM.HM9.If.hm(), com.cliffc.aa.HM.HM.If.hm(), com.cliffc.aa.node.StoreNode.ideal_reduce(), com.cliffc.aa.type.Type< TypeFlt >.isBitShape(), com.cliffc.aa.node.PhiNode.live_use(), com.cliffc.aa.node.NewObjNode.live_use(), com.cliffc.aa.node.CallEpiNode.live_use(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.node.CallNode.live_use_call(), com.cliffc.aa.type.Type< TypeFlt >.mtname(), com.cliffc.aa.type.Type< TypeFlt >.oob(), com.cliffc.aa.HM.HM9.Apply.val(), com.cliffc.aa.HM.HM.Apply.val(), com.cliffc.aa.HM.HM.Root.val(), com.cliffc.aa.HM.HM9.Field.val(), com.cliffc.aa.HM.HM.Field.val(), com.cliffc.aa.node.IfNode.value(), com.cliffc.aa.node.NewStrNode.AddStrStr.value(), com.cliffc.aa.node.StoreNode.value(), com.cliffc.aa.node.PrimNode.value(), com.cliffc.aa.node.PrimNode.AndI64.value(), com.cliffc.aa.node.PrimNode.OrI64.value(), com.cliffc.aa.node.PrimNode.EQ_OOP.value(), com.cliffc.aa.node.PrimNode.NE_OOP.value(), com.cliffc.aa.node.PrimNode.RandI64.value(), com.cliffc.aa.node.NewStrNode.ConvertI64Str.valueobj(), com.cliffc.aa.node.NewStrNode.ConvertF64Str.valueobj(), com.cliffc.aa.node.PrimNode.EQ_OOP.vs_nil(), and com.cliffc.aa.type.Type< TypeFlt >.xmt_name().
ALL_TYPES()
static Ary<Type> com.cliffc.aa.type.Type< T extends Type< T >.ALL_TYPES () static
Definition at line 651 of file Type.java.
{
     if( ALL_TYPES != null ) return ALL_TYPES;
     Ary<Type> ts = new Ary<>(new Type[1],0);
     concat(ts,Type      .TYPES);
     concat(ts,TypeFlt   .TYPES);
     concat(ts,TypeFunPtr.TYPES);
     concat(ts,TypeFunSig.TYPES);
     concat(ts,TypeInt   .TYPES);
     concat(ts,TypeLive  .TYPES);
     concat(ts,TypeMem   .TYPES);
     concat(ts,TypeMemPtr.TYPES);
     concat(ts,TypeObj   .TYPES);
     concat(ts,TypeRPC   .TYPES);
     concat(ts,TypeStr   .TYPES);
     concat(ts,TypeStruct.TYPES);
     concat(ts,TypeTuple .TYPES);
     concat(ts,TypeAry   .TYPES);
     // Partial order Sort, makes for easier tests later.  Arrays.sort requires
     // a total order (i.e., the obvious Comparator breaks the sort contract),
     // so we hand-roll a simple bubble sort.
     for( int i=0; i<ts._len; i++ )
       for( int j=i+1; j<ts._len; j++ )
         if( ts._es[j].isa(ts._es[i]) ) { Type tmp = ts._es[i]; ts._es[i] = ts._es[j]; ts._es[j] = tmp; }
     return (ALL_TYPES = ts); // Preserve for tests
   }
check_commute()
boolean com.cliffc.aa.type.Type< T extends Type< T >.check_commute (Type< T extends Type< T > t, Type< T extends Type< T > mt) private
Definition at line 593 of file Type.java.
{
     if( t==this ) return true;
     if( is_simple() && !t.is_simple() ) return true; // By design, flipped the only allowed order
     Type mt2 = t.xmeet(this);   // Reverse args and try again
     // Also reverse names.
     Type nmt2 = t.xmt_name(this,mt2);
     if( mt==nmt2 ) return true;
     System.out.println("Meet not commutative: "+this+".meet("+t+")="+mt+",\n but "+t+".meet("+this+")="+nmt2);
     return false;
   }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.check_startup().
check_name()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.check_name (String n) static package
Definition at line 548 of file Type.java.
 { return n.isEmpty() || n.charAt(n.length()-1)==':'; }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.mtname(), and com.cliffc.aa.type.Type< TypeFlt >.set_name().
check_startup()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.check_startup () static package
Definition at line 684 of file Type.java.
{
     Type[] ts = ALL_TYPES().asAry();
     // Confirm commutative & complete
     for( Type t0 : ts )
       for( Type t1 : ts ) {
         Type mt = t0.meet(t1);
         assert t0.check_commute  (t1,mt);
         assert t0.check_symmetric(t1,mt);
       }
     // Confirm associative
     int errs=0;
     for( Type t0 : ts )
       for( Type t1 : ts )
         for( Type t2 : ts ) {
           Type t01   = t0 .meet(t1 );
           Type t12   = t1 .meet(t2 );
           Type t01_2 = t01.meet(t2 );
           Type t0_12 = t0 .meet(t12);
           if( t01_2 != t0_12 && errs++ < 10 )
             System.err.println("("+t0+"&"+t1+") & "+t2+" == "+t0+" & ("+t1+" & "+t2+"); "+
                                "("+t01      +") & "+t2+" == "+t0+" & ("+t12        +"); "+
                                t01_2                  +" == "+t0_12);
         }
     assert errs==0 : "Found "+errs+" associative errors";
     // Confirm symmetry.  If A isa B, then A.join(C) isa B.join(C)
     for( Type t0 : ts )
       for( Type t1 : ts ) {
         if( t0.isa(t1) ) {
           for( Type t2 : ts ) {
             Type t02 = t0.join(t2);
             Type t12 = t1.join(t2);
             Type mt  = t02.meet(t12);
             if( mt != t12 && errs++ < 10 ) {
               System.err.println("("+t0+" ^ "+t2+") = "+t02+"; "+
                                  "("+t1+" ^ "+t2+") = "+t12+"; "+
                                  "their meet = "+mt+" which is not "+t12);
             }
           }
         }
       }
     assert errs==0 : "Found "+errs+" non-join-type errors";
     // Check scalar primitives; all are SCALARS and none sub-type each other.
     SCALAR_PRIMS = new Type[] { TypeInt.INT64, TypeFlt.FLT64, TypeMemPtr.OOP0, TypeFunPtr.GENERIC_FUNPTR, TypeRPC.ALL_CALL };
     for( Type t : SCALAR_PRIMS ) assert t.isa(SCALAR);
     for( int i=0; i<SCALAR_PRIMS.length; i++ )
       for( int j=i+1; j<SCALAR_PRIMS.length; j++ )
         assert !SCALAR_PRIMS[i].isa(SCALAR_PRIMS[j]);
     return true;
   }
Referenced by com.cliffc.aa.type.TestType.testCommuteSymmetricAssociative().
check_symmetric()
boolean com.cliffc.aa.type.Type< T extends Type< T >.check_symmetric (Type< T extends Type< T > t, Type< T extends Type< T > mt) private
Definition at line 608 of file Type.java.
{
     if( t==this ) return true;
     Type ta = mt._dual.meet(t._dual);
     Type tb = mt._dual.meet(  _dual);
     if( ta==t._dual && tb==_dual ) return true;
     System.err.print("("+this+" & "+t+")=="+mt+" but \n("+mt._dual+" & ");
     if( ta!=t._dual ) System.err.println(t._dual+")=="+ta+" \nwhich is not "+t._dual);
     else              System.err.println(  _dual+")=="+tb+" \nwhich is not "+  _dual);
     return false;
   }
clone()
Type com.cliffc.aa.type.Type< T extends Type< T >.clone () protected
Definition at line 304 of file Type.java.
{
     try {
       POOLS[_type]._clone++;
       Type t = (Type)super.clone();
       t._uid = _uid();
       t._dual = null;
       t._hash = 0;
       if( t instanceof TypeStruct )
         ((TypeStruct)t)._cyclic = false;
       return t;
     }
     catch( CloneNotSupportedException cns ) { throw new RuntimeException(cns); }
   }
Referenced by com.cliffc.aa.type.Type< TypeFlt >._set_name(), com.cliffc.aa.type.TypeStruct._sharp(), com.cliffc.aa.type.TypeStruct.ax_impl_fptr(), com.cliffc.aa.type.TypeStruct.ax_impl_ptr(), com.cliffc.aa.type.Type< TypeFlt >.clone(), com.cliffc.aa.type.TypeMem.crush(), com.cliffc.aa.type.TypeMem.flatten_fields(), com.cliffc.aa.type.Type< T extends Type< T >.Pool.malloc(), com.cliffc.aa.type.TypeMem.remove(), and com.cliffc.aa.type.TypeMem.widen().
compute_hash()
int com.cliffc.aa.type.Type< T extends Type< T >.compute_hash () package
Definition at line 109 of file Type.java.
 { return (_type<<1)|1|_name.hashCode(); }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.hashcons(), com.cliffc.aa.type.Type< TypeFlt >.intern_check0(), com.cliffc.aa.type.TypeStruct.post_mod(), and com.cliffc.aa.type.TypeStruct.shrink().
concat()
static void com.cliffc.aa.type.Type< T extends Type< T >.concat (Ary< Type< T extends Type< T > > ts, Type< T extends Type< T >[] ts1) static package
Definition at line 676 of file Type.java.
{
     for( Type t1 : ts1 ) {
       assert !t1.above_center(); // Always below-center or equal, because we'll dual anyways
       ts.push(t1);
       if( t1!=t1.dual() ) ts.push(t1.dual());
     }
   }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.ALL_TYPES().
contains() [1/2]
final boolean com.cliffc.aa.type.Type< T extends Type< T >.contains (Type< T extends Type< T > t)
Definition at line 926 of file Type.java.
 { return contains(t,null); }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.contains(), com.cliffc.aa.type.TypeStruct.contains(), and com.cliffc.aa.node.PhiNode.err().
contains() [2/2]
boolean com.cliffc.aa.type.Type< T extends Type< T >.contains (Type< T extends Type< T > t, VBitSet bs) package
Definition at line 927 of file Type.java.
 { return this==t; }
cross_nil()
final Type com.cliffc.aa.type.Type< T extends Type< T >.cross_nil (Type< T extends Type< T > t) package
Definition at line 865 of file Type.java.
 { return must_nil() || t.must_nil() ? SCALAR : NSCALR; }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.xmeet().
cycle_equals()
boolean com.cliffc.aa.type.Type< T extends Type< T >.cycle_equals (Type< T extends Type< T > t)
Definition at line 118 of file Type.java.
{
     assert is_simple();         // Overridden in subclasses
     return _type==t._type && Util.eq(_name,t._name);
   }
Referenced by com.cliffc.aa.type.TypeFld.cycle_equals(), com.cliffc.aa.type.TypeFunPtr.cycle_equals(), and com.cliffc.aa.type.TypeStruct.cycle_equals0().
dual()
final T com.cliffc.aa.type.Type< T extends Type< T >.dual ()
Definition at line 361 of file Type.java.
 { return _dual; }
Referenced by com.cliffc.aa.type.TypeStruct._dull(), com.cliffc.aa.node.PrimNode.ConvertTypeName.apply(), com.cliffc.aa.HM.HM9.EQ.apply(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM.EQ.apply(), com.cliffc.aa.HM.HM9.IsEmpty.apply(), com.cliffc.aa.HM.HM.EQ0.apply(), com.cliffc.aa.HM.HM.IsEmpty.apply(), com.cliffc.aa.HM.HM9.Mul.apply(), com.cliffc.aa.HM.HM.Mul.apply(), com.cliffc.aa.HM.HM9.Dec.apply(), com.cliffc.aa.HM.HM.Add.apply(), com.cliffc.aa.HM.HM9.Str.apply(), com.cliffc.aa.HM.HM.Dec.apply(), com.cliffc.aa.HM.HM9.Factor.apply(), com.cliffc.aa.HM.HM.Str.apply(), com.cliffc.aa.HM.HM.Factor.apply(), com.cliffc.aa.node.FunNode.bad_mem_use(), com.cliffc.aa.node.CallEpiNode.esc_out(), com.cliffc.aa.type.Type< TypeFlt >.high(), com.cliffc.aa.node.ScopeNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.type.Type< TypeFlt >.join(), com.cliffc.aa.type.TypeFunPtr.meet_nil(), com.cliffc.aa.type.TypeInt.not_nil(), com.cliffc.aa.type.Bits< BitsRPC >.oob(), com.cliffc.aa.type.Type< TypeFlt >.oob(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.type.TestType.testCrush(), com.cliffc.aa.type.TestType.testFunction(), com.cliffc.aa.type.TestType.testLoad(), com.cliffc.aa.node.TestNodeSmall.testMemoryArgs(), com.cliffc.aa.type.TestType.testNamesInts(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.type.TestType.testStructTuple(), com.cliffc.aa.node.TestNodeSmall.testUnresolvedAdd(), com.cliffc.aa.node.UnresolvedNode.value(), com.cliffc.aa.node.IntrinsicNode.value(), com.cliffc.aa.node.PrimNode.value(), com.cliffc.aa.node.CallEpiNode.value(), com.cliffc.aa.node.PrimNode.AndI64.value(), com.cliffc.aa.node.PrimNode.OrI64.value(), com.cliffc.aa.node.PrimNode.EQ_OOP.value(), com.cliffc.aa.node.CallNode.value(), com.cliffc.aa.node.PrimNode.NE_OOP.value(), com.cliffc.aa.node.PrimNode.Not.value(), com.cliffc.aa.node.PrimNode.RandI64.value(), com.cliffc.aa.node.PrimNode.EQ_OOP.vs_nil(), com.cliffc.aa.type.TypeAry.xdual(), com.cliffc.aa.type.TypeFunPtr.xdual(), com.cliffc.aa.type.TypeFunSig.xdual(), com.cliffc.aa.type.TypeMemPtr.xdual(), and com.cliffc.aa.type.Type< TypeFlt >.xmt_name().
eq()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.eq (Type< T extends Type< T >[] t0, Type< T extends Type< T >[] t1) static
Definition at line 136 of file Type.java.
{
     if( t0==t1 ) return true;
     if( t0==null || t1==null ) return false;
     if( t0.length != t1.length ) return false;
     for( int i=0; i<t0.length; i++ )
       if( t0[i] != t1[i] )
         return false;
     return true;
   }
equals()
boolean com.cliffc.aa.type.Type< T extends Type< T >.equals (Object o)
Definition at line 112 of file Type.java.
{
     if( this == o ) return true;
     if( !(o instanceof Type) ) return false;
     Type t = (Type)o;
     return _type==t._type && Util.eq(_name,t._name);
   }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.hashcons().
getd()
double com.cliffc.aa.type.Type< T extends Type< T >.getd ()
Definition at line 804 of file Type.java.
 { if( _type==TNIL || _type==TXNIL ) return 0.0; throw typerr(null); }
Referenced by com.cliffc.aa.TestParse.testParse07(), and com.cliffc.aa.node.NewStrNode.ConvertF64Str.valueobj().
getl()
long com.cliffc.aa.type.Type< T extends Type< T >.getl ()
Definition at line 802 of file Type.java.
 { if( _type==TNIL || _type==TXNIL ) return 0; throw typerr(null); }
Referenced by com.cliffc.aa.HM.HM.Mul.apply(), com.cliffc.aa.HM.HM9.Mul.apply(), com.cliffc.aa.HM.HM.Add.apply(), com.cliffc.aa.HM.HM9.Dec.apply(), com.cliffc.aa.HM.HM9.Str.apply(), com.cliffc.aa.HM.HM.Dec.apply(), com.cliffc.aa.HM.HM.Str.apply(), com.cliffc.aa.node.TestNode.print(), com.cliffc.aa.node.PrimNode.AndI64.value(), com.cliffc.aa.node.PrimNode.OrI64.value(), and com.cliffc.aa.node.NewStrNode.ConvertI64Str.valueobj().
getstr()
String com.cliffc.aa.type.Type< T extends Type< T >.getstr ()
Definition at line 806 of file Type.java.
 { throw typerr(null); }
Referenced by com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM9.IsEmpty.apply(), com.cliffc.aa.HM.HM.IsEmpty.apply(), com.cliffc.aa.tvar.TV2.str(), and com.cliffc.aa.HM.HM8.T2.str().
has_name()
boolean com.cliffc.aa.type.Type< T extends Type< T >.has_name ()
Definition at line 549 of file Type.java.
 { return !_name.isEmpty(); }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.isBitShape(), and com.cliffc.aa.type.Type< TypeFlt >.remove_name().
hashCode()
final int com.cliffc.aa.type.Type< T extends Type< T >.hashCode ()
Definition at line 106 of file Type.java.
 { assert _hash!=0; return _hash; }
Referenced by com.cliffc.aa.node.PhiNode.hashCode().
hashcons()
T com.cliffc.aa.type.Type< T extends Type< T >.hashcons () private
Definition at line 165 of file Type.java.
{
     _hash = compute_hash();     // Set hash
     T t2 = (T)INTERN.get(this); // Lookup
     if( t2!=null ) {            // Found prior
       assert t2._dual != null;  // Prior is complete with dual
       assert this != t2;        // Do not hashcons twice, should not get self back
       return t2;                // Return prior
     }
     if( RECURSIVE_MEET > 0 )    // Mid-building recursive types; do not intern
       return (T)this;
     // Not in type table
     _dual = null;                // No dual yet
     INTERN.put(this,this);       // Put in table without dual
     T d = xdual();               // Compute dual without requiring table lookup, and not setting name
     d._name = _name;             // xdual does not set name either
     d._hash = d.compute_hash();  // Set dual hash
     _dual = d;
     if( this==d ) return d;      // Self-symmetric?  Dual is self
     assert !equals(d);           // Self-symmetric is handled by caller
     assert d._dual==null;        // Else dual-dual not computed yet
     assert INTERN.get(d)==null;
     d._dual = (T)this;
     INTERN.put(d,d);
     return (T)this;
   }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.hashcons_free().
hashcons_free()
final T com.cliffc.aa.type.Type< T extends Type< T >.hashcons_free () package
Definition at line 153 of file Type.java.
{
     T t2 = hashcons();
     return this==t2 ? t2 : (T)POOLS[_type].free(this,t2);
   }
Referenced by com.cliffc.aa.type.TypeStruct._sharp(), com.cliffc.aa.type.TypeRPC.make(), com.cliffc.aa.type.TypeFlt.make(), com.cliffc.aa.type.TypeInt.make(), com.cliffc.aa.type.TypeFld.make(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeFunPtr.make(), com.cliffc.aa.type.TypeFunSig.make(), com.cliffc.aa.type.TypeTuple.make(), com.cliffc.aa.type.TypeMem.make(), com.cliffc.aa.type.TypeFld.make_from(), com.cliffc.aa.type.TypeStruct.remove_other_flds(), and com.cliffc.aa.type.TypeStruct.widen().
high()
Type com.cliffc.aa.type.Type< T extends Type< T >.high ()
Definition at line 796 of file Type.java.
 { return above_center() ? this : dual(); }
init()
T com.cliffc.aa.type.Type< T extends Type< T >.init (byte type, String name) protected
Definition at line 105 of file Type.java.
 { _type=type; _name=name; return (T)this; }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.make().
init0()
static void com.cliffc.aa.type.Type< T extends Type< T >.init0 (HashMap< String, Type< T extends Type< T > > types) static
Definition at line 642 of file Type.java.
{
     types.put("real",REAL);
     types.put("scalar",SCALAR);
     TypeInt.init1(types);
     TypeFlt.init1(types);
     TypeStr.init1(types);
   }
Referenced by com.cliffc.aa.node.ScopeNode.init().
intern_check()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check () static
Definition at line 212 of file Type.java.
{
     int errs=0;
     for( Type k : INTERN.keySet() ) {
       Type v = INTERN.get(k);
       if( !k.intern_check0(v) ) {
         System.out.println("INTERN_CHECK FAIL: "+k._uid+":"+k+" vs "+v._uid+":"+v);
         errs++;
       }
     }
     return errs==0;
   }
Referenced by com.cliffc.aa.HM.HM9.T2.as_flow(), and com.cliffc.aa.HM.HM.T2.as_flow().
intern_check0()
boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check0 (Type< T extends Type< T > v) private
Definition at line 223 of file Type.java.
{
     if( this != v || _dual==null || _dual._dual!=this || compute_hash()!=_hash ) return false;
     return intern_check1();
   }
intern_check1()
boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check1 () package
Definition at line 227 of file Type.java.
 { return true; }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.intern_check0().
intern_find()
static Type com.cliffc.aa.type.Type< T extends Type< T >.intern_find (int uid) static package
Definition at line 229 of file Type.java.
{
     for( Type k : INTERN.keySet() )
       if( k._uid==uid )
         return k;
     return null;
   }
intern_lookup()
Type com.cliffc.aa.type.Type< T extends Type< T >.intern_lookup () package
Definition at line 210 of file Type.java.
 { return INTERN.get(this); }
Referenced by com.cliffc.aa.type.TypeStruct.check_uf(), com.cliffc.aa.type.TypeFld.intern_check1(), com.cliffc.aa.type.TypeMemPtr.intern_check1(), com.cliffc.aa.type.TypeStruct.intern_check1(), and com.cliffc.aa.type.TypeStruct.shrink().
intern_size()
static int com.cliffc.aa.type.Type< T extends Type< T >.intern_size () static package
Definition at line 211 of file Type.java.
 { return INTERN.size(); }
interned()
boolean com.cliffc.aa.type.Type< T extends Type< T >.interned () package
Definition at line 209 of file Type.java.
 { return INTERN.get(this)==this; }
Referenced by com.cliffc.aa.type.TypeStruct._is_sharp(), com.cliffc.aa.type.TypeStruct._sharp(), com.cliffc.aa.type.TypeStruct.ax_impl_fptr(), com.cliffc.aa.type.TypeStruct.ax_impl_ptr(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.TypeStruct.get_cyclic(), com.cliffc.aa.type.TypeStruct.install_cyclic(), com.cliffc.aa.type.TypeStruct.push(), com.cliffc.aa.type.TypeStruct.sharpen(), com.cliffc.aa.type.TypeMem.sharput(), com.cliffc.aa.type.TypeStruct.shrink(), and com.cliffc.aa.type.Type< TypeFlt >.xmt_name().
is_con()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_con ()
Definition at line 776 of file Type.java.
{
     switch( _type ) {
     case TALL:
     case TCTRL:
     case TNREAL:
     case TREAL:
     case TNSCALR:
     case TSCALAR:
     case TANY:
     case TXCTRL:
     case TXNREAL:
     case TXREAL:
     case TXNSCALR:
     case TXSCALAR:
       return false;             // Not exactly a constant
     case TNIL: case TXNIL:
       return true;
     default: throw typerr(null);// Overridden in subclass
     }
   }
Referenced by com.cliffc.aa.node.MemPrimNode.LValueLength._live_use(), com.cliffc.aa.node.LoadNode._live_use(), com.cliffc.aa.HM.HM9.EQ.apply(), com.cliffc.aa.HM.HM.EQ.apply(), com.cliffc.aa.HM.HM.Mul.apply(), com.cliffc.aa.HM.HM9.Mul.apply(), com.cliffc.aa.HM.HM9.Dec.apply(), com.cliffc.aa.HM.HM.Add.apply(), com.cliffc.aa.HM.HM9.Str.apply(), com.cliffc.aa.HM.HM.Dec.apply(), com.cliffc.aa.HM.HM.Str.apply(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.RetNode.ideal_reduce(), com.cliffc.aa.node.Node.should_con(), com.cliffc.aa.node.FunNode.split_size(), com.cliffc.aa.node.PrimNode.value(), com.cliffc.aa.node.PrimNode.AndI64.value(), com.cliffc.aa.node.PrimNode.OrI64.value(), com.cliffc.aa.node.NewStrNode.ConvertI64Str.valueobj(), com.cliffc.aa.node.NewStrNode.ConvertF64Str.valueobj(), and com.cliffc.aa.node.CallEpiNode.wire0().
is_display()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_display () package
Definition at line 942 of file Type.java.
 { return false; }
is_display_ptr()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_display_ptr ()
Definition at line 941 of file Type.java.
 { return _type==TSCALAR || _type==TXSCALAR || _type==TNIL || _type==TXNIL || _type==TANY || _type==TALL; }
Referenced by com.cliffc.aa.Parse.get_display_ptr(), com.cliffc.aa.type.TypeFunSig.init(), com.cliffc.aa.type.TypeFld.is_display_ptr(), com.cliffc.aa.type.TypeFunPtr.make(), com.cliffc.aa.type.TypeTuple.make_args(), and com.cliffc.aa.TestParse.testParse06().
is_forward_ref()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_forward_ref ()
Definition at line 799 of file Type.java.
 { return false; }
Referenced by com.cliffc.aa.tvar.TV2._find_tvar(), and com.cliffc.aa.node.CastNode.value().
is_num()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_num () private
Definition at line 353 of file Type.java.
 { byte t = _type;  return t == TREAL || t == TXREAL || t == TNREAL || t == TXNREAL || t == TINT || t == TFLT; }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.isBitShape(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
is_ptr()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_ptr () private
Definition at line 352 of file Type.java.
 { byte t = _type;  return t == TFUNPTR || t == TMEMPTR; }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.xmeet().
is_simple()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_simple () private
Definition at line 351 of file Type.java.
 { return _type < TSIMPLE; }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.check_commute(), com.cliffc.aa.type.Type< TypeFlt >.cycle_equals(), com.cliffc.aa.type.Type< TypeFlt >.meet(), com.cliffc.aa.type.Type< TypeFlt >.walk(), com.cliffc.aa.type.Type< TypeFlt >.xmeet(), and com.cliffc.aa.type.Type< TypeFlt >.xmt_name().
isa()
boolean com.cliffc.aa.type.Type< T extends Type< T >.isa (Type< T extends Type< T > t)
Definition at line 623 of file Type.java.
 { return meet(t)==t; }
Referenced by com.cliffc.aa.HM.HM9.T2._can_be_HM_base(), com.cliffc.aa.HM.HM.T2._can_be_HM_base(), com.cliffc.aa.node.TestNodeSmall._testMonotonicChain(), com.cliffc.aa.type.TypeMem.all_reaching_aliases(), com.cliffc.aa.node.PrimNode.ConvertTypeName.apply(), com.cliffc.aa.node.TestNodeSmall.check(), com.cliffc.aa.GVNGCM.check_not_monotonic(), com.cliffc.aa.node.RetNode.check_phi_type(), com.cliffc.aa.type.Type< TypeFlt >.check_startup(), com.cliffc.aa.node.ScopeNode.compute_live_mem(), com.cliffc.aa.node.Node.do_flow(), com.cliffc.aa.node.ParmNode.err(), com.cliffc.aa.node.PrimNode.err(), com.cliffc.aa.node.PrimNode.ConvertTypeName.err(), com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.node.FunNode.find_type_split_index(), com.cliffc.aa.node.CallNode.get_alias(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.node.CallNode.ideal_grow(), com.cliffc.aa.node.FunNode.ideal_inline(), com.cliffc.aa.node.AssertNode.ideal_reduce(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.type.Type< TypeFlt >.isBitShape(), com.cliffc.aa.type.TypeStruct.isBitShape(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.node.Node.more_flow(), com.cliffc.aa.node.FreshNode.no_tvar_structure(), com.cliffc.aa.node.TestNode.redo_(), com.cliffc.aa.node.TestNode.set_value_type(), com.cliffc.aa.node.FunNode.split_size(), com.cliffc.aa.Parse.term(), com.cliffc.aa.TestParse.test_isa(), com.cliffc.aa.TestParse.test_obj_isa(), com.cliffc.aa.type.TestType.testBits(), com.cliffc.aa.type.TestType.testBits0(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.type.TestType.testCrush0(), com.cliffc.aa.type.TestType.testFunction(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.type.TestType.testStructTuple(), com.cliffc.aa.node.TestNodeSmall.testUnresolvedAdd(), com.cliffc.aa.node.FunNode.type_special(), com.cliffc.aa.Parse.typechk(), com.cliffc.aa.HM.HM9.T2.union(), com.cliffc.aa.HM.HM.T2.union(), com.cliffc.aa.type.TypeAry.update(), com.cliffc.aa.HM.HM9.Apply.val(), com.cliffc.aa.HM.HM.Apply.val(), com.cliffc.aa.node.ParmNode.valid_args(), com.cliffc.aa.node.IfNode.value(), com.cliffc.aa.node.ParmNode.value(), com.cliffc.aa.node.NewStrNode.AddStrStr.value(), com.cliffc.aa.node.AssertNode.value(), com.cliffc.aa.node.IntrinsicNode.value(), com.cliffc.aa.node.MemPrimNode.LValueWrite.value(), com.cliffc.aa.node.MemPrimNode.LValueWriteFinal.value(), com.cliffc.aa.node.PrimNode.AndI64.value(), com.cliffc.aa.node.PrimNode.OrI64.value(), com.cliffc.aa.node.PrimNode.RandI64.value(), and com.cliffc.aa.node.PrimNode.EQ_OOP.vs_nil().
isa_scalar()
final boolean com.cliffc.aa.type.Type< T extends Type< T >.isa_scalar ()
Definition at line 356 of file Type.java.
 { assert ISA_SCALAR.length==TLAST; return ISA_SCALAR[_type]!=0; }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.xmeet().
isBitShape()
byte com.cliffc.aa.type.Type< T extends Type< T >.isBitShape (Type< T extends Type< T > t)
Definition at line 814 of file Type.java.
{
     if( has_name() || t.has_name() ) throw com.cliffc.aa.AA.unimpl();
     if( _type == TNIL || _type==TXNIL ) return 0; // Nil is free to convert always
     if( above_center() && isa(t) ) return 0; // Can choose compatible format
     if( _type == t._type ) return 0; // Same type is OK
     if( t._type==TSCALAR ) return 0; // Generic function arg never requires a conversion
     if( _type == TALL || t._type==TALL || _type == TSCALAR || _type == TNSCALR ) return -1; // Scalar has to resolve
     if( (_type == TREAL || _type == TNREAL) && t.is_num() ) return -1; // Real->Int/Flt has to resolve
     if( t._type == TNIL || t._type == TXNIL ) return (byte)(may_nil() ? -1 : 99); // Must resolve to a NIL first
     throw typerr(t);  // Overridden in subtypes
   }
Referenced by com.cliffc.aa.node.CallEpiNode.ideal_reduce(), and com.cliffc.aa.node.CallNode.least_cost().
join()
Type com.cliffc.aa.type.Type< T extends Type< T >.join (Type< T extends Type< T > t)
Definition at line 619 of file Type.java.
 { return dual().meet(t.dual()).dual(); }
Referenced by com.cliffc.aa.type.TypeStruct._dull(), com.cliffc.aa.tvar.TV2._find_tvar(), com.cliffc.aa.HM.HM.NotNil.apply(), com.cliffc.aa.HM.HM9.NotNil.apply(), com.cliffc.aa.type.Type< TypeFlt >.check_startup(), com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.node.FunNode.find_type_split(), com.cliffc.aa.HM.HM9.NotNil.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.type.TypeMem.ld(), com.cliffc.aa.type.TestType.testBits(), com.cliffc.aa.type.TestType.testStructTuple(), com.cliffc.aa.HM.HM.T2.unify_nil(), com.cliffc.aa.HM.HM9.Apply.val(), com.cliffc.aa.HM.HM.Apply.val(), com.cliffc.aa.node.MProjNode.value(), com.cliffc.aa.node.CastNode.value(), com.cliffc.aa.node.UnresolvedNode.value(), com.cliffc.aa.node.CallEpiNode.value(), com.cliffc.aa.HM.HM9.T2.walk_types_in(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
make()
static Type com.cliffc.aa.type.Type< T extends Type< T >.make (byte type) static package
Definition at line 147 of file Type.java.
{
     Pool P = POOLS[type];
     Type t1 = P.malloc();
     return t1.init(type,"").hashcons_free();
   }
make_from()
Type com.cliffc.aa.type.Type< T extends Type< T >.make_from (Type< T extends Type< T > head, TypeMem map, VBitSet visit)
Definition at line 945 of file Type.java.
 { return this; }
Referenced by com.cliffc.aa.node.ConTypeNode.def_fref(), com.cliffc.aa.type.TypeFld.make_from(), com.cliffc.aa.type.TypeMemPtr.make_from(), and com.cliffc.aa.node.ConTypeNode.value().
may_be_con()
boolean com.cliffc.aa.type.Type< T extends Type< T >.may_be_con ()
Definition at line 759 of file Type.java.
{
     switch( _type ) {
     case TALL:
     case TSCALAR:  case TNSCALR:
     case TREAL:    case TNREAL:
     case TXCTRL:
     case TCTRL:
       return false;             // These all include not-constant things
     case TANY:
     case TXREAL:   case TXNREAL:
     case TXSCALAR: case TXNSCALR:
     case TNIL:     case TXNIL:
       return true;              // These all include some constants
     default: throw typerr(null);
     }
   }
Referenced by com.cliffc.aa.node.Node.do_flow(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.node.Node.live_uses(), and com.cliffc.aa.type.TypeFunPtr.may_be_con().
may_nil()
boolean com.cliffc.aa.type.Type< T extends Type< T >.may_nil ()
Definition at line 869 of file Type.java.
{
     switch(_type) {
     case TALL:
     case TREAL:
     case TSCALAR:
     case TXNSCALR: case TNSCALR:
     case TXNREAL:  case TNREAL:
     case TTUPLE:
       return false;
     case TANY:
     case TXREAL:
     case TXSCALAR:
     case TCTRL:  // Nonsense, only for IfNode.value test
     case TXCTRL: // Nonsense, only for IfNode.value test
     case TMEM:   // Nonsense, only for IfNode.value test
       return true;
     default: throw typerr(null); // Overridden in subclass
     }
   }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.isBitShape().
meet()
final Type com.cliffc.aa.type.Type< T extends Type< T >.meet (Type< T extends Type< T > t)
Definition at line 412 of file Type.java.
{
     // Short cut for the self case
     if( t == this ) return this;
     // Short-cut for seeing this meet before
     Type mt = Key.get(this,t);
     if( mt != null ) return mt;
     // "Triangulate" the matrix and cut in half the number of cases.
     // Reverse; xmeet 2nd arg is never "is_simple" and never equal to "this".
     // This meet ignores the _name field, and can return any-old name it wants.
     mt = !is_simple() && t.is_simple() ? t.xmeet(this) : xmeet(t);
     // Meet the names.  Subclasses basically ignore the names as they have
     // their own complicated meets to perform, so we meet them here for all.
     Type nmt = xmt_name(t,mt);
     // Quick check on NIL: if either argument is NIL the result is allowed to
     // be NIL...  but nobody in the lattice can make a NIL from whole cloth, or
     // we get the crossing-nil bug.
     assert (nmt != NIL && nmt!=XNIL) || this==NIL || this==XNIL || t==NIL || t==XNIL;
     // Record this meet, to short-cut next time
     if( RECURSIVE_MEET == 0 )   // Only not mid-building recursive types;
       Key.put(this,t,nmt);
     return nmt;
   }
Referenced by com.cliffc.aa.type.TypeStruct._dull(), com.cliffc.aa.type.TypeMem._meet(), com.cliffc.aa.type.Type< TypeFlt >.above(), com.cliffc.aa.HM.HM.Root.add_sig(), com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM9.If.apply(), com.cliffc.aa.HM.HM.If.apply(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.Type< TypeFlt >.check_startup(), com.cliffc.aa.type.TypeStruct.cyclic_meet(), com.cliffc.aa.HM.HM9.T2.fput(), com.cliffc.aa.HM.HM.T2.fput(), com.cliffc.aa.tvar.TV2.fresh_base(), com.cliffc.aa.HM.HM4.T2.fresh_base(), com.cliffc.aa.HM.HM5.T2.fresh_base(), com.cliffc.aa.HM.HM6.T2.fresh_base(), com.cliffc.aa.HM.HM7.T2.fresh_base(), com.cliffc.aa.HM.HM8.T2.fresh_base(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.type.Type< TypeFlt >.isa(), com.cliffc.aa.type.TypeMem.ld(), com.cliffc.aa.node.CallNode.least_cost(), com.cliffc.aa.node.Node.live(), com.cliffc.aa.node.NewStrNode.AddStrStr.live_use(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.HM.HM9.T2.meet_flow(), com.cliffc.aa.HM.HM.T2.meet_flow(), com.cliffc.aa.type.Type< TypeFlt >.meet_loop(), com.cliffc.aa.node.Node.merge(), com.cliffc.aa.type.TypeMem.st_new(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestType.testBits(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.type.TestType.testFunction(), com.cliffc.aa.type.TestType.testNameCycle(), com.cliffc.aa.type.TestType.testNamesInts(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.type.TestType.testStructTuple(), com.cliffc.aa.tvar.TV2.unify_base(), com.cliffc.aa.HM.HM7.T2.unify_base(), com.cliffc.aa.HM.HM8.T2.unify_base(), com.cliffc.aa.HM.HM1.HMVar.union(), com.cliffc.aa.HM.HM2.HMVar.union(), com.cliffc.aa.HM.HM3.HMVar.union(), com.cliffc.aa.type.TypeAry.update(), com.cliffc.aa.type.TypeStruct.update(), com.cliffc.aa.HM.HM9.Apply.val(), com.cliffc.aa.HM.HM.Apply.val(), com.cliffc.aa.HM.HM.Root.val(), com.cliffc.aa.node.UnresolvedNode.value(), com.cliffc.aa.node.PhiNode.value(), com.cliffc.aa.node.ParmNode.value(), com.cliffc.aa.node.CallEpiNode.value(), com.cliffc.aa.node.PrimNode.RandI64.value(), com.cliffc.aa.type.TypeAry.xmeet(), com.cliffc.aa.type.TypeFld.xmeet(), com.cliffc.aa.type.TypeFunSig.xmeet(), com.cliffc.aa.type.TypeFunPtr.xmeet(), com.cliffc.aa.type.TypeMemPtr.xmeet(), and com.cliffc.aa.HM.HM9.Root.xval().
meet_loop()
Type com.cliffc.aa.type.Type< T extends Type< T >.meet_loop (Type< T extends Type< T > t2)
Definition at line 628 of file Type.java.
 { return meet(t2); }
Referenced by com.cliffc.aa.type.TypeMem._meet(), and com.cliffc.aa.node.PhiNode.value().
meet_nil()
Type com.cliffc.aa.type.Type< T extends Type< T >.meet_nil (Type< T extends Type< T > nil)
Definition at line 904 of file Type.java.
{
     assert nil==NIL || nil==XNIL;
     switch( _type ) {
     case TANY:
     case TXREAL:
     case TXSCALAR:
     case TXNIL:   return nil; // Preserve high/low flavor
     case TNIL:    return NIL;
     case TXNREAL:
     case TXNSCALR:  return TypeInt.BOOL;
     case TREAL:   case TNREAL:    return REAL;
     case TSCALAR: case TNSCALR:   return SCALAR;
     case TCTRL:   case TXCTRL:
     case TOBJ:
     case TSTR:
     case TSTRUCT:
     case TMEM:      return ALL;
     default:        throw typerr(null); // Overridden in subclass
     }
   }
Referenced by com.cliffc.aa.HM.HM.T2._find_nil(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM.EQ0.apply(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.Parse.typeq(), com.cliffc.aa.node.IfNode.value(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
mtname()
final String com.cliffc.aa.type.Type< T extends Type< T >.mtname (Type< T extends Type< T > t, Type< T extends Type< T > mt) package
Definition at line 567 of file Type.java.
{
     Type   t0 = this,  t1 = t;
     String s0 = t0._name, s1 = t1._name;
     assert check_name(s0) && check_name(s1);
     if( Util.eq(s0,s1) ) return s0;
     // Sort by name length
     if( s0.length() > s1.length() ) { t1=this; t0=t; s0=t0._name; s1=t1._name; }
     int x = 0, i;  char c;    // Last colon separator index
     // Find split point
     for( i = 0; i < s0.length(); i++ ) {
       if( (c=s0.charAt(i)) != s1.charAt(i) )
         break;
       if( c==':' ) x=i;
     }
     // If s0 is a prefix of s1, and s0 is high then it can cover s1.
     if( i==s0.length() && t0.above_center() && (!t1.above_center() || mt.above_center()) )
       return s1;
     // Keep the common prefix, which might be all of s0
     String s2 = i==s0.length() ? s0 : s0.substring(0, x).intern();
     assert check_name(s2);
     return s2;
   }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.xmt_name().
must_nil()
boolean com.cliffc.aa.type.Type< T extends Type< T >.must_nil ()
Definition at line 845 of file Type.java.
{
     switch( _type ) {
     case TALL:
     case TREAL:
     case TSCALAR:
     case TNIL: case TXNIL:
     case TCTRL:  // Nonsense, only for IfNode.value test
     case TXCTRL: // Nonsense, only for IfNode.value test
     case TMEM:   // Nonsense, only for IfNode.value test
       return true;              // These all must include a nil
     case TANY:                  // All above-center types are not required to include a nil
     case TXREAL:
     case TXSCALAR:
     case TXNSCALR: case TNSCALR:
     case TXNREAL:  case TNREAL:
       return false;             // These all may be non-nil
     default: throw typerr(null); // Overridden in subclass
     }
   }
Referenced by com.cliffc.aa.HM.HM9.If.apply(), com.cliffc.aa.HM.HM.If.apply(), com.cliffc.aa.type.Type< TypeFlt >.cross_nil(), com.cliffc.aa.node.MemPrimNode.err(), com.cliffc.aa.node.StoreNode.err(), com.cliffc.aa.node.LoadNode.err(), com.cliffc.aa.HM.HM9.If.hm(), com.cliffc.aa.HM.HM.If.hm(), com.cliffc.aa.node.IfNode.value(), com.cliffc.aa.node.PrimNode.Not.value(), com.cliffc.aa.node.PrimNode.EQ_OOP.vs_nil(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
not_nil()
Type com.cliffc.aa.type.Type< T extends Type< T >.not_nil () package
Definition at line 893 of file Type.java.
                  {
     switch( _type ) {
     case TXSCALAR:  return XNSCALR;
     case TXREAL  :  return XNREAL ;
     case TSCALAR:   case TNSCALR:   case TXNSCALR:
     case TREAL:     case TNREAL:    case TXNREAL:
     case TNIL:      case TXNIL:
       return this;
     default: throw typerr(null); // Overridden in subclass
     }
   }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.xmeet().
oob() [1/6]
Type com.cliffc.aa.type.Type< T extends Type< T >.oob ()
Definition at line 635 of file Type.java.
 { return oob(ALL); }
Referenced by com.cliffc.aa.node.MemPrimNode.LValueLength._live_use(), com.cliffc.aa.node.LoadNode._live_use(), com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.node.ScopeNode.compute_live_mem(), com.cliffc.aa.node.CallNode.escapees(), com.cliffc.aa.node.LoadNode.get_fld(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.MemPrimNode.ReadPrimNode.live_use(), com.cliffc.aa.node.NewStrNode.AddStrStr.live_use(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.type.TypeMem.make0(), com.cliffc.aa.type.Type< TypeFlt >.oob(), com.cliffc.aa.type.Type< TypeFlt >.oop_deep_impl(), com.cliffc.aa.node.CallNode.tesc(), com.cliffc.aa.node.DefMemNode.value(), com.cliffc.aa.node.ProjNode.value(), com.cliffc.aa.node.MProjNode.value(), com.cliffc.aa.node.MemSplitNode.value(), com.cliffc.aa.node.CastNode.value(), com.cliffc.aa.node.UnresolvedNode.value(), com.cliffc.aa.node.FP2DispNode.value(), com.cliffc.aa.node.PhiNode.value(), com.cliffc.aa.node.ParmNode.value(), com.cliffc.aa.node.NewStrNode.AddStrStr.value(), com.cliffc.aa.node.MrgProjNode.value(), com.cliffc.aa.node.MemPrimNode.LValueLength.value(), com.cliffc.aa.node.AssertNode.value(), com.cliffc.aa.node.StoreNode.value(), com.cliffc.aa.node.MemJoinNode.value(), com.cliffc.aa.node.MemPrimNode.LValueRead.value(), com.cliffc.aa.node.LoadNode.value(), com.cliffc.aa.node.MemPrimNode.LValueWrite.value(), com.cliffc.aa.node.MemPrimNode.LValueWriteFinal.value(), com.cliffc.aa.node.CallEpiNode.value(), com.cliffc.aa.node.CallNode.value(), com.cliffc.aa.node.PrimNode.RandI64.value(), com.cliffc.aa.node.NewAryNode.NewAry.valueobj(), com.cliffc.aa.node.NewStrNode.ConvertI64Str.valueobj(), and com.cliffc.aa.node.NewStrNode.ConvertF64Str.valueobj().
oob() [2/6]
Type com.cliffc.aa.type.Type< T extends Type< T >.oob (Type< T extends Type< T > e)
Definition at line 636 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [3/6]
TypeMem com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeMem e)
Definition at line 639 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [4/6]
TypeMemPtr com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeMemPtr e)
Definition at line 640 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [5/6]
TypeObj com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeObj e)
Definition at line 637 of file Type.java.
 { return above_center() ? (TypeObj)e.dual() : e; }
oob() [6/6]
TypeStruct com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeStruct e)
Definition at line 638 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob_deep()
Type com.cliffc.aa.type.Type< T extends Type< T >.oob_deep (Type< T extends Type< T > t)
Definition at line 632 of file Type.java.
 { return oop_deep_impl(t); }
oop_deep_impl()
Type com.cliffc.aa.type.Type< T extends Type< T >.oop_deep_impl (Type< T extends Type< T > t)
Definition at line 634 of file Type.java.
 { return oob(); }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.oob_deep(), and com.cliffc.aa.type.TypeMemPtr.oop_deep_impl().
rdual()
T com.cliffc.aa.type.Type< T extends Type< T >.rdual () package
Definition at line 366 of file Type.java.
 { assert _dual!=null; return _dual; }
Referenced by com.cliffc.aa.type.TypeFld.rdual(), com.cliffc.aa.type.TypeFunPtr.rdual(), and com.cliffc.aa.type.TypeMemPtr.rdual().
remove_name()
final T com.cliffc.aa.type.Type< T extends Type< T >.remove_name ()
Definition at line 556 of file Type.java.
 { return has_name() ? _set_name("") : (T)this; }
Referenced by com.cliffc.aa.node.IntrinsicNode.ideal_reduce(), and com.cliffc.aa.node.IntrinsicNode.value().
repeats_in_cycles()
TypeStruct com.cliffc.aa.type.Type< T extends Type< T >.repeats_in_cycles (TypeStruct head, VBitSet bs) package
Definition at line 938 of file Type.java.
 { return null; }
retern()
final T com.cliffc.aa.type.Type< T extends Type< T >.retern () package
Definition at line 201 of file Type.java.
                     {
     assert _dual._dual == this;
     assert _hash != 0;
     assert INTERN.get(this)==null;
     INTERN.put(this,this);
     assert INTERN.get(this)==this;
     return (T)this;
   }
set_name()
final T com.cliffc.aa.type.Type< T extends Type< T >.set_name (String name)
Definition at line 551 of file Type.java.
{
     assert check_name(name);
     return _set_name(name);
   }
Referenced by com.cliffc.aa.node.PrimNode.ConvertTypeName.apply(), com.cliffc.aa.type.TestType.testNamesInts(), com.cliffc.aa.TestParse.testParse04(), com.cliffc.aa.TestParse.testParse06(), com.cliffc.aa.Parse.tstmt(), com.cliffc.aa.Parse.type0(), com.cliffc.aa.node.IntrinsicNode.value(), and com.cliffc.aa.type.Type< TypeFlt >.xmt_name().
sharptr()
Type com.cliffc.aa.type.Type< T extends Type< T >.sharptr (Type< T extends Type< T > ptr)
Definition at line 930 of file Type.java.
 { return this==ANY ? TypeMem.ANYMEM.sharptr(ptr) : ptr; }
Referenced by com.cliffc.aa.node.TestNodeSmall.check(), com.cliffc.aa.node.IntrinsicNode.ideal_reduce(), com.cliffc.aa.node.Node.sharptr(), and com.cliffc.aa.TestParse.test_isa().
simple_ptr()
Type com.cliffc.aa.type.Type< T extends Type< T >.simple_ptr ()
Definition at line 358 of file Type.java.
 { return this; }
Referenced by com.cliffc.aa.node.MemPrimNode.ReadPrimNode.as_fun(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.as_fun(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun(), com.cliffc.aa.node.TestNodeSmall.check(), com.cliffc.aa.GVNGCM.check_not_monotonic(), com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.node.PrimNode.err(), com.cliffc.aa.node.FunNode.find_type_split(), com.cliffc.aa.node.TestNode.make_subtypes(), com.cliffc.aa.type.TypeFld.simple_ptr(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.node.FP2DispNode.value(), com.cliffc.aa.node.ParmNode.value(), and com.cliffc.aa.node.AssertNode.value().
str()
SB com.cliffc.aa.type.Type< T extends Type< T >.str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
Definition at line 131 of file Type.java.
 { return sb.p(_name).p(STRS[_type]); }
Referenced by com.cliffc.aa.HM.HM1.HMVar._str(), com.cliffc.aa.HM.HM2.HMVar._str(), com.cliffc.aa.HM.HM3.HMVar._str(), com.cliffc.aa.node.Node.dump(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.type.TypeFld.str(), com.cliffc.aa.type.TypeFunSig.str(), com.cliffc.aa.type.TypeFunPtr.str(), com.cliffc.aa.type.TypeTuple.str(), com.cliffc.aa.type.Type< TypeFlt >.toString(), and com.cliffc.aa.node.Node.ErrMsg.typerr().
toString()
final String com.cliffc.aa.type.Type< T extends Type< T >.toString ()
Definition at line 127 of file Type.java.
 { return str(new SB(),new VBitSet(),null,true).toString(); }
Referenced by com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM5.T2._p(), com.cliffc.aa.HM.HM6.T2._p(), com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.AA.main(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM4.Con.p1(), com.cliffc.aa.HM.HM5.Con.p1(), com.cliffc.aa.HM.HM6.Con.p1(), com.cliffc.aa.HM.HM7.Con.p1(), com.cliffc.aa.HM.HM8.Con.p1(), com.cliffc.aa.HM.HM9.Con.p1(), com.cliffc.aa.HM.HM.Con.p1(), com.cliffc.aa.HM.HM4.T2.str(), com.cliffc.aa.HM.HM5.T2.str(), com.cliffc.aa.HM.HM6.T2.str(), com.cliffc.aa.HM.HM7.T2.str(), com.cliffc.aa.HM.HM8.T2.str(), com.cliffc.aa.HM.HM1.Con.toString(), com.cliffc.aa.HM.HM2.Con.toString(), and com.cliffc.aa.HM.HM3.Con.toString().
typerr()
RuntimeException com.cliffc.aa.type.Type< T extends Type< T >.typerr (Type< T extends Type< T > t) package
Definition at line 947 of file Type.java.
{
     throw new RuntimeException("Should not reach here: internal type system error with "+this+(t==null?"":(" and "+t)));
   }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.Type< TypeFlt >.getd(), com.cliffc.aa.type.Type< TypeFlt >.getl(), com.cliffc.aa.type.Type< TypeFlt >.getstr(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.isBitShape(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.may_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), com.cliffc.aa.type.Type< TypeFlt >.not_nil(), com.cliffc.aa.type.Type< TypeFlt >.widen(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
untern()
final T com.cliffc.aa.type.Type< T extends Type< T >.untern () package
Definition at line 193 of file Type.java.
                     {
     assert _hash != 0;
     assert INTERN.get(this)==this;
     Type rez = INTERN.remove(this);
     assert rez == this;
     return (T)this;
   }
walk()
void com.cliffc.aa.type.Type< T extends Type< T >.walk (Predicate< Type< T extends Type< T > > p)
Definition at line 936 of file Type.java.
 { assert is_simple(); p.test(this); }
Referenced by com.cliffc.aa.type.TypeFunPtr.walk(), and com.cliffc.aa.type.TypeFld.walk().
widen()
Type com.cliffc.aa.type.Type< T extends Type< T >.widen ()
Definition at line 828 of file Type.java.
                       {
     switch( _type ) {
     case TREAL:   case TXREAL:
     case TSCALAR: case TXSCALAR:
     case TNSCALR: case TXNSCALR:
     case TNIL:    case TXNIL:
       return SCALAR;
     case TANY : case TALL  :
       return this;
     case TCTRL: case TXCTRL:
       return Type.CTRL;
     default: throw typerr(null); // Overridden in subclass
     }
   }
Referenced by com.cliffc.aa.HM.HM9.T2._can_be_HM_base(), com.cliffc.aa.HM.HM.T2._can_be_HM_base(), com.cliffc.aa.node.FunNode.find_type_split(), com.cliffc.aa.node.FunNode.find_type_split_index(), com.cliffc.aa.tvar.TV2.make_base(), com.cliffc.aa.HM.HM9.T2.union(), com.cliffc.aa.HM.HM.T2.union(), com.cliffc.aa.HM.HM9.T2.walk_types_in(), com.cliffc.aa.HM.HM.T2.walk_types_in(), and com.cliffc.aa.type.TypeStruct.widen().
xdual()
T com.cliffc.aa.type.Type< T extends Type< T >.xdual () package
Definition at line 365 of file Type.java.
 { return (T)new Type().init((byte)(_type^1),""); }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.hashcons().
xmeet()
Type com.cliffc.aa.type.Type< T extends Type< T >.xmeet (Type< T extends Type< T > t) protected
Definition at line 461 of file Type.java.
{
     assert is_simple(); // Should be overridden in subclass
     // ANY meet anything is thing; thing meet ALL is ALL
     if( _type==TALL || t._type==TANY ) return this;
     if( _type==TANY || t._type==TALL ) return    t;
     // Ctrl can only meet Ctrl, XCtrl or Top
     byte type = (byte)(_type|t._type); // the OR is low if both are low
     if(  type <= TXCTRL ) return _type==TXCTRL && t._type==TXCTRL ? XCTRL : CTRL;
     if( _type <= TXCTRL || t._type <= TXCTRL ) return ALL;
     // Meeting scalar and non-scalar falls to ALL.  Includes most Memory shapes.
     if( isa_scalar() ^ t.isa_scalar() ) return ALL;
     // Memory does something complex with memory
     if( t._type==TMEM ) return t.xmeet(this);
     // Scalar is close to bottom: nearly everything falls to SCALAR, except
     // Bottom (already handled) and Control (error; already handled).
     if( _type == TSCALAR || t._type == TSCALAR ) return SCALAR;
     // ~Scalar is close to Top: it falls to nearly anything.
     if(   _type == TXSCALAR ) return t   ;
     if( t._type == TXSCALAR ) return this;
     // Not-nil variants
     if(   _type == TNSCALR ) return t.must_nil() ? SCALAR : NSCALR;
     if( t._type == TNSCALR ) return   must_nil() ? SCALAR : NSCALR;
     if(   _type == TXNSCALR) return t.not_nil();
     if( t._type == TXNSCALR) return   not_nil();
     if( _type == TNIL || _type == TXNIL ) return t.meet_nil(this);
     // Scalar values break out into: nums(reals (int,flt)), GC-ptrs (structs(tuples), arrays(strings)), fun-ptrs, RPC
     if( t._type == TFUNPTR ||
         t._type == TMEMPTR ||
         t._type == TRPC   )
       return cross_nil(t);
     boolean that_oop = t.is_ptr();
     boolean that_num = t.is_num();
     assert !(that_oop&&that_num);
     // Down to just nums and GC-ptrs
     if( is_num() ) {
       // May be OOP0 or STR or STRUCT or TUPLE
       if( that_oop ) return (must_nil() || t.must_nil()) ? SCALAR : NSCALR;
       if( that_num || t==NIL || t==XNIL ) {
         // Real; same pattern as ANY/ALL, or SCALAR/XSCALAR
         if( _type == TREAL || t._type == TREAL ) return REAL;
         if(   _type == TXREAL ) return t   ;
         if( t._type == TXREAL ) return this;
         // Not-nil variants
         if(   _type == TNREAL ) return t.must_nil() ? REAL : NREAL;
         if( t._type == TNREAL ) return   must_nil() ? REAL : NREAL;
         if(   _type == TXNREAL) return t.not_nil();
         if( t._type == TXNREAL) return   not_nil();
       }
     }
     throw typerr(t);
   }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.check_commute(), com.cliffc.aa.type.Type< TypeFlt >.meet(), com.cliffc.aa.type.TypeAry.xmeet(), com.cliffc.aa.type.TypeStr.xmeet(), com.cliffc.aa.type.TypeLive.xmeet(), com.cliffc.aa.type.TypeFunPtr.xmeet(), com.cliffc.aa.type.TypeStruct.xmeet(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
xmt_name()
Type com.cliffc.aa.type.Type< T extends Type< T >.xmt_name (Type< T extends Type< T > t, Type< T extends Type< T > mt) private
Definition at line 441 of file Type.java.
{
     String n = mtname(t,mt);    // Meet name strings
     // If the names are incompatible and the meet remained high then the
     // mismatched names force a drop.
     if( n.length() < _name.length() && n.length() < t._name.length() && mt.above_center() ) {
       if( mt.interned() ) // recursive type creation?
         mt = mt.dual();   // Force low
     }
     if( mt.is_simple() ) n=""; // No named simple types
     if( mt._type==TOBJ ) n=""; // OBJ splits into strings (arrays) and structs, which can keep their names
     // Inject the name
     if( !Util.eq(mt._name,n) )  // Fast path cutout
       mt = mt.set_name(n);
     return mt;
   }
Referenced by com.cliffc.aa.type.Type< TypeFlt >.check_commute(), and com.cliffc.aa.type.Type< TypeFlt >.meet().
Member Data Documentation
_dual
T com.cliffc.aa.type.Type< T extends Type< T >._dual package
Definition at line 100 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.check_symmetric(), com.cliffc.aa.type.Type< TypeFlt >.clone(), com.cliffc.aa.type.Type< TypeFlt >.dual(), com.cliffc.aa.type.Type< TypeFlt >.hashcons(), com.cliffc.aa.type.Type< TypeFlt >.intern_check0(), com.cliffc.aa.type.TypeStruct.rdual(), com.cliffc.aa.type.Type< TypeFlt >.rdual(), com.cliffc.aa.type.Type< TypeFlt >.retern(), and com.cliffc.aa.type.TypeFld.xdual().
_hash
int com.cliffc.aa.type.Type< T extends Type< T >._hash
Definition at line 97 of file Type.java.
Referenced by com.cliffc.aa.type.TypeStruct._sharp(), com.cliffc.aa.type.TypeFunPtr._sharpen_clone(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.Type< TypeFlt >.clone(), com.cliffc.aa.type.TypeAry.compute_hash(), com.cliffc.aa.type.TypeTuple.compute_hash(), com.cliffc.aa.type.TypeFunSig.compute_hash(), com.cliffc.aa.type.TypeMemPtr.compute_hash(), com.cliffc.aa.type.TypeFunPtr.compute_hash(), com.cliffc.aa.type.TypeStruct.compute_hash(), com.cliffc.aa.type.TypeTuple.equals(), com.cliffc.aa.node.CEProjNode.hashCode(), com.cliffc.aa.type.Type< TypeFlt >.hashCode(), com.cliffc.aa.node.PrimNode.hashCode(), com.cliffc.aa.type.Type< T extends Type< T >.Key.hashCode(), com.cliffc.aa.type.Type< TypeFlt >.hashcons(), com.cliffc.aa.type.Type< TypeFlt >.intern_check0(), com.cliffc.aa.type.TypeStruct.post_mod(), com.cliffc.aa.type.TypeStruct.push(), com.cliffc.aa.type.Type< TypeFlt >.retern(), com.cliffc.aa.type.TypeStruct.shrink(), and com.cliffc.aa.type.Type< TypeFlt >.untern().
_name
String com.cliffc.aa.type.Type< T extends Type< T >._name
Definition at line 99 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >._set_name(), com.cliffc.aa.node.PrimNode.ConvertTypeName.apply(), com.cliffc.aa.type.Type< TypeFlt >.compute_hash(), com.cliffc.aa.node.IntrinsicNode.convertTypeName(), com.cliffc.aa.node.PrimNode.ConvertTypeName.ConvertTypeName(), com.cliffc.aa.type.Type< TypeFlt >.cycle_equals(), com.cliffc.aa.node.ConTypeNode.def_fref(), com.cliffc.aa.type.Type< TypeFlt >.equals(), com.cliffc.aa.type.Type< TypeFlt >.has_name(), com.cliffc.aa.type.Type< TypeFlt >.hashcons(), com.cliffc.aa.node.IntrinsicNode.ideal_reduce(), com.cliffc.aa.type.Type< TypeFlt >.init(), com.cliffc.aa.type.Type< TypeFlt >.mtname(), com.cliffc.aa.type.Type< TypeFlt >.str(), com.cliffc.aa.node.IntrinsicNode.value(), com.cliffc.aa.type.Type< TypeFlt >.xmt_name(), and com.cliffc.aa.node.IntrinsicNode.xstr().
_type
byte com.cliffc.aa.type.Type< T extends Type< T >._type package
Definition at line 98 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >._set_name(), com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.TypeStruct.approx(), com.cliffc.aa.type.TypeStruct.ax_impl_struct(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.Type< TypeFlt >.clone(), com.cliffc.aa.type.Type< TypeFlt >.compute_hash(), com.cliffc.aa.type.Type< TypeFlt >.cycle_equals(), com.cliffc.aa.type.Type< TypeFlt >.equals(), com.cliffc.aa.type.TypeStruct.get_cyclic(), com.cliffc.aa.type.Type< TypeFlt >.getd(), com.cliffc.aa.type.Type< TypeFlt >.getl(), com.cliffc.aa.type.Type< TypeFlt >.hashcons_free(), com.cliffc.aa.type.Type< TypeFlt >.init(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.is_display_ptr(), com.cliffc.aa.type.Type< TypeFlt >.is_num(), com.cliffc.aa.type.Type< TypeFlt >.is_ptr(), com.cliffc.aa.type.Type< TypeFlt >.is_simple(), com.cliffc.aa.type.Type< TypeFlt >.isa_scalar(), com.cliffc.aa.type.TypeStr.isBitShape(), com.cliffc.aa.type.TypeFlt.isBitShape(), com.cliffc.aa.type.TypeInt.isBitShape(), com.cliffc.aa.type.TypeFunPtr.isBitShape(), com.cliffc.aa.type.Type< TypeFlt >.isBitShape(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.may_nil(), com.cliffc.aa.type.TypeMem.meet_loop(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), com.cliffc.aa.type.Type< TypeFlt >.not_nil(), com.cliffc.aa.type.Type< T extends Type< T >.Pool.Pool(), com.cliffc.aa.type.TypeStruct.push(), com.cliffc.aa.type.TypeStruct.reachable(), com.cliffc.aa.type.TypeStruct.shrink(), com.cliffc.aa.type.Type< TypeFlt >.str(), com.cliffc.aa.type.Type< TypeFlt >.widen(), com.cliffc.aa.type.Type< TypeFlt >.xdual(), com.cliffc.aa.type.TypeRPC.xmeet(), com.cliffc.aa.type.TypeFlt.xmeet(), com.cliffc.aa.type.TypeAry.xmeet(), com.cliffc.aa.type.TypeLive.xmeet(), com.cliffc.aa.type.TypeStr.xmeet(), com.cliffc.aa.type.TypeInt.xmeet(), com.cliffc.aa.type.TypeFld.xmeet(), com.cliffc.aa.type.TypeFunSig.xmeet(), com.cliffc.aa.type.TypeFunPtr.xmeet(), com.cliffc.aa.type.TypeMemPtr.xmeet(), com.cliffc.aa.type.TypeTuple.xmeet(), com.cliffc.aa.type.TypeMem.xmeet(), com.cliffc.aa.type.TypeStruct.xmeet(), com.cliffc.aa.type.Type< TypeFlt >.xmeet(), and com.cliffc.aa.type.Type< TypeFlt >.xmt_name().
_uid
int com.cliffc.aa.type.Type< T extends Type< T >._uid
Definition at line 96 of file Type.java.
Referenced by com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.Type< TypeFlt >.clone(), com.cliffc.aa.type.TypeStruct.get_cyclic(), com.cliffc.aa.type.Type< TypeFlt >.intern_check(), com.cliffc.aa.type.Type< TypeFlt >.Type(), com.cliffc.aa.HM.HM9.T2.walk_types_in(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
ALL
final Type com.cliffc.aa.type.Type< T extends Type< T >.ALL = make(TALL) static
Definition at line 324 of file Type.java.
Referenced by com.cliffc.aa.tvar.TV2._find_tvar(), com.cliffc.aa.node.PrimNode.ConvertTypeName.apply(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM.EQ0.apply(), com.cliffc.aa.node.CallNode.CallNode(), com.cliffc.aa.type.TypeStruct.crush(), com.cliffc.aa.node.ErrNode.err(), com.cliffc.aa.node.ParmNode.err(), com.cliffc.aa.node.StoreNode.err(), com.cliffc.aa.node.LoadNode.err(), com.cliffc.aa.tvar.TV2.find_tvar(), com.cliffc.aa.node.FunNode.find_type_split(), com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.node.FunNode.ideal_reduce(), com.cliffc.aa.type.TypeFunSig.init(), com.cliffc.aa.node.CallNode.least_cost(), com.cliffc.aa.type.TypeTuple.make_args(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.NewPrimNode(), com.cliffc.aa.node.Node.Node(), com.cliffc.aa.type.Type< TypeFlt >.oob(), com.cliffc.aa.node.PrimNode.PrimNode(), com.cliffc.aa.node.ScopeNode.set_mem(), com.cliffc.aa.node.FunNode.split_size(), com.cliffc.aa.TestLive.testNewObj(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.Env.top_scope(), com.cliffc.aa.node.Node.ErrMsg.typerr(), com.cliffc.aa.node.CProjNode.value(), com.cliffc.aa.node.ErrNode.value(), com.cliffc.aa.node.UnresolvedNode.value(), com.cliffc.aa.node.IfNode.value(), com.cliffc.aa.node.PhiNode.value(), com.cliffc.aa.node.ParmNode.value(), com.cliffc.aa.node.StoreNode.value(), com.cliffc.aa.node.RegionNode.value(), com.cliffc.aa.node.ScopeNode.value(), com.cliffc.aa.node.MemJoinNode.value(), com.cliffc.aa.node.CallEpiNode.value(), com.cliffc.aa.node.FunNode.value(), com.cliffc.aa.node.NewObjNode.valueobj(), com.cliffc.aa.node.Node.walkerr_def(), com.cliffc.aa.node.CallEpiNode.wire0(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
ALL_TYPES
Ary<Type> com.cliffc.aa.type.Type< T extends Type< T >.ALL_TYPES static private
Definition at line 650 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.ALL_TYPES(), com.cliffc.aa.type.Type< TypeFlt >.check_startup(), and com.cliffc.aa.node.TestNode.testMonotonic().
ANY
final Type com.cliffc.aa.type.Type< T extends Type< T >.ANY = make(TANY) static
Definition at line 325 of file Type.java.
Referenced by com.cliffc.aa.HM.HM9.T2._as_flow(), com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.tvar.TV2._find_tvar(), com.cliffc.aa.HM.HM1.HMVar._str(), com.cliffc.aa.HM.HM2.HMVar._str(), com.cliffc.aa.HM.HM3.HMVar._str(), com.cliffc.aa.node.CallNode.add_flow_extra(), com.cliffc.aa.node.PrimNode.ConvertTypeName.apply(), com.cliffc.aa.type.TypeStruct.ax_impl_fptr(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.node.CallNode.CallNode(), com.cliffc.aa.node.MemPrimNode.err(), com.cliffc.aa.node.StoreNode.err(), com.cliffc.aa.node.LoadNode.err(), com.cliffc.aa.HM.HM1.HMVar.HMVar(), com.cliffc.aa.HM.HM2.HMVar.HMVar(), com.cliffc.aa.HM.HM3.HMVar.HMVar(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.type.TypeFunSig.init(), com.cliffc.aa.node.CallNode.is_copy(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.Parse.prog(), com.cliffc.aa.node.NewObjNode.promote_forward(), com.cliffc.aa.node.ScopeNode.set_mem(), com.cliffc.aa.type.Type< TypeFlt >.sharptr(), com.cliffc.aa.node.TestNode.test1monotonic_init(), com.cliffc.aa.HM.TestHM9.test35(), com.cliffc.aa.HM.TestHM.test35(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.TestLive.testNewObj(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.TestParse.testParse15(), com.cliffc.aa.node.TestNodeSmall.testUnresolvedAdd(), com.cliffc.aa.Env.top_scope(), com.cliffc.aa.Parse.type0(), com.cliffc.aa.Parse.typev(), com.cliffc.aa.HM.HM1.HMVar.union(), com.cliffc.aa.HM.HM2.HMVar.union(), com.cliffc.aa.HM.HM3.HMVar.union(), com.cliffc.aa.HM.HM9.Lambda.val(), com.cliffc.aa.HM.HM.Lambda.val(), com.cliffc.aa.node.DefMemNode.value(), com.cliffc.aa.node.CProjNode.value(), com.cliffc.aa.node.ErrNode.value(), com.cliffc.aa.node.UnresolvedNode.value(), com.cliffc.aa.node.PhiNode.value(), com.cliffc.aa.node.ParmNode.value(), com.cliffc.aa.node.NewStrNode.AddStrStr.value(), com.cliffc.aa.node.MemJoinNode.value(), com.cliffc.aa.node.CallEpiNode.value(), and com.cliffc.aa.node.Node.walk_initype().
CNT
int com.cliffc.aa.type.Type< T extends Type< T >.CNT =1 static private
Definition at line 95 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >._uid().
CTRL
final Type com.cliffc.aa.type.Type< T extends Type< T >.CTRL = make(TCTRL) static
Definition at line 326 of file Type.java.
Referenced by com.cliffc.aa.node.NewStrNode.AddStrStr._value(), com.cliffc.aa.node.NewStrNode.AddStrStr.AddStrStr(), com.cliffc.aa.node.ConNode< T extends Type >.all_live(), com.cliffc.aa.node.TestNodeSmall.check(), com.cliffc.aa.node.NewStrNode.ConStr.ConStr(), com.cliffc.aa.node.NewStrNode.ConvertF64Str.ConvertF64Str(), com.cliffc.aa.node.NewStrNode.ConvertI64Str.ConvertI64Str(), com.cliffc.aa.Parse.do_exit(), com.cliffc.aa.node.FunNode.find_type_split(), com.cliffc.aa.Parse.func(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.node.CEProjNode.good_call(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.CastNode.ideal_reduce(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.Parse.ifex(), com.cliffc.aa.type.TypeFunSig.init(), com.cliffc.aa.node.Node.live(), com.cliffc.aa.type.TypeTuple.make(), com.cliffc.aa.type.TypeTuple.make_args(), com.cliffc.aa.type.TypeTuple.make_ret(), com.cliffc.aa.Parse.merge_exits(), com.cliffc.aa.node.NewAryNode.NewAryNode(), com.cliffc.aa.node.RetNode.tail_recursive(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.Env.top_scope(), com.cliffc.aa.Parse.type0(), com.cliffc.aa.node.CEProjNode.value(), com.cliffc.aa.node.ThunkNode.value(), com.cliffc.aa.node.CastNode.value(), com.cliffc.aa.node.IfNode.value(), com.cliffc.aa.node.PhiNode.value(), com.cliffc.aa.node.ParmNode.value(), com.cliffc.aa.node.NewNode< TypeStruct >.value(), com.cliffc.aa.node.RegionNode.value(), com.cliffc.aa.node.RetNode.value(), com.cliffc.aa.node.CallEpiNode.value(), com.cliffc.aa.node.CallNode.value(), com.cliffc.aa.node.FunNode.value(), com.cliffc.aa.type.Type< TypeFlt >.widen(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
INTERN
final ConcurrentHashMap<Type,Type> com.cliffc.aa.type.Type< T extends Type< T >.INTERN = new ConcurrentHashMap<>() static private
Definition at line 162 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.hashcons(), com.cliffc.aa.type.Type< TypeFlt >.intern_check(), com.cliffc.aa.type.Type< TypeFlt >.intern_find(), com.cliffc.aa.type.Type< TypeFlt >.intern_lookup(), com.cliffc.aa.type.Type< TypeFlt >.intern_size(), com.cliffc.aa.type.Type< TypeFlt >.interned(), com.cliffc.aa.type.Type< TypeFlt >.retern(), and com.cliffc.aa.type.Type< TypeFlt >.untern().
ISA_SCALAR
final byte [] com.cliffc.aa.type.Type< T extends Type< T >.ISA_SCALAR = new byte[]{0,0,0,0,1,1,1,1,1,1,1,1,1,1,0, 1,1,1,0,0,0,0,0,0,0,1,1,0,0} static private
Definition at line 355 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.isa_scalar().
NIL
final Type com.cliffc.aa.type.Type< T extends Type< T >.NIL = make(TNIL) static
Definition at line 332 of file Type.java.
Referenced by com.cliffc.aa.HM.HM7.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM8.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.HM.HM9.If.apply(), com.cliffc.aa.HM.HM.If.apply(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM.EQ0.apply(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.TestApprox.check_leaf(), com.cliffc.aa.node.CallEpiNode.esc_out(), com.cliffc.aa.HM.HM7.Apply.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM9.If.hm(), com.cliffc.aa.HM.HM.If.hm(), com.cliffc.aa.type.Type< TypeFlt >.meet(), com.cliffc.aa.type.TypeFlt.meet_nil(), com.cliffc.aa.type.TypeInt.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.HM.HM7.T2.or0(), com.cliffc.aa.HM.HM8.T2.or0(), com.cliffc.aa.HM.HM7.Con.prep_tree(), com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM7.T2.str(), com.cliffc.aa.HM.HM8.T2.str(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox4(), com.cliffc.aa.node.TestNodeSmall.testMemoryArgs(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.TestLive.testNewObj(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.TestParse.testParse04(), com.cliffc.aa.TestParse.testParse06(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.type.TestType.testStructTuple(), com.cliffc.aa.Env.top_scope(), com.cliffc.aa.node.IfNode.value(), com.cliffc.aa.node.PrimNode.OrI64.value(), com.cliffc.aa.node.PrimNode.EQ_OOP.value(), com.cliffc.aa.node.PrimNode.NE_OOP.value(), com.cliffc.aa.node.PrimNode.EQ_OOP.vs_nil(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
NREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.NREAL = make(TNREAL) static package
Definition at line 336 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.xmeet().
NSCALR
final Type com.cliffc.aa.type.Type< T extends Type< T >.NSCALR = make(TNSCALR) static
Definition at line 330 of file Type.java.
Referenced by com.cliffc.aa.node.LoadNode._live_use(), com.cliffc.aa.HM.HM.NotNil.apply(), com.cliffc.aa.HM.HM9.NotNil.apply(), com.cliffc.aa.type.Type< TypeFlt >.cross_nil(), com.cliffc.aa.node.PhiNode.err(), com.cliffc.aa.HM.HM9.NotNil.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.node.NewObjNode.live_use(), com.cliffc.aa.HM.TestHM.test18(), com.cliffc.aa.HM.TestHM9.test18(), com.cliffc.aa.HM.TestHM.test45(), com.cliffc.aa.HM.TestHM9.test45(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.HM.HM.T2.unify_nil(), com.cliffc.aa.HM.HM.T2.walk_types_in(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
POOLS
final Pool [] com.cliffc.aa.type.Type< T extends Type< T >.POOLS = new Pool[TLAST] static package
Definition at line 281 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >._set_name(), com.cliffc.aa.type.Type< TypeFlt >.clone(), com.cliffc.aa.type.Type< TypeFlt >.hashcons_free(), com.cliffc.aa.type.Type< TypeFlt >.make(), and com.cliffc.aa.type.Type< T extends Type< T >.Pool.Pool().
REAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.REAL = make(TREAL) static
Definition at line 334 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.init0(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.node.PrimNode.PRIMS(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.type.TestApprox.testTSMeet(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
RECURSIVE_MEET
int com.cliffc.aa.type.Type< T extends Type< T >.RECURSIVE_MEET static
Definition at line 163 of file Type.java.
Referenced by com.cliffc.aa.HM.HM9.T2._as_flow(), com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.type.Type< TypeFlt >.hashcons(), com.cliffc.aa.type.Type< TypeFlt >.meet(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.type.TestType.testNameCycle(), and com.cliffc.aa.type.TestApprox.testTSMeet().
SCALAR
final Type com.cliffc.aa.type.Type< T extends Type< T >.SCALAR = make(TSCALAR) static
Definition at line 328 of file Type.java.
Referenced by com.cliffc.aa.HM.HM9.T2._as_flow(), com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.node.MemPrimNode.LValueLength._live_use(), com.cliffc.aa.node.LoadNode._live_use(), com.cliffc.aa.type.TypeStruct.add_fld(), com.cliffc.aa.node.PhiNode.all_live(), com.cliffc.aa.node.PrimNode.AndThen.AndThen(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.Type< TypeFlt >.check_startup(), com.cliffc.aa.node.NewObjNode.create_active(), com.cliffc.aa.type.Type< TypeFlt >.cross_nil(), com.cliffc.aa.type.TypeAry.crush(), com.cliffc.aa.Parse.do_exit(), com.cliffc.aa.node.PhiNode.err(), com.cliffc.aa.type.TypeStruct.flatten_fields(), com.cliffc.aa.node.FunPtrNode.forward_ref(), com.cliffc.aa.Parse.func(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.LoadNode.ideal_grow(), com.cliffc.aa.node.PrimNode.AndThen.ideal_grow(), com.cliffc.aa.node.PrimNode.OrElse.ideal_grow(), com.cliffc.aa.Parse.ifex(), com.cliffc.aa.Env.init(), com.cliffc.aa.type.Type< TypeFlt >.init0(), com.cliffc.aa.type.TypeMemPtr.isBitShape(), com.cliffc.aa.node.MemPrimNode.ReadPrimNode.live_use(), com.cliffc.aa.node.NewStrNode.AddStrStr.live_use(), com.cliffc.aa.node.MemPrimNode.LValueRead.LValueRead(), com.cliffc.aa.node.MemPrimNode.LValueWrite.LValueWrite(), com.cliffc.aa.node.MemPrimNode.LValueWriteFinal.LValueWriteFinal(), com.cliffc.aa.type.TypeFunSig.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.node.PrimNode.OrElse.OrElse(), com.cliffc.aa.node.PhiNode.PhiNode(), com.cliffc.aa.type.TypeFld.str(), com.cliffc.aa.type.TypeFunSig.str(), com.cliffc.aa.HM.TestHM.test02(), com.cliffc.aa.HM.TestHM9.test02(), com.cliffc.aa.HM.TestHM.test07(), com.cliffc.aa.HM.TestHM9.test07(), com.cliffc.aa.HM.TestHM.test10(), com.cliffc.aa.HM.TestHM9.test10(), com.cliffc.aa.HM.TestHM.test11(), com.cliffc.aa.HM.TestHM9.test11(), com.cliffc.aa.HM.TestHM.test27(), com.cliffc.aa.HM.TestHM9.test27(), com.cliffc.aa.HM.TestHM.test28(), com.cliffc.aa.HM.TestHM9.test28(), com.cliffc.aa.HM.TestHM9.test32(), com.cliffc.aa.HM.TestHM.test32(), com.cliffc.aa.HM.TestHM9.test33(), com.cliffc.aa.HM.TestHM.test33(), com.cliffc.aa.HM.TestHM.test39(), com.cliffc.aa.HM.TestHM9.test39(), com.cliffc.aa.HM.TestHM.test40(), com.cliffc.aa.HM.TestHM9.test40(), com.cliffc.aa.HM.TestHM.test51(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.HM.TestHM.test53(), com.cliffc.aa.HM.TestHM.test54(), com.cliffc.aa.type.TestApprox.testApprox5(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.TestParse.testParse03(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.Parse.type0(), com.cliffc.aa.node.NewObjNode.update(), com.cliffc.aa.HM.HM9.Apply.val(), com.cliffc.aa.HM.HM.Apply.val(), com.cliffc.aa.HM.HM9.Field.val(), com.cliffc.aa.HM.HM.Field.val(), com.cliffc.aa.node.CastNode.value(), com.cliffc.aa.node.MemPrimNode.LValueRead.value(), com.cliffc.aa.node.MemPrimNode.LValueWrite.value(), com.cliffc.aa.node.MemPrimNode.LValueWriteFinal.value(), com.cliffc.aa.HM.HM9.T2.walk_types_in(), com.cliffc.aa.HM.HM.T2.walk_types_in(), com.cliffc.aa.type.Type< TypeFlt >.widen(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
SCALAR_PRIMS
Type [] com.cliffc.aa.type.Type< T extends Type< T >.SCALAR_PRIMS static private
Definition at line 349 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.check_startup().
STRS
final String [] com.cliffc.aa.type.Type< T extends Type< T >.STRS = new String[]{"all","any","Ctrl","~Ctrl","Scalar","~Scalar","nScalar","~nScalar","Real","~Real","nReal","~nReal","nil","0"} static private
Definition at line 262 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.str().
TALL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TALL = 0 static package
Definition at line 239 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.is_display_ptr(), com.cliffc.aa.type.TypeFlt.isBitShape(), com.cliffc.aa.type.TypeInt.isBitShape(), com.cliffc.aa.type.Type< TypeFlt >.isBitShape(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.may_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), com.cliffc.aa.type.Type< TypeFlt >.widen(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TANY
final byte com.cliffc.aa.type.Type< T extends Type< T >.TANY = 1 static package
Definition at line 240 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.is_display_ptr(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.may_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), com.cliffc.aa.type.Type< TypeFlt >.widen(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TARY
final byte com.cliffc.aa.type.Type< T extends Type< T >.TARY =21 static package
Definition at line 269 of file Type.java.
TCTRL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TCTRL = 2 static package
Definition at line 241 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.may_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), and com.cliffc.aa.type.Type< TypeFlt >.widen().
TFLD
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFLD =23 static package
Definition at line 271 of file Type.java.
TFLT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFLT =16 static package
Definition at line 264 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.is_num(), and com.cliffc.aa.type.TypeFlt.isBitShape().
TFUNPTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFUNPTR =26 static package
Definition at line 274 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.is_ptr(), com.cliffc.aa.type.TypeFlt.isBitShape(), com.cliffc.aa.type.TypeInt.isBitShape(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TFUNSIG
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFUNSIG =27 static package
Definition at line 275 of file Type.java.
TINT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TINT =15 static package
Definition at line 263 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.is_num(), and com.cliffc.aa.type.TypeFlt.isBitShape().
TLAST
final byte com.cliffc.aa.type.Type< T extends Type< T >.TLAST =29 static package
Definition at line 277 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.isa_scalar().
TLIVE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TLIVE =28 static package
Definition at line 276 of file Type.java.
TMEM
final byte com.cliffc.aa.type.Type< T extends Type< T >.TMEM =24 static package
Definition at line 272 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.may_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TMEMPTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TMEMPTR =25 static package
Definition at line 273 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.is_ptr(), com.cliffc.aa.type.TypeFlt.isBitShape(), com.cliffc.aa.type.TypeInt.isBitShape(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TNIL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNIL =12 static package
Definition at line 259 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.Type< TypeFlt >.getd(), com.cliffc.aa.type.Type< TypeFlt >.getl(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.is_display_ptr(), com.cliffc.aa.type.Type< TypeFlt >.isBitShape(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), com.cliffc.aa.type.Type< TypeFlt >.not_nil(), com.cliffc.aa.type.Type< TypeFlt >.widen(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TNREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNREAL =10 static package
Definition at line 257 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.is_num(), com.cliffc.aa.type.Type< TypeFlt >.isBitShape(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.may_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), com.cliffc.aa.type.Type< TypeFlt >.not_nil(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TNSCALR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNSCALR = 6 static package
Definition at line 253 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.isBitShape(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.may_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), com.cliffc.aa.type.Type< TypeFlt >.not_nil(), com.cliffc.aa.type.Type< TypeFlt >.widen(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TOBJ
final byte com.cliffc.aa.type.Type< T extends Type< T >.TOBJ =19 static package
Definition at line 267 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), and com.cliffc.aa.type.Type< TypeFlt >.xmt_name().
TREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TREAL = 8 static package
Definition at line 255 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.is_num(), com.cliffc.aa.type.TypeFlt.isBitShape(), com.cliffc.aa.type.Type< TypeFlt >.isBitShape(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.may_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), com.cliffc.aa.type.Type< TypeFlt >.not_nil(), com.cliffc.aa.type.Type< TypeFlt >.widen(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TRPC
final byte com.cliffc.aa.type.Type< T extends Type< T >.TRPC =17 static package
Definition at line 265 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TSCALAR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSCALAR = 4 static package
Definition at line 246 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.is_display_ptr(), com.cliffc.aa.type.Type< TypeFlt >.isBitShape(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.may_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), com.cliffc.aa.type.Type< TypeFlt >.not_nil(), com.cliffc.aa.type.Type< TypeFlt >.widen(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TSIMPLE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSIMPLE =14 static package
Definition at line 261 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.is_simple().
TSTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSTR =22 static package
Definition at line 270 of file Type.java.
Referenced by com.cliffc.aa.type.TypeStr.isBitShape(), and com.cliffc.aa.type.Type< TypeFlt >.meet_nil().
TSTRUCT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSTRUCT =20 static package
Definition at line 268 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.meet_nil().
TTUPLE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TTUPLE =18 static package
Definition at line 266 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.may_nil().
TXCTRL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXCTRL = 3 static package
Definition at line 242 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.may_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), com.cliffc.aa.type.Type< TypeFlt >.widen(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TXNIL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNIL =13 static package
Definition at line 260 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.Type< TypeFlt >.getd(), com.cliffc.aa.type.Type< TypeFlt >.getl(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.is_display_ptr(), com.cliffc.aa.type.Type< TypeFlt >.isBitShape(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), com.cliffc.aa.type.Type< TypeFlt >.not_nil(), com.cliffc.aa.type.Type< TypeFlt >.widen(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TXNREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNREAL =11 static package
Definition at line 258 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.is_num(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.may_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), com.cliffc.aa.type.Type< TypeFlt >.not_nil(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TXNSCALR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNSCALR = 7 static package
Definition at line 254 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.may_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), com.cliffc.aa.type.Type< TypeFlt >.not_nil(), com.cliffc.aa.type.Type< TypeFlt >.widen(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TXREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXREAL = 9 static package
Definition at line 256 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.is_num(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.may_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), com.cliffc.aa.type.Type< TypeFlt >.not_nil(), com.cliffc.aa.type.Type< TypeFlt >.widen(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TXSCALAR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXSCALAR = 5 static package
Definition at line 247 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.above_center(), com.cliffc.aa.type.Type< TypeFlt >.is_con(), com.cliffc.aa.type.Type< TypeFlt >.is_display_ptr(), com.cliffc.aa.type.Type< TypeFlt >.may_be_con(), com.cliffc.aa.type.Type< TypeFlt >.may_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.must_nil(), com.cliffc.aa.type.Type< TypeFlt >.not_nil(), com.cliffc.aa.type.Type< TypeFlt >.widen(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
TYPES
final Type [] com.cliffc.aa.type.Type< T extends Type< T >.TYPES = new Type[]{ALL,CTRL,SCALAR,NSCALR,REAL,NREAL} static private
Definition at line 340 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.ALL_TYPES().
XCTRL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XCTRL = make(TXCTRL) static
Definition at line 327 of file Type.java.
Referenced by com.cliffc.aa.node.FunNode.check_callers(), com.cliffc.aa.node.CastNode.checked(), com.cliffc.aa.node.ParmNode.err(), com.cliffc.aa.node.IfNode.ideal_reduce(), com.cliffc.aa.node.RegionNode.ideal_reduce(), com.cliffc.aa.node.PhiNode.ideal_reduce(), com.cliffc.aa.node.ParmNode.ideal_reduce(), com.cliffc.aa.node.RetNode.ideal_reduce(), com.cliffc.aa.Parse.ifex(), com.cliffc.aa.type.TypeFunSig.init(), com.cliffc.aa.node.Node.live(), com.cliffc.aa.node.CallNode.live(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.Env.top_scope(), com.cliffc.aa.node.CEProjNode.value(), com.cliffc.aa.node.CProjNode.value(), com.cliffc.aa.node.ThunkNode.value(), com.cliffc.aa.node.ErrNode.value(), com.cliffc.aa.node.ConNode< T extends Type >.value(), com.cliffc.aa.node.PhiNode.value(), com.cliffc.aa.node.ParmNode.value(), com.cliffc.aa.node.RegionNode.value(), com.cliffc.aa.node.FunNode.value(), com.cliffc.aa.node.Node.walkerr_def(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
XNIL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNIL = make(TXNIL) static
Definition at line 333 of file Type.java.
Referenced by com.cliffc.aa.HM.HM.T2._find_nil(), com.cliffc.aa.HM.HM9.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.node.CallNode._ideal_grow(), com.cliffc.aa.HM.HM9.T2._unify(), com.cliffc.aa.HM.HM9.If.apply(), com.cliffc.aa.HM.HM.If.apply(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM.EQ0.apply(), com.cliffc.aa.HM.HM9.NotNil.apply(), com.cliffc.aa.HM.HM.NotNil.apply(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.Env.Env(), com.cliffc.aa.node.MemPrimNode.err(), com.cliffc.aa.node.CallEpiNode.esc_out(), com.cliffc.aa.HM.HM9.Field.hm(), com.cliffc.aa.HM.HM9.If.hm(), com.cliffc.aa.HM.HM.If.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.node.IfNode.ideal_reduce(), com.cliffc.aa.node.ScopeNode.ideal_reduce(), com.cliffc.aa.type.Type< TypeFlt >.meet(), com.cliffc.aa.type.TypeFlt.meet_nil(), com.cliffc.aa.type.TypeInt.meet_nil(), com.cliffc.aa.type.Type< TypeFlt >.meet_nil(), com.cliffc.aa.HM.HM9.number(), com.cliffc.aa.HM.HM.number(), com.cliffc.aa.Parse.number(), com.cliffc.aa.HM.HM.Con.prep_tree(), com.cliffc.aa.HM.TestHM.test38(), com.cliffc.aa.HM.TestHM9.test38(), com.cliffc.aa.type.TestApprox.testApprox1(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestType.testBits0(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testMemoryArgs(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.TestParse.testParse(), com.cliffc.aa.TestParse.testParse00(), com.cliffc.aa.TestParse.testParse01(), com.cliffc.aa.TestParse.testParse01a(), com.cliffc.aa.TestParse.testParse02(), com.cliffc.aa.TestParse.testParse04(), com.cliffc.aa.TestParse.testParse05(), com.cliffc.aa.TestParse.testParse06(), com.cliffc.aa.TestParse.testParse07(), com.cliffc.aa.TestParse.testParse09(), com.cliffc.aa.TestParse.testParse11(), com.cliffc.aa.TestParse.testParse12(), com.cliffc.aa.TestParse.testParse14(), com.cliffc.aa.Env.top_scope(), com.cliffc.aa.Parse.typeq(), com.cliffc.aa.HM.HM9.T2.union(), com.cliffc.aa.HM.HM.T2.union(), com.cliffc.aa.node.IfNode.value(), com.cliffc.aa.node.NewStrNode.AddStrStr.value(), com.cliffc.aa.node.MemPrimNode.LValueRead.value(), com.cliffc.aa.node.MemPrimNode.LValueWrite.value(), com.cliffc.aa.node.MemPrimNode.LValueWriteFinal.value(), com.cliffc.aa.node.PrimNode.AndI64.value(), com.cliffc.aa.node.PrimNode.OrI64.value(), com.cliffc.aa.node.PrimNode.EQ_OOP.value(), com.cliffc.aa.node.PrimNode.NE_OOP.value(), com.cliffc.aa.node.PrimNode.Not.value(), com.cliffc.aa.node.NewAryNode.NewAry.valueobj(), com.cliffc.aa.node.PrimNode.EQ_OOP.vs_nil(), and com.cliffc.aa.type.Type< TypeFlt >.xmeet().
XNREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNREAL = make(TXNREAL) static private
Definition at line 337 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.not_nil().
XNSCALR
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNSCALR = make(TXNSCALR) static
Definition at line 331 of file Type.java.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.not_nil(), com.cliffc.aa.HM.TestHM.test18(), and com.cliffc.aa.HM.TestHM9.test18().
XREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XREAL = make(TXREAL) static private
Definition at line 335 of file Type.java.
XSCALAR
final Type com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR = make(TXSCALAR) static
Definition at line 329 of file Type.java.
Referenced by com.cliffc.aa.HM.HM.Root.add_sig(), com.cliffc.aa.HM.HM9.If.apply(), com.cliffc.aa.HM.HM.If.apply(), com.cliffc.aa.HM.HM.NotNil.apply(), com.cliffc.aa.HM.HM9.NotNil.apply(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.HM.HM9.Lambda.Lambda(), com.cliffc.aa.HM.HM.Lambda.Lambda(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM.Syntax.prep_tree_impl(), com.cliffc.aa.HM.TestHM.test37(), com.cliffc.aa.HM.TestHM9.test37(), com.cliffc.aa.HM.TestHM.test46(), com.cliffc.aa.HM.TestHM9.test46(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.type.TestType.testType(), com.cliffc.aa.HM.HM9.Apply.val(), com.cliffc.aa.HM.HM.Apply.val(), com.cliffc.aa.HM.HM9.Field.val(), com.cliffc.aa.HM.HM.Field.val(), com.cliffc.aa.node.CallNode.value(), com.cliffc.aa.HM.HM9.T2.walk_types_in(), com.cliffc.aa.HM.HM.T2.walk_types_in(), com.cliffc.aa.HM.HM9.T2.walk_types_out(), com.cliffc.aa.HM.HM.T2.walk_types_out(), and com.cliffc.aa.HM.HM9.Root.xval().
The documentation for this class was generated from the following file:
Type.java