aa: com.cliffc.aa.HM.HM8.Syntax Class Reference
com.cliffc.aa.HM.HM8.Syntax Class Reference abstract
Public Member Functions
String p ()
final String toString ()
Package Functions
abstract void add_work (Worklist work)
T2 debug_find ()
T2 find ()
abstract boolean hm (Worklist work)
abstract T2 lookup (String name)
abstract boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
abstract SB p1 (SB sb)
abstract SB p2 (SB sb, VBitSet dups)
T2 post ()
T2 pre ()
abstract void prep_lookup_deps (Ident id)
abstract int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
abstract SB str (SB sb)
Package Attributes
VStack _nongen
Syntax _par
T2 _post
T2 _pre
T2 _t
Detailed Description
Definition at line 239 of file HM8.java.
Member Function Documentation
add_work()
abstract void com.cliffc.aa.HM.HM8.Syntax.add_work (Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM8.Field, com.cliffc.aa.HM.HM8.Struct, com.cliffc.aa.HM.HM8.Apply, com.cliffc.aa.HM.HM8.Let, com.cliffc.aa.HM.HM8.Lambda, com.cliffc.aa.HM.HM8.Ident, and com.cliffc.aa.HM.HM8.Con.
Referenced by com.cliffc.aa.HM.HM8.Field.add_work(), and com.cliffc.aa.HM.HM8.hm().
debug_find()
T2 com.cliffc.aa.HM.HM8.Syntax.debug_find () package
Definition at line 249 of file HM8.java.
 { return _t.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM8.Syntax._t, and com.cliffc.aa.HM.HM8.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM8.hm().
find()
T2 com.cliffc.aa.HM.HM8.Syntax.find () package
Definition at line 245 of file HM8.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._t, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.T2._occurs_in(), com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Ident.hm(), com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.HM.HM8.Apply.is_if_nil(), and com.cliffc.aa.HM.HM8.Struct.prep_tree().
hm()
abstract boolean com.cliffc.aa.HM.HM8.Syntax.hm (Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM8.Field, com.cliffc.aa.HM.HM8.Struct, com.cliffc.aa.HM.HM8.Apply, com.cliffc.aa.HM.HM8.Let, com.cliffc.aa.HM.HM8.Lambda, com.cliffc.aa.HM.HM8.Ident, and com.cliffc.aa.HM.HM8.Con.
Referenced by com.cliffc.aa.HM.HM8.hm(), and com.cliffc.aa.HM.HM8.Syntax.more_work_impl().
lookup()
abstract T2 com.cliffc.aa.HM.HM8.Syntax.lookup (String name) abstract package
Reimplemented in com.cliffc.aa.HM.HM8.Field, com.cliffc.aa.HM.HM8.Struct, com.cliffc.aa.HM.HM8.Apply, com.cliffc.aa.HM.HM8.Let, com.cliffc.aa.HM.HM8.Lambda, com.cliffc.aa.HM.HM8.Ident, and com.cliffc.aa.HM.HM8.Con.
Referenced by com.cliffc.aa.HM.HM8.Ident.add_work(), com.cliffc.aa.HM.HM8.Ident.hm(), com.cliffc.aa.HM.HM8.Lambda.lookup(), com.cliffc.aa.HM.HM8.Let.lookup(), com.cliffc.aa.HM.HM8.Apply.lookup(), com.cliffc.aa.HM.HM8.Struct.lookup(), and com.cliffc.aa.HM.HM8.Field.lookup().
more_work()
abstract boolean com.cliffc.aa.HM.HM8.Syntax.more_work (Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM8.Field, com.cliffc.aa.HM.HM8.Struct, com.cliffc.aa.HM.HM8.Apply, com.cliffc.aa.HM.HM8.Let, com.cliffc.aa.HM.HM8.Lambda, com.cliffc.aa.HM.HM8.Ident, and com.cliffc.aa.HM.HM8.Con.
Referenced by com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM8.Lambda.more_work(), com.cliffc.aa.HM.HM8.Let.more_work(), com.cliffc.aa.HM.HM8.Apply.more_work(), and com.cliffc.aa.HM.HM8.Field.more_work().
more_work_impl()
final boolean com.cliffc.aa.HM.HM8.Syntax.more_work_impl (Worklist work) package
Definition at line 283 of file HM8.java.
{
       boolean no_more_work = work.has(this) || !hm(null); // Either on worklist, or no-progress
       return no_more_work;
     }
References com.cliffc.aa.HM.HM8.Worklist.has(), and com.cliffc.aa.HM.HM8.Syntax.hm().
Referenced by com.cliffc.aa.HM.HM8.Con.more_work(), com.cliffc.aa.HM.HM8.Ident.more_work(), com.cliffc.aa.HM.HM8.Lambda.more_work(), com.cliffc.aa.HM.HM8.Let.more_work(), com.cliffc.aa.HM.HM8.Apply.more_work(), com.cliffc.aa.HM.HM8.Struct.more_work(), and com.cliffc.aa.HM.HM8.Field.more_work().
p()
String com.cliffc.aa.HM.HM8.Syntax.p ()
Definition at line 291 of file HM8.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM8.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM8.Syntax.p0 (SB sb, VBitSet dups) package
Definition at line 292 of file HM8.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM8.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM8.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM8.Syntax.p1(), com.cliffc.aa.HM.HM8.Syntax.p2(), and com.cliffc.aa.HM.HM8.T2.str().
Referenced by com.cliffc.aa.HM.HM8.Syntax.p(), com.cliffc.aa.HM.HM8.Lambda.p2(), com.cliffc.aa.HM.HM8.Let.p2(), com.cliffc.aa.HM.HM8.Apply.p2(), com.cliffc.aa.HM.HM8.Struct.p2(), and com.cliffc.aa.HM.HM8.Field.p2().
p1()
abstract SB com.cliffc.aa.HM.HM8.Syntax.p1 (SB sb) abstract package
Reimplemented in com.cliffc.aa.HM.HM8.Field, com.cliffc.aa.HM.HM8.Struct, com.cliffc.aa.HM.HM8.Apply, com.cliffc.aa.HM.HM8.Let, com.cliffc.aa.HM.HM8.Lambda, com.cliffc.aa.HM.HM8.Ident, and com.cliffc.aa.HM.HM8.Con.
Referenced by com.cliffc.aa.HM.HM8.Syntax.p0().
p2()
abstract SB com.cliffc.aa.HM.HM8.Syntax.p2 (SB sb, VBitSet dups) abstract package
Reimplemented in com.cliffc.aa.HM.HM8.Field, com.cliffc.aa.HM.HM8.Struct, com.cliffc.aa.HM.HM8.Apply, com.cliffc.aa.HM.HM8.Let, com.cliffc.aa.HM.HM8.Lambda, com.cliffc.aa.HM.HM8.Ident, and com.cliffc.aa.HM.HM8.Con.
Referenced by com.cliffc.aa.HM.HM8.Syntax.p0().
post()
T2 com.cliffc.aa.HM.HM8.Syntax.post () package
Definition at line 254 of file HM8.java.
               {
       T2 t = _post.find();
       return t==_post ? t : (_post=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._post, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), and com.cliffc.aa.HM.HM8.Field.hm().
pre()
T2 com.cliffc.aa.HM.HM8.Syntax.pre () package
Definition at line 250 of file HM8.java.
              {
       T2 t = _pre.find();
       return t==_pre ? t : (_pre=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._pre, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), and com.cliffc.aa.HM.HM8.Field.hm().
prep_lookup_deps()
abstract void com.cliffc.aa.HM.HM8.Syntax.prep_lookup_deps (Ident id) abstract package
Reimplemented in com.cliffc.aa.HM.HM8.Field, com.cliffc.aa.HM.HM8.Struct, com.cliffc.aa.HM.HM8.Apply, com.cliffc.aa.HM.HM8.Let, com.cliffc.aa.HM.HM8.Lambda, com.cliffc.aa.HM.HM8.Ident, and com.cliffc.aa.HM.HM8.Con.
prep_tree()
abstract int com.cliffc.aa.HM.HM8.Syntax.prep_tree (Syntax par, VStack nongen, Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM8.Field, com.cliffc.aa.HM.HM8.Struct, com.cliffc.aa.HM.HM8.Apply, com.cliffc.aa.HM.HM8.Let, com.cliffc.aa.HM.HM8.Lambda, com.cliffc.aa.HM.HM8.Ident, and com.cliffc.aa.HM.HM8.Con.
Referenced by com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM8.Lambda.prep_tree(), com.cliffc.aa.HM.HM8.Let.prep_tree(), com.cliffc.aa.HM.HM8.Apply.prep_tree(), com.cliffc.aa.HM.HM8.Struct.prep_tree(), and com.cliffc.aa.HM.HM8.Field.prep_tree().
prep_tree_impl()
final void com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package
Definition at line 267 of file HM8.java.
{
       _par=par;
       _pre = T2.make_mem();
       _t=t;
       _post = T2.make_mem();
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM8.Syntax._nongen, com.cliffc.aa.HM.HM8.Syntax._par, com.cliffc.aa.HM.HM8.Syntax._post, com.cliffc.aa.HM.HM8.Syntax._pre, com.cliffc.aa.HM.HM8.Syntax._t, com.cliffc.aa.HM.HM8.T2.make_mem(), and com.cliffc.aa.HM.HM8.Worklist.push().
Referenced by com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), com.cliffc.aa.HM.HM8.Lambda.prep_tree(), com.cliffc.aa.HM.HM8.Let.prep_tree(), com.cliffc.aa.HM.HM8.Apply.prep_tree(), com.cliffc.aa.HM.HM8.Struct.prep_tree(), and com.cliffc.aa.HM.HM8.Field.prep_tree().
str()
abstract SB com.cliffc.aa.HM.HM8.Syntax.str (SB sb) abstract package
Reimplemented in com.cliffc.aa.HM.HM8.Field, com.cliffc.aa.HM.HM8.Struct, com.cliffc.aa.HM.HM8.Apply, com.cliffc.aa.HM.HM8.Let, com.cliffc.aa.HM.HM8.Lambda, com.cliffc.aa.HM.HM8.Ident, and com.cliffc.aa.HM.HM8.Con.
Referenced by com.cliffc.aa.HM.HM8.Lambda.str(), com.cliffc.aa.HM.HM8.Let.str(), com.cliffc.aa.HM.HM8.Apply.str(), com.cliffc.aa.HM.HM8.Struct.str(), com.cliffc.aa.HM.HM8.Field.str(), and com.cliffc.aa.HM.HM8.Syntax.toString().
toString()
final String com.cliffc.aa.HM.HM8.Syntax.toString ()
Definition at line 288 of file HM8.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM8.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_nongen
VStack com.cliffc.aa.HM.HM8.Syntax._nongen package
Definition at line 241 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Ident.hm(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM8.Syntax._par package
Definition at line 240 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._occurs_in(), com.cliffc.aa.HM.HM8.Con.add_work(), com.cliffc.aa.HM.HM8.Ident.add_work(), com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Apply.add_work(), com.cliffc.aa.HM.HM8.Struct.add_work(), com.cliffc.aa.HM.HM8.Field.add_work(), com.cliffc.aa.HM.HM8.Ident.hm(), com.cliffc.aa.HM.HM8.Lambda.lookup(), com.cliffc.aa.HM.HM8.Let.lookup(), com.cliffc.aa.HM.HM8.Apply.lookup(), com.cliffc.aa.HM.HM8.Struct.lookup(), com.cliffc.aa.HM.HM8.Field.lookup(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_post
T2 com.cliffc.aa.HM.HM8.Syntax._post package
Definition at line 244 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Syntax.post(), com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_pre
T2 com.cliffc.aa.HM.HM8.Syntax._pre package
Definition at line 242 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Syntax.pre(), com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM8.Syntax._t package
Definition at line 243 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Syntax.debug_find(), com.cliffc.aa.HM.HM8.Syntax.find(), com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM8.Syntax.p0(), com.cliffc.aa.HM.HM8.Let.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM8.java