aa: com.cliffc.aa.node.Work Class Reference
com.cliffc.aa.node.Work Class Reference abstract
Public Member Functions
Work (String name, boolean replacing)
abstract Node apply (Node n)
Node at (int i)
void clear ()
void del (int i)
void del (Node n)
boolean isEmpty ()
int len ()
boolean on (Node n)
Node pop ()
String toString ()
Public Attributes
final String _name
final boolean _replacing
final Ary< Node > _work = new Ary<>(new Node[1],0)
Package Functions
public< N extends Node > N add (N n)
Package Attributes
final VBitSet _on = new VBitSet()
Detailed Description
Definition at line 8 of file Work.java.
Constructor & Destructor Documentation
Work()
com.cliffc.aa.node.Work.Work (String name, boolean replacing)
Definition at line 13 of file Work.java.
 { _name=name; _replacing = replacing; }
References com.cliffc.aa.node.Work._name, and com.cliffc.aa.node.Work._replacing.
Member Function Documentation
add()
public<N extends Node> N com.cliffc.aa.node.Work.add (N n) package
Definition at line 15 of file Work.java.
{
     if( !_on.tset(n._uid) ) _work.push(n);
     return n;
   }
References com.cliffc.aa.node.Work._on, com.cliffc.aa.node.Work._work, and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.GVNGCM.add_work().
apply()
abstract Node com.cliffc.aa.node.Work.apply (Node n) abstract
Referenced by com.cliffc.aa.GVNGCM.iter().
at()
Node com.cliffc.aa.node.Work.at (int i)
Definition at line 27 of file Work.java.
 { return _work.at(i); }
References com.cliffc.aa.node.Work._work.
Referenced by com.cliffc.aa.node.Work.del(), and com.cliffc.aa.GVNGCM.iter().
clear()
void com.cliffc.aa.node.Work.clear ()
Definition at line 37 of file Work.java.
 { _work.clear(); _on.clear(); }
References com.cliffc.aa.node.Work._on, and com.cliffc.aa.node.Work._work.
Referenced by com.cliffc.aa.GVNGCM.reset_to_init0().
del() [1/2]
void com.cliffc.aa.node.Work.del (int i)
Definition at line 28 of file Work.java.
 { _on.clear(at(i)._uid); _work.del(i); }
References com.cliffc.aa.node.Work._on, com.cliffc.aa.node.Work._work, and com.cliffc.aa.node.Work.at().
Referenced by com.cliffc.aa.GVNGCM.check_not_monotonic(), and com.cliffc.aa.GVNGCM.iter().
del() [2/2]
void com.cliffc.aa.node.Work.del (Node n)
Definition at line 29 of file Work.java.
{
     if( !_on.get(n._uid) ) return;
     _on.clear(n._uid);
     _work.del(n);
   }
References com.cliffc.aa.node.Work._on, com.cliffc.aa.node.Node._uid, and com.cliffc.aa.node.Work._work.
isEmpty()
boolean com.cliffc.aa.node.Work.isEmpty ()
Definition at line 35 of file Work.java.
 { return _work._len==0; }
References com.cliffc.aa.node.Work._work.
Referenced by com.cliffc.aa.GVNGCM.gcp(), and com.cliffc.aa.GVNGCM.iter().
len()
int com.cliffc.aa.node.Work.len ()
Definition at line 14 of file Work.java.
 { return _work._len; }
References com.cliffc.aa.node.Work._work.
Referenced by com.cliffc.aa.GVNGCM.iter().
on()
boolean com.cliffc.aa.node.Work.on (Node n)
Definition at line 36 of file Work.java.
 { return _on.test(n._uid); }
References com.cliffc.aa.node.Work._on, com.cliffc.aa.node.Node._uid, and com.cliffc.aa.util.VBitSet.test().
Referenced by com.cliffc.aa.GVNGCM.on_dead(), com.cliffc.aa.GVNGCM.on_flow(), and com.cliffc.aa.GVNGCM.on_reduce().
pop()
Node com.cliffc.aa.node.Work.pop ()
Definition at line 21 of file Work.java.
                     {
     if( _work._len==0 ) return null;
     Node n = _work.pop();
     _on.clear(n._uid);
     return n;
   }
References com.cliffc.aa.node.Work._on, com.cliffc.aa.node.Node._uid, and com.cliffc.aa.node.Work._work.
Referenced by com.cliffc.aa.GVNGCM.gcp(), and com.cliffc.aa.GVNGCM.iter().
toString()
String com.cliffc.aa.node.Work.toString ()
Definition at line 38 of file Work.java.
 { return _name+_on.toString(); }
References com.cliffc.aa.node.Work._name, and com.cliffc.aa.node.Work._on.
Member Data Documentation
_name
final String com.cliffc.aa.node.Work._name
Definition at line 11 of file Work.java.
Referenced by com.cliffc.aa.node.Work.toString(), and com.cliffc.aa.node.Work.Work().
_on
final VBitSet com.cliffc.aa.node.Work._on = new VBitSet() package
Definition at line 10 of file Work.java.
Referenced by com.cliffc.aa.node.Work.add(), com.cliffc.aa.node.Work.clear(), com.cliffc.aa.node.Work.del(), com.cliffc.aa.node.Work.on(), com.cliffc.aa.node.Work.pop(), and com.cliffc.aa.node.Work.toString().
_replacing
final boolean com.cliffc.aa.node.Work._replacing
Definition at line 12 of file Work.java.
Referenced by com.cliffc.aa.node.Work.Work().
_work
final Ary<Node> com.cliffc.aa.node.Work._work = new Ary<>(new Node[1],0)
Definition at line 9 of file Work.java.
Referenced by com.cliffc.aa.node.Work.add(), com.cliffc.aa.node.Work.at(), com.cliffc.aa.node.Work.clear(), com.cliffc.aa.node.Work.del(), com.cliffc.aa.node.Work.isEmpty(), com.cliffc.aa.node.Work.len(), and com.cliffc.aa.node.Work.pop().
The documentation for this class was generated from the following file:
Work.java