aa: com.cliffc.aa.type.Type< T extends Type< T >.Key Class Reference
com.cliffc.aa.type.Type< T extends Type< T >.Key Class Reference
Public Member Functions
boolean equals (Object o)
int hashCode ()
Package Functions
Key (Type a, Type b)
Static Package Functions
static Type get (Type a, Type b)
static void intern_meet_quality_check ()
static void put (Type a, Type b, Type mt)
Package Attributes
Type _a
Type _b
Static Package Attributes
static NonBlockingHashMap< Key, Type > INTERN_MEET = new NonBlockingHashMap<>()
static Key K = new Key(null,null)
Detailed Description
Definition at line 370 of file Type.java.
Constructor & Destructor Documentation
Key()
com.cliffc.aa.type.Type< T extends Type< T >.Key.Key (Type a, Type b) package
Definition at line 373 of file Type.java.
 { _a=a; _b=b; }
References com.cliffc.aa.type.Type< T extends Type< T >.Key._a, and com.cliffc.aa.type.Type< T extends Type< T >.Key._b.
Referenced by com.cliffc.aa.type.Type< T extends Type< T >.Key.equals(), and com.cliffc.aa.type.Type< T extends Type< T >.Key.put().
Member Function Documentation
equals()
boolean com.cliffc.aa.type.Type< T extends Type< T >.Key.equals (Object o)
Definition at line 376 of file Type.java.
 { return _a==((Key)o)._a && _b==((Key)o)._b; }
References com.cliffc.aa.type.Type< T extends Type< T >.Key._a, com.cliffc.aa.type.Type< T extends Type< T >.Key._b, and com.cliffc.aa.type.Type< T extends Type< T >.Key.Key().
get()
static Type com.cliffc.aa.type.Type< T extends Type< T >.Key.get (Type a, Type b) static package
Definition at line 377 of file Type.java.
{
       K._a=a;
       K._b=b;
       return INTERN_MEET.get(K);
     }
References com.cliffc.aa.type.Type< T extends Type< T >.Key._a, com.cliffc.aa.type.Type< T extends Type< T >.Key._b, com.cliffc.aa.type.Type< T extends Type< T >.Key.INTERN_MEET, and com.cliffc.aa.type.Type< T extends Type< T >.Key.K.
hashCode()
int com.cliffc.aa.type.Type< T extends Type< T >.Key.hashCode ()
Definition at line 375 of file Type.java.
 { return ((_a._hash<<17)|(_a._hash>>>15))^_b._hash; }
References com.cliffc.aa.type.Type< T extends Type< T >.Key._a, com.cliffc.aa.type.Type< T extends Type< T >.Key._b, and com.cliffc.aa.type.Type< T extends Type< T >._hash.
intern_meet_quality_check()
static void com.cliffc.aa.type.Type< T extends Type< T >.Key.intern_meet_quality_check () static package
Definition at line 387 of file Type.java.
{
       NonBlockingHashMapLong<Integer> hashs = new NonBlockingHashMapLong<>();
       for( Key k : INTERN_MEET.keySet() ) {
         int hash = k.hashCode();
         Integer ii = hashs.get(hash);
         hashs.put(hash,ii==null ? 1 : ii+1);
       }
       int[] hist = new int[16];
       int maxval=0;
       long maxkey=-1;
       for( long l : hashs.keySet() ) {
         int reps = hashs.get(l);
         if( reps > maxval ) { maxval=reps; maxkey=l; }
         if( reps < hist.length ) hist[reps]++;
         else System.out.println("hash "+l+" repeats "+reps);
       }
       for( int i=0; i<hist.length; i++ )
         if( hist[i] > 0 )
           System.out.println("Number of hashes with "+i+" repeats: "+hist[i]);
       System.out.println("Max repeat key "+maxkey+" repeats: "+maxval);
     }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.get(), com.cliffc.aa.type.Type< T extends Type< T >.Key.INTERN_MEET, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.keySet(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.put().
put()
static void com.cliffc.aa.type.Type< T extends Type< T >.Key.put (Type a, Type b, Type mt) static package
Definition at line 382 of file Type.java.
{
       INTERN_MEET.put(new Key(a,b),mt);
       // Uncomment to check hash quality.
       //Util.hash_quality_check_per(INTERN_MEET);
     }
References com.cliffc.aa.type.Type< T extends Type< T >.Key.INTERN_MEET, and com.cliffc.aa.type.Type< T extends Type< T >.Key.Key().
Member Data Documentation
_a
Type com.cliffc.aa.type.Type< T extends Type< T >.Key._a package
Definition at line 374 of file Type.java.
Referenced by com.cliffc.aa.type.Type< T extends Type< T >.Key.equals(), com.cliffc.aa.type.Type< T extends Type< T >.Key.get(), com.cliffc.aa.type.Type< T extends Type< T >.Key.hashCode(), and com.cliffc.aa.type.Type< T extends Type< T >.Key.Key().
_b
Type com.cliffc.aa.type.Type< T extends Type< T >.Key._b package
Definition at line 374 of file Type.java.
Referenced by com.cliffc.aa.type.Type< T extends Type< T >.Key.equals(), com.cliffc.aa.type.Type< T extends Type< T >.Key.get(), com.cliffc.aa.type.Type< T extends Type< T >.Key.hashCode(), and com.cliffc.aa.type.Type< T extends Type< T >.Key.Key().
INTERN_MEET
NonBlockingHashMap<Key,Type> com.cliffc.aa.type.Type< T extends Type< T >.Key.INTERN_MEET = new NonBlockingHashMap<>() static package
Definition at line 372 of file Type.java.
Referenced by com.cliffc.aa.type.Type< T extends Type< T >.Key.get(), com.cliffc.aa.type.Type< T extends Type< T >.Key.intern_meet_quality_check(), and com.cliffc.aa.type.Type< T extends Type< T >.Key.put().
K
Key com.cliffc.aa.type.Type< T extends Type< T >.Key.K = new Key(null,null) static package
Definition at line 371 of file Type.java.
Referenced by com.cliffc.aa.type.Type< T extends Type< T >.Key.get().
The documentation for this class was generated from the following file:
Type.java