aa: com.cliffc.aa.type.Types.Key Class Reference
com.cliffc.aa.type.Types.Key Class Reference
Public Member Functions
boolean equals (Object o)
int hashCode ()
Package Attributes
int _hash
Type[] _ts
Private Member Functions
Key (Type[] ts, int hash)
Static Private Member Functions
static int hash (Type[] ts)
Detailed Description
Definition at line 22 of file Types.java.
Constructor & Destructor Documentation
Key()
com.cliffc.aa.type.Types.Key.Key (Type[] ts, int hash) private
Definition at line 25 of file Types.java.
 { _ts=ts; _hash = hash; }
References com.cliffc.aa.type.Types.Key._hash, com.cliffc.aa.type.Types.Key._ts, com.cliffc.aa.type.Types.Key.hash(), and com.cliffc.aa.type.Types.ts().
Referenced by com.cliffc.aa.type.Types.Key.equals().
Member Function Documentation
equals()
boolean com.cliffc.aa.type.Types.Key.equals (Object o)
Definition at line 32 of file Types.java.
{
       if( !(o instanceof Key) ) return false;
       Type[] ts = ((Key)o)._ts;
       // This series of tests is NOT the same as Arrays.equals(), since it
       // bottoms out in a pointer-equality test instead of 'equals'.
       if( _ts==ts ) return true;
       if( _ts.length != ts.length ) return false;
       for( int i=0; i<ts.length; i++ )
         if( _ts[i]!=ts[i] )
           return false;
       return true;
     }
References com.cliffc.aa.type.Types.Key._ts, com.cliffc.aa.type.Types.Key.Key(), and com.cliffc.aa.type.Types.ts().
hash()
static int com.cliffc.aa.type.Types.Key.hash (Type[] ts) static private
Definition at line 26 of file Types.java.
{
       int hash = 0;
       for( Type t : ts ) hash += t._hash;
       return hash;
     }
References com.cliffc.aa.type.Types.ts().
Referenced by com.cliffc.aa.type.Types.check_(), com.cliffc.aa.type.Types.hash_cons_(), and com.cliffc.aa.type.Types.Key.Key().
hashCode()
int com.cliffc.aa.type.Types.Key.hashCode ()
Definition at line 31 of file Types.java.
 { return _hash; }
References com.cliffc.aa.type.Types.Key._hash.
Member Data Documentation
_hash
int com.cliffc.aa.type.Types.Key._hash package
Definition at line 24 of file Types.java.
Referenced by com.cliffc.aa.type.Types.check_(), com.cliffc.aa.type.Types.hash_cons_(), com.cliffc.aa.type.Types.Key.hashCode(), and com.cliffc.aa.type.Types.Key.Key().
_ts
Type [] com.cliffc.aa.type.Types.Key._ts package
Definition at line 23 of file Types.java.
Referenced by com.cliffc.aa.type.Types.check_(), com.cliffc.aa.type.Types.Key.equals(), com.cliffc.aa.type.Types.hash_cons_(), and com.cliffc.aa.type.Types.Key.Key().
The documentation for this class was generated from the following file:
Types.java