aa: com.cliffc.aa.HM.HM9.Ident Class Reference
com.cliffc.aa.HM.HM9.Ident Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Ident (String name)
void add_hm_work (Worklist work)
void add_val_work (Syntax child, Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
T2 idt ()
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
Type val (Worklist work)
Package Attributes
Syntax _def
Type _flow
T2 _hmt
T2 _idt
int _idx
final String _name
VStack _nongen
Syntax _par
Private Member Functions
int _init (Syntax def, T2 idt)
Detailed Description
Definition at line 405 of file HM9.java.
Constructor & Destructor Documentation
Ident()
com.cliffc.aa.HM.HM9.Ident.Ident (String name) package
Definition at line 410 of file HM9.java.
 { _name=name; }
References com.cliffc.aa.HM.HM9.Ident._name.
Member Function Documentation
_init()
int com.cliffc.aa.HM.HM9.Ident._init (Syntax def, T2 idt) private
Definition at line 451 of file HM9.java.
 { _def = def; _idt = idt; return 1; }
References com.cliffc.aa.HM.HM9.Ident._def, com.cliffc.aa.HM.HM9.Ident._idt, and com.cliffc.aa.HM.HM9.Ident.idt().
Referenced by com.cliffc.aa.HM.HM9.Ident.prep_tree().
add_hm_work()
void com.cliffc.aa.HM.HM9.Ident.add_hm_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 421 of file HM9.java.
{
       work.push(_par);
       T2 t = idt();
       if( t.nongen_in(_par == null ? null : _par._nongen) ) // Got captured in some parent?
         t.add_deps_work(work);                              // Need to revisit dependent ids
       if( _par instanceof Apply && ((Apply)_par)._fun instanceof NotNil )
         work.push(((Apply)_par)._fun);
     }
References com.cliffc.aa.HM.HM9.Syntax._nongen, com.cliffc.aa.HM.HM9.Syntax._par, com.cliffc.aa.HM.HM9.T2.add_deps_work(), com.cliffc.aa.HM.HM9.Ident.idt(), com.cliffc.aa.HM.HM9.T2.nongen_in(), and com.cliffc.aa.HM.HM9.Worklist.push().
add_val_work()
void com.cliffc.aa.HM.HM9.Syntax.add_val_work (Syntax child, Worklist work) package inherited
Reimplemented in com.cliffc.aa.HM.HM9.PrimSyn, com.cliffc.aa.HM.HM9.Apply, com.cliffc.aa.HM.HM9.Let, and com.cliffc.aa.HM.HM9.Lambda.
Definition at line 346 of file HM9.java.
 {} // Add affected neighbors to worklist
Referenced by com.cliffc.aa.HM.HM9.hm().
debug_find()
T2 com.cliffc.aa.HM.HM9.Syntax.debug_find () package inherited
Definition at line 329 of file HM9.java.
 { return _hmt.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM9.Syntax._hmt, and com.cliffc.aa.HM.HM9.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM9.hm().
find()
T2 com.cliffc.aa.HM.HM9.Syntax.find () package inherited
Definition at line 325 of file HM9.java.
               {                 // U-F find
       T2 t = _hmt.find();
       return t== _hmt ? t : (_hmt =t);
     }
References com.cliffc.aa.HM.HM9.Syntax._hmt, and com.cliffc.aa.HM.HM9.T2.find().
Referenced by com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_val_work(), com.cliffc.aa.HM.HM9.Let.add_val_work(), com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Ident.hm(), com.cliffc.aa.HM.HM9.Lambda.hm(), com.cliffc.aa.HM.HM9.Apply.hm(), com.cliffc.aa.HM.HM9.Root.hm(), com.cliffc.aa.HM.HM9.Struct.hm(), com.cliffc.aa.HM.HM9.Field.hm(), com.cliffc.aa.HM.HM9.PrimSyn.hm(), com.cliffc.aa.HM.HM9.If.hm(), com.cliffc.aa.HM.HM9.NotNil.hm(), com.cliffc.aa.HM.HM9.Apply.is_if_nil(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.NotNil.prep_tree(), com.cliffc.aa.HM.HM9.Apply.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
hm()
boolean com.cliffc.aa.HM.HM9.Ident.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 418 of file HM9.java.
{
       return idt().fresh_unify(find(),_nongen,work);
     }
References com.cliffc.aa.HM.HM9.Syntax._nongen, com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.HM.HM9.T2.fresh_unify(), and com.cliffc.aa.HM.HM9.Ident.idt().
idt()
T2 com.cliffc.aa.HM.HM9.Ident.idt () package
Definition at line 414 of file HM9.java.
              {
       T2 idt = _idt.find();
       return idt==_idt ? idt : (_idt=idt);
     }
References com.cliffc.aa.HM.HM9.Ident._idt, and com.cliffc.aa.HM.HM9.T2.find().
Referenced by com.cliffc.aa.HM.HM9.Ident._init(), com.cliffc.aa.HM.HM9.Ident.add_hm_work(), and com.cliffc.aa.HM.HM9.Ident.hm().
more_work()
boolean com.cliffc.aa.HM.HM9.Ident.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 452 of file HM9.java.
 { return more_work_impl(work); }
References com.cliffc.aa.HM.HM9.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM9.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 362 of file HM9.java.
{
       if( work.has(this) ) return true;
       if( DO_HM && hm(null) )   // Any more HM work?
         return false;           // Found HM work not on worklist
       if( DO_GCP && val(null)!=_flow )
         return false;           // Found GCP work not on worklist
       return true;
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.DO_GCP, com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.Worklist.has(), com.cliffc.aa.HM.HM9.Syntax.hm(), and com.cliffc.aa.HM.HM9.Syntax.val().
Referenced by com.cliffc.aa.HM.HM9.Con.more_work(), com.cliffc.aa.HM.HM9.Ident.more_work(), com.cliffc.aa.HM.HM9.Lambda.more_work(), com.cliffc.aa.HM.HM9.Let.more_work(), com.cliffc.aa.HM.HM9.Apply.more_work(), com.cliffc.aa.HM.HM9.Struct.more_work(), com.cliffc.aa.HM.HM9.Field.more_work(), and com.cliffc.aa.HM.HM9.PrimSyn.more_work().
p()
String com.cliffc.aa.HM.HM9.Syntax.p () inherited
Definition at line 374 of file HM9.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM9.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM9.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 375 of file HM9.java.
{
       _hmt.get_dups(dups);
       VBitSet visit = new VBitSet();
       p1(sb.i());
       if( DO_HM  ) _hmt .str(sb.p(", HM="), visit,dups);
       if( DO_GCP ) _flow.str(sb.p(", CCP="),visit.clr(),null,false);
       sb.nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.util.VBitSet.clr(), com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM9.DO_GCP, com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM9.Syntax.p1(), com.cliffc.aa.HM.HM9.Syntax.p2(), com.cliffc.aa.type.Type< T extends Type< T >.str(), and com.cliffc.aa.HM.HM9.T2.str().
Referenced by com.cliffc.aa.HM.HM9.Syntax.p(), com.cliffc.aa.HM.HM9.Lambda.p2(), com.cliffc.aa.HM.HM9.Let.p2(), com.cliffc.aa.HM.HM9.Apply.p2(), com.cliffc.aa.HM.HM9.Struct.p2(), and com.cliffc.aa.HM.HM9.Field.p2().
p1()
SB com.cliffc.aa.HM.HM9.Ident.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 412 of file HM9.java.
 { return sb.p(_name); }
References com.cliffc.aa.HM.HM9.Ident._name, and com.cliffc.aa.util.SB.p().
Referenced by com.cliffc.aa.HM.HM9.Ident.str().
p2()
SB com.cliffc.aa.HM.HM9.Ident.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 413 of file HM9.java.
 { return sb; }
prep_lookup_deps()
void com.cliffc.aa.HM.HM9.Syntax.prep_lookup_deps (Ident id) package inherited
Reimplemented in com.cliffc.aa.HM.HM9.Let, and com.cliffc.aa.HM.HM9.Lambda.
Definition at line 358 of file HM9.java.
 {}
prep_tree()
int com.cliffc.aa.HM.HM9.Ident.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 432 of file HM9.java.
{
       prep_tree_impl(par,nongen,work,T2.make_leaf());
       for( Syntax syn = _par; syn!=null; syn = syn._par )
         syn.prep_lookup_deps(this);
       // Lookup, and get the T2 type var and a pointer to the flow type.
       for( Syntax syn = _par; syn!=null; syn = syn._par ) {
         if( syn instanceof Lambda ) {
           Lambda lam = (Lambda)syn;
           if( (_idx = Util.find(lam._args,_name)) != -1 )
             return _init(lam,lam.targ(_idx));
         } else if( syn instanceof Let ) {
           Let let = (Let)syn;  _idx=-1;
           if( Util.eq(let._arg0,_name) )
             return _init(let,let._targ);
         }
       }
       throw new RuntimeException("Parse error, "+_name+" is undefined");
     }
References com.cliffc.aa.HM.HM9.Let._arg0, com.cliffc.aa.HM.HM9.Lambda._args, com.cliffc.aa.HM.HM9.Ident._idx, com.cliffc.aa.HM.HM9.Ident._init(), com.cliffc.aa.HM.HM9.Ident._name, com.cliffc.aa.HM.HM9.Syntax._par, com.cliffc.aa.HM.HM9.Let._targ, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM9.T2.make_leaf(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM9.Lambda.targ().
prep_tree_impl()
final void com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 351 of file HM9.java.
{
       _par = par;
       _hmt = t;
       _flow= Type.XSCALAR;
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.HM.HM9.Syntax._nongen, com.cliffc.aa.HM.HM9.Syntax._par, com.cliffc.aa.HM.HM9.Worklist.push(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Referenced by com.cliffc.aa.HM.HM9.Con.prep_tree(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), com.cliffc.aa.HM.HM9.Lambda.prep_tree(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Apply.prep_tree(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.Field.prep_tree(), and com.cliffc.aa.HM.HM9.PrimSyn.prep_tree().
str()
SB com.cliffc.aa.HM.HM9.Ident.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 411 of file HM9.java.
 { return p1(sb); }
References com.cliffc.aa.HM.HM9.Ident.p1().
toString()
final String com.cliffc.aa.HM.HM9.Syntax.toString () inherited
Definition at line 371 of file HM9.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM9.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.HM.HM9.Lambda.p1().
val()
Type com.cliffc.aa.HM.HM9.Ident.val (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 429 of file HM9.java.
{
       return _def instanceof Let ? ((Let)_def)._def._flow : ((Lambda)_def)._types[_idx];
     }
References com.cliffc.aa.HM.HM9.Ident._def, com.cliffc.aa.HM.HM9.Let._def, com.cliffc.aa.HM.HM9.Syntax._flow, and com.cliffc.aa.HM.HM9.Ident._idx.
Member Data Documentation
_def
Syntax com.cliffc.aa.HM.HM9.Ident._def package
Definition at line 407 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident._init(), and com.cliffc.aa.HM.HM9.Ident.val().
_flow
Type com.cliffc.aa.HM.HM9.Syntax._flow package inherited
Definition at line 332 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Lambda.apply(), com.cliffc.aa.HM.HM9.Pair1.apply(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Pair.apply(), com.cliffc.aa.HM.HM9.Triple.apply(), com.cliffc.aa.HM.HM9.If.apply(), com.cliffc.aa.HM.HM9.EQ.apply(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM9.IsEmpty.apply(), com.cliffc.aa.HM.HM9.NotNil.apply(), com.cliffc.aa.HM.HM9.Mul.apply(), com.cliffc.aa.HM.HM9.Dec.apply(), com.cliffc.aa.HM.HM9.Str.apply(), com.cliffc.aa.HM.HM9.Factor.apply(), com.cliffc.aa.HM.HM9.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Lambda.Lambda(), com.cliffc.aa.HM.HM9.Syntax.more_work_impl(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM9.Ident.val(), com.cliffc.aa.HM.HM9.Let.val(), com.cliffc.aa.HM.HM9.Apply.val(), com.cliffc.aa.HM.HM9.Root.val(), com.cliffc.aa.HM.HM9.Struct.val(), com.cliffc.aa.HM.HM9.Field.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
_hmt
T2 com.cliffc.aa.HM.HM9.Syntax._hmt package inherited
Definition at line 324 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Syntax.debug_find(), com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.PrimSyn.prep_tree(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM9.PrimSyn.PrimSyn().
_idt
T2 com.cliffc.aa.HM.HM9.Ident._idt package
Definition at line 409 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident._init(), and com.cliffc.aa.HM.HM9.Ident.idt().
_idx
int com.cliffc.aa.HM.HM9.Ident._idx package
Definition at line 408 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.prep_tree(), and com.cliffc.aa.HM.HM9.Ident.val().
_name
final String com.cliffc.aa.HM.HM9.Ident._name package
Definition at line 406 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.Ident(), com.cliffc.aa.HM.HM9.Ident.p1(), and com.cliffc.aa.HM.HM9.Ident.prep_tree().
_nongen
VStack com.cliffc.aa.HM.HM9.Syntax._nongen package inherited
Definition at line 323 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.add_hm_work(), com.cliffc.aa.HM.HM9.Ident.hm(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM9.Syntax._par package inherited
Definition at line 322 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.Apply.add_hm_work(), com.cliffc.aa.HM.HM9.Struct.add_hm_work(), com.cliffc.aa.HM.HM9.Field.add_hm_work(), com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM9.java