aa: com.cliffc.aa.HM.HM6.T2 Class Reference
com.cliffc.aa.HM.HM6.T2 Class Reference
Public Member Functions
String p ()
String toString ()
Package Functions
boolean _cycle_equals (T2 t)
VBitSet _get_dups (VBitSet visit, VBitSet dups)
boolean _nongen_in (VStack nongen)
boolean _occurs_in (Syntax syn)
boolean _occurs_in_type (T2 x)
void add_deps_work (Worklist work)
T2 args (int i)
T2 copy ()
boolean cycle_equals (T2 t)
T2 find ()
boolean fresh_unify (T2 that, VStack nongen, Worklist work)
VBitSet get_dups (VBitSet dups)
boolean is_base ()
boolean is_fun ()
boolean is_leaf ()
boolean isa (String name)
boolean no_uf ()
boolean nongen_in (VStack syn)
boolean occurs_in (Syntax syn)
boolean occurs_in_type (T2 x)
String p (VBitSet dups)
boolean push_update (Ident a)
SB str (SB sb, VBitSet visit, VBitSet dups)
boolean unify (T2 that, Worklist work)
boolean union (T2 that, Worklist work)
Static Package Functions
static T2 make_base (Type con)
static T2 make_fun (T2... args)
static T2 make_leaf ()
static T2 prim (String name, T2... args)
static void reset ()
Package Attributes
T2[] _args
Type _con
Ary< Ident > _deps
final String _name
final int _uid
Static Package Attributes
static final VBitSet UPDATE_VISIT = new VBitSet()
Private Member Functions
T2 (@NotNull String name, Type con, T2 @NotNull ... args)
T2 _fresh (VStack nongen)
boolean _fresh_unify (T2 that, VStack nongen, Worklist work)
SB _p (SB sb, VBitSet visit, VBitSet dups)
boolean _unify (T2 that, Worklist work)
void add_deps_work_impl (Worklist work)
long dbl_uid (T2 t)
boolean fresh_base (T2 that, Worklist work)
void push_update_impl (Ident a)
boolean unify_base (T2 that, Worklist work)
boolean vput (T2 that, boolean progress)
Static Private Member Functions
static SB str (SB sb, VBitSet visit, T2 t, VBitSet dups)
Static Private Attributes
static final HashMap< T2, T2 > CDUPS = new HashMap<>()
static int CNT =0
static final HashMap< Long, T2 > DUPS = new HashMap<>()
static final VBitSet ODUPS = new VBitSet()
static final HashMap< T2, T2 > VARS = new HashMap<>()
Detailed Description
Definition at line 503 of file HM6.java.
Constructor & Destructor Documentation
T2()
com.cliffc.aa.HM.HM6.T2.T2 (@NotNull String name, Type con, T2 @NotNull ... args) private
Definition at line 528 of file HM6.java.
{
       _uid = CNT++;
       _name= name;
       _con = con;
       _args= args;
     }
References com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.T2._con, com.cliffc.aa.HM.HM6.T2._name, com.cliffc.aa.HM.HM6.T2._uid, com.cliffc.aa.HM.HM6.T2.args(), and com.cliffc.aa.HM.HM6.T2.CNT.
Referenced by com.cliffc.aa.HM.HM6.T2.copy(), com.cliffc.aa.HM.HM6.T2.make_base(), com.cliffc.aa.HM.HM6.T2.make_fun(), com.cliffc.aa.HM.HM6.T2.make_leaf(), and com.cliffc.aa.HM.HM6.T2.prim().
Member Function Documentation
_cycle_equals()
boolean com.cliffc.aa.HM.HM6.T2._cycle_equals (T2 t) package
Definition at line 770 of file HM6.java.
{
       assert no_uf() && t.no_uf();
       if( this==t ) return true;
       if( is_base() && t.is_base() )
         return _con==t._con;    // Base-cases have to be completely identical
       if( !Util.eq(_name,t._name) ||       // Wrong type-var names
           _args.length != t._args.length ) // Mismatched sizes
         return false;
       if( _args==t._args ) return true;
       // Cycles stall the equal/unequal decision until we see a difference.
       T2 tc = CDUPS.get(this);
       if( tc!=null )
         return tc==t; // Cycle check; true if both cycling the same
       CDUPS.put(this,t);
       for( int i=0; i<_args.length; i++ )
         if( !args(i)._cycle_equals(t.args(i)) )
           return false;
       return true;
     }
References com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.T2._con, com.cliffc.aa.HM.HM6.T2._name, com.cliffc.aa.HM.HM6.T2.args(), com.cliffc.aa.HM.HM6.T2.CDUPS, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM6.T2.is_base(), and com.cliffc.aa.HM.HM6.T2.no_uf().
Referenced by com.cliffc.aa.HM.HM6.T2.cycle_equals().
_fresh()
T2 com.cliffc.aa.HM.HM6.T2._fresh (VStack nongen) private
Definition at line 697 of file HM6.java.
{
       assert no_uf();
       T2 rez = VARS.get(this);
       if( rez!=null ) return rez; // Been there, done that
       if( is_leaf() ) {
         // If occurs_in lexical scope, keep same variable, else make a new leaf
         T2 t = nongen_in(nongen) ? this : T2.make_leaf();
         VARS.put(this,t);
         return t;
       } else {                  // Structure is deep-replicated
         T2 t = copy();
         VARS.put(this,t);       // Stop cyclic structure looping
         for( int i=0; i<_args.length; i++ )
           t._args[i] = args(i)._fresh(nongen);
         return t;
       }
     }
References com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.T2._fresh(), com.cliffc.aa.HM.HM6.T2.args(), com.cliffc.aa.HM.HM6.T2.copy(), com.cliffc.aa.HM.HM6.T2.is_leaf(), com.cliffc.aa.HM.HM6.T2.make_leaf(), com.cliffc.aa.HM.HM6.T2.no_uf(), com.cliffc.aa.HM.HM6.T2.nongen_in(), and com.cliffc.aa.HM.HM6.T2.VARS.
Referenced by com.cliffc.aa.HM.HM6.T2._fresh(), and com.cliffc.aa.HM.HM6.T2._fresh_unify().
_fresh_unify()
boolean com.cliffc.aa.HM.HM6.T2._fresh_unify (T2 that, VStack nongen, Worklist work) private
Definition at line 663 of file HM6.java.
{
       assert no_uf() && that.no_uf();
       T2 prior = VARS.get(this);
       if( prior!=null )         // Been there, done that
         return prior.find()._unify(that,work);  // Also 'prior' needs unification with 'that'
       if( cycle_equals(that) ) return vput(that,false);
       // Attempting to pre-compute occurs_in, by computing 'is_fresh' in the
       // Ident.hm() call does NOT work.  The 'is_fresh' is for the top-layer
       // only, not the internal layers.  As soon as we structural recurse down
       // a layer, 'is_fresh' does not correlate with an occurs_in check.
       if( nongen_in(nongen) ) return vput(that,_unify(that,work)); // Famous 'occurs-check', switch to normal unify
       if( this.is_leaf() ) return vput(that,false); // Lazy map LHS tvar to RHS
       if( that.is_leaf() )             // RHS is a tvar; union with a deep copy of LHS
         return work==null || vput(that,that.union(_fresh(nongen),work));
       // Bases MEET cons in RHS
       if( is_base() && that.is_base() ) return vput(that,fresh_base(that,work));
       if( !Util.eq(_name,that._name) ||
           _args.length != that._args.length )
         throw new RuntimeException("Cannot unify "+this+" and "+that);
       // Structural recursion unification, lazy on LHS
       boolean progress = vput(that,false); // Early set, to stop cycles
       for( int i=0; i<_args.length; i++ ) {
         progress |= args(i)._fresh_unify(that.args(i),nongen,work);
         if( progress && work==null ) return true;
       }
       return progress;
     }
References com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.T2._fresh(), com.cliffc.aa.HM.HM6.T2._fresh_unify(), com.cliffc.aa.HM.HM6.T2._name, com.cliffc.aa.HM.HM6.T2._unify(), com.cliffc.aa.HM.HM6.T2.args(), com.cliffc.aa.HM.HM6.T2.cycle_equals(), com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM6.T2.find(), com.cliffc.aa.HM.HM6.T2.fresh_base(), com.cliffc.aa.HM.HM6.T2.is_base(), com.cliffc.aa.HM.HM6.T2.is_leaf(), com.cliffc.aa.HM.HM6.T2.no_uf(), com.cliffc.aa.HM.HM6.T2.nongen_in(), com.cliffc.aa.HM.HM6.T2.union(), com.cliffc.aa.HM.HM6.T2.VARS, and com.cliffc.aa.HM.HM6.T2.vput().
Referenced by com.cliffc.aa.HM.HM6.T2._fresh_unify(), and com.cliffc.aa.HM.HM6.T2.fresh_unify().
_get_dups()
VBitSet com.cliffc.aa.HM.HM6.T2._get_dups (VBitSet visit, VBitSet dups) package
Definition at line 824 of file HM6.java.
{
       if( visit.tset(_uid) && no_uf() ) dups.set(_uid);
       else
         for( T2 t : _args )
           if( t!=null )
             t._get_dups(visit,dups);
       return dups;
     }
References com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.T2._uid, com.cliffc.aa.HM.HM6.T2.no_uf(), and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.HM.HM6.T2.get_dups().
_nongen_in()
boolean com.cliffc.aa.HM.HM6.T2._nongen_in (VStack nongen) package
Definition at line 755 of file HM6.java.
{
       for( T2 t2 : nongen )
         if( _occurs_in_type(t2.find()) )
           return true;
       return false;
     }
References com.cliffc.aa.HM.HM6.T2._occurs_in_type().
Referenced by com.cliffc.aa.HM.HM6.T2.nongen_in().
_occurs_in()
boolean com.cliffc.aa.HM.HM6.T2._occurs_in (Syntax syn) package
Definition at line 730 of file HM6.java.
{
       for( ; syn!=null; syn=syn._par )
         if( _occurs_in_type(syn.find()) )
           return true;
       return false;
     }
References com.cliffc.aa.HM.HM6.T2._occurs_in_type(), com.cliffc.aa.HM.HM6.Syntax._par, and com.cliffc.aa.HM.HM6.Syntax.find().
Referenced by com.cliffc.aa.HM.HM6.T2.occurs_in().
_occurs_in_type()
boolean com.cliffc.aa.HM.HM6.T2._occurs_in_type (T2 x) package
Definition at line 737 of file HM6.java.
{
       assert no_uf() && x.no_uf();
       if( x==this ) return true;
       if( ODUPS.tset(x._uid) ) return false; // Been there, done that
       if( !x.is_leaf() )
         for( int i=0; i<x._args.length; i++ )
           if( _occurs_in_type(x.args(i)) )
             return true;
       return false;
     }
References com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.T2._uid, com.cliffc.aa.HM.HM6.T2.args(), com.cliffc.aa.HM.HM6.T2.is_leaf(), com.cliffc.aa.HM.HM6.T2.no_uf(), com.cliffc.aa.HM.HM6.T2.ODUPS, and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.HM.HM6.T2._nongen_in(), com.cliffc.aa.HM.HM6.T2._occurs_in(), and com.cliffc.aa.HM.HM6.T2.occurs_in_type().
_p()
SB com.cliffc.aa.HM.HM6.T2._p (SB sb, VBitSet visit, VBitSet dups) private
Definition at line 862 of file HM6.java.
{
       assert no_uf();
       if( is_base() ) return sb.p(_con instanceof TypeMemPtr ? "str" : _con.toString() );
       if( is_leaf() ) return sb.p(_name);
       boolean dup = dups.get(_uid);
       if( dup ) sb.p('$').p(_uid);
       if( visit.tset(_uid) && dup ) return sb;
       if( dup ) sb.p(':');
       if( is_fun() ) {
         sb.p("{ ");
         for( int i=0; i<_args.length-1; i++ )
           args(i)._p(sb,visit,dups).p(" ");
         return args(_args.length-1)._p(sb.p("-> "),visit,dups).p(" }");
       }
       // Generic structural T2
       sb.p("(").p(_name).p(" ");
       for( int i=0; i<_args.length; i++ ) args(i)._p(sb,visit,dups).p(" ");
       return sb.unchar().p(")");
     }
References com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.T2._con, com.cliffc.aa.HM.HM6.T2._name, com.cliffc.aa.HM.HM6.T2._p(), com.cliffc.aa.HM.HM6.T2._uid, com.cliffc.aa.HM.HM6.T2.args(), com.cliffc.aa.HM.HM6.T2.is_base(), com.cliffc.aa.HM.HM6.T2.is_fun(), com.cliffc.aa.HM.HM6.T2.is_leaf(), com.cliffc.aa.HM.HM6.T2.no_uf(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.Type< T extends Type< T >.toString(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.util.SB.unchar().
Referenced by com.cliffc.aa.HM.HM6.T2._p(), and com.cliffc.aa.HM.HM6.T2.p().
_unify()
boolean com.cliffc.aa.HM.HM6.T2._unify (T2 that, Worklist work) private
Definition at line 597 of file HM6.java.
{
       assert no_uf() && that.no_uf();
       if( this==that ) return false;
       // two leafs union in either order, so keep lower uid
       if( is_leaf() && that.is_leaf() && _uid<that._uid ) return that.union(this,work);
       if(      is_leaf() ) return      union(that,work);
       if( that.is_leaf() ) return that.union(this,work);
       if( is_base() && that.is_base() ) return unify_base(that,work);
       if( !Util.eq(_name,that._name) )
         throw new RuntimeException("Cannot unify "+this+" and "+that);
       assert _args!=that._args; // Not expecting to share _args and not 'this'
       if( _args.length != that._args.length )
         throw new RuntimeException("Cannot unify "+this+" and "+that);
       // Cycle check
       long luid = dbl_uid(that);
       T2 rez = DUPS.get(luid);
       assert rez==null || rez==that;
       if( rez!=null ) return false; // Been there, done that
       DUPS.put(luid,that);          // Close cycles
       // Structural recursion unification.
       boolean progress=false;
       for( int i=0; i<_args.length; i++ ) {
         progress |= args(i)._unify(that.args(i),work);
         if( progress && work!=null ) return true;
       }
       return progress;
     }
References com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.T2._name, com.cliffc.aa.HM.HM6.T2._uid, com.cliffc.aa.HM.HM6.T2._unify(), com.cliffc.aa.HM.HM6.T2.args(), com.cliffc.aa.HM.HM6.T2.dbl_uid(), com.cliffc.aa.HM.HM6.T2.DUPS, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM6.T2.is_base(), com.cliffc.aa.HM.HM6.T2.is_leaf(), com.cliffc.aa.HM.HM6.T2.no_uf(), com.cliffc.aa.HM.HM6.T2.unify_base(), and com.cliffc.aa.HM.HM6.T2.union().
Referenced by com.cliffc.aa.HM.HM6.T2._fresh_unify(), com.cliffc.aa.HM.HM6.T2._unify(), and com.cliffc.aa.HM.HM6.T2.unify().
add_deps_work()
void com.cliffc.aa.HM.HM6.T2.add_deps_work (Worklist work) package
Definition at line 808 of file HM6.java.
 { assert UPDATE_VISIT.isEmpty(); add_deps_work_impl(work); UPDATE_VISIT.clear(); }
References com.cliffc.aa.HM.HM6.T2.add_deps_work_impl(), and com.cliffc.aa.HM.HM6.T2.UPDATE_VISIT.
Referenced by com.cliffc.aa.HM.HM6.Ident.add_occurs().
add_deps_work_impl()
void com.cliffc.aa.HM.HM6.T2.add_deps_work_impl (Worklist work) private
Definition at line 809 of file HM6.java.
{
       if( is_leaf() || _args.length==0 ) {
         work.addAll(_deps);
       } else {
         if( UPDATE_VISIT.tset(_uid) ) return;
         for( int i=0; i<_args.length; i++ )
           args(i).add_deps_work_impl(work);
       }
     }
References com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.T2._deps, com.cliffc.aa.HM.HM6.T2._uid, com.cliffc.aa.HM.HM6.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM6.Worklist.addAll(), com.cliffc.aa.HM.HM6.T2.args(), com.cliffc.aa.HM.HM6.T2.is_leaf(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.HM.HM6.T2.UPDATE_VISIT.
Referenced by com.cliffc.aa.HM.HM6.T2.add_deps_work(), and com.cliffc.aa.HM.HM6.T2.add_deps_work_impl().
args()
T2 com.cliffc.aa.HM.HM6.T2.args (int i) package
Definition at line 555 of file HM6.java.
                    {
       T2 u = _args[i];
       T2 uu = u.find();
       return u==uu ? uu : (_args[i]=uu);
     }
References com.cliffc.aa.HM.HM6.T2._args, and com.cliffc.aa.HM.HM6.T2.find().
Referenced by com.cliffc.aa.HM.HM6.T2._cycle_equals(), com.cliffc.aa.HM.HM6.T2._fresh(), com.cliffc.aa.HM.HM6.T2._fresh_unify(), com.cliffc.aa.HM.HM6.T2._occurs_in_type(), com.cliffc.aa.HM.HM6.T2._p(), com.cliffc.aa.HM.HM6.T2._unify(), com.cliffc.aa.HM.HM6.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM6.Lambda.hm(), com.cliffc.aa.HM.HM6.Lambda2.hm(), com.cliffc.aa.HM.HM6.Apply.hm(), com.cliffc.aa.HM.HM6.T2.make_fun(), com.cliffc.aa.HM.HM6.T2.prim(), com.cliffc.aa.HM.HM6.T2.push_update_impl(), and com.cliffc.aa.HM.HM6.T2.T2().
copy()
T2 com.cliffc.aa.HM.HM6.T2.copy () package
Definition at line 526 of file HM6.java.
 { return new T2(_name,_con,new T2[_args.length]); }
References com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.T2._con, com.cliffc.aa.HM.HM6.T2._name, and com.cliffc.aa.HM.HM6.T2.T2().
Referenced by com.cliffc.aa.HM.HM6.T2._fresh().
cycle_equals()
boolean com.cliffc.aa.HM.HM6.T2.cycle_equals (T2 t) package
Definition at line 764 of file HM6.java.
{
       assert CDUPS.isEmpty();
       boolean rez = _cycle_equals(t);
       CDUPS.clear();
       return rez;
     }
References com.cliffc.aa.HM.HM6.T2._cycle_equals(), and com.cliffc.aa.HM.HM6.T2.CDUPS.
Referenced by com.cliffc.aa.HM.HM6.T2._fresh_unify().
dbl_uid()
long com.cliffc.aa.HM.HM6.T2.dbl_uid (T2 t) private
Definition at line 629 of file HM6.java.
 { return ((long)_uid<<32)|t._uid; }
References com.cliffc.aa.HM.HM6.T2._uid.
Referenced by com.cliffc.aa.HM.HM6.T2._unify().
find()
T2 com.cliffc.aa.HM.HM6.T2.find () package
Definition at line 543 of file HM6.java.
               {
       if( !is_leaf() ) return this; // Shortcut
       T2 u = _args[0];
       if( u==null ) return this; // Shortcut
       if( u.no_uf() ) return u;  // Shortcut
       // U-F fixup
       while( u.is_leaf() && u._args[0]!=null ) u = u._args[0];
       T2 v = this, v2;
       while( !v.is_leaf() && (v2=v._args[0])!=u ) { v._args[0]=u; v = v2; }
       return u;
     }
References com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.T2.is_leaf(), and com.cliffc.aa.HM.HM6.T2.no_uf().
Referenced by com.cliffc.aa.HM.HM6.T2._fresh_unify(), com.cliffc.aa.HM.HM6.T2.args(), com.cliffc.aa.HM.HM6.Syntax.debug_find(), com.cliffc.aa.HM.HM6.Syntax.find(), com.cliffc.aa.HM.HM6.hm(), com.cliffc.aa.HM.HM6.T2.p(), com.cliffc.aa.HM.HM6.Lambda.targ(), com.cliffc.aa.HM.HM6.Let.targ(), com.cliffc.aa.HM.HM6.Lambda2.targ0(), and com.cliffc.aa.HM.HM6.Lambda2.targ1().
fresh_base()
boolean com.cliffc.aa.HM.HM6.T2.fresh_base (T2 that, Worklist work) private
Definition at line 638 of file HM6.java.
{
       Type con = _con.meet(that._con);
       if( con==that._con ) return false; // No progress
       if( work!=null ) that._con = con;  // Yes progress, but no update if null work
       return true;
     }
References com.cliffc.aa.HM.HM6.T2._con, and com.cliffc.aa.type.Type< T extends Type< T >.meet().
Referenced by com.cliffc.aa.HM.HM6.T2._fresh_unify(), and com.cliffc.aa.HM.HM6.T2.unify_base().
fresh_unify()
boolean com.cliffc.aa.HM.HM6.T2.fresh_unify (T2 that, VStack nongen, Worklist work) package
Definition at line 652 of file HM6.java.
{
       assert VARS.isEmpty() && DUPS.isEmpty();
       int old = CNT;
       boolean progress = _fresh_unify(that,nongen,work);
       VARS.clear();  DUPS.clear();
       if( work==null && old!=CNT && DEBUG_LEAKS )
         throw unimpl("busted, made T2s but just testing");
       return progress;
     }
References com.cliffc.aa.HM.HM6.T2._fresh_unify(), com.cliffc.aa.HM.HM6.T2.CNT, com.cliffc.aa.HM.HM6.DEBUG_LEAKS, com.cliffc.aa.HM.HM6.T2.DUPS, and com.cliffc.aa.HM.HM6.T2.VARS.
Referenced by com.cliffc.aa.HM.HM6.Ident.hm().
get_dups()
VBitSet com.cliffc.aa.HM.HM6.T2.get_dups (VBitSet dups) package
Definition at line 823 of file HM6.java.
 { return _get_dups(new VBitSet(),dups); }
References com.cliffc.aa.HM.HM6.T2._get_dups().
Referenced by com.cliffc.aa.HM.HM6.T2.p(), com.cliffc.aa.HM.HM6.Syntax.p0(), and com.cliffc.aa.HM.HM6.T2.toString().
is_base()
boolean com.cliffc.aa.HM.HM6.T2.is_base () package
Definition at line 539 of file HM6.java.
 { return isa("Base") && _con!=null; }
References com.cliffc.aa.HM.HM6.T2._con, and com.cliffc.aa.HM.HM6.T2.isa().
Referenced by com.cliffc.aa.HM.HM6.T2._cycle_equals(), com.cliffc.aa.HM.HM6.T2._fresh_unify(), com.cliffc.aa.HM.HM6.T2._p(), com.cliffc.aa.HM.HM6.T2._unify(), and com.cliffc.aa.HM.HM6.T2.str().
is_fun()
boolean com.cliffc.aa.HM.HM6.T2.is_fun () package
Definition at line 540 of file HM6.java.
 { return isa("->"); }
References com.cliffc.aa.HM.HM6.T2.isa().
Referenced by com.cliffc.aa.HM.HM6.T2._p(), com.cliffc.aa.HM.HM6.Lambda.hm(), com.cliffc.aa.HM.HM6.Lambda2.hm(), com.cliffc.aa.HM.HM6.Apply.hm(), and com.cliffc.aa.HM.HM6.T2.str().
is_leaf()
boolean com.cliffc.aa.HM.HM6.T2.is_leaf () package
Definition at line 536 of file HM6.java.
 { return _name.charAt(0)=='V' || (isa("Base") && _con==null); }
References com.cliffc.aa.HM.HM6.T2._con, com.cliffc.aa.HM.HM6.T2._name, and com.cliffc.aa.HM.HM6.T2.isa().
Referenced by com.cliffc.aa.HM.HM6.T2._fresh(), com.cliffc.aa.HM.HM6.T2._fresh_unify(), com.cliffc.aa.HM.HM6.T2._occurs_in_type(), com.cliffc.aa.HM.HM6.T2._p(), com.cliffc.aa.HM.HM6.T2._unify(), com.cliffc.aa.HM.HM6.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM6.T2.find(), com.cliffc.aa.HM.HM6.T2.no_uf(), com.cliffc.aa.HM.HM6.T2.push_update_impl(), com.cliffc.aa.HM.HM6.T2.str(), and com.cliffc.aa.HM.HM6.T2.union().
isa()
boolean com.cliffc.aa.HM.HM6.T2.isa (String name) package
Definition at line 538 of file HM6.java.
 { return Util.eq(_name,name); }
References com.cliffc.aa.HM.HM6.T2._name, and com.cliffc.aa.util.Util.eq().
Referenced by com.cliffc.aa.HM.HM6.Con.hm(), com.cliffc.aa.HM.HM6.T2.is_base(), com.cliffc.aa.HM.HM6.T2.is_fun(), and com.cliffc.aa.HM.HM6.T2.is_leaf().
make_base()
static T2 com.cliffc.aa.HM.HM6.T2.make_base (Type con) static package
Definition at line 524 of file HM6.java.
 { return new T2("Base",con); }
References com.cliffc.aa.HM.HM6.T2.T2().
Referenced by com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM6.Con.prep_tree().
make_fun()
static T2 com.cliffc.aa.HM.HM6.T2.make_fun (T2... args) static package
Definition at line 522 of file HM6.java.
 { return new T2("->",null,args); }
References com.cliffc.aa.HM.HM6.T2.args(), and com.cliffc.aa.HM.HM6.T2.T2().
Referenced by com.cliffc.aa.HM.HM6.hm(), com.cliffc.aa.HM.HM6.Lambda.hm(), com.cliffc.aa.HM.HM6.Lambda2.hm(), and com.cliffc.aa.HM.HM6.Apply.hm().
make_leaf()
static T2 com.cliffc.aa.HM.HM6.T2.make_leaf () static package
Definition at line 523 of file HM6.java.
 { return new T2("V"+CNT,null,new T2[1]); }
References com.cliffc.aa.HM.HM6.T2.CNT, and com.cliffc.aa.HM.HM6.T2.T2().
Referenced by com.cliffc.aa.HM.HM6.T2._fresh(), com.cliffc.aa.HM.HM6.hm(), com.cliffc.aa.HM.HM6.Lambda.Lambda(), com.cliffc.aa.HM.HM6.Lambda2.Lambda2(), com.cliffc.aa.HM.HM6.Let.Let(), com.cliffc.aa.HM.HM6.Ident.prep_tree(), com.cliffc.aa.HM.HM6.Lambda.prep_tree(), com.cliffc.aa.HM.HM6.Lambda2.prep_tree(), and com.cliffc.aa.HM.HM6.Apply.prep_tree().
no_uf()
boolean com.cliffc.aa.HM.HM6.T2.no_uf () package
Definition at line 537 of file HM6.java.
 { return !is_leaf() || _args[0]==null; }
References com.cliffc.aa.HM.HM6.T2._args, and com.cliffc.aa.HM.HM6.T2.is_leaf().
Referenced by com.cliffc.aa.HM.HM6.T2._cycle_equals(), com.cliffc.aa.HM.HM6.T2._fresh(), com.cliffc.aa.HM.HM6.T2._fresh_unify(), com.cliffc.aa.HM.HM6.T2._get_dups(), com.cliffc.aa.HM.HM6.T2._occurs_in_type(), com.cliffc.aa.HM.HM6.T2._p(), com.cliffc.aa.HM.HM6.T2._unify(), com.cliffc.aa.HM.HM6.T2.find(), com.cliffc.aa.HM.HM6.T2.push_update_impl(), and com.cliffc.aa.HM.HM6.T2.union().
nongen_in()
boolean com.cliffc.aa.HM.HM6.T2.nongen_in (VStack syn) package
Definition at line 748 of file HM6.java.
{
       if( syn==null ) return false;
       assert ODUPS.isEmpty();
       boolean found = _nongen_in(syn);
       ODUPS.clear();
       return found;
     }
References com.cliffc.aa.HM.HM6.T2._nongen_in(), and com.cliffc.aa.HM.HM6.T2.ODUPS.
Referenced by com.cliffc.aa.HM.HM6.T2._fresh(), and com.cliffc.aa.HM.HM6.T2._fresh_unify().
occurs_in()
boolean com.cliffc.aa.HM.HM6.T2.occurs_in (Syntax syn) package
Definition at line 717 of file HM6.java.
{
       if( syn==null ) return false;
       assert ODUPS.isEmpty();
       boolean found = _occurs_in(syn);
       ODUPS.clear();
       return found;
     }
References com.cliffc.aa.HM.HM6.T2._occurs_in(), and com.cliffc.aa.HM.HM6.T2.ODUPS.
Referenced by com.cliffc.aa.HM.HM6.Ident.add_occurs().
occurs_in_type()
boolean com.cliffc.aa.HM.HM6.T2.occurs_in_type (T2 x) package
Definition at line 724 of file HM6.java.
{
       assert ODUPS.isEmpty();
       boolean found = _occurs_in_type(x);
       ODUPS.clear();
       return found;
     }
References com.cliffc.aa.HM.HM6.T2._occurs_in_type(), and com.cliffc.aa.HM.HM6.T2.ODUPS.
p() [1/2]
String com.cliffc.aa.HM.HM6.T2.p ()
Definition at line 860 of file HM6.java.
 { return p(get_dups(new VBitSet())); }
References com.cliffc.aa.HM.HM6.T2.get_dups(), and com.cliffc.aa.HM.HM6.T2.p().
Referenced by com.cliffc.aa.HM.HM6.T2.p().
p() [2/2]
String com.cliffc.aa.HM.HM6.T2.p (VBitSet dups) package
Definition at line 861 of file HM6.java.
 { return find()._p(new SB(), new VBitSet(), dups).toString(); }
References com.cliffc.aa.HM.HM6.T2._p(), com.cliffc.aa.HM.HM6.T2.find(), and com.cliffc.aa.util.SB.toString().
prim()
static T2 com.cliffc.aa.HM.HM6.T2.prim (String name, T2... args) static package
Definition at line 525 of file HM6.java.
 { return new T2(name,null,args); }
References com.cliffc.aa.HM.HM6.T2.args(), and com.cliffc.aa.HM.HM6.T2.T2().
Referenced by com.cliffc.aa.HM.HM6.hm().
push_update()
boolean com.cliffc.aa.HM.HM6.T2.push_update (Ident a) package
Definition at line 795 of file HM6.java.
 { assert UPDATE_VISIT.isEmpty(); push_update_impl(a); UPDATE_VISIT.clear(); return true; }
References com.cliffc.aa.HM.HM6.T2.push_update_impl(), and com.cliffc.aa.HM.HM6.T2.UPDATE_VISIT.
Referenced by com.cliffc.aa.HM.HM6.Lambda.prep_lookup_deps(), com.cliffc.aa.HM.HM6.Lambda2.prep_lookup_deps(), and com.cliffc.aa.HM.HM6.Let.prep_lookup_deps().
push_update_impl()
void com.cliffc.aa.HM.HM6.T2.push_update_impl (Ident a) private
Definition at line 796 of file HM6.java.
{
       assert no_uf();
       if( is_leaf() || _args.length==0 ) {
         if( _deps==null ) _deps = new Ary<>(Ident.class);
         if( _deps.find(a)==-1 ) _deps.push(a);
       } else {
         if( UPDATE_VISIT.tset(_uid) ) return;
         for( int i=0; i<_args.length; i++ )
           args(i).push_update_impl(a);
       }
     }
References com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.T2._deps, com.cliffc.aa.HM.HM6.T2._uid, com.cliffc.aa.HM.HM6.T2.args(), com.cliffc.aa.HM.HM6.T2.is_leaf(), com.cliffc.aa.HM.HM6.T2.no_uf(), com.cliffc.aa.HM.HM6.T2.push_update_impl(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.HM.HM6.T2.UPDATE_VISIT.
Referenced by com.cliffc.aa.HM.HM6.T2.push_update(), and com.cliffc.aa.HM.HM6.T2.push_update_impl().
reset()
static void com.cliffc.aa.HM.HM6.T2.reset () static package
Definition at line 882 of file HM6.java.
 { CNT=0; DUPS.clear(); VARS.clear(); ODUPS.clear(); CDUPS.clear(); UPDATE_VISIT.clear(); }
References com.cliffc.aa.HM.HM6.T2.CDUPS, com.cliffc.aa.HM.HM6.T2.CNT, com.cliffc.aa.HM.HM6.T2.DUPS, com.cliffc.aa.HM.HM6.T2.ODUPS, com.cliffc.aa.HM.HM6.T2.UPDATE_VISIT, and com.cliffc.aa.HM.HM6.T2.VARS.
Referenced by com.cliffc.aa.HM.HM6.reset().
str() [1/2]
static SB com.cliffc.aa.HM.HM6.T2.str (SB sb, VBitSet visit, T2 t, VBitSet dups) static private
Definition at line 857 of file HM6.java.
 { return t==null ? sb.p("_") : t.str(sb,visit,dups); }
References com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM6.T2.str().
str() [2/2]
SB com.cliffc.aa.HM.HM6.T2.str (SB sb, VBitSet visit, VBitSet dups) package
Definition at line 836 of file HM6.java.
{
       if( is_leaf() || is_base() ) {
         if( is_base() ) sb.p(_con instanceof TypeMemPtr ? "str" : _con.toString()); else sb.p(_name);
         return _args.length==0 || _args[0]==null ? sb : _args[0].str(sb.p(">>"), visit, dups);
       }
       boolean dup = dups.get(_uid);
       if( dup ) sb.p('$').p(_uid);
       if( visit.tset(_uid) && dup ) return sb;
       if( dup ) sb.p(':');
       if( is_fun() ) {
         sb.p("{ ");
         for( int i=0; i<_args.length-1; i++ )
           str(sb,visit,_args[i],dups).p(" ");
         return str(sb.p("-> "),visit,_args[_args.length-1],dups).p(" }");
       }
       // Generic structural T2
       sb.p("(").p(_name).p(" ");
       for( T2 t : _args ) str(sb,visit,t,dups).p(" ");
       return sb.unchar().p(")");
     }
References com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.T2._con, com.cliffc.aa.HM.HM6.T2._name, com.cliffc.aa.HM.HM6.T2._uid, com.cliffc.aa.HM.HM6.T2.is_base(), com.cliffc.aa.HM.HM6.T2.is_fun(), com.cliffc.aa.HM.HM6.T2.is_leaf(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM6.T2.str(), com.cliffc.aa.type.Type< T extends Type< T >.toString(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.util.SB.unchar().
Referenced by com.cliffc.aa.HM.HM6.Syntax.p0(), com.cliffc.aa.HM.HM6.VStack.str(), com.cliffc.aa.HM.HM6.T2.str(), and com.cliffc.aa.HM.HM6.T2.toString().
toString()
String com.cliffc.aa.HM.HM6.T2.toString ()
Definition at line 835 of file HM6.java.
 { return str(new SB(), new VBitSet(), get_dups(new VBitSet()) ).toString(); }
References com.cliffc.aa.HM.HM6.T2.get_dups(), com.cliffc.aa.HM.HM6.T2.str(), and com.cliffc.aa.util.SB.toString().
unify()
boolean com.cliffc.aa.HM.HM6.T2.unify (T2 that, Worklist work) package
Definition at line 586 of file HM6.java.
{
       if( this==that ) return false;
       assert DUPS.isEmpty();
       boolean progress = _unify(that,work);
       DUPS.clear();
       return progress;
     }
References com.cliffc.aa.HM.HM6.T2._unify(), and com.cliffc.aa.HM.HM6.T2.DUPS.
Referenced by com.cliffc.aa.HM.HM6.hm(), com.cliffc.aa.HM.HM6.Lambda.hm(), com.cliffc.aa.HM.HM6.Lambda2.hm(), com.cliffc.aa.HM.HM6.Let.hm(), and com.cliffc.aa.HM.HM6.Apply.hm().
unify_base()
boolean com.cliffc.aa.HM.HM6.T2.unify_base (T2 that, Worklist work) private
Definition at line 631 of file HM6.java.
{
       fresh_base(that,work);
       if( work==null ) return true;
       _args = new T2[1];        // Room for a forwarding pointer
       _con=null;                // Flip from 'Base' to 'Leaf'
       return union(that,work);
     }
References com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.T2._con, and com.cliffc.aa.HM.HM6.T2.fresh_base().
Referenced by com.cliffc.aa.HM.HM6.T2._unify().
union()
boolean com.cliffc.aa.HM.HM6.T2.union (T2 that, Worklist work) package
Definition at line 563 of file HM6.java.
{
       assert is_leaf() && no_uf(); // Cannot union twice
       if( this==that ) return false;
       if( work==null ) return true; // Report progress without changing
       // Worklist: put updates on the worklist for revisiting
       if( _deps != null ) {
         work.addAll(_deps); // Re-Apply
         // Merge update lists, for future unions
         if( that._deps==null && that.is_leaf() ) that._deps = _deps;
         else
           for( Ident dep : _deps ) that.push_update(dep);
         _deps = null;
       }
       _args[0] = that;         // U-F update
       return true;
     }
References com.cliffc.aa.HM.HM6.T2._args, com.cliffc.aa.HM.HM6.T2._deps, com.cliffc.aa.HM.HM6.T2.is_leaf(), and com.cliffc.aa.HM.HM6.T2.no_uf().
Referenced by com.cliffc.aa.HM.HM6.T2._fresh_unify(), and com.cliffc.aa.HM.HM6.T2._unify().
vput()
boolean com.cliffc.aa.HM.HM6.T2.vput (T2 that, boolean progress) private
Definition at line 694 of file HM6.java.
 { VARS.put(this,that); return progress; }
References com.cliffc.aa.HM.HM6.T2.VARS.
Referenced by com.cliffc.aa.HM.HM6.T2._fresh_unify().
Member Data Documentation
_args
T2 [] com.cliffc.aa.HM.HM6.T2._args package
Definition at line 513 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.T2._cycle_equals(), com.cliffc.aa.HM.HM6.T2._fresh(), com.cliffc.aa.HM.HM6.T2._fresh_unify(), com.cliffc.aa.HM.HM6.T2._get_dups(), com.cliffc.aa.HM.HM6.T2._occurs_in_type(), com.cliffc.aa.HM.HM6.T2._p(), com.cliffc.aa.HM.HM6.T2._unify(), com.cliffc.aa.HM.HM6.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM6.T2.args(), com.cliffc.aa.HM.HM6.T2.copy(), com.cliffc.aa.HM.HM6.T2.find(), com.cliffc.aa.HM.HM6.Apply.hm(), com.cliffc.aa.HM.HM6.T2.no_uf(), com.cliffc.aa.HM.HM6.T2.push_update_impl(), com.cliffc.aa.HM.HM6.T2.str(), com.cliffc.aa.HM.HM6.T2.T2(), com.cliffc.aa.HM.HM6.T2.unify_base(), and com.cliffc.aa.HM.HM6.T2.union().
_con
Type com.cliffc.aa.HM.HM6.T2._con package
Definition at line 516 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.T2._cycle_equals(), com.cliffc.aa.HM.HM6.T2._p(), com.cliffc.aa.HM.HM6.T2.copy(), com.cliffc.aa.HM.HM6.T2.fresh_base(), com.cliffc.aa.HM.HM6.T2.is_base(), com.cliffc.aa.HM.HM6.T2.is_leaf(), com.cliffc.aa.HM.HM6.T2.str(), com.cliffc.aa.HM.HM6.T2.T2(), and com.cliffc.aa.HM.HM6.T2.unify_base().
_deps
Ary<Ident> com.cliffc.aa.HM.HM6.T2._deps package
Definition at line 519 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM6.Lambda.add_occurs(), com.cliffc.aa.HM.HM6.Lambda2.add_occurs(), com.cliffc.aa.HM.HM6.Let.add_occurs(), com.cliffc.aa.HM.HM6.T2.push_update_impl(), and com.cliffc.aa.HM.HM6.T2.union().
_name
final String com.cliffc.aa.HM.HM6.T2._name package
Definition at line 510 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.T2._cycle_equals(), com.cliffc.aa.HM.HM6.T2._fresh_unify(), com.cliffc.aa.HM.HM6.T2._p(), com.cliffc.aa.HM.HM6.T2._unify(), com.cliffc.aa.HM.HM6.T2.copy(), com.cliffc.aa.HM.HM6.T2.is_leaf(), com.cliffc.aa.HM.HM6.T2.isa(), com.cliffc.aa.HM.HM6.T2.str(), and com.cliffc.aa.HM.HM6.T2.T2().
_uid
final int com.cliffc.aa.HM.HM6.T2._uid package
Definition at line 505 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.T2._get_dups(), com.cliffc.aa.HM.HM6.T2._occurs_in_type(), com.cliffc.aa.HM.HM6.T2._p(), com.cliffc.aa.HM.HM6.T2._unify(), com.cliffc.aa.HM.HM6.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM6.T2.dbl_uid(), com.cliffc.aa.HM.HM6.T2.push_update_impl(), com.cliffc.aa.HM.HM6.T2.str(), and com.cliffc.aa.HM.HM6.T2.T2().
CDUPS
final HashMap<T2,T2> com.cliffc.aa.HM.HM6.T2.CDUPS = new HashMap<>() static private
Definition at line 763 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.T2._cycle_equals(), com.cliffc.aa.HM.HM6.T2.cycle_equals(), and com.cliffc.aa.HM.HM6.T2.reset().
CNT
int com.cliffc.aa.HM.HM6.T2.CNT =0 static private
Definition at line 504 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.T2.fresh_unify(), com.cliffc.aa.HM.HM6.hm(), com.cliffc.aa.HM.HM6.T2.make_leaf(), com.cliffc.aa.HM.HM6.T2.reset(), and com.cliffc.aa.HM.HM6.T2.T2().
DUPS
final HashMap<Long,T2> com.cliffc.aa.HM.HM6.T2.DUPS = new HashMap<>() static private
Definition at line 585 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.T2._unify(), com.cliffc.aa.HM.HM6.T2.fresh_unify(), com.cliffc.aa.HM.HM6.T2.reset(), and com.cliffc.aa.HM.HM6.T2.unify().
ODUPS
final VBitSet com.cliffc.aa.HM.HM6.T2.ODUPS = new VBitSet() static private
Definition at line 716 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.T2._occurs_in_type(), com.cliffc.aa.HM.HM6.T2.nongen_in(), com.cliffc.aa.HM.HM6.T2.occurs_in(), com.cliffc.aa.HM.HM6.T2.occurs_in_type(), and com.cliffc.aa.HM.HM6.T2.reset().
UPDATE_VISIT
final VBitSet com.cliffc.aa.HM.HM6.T2.UPDATE_VISIT = new VBitSet() static package
Definition at line 794 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.T2.add_deps_work(), com.cliffc.aa.HM.HM6.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM6.T2.push_update(), com.cliffc.aa.HM.HM6.T2.push_update_impl(), and com.cliffc.aa.HM.HM6.T2.reset().
VARS
final HashMap<T2,T2> com.cliffc.aa.HM.HM6.T2.VARS = new HashMap<>() static private
Definition at line 651 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.T2._fresh(), com.cliffc.aa.HM.HM6.T2._fresh_unify(), com.cliffc.aa.HM.HM6.T2.fresh_unify(), com.cliffc.aa.HM.HM6.T2.reset(), and com.cliffc.aa.HM.HM6.T2.vput().
The documentation for this class was generated from the following file:
HM6.java