aa: com.cliffc.aa.util.IBitSet Class Reference
com.cliffc.aa.util.IBitSet Class Reference
Classes
class Iter
Public Member Functions
int bitCount ()
IBitSet clear ()
boolean clr (int idx)
boolean disjoint (IBitSet bs)
IBitSet flip ()
boolean is_empty ()
Iterator< Integer > iterator ()
int max ()
IBitSet or (IBitSet bs)
boolean set (int idx)
boolean subsetsX (IBitSet bs)
void subtract (IBitSet bs)
String toString ()
SB toString (SB sb)
boolean tst (int idx)
Static Public Attributes
static final IBitSet EMPTY = new IBitSet()
static final IBitSet FULL = new IBitSet().flip()
Private Member Functions
boolean _clr (int idx)
boolean _set (int idx)
boolean _tst (int idx)
int wd (int x)
int xd (int x)
Static Private Member Functions
static int idx (int i)
static int mask (int i)
Private Attributes
final AryInt _bits = new AryInt()
boolean _sign
Detailed Description
Definition at line 10 of file IBitSet.java.
Member Function Documentation
_clr()
boolean com.cliffc.aa.util.IBitSet._clr (int idx) private
Definition at line 36 of file IBitSet.java.
{
     int widx = idx (idx);
     int mask = mask(idx);
     int bits = _bits.atX(widx);
     _bits.setX(widx, bits & ~mask);
     while( _bits._len>0 && _bits.last()==0 )  _bits.pop(); // Shrink
     return (bits&mask)!=0;
   }
References com.cliffc.aa.util.IBitSet._bits, com.cliffc.aa.util.AryInt._len, com.cliffc.aa.util.AryInt.atX(), com.cliffc.aa.util.IBitSet.idx(), com.cliffc.aa.util.AryInt.last(), com.cliffc.aa.util.IBitSet.mask(), com.cliffc.aa.util.AryInt.pop(), and com.cliffc.aa.util.AryInt.setX().
Referenced by com.cliffc.aa.util.IBitSet.clr(), and com.cliffc.aa.util.IBitSet.set().
_set()
boolean com.cliffc.aa.util.IBitSet._set (int idx) private
Definition at line 29 of file IBitSet.java.
{
     int widx = idx (idx);
     int mask = mask(idx);
     int bits = _bits.atX(widx);
     _bits.setX(widx, bits | mask);
     return (bits&mask)!=0;
   }
References com.cliffc.aa.util.IBitSet._bits, com.cliffc.aa.util.AryInt.atX(), com.cliffc.aa.util.IBitSet.idx(), com.cliffc.aa.util.IBitSet.mask(), and com.cliffc.aa.util.AryInt.setX().
Referenced by com.cliffc.aa.util.IBitSet.clr(), and com.cliffc.aa.util.IBitSet.set().
_tst()
boolean com.cliffc.aa.util.IBitSet._tst (int idx) private
Definition at line 23 of file IBitSet.java.
 { return (_bits.atX(idx(idx)) & mask(idx)) != 0; }
References com.cliffc.aa.util.IBitSet._bits, com.cliffc.aa.util.AryInt.atX(), com.cliffc.aa.util.IBitSet.idx(), and com.cliffc.aa.util.IBitSet.mask().
Referenced by com.cliffc.aa.util.IBitSet.tst().
bitCount()
int com.cliffc.aa.util.IBitSet.bitCount ()
Definition at line 47 of file IBitSet.java.
{
     assert !_sign;              // Infinite if sign is set
     int sum=0;
     for( int i=0; i<_bits._len; i++ )
       sum += Integer.bitCount(_bits._es[i]);
     return sum;
   }
References com.cliffc.aa.util.IBitSet._bits, com.cliffc.aa.util.AryInt._es, com.cliffc.aa.util.AryInt._len, and com.cliffc.aa.util.IBitSet._sign.
clear()
IBitSet com.cliffc.aa.util.IBitSet.clear ()
Definition at line 66 of file IBitSet.java.
{
     _sign=false;
     _bits.clear();
     return this;
   }
References com.cliffc.aa.util.IBitSet._bits, com.cliffc.aa.util.IBitSet._sign, and com.cliffc.aa.util.AryInt.clear().
clr()
boolean com.cliffc.aa.util.IBitSet.clr (int idx)
Definition at line 27 of file IBitSet.java.
 { return _sign ? !_set(idx) : _clr(idx); }
References com.cliffc.aa.util.IBitSet._clr(), com.cliffc.aa.util.IBitSet._set(), com.cliffc.aa.util.IBitSet._sign, and com.cliffc.aa.util.IBitSet.idx().
disjoint()
boolean com.cliffc.aa.util.IBitSet.disjoint (IBitSet bs)
Definition at line 88 of file IBitSet.java.
{
     if(    is_empty() ) return true; // Empty set must be disjoint
     if( bs.is_empty() ) return true; // Empty set must be disjoint
     if( _sign && bs._sign ) return false; // Both extensions are set
     IBitSet min = this;
     if( _bits._len > bs._bits._len ) { min=bs; bs=this; } // max in bs
     if( min._sign && min._bits._len < bs._bits._len ) return false; // Extension in min overlaps last bits in max
     for( int i=0; i<min._bits._len; i++ )
       if( (min.wd(i)&bs.wd(i))!= 0 )
         return false;
     return true;
   }
References com.cliffc.aa.util.IBitSet._bits, com.cliffc.aa.util.AryInt._len, com.cliffc.aa.util.IBitSet._sign, com.cliffc.aa.util.IBitSet.is_empty(), and com.cliffc.aa.util.IBitSet.wd().
flip()
IBitSet com.cliffc.aa.util.IBitSet.flip ()
Definition at line 45 of file IBitSet.java.
 { _sign=!_sign; return this; }
References com.cliffc.aa.util.IBitSet._sign.
idx()
static int com.cliffc.aa.util.IBitSet.idx (int i) static private
Definition at line 18 of file IBitSet.java.
 { return i>>5; }
Referenced by com.cliffc.aa.util.IBitSet._clr(), com.cliffc.aa.util.IBitSet._set(), com.cliffc.aa.util.IBitSet._tst(), com.cliffc.aa.util.IBitSet.clr(), com.cliffc.aa.util.IBitSet.Iter.hasNext(), com.cliffc.aa.util.IBitSet.Iter.next(), com.cliffc.aa.util.IBitSet.set(), and com.cliffc.aa.util.IBitSet.tst().
is_empty()
boolean com.cliffc.aa.util.IBitSet.is_empty ()
Definition at line 85 of file IBitSet.java.
 { return _bits._len==0 && !_sign; }
References com.cliffc.aa.util.IBitSet._bits, com.cliffc.aa.util.AryInt._len, and com.cliffc.aa.util.IBitSet._sign.
Referenced by com.cliffc.aa.util.IBitSet.disjoint(), and com.cliffc.aa.util.IBitSet.subsetsX().
iterator()
Iterator<Integer> com.cliffc.aa.util.IBitSet.iterator ()
Returns
an iterator
Definition at line 134 of file IBitSet.java.
 { return new Iter(); }
mask()
static int com.cliffc.aa.util.IBitSet.mask (int i) static private
Definition at line 19 of file IBitSet.java.
 { return 1<<(i&31); }
Referenced by com.cliffc.aa.util.IBitSet._clr(), com.cliffc.aa.util.IBitSet._set(), com.cliffc.aa.util.IBitSet._tst(), and com.cliffc.aa.util.IBitSet.Iter.hasNext().
max()
int com.cliffc.aa.util.IBitSet.max ()
Definition at line 54 of file IBitSet.java.
                     {
     assert !_sign;              // Infinite if sign is set
     if( _bits._len==0 ) return 0;
     return (31 - Integer.numberOfLeadingZeros(_bits.last()))+((_bits._len-1)<<5);
   }
References com.cliffc.aa.util.IBitSet._bits, com.cliffc.aa.util.AryInt._len, com.cliffc.aa.util.IBitSet._sign, and com.cliffc.aa.util.AryInt.last().
Referenced by com.cliffc.aa.util.IBitSet.subsetsX().
or()
IBitSet com.cliffc.aa.util.IBitSet.or (IBitSet bs)
Definition at line 73 of file IBitSet.java.
{
     _sign |= bs._sign;
     for( int i=0; i<bs._bits._len; i++ )
       _bits.setX(i,_bits.atX(i)|bs.wd(i));
     return this;
   }
References com.cliffc.aa.util.IBitSet._bits, com.cliffc.aa.util.AryInt._len, com.cliffc.aa.util.IBitSet._sign, com.cliffc.aa.util.AryInt.atX(), com.cliffc.aa.util.AryInt.setX(), and com.cliffc.aa.util.IBitSet.wd().
set()
boolean com.cliffc.aa.util.IBitSet.set (int idx)
Definition at line 26 of file IBitSet.java.
 { return _sign ? !_clr(idx) : _set(idx); }
References com.cliffc.aa.util.IBitSet._clr(), com.cliffc.aa.util.IBitSet._set(), com.cliffc.aa.util.IBitSet._sign, and com.cliffc.aa.util.IBitSet.idx().
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.bitset(), and com.cliffc.aa.HM.HM4.T2.live().
subsetsX()
boolean com.cliffc.aa.util.IBitSet.subsetsX (IBitSet bs)
Definition at line 103 of file IBitSet.java.
{
     assert !bs.is_empty();      // Undefined
     int max=Math.max(_bits._len,bs._bits._len);
     for( int i=0; i<max; i++ )
       if( (xd(i)|bs.xd(i)) != bs.xd(i) )     // All bits in common
         return false;
     return true;
   }
References com.cliffc.aa.util.IBitSet._bits, com.cliffc.aa.util.AryInt._len, com.cliffc.aa.util.IBitSet.is_empty(), com.cliffc.aa.util.IBitSet.max(), and com.cliffc.aa.util.IBitSet.xd().
subtract()
void com.cliffc.aa.util.IBitSet.subtract (IBitSet bs)
Definition at line 80 of file IBitSet.java.
{
     for( int i=0; i<bs._bits._len; i++ )
       _bits.setX(i,_bits.atX(i)&~bs.wd(i));
   }
References com.cliffc.aa.util.IBitSet._bits, com.cliffc.aa.util.AryInt._len, com.cliffc.aa.util.AryInt.atX(), com.cliffc.aa.util.AryInt.setX(), and com.cliffc.aa.util.IBitSet.wd().
toString() [1/2]
String com.cliffc.aa.util.IBitSet.toString ()
Definition at line 112 of file IBitSet.java.
 { return toString(new SB()).toString(); }
References com.cliffc.aa.util.IBitSet.toString().
Referenced by com.cliffc.aa.util.IBitSet.toString().
toString() [2/2]
SB com.cliffc.aa.util.IBitSet.toString (SB sb)
Definition at line 113 of file IBitSet.java.
{
     if( _bits._len==0 ) return sb.p(_sign?"[...]":"[]");
     int x = -1;                 // No range-in-process
     sb.p('[');
     for( int i=0; i<_bits._len*32+1; i++ ) {
       if( tst(i) ) {
         if( x==-1 ) x=i;        // Start a range
       } else {
         if( x!=-1 ) {           // End a range
           if( x+1==i ) sb.p(x).p(',');
           else if( x+2==i ) sb.p(x).p(',').p(i-1).p(',');
           else sb.p(x).p("...").p(i-1).p(',');
           x = -1;
         }
       }
     }
     if( x != -1 ) sb.p(x).p("...,"); // Close open range
     return sb.unchar().p(']');
   }
References com.cliffc.aa.util.IBitSet._bits, com.cliffc.aa.util.AryInt._len, com.cliffc.aa.util.IBitSet._sign, com.cliffc.aa.util.SB.p(), com.cliffc.aa.util.IBitSet.tst(), and com.cliffc.aa.util.SB.unchar().
tst()
boolean com.cliffc.aa.util.IBitSet.tst (int idx)
Definition at line 22 of file IBitSet.java.
 { return _sign != _tst(idx); }
References com.cliffc.aa.util.IBitSet._sign, com.cliffc.aa.util.IBitSet._tst(), and com.cliffc.aa.util.IBitSet.idx().
Referenced by com.cliffc.aa.util.IBitSet.toString().
wd()
int com.cliffc.aa.util.IBitSet.wd (int x) private
Definition at line 60 of file IBitSet.java.
 { return _bits._es[x]; }
References com.cliffc.aa.util.IBitSet._bits, and com.cliffc.aa.util.AryInt._es.
Referenced by com.cliffc.aa.util.IBitSet.disjoint(), com.cliffc.aa.util.IBitSet.or(), and com.cliffc.aa.util.IBitSet.subtract().
xd()
int com.cliffc.aa.util.IBitSet.xd (int x) private
Definition at line 61 of file IBitSet.java.
{
     int b = _bits.atX(x); // zero extend if off end
     return _sign ? ~b : b;// adjust for sign
   }
References com.cliffc.aa.util.IBitSet._bits, com.cliffc.aa.util.IBitSet._sign, and com.cliffc.aa.util.AryInt.atX().
Referenced by com.cliffc.aa.util.IBitSet.subsetsX().
Member Data Documentation
_bits
final AryInt com.cliffc.aa.util.IBitSet._bits = new AryInt() private
Definition at line 12 of file IBitSet.java.
Referenced by com.cliffc.aa.util.IBitSet._clr(), com.cliffc.aa.util.IBitSet._set(), com.cliffc.aa.util.IBitSet._tst(), com.cliffc.aa.util.IBitSet.bitCount(), com.cliffc.aa.util.IBitSet.clear(), com.cliffc.aa.util.IBitSet.disjoint(), com.cliffc.aa.util.IBitSet.Iter.hasNext(), com.cliffc.aa.util.IBitSet.is_empty(), com.cliffc.aa.util.IBitSet.max(), com.cliffc.aa.util.IBitSet.Iter.next(), com.cliffc.aa.util.IBitSet.or(), com.cliffc.aa.util.IBitSet.subsetsX(), com.cliffc.aa.util.IBitSet.subtract(), com.cliffc.aa.util.IBitSet.toString(), com.cliffc.aa.util.IBitSet.wd(), and com.cliffc.aa.util.IBitSet.xd().
_sign
boolean com.cliffc.aa.util.IBitSet._sign private
Definition at line 11 of file IBitSet.java.
Referenced by com.cliffc.aa.util.IBitSet.bitCount(), com.cliffc.aa.util.IBitSet.clear(), com.cliffc.aa.util.IBitSet.clr(), com.cliffc.aa.util.IBitSet.disjoint(), com.cliffc.aa.util.IBitSet.flip(), com.cliffc.aa.util.IBitSet.is_empty(), com.cliffc.aa.util.IBitSet.max(), com.cliffc.aa.util.IBitSet.or(), com.cliffc.aa.util.IBitSet.set(), com.cliffc.aa.util.IBitSet.toString(), com.cliffc.aa.util.IBitSet.tst(), and com.cliffc.aa.util.IBitSet.xd().
EMPTY
final IBitSet com.cliffc.aa.util.IBitSet.EMPTY = new IBitSet() static
Definition at line 15 of file IBitSet.java.
FULL
final IBitSet com.cliffc.aa.util.IBitSet.FULL = new IBitSet().flip() static
Definition at line 16 of file IBitSet.java.
The documentation for this class was generated from the following file:
IBitSet.java