aa: com.cliffc.aa.GVNGCM.Mode Enum Reference
com.cliffc.aa.GVNGCM.Mode Enum Reference
Public Member Functions
Mode (boolean CG)
Public Attributes
final boolean _CG
Opto =(true)
Parse =(false)
PesiCG =(true)
PesiNoCG =(false)
Detailed Description
Definition at line 14 of file GVNGCM.java.
Constructor & Destructor Documentation
Mode()
com.cliffc.aa.GVNGCM.Mode.Mode (boolean CG)
Definition at line 20 of file GVNGCM.java.
 { _CG=CG; }
Member Data Documentation
_CG
final boolean com.cliffc.aa.GVNGCM.Mode._CG
Definition at line 19 of file GVNGCM.java.
Referenced by com.cliffc.aa.node.CallNode.add_flow_use_extra(), and com.cliffc.aa.node.FunNode.split_size().
Opto
com.cliffc.aa.GVNGCM.Mode.Opto =(true)
Definition at line 17 of file GVNGCM.java.
Referenced by com.cliffc.aa.Parse.go(), com.cliffc.aa.node.Node.init1(), com.cliffc.aa.node.CallNode.least_cost(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.Env.lookup_valtype(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.node.TestNodeSmall.testUnresolvedAdd(), and com.cliffc.aa.node.Node.walk_opt().
Parse
com.cliffc.aa.GVNGCM.Mode.Parse =(false)
Definition at line 15 of file GVNGCM.java.
Referenced by com.cliffc.aa.Env.Env(), com.cliffc.aa.node.FunNode.ideal_inline(), com.cliffc.aa.node.ScopeNode.ideal_reduce(), com.cliffc.aa.node.ScopeNode.live(), com.cliffc.aa.node.ScopeNode.live_use(), com.cliffc.aa.node.FunPtrNode.merge_ref_def(), com.cliffc.aa.Parse.prog(), com.cliffc.aa.GVNGCM.reset_to_init0(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.node.TestNodeSmall.testUnresolvedAdd(), and com.cliffc.aa.Env.top_scope().
PesiCG
com.cliffc.aa.GVNGCM.Mode.PesiCG =(true)
Definition at line 18 of file GVNGCM.java.
Referenced by com.cliffc.aa.Parse.go(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.TestLive.testBasic(), and com.cliffc.aa.node.TestNode.testMonotonic().
PesiNoCG
com.cliffc.aa.GVNGCM.Mode.PesiNoCG =(false)
Definition at line 16 of file GVNGCM.java.
Referenced by com.cliffc.aa.Parse.go(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.TestLive.testBasic(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.TestLive.testNewObj(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), and com.cliffc.aa.node.TestNodeSmall.testUnresolvedAdd().
The documentation for this enum was generated from the following file:
GVNGCM.java