aa: com.cliffc.aa.HM.HM.T2 Class Reference
com.cliffc.aa.HM.HM.T2 Class Reference
Public Member Functions
String p ()
String toString ()
Package Functions
Type _as_flow ()
boolean _cycle_equals (T2 t)
VBitSet _get_dups (VBitSet visit, VBitSet dups)
boolean _occurs_in_type (T2 x)
void add_deps_work (Worklist work)
T2 args (int i)
Type as_flow ()
T2 copy ()
boolean cycle_equals (T2 t)
T2 debug_find ()
T2 find ()
T2 find (int uid)
BitsFun find_fidxs ()
T2 fresh ()
boolean fresh_unify (T2 that, VStack nongen, Worklist work)
VBitSet get_dups (VBitSet dups)
boolean is_base ()
boolean is_err ()
boolean is_fun ()
boolean is_leaf ()
boolean is_nilable ()
boolean is_struct ()
boolean is_tuple ()
boolean isa (String name)
T2 miss_field (String id)
boolean no_uf ()
boolean nongen_in (VStack vs)
boolean occurs_in_type (T2 x)
String p (VBitSet dups)
T2 push_update (Ary< Syntax > as)
T2 push_update (Syntax a)
SB str (SB sb, VBitSet visit, VBitSet dups)
boolean unify (T2 that, Worklist work)
boolean unify_nil (T2 that, Worklist work)
boolean union (T2 that, Worklist work)
Type walk_types_in (Type t)
Type walk_types_out (Type t)
Static Package Functions
static T2 make_base (Type flow)
static T2 make_err (String s)
static T2 make_fun (BitsFun fidxs, T2... args)
static T2 make_leaf ()
static T2 make_nil (T2 leaf)
static T2 make_struct (BitsAlias aliases, String[] ids, T2[] flds)
static T2 make_struct (BitsAlias aliases, String[] ids, T2[] flds, boolean open)
static void reset ()
Package Attributes
BitsAlias _alias
T2[] _args
Ary< Syntax > _deps
String _err
BitsFun _fidxs
Type _flow
String[] _ids
String _name
boolean _open
final int _uid
Static Package Attributes
static final NonBlockingHashMapLong< TypeStruct > ADUPS = new NonBlockingHashMapLong<>()
static final VBitSet UPDATE_VISIT = new VBitSet()
Private Member Functions
T2 (@NotNull String name)
T2 (@NotNull String name, T2 @NotNull ... args)
boolean _can_be_HM_base (T2 that, Type that_flow)
boolean _cycle_equals_struct (T2 t)
T2 _find (int uid, VBitSet visit)
T2 _find0 ()
void _find_fidxs ()
T2 _find_nil ()
T2 _fresh (VStack nongen)
boolean _fresh_unify (T2 that, VStack nongen, Worklist work)
boolean _fresh_unify_struct (T2 that, VStack nongen, Worklist work)
SB _p (SB sb, VBitSet visit, VBitSet dups)
boolean _unify (T2 that, Worklist work)
void _unify_struct (T2 that, Worklist work)
boolean _union (T2 that, Worklist work)
void add_deps_work_impl (Worklist work)
boolean add_fld (String id, T2 fld, Worklist work)
int base_states ()
long dbl_uid (long uid)
long dbl_uid (T2 t)
Type fput (final Type t)
boolean fresh_base (T2 that, Worklist work)
BitsAlias meet_alias (T2 that)
String meet_err (T2 that)
BitsFun meet_fidxs (T2 that)
Type meet_flow (T2 that)
String[] meet_ids (T2 that)
boolean meet_opens (T2 that)
void push_update_impl (Syntax a)
boolean union_err (T2 that, Worklist work, String msg)
boolean vput (T2 that, boolean progress)
Static Private Member Functions
static SB str (SB sb, VBitSet visit, T2 t, VBitSet dups)
Static Private Attributes
static final HashMap< T2, T2 > CDUPS = new HashMap<>()
static int CNT =0
static final HashMap< Long, T2 > DUPS = new HashMap<>()
static final VBitSet FIDX_VISIT = new VBitSet()
static BitsFun FIDXS = null
static final VBitSet ODUPS = new VBitSet()
static final HashMap< T2, T2 > VARS = new HashMap<>()
static int VCNT
static final HashMap< T2, Integer > VNAMES = new HashMap<>()
Detailed Description
Definition at line 1291 of file HM.java.
Constructor & Destructor Documentation
T2() [1/2]
com.cliffc.aa.HM.HM.T2.T2 (@NotNull String name) private
Definition at line 1348 of file HM.java.
 { _uid = CNT++; _name= name; }
References com.cliffc.aa.HM.HM.T2._name, com.cliffc.aa.HM.HM.T2._uid, and com.cliffc.aa.HM.HM.T2.CNT.
Referenced by com.cliffc.aa.HM.HM.T2.copy(), com.cliffc.aa.HM.HM.T2.make_base(), com.cliffc.aa.HM.HM.T2.make_err(), com.cliffc.aa.HM.HM.T2.make_fun(), com.cliffc.aa.HM.HM.T2.make_leaf(), com.cliffc.aa.HM.HM.T2.make_nil(), and com.cliffc.aa.HM.HM.T2.make_struct().
T2() [2/2]
com.cliffc.aa.HM.HM.T2.T2 (@NotNull String name, T2 @NotNull ... args) private
Definition at line 1349 of file HM.java.
{
       this(name);
       _args= args;
     }
References com.cliffc.aa.HM.HM.T2._args, and com.cliffc.aa.HM.HM.T2.args().
Member Function Documentation
_as_flow()
Type com.cliffc.aa.HM.HM.T2._as_flow () package
Definition at line 1434 of file HM.java.
                     {
       assert no_uf();
       if( is_base() ) return _flow;
       if( is_leaf() ) return Type.SCALAR;
       if( is_err()  ) return TypeMemPtr.make(BitsAlias.STRBITS,TypeStr.con(_err));
       if( is_fun()  ) return TypeFunPtr.make(_fidxs,_args.length-1,Type.ANY);
       if( is_nilable() ) return Type.SCALAR;
       if( is_struct() ) {
         TypeStruct tstr = ADUPS.get(_uid);
         if( tstr==null ) {
           Type.RECURSIVE_MEET++;
           TypeFld[] ts = TypeFlds.get(_ids.length+1);
           ts[0] = TypeFld.NO_DISP;
           for( int i=0; i<_ids.length; i++ )
             ts[i+1] = TypeFld.malloc(_ids[i],null,Access.Final,i+1);
           tstr = TypeStruct.malloc("",false,ts,true);
           tstr._hash = tstr.compute_hash();
           ADUPS.put(_uid,tstr); // Stop cycles
           for( int i=0; i<_ids.length; i++ )
             ts[i+1].setX(args(i)._as_flow()); // Recursive
           if( --Type.RECURSIVE_MEET == 0 ) {
             // Shrink / remove cycle dups.  Might make new (smaller)
             // TypeStructs, so keep RECURSIVE_MEET enabled.
             Type.RECURSIVE_MEET++;
             tstr = TypeStruct.shrink(tstr.reachable(),tstr);
             TypeStruct.UF.clear();
             Type.RECURSIVE_MEET--;
             // Walk the final cyclic structure and intern everything.
             tstr.install_cyclic(tstr.reachable());
           }
         } else {
           tstr._cyclic=true;    // Been there, done that, just mark it cyclic
         }
         return TypeMemPtr.make(_alias,tstr);
       }
       throw unimpl();
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.type.TypeStruct._cyclic, com.cliffc.aa.HM.HM.T2._err, com.cliffc.aa.HM.HM.T2._fidxs, com.cliffc.aa.HM.HM.T2._flow, com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.HM.HM.T2._uid, com.cliffc.aa.HM.HM.T2.ADUPS, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.type.TypeStruct.compute_hash(), com.cliffc.aa.type.TypeStr.con(), com.cliffc.aa.type.TypeFld.Access.Final, com.cliffc.aa.type.TypeFlds.get(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.get(), com.cliffc.aa.type.TypeStruct.install_cyclic(), com.cliffc.aa.HM.HM.T2.is_base(), com.cliffc.aa.HM.HM.T2.is_err(), com.cliffc.aa.HM.HM.T2.is_fun(), com.cliffc.aa.HM.HM.T2.is_leaf(), com.cliffc.aa.HM.HM.T2.is_nilable(), com.cliffc.aa.HM.HM.T2.is_struct(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeFunPtr.make(), com.cliffc.aa.type.TypeFld.malloc(), com.cliffc.aa.type.TypeStruct.malloc(), com.cliffc.aa.type.TypeFld.NO_DISP, com.cliffc.aa.HM.HM.T2.no_uf(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.put(), com.cliffc.aa.type.TypeStruct.reachable(), com.cliffc.aa.type.Type< T extends Type< T >.RECURSIVE_MEET, com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, com.cliffc.aa.type.TypeStruct.shrink(), com.cliffc.aa.type.BitsAlias.STRBITS, and com.cliffc.aa.type.TypeStruct.UF.
Referenced by com.cliffc.aa.HM.HM.T2.as_flow().
_can_be_HM_base()
boolean com.cliffc.aa.HM.HM.T2._can_be_HM_base (T2 that, Type that_flow) private
Definition at line 1749 of file HM.java.
{
       if( that.base_states() > 1 ) return false;
       if( _flow==null || that_flow==null ) return true;
       Type wthisflow =     _flow.widen();
       Type wthatflow = that_flow.widen();
       if( wthisflow==wthatflow ) return true;
       return wthisflow.isa(wthatflow);
     }
References com.cliffc.aa.HM.HM.T2._flow, com.cliffc.aa.HM.HM.T2.base_states(), com.cliffc.aa.type.Type< T extends Type< T >.isa(), and com.cliffc.aa.type.Type< T extends Type< T >.widen().
Referenced by com.cliffc.aa.HM.HM.T2.fresh_base().
_cycle_equals()
boolean com.cliffc.aa.HM.HM.T2._cycle_equals (T2 t) package
Definition at line 1968 of file HM.java.
{
       assert no_uf() && t.no_uf();
       if( this==t ) return true;
       if( _flow !=t._flow  ||  // Base-cases have to be completely identical
           _fidxs!=t._fidxs ||
           _alias!=t._alias ||
           !Util.eq(_err,t._err) )
         return false;
       if( !Util.eq(_name,t._name) ) return false; // Wrong type-var names
       if( _args==t._args ) return true;           // Same arrays (generally both null)
       if( _args.length != t._args.length )        // Mismatched sizes
         return false;
       // Cycles stall the equal/unequal decision until we see a difference.
       T2 tc = CDUPS.get(this);
       if( tc!=null )  return tc==t; // Cycle check; true if both cycling the same
       CDUPS.put(this,t);
       if( is_struct() )         // Struct equality honors field names without regard to order
         return _cycle_equals_struct(t);
       for( int i=0; i<_args.length; i++ )
         if( !args(i)._cycle_equals(t.args(i)) )
           return false;
       return true;
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM.T2._err, com.cliffc.aa.HM.HM.T2._fidxs, com.cliffc.aa.HM.HM.T2._flow, com.cliffc.aa.HM.HM.T2._name, com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.HM.HM.T2.CDUPS, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM.T2.is_struct(), and com.cliffc.aa.HM.HM.T2.no_uf().
Referenced by com.cliffc.aa.HM.HM.T2._cycle_equals_struct(), and com.cliffc.aa.HM.HM.T2.cycle_equals().
_cycle_equals_struct()
boolean com.cliffc.aa.HM.HM.T2._cycle_equals_struct (T2 t) private
Definition at line 1992 of file HM.java.
{
       assert is_struct() && t.is_struct();
       for( int i=0; i<_args.length; i++ ) {
         int idx = Util.find(t._ids,_ids[i]);
         if( idx==-1 || !args(i)._cycle_equals(t.args(idx)) )
           return false;
       }
       return true;
     }
References com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._cycle_equals(), com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.util.Util.find(), and com.cliffc.aa.HM.HM.T2.is_struct().
Referenced by com.cliffc.aa.HM.HM.T2._cycle_equals().
_find()
T2 com.cliffc.aa.HM.HM.T2._find (int uid, VBitSet visit) private
Definition at line 2279 of file HM.java.
{
       if( visit.tset(_uid) ) return null;
       if( _uid==uid ) return this;
       if( _args==null ) return null;
       for( T2 arg : _args )
         if( (arg=arg._find(uid,visit)) != null )
           return arg;
       return null;
     }
References com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._uid, and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.HM.HM.T2.find().
_find0()
T2 com.cliffc.aa.HM.HM.T2._find0 () private
Definition at line 1379 of file HM.java.
{
       T2 u = debug_find();
       if( u==this || u==_args[0] ) return u;
       T2 v = this, v2;
       // UF fixup
       while( v.is_leaf() && (v2=v._args[0])!=u ) { v._args[0]=u; v = v2; }
       return u;
     }
References com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2.debug_find(), and com.cliffc.aa.HM.HM.T2.is_leaf().
Referenced by com.cliffc.aa.HM.HM.T2.find().
_find_fidxs()
void com.cliffc.aa.HM.HM.T2._find_fidxs () private
Definition at line 2101 of file HM.java.
{
       if( FIDX_VISIT.tset(_uid) ) return;
       if( is_struct() )
         for( T2 arg : _args )
           arg._find_fidxs();
       if( is_fun() ) {
         FIDXS = FIDXS.meet(_fidxs);
         args(_args.length-1)._find_fidxs();
       }
     }
References com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._fidxs, com.cliffc.aa.HM.HM.T2._find_fidxs(), com.cliffc.aa.HM.HM.T2._uid, com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.HM.HM.T2.FIDX_VISIT, com.cliffc.aa.HM.HM.T2.FIDXS, com.cliffc.aa.HM.HM.T2.is_fun(), com.cliffc.aa.HM.HM.T2.is_struct(), com.cliffc.aa.type.Bits< B extends Bits< B >.meet(), and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.HM.HM.T2._find_fidxs(), and com.cliffc.aa.HM.HM.T2.find_fidxs().
_find_nil()
T2 com.cliffc.aa.HM.HM.T2._find_nil () private
Definition at line 1389 of file HM.java.
{
       T2 n = args(0);
       if( n.is_leaf() ) return this;
       // Nested nilable-and-not-leaf, need to fixup the nilable
       if( n.is_base() ) {
         _flow = n._flow .meet_nil(Type.XNIL);
         _args = null;
         _name = n._name;
       } else if( n.is_struct() ) {
         _alias= n._alias.meet_nil();
         _args = n._args.clone();
         _ids  = n._ids.clone();
         _open = n._open;
         _name = n._name;
       } else if( n.is_nilable() ) {
         _args[0] = n.args(0);
       } else
         throw unimpl();
       if( n._deps!=null ) {
         if( _deps == null ) _deps = n._deps;
         else _deps.addAll(n._deps);
       }
       return this;
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._deps, com.cliffc.aa.HM.HM.T2._flow, com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.HM.HM.T2._name, com.cliffc.aa.HM.HM.T2._open, com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.HM.HM.T2.is_base(), com.cliffc.aa.HM.HM.T2.is_leaf(), com.cliffc.aa.HM.HM.T2.is_nilable(), com.cliffc.aa.HM.HM.T2.is_struct(), com.cliffc.aa.type.Bits< B extends Bits< B >.meet_nil(), com.cliffc.aa.type.Type< T extends Type< T >.meet_nil(), and com.cliffc.aa.type.Type< T extends Type< T >.XNIL.
Referenced by com.cliffc.aa.HM.HM.T2.find().
_fresh()
T2 com.cliffc.aa.HM.HM.T2._fresh (VStack nongen) private
Definition at line 1904 of file HM.java.
{
       assert no_uf();
       T2 rez = VARS.get(this);
       if( rez!=null ) return rez; // Been there, done that
       // Unlike the original algorithm, to handle cycles here we stop making a
       // copy if it appears at this level in the nongen set.  Otherwise we'd
       // clone it down to the leaves - and keep all the nongen leaves.
       // Stopping here preserves the cyclic structure instead of unrolling it.
       if( nongen_in(nongen) ) {
         VARS.put(this,this);
         return this;
       }
       if( is_leaf() ) {
         // If occurs_in lexical scope, keep same variable, else make a new leaf
         T2 t = T2.make_leaf();
         VARS.put(this,t);
         return t;
       } else {                  // Structure is deep-replicated
         T2 t = copy();
         VARS.put(this,t);       // Stop cyclic structure looping
         if( _args!=null )
           for( int i=0; i<_args.length; i++ )
             t._args[i] = args(i)._fresh(nongen);
         return t;
       }
     }
References com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._fresh(), com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.HM.HM.T2.copy(), com.cliffc.aa.HM.HM.T2.is_leaf(), com.cliffc.aa.HM.HM.T2.make_leaf(), com.cliffc.aa.HM.HM.T2.no_uf(), com.cliffc.aa.HM.HM.T2.nongen_in(), and com.cliffc.aa.HM.HM.T2.VARS.
Referenced by com.cliffc.aa.HM.HM.T2._fresh(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._fresh_unify_struct(), and com.cliffc.aa.HM.HM.T2.fresh().
_fresh_unify()
boolean com.cliffc.aa.HM.HM.T2._fresh_unify (T2 that, VStack nongen, Worklist work) private
Definition at line 1780 of file HM.java.
{
       assert no_uf() && that.no_uf();
       T2 prior = VARS.get(this);
       if( prior!=null )         // Been there, done that
         return prior.find()._unify(that,work);  // Also 'prior' needs unification with 'that'
       if( cycle_equals(that) ) return vput(that,false);
       if( that.is_err() ) return vput(that,false); // That is an error, ignore 'this' and no progress
       if( this.is_err() ) return vput(that,_unify(that,work));
       // In the non-generative set, so do a hard unify, not a fresh-unify.
       if( nongen_in(nongen) ) return vput(that,_unify(that,work)); // Famous 'occurs-check', switch to normal unify
       // LHS is a leaf, base, or error
       if( this._args==null ) return vput(that,fresh_base(that,work));
       if( that.is_leaf() )  // RHS is a tvar; union with a deep copy of LHS
         return work==null || vput(that,that.union(_fresh(nongen),work));
       // Special handling for nilable
       if( this.is_nilable() && !that.is_nilable() ) {
         if( that.is_base() ) {
           Type mt = that._flow.meet_nil(Type.XNIL);
           if( mt==that._flow ) return false; // Nilable already
           if( work!=null ) that._flow = mt;
           return true;
         }
         if( that.is_struct() ) {
           if( that._alias.test(0) ) return false; // Nilable already
           throw unimpl();
         }
         throw unimpl();
       }
       // That is nilable and this is not
       if( that.is_nilable() && !this.is_nilable() ) {
         if( this.is_struct() ) {
           // fresh_unify a not-nil version of this with the not-nil version of that
           T2 copy = this;
           if( copy._alias.test(0) ) { // make a not=nil version of struct
             copy = this.copy();
             copy._alias = copy._alias.clear(0);
             System.arraycopy(this._args,0,copy._args,0,this._args.length);
           }
           boolean progress = copy._fresh_unify(that.args(0),nongen,work);
           return _alias.test(0) ? vput(that,progress) : progress;
         }
         throw unimpl();
       }
       if( !Util.eq(_name,that._name) ||
           (!is_struct() && _args.length != that._args.length) )
         return work == null || vput(that,that._unify(make_err("Cannot unify "+this.p()+" and "+that.p()),work));
       // Structural recursion unification, lazy on LHS
       vput(that,false); // Early set, to stop cycles
       boolean progress = false;
       if( is_struct() )
         progress = _fresh_unify_struct(that,nongen,work);
       else {
         for( int i=0; i<_args.length; i++ ) {
           progress |= args(i)._fresh_unify(that.args(i),nongen,work);
           if( progress && work==null ) return true;
           if( (that=that.find()).is_err() ) return true;
         }
         if( is_fun() ) {
           BitsFun fidxs = meet_fidxs(that);
           if( fidxs!=that._fidxs ) progress=true;
           if( progress && work==null ) return true;
           that._fidxs = fidxs;
         }
       }
       return progress;
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._fidxs, com.cliffc.aa.HM.HM.T2._flow, com.cliffc.aa.HM.HM.T2._fresh(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM.T2._name, com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.type.Bits< B extends Bits< B >.clear(), com.cliffc.aa.HM.HM.T2.copy(), com.cliffc.aa.HM.HM.T2.cycle_equals(), com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM.T2.find(), com.cliffc.aa.HM.HM.T2.fresh_base(), com.cliffc.aa.HM.HM.T2.is_base(), com.cliffc.aa.HM.HM.T2.is_err(), com.cliffc.aa.HM.HM.T2.is_fun(), com.cliffc.aa.HM.HM.T2.is_leaf(), com.cliffc.aa.HM.HM.T2.is_nilable(), com.cliffc.aa.HM.HM.T2.is_struct(), com.cliffc.aa.HM.HM.T2.make_err(), com.cliffc.aa.HM.HM.T2.meet_fidxs(), com.cliffc.aa.type.Type< T extends Type< T >.meet_nil(), com.cliffc.aa.HM.HM.T2.no_uf(), com.cliffc.aa.HM.HM.T2.nongen_in(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.Bits< B extends Bits< B >.test(), com.cliffc.aa.HM.HM.T2.union(), com.cliffc.aa.HM.HM.T2.VARS, com.cliffc.aa.HM.HM.T2.vput(), and com.cliffc.aa.type.Type< T extends Type< T >.XNIL.
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._fresh_unify_struct(), and com.cliffc.aa.HM.HM.T2.fresh_unify().
_fresh_unify_struct()
boolean com.cliffc.aa.HM.HM.T2._fresh_unify_struct (T2 that, VStack nongen, Worklist work) private
Definition at line 1855 of file HM.java.
{
       assert is_struct() && that.is_struct();
       boolean progress = false;
       // Unification for structs is more complicated; args are aligned via
       // field names and not by position.  Conceptually, fields in one struct
       // and not the other are put in both before unifying the structs.  Open
       // structs copy from the other side; closed structs insert a missing
       // field error.
       for( int i=0; i<_ids.length; i++ ) {
         int idx = Util.find(that._ids,_ids[i]);
         if( idx == -1 ) {       // Missing field on RHS
           if( work==null ) return true; // Will definitely make progress
           progress = true;
           // if both are closed, error on RHS
           that.add_fld(_ids[i], that._open ? args(i)._fresh(nongen) : that.miss_field(_ids[i]),  work);
         } else
           progress |= args(i)._fresh_unify(that.args(idx),nongen,work);
         if( (that=that.find()).is_err() ) return true;
         if( progress && work==null ) return true;
       }
       // Fields in RHS and not the LHS are also merged; if the LHS is open we'd
       // just copy the missing fields into it, then unify the structs
       // (shortcut: just skip the copy).  If the LHS is closed, then the extra
       // RHS fields are an error.
       if( !_open )
         for( int i=0; i<that._ids.length; i++ )    // For all fields in RHS
           if( Util.find(_ids,that._ids[i]) == -1 &&// Missing in LHS
               !that.args(i).is_err() ) {           // And not yet an error
             if( work == null ) return true; // Will definitely make progress
             progress |= that.args(i).unify(miss_field(that._ids[i]), work);
           }
       // Unify aliases
       BitsAlias alias = meet_alias(that);
       if( alias!=that._alias ) progress=true;
       if( progress && work==null ) return true;
       that._alias = alias;
       return progress;
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.T2._fresh(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.HM.HM.T2._open, com.cliffc.aa.HM.HM.T2.add_fld(), com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM.T2.find(), com.cliffc.aa.HM.HM.T2.is_err(), com.cliffc.aa.HM.HM.T2.is_struct(), com.cliffc.aa.HM.HM.T2.meet_alias(), com.cliffc.aa.HM.HM.T2.miss_field(), and com.cliffc.aa.HM.HM.T2.unify().
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify().
_get_dups()
VBitSet com.cliffc.aa.HM.HM.T2._get_dups (VBitSet visit, VBitSet dups) package
Definition at line 2149 of file HM.java.
{
       if( visit.tset(_uid) ) {
         dups.set(debug_find()._uid);
       } else
         if( _args!=null )
           for( T2 t : _args )
             if( t!=null )
               t._get_dups(visit,dups);
       return dups;
     }
References com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._uid, com.cliffc.aa.HM.HM.T2.debug_find(), and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.HM.HM.T2.get_dups().
_occurs_in_type()
boolean com.cliffc.aa.HM.HM.T2._occurs_in_type (T2 x) package
Definition at line 1934 of file HM.java.
{
       assert no_uf() && x.no_uf();
       if( x==this ) return true;
       if( ODUPS.tset(x._uid) ) return false; // Been there, done that
       if( !x.is_leaf() && x._args!=null )
         for( int i=0; i<x._args.length; i++ )
           if( _occurs_in_type(x.args(i)) )
             return true;
       return false;
     }
References com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._uid, com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.HM.HM.T2.is_leaf(), com.cliffc.aa.HM.HM.T2.no_uf(), com.cliffc.aa.HM.HM.T2.ODUPS, and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.HM.HM.T2.nongen_in(), and com.cliffc.aa.HM.HM.T2.occurs_in_type().
_p()
SB com.cliffc.aa.HM.HM.T2._p (SB sb, VBitSet visit, VBitSet dups) private
Definition at line 2209 of file HM.java.
{
       assert no_uf();
       if( is_base() ) return sb.p(_flow); // One-shot bases just do type
       if( is_leaf() || dups.get(_uid) ) { // Leafs or Duplicates?  Take some effort to pretty-print cycles
         Integer ii = VNAMES.get(this);
         if( ii==null )  VNAMES.put(this,ii=VCNT++); // Type-var name
         // 2nd and later visits use the short form
         boolean later = visit.tset(_uid);
         // Removed as being more confusing to more academic readers
         //if( later ) sb.p('$');
         char c = (char)('A'+ii);
         if( c<'V' ) sb.p(c); else sb.p("V"+ii);
         if( later ) return sb;
         if( is_leaf() ) return sb;
         sb.p(':'); // Dups now print their structure
       }
       if( is_err () ) return sb.p(_err);
       // Special printing for functions: { arg -> body }
       if( is_fun() ) {
         sb.p("{ ");
         for( int i=0; i<_args.length-1; i++ )
           args(i)._p(sb,visit,dups).p(" ");
         return args(_args.length-1)._p(sb.p("-> "),visit,dups).p(" }");
       }
       // Special printing for structures: @{ fld0 = body, fld1 = body, ... }
       if( is_struct() ) {
         if( is_tuple() ) {
           if( _ids.length == 0 ) return sb.p("()");
           sb.p('(');
           for( int i=0; i<_ids.length; i++ ) {
             int idx = Util.find(_ids,new String(new char[]{(char)('0'+i)}).intern());
             args(idx)._p(sb.p(' '),visit,dups).p(',');
           }
           sb.unchar().p(')');
         } else {
           sb.p("@{");
           TreeMap<String,Integer> map = new TreeMap<>();
           for( int i=0; i<_ids.length; i++ )
             map.put( _ids[i], i );
           for( int i : map.values() )
             args(i)._p(sb.p(' ').p(_ids[i]).p(" = "),visit,dups).p(',');
           sb.unchar().p("}");
         }
         //return _alias.str(sb);
         if( _alias.test(0) ) sb.p('?');
         return sb;
       }
       if( is_nilable() )
         return args(0)._p(sb,visit,dups).p('?');
       // Generic structural T2: (fun arg0 arg1...)
       sb.p("(").p(_name).p(" ");
       for( int i=0; i<_args.length; i++ ) args(i)._p(sb,visit,dups).p(" ");
       return sb.unchar().p(")");
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._err, com.cliffc.aa.HM.HM.T2._flow, com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.HM.HM.T2._name, com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2._uid, com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM.T2.is_base(), com.cliffc.aa.HM.HM.T2.is_err(), com.cliffc.aa.HM.HM.T2.is_fun(), com.cliffc.aa.HM.HM.T2.is_leaf(), com.cliffc.aa.HM.HM.T2.is_nilable(), com.cliffc.aa.HM.HM.T2.is_struct(), com.cliffc.aa.HM.HM.T2.is_tuple(), com.cliffc.aa.HM.HM.T2.no_uf(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.Bits< B extends Bits< B >.test(), com.cliffc.aa.util.VBitSet.tset(), com.cliffc.aa.util.SB.unchar(), com.cliffc.aa.HM.HM.T2.VCNT, and com.cliffc.aa.HM.HM.T2.VNAMES.
Referenced by com.cliffc.aa.HM.HM.T2._p(), and com.cliffc.aa.HM.HM.T2.p().
_unify()
boolean com.cliffc.aa.HM.HM.T2._unify (T2 that, Worklist work) private
Definition at line 1615 of file HM.java.
{
       assert no_uf() && that.no_uf();
       if( this==that ) return false;
       // All leaf types immediately unify.
       if( this._args==null && that._args==null ) {
         T2 lhs=this, rhs=that;
         if( is_err() ||         // Errors beat all others
             (!that.is_err() && is_base()) )
           { rhs=this; lhs=that; } // Base beats plain leaf
         // If tied, keep lower uid
         if( Util.eq(lhs._name,rhs._name) && _uid<that._uid ) { rhs=this; lhs=that; }
         return lhs.union(rhs,work);
       }
       // Any leaf immediately unifies with any non-leaf
       if( this.is_leaf() || that.is_err() ) return this.union(that,work);
       if( that.is_leaf() || this.is_err() ) return that.union(this,work);
       // Special case for nilable union something
       if( this.is_nilable() && !that.is_nilable() ) return this.unify_nil(that,work);
       if( that.is_nilable() && !this.is_nilable() ) return that.unify_nil(this,work);
       // Cycle check
       long luid = dbl_uid(that);    // long-unique-id formed from this and that
       T2 rez = DUPS.get(luid);
       assert rez==null || rez==that;
       if( rez!=null ) return false; // Been there, done that
       DUPS.put(luid,that);          // Close cycles
       if( work==null ) return true; // Here we definitely make progress; bail out early if just testing
       if( !Util.eq(_name,that._name) )
         return union_err(that,work,"Cannot unify "+this.p()+" and "+that.p());
       assert _args!=that._args; // Not expecting to share _args and not 'this'
       // Structural recursion unification.
       // Structs unify only on matching fields, and add missing fields.
       if( is_struct() ) {
         _unify_struct(that,work);
         that = that.find();
       } else {                                // Normal structural unification
         for( int i=0; i<_args.length; i++ ) { // For all fields in LHS
           args(i)._unify(that.args(i),work);
           if( (that=that.find()).is_err() ) break;
         }
       }
       if( find().is_err() && !that.is_err() )
         // TODO: Find a more elegant way to preserve errors
         return that.union(find(),work); // Preserve errors
       return find().union(that,work);
     }
References com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._name, com.cliffc.aa.HM.HM.T2._uid, com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2._unify_struct(), com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.HM.HM.T2.dbl_uid(), com.cliffc.aa.HM.HM.T2.DUPS, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM.T2.find(), com.cliffc.aa.HM.HM.T2.is_base(), com.cliffc.aa.HM.HM.T2.is_err(), com.cliffc.aa.HM.HM.T2.is_leaf(), com.cliffc.aa.HM.HM.T2.is_nilable(), com.cliffc.aa.HM.HM.T2.is_struct(), com.cliffc.aa.HM.HM.T2.no_uf(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.HM.HM.T2.unify_nil(), com.cliffc.aa.HM.HM.T2.union(), and com.cliffc.aa.HM.HM.T2.union_err().
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2._unify_struct(), and com.cliffc.aa.HM.HM.T2.unify().
_unify_struct()
void com.cliffc.aa.HM.HM.T2._unify_struct (T2 that, Worklist work) private
Definition at line 1667 of file HM.java.
{
       assert this.is_struct() && that.is_struct();
       T2 thsi = this;
       // Unification for structs is more complicated; args are aligned via
       // field names and not by position.  Conceptually, fields in one struct
       // and not the other are put in both before unifying the structs.  Open
       // structs copy from the other side; closed structs insert a missing
       // field error.
       for( int i=0; i<thsi._ids.length; i++ ) { // For all fields in LHS
         int idx = Util.find(that._ids,thsi._ids[i]);
         if( idx==-1 )           // Missing that field?  Copy from left if open, error if closed.
           that.add_fld(thsi._ids[i], that._open ? thsi.args(i) : that.miss_field(thsi._ids[i]),  work);
         else thsi.args(i)._unify(that.args(idx),work);    // Unify matching field
         if( (that=that.find()).is_err() ) return; // Recursively, might have already rolled this up
         thsi = thsi.find();  assert thsi.is_struct();
       }
       // Fields in RHS and not the LHS are also merged; if the LHS is open we'd
       // just copy the missing fields into it, then unify the structs
       // (shortcut: just skip the copy).  If the LHS is closed, then the extra
       // RHS fields are an error.
       if( !thsi._open )         // LHS is closed, so extras in RHS are errors
         for( int i=0; i<that._ids.length; i++ )    // For all fields in RHS
           if( Util.find(thsi._ids,that._ids[i]) == -1 ) // Missing in LHS
             that.args(i)._unify(miss_field(that._ids[i]),work); // If closed, extra field is an error
       // Shortcut (for asserts): LHS gets same ids as RHS, since its about to be top-level unified
       thsi._ids = that._ids;
       thsi._open= that._open;
     }
References com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.HM.HM.T2._open, com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2.add_fld(), com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM.T2.find(), com.cliffc.aa.HM.HM.T2.is_struct(), and com.cliffc.aa.HM.HM.T2.miss_field().
Referenced by com.cliffc.aa.HM.HM.T2._unify().
_union()
boolean com.cliffc.aa.HM.HM.T2._union (T2 that, Worklist work) private
Definition at line 1578 of file HM.java.
{
       assert that.no_uf();
       _flow=null;  _fidxs=null;  _alias=null; _ids=null; _err=null; // Kill the base types in a unified type
       // Worklist: put updates on the worklist for revisiting
       if( _deps != null ) {
         work.addAll(_deps); // Re-Apply
         // Merge update lists, for future unions
         if( that._deps==null && that._args==null ) that._deps = _deps;
         else for( Syntax dep : _deps ) that.push_update(dep);
         _deps = null;
       }
       if( _args==null || _args.length!=1 ) _args = new T2[1];
       // Unify the two base types, preserving errors
       _args[0] = that;         // U-F update
       _name = "X"+_uid; // Flag as a leaf & unified
       assert !no_uf();
       return true;
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._deps, com.cliffc.aa.HM.HM.T2._err, com.cliffc.aa.HM.HM.T2._fidxs, com.cliffc.aa.HM.HM.T2._flow, com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.HM.HM.T2._name, com.cliffc.aa.HM.HM.T2._uid, com.cliffc.aa.HM.HM.Worklist.addAll(), com.cliffc.aa.HM.HM.T2.no_uf(), and com.cliffc.aa.HM.HM.T2.push_update().
Referenced by com.cliffc.aa.HM.HM.T2.unify_nil(), and com.cliffc.aa.HM.HM.T2.union().
add_deps_work()
void com.cliffc.aa.HM.HM.T2.add_deps_work (Worklist work) package
Definition at line 2132 of file HM.java.
 { assert UPDATE_VISIT.isEmpty(); add_deps_work_impl(work); UPDATE_VISIT.clear(); }
References com.cliffc.aa.HM.HM.T2.add_deps_work_impl(), and com.cliffc.aa.HM.HM.T2.UPDATE_VISIT.
Referenced by com.cliffc.aa.HM.HM.Ident.add_hm_work(), and com.cliffc.aa.HM.HM.T2.fresh_base().
add_deps_work_impl()
void com.cliffc.aa.HM.HM.T2.add_deps_work_impl (Worklist work) private
Definition at line 2133 of file HM.java.
{
       if( is_leaf() ) {
         work.addAll(_deps);
       } else {
         if( UPDATE_VISIT.tset(_uid) ) return;
         if( _args != null )
           for( int i=0; i<_args.length; i++ )
             args(i).add_deps_work_impl(work);
       }
     }
References com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._deps, com.cliffc.aa.HM.HM.T2._uid, com.cliffc.aa.HM.HM.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM.Worklist.addAll(), com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.HM.HM.T2.is_leaf(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.HM.HM.T2.UPDATE_VISIT.
Referenced by com.cliffc.aa.HM.HM.T2.add_deps_work(), and com.cliffc.aa.HM.HM.T2.add_deps_work_impl().
add_fld()
boolean com.cliffc.aa.HM.HM.T2.add_fld (String id, T2 fld, Worklist work) private
Definition at line 1697 of file HM.java.
{
       assert is_struct();
       int len = _ids.length;
       // Find insertion point
       int idx = Arrays.binarySearch(_ids,id);
       assert idx<0;             // Never found
       idx = -idx-1;               // Insertion point
       // Insert in sorted order
       _ids  = Arrays.copyOf( _ids,len+1);
       _args = Arrays.copyOf(_args,len+1);
       System.arraycopy( _ids,idx, _ids,idx+1,len-idx);
       System.arraycopy(_args,idx,_args,idx+1,len-idx);
       _ids [idx] = id ;
       _args[idx] = fld;
       fld.push_update(_deps); // If field changes, all deps change
       work.addAll(_deps); //
       return true;        // Always progress
     }
References com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._deps, com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.HM.HM.Worklist.addAll(), com.cliffc.aa.HM.HM.id(), com.cliffc.aa.HM.HM.T2.is_struct(), and com.cliffc.aa.HM.HM.T2.push_update().
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM.T2._unify_struct(), and com.cliffc.aa.HM.HM.Field.hm().
args()
T2 com.cliffc.aa.HM.HM.T2.args (int i) package
Definition at line 1415 of file HM.java.
                    {
       T2 u = _args[i];
       T2 uu = u.find();
       return u==uu ? uu : (_args[i]=uu);
     }
References com.cliffc.aa.HM.HM.T2._args, and com.cliffc.aa.HM.HM.T2.find().
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2._cycle_equals(), com.cliffc.aa.HM.HM.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM.T2._find_fidxs(), com.cliffc.aa.HM.HM.T2._find_nil(), com.cliffc.aa.HM.HM.T2._fresh(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM.T2._occurs_in_type(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2._unify_struct(), com.cliffc.aa.HM.HM.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM.Lambda.hm(), com.cliffc.aa.HM.HM.Apply.hm(), com.cliffc.aa.HM.HM.Struct.hm(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.If.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.T2.make_fun(), com.cliffc.aa.HM.HM.NotNil.prep_tree(), com.cliffc.aa.HM.HM.PrimSyn.PrimSyn(), com.cliffc.aa.HM.HM.T2.push_update_impl(), com.cliffc.aa.HM.HM.T2.T2(), com.cliffc.aa.HM.HM.T2.unify_nil(), com.cliffc.aa.HM.HM.T2.walk_types_in(), and com.cliffc.aa.HM.HM.T2.walk_types_out().
as_flow()
Type com.cliffc.aa.HM.HM.T2.as_flow () package
Definition at line 1427 of file HM.java.
                    {
       assert ADUPS.isEmpty();
       Type t = _as_flow();
       ADUPS.clear();
       assert Type.intern_check();
       return t;
     }
References com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2.ADUPS, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.clear(), and com.cliffc.aa.type.Type< T extends Type< T >.intern_check().
Referenced by com.cliffc.aa.HM.HM.T2.walk_types_in(), and com.cliffc.aa.HM.HM.Root.widen().
base_states()
int com.cliffc.aa.HM.HM.T2.base_states () private
Definition at line 1515 of file HM.java.
{
       int cnt=0;
       if( _flow !=null ) cnt++;
       if( _fidxs!=null ) cnt++;
       if( _err  !=null ) cnt++;
       if( _alias!=null ) { cnt++; assert _ids!=null; }
       else assert _ids==null;
       return cnt;
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.T2._err, com.cliffc.aa.HM.HM.T2._fidxs, com.cliffc.aa.HM.HM.T2._flow, and com.cliffc.aa.HM.HM.T2._ids.
Referenced by com.cliffc.aa.HM.HM.T2._can_be_HM_base(), com.cliffc.aa.HM.HM.T2.fresh_base(), and com.cliffc.aa.HM.HM.T2.union().
copy()
T2 com.cliffc.aa.HM.HM.T2.copy () package
Definition at line 1335 of file HM.java.
               {
       T2 t = new T2(_name);
       if( _args!=null ) t._args = new T2[_args.length];
       t._flow  = _flow;
       t._fidxs = _fidxs;
       t._alias = _alias;
       t._ids   = _ids;
       t._err   = _err;
       t._deps  = _deps;
       t._open  = _open;
       return t;
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._deps, com.cliffc.aa.HM.HM.T2._err, com.cliffc.aa.HM.HM.T2._fidxs, com.cliffc.aa.HM.HM.T2._flow, com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.HM.HM.T2._name, com.cliffc.aa.HM.HM.T2._open, and com.cliffc.aa.HM.HM.T2.T2().
Referenced by com.cliffc.aa.HM.HM.T2._fresh(), com.cliffc.aa.HM.HM.T2._fresh_unify(), and com.cliffc.aa.HM.HM.T2.unify_nil().
cycle_equals()
boolean com.cliffc.aa.HM.HM.T2.cycle_equals (T2 t) package
Definition at line 1962 of file HM.java.
{
       assert CDUPS.isEmpty();
       boolean rez = _cycle_equals(t);
       CDUPS.clear();
       return rez;
     }
References com.cliffc.aa.HM.HM.T2._cycle_equals(), and com.cliffc.aa.HM.HM.T2.CDUPS.
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify().
dbl_uid() [1/2]
long com.cliffc.aa.HM.HM.T2.dbl_uid (long uid) private
Definition at line 1717 of file HM.java.
 { return ((long)_uid<<32)|uid; }
References com.cliffc.aa.HM.HM.T2._uid.
dbl_uid() [2/2]
long com.cliffc.aa.HM.HM.T2.dbl_uid (T2 t) private
Definition at line 1716 of file HM.java.
 { return dbl_uid(t._uid); }
References com.cliffc.aa.HM.HM.T2._uid, and com.cliffc.aa.HM.HM.T2.dbl_uid().
Referenced by com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2.dbl_uid(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
debug_find()
T2 com.cliffc.aa.HM.HM.T2.debug_find () package
Definition at line 1364 of file HM.java.
                     {// Find, without the roll-up
       if( !is_leaf() ) return this; // Shortcut
       if( _args==null ) return this;
       T2 u = _args[0];
       if( u.no_uf() ) return u;  // Shortcut
       // U-F search, no fixup
       while( u.is_leaf() && !u.no_uf() ) u = u._args[0];
       return u;
     }
References com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2.is_leaf(), and com.cliffc.aa.HM.HM.T2.no_uf().
Referenced by com.cliffc.aa.HM.HM.T2._find0(), com.cliffc.aa.HM.HM.T2._get_dups(), and com.cliffc.aa.HM.HM.Syntax.debug_find().
find() [1/2]
T2 com.cliffc.aa.HM.HM.T2.find () package
Definition at line 1374 of file HM.java.
               {
       T2 u = _find0();
       return u.is_nilable() ? u._find_nil() : u;
     }
References com.cliffc.aa.HM.HM.T2._find0(), com.cliffc.aa.HM.HM.T2._find_nil(), and com.cliffc.aa.HM.HM.T2.is_nilable().
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2._unify_struct(), com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.HM.HM.Syntax.find(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.Apply.hm(), com.cliffc.aa.HM.HM.If.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.Ident.idt(), com.cliffc.aa.HM.HM.VStack.nongen(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.HM.HM.Lambda.targ(), and com.cliffc.aa.HM.HM.T2.unify_nil().
find() [2/2]
T2 com.cliffc.aa.HM.HM.T2.find (int uid) package
Definition at line 2278 of file HM.java.
 { return _find(uid,new VBitSet()); }
References com.cliffc.aa.HM.HM.T2._find().
find_fidxs()
BitsFun com.cliffc.aa.HM.HM.T2.find_fidxs () package
Definition at line 2100 of file HM.java.
 {  FIDX_VISIT.clear(); FIDXS = BitsFun.EMPTY; _find_fidxs(); return FIDXS; }
References com.cliffc.aa.HM.HM.T2._find_fidxs(), com.cliffc.aa.type.BitsFun.EMPTY, com.cliffc.aa.HM.HM.T2.FIDX_VISIT, and com.cliffc.aa.HM.HM.T2.FIDXS.
Referenced by com.cliffc.aa.HM.HM.Root.val().
fput()
Type com.cliffc.aa.HM.HM.T2.fput (final Type t) private
Definition at line 2056 of file HM.java.
{
       Apply.T2MAP.merge(this, t, Type::meet);
       return t;
     }
References com.cliffc.aa.type.Type< T extends Type< T >.meet(), and com.cliffc.aa.HM.HM.Apply.T2MAP.
Referenced by com.cliffc.aa.HM.HM.T2.walk_types_in().
fresh()
T2 com.cliffc.aa.HM.HM.T2.fresh () package
Definition at line 1898 of file HM.java.
                {
       assert VARS.isEmpty();
       T2 rez = _fresh(null);
       VARS.clear();
       return rez;
     }
References com.cliffc.aa.HM.HM.T2._fresh(), and com.cliffc.aa.HM.HM.T2.VARS.
Referenced by com.cliffc.aa.HM.HM.PrimSyn.PrimSyn().
fresh_base()
boolean com.cliffc.aa.HM.HM.T2.fresh_base (T2 that, Worklist work) private
Definition at line 1719 of file HM.java.
{
       assert base_states()<=1 && that.base_states()<=1;
       boolean progress=false;
       Type      flow  = meet_flow (that);  progress |= flow  != that._flow ;
       BitsFun   fidxs = meet_fidxs(that);  progress |= fidxs != that._fidxs;
       BitsAlias alias = meet_alias(that);  progress |= alias != that._alias;
       String[]  ids   = meet_ids  (that);  progress |= ids   != that._ids;
       boolean   open  = meet_opens(that);  progress |= open  != that._open;
       String    err   = meet_err  (that);  progress |= !Util.eq(err,that._err);
       if( !progress ) return false;
       if( work==null ) return true;
       // Progress
       Type that_flow = that._flow;
       that._flow  = flow ;
       that._fidxs = fidxs;
       that._alias = alias;
       that._ids   = ids;
       that._open  = open;
       that._err   = err;
       if( !_can_be_HM_base(that,that_flow) ) {
         that._flow = that_flow; // Unwind for error message
         String msg = "Cannot unify "+this.p()+" and "+that.p();
         that._flow=null;  that._fidxs=null;  that._alias=null;  that._ids=null; // Now kill the base types, since in-error
         return that.union(make_err(msg),work);
       }
       assert that.base_states()<=1;
       that.add_deps_work(work);
       if( that.is_leaf() ) that._name = _name; // That is a base/err now
       return true;
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.T2._can_be_HM_base(), com.cliffc.aa.HM.HM.T2._err, com.cliffc.aa.HM.HM.T2._fidxs, com.cliffc.aa.HM.HM.T2._flow, com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.HM.HM.T2._name, com.cliffc.aa.HM.HM.T2._open, com.cliffc.aa.HM.HM.T2.add_deps_work(), com.cliffc.aa.HM.HM.T2.base_states(), com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM.T2.is_leaf(), com.cliffc.aa.HM.HM.T2.make_err(), com.cliffc.aa.HM.HM.T2.meet_alias(), com.cliffc.aa.HM.HM.T2.meet_err(), com.cliffc.aa.HM.HM.T2.meet_fidxs(), com.cliffc.aa.HM.HM.T2.meet_flow(), com.cliffc.aa.HM.HM.T2.meet_ids(), com.cliffc.aa.HM.HM.T2.meet_opens(), com.cliffc.aa.HM.HM.T2.p(), and com.cliffc.aa.HM.HM.T2.union().
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify().
fresh_unify()
boolean com.cliffc.aa.HM.HM.T2.fresh_unify (T2 that, VStack nongen, Worklist work) package
Definition at line 1769 of file HM.java.
{
       assert VARS.isEmpty() && DUPS.isEmpty();
       int old = CNT;
       boolean progress = _fresh_unify(that,nongen,work);
       VARS.clear();  DUPS.clear();
       if( work==null && old!=CNT && DEBUG_LEAKS )
         throw unimpl("busted, made T2s but just testing");
       return progress;
     }
References com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2.CNT, com.cliffc.aa.HM.HM.DEBUG_LEAKS, com.cliffc.aa.HM.HM.T2.DUPS, and com.cliffc.aa.HM.HM.T2.VARS.
Referenced by com.cliffc.aa.HM.HM.Ident.hm().
get_dups()
VBitSet com.cliffc.aa.HM.HM.T2.get_dups (VBitSet dups) package
Definition at line 2148 of file HM.java.
 { return _get_dups(new VBitSet(),dups); }
References com.cliffc.aa.HM.HM.T2._get_dups().
Referenced by com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.HM.HM.Syntax.p0(), and com.cliffc.aa.HM.HM.T2.toString().
is_base()
boolean com.cliffc.aa.HM.HM.T2.is_base () package
Definition at line 1358 of file HM.java.
 { return isa("Base"); }
References com.cliffc.aa.HM.HM.T2.isa().
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2._find_nil(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.T2.str(), com.cliffc.aa.HM.HM.T2.unify_nil(), com.cliffc.aa.HM.HM.T2.walk_types_in(), and com.cliffc.aa.HM.HM.T2.walk_types_out().
is_err()
boolean com.cliffc.aa.HM.HM.T2.is_err () package
Definition at line 1362 of file HM.java.
 { return isa("Err"); }
References com.cliffc.aa.HM.HM.T2.isa().
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.Lambda.hm(), com.cliffc.aa.HM.HM.Apply.hm(), com.cliffc.aa.HM.HM.Struct.hm(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.PrimSyn.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.T2.str(), com.cliffc.aa.HM.HM.T2.walk_types_in(), and com.cliffc.aa.HM.HM.T2.walk_types_out().
is_fun()
boolean com.cliffc.aa.HM.HM.T2.is_fun () package
Definition at line 1360 of file HM.java.
 { return isa("->"); }
References com.cliffc.aa.HM.HM.T2.isa().
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2._find_fidxs(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.Lambda.hm(), com.cliffc.aa.HM.HM.Apply.hm(), com.cliffc.aa.HM.HM.PrimSyn.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.T2.str(), com.cliffc.aa.HM.HM.T2.walk_types_in(), and com.cliffc.aa.HM.HM.T2.walk_types_out().
is_leaf()
boolean com.cliffc.aa.HM.HM.T2.is_leaf () package
Definition at line 1355 of file HM.java.
 { return _name.charAt(0)=='V' || _name.charAt(0)=='X'; }
References com.cliffc.aa.HM.HM.T2._name.
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2._find0(), com.cliffc.aa.HM.HM.T2._find_nil(), com.cliffc.aa.HM.HM.T2._fresh(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._occurs_in_type(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM.T2.debug_find(), com.cliffc.aa.HM.HM.T2.fresh_base(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.T2.no_uf(), com.cliffc.aa.HM.HM.T2.str(), com.cliffc.aa.HM.HM.T2.unify_nil(), com.cliffc.aa.HM.HM.T2.walk_types_in(), and com.cliffc.aa.HM.HM.T2.walk_types_out().
is_nilable()
boolean com.cliffc.aa.HM.HM.T2.is_nilable () package
Definition at line 1359 of file HM.java.
 { return isa("?"); }
References com.cliffc.aa.HM.HM.T2.isa().
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2._find_nil(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2.find(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.T2.no_uf(), com.cliffc.aa.HM.HM.T2.unify_nil(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
is_struct()
boolean com.cliffc.aa.HM.HM.T2.is_struct () package
Definition at line 1361 of file HM.java.
 { return isa("@{}"); }
References com.cliffc.aa.HM.HM.T2.isa().
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2._cycle_equals(), com.cliffc.aa.HM.HM.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM.T2._find_fidxs(), com.cliffc.aa.HM.HM.T2._find_nil(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2._unify_struct(), com.cliffc.aa.HM.HM.T2.add_fld(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.T2.meet_opens(), com.cliffc.aa.HM.HM.T2.str(), com.cliffc.aa.HM.HM.T2.unify_nil(), com.cliffc.aa.HM.HM.T2.walk_types_in(), and com.cliffc.aa.HM.HM.T2.walk_types_out().
is_tuple()
boolean com.cliffc.aa.HM.HM.T2.is_tuple () package
Definition at line 2269 of file HM.java.
{
       if( _ids==null ) return false;
       for( String id : _ids )
         if( !isDigit((byte) id.charAt(0)) )
           return false;
       return true;
     }
References com.cliffc.aa.HM.HM.T2._ids, and com.cliffc.aa.HM.HM.isDigit().
Referenced by com.cliffc.aa.HM.HM.T2._p().
isa()
boolean com.cliffc.aa.HM.HM.T2.isa (String name) package
Definition at line 1357 of file HM.java.
 { return Util.eq(_name,name); }
References com.cliffc.aa.HM.HM.T2._name, and com.cliffc.aa.util.Util.eq().
Referenced by com.cliffc.aa.HM.HM.T2.is_base(), com.cliffc.aa.HM.HM.T2.is_err(), com.cliffc.aa.HM.HM.T2.is_fun(), com.cliffc.aa.HM.HM.T2.is_nilable(), and com.cliffc.aa.HM.HM.T2.is_struct().
make_base()
static T2 com.cliffc.aa.HM.HM.T2.make_base (Type flow) static package
Definition at line 1323 of file HM.java.
 { T2 base = new T2("Base"); base._flow = flow; return base; }
References com.cliffc.aa.HM.HM.T2._flow, and com.cliffc.aa.HM.HM.T2.T2().
Referenced by com.cliffc.aa.HM.HM.Con.prep_tree(), and com.cliffc.aa.HM.HM.PrimSyn.reset().
make_err()
static T2 com.cliffc.aa.HM.HM.T2.make_err (String s) static package
Definition at line 1333 of file HM.java.
 { T2 terr = new T2("Err"); terr._err = s.intern(); return terr; }
References com.cliffc.aa.HM.HM.T2._err, and com.cliffc.aa.HM.HM.T2.T2().
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2.fresh_base(), com.cliffc.aa.HM.HM.Apply.hm(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.T2.miss_field(), and com.cliffc.aa.HM.HM.T2.union_err().
make_fun()
static T2 com.cliffc.aa.HM.HM.T2.make_fun (BitsFun fidxs, T2... args) static package
Definition at line 1324 of file HM.java.
 { T2 tfun = new T2("->",args); tfun._fidxs = fidxs; return tfun; }
References com.cliffc.aa.HM.HM.T2._fidxs, com.cliffc.aa.HM.HM.T2.args(), and com.cliffc.aa.HM.HM.T2.T2().
Referenced by com.cliffc.aa.HM.HM.Lambda.hm(), com.cliffc.aa.HM.HM.Apply.hm(), com.cliffc.aa.HM.HM.Pair1.Pair1(), and com.cliffc.aa.HM.HM.PrimSyn.PrimSyn().
make_leaf()
static T2 com.cliffc.aa.HM.HM.T2.make_leaf () static package
Definition at line 1321 of file HM.java.
 { return new T2("V"+CNT); }
References com.cliffc.aa.HM.HM.T2.CNT, and com.cliffc.aa.HM.HM.T2.T2().
Referenced by com.cliffc.aa.HM.HM.T2._fresh(), com.cliffc.aa.HM.HM.EQ.EQ(), com.cliffc.aa.HM.HM.If.If(), com.cliffc.aa.HM.HM.Lambda.Lambda(), com.cliffc.aa.HM.HM.Let.Let(), com.cliffc.aa.HM.HM.NotNil.NotNil(), com.cliffc.aa.HM.HM.Pair.Pair(), com.cliffc.aa.HM.HM.Pair1.Pair1(), com.cliffc.aa.HM.HM.Pair1.Pair1X.Pair1X(), com.cliffc.aa.HM.HM.Con.prep_tree(), com.cliffc.aa.HM.HM.Ident.prep_tree(), com.cliffc.aa.HM.HM.Lambda.prep_tree(), com.cliffc.aa.HM.HM.Apply.prep_tree(), com.cliffc.aa.HM.HM.Field.prep_tree(), and com.cliffc.aa.HM.HM.Triple.Triple().
make_nil()
static T2 com.cliffc.aa.HM.HM.T2.make_nil (T2 leaf) static package
Definition at line 1322 of file HM.java.
 { return new T2("?",leaf); }
References com.cliffc.aa.HM.HM.T2.T2().
Referenced by com.cliffc.aa.HM.HM.NotNil.hm(), and com.cliffc.aa.HM.HM.Con.prep_tree().
make_struct() [1/2]
static T2 com.cliffc.aa.HM.HM.T2.make_struct (BitsAlias aliases, String[] ids, T2[] flds) static package
Definition at line 1325 of file HM.java.
 { return make_struct(aliases,ids,flds,false); }
References com.cliffc.aa.HM.HM.T2.make_struct().
Referenced by com.cliffc.aa.HM.HM.Struct.hm(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.T2.make_struct(), com.cliffc.aa.HM.HM.Pair.Pair(), com.cliffc.aa.HM.HM.Pair1.Pair1(), com.cliffc.aa.HM.HM.Pair1.Pair1X.Pair1X(), com.cliffc.aa.HM.HM.Struct.prep_tree(), and com.cliffc.aa.HM.HM.Triple.Triple().
make_struct() [2/2]
static T2 com.cliffc.aa.HM.HM.T2.make_struct (BitsAlias aliases, String[] ids, T2[] flds, boolean open) static package
Definition at line 1326 of file HM.java.
{
       T2 tstr = new T2("@{}",flds);
       tstr._alias=aliases;
       tstr._ids = ids;
       tstr._open= open;
       return tstr;
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.HM.HM.T2._open, and com.cliffc.aa.HM.HM.T2.T2().
meet_alias()
BitsAlias com.cliffc.aa.HM.HM.T2.meet_alias (T2 that) private
Definition at line 1487 of file HM.java.
{
       if( this._alias==null ) return that._alias;
       if( that._alias==null ) return this._alias;
       return _alias.meet(that._alias);
     }
References com.cliffc.aa.HM.HM.T2._alias, and com.cliffc.aa.type.Bits< B extends Bits< B >.meet().
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM.T2.fresh_base(), and com.cliffc.aa.HM.HM.T2.union().
meet_err()
String com.cliffc.aa.HM.HM.T2.meet_err (T2 that) private
Definition at line 1509 of file HM.java.
{
       if( this._err==null ) return that._err;
       if( that._err==null ) return this._err;
       // TODO: Probably gather unrelated strings in a set
       return _uid < that._uid ? _err : that._err;
     }
References com.cliffc.aa.HM.HM.T2._err, and com.cliffc.aa.HM.HM.T2._uid.
Referenced by com.cliffc.aa.HM.HM.T2.fresh_base(), and com.cliffc.aa.HM.HM.T2.union().
meet_fidxs()
BitsFun com.cliffc.aa.HM.HM.T2.meet_fidxs (T2 that) private
Definition at line 1482 of file HM.java.
{
       if( this._fidxs==null ) return that._fidxs;
       if( that._fidxs==null ) return this._fidxs;
       return _fidxs.meet(that._fidxs);
     }
References com.cliffc.aa.HM.HM.T2._fidxs, and com.cliffc.aa.type.Bits< B extends Bits< B >.meet().
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2.fresh_base(), and com.cliffc.aa.HM.HM.T2.union().
meet_flow()
Type com.cliffc.aa.HM.HM.T2.meet_flow (T2 that) private
Definition at line 1477 of file HM.java.
{
       if( this._flow==null ) return that._flow;
       if( that._flow==null ) return this._flow;
       return _flow.meet(that._flow);
     }
References com.cliffc.aa.HM.HM.T2._flow, and com.cliffc.aa.type.Type< T extends Type< T >.meet().
Referenced by com.cliffc.aa.HM.HM.T2.fresh_base(), and com.cliffc.aa.HM.HM.T2.union().
meet_ids()
String [] com.cliffc.aa.HM.HM.T2.meet_ids (T2 that) private
Definition at line 1492 of file HM.java.
{
       String[] ids = that._ids;
       if( _ids==ids ) return ids;
       if( _ids==null ) return ids;
       if( ids==null ) return _ids;
       if( _ids.length!=ids.length ) throw unimpl(); // Handled at a higher level
       for( String id : ids )
         if( Util.find(_ids, id) == -1 )
           throw unimpl();
       return ids;               // Return RHS
     }
References com.cliffc.aa.HM.HM.T2._ids, and com.cliffc.aa.util.Util.find().
Referenced by com.cliffc.aa.HM.HM.T2.fresh_base(), and com.cliffc.aa.HM.HM.T2.union().
meet_opens()
boolean com.cliffc.aa.HM.HM.T2.meet_opens (T2 that) private
Definition at line 1503 of file HM.java.
{
       if( _open==that._open ) return that._open;
       if( !is_struct() ) return that._open;
       if( !that.is_struct() ) return _open;
       throw unimpl();
     }
References com.cliffc.aa.HM.HM.T2._open, and com.cliffc.aa.HM.HM.T2.is_struct().
Referenced by com.cliffc.aa.HM.HM.T2.fresh_base(), and com.cliffc.aa.HM.HM.T2.union().
miss_field()
T2 com.cliffc.aa.HM.HM.T2.miss_field (String id) package
Definition at line 1334 of file HM.java.
 { return make_err("Missing field "+id+" in "+p()); }
References com.cliffc.aa.HM.HM.T2.make_err(), and com.cliffc.aa.HM.HM.T2.p().
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM.T2._unify_struct(), and com.cliffc.aa.HM.HM.Field.hm().
no_uf()
boolean com.cliffc.aa.HM.HM.T2.no_uf () package
Definition at line 1356 of file HM.java.
 { return _name.charAt(0)!='X' && (!is_nilable() || _args[0].is_leaf()); }
References com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._name, com.cliffc.aa.HM.HM.T2.is_leaf(), and com.cliffc.aa.HM.HM.T2.is_nilable().
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2._cycle_equals(), com.cliffc.aa.HM.HM.T2._fresh(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._occurs_in_type(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2._union(), com.cliffc.aa.HM.HM.T2.debug_find(), com.cliffc.aa.HM.HM.T2.push_update_impl(), com.cliffc.aa.HM.HM.T2.str(), com.cliffc.aa.HM.HM.T2.union(), com.cliffc.aa.HM.HM.T2.walk_types_in(), and com.cliffc.aa.HM.HM.T2.walk_types_out().
nongen_in()
boolean com.cliffc.aa.HM.HM.T2.nongen_in (VStack vs) package
Definition at line 1950 of file HM.java.
{
       if( vs==null ) return false;
       ODUPS.clear();
       for( T2 t2 : vs )
         if( _occurs_in_type(t2.find()) )
           return true;
       return false;
     }
References com.cliffc.aa.HM.HM.T2._occurs_in_type(), and com.cliffc.aa.HM.HM.T2.ODUPS.
Referenced by com.cliffc.aa.HM.HM.T2._fresh(), com.cliffc.aa.HM.HM.T2._fresh_unify(), and com.cliffc.aa.HM.HM.Ident.add_hm_work().
occurs_in_type()
boolean com.cliffc.aa.HM.HM.T2.occurs_in_type (T2 x) package
Definition at line 1945 of file HM.java.
{
       ODUPS.clear();
       return _occurs_in_type(x);
     }
References com.cliffc.aa.HM.HM.T2._occurs_in_type(), and com.cliffc.aa.HM.HM.T2.ODUPS.
p() [1/2]
String com.cliffc.aa.HM.HM.T2.p ()
Definition at line 2205 of file HM.java.
 { return p(get_dups(new VBitSet())); }
References com.cliffc.aa.HM.HM.T2.get_dups(), and com.cliffc.aa.HM.HM.T2.p().
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2.fresh_base(), com.cliffc.aa.HM.HM.T2.miss_field(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.HM.TestHM.test05(), com.cliffc.aa.HM.TestHM9.test05(), com.cliffc.aa.HM.TestHM.test06(), com.cliffc.aa.HM.TestHM9.test06(), com.cliffc.aa.HM.TestHM.test14(), com.cliffc.aa.HM.TestHM9.test14(), com.cliffc.aa.HM.TestHM.test18(), com.cliffc.aa.HM.TestHM9.test18(), com.cliffc.aa.HM.TestHM.test20(), com.cliffc.aa.HM.TestHM9.test20(), com.cliffc.aa.HM.TestHM9.test32(), com.cliffc.aa.HM.TestHM.test32(), com.cliffc.aa.HM.TestHM9.test33(), com.cliffc.aa.HM.TestHM.test33(), com.cliffc.aa.HM.TestHM9.test34(), com.cliffc.aa.HM.TestHM.test34(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.HM.TestHM.test36(), com.cliffc.aa.HM.TestHM.test39(), com.cliffc.aa.HM.TestHM9.test39(), com.cliffc.aa.HM.TestHM.test40(), com.cliffc.aa.HM.TestHM9.test40(), com.cliffc.aa.HM.TestHM.test41(), com.cliffc.aa.HM.TestHM9.test41(), com.cliffc.aa.HM.TestHM.test42(), com.cliffc.aa.HM.TestHM9.test42(), com.cliffc.aa.HM.TestHM.test43(), com.cliffc.aa.HM.TestHM9.test43(), com.cliffc.aa.HM.TestHM.test44(), com.cliffc.aa.HM.TestHM9.test44(), com.cliffc.aa.HM.TestHM.test45(), com.cliffc.aa.HM.TestHM9.test45(), com.cliffc.aa.HM.TestHM.test49(), com.cliffc.aa.HM.TestHM9.test49(), com.cliffc.aa.HM.TestHM.test50(), com.cliffc.aa.HM.TestHM9.test50(), com.cliffc.aa.HM.TestHM.test51(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.HM.TestHM.test55(), com.cliffc.aa.HM.TestHM.test56(), com.cliffc.aa.HM.TestHM.test57(), and com.cliffc.aa.HM.HM.T2.union().
p() [2/2]
String com.cliffc.aa.HM.HM.T2.p (VBitSet dups) package
Definition at line 2208 of file HM.java.
 { VCNT=0; VNAMES.clear(); return find()._p(new SB(), new VBitSet(), dups).toString(); }
References com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2.find(), com.cliffc.aa.util.SB.toString(), com.cliffc.aa.HM.HM.T2.VCNT, and com.cliffc.aa.HM.HM.T2.VNAMES.
push_update() [1/2]
T2 com.cliffc.aa.HM.HM.T2.push_update (Ary< Syntax > as) package
Definition at line 2118 of file HM.java.
 { if( as != null ) for( Syntax a : as ) push_update(a);  return this;   }
References com.cliffc.aa.HM.HM.T2.push_update().
Referenced by com.cliffc.aa.HM.HM.T2._union(), com.cliffc.aa.HM.HM.T2.add_fld(), com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM.Struct.hm(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.Lambda.prep_lookup_deps(), com.cliffc.aa.HM.HM.Let.prep_lookup_deps(), com.cliffc.aa.HM.HM.NotNil.prep_tree(), com.cliffc.aa.HM.HM.PrimSyn.PrimSyn(), com.cliffc.aa.HM.HM.T2.push_update(), and com.cliffc.aa.HM.HM.Root.val().
push_update() [2/2]
T2 com.cliffc.aa.HM.HM.T2.push_update (Syntax a) package
Definition at line 2119 of file HM.java.
 { assert UPDATE_VISIT.isEmpty(); push_update_impl(a); UPDATE_VISIT.clear(); return this; }
References com.cliffc.aa.HM.HM.T2.push_update_impl(), and com.cliffc.aa.HM.HM.T2.UPDATE_VISIT.
push_update_impl()
void com.cliffc.aa.HM.HM.T2.push_update_impl (Syntax a) private
Definition at line 2120 of file HM.java.
{
       assert no_uf();
       if( UPDATE_VISIT.tset(_uid) ) return;
       if( _deps==null ) _deps = new Ary<>(Syntax.class);
       if( _deps.find(a)==-1 ) _deps.push(a);
       if( _args!=null )
         for( int i=0; i<_args.length; i++ )
           if( _args[i]!=null )
             args(i).push_update_impl(a);
     }
References com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._deps, com.cliffc.aa.HM.HM.T2._uid, com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.HM.HM.T2.no_uf(), com.cliffc.aa.HM.HM.T2.push_update_impl(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.HM.HM.T2.UPDATE_VISIT.
Referenced by com.cliffc.aa.HM.HM.T2.push_update(), and com.cliffc.aa.HM.HM.T2.push_update_impl().
reset()
static void com.cliffc.aa.HM.HM.T2.reset () static package
Definition at line 2288 of file HM.java.
 { CNT=0; DUPS.clear(); VARS.clear(); ODUPS.clear(); CDUPS.clear(); UPDATE_VISIT.clear(); }
References com.cliffc.aa.HM.HM.T2.CDUPS, com.cliffc.aa.HM.HM.T2.CNT, com.cliffc.aa.HM.HM.T2.DUPS, com.cliffc.aa.HM.HM.T2.ODUPS, com.cliffc.aa.HM.HM.T2.UPDATE_VISIT, and com.cliffc.aa.HM.HM.T2.VARS.
Referenced by com.cliffc.aa.HM.HM.reset().
str() [1/2]
static SB com.cliffc.aa.HM.HM.T2.str (SB sb, VBitSet visit, T2 t, VBitSet dups) static private
Definition at line 2202 of file HM.java.
 { return t==null ? sb.p("_") : t.str(sb,visit,dups); }
References com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM.T2.str().
str() [2/2]
SB com.cliffc.aa.HM.HM.T2.str (SB sb, VBitSet visit, VBitSet dups) package
Definition at line 2163 of file HM.java.
{
       if( is_err () ) return sb.p(_err);
       if( is_base() ) return sb.p(_flow);
       boolean dup = dups.get(_uid);
       if( is_leaf() ) {
         sb.p(_name);
         return no_uf() ? sb : _args[0].str(sb.p(">>"), visit, dups);
       }
       if( dup ) sb.p("$V").p(_uid);
       if( visit.tset(_uid) && dup ) return sb;
       if( dup ) sb.p(':');
       // Special printing for functions
       if( is_fun() ) {
         sb.p("{");
         if( _fidxs==null ) sb.p('_'); else _fidxs.str(sb);
         sb.p(' ');
         for( int i=0; i<_args.length-1; i++ )
           str(sb,visit,_args[i],dups).p(" ");
         return str(sb.p("-> "),visit,_args[_args.length-1],dups).p(" }");
       }
       // Special printing for structures
       if( is_struct() ) {
         sb.p("@{");
         if( _alias==null ) sb.p('_'); else _alias.str(sb);
         sb.p(' ');
         if( _ids==null ) sb.p("_ ");
         else for( int i=0; i<_ids.length; i++ )
                str(sb.p(' ').p(_ids[i]).p(" = "),visit,_args[i],dups).p(',');
         return sb.unchar().p("}");
       }
       // Generic structural T2
       sb.p("(").p(_name).p(" ");
       for( T2 t : _args ) str(sb,visit,t,dups).p(" ");
       return sb.unchar().p(")");
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._err, com.cliffc.aa.HM.HM.T2._fidxs, com.cliffc.aa.HM.HM.T2._flow, com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.HM.HM.T2._name, com.cliffc.aa.HM.HM.T2._uid, com.cliffc.aa.HM.HM.T2.is_base(), com.cliffc.aa.HM.HM.T2.is_err(), com.cliffc.aa.HM.HM.T2.is_fun(), com.cliffc.aa.HM.HM.T2.is_leaf(), com.cliffc.aa.HM.HM.T2.is_struct(), com.cliffc.aa.HM.HM.T2.no_uf(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.Bits< B extends Bits< B >.str(), com.cliffc.aa.HM.HM.T2.str(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.util.SB.unchar().
Referenced by com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.HM.HM.VStack.str(), com.cliffc.aa.HM.HM.T2.str(), and com.cliffc.aa.HM.HM.T2.toString().
toString()
String com.cliffc.aa.HM.HM.T2.toString ()
Definition at line 2162 of file HM.java.
 { return str(new SB(), new VBitSet(), get_dups(new VBitSet()) ).toString(); }
References com.cliffc.aa.HM.HM.T2.get_dups(), com.cliffc.aa.HM.HM.T2.str(), and com.cliffc.aa.util.SB.toString().
unify()
boolean com.cliffc.aa.HM.HM.T2.unify (T2 that, Worklist work) package
Definition at line 1604 of file HM.java.
{
       if( this==that ) return false;
       assert DUPS.isEmpty();
       boolean progress = _unify(that,work);
       DUPS.clear();
       return progress;
     }
References com.cliffc.aa.HM.HM.T2._unify(), and com.cliffc.aa.HM.HM.T2.DUPS.
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.Lambda.hm(), com.cliffc.aa.HM.HM.Apply.hm(), com.cliffc.aa.HM.HM.Root.hm(), com.cliffc.aa.HM.HM.Struct.hm(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.PrimSyn.hm(), com.cliffc.aa.HM.HM.If.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), and com.cliffc.aa.HM.HM.Let.prep_tree().
unify_nil()
boolean com.cliffc.aa.HM.HM.T2.unify_nil (T2 that, Worklist work) package
Definition at line 1559 of file HM.java.
{
       assert is_nilable() && !that.is_nilable();
       if( work==null ) return true; // Will make progress
       // Clone the top-level struct and make this nilable point to the clone;
       // this will collapse into the clone at the next find() call.
       // Unify the nilable leaf into that.
       T2 leaf = args(0);  assert leaf.is_leaf();
       T2 copy = that.copy();
       if( that.is_base() ) {
         copy._flow = copy._flow.join(Type.NSCALR);
       } else if( that.is_struct() ) {
         copy._alias = copy._alias.clear(0);
         System.arraycopy(that._args,0,copy._args,0,that._args.length);
       } else
         throw unimpl();
       return leaf._union(copy,work) | that._union(find(),work);
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._flow, com.cliffc.aa.HM.HM.T2._union(), com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.type.Bits< B extends Bits< B >.clear(), com.cliffc.aa.HM.HM.T2.copy(), com.cliffc.aa.HM.HM.T2.find(), com.cliffc.aa.HM.HM.T2.is_base(), com.cliffc.aa.HM.HM.T2.is_leaf(), com.cliffc.aa.HM.HM.T2.is_nilable(), com.cliffc.aa.HM.HM.T2.is_struct(), com.cliffc.aa.type.Type< T extends Type< T >.join(), and com.cliffc.aa.type.Type< T extends Type< T >.NSCALR.
Referenced by com.cliffc.aa.HM.HM.T2._unify().
union()
boolean com.cliffc.aa.HM.HM.T2.union (T2 that, Worklist work) package
Definition at line 1527 of file HM.java.
{
       assert no_uf() && that.no_uf(); // Cannot union twice
       assert base_states()<=1 && that.base_states()<=1;
       if( this==that ) return false;
       if( work==null ) return true; // Report progress without changing
       // Keep the merge of all base types, revisiting deps if any changes
       if( _flow !=that._flow  ||
           _fidxs!=that._fidxs ||
           _alias!=that._alias ||
           _ids  !=that._ids   ||
           _open !=that._open  ||
           !Util.eq(_err,that._err) )
         work.addAll(that._deps); // Any progress, revisit deps
       // If flow types are not compatible, return an error now
       if( _flow!=null & that._flow!=null && (_flow.widen() != that._flow.widen() && !_flow.isa(that._flow.widen())) )
         return union_err(that,work,"Cannot unify "+this.p()+" and "+that.p());
       that._flow  = meet_flow (that);
       that._fidxs = meet_fidxs(that);
       that._alias = meet_alias(that);
       that._ids   = meet_ids  (that);
       that._open  = meet_opens(that);
       that._err   = meet_err  (that);
       assert that._flow != Type.XNIL;
       if( that._err!=null ) {   // Kill the base types in an error
         that._flow=null;  that._fidxs=null;  that._alias=null;  that._ids=null;
       }
       // Hard union this into that, no more testing.
       return _union(that,work);
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.T2._err, com.cliffc.aa.HM.HM.T2._fidxs, com.cliffc.aa.HM.HM.T2._flow, com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.HM.HM.T2._open, com.cliffc.aa.HM.HM.T2._union(), com.cliffc.aa.HM.HM.T2.base_states(), com.cliffc.aa.util.Util.eq(), com.cliffc.aa.type.Type< T extends Type< T >.isa(), com.cliffc.aa.HM.HM.T2.meet_alias(), com.cliffc.aa.HM.HM.T2.meet_err(), com.cliffc.aa.HM.HM.T2.meet_fidxs(), com.cliffc.aa.HM.HM.T2.meet_flow(), com.cliffc.aa.HM.HM.T2.meet_ids(), com.cliffc.aa.HM.HM.T2.meet_opens(), com.cliffc.aa.HM.HM.T2.no_uf(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.HM.HM.T2.union_err(), com.cliffc.aa.type.Type< T extends Type< T >.widen(), and com.cliffc.aa.type.Type< T extends Type< T >.XNIL.
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2.fresh_base(), and com.cliffc.aa.HM.HM.T2.union_err().
union_err()
boolean com.cliffc.aa.HM.HM.T2.union_err (T2 that, Worklist work, String msg) private
Definition at line 1757 of file HM.java.
{
       that._flow=null;  that._fidxs=null;  that._alias=null;  that._ids=null; // Now kill the base types, since in-error
       union(that,work);
       return that.union(make_err(msg),work);
     }
References com.cliffc.aa.HM.HM.T2._alias, com.cliffc.aa.HM.HM.T2._fidxs, com.cliffc.aa.HM.HM.T2._flow, com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.HM.HM.T2.make_err(), and com.cliffc.aa.HM.HM.T2.union().
Referenced by com.cliffc.aa.HM.HM.T2._unify(), and com.cliffc.aa.HM.HM.T2.union().
vput()
boolean com.cliffc.aa.HM.HM.T2.vput (T2 that, boolean progress) private
Definition at line 1895 of file HM.java.
 { VARS.put(this,that); return progress; }
References com.cliffc.aa.HM.HM.T2.VARS.
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify().
walk_types_in()
Type com.cliffc.aa.HM.HM.T2.walk_types_in (Type t) package
Definition at line 2005 of file HM.java.
{
       long duid = dbl_uid(t._uid);
       if( Apply.WDUPS.putIfAbsent(duid,"")!=null ) return t;
       assert no_uf();
       if( is_err() ) return fput(t); //
       // Base variables (when widened to an HM type) might force a lift.
       if( is_base() ) return fput(_flow.widen().join(t));
       // Free variables keep the input flow type.
       if( is_leaf() ) return fput(t);
       // Nilable
       if( is_nilable() ) {
         fput(t);
         args(0).walk_types_in(t); // TODO: Not sure if i should strip nil or not
         return t;
       }
       if( t==Type.SCALAR || t==Type.NSCALR ) return fput(t); // Will be scalar for all the breakdown types
       if( is_fun() ) {
         if( !(t instanceof TypeFunPtr) ) return t; // Typically, some kind of error situation
         // TODO: PAIR1 should report better
         TypeFunPtr tfp = (TypeFunPtr)t;
         T2 ret = args(_args.length-1);
         if( tfp._fidxs==BitsFun.FULL        ) return ret.walk_types_in(Type. SCALAR);
         if( tfp._fidxs==BitsFun.FULL.dual() ) return ret.walk_types_in(Type.XSCALAR);
         for( int fidx : ((TypeFunPtr)t)._fidxs ) {
           Lambda lambda = Lambda.FUNS.get(fidx);
           Type body = lambda.find().is_err()
             ? Type.SCALAR           // Error, no lift
             : (lambda._body == null // Null only for primitives
                ? lambda.find().args(lambda._targs.length).as_flow() // Get primitive return type
                : lambda._body._flow); // Else use body type
           ret.walk_types_in(body);
         }
         return t;
       }
       if( is_struct() ) {
         fput(t);                // Recursive types need to put themselves first
         if( !(t instanceof TypeMemPtr) )  return t;
         TypeMemPtr tmp = (TypeMemPtr)t;
         if( !(tmp._obj instanceof TypeStruct) ) return t;
         TypeStruct ts = (TypeStruct)tmp._obj;
         for( int i=0; i<_args.length; i++ ) {
           int idx = ts.fld_find(_ids[i]);
           // Missing fields are walked as SCALAR
           args(i).walk_types_in(idx==-1 ? Type.SCALAR : ts.at(idx));
         }
         return ts;
       }
       throw unimpl();
     }
References com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.Lambda._body, com.cliffc.aa.type.TypeFunPtr._fidxs, com.cliffc.aa.HM.HM.T2._fidxs, com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.T2._flow, com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.HM.HM.Lambda._targs, com.cliffc.aa.type.Type< T extends Type< T >._uid, com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.HM.HM.T2.as_flow(), com.cliffc.aa.type.TypeStruct.at(), com.cliffc.aa.HM.HM.T2.dbl_uid(), com.cliffc.aa.type.Bits< B extends Bits< B >.dual(), com.cliffc.aa.HM.HM.Syntax.find(), com.cliffc.aa.type.TypeStruct.fld_find(), com.cliffc.aa.HM.HM.T2.fput(), com.cliffc.aa.type.BitsFun.FULL, com.cliffc.aa.HM.HM.Lambda.FUNS, com.cliffc.aa.HM.HM.T2.is_base(), com.cliffc.aa.HM.HM.T2.is_err(), com.cliffc.aa.HM.HM.T2.is_fun(), com.cliffc.aa.HM.HM.T2.is_leaf(), com.cliffc.aa.HM.HM.T2.is_nilable(), com.cliffc.aa.HM.HM.T2.is_struct(), com.cliffc.aa.type.Type< T extends Type< T >.join(), com.cliffc.aa.HM.HM.T2.no_uf(), com.cliffc.aa.type.Type< T extends Type< T >.NSCALR, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.putIfAbsent(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, com.cliffc.aa.HM.HM.T2.walk_types_in(), com.cliffc.aa.HM.HM.Apply.WDUPS, com.cliffc.aa.type.Type< T extends Type< T >.widen(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Referenced by com.cliffc.aa.HM.HM.Apply.val(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
walk_types_out()
Type com.cliffc.aa.HM.HM.T2.walk_types_out (Type t) package
Definition at line 2061 of file HM.java.
{
       assert no_uf();
       if( t == Type.XSCALAR ) return t;  // No lift possible
       Type tmap = Apply.T2MAP.get(this);
       if( tmap != null ) return tmap;
       if( is_err() ) throw unimpl();
       assert !is_leaf() && !is_base();        // All output leafs found as inputs already
       if( is_fun() ) return t; // No change, already known as a function (and no TFS in the flow types)
       if( is_struct() ) {
         if( !(t instanceof TypeMemPtr) ) throw unimpl();
         TypeMemPtr tmp = (TypeMemPtr)t;
         if( !(tmp._obj instanceof TypeStruct) ) throw unimpl();
         TypeStruct ts = (TypeStruct)tmp._obj;
         boolean progress=false;
         for( int i=0; i<_args.length; i++ ) {
           int idx = ts.fld_find(_ids[i]);
           if( idx==-1 ) continue;
           Type targ = ts.at(idx);
           Type rez = args(i).walk_types_out(targ);
           progress |= targ != rez;
         }
         if( !progress ) return t;
         // Make a new result
         TypeFld[] flds = TypeFlds.get(ts.len());
         for( int i=0; i<_args.length; i++ ) {
           int idx = ts.fld_find(_ids[i]);
           if( idx==-1 ) continue;
           Type targ = ts.at(idx);
           Type rez = args(i).walk_types_out(targ);
           flds[i] = ts.fld(i).make_from(rez);
         }
         return tmp.make_from(ts.make_from(flds));
       }
       throw unimpl();           // Handled all cases
     }
References com.cliffc.aa.HM.HM.T2._args, com.cliffc.aa.HM.HM.T2._ids, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.type.TypeStruct.at(), com.cliffc.aa.type.TypeStruct.fld(), com.cliffc.aa.type.TypeStruct.fld_find(), com.cliffc.aa.type.TypeFlds.get(), com.cliffc.aa.HM.HM.T2.is_base(), com.cliffc.aa.HM.HM.T2.is_err(), com.cliffc.aa.HM.HM.T2.is_fun(), com.cliffc.aa.HM.HM.T2.is_leaf(), com.cliffc.aa.HM.HM.T2.is_struct(), com.cliffc.aa.type.TypeStruct.len(), com.cliffc.aa.type.TypeFld.make_from(), com.cliffc.aa.type.TypeMemPtr.make_from(), com.cliffc.aa.type.TypeStruct.make_from(), com.cliffc.aa.HM.HM.T2.no_uf(), com.cliffc.aa.HM.HM.Apply.T2MAP, com.cliffc.aa.HM.HM.T2.walk_types_out(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Referenced by com.cliffc.aa.HM.HM.Apply.val(), and com.cliffc.aa.HM.HM.T2.walk_types_out().
Member Data Documentation
_alias
BitsAlias com.cliffc.aa.HM.HM.T2._alias package
Definition at line 1312 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2._cycle_equals(), com.cliffc.aa.HM.HM.T2._find_nil(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2._union(), com.cliffc.aa.HM.HM.T2.base_states(), com.cliffc.aa.HM.HM.T2.copy(), com.cliffc.aa.HM.HM.T2.fresh_base(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.T2.make_struct(), com.cliffc.aa.HM.HM.T2.meet_alias(), com.cliffc.aa.HM.HM.T2.str(), com.cliffc.aa.HM.HM.T2.unify_nil(), com.cliffc.aa.HM.HM.T2.union(), and com.cliffc.aa.HM.HM.T2.union_err().
_args
T2 [] com.cliffc.aa.HM.HM.T2._args package
Definition at line 1301 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2._cycle_equals(), com.cliffc.aa.HM.HM.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM.T2._find(), com.cliffc.aa.HM.HM.T2._find0(), com.cliffc.aa.HM.HM.T2._find_fidxs(), com.cliffc.aa.HM.HM.T2._find_nil(), com.cliffc.aa.HM.HM.T2._fresh(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._get_dups(), com.cliffc.aa.HM.HM.T2._occurs_in_type(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2._union(), com.cliffc.aa.HM.HM.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM.T2.add_fld(), com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.HM.HM.T2.copy(), com.cliffc.aa.HM.HM.T2.debug_find(), com.cliffc.aa.HM.HM.Apply.hm(), com.cliffc.aa.HM.HM.T2.no_uf(), com.cliffc.aa.HM.HM.T2.push_update_impl(), com.cliffc.aa.HM.HM.T2.str(), com.cliffc.aa.HM.HM.T2.T2(), com.cliffc.aa.HM.HM.T2.unify_nil(), com.cliffc.aa.HM.HM.T2.walk_types_in(), and com.cliffc.aa.HM.HM.T2.walk_types_out().
_deps
Ary<Syntax> com.cliffc.aa.HM.HM.T2._deps package
Definition at line 1318 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._find_nil(), com.cliffc.aa.HM.HM.T2._union(), com.cliffc.aa.HM.HM.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM.T2.add_fld(), com.cliffc.aa.HM.HM.Let.add_hm_work(), com.cliffc.aa.HM.HM.Let.add_val_work(), com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM.T2.copy(), com.cliffc.aa.HM.HM.T2.push_update_impl(), and com.cliffc.aa.HM.HM.Root.val().
_err
String com.cliffc.aa.HM.HM.T2._err package
Definition at line 1315 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2._cycle_equals(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2._union(), com.cliffc.aa.HM.HM.T2.base_states(), com.cliffc.aa.HM.HM.T2.copy(), com.cliffc.aa.HM.HM.T2.fresh_base(), com.cliffc.aa.HM.HM.T2.make_err(), com.cliffc.aa.HM.HM.T2.meet_err(), com.cliffc.aa.HM.HM.T2.str(), and com.cliffc.aa.HM.HM.T2.union().
_fidxs
BitsFun com.cliffc.aa.HM.HM.T2._fidxs package
Definition at line 1310 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2._cycle_equals(), com.cliffc.aa.HM.HM.T2._find_fidxs(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._union(), com.cliffc.aa.HM.HM.T2.base_states(), com.cliffc.aa.HM.HM.T2.copy(), com.cliffc.aa.HM.HM.T2.fresh_base(), com.cliffc.aa.HM.HM.T2.make_fun(), com.cliffc.aa.HM.HM.T2.meet_fidxs(), com.cliffc.aa.HM.HM.T2.str(), com.cliffc.aa.HM.HM.T2.union(), com.cliffc.aa.HM.HM.T2.union_err(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
_flow
Type com.cliffc.aa.HM.HM.T2._flow package
Definition at line 1309 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2._can_be_HM_base(), com.cliffc.aa.HM.HM.T2._cycle_equals(), com.cliffc.aa.HM.HM.T2._find_nil(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2._union(), com.cliffc.aa.HM.HM.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM.T2.base_states(), com.cliffc.aa.HM.HM.T2.copy(), com.cliffc.aa.HM.HM.T2.fresh_base(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.T2.make_base(), com.cliffc.aa.HM.HM.T2.meet_flow(), com.cliffc.aa.HM.HM.T2.str(), com.cliffc.aa.HM.HM.T2.unify_nil(), com.cliffc.aa.HM.HM.T2.union(), com.cliffc.aa.HM.HM.T2.union_err(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
_ids
String [] com.cliffc.aa.HM.HM.T2._ids package
Definition at line 1313 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM.T2._find_nil(), com.cliffc.aa.HM.HM.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2._unify_struct(), com.cliffc.aa.HM.HM.T2._union(), com.cliffc.aa.HM.HM.T2.add_fld(), com.cliffc.aa.HM.HM.T2.base_states(), com.cliffc.aa.HM.HM.T2.copy(), com.cliffc.aa.HM.HM.T2.fresh_base(), com.cliffc.aa.HM.HM.Struct.hm(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.T2.is_tuple(), com.cliffc.aa.HM.HM.T2.make_struct(), com.cliffc.aa.HM.HM.T2.meet_ids(), com.cliffc.aa.HM.HM.T2.str(), com.cliffc.aa.HM.HM.T2.union(), com.cliffc.aa.HM.HM.T2.union_err(), com.cliffc.aa.HM.HM.T2.walk_types_in(), and com.cliffc.aa.HM.HM.T2.walk_types_out().
_name
String com.cliffc.aa.HM.HM.T2._name package
Definition at line 1298 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._cycle_equals(), com.cliffc.aa.HM.HM.T2._find_nil(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2._union(), com.cliffc.aa.HM.HM.T2.copy(), com.cliffc.aa.HM.HM.T2.fresh_base(), com.cliffc.aa.HM.HM.T2.is_leaf(), com.cliffc.aa.HM.HM.T2.isa(), com.cliffc.aa.HM.HM.T2.no_uf(), com.cliffc.aa.HM.HM.T2.str(), and com.cliffc.aa.HM.HM.T2.T2().
_open
boolean com.cliffc.aa.HM.HM.T2._open package
Definition at line 1314 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._find_nil(), com.cliffc.aa.HM.HM.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM.T2._unify_struct(), com.cliffc.aa.HM.HM.T2.copy(), com.cliffc.aa.HM.HM.T2.fresh_base(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.T2.make_struct(), com.cliffc.aa.HM.HM.T2.meet_opens(), and com.cliffc.aa.HM.HM.T2.union().
_uid
final int com.cliffc.aa.HM.HM.T2._uid package
Definition at line 1293 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM.T2._find(), com.cliffc.aa.HM.HM.T2._find_fidxs(), com.cliffc.aa.HM.HM.T2._get_dups(), com.cliffc.aa.HM.HM.T2._occurs_in_type(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2._union(), com.cliffc.aa.HM.HM.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM.T2.dbl_uid(), com.cliffc.aa.HM.HM.T2.meet_err(), com.cliffc.aa.HM.HM.T2.push_update_impl(), com.cliffc.aa.HM.HM.T2.str(), and com.cliffc.aa.HM.HM.T2.T2().
ADUPS
final NonBlockingHashMapLong<TypeStruct> com.cliffc.aa.HM.HM.T2.ADUPS = new NonBlockingHashMapLong<>() static package
Definition at line 1426 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._as_flow(), and com.cliffc.aa.HM.HM.T2.as_flow().
CDUPS
final HashMap<T2,T2> com.cliffc.aa.HM.HM.T2.CDUPS = new HashMap<>() static private
Definition at line 1961 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._cycle_equals(), com.cliffc.aa.HM.HM.T2.cycle_equals(), and com.cliffc.aa.HM.HM.T2.reset().
CNT
int com.cliffc.aa.HM.HM.T2.CNT =0 static private
Definition at line 1292 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2.fresh_unify(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.T2.make_leaf(), com.cliffc.aa.HM.HM.T2.reset(), and com.cliffc.aa.HM.HM.T2.T2().
DUPS
final HashMap<Long,T2> com.cliffc.aa.HM.HM.T2.DUPS = new HashMap<>() static private
Definition at line 1603 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._unify(), com.cliffc.aa.HM.HM.T2.fresh_unify(), com.cliffc.aa.HM.HM.T2.reset(), and com.cliffc.aa.HM.HM.T2.unify().
FIDX_VISIT
final VBitSet com.cliffc.aa.HM.HM.T2.FIDX_VISIT = new VBitSet() static private
Definition at line 2098 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._find_fidxs(), and com.cliffc.aa.HM.HM.T2.find_fidxs().
FIDXS
BitsFun com.cliffc.aa.HM.HM.T2.FIDXS = null static private
Definition at line 2099 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._find_fidxs(), and com.cliffc.aa.HM.HM.T2.find_fidxs().
ODUPS
final VBitSet com.cliffc.aa.HM.HM.T2.ODUPS = new VBitSet() static private
Definition at line 1933 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._occurs_in_type(), com.cliffc.aa.HM.HM.T2.nongen_in(), com.cliffc.aa.HM.HM.T2.occurs_in_type(), and com.cliffc.aa.HM.HM.T2.reset().
UPDATE_VISIT
final VBitSet com.cliffc.aa.HM.HM.T2.UPDATE_VISIT = new VBitSet() static package
Definition at line 2117 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2.add_deps_work(), com.cliffc.aa.HM.HM.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM.T2.push_update(), com.cliffc.aa.HM.HM.T2.push_update_impl(), and com.cliffc.aa.HM.HM.T2.reset().
VARS
final HashMap<T2,T2> com.cliffc.aa.HM.HM.T2.VARS = new HashMap<>() static private
Definition at line 1768 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._fresh(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2.fresh(), com.cliffc.aa.HM.HM.T2.fresh_unify(), com.cliffc.aa.HM.HM.T2.reset(), and com.cliffc.aa.HM.HM.T2.vput().
VCNT
int com.cliffc.aa.HM.HM.T2.VCNT static private
Definition at line 2206 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._p(), and com.cliffc.aa.HM.HM.T2.p().
VNAMES
final HashMap<T2,Integer> com.cliffc.aa.HM.HM.T2.VNAMES = new HashMap<>() static private
Definition at line 2207 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2._p(), and com.cliffc.aa.HM.HM.T2.p().
The documentation for this class was generated from the following file:
HM.java