aa: com.cliffc.aa.HM.HM8.Ident Class Reference
com.cliffc.aa.HM.HM8.Ident Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Ident (String name)
void add_work (Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
T2 lookup (String name)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
T2 post ()
T2 pre ()
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
Package Attributes
final String _name
VStack _nongen
Syntax _par
T2 _post
T2 _pre
T2 _t
Detailed Description
Definition at line 319 of file HM8.java.
Constructor & Destructor Documentation
Ident()
com.cliffc.aa.HM.HM8.Ident.Ident (String name) package
Definition at line 321 of file HM8.java.
 { _name=name; }
References com.cliffc.aa.HM.HM8.Ident._name.
Member Function Documentation
add_work()
void com.cliffc.aa.HM.HM8.Ident.add_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 338 of file HM8.java.
{
       work.push(_par);
       T2 t = _par==null ? null : _par.lookup(_name); // Lookup in current env
       if( t==null ) t = PRIMS.get(_name);            // Lookup in prims
       t = t.find();
       if( t.occurs_in(_par) )                        // Got captured in some parent?
         t.add_deps_work(work);                       // Need to revisit dependent ids
     }
References com.cliffc.aa.HM.HM8.Ident._name, com.cliffc.aa.HM.HM8.Syntax._par, com.cliffc.aa.HM.HM8.T2.add_deps_work(), com.cliffc.aa.HM.HM8.T2.find(), com.cliffc.aa.HM.HM8.Syntax.lookup(), com.cliffc.aa.HM.HM8.T2.occurs_in(), com.cliffc.aa.HM.HM8.PRIMS, and com.cliffc.aa.HM.HM8.Worklist.push().
debug_find()
T2 com.cliffc.aa.HM.HM8.Syntax.debug_find () package inherited
Definition at line 249 of file HM8.java.
 { return _t.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM8.Syntax._t, and com.cliffc.aa.HM.HM8.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM8.hm().
find()
T2 com.cliffc.aa.HM.HM8.Syntax.find () package inherited
Definition at line 245 of file HM8.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._t, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.T2._occurs_in(), com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Ident.hm(), com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.HM.HM8.Apply.is_if_nil(), and com.cliffc.aa.HM.HM8.Struct.prep_tree().
hm()
boolean com.cliffc.aa.HM.HM8.Ident.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 325 of file HM8.java.
{
       // A boolean if name is from a Let._body (or PRIM) vs Let._def (or
       // Lambda).  Not helpful, as its only useful at the top-layer.
       // Structural unification requires the 'occurs check' at each internal
       // layer, which can differ from the top-layer.
       //boolean occurs_fresh = _par==null /*from prims*/ || _par.is_fresh(_name,this);
       T2 t = _par==null ? null : _par.lookup(_name); // Lookup in current env
       if( t==null ) t = PRIMS.get(_name);            // Lookup in prims
       if( t==null )
         throw new RuntimeException("Parse error, "+_name+" is undefined");
       return t.find().fresh_unify(find(),_nongen,work);
     }
References com.cliffc.aa.HM.HM8.Ident._name, com.cliffc.aa.HM.HM8.Syntax._nongen, com.cliffc.aa.HM.HM8.Syntax._par, com.cliffc.aa.HM.HM8.Syntax.find(), com.cliffc.aa.HM.HM8.T2.find(), com.cliffc.aa.HM.HM8.T2.fresh_unify(), com.cliffc.aa.HM.HM8.Syntax.lookup(), and com.cliffc.aa.HM.HM8.PRIMS.
lookup()
T2 com.cliffc.aa.HM.HM8.Ident.lookup (String name) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 337 of file HM8.java.
 { throw unimpl("should not reach here"); }
more_work()
boolean com.cliffc.aa.HM.HM8.Ident.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 354 of file HM8.java.
 { return more_work_impl(work); }
References com.cliffc.aa.HM.HM8.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM8.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 283 of file HM8.java.
{
       boolean no_more_work = work.has(this) || !hm(null); // Either on worklist, or no-progress
       return no_more_work;
     }
References com.cliffc.aa.HM.HM8.Worklist.has(), and com.cliffc.aa.HM.HM8.Syntax.hm().
Referenced by com.cliffc.aa.HM.HM8.Con.more_work(), com.cliffc.aa.HM.HM8.Ident.more_work(), com.cliffc.aa.HM.HM8.Lambda.more_work(), com.cliffc.aa.HM.HM8.Let.more_work(), com.cliffc.aa.HM.HM8.Apply.more_work(), com.cliffc.aa.HM.HM8.Struct.more_work(), and com.cliffc.aa.HM.HM8.Field.more_work().
p()
String com.cliffc.aa.HM.HM8.Syntax.p () inherited
Definition at line 291 of file HM8.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM8.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM8.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 292 of file HM8.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM8.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM8.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM8.Syntax.p1(), com.cliffc.aa.HM.HM8.Syntax.p2(), and com.cliffc.aa.HM.HM8.T2.str().
Referenced by com.cliffc.aa.HM.HM8.Syntax.p(), com.cliffc.aa.HM.HM8.Lambda.p2(), com.cliffc.aa.HM.HM8.Let.p2(), com.cliffc.aa.HM.HM8.Apply.p2(), com.cliffc.aa.HM.HM8.Struct.p2(), and com.cliffc.aa.HM.HM8.Field.p2().
p1()
SB com.cliffc.aa.HM.HM8.Ident.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 323 of file HM8.java.
 { return sb.p(_name); }
References com.cliffc.aa.HM.HM8.Ident._name, and com.cliffc.aa.util.SB.p().
Referenced by com.cliffc.aa.HM.HM8.Ident.str().
p2()
SB com.cliffc.aa.HM.HM8.Ident.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 324 of file HM8.java.
 { return sb; }
post()
T2 com.cliffc.aa.HM.HM8.Syntax.post () package inherited
Definition at line 254 of file HM8.java.
               {
       T2 t = _post.find();
       return t==_post ? t : (_post=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._post, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), and com.cliffc.aa.HM.HM8.Field.hm().
pre()
T2 com.cliffc.aa.HM.HM8.Syntax.pre () package inherited
Definition at line 250 of file HM8.java.
              {
       T2 t = _pre.find();
       return t==_pre ? t : (_pre=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._pre, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), and com.cliffc.aa.HM.HM8.Field.hm().
prep_lookup_deps()
void com.cliffc.aa.HM.HM8.Ident.prep_lookup_deps (Ident id) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 353 of file HM8.java.
 { throw unimpl("should not reach here"); }
prep_tree()
int com.cliffc.aa.HM.HM8.Ident.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 346 of file HM8.java.
{
       prep_tree_impl(par,nongen,work,T2.make_leaf());
       _pre=_post;               // Unify at prep-time
       for( Syntax syn = _par; syn!=null; syn = syn._par )
         syn.prep_lookup_deps(this);
       return 1;
     }
References com.cliffc.aa.HM.HM8.Syntax._par, com.cliffc.aa.HM.HM8.Syntax._post, com.cliffc.aa.HM.HM8.Syntax._pre, com.cliffc.aa.HM.HM8.T2.make_leaf(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
prep_tree_impl()
final void com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 267 of file HM8.java.
{
       _par=par;
       _pre = T2.make_mem();
       _t=t;
       _post = T2.make_mem();
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM8.Syntax._nongen, com.cliffc.aa.HM.HM8.Syntax._par, com.cliffc.aa.HM.HM8.Syntax._post, com.cliffc.aa.HM.HM8.Syntax._pre, com.cliffc.aa.HM.HM8.Syntax._t, com.cliffc.aa.HM.HM8.T2.make_mem(), and com.cliffc.aa.HM.HM8.Worklist.push().
Referenced by com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), com.cliffc.aa.HM.HM8.Lambda.prep_tree(), com.cliffc.aa.HM.HM8.Let.prep_tree(), com.cliffc.aa.HM.HM8.Apply.prep_tree(), com.cliffc.aa.HM.HM8.Struct.prep_tree(), and com.cliffc.aa.HM.HM8.Field.prep_tree().
str()
SB com.cliffc.aa.HM.HM8.Ident.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 322 of file HM8.java.
 { return p1(sb); }
References com.cliffc.aa.HM.HM8.Ident.p1().
toString()
final String com.cliffc.aa.HM.HM8.Syntax.toString () inherited
Definition at line 288 of file HM8.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM8.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_name
final String com.cliffc.aa.HM.HM8.Ident._name package
Definition at line 320 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Ident.add_work(), com.cliffc.aa.HM.HM8.Ident.hm(), com.cliffc.aa.HM.HM8.Ident.Ident(), and com.cliffc.aa.HM.HM8.Ident.p1().
_nongen
VStack com.cliffc.aa.HM.HM8.Syntax._nongen package inherited
Definition at line 241 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Ident.hm(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM8.Syntax._par package inherited
Definition at line 240 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._occurs_in(), com.cliffc.aa.HM.HM8.Con.add_work(), com.cliffc.aa.HM.HM8.Ident.add_work(), com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Apply.add_work(), com.cliffc.aa.HM.HM8.Struct.add_work(), com.cliffc.aa.HM.HM8.Field.add_work(), com.cliffc.aa.HM.HM8.Ident.hm(), com.cliffc.aa.HM.HM8.Lambda.lookup(), com.cliffc.aa.HM.HM8.Let.lookup(), com.cliffc.aa.HM.HM8.Apply.lookup(), com.cliffc.aa.HM.HM8.Struct.lookup(), com.cliffc.aa.HM.HM8.Field.lookup(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_post
T2 com.cliffc.aa.HM.HM8.Syntax._post package inherited
Definition at line 244 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Syntax.post(), com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_pre
T2 com.cliffc.aa.HM.HM8.Syntax._pre package inherited
Definition at line 242 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Syntax.pre(), com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM8.Syntax._t package inherited
Definition at line 243 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Syntax.debug_find(), com.cliffc.aa.HM.HM8.Syntax.find(), com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM8.Syntax.p0(), com.cliffc.aa.HM.HM8.Let.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM8.java