aa: com.cliffc.aa.type.TypeAry Class Reference
com.cliffc.aa.type.TypeAry Class Reference
Public Member Functions
boolean above_center ()
TypeAry crush ()
boolean cycle_equals (Type o)
boolean equals (Object o)
boolean is_con ()
Type ld (TypeInt idx)
boolean may_be_con ()
boolean may_nil ()
boolean must_nil ()
SB str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
TypeObj update (Access fin, String fld, Type val)
TypeObj update (TypeInt idx, Type val)
void walk (Predicate< Type > p)
TypeObj widen ()
Static Public Member Functions
static TypeAry make (String name, boolean any, TypeInt sz, Type elem, TypeObj stor)
static TypeAry make (TypeInt sz, Type elem, TypeObj stor)
Public Attributes
TypeInt _size
Static Public Attributes
static final TypeAry ARY = make("",false,TypeInt.INT64 ,Type.SCALAR ,TypeObj.OBJ)
static final TypeAry ARY0 = make("",false,TypeInt.INT64 ,Type.XNIL ,TypeObj.OBJ)
static final TypeAry BYTES = make("",false,TypeInt.con(3),TypeInt.INT8,TypeObj.OBJ)
static final TypeObj ISUSED
static final TypeObj OBJ
static final TypeObj UNUSED
static final TypeObj XOBJ
Protected Member Functions
O init (byte type, String name, boolean any, boolean use)
TypeAry xdual ()
Type xmeet (Type t)
Package Functions
int compute_hash ()
TypeObj flatten_fields ()
boolean is_display ()
TypeAry rdual ()
TypeAry remove_other_flds (String fld, Type live)
Static Package Functions
[static initializer]
Package Attributes
boolean _any
boolean _use
Static Package Attributes
static final TypeAry[] TYPES = new TypeAry[]{ARY,ARY0,BYTES}
Private Member Functions
TypeAry init (String name, boolean any, TypeInt sz, Type elem, TypeObj stor)
Private Attributes
Type _elem
TypeObj _stor
Detailed Description
Definition at line 7 of file TypeAry.java.
Member Function Documentation
[static initializer]()
com.cliffc.aa.type.TypeAry.[static initializer] static package
above_center()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.above_center inherited
Definition at line 77 of file TypeObj.java.
 { return _any; }
compute_hash()
int com.cliffc.aa.type.TypeAry.compute_hash () package
Definition at line 19 of file TypeAry.java.
 { return super.compute_hash() + _size._hash + _elem._hash + _stor._hash;  }
References com.cliffc.aa.type.TypeAry._elem, com.cliffc.aa.type.Type< T extends Type< T >._hash, com.cliffc.aa.type.TypeAry._size, and com.cliffc.aa.type.TypeAry._stor.
Referenced by com.cliffc.aa.type.TypeAry.rdual().
crush()
TypeAry com.cliffc.aa.type.TypeAry.crush ()
Definition at line 85 of file TypeAry.java.
{
     if( _any ) return this;     // No crush on high arrays
     return make(_size,Type.SCALAR,_stor);
   }
References com.cliffc.aa.type.TypeObj< TypeAry >._any, com.cliffc.aa.type.TypeAry._size, com.cliffc.aa.type.TypeAry._stor, com.cliffc.aa.type.TypeAry.make(), and com.cliffc.aa.type.Type< T extends Type< T >.SCALAR.
cycle_equals()
boolean com.cliffc.aa.type.TypeAry.cycle_equals (Type o)
Definition at line 26 of file TypeAry.java.
 { return equals(o); }
References com.cliffc.aa.type.TypeAry.equals().
equals()
boolean com.cliffc.aa.type.TypeAry.equals (Object o)
Definition at line 20 of file TypeAry.java.
{
     if( this==o ) return true;
     if( !(o instanceof TypeAry) || !super.equals(o) ) return false;
     TypeAry ta = (TypeAry)o;
     return _size == ta._size && _elem == ta._elem && _stor == ta._stor;
   }
References com.cliffc.aa.type.TypeAry._elem, com.cliffc.aa.type.TypeAry._size, and com.cliffc.aa.type.TypeAry._stor.
Referenced by com.cliffc.aa.type.TypeAry.cycle_equals().
flatten_fields()
TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.flatten_fields package inherited
Definition at line 74 of file TypeObj.java.
 { return this; }
init() [1/2]
O com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.init (byte type, String name, boolean any, boolean use) protected inherited
Definition at line 19 of file TypeObj.java.
{
     super.init(type,name);
     _any=any;
     _use=use;
     return (O)this;
   }
init() [2/2]
TypeAry com.cliffc.aa.type.TypeAry.init (String name, boolean any, TypeInt sz, Type elem, TypeObj stor) private
Definition at line 12 of file TypeAry.java.
{
     super.init(TARY,name,any,any);
     _size = sz;
     _elem = elem;
     _stor = stor;
     return this;
   }
References com.cliffc.aa.type.TypeAry._elem, com.cliffc.aa.type.TypeAry._size, com.cliffc.aa.type.TypeAry._stor, and com.cliffc.aa.type.TypeAry.init().
Referenced by com.cliffc.aa.type.TypeAry.init(), com.cliffc.aa.type.TypeAry.make(), and com.cliffc.aa.type.TypeAry.xdual().
is_con()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.is_con inherited
Definition at line 79 of file TypeObj.java.
 { return false; }
is_display()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.is_display package inherited
Definition at line 50 of file TypeObj.java.
 { return false; }
ld()
Type com.cliffc.aa.type.TypeAry.ld (TypeInt idx)
Definition at line 90 of file TypeAry.java.
{
     return _elem;
   }
References com.cliffc.aa.type.TypeAry._elem.
Referenced by com.cliffc.aa.node.MemPrimNode.LValueRead.value().
make() [1/2]
static TypeAry com.cliffc.aa.type.TypeAry.make (String name, boolean any, TypeInt sz, Type elem, TypeObj stor) static
Definition at line 38 of file TypeAry.java.
{
     TypeAry t1 = POOLS[TARY].malloc();
     return t1.init(name,any,sz,elem,stor).hashcons_free();
   }
References com.cliffc.aa.type.TypeAry.init().
Referenced by com.cliffc.aa.type.TypeAry.crush(), com.cliffc.aa.TestParse.testParse14(), com.cliffc.aa.Parse.type0(), com.cliffc.aa.type.TypeAry.update(), com.cliffc.aa.node.NewAryNode.NewAry.valueobj(), and com.cliffc.aa.type.TypeAry.xmeet().
make() [2/2]
static TypeAry com.cliffc.aa.type.TypeAry.make (TypeInt sz, Type elem, TypeObj stor) static
Definition at line 43 of file TypeAry.java.
 { return make("",false,sz,elem,stor); }
References com.cliffc.aa.type.TypeAry.make().
Referenced by com.cliffc.aa.type.TypeAry.make().
may_be_con()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.may_be_con inherited
Definition at line 78 of file TypeObj.java.
 { return _any; }
may_nil()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.may_nil inherited
Definition at line 81 of file TypeObj.java.
 { return false; }
must_nil()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.must_nil inherited
Definition at line 80 of file TypeObj.java.
 { return false; }
rdual()
TypeAry com.cliffc.aa.type.TypeAry.rdual () package
Definition at line 51 of file TypeAry.java.
                   {
     if( _dual != null ) return _dual;
     TypeAry dual = _dual = xdual();
     dual._dual = this;
     dual._hash = dual.compute_hash();
     return dual;
   }
References com.cliffc.aa.type.TypeAry.compute_hash(), and com.cliffc.aa.type.TypeAry.xdual().
remove_other_flds()
TypeAry com.cliffc.aa.type.TypeAry.remove_other_flds (String fld, Type live) package
Definition at line 102 of file TypeAry.java.
{
     return ARY;
   }
References com.cliffc.aa.type.TypeAry.ARY.
str()
SB com.cliffc.aa.type.TypeAry.str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
Definition at line 27 of file TypeAry.java.
{
     if( _any ) sb.p('~');
     sb.p('[');
     if( _size!=null && _size != TypeInt.INT64 ) sb.p(_size);
     sb.p(']');
     if( _elem !=null ) sb.p(_elem);
     if( _elem != _stor && _stor!=null ) sb.p('/').p(_stor);
     return sb;
   }
References com.cliffc.aa.type.TypeObj< TypeAry >._any, com.cliffc.aa.type.TypeAry._elem, com.cliffc.aa.type.TypeAry._size, com.cliffc.aa.type.TypeAry._stor, com.cliffc.aa.type.TypeInt.INT64, and com.cliffc.aa.util.SB.p().
update() [1/2]
TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.update (Access fin, String fld, Type val) inherited
Definition at line 67 of file TypeObj.java.
 { return this; }
update() [2/2]
TypeObj com.cliffc.aa.type.TypeAry.update (TypeInt idx, Type val)
Definition at line 93 of file TypeAry.java.
{
     if( idx.above_center() ) return this; // Nothing updates
     if( val.isa(_elem) ) return this;     // No change
     Type elem = _elem.meet(val);          // Worse-case
     TypeInt size = _size; // TypeInt size = (TypeInt)_size.meet(idx); // CNC - Not inferring array size yet
     return make(size,elem,TypeObj.OBJ);
   }
References com.cliffc.aa.type.TypeAry._elem, com.cliffc.aa.type.TypeAry._size, com.cliffc.aa.type.TypeInt.above_center(), com.cliffc.aa.type.Type< T extends Type< T >.isa(), com.cliffc.aa.type.TypeAry.make(), com.cliffc.aa.type.Type< T extends Type< T >.meet(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.OBJ.
Referenced by com.cliffc.aa.type.TypeObj< TypeStruct >.update().
walk()
void com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.walk (Predicate< Type > p) inherited
Definition at line 82 of file TypeObj.java.
 { p.test(this); }
widen()
TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.widen inherited
Definition at line 76 of file TypeObj.java.
 { return ISUSED; }
xdual()
TypeAry com.cliffc.aa.type.TypeAry.xdual () protected
Definition at line 49 of file TypeAry.java.
 { return new TypeAry().init(_name, !_any,_size.dual(),_elem.dual(),(TypeObj)_stor.dual()); }
References com.cliffc.aa.type.TypeObj< TypeAry >._any, com.cliffc.aa.type.TypeAry._elem, com.cliffc.aa.type.TypeAry._size, com.cliffc.aa.type.TypeAry._stor, com.cliffc.aa.type.Type< T extends Type< T >.dual(), and com.cliffc.aa.type.TypeAry.init().
Referenced by com.cliffc.aa.type.TypeAry.rdual().
xmeet()
Type com.cliffc.aa.type.TypeAry.xmeet (Type t) protected
Definition at line 58 of file TypeAry.java.
{
     switch( t._type ) {
     case TARY:   break;
     case TSTR:
     case TLIVE:
     case TSTRUCT:return OBJ;
     case TOBJ:   return t.xmeet(this);
     case TFUNSIG:
     case TTUPLE:
     case TFUNPTR:
     case TMEMPTR:
     case TFLT:
     case TINT:
     case TRPC:
     case TMEM:   return ALL;
     default: throw typerr(t);
     }
     TypeAry ta = (TypeAry)t;
     boolean any = _any&ta._any;
     TypeInt size = (TypeInt)_size.meet(ta._size);
     Type elem = _elem.meet(ta._elem);
     TypeObj stor = (TypeObj)_stor.meet(ta._stor);
     return make("",any,size,elem,stor);
   }
References com.cliffc.aa.type.TypeObj< TypeAry >._any, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >._any, com.cliffc.aa.type.TypeAry._elem, com.cliffc.aa.type.TypeAry._size, com.cliffc.aa.type.TypeAry._stor, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.type.TypeAry.make(), com.cliffc.aa.type.Type< T extends Type< T >.meet(), com.cliffc.aa.type.TypeObj< TypeAry >.OBJ, and com.cliffc.aa.type.Type< T extends Type< T >.xmeet().
Member Data Documentation
_any
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >._any package inherited
Definition at line 16 of file TypeObj.java.
_elem
Type com.cliffc.aa.type.TypeAry._elem private
Definition at line 9 of file TypeAry.java.
Referenced by com.cliffc.aa.type.TypeAry.compute_hash(), com.cliffc.aa.type.TypeAry.equals(), com.cliffc.aa.type.TypeAry.init(), com.cliffc.aa.type.TypeAry.ld(), com.cliffc.aa.type.TypeAry.str(), com.cliffc.aa.type.TypeAry.update(), com.cliffc.aa.type.TypeAry.xdual(), and com.cliffc.aa.type.TypeAry.xmeet().
_size
TypeInt com.cliffc.aa.type.TypeAry._size
Definition at line 8 of file TypeAry.java.
Referenced by com.cliffc.aa.type.TypeAry.compute_hash(), com.cliffc.aa.type.TypeAry.crush(), com.cliffc.aa.type.TypeAry.equals(), com.cliffc.aa.node.MemPrimNode.err(), com.cliffc.aa.type.TypeAry.init(), com.cliffc.aa.type.TypeAry.str(), com.cliffc.aa.type.TypeAry.update(), com.cliffc.aa.node.MemPrimNode.LValueLength.value(), com.cliffc.aa.type.TypeAry.xdual(), and com.cliffc.aa.type.TypeAry.xmeet().
_stor
TypeObj com.cliffc.aa.type.TypeAry._stor private
Definition at line 10 of file TypeAry.java.
Referenced by com.cliffc.aa.type.TypeAry.compute_hash(), com.cliffc.aa.type.TypeAry.crush(), com.cliffc.aa.type.TypeAry.equals(), com.cliffc.aa.type.TypeAry.init(), com.cliffc.aa.type.TypeAry.str(), com.cliffc.aa.type.TypeAry.xdual(), and com.cliffc.aa.type.TypeAry.xmeet().
_use
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >._use package inherited
Definition at line 17 of file TypeObj.java.
ARY
final TypeAry com.cliffc.aa.type.TypeAry.ARY = make("",false,TypeInt.INT64 ,Type.SCALAR ,TypeObj.OBJ) static
Definition at line 44 of file TypeAry.java.
Referenced by com.cliffc.aa.node.NewAryNode.dead_type(), com.cliffc.aa.type.TypeAry.remove_other_flds(), com.cliffc.aa.node.TestNodeSmall.tmem(), and com.cliffc.aa.type.TypeObj< TypeStruct >.update().
ARY0
final TypeAry com.cliffc.aa.type.TypeAry.ARY0 = make("",false,TypeInt.INT64 ,Type.XNIL ,TypeObj.OBJ) static
Definition at line 45 of file TypeAry.java.
Referenced by com.cliffc.aa.node.NewAryNode.add_libs().
BYTES
final TypeAry com.cliffc.aa.type.TypeAry.BYTES = make("",false,TypeInt.con(3),TypeInt.INT8,TypeObj.OBJ) static
Definition at line 46 of file TypeAry.java.
ISUSED
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.ISUSED static inherited
Definition at line 45 of file TypeObj.java.
OBJ
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.OBJ static inherited
Definition at line 44 of file TypeObj.java.
TYPES
final TypeAry [] com.cliffc.aa.type.TypeAry.TYPES = new TypeAry[]{ARY,ARY0,BYTES} static package
Definition at line 47 of file TypeAry.java.
UNUSED
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED static inherited
Definition at line 46 of file TypeObj.java.
XOBJ
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.XOBJ static inherited
Definition at line 47 of file TypeObj.java.
The documentation for this class was generated from the following file:
TypeAry.java