aa: com.cliffc.aa.HM.HM.Ident Class Reference
com.cliffc.aa.HM.HM.Ident Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Ident (String name)
void add_hm_work (Worklist work)
void add_val_work (Syntax child, Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
T2 idt ()
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
Type val (Worklist work)
Package Attributes
Syntax _def
Type _flow
T2 _hmt
T2 _idt
int _idx
final String _name
VStack _nongen
Syntax _par
Private Member Functions
int _init (Syntax def, T2 idt)
Detailed Description
Definition at line 426 of file HM.java.
Constructor & Destructor Documentation
Ident()
com.cliffc.aa.HM.HM.Ident.Ident (String name) package
Definition at line 431 of file HM.java.
 { _name=name; }
References com.cliffc.aa.HM.HM.Ident._name.
Member Function Documentation
_init()
int com.cliffc.aa.HM.HM.Ident._init (Syntax def, T2 idt) private
Definition at line 472 of file HM.java.
 { _def = def; _idt = idt; return 1; }
References com.cliffc.aa.HM.HM.Ident._def, com.cliffc.aa.HM.HM.Ident._idt, and com.cliffc.aa.HM.HM.Ident.idt().
Referenced by com.cliffc.aa.HM.HM.Ident.prep_tree().
add_hm_work()
void com.cliffc.aa.HM.HM.Ident.add_hm_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 442 of file HM.java.
{
       work.push(_par);
       T2 t = idt();
       if( t.nongen_in(_par == null ? null : _par._nongen) ) // Got captured in some parent?
         t.add_deps_work(work);                              // Need to revisit dependent ids
       if( _par instanceof Apply && ((Apply)_par)._fun instanceof NotNil )
         work.push(((Apply)_par)._fun);
     }
References com.cliffc.aa.HM.HM.Syntax._nongen, com.cliffc.aa.HM.HM.Syntax._par, com.cliffc.aa.HM.HM.T2.add_deps_work(), com.cliffc.aa.HM.HM.Ident.idt(), com.cliffc.aa.HM.HM.T2.nongen_in(), and com.cliffc.aa.HM.HM.Worklist.push().
add_val_work()
void com.cliffc.aa.HM.HM.Syntax.add_val_work (Syntax child, Worklist work) package inherited
Reimplemented in com.cliffc.aa.HM.HM.PrimSyn, com.cliffc.aa.HM.HM.Apply, com.cliffc.aa.HM.HM.Let, and com.cliffc.aa.HM.HM.Lambda.
Definition at line 365 of file HM.java.
 {} // Add affected neighbors to worklist
Referenced by com.cliffc.aa.HM.HM.hm().
debug_find()
T2 com.cliffc.aa.HM.HM.Syntax.debug_find () package inherited
Definition at line 348 of file HM.java.
 { return _hmt.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM.Syntax._hmt, and com.cliffc.aa.HM.HM.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM.hm().
find()
T2 com.cliffc.aa.HM.HM.Syntax.find () package inherited
Definition at line 344 of file HM.java.
               {                 // U-F find
       T2 t = _hmt.find();
       return t== _hmt ? t : (_hmt =t);
     }
References com.cliffc.aa.HM.HM.Syntax._hmt, and com.cliffc.aa.HM.HM.T2.find().
Referenced by com.cliffc.aa.HM.HM.Lambda.add_hm_work(), com.cliffc.aa.HM.HM.Let.add_hm_work(), com.cliffc.aa.HM.HM.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM.Lambda.add_val_work(), com.cliffc.aa.HM.HM.Let.add_val_work(), com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM.Ident.hm(), com.cliffc.aa.HM.HM.Lambda.hm(), com.cliffc.aa.HM.HM.Apply.hm(), com.cliffc.aa.HM.HM.Root.hm(), com.cliffc.aa.HM.HM.Struct.hm(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.PrimSyn.hm(), com.cliffc.aa.HM.HM.If.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.Let.prep_tree(), com.cliffc.aa.HM.HM.Struct.prep_tree(), com.cliffc.aa.HM.HM.NotNil.prep_tree(), com.cliffc.aa.HM.HM.Apply.val(), com.cliffc.aa.HM.HM.Root.val(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
hm()
boolean com.cliffc.aa.HM.HM.Ident.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 439 of file HM.java.
{
       return idt().fresh_unify(find(),_nongen,work);
     }
References com.cliffc.aa.HM.HM.Syntax._nongen, com.cliffc.aa.HM.HM.Syntax.find(), com.cliffc.aa.HM.HM.T2.fresh_unify(), and com.cliffc.aa.HM.HM.Ident.idt().
idt()
T2 com.cliffc.aa.HM.HM.Ident.idt () package
Definition at line 435 of file HM.java.
              {
       T2 idt = _idt.find();
       return idt==_idt ? idt : (_idt=idt);
     }
References com.cliffc.aa.HM.HM.Ident._idt, and com.cliffc.aa.HM.HM.T2.find().
Referenced by com.cliffc.aa.HM.HM.Ident._init(), com.cliffc.aa.HM.HM.Ident.add_hm_work(), and com.cliffc.aa.HM.HM.Ident.hm().
more_work()
boolean com.cliffc.aa.HM.HM.Ident.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 473 of file HM.java.
 { return more_work_impl(work); }
References com.cliffc.aa.HM.HM.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 381 of file HM.java.
{
       if( work.has(this) ) return true;
       if( DO_HM && hm(null) )   // Any more HM work?
         return false;           // Found HM work not on worklist
       if( DO_GCP && val(null)!=_flow )
         return false;           // Found GCP work not on worklist
       return true;
     }
References com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Worklist.has(), com.cliffc.aa.HM.HM.Syntax.hm(), and com.cliffc.aa.HM.HM.Syntax.val().
Referenced by com.cliffc.aa.HM.HM.Con.more_work(), com.cliffc.aa.HM.HM.Ident.more_work(), com.cliffc.aa.HM.HM.Lambda.more_work(), com.cliffc.aa.HM.HM.Let.more_work(), com.cliffc.aa.HM.HM.Apply.more_work(), com.cliffc.aa.HM.HM.Struct.more_work(), com.cliffc.aa.HM.HM.Field.more_work(), and com.cliffc.aa.HM.HM.PrimSyn.more_work().
p()
String com.cliffc.aa.HM.HM.Syntax.p () inherited
Definition at line 393 of file HM.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 394 of file HM.java.
{
       _hmt.get_dups(dups);
       VBitSet visit = new VBitSet();
       p1(sb.i());
       if( DO_HM  ) _hmt .str(sb.p(", HM="), visit,dups);
       if( DO_GCP ) _flow.str(sb.p(", CCP="),visit.clr(),null,false);
       sb.nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.util.VBitSet.clr(), com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM.Syntax.p1(), com.cliffc.aa.HM.HM.Syntax.p2(), com.cliffc.aa.type.Type< T extends Type< T >.str(), and com.cliffc.aa.HM.HM.T2.str().
Referenced by com.cliffc.aa.HM.HM.Syntax.p(), com.cliffc.aa.HM.HM.Lambda.p2(), com.cliffc.aa.HM.HM.Let.p2(), com.cliffc.aa.HM.HM.Apply.p2(), com.cliffc.aa.HM.HM.Struct.p2(), and com.cliffc.aa.HM.HM.Field.p2().
p1()
SB com.cliffc.aa.HM.HM.Ident.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 433 of file HM.java.
 { return sb.p(_name); }
References com.cliffc.aa.HM.HM.Ident._name, and com.cliffc.aa.util.SB.p().
Referenced by com.cliffc.aa.HM.HM.Ident.str().
p2()
SB com.cliffc.aa.HM.HM.Ident.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 434 of file HM.java.
 { return sb; }
prep_lookup_deps()
void com.cliffc.aa.HM.HM.Syntax.prep_lookup_deps (Ident id) package inherited
Reimplemented in com.cliffc.aa.HM.HM.Let, and com.cliffc.aa.HM.HM.Lambda.
Definition at line 377 of file HM.java.
 {}
prep_tree()
int com.cliffc.aa.HM.HM.Ident.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 453 of file HM.java.
{
       prep_tree_impl(par,nongen,work,T2.make_leaf());
       for( Syntax syn = _par; syn!=null; syn = syn._par )
         syn.prep_lookup_deps(this);
       // Lookup, and get the T2 type var and a pointer to the flow type.
       for( Syntax syn = _par; syn!=null; syn = syn._par ) {
         if( syn instanceof Lambda ) {
           Lambda lam = (Lambda)syn;
           if( (_idx = Util.find(lam._args,_name)) != -1 )
             return _init(lam,lam.targ(_idx));
         } else if( syn instanceof Let ) {
           Let let = (Let)syn;  _idx=-1;
           if( Util.eq(let._arg0,_name) )
             return _init(let,let._targ);
         }
       }
       throw new RuntimeException("Parse error, "+_name+" is undefined in "+_par);
     }
References com.cliffc.aa.HM.HM.Let._arg0, com.cliffc.aa.HM.HM.Lambda._args, com.cliffc.aa.HM.HM.Ident._idx, com.cliffc.aa.HM.HM.Ident._init(), com.cliffc.aa.HM.HM.Ident._name, com.cliffc.aa.HM.HM.Syntax._par, com.cliffc.aa.HM.HM.Let._targ, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM.T2.make_leaf(), com.cliffc.aa.HM.HM.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM.Lambda.targ().
prep_tree_impl()
final void com.cliffc.aa.HM.HM.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 370 of file HM.java.
{
       _par = par;
       _hmt = t;
       _flow= Type.XSCALAR;
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.Syntax._nongen, com.cliffc.aa.HM.HM.Syntax._par, com.cliffc.aa.HM.HM.Worklist.push(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Referenced by com.cliffc.aa.HM.HM.Con.prep_tree(), com.cliffc.aa.HM.HM.Ident.prep_tree(), com.cliffc.aa.HM.HM.Lambda.prep_tree(), com.cliffc.aa.HM.HM.Let.prep_tree(), com.cliffc.aa.HM.HM.Apply.prep_tree(), com.cliffc.aa.HM.HM.Struct.prep_tree(), com.cliffc.aa.HM.HM.Field.prep_tree(), and com.cliffc.aa.HM.HM.PrimSyn.prep_tree().
str()
SB com.cliffc.aa.HM.HM.Ident.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 432 of file HM.java.
 { return p1(sb); }
References com.cliffc.aa.HM.HM.Ident.p1().
toString()
final String com.cliffc.aa.HM.HM.Syntax.toString () inherited
Definition at line 390 of file HM.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.HM.HM.Lambda.p1().
val()
Type com.cliffc.aa.HM.HM.Ident.val (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 450 of file HM.java.
{
       return _def instanceof Let ? ((Let)_def)._def._flow : ((Lambda)_def)._types[_idx];
     }
References com.cliffc.aa.HM.HM.Ident._def, com.cliffc.aa.HM.HM.Let._def, com.cliffc.aa.HM.HM.Syntax._flow, and com.cliffc.aa.HM.HM.Ident._idx.
Member Data Documentation
_def
Syntax com.cliffc.aa.HM.HM.Ident._def package
Definition at line 428 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Ident._init(), and com.cliffc.aa.HM.HM.Ident.val().
_flow
Type com.cliffc.aa.HM.HM.Syntax._flow package inherited
Definition at line 351 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM.Lambda.apply(), com.cliffc.aa.HM.HM.Pair1.apply(), com.cliffc.aa.HM.HM.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM.Pair.apply(), com.cliffc.aa.HM.HM.Triple.apply(), com.cliffc.aa.HM.HM.If.apply(), com.cliffc.aa.HM.HM.EQ.apply(), com.cliffc.aa.HM.HM.EQ0.apply(), com.cliffc.aa.HM.HM.IsEmpty.apply(), com.cliffc.aa.HM.HM.NotNil.apply(), com.cliffc.aa.HM.HM.Mul.apply(), com.cliffc.aa.HM.HM.Add.apply(), com.cliffc.aa.HM.HM.Dec.apply(), com.cliffc.aa.HM.HM.Str.apply(), com.cliffc.aa.HM.HM.Factor.apply(), com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.Lambda.Lambda(), com.cliffc.aa.HM.HM.Syntax.more_work_impl(), com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.HM.HM.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM.Ident.val(), com.cliffc.aa.HM.HM.Let.val(), com.cliffc.aa.HM.HM.Apply.val(), com.cliffc.aa.HM.HM.Root.val(), com.cliffc.aa.HM.HM.Struct.val(), com.cliffc.aa.HM.HM.Field.val(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
_hmt
T2 com.cliffc.aa.HM.HM.Syntax._hmt package inherited
Definition at line 343 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Syntax.debug_find(), com.cliffc.aa.HM.HM.Syntax.find(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.HM.HM.Let.prep_tree(), com.cliffc.aa.HM.HM.PrimSyn.prep_tree(), com.cliffc.aa.HM.HM.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM.PrimSyn.PrimSyn(), com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.HM.TestHM.test05(), com.cliffc.aa.HM.TestHM9.test05(), com.cliffc.aa.HM.TestHM.test06(), com.cliffc.aa.HM.TestHM9.test06(), com.cliffc.aa.HM.TestHM.test14(), com.cliffc.aa.HM.TestHM9.test14(), com.cliffc.aa.HM.TestHM.test18(), com.cliffc.aa.HM.TestHM9.test18(), com.cliffc.aa.HM.TestHM.test20(), com.cliffc.aa.HM.TestHM9.test20(), com.cliffc.aa.HM.TestHM9.test32(), com.cliffc.aa.HM.TestHM.test32(), com.cliffc.aa.HM.TestHM9.test33(), com.cliffc.aa.HM.TestHM.test33(), com.cliffc.aa.HM.TestHM9.test34(), com.cliffc.aa.HM.TestHM.test34(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.HM.TestHM.test36(), com.cliffc.aa.HM.TestHM.test39(), com.cliffc.aa.HM.TestHM9.test39(), com.cliffc.aa.HM.TestHM.test40(), com.cliffc.aa.HM.TestHM9.test40(), com.cliffc.aa.HM.TestHM.test41(), com.cliffc.aa.HM.TestHM9.test41(), com.cliffc.aa.HM.TestHM.test42(), com.cliffc.aa.HM.TestHM9.test42(), com.cliffc.aa.HM.TestHM.test43(), com.cliffc.aa.HM.TestHM9.test43(), com.cliffc.aa.HM.TestHM.test44(), com.cliffc.aa.HM.TestHM9.test44(), com.cliffc.aa.HM.TestHM.test45(), com.cliffc.aa.HM.TestHM9.test45(), com.cliffc.aa.HM.TestHM.test49(), com.cliffc.aa.HM.TestHM9.test49(), com.cliffc.aa.HM.TestHM.test50(), com.cliffc.aa.HM.TestHM9.test50(), com.cliffc.aa.HM.TestHM.test51(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.HM.TestHM.test55(), com.cliffc.aa.HM.TestHM.test56(), and com.cliffc.aa.HM.TestHM.test57().
_idt
T2 com.cliffc.aa.HM.HM.Ident._idt package
Definition at line 430 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Ident._init(), and com.cliffc.aa.HM.HM.Ident.idt().
_idx
int com.cliffc.aa.HM.HM.Ident._idx package
Definition at line 429 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Ident.prep_tree(), and com.cliffc.aa.HM.HM.Ident.val().
_name
final String com.cliffc.aa.HM.HM.Ident._name package
Definition at line 427 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Ident.Ident(), com.cliffc.aa.HM.HM.Ident.p1(), and com.cliffc.aa.HM.HM.Ident.prep_tree().
_nongen
VStack com.cliffc.aa.HM.HM.Syntax._nongen package inherited
Definition at line 342 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Ident.add_hm_work(), com.cliffc.aa.HM.HM.Ident.hm(), and com.cliffc.aa.HM.HM.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM.Syntax._par package inherited
Definition at line 341 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Ident.add_hm_work(), com.cliffc.aa.HM.HM.Lambda.add_hm_work(), com.cliffc.aa.HM.HM.Let.add_hm_work(), com.cliffc.aa.HM.HM.Apply.add_hm_work(), com.cliffc.aa.HM.HM.Struct.add_hm_work(), com.cliffc.aa.HM.HM.Field.add_hm_work(), com.cliffc.aa.HM.HM.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.Ident.prep_tree(), and com.cliffc.aa.HM.HM.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM.java