aa: com.cliffc.aa.type.Types Class Reference
com.cliffc.aa.type.Types Class Reference
Classes
class Key
Static Public Member Functions
static Type[] clone (Type[] ts)
static Type[] copyOf (Type[] ts, int len)
static boolean eq (Type[] ts0, Type[] ts1)
static void free (Type[] ts)
static Type[] get (int len)
static Type[] hash_cons (Type[] ts)
static Type[] ts (Type t0)
static Type[] ts (Type t0, Type t1)
static Type[] ts (Type t0, Type t1, Type t2)
static Type[] ts (Type t0, Type t1, Type t2, Type t3)
static Type[] ts (Type t0, Type t1, Type t2, Type t3, Type t4)
static Type[] ts (Type t0, Type t1, Type t2, Type t3, Type t4, Type t5)
Private Member Functions
Types (int len)
Types check ()
boolean check_ ()
boolean check_ (Type[] ts)
Type[] get ()
Type[] hash_cons_ (Type[] ts)
Static Private Member Functions
static Types tary (int len)
Private Attributes
final Ary< Type[]> _free = new Ary<>(new Type[1][],0)
final IHashMap _intern = new IHashMap()
final int _len
Static Private Attributes
static final Key K = new Key(null,0)
static final Ary< Types > TYPEARY = new Ary<>(new Types[1],0)
Detailed Description
Definition at line 9 of file Types.java.
Constructor & Destructor Documentation
Types()
com.cliffc.aa.type.Types.Types (int len) private
Definition at line 49 of file Types.java.
 { _len=len; }
References com.cliffc.aa.type.Types._len.
Referenced by com.cliffc.aa.type.Types.tary().
Member Function Documentation
check()
Types com.cliffc.aa.type.Types.check () private
Definition at line 51 of file Types.java.
 { assert check_();  return this; }
References com.cliffc.aa.type.Types.check_().
Referenced by com.cliffc.aa.type.Types.clone(), com.cliffc.aa.type.Types.copyOf(), com.cliffc.aa.type.Types.get(), com.cliffc.aa.type.Types.hash_cons(), and com.cliffc.aa.type.Types.ts().
check_() [1/2]
boolean com.cliffc.aa.type.Types.check_ () private
Definition at line 52 of file Types.java.
{
     //for( Object k : _intern.keySet() )
     //  assert Key.hash(((Key)k)._ts)==((Key)k)._hash; // Basically asserting array not hacked
     return true;
   }
Referenced by com.cliffc.aa.type.Types.check().
check_() [2/2]
boolean com.cliffc.aa.type.Types.check_ (Type[] ts) private
Definition at line 57 of file Types.java.
{
     K._ts=ts;
     K._hash = Key.hash(ts);
     Key k2 = _intern.get(K);
     return k2._ts==ts;
   }
References com.cliffc.aa.type.Types.Key._hash, com.cliffc.aa.type.Types._intern, com.cliffc.aa.type.Types.Key._ts, com.cliffc.aa.util.IHashMap.get(), com.cliffc.aa.type.Types.Key.hash(), com.cliffc.aa.type.Types.K, and com.cliffc.aa.type.Types.ts().
clone()
static Type [] com.cliffc.aa.type.Types.clone (Type[] ts) static
Definition at line 144 of file Types.java.
{
     Type[] ts2 = tary(ts.length).check().get();
     System.arraycopy(ts,0,ts2,0,ts.length);
     return ts2;
   }
References com.cliffc.aa.type.Types.check(), com.cliffc.aa.type.Types.get(), com.cliffc.aa.type.Types.tary(), and com.cliffc.aa.type.Types.ts().
Referenced by com.cliffc.aa.type.TypeTuple.make_from_arg(), com.cliffc.aa.type.TypeTuple.set(), com.cliffc.aa.type.TypeTuple.sharptr(), and com.cliffc.aa.type.TypeTuple.simple_ptr().
copyOf()
static Type [] com.cliffc.aa.type.Types.copyOf (Type[] ts, int len) static
Definition at line 151 of file Types.java.
{
     Type[] ts2 = tary(len).check().get();
     int minlen = Math.min(len,ts.length);
     System.arraycopy(ts,0,ts2,0,minlen);
     Arrays.fill(ts2,minlen,len,null);
     return ts2;
   }
References com.cliffc.aa.type.Types.check(), com.cliffc.aa.type.Types.get(), com.cliffc.aa.type.Types.tary(), and com.cliffc.aa.type.Types.ts().
eq()
static boolean com.cliffc.aa.type.Types.eq (Type[] ts0, Type[] ts1) static
Definition at line 158 of file Types.java.
{
     if( ts0==ts1 ) return true;
     if( ts0==null || ts1==null ) return false;
     //assert                             tary(ts0.length).check().check_(ts0);
     //assert ts0.length == ts1.length || tary(ts1.length).check().check_(ts1);
     return false;               // No need for deep check, since interned
   }
Referenced by com.cliffc.aa.type.TypeTuple.equals().
free()
static void com.cliffc.aa.type.Types.free (Type[] ts) static
Definition at line 85 of file Types.java.
 { tary(ts.length)._free.push(ts); }
References com.cliffc.aa.type.Types._free, com.cliffc.aa.type.Types.tary(), and com.cliffc.aa.type.Types.ts().
get() [1/2]
Type [] com.cliffc.aa.type.Types.get () private
Definition at line 66 of file Types.java.
{
     if( _free.isEmpty() )
       _free.push(new Type[_len]);
     return _free.pop();
   }
References com.cliffc.aa.type.Types._free, and com.cliffc.aa.type.Types._len.
Referenced by com.cliffc.aa.type.Types.clone(), com.cliffc.aa.type.Types.copyOf(), com.cliffc.aa.node.FunNode.find_type_split(), com.cliffc.aa.type.Types.get(), com.cliffc.aa.type.TypeTuple.make(), com.cliffc.aa.type.Types.ts(), com.cliffc.aa.node.MemSplitNode.value(), com.cliffc.aa.node.CallNode.value(), com.cliffc.aa.type.TypeTuple.widen(), com.cliffc.aa.type.TypeTuple.xdual(), and com.cliffc.aa.type.TypeTuple.xmeet1().
get() [2/2]
static Type [] com.cliffc.aa.type.Types.get (int len) static
Definition at line 84 of file Types.java.
 { return tary(len).check().get(); }
References com.cliffc.aa.type.Types.check(), com.cliffc.aa.type.Types.get(), and com.cliffc.aa.type.Types.tary().
hash_cons()
static Type [] com.cliffc.aa.type.Types.hash_cons (Type[] ts) static
Definition at line 86 of file Types.java.
 { return tary(ts.length).check().hash_cons_(ts); }
References com.cliffc.aa.type.Types.check(), com.cliffc.aa.type.Types.hash_cons_(), com.cliffc.aa.type.Types.tary(), and com.cliffc.aa.type.Types.ts().
Referenced by com.cliffc.aa.type.TypeTuple.make0(), and com.cliffc.aa.type.TypeTuple.xdual().
hash_cons_()
Type [] com.cliffc.aa.type.Types.hash_cons_ (Type[] ts) private
Definition at line 72 of file Types.java.
{
     K._ts=ts;
     K._hash = Key.hash(ts);
     Key k2 = _intern.get(K);
     if( k2 != null ) {
       if( k2._ts!=ts ) _free.push(ts);
       return k2._ts;
     }
     _intern.put(new Key(ts,K._hash));
     return ts;
   }
References com.cliffc.aa.type.Types._free, com.cliffc.aa.type.Types.Key._hash, com.cliffc.aa.type.Types._intern, com.cliffc.aa.type.Types.Key._ts, com.cliffc.aa.util.IHashMap.get(), com.cliffc.aa.type.Types.Key.hash(), com.cliffc.aa.type.Types.K, com.cliffc.aa.util.IHashMap.put(), and com.cliffc.aa.type.Types.ts().
Referenced by com.cliffc.aa.type.Types.hash_cons().
tary()
static Types com.cliffc.aa.type.Types.tary (int len) static private
Definition at line 14 of file Types.java.
{
     Types tary = TYPEARY.atX(len);
     return tary==null ? TYPEARY.setX(len,new Types(len)) : tary;
   }
References com.cliffc.aa.type.Types.TYPEARY, and com.cliffc.aa.type.Types.Types().
Referenced by com.cliffc.aa.type.Types.clone(), com.cliffc.aa.type.Types.copyOf(), com.cliffc.aa.type.Types.free(), com.cliffc.aa.type.Types.get(), com.cliffc.aa.type.Types.hash_cons(), and com.cliffc.aa.type.Types.ts().
ts() [1/6]
static Type [] com.cliffc.aa.type.Types.ts (Type t0) static
Definition at line 90 of file Types.java.
{
     Types t1 = tary(1).check();
     Type[] ts = t1.get();
     ts[0] = t0;
     return ts;
   }
References com.cliffc.aa.type.Types.check(), com.cliffc.aa.type.Types.get(), and com.cliffc.aa.type.Types.tary().
Referenced by com.cliffc.aa.type.Types.check_(), com.cliffc.aa.type.Types.clone(), com.cliffc.aa.type.Types.copyOf(), com.cliffc.aa.type.Types.Key.equals(), com.cliffc.aa.type.Types.free(), com.cliffc.aa.type.Types.Key.hash(), com.cliffc.aa.type.Types.hash_cons(), com.cliffc.aa.type.Types.hash_cons_(), com.cliffc.aa.type.Types.Key.Key(), com.cliffc.aa.type.TypeFunSig.make(), com.cliffc.aa.type.TypeTuple.make(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.type.TestType.testStructTuple(), and com.cliffc.aa.type.Types.ts().
ts() [2/6]
static Type [] com.cliffc.aa.type.Types.ts (Type t0, Type t1) static
Definition at line 96 of file Types.java.
{
     Types t2 = tary(2).check();
     Type[] ts = t2.get();
     ts[0] = t0;
     ts[1] = t1;
     return ts;
   }
References com.cliffc.aa.type.Types.check(), com.cliffc.aa.type.Types.get(), com.cliffc.aa.type.Types.tary(), and com.cliffc.aa.type.Types.ts().
ts() [3/6]
static Type [] com.cliffc.aa.type.Types.ts (Type t0, Type t1, Type t2) static
Definition at line 103 of file Types.java.
{
     Types t3 = tary(3).check();
     Type[] ts = t3.get();
     ts[0] = t0;
     ts[1] = t1;
     ts[2] = t2;
     return ts;
   }
References com.cliffc.aa.type.Types.check(), com.cliffc.aa.type.Types.get(), com.cliffc.aa.type.Types.tary(), and com.cliffc.aa.type.Types.ts().
ts() [4/6]
static Type [] com.cliffc.aa.type.Types.ts (Type t0, Type t1, Type t2, Type t3) static
Definition at line 111 of file Types.java.
{
     Types t4 = tary(4).check();
     Type[] ts = t4.get();
     ts[0] = t0;
     ts[1] = t1;
     ts[2] = t2;
     ts[3] = t3;
     return ts;
   }
References com.cliffc.aa.type.Types.check(), com.cliffc.aa.type.Types.get(), com.cliffc.aa.type.Types.tary(), and com.cliffc.aa.type.Types.ts().
ts() [5/6]
static Type [] com.cliffc.aa.type.Types.ts (Type t0, Type t1, Type t2, Type t3, Type t4) static
Definition at line 120 of file Types.java.
{
     Types t5 = tary(5).check();
     Type[] ts = t5.get();
     ts[0] = t0;
     ts[1] = t1;
     ts[2] = t2;
     ts[3] = t3;
     ts[4] = t4;
     return ts;
   }
References com.cliffc.aa.type.Types.check(), com.cliffc.aa.type.Types.get(), com.cliffc.aa.type.Types.tary(), and com.cliffc.aa.type.Types.ts().
ts() [6/6]
static Type [] com.cliffc.aa.type.Types.ts (Type t0, Type t1, Type t2, Type t3, Type t4, Type t5) static
Definition at line 130 of file Types.java.
{
     Types t6 = tary(6).check();
     Type[] ts = t6.get();
     ts[0] = t0;
     ts[1] = t1;
     ts[2] = t2;
     ts[3] = t3;
     ts[4] = t4;
     ts[5] = t5;
     return ts;
   }
References com.cliffc.aa.type.Types.check(), com.cliffc.aa.type.Types.get(), com.cliffc.aa.type.Types.tary(), and com.cliffc.aa.type.Types.ts().
Member Data Documentation
_free
final Ary<Type[]> com.cliffc.aa.type.Types._free = new Ary<>(new Type[1][],0) private
Definition at line 48 of file Types.java.
Referenced by com.cliffc.aa.type.Types.free(), com.cliffc.aa.type.Types.get(), and com.cliffc.aa.type.Types.hash_cons_().
_intern
final IHashMap com.cliffc.aa.type.Types._intern = new IHashMap() private
Definition at line 47 of file Types.java.
Referenced by com.cliffc.aa.type.Types.check_(), and com.cliffc.aa.type.Types.hash_cons_().
_len
final int com.cliffc.aa.type.Types._len private
Definition at line 46 of file Types.java.
Referenced by com.cliffc.aa.type.Types.get(), and com.cliffc.aa.type.Types.Types().
K
final Key com.cliffc.aa.type.Types.K = new Key(null,0) static private
Definition at line 19 of file Types.java.
Referenced by com.cliffc.aa.type.Types.check_(), and com.cliffc.aa.type.Types.hash_cons_().
TYPEARY
final Ary<Types> com.cliffc.aa.type.Types.TYPEARY = new Ary<>(new Types[1],0) static private
Definition at line 11 of file Types.java.
Referenced by com.cliffc.aa.type.Types.tary().
The documentation for this class was generated from the following file:
Types.java