aa: com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T > Class Template Reference
com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T > Class Template Reference abstract
Public Member Functions
void add_flow_def_extra (Node chg)
void add_reduce_extra ()
TypeMem all_live ()
FunPtrNode as_fun (GVNGCM gvn)
NewNode copy (boolean copy_edges)
boolean equals (Object o)
int hashCode ()
Node ideal_reduce ()
TypeMem live_use (GVNGCM.Mode opt_mode, Node def)
MrgProjNode mrg ()
final void sets (T ts)
final void setsm (T ts)
Type value (GVNGCM.Mode opt_mode)
String xstr ()
Static Public Member Functions
static Ary< NewPrimNode > INTRINSICS ()
static void reset ()
Public Attributes
int _alias
final String _name
TypeMemPtr _tptr
T _ts
Package Functions
NewPrimNode (byte op, int parent_alias, T to, String name, boolean reads, int op_prec, Type... args)
String bal_close ()
abstract T dead_type ()
BitsAlias escapees ()
Node fld (int fld)
boolean is_unused ()
void kill2 ()
ProjNode ptr ()
String str ()
abstract TypeObj valueobj ()
Static Package Functions
[static initializer]
static int def_idx (int fld)
Package Attributes
TypeObj _crushed
final int _op_prec
final boolean _reads
final TypeFunSig _sig
Private Member Functions
void _init (int alias, T ts)
boolean captured ()
Static Private Attributes
static final Ary< NewPrimNode > INTRINSICS = new Ary<>(NewPrimNode.class)
Detailed Description
Definition at line 170 of file NewNode.java.
Constructor & Destructor Documentation
NewPrimNode()
com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.NewPrimNode (byte op, int parent_alias, T to, String name, boolean reads, int op_prec, Type... args) package
Definition at line 175 of file NewNode.java.
{
       super(op,parent_alias,to);
       _name = name;
       _reads = reads;
       assert (reads == (args[MEM_IDX]!=TypeMem.ALLMEM)); // If reading, then memory has some requirements
       args[DSP_IDX] = Type.ALL; // No display
       _sig = TypeFunSig.make(TypeTuple.RET,TypeTuple.make_args(args));
       _op_prec = op_prec;
     }
Member Function Documentation
[static initializer]()
com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.[static initializer] static package
_init()
void com.cliffc.aa.node.NewNode< T extends TypeObj< T >._init (int alias, T ts) private inherited
Definition at line 43 of file NewNode.java.
{
     if( _elock ) unelock();    // Unlock before changing hash
     _alias = alias;
     _tptr = TypeMemPtr.make(BitsAlias.make0(alias),TypeObj.ISUSED);
     sets(ts);
   }
add_flow_def_extra()
void com.cliffc.aa.node.NewNode< T extends TypeObj< T >.add_flow_def_extra (Node chg) inherited
Definition at line 72 of file NewNode.java.
{
     if( chg instanceof MrgProjNode && chg._live.at(_alias)==TypeObj.UNUSED )
       Env.GVN.add_reduce(chg);
   }
add_reduce_extra()
void com.cliffc.aa.node.NewNode< T extends TypeObj< T >.add_reduce_extra inherited
Definition at line 77 of file NewNode.java.
{
     Env.GVN.add_flow(Env.DEFMEM);
   }
all_live()
TypeMem com.cliffc.aa.node.NewNode< T extends TypeObj< T >.all_live inherited
Definition at line 86 of file NewNode.java.
 { return TypeMem.ALLMEM; }
as_fun()
FunPtrNode com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.as_fun (GVNGCM gvn)
Definition at line 198 of file NewNode.java.
{
       try(GVNGCM.Build<FunPtrNode> X = gvn.new Build<>()) {
         assert in(0)==null && _uses._len==0;
         FunNode  fun = ( FunNode) X.xform(new  FunNode(this).add_def(Env.ALL_CTRL));
         ParmNode rpc = (ParmNode) X.xform(new ParmNode(0,"rpc",fun,Env.ALL_CALL,null));
         Node memp= X.xform(new ParmNode(MEM_IDX,_sig._args[MEM_IDX],fun, TypeMem.MEM, Env.DEFMEM,null));
         fun._bal_close = bal_close();
         // Add input edges to the intrinsic
         add_def(_reads ? memp : null); // Memory  for the primitive in slot MEM_IDX
         add_def(null);                 // Closure for the primitive in slot DSP_IDX
         for( int i=ARG_IDX; i<_sig.nargs(); i++ ) // Args follow
           add_def( X.xform(new ParmNode(i,_sig._args[i],fun, (ConNode)Node.con(_sig.arg(i).simple_ptr()),null)));
         NewNode nnn = (NewNode)X.xform(this);
         Node mem = Env.DEFMEM.make_mem_proj(nnn,memp);
         Node ptr = X.xform(new ProjNode(nnn,REZ_IDX));
         RetNode ret = (RetNode)X.xform(new RetNode(fun,mem,ptr,rpc,fun));
         return (X._ret = new FunPtrNode(_name,ret));
       }
     }
bal_close()
String com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.bal_close () package
Definition at line 184 of file NewNode.java.
 { return null; }
Referenced by com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun().
captured()
boolean com.cliffc.aa.node.NewNode< T extends TypeObj< T >.captured private inherited
Definition at line 116 of file NewNode.java.
{
     if( _keep > 0 ) return false;
     if( _uses._len==0 ) return false; // Dead or being created
     Node mem = _uses.at(0);
     // If only either address or memory remains, then memory contents are dead
     if( _uses._len==1 ) {
       if( mem instanceof MrgProjNode ) return true; // No pointer, just dead memory
       // Just a pointer; currently on Strings become memory constants and
       // constant-fold - leaving the allocation dead.
       return !(val(1) instanceof TypeStr);
     }
     Node ptr = _uses.at(1);
     if( ptr instanceof MrgProjNode ) ptr = _uses.at(0); // Get ptr not mem
     if( ptr._keep>0 ) return false;
     // Scan for memory contents being unreachable.
     // Really stupid!
     for( Node use : ptr._uses )
       if( !(use instanceof IfNode) )
         return false;
     // Only used to nil-check (always not-nil) and equality (always unequal to
     // other aliases).
     return true;
   }
copy()
NewNode com.cliffc.aa.node.NewNode< T extends TypeObj< T >.copy (boolean copy_edges) inherited
Definition at line 143 of file NewNode.java.
{
     // Split the original '_alias' class into 2 sub-aliases
     NewNode<T> nnn = (NewNode<T>)super.copy(copy_edges);
     nnn._init(BitsAlias.new_alias(_alias),_ts);      // Children alias classes, split from parent
     _init(BitsAlias.new_alias(_alias),_ts); // The original NewNode also splits from the parent alias
     Env.GVN.add_flow(this);     // Alias changes flow
     return nnn;
   }
dead_type()
abstract T com.cliffc.aa.node.NewNode< T extends TypeObj< T >.dead_type abstract package inherited
def_idx()
static int com.cliffc.aa.node.NewNode< T extends TypeObj< T >.def_idx (int fld) static package inherited
Definition at line 52 of file NewNode.java.
 { return fld+1; } // Skip ctl in slot 0
equals()
boolean com.cliffc.aa.node.NewNode< T extends TypeObj< T >.equals (Object o) inherited
Definition at line 157 of file NewNode.java.
 {  return this==o; }
escapees()
BitsAlias com.cliffc.aa.node.NewNode< T extends TypeObj< T >.escapees package inherited
Definition at line 98 of file NewNode.java.
 { return _tptr._aliases; }
fld()
Node com.cliffc.aa.node.NewNode< T extends TypeObj< T >.fld (int fld) package inherited
Definition at line 53 of file NewNode.java.
 { return in(def_idx(fld)); } // Node for field#
hashCode()
int com.cliffc.aa.node.NewNode< T extends TypeObj< T >.hashCode inherited
Definition at line 152 of file NewNode.java.
 { return super.hashCode()+ _alias; }
ideal_reduce()
Node com.cliffc.aa.node.NewNode< T extends TypeObj< T >.ideal_reduce inherited
Definition at line 64 of file NewNode.java.
{
     // If either the address or memory is not looked at then the memory
     // contents are dead.  The object might remain as a 'gensym' or 'sentinel'
     // for identity tests.
     if( _defs._len > 1 && captured() ) { kill2(); return this; }
     return null;
   }
INTRINSICS()
static Ary<NewPrimNode> com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.INTRINSICS () static
Definition at line 189 of file NewNode.java.
{
       if( INTRINSICS.isEmpty() ) {
         NewAryNode.add_libs(INTRINSICS);
         NewStrNode.add_libs(INTRINSICS);
       }
       return INTRINSICS;
     }
is_unused()
boolean com.cliffc.aa.node.NewNode< T extends TypeObj< T >.is_unused package inherited
Definition at line 100 of file NewNode.java.
 { return _ts==dead_type(); }
kill2()
void com.cliffc.aa.node.NewNode< T extends TypeObj< T >.kill2 package inherited
Definition at line 102 of file NewNode.java.
                {
     unelock();
     while( !is_dead() && _defs._len > 1 )
       pop();                    // Kill all fields except memory
     _crushed = _ts = dead_type();
     _tptr = TypeMemPtr.make(BitsAlias.make0(_alias),TypeObj.UNUSED);
     Env.DEFMEM.set_def(_alias,Node.con(TypeObj.UNUSED));
     Env.GVN.revalive(this,ProjNode.proj(this,0),Env.DEFMEM);
     if( is_dead() ) return;
     for( Node use : _uses )
       Env.GVN.add_flow_uses(use); // Get FPtrs from MrgProj, and dead Ptrs into New
   }
live_use()
TypeMem com.cliffc.aa.node.NewNode< T extends TypeObj< T >.live_use (GVNGCM.Mode opt_mode, Node def) inherited
Definition at line 89 of file NewNode.java.
{
     TypeObj to = _live.at(_alias);
     return to.above_center() ? TypeMem.DEAD : TypeMem.ESCAPE;
   }
mrg()
MrgProjNode com.cliffc.aa.node.NewNode< T extends TypeObj< T >.mrg inherited
Definition at line 158 of file NewNode.java.
{
     Node ptr = _uses.at(0);
     if( !(ptr instanceof MrgProjNode) ) ptr = _uses.at(1);
     return (MrgProjNode)ptr;
   }
ptr()
ProjNode com.cliffc.aa.node.NewNode< T extends TypeObj< T >.ptr package inherited
Definition at line 163 of file NewNode.java.
                  {
     Node ptr = _uses.at(0);
     if( ptr instanceof MrgProjNode ) ptr = _uses.at(1);
     return (ProjNode)ptr;
   }
reset()
static void com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.reset () static
Definition at line 188 of file NewNode.java.
 { INTRINSICS.clear(); }
Referenced by com.cliffc.aa.Env.top_reset().
sets()
final void com.cliffc.aa.node.NewNode< T extends TypeObj< T >.sets (T ts) inherited
Definition at line 57 of file NewNode.java.
{
     _ts = ts;
     _crushed = ts.crush();
   }
setsm()
final void com.cliffc.aa.node.NewNode< T extends TypeObj< T >.setsm (T ts) inherited
Definition at line 62 of file NewNode.java.
 { assert ts.isa(_ts); sets(ts); }
str()
String com.cliffc.aa.node.NewNode< T extends TypeObj< T >.str package inherited
Definition at line 50 of file NewNode.java.
 { return "New"+_ts; } // Inline less-short name
value()
Type com.cliffc.aa.node.NewNode< T extends TypeObj< T >.value (GVNGCM.Mode opt_mode) inherited
Definition at line 81 of file NewNode.java.
{
     return TypeTuple.make(Type.CTRL, is_unused() ? TypeObj.UNUSED : valueobj(),_tptr);   // Complex obj, simple ptr.
   }
valueobj()
abstract TypeObj com.cliffc.aa.node.NewNode< T extends TypeObj< T >.valueobj abstract package inherited
xstr()
String com.cliffc.aa.node.NewNode< T extends TypeObj< T >.xstr inherited
Definition at line 49 of file NewNode.java.
 { return "New"+"*"+_alias; } // Self short name
Member Data Documentation
_alias
int com.cliffc.aa.node.NewNode< T extends TypeObj< T >._alias inherited
Definition at line 20 of file NewNode.java.
_crushed
TypeObj com.cliffc.aa.node.NewNode< T extends TypeObj< T >._crushed package inherited
Definition at line 31 of file NewNode.java.
_name
final String com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >._name
Definition at line 171 of file NewNode.java.
Referenced by com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun(), and com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.NewPrimNode().
_op_prec
final int com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >._op_prec package
Definition at line 174 of file NewNode.java.
Referenced by com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.NewPrimNode().
_reads
final boolean com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >._reads package
Definition at line 173 of file NewNode.java.
Referenced by com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun(), and com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.NewPrimNode().
_sig
final TypeFunSig com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >._sig package
Definition at line 172 of file NewNode.java.
Referenced by com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun(), and com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.NewPrimNode().
_tptr
TypeMemPtr com.cliffc.aa.node.NewNode< T extends TypeObj< T >._tptr inherited
Definition at line 34 of file NewNode.java.
_ts
T com.cliffc.aa.node.NewNode< T extends TypeObj< T >._ts inherited
Definition at line 25 of file NewNode.java.
INTRINSICS
final Ary<NewPrimNode> com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.INTRINSICS = new Ary<>(NewPrimNode.class) static private
Definition at line 186 of file NewNode.java.
Referenced by com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.INTRINSICS(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.reset(), com.cliffc.aa.node.TestNode.testMonotonic(), and com.cliffc.aa.Env.top_scope().
The documentation for this class was generated from the following file:
NewNode.java