aa: com.cliffc.aa.GVNGCM.Build< N extends Node > Class Template Reference
com.cliffc.aa.GVNGCM.Build< N extends Node > Class Template Reference
Public Member Functions
Node add (Node n)
void close ()
Node init (Node n)
Node xform (Node n)
Public Attributes
N _ret
Package Functions
public< M extends Node > M init2 (M n)
Package Attributes
Ary< Node > _tmps = new Ary<>(new Node[1],0)
Detailed Description
Definition at line 356 of file GVNGCM.java.
Member Function Documentation
add()
Node com.cliffc.aa.GVNGCM.Build< N extends Node >.add (Node n)
Definition at line 369 of file GVNGCM.java.
{
       assert _tmps._len<16;             // Time for a BitSet
       if( _tmps.find(n)!=-1 ) return n; // Already flowed & keeped
       return _tmps.push(n.keep());
     }
References com.cliffc.aa.GVNGCM.Build< N extends Node >._tmps, and com.cliffc.aa.node.Node.keep().
close()
void com.cliffc.aa.GVNGCM.Build< N extends Node >.close ()
Definition at line 376 of file GVNGCM.java.
{
       for( Node tmp : _tmps )
         add_unuse(tmp.unkeep()); // Needs proper liveness at least
     }
References com.cliffc.aa.GVNGCM.Build< N extends Node >._tmps, and com.cliffc.aa.GVNGCM.add_unuse().
init()
Node com.cliffc.aa.GVNGCM.Build< N extends Node >.init (Node n)
Definition at line 363 of file GVNGCM.java.
{
       assert _tmps._len<16;             // Time for a BitSet
       if( _tmps.find(n)!=-1 ) return n; // Already flowed & keeped
       n.keep().do_flow(); // Update types, and future Parser uses, so always alive
       return _tmps.push(n);
     }
References com.cliffc.aa.GVNGCM.Build< N extends Node >._tmps, and com.cliffc.aa.node.Node.keep().
Referenced by com.cliffc.aa.GVNGCM.Build< N extends Node >.init2(), and com.cliffc.aa.GVNGCM.Build< N extends Node >.xform().
init2()
public<M extends Node> M com.cliffc.aa.GVNGCM.Build< N extends Node >.init2 (M n) package
Definition at line 375 of file GVNGCM.java.
 { return (M)init(n); }
References com.cliffc.aa.GVNGCM.Build< N extends Node >.init().
xform()
Node com.cliffc.aa.GVNGCM.Build< N extends Node >.xform (Node n)
Definition at line 359 of file GVNGCM.java.
{
       Node x = n.do_reduce();   // Attempt to reduce
       return init(x==null ? n : x);
     }
References com.cliffc.aa.node.Node.do_reduce(), and com.cliffc.aa.GVNGCM.Build< N extends Node >.init().
Member Data Documentation
_ret
N com.cliffc.aa.GVNGCM.Build< N extends Node >._ret
Definition at line 358 of file GVNGCM.java.
_tmps
Ary<Node> com.cliffc.aa.GVNGCM.Build< N extends Node >._tmps = new Ary<>(new Node[1],0) package
Definition at line 357 of file GVNGCM.java.
Referenced by com.cliffc.aa.GVNGCM.Build< N extends Node >.add(), com.cliffc.aa.GVNGCM.Build< N extends Node >.close(), and com.cliffc.aa.GVNGCM.Build< N extends Node >.init().
The documentation for this class was generated from the following file:
GVNGCM.java