aa: com.cliffc.aa.HM.TestHM9 Class Reference
com.cliffc.aa.HM.TestHM9 Class Reference
Public Member Functions
void reset ()
void test00 ()
void test01 ()
void test02 ()
void test03 ()
void test04 ()
void test05 ()
void test06 ()
void test07 ()
void test08 ()
void test09 ()
void test10 ()
void test11 ()
void test12 ()
void test13 ()
void test14 ()
void test15 ()
void test16 ()
void test17 ()
void test18 ()
void test19 ()
void test20 ()
void test21 ()
void test22 ()
void test23 ()
void test24 ()
void test25 ()
void test26 ()
void test27 ()
void test28 ()
void test29 ()
void test30 ()
void test31 ()
void test32 ()
void test33 ()
void test34 ()
void test35 ()
void test36 ()
void test37 ()
void test38 ()
void test39 ()
void test40 ()
void test41 ()
void test42 ()
void test43 ()
void test44 ()
void test45 ()
void test46 ()
void test47 ()
void test48 ()
void test49 ()
void test50 ()
Private Member Functions
void run (String prog, String rez_hm, Type rez_gcp)
Static Private Member Functions
static TypeMemPtr build_cycle (int alias, boolean nil, Type fld)
static TypeFunSig tfs (Type ret)
Static Private Attributes
static final String[] N1V1 = new String[]{"^","n1","v1"}
static final TypeFunSig ret_tuple2 = tfs(tuple2)
static final TypeMemPtr tuple2 = TypeMemPtr.make(7,TypeStruct.make(Type.SCALAR, Type.SCALAR))
static final TypeMemPtr tuple55 = TypeMemPtr.make(7,TypeStruct.make(TypeInt.con(5),TypeInt.con(5)))
static final TypeMemPtr tuple82 = TypeMemPtr.make(7,TypeStruct.make(TypeInt.NINT8, TypeInt.NINT8))
static final TypeMemPtr tuple9 = TypeMemPtr.make(9,TypeStruct.make(TypeStruct.flds(Type.SCALAR,Type.SCALAR)))
static final TypeMemPtr tuplen2 = TypeMemPtr.make(7,TypeStruct.make(Type.NSCALR, Type.NSCALR))
static final String[] XY = new String[]{"^","x","y"}
Detailed Description
Definition at line 12 of file TestHM9.java.
Member Function Documentation
build_cycle()
static TypeMemPtr com.cliffc.aa.HM.TestHM9.build_cycle (int alias, boolean nil, Type fld) static private
Definition at line 239 of file TestHM9.java.
{
     // Build a cycle of length 2.
     BitsAlias aliases = BitsAlias.make0(alias);
     if( nil ) aliases = aliases.meet_nil();
     TypeMemPtr cycle_ptr0 = TypeMemPtr.make(aliases,TypeObj.XOBJ);
     TypeStruct cycle_str1 = TypeStruct.make(TypeFld.NO_DISP,TypeFld.malloc("n1",cycle_ptr0,1),TypeFld.malloc("v1",fld,1));
     TypeMemPtr cycle_ptr1 = TypeMemPtr.make(aliases,cycle_str1);
     TypeStruct cycle_str2 = TypeStruct.make(TypeFld.NO_DISP,TypeFld.malloc("n1",cycle_ptr1,1),TypeFld.malloc("v1",fld,1));
     TypeStruct cycle_strn = cycle_str2.approx(1,alias);
     TypeMemPtr cycle_ptrn = (TypeMemPtr)cycle_strn.at(1);
     return cycle_ptrn;
   }
References com.cliffc.aa.type.TypeStruct.approx(), com.cliffc.aa.type.TypeStruct.at(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.BitsAlias.make0(), com.cliffc.aa.type.TypeFld.malloc(), com.cliffc.aa.type.Bits< B extends Bits< B >.meet_nil(), com.cliffc.aa.type.TypeFld.NO_DISP, and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.XOBJ.
Referenced by com.cliffc.aa.HM.TestHM9.test32(), com.cliffc.aa.HM.TestHM9.test33(), and com.cliffc.aa.HM.TestHM9.test34().
reset()
void com.cliffc.aa.HM.TestHM9.reset ()
Definition at line 14 of file TestHM9.java.
 { HM.reset(); }
References com.cliffc.aa.HM.HM.reset().
run()
void com.cliffc.aa.HM.TestHM9.run (String prog, String rez_hm, Type rez_gcp) private
Definition at line 16 of file TestHM9.java.
{
     Root syn = HM9.hm(prog);
     if( HM.DO_HM )
       assertEquals(rez_hm,syn._hmt.p());
     if( HM.DO_GCP )
       assertEquals(rez_gcp,syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), and com.cliffc.aa.HM.HM.T2.p().
Referenced by com.cliffc.aa.HM.TestHM9.test00(), com.cliffc.aa.HM.TestHM9.test01(), com.cliffc.aa.HM.TestHM9.test02(), com.cliffc.aa.HM.TestHM9.test03(), com.cliffc.aa.HM.TestHM9.test04(), com.cliffc.aa.HM.TestHM9.test07(), com.cliffc.aa.HM.TestHM9.test08(), com.cliffc.aa.HM.TestHM9.test09(), com.cliffc.aa.HM.TestHM9.test10(), com.cliffc.aa.HM.TestHM9.test11(), com.cliffc.aa.HM.TestHM9.test12(), com.cliffc.aa.HM.TestHM9.test13(), com.cliffc.aa.HM.TestHM9.test15(), com.cliffc.aa.HM.TestHM9.test16(), com.cliffc.aa.HM.TestHM9.test17(), com.cliffc.aa.HM.TestHM9.test19(), com.cliffc.aa.HM.TestHM9.test21(), com.cliffc.aa.HM.TestHM9.test22(), com.cliffc.aa.HM.TestHM9.test23(), com.cliffc.aa.HM.TestHM9.test24(), com.cliffc.aa.HM.TestHM9.test25(), com.cliffc.aa.HM.TestHM9.test26(), com.cliffc.aa.HM.TestHM9.test27(), com.cliffc.aa.HM.TestHM9.test28(), com.cliffc.aa.HM.TestHM9.test29(), com.cliffc.aa.HM.TestHM9.test30(), com.cliffc.aa.HM.TestHM9.test31(), com.cliffc.aa.HM.TestHM9.test35(), com.cliffc.aa.HM.TestHM9.test37(), com.cliffc.aa.HM.TestHM9.test38(), com.cliffc.aa.HM.TestHM9.test46(), com.cliffc.aa.HM.TestHM9.test47(), and com.cliffc.aa.HM.TestHM9.test48().
test00()
void com.cliffc.aa.HM.TestHM9.test00 ()
Definition at line 38 of file TestHM9.java.
 { run( "fred",null,null); }
References com.cliffc.aa.HM.TestHM9.run().
test01()
void com.cliffc.aa.HM.TestHM9.test01 ()
Definition at line 40 of file TestHM9.java.
                              { run( "3" ,
                                     "3", TypeInt.con(3));  }
References com.cliffc.aa.type.TypeInt.con(), and com.cliffc.aa.HM.TestHM9.run().
test02()
void com.cliffc.aa.HM.TestHM9.test02 ()
Definition at line 43 of file TestHM9.java.
                              { run( "(pair1 3)" ,
                                     "{ A -> ( 3, $A)[7] }", tfs(TypeMemPtr.make(7,TypeStruct.make(TypeInt.con(3),Type.SCALAR)))); }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM9.tfs().
test03()
void com.cliffc.aa.HM.TestHM9.test03 ()
Definition at line 46 of file TestHM9.java.
                              { run( "{ z -> (pair (z 0) (z \"abc\")) }" ,
                                     "{ { *[0,4]\"abc\"? -> A } -> ( $A, $A)[7] }", tfs(tuple2)); }
References com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.HM.TestHM9.tfs(), and com.cliffc.aa.HM.TestHM9.tuple2.
test04()
void com.cliffc.aa.HM.TestHM9.test04 ()
Definition at line 49 of file TestHM9.java.
                              { run( "fact = { n -> (if (?0 n) 1 (* n (fact (dec n))))}; fact",
                                     "{ int64 -> int64 }", tfs(TypeInt.INT64) ); }
References com.cliffc.aa.type.TypeInt.INT64, com.cliffc.aa.HM.TestHM9.run(), and com.cliffc.aa.HM.TestHM9.tfs().
test05()
void com.cliffc.aa.HM.TestHM9.test05 ()
Definition at line 54 of file TestHM9.java.
{
     Root syn = HM9.hm("({ x -> (pair (x 3) (x 5)) } {y->y})");
     if( HM.DO_HM )
       assertEquals("( nint8, nint8)[7]",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM )
         assertEquals(tuple82,syn.flow_type());
       else
         assertEquals(tuple82,syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM.T2.p(), and com.cliffc.aa.HM.TestHM9.tuple82.
test06()
void com.cliffc.aa.HM.TestHM9.test06 ()
Definition at line 65 of file TestHM9.java.
{
     Root syn = HM9.hm("id={x->x}; (pair (id 3) (id \"abc\"))");
     if( HM.DO_HM ) // HM is sharper here than in test05, because id is generalized per each use site
       assertEquals("( 3, *[4]\"abc\")[7]",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM )
         assertEquals(TypeMemPtr.make(7,TypeStruct.make(TypeInt.con(3),TypeMemPtr.make(4,TypeStr.ABC))),syn.flow_type());
       else
         assertEquals(tuplen2,syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeStr.ABC, com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.HM.HM.T2.p(), and com.cliffc.aa.HM.TestHM9.tuplen2.
test07()
void com.cliffc.aa.HM.TestHM9.test07 ()
Definition at line 77 of file TestHM9.java.
                              { run( "{ f -> (f f) }",
     // We can argue the pretty-print should print:
     //                              "  A:{ $A -> B }"
                                     "{ A:{ $A -> B } -> $B }", tfs(Type.SCALAR) ); }
References com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM9.tfs().
test08()
void com.cliffc.aa.HM.TestHM9.test08 ()
Definition at line 82 of file TestHM9.java.
                              { run( "g = {f -> 5}; (g g)",
                                     "5", TypeInt.con(5)); }
References com.cliffc.aa.type.TypeInt.con(), and com.cliffc.aa.HM.TestHM9.run().
test09()
void com.cliffc.aa.HM.TestHM9.test09 ()
Definition at line 86 of file TestHM9.java.
                              { run( "{ g -> f = { x -> g }; (pair (f 3) (f \"abc\"))}",
                                     "{ A -> ( $A, $A)[7] }", ret_tuple2); }
References com.cliffc.aa.HM.TestHM9.ret_tuple2, and com.cliffc.aa.HM.TestHM9.run().
test10()
void com.cliffc.aa.HM.TestHM9.test10 ()
Definition at line 89 of file TestHM9.java.
                              { run( "{ f g -> (f g)}",
                                     "{ { A -> B } $A -> $B }", tfs(Type.SCALAR) ); }
References com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM9.tfs().
test11()
void com.cliffc.aa.HM.TestHM9.test11 ()
Definition at line 93 of file TestHM9.java.
                              { run( "{ f g -> { arg -> (g (f arg))} }",
                                     "{ { A -> B } { $B -> C } -> { $A -> $C } }", tfs(tfs(Type.SCALAR))); }
References com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM9.tfs().
test12()
void com.cliffc.aa.HM.TestHM9.test12 ()
Definition at line 97 of file TestHM9.java.
                              { run( "map = { fun -> { x -> 2 } }; ((map 3) 5)",
                                     "2", TypeInt.con(2)); }
References com.cliffc.aa.type.TypeInt.con(), and com.cliffc.aa.HM.TestHM9.run().
test13()
void com.cliffc.aa.HM.TestHM9.test13 ()
Definition at line 101 of file TestHM9.java.
                              { run( "map = { fun -> { x -> (fun x)}}; { p -> 5 }",
                                     "{ A -> 5 }", tfs(TypeInt.con(5))); }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.TestHM9.run(), and com.cliffc.aa.HM.TestHM9.tfs().
test14()
void com.cliffc.aa.HM.TestHM9.test14 ()
Definition at line 107 of file TestHM9.java.
{
     Root syn = HM9.hm("map = { fun -> { x -> (fun x)}};"+
                      "(pair ((map str) 5) ((map factor) 2.3))");
     if( HM.DO_HM )
       assertEquals("( *[4]str, flt64)[7]",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM )
         assertEquals(TypeMemPtr.make(7,TypeStruct.make(TypeMemPtr.STRPTR,TypeFlt.FLT64)),syn.flow_type());
       else
         assertEquals(tuple2,syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.type.TypeFlt.FLT64, com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.TypeMemPtr.STRPTR, and com.cliffc.aa.HM.TestHM9.tuple2.
test15()
void com.cliffc.aa.HM.TestHM9.test15 ()
Definition at line 120 of file TestHM9.java.
                              { run("map = { fun x -> (fun x)}; (map {a->3} 5)",
                                    "3", TypeInt.con(3)); }
References com.cliffc.aa.type.TypeInt.con(), and com.cliffc.aa.HM.TestHM9.run().
test16()
void com.cliffc.aa.HM.TestHM9.test16 ()
Definition at line 124 of file TestHM9.java.
                              { run("map = { fun x -> (fun x)}; (map { a-> (pair a a)} 5)",
                                    "( 5, 5)[7]", tuple55); }
References com.cliffc.aa.HM.TestHM9.run(), and com.cliffc.aa.HM.TestHM9.tuple55.
test17()
void com.cliffc.aa.HM.TestHM9.test17 ()
Definition at line 127 of file TestHM9.java.
                              { run("fcn = { p -> { a -> (pair a a) }};"+
                                    "map = { fun x -> (fun x)};"+
                                    "{ q -> (map (fcn q) 5)}",
                                    "{ A -> ( 5, 5)[7] }", tfs(tuple55)); }
References com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.HM.TestHM9.tfs(), and com.cliffc.aa.HM.TestHM9.tuple55.
test18()
void com.cliffc.aa.HM.TestHM9.test18 ()
Definition at line 142 of file TestHM9.java.
{
     Root syn = HM9.hm("fcn = {p -> (if p {a -> (pair a a)} {b -> (pair b (pair 3 b))})};"+
                      "map = { fun x -> (fun x)};"+
                      "{ q -> (map (fcn q) 5)}");
     if( HM.DO_HM )
       assertEquals("{ A -> ( B:Cannot unify A:( 3, $A)[7] and 5, $B)[7] }",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM )
         assertEquals(tfs(TypeMemPtr.make(7,TypeStruct.make(Type.XNSCALR,TypeMemPtr.make(7,TypeStruct.make(TypeInt.con(3),Type.XNSCALR))))),syn.flow_type());
       else
         assertEquals(tfs(TypeMemPtr.make(7,TypeStruct.make(TypeInt.con(5),Type.NSCALR))),syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.Type< T extends Type< T >.NSCALR, com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.HM.TestHM9.tfs(), and com.cliffc.aa.type.Type< T extends Type< T >.XNSCALR.
test19()
void com.cliffc.aa.HM.TestHM9.test19 ()
Definition at line 155 of file TestHM9.java.
                              { run("cons ={x y-> {cadr -> (cadr x y)}};"+
                                    "cdr ={mycons -> (mycons { p q -> q})};"+
                                    "(cdr (cons 2 3))",
                                    "3", TypeInt.con(3)); }
References com.cliffc.aa.type.TypeInt.con(), and com.cliffc.aa.HM.TestHM9.run().
test20()
void com.cliffc.aa.HM.TestHM9.test20 ()
Definition at line 167 of file TestHM9.java.
{
     Root syn = HM9.hm("cons ={x y-> {cadr -> (cadr x y)}};"+
                      "cdr ={mycons -> (mycons { p q -> q})};"+
                      "map ={fun parg -> (fun (cdr parg))};"+
                      "(pair (map str (cons 0 5)) (map isempty (cons 0 \"abc\")))");
     if( HM.DO_HM )
       assertEquals("( *[4]str, int1)[7]",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM )
         assertEquals(TypeMemPtr.make(7,TypeStruct.make(TypeMemPtr.STRPTR,TypeInt.BOOL)),syn.flow_type());
       else
         assertEquals(tuple2,syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeInt.BOOL, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.TypeMemPtr.STRPTR, and com.cliffc.aa.HM.TestHM9.tuple2.
test21()
void com.cliffc.aa.HM.TestHM9.test21 ()
Definition at line 182 of file TestHM9.java.
                              { run("f0 = { f x -> (if (?0 x) 1 (f (f0 f (dec x)) 2))}; (f0 * 99)",
                                    "int64", TypeInt.INT64); }
References com.cliffc.aa.type.TypeInt.INT64, and com.cliffc.aa.HM.TestHM9.run().
test22()
void com.cliffc.aa.HM.TestHM9.test22 ()
Definition at line 188 of file TestHM9.java.
                              { run("f0 = { f x -> (if (?0 x) 1 (* (f0 f (dec x)) 2))}; (f0 f0 99)",
                                    "int64", TypeInt.INT64); }
References com.cliffc.aa.type.TypeInt.INT64, and com.cliffc.aa.HM.TestHM9.run().
test23()
void com.cliffc.aa.HM.TestHM9.test23 ()
Definition at line 192 of file TestHM9.java.
                              { run("is_even = "+
                                    "  is_odd = { n -> (if (?0 n) 0 (is_even (dec n)))}; "+
                                    "     { n -> (if (?0 n) 1 (is_odd (dec n)))};"+
                                    "(is_even 3)" ,
                                    "int1", TypeInt.BOOL); }
References com.cliffc.aa.type.TypeInt.BOOL, and com.cliffc.aa.HM.TestHM9.run().
test24()
void com.cliffc.aa.HM.TestHM9.test24 ()
Definition at line 199 of file TestHM9.java.
                              { run("{ g -> fgz = "+
                                    "         cons = {x y -> {cadr -> (cadr x y)}};"+
                                    "         cdr = {mycons -> (mycons { p q -> q})};"+
                                    "         (cdr (cons 2 { z -> (g z) }));"+
                                    "      (pair (fgz 3) (fgz 5))"+
                                    "}"
                                    ,
                                    "{ { nint8 -> A } -> ( $A, $A)[7] }", tfs(tuple2)); }
References com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.HM.TestHM9.tfs(), and com.cliffc.aa.HM.TestHM9.tuple2.
test25()
void com.cliffc.aa.HM.TestHM9.test25 ()
Definition at line 209 of file TestHM9.java.
                              { run("@{x=2, y=3}",
                                    "@{ x = 2, y = 3}[9]",
                                    TypeMemPtr.make(9,TypeStruct.make(TypeStruct.flds(TypeInt.con(2),TypeInt.con(3))))
                                    ); }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeStruct.make(), and com.cliffc.aa.HM.TestHM9.run().
test26()
void com.cliffc.aa.HM.TestHM9.test26 ()
Definition at line 215 of file TestHM9.java.
                              { run(".x @{x =2, y =3}",
                                    "2", TypeInt.con(2)); }
References com.cliffc.aa.type.TypeInt.con(), and com.cliffc.aa.HM.TestHM9.run().
test27()
void com.cliffc.aa.HM.TestHM9.test27 ()
Definition at line 219 of file TestHM9.java.
                              { run(".x 5",
                                    "Missing field x in 5", Type.SCALAR); }
References com.cliffc.aa.HM.TestHM9.run(), and com.cliffc.aa.type.Type< T extends Type< T >.SCALAR.
test28()
void com.cliffc.aa.HM.TestHM9.test28 ()
Definition at line 223 of file TestHM9.java.
                              { run(".x @{ y =3}",
                                    "Missing field x in @{ y = 3}[9]",
                                    Type.SCALAR); }
References com.cliffc.aa.HM.TestHM9.run(), and com.cliffc.aa.type.Type< T extends Type< T >.SCALAR.
test29()
void com.cliffc.aa.HM.TestHM9.test29 ()
Definition at line 227 of file TestHM9.java.
                              { run("{ g -> @{x=g, y=g}}",
                                    "{ A -> @{ x = $A, y = $A}[9] }", tfs(tuple9)); }
References com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.HM.TestHM9.tfs(), and com.cliffc.aa.HM.TestHM9.tuple9.
test30()
void com.cliffc.aa.HM.TestHM9.test30 ()
Definition at line 231 of file TestHM9.java.
                              { run("{ pred -> .x (if pred @{x=2,y=3} @{x=3,z= \"abc\"}) }",
                                    "{ A -> nint8 }", tfs(TypeInt.NINT8)); }
References com.cliffc.aa.type.TypeInt.NINT8, com.cliffc.aa.HM.TestHM9.run(), and com.cliffc.aa.HM.TestHM9.tfs().
test31()
void com.cliffc.aa.HM.TestHM9.test31 ()
Definition at line 236 of file TestHM9.java.
                              { run("{ sq -> (* .x sq .y sq) }", // { sq -> sq.x * sq.y }
                                    "{ @{ x = int64, y = int64}[] -> int64 }", tfs(TypeInt.INT64)); }
References com.cliffc.aa.type.TypeInt.INT64, com.cliffc.aa.HM.TestHM9.run(), and com.cliffc.aa.HM.TestHM9.tfs().
test32()
void com.cliffc.aa.HM.TestHM9.test32 ()
Definition at line 256 of file TestHM9.java.
{
     Root syn = HM9.hm("map = { fcn lst -> @{ n1 = (map fcn .n0 lst), v1 = (fcn .v0 lst) } }; map");
     if( HM.DO_HM )
       assertEquals("{ { A -> B } C:@{ n0 = $C, v0 = $A}[] -> D:@{ n1 = $D, v1 = $B}[9] }",syn._hmt.p());
     if( HM.DO_GCP )
       // Build a cycle of length 2, without nil.
       assertEquals(tfs(build_cycle(9,false,Type.SCALAR)),syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.TestHM9.build_cycle(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM9.tfs().
test33()
void com.cliffc.aa.HM.TestHM9.test33 ()
Definition at line 268 of file TestHM9.java.
{
     Root syn = HM9.hm("map = { fcn lst -> (if lst @{ n1=(map fcn .n0 lst), v1=(fcn .v0 lst) } 0) }; map");
     if( HM.DO_HM )
       assertEquals("{ { A -> B } C:@{ n0 = $C, v0 = $A}[0] -> D:@{ n1 = $D, v1 = $B}[0,9] }",syn._hmt.p());
     if( HM.DO_GCP )
       // Build a cycle of length 2, with nil.
       assertEquals(tfs(build_cycle(9,true,Type.SCALAR)),syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.TestHM9.build_cycle(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM9.tfs().
test34()
void com.cliffc.aa.HM.TestHM9.test34 ()
Definition at line 278 of file TestHM9.java.
{
     Root syn = HM9.hm("map = { fcn lst -> (if lst @{ n1 = (map fcn .n0 lst), v1 = (fcn .v0 lst) } 0) }; (map dec @{n0 = 0, v0 = 5})");
     if( HM.DO_HM )
       assertEquals("A:@{ n1 = $A, v1 = int64}[0,9]",syn._hmt.p());
     if( HM.DO_GCP )
       assertEquals(build_cycle(9,true,TypeInt.con(4)),syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.TestHM9.build_cycle(), com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), and com.cliffc.aa.HM.HM.T2.p().
test35()
void com.cliffc.aa.HM.TestHM9.test35 ()
Definition at line 287 of file TestHM9.java.
{
     TypeFunPtr tfp = TypeFunPtr.make(15,3,Type.ANY);
     TypeMemPtr tmp0 = TypeMemPtr.make(8,TypeStruct.make(tfp ,tfp ,tfp ));
     TypeMemPtr tmp1 = TypeMemPtr.make(8,TypeStruct.make(tmp0,tmp0,tmp0));
     TypeMemPtr tmp2 = TypeMemPtr.make(8,TypeStruct.make(tmp1,tmp1,tmp1));
     run("p0 = { x y z -> (triple x y z) };"+
         "p1 = (triple p0 p0 p0);"+
         "p2 = (triple p1 p1 p1);"+
         "p3 = (triple p2 p2 p2);"+
         "p3",
         "( ( ( { A B C -> ( $A, $B, $C)[8] }, { D E F -> ( $D, $E, $F)[8] }, { G H I -> ( $G, $H, $I)[8] })[8], ( { J K L -> ( $J, $K, $L)[8] }, { M N O -> ( $M, $N, $O)[8] }, { P Q R -> ( $P, $Q, $R)[8] })[8], ( { S T U -> ( $S, $T, $U)[8] }, { V21 V22 V23 -> ( $V21, $V22, $V23)[8] }, { V24 V25 V26 -> ( $V24, $V25, $V26)[8] })[8])[8], ( ( { V27 V28 V29 -> ( $V27, $V28, $V29)[8] }, { V30 V31 V32 -> ( $V30, $V31, $V32)[8] }, { V33 V34 V35 -> ( $V33, $V34, $V35)[8] })[8], ( { V36 V37 V38 -> ( $V36, $V37, $V38)[8] }, { V39 V40 V41 -> ( $V39, $V40, $V41)[8] }, { V42 V43 V44 -> ( $V42, $V43, $V44)[8] })[8], ( { V45 V46 V47 -> ( $V45, $V46, $V47)[8] }, { V48 V49 V50 -> ( $V48, $V49, $V50)[8] }, { V51 V52 V53 -> ( $V51, $V52, $V53)[8] })[8])[8], ( ( { V54 V55 V56 -> ( $V54, $V55, $V56)[8] }, { V57 V58 V59 -> ( $V57, $V58, $V59)[8] }, { V60 V61 V62 -> ( $V60, $V61, $V62)[8] })[8], ( { V63 V64 V65 -> ( $V63, $V64, $V65)[8] }, { V66 V67 V68 -> ( $V66, $V67, $V68)[8] }, { V69 V70 V71 -> ( $V69, $V70, $V71)[8] })[8], ( { V72 V73 V74 -> ( $V72, $V73, $V74)[8] }, { V75 V76 V77 -> ( $V75, $V76, $V77)[8] }, { V78 V79 V80 -> ( $V78, $V79, $V80)[8] })[8])[8])[8]",
         tmp2  );
   }
References com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeFunPtr.make(), com.cliffc.aa.type.TypeStruct.make(), and com.cliffc.aa.HM.TestHM9.run().
test36()
void com.cliffc.aa.HM.TestHM9.test36 ()
Definition at line 304 of file TestHM9.java.
{
     Root syn = HM9.hm("map = { lst -> (if lst @{ n1= arg= .n0 lst; (if arg @{ n1=(map .n0 arg), v1=(str .v0 arg)} 0), v1=(str .v0 lst) } 0) }; map");
     if( HM.DO_HM )
       assertEquals("{ A:@{ n0 = @{ n0 = $A, v0 = int64}[0], v0 = int64}[0] -> B:@{ n1 = @{ n1 = $B, v1 = *[4]str}[0,9], v1 = *[4]str}[0,10] }",syn._hmt.p());
     if( HM.DO_GCP ) {
       TypeStruct cycle_strX;
       if( true ) {
         // Unrolled, known to only produce results where either other nested
         // struct is from a different allocation site.
         TypeMemPtr cycle_ptr0 = TypeMemPtr.make(BitsAlias.FULL.make(0,10),TypeObj.XOBJ);
         TypeStruct cycle_str1 = TypeStruct.make(TypeFld.NO_DISP,TypeFld.malloc("n1",cycle_ptr0,1),TypeFld.malloc("v1",TypeMemPtr.STRPTR,1));
         TypeMemPtr cycle_ptr1 = TypeMemPtr.make(BitsAlias.FULL.make(0, 9),cycle_str1);
         TypeStruct cycle_str2 = TypeStruct.make(TypeFld.NO_DISP,TypeFld.malloc("n1",cycle_ptr1,1),TypeFld.malloc("v1",TypeMemPtr.STRPTR,1));
         TypeMemPtr cycle_ptr2 = TypeMemPtr.make(BitsAlias.FULL.make(0,10),cycle_str2);
         TypeStruct cycle_str3 = TypeStruct.make(TypeFld.NO_DISP,TypeFld.malloc("n1",cycle_ptr2,1),TypeFld.malloc("v1",TypeMemPtr.STRPTR,1));
         cycle_strX = cycle_str3;
       } else {
         // Not unrolled, both structs are folded
         TypeMemPtr cycle_ptr0 = TypeMemPtr.make(BitsAlias.FULL.make(0,7, 8),TypeObj.XOBJ);
         TypeStruct cycle_str1 = TypeStruct.make(TypeFld.NO_DISP,TypeFld.malloc("n1",cycle_ptr0,1),TypeFld.malloc("v1",TypeMemPtr.STRPTR,1));
         TypeMemPtr cycle_ptr1 = TypeMemPtr.make(BitsAlias.FULL.make(0,7, 8),cycle_str1);
         TypeStruct cycle_str2 = TypeStruct.make(TypeFld.NO_DISP,TypeFld.malloc("n1",cycle_ptr1,1),TypeFld.malloc("v1",TypeMemPtr.STRPTR,1));
         cycle_strX = cycle_str2;
       }
       TypeStruct cycle_strn = cycle_strX.approx(1,9);
       TypeMemPtr cycle_ptrn = (TypeMemPtr)cycle_strn.at(1);
       assertEquals(tfs(cycle_ptrn),syn.flow_type());
     }
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeStruct.approx(), com.cliffc.aa.type.TypeStruct.at(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.type.BitsAlias.FULL, com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.Bits< B extends Bits< B >.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.TypeFld.malloc(), com.cliffc.aa.type.TypeFld.NO_DISP, com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.TypeMemPtr.STRPTR, com.cliffc.aa.HM.TestHM9.tfs(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.XOBJ.
test37()
void com.cliffc.aa.HM.TestHM9.test37 ()
Definition at line 334 of file TestHM9.java.
                              { run("x = { y -> (x (y y))}; x",
                                    "{ A:{ $A -> $A } -> B }", tfs(Type.XSCALAR)); }
References com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.HM.TestHM9.tfs(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
test38()
void com.cliffc.aa.HM.TestHM9.test38 ()
Definition at line 339 of file TestHM9.java.
                              { run("{ x -> y = ( x .v x ); 0}",
                                    "{ Cannot unify @{ v = A}[] and { A -> B } -> 0 }", tfs(Type.XNIL)); }
References com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.HM.TestHM9.tfs(), and com.cliffc.aa.type.Type< T extends Type< T >.XNIL.
test39()
void com.cliffc.aa.HM.TestHM9.test39 ()
Definition at line 344 of file TestHM9.java.
{
     Root syn = HM9.hm("x = { z -> z}; (x { y -> .u y})");
     if( HM.DO_HM )
       assertEquals("{ @{ u = A}[] -> $A }",syn._hmt.p());
     if( HM.DO_GCP )
       assertEquals(tfs(Type.SCALAR), syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM9.tfs().
test40()
void com.cliffc.aa.HM.TestHM9.test40 ()
Definition at line 356 of file TestHM9.java.
{
     Root syn = HM9.hm("x = w = (x x); { z -> z}; (x { y -> .u y})");
     if( HM.DO_HM )
       assertEquals("Cannot unify A:{ $A -> $A } and @{ u = A}[]",syn._hmt.p());
     if( HM.DO_GCP ) {
       if( HM.DO_HM ) {
         assertEquals(tfs(Type.SCALAR), syn.flow_type());
       } else {
         assertEquals(Type.SCALAR, syn.flow_type());
       }
     }
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM9.tfs().
test41()
void com.cliffc.aa.HM.TestHM9.test41 ()
Definition at line 376 of file TestHM9.java.
{
     Root syn = HM9.hm("map={lst fcn -> (fcn .y lst) }; "+
                      "in_int=@{ x=0 y=2}; " +
                      "in_str=@{ x=0 y=\"abc\"}; " +
                      "out_str = (map in_int str); " +
                      "out_bool= (map in_str { xstr -> (eq xstr \"def\")}); "+
                      "(pair out_str out_bool)");
     if( HM.DO_HM )
       assertEquals("( *[4]str, int1)[7]",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM )
         assertEquals(TypeMemPtr.make(7,TypeStruct.make(TypeMemPtr.STRPTR,TypeInt.BOOL)),syn.flow_type());
       else
         assertEquals(tuple2,syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeInt.BOOL, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.TypeMemPtr.STRPTR, and com.cliffc.aa.HM.TestHM9.tuple2.
test42()
void com.cliffc.aa.HM.TestHM9.test42 ()
Definition at line 393 of file TestHM9.java.
{
     Root syn = HM9.hm("pred = 0; s1 = @{ x=\"abc\" }; s2 = @{ y=3.4 }; .y (if pred s1 s2)");
     if( HM.DO_HM ) {
       if( HM.DO_GCP )
         assertEquals("3.4000000953674316",syn._hmt.p());
       else
         assertEquals("Missing field y in @{ x = *[4]\"abc\"}[9]",syn._hmt.p());
     }
     if( HM.DO_GCP )
       assertEquals(TypeFlt.con(3.4f), syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeFlt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), and com.cliffc.aa.HM.HM.T2.p().
test43()
void com.cliffc.aa.HM.TestHM9.test43 ()
Definition at line 406 of file TestHM9.java.
{
     Root syn = HM9.hm("pred = 0; s1 = @{ x=\"abc\" }; s2 = @{ y=3.4 }; z = (if pred s1 s2); .y s2");
     if( HM.DO_HM )
       assertEquals("3.4000000953674316",syn._hmt.p());
     if( HM.DO_GCP )
       assertEquals(TypeFlt.con(3.4f), syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeFlt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), and com.cliffc.aa.HM.HM.T2.p().
test44()
void com.cliffc.aa.HM.TestHM9.test44 ()
Definition at line 415 of file TestHM9.java.
{
     Root syn = HM9.hm("fun = (if (isempty \"abc\") {x->x} {x->1.2}); (fun @{})");
     if( HM.DO_HM ) {
       if( HM.DO_GCP )
         assertEquals("1.2000000476837158",syn._hmt.p());
       else
         assertEquals("Cannot unify 1.2000000476837158 and )[9]",syn._hmt.p());
     }
     if( HM.DO_GCP )
       assertEquals(TypeFlt.con(1.2f), syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeFlt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), and com.cliffc.aa.HM.HM.T2.p().
test45()
void com.cliffc.aa.HM.TestHM9.test45 ()
Definition at line 429 of file TestHM9.java.
{
     Root syn = HM9.hm(
 "id = {x -> x};" +
 "loop = { name cnt ->" +
 "  (if cnt " +
 "    (loop" +
 "       fltfun = (if name id {x->3});" +
 "       (fltfun \"abc\")" +
 "       (dec cnt)" +
 "     )" +
 "     name" +
 "   )"+
 "};" +
 "(loop \"def\" (id 2))");
     if( HM.DO_HM )
       assertEquals(HM.DO_GCP
                    ? "*[4]str"  // Both HM and GCP
                    : "Cannot unify *[4]\"abc\" and 3", // HM alone cannot do this one
                    syn._hmt.p());
     if( HM.DO_GCP )
       assertEquals(HM.DO_HM
                    ? TypeMemPtr.STRPTR // Both HM and GCP
                    : Type.NSCALR,      // GCP alone gets a very weak answer
                    syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.type.Type< T extends Type< T >.NSCALR, com.cliffc.aa.HM.HM.T2.p(), and com.cliffc.aa.type.TypeMemPtr.STRPTR.
test46()
void com.cliffc.aa.HM.TestHM9.test46 ()
Definition at line 457 of file TestHM9.java.
                              { run(".x 0",
                                    "May be nil when loading field x", Type.XSCALAR); }
References com.cliffc.aa.HM.TestHM9.run(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
test47()
void com.cliffc.aa.HM.TestHM9.test47 ()
Definition at line 461 of file TestHM9.java.
                              { run("{ pred -> .x (if pred @{x=3} 0)}",
                                    "{ A -> May be nil when loading field x }", tfs(TypeInt.con(3))); }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.TestHM9.run(), and com.cliffc.aa.HM.TestHM9.tfs().
test48()
void com.cliffc.aa.HM.TestHM9.test48 ()
Definition at line 465 of file TestHM9.java.
                              { run("{ pred -> tmp=(if pred @{x=3} 0); (if tmp .x tmp 4) }",
                                    "{ A -> nint8 }", tfs(TypeInt.NINT8)); }
References com.cliffc.aa.type.TypeInt.NINT8, com.cliffc.aa.HM.TestHM9.run(), and com.cliffc.aa.HM.TestHM9.tfs().
test49()
void com.cliffc.aa.HM.TestHM9.test49 ()
Definition at line 470 of file TestHM9.java.
{
     Root syn = HM9.hm("{ pred -> \n"+
                      "  map = { fun x -> (fun x) };\n" +
                      "  (pair (map {str0 ->          .x str0   }          @{x = 3}   )\n" +
                      "        (map {str1 -> (if str1 .x str1 4)} (if pred @{x = 5} 0))\n" +
                      "  )\n"+
                      "}");
     if( HM.DO_HM )
       assertEquals("{ A -> ( 3, nint8)[7] }",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM ) tfs(TypeMemPtr.make(7,TypeStruct.make(TypeInt.con(3), TypeInt.NINT8 )));
       else           tfs(TypeMemPtr.make(7,TypeStruct.make(TypeInt.NINT8 , TypeInt.NINT8 )));
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.TypeInt.NINT8, com.cliffc.aa.HM.HM.T2.p(), and com.cliffc.aa.HM.TestHM9.tfs().
test50()
void com.cliffc.aa.HM.TestHM9.test50 ()
Definition at line 485 of file TestHM9.java.
{
     Root syn = HM9.hm("{ pred -> \n"+
                      "  map = { fun x -> (fun x) };\n" +
                      "  (pair (map {str0 ->          .x str0   }          @{x = 3}   )\n" +
                      "        (map {str1 ->          .x str1   } (if pred @{x = 5} 0))\n" +
                      "  )\n"+
                      "}");
     if( HM.DO_HM )
       assertEquals("{ A -> May be nil when loading field x }",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM ) tfs(TypeMemPtr.make(7,TypeStruct.make(TypeInt.con(3), TypeInt.NINT8 )));
       else           tfs(TypeMemPtr.make(7,TypeStruct.make(TypeInt.NINT8 , TypeInt.NINT8 )));
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.TypeInt.NINT8, com.cliffc.aa.HM.HM.T2.p(), and com.cliffc.aa.HM.TestHM9.tfs().
tfs()
static TypeFunSig com.cliffc.aa.HM.TestHM9.tfs (Type ret) static private
Definition at line 24 of file TestHM9.java.
{
     return TypeFunSig.make(TypeTuple.make_ret(ret),TypeTuple.make_args());
   }
References com.cliffc.aa.type.TypeFunSig.make(), com.cliffc.aa.type.TypeTuple.make_args(), and com.cliffc.aa.type.TypeTuple.make_ret().
Referenced by com.cliffc.aa.HM.TestHM9.test02(), com.cliffc.aa.HM.TestHM9.test03(), com.cliffc.aa.HM.TestHM9.test04(), com.cliffc.aa.HM.TestHM9.test07(), com.cliffc.aa.HM.TestHM9.test10(), com.cliffc.aa.HM.TestHM9.test11(), com.cliffc.aa.HM.TestHM9.test13(), com.cliffc.aa.HM.TestHM9.test17(), com.cliffc.aa.HM.TestHM9.test18(), com.cliffc.aa.HM.TestHM9.test24(), com.cliffc.aa.HM.TestHM9.test29(), com.cliffc.aa.HM.TestHM9.test30(), com.cliffc.aa.HM.TestHM9.test31(), com.cliffc.aa.HM.TestHM9.test32(), com.cliffc.aa.HM.TestHM9.test33(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.HM.TestHM9.test37(), com.cliffc.aa.HM.TestHM9.test38(), com.cliffc.aa.HM.TestHM9.test39(), com.cliffc.aa.HM.TestHM9.test40(), com.cliffc.aa.HM.TestHM9.test47(), com.cliffc.aa.HM.TestHM9.test48(), com.cliffc.aa.HM.TestHM9.test49(), and com.cliffc.aa.HM.TestHM9.test50().
Member Data Documentation
N1V1
final String [] com.cliffc.aa.HM.TestHM9.N1V1 = new String[]{"^","n1","v1"} static private
Definition at line 34 of file TestHM9.java.
ret_tuple2
final TypeFunSig com.cliffc.aa.HM.TestHM9.ret_tuple2 = tfs(tuple2) static private
Definition at line 32 of file TestHM9.java.
Referenced by com.cliffc.aa.HM.TestHM9.test09().
tuple2
final TypeMemPtr com.cliffc.aa.HM.TestHM9.tuple2 = TypeMemPtr.make(7,TypeStruct.make(Type.SCALAR, Type.SCALAR)) static private
Definition at line 28 of file TestHM9.java.
Referenced by com.cliffc.aa.HM.TestHM9.test03(), com.cliffc.aa.HM.TestHM9.test14(), com.cliffc.aa.HM.TestHM9.test20(), com.cliffc.aa.HM.TestHM9.test24(), and com.cliffc.aa.HM.TestHM9.test41().
tuple55
final TypeMemPtr com.cliffc.aa.HM.TestHM9.tuple55 = TypeMemPtr.make(7,TypeStruct.make(TypeInt.con(5),TypeInt.con(5))) static private
Definition at line 31 of file TestHM9.java.
Referenced by com.cliffc.aa.HM.TestHM9.test16(), and com.cliffc.aa.HM.TestHM9.test17().
tuple82
final TypeMemPtr com.cliffc.aa.HM.TestHM9.tuple82 = TypeMemPtr.make(7,TypeStruct.make(TypeInt.NINT8, TypeInt.NINT8)) static private
Definition at line 30 of file TestHM9.java.
Referenced by com.cliffc.aa.HM.TestHM9.test05().
tuple9
final TypeMemPtr com.cliffc.aa.HM.TestHM9.tuple9 = TypeMemPtr.make(9,TypeStruct.make(TypeStruct.flds(Type.SCALAR,Type.SCALAR))) static private
Definition at line 35 of file TestHM9.java.
Referenced by com.cliffc.aa.HM.TestHM9.test29().
tuplen2
final TypeMemPtr com.cliffc.aa.HM.TestHM9.tuplen2 = TypeMemPtr.make(7,TypeStruct.make(Type.NSCALR, Type.NSCALR)) static private
Definition at line 29 of file TestHM9.java.
Referenced by com.cliffc.aa.HM.TestHM9.test06().
XY
final String [] com.cliffc.aa.HM.TestHM9.XY = new String[]{"^","x","y"} static private
Definition at line 33 of file TestHM9.java.
The documentation for this class was generated from the following file:
TestHM9.java