aa: com.cliffc.aa.type.TypeStr Class Reference
com.cliffc.aa.type.TypeStr Class Reference
Public Member Functions
boolean above_center ()
TypeObj crush ()
boolean cycle_equals (Type o)
boolean equals (Object o)
String getstr ()
boolean is_con ()
byte isBitShape (Type t)
boolean may_be_con ()
boolean may_nil ()
Type meet_nil (Type t)
boolean must_nil ()
SB str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
TypeObj update (Access fin, String fld, Type val)
TypeObj update (TypeInt idx, Type val)
void walk (Predicate< Type > p)
TypeStr widen ()
Static Public Member Functions
static TypeStr con (String con)
static void init ()
static TypeStr make (boolean any, String con)
static TypeStr make (String name, boolean any, String con)
Static Public Attributes
static final TypeStr ABC = make(false,"abc")
static final TypeObj ISUSED
static final TypeObj OBJ
static final TypeStr STR = make(false,null)
static final TypeObj UNUSED
static final TypeObj XOBJ
static final TypeStr XSTR = STR.dual()
Protected Member Functions
O init (byte type, String name, boolean any, boolean use)
TypeStr xdual ()
Type xmeet (Type t)
Package Functions
int compute_hash ()
TypeObj flatten_fields ()
boolean is_display ()
TypeStr rdual ()
TypeObj remove_other_flds (String fld, Type live)
Static Package Functions
[static initializer]
static void init1 (HashMap< String, Type > types)
Package Attributes
boolean _any
boolean _use
Static Package Attributes
static final TypeStr[] TYPES = new TypeStr[]{STR,ABC,DEF}
Private Member Functions
TypeStr init (String name, boolean any, String con)
Private Attributes
String _con
Static Private Attributes
static final TypeStr DEF = con("def")
Detailed Description
Definition at line 14 of file TypeStr.java.
Member Function Documentation
[static initializer]()
com.cliffc.aa.type.TypeStr.[static initializer] static package
above_center()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.above_center inherited
Definition at line 77 of file TypeObj.java.
 { return _any; }
compute_hash()
int com.cliffc.aa.type.TypeStr.compute_hash () package
Definition at line 21 of file TypeStr.java.
 { return super.compute_hash() + (_con==null ? 0 : _con.hashCode());  }
References com.cliffc.aa.type.TypeStr._con.
Referenced by com.cliffc.aa.type.TypeStr.rdual().
con()
static TypeStr com.cliffc.aa.type.TypeStr.con (String con) static
Definition at line 42 of file TypeStr.java.
 { return make(false,con); }
References com.cliffc.aa.type.TypeStr.make().
Referenced by com.cliffc.aa.HM.HM9.T2._as_flow(), com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM9.Str.apply(), com.cliffc.aa.HM.HM.Str.apply(), com.cliffc.aa.node.NewStrNode.ConStr.ConStr(), com.cliffc.aa.type.TypeStr.init(), com.cliffc.aa.type.TypeStr.make(), com.cliffc.aa.tvar.TV2.make_err(), com.cliffc.aa.HM.HM8.T2.make_err(), com.cliffc.aa.HM.HM6.string(), com.cliffc.aa.HM.HM8.string(), com.cliffc.aa.HM.HM7.string(), com.cliffc.aa.HM.HM9.string(), com.cliffc.aa.HM.HM.string(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.TestParse.testParse(), com.cliffc.aa.TestParse.testParse00(), com.cliffc.aa.TestParse.testParse06(), and com.cliffc.aa.type.TypeStr.xmeet().
crush()
TypeObj com.cliffc.aa.type.TypeStr.crush ()
Definition at line 97 of file TypeStr.java.
 { return this; }
cycle_equals()
boolean com.cliffc.aa.type.TypeStr.cycle_equals (Type o)
Definition at line 27 of file TypeStr.java.
 { return equals(o); }
References com.cliffc.aa.type.TypeStr.equals().
equals()
boolean com.cliffc.aa.type.TypeStr.equals (Object o)
Definition at line 22 of file TypeStr.java.
{
     if( this==o ) return true;
     if( !(o instanceof TypeStr) || !super.equals(o) ) return false;
     return Util.eq(_con,((TypeStr)o)._con);
   }
References com.cliffc.aa.type.TypeStr._con, and com.cliffc.aa.util.Util.eq().
Referenced by com.cliffc.aa.type.TypeStr.cycle_equals().
flatten_fields()
TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.flatten_fields package inherited
Definition at line 74 of file TypeObj.java.
 { return this; }
getstr()
String com.cliffc.aa.type.TypeStr.getstr ()
Definition at line 52 of file TypeStr.java.
 { assert _con!=null; return _con; }
References com.cliffc.aa.type.TypeStr._con.
Referenced by com.cliffc.aa.node.NewStrNode.AddStrStr.value().
init() [1/3]
static void com.cliffc.aa.type.TypeStr.init () static
Definition at line 43 of file TypeStr.java.
 {} // Used to force class init
init() [2/3]
O com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.init (byte type, String name, boolean any, boolean use) protected inherited
Definition at line 19 of file TypeObj.java.
{
     super.init(type,name);
     _any=any;
     _use=use;
     return (O)this;
   }
init() [3/3]
TypeStr com.cliffc.aa.type.TypeStr.init (String name, boolean any, String con) private
Definition at line 16 of file TypeStr.java.
{
     super.init(TSTR,name,any,any);
     _con = con;
     return this;
   }
References com.cliffc.aa.type.TypeStr._con, com.cliffc.aa.type.TypeStr.con(), and com.cliffc.aa.type.TypeStr.init().
Referenced by com.cliffc.aa.type.TypeStr.init(), com.cliffc.aa.type.TypeStr.make(), and com.cliffc.aa.type.TypeStr.xdual().
init1()
static void com.cliffc.aa.type.TypeStr.init1 (HashMap< String, Type > types) static package
Definition at line 50 of file TypeStr.java.
 { types.put("str",TypeMemPtr.STRPTR); }
References com.cliffc.aa.type.TypeMemPtr.STRPTR.
Referenced by com.cliffc.aa.type.Type< TypeFlt >.init0().
is_con()
boolean com.cliffc.aa.type.TypeStr.is_con ()
Definition at line 94 of file TypeStr.java.
 { return _con != null; }
References com.cliffc.aa.type.TypeStr._con.
Referenced by com.cliffc.aa.node.NewStrNode.AddStrStr.value().
is_display()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.is_display package inherited
Definition at line 50 of file TypeObj.java.
 { return false; }
isBitShape()
byte com.cliffc.aa.type.TypeStr.isBitShape (Type t)
Definition at line 105 of file TypeStr.java.
{
     if( t._type==TNIL || t._type==Type.TSTR || t._type == TOBJ ) return 0;
     return 99;
   }
References com.cliffc.aa.type.Type< T extends Type< T >._type, and com.cliffc.aa.type.Type< T extends Type< T >.TSTR.
make() [1/2]
static TypeStr com.cliffc.aa.type.TypeStr.make (boolean any, String con) static
Definition at line 41 of file TypeStr.java.
 { return make("",any,con); }
References com.cliffc.aa.type.TypeStr.con(), and com.cliffc.aa.type.TypeStr.make().
Referenced by com.cliffc.aa.type.TypeStr.make().
make() [2/2]
static TypeStr com.cliffc.aa.type.TypeStr.make (String name, boolean any, String con) static
Definition at line 36 of file TypeStr.java.
{
     TypeStr t1 = POOLS[TSTR].malloc();
     return t1.init(name,any,con).hashcons_free();
   }
References com.cliffc.aa.type.TypeStr.con(), and com.cliffc.aa.type.TypeStr.init().
Referenced by com.cliffc.aa.type.TypeStr.con(), com.cliffc.aa.node.NewStrNode.AddStrStr.value(), com.cliffc.aa.node.NewStrNode.ConvertI64Str.valueobj(), com.cliffc.aa.node.NewStrNode.ConvertF64Str.valueobj(), and com.cliffc.aa.type.TypeStr.xmeet().
may_be_con()
boolean com.cliffc.aa.type.TypeStr.may_be_con ()
Definition at line 93 of file TypeStr.java.
 { return super.may_be_con() || _con != null; }
References com.cliffc.aa.type.TypeStr._con.
may_nil()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.may_nil inherited
Definition at line 81 of file TypeObj.java.
 { return false; }
meet_nil()
Type com.cliffc.aa.type.TypeStr.meet_nil (Type t)
Definition at line 95 of file TypeStr.java.
 { return this; }
must_nil()
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.must_nil inherited
Definition at line 80 of file TypeObj.java.
 { return false; }
rdual()
TypeStr com.cliffc.aa.type.TypeStr.rdual () package
Definition at line 55 of file TypeStr.java.
{
     if( _dual != null ) return _dual;
     TypeStr dual = _dual = xdual();
     dual._dual = this;
     dual._hash = dual.compute_hash();
     return dual;
   }
References com.cliffc.aa.type.TypeStr.compute_hash(), and com.cliffc.aa.type.TypeStr.xdual().
remove_other_flds()
TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.remove_other_flds (String fld, Type live) package inherited
Definition at line 75 of file TypeObj.java.
 { return UNUSED; }
str()
SB com.cliffc.aa.type.TypeStr.str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
Definition at line 28 of file TypeStr.java.
{
     if( _any ) sb.p('~');
     if( _con == null ) sb.p("str");
     else sb.p('"').p(_con).p('"');
     return sb;
   }
References com.cliffc.aa.type.TypeObj< TypeStr >._any, com.cliffc.aa.type.TypeStr._con, and com.cliffc.aa.util.SB.p().
update() [1/2]
TypeObj com.cliffc.aa.type.TypeStr.update (Access fin, String fld, Type val)
Definition at line 91 of file TypeStr.java.
 { return this; }
update() [2/2]
TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.update (TypeInt idx, Type val) inherited
Definition at line 69 of file TypeObj.java.
{
     if( this==ISUSED || this==OBJ ) return this;
     return TypeAry.ARY.dual().update(idx,val);
   }
walk()
void com.cliffc.aa.type.TypeStr.walk (Predicate< Type > p)
Definition at line 110 of file TypeStr.java.
 { p.test(this); }
widen()
TypeStr com.cliffc.aa.type.TypeStr.widen ()
Definition at line 109 of file TypeStr.java.
 { return STR; }
References com.cliffc.aa.type.TypeStr.STR.
xdual()
TypeStr com.cliffc.aa.type.TypeStr.xdual () protected
Definition at line 54 of file TypeStr.java.
 { return _con == null ? new TypeStr().init(_name, !_any,_con) : this; }
References com.cliffc.aa.type.TypeObj< TypeStr >._any, com.cliffc.aa.type.TypeStr._con, and com.cliffc.aa.type.TypeStr.init().
Referenced by com.cliffc.aa.type.TypeStr.rdual().
xmeet()
Type com.cliffc.aa.type.TypeStr.xmeet (Type t) protected
Definition at line 62 of file TypeStr.java.
{
     switch( t._type ) {
     case TSTR:   break;
     case TARY:
     case TLIVE:
     case TSTRUCT:return OBJ;
     case TOBJ:   return t.xmeet(this);
     case TFUNSIG:
     case TTUPLE:
     case TFUNPTR:
     case TMEMPTR:
     case TFLT:
     case TINT:
     case TRPC:
     case TMEM:   return ALL;
     default: throw typerr(t);
     }
     TypeStr ts = (TypeStr)t;
     boolean any = _any&ts._any;
     String con = null;
     if( ts._any && ts._con==null ) con =    _con;
     else if( _any &&  _con==null ) con = ts._con;
     else if( Util.eq(_con,ts._con) ) con =  _con;
     else any=false;
     return make("",any,con);
   }
References com.cliffc.aa.type.TypeObj< TypeStr >._any, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >._any, com.cliffc.aa.type.TypeStr._con, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.type.TypeStr.con(), com.cliffc.aa.util.Util.eq(), com.cliffc.aa.type.TypeStr.make(), com.cliffc.aa.type.TypeObj< TypeStr >.OBJ, and com.cliffc.aa.type.Type< T extends Type< T >.xmeet().
Member Data Documentation
_any
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >._any package inherited
Definition at line 16 of file TypeObj.java.
_con
String com.cliffc.aa.type.TypeStr._con private
Definition at line 15 of file TypeStr.java.
Referenced by com.cliffc.aa.type.TypeStr.compute_hash(), com.cliffc.aa.type.TypeStr.equals(), com.cliffc.aa.type.TypeStr.getstr(), com.cliffc.aa.type.TypeStr.init(), com.cliffc.aa.type.TypeStr.is_con(), com.cliffc.aa.type.TypeStr.may_be_con(), com.cliffc.aa.type.TypeStr.str(), com.cliffc.aa.type.TypeStr.xdual(), and com.cliffc.aa.type.TypeStr.xmeet().
_use
boolean com.cliffc.aa.type.TypeObj< O extends TypeObj< O >._use package inherited
Definition at line 17 of file TypeObj.java.
ABC
final TypeStr com.cliffc.aa.type.TypeStr.ABC = make(false,"abc") static
Definition at line 47 of file TypeStr.java.
Referenced by com.cliffc.aa.HM.TestHM4.test03(), com.cliffc.aa.HM.TestHM5.test03(), com.cliffc.aa.HM.TestHM2.test04(), com.cliffc.aa.HM.TestHM3.test04(), com.cliffc.aa.HM.TestHM2.test05(), com.cliffc.aa.HM.TestHM4.test05(), com.cliffc.aa.HM.TestHM5.test05(), com.cliffc.aa.HM.TestHM3.test05(), com.cliffc.aa.HM.TestHM3.test05a(), com.cliffc.aa.HM.TestHM.test06(), com.cliffc.aa.HM.TestHM9.test06(), com.cliffc.aa.HM.TestHM4.test19(), com.cliffc.aa.HM.TestHM5.test19(), com.cliffc.aa.HM.TestHM1.test3(), com.cliffc.aa.HM.TestHM1.test5(), com.cliffc.aa.type.TestType.testCrush(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.TestParse.testParse00(), com.cliffc.aa.TestParse.testParse01(), com.cliffc.aa.TestParse.testParse04(), com.cliffc.aa.TestParse.testParse05(), and com.cliffc.aa.node.TestNodeSmall.tmem().
DEF
final TypeStr com.cliffc.aa.type.TypeStr.DEF = con("def") static private
Definition at line 48 of file TypeStr.java.
ISUSED
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.ISUSED static inherited
Definition at line 45 of file TypeObj.java.
OBJ
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.OBJ static inherited
Definition at line 44 of file TypeObj.java.
STR
final TypeStr com.cliffc.aa.type.TypeStr.STR = make(false,null) static
Definition at line 45 of file TypeStr.java.
Referenced by com.cliffc.aa.node.NewStrNode.AddStrStr.AddStrStr(), com.cliffc.aa.node.NewStrNode.ConvertF64Str.ConvertF64Str(), com.cliffc.aa.node.NewStrNode.ConvertI64Str.ConvertI64Str(), com.cliffc.aa.type.TestType.testCrush(), com.cliffc.aa.node.TestNodeSmall.testMemoryArgs(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.node.TestNodeSmall.tmem(), com.cliffc.aa.node.NewStrNode.AddStrStr.value(), com.cliffc.aa.node.NewStrNode.ConvertI64Str.valueobj(), com.cliffc.aa.node.NewStrNode.ConvertF64Str.valueobj(), and com.cliffc.aa.type.TypeStr.widen().
TYPES
final TypeStr [] com.cliffc.aa.type.TypeStr.TYPES = new TypeStr[]{STR,ABC,DEF} static package
Definition at line 49 of file TypeStr.java.
UNUSED
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED static inherited
Definition at line 46 of file TypeObj.java.
XOBJ
final TypeObj com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.XOBJ static inherited
Definition at line 47 of file TypeObj.java.
XSTR
final TypeStr com.cliffc.aa.type.TypeStr.XSTR = STR.dual() static
Definition at line 46 of file TypeStr.java.
Referenced by com.cliffc.aa.node.NewStrNode.dead_type().
The documentation for this class was generated from the following file:
TypeStr.java