aa: com.cliffc.aa.HM.HM3.Let Class Reference
com.cliffc.aa.HM.HM3.Let Class Reference
Public Member Functions
String toString ()
Protected Member Functions
final void add_work (Worklist work)
Package Functions
Let (String arg0, Syntax body, Syntax use)
final void add_neighbors (Worklist work)
final boolean all_kids_ready ()
boolean check_progress (Worklist work)
void get_ids (VStack vstk, Worklist work)
HMType hm (Worklist work)
boolean progress ()
Package Attributes
final String _arg0
HMType _hm
Syntax[] _kids
Syntax _par
Private Member Functions
Syntax body ()
Syntax use ()
Detailed Description
Definition at line 217 of file HM3.java.
Constructor & Destructor Documentation
Let()
com.cliffc.aa.HM.HM3.Let.Let (String arg0, Syntax body, Syntax use) package
Definition at line 219 of file HM3.java.
 { _arg0=arg0; _kids=new Syntax[]{body,use}; body._par=use._par=this; }
References com.cliffc.aa.HM.HM3.Let._arg0, com.cliffc.aa.HM.HM3.Syntax._kids, com.cliffc.aa.HM.HM3.Syntax._par, com.cliffc.aa.HM.HM3.Let.body(), and com.cliffc.aa.HM.HM3.Let.use().
Member Function Documentation
add_neighbors()
final void com.cliffc.aa.HM.HM3.Syntax.add_neighbors (Worklist work) package inherited
Definition at line 128 of file HM3.java.
{
       if( _par!=null ) _par.add_work(work);
       if( _kids!=null )
         for( Syntax kid : _kids )
           kid.add_work(work);
     }
References com.cliffc.aa.HM.HM3.Syntax._kids, com.cliffc.aa.HM.HM3.Syntax._par, and com.cliffc.aa.HM.HM3.Syntax.add_work().
Referenced by com.cliffc.aa.HM.HM3.hm().
add_work()
final void com.cliffc.aa.HM.HM3.Syntax.add_work (Worklist work) protected inherited
Definition at line 126 of file HM3.java.
 {  if( all_kids_ready() ) work.push(this);  }
References com.cliffc.aa.HM.HM3.Syntax.all_kids_ready(), and com.cliffc.aa.HM.HM3.Worklist.push().
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.HM.HM3.Con.get_ids(), and com.cliffc.aa.HM.HM3.Ident.get_ids().
all_kids_ready()
final boolean com.cliffc.aa.HM.HM3.Syntax.all_kids_ready () package inherited
Definition at line 135 of file HM3.java.
{
       if( _kids==null ) return true;
       for( Syntax kid : _kids ) if( kid._hm==null ) return false;
       return true;
     }
References com.cliffc.aa.HM.HM3.Syntax._kids.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_work(), and com.cliffc.aa.HM.HM3.Syntax.check_progress().
body()
Syntax com.cliffc.aa.HM.HM3.Let.body () private
Definition at line 220 of file HM3.java.
 { return _kids[0]; }
References com.cliffc.aa.HM.HM3.Syntax._kids.
Referenced by com.cliffc.aa.HM.HM3.Let.get_ids(), com.cliffc.aa.HM.HM3.Let.hm(), com.cliffc.aa.HM.HM3.Let.Let(), com.cliffc.aa.HM.HM3.Let.progress(), and com.cliffc.aa.HM.HM3.Let.toString().
check_progress()
boolean com.cliffc.aa.HM.HM3.Syntax.check_progress (Worklist work) package inherited
Definition at line 144 of file HM3.java.
{
       if( all_kids_ready() ) // If kids are not ready, then cannot compute hm() so not on worklist
         if( _hm==null || progress() ) // Progress is possible
           if( !work.has(this) )       // Not on worklist?
             return false;             // Fails check
       if( _kids!=null )               // For all kids
         for( Syntax kid : _kids )
           if( !kid.check_progress(work) ) // Recursively check nodes that can make progress on worklist
             return false;
       return true;
     }
References com.cliffc.aa.HM.HM3.Syntax._hm, com.cliffc.aa.HM.HM3.Syntax._kids, com.cliffc.aa.HM.HM3.Syntax.all_kids_ready(), com.cliffc.aa.HM.HM3.Worklist.has(), and com.cliffc.aa.HM.HM3.Syntax.progress().
Referenced by com.cliffc.aa.HM.HM3.hm().
get_ids()
void com.cliffc.aa.HM.HM3.Let.get_ids (VStack vstk, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM3.Syntax.
Definition at line 240 of file HM3.java.
{
       HMVar var = new HMVar();
       ENV.put(_arg0, var);
       body().get_ids(new VStack(vstk,var),work);
       use() .get_ids(vstk,work);
     }
References com.cliffc.aa.HM.HM3.Let._arg0, com.cliffc.aa.HM.HM3.Let.body(), com.cliffc.aa.HM.HM3.ENV, com.cliffc.aa.HM.HM3.Syntax.get_ids(), and com.cliffc.aa.HM.HM3.Let.use().
hm()
HMType com.cliffc.aa.HM.HM3.Let.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM3.Syntax.
Definition at line 223 of file HM3.java.
{
       if( _hm!=null && !progress() ) return null;
       HMType tbody = body()._hm.find();
       HMType trez  = use() ._hm.find();
       HMType tnew  = ENV.get(_arg0).find();
       tnew.union(tbody,work);
       if( _hm!=null ) _hm.union(trez,work);
       return trez;
     }
References com.cliffc.aa.HM.HM3.Let._arg0, com.cliffc.aa.HM.HM3.Syntax._hm, com.cliffc.aa.HM.HM3.Let.body(), com.cliffc.aa.HM.HM3.ENV, com.cliffc.aa.HM.HM3.HMType.find(), com.cliffc.aa.HM.HM3.Let.progress(), com.cliffc.aa.HM.HM3.HMType.union(), and com.cliffc.aa.HM.HM3.Let.use().
progress()
boolean com.cliffc.aa.HM.HM3.Let.progress () package
Reimplemented from com.cliffc.aa.HM.HM3.Syntax.
Definition at line 232 of file HM3.java.
{
       HMType tbody = body()._hm.find();
       HMType trez  = use() ._hm.find();
       HMType tnew = ENV.get(_arg0).find();
       // Progress if tnew != tbody (they get unioned) OR
       // trez != _hm
       return !tnew.eq(tbody) || !_hm.find().eq(trez);
     }
References com.cliffc.aa.HM.HM3.Let._arg0, com.cliffc.aa.HM.HM3.Syntax._hm, com.cliffc.aa.HM.HM3.Let.body(), com.cliffc.aa.HM.HM3.ENV, com.cliffc.aa.HM.HM3.HMType.eq(), com.cliffc.aa.HM.HM3.HMType.find(), and com.cliffc.aa.HM.HM3.Let.use().
Referenced by com.cliffc.aa.HM.HM3.Let.hm().
toString()
String com.cliffc.aa.HM.HM3.Let.toString ()
Definition at line 222 of file HM3.java.
 { return "let "+_arg0+" = "+body()+" in "+use()+" }"; }
References com.cliffc.aa.HM.HM3.Let._arg0, com.cliffc.aa.HM.HM3.Let.body(), and com.cliffc.aa.HM.HM3.Let.use().
use()
Syntax com.cliffc.aa.HM.HM3.Let.use () private
Definition at line 221 of file HM3.java.
 { return _kids[1]; }
References com.cliffc.aa.HM.HM3.Syntax._kids.
Referenced by com.cliffc.aa.HM.HM3.Let.get_ids(), com.cliffc.aa.HM.HM3.Let.hm(), com.cliffc.aa.HM.HM3.Let.Let(), com.cliffc.aa.HM.HM3.Let.progress(), and com.cliffc.aa.HM.HM3.Let.toString().
Member Data Documentation
_arg0
final String com.cliffc.aa.HM.HM3.Let._arg0 package
Definition at line 218 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Let.get_ids(), com.cliffc.aa.HM.HM3.Let.hm(), com.cliffc.aa.HM.HM3.Let.Let(), com.cliffc.aa.HM.HM3.Let.progress(), and com.cliffc.aa.HM.HM3.Let.toString().
_hm
HMType com.cliffc.aa.HM.HM3.Syntax._hm package inherited
Definition at line 118 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Syntax.check_progress(), com.cliffc.aa.HM.HM3.hm(), com.cliffc.aa.HM.HM3.Con.hm(), com.cliffc.aa.HM.HM3.Ident.hm(), com.cliffc.aa.HM.HM3.Lambda.hm(), com.cliffc.aa.HM.HM3.Let.hm(), com.cliffc.aa.HM.HM3.Apply.hm(), com.cliffc.aa.HM.HM3.Lambda.progress(), com.cliffc.aa.HM.HM3.Let.progress(), and com.cliffc.aa.HM.HM3.Apply.progress().
_kids
Syntax [] com.cliffc.aa.HM.HM3.Syntax._kids package inherited
Definition at line 117 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.HM.HM3.Syntax.all_kids_ready(), com.cliffc.aa.HM.HM3.Apply.Apply(), com.cliffc.aa.HM.HM3.Apply.arg(), com.cliffc.aa.HM.HM3.Lambda.body(), com.cliffc.aa.HM.HM3.Let.body(), com.cliffc.aa.HM.HM3.Syntax.check_progress(), com.cliffc.aa.HM.HM3.Apply.fun(), com.cliffc.aa.HM.HM3.Lambda.Lambda(), com.cliffc.aa.HM.HM3.Let.Let(), and com.cliffc.aa.HM.HM3.Let.use().
_par
Syntax com.cliffc.aa.HM.HM3.Syntax._par package inherited
Definition at line 116 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.HM.HM3.Apply.Apply(), com.cliffc.aa.HM.HM3.Lambda.Lambda(), and com.cliffc.aa.HM.HM3.Let.Let().
The documentation for this class was generated from the following file:
HM3.java