aa: com.cliffc.aa.HM.HM7.Apply Class Reference
com.cliffc.aa.HM.HM7.Apply Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Apply (Syntax fun, Syntax... args)
void add_kids (Worklist work)
void add_occurs (Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
T2 lookup (String name)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
Package Attributes
final Syntax[] _args
final Syntax _fun
VStack _nongen
Syntax _par
T2 _t
Private Member Functions
T2 is_if_nil ()
Detailed Description
Definition at line 441 of file HM7.java.
Constructor & Destructor Documentation
Apply()
com.cliffc.aa.HM.HM7.Apply.Apply (Syntax fun, Syntax... args) package
Definition at line 444 of file HM7.java.
 { _fun = fun; _args = args; }
References com.cliffc.aa.HM.HM7.Apply._args, and com.cliffc.aa.HM.HM7.Apply._fun.
Member Function Documentation
add_kids()
void com.cliffc.aa.HM.HM7.Apply.add_kids (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 502 of file HM7.java.
 { for( Syntax arg : _args ) work.push(arg); }
References com.cliffc.aa.HM.HM7.Apply._args, and com.cliffc.aa.HM.HM7.Worklist.push().
add_occurs()
void com.cliffc.aa.HM.HM7.Syntax.add_occurs (Worklist work) package inherited
Reimplemented in com.cliffc.aa.HM.HM7.Field, com.cliffc.aa.HM.HM7.Let, com.cliffc.aa.HM.HM7.Lambda, and com.cliffc.aa.HM.HM7.Ident.
Definition at line 266 of file HM7.java.
 {}
Referenced by com.cliffc.aa.HM.HM7.Field.add_occurs(), and com.cliffc.aa.HM.HM7.hm().
debug_find()
T2 com.cliffc.aa.HM.HM7.Syntax.debug_find () package inherited
Definition at line 250 of file HM7.java.
 { return _t.find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM7.Syntax._t, and com.cliffc.aa.HM.HM7.T2.find().
Referenced by com.cliffc.aa.HM.HM7.hm().
find()
T2 com.cliffc.aa.HM.HM7.Syntax.find () package inherited
Definition at line 246 of file HM7.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM7.Syntax._t, and com.cliffc.aa.HM.HM7.T2.find().
Referenced by com.cliffc.aa.HM.HM7.T2._occurs_in(), com.cliffc.aa.HM.HM7.Lambda.add_occurs(), com.cliffc.aa.HM.HM7.Let.add_occurs(), com.cliffc.aa.HM.HM7.Ident.hm(), com.cliffc.aa.HM.HM7.Lambda.hm(), com.cliffc.aa.HM.HM7.Let.hm(), com.cliffc.aa.HM.HM7.Apply.hm(), com.cliffc.aa.HM.HM7.Struct.hm(), com.cliffc.aa.HM.HM7.Field.hm(), com.cliffc.aa.HM.HM7.Apply.is_if_nil(), and com.cliffc.aa.HM.HM7.Struct.prep_tree().
hm()
boolean com.cliffc.aa.HM.HM7.Apply.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 458 of file HM7.java.
{
       // Unifiying these: make_fun(this.arg0 this.arg1 -> new     )
       //                      _fun{_fun.arg0 _fun.arg1 -> _fun.rez}
       // Discover not-nil in the trivial case of directly using the 'if'
       // primitive against a T2.is_struct().  Will not work if 'if' is some
       // more hidden or complex function (e.q. '&&' or '||') or the predicate
       // implies not-null on some other struct.
       boolean progress = false;
       T2 str = is_if_nil();
       if( str!=null && str.is_struct() && str._con==null ) {
         if( work==null ) return true;
         progress = true;
         str._con = Type.NIL;    // Add nil to a struct
         work.addAll(str._deps);
       }
       // Progress if:
       //   _fun is not a function
       //   any arg-pair-unifies make progress
       //   this-unify-_fun.return makes progress
       T2 tfun = _fun.find();
       if( !tfun.is_fun() ) {
         if( work==null ) return true; // Will-progress & just-testing
         T2[] targs = new T2[_args.length+1];
         for( int i=0; i<_args.length; i++ )
           targs[i] = _args[i].find();
         targs[_args.length] = find(); // Return
         T2 nfun = T2.make_fun(targs);
         return tfun.unify(nfun,work);
       }
       if( tfun._args.length != _args.length+1 )
         throw new RuntimeException("Mismatched argument lengths");
       // Check for progress amongst arg pairs
       for( int i=0; i<_args.length; i++ ) {
         progress |= tfun.args(i).unify(_args[i].find(),work);
         if( progress && work==null )
           return true;          // Will-progress & just-testing early exit
       }
       progress |= tfun.args(_args.length).unify(find(),work);
       return progress;
     }
References com.cliffc.aa.HM.HM7.Apply._args, com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.Apply._fun, com.cliffc.aa.HM.HM7.Worklist.addAll(), com.cliffc.aa.HM.HM7.T2.args(), com.cliffc.aa.HM.HM7.Syntax.find(), com.cliffc.aa.HM.HM7.T2.is_fun(), com.cliffc.aa.HM.HM7.Apply.is_if_nil(), com.cliffc.aa.HM.HM7.T2.make_fun(), com.cliffc.aa.type.Type< T extends Type< T >.NIL, com.cliffc.aa.HM.HM7.Apply.str(), and com.cliffc.aa.HM.HM7.T2.unify().
is_if_nil()
T2 com.cliffc.aa.HM.HM7.Apply.is_if_nil () private
Definition at line 519 of file HM7.java.
{
       return _fun instanceof Ident && Util.eq(((Ident)_fun)._name,"if") && _args[0] instanceof Ident ? _args[0].find() : null;
     }
References com.cliffc.aa.HM.HM7.Apply._args, com.cliffc.aa.HM.HM7.Apply._fun, com.cliffc.aa.util.Util.eq(), and com.cliffc.aa.HM.HM7.Syntax.find().
Referenced by com.cliffc.aa.HM.HM7.Apply.hm(), and com.cliffc.aa.HM.HM7.Apply.prep_tree().
lookup()
T2 com.cliffc.aa.HM.HM7.Apply.lookup (String name) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 501 of file HM7.java.
 { return _par==null ? null : _par.lookup(name); }
References com.cliffc.aa.HM.HM7.Syntax._par, and com.cliffc.aa.HM.HM7.Syntax.lookup().
more_work()
boolean com.cliffc.aa.HM.HM7.Apply.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 512 of file HM7.java.
{
       if( !more_work_impl(work) ) return false;
       if( !_fun.more_work(work) ) return false;
       for( Syntax arg : _args ) if( !arg.more_work(work) ) return false;
       return true;
     }
References com.cliffc.aa.HM.HM7.Apply._args, com.cliffc.aa.HM.HM7.Apply._fun, com.cliffc.aa.HM.HM7.Syntax.more_work(), and com.cliffc.aa.HM.HM7.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM7.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 270 of file HM7.java.
{
       boolean no_more_work = work.has(this) || !hm(null); // Either on worklist, or no-progress
       return no_more_work;
     }
References com.cliffc.aa.HM.HM7.Worklist.has(), and com.cliffc.aa.HM.HM7.Syntax.hm().
Referenced by com.cliffc.aa.HM.HM7.Con.more_work(), com.cliffc.aa.HM.HM7.Ident.more_work(), com.cliffc.aa.HM.HM7.Lambda.more_work(), com.cliffc.aa.HM.HM7.Let.more_work(), com.cliffc.aa.HM.HM7.Apply.more_work(), com.cliffc.aa.HM.HM7.Struct.more_work(), and com.cliffc.aa.HM.HM7.Field.more_work().
p()
String com.cliffc.aa.HM.HM7.Syntax.p () inherited
Definition at line 278 of file HM7.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM7.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM7.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 279 of file HM7.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM7.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM7.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM7.Syntax.p1(), com.cliffc.aa.HM.HM7.Syntax.p2(), and com.cliffc.aa.HM.HM7.T2.str().
Referenced by com.cliffc.aa.HM.HM7.Syntax.p(), com.cliffc.aa.HM.HM7.Lambda.p2(), com.cliffc.aa.HM.HM7.Let.p2(), com.cliffc.aa.HM.HM7.Apply.p2(), com.cliffc.aa.HM.HM7.Struct.p2(), and com.cliffc.aa.HM.HM7.Field.p2().
p1()
SB com.cliffc.aa.HM.HM7.Apply.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 451 of file HM7.java.
 { return sb.p("(...)"); }
References com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM7.Apply.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 452 of file HM7.java.
{
       _fun.p0(sb,dups);
       for( Syntax arg : _args ) arg.p0(sb,dups);
       return sb;
     }
References com.cliffc.aa.HM.HM7.Apply._args, com.cliffc.aa.HM.HM7.Apply._fun, and com.cliffc.aa.HM.HM7.Syntax.p0().
prep_lookup_deps()
void com.cliffc.aa.HM.HM7.Apply.prep_lookup_deps (Ident id) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 511 of file HM7.java.
 { }
prep_tree()
int com.cliffc.aa.HM.HM7.Apply.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 503 of file HM7.java.
{
       prep_tree_impl(par,nongen,work,T2.make_leaf());
       int cnt = 1+_fun.prep_tree(this,nongen,work);
       for( Syntax arg : _args ) cnt += arg.prep_tree(this,nongen,work);
       T2 str = is_if_nil();
       if( str!=null ) str.push_update(this);
       return cnt;
     }
References com.cliffc.aa.HM.HM7.Apply._args, com.cliffc.aa.HM.HM7.Apply._fun, com.cliffc.aa.HM.HM7.Apply.is_if_nil(), com.cliffc.aa.HM.HM7.T2.make_leaf(), com.cliffc.aa.HM.HM7.Syntax.prep_tree(), com.cliffc.aa.HM.HM7.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM7.Apply.str().
prep_tree_impl()
final void com.cliffc.aa.HM.HM7.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 260 of file HM7.java.
 { _par=par; _t=t; _nongen = nongen; work.push(this); }
References com.cliffc.aa.HM.HM7.Syntax._nongen, com.cliffc.aa.HM.HM7.Syntax._par, com.cliffc.aa.HM.HM7.Syntax._t, and com.cliffc.aa.HM.HM7.Worklist.push().
Referenced by com.cliffc.aa.HM.HM7.Con.prep_tree(), com.cliffc.aa.HM.HM7.Ident.prep_tree(), com.cliffc.aa.HM.HM7.Lambda.prep_tree(), com.cliffc.aa.HM.HM7.Let.prep_tree(), com.cliffc.aa.HM.HM7.Apply.prep_tree(), com.cliffc.aa.HM.HM7.Struct.prep_tree(), and com.cliffc.aa.HM.HM7.Field.prep_tree().
str()
SB com.cliffc.aa.HM.HM7.Apply.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 445 of file HM7.java.
{
       _fun.str(sb.p("(")).p(" ");
       for( Syntax arg : _args )
         arg.str(sb).p(" ");
       return sb.unchar().p(")");
     }
References com.cliffc.aa.HM.HM7.Apply._args, com.cliffc.aa.HM.HM7.Apply._fun, com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM7.Syntax.str(), and com.cliffc.aa.util.SB.unchar().
Referenced by com.cliffc.aa.HM.HM7.Apply.hm(), and com.cliffc.aa.HM.HM7.Apply.prep_tree().
toString()
final String com.cliffc.aa.HM.HM7.Syntax.toString () inherited
Definition at line 275 of file HM7.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM7.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_args
final Syntax [] com.cliffc.aa.HM.HM7.Apply._args package
Definition at line 443 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.Apply.add_kids(), com.cliffc.aa.HM.HM7.Apply.Apply(), com.cliffc.aa.HM.HM7.Apply.hm(), com.cliffc.aa.HM.HM7.Apply.is_if_nil(), com.cliffc.aa.HM.HM7.Apply.more_work(), com.cliffc.aa.HM.HM7.Apply.p2(), com.cliffc.aa.HM.HM7.Apply.prep_tree(), and com.cliffc.aa.HM.HM7.Apply.str().
_fun
final Syntax com.cliffc.aa.HM.HM7.Apply._fun package
Definition at line 442 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.Apply.Apply(), com.cliffc.aa.HM.HM7.Apply.hm(), com.cliffc.aa.HM.HM7.Apply.is_if_nil(), com.cliffc.aa.HM.HM7.Apply.more_work(), com.cliffc.aa.HM.HM7.Apply.p2(), com.cliffc.aa.HM.HM7.Apply.prep_tree(), and com.cliffc.aa.HM.HM7.Apply.str().
_nongen
VStack com.cliffc.aa.HM.HM7.Syntax._nongen package inherited
Definition at line 244 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.Ident.hm(), and com.cliffc.aa.HM.HM7.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM7.Syntax._par package inherited
Definition at line 243 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2._occurs_in(), com.cliffc.aa.HM.HM7.Ident.add_occurs(), com.cliffc.aa.HM.HM7.hm(), com.cliffc.aa.HM.HM7.Ident.hm(), com.cliffc.aa.HM.HM7.Lambda.lookup(), com.cliffc.aa.HM.HM7.Let.lookup(), com.cliffc.aa.HM.HM7.Apply.lookup(), com.cliffc.aa.HM.HM7.Struct.lookup(), com.cliffc.aa.HM.HM7.Field.lookup(), com.cliffc.aa.HM.HM7.Ident.prep_tree(), and com.cliffc.aa.HM.HM7.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM7.Syntax._t package inherited
Definition at line 245 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.Syntax.debug_find(), com.cliffc.aa.HM.HM7.Syntax.find(), com.cliffc.aa.HM.HM7.hm(), com.cliffc.aa.HM.HM7.Syntax.p0(), com.cliffc.aa.HM.HM7.Let.prep_tree(), and com.cliffc.aa.HM.HM7.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM7.java