aa: com.cliffc.aa.type.TypeFlds Class Reference
com.cliffc.aa.type.TypeFlds Class Reference
Classes
class Key
Static Public Member Functions
static TypeFld[] clone (TypeFld[] ts)
static TypeFld[] copyOf (TypeFld[] flds, int len)
static void free (TypeFld[] ts)
static TypeFld[] get (int len)
static TypeFld[] hash_cons (TypeFld[] ts)
static TypeFld[] ts (TypeFld t0)
static TypeFld[] ts (TypeFld t0, TypeFld t1)
static TypeFld[] ts (TypeFld t0, TypeFld t1, TypeFld t2)
static TypeFld[] ts (TypeFld t0, TypeFld t1, TypeFld t2, TypeFld t3)
Private Member Functions
TypeFlds (int len)
boolean check_ (TypeFld[] ts)
TypeFld[] get ()
TypeFld[] hash_cons_ (TypeFld[] ts)
Static Private Member Functions
static TypeFlds tary (int len)
Private Attributes
final Ary< TypeFld[]> _free = new Ary<>(new TypeFld[1][],0)
final IHashMap _intern = new IHashMap()
final int _len
Static Private Attributes
static final Key K = new Key(null,0)
static final Ary< TypeFlds > TYPEARY = new Ary<>(new TypeFlds[1],0)
Detailed Description
Definition at line 8 of file TypeFlds.java.
Constructor & Destructor Documentation
TypeFlds()
com.cliffc.aa.type.TypeFlds.TypeFlds (int len) private
Definition at line 48 of file TypeFlds.java.
 { _len=len; }
References com.cliffc.aa.type.TypeFlds._len.
Referenced by com.cliffc.aa.type.TypeFlds.tary().
Member Function Documentation
check_()
boolean com.cliffc.aa.type.TypeFlds.check_ (TypeFld[] ts) private
Definition at line 50 of file TypeFlds.java.
{
     K._ts=ts;
     K._hash = Key.hash(ts);
     Key k2 = _intern.get(K);
     return k2._ts==ts;
   }
References com.cliffc.aa.type.TypeFlds.Key._hash, com.cliffc.aa.type.TypeFlds._intern, com.cliffc.aa.type.TypeFlds.Key._ts, com.cliffc.aa.util.IHashMap.get(), com.cliffc.aa.type.TypeFlds.Key.hash(), com.cliffc.aa.type.TypeFlds.K, and com.cliffc.aa.type.TypeFlds.ts().
clone()
static TypeFld [] com.cliffc.aa.type.TypeFlds.clone (TypeFld[] ts) static
Definition at line 116 of file TypeFlds.java.
{
     TypeFld[] ts2 = tary(ts.length).get();
     for( int i=0; i<ts.length; i++ )
       ts2[i] = TypeFld.malloc(ts[i]._fld,ts[i]._t,ts[i]._access,ts[i]._order);
     return ts2;
   }
References com.cliffc.aa.type.TypeFld._access, com.cliffc.aa.type.TypeFld._fld, com.cliffc.aa.type.TypeFld._order, com.cliffc.aa.type.TypeFld._t, com.cliffc.aa.type.TypeFlds.get(), com.cliffc.aa.type.TypeFld.malloc(), com.cliffc.aa.type.TypeFlds.tary(), and com.cliffc.aa.type.TypeFlds.ts().
Referenced by com.cliffc.aa.type.TypeStruct._clone(), com.cliffc.aa.type.TypeStruct.ax_impl_struct(), com.cliffc.aa.type.TypeStruct.make_from(), com.cliffc.aa.type.TypeStruct.remove_other_flds(), and com.cliffc.aa.type.TypeStruct.widen().
copyOf()
static TypeFld [] com.cliffc.aa.type.TypeFlds.copyOf (TypeFld[] flds, int len) static
Definition at line 124 of file TypeFlds.java.
{
     TypeFld[] flds2 = tary(len).get();
     System.arraycopy(flds,0,flds2,0,Math.min(flds.length,len));
     return flds2;
   }
References com.cliffc.aa.type.TypeFlds.get(), and com.cliffc.aa.type.TypeFlds.tary().
Referenced by com.cliffc.aa.type.TypeStruct.add_fld(), com.cliffc.aa.type.TypeStruct.set_fld(), and com.cliffc.aa.type.TypeStruct.update().
free()
static void com.cliffc.aa.type.TypeFlds.free (TypeFld[] ts) static
Definition at line 80 of file TypeFlds.java.
 { tary(ts.length)._free.push(ts); }
References com.cliffc.aa.type.TypeFlds._free, com.cliffc.aa.type.TypeFlds.tary(), and com.cliffc.aa.type.TypeFlds.ts().
get() [1/2]
TypeFld [] com.cliffc.aa.type.TypeFlds.get () private
Definition at line 59 of file TypeFlds.java.
{
     if( _free.isEmpty() )
       _free.push(new TypeFld[_len]);
     return _free.pop();
   }
References com.cliffc.aa.type.TypeFlds._free, and com.cliffc.aa.type.TypeFlds._len.
Referenced by com.cliffc.aa.HM.HM9.T2._as_flow(), com.cliffc.aa.HM.HM.T2._as_flow(), com.cliffc.aa.HM.HM9.Pair.apply(), com.cliffc.aa.HM.HM9.Triple.apply(), com.cliffc.aa.HM.HM.Pair.apply(), com.cliffc.aa.HM.HM.Triple.apply(), com.cliffc.aa.type.TypeFlds.clone(), com.cliffc.aa.type.TypeFlds.copyOf(), com.cliffc.aa.type.TypeStruct.crush(), com.cliffc.aa.type.TypeStruct.flatten_fields(), com.cliffc.aa.type.TypeFlds.get(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.TypeStruct.rdual(), com.cliffc.aa.type.TypeFlds.ts(), com.cliffc.aa.HM.HM9.Struct.val(), com.cliffc.aa.HM.HM.Struct.val(), com.cliffc.aa.node.NewObjNode.valueobj(), com.cliffc.aa.HM.HM9.T2.walk_types_out(), com.cliffc.aa.HM.HM.T2.walk_types_out(), com.cliffc.aa.type.TypeStruct.xdual(), and com.cliffc.aa.type.TypeStruct.xmeet1().
get() [2/2]
static TypeFld [] com.cliffc.aa.type.TypeFlds.get (int len) static
Definition at line 79 of file TypeFlds.java.
 { return tary(len).get(); }
References com.cliffc.aa.type.TypeFlds.get(), and com.cliffc.aa.type.TypeFlds.tary().
hash_cons()
static TypeFld [] com.cliffc.aa.type.TypeFlds.hash_cons (TypeFld[] ts) static
Definition at line 81 of file TypeFlds.java.
 { return tary(ts.length).hash_cons_(ts); }
References com.cliffc.aa.type.TypeFlds.hash_cons_(), com.cliffc.aa.type.TypeFlds.tary(), and com.cliffc.aa.type.TypeFlds.ts().
Referenced by com.cliffc.aa.type.TypeStruct.hashcons_freeS(), com.cliffc.aa.type.TypeStruct.mark_cyclic(), com.cliffc.aa.type.TypeStruct.rdual(), and com.cliffc.aa.type.TypeStruct.xdual().
hash_cons_()
TypeFld [] com.cliffc.aa.type.TypeFlds.hash_cons_ (TypeFld[] ts) private
Definition at line 65 of file TypeFlds.java.
{
     K._ts=ts;
     K._hash = Key.hash(ts);
     Key k2 = _intern.get(K);
     if( k2 != null ) {
       if( k2._ts!=ts ) _free.push(ts);
       return k2._ts;
     }
     _intern.put(new Key(ts,K._hash));
     return ts;
   }
References com.cliffc.aa.type.TypeFlds._free, com.cliffc.aa.type.TypeFlds.Key._hash, com.cliffc.aa.type.TypeFlds._intern, com.cliffc.aa.type.TypeFlds.Key._ts, com.cliffc.aa.util.IHashMap.get(), com.cliffc.aa.type.TypeFlds.Key.hash(), com.cliffc.aa.type.TypeFlds.K, com.cliffc.aa.util.IHashMap.put(), and com.cliffc.aa.type.TypeFlds.ts().
Referenced by com.cliffc.aa.type.TypeFlds.hash_cons().
tary()
static TypeFlds com.cliffc.aa.type.TypeFlds.tary (int len) static private
Definition at line 13 of file TypeFlds.java.
{
     TypeFlds tary = TYPEARY.atX(len);
     return tary==null ? TYPEARY.setX(len,new TypeFlds(len)) : tary;
   }
References com.cliffc.aa.type.TypeFlds.TYPEARY, and com.cliffc.aa.type.TypeFlds.TypeFlds().
Referenced by com.cliffc.aa.type.TypeFlds.clone(), com.cliffc.aa.type.TypeFlds.copyOf(), com.cliffc.aa.type.TypeFlds.free(), com.cliffc.aa.type.TypeFlds.get(), com.cliffc.aa.type.TypeFlds.hash_cons(), and com.cliffc.aa.type.TypeFlds.ts().
ts() [1/4]
static TypeFld [] com.cliffc.aa.type.TypeFlds.ts (TypeFld t0) static
Definition at line 82 of file TypeFlds.java.
{
     TypeFlds t1 = tary(1);
     TypeFld[] ts = t1.get();
     ts[0] = t0;
     return ts;
   }
References com.cliffc.aa.type.TypeFlds.get(), and com.cliffc.aa.type.TypeFlds.tary().
Referenced by com.cliffc.aa.type.TypeFlds.check_(), com.cliffc.aa.type.TypeFlds.clone(), com.cliffc.aa.type.TypeFlds.Key.equals(), com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeFlds.free(), com.cliffc.aa.type.TypeFlds.Key.hash(), com.cliffc.aa.type.TypeFlds.hash_cons(), com.cliffc.aa.type.TypeFlds.hash_cons_(), com.cliffc.aa.type.TypeFlds.Key.Key(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.TypeStruct.open(), com.cliffc.aa.type.TestApprox.testApprox2(), com.cliffc.aa.type.TestApprox.testApprox3(), com.cliffc.aa.type.TestApprox.testApprox6(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.type.TestType.testNameCycle(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.type.TestApprox.testTSMeet(), com.cliffc.aa.type.TypeFlds.ts(), and com.cliffc.aa.type.TypeStruct.tups().
ts() [2/4]
static TypeFld [] com.cliffc.aa.type.TypeFlds.ts (TypeFld t0, TypeFld t1) static
Definition at line 88 of file TypeFlds.java.
{
     TypeFlds t2 = tary(2);
     TypeFld[] ts = t2.get();
     ts[0] = t0;
     ts[1] = t1;
     return ts;
   }
References com.cliffc.aa.type.TypeFlds.get(), com.cliffc.aa.type.TypeFlds.tary(), and com.cliffc.aa.type.TypeFlds.ts().
ts() [3/4]
static TypeFld [] com.cliffc.aa.type.TypeFlds.ts (TypeFld t0, TypeFld t1, TypeFld t2) static
Definition at line 95 of file TypeFlds.java.
{
     TypeFlds t3 = tary(3);
     TypeFld[] ts = t3.get();
     ts[0] = t0;
     ts[1] = t1;
     ts[2] = t2;
     return ts;
   }
References com.cliffc.aa.type.TypeFlds.get(), com.cliffc.aa.type.TypeFlds.tary(), and com.cliffc.aa.type.TypeFlds.ts().
ts() [4/4]
static TypeFld [] com.cliffc.aa.type.TypeFlds.ts (TypeFld t0, TypeFld t1, TypeFld t2, TypeFld t3) static
Definition at line 103 of file TypeFlds.java.
{
     TypeFlds t4 = tary(4);
     TypeFld[] ts = t4.get();
     ts[0] = t0;
     ts[1] = t1;
     ts[2] = t2;
     ts[3] = t3;
     return ts;
   }
References com.cliffc.aa.type.TypeFlds.get(), com.cliffc.aa.type.TypeFlds.tary(), and com.cliffc.aa.type.TypeFlds.ts().
Member Data Documentation
_free
final Ary<TypeFld[]> com.cliffc.aa.type.TypeFlds._free = new Ary<>(new TypeFld[1][],0) private
Definition at line 47 of file TypeFlds.java.
Referenced by com.cliffc.aa.type.TypeFlds.free(), com.cliffc.aa.type.TypeFlds.get(), and com.cliffc.aa.type.TypeFlds.hash_cons_().
_intern
final IHashMap com.cliffc.aa.type.TypeFlds._intern = new IHashMap() private
Definition at line 46 of file TypeFlds.java.
Referenced by com.cliffc.aa.type.TypeFlds.check_(), and com.cliffc.aa.type.TypeFlds.hash_cons_().
_len
final int com.cliffc.aa.type.TypeFlds._len private
Definition at line 45 of file TypeFlds.java.
Referenced by com.cliffc.aa.type.TypeFlds.get(), and com.cliffc.aa.type.TypeFlds.TypeFlds().
K
final Key com.cliffc.aa.type.TypeFlds.K = new Key(null,0) static private
Definition at line 18 of file TypeFlds.java.
Referenced by com.cliffc.aa.type.TypeFlds.check_(), and com.cliffc.aa.type.TypeFlds.hash_cons_().
TYPEARY
final Ary<TypeFlds> com.cliffc.aa.type.TypeFlds.TYPEARY = new Ary<>(new TypeFlds[1],0) static private
Definition at line 10 of file TypeFlds.java.
Referenced by com.cliffc.aa.type.TypeFlds.tary().
The documentation for this class was generated from the following file:
TypeFlds.java