aa: com.cliffc.aa.HM.HM7.T2 Class Reference
com.cliffc.aa.HM.HM7.T2 Class Reference
Public Member Functions
String p ()
String toString ()
Package Functions
boolean _cycle_equals (T2 t)
VBitSet _get_dups (VBitSet visit, VBitSet dups)
boolean _nongen_in (VStack nongen)
boolean _occurs_in (Syntax syn)
boolean _occurs_in_type (T2 x)
void add_deps_work (Worklist work)
T2 args (int i)
T2 copy ()
boolean cycle_equals (T2 t)
T2 find ()
boolean fresh_unify (T2 that, VStack nongen, Worklist work)
VBitSet get_dups (VBitSet dups)
boolean is_base ()
boolean is_fun ()
boolean is_leaf ()
boolean is_nil ()
boolean is_struct ()
boolean isa (String name)
boolean no_uf ()
boolean nongen_in (VStack syn)
boolean occurs_in (Syntax syn)
boolean occurs_in_type (T2 x)
boolean or0 (T2 that, Worklist work)
String p (VBitSet dups)
T2 push_update (Ary< Syntax > as)
void push_update (Syntax a)
SB str (SB sb, VBitSet visit, VBitSet dups)
boolean unify (T2 that, Worklist work)
boolean union (T2 that, Worklist work)
Static Package Functions
static T2 make_base (Type con)
static T2 make_fun (T2... args)
static T2 make_leaf ()
static T2 make_nil ()
static T2 make_struct (String[] ids, T2[] flds)
static T2 prim (String name, T2... args)
static void reset ()
Package Attributes
T2[] _args
Type _con
Ary< Syntax > _deps
String[] _ids
String _name
final int _uid
Static Package Attributes
static final VBitSet UPDATE_VISIT = new VBitSet()
Private Member Functions
T2 (@NotNull String name, Type con, String[] ids, T2 @NotNull ... args)
boolean _cycle_equals_struct (T2 t)
T2 _fresh (VStack nongen)
boolean _fresh_unify (T2 that, VStack nongen, Worklist work)
boolean _fresh_unify_struct (T2 that, VStack nongen, Worklist work)
SB _p (SB sb, VBitSet visit, VBitSet dups)
boolean _unify (T2 that, Worklist work)
void add_deps_work_impl (Worklist work)
void add_fld (String id, T2 fld, Worklist work)
long dbl_uid (T2 t)
boolean fresh_base (T2 that, Worklist work)
void push_update_impl (Syntax a)
boolean unify_base (T2 that, Worklist work)
boolean vput (T2 that, boolean progress)
Static Private Member Functions
static SB str (SB sb, VBitSet visit, T2 t, VBitSet dups)
Static Private Attributes
static final HashMap< T2, T2 > CDUPS = new HashMap<>()
static int CNT =0
static final HashMap< Long, T2 > DUPS = new HashMap<>()
static final VBitSet ODUPS = new VBitSet()
static final HashMap< T2, T2 > VARS = new HashMap<>()
static int VCNT
static final HashMap< T2, Integer > VNAMES = new HashMap<>()
Detailed Description
Definition at line 621 of file HM7.java.
Constructor & Destructor Documentation
T2()
com.cliffc.aa.HM.HM7.T2.T2 (@NotNull String name, Type con, String[] ids, T2 @NotNull ... args) private
Definition at line 651 of file HM7.java.
{
       _uid = CNT++;
       _name= name;
       _con = con;
       _ids = ids;
       _args= args;
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._con, com.cliffc.aa.HM.HM7.T2._ids, com.cliffc.aa.HM.HM7.T2._name, com.cliffc.aa.HM.HM7.T2._uid, com.cliffc.aa.HM.HM7.T2.args(), and com.cliffc.aa.HM.HM7.T2.CNT.
Referenced by com.cliffc.aa.HM.HM7.T2.copy(), com.cliffc.aa.HM.HM7.T2.make_base(), com.cliffc.aa.HM.HM7.T2.make_fun(), com.cliffc.aa.HM.HM7.T2.make_leaf(), com.cliffc.aa.HM.HM7.T2.make_nil(), com.cliffc.aa.HM.HM7.T2.make_struct(), and com.cliffc.aa.HM.HM7.T2.prim().
Member Function Documentation
_cycle_equals()
boolean com.cliffc.aa.HM.HM7.T2._cycle_equals (T2 t) package
Definition at line 968 of file HM7.java.
{
       assert no_uf() && t.no_uf();
       if( this==t ) return true;
       if( is_base() && t.is_base() )
         return _con==t._con;    // Base-cases have to be completely identical
       if( !Util.eq(_name,t._name) ||       // Wrong type-var names
           _args.length != t._args.length ) // Mismatched sizes
         return false;
       if( _args==t._args ) return true;
       // Cycles stall the equal/unequal decision until we see a difference.
       T2 tc = CDUPS.get(this);
       if( tc!=null )
         return tc==t; // Cycle check; true if both cycling the same
       CDUPS.put(this,t);
       if( is_struct() )         // Struct equality honors field names without regard to order
         return _cycle_equals_struct(t);
       for( int i=0; i<_args.length; i++ )
         if( !args(i)._cycle_equals(t.args(i)) )
           return false;
       return true;
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._con, com.cliffc.aa.HM.HM7.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM7.T2._name, com.cliffc.aa.HM.HM7.T2.args(), com.cliffc.aa.HM.HM7.T2.CDUPS, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM7.T2.is_base(), com.cliffc.aa.HM.HM7.T2.is_struct(), and com.cliffc.aa.HM.HM7.T2.no_uf().
Referenced by com.cliffc.aa.HM.HM7.T2._cycle_equals_struct(), and com.cliffc.aa.HM.HM7.T2.cycle_equals().
_cycle_equals_struct()
boolean com.cliffc.aa.HM.HM7.T2._cycle_equals_struct (T2 t) private
Definition at line 990 of file HM7.java.
{
       assert is_struct() && t.is_struct();
       if( _con != t._con ) return false;
       for( int i=0; i<_args.length; i++ ) {
         int idx = Util.find(t._ids,_ids[i]);
         if( idx==-1 || !args(i)._cycle_equals(t.args(idx)) )
           return false;
       }
       return true;
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._con, com.cliffc.aa.HM.HM7.T2._cycle_equals(), com.cliffc.aa.HM.HM7.T2._ids, com.cliffc.aa.HM.HM7.T2.args(), com.cliffc.aa.util.Util.find(), and com.cliffc.aa.HM.HM7.T2.is_struct().
Referenced by com.cliffc.aa.HM.HM7.T2._cycle_equals().
_fresh()
T2 com.cliffc.aa.HM.HM7.T2._fresh (VStack nongen) private
Definition at line 894 of file HM7.java.
{
       assert no_uf();
       T2 rez = VARS.get(this);
       if( rez!=null ) return rez; // Been there, done that
       if( is_leaf() ) {
         // If occurs_in lexical scope, keep same variable, else make a new leaf
         T2 t = nongen_in(nongen) ? this : T2.make_leaf();
         VARS.put(this,t);
         return t;
       } else {                  // Structure is deep-replicated
         T2 t = copy();
         VARS.put(this,t);       // Stop cyclic structure looping
         for( int i=0; i<_args.length; i++ )
           t._args[i] = args(i)._fresh(nongen);
         return t;
       }
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._fresh(), com.cliffc.aa.HM.HM7.T2.args(), com.cliffc.aa.HM.HM7.T2.copy(), com.cliffc.aa.HM.HM7.T2.is_leaf(), com.cliffc.aa.HM.HM7.T2.make_leaf(), com.cliffc.aa.HM.HM7.T2.no_uf(), com.cliffc.aa.HM.HM7.T2.nongen_in(), and com.cliffc.aa.HM.HM7.T2.VARS.
Referenced by com.cliffc.aa.HM.HM7.T2._fresh(), com.cliffc.aa.HM.HM7.T2._fresh_unify(), and com.cliffc.aa.HM.HM7.T2._fresh_unify_struct().
_fresh_unify()
boolean com.cliffc.aa.HM.HM7.T2._fresh_unify (T2 that, VStack nongen, Worklist work) private
Definition at line 830 of file HM7.java.
{
       assert no_uf() && that.no_uf();
       T2 prior = VARS.get(this);
       if( prior!=null )         // Been there, done that
         return prior.find()._unify(that,work);  // Also 'prior' needs unification with 'that'
       if( cycle_equals(that) ) return vput(that,false);
       // Attempting to pre-compute occurs_in, by computing 'is_fresh' in the
       // Ident.hm() call does NOT work.  The 'is_fresh' is for the top-layer
       // only, not the internal layers.  As soon as we structural recurse down
       // a layer, 'is_fresh' does not correlate with an occurs_in check.
       if( nongen_in(nongen) ) return vput(that,_unify(that,work)); // Famous 'occurs-check', switch to normal unify
       if( this.is_leaf() ) return vput(that,false); // Lazy map LHS tvar to RHS
       if( that.is_leaf() )             // RHS is a tvar; union with a deep copy of LHS
         return work==null || vput(that,that.union(_fresh(nongen),work));
       // Bases MEET cons in RHS
       if( is_base() && that.is_base() ) return vput(that,fresh_base(that,work));
       // Unify struct with nil
       if( is_nil() && that.is_struct() ) return vput(that,or0(that,work));
       if( that.is_nil() && is_struct() )
         return work==null || vput(that,that.or0(_fresh(nongen),work));
       if( !Util.eq(_name,that._name) ||
           (!is_struct() && _args.length != that._args.length) )
         throw new RuntimeException("Cannot unify "+this+" and "+that);
       // Structural recursion unification, lazy on LHS
       vput(that,false); // Early set, to stop cycles
       boolean progress = false;
       if( is_struct() )
         progress = _fresh_unify_struct(that,nongen,work);
       else {
         for( int i=0; i<_args.length; i++ ) {
           progress |= args(i)._fresh_unify(that.args(i),nongen,work);
           if( progress && work==null ) return true;
         }
       }
       return progress;
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._fresh(), com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM7.T2._name, com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM7.T2.args(), com.cliffc.aa.HM.HM7.T2.cycle_equals(), com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM7.T2.find(), com.cliffc.aa.HM.HM7.T2.fresh_base(), com.cliffc.aa.HM.HM7.T2.is_base(), com.cliffc.aa.HM.HM7.T2.is_leaf(), com.cliffc.aa.HM.HM7.T2.is_nil(), com.cliffc.aa.HM.HM7.T2.is_struct(), com.cliffc.aa.HM.HM7.T2.no_uf(), com.cliffc.aa.HM.HM7.T2.nongen_in(), com.cliffc.aa.HM.HM7.T2.or0(), com.cliffc.aa.HM.HM7.T2.union(), com.cliffc.aa.HM.HM7.T2.VARS, and com.cliffc.aa.HM.HM7.T2.vput().
Referenced by com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2._fresh_unify_struct(), and com.cliffc.aa.HM.HM7.T2.fresh_unify().
_fresh_unify_struct()
boolean com.cliffc.aa.HM.HM7.T2._fresh_unify_struct (T2 that, VStack nongen, Worklist work) private
Definition at line 871 of file HM7.java.
{
       assert is_struct() && that.is_struct();
       if( _con!=null && that._con==null ) {
         if( work==null ) return true; // Will progress
         that._con = Type.NIL;         // Allow nil
       }
       boolean progress = false;
       for( int i=0; i<_args.length; i++ ) {
         int idx = Util.find(that._ids,_ids[i]);
         if( idx == -1 ) {       // Missing field on RHS
           if( work==null ) return true; // Will definitely make progress
           progress = true;
           that.add_fld(_ids[i],args(i)._fresh(nongen), work);
         } else
           progress |= args(i)._fresh_unify(that.args(idx),nongen,work);
         if( progress && work==null ) return true;
       }
       return progress;
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._con, com.cliffc.aa.HM.HM7.T2._fresh(), com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2._ids, com.cliffc.aa.HM.HM7.T2.add_fld(), com.cliffc.aa.HM.HM7.T2.args(), com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM7.T2.is_struct(), and com.cliffc.aa.type.Type< T extends Type< T >.NIL.
Referenced by com.cliffc.aa.HM.HM7.T2._fresh_unify().
_get_dups()
VBitSet com.cliffc.aa.HM.HM7.T2._get_dups (VBitSet visit, VBitSet dups) package
Definition at line 1034 of file HM7.java.
{
       if( visit.tset(_uid) && no_uf() ) dups.set(_uid);
       else
         for( T2 t : _args )
           if( t!=null )
             t._get_dups(visit,dups);
       return dups;
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._uid, com.cliffc.aa.HM.HM7.T2.no_uf(), and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.HM.HM7.T2.get_dups().
_nongen_in()
boolean com.cliffc.aa.HM.HM7.T2._nongen_in (VStack nongen) package
Definition at line 953 of file HM7.java.
{
       for( T2 t2 : nongen )
         if( _occurs_in_type(t2.find()) )
           return true;
       return false;
     }
References com.cliffc.aa.HM.HM7.T2._occurs_in_type().
Referenced by com.cliffc.aa.HM.HM7.T2.nongen_in().
_occurs_in()
boolean com.cliffc.aa.HM.HM7.T2._occurs_in (Syntax syn) package
Definition at line 928 of file HM7.java.
{
       for( ; syn!=null; syn=syn._par )
         if( _occurs_in_type(syn.find()) )
           return true;
       return false;
     }
References com.cliffc.aa.HM.HM7.T2._occurs_in_type(), com.cliffc.aa.HM.HM7.Syntax._par, and com.cliffc.aa.HM.HM7.Syntax.find().
Referenced by com.cliffc.aa.HM.HM7.T2.occurs_in().
_occurs_in_type()
boolean com.cliffc.aa.HM.HM7.T2._occurs_in_type (T2 x) package
Definition at line 935 of file HM7.java.
{
       assert no_uf() && x.no_uf();
       if( x==this ) return true;
       if( ODUPS.tset(x._uid) ) return false; // Been there, done that
       if( !x.is_leaf() )
         for( int i=0; i<x._args.length; i++ )
           if( _occurs_in_type(x.args(i)) )
             return true;
       return false;
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._uid, com.cliffc.aa.HM.HM7.T2.args(), com.cliffc.aa.HM.HM7.T2.is_leaf(), com.cliffc.aa.HM.HM7.T2.no_uf(), com.cliffc.aa.HM.HM7.T2.ODUPS, and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.HM.HM7.T2._nongen_in(), com.cliffc.aa.HM.HM7.T2._occurs_in(), and com.cliffc.aa.HM.HM7.T2.occurs_in_type().
_p()
SB com.cliffc.aa.HM.HM7.T2._p (SB sb, VBitSet visit, VBitSet dups) private
Definition at line 1086 of file HM7.java.
{
       assert no_uf();
       if( is_base() ) return sb.p(_con instanceof TypeMemPtr ? "str" : _con.toString() );
       if( is_leaf() || dups.get(_uid) ) { // Leafs or Duplicates?  Take some effort to pretty-print cycles
         Integer ii = VNAMES.get(this);
         if( ii==null )  VNAMES.put(this,ii=VCNT++);
         // 2nd and later visits use the short form
         boolean later = !is_leaf() && visit.tset(_uid);
         if( later ) sb.p('$');
         char c = (char)('A'+ii);
         if( c<'V' ) sb.p(c); else sb.p("V"+ii);
         if( is_leaf() || later ) return sb;
         // First visit prints the V._uid and the type
         sb.p(':');
       }
       // Special printing for functions: { arg -> body }
       if( is_fun() ) {
         sb.p("{ ");
         for( int i=0; i<_args.length-1; i++ )
           args(i)._p(sb,visit,dups).p(" ");
         return args(_args.length-1)._p(sb.p("-> "),visit,dups).p(" }");
       }
       // Special printing for structures: @{ fld0 = body, fld1 = body, ... }
       if( is_struct() ) {
         sb.p("@{");
         for( int i=0; i<_ids.length; i++ )
           args(i)._p(sb.p(' ').p(_ids[i]).p(" = "),visit,dups).p(',');
         sb.unchar().p("}");
         if( _con==Type.NIL ) sb.p('?');
         return sb;
       }
       // Generic structural T2: (fun arg0 arg1...)
       sb.p("(").p(_name).p(" ");
       for( int i=0; i<_args.length; i++ ) args(i)._p(sb,visit,dups).p(" ");
       return sb.unchar().p(")");
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._con, com.cliffc.aa.HM.HM7.T2._ids, com.cliffc.aa.HM.HM7.T2._name, com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM7.T2._uid, com.cliffc.aa.HM.HM7.T2.args(), com.cliffc.aa.HM.HM7.T2.is_base(), com.cliffc.aa.HM.HM7.T2.is_fun(), com.cliffc.aa.HM.HM7.T2.is_leaf(), com.cliffc.aa.HM.HM7.T2.is_struct(), com.cliffc.aa.type.Type< T extends Type< T >.NIL, com.cliffc.aa.HM.HM7.T2.no_uf(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.Type< T extends Type< T >.toString(), com.cliffc.aa.util.VBitSet.tset(), com.cliffc.aa.util.SB.unchar(), com.cliffc.aa.HM.HM7.T2.VCNT, and com.cliffc.aa.HM.HM7.T2.VNAMES.
Referenced by com.cliffc.aa.HM.HM7.T2._p(), and com.cliffc.aa.HM.HM7.T2.p().
_unify()
boolean com.cliffc.aa.HM.HM7.T2._unify (T2 that, Worklist work) private
Definition at line 735 of file HM7.java.
{
       assert no_uf() && that.no_uf();
       if( this==that ) return false;
       // two leafs union in either order, so keep lower uid
       if( is_leaf() && that.is_leaf() && _uid<that._uid ) return that.union(this,work);
       if(      is_leaf() ) return      union(that,work);
       if( that.is_leaf() ) return that.union(this,work);
       if( is_base() && that.is_base() ) return unify_base(that,work);
       // Unify struct with nil
       if( is_nil() && that.is_struct() ) return or0(that,work);
       if( that.is_nil() && is_struct() ) return that.or0(this,work);
       if( !Util.eq(_name,that._name) )
         throw new RuntimeException("Cannot unify "+this+" and "+that);
       assert _args!=that._args; // Not expecting to share _args and not 'this'
       if( !is_struct() && _args.length != that._args.length )
         throw new RuntimeException("Cannot unify "+this+" and "+that);
       // Cycle check
       long luid = dbl_uid(that);
       T2 rez = DUPS.get(luid);
       assert rez==null || rez==that;
       if( rez!=null ) return false; // Been there, done that
       DUPS.put(luid,that);          // Close cycles
       if( work==null ) return true; // Here we definitely make progress; bail out early if just testing
       // Structural recursion unification.
       // Structs unify only on matching fields, and add missing fields.
       if( is_struct() ) {
         // Unification for structs is more complicated; args are aligned via
         // field names and not by position.
         for( int i=0; i<_ids.length; i++ ) { // For all fields in LHS
           int idx = Util.find(that._ids,_ids[i]);
           if( idx==-1 ) that.add_fld(_ids[i],args(i), work); // Extend 'that' with matching field from 'this'
           else args(i)._unify(that.args(idx),work);    // Unify matching field
           that = that.find();                          // Recursively, might have already rolled this up
         }
         if( _con!=null && that._con==null ) that._con=Type.NIL;
         if( this==that ) return true; // Might have unioned this-into-that recursively, exit now with progress
       } else {
         for( int i=0; i<_args.length; i++ ) // For all fields in LHS
           args(i)._unify(that.args(i),work);
       }
       return union(that,work);
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._con, com.cliffc.aa.HM.HM7.T2._ids, com.cliffc.aa.HM.HM7.T2._name, com.cliffc.aa.HM.HM7.T2._uid, com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM7.T2.add_fld(), com.cliffc.aa.HM.HM7.T2.args(), com.cliffc.aa.HM.HM7.T2.dbl_uid(), com.cliffc.aa.HM.HM7.T2.DUPS, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM7.T2.find(), com.cliffc.aa.HM.HM7.T2.is_base(), com.cliffc.aa.HM.HM7.T2.is_leaf(), com.cliffc.aa.HM.HM7.T2.is_nil(), com.cliffc.aa.HM.HM7.T2.is_struct(), com.cliffc.aa.type.Type< T extends Type< T >.NIL, com.cliffc.aa.HM.HM7.T2.no_uf(), com.cliffc.aa.HM.HM7.T2.or0(), com.cliffc.aa.HM.HM7.T2.unify_base(), and com.cliffc.aa.HM.HM7.T2.union().
Referenced by com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2._unify(), and com.cliffc.aa.HM.HM7.T2.unify().
add_deps_work()
void com.cliffc.aa.HM.HM7.T2.add_deps_work (Worklist work) package
Definition at line 1018 of file HM7.java.
 { assert UPDATE_VISIT.isEmpty(); add_deps_work_impl(work); UPDATE_VISIT.clear(); }
References com.cliffc.aa.HM.HM7.T2.add_deps_work_impl(), and com.cliffc.aa.HM.HM7.T2.UPDATE_VISIT.
Referenced by com.cliffc.aa.HM.HM7.Ident.add_occurs().
add_deps_work_impl()
void com.cliffc.aa.HM.HM7.T2.add_deps_work_impl (Worklist work) private
Definition at line 1019 of file HM7.java.
{
       if( is_leaf() || _args.length==0 ) {
         work.addAll(_deps);
       } else {
         if( UPDATE_VISIT.tset(_uid) ) return;
         for( int i=0; i<_args.length; i++ )
           args(i).add_deps_work_impl(work);
       }
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._deps, com.cliffc.aa.HM.HM7.T2._uid, com.cliffc.aa.HM.HM7.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM7.Worklist.addAll(), com.cliffc.aa.HM.HM7.T2.args(), com.cliffc.aa.HM.HM7.T2.is_leaf(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.HM.HM7.T2.UPDATE_VISIT.
Referenced by com.cliffc.aa.HM.HM7.T2.add_deps_work(), and com.cliffc.aa.HM.HM7.T2.add_deps_work_impl().
add_fld()
void com.cliffc.aa.HM.HM7.T2.add_fld (String id, T2 fld, Worklist work) private
Definition at line 783 of file HM7.java.
{
       assert is_struct();
       int len = _ids.length;
       _ids  = Arrays.copyOf( _ids,len+1);
       _args = Arrays.copyOf(_args,len+1);
       _ids [len] = id ;
       _args[len] = fld;
       work.addAll(_deps); //
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._deps, com.cliffc.aa.HM.HM7.T2._ids, com.cliffc.aa.HM.HM7.Worklist.addAll(), com.cliffc.aa.HM.HM7.id(), and com.cliffc.aa.HM.HM7.T2.is_struct().
Referenced by com.cliffc.aa.HM.HM7.T2._fresh_unify_struct(), and com.cliffc.aa.HM.HM7.T2._unify().
args()
T2 com.cliffc.aa.HM.HM7.T2.args (int i) package
Definition at line 681 of file HM7.java.
                    {
       T2 u = _args[i];
       T2 uu = u.find();
       return u==uu ? uu : (_args[i]=uu);
     }
References com.cliffc.aa.HM.HM7.T2._args, and com.cliffc.aa.HM.HM7.T2.find().
Referenced by com.cliffc.aa.HM.HM7.T2._cycle_equals(), com.cliffc.aa.HM.HM7.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM7.T2._fresh(), com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM7.T2._occurs_in_type(), com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM7.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM7.Lambda.hm(), com.cliffc.aa.HM.HM7.Apply.hm(), com.cliffc.aa.HM.HM7.Struct.hm(), com.cliffc.aa.HM.HM7.T2.make_fun(), com.cliffc.aa.HM.HM7.T2.prim(), com.cliffc.aa.HM.HM7.T2.push_update_impl(), and com.cliffc.aa.HM.HM7.T2.T2().
copy()
T2 com.cliffc.aa.HM.HM7.T2.copy () package
Definition at line 649 of file HM7.java.
 { return new T2(_name,_con,_ids,new T2[_args.length]); }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._con, com.cliffc.aa.HM.HM7.T2._ids, com.cliffc.aa.HM.HM7.T2._name, and com.cliffc.aa.HM.HM7.T2.T2().
Referenced by com.cliffc.aa.HM.HM7.T2._fresh().
cycle_equals()
boolean com.cliffc.aa.HM.HM7.T2.cycle_equals (T2 t) package
Definition at line 962 of file HM7.java.
{
       assert CDUPS.isEmpty();
       boolean rez = _cycle_equals(t);
       CDUPS.clear();
       return rez;
     }
References com.cliffc.aa.HM.HM7.T2._cycle_equals(), and com.cliffc.aa.HM.HM7.T2.CDUPS.
Referenced by com.cliffc.aa.HM.HM7.T2._fresh_unify().
dbl_uid()
long com.cliffc.aa.HM.HM7.T2.dbl_uid (T2 t) private
Definition at line 793 of file HM7.java.
 { return ((long)_uid<<32)|t._uid; }
References com.cliffc.aa.HM.HM7.T2._uid.
Referenced by com.cliffc.aa.HM.HM7.T2._unify().
find()
T2 com.cliffc.aa.HM.HM7.T2.find () package
Definition at line 669 of file HM7.java.
               {
       if( !is_leaf() ) return this; // Shortcut
       T2 u = _args[0];
       if( u==null ) return this; // Shortcut
       if( u.no_uf() ) return u;  // Shortcut
       // U-F fixup
       while( u.is_leaf() && u._args[0]!=null ) u = u._args[0];
       T2 v = this, v2;
       while( !v.is_leaf() && (v2=v._args[0])!=u ) { v._args[0]=u; v = v2; }
       return u;
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2.is_leaf(), and com.cliffc.aa.HM.HM7.T2.no_uf().
Referenced by com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM7.Ident.add_occurs(), com.cliffc.aa.HM.HM7.T2.args(), com.cliffc.aa.HM.HM7.Syntax.debug_find(), com.cliffc.aa.HM.HM7.Syntax.find(), com.cliffc.aa.HM.HM7.hm(), com.cliffc.aa.HM.HM7.Ident.hm(), com.cliffc.aa.HM.HM7.T2.p(), com.cliffc.aa.HM.HM7.Lambda.targ(), and com.cliffc.aa.HM.HM7.Let.targ().
fresh_base()
boolean com.cliffc.aa.HM.HM7.T2.fresh_base (T2 that, Worklist work) private
Definition at line 804 of file HM7.java.
{
       Type con = _con.meet(that._con);
       if( con==that._con ) return false; // No progress
       if( work==null ) return true;
       that._con = con;          // Yes progress, but no update if null work
       return true;
     }
References com.cliffc.aa.HM.HM7.T2._con, and com.cliffc.aa.type.Type< T extends Type< T >.meet().
Referenced by com.cliffc.aa.HM.HM7.T2._fresh_unify().
fresh_unify()
boolean com.cliffc.aa.HM.HM7.T2.fresh_unify (T2 that, VStack nongen, Worklist work) package
Definition at line 819 of file HM7.java.
{
       assert VARS.isEmpty() && DUPS.isEmpty();
       int old = CNT;
       boolean progress = _fresh_unify(that,nongen,work);
       VARS.clear();  DUPS.clear();
       if( work==null && old!=CNT && DEBUG_LEAKS )
         throw unimpl("busted, made T2s but just testing");
       return progress;
     }
References com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2.CNT, com.cliffc.aa.HM.HM7.DEBUG_LEAKS, com.cliffc.aa.HM.HM7.T2.DUPS, and com.cliffc.aa.HM.HM7.T2.VARS.
Referenced by com.cliffc.aa.HM.HM7.Ident.hm().
get_dups()
VBitSet com.cliffc.aa.HM.HM7.T2.get_dups (VBitSet dups) package
Definition at line 1033 of file HM7.java.
 { return _get_dups(new VBitSet(),dups); }
References com.cliffc.aa.HM.HM7.T2._get_dups().
Referenced by com.cliffc.aa.HM.HM7.T2.p(), com.cliffc.aa.HM.HM7.Syntax.p0(), and com.cliffc.aa.HM.HM7.T2.toString().
is_base()
boolean com.cliffc.aa.HM.HM7.T2.is_base () package
Definition at line 663 of file HM7.java.
 { return isa("Base") && _con!=null; }
References com.cliffc.aa.HM.HM7.T2._con, and com.cliffc.aa.HM.HM7.T2.isa().
Referenced by com.cliffc.aa.HM.HM7.T2._cycle_equals(), com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM7.T2.occurs_in(), and com.cliffc.aa.HM.HM7.T2.str().
is_fun()
boolean com.cliffc.aa.HM.HM7.T2.is_fun () package
Definition at line 665 of file HM7.java.
 { return isa("->"); }
References com.cliffc.aa.HM.HM7.T2.isa().
Referenced by com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM7.Lambda.hm(), com.cliffc.aa.HM.HM7.Apply.hm(), and com.cliffc.aa.HM.HM7.T2.str().
is_leaf()
boolean com.cliffc.aa.HM.HM7.T2.is_leaf () package
Definition at line 660 of file HM7.java.
 { return _name.charAt(0)=='V' || (isa("Base") && _con==null); }
References com.cliffc.aa.HM.HM7.T2._con, com.cliffc.aa.HM.HM7.T2._name, and com.cliffc.aa.HM.HM7.T2.isa().
Referenced by com.cliffc.aa.HM.HM7.T2._fresh(), com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2._occurs_in_type(), com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM7.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM7.T2.find(), com.cliffc.aa.HM.HM7.T2.no_uf(), and com.cliffc.aa.HM.HM7.T2.str().
is_nil()
boolean com.cliffc.aa.HM.HM7.T2.is_nil () package
Definition at line 664 of file HM7.java.
 { return isa("Nil"); }
References com.cliffc.aa.HM.HM7.T2.isa().
Referenced by com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2._unify(), and com.cliffc.aa.HM.HM7.T2.or0().
is_struct()
boolean com.cliffc.aa.HM.HM7.T2.is_struct () package
Definition at line 666 of file HM7.java.
 { return isa("@{}"); }
References com.cliffc.aa.HM.HM7.T2.isa().
Referenced by com.cliffc.aa.HM.HM7.T2._cycle_equals(), com.cliffc.aa.HM.HM7.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM7.T2.add_fld(), com.cliffc.aa.HM.HM7.Struct.hm(), com.cliffc.aa.HM.HM7.T2.or0(), and com.cliffc.aa.HM.HM7.T2.str().
isa()
boolean com.cliffc.aa.HM.HM7.T2.isa (String name) package
Definition at line 662 of file HM7.java.
 { return Util.eq(_name,name); }
References com.cliffc.aa.HM.HM7.T2._name, and com.cliffc.aa.util.Util.eq().
Referenced by com.cliffc.aa.HM.HM7.T2.is_base(), com.cliffc.aa.HM.HM7.T2.is_fun(), com.cliffc.aa.HM.HM7.T2.is_leaf(), com.cliffc.aa.HM.HM7.T2.is_nil(), and com.cliffc.aa.HM.HM7.T2.is_struct().
make_base()
static T2 com.cliffc.aa.HM.HM7.T2.make_base (Type con) static package
Definition at line 645 of file HM7.java.
 { return new T2("Base",con,null); }
References com.cliffc.aa.HM.HM7.T2.T2().
Referenced by com.cliffc.aa.HM.HM7.hm(), and com.cliffc.aa.HM.HM7.Con.prep_tree().
make_fun()
static T2 com.cliffc.aa.HM.HM7.T2.make_fun (T2... args) static package
Definition at line 643 of file HM7.java.
 { return new T2("->",null,null,args); }
References com.cliffc.aa.HM.HM7.T2.args(), and com.cliffc.aa.HM.HM7.T2.T2().
Referenced by com.cliffc.aa.HM.HM7.hm(), com.cliffc.aa.HM.HM7.Lambda.hm(), and com.cliffc.aa.HM.HM7.Apply.hm().
make_leaf()
static T2 com.cliffc.aa.HM.HM7.T2.make_leaf () static package
Definition at line 644 of file HM7.java.
 { return new T2("V"+CNT,null,null,new T2[1]); }
References com.cliffc.aa.HM.HM7.T2.CNT, and com.cliffc.aa.HM.HM7.T2.T2().
Referenced by com.cliffc.aa.HM.HM7.T2._fresh(), com.cliffc.aa.HM.HM7.hm(), com.cliffc.aa.HM.HM7.Lambda.Lambda(), com.cliffc.aa.HM.HM7.Let.Let(), com.cliffc.aa.HM.HM7.Ident.prep_tree(), com.cliffc.aa.HM.HM7.Lambda.prep_tree(), com.cliffc.aa.HM.HM7.Apply.prep_tree(), and com.cliffc.aa.HM.HM7.Field.prep_tree().
make_nil()
static T2 com.cliffc.aa.HM.HM7.T2.make_nil () static package
Definition at line 646 of file HM7.java.
 { return new T2("Nil",null,null); }
References com.cliffc.aa.HM.HM7.T2.T2().
Referenced by com.cliffc.aa.HM.HM7.hm(), and com.cliffc.aa.HM.HM7.Con.prep_tree().
make_struct()
static T2 com.cliffc.aa.HM.HM7.T2.make_struct (String[] ids, T2[] flds) static package
Definition at line 647 of file HM7.java.
 { return new T2("@{}", null,ids,flds); }
References com.cliffc.aa.HM.HM7.T2.T2().
Referenced by com.cliffc.aa.HM.HM7.Struct.hm(), com.cliffc.aa.HM.HM7.Field.hm(), and com.cliffc.aa.HM.HM7.Struct.prep_tree().
no_uf()
boolean com.cliffc.aa.HM.HM7.T2.no_uf () package
Definition at line 661 of file HM7.java.
 { return !is_leaf() || _args[0]==null; }
References com.cliffc.aa.HM.HM7.T2._args, and com.cliffc.aa.HM.HM7.T2.is_leaf().
Referenced by com.cliffc.aa.HM.HM7.T2._cycle_equals(), com.cliffc.aa.HM.HM7.T2._fresh(), com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2._get_dups(), com.cliffc.aa.HM.HM7.T2._occurs_in_type(), com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM7.T2.find(), com.cliffc.aa.HM.HM7.T2.push_update_impl(), and com.cliffc.aa.HM.HM7.T2.union().
nongen_in()
boolean com.cliffc.aa.HM.HM7.T2.nongen_in (VStack syn) package
Definition at line 946 of file HM7.java.
{
       if( syn==null ) return false;
       assert ODUPS.isEmpty();
       boolean found = _nongen_in(syn);
       ODUPS.clear();
       return found;
     }
References com.cliffc.aa.HM.HM7.T2._nongen_in(), and com.cliffc.aa.HM.HM7.T2.ODUPS.
Referenced by com.cliffc.aa.HM.HM7.T2._fresh(), and com.cliffc.aa.HM.HM7.T2._fresh_unify().
occurs_in()
boolean com.cliffc.aa.HM.HM7.T2.occurs_in (Syntax syn) package
Definition at line 914 of file HM7.java.
{
       if( syn==null ) return false;
       if( is_base() ) return false;
       assert ODUPS.isEmpty();
       boolean found = _occurs_in(syn);
       ODUPS.clear();
       return found;
     }
References com.cliffc.aa.HM.HM7.T2._occurs_in(), com.cliffc.aa.HM.HM7.T2.is_base(), and com.cliffc.aa.HM.HM7.T2.ODUPS.
Referenced by com.cliffc.aa.HM.HM7.Ident.add_occurs().
occurs_in_type()
boolean com.cliffc.aa.HM.HM7.T2.occurs_in_type (T2 x) package
Definition at line 922 of file HM7.java.
{
       assert ODUPS.isEmpty();
       boolean found = _occurs_in_type(x);
       ODUPS.clear();
       return found;
     }
References com.cliffc.aa.HM.HM7.T2._occurs_in_type(), and com.cliffc.aa.HM.HM7.T2.ODUPS.
or0()
boolean com.cliffc.aa.HM.HM7.T2.or0 (T2 that, Worklist work) package
Definition at line 709 of file HM7.java.
{
       assert is_nil() && that.is_struct();
       if( work==null ) return that._con==null; // Progress if moving from not-nil to nilable
       if( that._con == Type.NIL ) return false;// Already nilable
       _args = new T2[1];                       // Room for U-F
       that._con=Type.NIL;
       return union(that,work);
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._con, com.cliffc.aa.HM.HM7.T2.is_nil(), com.cliffc.aa.HM.HM7.T2.is_struct(), and com.cliffc.aa.type.Type< T extends Type< T >.NIL.
Referenced by com.cliffc.aa.HM.HM7.T2._fresh_unify(), and com.cliffc.aa.HM.HM7.T2._unify().
p() [1/2]
String com.cliffc.aa.HM.HM7.T2.p ()
Definition at line 1082 of file HM7.java.
 { return p(get_dups(new VBitSet())); }
References com.cliffc.aa.HM.HM7.T2.get_dups(), and com.cliffc.aa.HM.HM7.T2.p().
Referenced by com.cliffc.aa.HM.HM7.T2.p(), com.cliffc.aa.HM.TestHM7.test01(), com.cliffc.aa.HM.TestHM6.test01(), com.cliffc.aa.HM.TestHM4.test01(), com.cliffc.aa.HM.TestHM5.test01(), com.cliffc.aa.HM.TestHM7.test02(), com.cliffc.aa.HM.TestHM6.test02(), com.cliffc.aa.HM.TestHM4.test02(), com.cliffc.aa.HM.TestHM5.test02(), com.cliffc.aa.HM.TestHM7.test03(), com.cliffc.aa.HM.TestHM6.test03(), com.cliffc.aa.HM.TestHM4.test03(), com.cliffc.aa.HM.TestHM5.test03(), com.cliffc.aa.HM.TestHM7.test04(), com.cliffc.aa.HM.TestHM6.test04(), com.cliffc.aa.HM.TestHM4.test04(), com.cliffc.aa.HM.TestHM5.test04(), com.cliffc.aa.HM.TestHM7.test05(), com.cliffc.aa.HM.TestHM6.test05(), com.cliffc.aa.HM.TestHM4.test05(), com.cliffc.aa.HM.TestHM5.test05(), com.cliffc.aa.HM.TestHM7.test06(), com.cliffc.aa.HM.TestHM6.test06(), com.cliffc.aa.HM.TestHM4.test06(), com.cliffc.aa.HM.TestHM5.test06(), com.cliffc.aa.HM.TestHM7.test07(), com.cliffc.aa.HM.TestHM6.test07(), com.cliffc.aa.HM.TestHM4.test07(), com.cliffc.aa.HM.TestHM5.test07(), com.cliffc.aa.HM.TestHM7.test08(), com.cliffc.aa.HM.TestHM6.test08(), com.cliffc.aa.HM.TestHM5.test08(), com.cliffc.aa.HM.TestHM4.test08(), com.cliffc.aa.HM.TestHM7.test09(), com.cliffc.aa.HM.TestHM6.test09(), com.cliffc.aa.HM.TestHM5.test09(), com.cliffc.aa.HM.TestHM4.test09(), com.cliffc.aa.HM.TestHM7.test10(), com.cliffc.aa.HM.TestHM6.test10(), com.cliffc.aa.HM.TestHM5.test10(), com.cliffc.aa.HM.TestHM4.test10(), com.cliffc.aa.HM.TestHM7.test11(), com.cliffc.aa.HM.TestHM6.test11(), com.cliffc.aa.HM.TestHM5.test11(), com.cliffc.aa.HM.TestHM4.test11(), com.cliffc.aa.HM.TestHM7.test12(), com.cliffc.aa.HM.TestHM6.test12(), com.cliffc.aa.HM.TestHM5.test12(), com.cliffc.aa.HM.TestHM4.test12(), com.cliffc.aa.HM.TestHM7.test13(), com.cliffc.aa.HM.TestHM6.test13(), com.cliffc.aa.HM.TestHM5.test13(), com.cliffc.aa.HM.TestHM4.test13(), com.cliffc.aa.HM.TestHM7.test14(), com.cliffc.aa.HM.TestHM6.test14(), com.cliffc.aa.HM.TestHM5.test14(), com.cliffc.aa.HM.TestHM4.test14(), com.cliffc.aa.HM.TestHM7.test15(), com.cliffc.aa.HM.TestHM6.test15(), com.cliffc.aa.HM.TestHM4.test15(), com.cliffc.aa.HM.TestHM5.test15(), com.cliffc.aa.HM.TestHM7.test16(), com.cliffc.aa.HM.TestHM6.test16(), com.cliffc.aa.HM.TestHM4.test16(), com.cliffc.aa.HM.TestHM5.test16(), com.cliffc.aa.HM.TestHM7.test17(), com.cliffc.aa.HM.TestHM6.test17(), com.cliffc.aa.HM.TestHM5.test17(), com.cliffc.aa.HM.TestHM4.test17(), com.cliffc.aa.HM.TestHM7.test18(), com.cliffc.aa.HM.TestHM6.test18(), com.cliffc.aa.HM.TestHM4.test18(), com.cliffc.aa.HM.TestHM5.test18(), com.cliffc.aa.HM.TestHM7.test19(), com.cliffc.aa.HM.TestHM6.test19(), com.cliffc.aa.HM.TestHM5.test19(), com.cliffc.aa.HM.TestHM4.test19(), com.cliffc.aa.HM.TestHM7.test20(), com.cliffc.aa.HM.TestHM6.test20(), com.cliffc.aa.HM.TestHM4.test20(), com.cliffc.aa.HM.TestHM5.test20(), com.cliffc.aa.HM.TestHM7.test21(), com.cliffc.aa.HM.TestHM6.test21(), com.cliffc.aa.HM.TestHM4.test21(), com.cliffc.aa.HM.TestHM5.test21(), com.cliffc.aa.HM.TestHM7.test22(), com.cliffc.aa.HM.TestHM6.test22(), com.cliffc.aa.HM.TestHM4.test22(), com.cliffc.aa.HM.TestHM5.test22(), com.cliffc.aa.HM.TestHM7.test23(), com.cliffc.aa.HM.TestHM6.test23(), com.cliffc.aa.HM.TestHM5.test23(), com.cliffc.aa.HM.TestHM4.test23(), com.cliffc.aa.HM.TestHM7.test24(), com.cliffc.aa.HM.TestHM7.test25(), com.cliffc.aa.HM.TestHM7.test26(), com.cliffc.aa.HM.TestHM7.test27(), com.cliffc.aa.HM.TestHM7.test28(), com.cliffc.aa.HM.TestHM7.test29(), com.cliffc.aa.HM.TestHM7.test30(), com.cliffc.aa.HM.TestHM7.test31(), and com.cliffc.aa.HM.TestHM7.test32().
p() [2/2]
String com.cliffc.aa.HM.HM7.T2.p (VBitSet dups) package
Definition at line 1085 of file HM7.java.
 { VCNT=0; VNAMES.clear(); return find()._p(new SB(), new VBitSet(), dups).toString(); }
References com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM7.T2.find(), com.cliffc.aa.util.SB.toString(), com.cliffc.aa.HM.HM7.T2.VCNT, and com.cliffc.aa.HM.HM7.T2.VNAMES.
prim()
static T2 com.cliffc.aa.HM.HM7.T2.prim (String name, T2... args) static package
Definition at line 648 of file HM7.java.
 { return new T2(name,null,null,args); }
References com.cliffc.aa.HM.HM7.T2.args(), and com.cliffc.aa.HM.HM7.T2.T2().
Referenced by com.cliffc.aa.HM.HM7.hm().
push_update() [1/2]
T2 com.cliffc.aa.HM.HM7.T2.push_update (Ary< Syntax > as) package
Definition at line 1006 of file HM7.java.
 { if( as != null ) for( Syntax a : as ) push_update(a);  return this;   }
References com.cliffc.aa.HM.HM7.T2.push_update().
Referenced by com.cliffc.aa.HM.HM7.Field.hm(), com.cliffc.aa.HM.HM7.Lambda.prep_lookup_deps(), com.cliffc.aa.HM.HM7.Let.prep_lookup_deps(), and com.cliffc.aa.HM.HM7.T2.push_update().
push_update() [2/2]
void com.cliffc.aa.HM.HM7.T2.push_update (Syntax a) package
Definition at line 1007 of file HM7.java.
 { assert UPDATE_VISIT.isEmpty(); push_update_impl(a); UPDATE_VISIT.clear(); }
References com.cliffc.aa.HM.HM7.T2.push_update_impl(), and com.cliffc.aa.HM.HM7.T2.UPDATE_VISIT.
push_update_impl()
void com.cliffc.aa.HM.HM7.T2.push_update_impl (Syntax a) private
Definition at line 1008 of file HM7.java.
{
       assert no_uf();
       if( UPDATE_VISIT.tset(_uid) ) return;
       if( _deps==null ) _deps = new Ary<>(Syntax.class);
       if( _deps.find(a)==-1 ) _deps.push(a);
       for( int i=0; i<_args.length; i++ )
         if( _args[i]!=null )
           args(i).push_update_impl(a);
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._deps, com.cliffc.aa.HM.HM7.T2._uid, com.cliffc.aa.HM.HM7.T2.args(), com.cliffc.aa.HM.HM7.T2.no_uf(), com.cliffc.aa.HM.HM7.T2.push_update_impl(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.HM.HM7.T2.UPDATE_VISIT.
Referenced by com.cliffc.aa.HM.HM7.T2.push_update(), and com.cliffc.aa.HM.HM7.T2.push_update_impl().
reset()
static void com.cliffc.aa.HM.HM7.T2.reset () static package
Definition at line 1126 of file HM7.java.
 { CNT=0; DUPS.clear(); VARS.clear(); ODUPS.clear(); CDUPS.clear(); UPDATE_VISIT.clear(); }
References com.cliffc.aa.HM.HM7.T2.CDUPS, com.cliffc.aa.HM.HM7.T2.CNT, com.cliffc.aa.HM.HM7.T2.DUPS, com.cliffc.aa.HM.HM7.T2.ODUPS, com.cliffc.aa.HM.HM7.T2.UPDATE_VISIT, and com.cliffc.aa.HM.HM7.T2.VARS.
Referenced by com.cliffc.aa.HM.HM7.reset().
str() [1/2]
static SB com.cliffc.aa.HM.HM7.T2.str (SB sb, VBitSet visit, T2 t, VBitSet dups) static private
Definition at line 1079 of file HM7.java.
 { return t==null ? sb.p("_") : t.str(sb,visit,dups); }
References com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM7.T2.str().
str() [2/2]
SB com.cliffc.aa.HM.HM7.T2.str (SB sb, VBitSet visit, VBitSet dups) package
Definition at line 1046 of file HM7.java.
{
       if( is_leaf() || is_base() ) {
         if( is_base() ) sb.p(_con instanceof TypeMemPtr ? "str" : _con.toString()); else sb.p(_name);
         return _args.length==0 || _args[0]==null ? sb : _args[0].str(sb.p(">>"), visit, dups);
       }
       boolean dup = dups.get(_uid);
       if( dup ) sb.p("$V").p(_uid);
       if( visit.tset(_uid) && dup ) return sb;
       if( dup ) sb.p(':');
       // Special printing for functions
       if( is_fun() ) {
         sb.p("{ ");
         for( int i=0; i<_args.length-1; i++ )
           str(sb,visit,_args[i],dups).p(" ");
         return str(sb.p("-> "),visit,_args[_args.length-1],dups).p(" }");
       }
       // Special printing for structures
       if( is_struct() ) {
         sb.p("@{");
         for( int i=0; i<_ids.length; i++ )
           str(sb.p(' ').p(_ids[i]).p(" = "),visit,_args[i],dups).p(',');
         sb.unchar().p("}");
         if( _con==Type.NIL ) sb.p('?');
         return sb;
       }
       // Generic structural T2
       sb.p("(").p(_name).p(" ");
       for( T2 t : _args ) str(sb,visit,t,dups).p(" ");
       return sb.unchar().p(")");
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._con, com.cliffc.aa.HM.HM7.T2._ids, com.cliffc.aa.HM.HM7.T2._name, com.cliffc.aa.HM.HM7.T2._uid, com.cliffc.aa.HM.HM7.T2.is_base(), com.cliffc.aa.HM.HM7.T2.is_fun(), com.cliffc.aa.HM.HM7.T2.is_leaf(), com.cliffc.aa.HM.HM7.T2.is_struct(), com.cliffc.aa.type.Type< T extends Type< T >.NIL, com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM7.T2.str(), com.cliffc.aa.type.Type< T extends Type< T >.toString(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.util.SB.unchar().
Referenced by com.cliffc.aa.HM.HM7.Syntax.p0(), com.cliffc.aa.HM.HM7.VStack.str(), com.cliffc.aa.HM.HM7.T2.str(), and com.cliffc.aa.HM.HM7.T2.toString().
toString()
String com.cliffc.aa.HM.HM7.T2.toString ()
Definition at line 1045 of file HM7.java.
 { return str(new SB(), new VBitSet(), get_dups(new VBitSet()) ).toString(); }
References com.cliffc.aa.HM.HM7.T2.get_dups(), com.cliffc.aa.HM.HM7.T2.str(), and com.cliffc.aa.util.SB.toString().
unify()
boolean com.cliffc.aa.HM.HM7.T2.unify (T2 that, Worklist work) package
Definition at line 724 of file HM7.java.
{
       if( this==that ) return false;
       assert DUPS.isEmpty();
       boolean progress = _unify(that,work);
       DUPS.clear();
       return progress;
     }
References com.cliffc.aa.HM.HM7.T2._unify(), and com.cliffc.aa.HM.HM7.T2.DUPS.
Referenced by com.cliffc.aa.HM.HM7.hm(), com.cliffc.aa.HM.HM7.Lambda.hm(), com.cliffc.aa.HM.HM7.Let.hm(), com.cliffc.aa.HM.HM7.Apply.hm(), and com.cliffc.aa.HM.HM7.Struct.hm().
unify_base()
boolean com.cliffc.aa.HM.HM7.T2.unify_base (T2 that, Worklist work) private
Definition at line 795 of file HM7.java.
{
       Type con = _con.meet(that._con);
       if( con==that._con ) return false; // No progress
       if( work==null ) return true;
       that._con = con;          // Yes progress, but no update if null work
       _args = new T2[1];        // Room for a forwarding pointer
       _con=null;                // Flip from 'Base' to 'Leaf'
       return union(that,work);
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._con, and com.cliffc.aa.type.Type< T extends Type< T >.meet().
Referenced by com.cliffc.aa.HM.HM7.T2._unify().
union()
boolean com.cliffc.aa.HM.HM7.T2.union (T2 that, Worklist work) package
Definition at line 689 of file HM7.java.
{
       assert no_uf(); // Cannot union twice
       if( this==that ) return false;
       if( work==null ) return true; // Report progress without changing
       // Worklist: put updates on the worklist for revisiting
       if( _deps != null ) {
         work.addAll(_deps); // Re-Apply
         // Merge update lists, for future unions
         if( that._deps==null && that.is_leaf() ) that._deps = _deps;
         else
           for( Syntax dep : _deps ) that.push_update(dep);
         _deps = null;
       }
       _args[0] = that;         // U-F update
       if( _name.charAt(0)!='V' ) _name = "V"+_uid; // Flag as a leaf & unified
       assert !no_uf();
       return true;
     }
References com.cliffc.aa.HM.HM7.T2._args, com.cliffc.aa.HM.HM7.T2._deps, com.cliffc.aa.HM.HM7.T2._name, com.cliffc.aa.HM.HM7.T2._uid, and com.cliffc.aa.HM.HM7.T2.no_uf().
Referenced by com.cliffc.aa.HM.HM7.T2._fresh_unify(), and com.cliffc.aa.HM.HM7.T2._unify().
vput()
boolean com.cliffc.aa.HM.HM7.T2.vput (T2 that, boolean progress) private
Definition at line 891 of file HM7.java.
 { VARS.put(this,that); return progress; }
References com.cliffc.aa.HM.HM7.T2.VARS.
Referenced by com.cliffc.aa.HM.HM7.T2._fresh_unify().
Member Data Documentation
_args
T2 [] com.cliffc.aa.HM.HM7.T2._args package
Definition at line 631 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2._cycle_equals(), com.cliffc.aa.HM.HM7.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM7.T2._fresh(), com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM7.T2._get_dups(), com.cliffc.aa.HM.HM7.T2._occurs_in_type(), com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM7.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM7.T2.add_fld(), com.cliffc.aa.HM.HM7.T2.args(), com.cliffc.aa.HM.HM7.T2.copy(), com.cliffc.aa.HM.HM7.T2.find(), com.cliffc.aa.HM.HM7.Apply.hm(), com.cliffc.aa.HM.HM7.T2.no_uf(), com.cliffc.aa.HM.HM7.T2.or0(), com.cliffc.aa.HM.HM7.T2.push_update_impl(), com.cliffc.aa.HM.HM7.T2.str(), com.cliffc.aa.HM.HM7.T2.T2(), com.cliffc.aa.HM.HM7.T2.unify_base(), and com.cliffc.aa.HM.HM7.T2.union().
_con
Type com.cliffc.aa.HM.HM7.T2._con package
Definition at line 634 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2._cycle_equals(), com.cliffc.aa.HM.HM7.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM7.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM7.T2.copy(), com.cliffc.aa.HM.HM7.T2.fresh_base(), com.cliffc.aa.HM.HM7.T2.is_base(), com.cliffc.aa.HM.HM7.T2.is_leaf(), com.cliffc.aa.HM.HM7.T2.or0(), com.cliffc.aa.HM.HM7.T2.str(), com.cliffc.aa.HM.HM7.T2.T2(), and com.cliffc.aa.HM.HM7.T2.unify_base().
_deps
Ary<Syntax> com.cliffc.aa.HM.HM7.T2._deps package
Definition at line 640 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM7.T2.add_fld(), com.cliffc.aa.HM.HM7.Let.add_occurs(), com.cliffc.aa.HM.HM7.T2.push_update_impl(), and com.cliffc.aa.HM.HM7.T2.union().
_ids
String [] com.cliffc.aa.HM.HM7.T2._ids package
Definition at line 637 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2._cycle_equals_struct(), com.cliffc.aa.HM.HM7.T2._fresh_unify_struct(), com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM7.T2.add_fld(), com.cliffc.aa.HM.HM7.T2.copy(), com.cliffc.aa.HM.HM7.Struct.hm(), com.cliffc.aa.HM.HM7.T2.str(), and com.cliffc.aa.HM.HM7.T2.T2().
_name
String com.cliffc.aa.HM.HM7.T2._name package
Definition at line 628 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2._cycle_equals(), com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM7.T2.copy(), com.cliffc.aa.HM.HM7.T2.is_leaf(), com.cliffc.aa.HM.HM7.T2.isa(), com.cliffc.aa.HM.HM7.T2.str(), com.cliffc.aa.HM.HM7.T2.T2(), and com.cliffc.aa.HM.HM7.T2.union().
_uid
final int com.cliffc.aa.HM.HM7.T2._uid package
Definition at line 623 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2._get_dups(), com.cliffc.aa.HM.HM7.T2._occurs_in_type(), com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM7.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM7.T2.dbl_uid(), com.cliffc.aa.HM.HM7.T2.push_update_impl(), com.cliffc.aa.HM.HM7.T2.str(), com.cliffc.aa.HM.HM7.T2.T2(), and com.cliffc.aa.HM.HM7.T2.union().
CDUPS
final HashMap<T2,T2> com.cliffc.aa.HM.HM7.T2.CDUPS = new HashMap<>() static private
Definition at line 961 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2._cycle_equals(), com.cliffc.aa.HM.HM7.T2.cycle_equals(), and com.cliffc.aa.HM.HM7.T2.reset().
CNT
int com.cliffc.aa.HM.HM7.T2.CNT =0 static private
Definition at line 622 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2.fresh_unify(), com.cliffc.aa.HM.HM7.hm(), com.cliffc.aa.HM.HM7.T2.make_leaf(), com.cliffc.aa.HM.HM7.T2.reset(), and com.cliffc.aa.HM.HM7.T2.T2().
DUPS
final HashMap<Long,T2> com.cliffc.aa.HM.HM7.T2.DUPS = new HashMap<>() static private
Definition at line 723 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2._unify(), com.cliffc.aa.HM.HM7.T2.fresh_unify(), com.cliffc.aa.HM.HM7.T2.reset(), and com.cliffc.aa.HM.HM7.T2.unify().
ODUPS
final VBitSet com.cliffc.aa.HM.HM7.T2.ODUPS = new VBitSet() static private
Definition at line 913 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2._occurs_in_type(), com.cliffc.aa.HM.HM7.T2.nongen_in(), com.cliffc.aa.HM.HM7.T2.occurs_in(), com.cliffc.aa.HM.HM7.T2.occurs_in_type(), and com.cliffc.aa.HM.HM7.T2.reset().
UPDATE_VISIT
final VBitSet com.cliffc.aa.HM.HM7.T2.UPDATE_VISIT = new VBitSet() static package
Definition at line 1005 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2.add_deps_work(), com.cliffc.aa.HM.HM7.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM7.T2.push_update(), com.cliffc.aa.HM.HM7.T2.push_update_impl(), and com.cliffc.aa.HM.HM7.T2.reset().
VARS
final HashMap<T2,T2> com.cliffc.aa.HM.HM7.T2.VARS = new HashMap<>() static private
Definition at line 818 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2._fresh(), com.cliffc.aa.HM.HM7.T2._fresh_unify(), com.cliffc.aa.HM.HM7.T2.fresh_unify(), com.cliffc.aa.HM.HM7.T2.reset(), and com.cliffc.aa.HM.HM7.T2.vput().
VCNT
int com.cliffc.aa.HM.HM7.T2.VCNT static private
Definition at line 1083 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2._p(), and com.cliffc.aa.HM.HM7.T2.p().
VNAMES
final HashMap<T2,Integer> com.cliffc.aa.HM.HM7.T2.VNAMES = new HashMap<>() static private
Definition at line 1084 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2._p(), and com.cliffc.aa.HM.HM7.T2.p().
The documentation for this class was generated from the following file:
HM7.java