aa: com.cliffc.aa.HM.HM9.Syntax Class Reference
com.cliffc.aa.HM.HM9.Syntax Class Reference abstract
Public Member Functions
String p ()
final String toString ()
Package Functions
abstract void add_hm_work (Worklist work)
void add_val_work (Syntax child, Worklist work)
T2 debug_find ()
T2 find ()
abstract boolean hm (Worklist work)
abstract boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
abstract SB p1 (SB sb)
abstract SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
abstract int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
abstract SB str (SB sb)
abstract Type val (Worklist work)
Package Attributes
Type _flow
T2 _hmt
VStack _nongen
Syntax _par
Detailed Description
Definition at line 321 of file HM9.java.
Member Function Documentation
add_hm_work()
abstract void com.cliffc.aa.HM.HM9.Syntax.add_hm_work (Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM9.PrimSyn, com.cliffc.aa.HM.HM9.Field, com.cliffc.aa.HM.HM9.Struct, com.cliffc.aa.HM.HM9.Root, com.cliffc.aa.HM.HM9.Apply, com.cliffc.aa.HM.HM9.Let, com.cliffc.aa.HM.HM9.Lambda, com.cliffc.aa.HM.HM9.Ident, and com.cliffc.aa.HM.HM9.Con.
Referenced by com.cliffc.aa.HM.HM9.Field.add_hm_work(), and com.cliffc.aa.HM.HM9.hm().
add_val_work()
void com.cliffc.aa.HM.HM9.Syntax.add_val_work (Syntax child, Worklist work) package
Reimplemented in com.cliffc.aa.HM.HM9.PrimSyn, com.cliffc.aa.HM.HM9.Apply, com.cliffc.aa.HM.HM9.Let, and com.cliffc.aa.HM.HM9.Lambda.
Definition at line 346 of file HM9.java.
 {} // Add affected neighbors to worklist
Referenced by com.cliffc.aa.HM.HM9.hm().
debug_find()
T2 com.cliffc.aa.HM.HM9.Syntax.debug_find () package
Definition at line 329 of file HM9.java.
 { return _hmt.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM9.Syntax._hmt, and com.cliffc.aa.HM.HM9.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM9.hm().
find()
T2 com.cliffc.aa.HM.HM9.Syntax.find () package
Definition at line 325 of file HM9.java.
               {                 // U-F find
       T2 t = _hmt.find();
       return t== _hmt ? t : (_hmt =t);
     }
References com.cliffc.aa.HM.HM9.Syntax._hmt, and com.cliffc.aa.HM.HM9.T2.find().
Referenced by com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_val_work(), com.cliffc.aa.HM.HM9.Let.add_val_work(), com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Ident.hm(), com.cliffc.aa.HM.HM9.Lambda.hm(), com.cliffc.aa.HM.HM9.Apply.hm(), com.cliffc.aa.HM.HM9.Root.hm(), com.cliffc.aa.HM.HM9.Struct.hm(), com.cliffc.aa.HM.HM9.Field.hm(), com.cliffc.aa.HM.HM9.PrimSyn.hm(), com.cliffc.aa.HM.HM9.If.hm(), com.cliffc.aa.HM.HM9.NotNil.hm(), com.cliffc.aa.HM.HM9.Apply.is_if_nil(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.NotNil.prep_tree(), com.cliffc.aa.HM.HM9.Apply.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
hm()
abstract boolean com.cliffc.aa.HM.HM9.Syntax.hm (Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM9.NotNil, com.cliffc.aa.HM.HM9.If, com.cliffc.aa.HM.HM9.PrimSyn, com.cliffc.aa.HM.HM9.Field, com.cliffc.aa.HM.HM9.Struct, com.cliffc.aa.HM.HM9.Root, com.cliffc.aa.HM.HM9.Apply, com.cliffc.aa.HM.HM9.Let, com.cliffc.aa.HM.HM9.Lambda, com.cliffc.aa.HM.HM9.Ident, and com.cliffc.aa.HM.HM9.Con.
Referenced by com.cliffc.aa.HM.HM9.hm(), and com.cliffc.aa.HM.HM9.Syntax.more_work_impl().
more_work()
abstract boolean com.cliffc.aa.HM.HM9.Syntax.more_work (Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM9.PrimSyn, com.cliffc.aa.HM.HM9.Field, com.cliffc.aa.HM.HM9.Struct, com.cliffc.aa.HM.HM9.Apply, com.cliffc.aa.HM.HM9.Let, com.cliffc.aa.HM.HM9.Lambda, com.cliffc.aa.HM.HM9.Ident, and com.cliffc.aa.HM.HM9.Con.
Referenced by com.cliffc.aa.HM.HM9.Lambda.more_work(), com.cliffc.aa.HM.HM9.Let.more_work(), com.cliffc.aa.HM.HM9.Apply.more_work(), and com.cliffc.aa.HM.HM9.Field.more_work().
more_work_impl()
final boolean com.cliffc.aa.HM.HM9.Syntax.more_work_impl (Worklist work) package
Definition at line 362 of file HM9.java.
{
       if( work.has(this) ) return true;
       if( DO_HM && hm(null) )   // Any more HM work?
         return false;           // Found HM work not on worklist
       if( DO_GCP && val(null)!=_flow )
         return false;           // Found GCP work not on worklist
       return true;
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.DO_GCP, com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.Worklist.has(), com.cliffc.aa.HM.HM9.Syntax.hm(), and com.cliffc.aa.HM.HM9.Syntax.val().
Referenced by com.cliffc.aa.HM.HM9.Con.more_work(), com.cliffc.aa.HM.HM9.Ident.more_work(), com.cliffc.aa.HM.HM9.Lambda.more_work(), com.cliffc.aa.HM.HM9.Let.more_work(), com.cliffc.aa.HM.HM9.Apply.more_work(), com.cliffc.aa.HM.HM9.Struct.more_work(), com.cliffc.aa.HM.HM9.Field.more_work(), and com.cliffc.aa.HM.HM9.PrimSyn.more_work().
p()
String com.cliffc.aa.HM.HM9.Syntax.p ()
Definition at line 374 of file HM9.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM9.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM9.Syntax.p0 (SB sb, VBitSet dups) package
Definition at line 375 of file HM9.java.
{
       _hmt.get_dups(dups);
       VBitSet visit = new VBitSet();
       p1(sb.i());
       if( DO_HM  ) _hmt .str(sb.p(", HM="), visit,dups);
       if( DO_GCP ) _flow.str(sb.p(", CCP="),visit.clr(),null,false);
       sb.nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.util.VBitSet.clr(), com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM9.DO_GCP, com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM9.Syntax.p1(), com.cliffc.aa.HM.HM9.Syntax.p2(), com.cliffc.aa.type.Type< T extends Type< T >.str(), and com.cliffc.aa.HM.HM9.T2.str().
Referenced by com.cliffc.aa.HM.HM9.Syntax.p(), com.cliffc.aa.HM.HM9.Lambda.p2(), com.cliffc.aa.HM.HM9.Let.p2(), com.cliffc.aa.HM.HM9.Apply.p2(), com.cliffc.aa.HM.HM9.Struct.p2(), and com.cliffc.aa.HM.HM9.Field.p2().
p1()
abstract SB com.cliffc.aa.HM.HM9.Syntax.p1 (SB sb) abstract package
Reimplemented in com.cliffc.aa.HM.HM9.PrimSyn, com.cliffc.aa.HM.HM9.Field, com.cliffc.aa.HM.HM9.Struct, com.cliffc.aa.HM.HM9.Apply, com.cliffc.aa.HM.HM9.Let, com.cliffc.aa.HM.HM9.Lambda, com.cliffc.aa.HM.HM9.Ident, and com.cliffc.aa.HM.HM9.Con.
Referenced by com.cliffc.aa.HM.HM9.Syntax.p0().
p2()
abstract SB com.cliffc.aa.HM.HM9.Syntax.p2 (SB sb, VBitSet dups) abstract package
Reimplemented in com.cliffc.aa.HM.HM9.PrimSyn, com.cliffc.aa.HM.HM9.Field, com.cliffc.aa.HM.HM9.Struct, com.cliffc.aa.HM.HM9.Apply, com.cliffc.aa.HM.HM9.Let, com.cliffc.aa.HM.HM9.Lambda, com.cliffc.aa.HM.HM9.Ident, and com.cliffc.aa.HM.HM9.Con.
Referenced by com.cliffc.aa.HM.HM9.Syntax.p0().
prep_lookup_deps()
void com.cliffc.aa.HM.HM9.Syntax.prep_lookup_deps (Ident id) package
Reimplemented in com.cliffc.aa.HM.HM9.Let, and com.cliffc.aa.HM.HM9.Lambda.
Definition at line 358 of file HM9.java.
 {}
prep_tree()
abstract int com.cliffc.aa.HM.HM9.Syntax.prep_tree (Syntax par, VStack nongen, Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM9.NotNil, com.cliffc.aa.HM.HM9.PrimSyn, com.cliffc.aa.HM.HM9.Field, com.cliffc.aa.HM.HM9.Struct, com.cliffc.aa.HM.HM9.Apply, com.cliffc.aa.HM.HM9.Let, com.cliffc.aa.HM.HM9.Lambda, com.cliffc.aa.HM.HM9.Ident, and com.cliffc.aa.HM.HM9.Con.
Referenced by com.cliffc.aa.HM.HM9.Lambda.prep_tree(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Apply.prep_tree(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), and com.cliffc.aa.HM.HM9.Field.prep_tree().
prep_tree_impl()
final void com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package
Definition at line 351 of file HM9.java.
{
       _par = par;
       _hmt = t;
       _flow= Type.XSCALAR;
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.HM.HM9.Syntax._nongen, com.cliffc.aa.HM.HM9.Syntax._par, com.cliffc.aa.HM.HM9.Worklist.push(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Referenced by com.cliffc.aa.HM.HM9.Con.prep_tree(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), com.cliffc.aa.HM.HM9.Lambda.prep_tree(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Apply.prep_tree(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.Field.prep_tree(), and com.cliffc.aa.HM.HM9.PrimSyn.prep_tree().
str()
abstract SB com.cliffc.aa.HM.HM9.Syntax.str (SB sb) abstract package
Reimplemented in com.cliffc.aa.HM.HM9.PrimSyn, com.cliffc.aa.HM.HM9.Field, com.cliffc.aa.HM.HM9.Struct, com.cliffc.aa.HM.HM9.Root, com.cliffc.aa.HM.HM9.Apply, com.cliffc.aa.HM.HM9.Let, com.cliffc.aa.HM.HM9.Lambda, com.cliffc.aa.HM.HM9.Ident, and com.cliffc.aa.HM.HM9.Con.
Referenced by com.cliffc.aa.HM.HM9.Lambda.str(), com.cliffc.aa.HM.HM9.Let.str(), com.cliffc.aa.HM.HM9.Apply.str(), com.cliffc.aa.HM.HM9.Root.str(), com.cliffc.aa.HM.HM9.Struct.str(), com.cliffc.aa.HM.HM9.Field.str(), and com.cliffc.aa.HM.HM9.Syntax.toString().
toString()
final String com.cliffc.aa.HM.HM9.Syntax.toString ()
Definition at line 371 of file HM9.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM9.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.HM.HM9.Lambda.p1().
val()
abstract Type com.cliffc.aa.HM.HM9.Syntax.val (Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM9.Field, com.cliffc.aa.HM.HM9.Struct, com.cliffc.aa.HM.HM9.Root, com.cliffc.aa.HM.HM9.Apply, com.cliffc.aa.HM.HM9.Let, com.cliffc.aa.HM.HM9.Lambda, com.cliffc.aa.HM.HM9.Ident, and com.cliffc.aa.HM.HM9.Con.
Referenced by com.cliffc.aa.HM.HM9.hm(), and com.cliffc.aa.HM.HM9.Syntax.more_work_impl().
Member Data Documentation
_flow
Type com.cliffc.aa.HM.HM9.Syntax._flow package
Definition at line 332 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Lambda.apply(), com.cliffc.aa.HM.HM9.Pair1.apply(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Pair.apply(), com.cliffc.aa.HM.HM9.Triple.apply(), com.cliffc.aa.HM.HM9.If.apply(), com.cliffc.aa.HM.HM9.EQ.apply(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM9.IsEmpty.apply(), com.cliffc.aa.HM.HM9.NotNil.apply(), com.cliffc.aa.HM.HM9.Mul.apply(), com.cliffc.aa.HM.HM9.Dec.apply(), com.cliffc.aa.HM.HM9.Str.apply(), com.cliffc.aa.HM.HM9.Factor.apply(), com.cliffc.aa.HM.HM9.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Lambda.Lambda(), com.cliffc.aa.HM.HM9.Syntax.more_work_impl(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM9.Ident.val(), com.cliffc.aa.HM.HM9.Let.val(), com.cliffc.aa.HM.HM9.Apply.val(), com.cliffc.aa.HM.HM9.Root.val(), com.cliffc.aa.HM.HM9.Struct.val(), com.cliffc.aa.HM.HM9.Field.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
_hmt
T2 com.cliffc.aa.HM.HM9.Syntax._hmt package
Definition at line 324 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Syntax.debug_find(), com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.PrimSyn.prep_tree(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM9.PrimSyn.PrimSyn().
_nongen
VStack com.cliffc.aa.HM.HM9.Syntax._nongen package
Definition at line 323 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.add_hm_work(), com.cliffc.aa.HM.HM9.Ident.hm(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM9.Syntax._par package
Definition at line 322 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.Apply.add_hm_work(), com.cliffc.aa.HM.HM9.Struct.add_hm_work(), com.cliffc.aa.HM.HM9.Field.add_hm_work(), com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM9.java