aa: com.cliffc.aa.HM.TestHM4 Class Reference
com.cliffc.aa.HM.TestHM4 Class Reference
Public Member Functions
void reset ()
void test00 ()
void test01 ()
void test02 ()
void test03 ()
void test04 ()
void test05 ()
void test06 ()
void test07 ()
void test08 ()
void test09 ()
void test10 ()
void test11 ()
void test12 ()
void test13 ()
void test14 ()
void test15 ()
void test16 ()
void test17 ()
void test18 ()
void test19 ()
void test20 ()
void test21 ()
void test22 ()
void test23 ()
Detailed Description
Definition at line 10 of file TestHM4.java.
Member Function Documentation
reset()
void com.cliffc.aa.HM.TestHM4.reset ()
Definition at line 12 of file TestHM4.java.
 { HM4.reset(); }
References com.cliffc.aa.HM.HM4.reset().
test00()
void com.cliffc.aa.HM.TestHM4.test00 ()
Definition at line 15 of file TestHM4.java.
{
     Syntax syn = new Ident("fred");
     HM4.hm(syn);
   }
References com.cliffc.aa.HM.HM4.hm().
test01()
void com.cliffc.aa.HM.TestHM4.test01 ()
Definition at line 21 of file TestHM4.java.
{
     Syntax syn = new Con(TypeInt.con(3));
     T2 t = HM4.hm(syn);
     assertEquals("3",t.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test02()
void com.cliffc.aa.HM.TestHM4.test02 ()
Definition at line 28 of file TestHM4.java.
{
     Syntax syn = new Apply(new Ident("pair"),new Con(TypeInt.con(3)));
     T2 t = HM4.hm(syn);
     assertEquals("{ V36 -> (pair 3 V36) }",t.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test03()
void com.cliffc.aa.HM.TestHM4.test03 ()
Definition at line 35 of file TestHM4.java.
{
     // { z -> (pair2 (z 3) (z "abc")) }
     Syntax x =
       new Lambda("z",
                  new Apply(new Ident("pair2"),
                            new Apply(new Ident("z"), new Con(TypeInt.con(3))),
                            new Apply(new Ident("z"), new Con(TypeStr.ABC))));
     T2 t = HM4.hm(x);
     assertEquals("{ { all -> V34 } -> (pair2 V34 V34) }",t.p());
   }
References com.cliffc.aa.type.TypeStr.ABC, com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test04()
void com.cliffc.aa.HM.TestHM4.test04 ()
Definition at line 47 of file TestHM4.java.
{
     // let fact = {n -> (if/else3 (==0 n)  1  (*2 n (fact (dec n))))} in fact;
     Syntax fact =
       new Let("fact",
               new Lambda("n",
                          new Apply(new Ident("if/else3"),
                                    new Apply(new Ident("==0"),new Ident("n")), // Predicate
                                    new Con(TypeInt.con(1)),                    // True arm
                                    new Apply(new Ident("*2"),                  // False arm
                                              new Ident("n"),
                                              new Apply(new Ident("fact"),
                                                        new Apply(new Ident("dec"),new Ident("n")))))),
               new Ident("fact"));
     T2 t = HM4.hm(fact);
     assertEquals("#{ int64 -> int64 }",t.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test05()
void com.cliffc.aa.HM.TestHM4.test05 ()
Definition at line 65 of file TestHM4.java.
{
     // ({ x -> (pair2 (x 3) (x "abc")) } {y->y})
     // Because {y->y} is passed in, all 'y' types must agree.
     // This unifies 3 and "abc" which results in 'all'
     Syntax x =
       new Apply(new Lambda("x",
                            new Apply(new Ident("pair2"),
                                      new Apply(new Ident("x"), new Con(TypeInt.con(3))),
                                      new Apply(new Ident("x"), new Con(TypeStr.ABC)))),
                 new Lambda("y", new Ident("y")));
     T2 t1 = HM4.hm(x);
     assertEquals("(pair2 all all)",t1.p());
   }
References com.cliffc.aa.type.TypeStr.ABC, com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test06()
void com.cliffc.aa.HM.TestHM4.test06 ()
Definition at line 81 of file TestHM4.java.
{
     // recursive unification
     // fn f => f f (fail)
     Syntax x =
       new Lambda("f", new Apply(new Ident("f"), new Ident("f")));
     T2 t1 = HM4.hm(x);
     assertEquals("{ $36:{ $36 -> V33 } -> V33 }",t1.p());
     // We can argue the pretty-print should print:
     // "$36:{ $36 -> V33 }"
   }
References com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test07()
void com.cliffc.aa.HM.TestHM4.test07 ()
Definition at line 93 of file TestHM4.java.
{
     // let g = fn f => 5 in g g
     Syntax x =
       new Let("g",
               new Lambda("f", new Con(TypeInt.con(5))),
               new Apply(new Ident("g"), new Ident("g")));
     T2 t1 = HM4.hm(x);
     assertEquals("5",t1.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test08()
void com.cliffc.aa.HM.TestHM4.test08 ()
Definition at line 104 of file TestHM4.java.
{
     // example that demonstrates generic and non-generic variables:
     // fn g => let f = (fn x => g) in pair2 (f 3, f true)
     Syntax syn =
       new Lambda("g",
                  new Let("f",
                          new Lambda("x", new Ident("g")),
                          new Apply(new Ident("pair2"),
                                    new Apply(new Ident("f"), new Con(TypeInt.con(3))),
                                    new Apply(new Ident("f"), new Con(TypeInt.con(1))))));
     T2 t1 = HM4.hm(syn);
     assertEquals("{ V2 -> (pair2 V2 V2) }",t1.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test09()
void com.cliffc.aa.HM.TestHM4.test09 ()
Definition at line 119 of file TestHM4.java.
{
     // fn f g => (f g)
     Syntax syn =
       new Lambda2("f", "g", new Apply(new Ident("f"), new Ident("g")));
     T2 t1 = HM4.hm(syn);
     assertEquals("{ { V1 -> V34 } V1 -> V34 }",t1.p());
   }
References com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test10()
void com.cliffc.aa.HM.TestHM4.test10 ()
Definition at line 128 of file TestHM4.java.
{
     // Function composition
     // fn f g => (fn arg => g (f arg))
     Syntax syn =
       new Lambda2("f", "g", new Lambda("arg", new Apply(new Ident("g"), new Apply(new Ident("f"), new Ident("arg")))));
     T2 t1 = HM4.hm(syn);
     assertEquals("{ { V0 -> V37 } { V37 -> V36 } -> { V0 -> V36 } }",t1.p());
   }
References com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test11()
void com.cliffc.aa.HM.TestHM4.test11 ()
Definition at line 138 of file TestHM4.java.
{
     // Stacked functions ignoring all function arguments
     // let map = (fn fun => (fn x => 2))
     //        in ((map 3) 5)
     Syntax syn =
       new Let("map",
               new Lambda("fun",
                          new Lambda("x",
                                     new Con(TypeInt.con(2)))),
               new Apply(new Apply(new Ident("map"),
                                   new Con(TypeInt.con(3))),
                         new Con(TypeInt.con(5))));
     T2 t1 = HM4.hm(syn);
     assertEquals("2",t1.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test12()
void com.cliffc.aa.HM.TestHM4.test12 ()
Definition at line 155 of file TestHM4.java.
{
     // map takes a function and an element (collection?) and applies it (applies to collection?)
     //   let map = { fun -> {x -> (fun x) }}
     //          in { p -> 5 }
     Syntax syn =
       new Let("map",
               new Lambda("fun",
                          new Lambda("x",
                                     new Apply(new Ident("fun"),new Ident("x")))),
               new Lambda("p",
                          new Con(TypeInt.con(5))));
     T2 t1 = HM4.hm(syn);
     assertEquals("{ V2 -> 5 }",t1.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test13()
void com.cliffc.aa.HM.TestHM4.test13 ()
Definition at line 171 of file TestHM4.java.
{
     // Looking at when tvars are duplicated ("fresh" copies made).
     // This is the "map" problem with a scalar instead of a collection.
     // Takes a '{a->b}' and a 'a' for a couple of different prims.
     // let map = { fun -> {x -> (fun x) }}
     //        in (pair2 ((map str) 5) ((map factor) 2.3))
     Syntax syn =
       new Let("map",
               new Lambda("fun",
                          new Lambda("x",
                                     new Apply(new Ident("fun"),new Ident("x")))),
               new Apply(new Ident("pair2"),
                         new Apply(new Apply(new Ident("map"), new Ident("str")),
                                   new Con(TypeInt.con(5))),
                         new Apply(new Apply(new Ident("map"), new Ident("factor")),
                                   new Con(TypeFlt.con(2.3))))
               );
     T2 t1 = HM4.hm(syn);
     assertEquals("(pair2 str (divmod flt64 flt64))",t1.p());
   }
References com.cliffc.aa.type.TypeFlt.con(), com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test14()
void com.cliffc.aa.HM.TestHM4.test14 ()
Definition at line 193 of file TestHM4.java.
{
     // map takes a function and an element (collection?) and applies it (applies to collection?)
     //   let map = { fun -> {x -> (fun x) }}
     //          in (map {a -> 3} 5)
     Syntax syn =
       new Let("map",
               new Lambda("fun",
                          new Lambda("x",
                                     new Apply(new Ident("fun"),new Ident("x")))),
               new Apply(new Apply(new Ident("map"),
                                   new Lambda("a",new Con(TypeInt.con(3)))),
                         new Con(TypeInt.con(5))));
     T2 t1 = HM4.hm(syn);
     assertEquals("3",t1.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test15()
void com.cliffc.aa.HM.TestHM4.test15 ()
Definition at line 210 of file TestHM4.java.
{
     // map takes a function and an element (collection?) and applies it (applies to collection?)
     //   let map = { fun -> {x -> (fun x) }}
     //          in (map {a -> [a,a]} 5)
     Syntax syn =
       new Let("map",
               new Lambda("fun",
                          new Lambda("x",
                                     new Apply(new Ident("fun"),new Ident("x")))),
               new Apply(new Apply(new Ident("map"),
                                   new Lambda("a",
                                              new Apply(new Ident("pair2"),
                                                        new Ident("a"),
                                                        new Ident("a")))),
                         new Con(TypeInt.con(5))));
     T2 t1 = HM4.hm(syn);
     assertEquals("(pair2 5 5)",t1.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test16()
void com.cliffc.aa.HM.TestHM4.test16 ()
Definition at line 230 of file TestHM4.java.
{
     //   let fcn = { p a -> pair[a,a] } in
     // map takes a function and an element (collection?) and applies it (applies to collection?)
     //   let map = { fun x -> (fun x) } in
     //          in { q -> (map (fcn q) 5) }
     // Should return  { p -> [5,5] }
     Syntax syn =
       new Let("fcn",
               new Lambda("p",
                          new Lambda("a",
                                     new Apply(new Ident("pair2"),
                                               new Ident("a"),
                                               new Ident("a")))),
               new Let("map",
                       new Lambda2("fun", "x", new Apply(new Ident("fun"),new Ident("x"))),
                       new Lambda("q",
                                  new Apply(new Ident("map"),
                                            new Apply(new Ident("fcn"),new Ident("q")),
                                            new Con(TypeInt.con(5))))));
     T2 t1 = HM4.hm(syn);
     assertEquals("{ V4 -> (pair2 5 5) }",t1.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test17()
void com.cliffc.aa.HM.TestHM4.test17 ()
Definition at line 254 of file TestHM4.java.
{
     // Checking behavior when using "if/else" to merge two functions with
     // sufficiently different signatures, then attempting to pass them to a map
     // & calling internally.
     // fcn takes a predicate 'p' and returns one of two fcns.
     //   let fcn = { p -> (if/else3 p {a -> pair[a,a        ]}
     //                                {b -> pair[b,pair[3,b]]}) } in
     // map takes a function and an element (collection?) and applies it (applies to collection?)
     //   let map = { fun x -> (fun x) }
     //          in { q -> ((map (fcn q)) 5) }
     // Should return { q -> q ? [5,5] : [5,[3,5]] }
     Syntax syn =
       new Let("fcn",
               new Lambda("p",
                          new Apply(new Ident("if/else3"),
                                    new Ident("p"), // p ?
                                    new Lambda("a",
                                               new Apply(new Ident("pair2"),
                                                         new Ident("a"),
                                                         new Ident("a"))),
                                    new Lambda("b",
                                               new Apply(new Ident("pair2"),
                                                         new Ident("b"),
                                                         new Apply(new Ident("pair2"),
                                                                   new Con(TypeInt.con(3)),
                                                                   new Ident("b")))))),
               new Let("map",
                       new Lambda2("fun","x",new Apply(new Ident("fun"),new Ident("x"))),
                       new Lambda("q",
                                  new Apply(new Ident("map"),
                                            new Apply(new Ident("fcn"),new Ident("q")),
                                            new Con(TypeInt.con(5))))));
     // Ultimately, unifies "a" with "pair[3,a]" which throws recursive unification.
     T2 t1 = HM4.hm(syn);
     assertEquals("TBD",t1.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test18()
void com.cliffc.aa.HM.TestHM4.test18 ()
Definition at line 292 of file TestHM4.java.
{
     // Hand-rolled cons/cdr
     // let cons = { x y -> { cadr -> (cadr x y) } }
     // in         let cdr = { mycons -> (mycons { p q -> q}) }
     //            in (cdr (cons 2 3))
     Syntax syn =
       new Let("cons", new Lambda2("x","y",
                                   new Lambda("cadr",new Apply(new Ident("cadr"),new Ident("x"),new Ident("y")))),
               new Let("cdr", new Lambda("mycons", new Apply(new Ident("mycons"), new Lambda2("p","q", new Ident("q")))),
                       new Apply(new Ident("cdr"),
                                 new Apply(new Ident("cons"), new Con(TypeInt.con(2)), new Con(TypeInt.con(3))))));
     T2 t1 = HM4.hm(syn);
     assertEquals("3",t1.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test19()
void com.cliffc.aa.HM.TestHM4.test19 ()
Definition at line 315 of file TestHM4.java.
{
     Syntax syn =
       new Let("cons", new Lambda2("x","y",
                                   new Lambda("cadr",new Apply(new Ident("cadr"),new Ident("x"),new Ident("y")))),
               new Let("cdr", new Lambda("mycons", new Apply(new Ident("mycons"), new Lambda2("p","q", new Ident("q")))),
                       new Let("map",
                               new Lambda2("fun", "parg",
                                           new Apply(new Ident("fun"),
                                                     new Apply(new Ident("cdr"),new Ident("parg"))
                                                     )),
                               // in pair(map(),map())
                               new Apply(new Ident("pair2"),
                                         new Apply(new Ident("map"), new Ident("str"    ), (new Apply(new Ident("cons"),new Con(TypeInt.BOOL),new Con(TypeInt.con(5))))),
                                         new Apply(new Ident("map"), new Ident("isempty"), (new Apply(new Ident("cons"),new Con(TypeInt.BOOL),new Con(TypeStr.ABC   ))))
                                         ))));
     T2 t1 = HM4.hm(syn);
     assertEquals("(pair2 str int1)",t1.p());
   }
References com.cliffc.aa.type.TypeStr.ABC, com.cliffc.aa.type.TypeInt.BOOL, com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test20()
void com.cliffc.aa.HM.TestHM4.test20 ()
Definition at line 336 of file TestHM4.java.
{
     // let f0 = fn f x => (if/else3 (==0 x) 1 (f (f0 f (dec x)) 2) ) in f0 *2 99
     Syntax x =
       new Let("f0", new Lambda2("f","x",
                                 new Apply(new Ident("if/else3"),
                                           new Apply(new Ident("==0"), new Ident("x")),
                                           new Con(TypeInt.con(1)),
                                           new Apply(new Ident("f"),
                                                     new Apply(new Ident("f0"),
                                                               new Ident("f"),
                                                               new Apply(new Ident("dec"), new Ident("x"))),
                                                     new Con(TypeInt.con(2)))
                                           )
                                 ),
               new Apply(new Ident("f0"), new Ident("*2"), new Con(TypeInt.con(99))));
     T2 t1 = HM4.hm(x);
     assertEquals("int64",t1.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test21()
void com.cliffc.aa.HM.TestHM4.test21 ()
Definition at line 358 of file TestHM4.java.
{
     // let f0 = fn f x => (if/else3 (==0 x) 1 (*2 (f0 f (dec x)) 2) ) in f0 f0 99
     // let f0 = fn f x => (if/else3 (==0 x) 1 (f  (f0 f (dec x)) 2) ) in f0 *2 99
     Syntax x =
       new Let("f0", new Lambda2("f","x",
                                 new Apply(new Ident("if/else3"),
                                           new Apply(new Ident("==0"), new Ident("x")),
                                           new Con(TypeInt.con(1)),
                                           new Apply(new Ident("*2"),
                                                     new Apply(new Ident("f0"),
                                                               new Ident("f"),
                                                               new Apply(new Ident("dec"), new Ident("x"))),
                                                     new Con(TypeInt.con(2)))
                                           )
                                 ),
               new Apply(new Ident("f0"), new Ident("f0"), new Con(TypeInt.con(99))));
     T2 t1 = HM4.hm(x);
     assertEquals("int64",t1.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test22()
void com.cliffc.aa.HM.TestHM4.test22 ()
Definition at line 380 of file TestHM4.java.
{
     /* let is_even =
            (let is_odd = fn x => (if/else3 (==0 x) false (is_even (dec x)))
                       in fn x => (if/else3 (==0 x) true  (is_odd  (dec x))))
                    in (is_even 3)
     */
     Syntax x = new Let("is_even",
                        new Let("is_odd",
                                new Lambda("n",
                                           new Apply(new Ident("if/else3"),
                                                     new Apply(new Ident("==0"), new Ident("n")),
                                                     new Con(TypeInt.con(0)),
                                                     new Apply(new Ident("is_even"),
                                                               new Apply(new Ident("dec"), new Ident("n"))))),
                                new Lambda("n",
                                           new Apply(new Ident("if/else3"),
                                                     new Apply(new Ident("==0"), new Ident("n")),
                                                     new Con(TypeInt.con(1)),
                                                     new Apply(new Ident("is_odd" ),
                                                               new Apply(new Ident("dec"), new Ident("n")))))
                                ),
                        new Apply(new Ident("is_even"), new Con(TypeInt.con(3))));
     T2 t1 = HM4.hm(x);
     assertEquals("int1",t1.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test23()
void com.cliffc.aa.HM.TestHM4.test23 ()
Definition at line 408 of file TestHM4.java.
{
     // { g ->
     //   let fgz =
     //     // Hand-rolled cons/cdr
     //     let cons = { x y -> { cadr -> (cadr x y) } }
     //     in         let cdr = { mycons -> (mycons { p q -> q}) }
     //                in (cdr (cons 2 {z -> g z}))
     //   in (pair2 (fgz 3) (fgz 5))
     // }
     Syntax syn =
       new Lambda("g",
                  new Let("fgz",
                          new Let("cons",
                                  new Lambda2("x","y", new Lambda("cadr",new Apply(new Ident("cadr"),new Ident("x"),new Ident("y")))),
                                  new Let("cdr",
                                          new Lambda("mycons", new Apply(new Ident("mycons"), new Lambda2("p","q", new Ident("q")))),
                                          new Apply(new Ident("cdr"),
                                                    new Apply(new Ident("cons"),
                                                              new Con(TypeInt.con(2)),
                                                              new Lambda("z",new Apply(new Ident("g"),new Ident("z"))))))),
                          new Apply(new Ident("pair2"),
                                    new Apply(new Ident("fgz"),new Con(TypeInt.con(3))),
                                    new Apply(new Ident("fgz"),new Con(TypeInt.con(5))))));
     T2 t1 = HM4.hm(syn);
     assertEquals("{ { nint8 -> V31 } -> (pair2 V31 V31) }",t1.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM7.T2.p().
The documentation for this class was generated from the following file:
TestHM4.java