aa: com.cliffc.aa.HM.HM4.T2 Class Reference
com.cliffc.aa.HM.HM4.T2 Class Reference
Public Member Functions
String p ()
String toString ()
Package Functions
boolean _cycle_equals (T2 t)
VBitSet _get_dups (VBitSet visit, VBitSet dups)
T2 _repl (HashMap< T2, T2 > vars, HashMap< T2, T2 > dups)
boolean cycle_equals (T2 t)
T2 find ()
T2 find (int i)
VBitSet get_dups (VBitSet dups)
T2 get_fresh ()
boolean is_base ()
boolean is_fresh ()
boolean is_leaf ()
boolean is_tvar ()
void live (IBitSet visit)
boolean no_uf ()
String p (VBitSet dups)
boolean progress (T2 t)
void push_update (Syntax a)
T2 repl (HashMap< T2, T2 > vars, HashMap< T2, T2 > dups)
SB str (SB sb, VBitSet visit, VBitSet dups)
T2 unify (T2 t, Ary< Syntax > work)
T2 union (T2 that, Ary< Syntax > work)
Static Package Functions
static T2 base (Type con)
static T2 fresh (String name, T2 t)
static T2 fun (T2... args)
static T2 prim (String name, T2... args)
static void reset ()
static T2 tnew ()
Package Attributes
T2[] _args
Type _con
String _fresh
final String _name
final int _uid
Ary< Syntax > _updates
Static Package Attributes
static final VBitSet UPDATE_VISIT = new VBitSet()
Private Member Functions
T2 (@NotNull String name, T2 @NotNull ... args)
T2 _fresh_unify (HashMap< T2, T2 > vars, T2 t, Ary< Syntax > work)
T2 _fresh_unify_impl (HashMap< T2, T2 > vars, T2 t, Ary< Syntax > work)
SB _p (SB sb, VBitSet visit, VBitSet dups)
T2 _unify (T2 t, Ary< Syntax > work)
T2 fresh_base (T2 t)
void push_update_impl (Syntax a)
T2 unify_base (T2 t, Ary< Syntax > work)
Static Private Member Functions
static SB str (SB sb, VBitSet visit, T2 t, VBitSet dups)
Static Private Attributes
static final HashMap< T2, T2 > CDUPS = new HashMap<>()
static int CNT =0
static final HashMap< Long, T2 > DUPS = new HashMap<>()
Detailed Description
Definition at line 324 of file HM4.java.
Constructor & Destructor Documentation
T2()
com.cliffc.aa.HM.HM4.T2.T2 (@NotNull String name, T2 @NotNull ... args) private
Definition at line 355 of file HM4.java.
 { _name = name; _args= args; _uid=CNT++; }
References com.cliffc.aa.HM.HM4.T2._args, com.cliffc.aa.HM.HM4.T2._name, com.cliffc.aa.HM.HM4.T2._uid, and com.cliffc.aa.HM.HM4.T2.CNT.
Referenced by com.cliffc.aa.HM.HM4.T2._fresh_unify_impl(), com.cliffc.aa.HM.HM4.T2._repl(), com.cliffc.aa.HM.HM4.T2._unify(), com.cliffc.aa.HM.HM4.T2.fresh(), com.cliffc.aa.HM.HM4.T2.fun(), com.cliffc.aa.HM.HM4.T2.prim(), and com.cliffc.aa.HM.HM4.T2.tnew().
Member Function Documentation
_cycle_equals()
boolean com.cliffc.aa.HM.HM4.T2._cycle_equals (T2 t) package
Definition at line 558 of file HM4.java.
{
       assert no_uf() && t.no_uf();
       if( this==t ) return true;
       if( !is_tvar() || !t.is_tvar() ||    // Base-cases have to be completely identical
           !Util.eq(_name,t._name) ||       // Wrong type-var names
           _args.length != t._args.length ) // Mismatched sizes
         return false;
       if( _args==t._args ) return true;
       // Cycles stall the equal/unequal decision until we see a difference.
       T2 tc = CDUPS.get(this);
       if( tc!=null )
         return tc==t; // Cycle check; true if both cycling the same
       CDUPS.put(this,t);
       for( int i=0; i<_args.length; i++ )
         if( !find(i)._cycle_equals(t.find(i)) )
           return false;
       return true;
     }
References com.cliffc.aa.HM.HM4.T2._args, com.cliffc.aa.HM.HM4.T2._name, com.cliffc.aa.HM.HM4.T2.CDUPS, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM4.T2.find(), com.cliffc.aa.HM.HM4.T2.is_tvar(), and com.cliffc.aa.HM.HM4.T2.no_uf().
Referenced by com.cliffc.aa.HM.HM4.T2.cycle_equals().
_fresh_unify()
T2 com.cliffc.aa.HM.HM4.T2._fresh_unify (HashMap< T2, T2 > vars, T2 t, Ary< Syntax > work) private
Definition at line 477 of file HM4.java.
{
       assert no_uf() && t.no_uf();
       assert this!=t || is_base(); // No overlap between LHS and RHS.
       T2 prior = vars.get(this);
       if( prior!=null )         // Been there, done that?  Return prior mapping
         return prior.find().unify(t,work);
       assert !is_fresh();       // recursive fresh?
       T2 rez = _fresh_unify_impl( vars, t, work );
       vars.put(this,rez);
       return rez;
     }
References com.cliffc.aa.HM.HM4.T2._fresh_unify_impl(), com.cliffc.aa.HM.HM4.T2.find(), com.cliffc.aa.HM.HM4.T2.is_base(), com.cliffc.aa.HM.HM4.T2.is_fresh(), com.cliffc.aa.HM.HM4.T2.no_uf(), and com.cliffc.aa.HM.HM4.T2.unify().
Referenced by com.cliffc.aa.HM.HM4.T2._fresh_unify_impl(), and com.cliffc.aa.HM.HM4.T2.unify().
_fresh_unify_impl()
T2 com.cliffc.aa.HM.HM4.T2._fresh_unify_impl (HashMap< T2, T2 > vars, T2 t, Ary< Syntax > work) private
Definition at line 489 of file HM4.java.
{
       // RHS is also a lazy clone, which if cloned, will not be part of any
       // other structure.  When unioned with the clone of the LHS, the result
       // is not part of anything direct... but the structures still have to
       // align for the returned T2.  Make a replica & unify (e.g. stop being lazy).
       if( t.is_fresh() ) t = t.get_fresh().repl(vars, new HashMap<>());
       if( is_base() && t.is_base() ) return fresh_base(t);
       if(   is_leaf() ) return t;   // Lazy map LHS tvar to RHS
       if( t.is_leaf() ) return t.union(repl(vars, new HashMap<>()),work); // RHS is a tvar; union with a copy of LHS
       if( !Util.eq(_name,t._name) )
         throw com.cliffc.aa.AA.unimpl(); // unification error
       if( _args.length != t._args.length )
         throw new RuntimeException("Cannot unify "+this+" and "+t);
       // Structural recursion unification, lazy on LHS
       T2[] args = new T2[_args.length];
       for( int i=0; i<_args.length; i++ )
         args[i] = find(i)._fresh_unify(vars,t.find(i),work);
       return new T2(_name,args);
     }
References com.cliffc.aa.HM.HM4.T2._args, com.cliffc.aa.HM.HM4.T2._fresh_unify(), com.cliffc.aa.HM.HM4.T2._name, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM4.T2.find(), com.cliffc.aa.HM.HM4.T2.fresh_base(), com.cliffc.aa.HM.HM4.T2.get_fresh(), com.cliffc.aa.HM.HM4.T2.is_base(), com.cliffc.aa.HM.HM4.T2.is_fresh(), com.cliffc.aa.HM.HM4.T2.is_leaf(), com.cliffc.aa.HM.HM4.T2.repl(), com.cliffc.aa.HM.HM4.T2.T2(), com.cliffc.aa.AA.unimpl(), and com.cliffc.aa.HM.HM4.T2.union().
Referenced by com.cliffc.aa.HM.HM4.T2._fresh_unify().
_get_dups()
VBitSet com.cliffc.aa.HM.HM4.T2._get_dups (VBitSet visit, VBitSet dups) package
Definition at line 600 of file HM4.java.
{
       if( visit.tset(_uid) && no_uf() ) dups.set(_uid);
       else
         for( T2 t : _args )
           if( t!=null )
             t._get_dups(visit,dups);
       return dups;
     }
References com.cliffc.aa.HM.HM4.T2._args, com.cliffc.aa.HM.HM4.T2._uid, com.cliffc.aa.HM.HM4.T2.no_uf(), and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.HM.HM4.T2.get_dups().
_p()
SB com.cliffc.aa.HM.HM4.T2._p (SB sb, VBitSet visit, VBitSet dups) private
Definition at line 639 of file HM4.java.
{
       assert no_uf();
       if( is_fresh() ) return get_fresh()._p(sb.p('#'),visit,dups);
       if( is_base() ) return sb.p(_con instanceof TypeMemPtr ? "str" : _con.toString() );
       if( is_leaf() ) return sb.p(_name);
       boolean dup = dups.get(_uid);
       if( dup ) sb.p('$').p(_uid);
       if( visit.tset(_uid) && dup ) return sb;
       if( dup ) sb.p(':');
       if( _name.equals("->") ) {
         sb.p("{ ");
         for( int i=0; i<_args.length-1; i++ )
           find(i)._p(sb,visit,dups).p(" ");
         return find(_args.length-1)._p(sb.p("-> "),visit,dups).p(" }");
       }
       // Generic structural T2
       sb.p("(").p(_name).p(" ");
       for( int i=0; i<_args.length; i++ ) find(i)._p(sb,visit,dups).p(" ");
       return sb.unchar().p(")");
     }
References com.cliffc.aa.HM.HM4.T2._args, com.cliffc.aa.HM.HM4.T2._con, com.cliffc.aa.HM.HM4.T2._name, com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM4.T2._uid, com.cliffc.aa.HM.HM4.T2.find(), com.cliffc.aa.HM.HM4.T2.get_fresh(), com.cliffc.aa.HM.HM4.T2.is_base(), com.cliffc.aa.HM.HM4.T2.is_fresh(), com.cliffc.aa.HM.HM4.T2.is_leaf(), com.cliffc.aa.HM.HM4.T2.no_uf(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.Type< T extends Type< T >.toString(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.util.SB.unchar().
Referenced by com.cliffc.aa.HM.HM4.T2._p(), and com.cliffc.aa.HM.HM4.T2.p().
_repl()
T2 com.cliffc.aa.HM.HM4.T2._repl (HashMap< T2, T2 > vars, HashMap< T2, T2 > dups) package
Definition at line 521 of file HM4.java.
{
       if( is_leaf() ) return tnew(); // LHS is a leaf, make a new one for RHS
       // Must replicate base's, because they are not really immutable:
       // mismatched Types meet instead of error.
       if( is_base() ) return base(_con);
       T2[] args = new T2[_args.length];
       T2 rez = new T2(_name,args);
       vars.put(this,rez); // Insert in dups BEFORE structural recursion, to stop cycles
       // Structural recursion replicate
       for( int i=0; i<_args.length; i++ )
         args[i] = find(i).repl(vars,dups);
       return rez;
     }
References com.cliffc.aa.HM.HM4.T2._args, com.cliffc.aa.HM.HM4.T2._con, com.cliffc.aa.HM.HM4.T2._name, com.cliffc.aa.HM.HM4.T2.base(), com.cliffc.aa.HM.HM4.T2.find(), com.cliffc.aa.HM.HM4.T2.is_base(), com.cliffc.aa.HM.HM4.T2.is_leaf(), com.cliffc.aa.HM.HM4.T2.repl(), com.cliffc.aa.HM.HM4.T2.T2(), and com.cliffc.aa.HM.HM4.T2.tnew().
Referenced by com.cliffc.aa.HM.HM4.T2.repl().
_unify()
T2 com.cliffc.aa.HM.HM4.T2._unify (T2 t, Ary< Syntax > work) private
Definition at line 431 of file HM4.java.
{
       assert no_uf() && t.no_uf();
       if( this==t ) return this;
       if(   is_fresh() ) throw com.cliffc.aa.AA.unimpl(); // recursive fresh?
       if( t.is_fresh() ) throw com.cliffc.aa.AA.unimpl(); // RHS is fresh?
       if( is_base() && t.is_base() ) return unify_base(t,work);
       // two leafs union in either order, so keep lower uid
       if( is_leaf() && t.is_leaf() && _uid<t._uid ) return t.union(this,work);
       if(   is_leaf() ) return   union(t   ,work);
       if( t.is_leaf() ) return t.union(this,work);
       if( !Util.eq(_name,t._name) )
         throw new RuntimeException("Cannot unify "+this+" and "+t);
       if( _args==t._args ) return this; // Names are equal, args are equal
       if( _args.length != t._args.length )
         throw new RuntimeException("Cannot unify "+this+" and "+t);
       // Cycle check.
       long luid = ((long)_uid<<32)|t._uid;
       T2 rez = DUPS.get(luid), rez2;
       if( rez!=null ) return rez; // Been there, done that
       T2[] args = new T2[_args.length];
       rez = rez2 = new T2(_name,args);
       DUPS.put(luid,rez);       // Close cycles
       // Structural recursion unification.
       for( int i=0; i<_args.length; i++ )
         args[i] = find(i)._unify(t.find(i),work);
       // Check for being equal, cyclic-ly, and return a prior if possible.
       boolean eq0 = rez.cycle_equals(this);
       boolean eq1 = rez.cycle_equals(t   );
       if( eq0 ) rez2 = this;
       if( eq1 ) rez2 = t   ;
       if( eq0 && eq1 ) rez2 = _uid < t._uid ? this : t;
       if( rez!=rez2 ) DUPS.put(luid,rez2);
       // Return new unified T2
       return rez2;
     }
References com.cliffc.aa.HM.HM4.T2._args, com.cliffc.aa.HM.HM4.T2._name, com.cliffc.aa.HM.HM4.T2._uid, com.cliffc.aa.HM.HM4.T2._unify(), com.cliffc.aa.HM.HM4.T2.cycle_equals(), com.cliffc.aa.HM.HM4.T2.DUPS, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM4.T2.find(), com.cliffc.aa.HM.HM4.T2.is_base(), com.cliffc.aa.HM.HM4.T2.is_fresh(), com.cliffc.aa.HM.HM4.T2.is_leaf(), com.cliffc.aa.HM.HM4.T2.no_uf(), com.cliffc.aa.HM.HM4.T2.T2(), com.cliffc.aa.HM.HM4.T2.unify_base(), com.cliffc.aa.AA.unimpl(), and com.cliffc.aa.HM.HM4.T2.union().
Referenced by com.cliffc.aa.HM.HM4.T2._unify(), and com.cliffc.aa.HM.HM4.T2.unify().
base()
static T2 com.cliffc.aa.HM.HM4.T2.base (Type con) static package
Definition at line 345 of file HM4.java.
 { T2 t = tnew(); t._con=con; return t; }
References com.cliffc.aa.HM.HM4.T2._con, and com.cliffc.aa.HM.HM4.T2.tnew().
Referenced by com.cliffc.aa.HM.HM4.T2._repl(), com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM4.Con.prep_tree().
cycle_equals()
boolean com.cliffc.aa.HM.HM4.T2.cycle_equals (T2 t) package
Definition at line 552 of file HM4.java.
{
       assert CDUPS.isEmpty();
       boolean rez = _cycle_equals(t);
       CDUPS.clear();
       return rez;
     }
References com.cliffc.aa.HM.HM4.T2._cycle_equals(), and com.cliffc.aa.HM.HM4.T2.CDUPS.
Referenced by com.cliffc.aa.HM.HM4.T2._unify().
find() [1/2]
T2 com.cliffc.aa.HM.HM4.T2.find () package
Definition at line 378 of file HM4.java.
               {
       if( is_tvar() ) return this; // Shortcut
       T2 u = _args[0];
       if( u==null ) return this; // Shortcut
       if( u.no_uf() ) return u;  // Shortcut
       // U-F fixup
       while( !u.is_tvar() && u._args[0]!=null ) u = u._args[0];
       T2 v = this, v2;
       while( !v.is_tvar() && (v2=v._args[0])!=u ) { v._args[0]=u; v = v2; }
       return u;
     }
References com.cliffc.aa.HM.HM4.T2._args, com.cliffc.aa.HM.HM4.T2.is_tvar(), and com.cliffc.aa.HM.HM4.T2.no_uf().
Referenced by com.cliffc.aa.HM.HM4.T2._cycle_equals(), com.cliffc.aa.HM.HM4.T2._fresh_unify(), com.cliffc.aa.HM.HM4.T2._fresh_unify_impl(), com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM4.T2._repl(), com.cliffc.aa.HM.HM4.T2._unify(), com.cliffc.aa.HM.HM4.Syntax.find(), com.cliffc.aa.HM.HM4.T2.find(), com.cliffc.aa.HM.HM4.T2.get_fresh(), com.cliffc.aa.HM.HM4.Apply.hm(), com.cliffc.aa.HM.HM4.T2.p(), com.cliffc.aa.HM.HM4.T2.progress(), com.cliffc.aa.HM.HM4.T2.push_update_impl(), com.cliffc.aa.HM.HM4.Lambda.targ(), com.cliffc.aa.HM.HM4.Let.targ(), com.cliffc.aa.HM.HM4.Lambda2.targ0(), and com.cliffc.aa.HM.HM4.Lambda2.targ1().
find() [2/2]
T2 com.cliffc.aa.HM.HM4.T2.find (int i) package
Definition at line 390 of file HM4.java.
                    {
       T2 u = _args[i];
       T2 uu = u.find();
       return u==uu ? uu : (_args[i]=uu);
     }
References com.cliffc.aa.HM.HM4.T2._args, and com.cliffc.aa.HM.HM4.T2.find().
fresh()
static T2 com.cliffc.aa.HM.HM4.T2.fresh (String name, T2 t) static package
Definition at line 347 of file HM4.java.
{
       assert !t.is_fresh();
       T2 t2 = new T2(name,t); // Points to non-fresh
       t2._fresh=name;
       assert t2.is_fresh();
       return t2;
     }
References com.cliffc.aa.HM.HM4.T2._fresh, com.cliffc.aa.HM.HM4.T2.is_fresh(), and com.cliffc.aa.HM.HM4.T2.T2().
Referenced by com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM4.Let.prep_tree_lookup().
fresh_base()
T2 com.cliffc.aa.HM.HM4.T2.fresh_base (T2 t) private
Definition at line 472 of file HM4.java.
 { t._con = _con.meet(t._con); return t; }
References com.cliffc.aa.HM.HM4.T2._con, and com.cliffc.aa.type.Type< T extends Type< T >.meet().
Referenced by com.cliffc.aa.HM.HM4.T2._fresh_unify_impl(), and com.cliffc.aa.HM.HM4.T2.unify_base().
fun()
static T2 com.cliffc.aa.HM.HM4.T2.fun (T2... args) static package
Definition at line 343 of file HM4.java.
 { return new T2("->",args); }
References com.cliffc.aa.HM.HM4.T2.T2().
Referenced by com.cliffc.aa.HM.HM4.T2.get_fresh(), com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Lambda.hm(), com.cliffc.aa.HM.HM4.Lambda2.hm(), and com.cliffc.aa.HM.HM4.Apply.hm().
get_dups()
VBitSet com.cliffc.aa.HM.HM4.T2.get_dups (VBitSet dups) package
Definition at line 599 of file HM4.java.
 { return _get_dups(new VBitSet(),dups); }
References com.cliffc.aa.HM.HM4.T2._get_dups().
Referenced by com.cliffc.aa.HM.HM4.T2.p(), com.cliffc.aa.HM.HM4.Syntax.p0(), and com.cliffc.aa.HM.HM4.T2.toString().
get_fresh()
T2 com.cliffc.aa.HM.HM4.T2.get_fresh () package
Definition at line 365 of file HM4.java.
                    {
       assert is_fresh();
       T2 fun = find(0);
       assert Util.eq(fun._name,"->");
       return fun;
     }
References com.cliffc.aa.HM.HM4.T2._name, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM4.T2.find(), com.cliffc.aa.HM.HM4.T2.fun(), and com.cliffc.aa.HM.HM4.T2.is_fresh().
Referenced by com.cliffc.aa.HM.HM4.T2._fresh_unify_impl(), com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM4.Apply.hm(), com.cliffc.aa.HM.HM4.T2.progress(), and com.cliffc.aa.HM.HM4.T2.unify().
is_base()
boolean com.cliffc.aa.HM.HM4.T2.is_base () package
Definition at line 362 of file HM4.java.
 { return _con!=null; }
References com.cliffc.aa.HM.HM4.T2._con.
Referenced by com.cliffc.aa.HM.HM4.T2._fresh_unify(), com.cliffc.aa.HM.HM4.T2._fresh_unify_impl(), com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM4.T2._repl(), com.cliffc.aa.HM.HM4.T2._unify(), com.cliffc.aa.HM.HM4.T2.is_leaf(), com.cliffc.aa.HM.HM4.T2.progress(), com.cliffc.aa.HM.HM4.T2.push_update_impl(), and com.cliffc.aa.HM.HM4.T2.str().
is_fresh()
boolean com.cliffc.aa.HM.HM4.T2.is_fresh () package
Definition at line 358 of file HM4.java.
 { assert _fresh==null || (_args.length==1 && _args[0]!=null); return _fresh!=null; }
References com.cliffc.aa.HM.HM4.T2._args, and com.cliffc.aa.HM.HM4.T2._fresh.
Referenced by com.cliffc.aa.HM.HM4.T2._fresh_unify(), com.cliffc.aa.HM.HM4.T2._fresh_unify_impl(), com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM4.T2._unify(), com.cliffc.aa.HM.HM4.T2.fresh(), com.cliffc.aa.HM.HM4.T2.get_fresh(), com.cliffc.aa.HM.HM4.Lambda.hm(), com.cliffc.aa.HM.HM4.Apply.hm(), com.cliffc.aa.HM.HM4.T2.progress(), com.cliffc.aa.HM.HM4.T2.repl(), com.cliffc.aa.HM.HM4.T2.str(), and com.cliffc.aa.HM.HM4.T2.unify().
is_leaf()
boolean com.cliffc.aa.HM.HM4.T2.is_leaf () package
Definition at line 360 of file HM4.java.
 { return _name.charAt(0)=='V' && !is_base(); }
References com.cliffc.aa.HM.HM4.T2._name, and com.cliffc.aa.HM.HM4.T2.is_base().
Referenced by com.cliffc.aa.HM.HM4.T2._fresh_unify_impl(), com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM4.T2._repl(), com.cliffc.aa.HM.HM4.T2._unify(), com.cliffc.aa.HM.HM4.T2.progress(), com.cliffc.aa.HM.HM4.T2.push_update_impl(), and com.cliffc.aa.HM.HM4.T2.str().
is_tvar()
boolean com.cliffc.aa.HM.HM4.T2.is_tvar () package
Definition at line 364 of file HM4.java.
 { return _name.charAt(0)!='V' && _con==null; }
References com.cliffc.aa.HM.HM4.T2._con, and com.cliffc.aa.HM.HM4.T2._name.
Referenced by com.cliffc.aa.HM.HM4.T2._cycle_equals(), com.cliffc.aa.HM.HM4.T2.find(), com.cliffc.aa.HM.HM4.T2.no_uf(), and com.cliffc.aa.HM.HM4.T2.push_update_impl().
live()
void com.cliffc.aa.HM.HM4.T2.live (IBitSet visit) package
Definition at line 372 of file HM4.java.
{
       if( visit.set(_uid) ) return;
       for( T2 t : _args ) if( t!=null ) t.live(visit);
     }
References com.cliffc.aa.HM.HM4.T2._args, com.cliffc.aa.HM.HM4.T2._uid, and com.cliffc.aa.util.IBitSet.set().
Referenced by com.cliffc.aa.HM.HM4.Con.live(), com.cliffc.aa.HM.HM4.Ident.live(), com.cliffc.aa.HM.HM4.Lambda.live(), com.cliffc.aa.HM.HM4.Lambda2.live(), com.cliffc.aa.HM.HM4.Let.live(), and com.cliffc.aa.HM.HM4.Apply.live().
no_uf()
boolean com.cliffc.aa.HM.HM4.T2.no_uf () package
Definition at line 395 of file HM4.java.
 { return is_tvar() || _args[0]==null; }
References com.cliffc.aa.HM.HM4.T2._args, and com.cliffc.aa.HM.HM4.T2.is_tvar().
Referenced by com.cliffc.aa.HM.HM4.T2._cycle_equals(), com.cliffc.aa.HM.HM4.T2._fresh_unify(), com.cliffc.aa.HM.HM4.T2._get_dups(), com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM4.T2._unify(), com.cliffc.aa.HM.HM4.T2.find(), com.cliffc.aa.HM.HM4.T2.progress(), com.cliffc.aa.HM.HM4.T2.push_update_impl(), com.cliffc.aa.HM.HM4.T2.repl(), and com.cliffc.aa.HM.HM4.T2.unify().
p() [1/2]
String com.cliffc.aa.HM.HM4.T2.p ()
Definition at line 637 of file HM4.java.
 { return p(get_dups(new VBitSet())); }
References com.cliffc.aa.HM.HM4.T2.get_dups(), and com.cliffc.aa.HM.HM4.T2.p().
Referenced by com.cliffc.aa.HM.HM4.T2.p().
p() [2/2]
String com.cliffc.aa.HM.HM4.T2.p (VBitSet dups) package
Definition at line 638 of file HM4.java.
 { return find()._p(new SB(), new VBitSet(), dups).toString(); }
References com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM4.T2.find(), and com.cliffc.aa.util.SB.toString().
prim()
static T2 com.cliffc.aa.HM.HM4.T2.prim (String name, T2... args) static package
Definition at line 346 of file HM4.java.
 { return new T2(name,args); }
References com.cliffc.aa.HM.HM4.T2.T2().
Referenced by com.cliffc.aa.HM.HM4.hm().
progress()
boolean com.cliffc.aa.HM.HM4.T2.progress (T2 t) package
Definition at line 537 of file HM4.java.
{
       assert no_uf() && t.no_uf();
       if( this==t ) return false;
       if( t.is_leaf() ) return false; // will be equal after unify
       if( is_base() && t.is_base() && _con==t._con ) return false;
       if( is_fresh() ) return get_fresh().progress(t);
       if( !Util.eq(_name,t._name) || _args.length!=t._args.length )
         return true;            // Blatantly not-equal
       for( int i=0; i<_args.length; i++ )
         if( find(i).progress(t.find(i)) )
           return true;          // Recursive progress
       return false;
     }
References com.cliffc.aa.HM.HM4.T2._args, com.cliffc.aa.HM.HM4.T2._con, com.cliffc.aa.HM.HM4.T2._name, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM4.T2.find(), com.cliffc.aa.HM.HM4.T2.get_fresh(), com.cliffc.aa.HM.HM4.T2.is_base(), com.cliffc.aa.HM.HM4.T2.is_fresh(), com.cliffc.aa.HM.HM4.T2.is_leaf(), com.cliffc.aa.HM.HM4.T2.no_uf(), and com.cliffc.aa.HM.HM4.T2.progress().
Referenced by com.cliffc.aa.HM.HM4.hm(), and com.cliffc.aa.HM.HM4.T2.progress().
push_update()
void com.cliffc.aa.HM.HM4.T2.push_update (Syntax a) package
Definition at line 582 of file HM4.java.
 { UPDATE_VISIT.clear(); push_update_impl(a); }
References com.cliffc.aa.HM.HM4.T2.push_update_impl(), and com.cliffc.aa.HM.HM4.T2.UPDATE_VISIT.
Referenced by com.cliffc.aa.HM.HM4.Let.hm(), and com.cliffc.aa.HM.HM4.Apply.hm().
push_update_impl()
void com.cliffc.aa.HM.HM4.T2.push_update_impl (Syntax a) private
Definition at line 583 of file HM4.java.
{
       assert no_uf();
       if( is_leaf() ) {
         if( _updates==null ) _updates = new Ary<>(Syntax.class);
         if( _updates.find(a)==-1 ) _updates.push(a);
       } else if( is_tvar() ) {
         if( UPDATE_VISIT.tset(_uid) ) return;
         for( int i=0; i<_args.length; i++ )
           find(i).push_update_impl(a);
       } else assert is_base();
     }
References com.cliffc.aa.HM.HM4.T2._args, com.cliffc.aa.HM.HM4.T2._uid, com.cliffc.aa.HM.HM4.T2._updates, com.cliffc.aa.HM.HM4.T2.find(), com.cliffc.aa.HM.HM4.T2.is_base(), com.cliffc.aa.HM.HM4.T2.is_leaf(), com.cliffc.aa.HM.HM4.T2.is_tvar(), com.cliffc.aa.HM.HM4.T2.no_uf(), com.cliffc.aa.HM.HM4.T2.push_update_impl(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.HM.HM4.T2.UPDATE_VISIT.
Referenced by com.cliffc.aa.HM.HM4.T2.push_update(), and com.cliffc.aa.HM.HM4.T2.push_update_impl().
repl()
T2 com.cliffc.aa.HM.HM4.T2.repl (HashMap< T2, T2 > vars, HashMap< T2, T2 > dups) package
Definition at line 513 of file HM4.java.
{
       assert no_uf() && !is_fresh();
       T2 t = vars.get(this);
       if( t!=null ) return t;   // Been there, done that, return prior answer
       T2 rez = _repl(vars,dups);
       vars.put(this,rez);
       return rez;
     }
References com.cliffc.aa.HM.HM4.T2._repl(), com.cliffc.aa.HM.HM4.T2.is_fresh(), and com.cliffc.aa.HM.HM4.T2.no_uf().
Referenced by com.cliffc.aa.HM.HM4.T2._fresh_unify_impl(), and com.cliffc.aa.HM.HM4.T2._repl().
reset()
static void com.cliffc.aa.HM.HM4.T2.reset () static package
Definition at line 325 of file HM4.java.
 { CNT=0; }
References com.cliffc.aa.HM.HM4.T2.CNT.
Referenced by com.cliffc.aa.HM.HM4.reset().
str() [1/2]
static SB com.cliffc.aa.HM.HM4.T2.str (SB sb, VBitSet visit, T2 t, VBitSet dups) static private
Definition at line 634 of file HM4.java.
 { return t==null ? sb.p("_") : t.str(sb,visit,dups); }
References com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM4.T2.str().
str() [2/2]
SB com.cliffc.aa.HM.HM4.T2.str (SB sb, VBitSet visit, VBitSet dups) package
Definition at line 612 of file HM4.java.
{
       if( is_fresh() ) return _args[0].str(sb.p('#'),visit,dups);
       if( is_leaf() || is_base() ) {
         if( is_base() ) sb.p(_con instanceof TypeMemPtr ? "str" : _con.toString()); else sb.p(_name);
         return _args[0]==null ? sb : _args[0].str(sb.p(">>"), visit, dups);
       }
       boolean dup = dups.get(_uid);
       if( dup ) sb.p('$').p(_uid);
       if( visit.tset(_uid) && dup ) return sb;
       if( dup ) sb.p(':');
       if( _name.equals("->") ) {
         sb.p("{ ");
         for( int i=0; i<_args.length-1; i++ )
           str(sb,visit,_args[i],dups).p(" ");
         return str(sb.p("-> "),visit,_args[_args.length-1],dups).p(" }");
       }
       // Generic structural T2
       sb.p("(").p(_name).p(" ");
       for( T2 t : _args ) str(sb,visit,t,dups).p(" ");
       return sb.unchar().p(")");
     }
References com.cliffc.aa.HM.HM4.T2._args, com.cliffc.aa.HM.HM4.T2._con, com.cliffc.aa.HM.HM4.T2._name, com.cliffc.aa.HM.HM4.T2._uid, com.cliffc.aa.HM.HM4.T2.is_base(), com.cliffc.aa.HM.HM4.T2.is_fresh(), com.cliffc.aa.HM.HM4.T2.is_leaf(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM4.T2.str(), com.cliffc.aa.type.Type< T extends Type< T >.toString(), com.cliffc.aa.util.VBitSet.tset(), and com.cliffc.aa.util.SB.unchar().
Referenced by com.cliffc.aa.HM.HM4.Syntax.p0(), com.cliffc.aa.HM.HM4.T2.str(), and com.cliffc.aa.HM.HM4.T2.toString().
tnew()
static T2 com.cliffc.aa.HM.HM4.T2.tnew () static package
Definition at line 344 of file HM4.java.
 { return new T2("V"+CNT,new T2[1]); }
References com.cliffc.aa.HM.HM4.T2.CNT, and com.cliffc.aa.HM.HM4.T2.T2().
Referenced by com.cliffc.aa.HM.HM4.T2._repl(), com.cliffc.aa.HM.HM4.T2.base(), com.cliffc.aa.HM.HM4.hm(), com.cliffc.aa.HM.HM4.Apply.hm(), com.cliffc.aa.HM.HM4.Lambda.Lambda(), com.cliffc.aa.HM.HM4.Lambda2.Lambda2(), com.cliffc.aa.HM.HM4.Let.Let(), com.cliffc.aa.HM.HM4.Lambda.prep_tree(), com.cliffc.aa.HM.HM4.Lambda2.prep_tree(), com.cliffc.aa.HM.HM4.Let.prep_tree(), and com.cliffc.aa.HM.HM4.Apply.prep_tree().
toString()
String com.cliffc.aa.HM.HM4.T2.toString ()
Definition at line 611 of file HM4.java.
 { return str(new SB(), new VBitSet(), get_dups(new VBitSet()) ).toString(); }
References com.cliffc.aa.HM.HM4.T2.get_dups(), com.cliffc.aa.HM.HM4.T2.str(), and com.cliffc.aa.util.SB.toString().
unify()
T2 com.cliffc.aa.HM.HM4.T2.unify (T2 t, Ary< Syntax > work) package
Definition at line 415 of file HM4.java.
{
       if( this==t ) return this;
       assert no_uf() && t.no_uf();
       assert !t.is_fresh();     // Only can lazy-clone LHS
       if( is_fresh() )          // Peel off fresh lazy & do a fresh-unify
         return get_fresh()._fresh_unify(new HashMap<>(),t,work);
       // Normal unification, with side-effects
       assert DUPS.isEmpty();
       T2 rez = _unify(t,work);
       DUPS.clear();
       return rez;
     }
References com.cliffc.aa.HM.HM4.T2._fresh_unify(), com.cliffc.aa.HM.HM4.T2._unify(), com.cliffc.aa.HM.HM4.T2.DUPS, com.cliffc.aa.HM.HM4.T2.get_fresh(), com.cliffc.aa.HM.HM4.T2.is_fresh(), and com.cliffc.aa.HM.HM4.T2.no_uf().
Referenced by com.cliffc.aa.HM.HM4.T2._fresh_unify(), com.cliffc.aa.HM.HM4.Lambda.hm(), com.cliffc.aa.HM.HM4.Lambda2.hm(), com.cliffc.aa.HM.HM4.Let.hm(), com.cliffc.aa.HM.HM4.Apply.hm(), and com.cliffc.aa.HM.HM4.Syntax.more_work_impl().
unify_base()
T2 com.cliffc.aa.HM.HM4.T2.unify_base (T2 t, Ary< Syntax > work) private
Definition at line 473 of file HM4.java.
 { return union(fresh_base(t),work); }
References com.cliffc.aa.HM.HM4.T2.fresh_base().
Referenced by com.cliffc.aa.HM.HM4.T2._unify().
union()
T2 com.cliffc.aa.HM.HM4.T2.union (T2 that, Ary< Syntax > work) package
Definition at line 399 of file HM4.java.
{
       assert _args[0]==null;    // Cannot union twice
       if( this==that ) return this;
       // Worklist: put updates on the worklist for revisiting
       if( work!=null ) work.addAll(_updates); // Re-Apply
       // Merge update lists, for future unions
       if( _updates != null ) {
         if( that._updates==null ) that._updates = _updates;
         else throw com.cliffc.aa.AA.unimpl();
       }
       return (_args[0] = that);
     }
References com.cliffc.aa.HM.HM4.T2._args, com.cliffc.aa.HM.HM4.T2._updates, and com.cliffc.aa.AA.unimpl().
Referenced by com.cliffc.aa.HM.HM4.T2._fresh_unify_impl(), and com.cliffc.aa.HM.HM4.T2._unify().
Member Data Documentation
_args
T2 [] com.cliffc.aa.HM.HM4.T2._args package
Definition at line 331 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.T2._cycle_equals(), com.cliffc.aa.HM.HM4.T2._fresh_unify_impl(), com.cliffc.aa.HM.HM4.T2._get_dups(), com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM4.T2._repl(), com.cliffc.aa.HM.HM4.T2._unify(), com.cliffc.aa.HM.HM4.T2.find(), com.cliffc.aa.HM.HM4.Apply.hm(), com.cliffc.aa.HM.HM4.T2.is_fresh(), com.cliffc.aa.HM.HM4.T2.live(), com.cliffc.aa.HM.HM4.T2.no_uf(), com.cliffc.aa.HM.HM4.T2.progress(), com.cliffc.aa.HM.HM4.T2.push_update_impl(), com.cliffc.aa.HM.HM4.T2.str(), com.cliffc.aa.HM.HM4.T2.T2(), and com.cliffc.aa.HM.HM4.T2.union().
_con
Type com.cliffc.aa.HM.HM4.T2._con package
Definition at line 338 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM4.T2._repl(), com.cliffc.aa.HM.HM4.T2.base(), com.cliffc.aa.HM.HM4.T2.fresh_base(), com.cliffc.aa.HM.HM4.T2.is_base(), com.cliffc.aa.HM.HM4.T2.is_tvar(), com.cliffc.aa.HM.HM4.Syntax.more_work_impl(), com.cliffc.aa.HM.HM4.T2.progress(), and com.cliffc.aa.HM.HM4.T2.str().
_fresh
String com.cliffc.aa.HM.HM4.T2._fresh package
Definition at line 336 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.T2.fresh(), and com.cliffc.aa.HM.HM4.T2.is_fresh().
_name
final String com.cliffc.aa.HM.HM4.T2._name package
Definition at line 330 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.T2._cycle_equals(), com.cliffc.aa.HM.HM4.T2._fresh_unify_impl(), com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM4.T2._repl(), com.cliffc.aa.HM.HM4.T2._unify(), com.cliffc.aa.HM.HM4.T2.get_fresh(), com.cliffc.aa.HM.HM4.Apply.hm(), com.cliffc.aa.HM.HM4.T2.is_leaf(), com.cliffc.aa.HM.HM4.T2.is_tvar(), com.cliffc.aa.HM.HM4.T2.progress(), com.cliffc.aa.HM.HM4.T2.str(), and com.cliffc.aa.HM.HM4.T2.T2().
_uid
final int com.cliffc.aa.HM.HM4.T2._uid package
Definition at line 332 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.T2._get_dups(), com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM4.T2._unify(), com.cliffc.aa.HM.HM4.T2.live(), com.cliffc.aa.HM.HM4.T2.push_update_impl(), com.cliffc.aa.HM.HM4.T2.str(), and com.cliffc.aa.HM.HM4.T2.T2().
_updates
Ary<Syntax> com.cliffc.aa.HM.HM4.T2._updates package
Definition at line 341 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.T2.push_update_impl(), and com.cliffc.aa.HM.HM4.T2.union().
CDUPS
final HashMap<T2,T2> com.cliffc.aa.HM.HM4.T2.CDUPS = new HashMap<>() static private
Definition at line 551 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.T2._cycle_equals(), and com.cliffc.aa.HM.HM4.T2.cycle_equals().
CNT
int com.cliffc.aa.HM.HM4.T2.CNT =0 static private
Definition at line 326 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.Syntax.more_work_impl(), com.cliffc.aa.HM.HM4.T2.reset(), com.cliffc.aa.HM.HM4.T2.T2(), and com.cliffc.aa.HM.HM4.T2.tnew().
DUPS
final HashMap<Long,T2> com.cliffc.aa.HM.HM4.T2.DUPS = new HashMap<>() static private
Definition at line 430 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.T2._unify(), and com.cliffc.aa.HM.HM4.T2.unify().
UPDATE_VISIT
final VBitSet com.cliffc.aa.HM.HM4.T2.UPDATE_VISIT = new VBitSet() static package
Definition at line 581 of file HM4.java.
Referenced by com.cliffc.aa.HM.HM4.T2.push_update(), and com.cliffc.aa.HM.HM4.T2.push_update_impl().
The documentation for this class was generated from the following file:
HM4.java