aa: com.cliffc.aa.HM.HM9.Field Class Reference
com.cliffc.aa.HM.HM9.Field Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Field (String id, Syntax str)
void add_hm_work (Worklist work)
void add_val_work (Syntax child, Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
Type val (Worklist work)
Package Attributes
Type _flow
T2 _hmt
final String _id
VStack _nongen
Syntax _par
final Syntax _rec
Detailed Description
Definition at line 869 of file HM9.java.
Constructor & Destructor Documentation
Field()
com.cliffc.aa.HM.HM9.Field.Field (String id, Syntax str) package
Definition at line 872 of file HM9.java.
 { _id=id; _rec =str; }
References com.cliffc.aa.HM.HM9.Field._id, com.cliffc.aa.HM.HM9.Field._rec, com.cliffc.aa.HM.HM9.id(), and com.cliffc.aa.HM.HM9.Field.str().
Member Function Documentation
add_hm_work()
void com.cliffc.aa.HM.HM9.Field.add_hm_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 895 of file HM9.java.
{
       work.push(_par);
       work.push(_rec);
       _rec.add_hm_work(work);
     }
References com.cliffc.aa.HM.HM9.Syntax._par, com.cliffc.aa.HM.HM9.Field._rec, com.cliffc.aa.HM.HM9.Syntax.add_hm_work(), and com.cliffc.aa.HM.HM9.Worklist.push().
add_val_work()
void com.cliffc.aa.HM.HM9.Syntax.add_val_work (Syntax child, Worklist work) package inherited
Reimplemented in com.cliffc.aa.HM.HM9.PrimSyn, com.cliffc.aa.HM.HM9.Apply, com.cliffc.aa.HM.HM9.Let, and com.cliffc.aa.HM.HM9.Lambda.
Definition at line 346 of file HM9.java.
 {} // Add affected neighbors to worklist
Referenced by com.cliffc.aa.HM.HM9.hm().
debug_find()
T2 com.cliffc.aa.HM.HM9.Syntax.debug_find () package inherited
Definition at line 329 of file HM9.java.
 { return _hmt.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM9.Syntax._hmt, and com.cliffc.aa.HM.HM9.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM9.hm().
find()
T2 com.cliffc.aa.HM.HM9.Syntax.find () package inherited
Definition at line 325 of file HM9.java.
               {                 // U-F find
       T2 t = _hmt.find();
       return t== _hmt ? t : (_hmt =t);
     }
References com.cliffc.aa.HM.HM9.Syntax._hmt, and com.cliffc.aa.HM.HM9.T2.find().
Referenced by com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_val_work(), com.cliffc.aa.HM.HM9.Let.add_val_work(), com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Ident.hm(), com.cliffc.aa.HM.HM9.Lambda.hm(), com.cliffc.aa.HM.HM9.Apply.hm(), com.cliffc.aa.HM.HM9.Root.hm(), com.cliffc.aa.HM.HM9.Struct.hm(), com.cliffc.aa.HM.HM9.Field.hm(), com.cliffc.aa.HM.HM9.PrimSyn.hm(), com.cliffc.aa.HM.HM9.If.hm(), com.cliffc.aa.HM.HM9.NotNil.hm(), com.cliffc.aa.HM.HM9.Apply.is_if_nil(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.NotNil.prep_tree(), com.cliffc.aa.HM.HM9.Apply.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
hm()
boolean com.cliffc.aa.HM.HM9.Field.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 876 of file HM9.java.
{
       if( find().is_err() ) return false; // Already an error; no progress
       T2 rec = _rec.find();
       if( (rec._alias!=null && rec._alias.test(0)) || rec._flow == Type.XNIL )
         return find().unify(T2.make_err("May be nil when loading field "+_id),work);
       int idx = rec._ids==null ? -1 : Util.find(rec._ids,_id);
       if( idx!= -1 )            // Unify against a pre-existing field
         return rec.args(idx).unify(find(), work);
       // The remaining cases all make progress and return true
       if( work==null ) return true;
       if( rec.is_err() ) return find().unify(rec,work);
       // Not a struct or no field, force it to be one
       if( rec.is_struct() && rec._open ) // Effectively unify with an extended struct.
         return rec.add_fld(_id,find(),work);
       if( rec.is_leaf() )
         return T2.make_struct(BitsAlias.EMPTY,new String[]{_id}, new T2[]{find().push_update(rec._deps)},true).unify(rec.push_update(this), work);
       return find().unify(rec.miss_field(_id),work);
     }
References com.cliffc.aa.HM.HM9.T2._alias, com.cliffc.aa.HM.HM9.T2._flow, com.cliffc.aa.HM.HM9.Field._id, com.cliffc.aa.HM.HM9.T2._ids, com.cliffc.aa.HM.HM9.T2._open, com.cliffc.aa.HM.HM9.Field._rec, com.cliffc.aa.HM.HM9.T2.add_fld(), com.cliffc.aa.HM.HM9.T2.args(), com.cliffc.aa.type.BitsAlias.EMPTY, com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.HM.HM9.T2.is_err(), com.cliffc.aa.HM.HM9.T2.is_leaf(), com.cliffc.aa.HM.HM9.T2.is_struct(), com.cliffc.aa.HM.HM9.T2.make_err(), com.cliffc.aa.HM.HM9.T2.make_struct(), com.cliffc.aa.HM.HM9.T2.miss_field(), com.cliffc.aa.HM.HM9.T2.push_update(), com.cliffc.aa.type.Bits< B extends Bits< B >.test(), com.cliffc.aa.HM.HM9.T2.unify(), and com.cliffc.aa.type.Type< T extends Type< T >.XNIL.
more_work()
boolean com.cliffc.aa.HM.HM9.Field.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 919 of file HM9.java.
{
       if( !more_work_impl(work) ) return false;
       return _rec.more_work(work);
     }
References com.cliffc.aa.HM.HM9.Field._rec, com.cliffc.aa.HM.HM9.Syntax.more_work(), and com.cliffc.aa.HM.HM9.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM9.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 362 of file HM9.java.
{
       if( work.has(this) ) return true;
       if( DO_HM && hm(null) )   // Any more HM work?
         return false;           // Found HM work not on worklist
       if( DO_GCP && val(null)!=_flow )
         return false;           // Found GCP work not on worklist
       return true;
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.DO_GCP, com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.Worklist.has(), com.cliffc.aa.HM.HM9.Syntax.hm(), and com.cliffc.aa.HM.HM9.Syntax.val().
Referenced by com.cliffc.aa.HM.HM9.Con.more_work(), com.cliffc.aa.HM.HM9.Ident.more_work(), com.cliffc.aa.HM.HM9.Lambda.more_work(), com.cliffc.aa.HM.HM9.Let.more_work(), com.cliffc.aa.HM.HM9.Apply.more_work(), com.cliffc.aa.HM.HM9.Struct.more_work(), com.cliffc.aa.HM.HM9.Field.more_work(), and com.cliffc.aa.HM.HM9.PrimSyn.more_work().
p()
String com.cliffc.aa.HM.HM9.Syntax.p () inherited
Definition at line 374 of file HM9.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM9.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM9.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 375 of file HM9.java.
{
       _hmt.get_dups(dups);
       VBitSet visit = new VBitSet();
       p1(sb.i());
       if( DO_HM  ) _hmt .str(sb.p(", HM="), visit,dups);
       if( DO_GCP ) _flow.str(sb.p(", CCP="),visit.clr(),null,false);
       sb.nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.util.VBitSet.clr(), com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM9.DO_GCP, com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM9.Syntax.p1(), com.cliffc.aa.HM.HM9.Syntax.p2(), com.cliffc.aa.type.Type< T extends Type< T >.str(), and com.cliffc.aa.HM.HM9.T2.str().
Referenced by com.cliffc.aa.HM.HM9.Syntax.p(), com.cliffc.aa.HM.HM9.Lambda.p2(), com.cliffc.aa.HM.HM9.Let.p2(), com.cliffc.aa.HM.HM9.Apply.p2(), com.cliffc.aa.HM.HM9.Struct.p2(), and com.cliffc.aa.HM.HM9.Field.p2().
p1()
SB com.cliffc.aa.HM.HM9.Field.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 874 of file HM9.java.
 { return sb.p(".").p(_id); }
References com.cliffc.aa.HM.HM9.Field._id, and com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM9.Field.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 875 of file HM9.java.
 { return _rec.p0(sb,dups); }
References com.cliffc.aa.HM.HM9.Field._rec, and com.cliffc.aa.HM.HM9.Syntax.p0().
prep_lookup_deps()
void com.cliffc.aa.HM.HM9.Syntax.prep_lookup_deps (Ident id) package inherited
Reimplemented in com.cliffc.aa.HM.HM9.Let, and com.cliffc.aa.HM.HM9.Lambda.
Definition at line 358 of file HM9.java.
 {}
prep_tree()
int com.cliffc.aa.HM.HM9.Field.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 915 of file HM9.java.
{
       prep_tree_impl(par, nongen, work, T2.make_leaf());
       return _rec.prep_tree(this,nongen,work)+1;
     }
References com.cliffc.aa.HM.HM9.Field._rec, com.cliffc.aa.HM.HM9.T2.make_leaf(), com.cliffc.aa.HM.HM9.Syntax.prep_tree(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
prep_tree_impl()
final void com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 351 of file HM9.java.
{
       _par = par;
       _hmt = t;
       _flow= Type.XSCALAR;
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.HM.HM9.Syntax._nongen, com.cliffc.aa.HM.HM9.Syntax._par, com.cliffc.aa.HM.HM9.Worklist.push(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Referenced by com.cliffc.aa.HM.HM9.Con.prep_tree(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), com.cliffc.aa.HM.HM9.Lambda.prep_tree(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Apply.prep_tree(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.Field.prep_tree(), and com.cliffc.aa.HM.HM9.PrimSyn.prep_tree().
str()
SB com.cliffc.aa.HM.HM9.Field.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 873 of file HM9.java.
 { return _rec.str(sb.p(".").p(_id).p(' ')); }
References com.cliffc.aa.HM.HM9.Field._id, com.cliffc.aa.HM.HM9.Field._rec, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM9.Syntax.str().
Referenced by com.cliffc.aa.HM.HM9.Field.Field().
toString()
final String com.cliffc.aa.HM.HM9.Syntax.toString () inherited
Definition at line 371 of file HM9.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM9.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.HM.HM9.Lambda.p1().
val()
Type com.cliffc.aa.HM.HM9.Field.val (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 900 of file HM9.java.
{
       Type trec = _rec._flow;
       if( trec.above_center() ) return Type.XSCALAR;
       if( trec instanceof TypeMemPtr ) {
         TypeMemPtr tmp = (TypeMemPtr)trec;
         if( tmp._obj instanceof TypeStruct ) {
           TypeStruct tstr = (TypeStruct)tmp._obj;
           int idx = tstr.fld_find(_id);
           if( idx!=-1 ) return tstr.at(idx); // Field type
         }
         if( tmp._obj.above_center() ) return Type.XSCALAR;
       }
       // TODO: Need an error type here
       return Type.SCALAR;
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Field._id, com.cliffc.aa.type.TypeMemPtr._obj, com.cliffc.aa.HM.HM9.Field._rec, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.above_center(), com.cliffc.aa.type.Type< T extends Type< T >.above_center(), com.cliffc.aa.type.TypeStruct.at(), com.cliffc.aa.type.TypeStruct.fld_find(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Member Data Documentation
_flow
Type com.cliffc.aa.HM.HM9.Syntax._flow package inherited
Definition at line 332 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Lambda.apply(), com.cliffc.aa.HM.HM9.Pair1.apply(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Pair.apply(), com.cliffc.aa.HM.HM9.Triple.apply(), com.cliffc.aa.HM.HM9.If.apply(), com.cliffc.aa.HM.HM9.EQ.apply(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM9.IsEmpty.apply(), com.cliffc.aa.HM.HM9.NotNil.apply(), com.cliffc.aa.HM.HM9.Mul.apply(), com.cliffc.aa.HM.HM9.Dec.apply(), com.cliffc.aa.HM.HM9.Str.apply(), com.cliffc.aa.HM.HM9.Factor.apply(), com.cliffc.aa.HM.HM9.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Lambda.Lambda(), com.cliffc.aa.HM.HM9.Syntax.more_work_impl(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM9.Ident.val(), com.cliffc.aa.HM.HM9.Let.val(), com.cliffc.aa.HM.HM9.Apply.val(), com.cliffc.aa.HM.HM9.Root.val(), com.cliffc.aa.HM.HM9.Struct.val(), com.cliffc.aa.HM.HM9.Field.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
_hmt
T2 com.cliffc.aa.HM.HM9.Syntax._hmt package inherited
Definition at line 324 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Syntax.debug_find(), com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.PrimSyn.prep_tree(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM9.PrimSyn.PrimSyn().
_id
final String com.cliffc.aa.HM.HM9.Field._id package
Definition at line 870 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Field.Field(), com.cliffc.aa.HM.HM9.Field.hm(), com.cliffc.aa.HM.HM9.Field.p1(), com.cliffc.aa.HM.HM9.Field.str(), and com.cliffc.aa.HM.HM9.Field.val().
_nongen
VStack com.cliffc.aa.HM.HM9.Syntax._nongen package inherited
Definition at line 323 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.add_hm_work(), com.cliffc.aa.HM.HM9.Ident.hm(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM9.Syntax._par package inherited
Definition at line 322 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.Apply.add_hm_work(), com.cliffc.aa.HM.HM9.Struct.add_hm_work(), com.cliffc.aa.HM.HM9.Field.add_hm_work(), com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
_rec
final Syntax com.cliffc.aa.HM.HM9.Field._rec package
Definition at line 871 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Field.add_hm_work(), com.cliffc.aa.HM.HM9.Field.Field(), com.cliffc.aa.HM.HM9.Field.hm(), com.cliffc.aa.HM.HM9.Field.more_work(), com.cliffc.aa.HM.HM9.Field.p2(), com.cliffc.aa.HM.HM9.Field.prep_tree(), com.cliffc.aa.HM.HM9.Field.str(), and com.cliffc.aa.HM.HM9.Field.val().
The documentation for this class was generated from the following file:
HM9.java