aa: com.cliffc.aa.HM.HM9.Apply Class Reference
com.cliffc.aa.HM.HM9.Apply Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Apply (Syntax fun, Syntax... args)
void add_hm_work (Worklist work)
void add_val_work (Syntax child, Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
Type val (Worklist work)
Package Attributes
final Syntax[] _args
Type _flow
final Syntax _fun
T2 _hmt
VStack _nongen
Syntax _par
Private Member Functions
T2 is_if_nil ()
Static Private Attributes
static final HashMap< T2, Type > T2MAP = new HashMap<>()
static final NonBlockingHashMapLong< String > WDUPS = new NonBlockingHashMapLong<>()
Detailed Description
Definition at line 581 of file HM9.java.
Constructor & Destructor Documentation
Apply()
com.cliffc.aa.HM.HM9.Apply.Apply (Syntax fun, Syntax... args) package
Definition at line 584 of file HM9.java.
 { _fun = fun; _args = args; }
References com.cliffc.aa.HM.HM9.Apply._args, and com.cliffc.aa.HM.HM9.Apply._fun.
Member Function Documentation
add_hm_work()
void com.cliffc.aa.HM.HM9.Apply.add_hm_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Reimplemented in com.cliffc.aa.HM.HM9.Root.
Definition at line 649 of file HM9.java.
{
       work.push(_par);
       for( Syntax arg : _args ) work.push(arg);
     }
References com.cliffc.aa.HM.HM9.Apply._args, com.cliffc.aa.HM.HM9.Syntax._par, and com.cliffc.aa.HM.HM9.Worklist.push().
add_val_work()
void com.cliffc.aa.HM.HM9.Apply.add_val_work (Syntax child, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 687 of file HM9.java.
{
       // If function changes type, recompute self
       if( child==_fun ) work.push(this);
       // If an argument changes type, adjust the lambda arg types
       Type flow = _fun._flow;
       if( flow.above_center() ) return;
       if( !(flow instanceof TypeFunPtr) ) return;
       // Meet the actuals over the formals.
       for( int fidx : ((TypeFunPtr)flow)._fidxs ) {
         Lambda fun = Lambda.FUNS.get(fidx);
         if( fun!=null ) {
           fun.find().push_update(this); // Discovered as call-site; if the Lambda changes the Apply needs to be revisited.
           for( int i=0; i<fun._types.length; i++ ) {
             Type formal = fun._types[i];
             Type actual = this instanceof Root ? Root.widen(fun.targ(i)) : _args[i]._flow;
             Type rez = formal.meet(actual);
             if( formal != rez ) {
               fun._types[i] = rez;
               work.addAll(fun.targ(i)._deps);
               work.push(fun._body);
               if( i==0 && fun instanceof If ) work.push(fun); // Specifically If might need more unification
             }
           }
         }
       }
     }
References com.cliffc.aa.HM.HM9.Apply._args, com.cliffc.aa.HM.HM9.Lambda._body, com.cliffc.aa.HM.HM9.T2._deps, com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Apply._fun, com.cliffc.aa.HM.HM9.Lambda._types, com.cliffc.aa.type.Type< T extends Type< T >.above_center(), com.cliffc.aa.HM.HM9.Worklist.addAll(), com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.HM.HM9.Lambda.FUNS, com.cliffc.aa.type.Type< T extends Type< T >.meet(), com.cliffc.aa.HM.HM9.Worklist.push(), com.cliffc.aa.HM.HM9.T2.push_update(), com.cliffc.aa.HM.HM9.Lambda.targ(), and com.cliffc.aa.HM.HM9.Root.widen().
Referenced by com.cliffc.aa.HM.HM9.Root.val().
debug_find()
T2 com.cliffc.aa.HM.HM9.Syntax.debug_find () package inherited
Definition at line 329 of file HM9.java.
 { return _hmt.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM9.Syntax._hmt, and com.cliffc.aa.HM.HM9.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM9.hm().
find()
T2 com.cliffc.aa.HM.HM9.Syntax.find () package inherited
Definition at line 325 of file HM9.java.
               {                 // U-F find
       T2 t = _hmt.find();
       return t== _hmt ? t : (_hmt =t);
     }
References com.cliffc.aa.HM.HM9.Syntax._hmt, and com.cliffc.aa.HM.HM9.T2.find().
Referenced by com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_val_work(), com.cliffc.aa.HM.HM9.Let.add_val_work(), com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Ident.hm(), com.cliffc.aa.HM.HM9.Lambda.hm(), com.cliffc.aa.HM.HM9.Apply.hm(), com.cliffc.aa.HM.HM9.Root.hm(), com.cliffc.aa.HM.HM9.Struct.hm(), com.cliffc.aa.HM.HM9.Field.hm(), com.cliffc.aa.HM.HM9.PrimSyn.hm(), com.cliffc.aa.HM.HM9.If.hm(), com.cliffc.aa.HM.HM9.NotNil.hm(), com.cliffc.aa.HM.HM9.Apply.is_if_nil(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.NotNil.prep_tree(), com.cliffc.aa.HM.HM9.Apply.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
hm()
boolean com.cliffc.aa.HM.HM9.Apply.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Reimplemented in com.cliffc.aa.HM.HM9.Root.
Definition at line 600 of file HM9.java.
{
       boolean progress = false;
       // Discover not-nil in the trivial case of directly using the 'if'
       // primitive against a T2.is_struct().  Will not work if 'if' is some
       // more hidden or complex function (e.q. '&&' or '||') or the predicate
       // implies not-null on some other struct.
       T2 str = is_if_nil();
       if( str!=null && str.is_struct() ) {
         BitsAlias aliases = str._alias;
         if( !aliases.test(0) ) {
           str._alias = str._alias.meet_nil(); // Nil is allowed on the tested value
           progress = true;
           if( work==null ) return true;
           work.addAll(str._deps);
         }
       }
       // Progress if:
       //   _fun is not a function
       //   any arg-pair-unifies make progress
       //   this-unify-_fun.return makes progress
       T2 tfun = _fun.find();
       if( !tfun.is_fun() ) {    // Not a function, so progress
         if( tfun.is_err() ) return find().unify(tfun,work);
         if( work==null ) return true; // Will-progress & just-testing
         T2[] targs = new T2[_args.length+1];
         for( int i=0; i<_args.length; i++ )
           targs[i] = _args[i].find();
         targs[_args.length] = find(); // Return
         T2 nfun = T2.make_fun(BitsFun.FULL,targs);
         progress = tfun.unify(nfun,work);
         return tfun.find().is_err() ? find().unify(tfun.find(),work) : progress;
       }
       if( tfun._args.length != _args.length+1 )
         progress |= T2.make_err("Mismatched argument lengths").unify(find(),work);
       // Check for progress amongst arg pairs
       for( int i=0; i<_args.length; i++ ) {
         progress |= tfun.args(i).unify(_args[i].find(),work);
         if( progress && work==null ) return true; // Will-progress & just-testing early exit
         if( (tfun=tfun.find()).is_err() ) return find().unify(tfun,work);
       }
       // Check for progress on the return
       progress |= tfun.args(_args.length).unify(find(),work);
       if( (tfun=tfun.find()).is_err() ) return find().unify(tfun,work);
       return progress;
     }
References com.cliffc.aa.HM.HM9.Apply._args, com.cliffc.aa.HM.HM9.T2._args, com.cliffc.aa.HM.HM9.Apply._fun, com.cliffc.aa.HM.HM9.Worklist.addAll(), com.cliffc.aa.HM.HM9.T2.args(), com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.HM.HM9.T2.find(), com.cliffc.aa.type.BitsFun.FULL, com.cliffc.aa.HM.HM9.T2.is_err(), com.cliffc.aa.HM.HM9.T2.is_fun(), com.cliffc.aa.HM.HM9.Apply.is_if_nil(), com.cliffc.aa.HM.HM9.T2.make_err(), com.cliffc.aa.HM.HM9.T2.make_fun(), com.cliffc.aa.HM.HM9.Apply.str(), com.cliffc.aa.type.Bits< B extends Bits< B >.test(), and com.cliffc.aa.HM.HM9.T2.unify().
is_if_nil()
T2 com.cliffc.aa.HM.HM9.Apply.is_if_nil () private
Definition at line 729 of file HM9.java.
{
       return _fun instanceof If && _args[0] instanceof Ident ? _args[0].find() : null;
     }
References com.cliffc.aa.HM.HM9.Apply._args, com.cliffc.aa.HM.HM9.Apply._fun, and com.cliffc.aa.HM.HM9.Syntax.find().
Referenced by com.cliffc.aa.HM.HM9.Apply.hm(), and com.cliffc.aa.HM.HM9.Apply.prep_tree().
more_work()
boolean com.cliffc.aa.HM.HM9.Apply.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 722 of file HM9.java.
{
       if( !more_work_impl(work) ) return false;
       if( !_fun.more_work(work) ) return false;
       for( Syntax arg : _args ) if( !arg.more_work(work) ) return false;
       return true;
     }
References com.cliffc.aa.HM.HM9.Apply._args, com.cliffc.aa.HM.HM9.Apply._fun, com.cliffc.aa.HM.HM9.Syntax.more_work(), and com.cliffc.aa.HM.HM9.Syntax.more_work_impl().
Referenced by com.cliffc.aa.HM.HM9.hm().
more_work_impl()
final boolean com.cliffc.aa.HM.HM9.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 362 of file HM9.java.
{
       if( work.has(this) ) return true;
       if( DO_HM && hm(null) )   // Any more HM work?
         return false;           // Found HM work not on worklist
       if( DO_GCP && val(null)!=_flow )
         return false;           // Found GCP work not on worklist
       return true;
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.DO_GCP, com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.Worklist.has(), com.cliffc.aa.HM.HM9.Syntax.hm(), and com.cliffc.aa.HM.HM9.Syntax.val().
Referenced by com.cliffc.aa.HM.HM9.Con.more_work(), com.cliffc.aa.HM.HM9.Ident.more_work(), com.cliffc.aa.HM.HM9.Lambda.more_work(), com.cliffc.aa.HM.HM9.Let.more_work(), com.cliffc.aa.HM.HM9.Apply.more_work(), com.cliffc.aa.HM.HM9.Struct.more_work(), com.cliffc.aa.HM.HM9.Field.more_work(), and com.cliffc.aa.HM.HM9.PrimSyn.more_work().
p()
String com.cliffc.aa.HM.HM9.Syntax.p () inherited
Definition at line 374 of file HM9.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM9.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM9.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 375 of file HM9.java.
{
       _hmt.get_dups(dups);
       VBitSet visit = new VBitSet();
       p1(sb.i());
       if( DO_HM  ) _hmt .str(sb.p(", HM="), visit,dups);
       if( DO_GCP ) _flow.str(sb.p(", CCP="),visit.clr(),null,false);
       sb.nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.util.VBitSet.clr(), com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM9.DO_GCP, com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM9.Syntax.p1(), com.cliffc.aa.HM.HM9.Syntax.p2(), com.cliffc.aa.type.Type< T extends Type< T >.str(), and com.cliffc.aa.HM.HM9.T2.str().
Referenced by com.cliffc.aa.HM.HM9.Syntax.p(), com.cliffc.aa.HM.HM9.Lambda.p2(), com.cliffc.aa.HM.HM9.Let.p2(), com.cliffc.aa.HM.HM9.Apply.p2(), com.cliffc.aa.HM.HM9.Struct.p2(), and com.cliffc.aa.HM.HM9.Field.p2().
p1()
SB com.cliffc.aa.HM.HM9.Apply.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 591 of file HM9.java.
 { return sb.p("(...)"); }
References com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM9.Apply.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 592 of file HM9.java.
{
       _fun.p0(sb,dups);
       for( Syntax arg : _args ) arg.p0(sb,dups);
       return sb;
     }
References com.cliffc.aa.HM.HM9.Apply._args, com.cliffc.aa.HM.HM9.Apply._fun, and com.cliffc.aa.HM.HM9.Syntax.p0().
prep_lookup_deps()
void com.cliffc.aa.HM.HM9.Syntax.prep_lookup_deps (Ident id) package inherited
Reimplemented in com.cliffc.aa.HM.HM9.Let, and com.cliffc.aa.HM.HM9.Lambda.
Definition at line 358 of file HM9.java.
 {}
prep_tree()
int com.cliffc.aa.HM.HM9.Apply.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 714 of file HM9.java.
{
       prep_tree_impl(par,nongen,work,T2.make_leaf());
       int cnt = 1+_fun.prep_tree(this,nongen,work);
       for( Syntax arg : _args ) cnt += arg.prep_tree(this,nongen,work);
       T2 str = is_if_nil();
       if( str!=null ) str.push_update(this);
       return cnt;
     }
References com.cliffc.aa.HM.HM9.Apply._args, com.cliffc.aa.HM.HM9.Apply._fun, com.cliffc.aa.HM.HM9.Apply.is_if_nil(), com.cliffc.aa.HM.HM9.T2.make_leaf(), com.cliffc.aa.HM.HM9.Syntax.prep_tree(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM9.Apply.str().
Referenced by com.cliffc.aa.HM.HM9.hm().
prep_tree_impl()
final void com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 351 of file HM9.java.
{
       _par = par;
       _hmt = t;
       _flow= Type.XSCALAR;
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.HM.HM9.Syntax._nongen, com.cliffc.aa.HM.HM9.Syntax._par, com.cliffc.aa.HM.HM9.Worklist.push(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Referenced by com.cliffc.aa.HM.HM9.Con.prep_tree(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), com.cliffc.aa.HM.HM9.Lambda.prep_tree(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Apply.prep_tree(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.Field.prep_tree(), and com.cliffc.aa.HM.HM9.PrimSyn.prep_tree().
str()
SB com.cliffc.aa.HM.HM9.Apply.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Reimplemented in com.cliffc.aa.HM.HM9.Root.
Definition at line 585 of file HM9.java.
{
       _fun.str(sb.p("(")).p(" ");
       for( Syntax arg : _args )
         arg.str(sb).p(" ");
       return sb.unchar().p(")");
     }
References com.cliffc.aa.HM.HM9.Apply._args, com.cliffc.aa.HM.HM9.Apply._fun, com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM9.Syntax.str(), and com.cliffc.aa.util.SB.unchar().
Referenced by com.cliffc.aa.HM.HM9.Apply.hm(), and com.cliffc.aa.HM.HM9.Apply.prep_tree().
toString()
final String com.cliffc.aa.HM.HM9.Syntax.toString () inherited
Definition at line 371 of file HM9.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM9.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.HM.HM9.Lambda.p1().
val()
Type com.cliffc.aa.HM.HM9.Apply.val (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Reimplemented in com.cliffc.aa.HM.HM9.Root.
Definition at line 655 of file HM9.java.
{
       Type flow = _fun._flow;
       if( flow.above_center() ) return Type.XSCALAR;
       if( !(flow instanceof TypeFunPtr) ) return Type.SCALAR;
       TypeFunPtr tfp = (TypeFunPtr)flow;
       // Have some functions, meet over their returns.
       Type rez = Type.XSCALAR;
       if( tfp._fidxs==BitsFun.FULL ) rez = Type.SCALAR;
       else
         for( int fidx : tfp._fidxs )
           rez = rez.meet(Lambda.FUNS.get(fidx).apply(_args));
       if( rez==Type.XSCALAR ) // Fast path cutout, no improvement possible
         return rez;
       // Attempt to lift the result, based on HM types.  Walk the input HM type
       // and CCP flow type in parallel and create a mapping.  Then walk the
       // output HM type and CCP flow type in parallel, and join output CCP
       // types with the matching input CCP type.
       if( DO_HM ) {
         T2MAP.clear();  WDUPS.clear();
         // Walk the inputs, building a mapping
         _fun.find().walk_types_in(_fun._flow);
         for( Syntax arg : _args )
           { WDUPS.clear(); arg.find().walk_types_in(arg._flow); }
         // Walk the outputs, building an improved result
         Type rez2 = find().walk_types_out(rez);
         rez = rez2.join(rez);   // Lift result
         if( !_flow.isa(rez) )
           rez = _flow; // TODO: Cheaty force monotonic
       }
       return rez;
     }
References com.cliffc.aa.HM.HM9.Apply._args, com.cliffc.aa.type.TypeFunPtr._fidxs, com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Apply._fun, com.cliffc.aa.type.Type< T extends Type< T >.above_center(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.clear(), com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.type.BitsFun.FULL, com.cliffc.aa.HM.HM9.Lambda.FUNS, com.cliffc.aa.type.Type< T extends Type< T >.isa(), com.cliffc.aa.type.Type< T extends Type< T >.join(), com.cliffc.aa.type.Type< T extends Type< T >.meet(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, com.cliffc.aa.HM.HM9.Apply.T2MAP, com.cliffc.aa.HM.HM9.T2.walk_types_in(), com.cliffc.aa.HM.HM9.T2.walk_types_out(), com.cliffc.aa.HM.HM9.Apply.WDUPS, and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Member Data Documentation
_args
final Syntax [] com.cliffc.aa.HM.HM9.Apply._args package
Definition at line 583 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Apply.add_hm_work(), com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Apply.Apply(), com.cliffc.aa.HM.HM9.Apply.hm(), com.cliffc.aa.HM.HM9.Apply.is_if_nil(), com.cliffc.aa.HM.HM9.Apply.more_work(), com.cliffc.aa.HM.HM9.Apply.p2(), com.cliffc.aa.HM.HM9.Apply.prep_tree(), com.cliffc.aa.HM.HM9.Apply.str(), and com.cliffc.aa.HM.HM9.Apply.val().
_flow
Type com.cliffc.aa.HM.HM9.Syntax._flow package inherited
Definition at line 332 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Lambda.apply(), com.cliffc.aa.HM.HM9.Pair1.apply(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Pair.apply(), com.cliffc.aa.HM.HM9.Triple.apply(), com.cliffc.aa.HM.HM9.If.apply(), com.cliffc.aa.HM.HM9.EQ.apply(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM9.IsEmpty.apply(), com.cliffc.aa.HM.HM9.NotNil.apply(), com.cliffc.aa.HM.HM9.Mul.apply(), com.cliffc.aa.HM.HM9.Dec.apply(), com.cliffc.aa.HM.HM9.Str.apply(), com.cliffc.aa.HM.HM9.Factor.apply(), com.cliffc.aa.HM.HM9.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Lambda.Lambda(), com.cliffc.aa.HM.HM9.Syntax.more_work_impl(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM9.Ident.val(), com.cliffc.aa.HM.HM9.Let.val(), com.cliffc.aa.HM.HM9.Apply.val(), com.cliffc.aa.HM.HM9.Root.val(), com.cliffc.aa.HM.HM9.Struct.val(), com.cliffc.aa.HM.HM9.Field.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
_fun
final Syntax com.cliffc.aa.HM.HM9.Apply._fun package
Definition at line 582 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Apply.Apply(), com.cliffc.aa.HM.HM9.Apply.hm(), com.cliffc.aa.HM.HM9.Root.hm(), com.cliffc.aa.HM.HM9.Apply.is_if_nil(), com.cliffc.aa.HM.HM9.Apply.more_work(), com.cliffc.aa.HM.HM9.Apply.p2(), com.cliffc.aa.HM.HM9.Apply.prep_tree(), com.cliffc.aa.HM.HM9.Apply.str(), com.cliffc.aa.HM.HM9.Root.str(), com.cliffc.aa.HM.HM9.Apply.val(), and com.cliffc.aa.HM.HM9.Root.val().
_hmt
T2 com.cliffc.aa.HM.HM9.Syntax._hmt package inherited
Definition at line 324 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Syntax.debug_find(), com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.PrimSyn.prep_tree(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM9.PrimSyn.PrimSyn().
_nongen
VStack com.cliffc.aa.HM.HM9.Syntax._nongen package inherited
Definition at line 323 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.add_hm_work(), com.cliffc.aa.HM.HM9.Ident.hm(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM9.Syntax._par package inherited
Definition at line 322 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.Apply.add_hm_work(), com.cliffc.aa.HM.HM9.Struct.add_hm_work(), com.cliffc.aa.HM.HM9.Field.add_hm_work(), com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
T2MAP
final HashMap<T2,Type> com.cliffc.aa.HM.HM9.Apply.T2MAP = new HashMap<>() static private
Definition at line 653 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.T2.fput(), com.cliffc.aa.HM.HM9.Apply.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_out().
WDUPS
final NonBlockingHashMapLong<String> com.cliffc.aa.HM.HM9.Apply.WDUPS = new NonBlockingHashMapLong<>() static private
Definition at line 654 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Apply.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
The documentation for this class was generated from the following file:
HM9.java