aa: com.cliffc.aa.HM.HM1.Oper Class Reference
com.cliffc.aa.HM.HM1.Oper Class Reference
Public Member Functions
SB _str (SB sb, VBitSet dups, boolean debug)
String str ()
final String toString ()
Package Functions
Oper (String name, HMType... args)
HMType _fresh (HashSet< HMVar > nongen, HashMap< HMType, HMType > vars)
HMType find ()
HMType fresh (HashSet< HMVar > nongen)
boolean is_top ()
boolean occurs_in (HashSet< HMVar >nongen)
boolean occurs_in (HMType[] args)
boolean occurs_in_type (HMType v)
HMType union (HMType that)
Static Package Functions
static Oper fun (HMType... args)
Package Attributes
final HMType[] _args
final String _name
HMType _u
Detailed Description
Definition at line 248 of file HM1.java.
Constructor & Destructor Documentation
Oper()
com.cliffc.aa.HM.HM1.Oper.Oper (String name, HMType... args) package
Definition at line 251 of file HM1.java.
 { _name=name; _args=args; }
References com.cliffc.aa.HM.HM1.Oper._args, and com.cliffc.aa.HM.HM1.Oper._name.
Referenced by com.cliffc.aa.HM.HM1.Oper.fun(), and com.cliffc.aa.HM.HM1.Oper.union().
Member Function Documentation
_fresh()
HMType com.cliffc.aa.HM.HM1.HMType._fresh (HashSet< HMVar > nongen, HashMap< HMType, HMType > vars) package inherited
Definition at line 171 of file HM1.java.
{
       HMType t2 = find();
       if( t2 instanceof HMVar ) {
         return t2.occurs_in(nongen) //
           ? t2                      // Keep same var
           : vars.computeIfAbsent(t2, e -> new HMVar(((HMVar)t2)._t));
       } else {
         Oper op = (Oper)t2;
         HMType[] args = new HMType[op._args.length];
         for( int i=0; i<args.length; i++ )
           args[i] = op._args[i]._fresh(nongen,vars);
         return new Oper(op._name,args);
       }
     }
References com.cliffc.aa.HM.HM1.Oper._args, com.cliffc.aa.HM.HM1.HMType._fresh(), com.cliffc.aa.HM.HM1.Oper._name, com.cliffc.aa.HM.HM1.HMType.find(), and com.cliffc.aa.HM.HM1.HMType.occurs_in().
Referenced by com.cliffc.aa.HM.HM1.HMType._fresh(), and com.cliffc.aa.HM.HM1.HMType.fresh().
_str()
SB com.cliffc.aa.HM.HM1.Oper._str (SB sb, VBitSet dups, boolean debug)
Reimplemented from com.cliffc.aa.HM.HM1.HMType.
Definition at line 253 of file HM1.java.
{
       if( _name.equals("->") ) {
         sb.p("{ ");
         for( int i=0; i<_args.length-1; i++ )
           _args[i]._str(sb,dups,debug).p(" ");
         sb.p("-> ");
         _args[_args.length-1]._str(sb,dups,debug);
         return sb.p(" }");
       }
       sb.p(_name).p('(');
       for( HMType t : _args )
         t._str(sb,dups,debug).p(',');
       return sb.unchar().p(')');
     }
References com.cliffc.aa.HM.HM1.Oper._args, com.cliffc.aa.HM.HM1.Oper._name, com.cliffc.aa.HM.HM1.HMType._str(), com.cliffc.aa.util.SB.p(), and com.cliffc.aa.util.SB.unchar().
find()
HMType com.cliffc.aa.HM.HM1.Oper.find () package
Reimplemented from com.cliffc.aa.HM.HM1.HMType.
Definition at line 268 of file HM1.java.
 { return this; }
fresh()
HMType com.cliffc.aa.HM.HM1.HMType.fresh (HashSet< HMVar > nongen) package inherited
Definition at line 167 of file HM1.java.
{
       HashMap<HMType,HMType> vars = new HashMap<>();
       return _fresh(nongen,vars);
     }
References com.cliffc.aa.HM.HM1.HMType._fresh().
Referenced by com.cliffc.aa.HM.HM1.Ident.hm().
fun()
static Oper com.cliffc.aa.HM.HM1.Oper.fun (HMType... args) static package
Definition at line 252 of file HM1.java.
 { return new Oper("->",args); }
References com.cliffc.aa.HM.HM1.Oper.Oper().
Referenced by com.cliffc.aa.HM.HM1.HM(), com.cliffc.aa.HM.HM1.Lambda.hm(), com.cliffc.aa.HM.HM1.Lambda2.hm(), and com.cliffc.aa.HM.HM1.Apply.hm().
is_top()
boolean com.cliffc.aa.HM.HM1.HMType.is_top () package inherited
Definition at line 165 of file HM1.java.
 { return _u==null; }
References com.cliffc.aa.HM.HM1.HMType._u.
Referenced by com.cliffc.aa.HM.HM1.HMType.occurs_in_type(), and com.cliffc.aa.HM.HM1.HMVar.type().
occurs_in() [1/2]
boolean com.cliffc.aa.HM.HM1.HMType.occurs_in (HashSet< HMVar > nongen) package inherited
Definition at line 186 of file HM1.java.
{
       for( HMVar x : nongen ) if( occurs_in_type(x) ) return true;
       return false;
     }
References com.cliffc.aa.HM.HM1.HMType.occurs_in_type().
Referenced by com.cliffc.aa.HM.HM1.HMType._fresh(), and com.cliffc.aa.HM.HM1.HMType.occurs_in_type().
occurs_in() [2/2]
boolean com.cliffc.aa.HM.HM1.HMType.occurs_in (HMType[] args) package inherited
Definition at line 190 of file HM1.java.
{
       for( HMType x : args ) if( occurs_in_type(x) ) return true;
       return false;
     }
References com.cliffc.aa.HM.HM1.HMType.occurs_in_type().
occurs_in_type()
boolean com.cliffc.aa.HM.HM1.HMType.occurs_in_type (HMType v) package inherited
Definition at line 194 of file HM1.java.
{
       assert is_top();
       HMType y = v.find();
       if( y==this )
         return true;
       if( y instanceof Oper )
         return occurs_in(((Oper)y)._args);
       return false;
     }
References com.cliffc.aa.HM.HM1.HMType.find(), com.cliffc.aa.HM.HM1.HMType.is_top(), and com.cliffc.aa.HM.HM1.HMType.occurs_in().
Referenced by com.cliffc.aa.HM.HM1.HMType.occurs_in(), and com.cliffc.aa.HM.HM1.HMVar.union().
str()
String com.cliffc.aa.HM.HM1.HMType.str () inherited
Definition at line 163 of file HM1.java.
 { return _str(new SB(),new VBitSet(),false).toString(); }
References com.cliffc.aa.HM.HM1.HMType._str(), and com.cliffc.aa.util.SB.toString().
toString()
final String com.cliffc.aa.HM.HM1.HMType.toString () inherited
Definition at line 162 of file HM1.java.
 { return _str(new SB(),new VBitSet(),true).toString(); }
References com.cliffc.aa.HM.HM1.HMType._str(), and com.cliffc.aa.util.SB.toString().
union()
HMType com.cliffc.aa.HM.HM1.Oper.union (HMType that) package
Reimplemented from com.cliffc.aa.HM.HM1.HMType.
Definition at line 269 of file HM1.java.
{
       if( !(that instanceof Oper) ) return that.union(this);
       Oper op2 = (Oper)that;
       if( !_name.equals(op2._name) ||
           _args.length != op2._args.length )
         throw new RuntimeException("Cannot unify "+this+" and "+that);
       for( int i=0; i<_args.length; i++ )
         _args[i].union(op2._args[i]);
       return this;
     }
References com.cliffc.aa.HM.HM1.Oper._args, com.cliffc.aa.HM.HM1.Oper._name, com.cliffc.aa.HM.HM1.Oper.Oper(), and com.cliffc.aa.HM.HM1.HMType.union().
Member Data Documentation
_args
final HMType [] com.cliffc.aa.HM.HM1.Oper._args package
Definition at line 250 of file HM1.java.
Referenced by com.cliffc.aa.HM.HM1.HMType._fresh(), com.cliffc.aa.HM.HM1.Oper._str(), com.cliffc.aa.HM.HM1.Oper.Oper(), and com.cliffc.aa.HM.HM1.Oper.union().
_name
final String com.cliffc.aa.HM.HM1.Oper._name package
Definition at line 249 of file HM1.java.
Referenced by com.cliffc.aa.HM.HM1.HMType._fresh(), com.cliffc.aa.HM.HM1.Oper._str(), com.cliffc.aa.HM.HM1.Oper.Oper(), and com.cliffc.aa.HM.HM1.Oper.union().
_u
HMType com.cliffc.aa.HM.HM1.HMType._u package inherited
Definition at line 159 of file HM1.java.
Referenced by com.cliffc.aa.HM.HM1.HMVar._str(), com.cliffc.aa.HM.HM1.HMVar.find(), com.cliffc.aa.HM.HM1.HMType.is_top(), and com.cliffc.aa.HM.HM1.HMVar.union().
The documentation for this class was generated from the following file:
HM1.java