aa: com.cliffc.aa.util.AryInt Class Reference
com.cliffc.aa.util.AryInt Class Reference
Public Member Functions
AryInt ()
AryInt (int[] es)
AryInt (int[] es, int len)
AryInt addAll (Collection<? extends Integer > c)
AryInt addAll (int[] es)
int[] asAry ()
int at (int i)
int atX (int i)
int binary_search (int e)
void clear ()
Remove all elements.
int del (int i)
Fast, constant-time, element removal.
boolean equals (Object o)
int find (int e)
Find the first matching element using ==, or -1 if none.
int hashCode ()
void insert (int i, int e)
Slow, linear-time, element insert.
boolean isEmpty ()
int last ()
int len ()
AryInt map_update (IntUnaryOperator f)
int pop ()
AryInt push (int e)
Add element in amortized constant time.
int remove (int i)
Slow, linear-time, element removal.
int set (int i, int e)
AryInt set_as (int e)
AryInt set_len (int len)
int setX (int i, int e)
void sort_update ()
Sorts in-place.
String toString ()
Public Attributes
int[] _es
int _len
Private Member Functions
void range_check (int i)
Detailed Description
Definition at line 8 of file AryInt.java.
Constructor & Destructor Documentation
AryInt() [1/3]
com.cliffc.aa.util.AryInt.AryInt (int[] es)
Definition at line 11 of file AryInt.java.
 { this(es,es.length); }
AryInt() [2/3]
com.cliffc.aa.util.AryInt.AryInt (int[] es, int len)
Definition at line 12 of file AryInt.java.
 { _es=es; _len=len; }
References com.cliffc.aa.util.AryInt._es, com.cliffc.aa.util.AryInt._len, and com.cliffc.aa.util.AryInt.len().
AryInt() [3/3]
com.cliffc.aa.util.AryInt.AryInt ()
Definition at line 13 of file AryInt.java.
 { this(new int[1],0); }
Referenced by com.cliffc.aa.util.AryInt.equals().
Member Function Documentation
addAll() [1/2]
AryInt com.cliffc.aa.util.AryInt.addAll (Collection<? extends Integer > c)
Parameters
c Collection to be added
Definition at line 109 of file AryInt.java.
 { for( int e : c ) push(e); return this; }
References com.cliffc.aa.util.AryInt.push().
addAll() [2/2]
AryInt com.cliffc.aa.util.AryInt.addAll (int[] es)
Parameters
es Array to be added
Definition at line 112 of file AryInt.java.
{
     if( es.length==0 ) return this;
     while( _len+es.length > _es.length ) _es = Arrays.copyOf(_es,_es.length<<1);
     System.arraycopy(es,0,_es,_len,es.length);
     _len += es.length;
     return this;
   }
References com.cliffc.aa.util.AryInt._es, and com.cliffc.aa.util.AryInt._len.
asAry()
int [] com.cliffc.aa.util.AryInt.asAry ()
Returns
compact array version, using the internal base array where possible.
Definition at line 123 of file AryInt.java.
 { return _len==_es.length ? _es : Arrays.copyOf(_es,_len); }
References com.cliffc.aa.util.AryInt._es, and com.cliffc.aa.util.AryInt._len.
at()
int com.cliffc.aa.util.AryInt.at (int i)
Parameters
i element index
Returns
element being returned; throws if OOB
Definition at line 21 of file AryInt.java.
{
     range_check(i);
     return _es[i];
   }
References com.cliffc.aa.util.AryInt._es, and com.cliffc.aa.util.AryInt.range_check().
Referenced by com.cliffc.aa.Parse.errLocMsg().
atX()
int com.cliffc.aa.util.AryInt.atX (int i)
Parameters
i element index
Returns
element being returned, or 0 if OOB
Definition at line 27 of file AryInt.java.
{
     return i < _len ? _es[i] : 0;
   }
References com.cliffc.aa.util.AryInt._es, and com.cliffc.aa.util.AryInt._len.
Referenced by com.cliffc.aa.util.IBitSet._clr(), com.cliffc.aa.util.IBitSet._set(), com.cliffc.aa.util.IBitSet._tst(), com.cliffc.aa.util.IBitSet.or(), com.cliffc.aa.util.IBitSet.subtract(), and com.cliffc.aa.util.IBitSet.xd().
binary_search()
int com.cliffc.aa.util.AryInt.binary_search (int e)
Definition at line 150 of file AryInt.java.
{
     int lo=0, hi=_len-1;
     while( lo <= hi ) {
       int mid = (hi + lo) >>> 1; // midpoint, rounded down
       int mval = _es[mid];
       if( e==mval ) {
         // If dups, get to the first.
         while( mid>0 && e==_es[mid-1] ) mid--;
         return mid;
       }
       if( e >mval ) lo = mid+1;
       else          hi = mid-1;
     }
     return lo;
   }
References com.cliffc.aa.util.AryInt._es, and com.cliffc.aa.util.AryInt._len.
Referenced by com.cliffc.aa.Parse.apply(), and com.cliffc.aa.Parse.errLocMsg().
clear()
void com.cliffc.aa.util.AryInt.clear ()
Remove all elements.
Definition at line 84 of file AryInt.java.
 { Arrays.fill(_es,0,_len,0); _len=0; }
References com.cliffc.aa.util.AryInt._es, and com.cliffc.aa.util.AryInt._len.
Referenced by com.cliffc.aa.util.IBitSet.clear().
del()
int com.cliffc.aa.util.AryInt.del (int i)
Fast, constant-time, element removal.
Does not preserve order
Parameters
i element to be removed
Returns
element removed
Definition at line 66 of file AryInt.java.
{
     range_check(i);
     int tmp = _es[i];
     _es[i]=_es[--_len];
     return tmp;
   }
References com.cliffc.aa.util.AryInt._es, com.cliffc.aa.util.AryInt._len, and com.cliffc.aa.util.AryInt.range_check().
equals()
boolean com.cliffc.aa.util.AryInt.equals (Object o)
Definition at line 169 of file AryInt.java.
{
     if( this==o ) return true;
     if( !(o instanceof AryInt) ) return false;
     AryInt ary = (AryInt)o;
     if( _len != ary._len ) return false;
     if( _es == ary._es ) return true;
     for( int i=0; i<_len; i++ )
       if( _es[i] != ary._es[i] )
         return false;
     return true;
   }
References com.cliffc.aa.util.AryInt._es, com.cliffc.aa.util.AryInt._len, and com.cliffc.aa.util.AryInt.AryInt().
find()
int com.cliffc.aa.util.AryInt.find (int e)
Find the first matching element using ==, or -1 if none.
Note that most del calls shuffle the list, so the first element might be random.
Parameters
e intlement to find
Returns
index of first matching element, or -1 if none
Definition at line 131 of file AryInt.java.
{
     for( int i=0; i<_len; i++ )  if( _es[i]==e )  return i;
     return -1;
   }
References com.cliffc.aa.util.AryInt._es, and com.cliffc.aa.util.AryInt._len.
hashCode()
int com.cliffc.aa.util.AryInt.hashCode ()
Definition at line 180 of file AryInt.java.
{
     int sum=_len;
     for( int i=0; i<_len; i++ )
       sum += _es[i];
     return sum;
   }
References com.cliffc.aa.util.AryInt._es, and com.cliffc.aa.util.AryInt._len.
insert()
void com.cliffc.aa.util.AryInt.insert (int i, int e)
Slow, linear-time, element insert.
Preserves order.
Parameters
i index to insert at, between 0 and _len inclusive.
e intlement to insert
Definition at line 55 of file AryInt.java.
{
     if( i < 0 || i>_len )
       throw new ArrayIndexOutOfBoundsException(""+i+" >= "+_len);
     if( _len >= _es.length ) _es = Arrays.copyOf(_es,Math.max(1,_es.length<<1));
     System.arraycopy(_es,i,_es,i+1,(_len++)-i);
     _es[i] = e;
   }
References com.cliffc.aa.util.AryInt._es, and com.cliffc.aa.util.AryInt._len.
isEmpty()
boolean com.cliffc.aa.util.AryInt.isEmpty ()
Returns
list is empty
Definition at line 16 of file AryInt.java.
 { return _len==0; }
References com.cliffc.aa.util.AryInt._len.
Referenced by com.cliffc.aa.type.TypeMem.all_reaching_aliases().
last()
int com.cliffc.aa.util.AryInt.last ()
Returns
last element
Definition at line 31 of file AryInt.java.
                      {
     range_check(0);
     return _es[_len-1];
   }
References com.cliffc.aa.util.AryInt._es, com.cliffc.aa.util.AryInt._len, and com.cliffc.aa.util.AryInt.range_check().
Referenced by com.cliffc.aa.util.IBitSet._clr(), com.cliffc.aa.util.IBitSet.max(), and com.cliffc.aa.Parse.skipWS().
len()
int com.cliffc.aa.util.AryInt.len ()
Returns
active list length
Definition at line 18 of file AryInt.java.
 { return _len; }
References com.cliffc.aa.util.AryInt._len.
Referenced by com.cliffc.aa.util.AryInt.AryInt(), and com.cliffc.aa.util.AryInt.set_len().
map_update()
AryInt com.cliffc.aa.util.AryInt.map_update (IntUnaryOperator f)
Definition at line 120 of file AryInt.java.
 { for( int i = 0; i<_len; i++ ) _es[i] = f.applyAsInt(_es[i]); return this; }
References com.cliffc.aa.util.AryInt._es, and com.cliffc.aa.util.AryInt._len.
pop()
int com.cliffc.aa.util.AryInt.pop ()
Returns
remove and return last element
Definition at line 37 of file AryInt.java.
                     {
     range_check(0);
     return _es[--_len];
   }
References com.cliffc.aa.util.AryInt._es, com.cliffc.aa.util.AryInt._len, and com.cliffc.aa.util.AryInt.range_check().
Referenced by com.cliffc.aa.util.IBitSet._clr(), and com.cliffc.aa.type.TypeMem.all_reaching_aliases().
push()
AryInt com.cliffc.aa.util.AryInt.push (int e)
Add element in amortized constant time.
Parameters
e element to add at end of list
Returns
'this' for flow-coding
Definition at line 45 of file AryInt.java.
{
     if( _len >= _es.length ) _es = Arrays.copyOf(_es,Math.max(1,_es.length<<1));
     _es[_len++] = e;
     return this;
   }
References com.cliffc.aa.util.AryInt._es, and com.cliffc.aa.util.AryInt._len.
Referenced by com.cliffc.aa.util.AryInt.addAll(), com.cliffc.aa.type.TypeMem.all_reaching_aliases(), com.cliffc.aa.Parse.Parse(), and com.cliffc.aa.Parse.skipWS().
range_check()
void com.cliffc.aa.util.AryInt.range_check (int i) private
Definition at line 143 of file AryInt.java.
{
     if( i < 0 || i>=_len )
       throw new ArrayIndexOutOfBoundsException(""+i+" >= "+_len);
   }
References com.cliffc.aa.util.AryInt._len.
Referenced by com.cliffc.aa.util.AryInt.at(), com.cliffc.aa.util.AryInt.del(), com.cliffc.aa.util.AryInt.last(), com.cliffc.aa.util.AryInt.pop(), com.cliffc.aa.util.AryInt.remove(), and com.cliffc.aa.util.AryInt.set().
remove()
int com.cliffc.aa.util.AryInt.remove (int i)
Slow, linear-time, element removal.
Preserves order.
Parameters
i element to be removed
Returns
element removed
Definition at line 76 of file AryInt.java.
{
     range_check(i);
     int e = _es[i];
     System.arraycopy(_es,i+1,_es,i,(--_len)-i);
     return e;
   }
References com.cliffc.aa.util.AryInt._es, com.cliffc.aa.util.AryInt._len, and com.cliffc.aa.util.AryInt.range_check().
set()
int com.cliffc.aa.util.AryInt.set (int i, int e)
Definition at line 93 of file AryInt.java.
{
     range_check(i);
     return (_es[i] = e);
   }
References com.cliffc.aa.util.AryInt._es, and com.cliffc.aa.util.AryInt.range_check().
set_as()
AryInt com.cliffc.aa.util.AryInt.set_as (int e)
Definition at line 98 of file AryInt.java.
 { _es[0] = e; _len=1; return this; }
References com.cliffc.aa.util.AryInt._es, and com.cliffc.aa.util.AryInt._len.
set_len()
AryInt com.cliffc.aa.util.AryInt.set_len (int len)
Definition at line 99 of file AryInt.java.
{
     if( len > _len )
       while( len>= _es.length ) _es = Arrays.copyOf(_es,_es.length<<1);
     _len = len;
     while( _es.length > (len<<1) ) // Shrink if hugely too large
       _es = Arrays.copyOf(_es,_es.length>>1);
     return this;
   }
References com.cliffc.aa.util.AryInt._es, com.cliffc.aa.util.AryInt._len, and com.cliffc.aa.util.AryInt.len().
setX()
int com.cliffc.aa.util.AryInt.setX (int i, int e)
Definition at line 87 of file AryInt.java.
{
     while( i>= _es.length ) _es = Arrays.copyOf(_es,_es.length<<1);
     if( i >= _len ) _len = i+1;
     return (_es[i] = e);
   }
References com.cliffc.aa.util.AryInt._es, and com.cliffc.aa.util.AryInt._len.
Referenced by com.cliffc.aa.util.IBitSet._clr(), com.cliffc.aa.util.IBitSet._set(), com.cliffc.aa.util.IBitSet.or(), and com.cliffc.aa.util.IBitSet.subtract().
sort_update()
void com.cliffc.aa.util.AryInt.sort_update ()
Sorts in-place.
Definition at line 126 of file AryInt.java.
 { Arrays.sort(_es, 0, _len);  }
References com.cliffc.aa.util.AryInt._es, and com.cliffc.aa.util.AryInt._len.
toString()
String com.cliffc.aa.util.AryInt.toString ()
Definition at line 136 of file AryInt.java.
{
     SB sb = new SB().p('[');
     for( int i=0; i<_len; i++ )
       sb.p(_es[i]).p(',');
     return sb.unchar().p(']').toString();
   }
References com.cliffc.aa.util.AryInt._es, com.cliffc.aa.util.AryInt._len, com.cliffc.aa.util.SB.p(), com.cliffc.aa.util.SB.toString(), and com.cliffc.aa.util.SB.unchar().
Member Data Documentation
_es
int [] com.cliffc.aa.util.AryInt._es
Definition at line 9 of file AryInt.java.
Referenced by com.cliffc.aa.util.AryInt.addAll(), com.cliffc.aa.util.AryInt.AryInt(), com.cliffc.aa.util.AryInt.asAry(), com.cliffc.aa.util.AryInt.at(), com.cliffc.aa.util.AryInt.atX(), com.cliffc.aa.util.AryInt.binary_search(), com.cliffc.aa.util.IBitSet.bitCount(), com.cliffc.aa.util.AryInt.clear(), com.cliffc.aa.util.AryInt.del(), com.cliffc.aa.util.AryInt.equals(), com.cliffc.aa.util.AryInt.find(), com.cliffc.aa.util.AryInt.hashCode(), com.cliffc.aa.util.IBitSet.Iter.hasNext(), com.cliffc.aa.util.AryInt.insert(), com.cliffc.aa.util.AryInt.last(), com.cliffc.aa.util.AryInt.map_update(), com.cliffc.aa.util.AryInt.pop(), com.cliffc.aa.util.AryInt.push(), com.cliffc.aa.util.AryInt.remove(), com.cliffc.aa.util.AryInt.set(), com.cliffc.aa.util.AryInt.set_as(), com.cliffc.aa.util.AryInt.set_len(), com.cliffc.aa.util.AryInt.setX(), com.cliffc.aa.util.AryInt.sort_update(), com.cliffc.aa.util.AryInt.toString(), and com.cliffc.aa.util.IBitSet.wd().
_len
int com.cliffc.aa.util.AryInt._len
Definition at line 10 of file AryInt.java.
Referenced by com.cliffc.aa.util.IBitSet._clr(), com.cliffc.aa.util.AryInt.addAll(), com.cliffc.aa.util.AryInt.AryInt(), com.cliffc.aa.util.AryInt.asAry(), com.cliffc.aa.util.AryInt.atX(), com.cliffc.aa.util.AryInt.binary_search(), com.cliffc.aa.util.IBitSet.bitCount(), com.cliffc.aa.util.AryInt.clear(), com.cliffc.aa.util.AryInt.del(), com.cliffc.aa.util.IBitSet.disjoint(), com.cliffc.aa.util.AryInt.equals(), com.cliffc.aa.Parse.errLocMsg(), com.cliffc.aa.util.AryInt.find(), com.cliffc.aa.util.AryInt.hashCode(), com.cliffc.aa.util.IBitSet.Iter.hasNext(), com.cliffc.aa.util.AryInt.insert(), com.cliffc.aa.util.IBitSet.is_empty(), com.cliffc.aa.util.AryInt.isEmpty(), com.cliffc.aa.util.AryInt.last(), com.cliffc.aa.util.AryInt.len(), com.cliffc.aa.util.AryInt.map_update(), com.cliffc.aa.util.IBitSet.max(), com.cliffc.aa.util.IBitSet.Iter.next(), com.cliffc.aa.util.IBitSet.or(), com.cliffc.aa.util.AryInt.pop(), com.cliffc.aa.util.AryInt.push(), com.cliffc.aa.util.AryInt.range_check(), com.cliffc.aa.util.AryInt.remove(), com.cliffc.aa.util.AryInt.set_as(), com.cliffc.aa.util.AryInt.set_len(), com.cliffc.aa.util.AryInt.setX(), com.cliffc.aa.util.AryInt.sort_update(), com.cliffc.aa.util.IBitSet.subsetsX(), com.cliffc.aa.util.IBitSet.subtract(), com.cliffc.aa.util.IBitSet.toString(), and com.cliffc.aa.util.AryInt.toString().
The documentation for this class was generated from the following file:
AryInt.java