aa: com.cliffc.aa.HM.HM6.VStack Class Reference
com.cliffc.aa.HM.HM6.VStack Class Reference
Classes
class Iter
Public Member Functions
Iterator< T2 > iterator ()
String toString ()
Package Functions
VStack (VStack par, T2 nongen)
SB str (SB sb)
Package Attributes
final T2 _nongen
final VStack _par
Detailed Description
Definition at line 190 of file HM6.java.
Constructor & Destructor Documentation
VStack()
com.cliffc.aa.HM.HM6.VStack.VStack (VStack par, T2 nongen) package
Definition at line 193 of file HM6.java.
 { _par=par; _nongen=nongen; }
References com.cliffc.aa.HM.HM6.VStack._nongen, and com.cliffc.aa.HM.HM6.VStack._par.
Member Function Documentation
iterator()
Iterator<T2> com.cliffc.aa.HM.HM6.VStack.iterator ()
Definition at line 200 of file HM6.java.
 { return new Iter(); }
str()
SB com.cliffc.aa.HM.HM6.VStack.str (SB sb) package
Definition at line 195 of file HM6.java.
                   {
       _nongen.str(sb,new VBitSet(),new VBitSet());
       if( _par!=null ) _par.str(sb.p(" >> "));
       return sb;
     }
References com.cliffc.aa.HM.HM6.VStack._nongen, com.cliffc.aa.HM.HM6.VStack._par, com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM6.VStack.str(), and com.cliffc.aa.HM.HM6.T2.str().
Referenced by com.cliffc.aa.HM.HM6.VStack.str(), and com.cliffc.aa.HM.HM6.VStack.toString().
toString()
String com.cliffc.aa.HM.HM6.VStack.toString ()
Definition at line 194 of file HM6.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM6.VStack.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_nongen
final T2 com.cliffc.aa.HM.HM6.VStack._nongen package
Definition at line 192 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.VStack.Iter.next(), com.cliffc.aa.HM.HM6.VStack.str(), and com.cliffc.aa.HM.HM6.VStack.VStack().
_par
final VStack com.cliffc.aa.HM.HM6.VStack._par package
Definition at line 191 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.VStack.Iter.next(), com.cliffc.aa.HM.HM6.VStack.str(), and com.cliffc.aa.HM.HM6.VStack.VStack().
The documentation for this class was generated from the following file:
HM6.java