aa: com.cliffc.aa.HM.HM3.Syntax Class Reference
com.cliffc.aa.HM.HM3.Syntax Class Reference abstract
Protected Member Functions
final void add_work (Worklist work)
Package Functions
final void add_neighbors (Worklist work)
final boolean all_kids_ready ()
boolean check_progress (Worklist work)
abstract void get_ids (VStack vstk, Worklist work)
abstract HMType hm (Worklist work)
abstract boolean progress ()
Package Attributes
HMType _hm
Syntax[] _kids
Syntax _par
Detailed Description
Definition at line 115 of file HM3.java.
Member Function Documentation
add_neighbors()
final void com.cliffc.aa.HM.HM3.Syntax.add_neighbors (Worklist work) package
Definition at line 128 of file HM3.java.
{
       if( _par!=null ) _par.add_work(work);
       if( _kids!=null )
         for( Syntax kid : _kids )
           kid.add_work(work);
     }
References com.cliffc.aa.HM.HM3.Syntax._kids, com.cliffc.aa.HM.HM3.Syntax._par, and com.cliffc.aa.HM.HM3.Syntax.add_work().
Referenced by com.cliffc.aa.HM.HM3.hm().
add_work()
final void com.cliffc.aa.HM.HM3.Syntax.add_work (Worklist work) protected
Definition at line 126 of file HM3.java.
 {  if( all_kids_ready() ) work.push(this);  }
References com.cliffc.aa.HM.HM3.Syntax.all_kids_ready(), and com.cliffc.aa.HM.HM3.Worklist.push().
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.HM.HM3.Con.get_ids(), and com.cliffc.aa.HM.HM3.Ident.get_ids().
all_kids_ready()
final boolean com.cliffc.aa.HM.HM3.Syntax.all_kids_ready () package
Definition at line 135 of file HM3.java.
{
       if( _kids==null ) return true;
       for( Syntax kid : _kids ) if( kid._hm==null ) return false;
       return true;
     }
References com.cliffc.aa.HM.HM3.Syntax._kids.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_work(), and com.cliffc.aa.HM.HM3.Syntax.check_progress().
check_progress()
boolean com.cliffc.aa.HM.HM3.Syntax.check_progress (Worklist work) package
Definition at line 144 of file HM3.java.
{
       if( all_kids_ready() ) // If kids are not ready, then cannot compute hm() so not on worklist
         if( _hm==null || progress() ) // Progress is possible
           if( !work.has(this) )       // Not on worklist?
             return false;             // Fails check
       if( _kids!=null )               // For all kids
         for( Syntax kid : _kids )
           if( !kid.check_progress(work) ) // Recursively check nodes that can make progress on worklist
             return false;
       return true;
     }
References com.cliffc.aa.HM.HM3.Syntax._hm, com.cliffc.aa.HM.HM3.Syntax._kids, com.cliffc.aa.HM.HM3.Syntax.all_kids_ready(), com.cliffc.aa.HM.HM3.Worklist.has(), and com.cliffc.aa.HM.HM3.Syntax.progress().
Referenced by com.cliffc.aa.HM.HM3.hm().
get_ids()
abstract void com.cliffc.aa.HM.HM3.Syntax.get_ids (VStack vstk, Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM3.Apply, com.cliffc.aa.HM.HM3.Let, com.cliffc.aa.HM.HM3.Lambda, com.cliffc.aa.HM.HM3.Ident, and com.cliffc.aa.HM.HM3.Con.
Referenced by com.cliffc.aa.HM.HM3.Lambda.get_ids(), com.cliffc.aa.HM.HM3.Let.get_ids(), com.cliffc.aa.HM.HM3.Apply.get_ids(), and com.cliffc.aa.HM.HM3.hm().
hm()
abstract HMType com.cliffc.aa.HM.HM3.Syntax.hm (Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM3.Apply, com.cliffc.aa.HM.HM3.Let, com.cliffc.aa.HM.HM3.Lambda, com.cliffc.aa.HM.HM3.Ident, and com.cliffc.aa.HM.HM3.Con.
Referenced by com.cliffc.aa.HM.HM3.hm().
progress()
abstract boolean com.cliffc.aa.HM.HM3.Syntax.progress () abstract package
Reimplemented in com.cliffc.aa.HM.HM3.Apply, com.cliffc.aa.HM.HM3.Let, com.cliffc.aa.HM.HM3.Lambda, com.cliffc.aa.HM.HM3.Ident, and com.cliffc.aa.HM.HM3.Con.
Referenced by com.cliffc.aa.HM.HM3.Syntax.check_progress().
Member Data Documentation
_hm
HMType com.cliffc.aa.HM.HM3.Syntax._hm package
Definition at line 118 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Syntax.check_progress(), com.cliffc.aa.HM.HM3.hm(), com.cliffc.aa.HM.HM3.Con.hm(), com.cliffc.aa.HM.HM3.Ident.hm(), com.cliffc.aa.HM.HM3.Lambda.hm(), com.cliffc.aa.HM.HM3.Let.hm(), com.cliffc.aa.HM.HM3.Apply.hm(), com.cliffc.aa.HM.HM3.Lambda.progress(), com.cliffc.aa.HM.HM3.Let.progress(), and com.cliffc.aa.HM.HM3.Apply.progress().
_kids
Syntax [] com.cliffc.aa.HM.HM3.Syntax._kids package
Definition at line 117 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.HM.HM3.Syntax.all_kids_ready(), com.cliffc.aa.HM.HM3.Apply.Apply(), com.cliffc.aa.HM.HM3.Apply.arg(), com.cliffc.aa.HM.HM3.Lambda.body(), com.cliffc.aa.HM.HM3.Let.body(), com.cliffc.aa.HM.HM3.Syntax.check_progress(), com.cliffc.aa.HM.HM3.Apply.fun(), com.cliffc.aa.HM.HM3.Lambda.Lambda(), com.cliffc.aa.HM.HM3.Let.Let(), and com.cliffc.aa.HM.HM3.Let.use().
_par
Syntax com.cliffc.aa.HM.HM3.Syntax._par package
Definition at line 116 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.HM.HM3.Apply.Apply(), com.cliffc.aa.HM.HM3.Lambda.Lambda(), and com.cliffc.aa.HM.HM3.Let.Let().
The documentation for this class was generated from the following file:
HM3.java