aa: com.cliffc.aa.HM.HM8.Struct Class Reference
com.cliffc.aa.HM.HM8.Struct Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Struct (String[] ids, Syntax[] flds)
void add_work (Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
T2 lookup (String name)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
T2 post ()
T2 pre ()
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
Package Attributes
final BitsAlias _alias
final Syntax[] _flds
final String[] _ids
VStack _nongen
Syntax _par
T2 _post
T2 _pre
T2 _t
Detailed Description
Definition at line 576 of file HM8.java.
Constructor & Destructor Documentation
Struct()
com.cliffc.aa.HM.HM8.Struct.Struct (String[] ids, Syntax[] flds) package
Definition at line 580 of file HM8.java.
 { _ids=ids; _flds=flds; _alias = BitsAlias.make0(BitsAlias.new_alias(BitsAlias.REC)); }
References com.cliffc.aa.HM.HM8.Struct._alias, com.cliffc.aa.HM.HM8.Struct._flds, com.cliffc.aa.HM.HM8.Struct._ids, com.cliffc.aa.type.BitsAlias.make0(), com.cliffc.aa.type.BitsAlias.new_alias(), and com.cliffc.aa.type.BitsAlias.REC.
Member Function Documentation
add_work()
void com.cliffc.aa.HM.HM8.Struct.add_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 644 of file HM8.java.
{
       work.push(_par);
       for( Syntax fld : _flds ) work.push(fld);
     }
References com.cliffc.aa.HM.HM8.Struct._flds, com.cliffc.aa.HM.HM8.Syntax._par, and com.cliffc.aa.HM.HM8.Worklist.push().
debug_find()
T2 com.cliffc.aa.HM.HM8.Syntax.debug_find () package inherited
Definition at line 249 of file HM8.java.
 { return _t.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM8.Syntax._t, and com.cliffc.aa.HM.HM8.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM8.hm().
find()
T2 com.cliffc.aa.HM.HM8.Syntax.find () package inherited
Definition at line 245 of file HM8.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._t, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.T2._occurs_in(), com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Ident.hm(), com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.HM.HM8.Apply.is_if_nil(), and com.cliffc.aa.HM.HM8.Struct.prep_tree().
hm()
boolean com.cliffc.aa.HM.HM8.Struct.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 596 of file HM8.java.
{
       // U/F link pre/post memory with fields' memories
       boolean progress = false, must_alloc=false;
       progress |= pre().unify(_flds[0].pre(),work);
       if( work==null && progress ) return true;
       for( int i=1; i<_flds.length; i++ ) {
         progress |= _flds[i-1].post().unify(_flds[i].pre(),work);
         if( work==null && progress ) return true;
       }
       progress |= _flds[_flds.length-1].post().unify(post(),work);
       if( work==null && progress ) return true;
       // Force result to be a struct with at least these fields.
       // Do not allocate a T2 unless we need to pick up fields.
       T2 rec = find();
       for( String id : _ids )
         if( Util.find(rec._ids, id) == -1 )
           { must_alloc = true; break; }
       if( must_alloc ) {              // Must allocate.
         if( work==null ) return true; // Will progress
         T2[] t2s = new T2[_ids.length];
         for( int i=0; i<_ids.length; i++ )
           t2s[i] = _flds[i].find();
         T2.make_struct(_ids,_alias,t2s).unify(rec,work);
         rec=find();
         progress = true;
       }
       // Extra fields are unified with ALL since they are not created here.
       for( int i=0; i<rec._ids.length; i++ ) {
         if( Util.find(_ids,rec._ids[i])== -1 && rec.args(i)._con!=Type.ALL && !rec.args(i).is_err() ) {
           if( work==null ) return true;
           progress |= T2.make_base(Type.ALL).unify(rec.args(i),work);
         }
       }
       // Unify existing fields.  Ignore extras on either side.
       for( int i=0; i<_ids.length; i++ ) {
         int idx = Util.find(rec._ids,_ids[i]);
         if( idx!= -1 ) progress |= rec.args(idx).unify(_flds[i].find(),work);
         if( work==null && progress ) return true;
       }
       // Unify struct at alias into post-memory
       progress |= _post.unify_rec(_alias.getbit(),rec,work);
       return progress;
     }
References com.cliffc.aa.HM.HM8.Struct._alias, com.cliffc.aa.HM.HM8.T2._con, com.cliffc.aa.HM.HM8.Struct._flds, com.cliffc.aa.HM.HM8.Struct._ids, com.cliffc.aa.HM.HM8.T2._ids, com.cliffc.aa.HM.HM8.Syntax._post, com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.HM.HM8.T2.args(), com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM8.Syntax.find(), com.cliffc.aa.type.Bits< B extends Bits< B >.getbit(), com.cliffc.aa.HM.HM8.T2.is_err(), com.cliffc.aa.HM.HM8.T2.make_base(), com.cliffc.aa.HM.HM8.T2.make_struct(), com.cliffc.aa.HM.HM8.Syntax.post(), com.cliffc.aa.HM.HM8.Syntax.pre(), com.cliffc.aa.HM.HM8.T2.unify(), and com.cliffc.aa.HM.HM8.T2.unify_rec().
lookup()
T2 com.cliffc.aa.HM.HM8.Struct.lookup (String name) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 643 of file HM8.java.
 { return _par==null ? null : _par.lookup(name); }
References com.cliffc.aa.HM.HM8.Syntax._par, and com.cliffc.aa.HM.HM8.Syntax.lookup().
more_work()
boolean com.cliffc.aa.HM.HM8.Struct.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 660 of file HM8.java.
{
       if( !more_work_impl(work) ) return false;
       for( Syntax fld : _flds )
         if( !fld.more_work(work) )
           return false;
       return true;
     }
References com.cliffc.aa.HM.HM8.Struct._flds, and com.cliffc.aa.HM.HM8.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM8.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 283 of file HM8.java.
{
       boolean no_more_work = work.has(this) || !hm(null); // Either on worklist, or no-progress
       return no_more_work;
     }
References com.cliffc.aa.HM.HM8.Worklist.has(), and com.cliffc.aa.HM.HM8.Syntax.hm().
Referenced by com.cliffc.aa.HM.HM8.Con.more_work(), com.cliffc.aa.HM.HM8.Ident.more_work(), com.cliffc.aa.HM.HM8.Lambda.more_work(), com.cliffc.aa.HM.HM8.Let.more_work(), com.cliffc.aa.HM.HM8.Apply.more_work(), com.cliffc.aa.HM.HM8.Struct.more_work(), and com.cliffc.aa.HM.HM8.Field.more_work().
p()
String com.cliffc.aa.HM.HM8.Syntax.p () inherited
Definition at line 291 of file HM8.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM8.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM8.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 292 of file HM8.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM8.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM8.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM8.Syntax.p1(), com.cliffc.aa.HM.HM8.Syntax.p2(), and com.cliffc.aa.HM.HM8.T2.str().
Referenced by com.cliffc.aa.HM.HM8.Syntax.p(), com.cliffc.aa.HM.HM8.Lambda.p2(), com.cliffc.aa.HM.HM8.Let.p2(), com.cliffc.aa.HM.HM8.Apply.p2(), com.cliffc.aa.HM.HM8.Struct.p2(), and com.cliffc.aa.HM.HM8.Field.p2().
p1()
SB com.cliffc.aa.HM.HM8.Struct.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 590 of file HM8.java.
 { return _alias.str(sb.p('*')).p("@{ ... } "); }
References com.cliffc.aa.HM.HM8.Struct._alias, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.type.Bits< B extends Bits< B >.str().
p2()
SB com.cliffc.aa.HM.HM8.Struct.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 591 of file HM8.java.
{
       for( int i=0; i<_ids.length; i++ )
         _flds[i].p0(sb.p(_ids[i]).p(" = "),dups);
       return sb;
     }
References com.cliffc.aa.HM.HM8.Struct._flds, com.cliffc.aa.HM.HM8.Struct._ids, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM8.Syntax.p0().
post()
T2 com.cliffc.aa.HM.HM8.Syntax.post () package inherited
Definition at line 254 of file HM8.java.
               {
       T2 t = _post.find();
       return t==_post ? t : (_post=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._post, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), and com.cliffc.aa.HM.HM8.Field.hm().
pre()
T2 com.cliffc.aa.HM.HM8.Syntax.pre () package inherited
Definition at line 250 of file HM8.java.
              {
       T2 t = _pre.find();
       return t==_pre ? t : (_pre=t);
     }
References com.cliffc.aa.HM.HM8.Syntax._pre, and com.cliffc.aa.HM.HM8.T2.find().
Referenced by com.cliffc.aa.HM.HM8.Lambda.hm(), com.cliffc.aa.HM.HM8.Let.hm(), com.cliffc.aa.HM.HM8.Apply.hm(), com.cliffc.aa.HM.HM8.Struct.hm(), and com.cliffc.aa.HM.HM8.Field.hm().
prep_lookup_deps()
void com.cliffc.aa.HM.HM8.Struct.prep_lookup_deps (Ident id) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 659 of file HM8.java.
 { }
prep_tree()
int com.cliffc.aa.HM.HM8.Struct.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 648 of file HM8.java.
{
       T2[] t2s = new T2[_ids.length];
       prep_tree_impl(par, nongen, work, T2.make_struct(_ids,_alias,t2s));
       prep_tree_impl(par, nongen, work, T2.make_struct(new String[0],_alias,new T2[0]));
       int cnt = 1;              // One for self
       for( int i=0; i<_flds.length; i++ ) { // Prep all sub-fields
         cnt += _flds[i].prep_tree(this,nongen,work);
         t2s[i] = _flds[i].find();
       }
       return cnt;
     }
References com.cliffc.aa.HM.HM8.Struct._alias, com.cliffc.aa.HM.HM8.Struct._flds, com.cliffc.aa.HM.HM8.Struct._ids, com.cliffc.aa.HM.HM8.Syntax.find(), com.cliffc.aa.HM.HM8.T2.make_struct(), com.cliffc.aa.HM.HM8.Syntax.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
prep_tree_impl()
final void com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 267 of file HM8.java.
{
       _par=par;
       _pre = T2.make_mem();
       _t=t;
       _post = T2.make_mem();
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM8.Syntax._nongen, com.cliffc.aa.HM.HM8.Syntax._par, com.cliffc.aa.HM.HM8.Syntax._post, com.cliffc.aa.HM.HM8.Syntax._pre, com.cliffc.aa.HM.HM8.Syntax._t, com.cliffc.aa.HM.HM8.T2.make_mem(), and com.cliffc.aa.HM.HM8.Worklist.push().
Referenced by com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), com.cliffc.aa.HM.HM8.Lambda.prep_tree(), com.cliffc.aa.HM.HM8.Let.prep_tree(), com.cliffc.aa.HM.HM8.Apply.prep_tree(), com.cliffc.aa.HM.HM8.Struct.prep_tree(), and com.cliffc.aa.HM.HM8.Field.prep_tree().
str()
SB com.cliffc.aa.HM.HM8.Struct.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM8.Syntax.
Definition at line 581 of file HM8.java.
{
       _alias.str(sb.p('*')).p("@{");
       for( int i=0; i<_ids.length; i++ ) {
         sb.p(' ').p(_ids[i]).p(" = ");
         _flds[i].str(sb);
         if( i < _ids.length-1 ) sb.p(',');
       }
       return sb.p("}");
     }
References com.cliffc.aa.HM.HM8.Struct._alias, com.cliffc.aa.HM.HM8.Struct._flds, com.cliffc.aa.HM.HM8.Struct._ids, com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.Bits< B extends Bits< B >.str(), and com.cliffc.aa.HM.HM8.Syntax.str().
toString()
final String com.cliffc.aa.HM.HM8.Syntax.toString () inherited
Definition at line 288 of file HM8.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM8.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_alias
final BitsAlias com.cliffc.aa.HM.HM8.Struct._alias package
Definition at line 577 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Struct.p1(), com.cliffc.aa.HM.HM8.Struct.prep_tree(), com.cliffc.aa.HM.HM8.Struct.str(), and com.cliffc.aa.HM.HM8.Struct.Struct().
_flds
final Syntax [] com.cliffc.aa.HM.HM8.Struct._flds package
Definition at line 579 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Struct.add_work(), com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Struct.more_work(), com.cliffc.aa.HM.HM8.Struct.p2(), com.cliffc.aa.HM.HM8.Struct.prep_tree(), com.cliffc.aa.HM.HM8.Struct.str(), and com.cliffc.aa.HM.HM8.Struct.Struct().
_ids
final String [] com.cliffc.aa.HM.HM8.Struct._ids package
Definition at line 578 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Struct.p2(), com.cliffc.aa.HM.HM8.Struct.prep_tree(), com.cliffc.aa.HM.HM8.Struct.str(), and com.cliffc.aa.HM.HM8.Struct.Struct().
_nongen
VStack com.cliffc.aa.HM.HM8.Syntax._nongen package inherited
Definition at line 241 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Ident.hm(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM8.Syntax._par package inherited
Definition at line 240 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2._occurs_in(), com.cliffc.aa.HM.HM8.Con.add_work(), com.cliffc.aa.HM.HM8.Ident.add_work(), com.cliffc.aa.HM.HM8.Lambda.add_work(), com.cliffc.aa.HM.HM8.Let.add_work(), com.cliffc.aa.HM.HM8.Apply.add_work(), com.cliffc.aa.HM.HM8.Struct.add_work(), com.cliffc.aa.HM.HM8.Field.add_work(), com.cliffc.aa.HM.HM8.Ident.hm(), com.cliffc.aa.HM.HM8.Lambda.lookup(), com.cliffc.aa.HM.HM8.Let.lookup(), com.cliffc.aa.HM.HM8.Apply.lookup(), com.cliffc.aa.HM.HM8.Struct.lookup(), com.cliffc.aa.HM.HM8.Field.lookup(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_post
T2 com.cliffc.aa.HM.HM8.Syntax._post package inherited
Definition at line 244 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Struct.hm(), com.cliffc.aa.HM.HM8.Syntax.post(), com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_pre
T2 com.cliffc.aa.HM.HM8.Syntax._pre package inherited
Definition at line 242 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Syntax.pre(), com.cliffc.aa.HM.HM8.Con.prep_tree(), com.cliffc.aa.HM.HM8.Ident.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM8.Syntax._t package inherited
Definition at line 243 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Syntax.debug_find(), com.cliffc.aa.HM.HM8.Syntax.find(), com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM8.Syntax.p0(), com.cliffc.aa.HM.HM8.Let.prep_tree(), and com.cliffc.aa.HM.HM8.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM8.java