aa: com.cliffc.aa.HM.HM8 Class Reference
com.cliffc.aa.HM.HM8 Class Reference
Classes
class Apply
class Con
class Field
class Ident
class Lambda
class Let
class Struct
class Syntax
class T2
class VStack
class Worklist
Public Member Functions
String toString ()
Static Public Member Functions
static Syntax hm (String sprog)
Static Package Functions
[static initializer]
static Syntax parse (String s)
static void reset ()
static Syntax term ()
Static Package Attributes
static boolean DEBUG_LEAKS =false
static final HashMap< String, T2 > PRIMS = new HashMap<>()
Static Private Member Functions
static String id ()
static boolean isAlpha0 (byte c)
static boolean isAlpha1 (byte c)
static boolean isDigit (byte c)
static boolean isWS (byte c)
static Syntax number ()
static< T > T require (char c, T t)
static void require (String s)
static byte skipWS ()
static Syntax string ()
Static Private Attributes
static byte[] BUF
static final SB ID = new SB()
static int X
Detailed Description
Definition at line 24 of file HM8.java.
Member Function Documentation
[static initializer]()
com.cliffc.aa.HM.HM8.[static initializer] static package
hm()
static Syntax com.cliffc.aa.HM.HM8.hm (String sprog) static
Definition at line 29 of file HM8.java.
{
     Worklist work = new Worklist();
     // Simple types
     T2 bool  = T2.make_base(TypeInt.BOOL);
     T2 int64 = T2.make_base(TypeInt.INT64);
     T2 flt64 = T2.make_base(TypeFlt.FLT64);
     T2 strp  = T2.make_base(TypeMemPtr.STRPTR);
     // Primitives
     PRIMS.put("nil",T2.make_nil());
     T2 var1 = T2.make_leaf();
     T2 var2 = T2.make_leaf();
     T2 var3 = T2.make_leaf();
     PRIMS.put("pair1",T2.make_fun(var1, T2.make_fun(var2, T2.prim("pair",var1,var2) ))); // curried
     PRIMS.put("pair",T2.make_fun(var1, var2, T2.prim("pair",var1,var2) ));
     PRIMS.put("triple",T2.make_fun(var1, var2, var3, T2.prim("triple",var1,var2,var3) ));
     PRIMS.put("if",T2.make_fun(var2,var1,var1,var1));
     PRIMS.put("dec",T2.make_fun(int64,int64));
     PRIMS.put("*"  ,T2.make_fun(int64,int64,int64));
     PRIMS.put("?0",T2.make_fun(T2.make_leaf(),bool));
     PRIMS.put("isempty",T2.make_fun(strp,bool));
     // Print a string; int->str
     PRIMS.put("str",T2.make_fun(int64,strp));
     // Factor; FP div/mod-like operation
     PRIMS.put("factor",T2.make_fun(flt64,T2.prim("divmod",flt64,flt64)));
     // Parse
     Syntax prog = parse( sprog );
     // Prep for SSA: pre-gather all the (unique) ids
     int cnt_syns = prog.prep_tree(null,null,work);
     int init_T2s = T2.CNT;
     while( work.len()>0 ) {     // While work
       int oldcnt = T2.CNT;      // Used for cost-check when no-progress
       Syntax syn = work.pop();  // Get work
       T2 old = syn._t;          // Old value for progress assert
       if( syn.hm(work) ) {      // Compute a new HM type and check for progress
         assert !syn.debug_find().unify(old.find(),null);// monotonic: unifying with the result is no-progress
         syn.add_work(work);     // Push affected neighors on worklist
       } else {
         assert !DEBUG_LEAKS || oldcnt==T2.CNT;  // No-progress consumes no-new-T2s
       }
       // VERY EXPENSIVE ASSERT: O(n^2).  Every Syntax that makes progress is on the worklist
       assert prog.more_work(work);
     }
     assert prog.more_work(work);
     //System.out.println("Initial T2s: "+init_T2s+", Prog size: "+cnt_syns+", worklist iters: "+work._cnt+", T2s: "+T2.CNT);
     return prog;
   }
References com.cliffc.aa.HM.HM8.Syntax._t, com.cliffc.aa.HM.HM8.Syntax.add_work(), com.cliffc.aa.type.TypeInt.BOOL, com.cliffc.aa.HM.HM8.T2.CNT, com.cliffc.aa.HM.HM8.Syntax.debug_find(), com.cliffc.aa.HM.HM8.DEBUG_LEAKS, com.cliffc.aa.HM.HM8.T2.find(), com.cliffc.aa.type.TypeFlt.FLT64, com.cliffc.aa.HM.HM8.Syntax.hm(), com.cliffc.aa.type.TypeInt.INT64, com.cliffc.aa.HM.HM8.Worklist.len(), com.cliffc.aa.HM.HM8.T2.make_base(), com.cliffc.aa.HM.HM8.T2.make_fun(), com.cliffc.aa.HM.HM8.T2.make_leaf(), com.cliffc.aa.HM.HM8.T2.make_nil(), com.cliffc.aa.HM.HM8.Syntax.more_work(), com.cliffc.aa.HM.HM8.parse(), com.cliffc.aa.HM.HM8.Worklist.pop(), com.cliffc.aa.HM.HM8.Syntax.prep_tree(), com.cliffc.aa.HM.HM8.T2.prim(), com.cliffc.aa.HM.HM8.PRIMS, com.cliffc.aa.type.TypeMemPtr.STRPTR, and com.cliffc.aa.HM.HM8.T2.unify().
Referenced by com.cliffc.aa.HM.TestHM8.test00(), com.cliffc.aa.HM.TestHM8.test01(), com.cliffc.aa.HM.TestHM8.test02(), com.cliffc.aa.HM.TestHM8.test03(), com.cliffc.aa.HM.TestHM8.test04(), com.cliffc.aa.HM.TestHM8.test05(), com.cliffc.aa.HM.TestHM8.test05a(), com.cliffc.aa.HM.TestHM8.test06(), com.cliffc.aa.HM.TestHM8.test07(), com.cliffc.aa.HM.TestHM8.test08(), com.cliffc.aa.HM.TestHM8.test09(), com.cliffc.aa.HM.TestHM8.test10(), com.cliffc.aa.HM.TestHM8.test11(), com.cliffc.aa.HM.TestHM8.test12(), com.cliffc.aa.HM.TestHM8.test13(), com.cliffc.aa.HM.TestHM8.test14(), com.cliffc.aa.HM.TestHM8.test15(), com.cliffc.aa.HM.TestHM8.test16(), com.cliffc.aa.HM.TestHM8.test17(), com.cliffc.aa.HM.TestHM8.test18(), com.cliffc.aa.HM.TestHM8.test19(), com.cliffc.aa.HM.TestHM8.test20(), com.cliffc.aa.HM.TestHM8.test21(), com.cliffc.aa.HM.TestHM8.test22(), com.cliffc.aa.HM.TestHM8.test23(), com.cliffc.aa.HM.TestHM8.test24(), com.cliffc.aa.HM.TestHM8.test25(), com.cliffc.aa.HM.TestHM8.test25a(), com.cliffc.aa.HM.TestHM8.test25b(), com.cliffc.aa.HM.TestHM8.test26(), com.cliffc.aa.HM.TestHM8.test27(), com.cliffc.aa.HM.TestHM8.test28(), com.cliffc.aa.HM.TestHM8.test29(), com.cliffc.aa.HM.TestHM8.test30(), com.cliffc.aa.HM.TestHM8.test30a(), com.cliffc.aa.HM.TestHM8.test31(), com.cliffc.aa.HM.TestHM8.test32(), com.cliffc.aa.HM.TestHM8.test33(), com.cliffc.aa.HM.TestHM8.test34(), com.cliffc.aa.HM.TestHM8.test35(), and com.cliffc.aa.HM.TestHM8.test36().
id()
static String com.cliffc.aa.HM.HM8.id () static private
Definition at line 155 of file HM8.java.
{
     ID.clear();
     while( X<BUF.length && isAlpha1(BUF[X]) )
       ID.p((char)BUF[X++]);
     String s = ID.toString().intern();
     if( s.length()==0 ) throw unimpl("Missing id");
     return s;
   }
References com.cliffc.aa.HM.HM8.BUF, com.cliffc.aa.util.SB.clear(), com.cliffc.aa.HM.HM8.ID, com.cliffc.aa.HM.HM8.isAlpha1(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.util.SB.toString(), and com.cliffc.aa.HM.HM8.X.
Referenced by com.cliffc.aa.HM.HM8.T2.add_fld(), com.cliffc.aa.HM.HM8.Field.Field(), and com.cliffc.aa.HM.HM8.term().
isAlpha0()
static boolean com.cliffc.aa.HM.HM8.isAlpha0 (byte c) static private
Definition at line 184 of file HM8.java.
 { return ('a'<=c && c <= 'z') || ('A'<=c && c <= 'Z') || (c=='_') || (c=='*') || (c=='?'); }
Referenced by com.cliffc.aa.HM.HM8.isAlpha1(), and com.cliffc.aa.HM.HM8.term().
isAlpha1()
static boolean com.cliffc.aa.HM.HM8.isAlpha1 (byte c) static private
Definition at line 185 of file HM8.java.
 { return isAlpha0(c) || ('0'<=c && c <= '9') || (c=='/'); }
References com.cliffc.aa.HM.HM8.isAlpha0().
Referenced by com.cliffc.aa.HM.HM8.id().
isDigit()
static boolean com.cliffc.aa.HM.HM8.isDigit (byte c) static private
Definition at line 183 of file HM8.java.
 { return '0' <= c && c <= '9'; }
Referenced by com.cliffc.aa.HM.HM8.number(), and com.cliffc.aa.HM.HM8.term().
isWS()
static boolean com.cliffc.aa.HM.HM8.isWS (byte c) static private
Definition at line 182 of file HM8.java.
 { return c == ' ' || c == '\t' || c == '\n' || c == '\r'; }
Referenced by com.cliffc.aa.HM.HM8.skipWS().
number()
static Syntax com.cliffc.aa.HM.HM8.number () static private
Definition at line 163 of file HM8.java.
{
     int sum=0;
     while( X<BUF.length && isDigit(BUF[X]) )
       sum = sum*10+BUF[X++]-'0';
     if( X>= BUF.length || BUF[X]!='.' ) return new Con(TypeInt.con(sum));
     X++;
     float f = (float)sum;
     f = f + (BUF[X++]-'0')/10.0f;
     return new Con(TypeFlt.con(f));
   }
References com.cliffc.aa.HM.HM8.BUF, com.cliffc.aa.type.TypeFlt.con(), com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM8.isDigit(), and com.cliffc.aa.HM.HM8.X.
Referenced by com.cliffc.aa.HM.HM8.term().
parse()
static Syntax com.cliffc.aa.HM.HM8.parse (String s) static package
Definition at line 93 of file HM8.java.
{
     X = 0;
     BUF = s.getBytes();
     Syntax prog = term();
     if( skipWS() != -1 ) throw unimpl("Junk at end of program: "+new String(BUF,X,BUF.length-X));
     return prog;
   }
References com.cliffc.aa.HM.HM8.BUF, com.cliffc.aa.HM.HM8.skipWS(), com.cliffc.aa.HM.HM8.term(), and com.cliffc.aa.HM.HM8.X.
Referenced by com.cliffc.aa.HM.HM8.hm().
require() [1/2]
static <T> T com.cliffc.aa.HM.HM8.require (char c, T t) static private
Definition at line 186 of file HM8.java.
 { if( skipWS()!=c ) throw unimpl("Missing '"+c+"'"); X++; return t; }
References com.cliffc.aa.HM.HM8.skipWS(), and com.cliffc.aa.HM.HM8.X.
Referenced by com.cliffc.aa.HM.HM8.string(), and com.cliffc.aa.HM.HM8.term().
require() [2/2]
static void com.cliffc.aa.HM.HM8.require (String s) static private
Definition at line 187 of file HM8.java.
{
     skipWS();
     for( int i=0; i<s.length(); i++ )
       if( X+i >= BUF.length || BUF[X+i]!=s.charAt(i) )
         throw unimpl("Missing '"+s+"'");
     X+=s.length();
   }
References com.cliffc.aa.HM.HM8.BUF, com.cliffc.aa.HM.HM8.skipWS(), and com.cliffc.aa.HM.HM8.X.
reset()
static void com.cliffc.aa.HM.HM8.reset () static package
Definition at line 86 of file HM8.java.
 { PRIMS.clear(); T2.reset(); BitsAlias.reset_to_init0(); }
References com.cliffc.aa.HM.HM8.PRIMS, com.cliffc.aa.HM.HM8.T2.reset(), and com.cliffc.aa.type.BitsAlias.reset_to_init0().
Referenced by com.cliffc.aa.HM.TestHM8.reset().
skipWS()
static byte com.cliffc.aa.HM.HM8.skipWS () static private
Definition at line 178 of file HM8.java.
{
     while( X<BUF.length && isWS(BUF[X]) ) X++;
     return X==BUF.length ? -1 : BUF[X];
   }
References com.cliffc.aa.HM.HM8.BUF, com.cliffc.aa.HM.HM8.isWS(), and com.cliffc.aa.HM.HM8.X.
Referenced by com.cliffc.aa.HM.HM8.parse(), com.cliffc.aa.HM.HM8.require(), and com.cliffc.aa.HM.HM8.term().
string()
static Syntax com.cliffc.aa.HM.HM8.string () static private
Definition at line 173 of file HM8.java.
{
     int start = ++X;
     while( X<BUF.length && BUF[X]!='"' ) X++;
     return require('"', new Con(TypeStr.con(new String(BUF,start,X-start).intern())));
   }
References com.cliffc.aa.HM.HM8.BUF, com.cliffc.aa.type.TypeStr.con(), com.cliffc.aa.HM.HM8.require(), and com.cliffc.aa.HM.HM8.X.
Referenced by com.cliffc.aa.HM.HM8.term().
term()
static Syntax com.cliffc.aa.HM.HM8.term () static package
Definition at line 100 of file HM8.java.
{
     if( skipWS()==-1 ) return null;
     if( isDigit(BUF[X]) ) return number();
     if( BUF[X]=='"' ) return string();
     if( BUF[X]=='(' ) {         // Parse an Apply
       X++;                      // Skip paren
       Syntax fun = term();
       Ary<Syntax> ARGS = new Ary<>(new Syntax[1],0);
       while( skipWS()!= ')' && X<BUF.length ) ARGS.push(term());
       return new Apply(fun,require(')',ARGS.asAry()));
     }
     if( BUF[X]=='{' ) {         // Lambda of 1 or 2 args
       X++;                      // Skip paren
       Ary<String> args = new Ary<>(new String[1],0);
       while( skipWS()!='-' ) args.push(id());
       require("->");
       Syntax body = require('}',term());
       return new Lambda(body,args.asAry());
     }
     // Let or Id
     if( isAlpha0(BUF[X]) ) {
       String id = id();
       if( skipWS()!='=' )  return new Ident(id);
       // Let expression; "id = term(); term..."
       X++;                      // Skip '='
       Syntax def = require(';',term());
       return new Let(id,def,term());
     }
     // Structure
     if( BUF[X]=='@' ) {
       X++;
       require('{',null);
       Ary<String>  ids = new Ary<>(String.class);
       Ary<Syntax> flds = new Ary<>(Syntax.class);
       while( skipWS()!='}' && X < BUF.length ) {
         String id = require('=',id());
         Syntax fld = term();
         if( fld==null ) throw unimpl("Missing term for field "+id);
         ids .push( id);
         flds.push(fld);
         if( skipWS()==',' ) X++;
       }
       return require('}',new Struct(ids.asAry(),flds.asAry()));
     }
     // Field lookup is prefix or backwards: ".x term"
     if( BUF[X]=='.' ) {
       X++;
       return new Field(id(),term());
     }
     throw unimpl("Unknown syntax");
   }
References com.cliffc.aa.util.Ary< E >.asAry(), com.cliffc.aa.HM.HM8.BUF, com.cliffc.aa.HM.HM8.id(), com.cliffc.aa.HM.HM8.isAlpha0(), com.cliffc.aa.HM.HM8.isDigit(), com.cliffc.aa.HM.HM8.number(), com.cliffc.aa.util.Ary< E >.push(), com.cliffc.aa.HM.HM8.require(), com.cliffc.aa.HM.HM8.skipWS(), com.cliffc.aa.HM.HM8.string(), and com.cliffc.aa.HM.HM8.X.
Referenced by com.cliffc.aa.HM.HM8.parse().
toString()
String com.cliffc.aa.HM.HM8.toString ()
Definition at line 92 of file HM8.java.
 { return new String(BUF,X,BUF.length-X); }
References com.cliffc.aa.HM.HM8.BUF, and com.cliffc.aa.HM.HM8.X.
Member Data Documentation
BUF
byte [] com.cliffc.aa.HM.HM8.BUF static private
Definition at line 91 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.id(), com.cliffc.aa.HM.HM8.number(), com.cliffc.aa.HM.HM8.parse(), com.cliffc.aa.HM.HM8.require(), com.cliffc.aa.HM.HM8.skipWS(), com.cliffc.aa.HM.HM8.string(), com.cliffc.aa.HM.HM8.term(), and com.cliffc.aa.HM.HM8.toString().
DEBUG_LEAKS
boolean com.cliffc.aa.HM.HM8.DEBUG_LEAKS =false static package
Definition at line 26 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.T2.fresh_unify(), and com.cliffc.aa.HM.HM8.hm().
ID
final SB com.cliffc.aa.HM.HM8.ID = new SB() static private
Definition at line 154 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.id().
PRIMS
final HashMap<String,T2> com.cliffc.aa.HM.HM8.PRIMS = new HashMap<>() static package
Definition at line 25 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.Ident.add_work(), com.cliffc.aa.HM.HM8.hm(), com.cliffc.aa.HM.HM8.Ident.hm(), and com.cliffc.aa.HM.HM8.reset().
X
int com.cliffc.aa.HM.HM8.X static private
Definition at line 90 of file HM8.java.
Referenced by com.cliffc.aa.HM.HM8.id(), com.cliffc.aa.HM.HM8.number(), com.cliffc.aa.HM.HM8.parse(), com.cliffc.aa.HM.HM8.require(), com.cliffc.aa.HM.HM8.skipWS(), com.cliffc.aa.HM.HM8.string(), com.cliffc.aa.HM.HM8.term(), and com.cliffc.aa.HM.HM8.toString().
The documentation for this class was generated from the following file:
HM8.java