aa: com.cliffc.aa.HM.HM2.Apply Class Reference
com.cliffc.aa.HM.HM2.Apply Class Reference
Public Member Functions
String toString ()
Package Functions
Apply (Syntax fun, Syntax arg)
void get_ids ()
HMType hm (HashSet< HMVar > nongen)
Package Attributes
final Syntax _arg
final Syntax _fun
Detailed Description
Definition at line 157 of file HM2.java.
Constructor & Destructor Documentation
Apply()
com.cliffc.aa.HM.HM2.Apply.Apply (Syntax fun, Syntax arg) package
Definition at line 159 of file HM2.java.
 { _fun=fun; _arg=arg; }
References com.cliffc.aa.HM.HM2.Apply._arg, and com.cliffc.aa.HM.HM2.Apply._fun.
Member Function Documentation
get_ids()
void com.cliffc.aa.HM.HM2.Apply.get_ids () package
Reimplemented from com.cliffc.aa.HM.HM2.Syntax.
Definition at line 169 of file HM2.java.
 { _fun.get_ids(); _arg.get_ids(); }
References com.cliffc.aa.HM.HM2.Apply._arg, com.cliffc.aa.HM.HM2.Apply._fun, and com.cliffc.aa.HM.HM2.Syntax.get_ids().
hm()
HMType com.cliffc.aa.HM.HM2.Apply.hm (HashSet< HMVar > nongen) package
Reimplemented from com.cliffc.aa.HM.HM2.Syntax.
Definition at line 161 of file HM2.java.
{
       HMType tfun = _fun.hm(nongen);
       HMType targ = _arg.hm(nongen);
       HMType trez = new HMVar();
       HMType nfun = Oper.fun(targ,trez);
       nfun.union(tfun);
       return trez;
     }
References com.cliffc.aa.HM.HM2.Apply._arg, com.cliffc.aa.HM.HM2.Apply._fun, com.cliffc.aa.HM.HM2.Oper.fun(), com.cliffc.aa.HM.HM2.Syntax.hm(), and com.cliffc.aa.HM.HM2.HMType.union().
toString()
String com.cliffc.aa.HM.HM2.Apply.toString ()
Definition at line 160 of file HM2.java.
 { return "("+_fun+" "+_arg+")"; }
References com.cliffc.aa.HM.HM2.Apply._arg, and com.cliffc.aa.HM.HM2.Apply._fun.
Member Data Documentation
_arg
final Syntax com.cliffc.aa.HM.HM2.Apply._arg package
Definition at line 158 of file HM2.java.
Referenced by com.cliffc.aa.HM.HM2.Apply.Apply(), com.cliffc.aa.HM.HM2.Apply.get_ids(), com.cliffc.aa.HM.HM2.Apply.hm(), and com.cliffc.aa.HM.HM2.Apply.toString().
_fun
final Syntax com.cliffc.aa.HM.HM2.Apply._fun package
Definition at line 158 of file HM2.java.
Referenced by com.cliffc.aa.HM.HM2.Apply.Apply(), com.cliffc.aa.HM.HM2.Apply.get_ids(), com.cliffc.aa.HM.HM2.Apply.hm(), and com.cliffc.aa.HM.HM2.Apply.toString().
The documentation for this class was generated from the following file:
HM2.java