aa: com.cliffc.aa.HM.HM3.HMType Class Reference
com.cliffc.aa.HM.HM3.HMType Class Reference abstract
Public Member Functions
String str ()
final String toString ()
Package Functions
HMType ()
abstract boolean _eq (HMType v, BitSetSparse dups)
abstract HMType _fresh (VStack vstk, HashMap< HMVar, HMVar > vars, HashMap< Oper, Oper > opers)
abstract SB _str (SB sb, VBitSet vbs, boolean debug)
final boolean eq (HMType v)
abstract HMType find ()
HMType fresh (VStack vstk)
boolean is_top ()
boolean occurs_in (HMType[] args, VBitSet dups)
boolean occurs_in (VStack vstk, VBitSet dups)
boolean occurs_in_type (HMType v, VBitSet dups)
abstract HMType union (HMType t, Worklist work)
Static Package Functions
static void reset ()
Package Attributes
Ary< Ident > _ids
HMType _u
final int _uid
Static Package Attributes
static final HashMap< HMVar, HMVar > EQS = new HashMap<>()
Static Private Attributes
static int CNT
Detailed Description
Definition at line 277 of file HM3.java.
Constructor & Destructor Documentation
HMType()
com.cliffc.aa.HM.HM3.HMType.HMType () package
Definition at line 282 of file HM3.java.
 { _uid=CNT++; }
References com.cliffc.aa.HM.HM3.HMType._uid, and com.cliffc.aa.HM.HM3.HMType.CNT.
Member Function Documentation
_eq()
abstract boolean com.cliffc.aa.HM.HM3.HMType._eq (HMType v, BitSetSparse dups) abstract package
Reimplemented in com.cliffc.aa.HM.HM3.Oper, and com.cliffc.aa.HM.HM3.HMVar.
Referenced by com.cliffc.aa.HM.HM3.Oper._eq(), and com.cliffc.aa.HM.HM3.HMType.eq().
_fresh()
abstract HMType com.cliffc.aa.HM.HM3.HMType._fresh (VStack vstk, HashMap< HMVar, HMVar > vars, HashMap< Oper, Oper > opers) abstract package
Reimplemented in com.cliffc.aa.HM.HM3.Oper, and com.cliffc.aa.HM.HM3.HMVar.
Referenced by com.cliffc.aa.HM.HM3.Oper._fresh(), and com.cliffc.aa.HM.HM3.HMType.fresh().
_str()
abstract SB com.cliffc.aa.HM.HM3.HMType._str (SB sb, VBitSet vbs, boolean debug) abstract package
Reimplemented in com.cliffc.aa.HM.HM3.Oper, and com.cliffc.aa.HM.HM3.HMVar.
Referenced by com.cliffc.aa.HM.HM3.HMVar._str(), com.cliffc.aa.HM.HM3.Oper._str(), com.cliffc.aa.HM.HM3.HMType.str(), and com.cliffc.aa.HM.HM3.HMType.toString().
eq()
final boolean com.cliffc.aa.HM.HM3.HMType.eq (HMType v) package
Definition at line 291 of file HM3.java.
 { EQS.clear(); return find()._eq(v, new BitSetSparse()); }
References com.cliffc.aa.HM.HM3.HMType._eq(), com.cliffc.aa.HM.HM3.HMType.EQS, and com.cliffc.aa.HM.HM3.HMType.find().
Referenced by com.cliffc.aa.HM.HM3.Lambda.progress(), com.cliffc.aa.HM.HM3.Let.progress(), and com.cliffc.aa.HM.HM3.Apply.progress().
find()
abstract HMType com.cliffc.aa.HM.HM3.HMType.find () abstract package
Reimplemented in com.cliffc.aa.HM.HM3.Oper, and com.cliffc.aa.HM.HM3.HMVar.
Referenced by com.cliffc.aa.HM.HM3.HMVar._eq(), com.cliffc.aa.HM.HM3.Oper._eq(), com.cliffc.aa.HM.HM3.HMType.eq(), com.cliffc.aa.HM.HM3.HMType.fresh(), com.cliffc.aa.HM.HM3.Lambda.hm(), com.cliffc.aa.HM.HM3.Let.hm(), com.cliffc.aa.HM.HM3.Apply.hm(), com.cliffc.aa.HM.HM3.HMType.occurs_in_type(), com.cliffc.aa.HM.HM3.Lambda.progress(), com.cliffc.aa.HM.HM3.Let.progress(), com.cliffc.aa.HM.HM3.Apply.progress(), and com.cliffc.aa.HM.HM3.HMVar.union().
fresh()
HMType com.cliffc.aa.HM.HM3.HMType.fresh (VStack vstk) package
Definition at line 294 of file HM3.java.
{
       HashMap<HMVar,HMVar> vars = new HashMap<>();
       HashMap<Oper,Oper> opers = new HashMap<>();
       return find()._fresh(vstk,vars,opers);
     }
References com.cliffc.aa.HM.HM3.HMType._fresh(), and com.cliffc.aa.HM.HM3.HMType.find().
Referenced by com.cliffc.aa.HM.HM3.Ident.hm().
is_top()
boolean com.cliffc.aa.HM.HM3.HMType.is_top () package
Definition at line 289 of file HM3.java.
 { return _u==null; }
References com.cliffc.aa.HM.HM3.HMType._u.
Referenced by com.cliffc.aa.HM.HM3.Oper._eq(), com.cliffc.aa.HM.HM3.HMVar._fresh(), com.cliffc.aa.HM.HM3.Oper._fresh(), com.cliffc.aa.HM.HM3.HMType.occurs_in_type(), and com.cliffc.aa.HM.HM3.HMVar.type().
occurs_in() [1/2]
boolean com.cliffc.aa.HM.HM3.HMType.occurs_in (HMType[] args, VBitSet dups) package
Definition at line 306 of file HM3.java.
{
       for( HMType x : args ) if( occurs_in_type(x,dups) ) return true;
       return false;
     }
References com.cliffc.aa.HM.HM3.HMType.occurs_in_type().
occurs_in() [2/2]
boolean com.cliffc.aa.HM.HM3.HMType.occurs_in (VStack vstk, VBitSet dups) package
Definition at line 301 of file HM3.java.
{
       if( vstk==null ) return false;
       for( HMVar x : vstk ) if( occurs_in_type(x,dups) ) return true;
       return false;
     }
References com.cliffc.aa.HM.HM3.HMType.occurs_in_type().
Referenced by com.cliffc.aa.HM.HM3.HMVar._fresh(), and com.cliffc.aa.HM.HM3.HMType.occurs_in_type().
occurs_in_type()
boolean com.cliffc.aa.HM.HM3.HMType.occurs_in_type (HMType v, VBitSet dups) package
Definition at line 310 of file HM3.java.
{
       assert is_top();
       if( dups.tset(v._uid) )
         return false;           // Been there, done that
       HMType y = v.find();      // Find top
       if( y==this )             // Occurs in type?
         return true;            // Yup, occurs in type right here
       if( y instanceof Oper )   // Structural recursive test
         return occurs_in(((Oper)y)._args,dups);
       return false;
     }
References com.cliffc.aa.HM.HM3.HMType._uid, com.cliffc.aa.HM.HM3.HMType.find(), com.cliffc.aa.HM.HM3.HMType.is_top(), com.cliffc.aa.HM.HM3.HMType.occurs_in(), and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.HM.HM3.HMType.occurs_in(), and com.cliffc.aa.HM.HM3.HMVar.union().
reset()
static void com.cliffc.aa.HM.HM3.HMType.reset () static package
Definition at line 281 of file HM3.java.
 { CNT=1; }
References com.cliffc.aa.HM.HM3.HMType.CNT.
Referenced by com.cliffc.aa.HM.HM3.reset().
str()
String com.cliffc.aa.HM.HM3.HMType.str ()
Definition at line 287 of file HM3.java.
 { return _str(new SB(),new VBitSet(),false).toString(); }
References com.cliffc.aa.HM.HM3.HMType._str(), and com.cliffc.aa.util.SB.toString().
toString()
final String com.cliffc.aa.HM.HM3.HMType.toString ()
Definition at line 286 of file HM3.java.
 { return _str(new SB(),new VBitSet(),true).toString(); }
References com.cliffc.aa.HM.HM3.HMType._str(), and com.cliffc.aa.util.SB.toString().
union()
abstract HMType com.cliffc.aa.HM.HM3.HMType.union (HMType t, Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM3.Oper, and com.cliffc.aa.HM.HM3.HMVar.
Referenced by com.cliffc.aa.HM.HM3.Let.hm(), com.cliffc.aa.HM.HM3.Apply.hm(), com.cliffc.aa.HM.HM3.HMVar.union(), and com.cliffc.aa.HM.HM3.Oper.union().
Member Data Documentation
_ids
Ary<Ident> com.cliffc.aa.HM.HM3.HMType._ids package
Definition at line 283 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Ident.get_ids(), com.cliffc.aa.HM.HM3.HMVar.union(), and com.cliffc.aa.HM.HM3.Oper.union().
_u
HMType com.cliffc.aa.HM.HM3.HMType._u package
Definition at line 278 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.HMVar._eq(), com.cliffc.aa.HM.HM3.HMVar._str(), com.cliffc.aa.HM.HM3.HMVar.find(), com.cliffc.aa.HM.HM3.HMType.is_top(), and com.cliffc.aa.HM.HM3.HMVar.union().
_uid
final int com.cliffc.aa.HM.HM3.HMType._uid package
Definition at line 279 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Oper._eq(), com.cliffc.aa.HM.HM3.HMVar._str(), com.cliffc.aa.HM.HM3.Oper._str(), com.cliffc.aa.HM.HM3.HMType.HMType(), com.cliffc.aa.HM.HM3.HMType.occurs_in_type(), com.cliffc.aa.HM.HM3.HMVar.union(), and com.cliffc.aa.HM.HM3.Oper.union().
CNT
int com.cliffc.aa.HM.HM3.HMType.CNT static private
Definition at line 280 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.HMType.HMType(), and com.cliffc.aa.HM.HM3.HMType.reset().
EQS
final HashMap<HMVar,HMVar> com.cliffc.aa.HM.HM3.HMType.EQS = new HashMap<>() static package
Definition at line 290 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.HMVar._eq(), and com.cliffc.aa.HM.HM3.HMType.eq().
The documentation for this class was generated from the following file:
HM3.java