aa: com.cliffc.aa.HM.HM7.Struct Class Reference
com.cliffc.aa.HM.HM7.Struct Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Struct (String[] ids, Syntax[] flds)
void add_kids (Worklist work)
void add_occurs (Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
T2 lookup (String name)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
Package Attributes
final Syntax[] _flds
final String[] _ids
VStack _nongen
Syntax _par
T2 _t
Detailed Description
Definition at line 525 of file HM7.java.
Constructor & Destructor Documentation
Struct()
com.cliffc.aa.HM.HM7.Struct.Struct (String[] ids, Syntax[] flds) package
Definition at line 528 of file HM7.java.
 { _ids=ids; _flds=flds; }
References com.cliffc.aa.HM.HM7.Struct._flds, and com.cliffc.aa.HM.HM7.Struct._ids.
Member Function Documentation
add_kids()
void com.cliffc.aa.HM.HM7.Struct.add_kids (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 563 of file HM7.java.
 { for( Syntax fld : _flds ) work.push(fld); }
References com.cliffc.aa.HM.HM7.Struct._flds, and com.cliffc.aa.HM.HM7.Worklist.push().
add_occurs()
void com.cliffc.aa.HM.HM7.Syntax.add_occurs (Worklist work) package inherited
Reimplemented in com.cliffc.aa.HM.HM7.Field, com.cliffc.aa.HM.HM7.Let, com.cliffc.aa.HM.HM7.Lambda, and com.cliffc.aa.HM.HM7.Ident.
Definition at line 266 of file HM7.java.
 {}
Referenced by com.cliffc.aa.HM.HM7.Field.add_occurs(), and com.cliffc.aa.HM.HM7.hm().
debug_find()
T2 com.cliffc.aa.HM.HM7.Syntax.debug_find () package inherited
Definition at line 250 of file HM7.java.
 { return _t.find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM7.Syntax._t, and com.cliffc.aa.HM.HM7.T2.find().
Referenced by com.cliffc.aa.HM.HM7.hm().
find()
T2 com.cliffc.aa.HM.HM7.Syntax.find () package inherited
Definition at line 246 of file HM7.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM7.Syntax._t, and com.cliffc.aa.HM.HM7.T2.find().
Referenced by com.cliffc.aa.HM.HM7.T2._occurs_in(), com.cliffc.aa.HM.HM7.Lambda.add_occurs(), com.cliffc.aa.HM.HM7.Let.add_occurs(), com.cliffc.aa.HM.HM7.Ident.hm(), com.cliffc.aa.HM.HM7.Lambda.hm(), com.cliffc.aa.HM.HM7.Let.hm(), com.cliffc.aa.HM.HM7.Apply.hm(), com.cliffc.aa.HM.HM7.Struct.hm(), com.cliffc.aa.HM.HM7.Field.hm(), com.cliffc.aa.HM.HM7.Apply.is_if_nil(), and com.cliffc.aa.HM.HM7.Struct.prep_tree().
hm()
boolean com.cliffc.aa.HM.HM7.Struct.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 544 of file HM7.java.
{
       // Check for progress before making new
       T2 old = find();
       if( old.is_struct() ) {  // Already a struct?  Compare-by-parts
         for( int i=0; i<_ids.length; i++ ) {
           int idx = Util.find(old._ids,_ids[i]);
           if( idx== -1 || old.args(idx).unify(_flds[i].find(),work) ) { old=null; break; }
         }
         if( old!=null ) return false; // Shortcut: no progress, no allocation
       }
       // Make a new T2 for progress
       T2[] t2s = new T2[_ids.length];
       for( int i=0; i<_ids.length; i++ )
         t2s[i] = _flds[i].find();
       T2 tstruct = T2.make_struct(_ids,t2s);
       return tstruct.unify(find(),work);
     }
References com.cliffc.aa.HM.HM7.Struct._flds, com.cliffc.aa.HM.HM7.Struct._ids, com.cliffc.aa.HM.HM7.T2._ids, com.cliffc.aa.HM.HM7.T2.args(), com.cliffc.aa.util.Util.find(), com.cliffc.aa.HM.HM7.Syntax.find(), com.cliffc.aa.HM.HM7.T2.is_struct(), com.cliffc.aa.HM.HM7.T2.make_struct(), and com.cliffc.aa.HM.HM7.T2.unify().
lookup()
T2 com.cliffc.aa.HM.HM7.Struct.lookup (String name) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 562 of file HM7.java.
 { return _par==null ? null : _par.lookup(name); }
References com.cliffc.aa.HM.HM7.Syntax._par, and com.cliffc.aa.HM.HM7.Syntax.lookup().
more_work()
boolean com.cliffc.aa.HM.HM7.Struct.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 575 of file HM7.java.
{
       if( !more_work_impl(work) ) return false;
       for( Syntax fld : _flds )
         if( !fld.more_work(work) )
           return false;
       return true;
     }
References com.cliffc.aa.HM.HM7.Struct._flds, and com.cliffc.aa.HM.HM7.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM7.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 270 of file HM7.java.
{
       boolean no_more_work = work.has(this) || !hm(null); // Either on worklist, or no-progress
       return no_more_work;
     }
References com.cliffc.aa.HM.HM7.Worklist.has(), and com.cliffc.aa.HM.HM7.Syntax.hm().
Referenced by com.cliffc.aa.HM.HM7.Con.more_work(), com.cliffc.aa.HM.HM7.Ident.more_work(), com.cliffc.aa.HM.HM7.Lambda.more_work(), com.cliffc.aa.HM.HM7.Let.more_work(), com.cliffc.aa.HM.HM7.Apply.more_work(), com.cliffc.aa.HM.HM7.Struct.more_work(), and com.cliffc.aa.HM.HM7.Field.more_work().
p()
String com.cliffc.aa.HM.HM7.Syntax.p () inherited
Definition at line 278 of file HM7.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM7.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM7.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 279 of file HM7.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM7.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM7.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM7.Syntax.p1(), com.cliffc.aa.HM.HM7.Syntax.p2(), and com.cliffc.aa.HM.HM7.T2.str().
Referenced by com.cliffc.aa.HM.HM7.Syntax.p(), com.cliffc.aa.HM.HM7.Lambda.p2(), com.cliffc.aa.HM.HM7.Let.p2(), com.cliffc.aa.HM.HM7.Apply.p2(), com.cliffc.aa.HM.HM7.Struct.p2(), and com.cliffc.aa.HM.HM7.Field.p2().
p1()
SB com.cliffc.aa.HM.HM7.Struct.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 538 of file HM7.java.
 { return sb.p("@{ ... } "); }
References com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM7.Struct.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 539 of file HM7.java.
{
       for( int i=0; i<_ids.length; i++ )
         _flds[i].p0(sb.p(_ids[i]).p(" = "),dups);
       return sb;
     }
References com.cliffc.aa.HM.HM7.Struct._flds, com.cliffc.aa.HM.HM7.Struct._ids, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM7.Syntax.p0().
prep_lookup_deps()
void com.cliffc.aa.HM.HM7.Struct.prep_lookup_deps (Ident id) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 574 of file HM7.java.
 { }
prep_tree()
int com.cliffc.aa.HM.HM7.Struct.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 564 of file HM7.java.
{
       T2[] t2s = new T2[_ids.length];
       prep_tree_impl(par, nongen, work, T2.make_struct(_ids,t2s));
       int cnt = 1;              // One for self
       for( int i=0; i<_flds.length; i++ ) { // Prep all sub-fields
         cnt += _flds[i].prep_tree(this,nongen,work);
         t2s[i] = _flds[i].find();
       }
       return cnt;
     }
References com.cliffc.aa.HM.HM7.Struct._flds, com.cliffc.aa.HM.HM7.Struct._ids, com.cliffc.aa.HM.HM7.Syntax.find(), com.cliffc.aa.HM.HM7.T2.make_struct(), com.cliffc.aa.HM.HM7.Syntax.prep_tree(), and com.cliffc.aa.HM.HM7.Syntax.prep_tree_impl().
prep_tree_impl()
final void com.cliffc.aa.HM.HM7.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 260 of file HM7.java.
 { _par=par; _t=t; _nongen = nongen; work.push(this); }
References com.cliffc.aa.HM.HM7.Syntax._nongen, com.cliffc.aa.HM.HM7.Syntax._par, com.cliffc.aa.HM.HM7.Syntax._t, and com.cliffc.aa.HM.HM7.Worklist.push().
Referenced by com.cliffc.aa.HM.HM7.Con.prep_tree(), com.cliffc.aa.HM.HM7.Ident.prep_tree(), com.cliffc.aa.HM.HM7.Lambda.prep_tree(), com.cliffc.aa.HM.HM7.Let.prep_tree(), com.cliffc.aa.HM.HM7.Apply.prep_tree(), com.cliffc.aa.HM.HM7.Struct.prep_tree(), and com.cliffc.aa.HM.HM7.Field.prep_tree().
str()
SB com.cliffc.aa.HM.HM7.Struct.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM7.Syntax.
Definition at line 529 of file HM7.java.
{
       sb.p("@{");
       for( int i=0; i<_ids.length; i++ ) {
         sb.p(' ').p(_ids[i]).p(" = ");
         _flds[i].str(sb);
         if( i < _ids.length-1 ) sb.p(',');
       }
       return sb.p("}");
     }
References com.cliffc.aa.HM.HM7.Struct._flds, com.cliffc.aa.HM.HM7.Struct._ids, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM7.Syntax.str().
toString()
final String com.cliffc.aa.HM.HM7.Syntax.toString () inherited
Definition at line 275 of file HM7.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM7.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_flds
final Syntax [] com.cliffc.aa.HM.HM7.Struct._flds package
Definition at line 527 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.Struct.add_kids(), com.cliffc.aa.HM.HM7.Struct.hm(), com.cliffc.aa.HM.HM7.Struct.more_work(), com.cliffc.aa.HM.HM7.Struct.p2(), com.cliffc.aa.HM.HM7.Struct.prep_tree(), com.cliffc.aa.HM.HM7.Struct.str(), and com.cliffc.aa.HM.HM7.Struct.Struct().
_ids
final String [] com.cliffc.aa.HM.HM7.Struct._ids package
Definition at line 526 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.Struct.hm(), com.cliffc.aa.HM.HM7.Struct.p2(), com.cliffc.aa.HM.HM7.Struct.prep_tree(), com.cliffc.aa.HM.HM7.Struct.str(), and com.cliffc.aa.HM.HM7.Struct.Struct().
_nongen
VStack com.cliffc.aa.HM.HM7.Syntax._nongen package inherited
Definition at line 244 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.Ident.hm(), and com.cliffc.aa.HM.HM7.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM7.Syntax._par package inherited
Definition at line 243 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2._occurs_in(), com.cliffc.aa.HM.HM7.Ident.add_occurs(), com.cliffc.aa.HM.HM7.hm(), com.cliffc.aa.HM.HM7.Ident.hm(), com.cliffc.aa.HM.HM7.Lambda.lookup(), com.cliffc.aa.HM.HM7.Let.lookup(), com.cliffc.aa.HM.HM7.Apply.lookup(), com.cliffc.aa.HM.HM7.Struct.lookup(), com.cliffc.aa.HM.HM7.Field.lookup(), com.cliffc.aa.HM.HM7.Ident.prep_tree(), and com.cliffc.aa.HM.HM7.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM7.Syntax._t package inherited
Definition at line 245 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.Syntax.debug_find(), com.cliffc.aa.HM.HM7.Syntax.find(), com.cliffc.aa.HM.HM7.hm(), com.cliffc.aa.HM.HM7.Syntax.p0(), com.cliffc.aa.HM.HM7.Let.prep_tree(), and com.cliffc.aa.HM.HM7.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM7.java