aa: com.cliffc.aa.HM.HM3.Worklist Class Reference
com.cliffc.aa.HM.HM3.Worklist Class Reference
Public Member Functions
void addAll (Ary<? extends Syntax > ss)
boolean has (Syntax s)
int len ()
Syntax pop ()
void push (Syntax s)
String toString ()
Private Attributes
final Ary< Syntax > _ary = new Ary<>(Syntax.class)
final HashSet< Syntax > _work = new HashSet<>()
Detailed Description
Definition at line 103 of file HM3.java.
Member Function Documentation
addAll()
void com.cliffc.aa.HM.HM3.Worklist.addAll (Ary<? extends Syntax > ss)
Definition at line 110 of file HM3.java.
 { for( Syntax s : ss ) push(s); }
References com.cliffc.aa.HM.HM3.Worklist.push().
has()
boolean com.cliffc.aa.HM.HM3.Worklist.has (Syntax s)
Definition at line 109 of file HM3.java.
 { return _work.contains(s); }
References com.cliffc.aa.HM.HM3.Worklist._work.
Referenced by com.cliffc.aa.HM.HM3.Syntax.check_progress().
len()
int com.cliffc.aa.HM.HM3.Worklist.len ()
Definition at line 106 of file HM3.java.
 { return _ary.len(); }
References com.cliffc.aa.HM.HM3.Worklist._ary.
Referenced by com.cliffc.aa.HM.HM3.hm().
pop()
Syntax com.cliffc.aa.HM.HM3.Worklist.pop ()
Definition at line 108 of file HM3.java.
 { Syntax s = _ary.pop(); _work.remove(s); return s; }
References com.cliffc.aa.HM.HM3.Worklist._ary, and com.cliffc.aa.HM.HM3.Worklist._work.
Referenced by com.cliffc.aa.HM.HM3.hm().
push()
void com.cliffc.aa.HM.HM3.Worklist.push (Syntax s)
Definition at line 107 of file HM3.java.
 { if( !_work.contains(s) ) _work.add(_ary.push(s)); }
References com.cliffc.aa.HM.HM3.Worklist._ary, and com.cliffc.aa.HM.HM3.Worklist._work.
Referenced by com.cliffc.aa.HM.HM3.Syntax.add_work(), and com.cliffc.aa.HM.HM3.Worklist.addAll().
toString()
String com.cliffc.aa.HM.HM3.Worklist.toString ()
Definition at line 111 of file HM3.java.
 { return _ary.toString(); }
References com.cliffc.aa.HM.HM3.Worklist._ary.
Member Data Documentation
_ary
final Ary<Syntax> com.cliffc.aa.HM.HM3.Worklist._ary = new Ary<>(Syntax.class) private
Definition at line 104 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Worklist.len(), com.cliffc.aa.HM.HM3.Worklist.pop(), com.cliffc.aa.HM.HM3.Worklist.push(), and com.cliffc.aa.HM.HM3.Worklist.toString().
_work
final HashSet<Syntax> com.cliffc.aa.HM.HM3.Worklist._work = new HashSet<>() private
Definition at line 105 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Worklist.has(), com.cliffc.aa.HM.HM3.Worklist.pop(), and com.cliffc.aa.HM.HM3.Worklist.push().
The documentation for this class was generated from the following file:
HM3.java