aa: com.cliffc.aa.HM.HM1.Apply Class Reference
com.cliffc.aa.HM.HM1.Apply Class Reference
Public Member Functions
String toString ()
Package Functions
Apply (Syntax fun, Syntax... args)
HMType hm (HashMap< String, HMType > env, HashSet< HMVar > nongen)
Package Attributes
final Syntax[] _args
final Syntax _fun
Detailed Description
Definition at line 138 of file HM1.java.
Constructor & Destructor Documentation
Apply()
com.cliffc.aa.HM.HM1.Apply.Apply (Syntax fun, Syntax... args) package
Definition at line 141 of file HM1.java.
 { _fun=fun; _args=args; }
References com.cliffc.aa.HM.HM1.Apply._args, and com.cliffc.aa.HM.HM1.Apply._fun.
Member Function Documentation
hm()
HMType com.cliffc.aa.HM.HM1.Apply.hm (HashMap< String, HMType > env, HashSet< HMVar > nongen) package
Reimplemented from com.cliffc.aa.HM.HM1.Syntax.
Definition at line 143 of file HM1.java.
{
       HMType tfun = _fun.hm(env,nongen);
       HMType[] targs = new HMType[_args.length+1];
       for( int i=0; i<_args.length; i++ )
         targs[i] = _args[i].hm(env,nongen);
       HMType trez = targs[_args.length] = new HMVar();
       HMType nfun = Oper.fun(targs);
       nfun.union(tfun);
       return trez;
     }
References com.cliffc.aa.HM.HM1.Apply._args, com.cliffc.aa.HM.HM1.Apply._fun, com.cliffc.aa.HM.HM1.Oper.fun(), com.cliffc.aa.HM.HM1.Syntax.hm(), and com.cliffc.aa.HM.HM1.HMType.union().
toString()
String com.cliffc.aa.HM.HM1.Apply.toString ()
Definition at line 142 of file HM1.java.
 { return "("+_fun+" "+Arrays.deepToString(_args)+")"; }
References com.cliffc.aa.HM.HM1.Apply._args, and com.cliffc.aa.HM.HM1.Apply._fun.
Member Data Documentation
_args
final Syntax [] com.cliffc.aa.HM.HM1.Apply._args package
Definition at line 140 of file HM1.java.
Referenced by com.cliffc.aa.HM.HM1.Apply.Apply(), com.cliffc.aa.HM.HM1.Apply.hm(), and com.cliffc.aa.HM.HM1.Apply.toString().
_fun
final Syntax com.cliffc.aa.HM.HM1.Apply._fun package
Definition at line 139 of file HM1.java.
Referenced by com.cliffc.aa.HM.HM1.Apply.Apply(), com.cliffc.aa.HM.HM1.Apply.hm(), and com.cliffc.aa.HM.HM1.Apply.toString().
The documentation for this class was generated from the following file:
HM1.java