aa: com.cliffc.aa.type.BitsRPC Class Reference
com.cliffc.aa.type.BitsRPC Class Reference
Public Member Functions
int abit ()
boolean above_center ()
BitsRPC ALL ()
BitsRPC ANY ()
int bitCount ()
IBitSet bitset ()
B clear (int bit)
B dual ()
BitsRPC EMPTY ()
boolean equals (Object o)
int getbit ()
int hashCode ()
boolean is_con ()
boolean is_empty ()
boolean is_nil ()
boolean isa (B bs)
Iterator< Integer > iterator ()
Bits< B > join (Bits< B > bs)
final B make (int... bits)
int max ()
B meet (final B bs)
B meet_nil ()
TypeObj oob (TypeObj t)
boolean overlaps (Bits< B > bs)
B set (int bit)
SB str (SB sb)
B strip_nil ()
Bits< B > subtract (Bits< B > bs)
boolean test (int i)
boolean test_recur (int i)
String toString ()
Static Public Member Functions
static void init0 ()
static int new_rpc (int par)
static void reset_to_init0 ()
Static Public Attributes
static final int ALL = new_rpc(0)
static final BitsRPC NIL = make0(0)
Package Functions
void init (int con, long[] bits)
final B make (int bit)
BitsRPC make_impl (int con, long[] bits)
boolean may_nil ()
B not_nil ()
Tree< BitsRPC > tree ()
Static Package Functions
static BitsRPC make0 (int bit)
Package Attributes
long[] _bits
int _con
int _hash
Static Package Attributes
static final BitsRPC FULL = new BitsRPC().make_impl(1,new long[]{1L | (1L<<ALL)})
Private Member Functions
boolean check ()
B make (boolean any, long[] bits)
Static Private Member Functions
static void and (long[] bits, long con)
static long[] bits (int b)
static boolean check_multi_bits (long[] bits)
static int idx (long i)
static void join (Tree tree, long[] bits0, long[] bits1, long[] bits2)
static long mask (long i)
static void or (long[] bits, long con)
static boolean test (long[] bits, int i)
Static Private Attributes
static final BitsRPC ANY = FULL.dual()
static final BitsRPC EMPTY = FULL.make()
static BitsRPC FREE =null
static HashMap< BitsRPC, BitsRPC > INTERN = new HashMap<>()
static final Bits.Tree< BitsRPC > TREE = new Bits.Tree<>()
Detailed Description
Definition at line 8 of file BitsRPC.java.
Member Function Documentation
abit()
int com.cliffc.aa.type.Bits< B extends Bits< B >.abit inherited
Definition at line 203 of file Bits.java.
 { return _bits==null&&_con!=0 ? _con : -1; }
above_center()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.above_center inherited
Definition at line 204 of file Bits.java.
 { return _con<0; }
ALL()
BitsRPC com.cliffc.aa.type.BitsRPC.ALL ()
Definition at line 37 of file BitsRPC.java.
 { return FULL; }
References com.cliffc.aa.type.BitsRPC.FULL.
and()
static void com.cliffc.aa.type.Bits< B extends Bits< B >.and (long[] bits, long con) static private inherited
Definition at line 282 of file Bits.java.
 { bits[idx(con)] &= ~mask(con); }
ANY()
BitsRPC com.cliffc.aa.type.BitsRPC.ANY ()
Definition at line 38 of file BitsRPC.java.
 { return ANY ; }
References com.cliffc.aa.type.BitsRPC.ANY().
Referenced by com.cliffc.aa.type.BitsRPC.ANY().
bitCount()
int com.cliffc.aa.type.Bits< B extends Bits< B >.bitCount inherited
Definition at line 113 of file Bits.java.
{
     if( _bits==null ) return _con==0 ? 0 : 1;
     int sum=0;
     for( long b : _bits )
       sum += Long.bitCount(b);
     return sum;
   }
bits()
static long [] com.cliffc.aa.type.Bits< B extends Bits< B >.bits (int b) static private inherited
Definition at line 283 of file Bits.java.
 { return new long[idx(b)+1]; }
bitset()
IBitSet com.cliffc.aa.type.Bits< B extends Bits< B >.bitset inherited
Definition at line 391 of file Bits.java.
{
     IBitSet bs = new IBitSet();
     for( int alias : this )
       bs.set(alias);
     return bs;
   }
check()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.check private inherited
Definition at line 89 of file Bits.java.
{
     if( _bits==null ) return true;  // Must be a single bit#
     if( _con != 1 && _con != -1 ) return false;
     if( _bits.length==0 ) return false;  // Empty bits replaced by a con
     if( _bits.length==1 && _bits[0]== 0 ) return false; // NO bits is bad, use EMPTY instead
     if( _bits[_bits.length-1]==0 ) return false; // Array is "tight"
     if( _bits.length==1 && _bits[0]==1 ) return true; // NIL
     // No set bit has a parent bit set, because the parent overrides
     Tree<B> tree = tree();
     for( int i : this )
       while( (i = tree.parent(i)) != 0 )
         if( test(i) )
           return false;
     // For efficiency, 1 bit set uses 'con' instead of 'bits'
     return check_multi_bits(_bits); // Found multiple bits
   }
check_multi_bits()
static boolean com.cliffc.aa.type.Bits< B extends Bits< B >.check_multi_bits (long[] bits) static private inherited
Definition at line 105 of file Bits.java.
{
     int len = bits.length;
     long b = bits[len-1];             // Last word
     if( (b & (b-1))!=0 ) return true; // Last word has multiple bits
     // Check multiple bits spread over multiple words
     for( int i=0; i<len-1; i++ ) if( bits[i] != 0 ) return true;
     return false;                // Found a single bit in last word
   }
clear()
B com.cliffc.aa.type.Bits< B extends Bits< B >.clear (int bit) inherited
Definition at line 255 of file Bits.java.
{
     if( !test(bit) ) return (B)this;
     if( _bits == null ) return EMPTY();
     long[] bs = _bits.clone();
     and(bs,bit);
     return make(_con==-1,bs);
   }
dual()
B com.cliffc.aa.type.Bits< B extends Bits< B >.dual inherited
Definition at line 368 of file Bits.java.
 { return make_impl(-_con,_bits); }
EMPTY()
BitsRPC com.cliffc.aa.type.BitsRPC.EMPTY ()
Definition at line 39 of file BitsRPC.java.
 { return EMPTY ; }
References com.cliffc.aa.type.BitsRPC.EMPTY().
Referenced by com.cliffc.aa.type.BitsRPC.EMPTY().
equals()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.equals (Object o) inherited
Definition at line 121 of file Bits.java.
{
     if( this==o ) return true;
     if( !(o instanceof Bits) ) return false;
     Bits bs = (Bits)o;
     if( _con != bs._con || _hash != bs._hash ) return false;
     if( _bits == bs._bits ) return true;
     if( _bits ==null || bs._bits==null ) return false;
     if( _bits.length != bs._bits.length ) return false;
     for( int i=0; i<_bits.length; i++ )
       if( _bits[i]!=bs._bits[i] ) return false;
     return true;
   }
getbit()
int com.cliffc.aa.type.Bits< B extends Bits< B >.getbit inherited
Definition at line 202 of file Bits.java.
 { assert _bits==null && _con!=0; return _con; }
hashCode()
int com.cliffc.aa.type.Bits< B extends Bits< B >.hashCode inherited
Definition at line 120 of file Bits.java.
 { return _hash; }
idx()
static int com.cliffc.aa.type.Bits< B extends Bits< B >.idx (long i) static private inherited
Definition at line 199 of file Bits.java.
 { return (int)(i>>6); }
init()
void com.cliffc.aa.type.Bits< B extends Bits< B >.init (int con, long[] bits) package inherited
Definition at line 80 of file Bits.java.
{
     _con = con;
     _bits=bits;
     long sum=_con;
     if( _bits != null ) for( long l : _bits ) sum += l;
     _hash = (int)((sum>>32)+sum);
     if( _hash==0 ) _hash=1;
     assert check();
   }
init0()
static void com.cliffc.aa.type.BitsRPC.init0 () static
Definition at line 28 of file BitsRPC.java.
 { TREE.init0(); }
References com.cliffc.aa.type.BitsRPC.TREE.
Referenced by com.cliffc.aa.Env.record_for_top_reset1().
is_con()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.is_con inherited
Definition at line 206 of file Bits.java.
 { return is_nil() || is_empty(); }
is_empty()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.is_empty inherited
Definition at line 207 of file Bits.java.
 { return _bits==null && _con==0; }
is_nil()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.is_nil inherited
Definition at line 208 of file Bits.java.
 { return _bits!=null && _bits.length==1 && _bits[0]==1; }
isa()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.isa (B bs) inherited
Definition at line 372 of file Bits.java.
 { return meet(bs) == bs; }
iterator()
Iterator<Integer> com.cliffc.aa.type.Bits< B extends Bits< B >.iterator inherited
Returns
an iterator
Definition at line 523 of file Bits.java.
 { return new Iter(); }
join() [1/2]
Bits<B> com.cliffc.aa.type.Bits< B extends Bits< B >.join (Bits< B > bs) inherited
Definition at line 370 of file Bits.java.
 { return dual().meet(bs.dual()).dual(); }
join() [2/2]
static void com.cliffc.aa.type.Bits< B extends Bits< B >.join (Tree tree, long[] bits0, long[] bits1, long[] bits2) static private inherited
Definition at line 349 of file Bits.java.
{
     // If a 'parent' bit is set, then no need to have any child bits set.
     for( int i=0; i<bits0.length; i++ ) { // For all words
       long l = bits0[i];
       if( l!=0 ) {
         // TODO: Use Long.numberOfTrailingZeros (or LeadingZeros probably) to
         // do this only once-per-set-bit.
         for( int j=0; j<64; j++ ) // For all bits in word
           if( (mask(j)&l) != 0 ) {
             for( int par = (i<<6)+j; par!=0; par = tree.parent(par) ) // Walk parent chain
               if( test(bits1,par) )                // If parent set
                 { bits2[i]|=mask(j); break; }      // then set kid
           }
       }
     }
   }
make() [1/3]
B com.cliffc.aa.type.Bits< B extends Bits< B >.make (boolean any, long[] bits) private inherited
Definition at line 154 of file Bits.java.
{
     // If a 'parent' bit is set, then no need to have any child bits set.
     Tree<B> tree = tree();
     // TODO: Run this loop backwards, avoids most tree-walks; lowers O(n log n) to O(n).
     for( int i=0; i<bits.length; i++ ) { // For all words
       long l = bits[i];
       if( l!=0 ) {
         for( int j=0; j<64; j++ ) // For all bits in word
           if( (mask(j)&l) != 0 ) {
             int par = (i<<6)+j; // Kid index
             while( (par = tree.parent(par)) != 0 ) // Walk parent chain
               if( test(bits,par) )                 // If parent set
                 { bits[i]&=~mask(j); break; }      // then clear kid
           }
       }
     }
     // Remove any trailing empty words
     int len = bits.length;
     while( len > 1 && bits[len-1]==0 ) len--;
     if( bits.length != len ) bits = Arrays.copyOf(bits,len);
     // Check for a single bit or NO bits
     if( check_multi_bits(bits) ) return make_impl(any ? -1 : 1,bits);
     // Special check for +/-0
     if( len==1 && bits[0]==1 ) return make_impl(any ? -1 : 1,bits);
     // Empty is self-dual, ignores 'any'
     if( len==1 && bits[0]==0 ) return make_impl(0,null);
     // Single bit
     int bnum0 = 63 - Long.numberOfLeadingZeros(bits[len-1]);
     int bnum = bnum0 + ((len-1)<<6);
     if( any ) bnum = -bnum;
     return make_impl(bnum,null);
   }
make() [2/3]
final B com.cliffc.aa.type.Bits< B extends Bits< B >.make (int bit) package inherited
Definition at line 189 of file Bits.java.
 { return bit==0 ? make_impl(1,new long[]{1}) : make_impl(bit,null); }
make() [3/3]
final B com.cliffc.aa.type.Bits< B extends Bits< B >.make (int... bits) inherited
Definition at line 191 of file Bits.java.
{
     int max= 0;                // Find max bit
     for( int bit : bits ) max=Math.max(max,bit);
     long[] ls = bits(max);  // Big enuf bits
     for( int bit : bits ) or(ls,bit);
     return make(false,ls);
   }
make0()
static BitsRPC com.cliffc.aa.type.BitsRPC.make0 (int bit) static package
Definition at line 41 of file BitsRPC.java.
 { return FULL.make(bit); }
References com.cliffc.aa.type.BitsRPC.FULL, and com.cliffc.aa.type.Bits< B extends Bits< B >.make().
Referenced by com.cliffc.aa.type.TypeRPC.make().
make_impl()
BitsRPC com.cliffc.aa.type.BitsRPC.make_impl (int con, long[] bits) package
Definition at line 13 of file BitsRPC.java.
{
     BitsRPC b1 = FREE;
     if( b1 == null ) b1 = new BitsRPC();
     else FREE = null;
     b1.init(con,bits);
     BitsRPC b2 = INTERN.get(b1);
     if( b2 != null ) { FREE = b1; return b2; }
     else { INTERN.put(b1,b1); return b1; }
   }
References com.cliffc.aa.type.Bits< BitsRPC >.bits(), com.cliffc.aa.type.BitsRPC.FREE, com.cliffc.aa.type.Bits< B extends Bits< B >.init(), and com.cliffc.aa.type.BitsRPC.INTERN.
mask()
static long com.cliffc.aa.type.Bits< B extends Bits< B >.mask (long i) static private inherited
Definition at line 200 of file Bits.java.
 { return 1L<<(i&63); }
max()
int com.cliffc.aa.type.Bits< B extends Bits< B >.max inherited
Definition at line 284 of file Bits.java.
                     {
     return _bits==null ? Math.abs(_con) : (63 - Long.numberOfLeadingZeros(_bits[_bits.length-1]))+((_bits.length-1)<<6);
   }
may_nil()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.may_nil package inherited
Definition at line 209 of file Bits.java.
 { return _con==-1 && _bits != null && ((_bits[0]&1) == 1); }
meet()
B com.cliffc.aa.type.Bits< B extends Bits< B >.meet (final B bs) inherited
Definition at line 298 of file Bits.java.
{
     if( this==bs ) return (B)this;
     B full = ALL();             // Subclass-specific version of full
     if( this==full || bs==full ) return full;
     B any  = ANY();             // Subclass-specific version of any
     if( this==any ) return bs;
     if( bs  ==any ) return (B)this;
     // Empty is a little odd; similar to meeting two JOIN sets with nothing in
     // common - it is on the center, and forces above values to fall, and
     // itself falls to below values.
     if( is_empty() ) return bs.above_center() ? (B)this : bs;
     if( bs.is_empty() ) return above_center() ? bs : (B)this;
     long[] bits0 = _bits, bits1 = bs._bits;
     int con0 = Math.abs(_con), con1 = Math.abs(bs._con);
     // Expand any single bits
     if( bits0==null ) or(bits0=bits(con0), con0);
     if( bits1==null ) or(bits1=bits(con1), con1);
     con0 =    _con < 0 ? -1 : 1;
     con1 = bs._con < 0 ? -1 : 1;
     // Bigger in bits0
     if( bits0.length < bits1.length ) { long[] tmp=bits0; bits0=bits1; bits1=tmp; int t=con0; con0=con1; con1=t; }
     // Both meets?  Set-union
     if( con0 == 1 && con1 == 1 ) {
       long[] bits = bits0.clone();        // Clone larger
       for( int i=0; i<bits1.length; i++ ) // OR in smaller bits
         bits[i] |= bits1[i];
       return make(false,bits);  // This will remove parent/child dups
     }
     // Both joins?  Set-intersection
     Tree<B> tree = tree();
     if( con0 == -1 && con1 == -1 ) {
       long[] bits = new long[bits0.length];// Result array
       join(tree,bits0,bits1,bits);         // Merge left into right
       join(tree,bits1,bits0,bits);         // Merge right into left
       // Nil is not part of the parent tree, so needs to be set explicitly
       if( (bits0[0]&1)==1 && (bits1[0]&1)==1 )  bits[0]|=1;
       // Just the intersection, which may be empty.
       return make(true,bits);
     }
     // Mixed meet/join.  Toss away the join, keep only the meet bits.
     return above_center() ? bs : (B)this;
   }
meet_nil()
B com.cliffc.aa.type.Bits< B extends Bits< B >.meet_nil inherited
Definition at line 212 of file Bits.java.
                       {
     if( above_center() ) return make(0); // Crossing centerline, drop all above bits, just [0]
     if( test(0) ) return (B)this;// Already has nil
     long[] bs = _bits;
     if( bs==null )              // Is a single compressed bit
       or(bs = bits(Math.abs(_con)),Math.abs(_con)); // Decompress single bit into array
     else bs = _bits.clone();    // Make a private set
     bs[0] |= 1;                 // Set nil
     return make(false,bs);      // Its below center now, even if the original was above
   }
new_rpc()
static int com.cliffc.aa.type.BitsRPC.new_rpc (int par) static
Definition at line 26 of file BitsRPC.java.
 { return TREE.split(par); }
References com.cliffc.aa.type.BitsRPC.TREE.
Referenced by com.cliffc.aa.node.CallNode.CallNode(), and com.cliffc.aa.node.CallNode.copy().
not_nil()
B com.cliffc.aa.type.Bits< B extends Bits< B >.not_nil package inherited
Definition at line 246 of file Bits.java.
               {
     if( !above_center() || _bits == null ) return (B)this;  // Some constant not-nil
     if( !test(_bits,0) ) return (B)this; // No nil choice
     long[] bs = _bits.clone();           // Keep all other bits
     and(bs,0);                           // remove nil choice
     return make(true,bs);                // Choices without nil
   }
oob()
TypeObj com.cliffc.aa.type.Bits< B extends Bits< B >.oob (TypeObj t) inherited
Definition at line 397 of file Bits.java.
 { return above_center() ? (TypeObj)t.dual() : t; }
or()
static void com.cliffc.aa.type.Bits< B extends Bits< B >.or (long[] bits, long con) static private inherited
Definition at line 281 of file Bits.java.
 { bits[idx(con)] |=  mask(con); }
overlaps()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.overlaps (Bits< B > bs) inherited
Definition at line 382 of file Bits.java.
{
     for( int alias : this )
       for( int kid=alias; kid!=0; kid = tree().next_kid(alias,kid) )
         if( bs.test_recur(kid) )
           return true;
     return false;
   }
reset_to_init0()
static void com.cliffc.aa.type.BitsRPC.reset_to_init0 () static
Definition at line 29 of file BitsRPC.java.
 { TREE.reset_to_init0(); }
References com.cliffc.aa.type.BitsRPC.TREE.
Referenced by com.cliffc.aa.Env.top_reset().
set()
B com.cliffc.aa.type.Bits< B extends Bits< B >.set (int bit) inherited
Definition at line 264 of file Bits.java.
{
     if( test(bit) ) return (B)this;
     B b = make(bit);
     if( this == EMPTY() ) return b;
     return meet(b);
   }
str()
SB com.cliffc.aa.type.Bits< B extends Bits< B >.str (SB sb) inherited
Definition at line 134 of file Bits.java.
{
     if( _bits==null ) {
       if( _con== 0 ) return sb.p("[]"); // EMPTY
       if( _con== 1 ) return sb.p("[ALL]");
       if( _con==-1 ) return sb.p("[ANY]");
       return sb.p('[').p(_con).p(']');
     }
     sb.p('[');
     if( above_center() ) sb.p('~');
     char sep = above_center()?'+':',';
     if( test(_bits,1) ) {
       if( test(_bits,0) ) sb.p('0').p(sep);
       return sb.p(above_center() ? "ANY]" : "ALL]");
     }
     for( Integer idx : this ) sb.p(idx).p(sep);
     return sb.unchar().p(']');
   }
strip_nil()
B com.cliffc.aa.type.Bits< B extends Bits< B >.strip_nil inherited
Definition at line 273 of file Bits.java.
{
     if( _bits == null ) return (B)this; // Should not be a nil to remove
     if( (_bits[0] &1)==0 ) return (B) this; // No nil
     long[] bs = _bits.clone();
     bs[0] &= ~1;                // Strip nil
     return make(_con==-1,bs);
   }
subtract()
Bits<B> com.cliffc.aa.type.Bits< B extends Bits< B >.subtract (Bits< B > bs) inherited
Definition at line 374 of file Bits.java.
{
     Bits<B> bs0 = this;
     for( int alias : this )
       for( int kid=alias; kid!=0; kid = tree().next_kid(alias,kid) )
         if( bs.test_recur(kid) )
           bs0 = bs0.clear(kid);
     return bs0;
   }
test() [1/2]
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.test (int i) inherited
Definition at line 226 of file Bits.java.
{
     if( _bits==null ) return i!=0 && i==Math.abs(_con);
     int idx = idx(i);
     return idx < _bits.length && test(_bits, i);
   }
test() [2/2]
static boolean com.cliffc.aa.type.Bits< B extends Bits< B >.test (long[] bits, int i) static private inherited
Definition at line 224 of file Bits.java.
 { return idx(i) < bits.length && (bits[idx(i)]&mask(i))!=0; }
test_recur()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.test_recur (int i) inherited
Definition at line 232 of file Bits.java.
{
     if( test(i) ) return true;
     Tree<B> tree = tree();
     while( (i = tree.parent(i)) != 0 )
       if( test(i) )
         return true;
     return false;
   }
toString()
String com.cliffc.aa.type.Bits< B extends Bits< B >.toString inherited
Definition at line 133 of file Bits.java.
 { return str(new SB()).toString(); }
tree()
Tree<BitsRPC> com.cliffc.aa.type.BitsRPC.tree () package
Definition at line 24 of file BitsRPC.java.
 { return TREE; }
References com.cliffc.aa.type.BitsRPC.TREE.
Member Data Documentation
_bits
long [] com.cliffc.aa.type.Bits< B extends Bits< B >._bits package inherited
Definition at line 68 of file Bits.java.
_con
int com.cliffc.aa.type.Bits< B extends Bits< B >._con package inherited
Definition at line 69 of file Bits.java.
_hash
int com.cliffc.aa.type.Bits< B extends Bits< B >._hash package inherited
Definition at line 70 of file Bits.java.
ALL
final int com.cliffc.aa.type.BitsRPC.ALL = new_rpc(0) static
Definition at line 25 of file BitsRPC.java.
Referenced by com.cliffc.aa.node.CallNode.CallNode().
ANY
final BitsRPC com.cliffc.aa.type.BitsRPC.ANY = FULL.dual() static private
Definition at line 34 of file BitsRPC.java.
EMPTY
final BitsRPC com.cliffc.aa.type.BitsRPC.EMPTY = FULL.make() static private
Definition at line 36 of file BitsRPC.java.
FREE
BitsRPC com.cliffc.aa.type.BitsRPC.FREE =null static private
Definition at line 12 of file BitsRPC.java.
Referenced by com.cliffc.aa.type.BitsRPC.make_impl().
FULL
final BitsRPC com.cliffc.aa.type.BitsRPC.FULL = new BitsRPC().make_impl(1,new long[]{1L | (1L<<ALL)}) static package
Definition at line 33 of file BitsRPC.java.
Referenced by com.cliffc.aa.type.BitsRPC.ALL(), and com.cliffc.aa.type.BitsRPC.make0().
INTERN
HashMap<BitsRPC,BitsRPC> com.cliffc.aa.type.BitsRPC.INTERN = new HashMap<>() static private
Definition at line 11 of file BitsRPC.java.
Referenced by com.cliffc.aa.type.BitsRPC.make_impl().
NIL
final BitsRPC com.cliffc.aa.type.BitsRPC.NIL = make0(0) static
Definition at line 35 of file BitsRPC.java.
Referenced by com.cliffc.aa.type.TypeRPC.meet_nil().
TREE
final Bits.Tree<BitsRPC> com.cliffc.aa.type.BitsRPC.TREE = new Bits.Tree<>() static private
Definition at line 23 of file BitsRPC.java.
Referenced by com.cliffc.aa.type.BitsRPC.init0(), com.cliffc.aa.type.BitsRPC.new_rpc(), com.cliffc.aa.type.BitsRPC.reset_to_init0(), and com.cliffc.aa.type.BitsRPC.tree().
The documentation for this class was generated from the following file:
BitsRPC.java