aa: com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV Class Reference
com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV Class Reference
Public Member Functions
SnapshotV ()
boolean hasMoreElements ()
boolean hasNext ()
TypeV next ()
TypeV nextElement ()
void remove ()
void removeKey ()
Package Functions
long key (final int idx)
int length ()
Package Attributes
long _prevK
TypeV _prevV
final CHM _sschm
Private Attributes
int _idx
long _nextK
TypeV _nextV
Detailed Description
Definition at line 1029 of file NonBlockingHashMapLong.java.
Constructor & Destructor Documentation
SnapshotV()
com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.SnapshotV ()
Definition at line 1031 of file NonBlockingHashMapLong.java.
{
       CHM topchm;
       while( true ) {           // Verify no table-copy-in-progress
         topchm = _chm;
         if( topchm._newchm == null ) // No table-copy-in-progress
           break;
         // Table copy in-progress - so we cannot get a clean iteration.  We
         // must help finish the table copy before we can start iterating.
         topchm.help_copy_impl(true);
       }
       // The "linearization point" for the iteration.  Every key in this table
       // will be visited, but keys added later might be skipped or even be
       // added to a following table (also not iterated over).
       _sschm = topchm;
       // Warm-up the iterator
       _idx = -1;
       next();
     }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >._chm, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._idx, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.CHM._newchm, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._sschm, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.CHM.help_copy_impl(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.next().
Member Function Documentation
hasMoreElements()
boolean com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.hasMoreElements ()
Definition at line 1096 of file NonBlockingHashMapLong.java.
 { return hasNext(); }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.hasNext().
hasNext()
boolean com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.hasNext ()
Definition at line 1054 of file NonBlockingHashMapLong.java.
 { return _nextV != null; }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._nextV.
Referenced by com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.hasMoreElements(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.hasNext(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE.hasNext().
key()
long com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.key (final int idx) package
Definition at line 1050 of file NonBlockingHashMapLong.java.
 { return _sschm._keys[idx]; }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.CHM._keys, and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._sschm.
Referenced by com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.next().
length()
int com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.length () package
Definition at line 1049 of file NonBlockingHashMapLong.java.
 { return _sschm._keys.length; }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.CHM._keys, and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._sschm.
Referenced by com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.next().
next()
TypeV com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.next ()
Definition at line 1055 of file NonBlockingHashMapLong.java.
{
       // 'next' actually knows what the next value will be - it had to
       // figure that out last go 'round lest 'hasNext' report true and
       // some other thread deleted the last value.  Instead, 'next'
       // spends all its effort finding the key that comes after the
       // 'next' key.
       if( _idx != -1 && _nextV == null ) throw new NoSuchElementException();
       _prevK = _nextK;          // This will become the previous key
       _prevV = _nextV;          // This will become the previous value
       _nextV = null;            // We have no more next-key
       // Attempt to set <_nextK,_nextV> to the next K,V pair.
       // _nextV is the trigger: stop searching when it is != null
       if( _idx == -1 ) {        // Check for NO_KEY
         _idx = 0;               // Setup for next phase of search
         _nextK = NO_KEY;
         if( (_nextV=get(_nextK)) != null ) return _prevV;
       }
       while( _idx<length() ) {  // Scan array
         _nextK = key(_idx++); // Get a key that definitely is in the set (for the moment!)
         if( _nextK != NO_KEY && // Found something?
             (_nextV=get(_nextK)) != null )
           break;                // Got it!  _nextK is a valid Key
       }                         // Else keep scanning
       return _prevV;            // Return current value.
     }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._idx, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._nextK, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._nextV, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._prevK, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._prevV, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.key(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.length(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.NO_KEY.
Referenced by com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.next(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE.next(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.nextElement(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.nextLong(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.SnapshotV().
nextElement()
TypeV com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.nextElement ()
Definition at line 1095 of file NonBlockingHashMapLong.java.
 { return next(); }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.next().
remove()
void com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.remove ()
Definition at line 1088 of file NonBlockingHashMapLong.java.
{
       // NOTE: it would seem logical that value removal will semantically mean
       // removing the matching value for the mapping <k,v>, but the JDK always
       // removes by key, even when the value has changed.
       removeKey();
     }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.removeKey().
removeKey()
void com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.removeKey ()
Definition at line 1081 of file NonBlockingHashMapLong.java.
{
       if( _prevV == null ) throw new IllegalStateException();
       NonBlockingHashMapLong.this.putIfMatch( _prevK, TOMBSTONE, NO_MATCH_OLD);
       _prevV = null;
     }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._prevK, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._prevV, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.NO_MATCH_OLD, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.putIfMatch(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.TOMBSTONE.
Referenced by com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.remove(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.remove(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE.remove().
Member Data Documentation
_idx
int com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._idx private
Definition at line 1051 of file NonBlockingHashMapLong.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.next(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.SnapshotV().
_nextK
long com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._nextK private
Definition at line 1052 of file NonBlockingHashMapLong.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.next().
_nextV
TypeV com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._nextV private
Definition at line 1053 of file NonBlockingHashMapLong.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.hasNext(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.next().
_prevK
long com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._prevK package
Definition at line 1052 of file NonBlockingHashMapLong.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.next(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.next(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE.next(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.IteratorLong.nextLong(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.removeKey().
_prevV
TypeV com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._prevV package
Definition at line 1053 of file NonBlockingHashMapLong.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.next(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE.next(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.removeKey().
_sschm
final CHM com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._sschm package
Definition at line 1030 of file NonBlockingHashMapLong.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.key(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.length(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.SnapshotV().
The documentation for this class was generated from the following file:
NonBlockingHashMapLong.java