aa: com.cliffc.aa.HM.TestHM6 Class Reference
com.cliffc.aa.HM.TestHM6 Class Reference
Public Member Functions
void reset ()
void test00 ()
void test01 ()
void test02 ()
void test03 ()
void test04 ()
void test05 ()
void test06 ()
void test07 ()
void test08 ()
void test09 ()
void test10 ()
void test11 ()
void test12 ()
void test13 ()
void test14 ()
void test15 ()
void test16 ()
void test17 ()
void test18 ()
void test19 ()
void test20 ()
void test21 ()
void test22 ()
void test23 ()
Detailed Description
Definition at line 10 of file TestHM6.java.
Member Function Documentation
reset()
void com.cliffc.aa.HM.TestHM6.reset ()
Definition at line 12 of file TestHM6.java.
 { HM.reset(); }
References com.cliffc.aa.HM.HM.reset().
test00()
void com.cliffc.aa.HM.TestHM6.test00 ()
Definition at line 15 of file TestHM6.java.
{
     HM6.hm("fred");
   }
References com.cliffc.aa.HM.HM6.hm().
test01()
void com.cliffc.aa.HM.TestHM6.test01 ()
Definition at line 20 of file TestHM6.java.
{
     Syntax syn = new Con(TypeInt.con(3));
     T2 t = HM6.hm("3");
     assertEquals("3",t.p());
   }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test02()
void com.cliffc.aa.HM.TestHM6.test02 ()
Definition at line 27 of file TestHM6.java.
{
     T2 t = HM6.hm("(pair1 3)");
     assertEquals("{ V24 -> (pair 3 V24) }",t.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test03()
void com.cliffc.aa.HM.TestHM6.test03 ()
Definition at line 33 of file TestHM6.java.
{
     T2 t = HM6.hm("{ z -> (pair (z 3) (z \"abc\")) }");
     assertEquals("{ { all -> V23 } -> (pair V23 V23) }",t.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test04()
void com.cliffc.aa.HM.TestHM6.test04 ()
Definition at line 39 of file TestHM6.java.
{
     T2 t = HM6.hm("fact = { n -> (if/else (==0 n) 1 (* n (fact (dec n))))}; fact");
     assertEquals("{ int64 -> int64 }",t.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test05()
void com.cliffc.aa.HM.TestHM6.test05 ()
Definition at line 45 of file TestHM6.java.
{
     // Because {y->y} is passed in, all 'y' types must agree.
     // This unifies 3 and "abc" which results in 'all'
     T2 t1 = HM6.hm("({ x -> (pair (x 3) (x \"abc\")) } {y->y})");
     assertEquals("(pair all all)",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test06()
void com.cliffc.aa.HM.TestHM6.test06 ()
Definition at line 53 of file TestHM6.java.
{
     // recursive unification
     T2 t1 = HM6.hm("{ f -> (f f) }");
     assertEquals("{ $25:{ $25 -> V21 } -> V21 }",t1.p());
     // We can argue the pretty-print should print:
     // "$26:{ $26 -> V21 }"
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test07()
void com.cliffc.aa.HM.TestHM6.test07 ()
Definition at line 62 of file TestHM6.java.
{
     T2 t1 = HM6.hm("g = {f -> 5}; (g g)");
     assertEquals("5",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test08()
void com.cliffc.aa.HM.TestHM6.test08 ()
Definition at line 68 of file TestHM6.java.
{
     // example that demonstrates generic and non-generic variables:
     T2 t1 = HM6.hm("{ g -> f = { x -> g }; (pair (f 3) (f \"abc\"))}");
     assertEquals("{ V21 -> (pair V21 V21) }",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test09()
void com.cliffc.aa.HM.TestHM6.test09 ()
Definition at line 75 of file TestHM6.java.
{
     T2 t1 = HM6.hm("{ f g -> (f g)}");
     assertEquals("{ { V20 -> V22 } V20 -> V22 }",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test10()
void com.cliffc.aa.HM.TestHM6.test10 ()
Definition at line 81 of file TestHM6.java.
{
     // Function composition
     T2 t1 = HM6.hm("{ f g -> { arg -> (g (f arg))} }");
     assertEquals("{ { V19 -> V26 } { V26 -> V24 } -> { V19 -> V24 } }",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test11()
void com.cliffc.aa.HM.TestHM6.test11 ()
Definition at line 88 of file TestHM6.java.
{
     // Stacked functions ignoring all function arguments
     T2 t1 = HM6.hm("map = { fun -> { x -> 2 } }; ((map 3) 5)");
     assertEquals("2",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test12()
void com.cliffc.aa.HM.TestHM6.test12 ()
Definition at line 95 of file TestHM6.java.
{
     // map takes a function and an element (collection?) and applies it (applies to collection?)
     T2 t1 = HM6.hm("map = { fun -> { x -> (fun x)}}; { p -> 5 }");
     assertEquals("{ V21 -> 5 }",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test13()
void com.cliffc.aa.HM.TestHM6.test13 ()
Definition at line 102 of file TestHM6.java.
{
     // Looking at when tvars are duplicated ("fresh" copies made).
     // This is the "map" problem with a scalar instead of a collection.
     // Takes a '{a->b}' and a 'a' for a couple of different prims.
     T2 t1 = HM6.hm("map = { fun -> { x -> (fun x)}};"+
                   "(pair ((map str) 5) ((map factor) 2.3))");
     assertEquals("(pair str (divmod flt64 flt64))",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test14()
void com.cliffc.aa.HM.TestHM6.test14 ()
Definition at line 112 of file TestHM6.java.
{
     // map takes a function and an element (collection?) and applies it (applies to collection?)
     T2 t1 = HM6.hm("map = { fun x -> (fun x)}; (map {a->3} 5)");
     assertEquals("3",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test15()
void com.cliffc.aa.HM.TestHM6.test15 ()
Definition at line 119 of file TestHM6.java.
{
     // map takes a function and an element (collection?) and applies it (applies to collection?)
     T2 t1 = HM6.hm("map = { fun x -> (fun x)}; (map { a-> (pair a a)} 5)");
     assertEquals("(pair 5 5)",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test16()
void com.cliffc.aa.HM.TestHM6.test16 ()
Definition at line 126 of file TestHM6.java.
{
     T2 t1 = HM6.hm("fcn = { p -> { a -> (pair a a) }};"+
                   "map = { fun x -> (fun x)};"+
                   "{ q -> (map (fcn q) 5)}");
     assertEquals("{ V23 -> (pair 5 5) }",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test17()
void com.cliffc.aa.HM.TestHM6.test17 ()
Definition at line 134 of file TestHM6.java.
{
     // Checking behavior when using "if/else" to merge two functions with
     // sufficiently different signatures, then attempting to pass them to a map
     // & calling internally.
     // fcn takes a predicate 'p' and returns one of two fcns.
     //   let fcn = { p -> (if/else p {a -> pair[a,a        ]}
     //                               {b -> pair[b,pair[3,b]]}) } in
     // map takes a function and an element (collection?) and applies it (applies to collection?)
     //   let map = { fun x -> (fun x) }
     //          in { q -> ((map (fcn q)) 5) }
     // Should return { q -> q ? [5,5] : [5,[3,5]] }
     // Ultimately, unifies "a" with "pair[3,a]" which throws recursive unification.
     T2 t1 = HM6.hm("fcn = {p -> (if/else p {a -> (pair a a)} {b -> (pair b (pair 3 b))})};"+
                   "map = { fun x -> (fun x)};"+
                   "{ q -> (map (fcn q) 5)}");
     assertEquals("TBD",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test18()
void com.cliffc.aa.HM.TestHM6.test18 ()
Definition at line 153 of file TestHM6.java.
{
     T2 t1 = HM6.hm("cons ={x y-> {cadr -> (cadr x y)}};"+
                   "cdr ={mycons -> (mycons { p q -> q})};"+
                   "(cdr (cons 2 3))");
     assertEquals("3",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test19()
void com.cliffc.aa.HM.TestHM6.test19 ()
Definition at line 168 of file TestHM6.java.
{
     T2 t1 = HM6.hm("cons ={x y-> {cadr -> (cadr x y)}};"+
                   "cdr ={mycons -> (mycons { p q -> q})};"+
                   "map ={fun parg -> (fun (cdr parg))};"+
                   "(pair (map str (cons 0 5)) (map isempty (cons 0 \"abc\")))"
                   );
     assertEquals("(pair str int1)",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test20()
void com.cliffc.aa.HM.TestHM6.test20 ()
Definition at line 179 of file TestHM6.java.
{
     T2 t1 = HM6.hm("f0 = { f x -> (if/else (==0 x) 1 (f (f0 f (dec x)) 2))}; (f0 * 99)");
     assertEquals("int64",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test21()
void com.cliffc.aa.HM.TestHM6.test21 ()
Definition at line 186 of file TestHM6.java.
{
     // let f0 = fn f x => (if/else (==0 x) 1 (* (f0 f (dec x)) 2) ) in f0 f0 99
     // let f0 = fn f x => (if/else (==0 x) 1 (f (f0 f (dec x)) 2) ) in f0 *  99
     T2 t1 = HM6.hm("f0 = { f x -> (if/else (==0 x) 1 (* (f0 f (dec x)) 2))}; (f0 f0 99)");
     assertEquals("int64",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test22()
void com.cliffc.aa.HM.TestHM6.test22 ()
Definition at line 195 of file TestHM6.java.
{
     T2 t1 = HM6.hm("is_even = "+
                   "  is_odd = { n -> (if/else (==0 n) 0 (is_even (dec n)))}; "+
                   "     { n -> (if/else (==0 n) 1 (is_odd (dec n)))};"+
                   "(is_even 3)"
                   );
     assertEquals("int1",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
test23()
void com.cliffc.aa.HM.TestHM6.test23 ()
Definition at line 206 of file TestHM6.java.
{
     T2 t1 = HM6.hm("{ g -> fgz = "+
                   "         cons = {x y -> {cadr -> (cadr x y)}};"+
                   "         cdr = {mycons -> (mycons { p q -> q})};"+
                   "         (cdr (cons 2 { z -> (g z) }));"+
                   "      (pair (fgz 3) (fgz 5))"+
                   "}"
                   );
     assertEquals("{ { nint8 -> V44 } -> (pair V44 V44) }",t1.p());
   }
References com.cliffc.aa.HM.HM6.hm(), and com.cliffc.aa.HM.HM7.T2.p().
The documentation for this class was generated from the following file:
TestHM6.java