aa: com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotK Class Reference
com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotK Class Reference
Public Member Functions
SnapshotK ()
boolean hasMoreElements ()
boolean hasNext ()
TypeK next ()
TypeK nextElement ()
void remove ()
Package Attributes
final SnapshotV _ss
Detailed Description
Definition at line 1276 of file NonBlockingHashMap.java.
Constructor & Destructor Documentation
SnapshotK()
com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotK.SnapshotK ()
Definition at line 1278 of file NonBlockingHashMap.java.
 { _ss = new SnapshotV(); }
Member Function Documentation
hasMoreElements()
boolean com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotK.hasMoreElements ()
Definition at line 1283 of file NonBlockingHashMap.java.
 { return hasNext(); }
hasNext()
boolean com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotK.hasNext ()
Definition at line 1281 of file NonBlockingHashMap.java.
 { return _ss.hasNext(); }
References com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.hasNext().
next()
TypeK com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotK.next ()
Definition at line 1280 of file NonBlockingHashMap.java.
 { _ss.next(); return (TypeK)_ss._prevK; }
References com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._prevK, and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.next().
nextElement()
TypeK com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotK.nextElement ()
Definition at line 1282 of file NonBlockingHashMap.java.
 { return next(); }
remove()
void com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotK.remove ()
Definition at line 1279 of file NonBlockingHashMap.java.
 { _ss.remove(); }
References com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.remove().
Member Data Documentation
_ss
final SnapshotV com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotK._ss package
Definition at line 1277 of file NonBlockingHashMap.java.
The documentation for this class was generated from the following file:
NonBlockingHashMap.java