aa: com.cliffc.aa.HM.HM Class Reference
com.cliffc.aa.HM.HM Class Reference
Classes
class Add
class Apply
class Con
class Dec
class EQ
class EQ0
class Factor
class Field
class Ident
class If
class IsEmpty
class Lambda
class Let
class Mul
class NotNil
class Pair
class Pair1
class PrimSyn
class Root
class Str
class Struct
class Syntax
class T2
class Triple
class VStack
class Worklist
Public Member Functions
String toString ()
Static Public Member Functions
static Root hm (String sprog)
Static Package Functions
[static initializer]
static Root parse (String s)
static void reset ()
static Syntax term ()
Static Package Attributes
static final boolean DEBUG_LEAKS =false
static final boolean DO_GCP = true
static final boolean DO_HM = true
static final HashMap< String, PrimSyn > PRIMSYNS = new HashMap<>()
Static Private Member Functions
static Syntax fterm ()
static String id ()
static boolean isAlpha0 (byte c)
static boolean isAlpha1 (byte c)
static boolean isDigit (byte c)
static boolean isWS (byte c)
static Syntax number ()
static void require (char c)
static< T > T require (char c, T t)
static void require (String s)
static byte skipWS ()
static Syntax string ()
Static Private Attributes
static byte[] BUF
static final SB ID = new SB()
static int X
Detailed Description
Definition at line 84 of file HM.java.
Member Function Documentation
[static initializer]()
com.cliffc.aa.HM.HM.[static initializer] static package
fterm()
static Syntax com.cliffc.aa.HM.HM.fterm () static private
Definition at line 231 of file HM.java.
{
     Syntax term=term();
     while( true ) {
       if( term==null || skipWS()!='.' ) return term;
       X++;
       term = new Field(id(),term);
     }
   }
References com.cliffc.aa.HM.HM.skipWS(), com.cliffc.aa.HM.HM.term(), and com.cliffc.aa.HM.HM.X.
Referenced by com.cliffc.aa.HM.HM.parse(), and com.cliffc.aa.HM.HM.term().
hm()
static Root com.cliffc.aa.HM.HM.hm (String sprog) static
Definition at line 94 of file HM.java.
{
     Worklist work = new Worklist();
     PrimSyn.WORK=work;
     for( PrimSyn prim : new PrimSyn[]{new If(), new Pair1(), new Pair(), new EQ(), new EQ0(), new Mul(), new Add(), new Dec(), new Str(), new Triple(), new Factor(), new IsEmpty(), new NotNil()} )
       PRIMSYNS.put(prim.name(),prim);
     // Parse
     Root prog = parse( sprog );
     // Prep for SSA: pre-gather all the (unique) ids
     int cnt_syns = prog.prep_tree(null,null,work);
     int init_T2s = T2.CNT;
     while( work.len()>0 ) {     // While work
       int oldcnt = T2.CNT;      // Used for cost-check when no-progress
       assert work._cnt<2000;
       Syntax syn = work.pop();  // Get work
       if( DO_HM ) {
         T2 old = syn._hmt;        // Old value for progress assert
         if( syn.hm(work) ) {
           assert !syn.debug_find().unify(old.find(),null);// monotonic: unifying with the result is no-progress
           syn.add_hm_work(work);     // Push affected neighbors on worklist
         } else {
           assert !DEBUG_LEAKS || oldcnt==T2.CNT;  // No-progress consumes no-new-T2s
         }
       }
       if( DO_GCP ) {
         Type old = syn._flow;
         Type t = syn.val(work);
         if( t!=old ) {           // Progress
           assert old.isa(t);     // Monotonic falling
           syn._flow = t;         // Update type
           if( syn._par!=null ) { // Generally, parent needs revisit
             work.push(syn._par); // Assume parent needs revisit
             syn._par.add_val_work(syn,work); // Push affected neighbors on worklist
           }
         }
       }
       // VERY EXPENSIVE ASSERT: O(n^2).  Every Syntax that makes progress is on the worklist
       assert prog.more_work(work);
     }
     assert prog.more_work(work);
     System.out.println("Initial T2s: "+init_T2s+", Prog size: "+cnt_syns+", worklist iters: "+work._cnt+", T2s: "+T2.CNT);
     return prog;
   }
References com.cliffc.aa.HM.HM.Worklist._cnt, com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.Syntax._par, com.cliffc.aa.HM.HM.Syntax.add_hm_work(), com.cliffc.aa.HM.HM.Syntax.add_val_work(), com.cliffc.aa.HM.HM.T2.CNT, com.cliffc.aa.HM.HM.Syntax.debug_find(), com.cliffc.aa.HM.HM.DEBUG_LEAKS, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.T2.find(), com.cliffc.aa.HM.HM.Syntax.hm(), com.cliffc.aa.type.Type< T extends Type< T >.isa(), com.cliffc.aa.HM.HM.Worklist.len(), com.cliffc.aa.HM.HM.Apply.more_work(), com.cliffc.aa.HM.HM.parse(), com.cliffc.aa.HM.HM.Worklist.pop(), com.cliffc.aa.HM.HM.Apply.prep_tree(), com.cliffc.aa.HM.HM.PRIMSYNS, com.cliffc.aa.HM.HM.Worklist.push(), com.cliffc.aa.HM.HM.T2.unify(), com.cliffc.aa.HM.HM.Syntax.val(), and com.cliffc.aa.HM.HM.PrimSyn.WORK.
Referenced by com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.HM.TestHM.test05(), com.cliffc.aa.HM.TestHM.test06(), com.cliffc.aa.HM.TestHM.test14(), com.cliffc.aa.HM.TestHM.test18(), com.cliffc.aa.HM.TestHM.test20(), com.cliffc.aa.HM.TestHM.test32(), com.cliffc.aa.HM.TestHM.test33(), com.cliffc.aa.HM.TestHM.test34(), com.cliffc.aa.HM.TestHM.test36(), com.cliffc.aa.HM.TestHM.test39(), com.cliffc.aa.HM.TestHM.test40(), com.cliffc.aa.HM.TestHM.test41(), com.cliffc.aa.HM.TestHM.test42(), com.cliffc.aa.HM.TestHM.test43(), com.cliffc.aa.HM.TestHM.test44(), com.cliffc.aa.HM.TestHM.test45(), com.cliffc.aa.HM.TestHM.test49(), com.cliffc.aa.HM.TestHM.test50(), com.cliffc.aa.HM.TestHM.test51(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.HM.TestHM.test55(), com.cliffc.aa.HM.TestHM.test56(), and com.cliffc.aa.HM.TestHM.test57().
id()
static String com.cliffc.aa.HM.HM.id () static private
Definition at line 240 of file HM.java.
{
     ID.clear();
     while( X<BUF.length && isAlpha1(BUF[X]) )
       ID.p((char)BUF[X++]);
     String s = ID.toString().intern();
     if( s.length()==0 ) throw unimpl("Missing id");
     return s;
   }
References com.cliffc.aa.HM.HM.BUF, com.cliffc.aa.util.SB.clear(), com.cliffc.aa.HM.HM.ID, com.cliffc.aa.HM.HM.isAlpha1(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.util.SB.toString(), and com.cliffc.aa.HM.HM.X.
Referenced by com.cliffc.aa.HM.HM.T2.add_fld(), com.cliffc.aa.HM.HM.Field.Field(), and com.cliffc.aa.HM.HM.term().
isAlpha0()
static boolean com.cliffc.aa.HM.HM.isAlpha0 (byte c) static private
Definition at line 274 of file HM.java.
 { return ('a'<=c && c <= 'z') || ('A'<=c && c <= 'Z') || (c=='_') || (c=='*') || (c=='?') || (c=='+'); }
Referenced by com.cliffc.aa.HM.HM.isAlpha1(), com.cliffc.aa.HM.HM.number(), and com.cliffc.aa.HM.HM.term().
isAlpha1()
static boolean com.cliffc.aa.HM.HM.isAlpha1 (byte c) static private
Definition at line 275 of file HM.java.
 { return isAlpha0(c) || ('0'<=c && c <= '9') || (c=='/'); }
References com.cliffc.aa.HM.HM.isAlpha0().
Referenced by com.cliffc.aa.HM.HM.id().
isDigit()
static boolean com.cliffc.aa.HM.HM.isDigit (byte c) static private
Definition at line 273 of file HM.java.
 { return '0' <= c && c <= '9'; }
Referenced by com.cliffc.aa.HM.HM.T2.is_tuple(), com.cliffc.aa.HM.HM.number(), and com.cliffc.aa.HM.HM.term().
isWS()
static boolean com.cliffc.aa.HM.HM.isWS (byte c) static private
Definition at line 272 of file HM.java.
 { return c == ' ' || c == '\t' || c == '\n' || c == '\r'; }
Referenced by com.cliffc.aa.HM.HM.skipWS().
number()
static Syntax com.cliffc.aa.HM.HM.number () static private
Definition at line 248 of file HM.java.
{
     if( BUF[X]=='0' ) { X++; return new Con(Type.XNIL); }
     int sum=0;
     while( X<BUF.length && isDigit(BUF[X]) )
       sum = sum*10+BUF[X++]-'0';
     if( X>= BUF.length || BUF[X]!='.' )
       return new Con(TypeInt.con(sum));
     // Ambiguous '.' in: 2.3 vs 2.x (field load from a number)
     if( X+1<BUF.length && isAlpha0(BUF[X+1]) )
       return new Con(TypeInt.con(sum));
     X++;
     float f = (float)sum;
     f = f + (BUF[X++]-'0')/10.0f;
     return new Con(TypeFlt.con(f));
   }
References com.cliffc.aa.HM.HM.BUF, com.cliffc.aa.type.TypeFlt.con(), com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM.isAlpha0(), com.cliffc.aa.HM.HM.isDigit(), com.cliffc.aa.HM.HM.X, and com.cliffc.aa.type.Type< T extends Type< T >.XNIL.
Referenced by com.cliffc.aa.HM.HM.term().
parse()
static Root com.cliffc.aa.HM.HM.parse (String s) static package
Definition at line 158 of file HM.java.
{
     X = 0;
     BUF = s.getBytes();
     Syntax prog = fterm();
     if( skipWS() != -1 ) throw unimpl("Junk at end of program: "+new String(BUF,X,BUF.length-X));
     // Inject IF at root
     return new Root(prog);
   }
References com.cliffc.aa.HM.HM.BUF, com.cliffc.aa.HM.HM.fterm(), com.cliffc.aa.HM.HM.skipWS(), and com.cliffc.aa.HM.HM.X.
Referenced by com.cliffc.aa.HM.HM.hm().
require() [1/3]
static void com.cliffc.aa.HM.HM.require (char c) static private
Definition at line 276 of file HM.java.
 { if( skipWS()!=c ) throw unimpl("Missing '"+c+"'"); X++; }
References com.cliffc.aa.HM.HM.skipWS(), and com.cliffc.aa.HM.HM.X.
Referenced by com.cliffc.aa.HM.HM.string(), and com.cliffc.aa.HM.HM.term().
require() [2/3]
static <T> T com.cliffc.aa.HM.HM.require (char c, T t) static private
Definition at line 277 of file HM.java.
 { require(c); return t; }
References com.cliffc.aa.HM.HM.require().
Referenced by com.cliffc.aa.HM.HM.require().
require() [3/3]
static void com.cliffc.aa.HM.HM.require (String s) static private
Definition at line 278 of file HM.java.
{
     skipWS();
     for( int i=0; i<s.length(); i++ )
       if( X+i >= BUF.length || BUF[X+i]!=s.charAt(i) )
         throw unimpl("Missing '"+s+"'");
     X+=s.length();
   }
References com.cliffc.aa.HM.HM.BUF, com.cliffc.aa.HM.HM.skipWS(), and com.cliffc.aa.HM.HM.X.
reset()
static void com.cliffc.aa.HM.HM.reset () static package
Definition at line 143 of file HM.java.
                       {
     BitsAlias.reset_to_init0();
     BitsFun.reset_to_init0();
     PRIMSYNS.clear();
     Pair1.PAIR1S.clear();
     Lambda.FUNS.clear();
     T2.reset();
     PrimSyn.reset();
   }
References com.cliffc.aa.HM.HM.Lambda.FUNS, com.cliffc.aa.HM.HM.Pair1.PAIR1S, com.cliffc.aa.HM.HM.PRIMSYNS, com.cliffc.aa.HM.HM.PrimSyn.reset(), com.cliffc.aa.HM.HM.T2.reset(), com.cliffc.aa.type.BitsFun.reset_to_init0(), and com.cliffc.aa.type.BitsAlias.reset_to_init0().
Referenced by com.cliffc.aa.HM.TestHM.reset(), com.cliffc.aa.HM.TestHM6.reset(), and com.cliffc.aa.HM.TestHM9.reset().
skipWS()
static byte com.cliffc.aa.HM.HM.skipWS () static private
Definition at line 268 of file HM.java.
{
     while( X<BUF.length && isWS(BUF[X]) ) X++;
     return X==BUF.length ? -1 : BUF[X];
   }
References com.cliffc.aa.HM.HM.BUF, com.cliffc.aa.HM.HM.isWS(), and com.cliffc.aa.HM.HM.X.
Referenced by com.cliffc.aa.HM.HM.fterm(), com.cliffc.aa.HM.HM.parse(), com.cliffc.aa.HM.HM.require(), and com.cliffc.aa.HM.HM.term().
string()
static Syntax com.cliffc.aa.HM.HM.string () static private
Definition at line 263 of file HM.java.
{
     int start = ++X;
     while( X<BUF.length && BUF[X]!='"' ) X++;
     return require('"', new Con(TypeMemPtr.make(BitsAlias.STRBITS,TypeStr.con(new String(BUF,start,X-start).intern()))));
   }
References com.cliffc.aa.HM.HM.BUF, com.cliffc.aa.type.TypeStr.con(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.HM.HM.require(), com.cliffc.aa.type.BitsAlias.STRBITS, and com.cliffc.aa.HM.HM.X.
Referenced by com.cliffc.aa.HM.HM.term().
term()
static Syntax com.cliffc.aa.HM.HM.term () static package
Definition at line 166 of file HM.java.
{
     if( skipWS()==-1 ) return null;
     if( isDigit(BUF[X]) ) return number();
     if( BUF[X]=='"' ) return string();
     if( BUF[X]=='(' ) {         // Parse an Apply
       X++;                      // Skip paren
       Syntax fun = fterm();
       Ary<Syntax> args = new Ary<>(new Syntax[1],0);
       while( skipWS()!= ')' && X<BUF.length ) args.push(fterm());
       require(')');
       // Guarding if-nil test inserts an upcast.  This is a syntatic transform only.
       if( fun instanceof If &&
           args.at(0) instanceof Ident ) {
         Ident id = (Ident)args.at(0);
         args.set(1,new Apply(new Lambda(args.at(1), id._name),
                              new Apply(new NotNil(),new Ident(id._name))));
       }
       return new Apply(fun,args.asAry());
     }
     if( BUF[X]=='{' ) {         // Lambda of 1 or 2 args
       X++;                      // Skip paren
       Ary<String> args = new Ary<>(new String[1],0);
       while( skipWS()!='-' ) args.push(id());
       require("->");
       Syntax body = fterm();
       require('}');
       return new Lambda(body,args.asAry());
     }
     // Let or Id
     if( isAlpha0(BUF[X]) ) {
       String id = id();
       if( skipWS()!='=' ) {
         PrimSyn prim = PRIMSYNS.get(id); // No shadowing primitives or this lookup returns the prim instead of the shadow
         return prim==null ? new Ident(id) : prim.make(); // Make a prim copy with fresh HM variables
       }
       // Let expression; "id = term(); term..."
       X++;                      // Skip '='
       Syntax def = fterm();
       require(';');
       return new Let(id,def,fterm());
     }
     // Structure
     if( BUF[X]=='@' ) {
       X++;
       require('{');
       Ary<String>  ids = new Ary<>(String.class);
       Ary<Syntax> flds = new Ary<>(Syntax.class);
       while( skipWS()!='}' && X < BUF.length ) {
         String id = require('=',id());
         Syntax fld = fterm();
         if( fld==null ) throw unimpl("Missing term for field "+id);
         ids .push( id);
         flds.push(fld);
         if( skipWS()==',' ) X++;
       }
       require('}');
       return new Struct(ids.asAry(),flds.asAry());
     }
     throw unimpl("Unknown syntax");
   }
References com.cliffc.aa.util.Ary< E >.asAry(), com.cliffc.aa.util.Ary< E >.at(), com.cliffc.aa.HM.HM.BUF, com.cliffc.aa.HM.HM.fterm(), com.cliffc.aa.HM.HM.id(), com.cliffc.aa.HM.HM.isAlpha0(), com.cliffc.aa.HM.HM.isDigit(), com.cliffc.aa.HM.HM.PrimSyn.make(), com.cliffc.aa.HM.HM.number(), com.cliffc.aa.HM.HM.PRIMSYNS, com.cliffc.aa.util.Ary< E >.push(), com.cliffc.aa.HM.HM.require(), com.cliffc.aa.util.Ary< E >.set(), com.cliffc.aa.HM.HM.skipWS(), com.cliffc.aa.HM.HM.string(), and com.cliffc.aa.HM.HM.X.
Referenced by com.cliffc.aa.HM.HM.fterm().
toString()
String com.cliffc.aa.HM.HM.toString ()
Definition at line 157 of file HM.java.
 { return new String(BUF,X,BUF.length-X); }
References com.cliffc.aa.HM.HM.BUF, and com.cliffc.aa.HM.HM.X.
Member Data Documentation
BUF
byte [] com.cliffc.aa.HM.HM.BUF static private
Definition at line 156 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.id(), com.cliffc.aa.HM.HM.number(), com.cliffc.aa.HM.HM.parse(), com.cliffc.aa.HM.HM.require(), com.cliffc.aa.HM.HM.skipWS(), com.cliffc.aa.HM.HM.string(), com.cliffc.aa.HM.HM.term(), and com.cliffc.aa.HM.HM.toString().
DEBUG_LEAKS
final boolean com.cliffc.aa.HM.HM.DEBUG_LEAKS =false static package
Definition at line 88 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.T2.fresh_unify(), and com.cliffc.aa.HM.HM.hm().
DO_GCP
final boolean com.cliffc.aa.HM.HM.DO_GCP = true static package
Definition at line 92 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.If.hm(), com.cliffc.aa.HM.HM.Syntax.more_work_impl(), com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.HM.HM.Lambda.p1(), com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.HM.TestHM.test05(), com.cliffc.aa.HM.TestHM9.test05(), com.cliffc.aa.HM.TestHM.test06(), com.cliffc.aa.HM.TestHM9.test06(), com.cliffc.aa.HM.TestHM.test14(), com.cliffc.aa.HM.TestHM9.test14(), com.cliffc.aa.HM.TestHM.test18(), com.cliffc.aa.HM.TestHM9.test18(), com.cliffc.aa.HM.TestHM.test20(), com.cliffc.aa.HM.TestHM9.test20(), com.cliffc.aa.HM.TestHM9.test32(), com.cliffc.aa.HM.TestHM.test32(), com.cliffc.aa.HM.TestHM9.test33(), com.cliffc.aa.HM.TestHM.test33(), com.cliffc.aa.HM.TestHM9.test34(), com.cliffc.aa.HM.TestHM.test34(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.HM.TestHM.test36(), com.cliffc.aa.HM.TestHM.test39(), com.cliffc.aa.HM.TestHM9.test39(), com.cliffc.aa.HM.TestHM.test40(), com.cliffc.aa.HM.TestHM9.test40(), com.cliffc.aa.HM.TestHM.test41(), com.cliffc.aa.HM.TestHM9.test41(), com.cliffc.aa.HM.TestHM.test42(), com.cliffc.aa.HM.TestHM9.test42(), com.cliffc.aa.HM.TestHM.test43(), com.cliffc.aa.HM.TestHM9.test43(), com.cliffc.aa.HM.TestHM.test44(), com.cliffc.aa.HM.TestHM9.test44(), com.cliffc.aa.HM.TestHM.test45(), com.cliffc.aa.HM.TestHM9.test45(), com.cliffc.aa.HM.TestHM.test49(), com.cliffc.aa.HM.TestHM9.test49(), com.cliffc.aa.HM.TestHM.test50(), com.cliffc.aa.HM.TestHM9.test50(), com.cliffc.aa.HM.TestHM.test51(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.HM.TestHM.test55(), com.cliffc.aa.HM.TestHM.test56(), and com.cliffc.aa.HM.TestHM.test57().
DO_HM
final boolean com.cliffc.aa.HM.HM.DO_HM = true static package
Definition at line 91 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.Syntax.more_work_impl(), com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.HM.HM.Lambda.p1(), com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.HM.TestHM.test05(), com.cliffc.aa.HM.TestHM9.test05(), com.cliffc.aa.HM.TestHM.test06(), com.cliffc.aa.HM.TestHM9.test06(), com.cliffc.aa.HM.TestHM.test14(), com.cliffc.aa.HM.TestHM9.test14(), com.cliffc.aa.HM.TestHM.test18(), com.cliffc.aa.HM.TestHM9.test18(), com.cliffc.aa.HM.TestHM.test20(), com.cliffc.aa.HM.TestHM9.test20(), com.cliffc.aa.HM.TestHM9.test32(), com.cliffc.aa.HM.TestHM.test32(), com.cliffc.aa.HM.TestHM9.test33(), com.cliffc.aa.HM.TestHM.test33(), com.cliffc.aa.HM.TestHM9.test34(), com.cliffc.aa.HM.TestHM.test34(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.HM.TestHM.test36(), com.cliffc.aa.HM.TestHM.test39(), com.cliffc.aa.HM.TestHM9.test39(), com.cliffc.aa.HM.TestHM.test40(), com.cliffc.aa.HM.TestHM9.test40(), com.cliffc.aa.HM.TestHM.test41(), com.cliffc.aa.HM.TestHM9.test41(), com.cliffc.aa.HM.TestHM.test42(), com.cliffc.aa.HM.TestHM9.test42(), com.cliffc.aa.HM.TestHM.test43(), com.cliffc.aa.HM.TestHM9.test43(), com.cliffc.aa.HM.TestHM.test44(), com.cliffc.aa.HM.TestHM9.test44(), com.cliffc.aa.HM.TestHM.test45(), com.cliffc.aa.HM.TestHM9.test45(), com.cliffc.aa.HM.TestHM.test49(), com.cliffc.aa.HM.TestHM9.test49(), com.cliffc.aa.HM.TestHM.test50(), com.cliffc.aa.HM.TestHM9.test50(), com.cliffc.aa.HM.TestHM.test51(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.HM.TestHM.test55(), com.cliffc.aa.HM.TestHM.test56(), com.cliffc.aa.HM.TestHM.test57(), and com.cliffc.aa.HM.HM.Apply.val().
ID
final SB com.cliffc.aa.HM.HM.ID = new SB() static private
Definition at line 239 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.id().
PRIMSYNS
final HashMap<String,PrimSyn> com.cliffc.aa.HM.HM.PRIMSYNS = new HashMap<>() static package
Definition at line 86 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.reset(), and com.cliffc.aa.HM.HM.term().
X
int com.cliffc.aa.HM.HM.X static private
Definition at line 155 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.fterm(), com.cliffc.aa.HM.HM.id(), com.cliffc.aa.HM.HM.number(), com.cliffc.aa.HM.HM.parse(), com.cliffc.aa.HM.HM.require(), com.cliffc.aa.HM.HM.skipWS(), com.cliffc.aa.HM.HM.string(), com.cliffc.aa.HM.HM.term(), and com.cliffc.aa.HM.HM.toString().
The documentation for this class was generated from the following file:
HM.java