aa: com.cliffc.aa.HM.HM.Syntax Class Reference
com.cliffc.aa.HM.HM.Syntax Class Reference abstract
Public Member Functions
String p ()
final String toString ()
Package Functions
abstract void add_hm_work (Worklist work)
void add_val_work (Syntax child, Worklist work)
T2 debug_find ()
T2 find ()
abstract boolean hm (Worklist work)
abstract boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
abstract SB p1 (SB sb)
abstract SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
abstract int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
abstract SB str (SB sb)
abstract Type val (Worklist work)
Package Attributes
Type _flow
T2 _hmt
VStack _nongen
Syntax _par
Detailed Description
Definition at line 340 of file HM.java.
Member Function Documentation
add_hm_work()
abstract void com.cliffc.aa.HM.HM.Syntax.add_hm_work (Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM.PrimSyn, com.cliffc.aa.HM.HM.Field, com.cliffc.aa.HM.HM.Struct, com.cliffc.aa.HM.HM.Root, com.cliffc.aa.HM.HM.Apply, com.cliffc.aa.HM.HM.Let, com.cliffc.aa.HM.HM.Lambda, com.cliffc.aa.HM.HM.Ident, and com.cliffc.aa.HM.HM.Con.
Referenced by com.cliffc.aa.HM.HM.Field.add_hm_work(), and com.cliffc.aa.HM.HM.hm().
add_val_work()
void com.cliffc.aa.HM.HM.Syntax.add_val_work (Syntax child, Worklist work) package
Reimplemented in com.cliffc.aa.HM.HM.PrimSyn, com.cliffc.aa.HM.HM.Apply, com.cliffc.aa.HM.HM.Let, and com.cliffc.aa.HM.HM.Lambda.
Definition at line 365 of file HM.java.
 {} // Add affected neighbors to worklist
Referenced by com.cliffc.aa.HM.HM.hm().
debug_find()
T2 com.cliffc.aa.HM.HM.Syntax.debug_find () package
Definition at line 348 of file HM.java.
 { return _hmt.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM.Syntax._hmt, and com.cliffc.aa.HM.HM.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM.hm().
find()
T2 com.cliffc.aa.HM.HM.Syntax.find () package
Definition at line 344 of file HM.java.
               {                 // U-F find
       T2 t = _hmt.find();
       return t== _hmt ? t : (_hmt =t);
     }
References com.cliffc.aa.HM.HM.Syntax._hmt, and com.cliffc.aa.HM.HM.T2.find().
Referenced by com.cliffc.aa.HM.HM.Lambda.add_hm_work(), com.cliffc.aa.HM.HM.Let.add_hm_work(), com.cliffc.aa.HM.HM.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM.Lambda.add_val_work(), com.cliffc.aa.HM.HM.Let.add_val_work(), com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM.Ident.hm(), com.cliffc.aa.HM.HM.Lambda.hm(), com.cliffc.aa.HM.HM.Apply.hm(), com.cliffc.aa.HM.HM.Root.hm(), com.cliffc.aa.HM.HM.Struct.hm(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.PrimSyn.hm(), com.cliffc.aa.HM.HM.If.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.Let.prep_tree(), com.cliffc.aa.HM.HM.Struct.prep_tree(), com.cliffc.aa.HM.HM.NotNil.prep_tree(), com.cliffc.aa.HM.HM.Apply.val(), com.cliffc.aa.HM.HM.Root.val(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
hm()
abstract boolean com.cliffc.aa.HM.HM.Syntax.hm (Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM.NotNil, com.cliffc.aa.HM.HM.If, com.cliffc.aa.HM.HM.PrimSyn, com.cliffc.aa.HM.HM.Field, com.cliffc.aa.HM.HM.Struct, com.cliffc.aa.HM.HM.Root, com.cliffc.aa.HM.HM.Apply, com.cliffc.aa.HM.HM.Let, com.cliffc.aa.HM.HM.Lambda, com.cliffc.aa.HM.HM.Ident, and com.cliffc.aa.HM.HM.Con.
Referenced by com.cliffc.aa.HM.HM.hm(), and com.cliffc.aa.HM.HM.Syntax.more_work_impl().
more_work()
abstract boolean com.cliffc.aa.HM.HM.Syntax.more_work (Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM.PrimSyn, com.cliffc.aa.HM.HM.Field, com.cliffc.aa.HM.HM.Struct, com.cliffc.aa.HM.HM.Apply, com.cliffc.aa.HM.HM.Let, com.cliffc.aa.HM.HM.Lambda, com.cliffc.aa.HM.HM.Ident, and com.cliffc.aa.HM.HM.Con.
Referenced by com.cliffc.aa.HM.HM.Lambda.more_work(), com.cliffc.aa.HM.HM.Let.more_work(), com.cliffc.aa.HM.HM.Apply.more_work(), and com.cliffc.aa.HM.HM.Field.more_work().
more_work_impl()
final boolean com.cliffc.aa.HM.HM.Syntax.more_work_impl (Worklist work) package
Definition at line 381 of file HM.java.
{
       if( work.has(this) ) return true;
       if( DO_HM && hm(null) )   // Any more HM work?
         return false;           // Found HM work not on worklist
       if( DO_GCP && val(null)!=_flow )
         return false;           // Found GCP work not on worklist
       return true;
     }
References com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Worklist.has(), com.cliffc.aa.HM.HM.Syntax.hm(), and com.cliffc.aa.HM.HM.Syntax.val().
Referenced by com.cliffc.aa.HM.HM.Con.more_work(), com.cliffc.aa.HM.HM.Ident.more_work(), com.cliffc.aa.HM.HM.Lambda.more_work(), com.cliffc.aa.HM.HM.Let.more_work(), com.cliffc.aa.HM.HM.Apply.more_work(), com.cliffc.aa.HM.HM.Struct.more_work(), com.cliffc.aa.HM.HM.Field.more_work(), and com.cliffc.aa.HM.HM.PrimSyn.more_work().
p()
String com.cliffc.aa.HM.HM.Syntax.p ()
Definition at line 393 of file HM.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM.Syntax.p0 (SB sb, VBitSet dups) package
Definition at line 394 of file HM.java.
{
       _hmt.get_dups(dups);
       VBitSet visit = new VBitSet();
       p1(sb.i());
       if( DO_HM  ) _hmt .str(sb.p(", HM="), visit,dups);
       if( DO_GCP ) _flow.str(sb.p(", CCP="),visit.clr(),null,false);
       sb.nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.util.VBitSet.clr(), com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM.Syntax.p1(), com.cliffc.aa.HM.HM.Syntax.p2(), com.cliffc.aa.type.Type< T extends Type< T >.str(), and com.cliffc.aa.HM.HM.T2.str().
Referenced by com.cliffc.aa.HM.HM.Syntax.p(), com.cliffc.aa.HM.HM.Lambda.p2(), com.cliffc.aa.HM.HM.Let.p2(), com.cliffc.aa.HM.HM.Apply.p2(), com.cliffc.aa.HM.HM.Struct.p2(), and com.cliffc.aa.HM.HM.Field.p2().
p1()
abstract SB com.cliffc.aa.HM.HM.Syntax.p1 (SB sb) abstract package
Reimplemented in com.cliffc.aa.HM.HM.PrimSyn, com.cliffc.aa.HM.HM.Field, com.cliffc.aa.HM.HM.Struct, com.cliffc.aa.HM.HM.Apply, com.cliffc.aa.HM.HM.Let, com.cliffc.aa.HM.HM.Lambda, com.cliffc.aa.HM.HM.Ident, and com.cliffc.aa.HM.HM.Con.
Referenced by com.cliffc.aa.HM.HM.Syntax.p0().
p2()
abstract SB com.cliffc.aa.HM.HM.Syntax.p2 (SB sb, VBitSet dups) abstract package
Reimplemented in com.cliffc.aa.HM.HM.PrimSyn, com.cliffc.aa.HM.HM.Field, com.cliffc.aa.HM.HM.Struct, com.cliffc.aa.HM.HM.Apply, com.cliffc.aa.HM.HM.Let, com.cliffc.aa.HM.HM.Lambda, com.cliffc.aa.HM.HM.Ident, and com.cliffc.aa.HM.HM.Con.
Referenced by com.cliffc.aa.HM.HM.Syntax.p0().
prep_lookup_deps()
void com.cliffc.aa.HM.HM.Syntax.prep_lookup_deps (Ident id) package
Reimplemented in com.cliffc.aa.HM.HM.Let, and com.cliffc.aa.HM.HM.Lambda.
Definition at line 377 of file HM.java.
 {}
prep_tree()
abstract int com.cliffc.aa.HM.HM.Syntax.prep_tree (Syntax par, VStack nongen, Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM.NotNil, com.cliffc.aa.HM.HM.PrimSyn, com.cliffc.aa.HM.HM.Field, com.cliffc.aa.HM.HM.Struct, com.cliffc.aa.HM.HM.Apply, com.cliffc.aa.HM.HM.Let, com.cliffc.aa.HM.HM.Lambda, com.cliffc.aa.HM.HM.Ident, and com.cliffc.aa.HM.HM.Con.
Referenced by com.cliffc.aa.HM.HM.Lambda.prep_tree(), com.cliffc.aa.HM.HM.Let.prep_tree(), com.cliffc.aa.HM.HM.Apply.prep_tree(), com.cliffc.aa.HM.HM.Struct.prep_tree(), and com.cliffc.aa.HM.HM.Field.prep_tree().
prep_tree_impl()
final void com.cliffc.aa.HM.HM.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package
Definition at line 370 of file HM.java.
{
       _par = par;
       _hmt = t;
       _flow= Type.XSCALAR;
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.Syntax._nongen, com.cliffc.aa.HM.HM.Syntax._par, com.cliffc.aa.HM.HM.Worklist.push(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Referenced by com.cliffc.aa.HM.HM.Con.prep_tree(), com.cliffc.aa.HM.HM.Ident.prep_tree(), com.cliffc.aa.HM.HM.Lambda.prep_tree(), com.cliffc.aa.HM.HM.Let.prep_tree(), com.cliffc.aa.HM.HM.Apply.prep_tree(), com.cliffc.aa.HM.HM.Struct.prep_tree(), com.cliffc.aa.HM.HM.Field.prep_tree(), and com.cliffc.aa.HM.HM.PrimSyn.prep_tree().
str()
abstract SB com.cliffc.aa.HM.HM.Syntax.str (SB sb) abstract package
Reimplemented in com.cliffc.aa.HM.HM.PrimSyn, com.cliffc.aa.HM.HM.Field, com.cliffc.aa.HM.HM.Struct, com.cliffc.aa.HM.HM.Root, com.cliffc.aa.HM.HM.Apply, com.cliffc.aa.HM.HM.Let, com.cliffc.aa.HM.HM.Lambda, com.cliffc.aa.HM.HM.Ident, and com.cliffc.aa.HM.HM.Con.
Referenced by com.cliffc.aa.HM.HM.Lambda.str(), com.cliffc.aa.HM.HM.Let.str(), com.cliffc.aa.HM.HM.Apply.str(), com.cliffc.aa.HM.HM.Root.str(), com.cliffc.aa.HM.HM.Struct.str(), com.cliffc.aa.HM.HM.Field.str(), and com.cliffc.aa.HM.HM.Syntax.toString().
toString()
final String com.cliffc.aa.HM.HM.Syntax.toString ()
Definition at line 390 of file HM.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.HM.HM.Lambda.p1().
val()
abstract Type com.cliffc.aa.HM.HM.Syntax.val (Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM.Field, com.cliffc.aa.HM.HM.Struct, com.cliffc.aa.HM.HM.Root, com.cliffc.aa.HM.HM.Apply, com.cliffc.aa.HM.HM.Let, com.cliffc.aa.HM.HM.Lambda, com.cliffc.aa.HM.HM.Ident, and com.cliffc.aa.HM.HM.Con.
Referenced by com.cliffc.aa.HM.HM.hm(), and com.cliffc.aa.HM.HM.Syntax.more_work_impl().
Member Data Documentation
_flow
Type com.cliffc.aa.HM.HM.Syntax._flow package
Definition at line 351 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM.Lambda.apply(), com.cliffc.aa.HM.HM.Pair1.apply(), com.cliffc.aa.HM.HM.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM.Pair.apply(), com.cliffc.aa.HM.HM.Triple.apply(), com.cliffc.aa.HM.HM.If.apply(), com.cliffc.aa.HM.HM.EQ.apply(), com.cliffc.aa.HM.HM.EQ0.apply(), com.cliffc.aa.HM.HM.IsEmpty.apply(), com.cliffc.aa.HM.HM.NotNil.apply(), com.cliffc.aa.HM.HM.Mul.apply(), com.cliffc.aa.HM.HM.Add.apply(), com.cliffc.aa.HM.HM.Dec.apply(), com.cliffc.aa.HM.HM.Str.apply(), com.cliffc.aa.HM.HM.Factor.apply(), com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.Lambda.Lambda(), com.cliffc.aa.HM.HM.Syntax.more_work_impl(), com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.HM.HM.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM.Ident.val(), com.cliffc.aa.HM.HM.Let.val(), com.cliffc.aa.HM.HM.Apply.val(), com.cliffc.aa.HM.HM.Root.val(), com.cliffc.aa.HM.HM.Struct.val(), com.cliffc.aa.HM.HM.Field.val(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
_hmt
T2 com.cliffc.aa.HM.HM.Syntax._hmt package
Definition at line 343 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Syntax.debug_find(), com.cliffc.aa.HM.HM.Syntax.find(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.HM.HM.Let.prep_tree(), com.cliffc.aa.HM.HM.PrimSyn.prep_tree(), com.cliffc.aa.HM.HM.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM.PrimSyn.PrimSyn(), com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.HM.TestHM.test05(), com.cliffc.aa.HM.TestHM9.test05(), com.cliffc.aa.HM.TestHM.test06(), com.cliffc.aa.HM.TestHM9.test06(), com.cliffc.aa.HM.TestHM.test14(), com.cliffc.aa.HM.TestHM9.test14(), com.cliffc.aa.HM.TestHM.test18(), com.cliffc.aa.HM.TestHM9.test18(), com.cliffc.aa.HM.TestHM.test20(), com.cliffc.aa.HM.TestHM9.test20(), com.cliffc.aa.HM.TestHM9.test32(), com.cliffc.aa.HM.TestHM.test32(), com.cliffc.aa.HM.TestHM9.test33(), com.cliffc.aa.HM.TestHM.test33(), com.cliffc.aa.HM.TestHM9.test34(), com.cliffc.aa.HM.TestHM.test34(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.HM.TestHM.test36(), com.cliffc.aa.HM.TestHM.test39(), com.cliffc.aa.HM.TestHM9.test39(), com.cliffc.aa.HM.TestHM.test40(), com.cliffc.aa.HM.TestHM9.test40(), com.cliffc.aa.HM.TestHM.test41(), com.cliffc.aa.HM.TestHM9.test41(), com.cliffc.aa.HM.TestHM.test42(), com.cliffc.aa.HM.TestHM9.test42(), com.cliffc.aa.HM.TestHM.test43(), com.cliffc.aa.HM.TestHM9.test43(), com.cliffc.aa.HM.TestHM.test44(), com.cliffc.aa.HM.TestHM9.test44(), com.cliffc.aa.HM.TestHM.test45(), com.cliffc.aa.HM.TestHM9.test45(), com.cliffc.aa.HM.TestHM.test49(), com.cliffc.aa.HM.TestHM9.test49(), com.cliffc.aa.HM.TestHM.test50(), com.cliffc.aa.HM.TestHM9.test50(), com.cliffc.aa.HM.TestHM.test51(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.HM.TestHM.test55(), com.cliffc.aa.HM.TestHM.test56(), and com.cliffc.aa.HM.TestHM.test57().
_nongen
VStack com.cliffc.aa.HM.HM.Syntax._nongen package
Definition at line 342 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Ident.add_hm_work(), com.cliffc.aa.HM.HM.Ident.hm(), and com.cliffc.aa.HM.HM.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM.Syntax._par package
Definition at line 341 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Ident.add_hm_work(), com.cliffc.aa.HM.HM.Lambda.add_hm_work(), com.cliffc.aa.HM.HM.Let.add_hm_work(), com.cliffc.aa.HM.HM.Apply.add_hm_work(), com.cliffc.aa.HM.HM.Struct.add_hm_work(), com.cliffc.aa.HM.HM.Field.add_hm_work(), com.cliffc.aa.HM.HM.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.Ident.prep_tree(), and com.cliffc.aa.HM.HM.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM.java