aa: com.cliffc.aa.Env.VStack Class Reference
com.cliffc.aa.Env.VStack Class Reference
Public Member Functions
TV2[] compact ()
boolean isEmpty ()
String toString ()
Public Attributes
Ary< String > _flds
final VStack _par
Ary< TV2 > _tvars
Package Functions
String add_var (String fld, TV2 tv)
Private Member Functions
VStack (VStack par)
Detailed Description
Definition at line 256 of file Env.java.
Constructor & Destructor Documentation
VStack()
com.cliffc.aa.Env.VStack.VStack (VStack par) private
Definition at line 260 of file Env.java.
 { _par=par; _flds = new Ary<>(new String[1],0); _tvars = new Ary<>(new TV2[1],0); }
References com.cliffc.aa.Env.VStack._flds, com.cliffc.aa.Env.VStack._par, and com.cliffc.aa.Env.VStack._tvars.
Member Function Documentation
add_var()
String com.cliffc.aa.Env.VStack.add_var (String fld, TV2 tv) package
Definition at line 261 of file Env.java.
 { _flds.push(fld);  _tvars.push(tv); return fld; }
References com.cliffc.aa.Env.VStack._flds, com.cliffc.aa.Env.VStack._tvars, and com.cliffc.aa.util.Ary< E >.push().
Referenced by com.cliffc.aa.Parse.func(), and com.cliffc.aa.Parse.stmt().
compact()
TV2 [] com.cliffc.aa.Env.VStack.compact ()
Definition at line 267 of file Env.java.
{
       int cnt=0;
       for( VStack vs = this; vs!=null; vs=vs._par )
         cnt += vs._tvars._len;
       TV2[] tv2s = new TV2[cnt];
       cnt=0;
       for( VStack vs = this; vs!=null; vs=vs._par ) {
         System.arraycopy(vs._tvars._es,0,tv2s,cnt,vs._tvars._len);
         cnt += vs._tvars._len;
       }
       return tv2s;
     }
References com.cliffc.aa.Env.VStack._par.
Referenced by com.cliffc.aa.Parse.func().
isEmpty()
boolean com.cliffc.aa.Env.VStack.isEmpty ()
Definition at line 262 of file Env.java.
{
       return _flds.isEmpty() && (_par == null || _par.isEmpty());
     }
References com.cliffc.aa.Env.VStack._flds, com.cliffc.aa.Env.VStack._par, com.cliffc.aa.util.Ary< E >.isEmpty(), and com.cliffc.aa.Env.VStack.isEmpty().
Referenced by com.cliffc.aa.Env.VStack.isEmpty().
toString()
String com.cliffc.aa.Env.VStack.toString ()
Definition at line 281 of file Env.java.
{
       // These types get large & complex; find all the dups up-front to allow
       // for prettier printing.  Uses '$A' style for repeats.
       NonBlockingHashMapLong<String> dups = new NonBlockingHashMapLong<>();
       VBitSet bs = new VBitSet();
       for( VStack vs = this; vs!=null ; vs=vs._par )
         if( vs._tvars != null )
           for( TV2 tv2 : vs._tvars )
             if( tv2 != null ) tv2.find_dups(bs,dups,0);
       // Print stack of types, grouped by depth
       bs.clr();
       SB sb = new SB().p("[");
       for( VStack vs = this; vs!=null ; vs=vs._par ) {
         if( vs._tvars != null ) {
           for( int i=0; i<vs._tvars._len; i++ ) {
             sb.p(vs._flds.at(i)).p('=');
             TV2 tv2 = vs._tvars.at(i);
             if( tv2 !=null ) tv2.str(sb,bs,dups,false,0,0);
             sb.p(", ");
           }
           if( vs._tvars._len>0 ) sb.unchar(2);
         }
         sb.p(" >> ");
       }
       if( _par!=null ) sb.unchar(4);
       return sb.p("]").toString();
     }
References com.cliffc.aa.Env.VStack._par, com.cliffc.aa.util.VBitSet.clr(), com.cliffc.aa.tvar.TV2.find_dups(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.tvar.TV2.str(), com.cliffc.aa.util.SB.toString(), and com.cliffc.aa.util.SB.unchar().
Member Data Documentation
_flds
Ary<String> com.cliffc.aa.Env.VStack._flds
Definition at line 258 of file Env.java.
Referenced by com.cliffc.aa.Env.VStack.add_var(), com.cliffc.aa.Env.VStack.isEmpty(), com.cliffc.aa.Env.lookup_fref(), and com.cliffc.aa.Env.VStack.VStack().
_par
final VStack com.cliffc.aa.Env.VStack._par
Definition at line 257 of file Env.java.
Referenced by com.cliffc.aa.Env.VStack.compact(), com.cliffc.aa.Env.VStack.isEmpty(), com.cliffc.aa.Env.nongen_pop(), com.cliffc.aa.Env.VStack.toString(), and com.cliffc.aa.Env.VStack.VStack().
_tvars
Ary<TV2> com.cliffc.aa.Env.VStack._tvars
Definition at line 259 of file Env.java.
Referenced by com.cliffc.aa.Env.VStack.add_var(), and com.cliffc.aa.Env.VStack.VStack().
The documentation for this class was generated from the following file:
Env.java