aa: com.cliffc.aa.Env Class Reference
com.cliffc.aa.Env Class Reference
Classes
class VStack
Public Member Functions
void close ()
void close_display (GVNGCM gvn)
HashSet< TV2 > collect_active_scope ()
Node lookup (String name)
ConTypeNode lookup_type (int alias)
Static Public Member Functions
static Env file_scope (Env top_scope)
static Env top_scope ()
Public Attributes
VStack _nongen
final Env _par
final ScopeNode _scope
Static Public Attributes
static ConNode ALL
static ConNode ALL_CALL
static ConNode ALL_CTRL
static BitsAlias ALL_DISPLAYS = BitsAlias.EMPTY
static ConNode ANY
static CProjNode CTL_0
static DefMemNode DEFMEM
static final GVNGCM GVN = new GVNGCM()
static BitsAlias LEX_DISPLAYS = BitsAlias.EMPTY
static StartMemNode MEM_0
static ConNode NIL
static ScopeNode SCP_0
static StartNode START
static NewObjNode STK_0
static ConNode XCTRL
static ConNode XNIL
Package Functions
Env (Env par, Parse P, boolean is_closure, Node ctrl, Node mem)
Node add_fun (Parse bad, String name, Node val)
void add_type (String name, ConTypeNode t)
Node early_exit (Parse P, Node val)
UnOrFunPtrNode lookup_filter_fresh (String name, int nargs, Node ctrl)
Env lookup_fref (String tok)
ScopeNode lookup_scope (String name, boolean lookup_current_scope_only)
ConTypeNode lookup_type (String name)
Type lookup_valtype (String name)
Node nongen_pop (Node ret)
void nongen_push (Env par)
Private Member Functions
Env ()
Static Private Member Functions
static ScopeNode init (Node ctl, Node clo, Node mem, Type back_ptr, Parse errmsg, boolean is_closure)
static void record_for_top_reset1 ()
static void record_for_top_reset2 ()
static void top_reset ()
Detailed Description
Definition at line 12 of file Env.java.
Constructor & Destructor Documentation
Env() [1/2]
com.cliffc.aa.Env.Env () private
Definition at line 40 of file Env.java.
                   {
     _par = null;
     _nongen = null;
     _scope = init(CTL_0,XNIL,MEM_0,Type.XNIL,null,true);
   }
References com.cliffc.aa.Env._nongen, com.cliffc.aa.Env._par, com.cliffc.aa.Env._scope, com.cliffc.aa.Env.CTL_0, com.cliffc.aa.Env.init(), com.cliffc.aa.Env.MEM_0, com.cliffc.aa.Env.XNIL, and com.cliffc.aa.type.Type< T extends Type< T >.XNIL.
Referenced by com.cliffc.aa.Env.file_scope(), and com.cliffc.aa.Env.top_scope().
Env() [2/2]
com.cliffc.aa.Env.Env (Env par, Parse P, boolean is_closure, Node ctrl, Node mem) package
Definition at line 47 of file Env.java.
{
     GVN._opt_mode=GVNGCM.Mode.Parse;
     _par = par;
     nongen_push(par);
     ScopeNode s = par._scope;   // Parent scope
     _scope = init(ctrl,s.ptr(),mem,s.stk()._tptr,P==null ? null : P.errMsg(),is_closure);
   }
References com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.Env._par, com.cliffc.aa.Env._scope, com.cliffc.aa.node.NewNode< T extends TypeObj< T >._tptr, com.cliffc.aa.Parse.errMsg(), com.cliffc.aa.Env.GVN, com.cliffc.aa.Env.init(), com.cliffc.aa.Env.nongen_push(), com.cliffc.aa.GVNGCM.Mode.Parse, com.cliffc.aa.node.ScopeNode.ptr(), and com.cliffc.aa.node.ScopeNode.stk().
Member Function Documentation
add_fun()
Node com.cliffc.aa.Env.add_fun (Parse bad, String name, Node val) package
Definition at line 218 of file Env.java.
 { return _scope.stk().add_fun(bad,name,(FunPtrNode)val); }
References com.cliffc.aa.Env._scope, com.cliffc.aa.node.NewObjNode.add_fun(), and com.cliffc.aa.node.ScopeNode.stk().
Referenced by com.cliffc.aa.Parse.tstmt().
add_type()
void com.cliffc.aa.Env.add_type (String name, ConTypeNode t) package
Definition at line 234 of file Env.java.
 { _scope.add_type(name,t); }
References com.cliffc.aa.Env._scope, and com.cliffc.aa.node.ScopeNode.add_type().
Referenced by com.cliffc.aa.Parse.tstmt(), and com.cliffc.aa.Parse.type0().
close()
void com.cliffc.aa.Env.close ()
Definition at line 141 of file Env.java.
{
     // Promote forward refs to the next outer scope
     ScopeNode pscope = _par._scope;
     if( pscope != null && _par._par != null )
       _scope.stk().promote_forward(pscope.stk());
     close_display(GVN);
     GVN.add_dead(_scope);
     GVN.iter(GVN._opt_mode);
     assert _scope.is_dead();
   }
References com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.Env._par, com.cliffc.aa.Env._scope, com.cliffc.aa.GVNGCM.add_dead(), com.cliffc.aa.Env.close_display(), com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.is_dead(), com.cliffc.aa.GVNGCM.iter(), com.cliffc.aa.node.NewObjNode.promote_forward(), and com.cliffc.aa.node.ScopeNode.stk().
Referenced by com.cliffc.aa.TypeEnv.close().
close_display()
void com.cliffc.aa.Env.close_display (GVNGCM gvn)
Definition at line 128 of file Env.java.
{
     Node ptr = _scope.ptr();
     if( ptr == null ) return;   // Already done
     NewObjNode stk = _scope.stk();
     stk.no_more_fields();
     gvn.add_flow(stk);          // Scope object going dead, trigger following projs to cleanup
     _scope.set_ptr(null);       // Clear pointer to display
     gvn.add_flow(ptr);          // Clearing pointer changes liveness
     gvn.add_work_all(_scope.unkeep());
     LEX_DISPLAYS = LEX_DISPLAYS.clear(stk._alias);
   }
References com.cliffc.aa.node.NewNode< T extends TypeObj< T >._alias, com.cliffc.aa.Env._scope, com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.GVNGCM.add_work_all(), com.cliffc.aa.type.Bits< B extends Bits< B >.clear(), com.cliffc.aa.Env.LEX_DISPLAYS, com.cliffc.aa.node.NewObjNode.no_more_fields(), com.cliffc.aa.node.ScopeNode.ptr(), com.cliffc.aa.node.ScopeNode.set_ptr(), com.cliffc.aa.node.ScopeNode.stk(), and com.cliffc.aa.node.Node.unkeep().
Referenced by com.cliffc.aa.Env.close(), and com.cliffc.aa.Parse.go().
collect_active_scope()
HashSet<TV2> com.cliffc.aa.Env.collect_active_scope ()
Definition at line 238 of file Env.java.
{
     HashSet<TV2> tvars = new HashSet<>();
     Env e = this;
     while( e!=null ) {
       for( Node def : _scope.stk()._defs )
         if( def != null ) tvars.add(def.tvar());
       e = e._par;
     }
     return tvars;
   }
References com.cliffc.aa.Env._par, com.cliffc.aa.Env._scope, and com.cliffc.aa.node.ScopeNode.stk().
early_exit()
Node com.cliffc.aa.Env.early_exit (Parse P, Node val) package
Definition at line 121 of file Env.java.
{
     return _scope.is_closure() ? P.do_exit(_scope,val) : _par.early_exit(P,val); // Hunt for an early-exit-enabled scope
   }
References com.cliffc.aa.Env._par, com.cliffc.aa.Env._scope, com.cliffc.aa.Parse.do_exit(), com.cliffc.aa.Env.early_exit(), and com.cliffc.aa.node.ScopeNode.is_closure().
Referenced by com.cliffc.aa.Env.early_exit(), and com.cliffc.aa.Parse.stmt().
file_scope()
static Env com.cliffc.aa.Env.file_scope (Env top_scope) static
Definition at line 116 of file Env.java.
{
     return new Env(top_scope,null, true, top_scope._scope.ctrl(), top_scope._scope.mem());
   }
References com.cliffc.aa.Env._scope, com.cliffc.aa.node.ScopeNode.ctrl(), com.cliffc.aa.Env.Env(), com.cliffc.aa.node.ScopeNode.mem(), and com.cliffc.aa.Env.top_scope().
Referenced by com.cliffc.aa.REPL.go_one(), com.cliffc.aa.AA.main(), com.cliffc.aa.TestParse.run(), com.cliffc.aa.TestParse.test_prim(), com.cliffc.aa.TestParse.testary(), com.cliffc.aa.TestParse.testerr(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.node.TestNode.testNode(), com.cliffc.aa.TestParse.testParse06(), and com.cliffc.aa.TestParse.testParse07().
init()
static ScopeNode com.cliffc.aa.Env.init (Node ctl, Node clo, Node mem, Type back_ptr, Parse errmsg, boolean is_closure) static private
Definition at line 55 of file Env.java.
{
     TypeStruct tdisp = TypeStruct.open(back_ptr);
     mem.keep(2);
     NewObjNode nnn = GVN.xform(new NewObjNode(is_closure,tdisp,clo)).keep(2);
     MrgProjNode  frm = DEFMEM.make_mem_proj(nnn,mem.unkeep(2));
     Node ptr = GVN.xform(new ProjNode(nnn.unkeep(2),AA.REZ_IDX));
     ALL_DISPLAYS = ALL_DISPLAYS.set(nnn._alias);   // Displays for all time
     LEX_DISPLAYS = LEX_DISPLAYS.set(nnn._alias);   // Lexically active displays
     ScopeNode scope = new ScopeNode(errmsg,is_closure);
     scope.set_ctrl(ctl);
     scope.set_ptr (ptr);  // Address for 'nnn', the local stack frame
     scope.set_mem (frm);  // Memory includes local stack frame
     scope.set_rez (Node.con(Type.SCALAR));
     return scope;
   }
References com.cliffc.aa.node.NewNode< T extends TypeObj< T >._alias, com.cliffc.aa.Env.ALL_DISPLAYS, com.cliffc.aa.node.Node.con(), com.cliffc.aa.Env.DEFMEM, com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.keep(), com.cliffc.aa.Env.LEX_DISPLAYS, com.cliffc.aa.node.DefMemNode.make_mem_proj(), com.cliffc.aa.type.TypeStruct.open(), com.cliffc.aa.AA.REZ_IDX, com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, com.cliffc.aa.type.Bits< B extends Bits< B >.set(), com.cliffc.aa.node.ScopeNode.set_ctrl(), com.cliffc.aa.node.ScopeNode.set_mem(), com.cliffc.aa.node.ScopeNode.set_ptr(), com.cliffc.aa.node.ScopeNode.set_rez(), com.cliffc.aa.node.Node.unkeep(), and com.cliffc.aa.GVNGCM.xform().
Referenced by com.cliffc.aa.Env.Env().
lookup()
Node com.cliffc.aa.Env.lookup (String name)
Definition at line 186 of file Env.java.
{
     ScopeNode scope = lookup_scope(name,false);
     return scope==null ? null : scope.get(name);
   }
References com.cliffc.aa.node.ScopeNode.get(), and com.cliffc.aa.Env.lookup_scope().
Referenced by com.cliffc.aa.Parse.fact(), com.cliffc.aa.Parse.lookup(), com.cliffc.aa.Env.lookup_filter_fresh(), com.cliffc.aa.Env.lookup_valtype(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.node.TestNode.testMonotonic(), and com.cliffc.aa.node.TestNodeSmall.testUnresolvedAdd().
lookup_filter_fresh()
UnOrFunPtrNode com.cliffc.aa.Env.lookup_filter_fresh (String name, int nargs, Node ctrl) package
Definition at line 203 of file Env.java.
{
     if( !Parse.isOp(name) ) return null; // Limit to operators
     for( int i=name.length(); i>0; i-- ) {
       UnOrFunPtrNode n = (UnOrFunPtrNode)lookup(name.substring(0,i).intern());
       if( n != null ) {         // First name found will return
         UnOrFunPtrNode u = nargs == 0 // Requiring a balanced-op?
           ? (n.op_prec()==0 ? n : null) // Return a balanced-op or error
           : n.filter(nargs);    // Non-balanced ops also check arg count; distinguish e.g. -x from x-y.
         return u==null ? null : (UnOrFunPtrNode)Env.GVN.xform(new FreshNode(_nongen,ctrl,u));
       }
     }
     return null;
   }
References com.cliffc.aa.Env._nongen, com.cliffc.aa.node.UnOrFunPtrNode.filter(), com.cliffc.aa.Env.GVN, com.cliffc.aa.Parse.isOp(), com.cliffc.aa.Env.lookup(), com.cliffc.aa.node.Node.op_prec(), and com.cliffc.aa.GVNGCM.xform().
Referenced by com.cliffc.aa.Parse._expr(), com.cliffc.aa.Parse.bal_open(), com.cliffc.aa.Parse.inc(), and com.cliffc.aa.Parse.term().
lookup_fref()
Env com.cliffc.aa.Env.lookup_fref (String tok) package
Definition at line 311 of file Env.java.
{
     if( _nongen!=null && _nongen._flds.find(tok)!= -1 ) return this;
     return _par==null ? null : _par.lookup_fref(tok);
   }
References com.cliffc.aa.Env.VStack._flds, com.cliffc.aa.Env._nongen, com.cliffc.aa.Env._par, com.cliffc.aa.util.Ary< E >.find(), and com.cliffc.aa.Env.lookup_fref().
Referenced by com.cliffc.aa.Parse.fact(), and com.cliffc.aa.Env.lookup_fref().
lookup_scope()
ScopeNode com.cliffc.aa.Env.lookup_scope (String name, boolean lookup_current_scope_only) package
Definition at line 177 of file Env.java.
{
     if( name == null ) return null; // Handle null here, easier on parser
     if( _scope.stk().exists(name) ) return _scope;
     return _par == null || lookup_current_scope_only ? null : _par.lookup_scope(name,false);
   }
References com.cliffc.aa.Env._par, com.cliffc.aa.Env._scope, com.cliffc.aa.node.NewObjNode.exists(), com.cliffc.aa.Env.lookup_scope(), and com.cliffc.aa.node.ScopeNode.stk().
Referenced by com.cliffc.aa.Env.lookup(), com.cliffc.aa.Env.lookup_scope(), and com.cliffc.aa.Parse.lookup_scope().
lookup_type() [1/2]
ConTypeNode com.cliffc.aa.Env.lookup_type (int alias)
Definition at line 228 of file Env.java.
{
     ConTypeNode t = _scope.get_type(alias);
     if( t != null ) return t;
     return _par == null ? null : _par.lookup_type(alias);
   }
References com.cliffc.aa.Env._par, com.cliffc.aa.Env._scope, com.cliffc.aa.node.ScopeNode.get_type(), and com.cliffc.aa.Env.lookup_type().
lookup_type() [2/2]
ConTypeNode com.cliffc.aa.Env.lookup_type (String name) package
Definition at line 222 of file Env.java.
{
     ConTypeNode t = _scope.get_type(name);
     if( t != null ) return t;
     return _par == null ? null : _par.lookup_type(name);
   }
References com.cliffc.aa.Env._par, com.cliffc.aa.Env._scope, com.cliffc.aa.node.ScopeNode.get_type(), and com.cliffc.aa.Env.lookup_type().
Referenced by com.cliffc.aa.node.ConTypeNode.def_fref(), com.cliffc.aa.Env.lookup_type(), com.cliffc.aa.Parse.tstmt(), and com.cliffc.aa.Parse.type0().
lookup_valtype()
Type com.cliffc.aa.Env.lookup_valtype (String name) package
Definition at line 191 of file Env.java.
{
     Node n = lookup(name);
     if( !(n instanceof UnresolvedNode) ) return n._val;
     // For unresolved, use the ambiguous type
     return n.value(GVNGCM.Mode.Opto);
   }
References com.cliffc.aa.node.Node._val, com.cliffc.aa.Env.lookup(), com.cliffc.aa.GVNGCM.Mode.Opto, and com.cliffc.aa.node.Node.value().
Referenced by com.cliffc.aa.TestParse.test_prim().
nongen_pop()
Node com.cliffc.aa.Env.nongen_pop (Node ret) package
Definition at line 254 of file Env.java.
 { _nongen = _nongen._par; return ret;}
References com.cliffc.aa.Env._nongen, and com.cliffc.aa.Env.VStack._par.
Referenced by com.cliffc.aa.Parse.stmt().
nongen_push()
void com.cliffc.aa.Env.nongen_push (Env par) package
Definition at line 255 of file Env.java.
 { _nongen = new VStack(par._nongen); }
References com.cliffc.aa.Env._nongen.
Referenced by com.cliffc.aa.Env.Env(), and com.cliffc.aa.Parse.stmt().
record_for_top_reset1()
static void com.cliffc.aa.Env.record_for_top_reset1 () static private
Definition at line 153 of file Env.java.
{
     BitsAlias.init0();
     BitsFun  .init0();
     BitsRPC  .init0();
   }
References com.cliffc.aa.type.BitsFun.init0(), com.cliffc.aa.type.BitsRPC.init0(), and com.cliffc.aa.type.BitsAlias.init0().
Referenced by com.cliffc.aa.Env.top_scope().
record_for_top_reset2()
static void com.cliffc.aa.Env.record_for_top_reset2 () static private
Definition at line 158 of file Env.java.
 { GVN.init0(); Node.init0(); }
References com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.init0(), and com.cliffc.aa.GVNGCM.init0().
Referenced by com.cliffc.aa.Env.top_scope().
top_reset()
static void com.cliffc.aa.Env.top_reset () static private
Definition at line 162 of file Env.java.
{
     BitsAlias .reset_to_init0();
     BitsFun   .reset_to_init0();
     BitsRPC   .reset_to_init0();
     TV2       .reset_to_init0();
     GVN       .reset_to_init0();
     Node      .reset_to_init0();
     FunNode   .reset();
     NewNode.NewPrimNode.reset();
     PrimNode  .reset();
     ALL_DISPLAYS = BitsAlias.EMPTY; // Reset aliases declared as Displays
     LEX_DISPLAYS = BitsAlias.EMPTY;
   }
References com.cliffc.aa.Env.ALL_DISPLAYS, com.cliffc.aa.type.BitsAlias.EMPTY, com.cliffc.aa.Env.GVN, com.cliffc.aa.Env.LEX_DISPLAYS, com.cliffc.aa.node.PrimNode.reset(), com.cliffc.aa.node.FunNode.reset(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.reset(), com.cliffc.aa.type.BitsFun.reset_to_init0(), com.cliffc.aa.type.BitsRPC.reset_to_init0(), com.cliffc.aa.type.BitsAlias.reset_to_init0(), com.cliffc.aa.node.Node.reset_to_init0(), com.cliffc.aa.GVNGCM.reset_to_init0(), and com.cliffc.aa.tvar.TV2.reset_to_init0().
Referenced by com.cliffc.aa.Env.top_scope().
top_scope()
static Env com.cliffc.aa.Env.top_scope () static
Definition at line 72 of file Env.java.
{
     boolean first_time = START == null;
     if( first_time ) record_for_top_reset1();
     else top_reset();
     // Top-level default values; ALL_CTRL is used by declared functions to
     // indicate that future not-yet-parsed code may call the function.
     START   = GVN.init (new StartNode());
     ALL_CTRL= GVN.xform(new ConNode<>(Type.CTRL )).keep();
     XCTRL   = GVN.xform(new ConNode<>(Type.XCTRL)).keep();
     XNIL    = GVN.xform(new ConNode<>(Type.XNIL )).keep();
     NIL     = GVN.xform(new ConNode<>(Type.NIL  )).keep();
     ANY     = GVN.xform(new ConNode<>(Type.ANY  )).keep();
     ALL     = GVN.xform(new ConNode<>(Type.ALL  )).keep();
     ALL_CALL= GVN.xform(new ConNode<>(TypeRPC.ALL_CALL)).keep();
     // Initial control & memory
     CTL_0  = GVN.init(new    CProjNode(START,0));
     DEFMEM = GVN.init(new   DefMemNode(  CTL_0));
     MEM_0  = GVN.init(new StartMemNode(START  ));
     // Top-most (file-scope) lexical environment
     Env top = new Env();
     // Top-level display defining all primitives
     SCP_0 = top._scope;
     SCP_0.init();               // Add base types
     STK_0 = SCP_0.stk();
     STK_0.keep();               // Inputs & type will rapidly change
     for( PrimNode prim : PrimNode.PRIMS() )
       STK_0.add_fun(null,prim._name,(FunPtrNode) GVN.xform(prim.as_fun(GVN)));
     for( NewNode.NewPrimNode lib : NewNode.NewPrimNode.INTRINSICS() )
       STK_0.add_fun(null,lib ._name,(FunPtrNode) GVN.xform(lib .as_fun(GVN)));
     // Top-level constants
     STK_0.create_active("math_pi", Node.con(TypeFlt.PI),Access.Final);
     STK_0.no_more_fields();
     STK_0.unkeep();
     // Run the worklist dry
     GVN.iter(GVNGCM.Mode.Parse);
     if( first_time ) record_for_top_reset2();
     return top;
   }
References com.cliffc.aa.Env._scope, com.cliffc.aa.node.NewObjNode.add_fun(), com.cliffc.aa.Env.ALL, com.cliffc.aa.type.Type< T extends Type< T >.ALL, com.cliffc.aa.Env.ALL_CALL, com.cliffc.aa.type.TypeRPC.ALL_CALL, com.cliffc.aa.Env.ALL_CTRL, com.cliffc.aa.Env.ANY, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.NewObjNode.create_active(), com.cliffc.aa.Env.CTL_0, com.cliffc.aa.type.Type< T extends Type< T >.CTRL, com.cliffc.aa.Env.DEFMEM, com.cliffc.aa.Env.Env(), com.cliffc.aa.type.TypeFld.Access.Final, com.cliffc.aa.Env.GVN, com.cliffc.aa.node.ScopeNode.init(), com.cliffc.aa.GVNGCM.init(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< T extends TypeObj< T >.INTRINSICS, com.cliffc.aa.GVNGCM.iter(), com.cliffc.aa.node.Node.keep(), com.cliffc.aa.Env.MEM_0, com.cliffc.aa.Env.NIL, com.cliffc.aa.type.Type< T extends Type< T >.NIL, com.cliffc.aa.node.NewObjNode.no_more_fields(), com.cliffc.aa.GVNGCM.Mode.Parse, com.cliffc.aa.type.TypeFlt.PI, com.cliffc.aa.node.PrimNode.PRIMS, com.cliffc.aa.Env.record_for_top_reset1(), com.cliffc.aa.Env.record_for_top_reset2(), com.cliffc.aa.Env.SCP_0, com.cliffc.aa.Env.START, com.cliffc.aa.node.ScopeNode.stk(), com.cliffc.aa.Env.STK_0, com.cliffc.aa.Env.top_reset(), com.cliffc.aa.Env.XCTRL, com.cliffc.aa.type.Type< T extends Type< T >.XCTRL, com.cliffc.aa.GVNGCM.xform(), com.cliffc.aa.Env.XNIL, and com.cliffc.aa.type.Type< T extends Type< T >.XNIL.
Referenced by com.cliffc.aa.Env.file_scope(), com.cliffc.aa.REPL.go_one(), com.cliffc.aa.AA.main(), com.cliffc.aa.TestParse.run(), com.cliffc.aa.TestParse.test_prim(), com.cliffc.aa.TestParse.testary(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.TestParse.testerr(), com.cliffc.aa.node.TestNodeSmall.testMemoryArgs(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.TestLive.testNewObj(), com.cliffc.aa.node.TestNode.testNode(), com.cliffc.aa.TestParse.testParse06(), com.cliffc.aa.TestParse.testParse07(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), and com.cliffc.aa.node.TestNodeSmall.testUnresolvedAdd().
Member Data Documentation
_nongen
VStack com.cliffc.aa.Env._nongen
Definition at line 36 of file Env.java.
Referenced by com.cliffc.aa.Parse._args(), com.cliffc.aa.Env.Env(), com.cliffc.aa.Parse.fact(), com.cliffc.aa.Parse.func(), com.cliffc.aa.Parse.inc(), com.cliffc.aa.Env.lookup_filter_fresh(), com.cliffc.aa.Env.lookup_fref(), com.cliffc.aa.Env.nongen_pop(), com.cliffc.aa.Env.nongen_push(), com.cliffc.aa.Parse.stmt(), and com.cliffc.aa.Parse.term().
_par
final Env com.cliffc.aa.Env._par
Definition at line 34 of file Env.java.
Referenced by com.cliffc.aa.Env.close(), com.cliffc.aa.Env.collect_active_scope(), com.cliffc.aa.Env.early_exit(), com.cliffc.aa.Env.Env(), com.cliffc.aa.Parse.func(), com.cliffc.aa.Parse.gather_errors(), com.cliffc.aa.Parse.get_display_ptr(), com.cliffc.aa.Env.lookup_fref(), com.cliffc.aa.Env.lookup_scope(), com.cliffc.aa.Env.lookup_type(), com.cliffc.aa.Parse.stmt(), and com.cliffc.aa.Parse.struct().
_scope
final ScopeNode com.cliffc.aa.Env._scope
Definition at line 35 of file Env.java.
Referenced by com.cliffc.aa.Env.add_fun(), com.cliffc.aa.Env.add_type(), com.cliffc.aa.Env.close(), com.cliffc.aa.Env.close_display(), com.cliffc.aa.Env.collect_active_scope(), com.cliffc.aa.Env.early_exit(), com.cliffc.aa.Env.Env(), com.cliffc.aa.Parse.fact(), com.cliffc.aa.Env.file_scope(), com.cliffc.aa.Parse.get_display_ptr(), com.cliffc.aa.Parse.go(), com.cliffc.aa.Env.lookup_scope(), com.cliffc.aa.Env.lookup_type(), com.cliffc.aa.Parse.scope(), and com.cliffc.aa.Env.top_scope().
ALL
ConNode com.cliffc.aa.Env.ALL static
Definition at line 25 of file Env.java.
Referenced by com.cliffc.aa.node.PrimNode.as_fun(), and com.cliffc.aa.Env.top_scope().
ALL_CALL
ConNode com.cliffc.aa.Env.ALL_CALL static
Definition at line 26 of file Env.java.
Referenced by com.cliffc.aa.node.MemPrimNode.ReadPrimNode.as_fun(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.as_fun(), com.cliffc.aa.node.PrimNode.as_fun(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun(), com.cliffc.aa.node.IntrinsicNode.convertTypeName(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.node.AssertNode.ideal_grow(), and com.cliffc.aa.Env.top_scope().
ALL_CTRL
ConNode com.cliffc.aa.Env.ALL_CTRL static
Definition at line 20 of file Env.java.
Referenced by com.cliffc.aa.node.MemPrimNode.ReadPrimNode.as_fun(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.as_fun(), com.cliffc.aa.node.PrimNode.as_fun(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun(), com.cliffc.aa.node.IntrinsicNode.convertTypeName(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.node.Node.dumprpo(), com.cliffc.aa.Parse.func(), com.cliffc.aa.node.FunNode.FunNode(), com.cliffc.aa.node.FunNode.has_unknown_callers(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.RegionNode.ideal_reduce(), com.cliffc.aa.node.PhiNode.ideal_reduce(), com.cliffc.aa.node.FunNode.ideal_reduce(), com.cliffc.aa.node.FunPtrNode.merge_ref_def(), com.cliffc.aa.Parse.remove_unknown_callers(), com.cliffc.aa.Env.top_scope(), com.cliffc.aa.node.ConNode< T extends Type >.value(), and com.cliffc.aa.node.ConNode< T extends Type >.xstr().
ALL_DISPLAYS
BitsAlias com.cliffc.aa.Env.ALL_DISPLAYS = BitsAlias.EMPTY static
Definition at line 28 of file Env.java.
Referenced by com.cliffc.aa.Env.init(), com.cliffc.aa.type.TypeMemPtr.is_display_ptr(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), and com.cliffc.aa.Env.top_reset().
ANY
ConNode com.cliffc.aa.Env.ANY static
Definition at line 24 of file Env.java.
Referenced by com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.FunPtrNode.FunPtrNode(), com.cliffc.aa.node.IfNode.ideal_reduce(), com.cliffc.aa.node.ProjNode.ideal_reduce(), com.cliffc.aa.node.FunPtrNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.node.CallNode.is_copy(), com.cliffc.aa.node.NewObjNode.promote_forward(), com.cliffc.aa.Parse.remove_unknown_callers(), com.cliffc.aa.Env.top_scope(), com.cliffc.aa.Parse.tuple(), and com.cliffc.aa.node.CallEpiNode.wire0().
CTL_0
CProjNode com.cliffc.aa.Env.CTL_0 static
Definition at line 15 of file Env.java.
Referenced by com.cliffc.aa.Env.Env(), and com.cliffc.aa.Env.top_scope().
DEFMEM
DefMemNode com.cliffc.aa.Env.DEFMEM static
Definition at line 19 of file Env.java.
Referenced by com.cliffc.aa.node.CallNode._ideal_grow(), com.cliffc.aa.Parse._short_circuit_expr(), com.cliffc.aa.node.MemJoinNode.add_alias_below(), com.cliffc.aa.node.NewNode< TypeStruct >.add_reduce_extra(), com.cliffc.aa.node.MemPrimNode.ReadPrimNode.as_fun(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.as_fun(), com.cliffc.aa.node.PrimNode.as_fun(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun(), com.cliffc.aa.node.TestNodeSmall.check(), com.cliffc.aa.node.MemSplitNode.check_split(), com.cliffc.aa.node.IntrinsicNode.convertTypeName(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.Parse.do_call0(), com.cliffc.aa.Parse.func(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.PrimNode.AndThen.ideal_grow(), com.cliffc.aa.node.PrimNode.OrElse.ideal_grow(), com.cliffc.aa.node.FunNode.ideal_inline(), com.cliffc.aa.node.NewObjNode.ideal_mono(), com.cliffc.aa.node.MrgProjNode.ideal_reduce(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.Env.init(), com.cliffc.aa.node.NewNode< TypeStruct >.kill2(), com.cliffc.aa.node.MProjNode.live_use(), com.cliffc.aa.Parse.remove_unknown_callers(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.Parse.string(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.Env.top_scope(), com.cliffc.aa.Parse.tuple(), com.cliffc.aa.node.MemJoinNode.value(), com.cliffc.aa.node.CallEpiNode.value(), and com.cliffc.aa.node.CallEpiNode.wire0().
GVN
final GVNGCM com.cliffc.aa.Env.GVN = new GVNGCM() static
Definition at line 13 of file Env.java.
Referenced by com.cliffc.aa.Parse._args(), com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.node.CallNode._ideal_grow(), com.cliffc.aa.Parse._short_circuit_expr(), com.cliffc.aa.node.TestNodeSmall._testMonotonicChain(), com.cliffc.aa.node.MrgProjNode.add_flow_def_extra(), com.cliffc.aa.node.RegionNode.add_flow_def_extra(), com.cliffc.aa.node.NewNode< TypeStruct >.add_flow_def_extra(), com.cliffc.aa.node.CallNode.add_flow_def_extra(), com.cliffc.aa.node.FreshNode.add_flow_extra(), com.cliffc.aa.node.CastNode.add_flow_extra(), com.cliffc.aa.node.StoreNode.add_flow_extra(), com.cliffc.aa.node.NewObjNode.add_flow_extra(), com.cliffc.aa.node.FunPtrNode.add_flow_extra(), com.cliffc.aa.node.CallNode.add_flow_extra(), com.cliffc.aa.node.CProjNode.add_flow_use_extra(), com.cliffc.aa.node.MProjNode.add_flow_use_extra(), com.cliffc.aa.node.ParmNode.add_flow_use_extra(), com.cliffc.aa.node.AssertNode.add_flow_use_extra(), com.cliffc.aa.node.NewStrNode.AddStrStr.add_flow_use_extra(), com.cliffc.aa.node.FunPtrNode.add_flow_use_extra(), com.cliffc.aa.node.RegionNode.add_flow_use_extra(), com.cliffc.aa.node.LoadNode.add_flow_use_extra(), com.cliffc.aa.node.CallEpiNode.add_flow_use_extra(), com.cliffc.aa.node.CallNode.add_flow_use_extra(), com.cliffc.aa.node.MemSplitNode.add_reduce_extra(), com.cliffc.aa.node.NewNode< TypeStruct >.add_reduce_extra(), com.cliffc.aa.node.StoreNode.add_reduce_extra(), com.cliffc.aa.node.CallNode.add_reduce_extra(), com.cliffc.aa.node.PrimNode.as_fun(), com.cliffc.aa.node.CastNode.CastNode(), com.cliffc.aa.Env.close(), com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.IntrinsicNode.convertTypeName(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.node.CastNode.copy(), com.cliffc.aa.node.NewNode< TypeStruct >.copy(), com.cliffc.aa.node.Node.copy(), com.cliffc.aa.node.NewObjNode.create_active(), com.cliffc.aa.Parse.do_call0(), com.cliffc.aa.node.Node.do_flow(), com.cliffc.aa.node.Node.do_grow(), com.cliffc.aa.node.Node.do_mono(), com.cliffc.aa.node.Node.do_reduce(), com.cliffc.aa.Env.Env(), com.cliffc.aa.node.UnresolvedNode.filter(), com.cliffc.aa.node.IfNode.flip(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.LoadNode.ideal_grow(), com.cliffc.aa.node.PrimNode.AndThen.ideal_grow(), com.cliffc.aa.node.PrimNode.OrElse.ideal_grow(), com.cliffc.aa.node.FunNode.ideal_inline(), com.cliffc.aa.node.NewObjNode.ideal_mono(), com.cliffc.aa.node.IfNode.ideal_reduce(), com.cliffc.aa.node.RegionNode.ideal_reduce(), com.cliffc.aa.node.StoreNode.ideal_reduce(), com.cliffc.aa.node.ScopeNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.node.FunNode.ideal_reduce(), com.cliffc.aa.Parse.ifex(), com.cliffc.aa.node.ScopeNode.init(), com.cliffc.aa.Env.init(), com.cliffc.aa.node.Node.init1(), com.cliffc.aa.node.MemSplitNode.insert_split(), com.cliffc.aa.node.NewNode< TypeStruct >.kill2(), com.cliffc.aa.Env.lookup_filter_fresh(), com.cliffc.aa.node.FunNode.make_new_fun(), com.cliffc.aa.node.Node.merge(), com.cliffc.aa.node.FunPtrNode.merge_ref_def(), com.cliffc.aa.node.Node.more_flow(), com.cliffc.aa.node.Node.more_ideal(), com.cliffc.aa.Parse.Parse(), com.cliffc.aa.node.NewObjNode.promote_forward(), com.cliffc.aa.Env.record_for_top_reset2(), com.cliffc.aa.node.ScopeNode.replace_mem(), com.cliffc.aa.GVNGCM.retype_mem(), com.cliffc.aa.node.CallEpiNode.set_is_copy(), com.cliffc.aa.node.FunNode.set_is_copy(), com.cliffc.aa.node.ScopeNode.set_mem(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.node.FunNode.split_size(), com.cliffc.aa.Parse.stmts(), com.cliffc.aa.node.CallNode.swap_new(), com.cliffc.aa.node.RetNode.tail_recursive(), com.cliffc.aa.Parse.term(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.node.TestNodeSmall.testMemoryArgs(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.TestLive.testNewObj(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.node.TestNodeSmall.testUnresolvedAdd(), com.cliffc.aa.Env.top_reset(), com.cliffc.aa.Env.top_scope(), com.cliffc.aa.node.Node.unelock(), com.cliffc.aa.node.Node.unhook(), com.cliffc.aa.tvar.TV2.unify_at(), com.cliffc.aa.tvar.TV2.union(), com.cliffc.aa.node.Node.unuse(), com.cliffc.aa.node.FunNode.unwire(), com.cliffc.aa.node.CallEpiNode.unwire(), com.cliffc.aa.node.NewObjNode.update(), com.cliffc.aa.node.Node.walk_opt(), and com.cliffc.aa.node.Node.xval().
LEX_DISPLAYS
BitsAlias com.cliffc.aa.Env.LEX_DISPLAYS = BitsAlias.EMPTY static
Definition at line 31 of file Env.java.
Referenced by com.cliffc.aa.Env.close_display(), com.cliffc.aa.node.FunPtrNode.forward_ref(), com.cliffc.aa.Env.init(), com.cliffc.aa.node.NewObjNode.promote_forward(), and com.cliffc.aa.Env.top_reset().
MEM_0
StartMemNode com.cliffc.aa.Env.MEM_0 static
Definition at line 16 of file Env.java.
Referenced by com.cliffc.aa.Env.Env(), and com.cliffc.aa.Env.top_scope().
NIL
ConNode com.cliffc.aa.Env.NIL static
Definition at line 23 of file Env.java.
Referenced by com.cliffc.aa.Env.top_scope().
SCP_0
ScopeNode com.cliffc.aa.Env.SCP_0 static
Definition at line 18 of file Env.java.
Referenced by com.cliffc.aa.node.ScopeNode.init(), com.cliffc.aa.node.ScopeNode.live(), com.cliffc.aa.node.ScopeNode.live_use(), and com.cliffc.aa.Env.top_scope().
START
StartNode com.cliffc.aa.Env.START static
Definition at line 14 of file Env.java.
Referenced by com.cliffc.aa.node.MemJoinNode.add_alias_below_new(), com.cliffc.aa.GVNGCM.check_and_wire(), com.cliffc.aa.node.ConNode< T extends Type >.ConNode(), com.cliffc.aa.node.ConTypeNode.ConTypeNode(), com.cliffc.aa.Exec.dump(), com.cliffc.aa.Parse.dumprpo(), com.cliffc.aa.Parse.err_ctrl1(), com.cliffc.aa.AA.f(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.node.FunNode.ideal_inline(), com.cliffc.aa.node.MemSplitNode.insert_split(), com.cliffc.aa.GVNGCM.iter(), com.cliffc.aa.node.FunPtrNode.merge_ref_def(), com.cliffc.aa.AA.p(), com.cliffc.aa.AA.plive(), com.cliffc.aa.GVNGCM.remove_ambi(), and com.cliffc.aa.Env.top_scope().
STK_0
NewObjNode com.cliffc.aa.Env.STK_0 static
Definition at line 17 of file Env.java.
Referenced by com.cliffc.aa.Env.top_scope().
XCTRL
ConNode com.cliffc.aa.Env.XCTRL static
Definition at line 21 of file Env.java.
Referenced by com.cliffc.aa.Parse.do_exit(), com.cliffc.aa.node.FunNode.ideal_reduce(), com.cliffc.aa.node.IfNode.is_copy(), com.cliffc.aa.Parse.remove_unknown_callers(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.node.RetNode.tail_recursive(), com.cliffc.aa.Env.top_scope(), and com.cliffc.aa.node.CallEpiNode.unwire().
XNIL
ConNode com.cliffc.aa.Env.XNIL static
Definition at line 22 of file Env.java.
Referenced by com.cliffc.aa.Parse.do_exit(), com.cliffc.aa.Env.Env(), com.cliffc.aa.node.PrimNode.AndThen.ideal_grow(), com.cliffc.aa.Parse.ifex(), com.cliffc.aa.Parse.inc(), com.cliffc.aa.Parse.stmt(), and com.cliffc.aa.Env.top_scope().
The documentation for this class was generated from the following file:
Env.java