aa: com.cliffc.aa.HM.HM2.Syntax Class Reference
com.cliffc.aa.HM.HM2.Syntax Class Reference abstract
Package Functions
abstract void get_ids ()
abstract HMType hm (HashSet< HMVar > nongen)
Detailed Description
Definition at line 103 of file HM2.java.
Member Function Documentation
get_ids()
abstract void com.cliffc.aa.HM.HM2.Syntax.get_ids () abstract package
Reimplemented in com.cliffc.aa.HM.HM2.Apply, com.cliffc.aa.HM.HM2.Let, com.cliffc.aa.HM.HM2.Lambda, com.cliffc.aa.HM.HM2.Ident, and com.cliffc.aa.HM.HM2.Con.
Referenced by com.cliffc.aa.HM.HM2.Lambda.get_ids(), com.cliffc.aa.HM.HM2.Let.get_ids(), com.cliffc.aa.HM.HM2.Apply.get_ids(), and com.cliffc.aa.HM.HM2.hm().
hm()
abstract HMType com.cliffc.aa.HM.HM2.Syntax.hm (HashSet< HMVar > nongen) abstract package
Reimplemented in com.cliffc.aa.HM.HM2.Apply, com.cliffc.aa.HM.HM2.Let, com.cliffc.aa.HM.HM2.Lambda, com.cliffc.aa.HM.HM2.Ident, and com.cliffc.aa.HM.HM2.Con.
Referenced by com.cliffc.aa.HM.HM2.hm(), com.cliffc.aa.HM.HM2.Lambda.hm(), com.cliffc.aa.HM.HM2.Let.hm(), and com.cliffc.aa.HM.HM2.Apply.hm().
The documentation for this class was generated from the following file:
HM2.java