aa: com.cliffc.aa.HM.TestHM Class Reference
com.cliffc.aa.HM.TestHM Class Reference
Public Member Functions
void reset ()
void test00 ()
void test01 ()
void test02 ()
void test03 ()
void test04 ()
void test05 ()
void test06 ()
void test07 ()
void test08 ()
void test09 ()
void test10 ()
void test11 ()
void test12 ()
void test13 ()
void test14 ()
void test15 ()
void test16 ()
void test17 ()
void test18 ()
void test19 ()
void test20 ()
void test21 ()
void test22 ()
void test23 ()
void test24 ()
void test25 ()
void test26 ()
void test27 ()
void test28 ()
void test29 ()
void test30 ()
void test31 ()
void test32 ()
void test33 ()
void test34 ()
void test35 ()
void test36 ()
void test37 ()
void test38 ()
void test39 ()
void test40 ()
void test41 ()
void test42 ()
void test43 ()
void test44 ()
void test45 ()
void test46 ()
void test47 ()
void test48 ()
void test49 ()
void test50 ()
void test51 ()
void test52 ()
void test53 ()
void test54 ()
void test55 ()
void test56 ()
void test57 ()
Private Member Functions
void run (String prog, String rez_hm, Type rez_gcp)
Static Private Member Functions
static TypeMemPtr build_cycle (int alias, boolean nil, Type fld)
static TypeMemPtr build_cycle2 (boolean nil, Type fld)
static TypeStruct make_tups (Type t0, Type t1)
static TypeStruct make_tups (Type t0, Type t1, Type t2)
static TypeFunSig tfs (Type ret)
Static Private Attributes
static final TypeFunSig ret_tuple2 = tfs(tuple2)
static final TypeMemPtr tuple2 = TypeMemPtr.make(7,make_tups(Type.SCALAR, Type.SCALAR))
static final TypeMemPtr tuple55 = TypeMemPtr.make(7,make_tups(TypeInt.con(5),TypeInt.con(5)))
static final TypeMemPtr tuple82 = TypeMemPtr.make(7,make_tups(TypeInt.NINT8, TypeInt.NINT8))
static final TypeMemPtr tuple9 = TypeMemPtr.make(9,TypeStruct.make(TypeStruct.flds(Type.SCALAR,Type.SCALAR)))
static final TypeMemPtr tuplen2 = TypeMemPtr.make(7,make_tups(Type.NSCALR, Type.NSCALR))
Detailed Description
Definition at line 10 of file TestHM.java.
Member Function Documentation
build_cycle()
static TypeMemPtr com.cliffc.aa.HM.TestHM.build_cycle (int alias, boolean nil, Type fld) static private
Definition at line 237 of file TestHM.java.
{
     // Build a cycle of length 2.
     BitsAlias aliases = BitsAlias.make0(alias);
     if( nil ) aliases = aliases.meet_nil();
     TypeMemPtr cycle_ptr0 = TypeMemPtr.make(aliases,TypeObj.XOBJ);
     TypeStruct cycle_str1 = TypeStruct.make(TypeFld.NO_DISP,TypeFld.make("n1",cycle_ptr0,1),TypeFld.make("v1",fld,2));
     TypeMemPtr cycle_ptr1 = TypeMemPtr.make(aliases,cycle_str1);
     TypeStruct cycle_str2 = TypeStruct.make(TypeFld.NO_DISP,TypeFld.make("n1",cycle_ptr1,1),TypeFld.make("v1",fld,2));
     TypeStruct cycle_strn = cycle_str2.approx(1,alias);
     TypeMemPtr cycle_ptrn = (TypeMemPtr)cycle_strn.at(1);
     return cycle_ptrn;
   }
References com.cliffc.aa.type.TypeStruct.approx(), com.cliffc.aa.type.TypeStruct.at(), com.cliffc.aa.type.TypeFld.make(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.BitsAlias.make0(), com.cliffc.aa.type.Bits< B extends Bits< B >.meet_nil(), com.cliffc.aa.type.TypeFld.NO_DISP, and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.XOBJ.
Referenced by com.cliffc.aa.HM.TestHM.test32(), com.cliffc.aa.HM.TestHM.test33(), and com.cliffc.aa.HM.TestHM.test34().
build_cycle2()
static TypeMemPtr com.cliffc.aa.HM.TestHM.build_cycle2 (boolean nil, Type fld) static private
Definition at line 249 of file TestHM.java.
{
     // Unrolled, known to only produce results where either other nested
     // struct is from a different allocation site.
     BitsAlias aliases0 = BitsAlias.make0(10);
     BitsAlias aliases9 = BitsAlias.make0( 9);
     if( nil ) aliases0 = aliases0.meet_nil();
     if( nil ) aliases9 = aliases9.meet_nil();
     TypeMemPtr cycle_ptr0 = TypeMemPtr.make(aliases0,TypeObj.XOBJ);
     TypeStruct cycle_str1 = TypeStruct.make(TypeFld.NO_DISP,TypeFld.make("n1",cycle_ptr0,1),TypeFld.make("v1",fld,2));
     TypeMemPtr cycle_ptr1 = TypeMemPtr.make(aliases9,cycle_str1);
     TypeStruct cycle_str2 = TypeStruct.make(TypeFld.NO_DISP,TypeFld.make("n1",cycle_ptr1,1),TypeFld.make("v1",fld,2));
     TypeMemPtr cycle_ptr2 = TypeMemPtr.make(aliases0,cycle_str2);
     TypeStruct cycle_str3 = TypeStruct.make(TypeFld.NO_DISP,TypeFld.make("n1",cycle_ptr2,1),TypeFld.make("v1",fld,2));
     TypeStruct cycle_strn = cycle_str3.approx(1,9);
     TypeMemPtr cycle_ptrn = (TypeMemPtr)cycle_strn.at(1);
     return cycle_ptrn;
   }
References com.cliffc.aa.type.TypeStruct.approx(), com.cliffc.aa.type.TypeStruct.at(), com.cliffc.aa.type.TypeFld.make(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.BitsAlias.make0(), com.cliffc.aa.type.Bits< B extends Bits< B >.meet_nil(), com.cliffc.aa.type.TypeFld.NO_DISP, and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.XOBJ.
Referenced by com.cliffc.aa.HM.TestHM.test36(), and com.cliffc.aa.HM.TestHM.test56().
make_tups() [1/2]
static TypeStruct com.cliffc.aa.HM.TestHM.make_tups (Type t0, Type t1) static private
Definition at line 26 of file TestHM.java.
 { return TypeStruct.make(TypeStruct.tups(t0,t1   )); }
References com.cliffc.aa.type.TypeStruct.make(), and com.cliffc.aa.type.TypeStruct.tups().
Referenced by com.cliffc.aa.HM.TestHM.test02(), com.cliffc.aa.HM.TestHM.test06(), com.cliffc.aa.HM.TestHM.test14(), com.cliffc.aa.HM.TestHM.test18(), com.cliffc.aa.HM.TestHM.test20(), com.cliffc.aa.HM.TestHM.test35(), com.cliffc.aa.HM.TestHM.test41(), com.cliffc.aa.HM.TestHM.test49(), and com.cliffc.aa.HM.TestHM.test50().
make_tups() [2/2]
static TypeStruct com.cliffc.aa.HM.TestHM.make_tups (Type t0, Type t1, Type t2) static private
Definition at line 27 of file TestHM.java.
 { return TypeStruct.make(TypeStruct.tups(t0,t1,t2)); }
References com.cliffc.aa.type.TypeStruct.make(), and com.cliffc.aa.type.TypeStruct.tups().
reset()
void com.cliffc.aa.HM.TestHM.reset ()
Definition at line 12 of file TestHM.java.
 { HM.reset(); }
References com.cliffc.aa.HM.HM.reset().
run()
void com.cliffc.aa.HM.TestHM.run (String prog, String rez_hm, Type rez_gcp) private
Definition at line 14 of file TestHM.java.
{
     Root syn = HM.hm(prog);
     if( HM.DO_HM )
       assertEquals(rez_hm,syn._hmt.p());
     if( HM.DO_GCP )
       assertEquals(rez_gcp,syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), and com.cliffc.aa.HM.HM.T2.p().
Referenced by com.cliffc.aa.HM.TestHM.test00(), com.cliffc.aa.HM.TestHM.test01(), com.cliffc.aa.HM.TestHM.test02(), com.cliffc.aa.HM.TestHM.test03(), com.cliffc.aa.HM.TestHM.test04(), com.cliffc.aa.HM.TestHM.test07(), com.cliffc.aa.HM.TestHM.test08(), com.cliffc.aa.HM.TestHM.test09(), com.cliffc.aa.HM.TestHM.test10(), com.cliffc.aa.HM.TestHM.test11(), com.cliffc.aa.HM.TestHM.test12(), com.cliffc.aa.HM.TestHM.test13(), com.cliffc.aa.HM.TestHM.test15(), com.cliffc.aa.HM.TestHM.test16(), com.cliffc.aa.HM.TestHM.test17(), com.cliffc.aa.HM.TestHM.test19(), com.cliffc.aa.HM.TestHM.test21(), com.cliffc.aa.HM.TestHM.test22(), com.cliffc.aa.HM.TestHM.test23(), com.cliffc.aa.HM.TestHM.test24(), com.cliffc.aa.HM.TestHM.test25(), com.cliffc.aa.HM.TestHM.test26(), com.cliffc.aa.HM.TestHM.test27(), com.cliffc.aa.HM.TestHM.test28(), com.cliffc.aa.HM.TestHM.test29(), com.cliffc.aa.HM.TestHM.test30(), com.cliffc.aa.HM.TestHM.test31(), com.cliffc.aa.HM.TestHM.test35(), com.cliffc.aa.HM.TestHM.test37(), com.cliffc.aa.HM.TestHM.test38(), com.cliffc.aa.HM.TestHM.test46(), com.cliffc.aa.HM.TestHM.test47(), com.cliffc.aa.HM.TestHM.test48(), com.cliffc.aa.HM.TestHM.test53(), and com.cliffc.aa.HM.TestHM.test54().
test00()
void com.cliffc.aa.HM.TestHM.test00 ()
Definition at line 36 of file TestHM.java.
 { run( "fred",null,null); }
References com.cliffc.aa.HM.TestHM.run().
test01()
void com.cliffc.aa.HM.TestHM.test01 ()
Definition at line 38 of file TestHM.java.
                              { run( "3" ,
                                     "3", TypeInt.con(3));  }
References com.cliffc.aa.type.TypeInt.con(), and com.cliffc.aa.HM.TestHM.run().
test02()
void com.cliffc.aa.HM.TestHM.test02 ()
Definition at line 41 of file TestHM.java.
                              { run( "(pair1 3)" ,
                                     "{ A -> ( 3, A) }", tfs(TypeMemPtr.make(7,make_tups(TypeInt.con(3),Type.SCALAR)))); }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.HM.TestHM.make_tups(), com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM.tfs().
test03()
void com.cliffc.aa.HM.TestHM.test03 ()
Definition at line 44 of file TestHM.java.
                              { run( "{ z -> (pair (z 0) (z \"abc\")) }" ,
                                     "{ { *[0,4]\"abc\"? -> A } -> ( A, A) }", tfs(tuple2)); }
References com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.HM.TestHM.tfs(), and com.cliffc.aa.HM.TestHM.tuple2.
test04()
void com.cliffc.aa.HM.TestHM.test04 ()
Definition at line 47 of file TestHM.java.
                              { run( "fact = { n -> (if (eq0 n) 1 (* n (fact (dec n))))}; fact",
                                     "{ int64 -> int64 }", tfs(TypeInt.INT64) ); }
References com.cliffc.aa.type.TypeInt.INT64, com.cliffc.aa.HM.TestHM.run(), and com.cliffc.aa.HM.TestHM.tfs().
test05()
void com.cliffc.aa.HM.TestHM.test05 ()
Definition at line 52 of file TestHM.java.
{
     Root syn = HM.hm("({ x -> (pair (x 3) (x 5)) } {y->y})");
     if( HM.DO_HM )
       assertEquals("( nint8, nint8)",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM )
         assertEquals(tuple82,syn.flow_type());
       else
         assertEquals(tuple82,syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.T2.p(), and com.cliffc.aa.HM.TestHM.tuple82.
test06()
void com.cliffc.aa.HM.TestHM.test06 ()
Definition at line 63 of file TestHM.java.
{
     Root syn = HM.hm("id={x->x}; (pair (id 3) (id \"abc\"))");
     if( HM.DO_HM ) // HM is sharper here than in test05, because id is generalized per each use site
       assertEquals("( 3, *[4]\"abc\")",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM )
         assertEquals(TypeMemPtr.make(7,make_tups(TypeInt.con(3),TypeMemPtr.make(4,TypeStr.ABC))),syn.flow_type());
       else
         assertEquals(tuplen2,syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeStr.ABC, com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.HM.TestHM.make_tups(), com.cliffc.aa.HM.HM.T2.p(), and com.cliffc.aa.HM.TestHM.tuplen2.
test07()
void com.cliffc.aa.HM.TestHM.test07 ()
Definition at line 75 of file TestHM.java.
                              { run( "{ f -> (f f) }",
     // We can argue the pretty-print should print:
     //                              "  A:{ A -> B }"
                                     "{ A:{ A -> B } -> B }", tfs(Type.SCALAR) ); }
References com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM.tfs().
test08()
void com.cliffc.aa.HM.TestHM.test08 ()
Definition at line 80 of file TestHM.java.
                              { run( "g = {f -> 5}; (g g)",
                                     "5", TypeInt.con(5)); }
References com.cliffc.aa.type.TypeInt.con(), and com.cliffc.aa.HM.TestHM.run().
test09()
void com.cliffc.aa.HM.TestHM.test09 ()
Definition at line 84 of file TestHM.java.
                              { run( "{ g -> f = { x -> g }; (pair (f 3) (f \"abc\"))}",
                                     "{ A -> ( A, A) }", ret_tuple2); }
References com.cliffc.aa.HM.TestHM.ret_tuple2, and com.cliffc.aa.HM.TestHM.run().
test10()
void com.cliffc.aa.HM.TestHM.test10 ()
Definition at line 87 of file TestHM.java.
                              { run( "{ f g -> (f g)}",
                                     "{ { A -> B } A -> B }", tfs(Type.SCALAR) ); }
References com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM.tfs().
test11()
void com.cliffc.aa.HM.TestHM.test11 ()
Definition at line 91 of file TestHM.java.
                              { run( "{ f g -> { arg -> (g (f arg))} }",
                                     "{ { A -> B } { B -> C } -> { A -> C } }", tfs(tfs(Type.SCALAR))); }
References com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM.tfs().
test12()
void com.cliffc.aa.HM.TestHM.test12 ()
Definition at line 95 of file TestHM.java.
                              { run( "map = { fun -> { x -> 2 } }; ((map 3) 5)",
                                     "2", TypeInt.con(2)); }
References com.cliffc.aa.type.TypeInt.con(), and com.cliffc.aa.HM.TestHM.run().
test13()
void com.cliffc.aa.HM.TestHM.test13 ()
Definition at line 99 of file TestHM.java.
                              { run( "map = { fun -> { x -> (fun x)}}; { p -> 5 }",
                                     "{ A -> 5 }", tfs(TypeInt.con(5))); }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.TestHM.run(), and com.cliffc.aa.HM.TestHM.tfs().
test14()
void com.cliffc.aa.HM.TestHM.test14 ()
Definition at line 105 of file TestHM.java.
{
     Root syn = HM.hm("map = { fun -> { x -> (fun x)}};"+
                      "(pair ((map str) 5) ((map factor) 2.3))");
     if( HM.DO_HM )
       assertEquals("( *[4]str, flt64)",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM )
         assertEquals(TypeMemPtr.make(7,make_tups(TypeMemPtr.STRPTR,TypeFlt.FLT64)),syn.flow_type());
       else
         assertEquals(tuple2,syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.type.TypeFlt.FLT64, com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.HM.TestHM.make_tups(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.TypeMemPtr.STRPTR, and com.cliffc.aa.HM.TestHM.tuple2.
test15()
void com.cliffc.aa.HM.TestHM.test15 ()
Definition at line 118 of file TestHM.java.
                              { run("map = { fun x -> (fun x)}; (map {a->3} 5)",
                                    "3", TypeInt.con(3)); }
References com.cliffc.aa.type.TypeInt.con(), and com.cliffc.aa.HM.TestHM.run().
test16()
void com.cliffc.aa.HM.TestHM.test16 ()
Definition at line 122 of file TestHM.java.
                              { run("map = { fun x -> (fun x)}; (map { a-> (pair a a)} 5)",
                                    "( 5, 5)", tuple55); }
References com.cliffc.aa.HM.TestHM.run(), and com.cliffc.aa.HM.TestHM.tuple55.
test17()
void com.cliffc.aa.HM.TestHM.test17 ()
Definition at line 125 of file TestHM.java.
                              { run("fcn = { p -> { a -> (pair a a) }};"+
                                    "map = { fun x -> (fun x)};"+
                                    "{ q -> (map (fcn q) 5)}",
                                    "{ A -> ( 5, 5) }", tfs(tuple55)); }
References com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.HM.TestHM.tfs(), and com.cliffc.aa.HM.TestHM.tuple55.
test18()
void com.cliffc.aa.HM.TestHM.test18 ()
Definition at line 140 of file TestHM.java.
{
     Root syn = HM.hm("fcn = {p -> (if p {a -> (pair a a)} {b -> (pair b (pair 3 b))})};"+
                      "map = { fun x -> (fun x)};"+
                      "{ q -> (map (fcn q) 5)}");
     if( HM.DO_HM )
       assertEquals("{ A? -> ( B:Cannot unify A:( 3, A) and 5, B) }",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM )
         assertEquals(tfs(TypeMemPtr.make(7,make_tups(Type.XNSCALR,TypeMemPtr.make(7,make_tups(TypeInt.con(3),Type.XNSCALR))))),syn.flow_type());
       else
         assertEquals(tfs(TypeMemPtr.make(7,make_tups(TypeInt.con(5),Type.NSCALR))),syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.HM.TestHM.make_tups(), com.cliffc.aa.type.Type< T extends Type< T >.NSCALR, com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.HM.TestHM.tfs(), and com.cliffc.aa.type.Type< T extends Type< T >.XNSCALR.
test19()
void com.cliffc.aa.HM.TestHM.test19 ()
Definition at line 153 of file TestHM.java.
                              { run("cons ={x y-> {cadr -> (cadr x y)}};"+
                                    "cdr ={mycons -> (mycons { p q -> q})};"+
                                    "(cdr (cons 2 3))",
                                    "3", TypeInt.con(3)); }
References com.cliffc.aa.type.TypeInt.con(), and com.cliffc.aa.HM.TestHM.run().
test20()
void com.cliffc.aa.HM.TestHM.test20 ()
Definition at line 165 of file TestHM.java.
{
     Root syn = HM.hm("cons ={x y-> {cadr -> (cadr x y)}};"+
                      "cdr ={mycons -> (mycons { p q -> q})};"+
                      "map ={fun parg -> (fun (cdr parg))};"+
                      "(pair (map str (cons 0 5)) (map isempty (cons 0 \"abc\")))");
     if( HM.DO_HM )
       assertEquals("( *[4]str, int1)",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM )
         assertEquals(TypeMemPtr.make(7,make_tups(TypeMemPtr.STRPTR,TypeInt.BOOL)),syn.flow_type());
       else
         assertEquals(tuple2,syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeInt.BOOL, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.HM.TestHM.make_tups(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.TypeMemPtr.STRPTR, and com.cliffc.aa.HM.TestHM.tuple2.
test21()
void com.cliffc.aa.HM.TestHM.test21 ()
Definition at line 180 of file TestHM.java.
                              { run("f0 = { f x -> (if (eq0 x) 1 (f (f0 f (dec x)) 2))}; (f0 * 99)",
                                    "int64", TypeInt.INT64); }
References com.cliffc.aa.type.TypeInt.INT64, and com.cliffc.aa.HM.TestHM.run().
test22()
void com.cliffc.aa.HM.TestHM.test22 ()
Definition at line 186 of file TestHM.java.
                              { run("f0 = { f x -> (if (eq0 x) 1 (* (f0 f (dec x)) 2))}; (f0 f0 99)",
                                    "int64", TypeInt.INT64); }
References com.cliffc.aa.type.TypeInt.INT64, and com.cliffc.aa.HM.TestHM.run().
test23()
void com.cliffc.aa.HM.TestHM.test23 ()
Definition at line 190 of file TestHM.java.
                              { run("is_even = "+
                                    "  is_odd = { n -> (if (eq0 n) 0 (is_even (dec n)))}; "+
                                    "     { n -> (if (eq0 n) 1 (is_odd (dec n)))};"+
                                    "(is_even 3)" ,
                                    "int1", TypeInt.BOOL); }
References com.cliffc.aa.type.TypeInt.BOOL, and com.cliffc.aa.HM.TestHM.run().
test24()
void com.cliffc.aa.HM.TestHM.test24 ()
Definition at line 197 of file TestHM.java.
                              { run("{ g -> fgz = "+
                                    "         cons = {x y -> {cadr -> (cadr x y)}};"+
                                    "         cdr = {mycons -> (mycons { p q -> q})};"+
                                    "         (cdr (cons 2 { z -> (g z) }));"+
                                    "      (pair (fgz 3) (fgz 5))"+
                                    "}"
                                    ,
                                    "{ { nint8 -> A } -> ( A, A) }", tfs(tuple2)); }
References com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.HM.TestHM.tfs(), and com.cliffc.aa.HM.TestHM.tuple2.
test25()
void com.cliffc.aa.HM.TestHM.test25 ()
Definition at line 207 of file TestHM.java.
                              { run("@{x=2, y=3}",
                                    "@{ x = 2, y = 3}",
                                    TypeMemPtr.make(9,TypeStruct.make(TypeStruct.flds(TypeInt.con(2),TypeInt.con(3))))
                                    ); }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeStruct.make(), and com.cliffc.aa.HM.TestHM.run().
test26()
void com.cliffc.aa.HM.TestHM.test26 ()
Definition at line 213 of file TestHM.java.
                              { run("@{x =2, y =3}.x",
                                    "2", TypeInt.con(2)); }
References com.cliffc.aa.type.TypeInt.con(), and com.cliffc.aa.HM.TestHM.run().
test27()
void com.cliffc.aa.HM.TestHM.test27 ()
Definition at line 217 of file TestHM.java.
                              { run("5.x",
                                    "Missing field x in 5", Type.SCALAR); }
References com.cliffc.aa.HM.TestHM.run(), and com.cliffc.aa.type.Type< T extends Type< T >.SCALAR.
test28()
void com.cliffc.aa.HM.TestHM.test28 ()
Definition at line 221 of file TestHM.java.
                              { run("@{ y =3}.x",
                                    "Missing field x in @{ y = 3}",
                                    Type.SCALAR); }
References com.cliffc.aa.HM.TestHM.run(), and com.cliffc.aa.type.Type< T extends Type< T >.SCALAR.
test29()
void com.cliffc.aa.HM.TestHM.test29 ()
Definition at line 225 of file TestHM.java.
                              { run("{ g -> @{x=g, y=g}}",
                                    "{ A -> @{ x = A, y = A} }", tfs(tuple9)); }
References com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.HM.TestHM.tfs(), and com.cliffc.aa.HM.TestHM.tuple9.
test30()
void com.cliffc.aa.HM.TestHM.test30 ()
Definition at line 229 of file TestHM.java.
                              { run("{ pred -> (if pred @{x=2,y=3} @{x=3,z= \"abc\"}) .x }",
                                    "{ A? -> nint8 }", tfs(TypeInt.NINT8)); }
References com.cliffc.aa.type.TypeInt.NINT8, com.cliffc.aa.HM.TestHM.run(), and com.cliffc.aa.HM.TestHM.tfs().
test31()
void com.cliffc.aa.HM.TestHM.test31 ()
Definition at line 234 of file TestHM.java.
                              { run("{ sq -> (* sq.x sq.y) }", // { sq -> sq.x * sq.y }
                                    "{ @{ x = int64, y = int64} -> int64 }", tfs(TypeInt.INT64)); }
References com.cliffc.aa.type.TypeInt.INT64, com.cliffc.aa.HM.TestHM.run(), and com.cliffc.aa.HM.TestHM.tfs().
test32()
void com.cliffc.aa.HM.TestHM.test32 ()
Definition at line 271 of file TestHM.java.
{
     Root syn = HM.hm("map = { fcn lst -> @{ n1 = (map fcn lst.n0), v1 = (fcn lst.v0) } }; map");
     if( HM.DO_HM )
       assertEquals("{ { A -> B } C:@{ n0 = C, v0 = A} -> D:@{ n1 = D, v1 = B} }",syn._hmt.p());
     if( HM.DO_GCP )
       // Build a cycle of length 2, without nil.
       assertEquals(tfs(build_cycle(9,false,Type.SCALAR)),syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.TestHM.build_cycle(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM.tfs().
test33()
void com.cliffc.aa.HM.TestHM.test33 ()
Definition at line 283 of file TestHM.java.
{
     Root syn = HM.hm("map = { fcn lst -> (if lst @{ n1=(map fcn lst.n0), v1=(fcn lst.v0) } 0) }; map");
     if( HM.DO_HM )
       assertEquals("{ { A -> B } C:@{ n0 = C, v0 = A}? -> D:@{ n1 = D, v1 = B}? }",syn._hmt.p());
     if( HM.DO_GCP )
       // Build a cycle of length 2, with nil.
       assertEquals(tfs(build_cycle(9,true,Type.SCALAR)),syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.TestHM.build_cycle(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM.tfs().
test34()
void com.cliffc.aa.HM.TestHM.test34 ()
Definition at line 293 of file TestHM.java.
{
     Root syn = HM.hm("map = { fcn lst -> (if lst @{ n1 = (map fcn lst.n0), v1 = (fcn lst.v0) } 0) }; (map dec @{n0 = 0, v0 = 5})");
     if( HM.DO_HM )
       assertEquals("A:@{ n1 = A, v1 = int64}?",syn._hmt.p());
     if( HM.DO_GCP )
       assertEquals(build_cycle(9,true,TypeInt.con(4)),syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.TestHM.build_cycle(), com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), and com.cliffc.aa.HM.HM.T2.p().
test35()
void com.cliffc.aa.HM.TestHM.test35 ()
Definition at line 302 of file TestHM.java.
{
     TypeFunPtr tfp  = TypeFunPtr.make(16,3,Type.ANY);
     TypeMemPtr tmp0 = TypeMemPtr.make(8,make_tups(tfp ,tfp ,tfp ));
     TypeMemPtr tmp1 = TypeMemPtr.make(8,make_tups(tmp0,tmp0,tmp0));
     TypeMemPtr tmp2 = TypeMemPtr.make(8,make_tups(tmp1,tmp1,tmp1));
     run("p0 = { x y z -> (triple x y z) };"+
         "p1 = (triple p0 p0 p0);"+
         "p2 = (triple p1 p1 p1);"+
         "p3 = (triple p2 p2 p2);"+
         "p3",
         "( ( ( { A B C -> ( A, B, C) }, { D E F -> ( D, E, F) }, { G H I -> ( G, H, I) }), ( { J K L -> ( J, K, L) }, { M N O -> ( M, N, O) }, { P Q R -> ( P, Q, R) }), ( { S T U -> ( S, T, U) }, { V21 V22 V23 -> ( V21, V22, V23) }, { V24 V25 V26 -> ( V24, V25, V26) })), ( ( { V27 V28 V29 -> ( V27, V28, V29) }, { V30 V31 V32 -> ( V30, V31, V32) }, { V33 V34 V35 -> ( V33, V34, V35) }), ( { V36 V37 V38 -> ( V36, V37, V38) }, { V39 V40 V41 -> ( V39, V40, V41) }, { V42 V43 V44 -> ( V42, V43, V44) }), ( { V45 V46 V47 -> ( V45, V46, V47) }, { V48 V49 V50 -> ( V48, V49, V50) }, { V51 V52 V53 -> ( V51, V52, V53) })), ( ( { V54 V55 V56 -> ( V54, V55, V56) }, { V57 V58 V59 -> ( V57, V58, V59) }, { V60 V61 V62 -> ( V60, V61, V62) }), ( { V63 V64 V65 -> ( V63, V64, V65) }, { V66 V67 V68 -> ( V66, V67, V68) }, { V69 V70 V71 -> ( V69, V70, V71) }), ( { V72 V73 V74 -> ( V72, V73, V74) }, { V75 V76 V77 -> ( V75, V76, V77) }, { V78 V79 V80 -> ( V78, V79, V80) })))",
         tmp2  );
   }
References com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeFunPtr.make(), com.cliffc.aa.HM.TestHM.make_tups(), and com.cliffc.aa.HM.TestHM.run().
test36()
void com.cliffc.aa.HM.TestHM.test36 ()
Definition at line 319 of file TestHM.java.
{
     Root syn = HM.hm("map = { lst -> (if lst @{ n1= arg= lst.n0; (if arg @{ n1=(map arg.n0), v1=(str arg.v0)} 0), v1=(str lst.v0) } 0) }; map");
     if( HM.DO_HM )
       assertEquals("{ A:@{ n0 = @{ n0 = A, v0 = int64}?, v0 = int64}? -> B:@{ n1 = @{ n1 = B, v1 = *[4]str}?, v1 = *[4]str}? }",syn._hmt.p());
     if( HM.DO_GCP )
       assertEquals(tfs(build_cycle2(true,TypeMemPtr.STRPTR)),syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.TestHM.build_cycle2(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.TypeMemPtr.STRPTR, and com.cliffc.aa.HM.TestHM.tfs().
test37()
void com.cliffc.aa.HM.TestHM.test37 ()
Definition at line 327 of file TestHM.java.
                              { run("x = { y -> (x (y y))}; x",
                                    "{ A:{ A -> A } -> B }", tfs(Type.XSCALAR)); }
References com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.HM.TestHM.tfs(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
test38()
void com.cliffc.aa.HM.TestHM.test38 ()
Definition at line 332 of file TestHM.java.
                              { run("{ x -> y = ( x x.v ); 0}",
                                    "{ Cannot unify @{ v = A} and { A -> B } -> A? }", tfs(Type.XNIL)); }
References com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.HM.TestHM.tfs(), and com.cliffc.aa.type.Type< T extends Type< T >.XNIL.
test39()
void com.cliffc.aa.HM.TestHM.test39 ()
Definition at line 337 of file TestHM.java.
{
     Root syn = HM.hm("x = { z -> z}; (x { y -> y.u})");
     if( HM.DO_HM )
       assertEquals("{ @{ u = A} -> A }",syn._hmt.p());
     if( HM.DO_GCP )
       assertEquals(tfs(Type.SCALAR), syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM.tfs().
test40()
void com.cliffc.aa.HM.TestHM.test40 ()
Definition at line 349 of file TestHM.java.
{
     Root syn = HM.hm("x = w = (x x); { z -> z}; (x { y -> y.u})");
     if( HM.DO_HM )
       assertEquals("Cannot unify A:{ A -> A } and @{ u = A}",syn._hmt.p());
     if( HM.DO_GCP ) {
       if( HM.DO_HM ) {
         assertEquals(tfs(Type.SCALAR), syn.flow_type());
       } else {
         assertEquals(Type.SCALAR, syn.flow_type());
       }
     }
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM.tfs().
test41()
void com.cliffc.aa.HM.TestHM.test41 ()
Definition at line 369 of file TestHM.java.
{
     Root syn = HM.hm("map={lst fcn -> (fcn lst.y) }; "+
                      "in_int=@{ x=0 y=2}; " +
                      "in_str=@{ x=0 y=\"abc\"}; " +
                      "out_str = (map in_int str); " +
                      "out_bool= (map in_str { xstr -> (eq xstr \"def\")}); "+
                      "(pair out_str out_bool)");
     if( HM.DO_HM )
       assertEquals("( *[4]str, int1)",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM )
         assertEquals(TypeMemPtr.make(7,make_tups(TypeMemPtr.STRPTR,TypeInt.BOOL)),syn.flow_type());
       else
         assertEquals(tuple2,syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeInt.BOOL, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.HM.TestHM.make_tups(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.TypeMemPtr.STRPTR, and com.cliffc.aa.HM.TestHM.tuple2.
test42()
void com.cliffc.aa.HM.TestHM.test42 ()
Definition at line 386 of file TestHM.java.
{
     Root syn = HM.hm("pred = 0; s1 = @{ x=\"abc\" }; s2 = @{ y=3.4 }; (if pred s1 s2).y");
     if( HM.DO_HM ) {
       if( HM.DO_GCP )
         assertEquals("3.4000000953674316",syn._hmt.p());
       else
         assertEquals("Missing field y in @{ x = *[4]\"abc\"}",syn._hmt.p());
     }
     if( HM.DO_GCP )
       assertEquals(TypeFlt.con(3.4f), syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeFlt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), and com.cliffc.aa.HM.HM.T2.p().
test43()
void com.cliffc.aa.HM.TestHM.test43 ()
Definition at line 399 of file TestHM.java.
{
     Root syn = HM.hm("pred = 0; s1 = @{ x=\"abc\" }; s2 = @{ y=3.4 }; z = (if pred s1 s2); s2.y");
     if( HM.DO_HM )
       assertEquals("3.4000000953674316",syn._hmt.p());
     if( HM.DO_GCP )
       assertEquals(TypeFlt.con(3.4f), syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeFlt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), and com.cliffc.aa.HM.HM.T2.p().
test44()
void com.cliffc.aa.HM.TestHM.test44 ()
Definition at line 408 of file TestHM.java.
{
     Root syn = HM.hm("fun = (if (isempty \"abc\") {x->x} {x->1.2}); (fun @{})");
     if( HM.DO_HM ) {
       if( HM.DO_GCP )
         assertEquals("1.2000000476837158",syn._hmt.p());
       else
         assertEquals("Cannot unify 1.2000000476837158 and ()",syn._hmt.p());
     }
     if( HM.DO_GCP )
       assertEquals(TypeFlt.con(1.2f), syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeFlt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), and com.cliffc.aa.HM.HM.T2.p().
test45()
void com.cliffc.aa.HM.TestHM.test45 ()
Definition at line 422 of file TestHM.java.
{
     Root syn = HM.hm(
 "id = {x -> x};" +
 "loop = { name cnt ->" +
 "  (if cnt " +
 "    (loop" +
 "       fltfun = (if name id {x->3});" +
 "       (fltfun \"abc\")" +
 "       (dec cnt)" +
 "     )" +
 "     name" +
 "   )"+
 "};" +
 "(loop \"def\" (id 2))");
     if( HM.DO_HM )
       assertEquals(HM.DO_GCP
                    ? "*[0,4]str?"  // Both HM and GCP
                    : "Cannot unify *[4]\"abc\" and 3", // HM alone cannot do this one
                    syn._hmt.p());
     if( HM.DO_GCP )
       assertEquals(HM.DO_HM
                    ? TypeMemPtr.STRPTR // Both HM and GCP
                    : Type.NSCALR,      // GCP alone gets a very weak answer
                    syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.type.Type< T extends Type< T >.NSCALR, com.cliffc.aa.HM.HM.T2.p(), and com.cliffc.aa.type.TypeMemPtr.STRPTR.
test46()
void com.cliffc.aa.HM.TestHM.test46 ()
Definition at line 450 of file TestHM.java.
                              { run("0.x",
                                    "May be nil when loading field x", Type.XSCALAR); }
References com.cliffc.aa.HM.TestHM.run(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
test47()
void com.cliffc.aa.HM.TestHM.test47 ()
Definition at line 454 of file TestHM.java.
                              { run("{ pred -> (if pred @{x=3} 0).x}",
                                    "{ A? -> May be nil when loading field x }", tfs(TypeInt.con(3))); }
References com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.TestHM.run(), and com.cliffc.aa.HM.TestHM.tfs().
test48()
void com.cliffc.aa.HM.TestHM.test48 ()
Definition at line 458 of file TestHM.java.
                              { run("{ pred -> tmp=(if pred @{x=3} 0); (if tmp tmp.x 4) }",
                                    "{ A? -> nint8 }", tfs(TypeInt.NINT8)); }
References com.cliffc.aa.type.TypeInt.NINT8, com.cliffc.aa.HM.TestHM.run(), and com.cliffc.aa.HM.TestHM.tfs().
test49()
void com.cliffc.aa.HM.TestHM.test49 ()
Definition at line 463 of file TestHM.java.
{
     Root syn = HM.hm("{ pred -> \n"+
                      "  map = { fun x -> (fun x) };\n" +
                      "  (pair (map {str0 ->          str0.x   }          @{x = 3}   )\n" +
                      "        (map {str1 -> (if str1 str1.x 4)} (if pred @{x = 5} 0))\n" +
                      "  )\n"+
                      "}");
     if( HM.DO_HM )
       assertEquals("{ A? -> ( 3, nint8) }",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM ) assertEquals(tfs(TypeMemPtr.make(7,make_tups(TypeInt.con(3), TypeInt.NINT8 ))),syn.flow_type());
       else           assertEquals(tfs(TypeMemPtr.make(7,make_tups(TypeInt.NINT8 , TypeInt.NINT8 ))),syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.HM.TestHM.make_tups(), com.cliffc.aa.type.TypeInt.NINT8, com.cliffc.aa.HM.HM.T2.p(), and com.cliffc.aa.HM.TestHM.tfs().
test50()
void com.cliffc.aa.HM.TestHM.test50 ()
Definition at line 478 of file TestHM.java.
{
     Root syn = HM.hm("{ pred -> \n"+
                      "  map = { fun x -> (fun x) };\n" +
                      "  (pair (map {str0 ->          str0.x   }          @{x = 3}   )\n" +
                      "        (map {str1 ->          str1.x   } (if pred @{x = 5} 0))\n" +
                      "  )\n"+
                      "}");
     if( HM.DO_HM )
       assertEquals("{ A? -> May be nil when loading field x }",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM ) assertEquals(tfs(TypeMemPtr.make(7,make_tups(TypeInt.NINT8, TypeInt.NINT8 ))),syn.flow_type());
       else           assertEquals(tfs(TypeMemPtr.make(7,make_tups(TypeInt.NINT8, TypeInt.NINT8 ))),syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.HM.TestHM.make_tups(), com.cliffc.aa.type.TypeInt.NINT8, com.cliffc.aa.HM.HM.T2.p(), and com.cliffc.aa.HM.TestHM.tfs().
test51()
void com.cliffc.aa.HM.TestHM.test51 ()
Definition at line 492 of file TestHM.java.
{
     Root syn = HM.hm("total_size = { a as ->" +  // Total_size takes an 'a' and a list of 'as'
                      "  (if as "+                // If list is not empty then
                      "      (+ a.size "+         // Add the size of 'a' to
                      "         (total_size as.val as.next))" + // the size of the rest of the list
                      "      a.size"+             // Else the list is empty, just take the a.size
                      "  )"+                      // End of (if as...)
                      "};" +                      // End of total_size={...}
                      "total_size"                // What is this type?
                      );
     if( HM.DO_HM )
       assertEquals("{ A:@{ size = int64} B:@{ next = B, val = A}? -> int64 }",syn._hmt.p());
     if( HM.DO_GCP )
       if( HM.DO_HM ) assertEquals(tfs(TypeInt.INT64),syn.flow_type());
       else           assertEquals(tfs(Type.SCALAR  ),syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.type.TypeInt.INT64, com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM.tfs().
test52()
void com.cliffc.aa.HM.TestHM.test52 ()
Definition at line 510 of file TestHM.java.
{
     Root syn = HM.hm("void = @{};"+              // Same as '()'; all empty structs are alike
                      "true = @{"+                // 'true' is a struct with and,or,thenElse
                      "  and= {b -> b}"+
                      "  or = {b -> true}"+
                      "  thenElse = {then else->(then void) }"+
                      "};"+
                      "false = @{"+               // 'false' is a struct with and,or,thenElse
                      "  and= {b -> false}"+
                      "  or = {b -> b}"+
                      "  thenElse = {then else->(else void) }"+
                      "};"+
                      "forceSubtyping ={b ->(if b true false)};"+ // A unified version
                      // Trying really hard here to unify 'true' and 'false'
                      "bool=@{true=(forceSubtyping 1), false=(forceSubtyping 0), force=forceSubtyping};"+
                      // Apply the unified 'false' to two different return contexts
                      "a=(bool.false.thenElse { x-> 3 } { y-> 4 });"+
                      "b=(bool.false.thenElse { z->@{}} { z->@{}});"+
                      // Look at the results
                      "@{a=a,b=b, bool=bool}"+
                      "");
     if( HM.DO_HM ) {
       /*  An indented version of this answer
         @{
           a = nint8,
           b = (),
           bool = @{
             false =        A:@{ and = { A -> A }, or = { A -> A }, thenElse = { { () -> B } { () -> B } -> B } },
             force = { C -> D:@{ and = { D -> D }, or = { D -> D }, thenElse = { { () -> E } { () -> E } -> E } } },
             true =         F:@{ and = { F -> F }, or = { F -> F }, thenElse = { { () -> G } { () -> G } -> G } }
           }
         }
        */
       assertEquals("@{ a = nint8, b = (), bool = @{ false = A:@{ and = { A -> A }, or = { A -> A }, thenElse = { { () -> B } { () -> B } -> B }}, force = { C? -> D:@{ and = { D -> D }, or = { D -> D }, thenElse = { { () -> E } { () -> E } -> E }} }, true = F:@{ and = { F -> F }, or = { F -> F }, thenElse = { { () -> G } { () -> G } -> G }}}}",syn._hmt.p());
     }
     if( HM.DO_GCP ) {
       Type tf   = TypeMemPtr.make(BitsAlias.FULL.make(10,11),
                                   TypeStruct.make(TypeFld.NO_DISP,
                                                   TypeFld.make("and"     ,TypeFunPtr.make(BitsFun.make0(15,18),1,TypeMemPtr.NO_DISP),1),
                                                   TypeFld.make("or"      ,TypeFunPtr.make(BitsFun.make0(16,19),1,TypeMemPtr.NO_DISP),2),
                                                   TypeFld.make("thenElse",TypeFunPtr.make(BitsFun.make0(17,20),2,TypeMemPtr.NO_DISP),3)));
       Type xbool= TypeMemPtr.make(12,TypeStruct.make(TypeFld.NO_DISP,
                                                      TypeFld.make("true", tf,1),
                                                      TypeFld.make("false",tf,2),
                                                      TypeFld.make("force",TypeFunPtr.make(24,1,TypeMemPtr.NO_DISP),3)));
       TypeStruct rez = TypeStruct.make(TypeFld.NO_DISP,
                                        TypeFld.make("a",HM.DO_HM ? TypeInt.INT64: Type.NSCALR,1),
                                        TypeFld.make("b",HM.DO_HM ? Type.SCALAR  : Type.NSCALR,2),
                                        TypeFld.make("bool",xbool,3));
       assertEquals(TypeMemPtr.make(15,rez),syn.flow_type());
     }
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.type.BitsAlias.FULL, com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.type.TypeInt.INT64, com.cliffc.aa.type.TypeFld.make(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeFunPtr.make(), com.cliffc.aa.type.Bits< B extends Bits< B >.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.BitsFun.make0(), com.cliffc.aa.type.TypeMemPtr.NO_DISP, com.cliffc.aa.type.TypeFld.NO_DISP, com.cliffc.aa.type.Type< T extends Type< T >.NSCALR, com.cliffc.aa.HM.HM.T2.p(), and com.cliffc.aa.type.Type< T extends Type< T >.SCALAR.
test53()
void com.cliffc.aa.HM.TestHM.test53 ()
Definition at line 565 of file TestHM.java.
                              { run( "{ x y -> (if x x y) }",
                                     "{ A? A -> A }", tfs(Type.SCALAR));  }
References com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM.tfs().
test54()
void com.cliffc.aa.HM.TestHM.test54 ()
Definition at line 569 of file TestHM.java.
                              { run( "{ x y -> (if x (if x x y) y) }",
                                     "{ A? A -> A }", tfs(Type.SCALAR));  }
References com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.type.Type< T extends Type< T >.SCALAR, and com.cliffc.aa.HM.TestHM.tfs().
test55()
void com.cliffc.aa.HM.TestHM.test55 ()
Definition at line 573 of file TestHM.java.
{
     Root syn = HM.hm("void = @{};                           "+
                      "true = @{                             "+
                      "  and      = {b -> b}                 "+
                      "  or       = {b -> true}              "+
                      "  not      = {unused ->true}          "+
                      "  thenElse = {then else->(then void) }"+
                      "};                                    "+
                      "false = @{                            "+
                      "  and      = {b -> false}             "+
                      "  or       = {b -> b}                 "+
                      "  not      = {unused ->true}          "+
                      "  thenElse = {then else->(else void) }"+
                      "};                                    "+
                      "boolSub ={b ->(if b true false)};     "+
                      "@{true=(boolSub 1) false=(boolSub 0)} "+
                      "");
     if( HM.DO_HM )
       assertEquals("@{ false = A:@{ and = { A -> A }, "+
                          "not = { B -> A }, "+
                          "or = { A -> A }, "+
                          "thenElse = { { () -> C } { () -> C } -> C }"+
                        "}, "+
                        "true = D:@{ and = { D -> D }, "+
                          "not = { E -> D }, "+
                          "or = { D -> D }, "+
                          "thenElse = { { () -> F } { () -> F } -> F }"+
                        "}"+
                     "}",syn._hmt.p());
     if( HM.DO_GCP ) {
       // true/false=*[10,11]@{$; and=[15,19]{any }; or=[16,20]{any }; not=[17,21]{any }; thenElse=[18,22]{any }}
       Type tf   = TypeMemPtr.make(BitsAlias.FULL.make(10,11),
                                   TypeStruct.make(TypeFld.NO_DISP,
                                                   TypeFld.make("and"     ,TypeFunPtr.make(BitsFun.make0(15,19),1,TypeMemPtr.NO_DISP),1),
                                                   TypeFld.make("or"      ,TypeFunPtr.make(BitsFun.make0(16,20),1,TypeMemPtr.NO_DISP),2),
                                                   TypeFld.make("not"     ,TypeFunPtr.make(BitsFun.make0(17,21),1,TypeMemPtr.NO_DISP),3),
                                                   TypeFld.make("thenElse",TypeFunPtr.make(BitsFun.make0(18,22),2,TypeMemPtr.NO_DISP),4)));
       // *[12]@{^=any; true=$TF; false=$TF}
       TypeStruct rez = TypeStruct.make(TypeFld.NO_DISP,
                                        TypeFld.make("true" ,tf,1),
                                        TypeFld.make("false",tf,2) );
       assertEquals(TypeMemPtr.make(12,rez),syn.flow_type());
     }
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.type.BitsAlias.FULL, com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.type.TypeFld.make(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeFunPtr.make(), com.cliffc.aa.type.Bits< B extends Bits< B >.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.BitsFun.make0(), com.cliffc.aa.type.TypeMemPtr.NO_DISP, com.cliffc.aa.type.TypeFld.NO_DISP, and com.cliffc.aa.HM.HM.T2.p().
test56()
void com.cliffc.aa.HM.TestHM.test56 ()
Definition at line 624 of file TestHM.java.
{
     Root syn = HM.hm("left =     "+
                      "  rite = @{n1 = left v1 = 7 }; "+
                      "  @{ n1 = rite v1 = 7 };"+
                      "left"+
                      "");
     if( HM.DO_HM )
       assertEquals("A:@{ n1 = @{ n1 = A, v1 = 7}, v1 = 7}",syn._hmt.p());
     if( HM.DO_GCP )
       assertEquals(build_cycle2(false,TypeInt.con(7)),syn.flow_type());
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.TestHM.build_cycle2(), com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), and com.cliffc.aa.HM.HM.T2.p().
test57()
void com.cliffc.aa.HM.TestHM.test57 ()
Definition at line 636 of file TestHM.java.
{
     Root syn = HM.hm(
 "all =                                      "+
 "true = @{                                  "+
 "  not = {unused -> all.false},             "+
 "  thenElse = {then else->(then 7) }        "+
 "};                                         "+
 "false = @{                                 "+
 "  not = {unused -> all.true},              "+
 "  thenElse = {then else->(else 7) }        "+
 "};                                         "+
 "boolSub ={b ->(if b true false)};          "+
 "@{true=true, false=false, boolSub=boolSub};"+
 "all"+
 "");
     if( HM.DO_HM )
         assertEquals("@{ boolSub = { A? -> @{ not = { B -> C:@{ not = { D -> C }, thenElse = { { 7 -> E } { 7 -> E } -> E }} }, thenElse = { { 7 -> F } { 7 -> F } -> F }} }, false = C, true = C}",syn._hmt.p());
     if( HM.DO_GCP ) {
       Type tt = TypeMemPtr.make(BitsAlias.FULL.make(9),
                                 TypeStruct.make(TypeFld.NO_DISP,
                                                 TypeFld.make("not"     ,TypeFunPtr.make(BitsFun.make0(15),1,TypeMemPtr.NO_DISP),1),
                                                 TypeFld.make("thenElse",TypeFunPtr.make(BitsFun.make0(16),2,TypeMemPtr.NO_DISP),2)));
       Type ff = TypeMemPtr.make(BitsAlias.FULL.make(10),
                                 TypeStruct.make(TypeFld.NO_DISP,
                                                 TypeFld.make("not"     ,TypeFunPtr.make(BitsFun.make0(17),1,TypeMemPtr.NO_DISP),1),
                                                 TypeFld.make("thenElse",TypeFunPtr.make(BitsFun.make0(18),2,TypeMemPtr.NO_DISP),2)));
       TypeStruct rez = TypeStruct.make(TypeFld.NO_DISP,
                                        TypeFld.make("true"   ,tt,1),
                                        TypeFld.make("false"  ,ff,2),
                                        TypeFld.make("boolSub",TypeFunPtr.make(BitsFun.make0(22),1,TypeMemPtr.NO_DISP),3));
       assertEquals(TypeMemPtr.make(11,rez),syn.flow_type());
     }
   }
References com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.type.BitsAlias.FULL, com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.type.TypeFld.make(), com.cliffc.aa.type.TypeMemPtr.make(), com.cliffc.aa.type.TypeFunPtr.make(), com.cliffc.aa.type.Bits< B extends Bits< B >.make(), com.cliffc.aa.type.TypeStruct.make(), com.cliffc.aa.type.BitsFun.make0(), com.cliffc.aa.type.TypeMemPtr.NO_DISP, com.cliffc.aa.type.TypeFld.NO_DISP, and com.cliffc.aa.HM.HM.T2.p().
tfs()
static TypeFunSig com.cliffc.aa.HM.TestHM.tfs (Type ret) static private
Definition at line 22 of file TestHM.java.
{
     return TypeFunSig.make(TypeTuple.make_ret(ret),TypeTuple.make_args());
   }
References com.cliffc.aa.type.TypeFunSig.make(), com.cliffc.aa.type.TypeTuple.make_args(), and com.cliffc.aa.type.TypeTuple.make_ret().
Referenced by com.cliffc.aa.HM.TestHM.test02(), com.cliffc.aa.HM.TestHM.test03(), com.cliffc.aa.HM.TestHM.test04(), com.cliffc.aa.HM.TestHM.test07(), com.cliffc.aa.HM.TestHM.test10(), com.cliffc.aa.HM.TestHM.test11(), com.cliffc.aa.HM.TestHM.test13(), com.cliffc.aa.HM.TestHM.test17(), com.cliffc.aa.HM.TestHM.test18(), com.cliffc.aa.HM.TestHM.test24(), com.cliffc.aa.HM.TestHM.test29(), com.cliffc.aa.HM.TestHM.test30(), com.cliffc.aa.HM.TestHM.test31(), com.cliffc.aa.HM.TestHM.test32(), com.cliffc.aa.HM.TestHM.test33(), com.cliffc.aa.HM.TestHM.test36(), com.cliffc.aa.HM.TestHM.test37(), com.cliffc.aa.HM.TestHM.test38(), com.cliffc.aa.HM.TestHM.test39(), com.cliffc.aa.HM.TestHM.test40(), com.cliffc.aa.HM.TestHM.test47(), com.cliffc.aa.HM.TestHM.test48(), com.cliffc.aa.HM.TestHM.test49(), com.cliffc.aa.HM.TestHM.test50(), com.cliffc.aa.HM.TestHM.test51(), com.cliffc.aa.HM.TestHM.test53(), and com.cliffc.aa.HM.TestHM.test54().
Member Data Documentation
ret_tuple2
final TypeFunSig com.cliffc.aa.HM.TestHM.ret_tuple2 = tfs(tuple2) static private
Definition at line 32 of file TestHM.java.
Referenced by com.cliffc.aa.HM.TestHM.test09().
tuple2
final TypeMemPtr com.cliffc.aa.HM.TestHM.tuple2 = TypeMemPtr.make(7,make_tups(Type.SCALAR, Type.SCALAR)) static private
Definition at line 28 of file TestHM.java.
Referenced by com.cliffc.aa.HM.TestHM.test03(), com.cliffc.aa.HM.TestHM.test14(), com.cliffc.aa.HM.TestHM.test20(), com.cliffc.aa.HM.TestHM.test24(), and com.cliffc.aa.HM.TestHM.test41().
tuple55
final TypeMemPtr com.cliffc.aa.HM.TestHM.tuple55 = TypeMemPtr.make(7,make_tups(TypeInt.con(5),TypeInt.con(5))) static private
Definition at line 31 of file TestHM.java.
Referenced by com.cliffc.aa.HM.TestHM.test16(), and com.cliffc.aa.HM.TestHM.test17().
tuple82
final TypeMemPtr com.cliffc.aa.HM.TestHM.tuple82 = TypeMemPtr.make(7,make_tups(TypeInt.NINT8, TypeInt.NINT8)) static private
Definition at line 30 of file TestHM.java.
Referenced by com.cliffc.aa.HM.TestHM.test05().
tuple9
final TypeMemPtr com.cliffc.aa.HM.TestHM.tuple9 = TypeMemPtr.make(9,TypeStruct.make(TypeStruct.flds(Type.SCALAR,Type.SCALAR))) static private
Definition at line 33 of file TestHM.java.
Referenced by com.cliffc.aa.HM.TestHM.test29().
tuplen2
final TypeMemPtr com.cliffc.aa.HM.TestHM.tuplen2 = TypeMemPtr.make(7,make_tups(Type.NSCALR, Type.NSCALR)) static private
Definition at line 29 of file TestHM.java.
Referenced by com.cliffc.aa.HM.TestHM.test06().
The documentation for this class was generated from the following file:
TestHM.java