aa: com.cliffc.aa.HM.HM5.Worklist Class Reference
com.cliffc.aa.HM.HM5.Worklist Class Reference
Public Member Functions
void addAll (Ary<? extends Syntax > ss)
boolean has (Syntax s)
int len ()
Syntax pop ()
void push (Syntax s)
String toString ()
Public Attributes
int _cnt
Private Attributes
final Ary< Syntax > _ary = new Ary<>(Syntax.class)
final HashSet< Syntax > _work = new HashSet<>()
Detailed Description
Definition at line 86 of file HM5.java.
Member Function Documentation
addAll()
void com.cliffc.aa.HM.HM5.Worklist.addAll (Ary<? extends Syntax > ss)
Definition at line 95 of file HM5.java.
 { if( ss != null ) for( Syntax s : ss ) push(s); }
References com.cliffc.aa.HM.HM5.Worklist.push().
Referenced by com.cliffc.aa.HM.HM5.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM5.Lambda.add_occurs(), com.cliffc.aa.HM.HM5.Lambda2.add_occurs(), and com.cliffc.aa.HM.HM5.Let.add_occurs().
has()
boolean com.cliffc.aa.HM.HM5.Worklist.has (Syntax s)
Definition at line 94 of file HM5.java.
 { return _work.contains(s); }
References com.cliffc.aa.HM.HM5.Worklist._work.
Referenced by com.cliffc.aa.HM.HM5.Syntax.more_work_impl().
len()
int com.cliffc.aa.HM.HM5.Worklist.len ()
Definition at line 90 of file HM5.java.
 { return _ary.len(); }
References com.cliffc.aa.HM.HM5.Worklist._ary.
Referenced by com.cliffc.aa.HM.HM5.hm().
pop()
Syntax com.cliffc.aa.HM.HM5.Worklist.pop ()
Definition at line 93 of file HM5.java.
 { Syntax s = _ary.del(  _cnt++%_ary._len); _work.remove(s); return s; }
References com.cliffc.aa.HM.HM5.Worklist._ary, com.cliffc.aa.HM.HM5.Worklist._cnt, and com.cliffc.aa.HM.HM5.Worklist._work.
Referenced by com.cliffc.aa.HM.HM5.hm().
push()
void com.cliffc.aa.HM.HM5.Worklist.push (Syntax s)
Definition at line 91 of file HM5.java.
 { if( !_work.contains(s) ) _work.add(_ary.push(s)); }
References com.cliffc.aa.HM.HM5.Worklist._ary, and com.cliffc.aa.HM.HM5.Worklist._work.
Referenced by com.cliffc.aa.HM.HM5.Lambda.add_kids(), com.cliffc.aa.HM.HM5.Lambda2.add_kids(), com.cliffc.aa.HM.HM5.Let.add_kids(), com.cliffc.aa.HM.HM5.Apply.add_kids(), com.cliffc.aa.HM.HM5.Worklist.addAll(), com.cliffc.aa.HM.HM5.hm(), and com.cliffc.aa.HM.HM5.Syntax.prep_tree_impl().
toString()
String com.cliffc.aa.HM.HM5.Worklist.toString ()
Definition at line 96 of file HM5.java.
 { return _ary.toString(); }
References com.cliffc.aa.HM.HM5.Worklist._ary.
Member Data Documentation
_ary
final Ary<Syntax> com.cliffc.aa.HM.HM5.Worklist._ary = new Ary<>(Syntax.class) private
Definition at line 88 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Worklist.len(), com.cliffc.aa.HM.HM5.Worklist.pop(), com.cliffc.aa.HM.HM5.Worklist.push(), and com.cliffc.aa.HM.HM5.Worklist.toString().
_cnt
int com.cliffc.aa.HM.HM5.Worklist._cnt
Definition at line 87 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Worklist.pop().
_work
final HashSet<Syntax> com.cliffc.aa.HM.HM5.Worklist._work = new HashSet<>() private
Definition at line 89 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Worklist.has(), com.cliffc.aa.HM.HM5.Worklist.pop(), and com.cliffc.aa.HM.HM5.Worklist.push().
The documentation for this class was generated from the following file:
HM5.java