aa: com.cliffc.aa.util.IHashMap Class Reference
com.cliffc.aa.util.IHashMap Class Reference
Public Member Functions
void clear ()
boolean isEmpty ()
void remove (Object key)
Package Functions
public< T > T get (T key)
public< T > Set< T > keySet ()
public< T > T put (T k, T v)
public< T > T put (T kv)
Private Attributes
final HashMap _map = new HashMap()
Detailed Description
Definition at line 7 of file IHashMap.java.
Member Function Documentation
clear()
void com.cliffc.aa.util.IHashMap.clear ()
Definition at line 13 of file IHashMap.java.
 { _map.clear(); }
Referenced by com.cliffc.aa.type.TypeStruct.approx(), and com.cliffc.aa.type.TypeStruct.shrink().
get()
public<T> T com.cliffc.aa.util.IHashMap.get (T key) package
Definition at line 11 of file IHashMap.java.
 { return (T)_map.get(key); }
Referenced by com.cliffc.aa.type.TypeStruct.ax_impl_fptr(), com.cliffc.aa.type.TypeStruct.ax_impl_ptr(), com.cliffc.aa.type.TypeStruct.ax_impl_struct(), com.cliffc.aa.type.TypeFlds.check_(), com.cliffc.aa.type.Types.check_(), com.cliffc.aa.type.TypeFlds.hash_cons_(), com.cliffc.aa.type.Types.hash_cons_(), and com.cliffc.aa.type.TypeStruct.shrink().
isEmpty()
boolean com.cliffc.aa.util.IHashMap.isEmpty ()
Definition at line 14 of file IHashMap.java.
 { return _map.isEmpty(); }
Referenced by com.cliffc.aa.type.TypeStruct.approx(), and com.cliffc.aa.type.TypeStruct.shrink().
keySet()
public<T> Set<T> com.cliffc.aa.util.IHashMap.keySet () package
Definition at line 15 of file IHashMap.java.
 { return _map.keySet(); }
put() [1/2]
public<T> T com.cliffc.aa.util.IHashMap.put (T k, T v) package
Definition at line 10 of file IHashMap.java.
 { _map.put(k,v); return v; }
put() [2/2]
public<T> T com.cliffc.aa.util.IHashMap.put (T kv) package
Definition at line 9 of file IHashMap.java.
 { _map.put(kv,kv); return kv; }
Referenced by com.cliffc.aa.type.TypeStruct.ax_impl_fptr(), com.cliffc.aa.type.TypeStruct.ax_impl_ptr(), com.cliffc.aa.type.TypeStruct.ax_impl_struct(), com.cliffc.aa.type.TypeFlds.hash_cons_(), com.cliffc.aa.type.Types.hash_cons_(), com.cliffc.aa.type.TypeStruct.post_mod(), and com.cliffc.aa.type.TypeStruct.shrink().
remove()
void com.cliffc.aa.util.IHashMap.remove (Object key)
Definition at line 12 of file IHashMap.java.
 { _map.remove(key); }
Member Data Documentation
_map
final HashMap com.cliffc.aa.util.IHashMap._map = new HashMap() private
Definition at line 8 of file IHashMap.java.
The documentation for this class was generated from the following file:
IHashMap.java