aa: com.cliffc.aa.util.SB Class Reference
com.cliffc.aa.util.SB Class Reference
Tight/tiny StringBuilder wrapper.
Public Member Functions
SB ()
SB (String s)
SB clear ()
SB di (int i)
SB i ()
SB i (int d)
SB ii (int i)
SB ip (String s)
SB nl ()
SB p (boolean s)
SB p (char s)
SB p (double s)
SB p (float s)
SB p (int s)
SB p (long s)
SB p (String s)
SB p (Type t)
SB pobj (Object s)
SB s ()
String toString ()
SB unchar ()
SB unchar (int x)
Private Attributes
int _indent = 0
final StringBuilder _sb
Detailed Description
Tight/tiny StringBuilder wrapper.
Short short names on purpose; so they don't obscure the printing. Can't believe this wasn't done long long ago.
Definition at line 8 of file SB.java.
Constructor & Destructor Documentation
SB() [1/2]
com.cliffc.aa.util.SB.SB ()
Definition at line 11 of file SB.java.
 { _sb = new StringBuilder( ); }
References com.cliffc.aa.util.SB._sb.
SB() [2/2]
com.cliffc.aa.util.SB.SB (String s)
Definition at line 12 of file SB.java.
 { _sb = new StringBuilder(s); }
References com.cliffc.aa.util.SB._sb, and com.cliffc.aa.util.SB.s().
Member Function Documentation
clear()
SB com.cliffc.aa.util.SB.clear ()
Definition at line 61 of file SB.java.
 { _sb.setLength(0); return this; }
References com.cliffc.aa.util.SB._sb.
Referenced by com.cliffc.aa.HM.HM6.id(), com.cliffc.aa.HM.HM8.id(), com.cliffc.aa.HM.HM7.id(), com.cliffc.aa.HM.HM9.id(), com.cliffc.aa.HM.HM.id(), and com.cliffc.aa.node.Node.ErrMsg.typerr().
di()
SB com.cliffc.aa.util.SB.di (int i)
Definition at line 46 of file SB.java.
 { _indent -= i; return this; }
References com.cliffc.aa.util.SB._indent, and com.cliffc.aa.util.SB.i().
Referenced by com.cliffc.aa.HM.HM4.Syntax.p0(), com.cliffc.aa.HM.HM5.Syntax.p0(), com.cliffc.aa.HM.HM6.Syntax.p0(), com.cliffc.aa.HM.HM7.Syntax.p0(), com.cliffc.aa.HM.HM8.Syntax.p0(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM.Syntax.p0(), and com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.toString().
i() [1/2]
SB com.cliffc.aa.util.SB.i ()
Definition at line 39 of file SB.java.
 { return i(0); }
References com.cliffc.aa.util.SB.i().
Referenced by com.cliffc.aa.util.SB.di(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), and com.cliffc.aa.util.SB.ip().
i() [2/2]
SB com.cliffc.aa.util.SB.i (int d)
Definition at line 38 of file SB.java.
 { for( int i=0; i<d+_indent; i++ ) p("  "); return this; }
References com.cliffc.aa.util.SB._indent, com.cliffc.aa.util.SB.i(), and com.cliffc.aa.util.SB.p().
Referenced by com.cliffc.aa.node.Node.dump(), com.cliffc.aa.HM.HM4.Syntax.p0(), com.cliffc.aa.HM.HM5.Syntax.p0(), com.cliffc.aa.HM.HM6.Syntax.p0(), com.cliffc.aa.HM.HM7.Syntax.p0(), com.cliffc.aa.HM.HM8.Syntax.p0(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.HM.HM9.Lambda.p1(), com.cliffc.aa.HM.HM.Lambda.p1(), com.cliffc.aa.HM.HM9.Struct.p2(), com.cliffc.aa.HM.HM.Struct.p2(), and com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.toString().
ii()
SB com.cliffc.aa.util.SB.ii (int i)
Definition at line 44 of file SB.java.
 { _indent += i; return this; }
References com.cliffc.aa.util.SB._indent, and com.cliffc.aa.util.SB.i().
Referenced by com.cliffc.aa.HM.HM4.Syntax.p0(), com.cliffc.aa.HM.HM5.Syntax.p0(), com.cliffc.aa.HM.HM6.Syntax.p0(), com.cliffc.aa.HM.HM7.Syntax.p0(), com.cliffc.aa.HM.HM8.Syntax.p0(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM.Syntax.p0(), and com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.toString().
ip()
SB com.cliffc.aa.util.SB.ip (String s)
Definition at line 40 of file SB.java.
 { return i().p(s); }
References com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.p(), and com.cliffc.aa.util.SB.s().
nl()
SB com.cliffc.aa.util.SB.nl ()
Definition at line 48 of file SB.java.
 { return p(System.lineSeparator()); }
References com.cliffc.aa.util.SB.p().
Referenced by com.cliffc.aa.node.Node._header(), com.cliffc.aa.node.Node.dumprpo(), com.cliffc.aa.Parse.errLocMsg(), com.cliffc.aa.HM.HM4.Syntax.p0(), com.cliffc.aa.HM.HM5.Syntax.p0(), com.cliffc.aa.HM.HM6.Syntax.p0(), com.cliffc.aa.HM.HM7.Syntax.p0(), com.cliffc.aa.HM.HM8.Syntax.p0(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.HM.HM9.Lambda.p1(), com.cliffc.aa.HM.HM.Lambda.p1(), com.cliffc.aa.HM.HM9.Struct.p2(), com.cliffc.aa.HM.HM.Struct.p2(), com.cliffc.aa.TestParse.testary(), com.cliffc.aa.TestREPL.testerr(), com.cliffc.aa.TestParse.testerr(), and com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.toString().
p() [1/8]
SB com.cliffc.aa.util.SB.p (boolean s)
Definition at line 34 of file SB.java.
 { _sb.append(s); return this; }
References com.cliffc.aa.util.SB._sb, and com.cliffc.aa.util.SB.s().
p() [2/8]
SB com.cliffc.aa.util.SB.p (char s)
Definition at line 31 of file SB.java.
 { _sb.append(s); return this; }
References com.cliffc.aa.util.SB._sb, and com.cliffc.aa.util.SB.s().
p() [3/8]
SB com.cliffc.aa.util.SB.p (double s)
Definition at line 23 of file SB.java.
{
     if( Double.isNaN(s) )
       _sb.append("Double.NaN");
     else if( Double.isInfinite(s) ) {
       _sb.append(s > 0 ? "Double.POSITIVE_INFINITY" : "Double.NEGATIVE_INFINITY");
     } else _sb.append(s);
     return this;
   }
References com.cliffc.aa.util.SB._sb, and com.cliffc.aa.util.SB.s().
p() [4/8]
SB com.cliffc.aa.util.SB.p (float s)
Definition at line 15 of file SB.java.
{
     if( Float.isNaN(s) )
       _sb.append( "Float.NaN");
     else if( Float.isInfinite(s) ) {
       _sb.append(s > 0 ? "Float.POSITIVE_INFINITY" : "Float.NEGATIVE_INFINITY");
     } else _sb.append(s);
     return this;
   }
References com.cliffc.aa.util.SB._sb, and com.cliffc.aa.util.SB.s().
p() [5/8]
SB com.cliffc.aa.util.SB.p (int s)
Definition at line 32 of file SB.java.
 { _sb.append(s); return this; }
References com.cliffc.aa.util.SB._sb, and com.cliffc.aa.util.SB.s().
p() [6/8]
SB com.cliffc.aa.util.SB.p (long s)
Definition at line 33 of file SB.java.
 { _sb.append(s); return this; }
References com.cliffc.aa.util.SB._sb, and com.cliffc.aa.util.SB.s().
p() [7/8]
SB com.cliffc.aa.util.SB.p (String s)
Definition at line 13 of file SB.java.
 { _sb.append(s); return this; }
References com.cliffc.aa.util.SB._sb, and com.cliffc.aa.util.SB.s().
Referenced by com.cliffc.aa.node.Node._header(), com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM5.T2._p(), com.cliffc.aa.HM.HM6.T2._p(), com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM9.T2._p(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM1.HMVar._str(), com.cliffc.aa.HM.HM1.Oper._str(), com.cliffc.aa.HM.HM2.Oper._str(), com.cliffc.aa.HM.HM3.HMVar._str(), com.cliffc.aa.HM.HM3.Oper._str(), com.cliffc.aa.node.Node.dump(), com.cliffc.aa.Parse.errLocMsg(), com.cliffc.aa.node.Node.ErrMsg.field(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.HM.HM6.id(), com.cliffc.aa.HM.HM8.id(), com.cliffc.aa.HM.HM7.id(), com.cliffc.aa.HM.HM9.id(), com.cliffc.aa.HM.HM.id(), com.cliffc.aa.util.SB.ip(), com.cliffc.aa.node.FunNode.names(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.HM.HM4.Syntax.p0(), com.cliffc.aa.HM.HM5.Syntax.p0(), com.cliffc.aa.HM.HM6.Syntax.p0(), com.cliffc.aa.HM.HM7.Syntax.p0(), com.cliffc.aa.HM.HM8.Syntax.p0(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.HM.HM4.Con.p1(), com.cliffc.aa.HM.HM4.Ident.p1(), com.cliffc.aa.HM.HM4.Lambda.p1(), com.cliffc.aa.HM.HM5.Con.p1(), com.cliffc.aa.HM.HM5.Ident.p1(), com.cliffc.aa.HM.HM4.Lambda2.p1(), com.cliffc.aa.HM.HM5.Lambda.p1(), com.cliffc.aa.HM.HM4.Let.p1(), com.cliffc.aa.HM.HM6.Con.p1(), com.cliffc.aa.HM.HM5.Lambda2.p1(), com.cliffc.aa.HM.HM6.Ident.p1(), com.cliffc.aa.HM.HM4.Apply.p1(), com.cliffc.aa.HM.HM7.Con.p1(), com.cliffc.aa.HM.HM8.Con.p1(), com.cliffc.aa.HM.HM7.Ident.p1(), com.cliffc.aa.HM.HM5.Let.p1(), com.cliffc.aa.HM.HM6.Lambda.p1(), com.cliffc.aa.HM.HM8.Ident.p1(), com.cliffc.aa.HM.HM5.Apply.p1(), com.cliffc.aa.HM.HM6.Lambda2.p1(), com.cliffc.aa.HM.HM7.Lambda.p1(), com.cliffc.aa.HM.HM8.Lambda.p1(), com.cliffc.aa.HM.HM9.Con.p1(), com.cliffc.aa.HM.HM6.Let.p1(), com.cliffc.aa.HM.HM7.Let.p1(), com.cliffc.aa.HM.HM.Con.p1(), com.cliffc.aa.HM.HM9.Ident.p1(), com.cliffc.aa.HM.HM.Ident.p1(), com.cliffc.aa.HM.HM8.Let.p1(), com.cliffc.aa.HM.HM6.Apply.p1(), com.cliffc.aa.HM.HM7.Apply.p1(), com.cliffc.aa.HM.HM9.Lambda.p1(), com.cliffc.aa.HM.HM8.Apply.p1(), com.cliffc.aa.HM.HM.Lambda.p1(), com.cliffc.aa.HM.HM7.Struct.p1(), com.cliffc.aa.HM.HM9.Let.p1(), com.cliffc.aa.HM.HM.Let.p1(), com.cliffc.aa.HM.HM7.Field.p1(), com.cliffc.aa.HM.HM8.Struct.p1(), com.cliffc.aa.HM.HM9.Apply.p1(), com.cliffc.aa.HM.HM.Apply.p1(), com.cliffc.aa.HM.HM8.Field.p1(), com.cliffc.aa.HM.HM9.Struct.p1(), com.cliffc.aa.HM.HM.Struct.p1(), com.cliffc.aa.HM.HM9.Field.p1(), com.cliffc.aa.HM.HM.Field.p1(), com.cliffc.aa.HM.HM9.PrimSyn.p1(), com.cliffc.aa.HM.HM.PrimSyn.p1(), com.cliffc.aa.HM.HM7.Struct.p2(), com.cliffc.aa.HM.HM8.Struct.p2(), com.cliffc.aa.HM.HM9.Struct.p2(), com.cliffc.aa.HM.HM.Struct.p2(), com.cliffc.aa.type.TypeRPC.str(), com.cliffc.aa.type.TypeFlt.str(), com.cliffc.aa.type.TypeInt.str(), com.cliffc.aa.type.TypeAry.str(), com.cliffc.aa.type.TypeStr.str(), com.cliffc.aa.node.MemSplitNode.str(), com.cliffc.aa.type.TypeLive.str(), com.cliffc.aa.type.TypeObj< TypeStruct >.str(), com.cliffc.aa.type.TypeFld.str(), com.cliffc.aa.type.TypeFunSig.str(), com.cliffc.aa.type.TypeMemPtr.str(), com.cliffc.aa.type.TypeFunPtr.str(), com.cliffc.aa.type.TypeTuple.str(), com.cliffc.aa.HM.HM3.VStack.str(), com.cliffc.aa.HM.HM5.VStack.str(), com.cliffc.aa.type.TypeMem.str(), com.cliffc.aa.type.Type< TypeFlt >.str(), com.cliffc.aa.type.TypeFld.Access.str(), com.cliffc.aa.type.Bits< BitsRPC >.str(), com.cliffc.aa.type.TypeStruct.str(), com.cliffc.aa.HM.HM4.Lambda.str(), com.cliffc.aa.HM.HM4.Lambda2.str(), com.cliffc.aa.HM.HM6.VStack.str(), com.cliffc.aa.HM.HM5.Lambda.str(), com.cliffc.aa.HM.HM8.VStack.str(), com.cliffc.aa.HM.HM7.VStack.str(), com.cliffc.aa.HM.HM4.Let.str(), com.cliffc.aa.HM.HM5.Lambda2.str(), com.cliffc.aa.HM.HM4.Apply.str(), com.cliffc.aa.HM.HM9.VStack.str(), com.cliffc.aa.HM.HM5.Let.str(), com.cliffc.aa.HM.HM6.Lambda.str(), com.cliffc.aa.HM.HM.VStack.str(), com.cliffc.aa.HM.HM5.Apply.str(), com.cliffc.aa.HM.HM7.Lambda.str(), com.cliffc.aa.HM.HM6.Lambda2.str(), com.cliffc.aa.HM.HM8.Lambda.str(), com.cliffc.aa.HM.HM6.Let.str(), com.cliffc.aa.HM.HM7.Let.str(), com.cliffc.aa.HM.HM6.Apply.str(), com.cliffc.aa.HM.HM8.Let.str(), com.cliffc.aa.HM.HM7.Apply.str(), com.cliffc.aa.HM.HM8.Apply.str(), com.cliffc.aa.HM.HM9.Lambda.str(), com.cliffc.aa.HM.HM.Lambda.str(), com.cliffc.aa.HM.HM7.Struct.str(), com.cliffc.aa.HM.HM9.Let.str(), com.cliffc.aa.HM.HM.Let.str(), com.cliffc.aa.HM.HM8.Struct.str(), com.cliffc.aa.HM.HM9.Apply.str(), com.cliffc.aa.HM.HM7.Field.str(), com.cliffc.aa.HM.HM.Apply.str(), com.cliffc.aa.HM.HM4.T2.str(), com.cliffc.aa.HM.HM8.Field.str(), com.cliffc.aa.HM.HM5.T2.str(), com.cliffc.aa.HM.HM9.Struct.str(), com.cliffc.aa.HM.HM.Struct.str(), com.cliffc.aa.HM.HM6.T2.str(), com.cliffc.aa.HM.HM9.Field.str(), com.cliffc.aa.HM.HM.Field.str(), com.cliffc.aa.HM.HM9.PrimSyn.str(), com.cliffc.aa.HM.HM.PrimSyn.str(), com.cliffc.aa.HM.HM7.T2.str(), com.cliffc.aa.HM.HM8.T2.str(), com.cliffc.aa.HM.HM9.T2.str(), com.cliffc.aa.HM.HM.T2.str(), com.cliffc.aa.TestParse.testary(), com.cliffc.aa.TestREPL.testerr(), com.cliffc.aa.TestParse.testerr(), com.cliffc.aa.AbstractBuildVersion.toString(), com.cliffc.aa.util.IBitSet.toString(), com.cliffc.aa.TestLattice.N.toString(), com.cliffc.aa.util.AryInt.toString(), com.cliffc.aa.Env.VStack.toString(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.toString(), com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.toString(), and com.cliffc.aa.node.Node.ErrMsg.typerr().
p() [8/8]
SB com.cliffc.aa.util.SB.p (Type t)
Definition at line 14 of file SB.java.
 { _sb.append(t.toString()); return this; }
References com.cliffc.aa.util.SB._sb, and com.cliffc.aa.type.Type< T extends Type< T >.toString().
pobj()
SB com.cliffc.aa.util.SB.pobj (Object s)
Definition at line 37 of file SB.java.
 { _sb.append(s.toString()); return this; }
References com.cliffc.aa.util.SB._sb, com.cliffc.aa.util.SB.s(), and com.cliffc.aa.util.SB.toString().
s()
SB com.cliffc.aa.util.SB.s ()
Definition at line 41 of file SB.java.
 { _sb.append(' '); return this; }
References com.cliffc.aa.util.SB._sb.
Referenced by com.cliffc.aa.node.Node.dump(), com.cliffc.aa.util.SB.ip(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.util.SB.pobj(), and com.cliffc.aa.util.SB.SB().
toString()
String com.cliffc.aa.util.SB.toString ()
Definition at line 62 of file SB.java.
 { return _sb.toString(); }
References com.cliffc.aa.util.SB._sb.
Referenced by com.cliffc.aa.HM.HM2.Oper._str(), com.cliffc.aa.node.Node.dumprpo(), com.cliffc.aa.Parse.errLocMsg(), com.cliffc.aa.node.Node.ErrMsg.field(), com.cliffc.aa.REPL.go_one(), com.cliffc.aa.HM.HM6.id(), com.cliffc.aa.HM.HM8.id(), com.cliffc.aa.HM.HM7.id(), com.cliffc.aa.HM.HM9.id(), com.cliffc.aa.HM.HM.id(), com.cliffc.aa.type.TypeFunPtr.names(), com.cliffc.aa.HM.HM4.Syntax.p(), com.cliffc.aa.HM.HM5.Syntax.p(), com.cliffc.aa.HM.HM6.Syntax.p(), com.cliffc.aa.HM.HM7.Syntax.p(), com.cliffc.aa.HM.HM8.Syntax.p(), com.cliffc.aa.HM.HM9.Syntax.p(), com.cliffc.aa.HM.HM.Syntax.p(), com.cliffc.aa.HM.HM4.T2.p(), com.cliffc.aa.HM.HM5.T2.p(), com.cliffc.aa.HM.HM6.T2.p(), com.cliffc.aa.HM.HM7.T2.p(), com.cliffc.aa.HM.HM8.T2.p(), com.cliffc.aa.HM.HM9.T2.p(), com.cliffc.aa.HM.HM.T2.p(), com.cliffc.aa.util.SB.pobj(), com.cliffc.aa.node.MemSplitNode.str(), com.cliffc.aa.node.FunNode.str(), com.cliffc.aa.HM.HM1.HMType.str(), com.cliffc.aa.HM.HM3.HMType.str(), com.cliffc.aa.TestParse.test_ptr(), com.cliffc.aa.TestParse.testary(), com.cliffc.aa.TestREPL.testerr(), com.cliffc.aa.TestParse.testerr(), com.cliffc.aa.AbstractBuildVersion.toString(), com.cliffc.aa.HM.HM3.VStack.toString(), com.cliffc.aa.HM.HM5.VStack.toString(), com.cliffc.aa.HM.HM4.Syntax.toString(), com.cliffc.aa.TestLattice.N.toString(), com.cliffc.aa.type.Type< TypeFlt >.toString(), com.cliffc.aa.type.Bits< BitsRPC >.toString(), com.cliffc.aa.util.AryInt.toString(), com.cliffc.aa.HM.HM5.Syntax.toString(), com.cliffc.aa.HM.HM1.HMType.toString(), com.cliffc.aa.HM.HM6.VStack.toString(), com.cliffc.aa.HM.HM8.VStack.toString(), com.cliffc.aa.HM.HM7.VStack.toString(), com.cliffc.aa.HM.HM6.Syntax.toString(), com.cliffc.aa.HM.HM7.Syntax.toString(), com.cliffc.aa.Env.VStack.toString(), com.cliffc.aa.HM.HM3.HMType.toString(), com.cliffc.aa.HM.HM8.Syntax.toString(), com.cliffc.aa.HM.HM9.VStack.toString(), com.cliffc.aa.util.Ary< com.cliffc.aa.HM.HM3.Ident >.toString(), com.cliffc.aa.HM.HM.VStack.toString(), com.cliffc.aa.HM.HM9.Syntax.toString(), com.cliffc.aa.HM.HM.Syntax.toString(), com.cliffc.aa.HM.HM4.T2.toString(), com.cliffc.aa.HM.HM5.T2.toString(), com.cliffc.aa.HM.HM6.T2.toString(), com.cliffc.aa.HM.HM7.T2.toString(), com.cliffc.aa.HM.HM8.T2.toString(), com.cliffc.aa.HM.HM9.T2.toString(), com.cliffc.aa.HM.HM.T2.toString(), and com.cliffc.aa.node.Node.ErrMsg.typerr().
unchar() [1/2]
SB com.cliffc.aa.util.SB.unchar ()
Definition at line 58 of file SB.java.
 { return unchar(1); }
References com.cliffc.aa.util.SB.unchar().
Referenced by com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM5.T2._p(), com.cliffc.aa.HM.HM6.T2._p(), com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM9.T2._p(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.HM.HM1.Oper._str(), com.cliffc.aa.HM.HM2.Oper._str(), com.cliffc.aa.HM.HM3.Oper._str(), com.cliffc.aa.node.FunNode.names(), com.cliffc.aa.node.MemSplitNode.str(), com.cliffc.aa.type.TypeFunSig.str(), com.cliffc.aa.type.TypeMem.str(), com.cliffc.aa.type.Bits< BitsRPC >.str(), com.cliffc.aa.type.TypeStruct.str(), com.cliffc.aa.HM.HM4.Apply.str(), com.cliffc.aa.HM.HM5.Apply.str(), com.cliffc.aa.HM.HM6.Apply.str(), com.cliffc.aa.HM.HM7.Apply.str(), com.cliffc.aa.HM.HM8.Apply.str(), com.cliffc.aa.HM.HM9.Apply.str(), com.cliffc.aa.HM.HM.Apply.str(), com.cliffc.aa.HM.HM4.T2.str(), com.cliffc.aa.HM.HM5.T2.str(), com.cliffc.aa.HM.HM6.T2.str(), com.cliffc.aa.HM.HM7.T2.str(), com.cliffc.aa.HM.HM8.T2.str(), com.cliffc.aa.HM.HM9.T2.str(), com.cliffc.aa.HM.HM.T2.str(), com.cliffc.aa.util.IBitSet.toString(), com.cliffc.aa.util.AryInt.toString(), com.cliffc.aa.Env.VStack.toString(), com.cliffc.aa.node.Node.ErrMsg.typerr(), and com.cliffc.aa.util.SB.unchar().
unchar() [2/2]
SB com.cliffc.aa.util.SB.unchar (int x)
Definition at line 59 of file SB.java.
 { _sb.setLength(_sb.length()-x); return this; }
References com.cliffc.aa.util.SB._sb.
Member Data Documentation
_indent
int com.cliffc.aa.util.SB._indent = 0 private
Definition at line 10 of file SB.java.
Referenced by com.cliffc.aa.util.SB.di(), com.cliffc.aa.util.SB.i(), and com.cliffc.aa.util.SB.ii().
_sb
final StringBuilder com.cliffc.aa.util.SB._sb private
Definition at line 9 of file SB.java.
Referenced by com.cliffc.aa.util.SB.clear(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.util.SB.pobj(), com.cliffc.aa.util.SB.s(), com.cliffc.aa.util.SB.SB(), com.cliffc.aa.util.SB.toString(), and com.cliffc.aa.util.SB.unchar().
The documentation for this class was generated from the following file:
SB.java