aa: com.cliffc.aa.HM.HM5.Syntax Class Reference
com.cliffc.aa.HM.HM5.Syntax Class Reference abstract
Public Member Functions
String p ()
final String toString ()
Package Functions
abstract void add_kids (Worklist work)
void add_occurs (Worklist work)
T2 debug_find ()
T2 find ()
abstract boolean hm (Worklist work)
abstract T2 lookup (String name)
abstract boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
abstract SB p1 (SB sb)
abstract SB p2 (SB sb, VBitSet dups)
abstract void prep_lookup_deps (Ident id)
abstract int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
abstract SB str (SB sb)
Package Attributes
VStack _nongen
Syntax _par
T2 _t
Detailed Description
Definition at line 119 of file HM5.java.
Member Function Documentation
add_kids()
abstract void com.cliffc.aa.HM.HM5.Syntax.add_kids (Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM5.Apply, com.cliffc.aa.HM.HM5.Let, com.cliffc.aa.HM.HM5.Lambda2, com.cliffc.aa.HM.HM5.Lambda, com.cliffc.aa.HM.HM5.Ident, and com.cliffc.aa.HM.HM5.Con.
Referenced by com.cliffc.aa.HM.HM5.hm().
add_occurs()
void com.cliffc.aa.HM.HM5.Syntax.add_occurs (Worklist work) package
Reimplemented in com.cliffc.aa.HM.HM5.Let, com.cliffc.aa.HM.HM5.Lambda2, com.cliffc.aa.HM.HM5.Lambda, and com.cliffc.aa.HM.HM5.Ident.
Definition at line 143 of file HM5.java.
 {}
Referenced by com.cliffc.aa.HM.HM5.hm().
debug_find()
T2 com.cliffc.aa.HM.HM5.Syntax.debug_find () package
Definition at line 127 of file HM5.java.
 { return _t.find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM5.Syntax._t, and com.cliffc.aa.HM.HM5.T2.find().
Referenced by com.cliffc.aa.HM.HM5.hm().
find()
T2 com.cliffc.aa.HM.HM5.Syntax.find () package
Definition at line 123 of file HM5.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM5.Syntax._t, and com.cliffc.aa.HM.HM5.T2.find().
Referenced by com.cliffc.aa.HM.HM5.T2._occurs_in(), com.cliffc.aa.HM.HM5.Lambda.add_occurs(), com.cliffc.aa.HM.HM5.Lambda2.add_occurs(), com.cliffc.aa.HM.HM5.Let.add_occurs(), com.cliffc.aa.HM.HM5.Con.hm(), com.cliffc.aa.HM.HM5.Ident.hm(), com.cliffc.aa.HM.HM5.Lambda.hm(), com.cliffc.aa.HM.HM5.Lambda2.hm(), com.cliffc.aa.HM.HM5.Let.hm(), and com.cliffc.aa.HM.HM5.Apply.hm().
hm()
abstract boolean com.cliffc.aa.HM.HM5.Syntax.hm (Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM5.Apply, com.cliffc.aa.HM.HM5.Let, com.cliffc.aa.HM.HM5.Lambda2, com.cliffc.aa.HM.HM5.Lambda, com.cliffc.aa.HM.HM5.Ident, and com.cliffc.aa.HM.HM5.Con.
Referenced by com.cliffc.aa.HM.HM5.hm(), and com.cliffc.aa.HM.HM5.Syntax.more_work_impl().
lookup()
abstract T2 com.cliffc.aa.HM.HM5.Syntax.lookup (String name) abstract package
Reimplemented in com.cliffc.aa.HM.HM5.Apply, com.cliffc.aa.HM.HM5.Let, com.cliffc.aa.HM.HM5.Lambda2, com.cliffc.aa.HM.HM5.Lambda, com.cliffc.aa.HM.HM5.Ident, and com.cliffc.aa.HM.HM5.Con.
Referenced by com.cliffc.aa.HM.HM5.Ident.add_occurs(), com.cliffc.aa.HM.HM5.Ident.hm(), com.cliffc.aa.HM.HM5.Lambda.lookup(), com.cliffc.aa.HM.HM5.Lambda2.lookup(), com.cliffc.aa.HM.HM5.Let.lookup(), and com.cliffc.aa.HM.HM5.Apply.lookup().
more_work()
abstract boolean com.cliffc.aa.HM.HM5.Syntax.more_work (Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM5.Apply, com.cliffc.aa.HM.HM5.Let, com.cliffc.aa.HM.HM5.Lambda2, com.cliffc.aa.HM.HM5.Lambda, com.cliffc.aa.HM.HM5.Ident, and com.cliffc.aa.HM.HM5.Con.
Referenced by com.cliffc.aa.HM.HM5.hm(), com.cliffc.aa.HM.HM5.Lambda.more_work(), com.cliffc.aa.HM.HM5.Lambda2.more_work(), com.cliffc.aa.HM.HM5.Let.more_work(), and com.cliffc.aa.HM.HM5.Apply.more_work().
more_work_impl()
final boolean com.cliffc.aa.HM.HM5.Syntax.more_work_impl (Worklist work) package
Definition at line 147 of file HM5.java.
{
       return work.has(this) || !hm(null); // Either on worklist, or no-progress
     }
References com.cliffc.aa.HM.HM5.Worklist.has(), and com.cliffc.aa.HM.HM5.Syntax.hm().
Referenced by com.cliffc.aa.HM.HM5.Con.more_work(), com.cliffc.aa.HM.HM5.Ident.more_work(), com.cliffc.aa.HM.HM5.Lambda.more_work(), com.cliffc.aa.HM.HM5.Lambda2.more_work(), com.cliffc.aa.HM.HM5.Let.more_work(), and com.cliffc.aa.HM.HM5.Apply.more_work().
p()
String com.cliffc.aa.HM.HM5.Syntax.p ()
Definition at line 154 of file HM5.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM5.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM5.Syntax.p0 (SB sb, VBitSet dups) package
Definition at line 155 of file HM5.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM5.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM5.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM5.Syntax.p1(), com.cliffc.aa.HM.HM5.Syntax.p2(), and com.cliffc.aa.HM.HM5.T2.str().
Referenced by com.cliffc.aa.HM.HM5.Syntax.p(), com.cliffc.aa.HM.HM5.Lambda.p2(), com.cliffc.aa.HM.HM5.Lambda2.p2(), com.cliffc.aa.HM.HM5.Let.p2(), and com.cliffc.aa.HM.HM5.Apply.p2().
p1()
abstract SB com.cliffc.aa.HM.HM5.Syntax.p1 (SB sb) abstract package
Reimplemented in com.cliffc.aa.HM.HM5.Apply, com.cliffc.aa.HM.HM5.Let, com.cliffc.aa.HM.HM5.Lambda2, com.cliffc.aa.HM.HM5.Lambda, com.cliffc.aa.HM.HM5.Ident, and com.cliffc.aa.HM.HM5.Con.
Referenced by com.cliffc.aa.HM.HM5.Syntax.p0().
p2()
abstract SB com.cliffc.aa.HM.HM5.Syntax.p2 (SB sb, VBitSet dups) abstract package
Reimplemented in com.cliffc.aa.HM.HM5.Apply, com.cliffc.aa.HM.HM5.Let, com.cliffc.aa.HM.HM5.Lambda2, com.cliffc.aa.HM.HM5.Lambda, com.cliffc.aa.HM.HM5.Ident, and com.cliffc.aa.HM.HM5.Con.
Referenced by com.cliffc.aa.HM.HM5.Syntax.p0().
prep_lookup_deps()
abstract void com.cliffc.aa.HM.HM5.Syntax.prep_lookup_deps (Ident id) abstract package
Reimplemented in com.cliffc.aa.HM.HM5.Apply, com.cliffc.aa.HM.HM5.Let, com.cliffc.aa.HM.HM5.Lambda2, com.cliffc.aa.HM.HM5.Lambda, com.cliffc.aa.HM.HM5.Ident, and com.cliffc.aa.HM.HM5.Con.
prep_tree()
abstract int com.cliffc.aa.HM.HM5.Syntax.prep_tree (Syntax par, VStack nongen, Worklist work) abstract package
Reimplemented in com.cliffc.aa.HM.HM5.Apply, com.cliffc.aa.HM.HM5.Let, com.cliffc.aa.HM.HM5.Lambda2, com.cliffc.aa.HM.HM5.Lambda, com.cliffc.aa.HM.HM5.Ident, and com.cliffc.aa.HM.HM5.Con.
Referenced by com.cliffc.aa.HM.HM5.hm(), com.cliffc.aa.HM.HM5.Lambda.prep_tree(), com.cliffc.aa.HM.HM5.Lambda2.prep_tree(), com.cliffc.aa.HM.HM5.Let.prep_tree(), and com.cliffc.aa.HM.HM5.Apply.prep_tree().
prep_tree_impl()
final void com.cliffc.aa.HM.HM5.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package
Definition at line 137 of file HM5.java.
 { _par=par; _t=t; _nongen = nongen; work.push(this); }
References com.cliffc.aa.HM.HM5.Syntax._nongen, com.cliffc.aa.HM.HM5.Syntax._par, com.cliffc.aa.HM.HM5.Syntax._t, and com.cliffc.aa.HM.HM5.Worklist.push().
Referenced by com.cliffc.aa.HM.HM5.Con.prep_tree(), com.cliffc.aa.HM.HM5.Ident.prep_tree(), com.cliffc.aa.HM.HM5.Lambda.prep_tree(), com.cliffc.aa.HM.HM5.Lambda2.prep_tree(), com.cliffc.aa.HM.HM5.Let.prep_tree(), and com.cliffc.aa.HM.HM5.Apply.prep_tree().
str()
abstract SB com.cliffc.aa.HM.HM5.Syntax.str (SB sb) abstract package
Reimplemented in com.cliffc.aa.HM.HM5.Apply, com.cliffc.aa.HM.HM5.Let, com.cliffc.aa.HM.HM5.Lambda2, com.cliffc.aa.HM.HM5.Lambda, com.cliffc.aa.HM.HM5.Ident, and com.cliffc.aa.HM.HM5.Con.
Referenced by com.cliffc.aa.HM.HM5.Lambda.str(), com.cliffc.aa.HM.HM5.Lambda2.str(), com.cliffc.aa.HM.HM5.Let.str(), com.cliffc.aa.HM.HM5.Apply.str(), and com.cliffc.aa.HM.HM5.Syntax.toString().
toString()
final String com.cliffc.aa.HM.HM5.Syntax.toString ()
Definition at line 151 of file HM5.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM5.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_nongen
VStack com.cliffc.aa.HM.HM5.Syntax._nongen package
Definition at line 121 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Ident.hm(), and com.cliffc.aa.HM.HM5.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM5.Syntax._par package
Definition at line 120 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.T2._occurs_in(), com.cliffc.aa.HM.HM5.Ident.add_occurs(), com.cliffc.aa.HM.HM5.hm(), com.cliffc.aa.HM.HM5.Ident.hm(), com.cliffc.aa.HM.HM5.Lambda.lookup(), com.cliffc.aa.HM.HM5.Lambda2.lookup(), com.cliffc.aa.HM.HM5.Let.lookup(), com.cliffc.aa.HM.HM5.Apply.lookup(), com.cliffc.aa.HM.HM5.Ident.prep_tree(), and com.cliffc.aa.HM.HM5.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM5.Syntax._t package
Definition at line 122 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Syntax.debug_find(), com.cliffc.aa.HM.HM5.Syntax.find(), com.cliffc.aa.HM.HM5.hm(), com.cliffc.aa.HM.HM5.Syntax.p0(), com.cliffc.aa.HM.HM5.Let.prep_tree(), and com.cliffc.aa.HM.HM5.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM5.java