aa: com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE Class Reference
com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE Class Reference
Public Member Functions
SnapshotE ()
boolean hasNext ()
Map.Entry< Long, TypeV > next ()
void remove ()
Package Attributes
final SnapshotV _ss
Detailed Description
Definition at line 1200 of file NonBlockingHashMapLong.java.
Constructor & Destructor Documentation
SnapshotE()
com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE.SnapshotE ()
Definition at line 1202 of file NonBlockingHashMapLong.java.
 { _ss = new SnapshotV(); }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE._ss.
Member Function Documentation
hasNext()
boolean com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE.hasNext ()
Definition at line 1210 of file NonBlockingHashMapLong.java.
 { return _ss.hasNext(); }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE._ss, and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.hasNext().
next()
Map.Entry<Long,TypeV> com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE.next ()
Definition at line 1209 of file NonBlockingHashMapLong.java.
 { _ss.next(); return new NBHMLEntry(_ss._prevK,_ss._prevV); }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._prevK, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV._prevV, com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE._ss, and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.next().
remove()
void com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE.remove ()
Definition at line 1203 of file NonBlockingHashMapLong.java.
{
       // NOTE: it would seem logical that entry removal will semantically mean
       // removing the matching pair <k,v>, but the JDK always removes by key,
       // even when the value has changed.
       _ss.removeKey();
     }
References com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE._ss, and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotV.removeKey().
Member Data Documentation
_ss
final SnapshotV com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE._ss package
Definition at line 1201 of file NonBlockingHashMapLong.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE.hasNext(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE.next(), com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE.remove(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.SnapshotE.SnapshotE().
The documentation for this class was generated from the following file:
NonBlockingHashMapLong.java