aa: com.cliffc.aa.HM.HM.Lambda Class Reference
com.cliffc.aa.HM.HM.Lambda Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Lambda (Syntax body, String... args)
void add_hm_work (Worklist work)
void add_val_work (Syntax child, Worklist work)
Type apply (Syntax[] args)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
T2 targ (int i)
Type val (Worklist work)
Package Attributes
final String[] _args
final Syntax _body
final int _fidx
Type _flow
T2 _hmt
VStack _nongen
Syntax _par
final T2[] _targs
final Type[] _types
Static Package Attributes
static final NonBlockingHashMapLong< Lambda > FUNS = new NonBlockingHashMapLong<>()
Detailed Description
Definition at line 477 of file HM.java.
Constructor & Destructor Documentation
Lambda()
com.cliffc.aa.HM.HM.Lambda.Lambda (Syntax body, String... args) package
Definition at line 486 of file HM.java.
{
       _args=args;
       _body=body;
       // Type variables for all arguments
       _targs = new T2[args.length];
       for( int i=0; i<args.length; i++ ) _targs[i] = T2.make_leaf();
       // Flow types for all arguments
       _types = new Type[args.length];
       for( int i=0; i<args.length; i++ ) _types[i] = Type.XSCALAR;
       // A unique FIDX for this Lambda
       _fidx = BitsFun.new_fidx();
       FUNS.put(_fidx,this);
       _flow = val(null);
     }
References com.cliffc.aa.HM.HM.Lambda._args, com.cliffc.aa.HM.HM.Lambda._body, com.cliffc.aa.HM.HM.Lambda._fidx, com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.Lambda._targs, com.cliffc.aa.HM.HM.Lambda._types, com.cliffc.aa.HM.HM.Lambda.FUNS, com.cliffc.aa.HM.HM.T2.make_leaf(), com.cliffc.aa.type.BitsFun.new_fidx(), com.cliffc.aa.HM.HM.Lambda.val(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Member Function Documentation
add_hm_work()
void com.cliffc.aa.HM.HM.Lambda.add_hm_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Reimplemented in com.cliffc.aa.HM.HM.PrimSyn.
Definition at line 535 of file HM.java.
{
       work.push(_par );
       work.push(_body);
       for( int i=0; i<_targs.length; i++ )
         if( targ(i).occurs_in_type(find()) ) work.addAll(targ(i)._deps);
     }
References com.cliffc.aa.HM.HM.Lambda._body, com.cliffc.aa.HM.HM.Syntax._par, com.cliffc.aa.HM.HM.Lambda._targs, com.cliffc.aa.HM.HM.Worklist.addAll(), com.cliffc.aa.HM.HM.Syntax.find(), com.cliffc.aa.HM.HM.Worklist.push(), and com.cliffc.aa.HM.HM.Lambda.targ().
add_val_work()
void com.cliffc.aa.HM.HM.Lambda.add_val_work (Syntax child, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Reimplemented in com.cliffc.aa.HM.HM.PrimSyn.
Definition at line 544 of file HM.java.
{
       // Body changed, all Apply sites need to recompute
       work.addAll(find()._deps);
     }
References com.cliffc.aa.HM.HM.Worklist.addAll(), and com.cliffc.aa.HM.HM.Syntax.find().
apply()
Type com.cliffc.aa.HM.HM.Lambda.apply (Syntax[] args) package
Reimplemented in com.cliffc.aa.HM.HM.Factor, com.cliffc.aa.HM.HM.Str, com.cliffc.aa.HM.HM.Dec, com.cliffc.aa.HM.HM.Add, com.cliffc.aa.HM.HM.Mul, com.cliffc.aa.HM.HM.NotNil, com.cliffc.aa.HM.HM.IsEmpty, com.cliffc.aa.HM.HM.EQ0, com.cliffc.aa.HM.HM.EQ, com.cliffc.aa.HM.HM.If, com.cliffc.aa.HM.HM.Triple, com.cliffc.aa.HM.HM.Pair, com.cliffc.aa.HM.HM.Pair1.Pair1X, and com.cliffc.aa.HM.HM.Pair1.
Definition at line 543 of file HM.java.
 { return _body._flow; }
References com.cliffc.aa.HM.HM.Lambda._body, and com.cliffc.aa.HM.HM.Syntax._flow.
debug_find()
T2 com.cliffc.aa.HM.HM.Syntax.debug_find () package inherited
Definition at line 348 of file HM.java.
 { return _hmt.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM.Syntax._hmt, and com.cliffc.aa.HM.HM.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM.hm().
find()
T2 com.cliffc.aa.HM.HM.Syntax.find () package inherited
Definition at line 344 of file HM.java.
               {                 // U-F find
       T2 t = _hmt.find();
       return t== _hmt ? t : (_hmt =t);
     }
References com.cliffc.aa.HM.HM.Syntax._hmt, and com.cliffc.aa.HM.HM.T2.find().
Referenced by com.cliffc.aa.HM.HM.Lambda.add_hm_work(), com.cliffc.aa.HM.HM.Let.add_hm_work(), com.cliffc.aa.HM.HM.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM.Lambda.add_val_work(), com.cliffc.aa.HM.HM.Let.add_val_work(), com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM.Ident.hm(), com.cliffc.aa.HM.HM.Lambda.hm(), com.cliffc.aa.HM.HM.Apply.hm(), com.cliffc.aa.HM.HM.Root.hm(), com.cliffc.aa.HM.HM.Struct.hm(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.HM.HM.PrimSyn.hm(), com.cliffc.aa.HM.HM.If.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.Let.prep_tree(), com.cliffc.aa.HM.HM.Struct.prep_tree(), com.cliffc.aa.HM.HM.NotNil.prep_tree(), com.cliffc.aa.HM.HM.Apply.val(), com.cliffc.aa.HM.HM.Root.val(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
hm()
boolean com.cliffc.aa.HM.HM.Lambda.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Reimplemented in com.cliffc.aa.HM.HM.NotNil, com.cliffc.aa.HM.HM.If, and com.cliffc.aa.HM.HM.PrimSyn.
Definition at line 517 of file HM.java.
{
       boolean progress = false;
       // The normal lambda work
       T2 old = find();
       if( old.is_err() ) return false;
       if( old.is_fun() ) {      // Already a function?  Compare-by-parts
         for( int i=0; i<_targs.length; i++ )
           if( old.args(i).unify(targ(i),work) )
             { progress=true; break; }
         if( !progress && !old.args(_targs.length).unify(_body.find(),work) )
           return false;           // Shortcut: no progress, no allocation
       }
       // Make a new T2 for progress
       T2[] targs = Arrays.copyOf(_targs,_targs.length+1);
       targs[_targs.length] = _body.find();
       T2 fun = T2.make_fun(BitsFun.make0(_fidx),targs);
       return old.unify(fun,work);
     }
References com.cliffc.aa.HM.HM.Lambda._body, com.cliffc.aa.HM.HM.Lambda._fidx, com.cliffc.aa.HM.HM.Lambda._targs, com.cliffc.aa.HM.HM.T2.args(), com.cliffc.aa.HM.HM.Syntax.find(), com.cliffc.aa.HM.HM.T2.is_err(), com.cliffc.aa.HM.HM.T2.is_fun(), com.cliffc.aa.type.BitsFun.make0(), com.cliffc.aa.HM.HM.T2.make_fun(), com.cliffc.aa.HM.HM.Lambda.targ(), and com.cliffc.aa.HM.HM.T2.unify().
more_work()
boolean com.cliffc.aa.HM.HM.Lambda.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Reimplemented in com.cliffc.aa.HM.HM.PrimSyn.
Definition at line 558 of file HM.java.
{
       if( !more_work_impl(work) ) return false;
       return _body.more_work(work);
     }
References com.cliffc.aa.HM.HM.Lambda._body, com.cliffc.aa.HM.HM.Syntax.more_work(), and com.cliffc.aa.HM.HM.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 381 of file HM.java.
{
       if( work.has(this) ) return true;
       if( DO_HM && hm(null) )   // Any more HM work?
         return false;           // Found HM work not on worklist
       if( DO_GCP && val(null)!=_flow )
         return false;           // Found GCP work not on worklist
       return true;
     }
References com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.Worklist.has(), com.cliffc.aa.HM.HM.Syntax.hm(), and com.cliffc.aa.HM.HM.Syntax.val().
Referenced by com.cliffc.aa.HM.HM.Con.more_work(), com.cliffc.aa.HM.HM.Ident.more_work(), com.cliffc.aa.HM.HM.Lambda.more_work(), com.cliffc.aa.HM.HM.Let.more_work(), com.cliffc.aa.HM.HM.Apply.more_work(), com.cliffc.aa.HM.HM.Struct.more_work(), com.cliffc.aa.HM.HM.Field.more_work(), and com.cliffc.aa.HM.HM.PrimSyn.more_work().
p()
String com.cliffc.aa.HM.HM.Syntax.p () inherited
Definition at line 393 of file HM.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 394 of file HM.java.
{
       _hmt.get_dups(dups);
       VBitSet visit = new VBitSet();
       p1(sb.i());
       if( DO_HM  ) _hmt .str(sb.p(", HM="), visit,dups);
       if( DO_GCP ) _flow.str(sb.p(", CCP="),visit.clr(),null,false);
       sb.nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.util.VBitSet.clr(), com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.HM.HM.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM.Syntax.p1(), com.cliffc.aa.HM.HM.Syntax.p2(), com.cliffc.aa.type.Type< T extends Type< T >.str(), and com.cliffc.aa.HM.HM.T2.str().
Referenced by com.cliffc.aa.HM.HM.Syntax.p(), com.cliffc.aa.HM.HM.Lambda.p2(), com.cliffc.aa.HM.HM.Let.p2(), com.cliffc.aa.HM.HM.Apply.p2(), com.cliffc.aa.HM.HM.Struct.p2(), and com.cliffc.aa.HM.HM.Field.p2().
p1()
SB com.cliffc.aa.HM.HM.Lambda.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Reimplemented in com.cliffc.aa.HM.HM.PrimSyn.
Definition at line 505 of file HM.java.
{
       sb.p("{ ");
       for( int i=0; i<_args.length; i++ ) {
         sb.p(_args[i]);
         if( DO_HM  ) sb.p(", HM=" ).p(targ(i).toString());
         if( DO_GCP ) sb.p(", CCP=").p(_types[i]);
         sb.nl().i().p("  ");
       }
       return sb.p(" -> ... } ");
     }
References com.cliffc.aa.HM.HM.Lambda._args, com.cliffc.aa.HM.HM.Lambda._types, com.cliffc.aa.HM.HM.DO_GCP, com.cliffc.aa.HM.HM.DO_HM, com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM.Lambda.targ(), and com.cliffc.aa.HM.HM.Syntax.toString().
p2()
SB com.cliffc.aa.HM.HM.Lambda.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Reimplemented in com.cliffc.aa.HM.HM.PrimSyn.
Definition at line 515 of file HM.java.
 { return _body.p0(sb,dups); }
References com.cliffc.aa.HM.HM.Lambda._body, and com.cliffc.aa.HM.HM.Syntax.p0().
prep_lookup_deps()
void com.cliffc.aa.HM.HM.Lambda.prep_lookup_deps (Ident id) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 554 of file HM.java.
{
       for( int i=0; i<_args.length; i++ )
         if( Util.eq(_args[i],id._name) ) _targs[i].push_update(id);
     }
References com.cliffc.aa.HM.HM.Lambda._args, com.cliffc.aa.HM.HM.Lambda._targs, com.cliffc.aa.util.Util.eq(), and com.cliffc.aa.HM.HM.T2.push_update().
prep_tree()
int com.cliffc.aa.HM.HM.Lambda.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Reimplemented in com.cliffc.aa.HM.HM.NotNil, and com.cliffc.aa.HM.HM.PrimSyn.
Definition at line 548 of file HM.java.
{
       prep_tree_impl(par,nongen,work,T2.make_leaf());
       VStack vs = nongen;
       for( T2 targ : _targs ) vs = new VStack(vs, targ);
       return _body.prep_tree(this,vs,work) + 1;
     }
References com.cliffc.aa.HM.HM.Lambda._body, com.cliffc.aa.HM.HM.Lambda._targs, com.cliffc.aa.HM.HM.T2.make_leaf(), com.cliffc.aa.HM.HM.Syntax.prep_tree(), com.cliffc.aa.HM.HM.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM.Lambda.targ().
prep_tree_impl()
final void com.cliffc.aa.HM.HM.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 370 of file HM.java.
{
       _par = par;
       _hmt = t;
       _flow= Type.XSCALAR;
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM.Syntax._flow, com.cliffc.aa.HM.HM.Syntax._hmt, com.cliffc.aa.HM.HM.Syntax._nongen, com.cliffc.aa.HM.HM.Syntax._par, com.cliffc.aa.HM.HM.Worklist.push(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Referenced by com.cliffc.aa.HM.HM.Con.prep_tree(), com.cliffc.aa.HM.HM.Ident.prep_tree(), com.cliffc.aa.HM.HM.Lambda.prep_tree(), com.cliffc.aa.HM.HM.Let.prep_tree(), com.cliffc.aa.HM.HM.Apply.prep_tree(), com.cliffc.aa.HM.HM.Struct.prep_tree(), com.cliffc.aa.HM.HM.Field.prep_tree(), and com.cliffc.aa.HM.HM.PrimSyn.prep_tree().
str()
SB com.cliffc.aa.HM.HM.Lambda.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Reimplemented in com.cliffc.aa.HM.HM.PrimSyn.
Definition at line 500 of file HM.java.
{
       sb.p("{ ");
       for( String arg : _args ) sb.p(arg).p(' ');
       return _body.str(sb.p("-> ")).p(" }");
     }
References com.cliffc.aa.HM.HM.Lambda._args, com.cliffc.aa.HM.HM.Lambda._body, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM.Syntax.str().
targ()
T2 com.cliffc.aa.HM.HM.Lambda.targ (int i) package
Definition at line 516 of file HM.java.
 { T2 targ = _targs[i].find(); return targ==_targs[i] ? targ : (_targs[i]=targ); }
References com.cliffc.aa.HM.HM.Lambda._targs, com.cliffc.aa.HM.HM.T2.find(), and com.cliffc.aa.HM.HM.Lambda.targ().
Referenced by com.cliffc.aa.HM.HM.Lambda.add_hm_work(), com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM.Lambda.hm(), com.cliffc.aa.HM.HM.PrimSyn.hm(), com.cliffc.aa.HM.HM.If.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.Lambda.p1(), com.cliffc.aa.HM.HM.Ident.prep_tree(), com.cliffc.aa.HM.HM.Lambda.prep_tree(), com.cliffc.aa.HM.HM.Lambda.targ(), and com.cliffc.aa.HM.HM.Root.val().
toString()
final String com.cliffc.aa.HM.HM.Syntax.toString () inherited
Definition at line 390 of file HM.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.HM.HM.Lambda.p1().
val()
Type com.cliffc.aa.HM.HM.Lambda.val (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM.Syntax.
Definition at line 541 of file HM.java.
 { return TypeFunPtr.make(_fidx,_args.length,Type.ANY); }
References com.cliffc.aa.HM.HM.Lambda._args, com.cliffc.aa.HM.HM.Lambda._fidx, com.cliffc.aa.type.Type< T extends Type< T >.ANY, and com.cliffc.aa.type.TypeFunPtr.make().
Referenced by com.cliffc.aa.HM.HM.NotNil.apply(), and com.cliffc.aa.HM.HM.Lambda.Lambda().
Member Data Documentation
_args
final String [] com.cliffc.aa.HM.HM.Lambda._args package
Definition at line 480 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Lambda.Lambda(), com.cliffc.aa.HM.HM.Lambda.p1(), com.cliffc.aa.HM.HM.Lambda.prep_lookup_deps(), com.cliffc.aa.HM.HM.Ident.prep_tree(), com.cliffc.aa.HM.HM.Lambda.str(), and com.cliffc.aa.HM.HM.Lambda.val().
_body
final Syntax com.cliffc.aa.HM.HM.Lambda._body package
Definition at line 481 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Lambda.add_hm_work(), com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM.Lambda.apply(), com.cliffc.aa.HM.HM.Lambda.hm(), com.cliffc.aa.HM.HM.Lambda.Lambda(), com.cliffc.aa.HM.HM.Lambda.more_work(), com.cliffc.aa.HM.HM.Lambda.p2(), com.cliffc.aa.HM.HM.Lambda.prep_tree(), com.cliffc.aa.HM.HM.Lambda.str(), com.cliffc.aa.HM.HM.Root.val(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
_fidx
final int com.cliffc.aa.HM.HM.Lambda._fidx package
Definition at line 484 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Lambda.hm(), com.cliffc.aa.HM.HM.Lambda.Lambda(), com.cliffc.aa.HM.HM.PrimSyn.PrimSyn(), and com.cliffc.aa.HM.HM.Lambda.val().
_flow
Type com.cliffc.aa.HM.HM.Syntax._flow package inherited
Definition at line 351 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM.Lambda.apply(), com.cliffc.aa.HM.HM.Pair1.apply(), com.cliffc.aa.HM.HM.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM.Pair.apply(), com.cliffc.aa.HM.HM.Triple.apply(), com.cliffc.aa.HM.HM.If.apply(), com.cliffc.aa.HM.HM.EQ.apply(), com.cliffc.aa.HM.HM.EQ0.apply(), com.cliffc.aa.HM.HM.IsEmpty.apply(), com.cliffc.aa.HM.HM.NotNil.apply(), com.cliffc.aa.HM.HM.Mul.apply(), com.cliffc.aa.HM.HM.Add.apply(), com.cliffc.aa.HM.HM.Dec.apply(), com.cliffc.aa.HM.HM.Str.apply(), com.cliffc.aa.HM.HM.Factor.apply(), com.cliffc.aa.HM.HM.Root.flow_type(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.Lambda.Lambda(), com.cliffc.aa.HM.HM.Syntax.more_work_impl(), com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.HM.HM.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM.Ident.val(), com.cliffc.aa.HM.HM.Let.val(), com.cliffc.aa.HM.HM.Apply.val(), com.cliffc.aa.HM.HM.Root.val(), com.cliffc.aa.HM.HM.Struct.val(), com.cliffc.aa.HM.HM.Field.val(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
_hmt
T2 com.cliffc.aa.HM.HM.Syntax._hmt package inherited
Definition at line 343 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Syntax.debug_find(), com.cliffc.aa.HM.HM.Syntax.find(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.HM.HM.Let.prep_tree(), com.cliffc.aa.HM.HM.PrimSyn.prep_tree(), com.cliffc.aa.HM.HM.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM.PrimSyn.PrimSyn(), com.cliffc.aa.HM.TestHM.run(), com.cliffc.aa.HM.TestHM9.run(), com.cliffc.aa.HM.TestHM.test05(), com.cliffc.aa.HM.TestHM9.test05(), com.cliffc.aa.HM.TestHM.test06(), com.cliffc.aa.HM.TestHM9.test06(), com.cliffc.aa.HM.TestHM.test14(), com.cliffc.aa.HM.TestHM9.test14(), com.cliffc.aa.HM.TestHM.test18(), com.cliffc.aa.HM.TestHM9.test18(), com.cliffc.aa.HM.TestHM.test20(), com.cliffc.aa.HM.TestHM9.test20(), com.cliffc.aa.HM.TestHM9.test32(), com.cliffc.aa.HM.TestHM.test32(), com.cliffc.aa.HM.TestHM9.test33(), com.cliffc.aa.HM.TestHM.test33(), com.cliffc.aa.HM.TestHM9.test34(), com.cliffc.aa.HM.TestHM.test34(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.HM.TestHM.test36(), com.cliffc.aa.HM.TestHM.test39(), com.cliffc.aa.HM.TestHM9.test39(), com.cliffc.aa.HM.TestHM.test40(), com.cliffc.aa.HM.TestHM9.test40(), com.cliffc.aa.HM.TestHM.test41(), com.cliffc.aa.HM.TestHM9.test41(), com.cliffc.aa.HM.TestHM.test42(), com.cliffc.aa.HM.TestHM9.test42(), com.cliffc.aa.HM.TestHM.test43(), com.cliffc.aa.HM.TestHM9.test43(), com.cliffc.aa.HM.TestHM.test44(), com.cliffc.aa.HM.TestHM9.test44(), com.cliffc.aa.HM.TestHM.test45(), com.cliffc.aa.HM.TestHM9.test45(), com.cliffc.aa.HM.TestHM.test49(), com.cliffc.aa.HM.TestHM9.test49(), com.cliffc.aa.HM.TestHM.test50(), com.cliffc.aa.HM.TestHM9.test50(), com.cliffc.aa.HM.TestHM.test51(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.HM.TestHM.test55(), com.cliffc.aa.HM.TestHM.test56(), and com.cliffc.aa.HM.TestHM.test57().
_nongen
VStack com.cliffc.aa.HM.HM.Syntax._nongen package inherited
Definition at line 342 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Ident.add_hm_work(), com.cliffc.aa.HM.HM.Ident.hm(), and com.cliffc.aa.HM.HM.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM.Syntax._par package inherited
Definition at line 341 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Ident.add_hm_work(), com.cliffc.aa.HM.HM.Lambda.add_hm_work(), com.cliffc.aa.HM.HM.Let.add_hm_work(), com.cliffc.aa.HM.HM.Apply.add_hm_work(), com.cliffc.aa.HM.HM.Struct.add_hm_work(), com.cliffc.aa.HM.HM.Field.add_hm_work(), com.cliffc.aa.HM.HM.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM.hm(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.HM.HM.Ident.prep_tree(), and com.cliffc.aa.HM.HM.Syntax.prep_tree_impl().
_targs
final T2 [] com.cliffc.aa.HM.HM.Lambda._targs package
Definition at line 482 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Lambda.add_hm_work(), com.cliffc.aa.HM.HM.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM.Lambda.hm(), com.cliffc.aa.HM.HM.PrimSyn.hm(), com.cliffc.aa.HM.HM.Lambda.Lambda(), com.cliffc.aa.HM.HM.Lambda.prep_lookup_deps(), com.cliffc.aa.HM.HM.Lambda.prep_tree(), com.cliffc.aa.HM.HM.PrimSyn.PrimSyn(), com.cliffc.aa.HM.HM.Lambda.targ(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
_types
final Type [] com.cliffc.aa.HM.HM.Lambda._types package
Definition at line 483 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM.If.hm(), com.cliffc.aa.HM.HM.Lambda.Lambda(), com.cliffc.aa.HM.HM.Lambda.p1(), and com.cliffc.aa.HM.HM.Root.val().
FUNS
final NonBlockingHashMapLong<Lambda> com.cliffc.aa.HM.HM.Lambda.FUNS = new NonBlockingHashMapLong<>() static package
Definition at line 479 of file HM.java.
Referenced by com.cliffc.aa.HM.HM.Root.add_sig(), com.cliffc.aa.HM.HM.Apply.add_val_work(), com.cliffc.aa.HM.HM.Lambda.Lambda(), com.cliffc.aa.HM.HM.reset(), com.cliffc.aa.HM.HM.Apply.val(), com.cliffc.aa.HM.HM.Root.val(), and com.cliffc.aa.HM.HM.T2.walk_types_in().
The documentation for this class was generated from the following file:
HM.java