aa: com.cliffc.aa.HM.HM7 Class Reference
com.cliffc.aa.HM.HM7 Class Reference
Classes
class Apply
class Con
class Field
class Ident
class Lambda
class Let
class Struct
class Syntax
class T2
class VStack
class Worklist
Public Member Functions
String toString ()
Static Public Member Functions
static T2 hm (String sprog)
Static Package Functions
static Syntax parse (String s)
static void reset ()
static Syntax term ()
Static Package Attributes
static boolean DEBUG_LEAKS =false
static final HashMap< String, T2 > PRIMS = new HashMap<>()
Static Private Member Functions
static String id ()
static boolean isAlpha0 (byte c)
static boolean isAlpha1 (byte c)
static boolean isDigit (byte c)
static boolean isWS (byte c)
static Syntax number ()
static< T > T require (char c, T t)
static void require (String s)
static byte skipWS ()
static Syntax string ()
Static Private Attributes
static byte[] BUF
static final SB ID = new SB()
static int X
Detailed Description
Definition at line 23 of file HM7.java.
Member Function Documentation
hm()
static T2 com.cliffc.aa.HM.HM7.hm (String sprog) static
Definition at line 27 of file HM7.java.
{
     Worklist work = new Worklist();
     // Simple types
     T2 bool  = T2.make_base(TypeInt.BOOL);
     T2 int64 = T2.make_base(TypeInt.INT64);
     T2 flt64 = T2.make_base(TypeFlt.FLT64);
     T2 strp  = T2.make_base(TypeMemPtr.STRPTR);
     // Primitives
     PRIMS.put("nil",T2.make_nil());
     T2 var1 = T2.make_leaf();
     T2 var2 = T2.make_leaf();
     T2 var3 = T2.make_leaf();
     PRIMS.put("pair1",T2.make_fun(var1, T2.make_fun(var2, T2.prim("pair",var1,var2) ))); // curried
     PRIMS.put("pair",T2.make_fun(var1, var2, T2.prim("pair",var1,var2) ));
     PRIMS.put("triple",T2.make_fun(var1, var2, var3, T2.prim("triple",var1,var2,var3) ));
     PRIMS.put("if",T2.make_fun(var2,var1,var1,var1));
     PRIMS.put("dec",T2.make_fun(int64,int64));
     PRIMS.put("*"  ,T2.make_fun(int64,int64,int64));
     PRIMS.put("?0",T2.make_fun(T2.make_leaf(),bool));
     PRIMS.put("isempty",T2.make_fun(strp,bool));
     // Print a string; int->str
     PRIMS.put("str",T2.make_fun(int64,strp));
     // Factor; FP div/mod-like operation
     PRIMS.put("factor",T2.make_fun(flt64,T2.prim("divmod",flt64,flt64)));
     // Parse
     Syntax prog = parse( sprog );
     // Prep for SSA: pre-gather all the (unique) ids
     int DEBUG_CNT=-1;
     int cnt_syns = prog.prep_tree(null,null,work);
     int init_T2s = T2.CNT;
     while( work.len()>0 ) {     // While work
       int oldcnt = T2.CNT;      // Used for cost-check when no-progress
       Syntax syn = work.pop();  // Get work
       T2 old = syn._t;          // Old value for progress assert
       if( work._cnt==DEBUG_CNT )
         System.out.println("break here");
       if( syn.hm(work) ) {      // Compute a new HM type and check for progress
         assert !syn.debug_find().unify(old.find(),null);// monotonic: unifying with the result is no-progress
         syn.add_kids(work);     // Push children on worklist
         syn.add_occurs(work);   // Push occurs-check ids on worklist
         if( syn._par !=null ) work.push(syn._par); // Parent updates
       } else {
         assert !DEBUG_LEAKS || oldcnt==T2.CNT;  // No-progress consumes no-new-T2s
       }
       // VERY EXPENSIVE ASSERT: O(n^2).  Every Syntax that makes progress is on the worklist
       //assert prog.more_work(work);
     }
     assert prog.more_work(work);
     //System.out.println("Initial T2s: "+init_T2s+", Prog size: "+cnt_syns+", worklist iters: "+work._cnt+", T2s: "+T2.CNT);
     return prog._t;
   }
References com.cliffc.aa.HM.HM7.Worklist._cnt, com.cliffc.aa.HM.HM7.Syntax._par, com.cliffc.aa.HM.HM7.Syntax._t, com.cliffc.aa.HM.HM7.Syntax.add_kids(), com.cliffc.aa.HM.HM7.Syntax.add_occurs(), com.cliffc.aa.type.TypeInt.BOOL, com.cliffc.aa.HM.HM7.T2.CNT, com.cliffc.aa.HM.HM7.Syntax.debug_find(), com.cliffc.aa.HM.HM7.DEBUG_LEAKS, com.cliffc.aa.HM.HM7.T2.find(), com.cliffc.aa.type.TypeFlt.FLT64, com.cliffc.aa.HM.HM7.Syntax.hm(), com.cliffc.aa.type.TypeInt.INT64, com.cliffc.aa.HM.HM7.Worklist.len(), com.cliffc.aa.HM.HM7.T2.make_base(), com.cliffc.aa.HM.HM7.T2.make_fun(), com.cliffc.aa.HM.HM7.T2.make_leaf(), com.cliffc.aa.HM.HM7.T2.make_nil(), com.cliffc.aa.HM.HM7.Syntax.more_work(), com.cliffc.aa.HM.HM7.parse(), com.cliffc.aa.HM.HM7.Worklist.pop(), com.cliffc.aa.HM.HM7.Syntax.prep_tree(), com.cliffc.aa.HM.HM7.T2.prim(), com.cliffc.aa.HM.HM7.PRIMS, com.cliffc.aa.HM.HM7.Worklist.push(), com.cliffc.aa.type.TypeMemPtr.STRPTR, and com.cliffc.aa.HM.HM7.T2.unify().
Referenced by com.cliffc.aa.HM.TestHM7.test00(), com.cliffc.aa.HM.TestHM7.test01(), com.cliffc.aa.HM.TestHM7.test02(), com.cliffc.aa.HM.TestHM7.test03(), com.cliffc.aa.HM.TestHM7.test04(), com.cliffc.aa.HM.TestHM7.test05(), com.cliffc.aa.HM.TestHM7.test06(), com.cliffc.aa.HM.TestHM7.test07(), com.cliffc.aa.HM.TestHM7.test08(), com.cliffc.aa.HM.TestHM7.test09(), com.cliffc.aa.HM.TestHM7.test10(), com.cliffc.aa.HM.TestHM7.test11(), com.cliffc.aa.HM.TestHM7.test12(), com.cliffc.aa.HM.TestHM7.test13(), com.cliffc.aa.HM.TestHM7.test14(), com.cliffc.aa.HM.TestHM7.test15(), com.cliffc.aa.HM.TestHM7.test16(), com.cliffc.aa.HM.TestHM7.test17(), com.cliffc.aa.HM.TestHM7.test18(), com.cliffc.aa.HM.TestHM7.test19(), com.cliffc.aa.HM.TestHM7.test20(), com.cliffc.aa.HM.TestHM7.test21(), com.cliffc.aa.HM.TestHM7.test22(), com.cliffc.aa.HM.TestHM7.test23(), com.cliffc.aa.HM.TestHM7.test24(), com.cliffc.aa.HM.TestHM7.test25(), com.cliffc.aa.HM.TestHM7.test26(), com.cliffc.aa.HM.TestHM7.test27(), com.cliffc.aa.HM.TestHM7.test28(), com.cliffc.aa.HM.TestHM7.test29(), com.cliffc.aa.HM.TestHM7.test30(), com.cliffc.aa.HM.TestHM7.test31(), and com.cliffc.aa.HM.TestHM7.test32().
id()
static String com.cliffc.aa.HM.HM7.id () static private
Definition at line 158 of file HM7.java.
{
     ID.clear();
     while( X<BUF.length && isAlpha1(BUF[X]) )
       ID.p((char)BUF[X++]);
     String s = ID.toString().intern();
     if( s.length()==0 ) throw unimpl("Missing id");
     return s;
   }
References com.cliffc.aa.HM.HM7.BUF, com.cliffc.aa.util.SB.clear(), com.cliffc.aa.HM.HM7.ID, com.cliffc.aa.HM.HM7.isAlpha1(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.util.SB.toString(), and com.cliffc.aa.HM.HM7.X.
Referenced by com.cliffc.aa.HM.HM7.T2.add_fld(), com.cliffc.aa.HM.HM7.Field.Field(), and com.cliffc.aa.HM.HM7.term().
isAlpha0()
static boolean com.cliffc.aa.HM.HM7.isAlpha0 (byte c) static private
Definition at line 187 of file HM7.java.
 { return ('a'<=c && c <= 'z') || ('A'<=c && c <= 'Z') || (c=='_') || (c=='*') || (c=='?'); }
Referenced by com.cliffc.aa.HM.HM7.isAlpha1(), and com.cliffc.aa.HM.HM7.term().
isAlpha1()
static boolean com.cliffc.aa.HM.HM7.isAlpha1 (byte c) static private
Definition at line 188 of file HM7.java.
 { return isAlpha0(c) || ('0'<=c && c <= '9') || (c=='/'); }
References com.cliffc.aa.HM.HM7.isAlpha0().
Referenced by com.cliffc.aa.HM.HM7.id().
isDigit()
static boolean com.cliffc.aa.HM.HM7.isDigit (byte c) static private
Definition at line 186 of file HM7.java.
 { return '0' <= c && c <= '9'; }
Referenced by com.cliffc.aa.HM.HM7.number(), and com.cliffc.aa.HM.HM7.term().
isWS()
static boolean com.cliffc.aa.HM.HM7.isWS (byte c) static private
Definition at line 185 of file HM7.java.
 { return c == ' ' || c == '\t' || c == '\n' || c == '\r'; }
Referenced by com.cliffc.aa.HM.HM7.skipWS().
number()
static Syntax com.cliffc.aa.HM.HM7.number () static private
Definition at line 166 of file HM7.java.
{
     int sum=0;
     while( X<BUF.length && isDigit(BUF[X]) )
       sum = sum*10+BUF[X++]-'0';
     if( X>= BUF.length || BUF[X]!='.' ) return new Con(TypeInt.con(sum));
     X++;
     float f = (float)sum;
     f = f + (BUF[X++]-'0')/10.0f;
     return new Con(TypeFlt.con(f));
   }
References com.cliffc.aa.HM.HM7.BUF, com.cliffc.aa.type.TypeFlt.con(), com.cliffc.aa.type.TypeInt.con(), com.cliffc.aa.HM.HM7.isDigit(), and com.cliffc.aa.HM.HM7.X.
Referenced by com.cliffc.aa.HM.HM7.term().
parse()
static Syntax com.cliffc.aa.HM.HM7.parse (String s) static package
Definition at line 96 of file HM7.java.
{
     X = 0;
     BUF = s.getBytes();
     Syntax prog = term();
     if( skipWS() != -1 ) throw unimpl("Junk at end of program: "+new String(BUF,X,BUF.length-X));
     return prog;
   }
References com.cliffc.aa.HM.HM7.BUF, com.cliffc.aa.HM.HM7.skipWS(), com.cliffc.aa.HM.HM7.term(), and com.cliffc.aa.HM.HM7.X.
Referenced by com.cliffc.aa.HM.HM7.hm().
require() [1/2]
static <T> T com.cliffc.aa.HM.HM7.require (char c, T t) static private
Definition at line 189 of file HM7.java.
 { if( skipWS()!=c ) throw unimpl("Missing '"+c+"'"); X++; return t; }
References com.cliffc.aa.HM.HM7.skipWS(), and com.cliffc.aa.HM.HM7.X.
Referenced by com.cliffc.aa.HM.HM7.string(), and com.cliffc.aa.HM.HM7.term().
require() [2/2]
static void com.cliffc.aa.HM.HM7.require (String s) static private
Definition at line 190 of file HM7.java.
{
     skipWS();
     for( int i=0; i<s.length(); i++ )
       if( X+i >= BUF.length || BUF[X+i]!=s.charAt(i) )
         throw unimpl("Missing '"+s+"'");
     X+=s.length();
   }
References com.cliffc.aa.HM.HM7.BUF, com.cliffc.aa.HM.HM7.skipWS(), and com.cliffc.aa.HM.HM7.X.
reset()
static void com.cliffc.aa.HM.HM7.reset () static package
Definition at line 89 of file HM7.java.
 { PRIMS.clear(); T2.reset(); }
References com.cliffc.aa.HM.HM7.PRIMS, and com.cliffc.aa.HM.HM7.T2.reset().
Referenced by com.cliffc.aa.HM.TestHM7.reset().
skipWS()
static byte com.cliffc.aa.HM.HM7.skipWS () static private
Definition at line 181 of file HM7.java.
{
     while( X<BUF.length && isWS(BUF[X]) ) X++;
     return X==BUF.length ? -1 : BUF[X];
   }
References com.cliffc.aa.HM.HM7.BUF, com.cliffc.aa.HM.HM7.isWS(), and com.cliffc.aa.HM.HM7.X.
Referenced by com.cliffc.aa.HM.HM7.parse(), com.cliffc.aa.HM.HM7.require(), and com.cliffc.aa.HM.HM7.term().
string()
static Syntax com.cliffc.aa.HM.HM7.string () static private
Definition at line 176 of file HM7.java.
{
     int start = ++X;
     while( X<BUF.length && BUF[X]!='"' ) X++;
     return require('"', new Con(TypeStr.con(new String(BUF,start,X-start).intern())));
   }
References com.cliffc.aa.HM.HM7.BUF, com.cliffc.aa.type.TypeStr.con(), com.cliffc.aa.HM.HM7.require(), and com.cliffc.aa.HM.HM7.X.
Referenced by com.cliffc.aa.HM.HM7.term().
term()
static Syntax com.cliffc.aa.HM.HM7.term () static package
Definition at line 103 of file HM7.java.
{
     if( skipWS()==-1 ) return null;
     if( isDigit(BUF[X]) ) return number();
     if( BUF[X]=='"' ) return string();
     if( BUF[X]=='(' ) {         // Parse an Apply
       X++;                      // Skip paren
       Syntax fun = term();
       Ary<Syntax> ARGS = new Ary<>(new Syntax[1],0);
       while( skipWS()!= ')' && X<BUF.length ) ARGS.push(term());
       return new Apply(fun,require(')',ARGS.asAry()));
     }
     if( BUF[X]=='{' ) {         // Lambda of 1 or 2 args
       X++;                      // Skip paren
       Ary<String> args = new Ary<>(new String[1],0);
       while( skipWS()!='-' ) args.push(id());
       require("->");
       Syntax body = require('}',term());
       return new Lambda(body,args.asAry());
     }
     // Let or Id
     if( isAlpha0(BUF[X]) ) {
       String id = id();
       if( skipWS()!='=' )  return new Ident(id);
       // Let expression; "id = term(); term..."
       X++;                      // Skip '='
       Syntax def = require(';',term());
       return new Let(id,def,term());
     }
     // Structure
     if( BUF[X]=='@' ) {
       X++;
       require('{',null);
       Ary<String>  ids = new Ary<>(String.class);
       Ary<Syntax> flds = new Ary<>(Syntax.class);
       while( skipWS()!='}' && X < BUF.length ) {
         String id = require('=',id());
         Syntax fld = term();
         if( fld==null ) throw unimpl("Missing term for field "+id);
         ids .push( id);
         flds.push(fld);
         if( skipWS()==',' ) X++;
       }
       return require('}',new Struct(ids.asAry(),flds.asAry()));
     }
     // Field lookup is prefix or backwards: ".x term"
     if( BUF[X]=='.' ) {
       X++;
       return new Field(id(),term());
     }
     throw unimpl("Unknown syntax");
   }
References com.cliffc.aa.util.Ary< E >.asAry(), com.cliffc.aa.HM.HM7.BUF, com.cliffc.aa.HM.HM7.id(), com.cliffc.aa.HM.HM7.isAlpha0(), com.cliffc.aa.HM.HM7.isDigit(), com.cliffc.aa.HM.HM7.number(), com.cliffc.aa.util.Ary< E >.push(), com.cliffc.aa.HM.HM7.require(), com.cliffc.aa.HM.HM7.skipWS(), com.cliffc.aa.HM.HM7.string(), and com.cliffc.aa.HM.HM7.X.
Referenced by com.cliffc.aa.HM.HM7.parse().
toString()
String com.cliffc.aa.HM.HM7.toString ()
Definition at line 95 of file HM7.java.
 { return new String(BUF,X,BUF.length-X); }
References com.cliffc.aa.HM.HM7.BUF, and com.cliffc.aa.HM.HM7.X.
Member Data Documentation
BUF
byte [] com.cliffc.aa.HM.HM7.BUF static private
Definition at line 94 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.id(), com.cliffc.aa.HM.HM7.number(), com.cliffc.aa.HM.HM7.parse(), com.cliffc.aa.HM.HM7.require(), com.cliffc.aa.HM.HM7.skipWS(), com.cliffc.aa.HM.HM7.string(), com.cliffc.aa.HM.HM7.term(), and com.cliffc.aa.HM.HM7.toString().
DEBUG_LEAKS
boolean com.cliffc.aa.HM.HM7.DEBUG_LEAKS =false static package
Definition at line 25 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.T2.fresh_unify(), and com.cliffc.aa.HM.HM7.hm().
ID
final SB com.cliffc.aa.HM.HM7.ID = new SB() static private
Definition at line 157 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.id().
PRIMS
final HashMap<String,T2> com.cliffc.aa.HM.HM7.PRIMS = new HashMap<>() static package
Definition at line 24 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.Ident.add_occurs(), com.cliffc.aa.HM.HM7.hm(), com.cliffc.aa.HM.HM7.Ident.hm(), and com.cliffc.aa.HM.HM7.reset().
X
int com.cliffc.aa.HM.HM7.X static private
Definition at line 93 of file HM7.java.
Referenced by com.cliffc.aa.HM.HM7.id(), com.cliffc.aa.HM.HM7.number(), com.cliffc.aa.HM.HM7.parse(), com.cliffc.aa.HM.HM7.require(), com.cliffc.aa.HM.HM7.skipWS(), com.cliffc.aa.HM.HM7.string(), com.cliffc.aa.HM.HM7.term(), and com.cliffc.aa.HM.HM7.toString().
The documentation for this class was generated from the following file:
HM7.java