aa: com.cliffc.aa.TestREPL Class Reference
com.cliffc.aa.TestREPL Class Reference
Public Member Functions
void close_repl ()
void open_repl ()
void testREPL00 ()
void testREPL01 ()
void testREPL02 ()
void testREPL03 ()
void testREPL04 () throws IOException
Public Attributes
final SystemErrRule sysErr = new SystemErrRule().enableLog().muteForSuccessfulTests()
final SystemOutRule sysOut = new SystemOutRule().enableLog().muteForSuccessfulTests()
Private Member Functions
void test (String partial, String expected)
void testerr (String partial, String parerr, String expected, int line, int cur_off)
Private Attributes
String _prog
Detailed Description
Definition at line 16 of file TestREPL.java.
Member Function Documentation
close_repl()
void com.cliffc.aa.TestREPL.close_repl ()
Definition at line 33 of file TestREPL.java.
{
   }
open_repl()
void com.cliffc.aa.TestREPL.open_repl ()
Definition at line 22 of file TestREPL.java.
{
     REPL.init();
     _prog = "";
     // Drain the initial prompt string so tests do not expect one
     String actual = sysOut.getLog();
     String expected = REPL.prompt;
     assertEquals(expected,actual);
     sysOut.clearLog();
     assertTrue(sysErr.getLog().isEmpty());
   }
References com.cliffc.aa.TestREPL._prog, com.cliffc.aa.REPL.init(), com.cliffc.aa.REPL.prompt, com.cliffc.aa.TestREPL.sysErr, and com.cliffc.aa.TestREPL.sysOut.
test()
void com.cliffc.aa.TestREPL.test (String partial, String expected) private
Definition at line 80 of file TestREPL.java.
{
     _prog = REPL.go_one(_prog,partial);
     String actual = sysOut.getLog();
     String exp = expected+System.lineSeparator()+REPL.prompt;
     assertEquals(exp,actual);
     sysOut.clearLog();
     assertTrue(sysErr.getLog().isEmpty());
   }
References com.cliffc.aa.TestREPL._prog, com.cliffc.aa.REPL.go_one(), com.cliffc.aa.REPL.prompt, com.cliffc.aa.TestREPL.sysErr, and com.cliffc.aa.TestREPL.sysOut.
Referenced by com.cliffc.aa.TestREPL.testREPL00(), com.cliffc.aa.TestREPL.testREPL01(), com.cliffc.aa.TestREPL.testREPL02(), com.cliffc.aa.TestREPL.testREPL03(), and com.cliffc.aa.TestREPL.testREPL04().
testerr()
void com.cliffc.aa.TestREPL.testerr (String partial, String parerr, String expected, int line, int cur_off) private
Definition at line 90 of file TestREPL.java.
{
     _prog = REPL.go_one(_prog,partial);
     String actual = sysOut.getLog();
     String cursor = new String(new char[cur_off]).replace('\0', ' ');
     String exp = new SB().p("stdin:").p(line).p(":").p(expected).nl().p(parerr).p(';').nl().p(cursor).p('^').nl().p(REPL.prompt).toString();
     assertEquals(exp,actual);
     sysOut.clearLog();
     assertTrue(sysErr.getLog().isEmpty());
   }
References com.cliffc.aa.TestREPL._prog, com.cliffc.aa.REPL.go_one(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.REPL.prompt, com.cliffc.aa.TestREPL.sysErr, com.cliffc.aa.TestREPL.sysOut, and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.TestREPL.testREPL01(), and com.cliffc.aa.TestREPL.testREPL03().
testREPL00()
void com.cliffc.aa.TestREPL.testREPL00 ()
Definition at line 37 of file TestREPL.java.
{
     test("2", "2");
   }
References com.cliffc.aa.TestREPL.test().
testREPL01()
void com.cliffc.aa.TestREPL.testREPL01 ()
Definition at line 42 of file TestREPL.java.
{
     test("2+3", "5");
     test("x=3", "3");
     test("x*x", "9");
     testerr("y*y", "y*y", "Unknown ref 'y'",4,0);
     test("x=4", "4");
     testerr("x+x", "x=4", "Cannot re-assign final val 'x'",4,0);
     test("3+2", "5");
     test("sq={x->x*x}", "[sq=*{x -> }]");
     test("sq 5","25");
     testerr("sq \"abc\"", "sq={x->x*x}", "*\"abc\" is none of (flt64,int64)", 6,7);
     testerr("x", "x=4", "Cannot re-assign final val 'x'",4,0);
   }
References com.cliffc.aa.TestREPL.test(), and com.cliffc.aa.TestREPL.testerr().
testREPL02()
void com.cliffc.aa.TestREPL.testREPL02 ()
Definition at line 57 of file TestREPL.java.
{
     test("do={pred->{body->pred()?body():^; do pred body}}","[do=*{pred -> }]");
     test("sum:=0; i:=0; do {i++ < 100} {sum:=sum+i}; sum","int64");
   }
References com.cliffc.aa.TestREPL.test().
testREPL03()
void com.cliffc.aa.TestREPL.testREPL03 ()
Definition at line 63 of file TestREPL.java.
{
     test   ("hash := {@{ tab = [3]; get = { key -> idx = key.hash(); tab[idx] } } }","[hash=*{ -> }]");
     testerr("junk := hash:int","junk := hash:int","[hash=*{ -> }] is not a int64",2,12);
     testerr("hash.tab","hash.tab","Unknown field '.tab'",2,5);
     test   ("x := hash()","@{tab==*[3]0/obj?; get==[get=*{key -> }]}");
     testerr("x.#tab","x.#tab","Unknown ref 'tab'",3,3);
     test   ("#x.tab","3");
   }
References com.cliffc.aa.TestREPL.test(), and com.cliffc.aa.TestREPL.testerr().
testREPL04()
void com.cliffc.aa.TestREPL.testREPL04 () throws IOException
Definition at line 72 of file TestREPL.java.
{
     String hash_src = new String(Files.readAllBytes( Paths.get("test/java/com/cliffc/aa","HashTable.aa")));
     test(hash_src,"[HashTable=*{ -> }]");
     test("htab = HashTable()","@{_tab=*[7]0/obj; get=[get=*{key -> }]; put=[put=*{key val -> }]}");
     test("htab.put(\"Monday\",1)","0");
   }
References com.cliffc.aa.TestREPL.test().
Member Data Documentation
_prog
String com.cliffc.aa.TestREPL._prog private
Definition at line 21 of file TestREPL.java.
Referenced by com.cliffc.aa.TestREPL.open_repl(), com.cliffc.aa.TestREPL.test(), and com.cliffc.aa.TestREPL.testerr().
sysErr
final SystemErrRule com.cliffc.aa.TestREPL.sysErr = new SystemErrRule().enableLog().muteForSuccessfulTests()
Definition at line 19 of file TestREPL.java.
Referenced by com.cliffc.aa.TestREPL.open_repl(), com.cliffc.aa.TestREPL.test(), and com.cliffc.aa.TestREPL.testerr().
sysOut
final SystemOutRule com.cliffc.aa.TestREPL.sysOut = new SystemOutRule().enableLog().muteForSuccessfulTests()
Definition at line 18 of file TestREPL.java.
Referenced by com.cliffc.aa.TestREPL.open_repl(), com.cliffc.aa.TestREPL.test(), and com.cliffc.aa.TestREPL.testerr().
The documentation for this class was generated from the following file:
TestREPL.java