aa: com.cliffc.aa.HM.HM9.Pair1 Class Reference
com.cliffc.aa.HM.HM9.Pair1 Class Reference
Classes
class Pair1X
Public Member Functions
Pair1 ()
String p ()
final String toString ()
Package Functions
void add_hm_work (Worklist work)
void add_val_work (Syntax child, Worklist work)
Type apply (Syntax[] args)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
PrimSyn make ()
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
String name ()
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
T2 targ (int i)
Type val (Worklist work)
Static Package Functions
static void reset ()
Package Attributes
final String[] _args
final Syntax _body
final int _fidx
Type _flow
T2 _hmt
VStack _nongen
Syntax _par
final T2[] _targs
final Type[] _types
Static Package Attributes
static T2 BOOL
static T2 FLT64
static final NonBlockingHashMapLong< Lambda > FUNS = new NonBlockingHashMapLong<>()
static T2 INT64
static HashMap< Type, Pair1X > PAIR1S = new HashMap<>()
static int PAIR_ALIAS
static T2 STRP
static int TRIPLE_ALIAS
static T2 var2
static Worklist WORK
Static Private Attributes
static final String[][] IDS
static T2 var1
Detailed Description
Definition at line 978 of file HM9.java.
Constructor & Destructor Documentation
Pair1()
com.cliffc.aa.HM.HM9.Pair1.Pair1 ()
Definition at line 982 of file HM9.java.
                    {
       super(var1=T2.make_leaf(),T2.make_fun(BitsFun.ANY,var2=T2.make_leaf(),T2.make_struct(BitsAlias.make0(PAIR_ALIAS),new String[]{"0","1"},new T2[]{var1,var2})));
     }
References com.cliffc.aa.type.BitsFun.ANY, com.cliffc.aa.type.BitsAlias.make0(), com.cliffc.aa.HM.HM9.T2.make_fun(), com.cliffc.aa.HM.HM9.T2.make_leaf(), com.cliffc.aa.HM.HM9.T2.make_struct(), com.cliffc.aa.HM.HM9.PrimSyn.PAIR_ALIAS, com.cliffc.aa.HM.HM9.Pair1.var1, and com.cliffc.aa.HM.HM9.Pair1.var2.
Referenced by com.cliffc.aa.HM.HM9.Pair1.make().
Member Function Documentation
add_hm_work()
void com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work (Worklist work) package inherited
Reimplemented from com.cliffc.aa.HM.HM9.Lambda.
Definition at line 966 of file HM9.java.
{
       if( find().is_err() ) work.push(_par);
     }
References com.cliffc.aa.HM.HM9.Syntax._par, com.cliffc.aa.HM.HM9.Syntax.find(), and com.cliffc.aa.HM.HM9.Worklist.push().
add_val_work()
void com.cliffc.aa.HM.HM9.PrimSyn.add_val_work (Syntax child, Worklist work) package inherited
Reimplemented from com.cliffc.aa.HM.HM9.Lambda.
Definition at line 969 of file HM9.java.
 { throw unimpl(); }
apply()
Type com.cliffc.aa.HM.HM9.Pair1.apply (Syntax[] args) package
Reimplemented from com.cliffc.aa.HM.HM9.Lambda.
Definition at line 986 of file HM9.java.
{
       Type t = args[0]._flow;
       Pair1X p1x = PAIR1S.get(t);
       if( p1x == null )
         PAIR1S.put(t,p1x = new Pair1X(t));
       return p1x._flow;
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, and com.cliffc.aa.HM.HM9.Pair1.PAIR1S.
debug_find()
T2 com.cliffc.aa.HM.HM9.Syntax.debug_find () package inherited
Definition at line 329 of file HM9.java.
 { return _hmt.debug_find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM9.Syntax._hmt, and com.cliffc.aa.HM.HM9.T2.debug_find().
Referenced by com.cliffc.aa.HM.HM9.hm().
find()
T2 com.cliffc.aa.HM.HM9.Syntax.find () package inherited
Definition at line 325 of file HM9.java.
               {                 // U-F find
       T2 t = _hmt.find();
       return t== _hmt ? t : (_hmt =t);
     }
References com.cliffc.aa.HM.HM9.Syntax._hmt, and com.cliffc.aa.HM.HM9.T2.find().
Referenced by com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_val_work(), com.cliffc.aa.HM.HM9.Let.add_val_work(), com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Ident.hm(), com.cliffc.aa.HM.HM9.Lambda.hm(), com.cliffc.aa.HM.HM9.Apply.hm(), com.cliffc.aa.HM.HM9.Root.hm(), com.cliffc.aa.HM.HM9.Struct.hm(), com.cliffc.aa.HM.HM9.Field.hm(), com.cliffc.aa.HM.HM9.PrimSyn.hm(), com.cliffc.aa.HM.HM9.If.hm(), com.cliffc.aa.HM.HM9.NotNil.hm(), com.cliffc.aa.HM.HM9.Apply.is_if_nil(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.NotNil.prep_tree(), com.cliffc.aa.HM.HM9.Apply.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
hm()
boolean com.cliffc.aa.HM.HM9.PrimSyn.hm (Worklist work) package inherited
Reimplemented from com.cliffc.aa.HM.HM9.Lambda.
Reimplemented in com.cliffc.aa.HM.HM9.NotNil, and com.cliffc.aa.HM.HM9.If.
Definition at line 956 of file HM9.java.
{
       T2 old = find();
       if( old.is_err() ) return false;
       assert old.is_fun();
       for( int i=0; i<_targs.length; i++ )
         if( targ(i).is_err() )
           return old.unify(targ(i),work);
       return false;
     }
References com.cliffc.aa.HM.HM9.Lambda._targs, com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.HM.HM9.T2.is_err(), com.cliffc.aa.HM.HM9.T2.is_fun(), com.cliffc.aa.HM.HM9.Lambda.targ(), and com.cliffc.aa.HM.HM9.T2.unify().
make()
PrimSyn com.cliffc.aa.HM.HM9.Pair1.make () package
Reimplemented from com.cliffc.aa.HM.HM9.PrimSyn.
Definition at line 985 of file HM9.java.
 { return new Pair1(); }
References com.cliffc.aa.HM.HM9.Pair1.Pair1().
more_work()
boolean com.cliffc.aa.HM.HM9.PrimSyn.more_work (Worklist work) package inherited
Reimplemented from com.cliffc.aa.HM.HM9.Lambda.
Definition at line 970 of file HM9.java.
 { return more_work_impl(work); }
References com.cliffc.aa.HM.HM9.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM9.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 362 of file HM9.java.
{
       if( work.has(this) ) return true;
       if( DO_HM && hm(null) )   // Any more HM work?
         return false;           // Found HM work not on worklist
       if( DO_GCP && val(null)!=_flow )
         return false;           // Found GCP work not on worklist
       return true;
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.DO_GCP, com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.Worklist.has(), com.cliffc.aa.HM.HM9.Syntax.hm(), and com.cliffc.aa.HM.HM9.Syntax.val().
Referenced by com.cliffc.aa.HM.HM9.Con.more_work(), com.cliffc.aa.HM.HM9.Ident.more_work(), com.cliffc.aa.HM.HM9.Lambda.more_work(), com.cliffc.aa.HM.HM9.Let.more_work(), com.cliffc.aa.HM.HM9.Apply.more_work(), com.cliffc.aa.HM.HM9.Struct.more_work(), com.cliffc.aa.HM.HM9.Field.more_work(), and com.cliffc.aa.HM.HM9.PrimSyn.more_work().
name()
String com.cliffc.aa.HM.HM9.Pair1.name () package
Reimplemented from com.cliffc.aa.HM.HM9.PrimSyn.
Definition at line 979 of file HM9.java.
 { return "pair1"; }
p()
String com.cliffc.aa.HM.HM9.Syntax.p () inherited
Definition at line 374 of file HM9.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM9.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM9.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 375 of file HM9.java.
{
       _hmt.get_dups(dups);
       VBitSet visit = new VBitSet();
       p1(sb.i());
       if( DO_HM  ) _hmt .str(sb.p(", HM="), visit,dups);
       if( DO_GCP ) _flow.str(sb.p(", CCP="),visit.clr(),null,false);
       sb.nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.util.VBitSet.clr(), com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM9.DO_GCP, com.cliffc.aa.HM.HM9.DO_HM, com.cliffc.aa.HM.HM9.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM9.Syntax.p1(), com.cliffc.aa.HM.HM9.Syntax.p2(), com.cliffc.aa.type.Type< T extends Type< T >.str(), and com.cliffc.aa.HM.HM9.T2.str().
Referenced by com.cliffc.aa.HM.HM9.Syntax.p(), com.cliffc.aa.HM.HM9.Lambda.p2(), com.cliffc.aa.HM.HM9.Let.p2(), com.cliffc.aa.HM.HM9.Apply.p2(), com.cliffc.aa.HM.HM9.Struct.p2(), and com.cliffc.aa.HM.HM9.Field.p2().
p1()
SB com.cliffc.aa.HM.HM9.PrimSyn.p1 (SB sb) package inherited
Reimplemented from com.cliffc.aa.HM.HM9.Lambda.
Definition at line 972 of file HM9.java.
 { return sb.p(name()); }
References com.cliffc.aa.HM.HM9.PrimSyn.name(), and com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM9.PrimSyn.p2 (SB sb, VBitSet dups) package inherited
Reimplemented from com.cliffc.aa.HM.HM9.Lambda.
Definition at line 973 of file HM9.java.
 { return sb; }
prep_lookup_deps()
void com.cliffc.aa.HM.HM9.Lambda.prep_lookup_deps (Ident id) package inherited
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 533 of file HM9.java.
{
       for( int i=0; i<_args.length; i++ )
         if( Util.eq(_args[i],id._name) ) _targs[i].push_update(id);
     }
References com.cliffc.aa.HM.HM9.Lambda._args, com.cliffc.aa.HM.HM9.Lambda._targs, com.cliffc.aa.util.Util.eq(), and com.cliffc.aa.HM.HM9.T2.push_update().
prep_tree()
int com.cliffc.aa.HM.HM9.PrimSyn.prep_tree (Syntax par, VStack nongen, Worklist work) package inherited
Reimplemented from com.cliffc.aa.HM.HM9.Lambda.
Reimplemented in com.cliffc.aa.HM.HM9.NotNil.
Definition at line 952 of file HM9.java.
{
       prep_tree_impl(par,nongen,work, _hmt);
       return 1;
     }
References com.cliffc.aa.HM.HM9.Syntax._hmt, and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
prep_tree_impl()
final void com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 351 of file HM9.java.
{
       _par = par;
       _hmt = t;
       _flow= Type.XSCALAR;
       _nongen = nongen;
       work.push(this);
     }
References com.cliffc.aa.HM.HM9.Syntax._flow, com.cliffc.aa.HM.HM9.Syntax._hmt, com.cliffc.aa.HM.HM9.Syntax._nongen, com.cliffc.aa.HM.HM9.Syntax._par, com.cliffc.aa.HM.HM9.Worklist.push(), and com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR.
Referenced by com.cliffc.aa.HM.HM9.Con.prep_tree(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), com.cliffc.aa.HM.HM9.Lambda.prep_tree(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.Apply.prep_tree(), com.cliffc.aa.HM.HM9.Struct.prep_tree(), com.cliffc.aa.HM.HM9.Field.prep_tree(), and com.cliffc.aa.HM.HM9.PrimSyn.prep_tree().
reset()
static void com.cliffc.aa.HM.HM9.PrimSyn.reset () static package inherited
Definition at line 930 of file HM9.java.
{
       PAIR_ALIAS   = BitsAlias.new_alias(BitsAlias.REC);
       TRIPLE_ALIAS = BitsAlias.new_alias(BitsAlias.REC);
       BOOL  = T2.make_base(TypeInt.BOOL);
       INT64 = T2.make_base(TypeInt.INT64);
       FLT64 = T2.make_base(TypeFlt.FLT64);
       STRP  = T2.make_base(TypeMemPtr.STRPTR);
     }
References com.cliffc.aa.type.TypeInt.BOOL, com.cliffc.aa.HM.HM9.PrimSyn.BOOL, com.cliffc.aa.type.TypeFlt.FLT64, com.cliffc.aa.HM.HM9.PrimSyn.FLT64, com.cliffc.aa.type.TypeInt.INT64, com.cliffc.aa.HM.HM9.PrimSyn.INT64, com.cliffc.aa.HM.HM9.T2.make_base(), com.cliffc.aa.type.BitsAlias.new_alias(), com.cliffc.aa.HM.HM9.PrimSyn.PAIR_ALIAS, com.cliffc.aa.type.BitsAlias.REC, com.cliffc.aa.HM.HM9.PrimSyn.STRP, com.cliffc.aa.type.TypeMemPtr.STRPTR, and com.cliffc.aa.HM.HM9.PrimSyn.TRIPLE_ALIAS.
Referenced by com.cliffc.aa.HM.HM9.reset().
str()
SB com.cliffc.aa.HM.HM9.PrimSyn.str (SB sb) package inherited
Reimplemented from com.cliffc.aa.HM.HM9.Lambda.
Definition at line 971 of file HM9.java.
 { return sb.p(name()); }
References com.cliffc.aa.HM.HM9.PrimSyn.name(), and com.cliffc.aa.util.SB.p().
targ()
T2 com.cliffc.aa.HM.HM9.Lambda.targ (int i) package inherited
Definition at line 495 of file HM9.java.
 { T2 targ = _targs[i].find(); return targ==_targs[i] ? targ : (_targs[i]=targ); }
References com.cliffc.aa.HM.HM9.Lambda._targs, com.cliffc.aa.HM.HM9.T2.find(), and com.cliffc.aa.HM.HM9.Lambda.targ().
Referenced by com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Lambda.hm(), com.cliffc.aa.HM.HM9.PrimSyn.hm(), com.cliffc.aa.HM.HM9.If.hm(), com.cliffc.aa.HM.HM9.NotNil.hm(), com.cliffc.aa.HM.HM9.Lambda.p1(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), com.cliffc.aa.HM.HM9.Lambda.prep_tree(), and com.cliffc.aa.HM.HM9.Lambda.targ().
toString()
final String com.cliffc.aa.HM.HM9.Syntax.toString () inherited
Definition at line 371 of file HM9.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM9.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Referenced by com.cliffc.aa.HM.HM9.Lambda.p1().
val()
Type com.cliffc.aa.HM.HM9.Lambda.val (Worklist work) package inherited
Reimplemented from com.cliffc.aa.HM.HM9.Syntax.
Definition at line 520 of file HM9.java.
 { return TypeFunPtr.make(_fidx,_args.length,Type.ANY); }
References com.cliffc.aa.HM.HM9.Lambda._args, com.cliffc.aa.HM.HM9.Lambda._fidx, com.cliffc.aa.type.Type< T extends Type< T >.ANY, and com.cliffc.aa.type.TypeFunPtr.make().
Referenced by com.cliffc.aa.HM.HM9.NotNil.apply(), and com.cliffc.aa.HM.HM9.Lambda.Lambda().
Member Data Documentation
_args
final String [] com.cliffc.aa.HM.HM9.Lambda._args package inherited
Definition at line 459 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Lambda.Lambda(), com.cliffc.aa.HM.HM9.Lambda.p1(), com.cliffc.aa.HM.HM9.Lambda.prep_lookup_deps(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), com.cliffc.aa.HM.HM9.Lambda.str(), and com.cliffc.aa.HM.HM9.Lambda.val().
_body
final Syntax com.cliffc.aa.HM.HM9.Lambda._body package inherited
Definition at line 460 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Lambda.apply(), com.cliffc.aa.HM.HM9.Lambda.hm(), com.cliffc.aa.HM.HM9.Lambda.Lambda(), com.cliffc.aa.HM.HM9.Lambda.more_work(), com.cliffc.aa.HM.HM9.Lambda.p2(), com.cliffc.aa.HM.HM9.Lambda.prep_tree(), com.cliffc.aa.HM.HM9.Lambda.str(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
_fidx
final int com.cliffc.aa.HM.HM9.Lambda._fidx package inherited
Definition at line 463 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Lambda.hm(), com.cliffc.aa.HM.HM9.Lambda.Lambda(), com.cliffc.aa.HM.HM9.PrimSyn.PrimSyn(), and com.cliffc.aa.HM.HM9.Lambda.val().
_flow
Type com.cliffc.aa.HM.HM9.Syntax._flow package inherited
Definition at line 332 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Lambda.apply(), com.cliffc.aa.HM.HM9.Pair1.apply(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Pair.apply(), com.cliffc.aa.HM.HM9.Triple.apply(), com.cliffc.aa.HM.HM9.If.apply(), com.cliffc.aa.HM.HM9.EQ.apply(), com.cliffc.aa.HM.HM9.EQ0.apply(), com.cliffc.aa.HM.HM9.IsEmpty.apply(), com.cliffc.aa.HM.HM9.NotNil.apply(), com.cliffc.aa.HM.HM9.Mul.apply(), com.cliffc.aa.HM.HM9.Dec.apply(), com.cliffc.aa.HM.HM9.Str.apply(), com.cliffc.aa.HM.HM9.Factor.apply(), com.cliffc.aa.HM.HM9.Root.flow_type(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Lambda.Lambda(), com.cliffc.aa.HM.HM9.Syntax.more_work_impl(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), com.cliffc.aa.HM.HM9.Ident.val(), com.cliffc.aa.HM.HM9.Let.val(), com.cliffc.aa.HM.HM9.Apply.val(), com.cliffc.aa.HM.HM9.Root.val(), com.cliffc.aa.HM.HM9.Struct.val(), com.cliffc.aa.HM.HM9.Field.val(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
_hmt
T2 com.cliffc.aa.HM.HM9.Syntax._hmt package inherited
Definition at line 324 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Syntax.debug_find(), com.cliffc.aa.HM.HM9.Syntax.find(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM9.Let.prep_tree(), com.cliffc.aa.HM.HM9.PrimSyn.prep_tree(), com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl(), and com.cliffc.aa.HM.HM9.PrimSyn.PrimSyn().
_nongen
VStack com.cliffc.aa.HM.HM9.Syntax._nongen package inherited
Definition at line 323 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.add_hm_work(), com.cliffc.aa.HM.HM9.Ident.hm(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM9.Syntax._par package inherited
Definition at line 322 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Ident.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.Apply.add_hm_work(), com.cliffc.aa.HM.HM9.Struct.add_hm_work(), com.cliffc.aa.HM.HM9.Field.add_hm_work(), com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM9.hm(), com.cliffc.aa.HM.HM9.Ident.prep_tree(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
_targs
final T2 [] com.cliffc.aa.HM.HM9.Lambda._targs package inherited
Definition at line 461 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Lambda.hm(), com.cliffc.aa.HM.HM9.PrimSyn.hm(), com.cliffc.aa.HM.HM9.Lambda.Lambda(), com.cliffc.aa.HM.HM9.Lambda.prep_lookup_deps(), com.cliffc.aa.HM.HM9.Lambda.prep_tree(), com.cliffc.aa.HM.HM9.PrimSyn.PrimSyn(), com.cliffc.aa.HM.HM9.Lambda.targ(), and com.cliffc.aa.HM.HM9.T2.walk_types_in().
_types
final Type [] com.cliffc.aa.HM.HM9.Lambda._types package inherited
Definition at line 462 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.If.hm(), com.cliffc.aa.HM.HM9.Lambda.Lambda(), and com.cliffc.aa.HM.HM9.Lambda.p1().
BOOL
T2 com.cliffc.aa.HM.HM9.PrimSyn.BOOL static package inherited
Definition at line 927 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.EQ.EQ(), com.cliffc.aa.HM.HM9.EQ0.EQ0(), com.cliffc.aa.HM.HM9.IsEmpty.IsEmpty(), and com.cliffc.aa.HM.HM9.PrimSyn.reset().
FLT64
T2 com.cliffc.aa.HM.HM9.PrimSyn.FLT64 static package inherited
Definition at line 927 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Factor.Factor(), and com.cliffc.aa.HM.HM9.PrimSyn.reset().
FUNS
final NonBlockingHashMapLong<Lambda> com.cliffc.aa.HM.HM9.Lambda.FUNS = new NonBlockingHashMapLong<>() static package inherited
Definition at line 458 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Lambda.Lambda(), com.cliffc.aa.HM.HM9.reset(), com.cliffc.aa.HM.HM9.Apply.val(), com.cliffc.aa.HM.HM9.T2.walk_types_in(), and com.cliffc.aa.HM.HM9.Root.xval().
IDS
final String [][] com.cliffc.aa.HM.HM9.PrimSyn.IDS static private inherited
Initial value:
= new String[][] {
      null,
      {"x"},
      {"x","y"},
      {"x","y","z"},
    }
Definition at line 939 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.PrimSyn.PrimSyn().
INT64
T2 com.cliffc.aa.HM.HM9.PrimSyn.INT64 static package inherited
Definition at line 927 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Dec.Dec(), com.cliffc.aa.HM.HM9.EQ0.EQ0(), com.cliffc.aa.HM.HM9.Mul.Mul(), com.cliffc.aa.HM.HM9.PrimSyn.reset(), and com.cliffc.aa.HM.HM9.Str.Str().
PAIR1S
HashMap<Type,Pair1X> com.cliffc.aa.HM.HM9.Pair1.PAIR1S = new HashMap<>() static package
Definition at line 981 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Pair1.apply(), and com.cliffc.aa.HM.HM9.reset().
PAIR_ALIAS
int com.cliffc.aa.HM.HM9.PrimSyn.PAIR_ALIAS static package inherited
Definition at line 929 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Pair1.Pair1X.apply(), com.cliffc.aa.HM.HM9.Pair.apply(), com.cliffc.aa.HM.HM9.Pair.Pair(), com.cliffc.aa.HM.HM9.Pair1.Pair1(), com.cliffc.aa.HM.HM9.Pair1.Pair1X.Pair1X(), and com.cliffc.aa.HM.HM9.PrimSyn.reset().
STRP
T2 com.cliffc.aa.HM.HM9.PrimSyn.STRP static package inherited
Definition at line 927 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.IsEmpty.IsEmpty(), com.cliffc.aa.HM.HM9.PrimSyn.reset(), and com.cliffc.aa.HM.HM9.Str.Str().
TRIPLE_ALIAS
int com.cliffc.aa.HM.HM9.PrimSyn.TRIPLE_ALIAS static package inherited
Definition at line 929 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Triple.apply(), com.cliffc.aa.HM.HM9.PrimSyn.reset(), and com.cliffc.aa.HM.HM9.Triple.Triple().
var1
T2 com.cliffc.aa.HM.HM9.Pair1.var1 static private
Definition at line 980 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Pair1.Pair1().
var2
T2 com.cliffc.aa.HM.HM9.Pair1.var2 static package
Definition at line 980 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Pair1.Pair1().
WORK
Worklist com.cliffc.aa.HM.HM9.PrimSyn.WORK static package inherited
Definition at line 928 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.hm().
The documentation for this class was generated from the following file:
HM9.java