aa: com.cliffc.aa.HM.HM9.Worklist Class Reference
com.cliffc.aa.HM.HM9.Worklist Class Reference
Public Member Functions
void addAll (Ary<? extends Syntax > ss)
void clear ()
boolean has (Syntax s)
int len ()
Syntax pop ()
void push (Syntax s)
String toString ()
Public Attributes
int _cnt
Private Attributes
final Ary< Syntax > _ary = new Ary<>(Syntax.class)
final HashSet< Syntax > _work = new HashSet<>()
Detailed Description
Definition at line 269 of file HM9.java.
Member Function Documentation
addAll()
void com.cliffc.aa.HM.HM9.Worklist.addAll (Ary<? extends Syntax > ss)
Definition at line 278 of file HM9.java.
 { if( ss != null ) for( Syntax s : ss ) push(s); }
References com.cliffc.aa.HM.HM9.Worklist.push().
Referenced by com.cliffc.aa.HM.HM9.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM9.T2.add_fld(), com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_val_work(), com.cliffc.aa.HM.HM9.Let.add_val_work(), com.cliffc.aa.HM.HM9.Apply.add_val_work(), and com.cliffc.aa.HM.HM9.Apply.hm().
clear()
void com.cliffc.aa.HM.HM9.Worklist.clear ()
Definition at line 279 of file HM9.java.
{
       _cnt=0;
       _ary.clear();
       _work.clear();
     }
References com.cliffc.aa.HM.HM9.Worklist._ary, com.cliffc.aa.HM.HM9.Worklist._cnt, and com.cliffc.aa.HM.HM9.Worklist._work.
has()
boolean com.cliffc.aa.HM.HM9.Worklist.has (Syntax s)
Definition at line 277 of file HM9.java.
 { return _work.contains(s); }
References com.cliffc.aa.HM.HM9.Worklist._work.
Referenced by com.cliffc.aa.HM.HM9.Syntax.more_work_impl().
len()
int com.cliffc.aa.HM.HM9.Worklist.len ()
Definition at line 273 of file HM9.java.
 { return _ary.len(); }
References com.cliffc.aa.HM.HM9.Worklist._ary.
Referenced by com.cliffc.aa.HM.HM9.hm().
pop()
Syntax com.cliffc.aa.HM.HM9.Worklist.pop ()
Definition at line 275 of file HM9.java.
 { Syntax s = _ary.pop();_cnt++;            _work.remove(s); return s; }
References com.cliffc.aa.HM.HM9.Worklist._ary, com.cliffc.aa.HM.HM9.Worklist._cnt, and com.cliffc.aa.HM.HM9.Worklist._work.
Referenced by com.cliffc.aa.HM.HM9.hm().
push()
void com.cliffc.aa.HM.HM9.Worklist.push (Syntax s)
Definition at line 274 of file HM9.java.
 { if( s!=null && !_work.contains(s) ) _work.add(_ary.push(s)); }
References com.cliffc.aa.HM.HM9.Worklist._ary, and com.cliffc.aa.HM.HM9.Worklist._work.
Referenced by com.cliffc.aa.HM.HM9.Ident.add_hm_work(), com.cliffc.aa.HM.HM9.Lambda.add_hm_work(), com.cliffc.aa.HM.HM9.Let.add_hm_work(), com.cliffc.aa.HM.HM9.Apply.add_hm_work(), com.cliffc.aa.HM.HM9.Struct.add_hm_work(), com.cliffc.aa.HM.HM9.Field.add_hm_work(), com.cliffc.aa.HM.HM9.PrimSyn.add_hm_work(), com.cliffc.aa.HM.HM9.Apply.add_val_work(), com.cliffc.aa.HM.HM9.Worklist.addAll(), com.cliffc.aa.HM.HM9.hm(), and com.cliffc.aa.HM.HM9.Syntax.prep_tree_impl().
toString()
String com.cliffc.aa.HM.HM9.Worklist.toString ()
Definition at line 284 of file HM9.java.
 { return _ary.toString(); }
References com.cliffc.aa.HM.HM9.Worklist._ary.
Member Data Documentation
_ary
final Ary<Syntax> com.cliffc.aa.HM.HM9.Worklist._ary = new Ary<>(Syntax.class) private
Definition at line 271 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Worklist.clear(), com.cliffc.aa.HM.HM9.Worklist.len(), com.cliffc.aa.HM.HM9.Worklist.pop(), com.cliffc.aa.HM.HM9.Worklist.push(), and com.cliffc.aa.HM.HM9.Worklist.toString().
_cnt
int com.cliffc.aa.HM.HM9.Worklist._cnt
Definition at line 270 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Worklist.clear(), com.cliffc.aa.HM.HM9.hm(), and com.cliffc.aa.HM.HM9.Worklist.pop().
_work
final HashSet<Syntax> com.cliffc.aa.HM.HM9.Worklist._work = new HashSet<>() private
Definition at line 272 of file HM9.java.
Referenced by com.cliffc.aa.HM.HM9.Worklist.clear(), com.cliffc.aa.HM.HM9.Worklist.has(), com.cliffc.aa.HM.HM9.Worklist.pop(), and com.cliffc.aa.HM.HM9.Worklist.push().
The documentation for this class was generated from the following file:
HM9.java