aa: com.cliffc.aa.HM.HM6.Ident Class Reference
com.cliffc.aa.HM.HM6.Ident Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Ident (String name)
void add_kids (Worklist work)
void add_occurs (Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
T2 lookup (String name)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
Package Attributes
final String _name
VStack _nongen
Syntax _par
T2 _t
Detailed Description
Definition at line 269 of file HM6.java.
Constructor & Destructor Documentation
Ident()
com.cliffc.aa.HM.HM6.Ident.Ident (String name) package
Definition at line 271 of file HM6.java.
 { _name=name; }
References com.cliffc.aa.HM.HM6.Ident._name.
Member Function Documentation
add_kids()
void com.cliffc.aa.HM.HM6.Ident.add_kids (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 288 of file HM6.java.
 { }
add_occurs()
void com.cliffc.aa.HM.HM6.Ident.add_occurs (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 289 of file HM6.java.
{
       T2 t = _par==null ? null : _par.lookup(_name); // Lookup in current env
       if( t==null ) t = PRIMS.get(_name);            // Lookup in prims
       if( t.occurs_in(_par) )                        // Got captured in some parent?
         t.add_deps_work(work);                       // Need to revisit dependent ids
     }
References com.cliffc.aa.HM.HM6.Ident._name, com.cliffc.aa.HM.HM6.Syntax._par, com.cliffc.aa.HM.HM6.T2.add_deps_work(), com.cliffc.aa.HM.HM6.Syntax.lookup(), com.cliffc.aa.HM.HM6.T2.occurs_in(), and com.cliffc.aa.HM.HM6.PRIMS.
debug_find()
T2 com.cliffc.aa.HM.HM6.Syntax.debug_find () package inherited
Definition at line 218 of file HM6.java.
 { return _t.find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM6.Syntax._t, and com.cliffc.aa.HM.HM6.T2.find().
Referenced by com.cliffc.aa.HM.HM6.hm().
find()
T2 com.cliffc.aa.HM.HM6.Syntax.find () package inherited
Definition at line 214 of file HM6.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM6.Syntax._t, and com.cliffc.aa.HM.HM6.T2.find().
Referenced by com.cliffc.aa.HM.HM6.T2._occurs_in(), com.cliffc.aa.HM.HM6.Lambda.add_occurs(), com.cliffc.aa.HM.HM6.Lambda2.add_occurs(), com.cliffc.aa.HM.HM6.Let.add_occurs(), com.cliffc.aa.HM.HM6.Con.hm(), com.cliffc.aa.HM.HM6.Ident.hm(), com.cliffc.aa.HM.HM6.Lambda.hm(), com.cliffc.aa.HM.HM6.Lambda2.hm(), com.cliffc.aa.HM.HM6.Let.hm(), and com.cliffc.aa.HM.HM6.Apply.hm().
hm()
boolean com.cliffc.aa.HM.HM6.Ident.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 275 of file HM6.java.
{
       // A boolean if name is from a Let._body (or PRIM) vs Let._def (or
       // Lambda).  Not helpful, as its only useful at the top-layer.
       // Structural unification requires the 'occurs check' at each internal
       // layer, which can differ from the top-layer.
       //boolean occurs_fresh = _par==null /*from prims*/ || _par.is_fresh(_name,this);
       T2 t = _par==null ? null : _par.lookup(_name); // Lookup in current env
       if( t==null ) t = PRIMS.get(_name);            // Lookup in prims
       if( t==null )
         throw new RuntimeException("Parse error, "+_name+" is undefined");
       return t.fresh_unify(find(),_nongen,work);
     }
References com.cliffc.aa.HM.HM6.Ident._name, com.cliffc.aa.HM.HM6.Syntax._nongen, com.cliffc.aa.HM.HM6.Syntax._par, com.cliffc.aa.HM.HM6.Syntax.find(), com.cliffc.aa.HM.HM6.T2.fresh_unify(), com.cliffc.aa.HM.HM6.Syntax.lookup(), and com.cliffc.aa.HM.HM6.PRIMS.
lookup()
T2 com.cliffc.aa.HM.HM6.Ident.lookup (String name) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 287 of file HM6.java.
 { throw unimpl("should not reach here"); }
more_work()
boolean com.cliffc.aa.HM.HM6.Ident.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 302 of file HM6.java.
 { return more_work_impl(work); }
References com.cliffc.aa.HM.HM6.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM6.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 238 of file HM6.java.
{
       return work.has(this) || !hm(null); // Either on worklist, or no-progress
     }
References com.cliffc.aa.HM.HM6.Worklist.has(), and com.cliffc.aa.HM.HM6.Syntax.hm().
Referenced by com.cliffc.aa.HM.HM6.Con.more_work(), com.cliffc.aa.HM.HM6.Ident.more_work(), com.cliffc.aa.HM.HM6.Lambda.more_work(), com.cliffc.aa.HM.HM6.Lambda2.more_work(), com.cliffc.aa.HM.HM6.Let.more_work(), and com.cliffc.aa.HM.HM6.Apply.more_work().
p()
String com.cliffc.aa.HM.HM6.Syntax.p () inherited
Definition at line 245 of file HM6.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM6.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM6.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 246 of file HM6.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM6.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM6.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM6.Syntax.p1(), com.cliffc.aa.HM.HM6.Syntax.p2(), and com.cliffc.aa.HM.HM6.T2.str().
Referenced by com.cliffc.aa.HM.HM6.Syntax.p(), com.cliffc.aa.HM.HM6.Lambda.p2(), com.cliffc.aa.HM.HM6.Lambda2.p2(), com.cliffc.aa.HM.HM6.Let.p2(), and com.cliffc.aa.HM.HM6.Apply.p2().
p1()
SB com.cliffc.aa.HM.HM6.Ident.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 273 of file HM6.java.
 { return sb.p(_name); }
References com.cliffc.aa.HM.HM6.Ident._name, and com.cliffc.aa.util.SB.p().
Referenced by com.cliffc.aa.HM.HM6.Ident.str().
p2()
SB com.cliffc.aa.HM.HM6.Ident.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 274 of file HM6.java.
 { return sb; }
prep_lookup_deps()
void com.cliffc.aa.HM.HM6.Ident.prep_lookup_deps (Ident id) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 301 of file HM6.java.
 { throw unimpl("should not reach here"); }
prep_tree()
int com.cliffc.aa.HM.HM6.Ident.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 295 of file HM6.java.
{
       prep_tree_impl(par,nongen,work,T2.make_leaf());
       for( Syntax syn = _par; syn!=null; syn = syn._par )
         syn.prep_lookup_deps(this);
       return 1;
     }
References com.cliffc.aa.HM.HM6.Syntax._par, com.cliffc.aa.HM.HM6.T2.make_leaf(), and com.cliffc.aa.HM.HM6.Syntax.prep_tree_impl().
prep_tree_impl()
final void com.cliffc.aa.HM.HM6.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 228 of file HM6.java.
 { _par=par; _t=t; _nongen = nongen; work.push(this); }
References com.cliffc.aa.HM.HM6.Syntax._nongen, com.cliffc.aa.HM.HM6.Syntax._par, com.cliffc.aa.HM.HM6.Syntax._t, and com.cliffc.aa.HM.HM6.Worklist.push().
Referenced by com.cliffc.aa.HM.HM6.Con.prep_tree(), com.cliffc.aa.HM.HM6.Ident.prep_tree(), com.cliffc.aa.HM.HM6.Lambda.prep_tree(), com.cliffc.aa.HM.HM6.Lambda2.prep_tree(), com.cliffc.aa.HM.HM6.Let.prep_tree(), and com.cliffc.aa.HM.HM6.Apply.prep_tree().
str()
SB com.cliffc.aa.HM.HM6.Ident.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM6.Syntax.
Definition at line 272 of file HM6.java.
 { return p1(sb); }
References com.cliffc.aa.HM.HM6.Ident.p1().
toString()
final String com.cliffc.aa.HM.HM6.Syntax.toString () inherited
Definition at line 242 of file HM6.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM6.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_name
final String com.cliffc.aa.HM.HM6.Ident._name package
Definition at line 270 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.Ident.add_occurs(), com.cliffc.aa.HM.HM6.Ident.hm(), com.cliffc.aa.HM.HM6.Ident.Ident(), and com.cliffc.aa.HM.HM6.Ident.p1().
_nongen
VStack com.cliffc.aa.HM.HM6.Syntax._nongen package inherited
Definition at line 212 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.Ident.hm(), and com.cliffc.aa.HM.HM6.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM6.Syntax._par package inherited
Definition at line 211 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.T2._occurs_in(), com.cliffc.aa.HM.HM6.Ident.add_occurs(), com.cliffc.aa.HM.HM6.hm(), com.cliffc.aa.HM.HM6.Ident.hm(), com.cliffc.aa.HM.HM6.Lambda.lookup(), com.cliffc.aa.HM.HM6.Lambda2.lookup(), com.cliffc.aa.HM.HM6.Let.lookup(), com.cliffc.aa.HM.HM6.Apply.lookup(), com.cliffc.aa.HM.HM6.Ident.prep_tree(), and com.cliffc.aa.HM.HM6.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM6.Syntax._t package inherited
Definition at line 213 of file HM6.java.
Referenced by com.cliffc.aa.HM.HM6.Syntax.debug_find(), com.cliffc.aa.HM.HM6.Syntax.find(), com.cliffc.aa.HM.HM6.hm(), com.cliffc.aa.HM.HM6.Syntax.p0(), com.cliffc.aa.HM.HM6.Let.prep_tree(), and com.cliffc.aa.HM.HM6.Syntax.prep_tree_impl().
The documentation for this class was generated from the following file:
HM6.java