aa: com.cliffc.aa.HM.HM1.HMVar Class Reference
com.cliffc.aa.HM.HM1.HMVar Class Reference
Public Member Functions
SB _str (SB sb, VBitSet dups, boolean debug)
String str ()
final String toString ()
Type type ()
Package Functions
HMVar ()
HMVar (Type t)
HMType _fresh (HashSet< HMVar > nongen, HashMap< HMType, HMType > vars)
HMType find ()
HMType fresh (HashSet< HMVar > nongen)
boolean is_top ()
boolean occurs_in (HashSet< HMVar >nongen)
boolean occurs_in (HMType[] args)
boolean occurs_in_type (HMType v)
HMType union (HMType that)
Static Package Functions
static void reset ()
Package Attributes
HMType _u
Private Attributes
Type _t
final int _uid
Static Private Attributes
static int CNT
Detailed Description
Definition at line 205 of file HM1.java.
Constructor & Destructor Documentation
HMVar() [1/2]
com.cliffc.aa.HM.HM1.HMVar.HMVar () package
Definition at line 209 of file HM1.java.
 { this(Type.ANY); }
References com.cliffc.aa.type.Type< T extends Type< T >.ANY.
Referenced by com.cliffc.aa.HM.HM1.HMVar.union().
HMVar() [2/2]
com.cliffc.aa.HM.HM1.HMVar.HMVar (Type t) package
Definition at line 210 of file HM1.java.
 { _uid=CNT++; _t=t; }
References com.cliffc.aa.HM.HM1.HMVar._t, com.cliffc.aa.HM.HM1.HMVar._uid, and com.cliffc.aa.HM.HM1.HMVar.CNT.
Member Function Documentation
_fresh()
HMType com.cliffc.aa.HM.HM1.HMType._fresh (HashSet< HMVar > nongen, HashMap< HMType, HMType > vars) package inherited
Definition at line 171 of file HM1.java.
{
       HMType t2 = find();
       if( t2 instanceof HMVar ) {
         return t2.occurs_in(nongen) //
           ? t2                      // Keep same var
           : vars.computeIfAbsent(t2, e -> new HMVar(((HMVar)t2)._t));
       } else {
         Oper op = (Oper)t2;
         HMType[] args = new HMType[op._args.length];
         for( int i=0; i<args.length; i++ )
           args[i] = op._args[i]._fresh(nongen,vars);
         return new Oper(op._name,args);
       }
     }
References com.cliffc.aa.HM.HM1.Oper._args, com.cliffc.aa.HM.HM1.HMType._fresh(), com.cliffc.aa.HM.HM1.Oper._name, com.cliffc.aa.HM.HM1.HMType.find(), and com.cliffc.aa.HM.HM1.HMType.occurs_in().
Referenced by com.cliffc.aa.HM.HM1.HMType._fresh(), and com.cliffc.aa.HM.HM1.HMType.fresh().
_str()
SB com.cliffc.aa.HM.HM1.HMVar._str (SB sb, VBitSet dups, boolean debug)
Reimplemented from com.cliffc.aa.HM.HM1.HMType.
Definition at line 213 of file HM1.java.
{
       if( _u!=null && !debug ) return _u._str(sb,dups,debug);
       sb.p("v").p(_uid);
       if( dups.tset(_uid) ) return sb.p("$");
       if( _t!=Type.ANY ) _t.str(sb.p(":"),dups,null,false);
       if( _u!=null ) _u._str(sb.p(">>"),dups,debug);
       return sb;
      }
References com.cliffc.aa.HM.HM1.HMType._str(), com.cliffc.aa.HM.HM1.HMVar._t, com.cliffc.aa.HM.HM1.HMType._u, com.cliffc.aa.HM.HM1.HMVar._uid, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.Type< T extends Type< T >.str(), and com.cliffc.aa.util.VBitSet.tset().
find()
HMType com.cliffc.aa.HM.HM1.HMVar.find () package
Reimplemented from com.cliffc.aa.HM.HM1.HMType.
Definition at line 222 of file HM1.java.
{
       HMType u = _u;
       if( u==null ) return this; // Top of union tree
       if( u._u==null ) return u; // One-step from top
       // Classic U-F rollup
       while( u._u!=null ) u = u._u; // Find the top
       HMType x = this;              // Collapse all to top
       while( x._u!=u ) { HMType tmp = x._u; x._u=u; x=tmp;}
       return u;
     }
References com.cliffc.aa.HM.HM1.HMType._u.
Referenced by com.cliffc.aa.HM.HM1.HMVar.union().
fresh()
HMType com.cliffc.aa.HM.HM1.HMType.fresh (HashSet< HMVar > nongen) package inherited
Definition at line 167 of file HM1.java.
{
       HashMap<HMType,HMType> vars = new HashMap<>();
       return _fresh(nongen,vars);
     }
References com.cliffc.aa.HM.HM1.HMType._fresh().
Referenced by com.cliffc.aa.HM.HM1.Ident.hm().
is_top()
boolean com.cliffc.aa.HM.HM1.HMType.is_top () package inherited
Definition at line 165 of file HM1.java.
 { return _u==null; }
References com.cliffc.aa.HM.HM1.HMType._u.
Referenced by com.cliffc.aa.HM.HM1.HMType.occurs_in_type(), and com.cliffc.aa.HM.HM1.HMVar.type().
occurs_in() [1/2]
boolean com.cliffc.aa.HM.HM1.HMType.occurs_in (HashSet< HMVar > nongen) package inherited
Definition at line 186 of file HM1.java.
{
       for( HMVar x : nongen ) if( occurs_in_type(x) ) return true;
       return false;
     }
References com.cliffc.aa.HM.HM1.HMType.occurs_in_type().
Referenced by com.cliffc.aa.HM.HM1.HMType._fresh(), and com.cliffc.aa.HM.HM1.HMType.occurs_in_type().
occurs_in() [2/2]
boolean com.cliffc.aa.HM.HM1.HMType.occurs_in (HMType[] args) package inherited
Definition at line 190 of file HM1.java.
{
       for( HMType x : args ) if( occurs_in_type(x) ) return true;
       return false;
     }
References com.cliffc.aa.HM.HM1.HMType.occurs_in_type().
occurs_in_type()
boolean com.cliffc.aa.HM.HM1.HMType.occurs_in_type (HMType v) package inherited
Definition at line 194 of file HM1.java.
{
       assert is_top();
       HMType y = v.find();
       if( y==this )
         return true;
       if( y instanceof Oper )
         return occurs_in(((Oper)y)._args);
       return false;
     }
References com.cliffc.aa.HM.HM1.HMType.find(), com.cliffc.aa.HM.HM1.HMType.is_top(), and com.cliffc.aa.HM.HM1.HMType.occurs_in().
Referenced by com.cliffc.aa.HM.HM1.HMType.occurs_in(), and com.cliffc.aa.HM.HM1.HMVar.union().
reset()
static void com.cliffc.aa.HM.HM1.HMVar.reset () static package
Definition at line 211 of file HM1.java.
 { CNT=1; }
References com.cliffc.aa.HM.HM1.HMVar.CNT.
Referenced by com.cliffc.aa.HM.HM1.reset().
str()
String com.cliffc.aa.HM.HM1.HMType.str () inherited
Definition at line 163 of file HM1.java.
 { return _str(new SB(),new VBitSet(),false).toString(); }
References com.cliffc.aa.HM.HM1.HMType._str(), and com.cliffc.aa.util.SB.toString().
toString()
final String com.cliffc.aa.HM.HM1.HMType.toString () inherited
Definition at line 162 of file HM1.java.
 { return _str(new SB(),new VBitSet(),true).toString(); }
References com.cliffc.aa.HM.HM1.HMType._str(), and com.cliffc.aa.util.SB.toString().
type()
Type com.cliffc.aa.HM.HM1.HMVar.type ()
Definition at line 212 of file HM1.java.
 { assert is_top(); return _t; }
References com.cliffc.aa.HM.HM1.HMVar._t, and com.cliffc.aa.HM.HM1.HMType.is_top().
union()
HMType com.cliffc.aa.HM.HM1.HMVar.union (HMType that) package
Reimplemented from com.cliffc.aa.HM.HM1.HMType.
Definition at line 232 of file HM1.java.
{
       if( _u!=null ) return find().union(that);
       if( that instanceof HMVar ) that = that.find();
       if( this==that ) return this; // Do nothing
       if( occurs_in_type(that) )
         throw new RuntimeException("recursive unification");
       if( that instanceof HMVar ) {
         HMVar v2 = (HMVar)that;
         v2._t = _t.meet(v2._t);
       }
       else assert _t==Type.ANY; // Else this var is un-MEETd with any Con
       return _u = that;         // Classic U-F union
     }
References com.cliffc.aa.HM.HM1.HMVar._t, com.cliffc.aa.HM.HM1.HMType._u, com.cliffc.aa.type.Type< T extends Type< T >.ANY, com.cliffc.aa.HM.HM1.HMType.find(), com.cliffc.aa.HM.HM1.HMVar.find(), com.cliffc.aa.HM.HM1.HMVar.HMVar(), com.cliffc.aa.type.Type< T extends Type< T >.meet(), com.cliffc.aa.HM.HM1.HMType.occurs_in_type(), and com.cliffc.aa.HM.HM1.HMType.union().
Referenced by com.cliffc.aa.HM.HM1.Let.hm().
Member Data Documentation
_t
Type com.cliffc.aa.HM.HM1.HMVar._t private
Definition at line 206 of file HM1.java.
Referenced by com.cliffc.aa.HM.HM1.HMVar._str(), com.cliffc.aa.HM.HM1.HMVar.HMVar(), com.cliffc.aa.HM.HM1.HMVar.type(), and com.cliffc.aa.HM.HM1.HMVar.union().
_u
HMType com.cliffc.aa.HM.HM1.HMType._u package inherited
Definition at line 159 of file HM1.java.
Referenced by com.cliffc.aa.HM.HM1.HMVar._str(), com.cliffc.aa.HM.HM1.HMVar.find(), com.cliffc.aa.HM.HM1.HMType.is_top(), and com.cliffc.aa.HM.HM1.HMVar.union().
_uid
final int com.cliffc.aa.HM.HM1.HMVar._uid private
Definition at line 207 of file HM1.java.
Referenced by com.cliffc.aa.HM.HM1.HMVar._str(), and com.cliffc.aa.HM.HM1.HMVar.HMVar().
CNT
int com.cliffc.aa.HM.HM1.HMVar.CNT static private
Definition at line 208 of file HM1.java.
Referenced by com.cliffc.aa.HM.HM1.HMVar.HMVar(), and com.cliffc.aa.HM.HM1.HMVar.reset().
The documentation for this class was generated from the following file:
HM1.java