aa: com.cliffc.aa.type.Bits< B extends Bits< B >.Iter Class Reference
com.cliffc.aa.type.Bits< B extends Bits< B >.Iter Class Reference
Public Member Functions
boolean hasNext ()
Integer next ()
Package Attributes
int _i =-1
Detailed Description
Definition at line 524 of file Bits.java.
Member Function Documentation
hasNext()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.Iter.hasNext ()
Definition at line 526 of file Bits.java.
{
       if( _bits==null )
         if( _i==-1 ) { _i=0; return true; } else return false;
       int idx;
       while( (idx=idx(++_i)) < _bits.length )
         if( (_bits[idx]&mask(_i)) != 0 )
           return true;
       return false;
     }
References com.cliffc.aa.type.Bits< B extends Bits< B >._bits, com.cliffc.aa.type.Bits< B extends Bits< B >.Iter._i, com.cliffc.aa.type.Bits< B extends Bits< B >.idx(), and com.cliffc.aa.type.Bits< B extends Bits< B >.mask().
next()
Integer com.cliffc.aa.type.Bits< B extends Bits< B >.Iter.next ()
Definition at line 535 of file Bits.java.
{
       if( _bits==null ) return Math.abs(_con);
       if( idx(_i) < _bits.length ) return _i;
       throw new java.util.NoSuchElementException();
     }
References com.cliffc.aa.type.Bits< B extends Bits< B >._bits, com.cliffc.aa.type.Bits< B extends Bits< B >._con, com.cliffc.aa.type.Bits< B extends Bits< B >.Iter._i, and com.cliffc.aa.type.Bits< B extends Bits< B >.idx().
Member Data Documentation
_i
int com.cliffc.aa.type.Bits< B extends Bits< B >.Iter._i =-1 package
Definition at line 525 of file Bits.java.
Referenced by com.cliffc.aa.type.Bits< B extends Bits< B >.Iter.hasNext(), and com.cliffc.aa.type.Bits< B extends Bits< B >.Iter.next().
The documentation for this class was generated from the following file:
Bits.java