aa: com.cliffc.aa.HM.HM5.Lambda2 Class Reference
com.cliffc.aa.HM.HM5.Lambda2 Class Reference
Public Member Functions
String p ()
final String toString ()
Package Functions
Lambda2 (String arg0, String arg1, Syntax body)
void add_kids (Worklist work)
void add_occurs (Worklist work)
T2 debug_find ()
T2 find ()
boolean hm (Worklist work)
T2 lookup (String name)
boolean more_work (Worklist work)
final boolean more_work_impl (Worklist work)
final SB p0 (SB sb, VBitSet dups)
SB p1 (SB sb)
SB p2 (SB sb, VBitSet dups)
void prep_lookup_deps (Ident id)
int prep_tree (Syntax par, VStack nongen, Worklist work)
final void prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t)
SB str (SB sb)
T2 targ0 ()
T2 targ1 ()
Package Attributes
final String _arg0
final String _arg1
final Syntax _body
VStack _nongen
Syntax _par
T2 _t
T2 _targ0
T2 _targ1
Detailed Description
Definition at line 255 of file HM5.java.
Constructor & Destructor Documentation
Lambda2()
com.cliffc.aa.HM.HM5.Lambda2.Lambda2 (String arg0, String arg1, Syntax body) package
Definition at line 260 of file HM5.java.
 { _arg0=arg0; _arg1 = arg1; _body=body; _targ0 = T2.make_leaf(); _targ1 = T2.make_leaf(); }
References com.cliffc.aa.HM.HM5.Lambda2._arg0, com.cliffc.aa.HM.HM5.Lambda2._arg1, com.cliffc.aa.HM.HM5.Lambda2._body, com.cliffc.aa.HM.HM5.Lambda2._targ0, com.cliffc.aa.HM.HM5.Lambda2._targ1, and com.cliffc.aa.HM.HM5.T2.make_leaf().
Member Function Documentation
add_kids()
void com.cliffc.aa.HM.HM5.Lambda2.add_kids (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 283 of file HM5.java.
 { work.push(_body); }
References com.cliffc.aa.HM.HM5.Lambda2._body, and com.cliffc.aa.HM.HM5.Worklist.push().
add_occurs()
void com.cliffc.aa.HM.HM5.Lambda2.add_occurs (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 284 of file HM5.java.
{
       if( targ0().occurs_in_type(find()) ) work.addAll(_targ0._deps);
       if( targ1().occurs_in_type(find()) ) work.addAll(_targ1._deps);
     }
References com.cliffc.aa.HM.HM5.T2._deps, com.cliffc.aa.HM.HM5.Lambda2._targ0, com.cliffc.aa.HM.HM5.Lambda2._targ1, com.cliffc.aa.HM.HM5.Worklist.addAll(), com.cliffc.aa.HM.HM5.Syntax.find(), com.cliffc.aa.HM.HM5.Lambda2.targ0(), and com.cliffc.aa.HM.HM5.Lambda2.targ1().
debug_find()
T2 com.cliffc.aa.HM.HM5.Syntax.debug_find () package inherited
Definition at line 127 of file HM5.java.
 { return _t.find(); } // Find, without the roll-up
References com.cliffc.aa.HM.HM5.Syntax._t, and com.cliffc.aa.HM.HM5.T2.find().
Referenced by com.cliffc.aa.HM.HM5.hm().
find()
T2 com.cliffc.aa.HM.HM5.Syntax.find () package inherited
Definition at line 123 of file HM5.java.
               {                 // U-F find
       T2 t = _t.find();
       return t==_t ? t : (_t=t);
     }
References com.cliffc.aa.HM.HM5.Syntax._t, and com.cliffc.aa.HM.HM5.T2.find().
Referenced by com.cliffc.aa.HM.HM5.T2._occurs_in(), com.cliffc.aa.HM.HM5.Lambda.add_occurs(), com.cliffc.aa.HM.HM5.Lambda2.add_occurs(), com.cliffc.aa.HM.HM5.Let.add_occurs(), com.cliffc.aa.HM.HM5.Con.hm(), com.cliffc.aa.HM.HM5.Ident.hm(), com.cliffc.aa.HM.HM5.Lambda.hm(), com.cliffc.aa.HM.HM5.Lambda2.hm(), com.cliffc.aa.HM.HM5.Let.hm(), and com.cliffc.aa.HM.HM5.Apply.hm().
hm()
boolean com.cliffc.aa.HM.HM5.Lambda2.hm (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 266 of file HM5.java.
{
       // The normal lambda work
       T2 old = find();
       if(  old.is_fun() &&      // Already a function?  Compare-by-parts
           !old.args(0).unify(targ0()     ,work) &&
           !old.args(1).unify(targ1()     ,work) &&
           !old.args(2).unify(_body.find(),work) )
         return false;
       // Make a new T2 for progress
       T2 fun = T2.make_fun(targ0(),targ1(),_body.find());
       return old.unify(fun,work);
     }
References com.cliffc.aa.HM.HM5.Lambda2._body, com.cliffc.aa.HM.HM5.T2.args(), com.cliffc.aa.HM.HM5.Syntax.find(), com.cliffc.aa.HM.HM5.T2.is_fun(), com.cliffc.aa.HM.HM5.T2.make_fun(), com.cliffc.aa.HM.HM5.Lambda2.targ0(), com.cliffc.aa.HM.HM5.Lambda2.targ1(), and com.cliffc.aa.HM.HM5.T2.unify().
lookup()
T2 com.cliffc.aa.HM.HM5.Lambda2.lookup (String name) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 278 of file HM5.java.
{
       if( Util.eq(_arg0,name) ) return targ0();
       if( Util.eq(_arg1,name) ) return targ1();
       return _par==null ? null : _par.lookup(name);
     }
References com.cliffc.aa.HM.HM5.Lambda2._arg0, com.cliffc.aa.HM.HM5.Lambda2._arg1, com.cliffc.aa.HM.HM5.Syntax._par, com.cliffc.aa.util.Util.eq(), com.cliffc.aa.HM.HM5.Syntax.lookup(), com.cliffc.aa.HM.HM5.Lambda2.targ0(), and com.cliffc.aa.HM.HM5.Lambda2.targ1().
more_work()
boolean com.cliffc.aa.HM.HM5.Lambda2.more_work (Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 298 of file HM5.java.
{
       if( !more_work_impl(work) ) return false;
       return _body.more_work(work);
     }
References com.cliffc.aa.HM.HM5.Lambda2._body, com.cliffc.aa.HM.HM5.Syntax.more_work(), and com.cliffc.aa.HM.HM5.Syntax.more_work_impl().
more_work_impl()
final boolean com.cliffc.aa.HM.HM5.Syntax.more_work_impl (Worklist work) package inherited
Definition at line 147 of file HM5.java.
{
       return work.has(this) || !hm(null); // Either on worklist, or no-progress
     }
References com.cliffc.aa.HM.HM5.Worklist.has(), and com.cliffc.aa.HM.HM5.Syntax.hm().
Referenced by com.cliffc.aa.HM.HM5.Con.more_work(), com.cliffc.aa.HM.HM5.Ident.more_work(), com.cliffc.aa.HM.HM5.Lambda.more_work(), com.cliffc.aa.HM.HM5.Lambda2.more_work(), com.cliffc.aa.HM.HM5.Let.more_work(), and com.cliffc.aa.HM.HM5.Apply.more_work().
p()
String com.cliffc.aa.HM.HM5.Syntax.p () inherited
Definition at line 154 of file HM5.java.
 { return p0(new SB(), new VBitSet()).toString(); }
References com.cliffc.aa.HM.HM5.Syntax.p0(), and com.cliffc.aa.util.SB.toString().
p0()
final SB com.cliffc.aa.HM.HM5.Syntax.p0 (SB sb, VBitSet dups) package inherited
Definition at line 155 of file HM5.java.
{
       _t.get_dups(dups);
       _t.str(p1(sb.i()).p(" "), new VBitSet(),dups).nl();
       return p2(sb.ii(1),dups).di(1);
     }
References com.cliffc.aa.HM.HM5.Syntax._t, com.cliffc.aa.util.SB.di(), com.cliffc.aa.HM.HM5.T2.get_dups(), com.cliffc.aa.util.SB.i(), com.cliffc.aa.util.SB.ii(), com.cliffc.aa.util.SB.nl(), com.cliffc.aa.util.SB.p(), com.cliffc.aa.HM.HM5.Syntax.p1(), com.cliffc.aa.HM.HM5.Syntax.p2(), and com.cliffc.aa.HM.HM5.T2.str().
Referenced by com.cliffc.aa.HM.HM5.Syntax.p(), com.cliffc.aa.HM.HM5.Lambda.p2(), com.cliffc.aa.HM.HM5.Lambda2.p2(), com.cliffc.aa.HM.HM5.Let.p2(), and com.cliffc.aa.HM.HM5.Apply.p2().
p1()
SB com.cliffc.aa.HM.HM5.Lambda2.p1 (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 262 of file HM5.java.
 { return sb.p("{ ").p(_arg0).p(" ").p(_arg1).p(" -> ... } "); }
References com.cliffc.aa.HM.HM5.Lambda2._arg0, com.cliffc.aa.HM.HM5.Lambda2._arg1, and com.cliffc.aa.util.SB.p().
p2()
SB com.cliffc.aa.HM.HM5.Lambda2.p2 (SB sb, VBitSet dups) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 263 of file HM5.java.
 { return _body.p0(sb,dups); }
References com.cliffc.aa.HM.HM5.Lambda2._body, and com.cliffc.aa.HM.HM5.Syntax.p0().
prep_lookup_deps()
void com.cliffc.aa.HM.HM5.Lambda2.prep_lookup_deps (Ident id) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 294 of file HM5.java.
{
       if( Util.eq(id._name,_arg0) ) _targ0.push_update(id);
       if( Util.eq(id._name,_arg1) ) _targ1.push_update(id);
     }
References com.cliffc.aa.HM.HM5.Lambda2._arg0, com.cliffc.aa.HM.HM5.Lambda2._arg1, com.cliffc.aa.HM.HM5.Lambda2._targ0, com.cliffc.aa.HM.HM5.Lambda2._targ1, com.cliffc.aa.util.Util.eq(), and com.cliffc.aa.HM.HM5.T2.push_update().
prep_tree()
int com.cliffc.aa.HM.HM5.Lambda2.prep_tree (Syntax par, VStack nongen, Worklist work) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 288 of file HM5.java.
{
       prep_tree_impl(par,nongen,work,T2.make_leaf());
       VStack vs0 = new VStack(nongen,_targ0);
       VStack vs1 = new VStack(vs0   ,_targ1);
       return _body.prep_tree(this,vs1,work) + 1;
     }
References com.cliffc.aa.HM.HM5.Lambda2._body, com.cliffc.aa.HM.HM5.Lambda2._targ0, com.cliffc.aa.HM.HM5.Lambda2._targ1, com.cliffc.aa.HM.HM5.T2.make_leaf(), com.cliffc.aa.HM.HM5.Syntax.prep_tree(), and com.cliffc.aa.HM.HM5.Syntax.prep_tree_impl().
prep_tree_impl()
final void com.cliffc.aa.HM.HM5.Syntax.prep_tree_impl (Syntax par, VStack nongen, Worklist work, T2 t) package inherited
Definition at line 137 of file HM5.java.
 { _par=par; _t=t; _nongen = nongen; work.push(this); }
References com.cliffc.aa.HM.HM5.Syntax._nongen, com.cliffc.aa.HM.HM5.Syntax._par, com.cliffc.aa.HM.HM5.Syntax._t, and com.cliffc.aa.HM.HM5.Worklist.push().
Referenced by com.cliffc.aa.HM.HM5.Con.prep_tree(), com.cliffc.aa.HM.HM5.Ident.prep_tree(), com.cliffc.aa.HM.HM5.Lambda.prep_tree(), com.cliffc.aa.HM.HM5.Lambda2.prep_tree(), com.cliffc.aa.HM.HM5.Let.prep_tree(), and com.cliffc.aa.HM.HM5.Apply.prep_tree().
str()
SB com.cliffc.aa.HM.HM5.Lambda2.str (SB sb) package
Reimplemented from com.cliffc.aa.HM.HM5.Syntax.
Definition at line 261 of file HM5.java.
 { return _body.str(sb.p("{ ").p(_arg0).p(" ").p(_arg1).p(" -> ")).p(" }"); }
References com.cliffc.aa.HM.HM5.Lambda2._arg0, com.cliffc.aa.HM.HM5.Lambda2._arg1, com.cliffc.aa.HM.HM5.Lambda2._body, com.cliffc.aa.util.SB.p(), and com.cliffc.aa.HM.HM5.Syntax.str().
targ0()
T2 com.cliffc.aa.HM.HM5.Lambda2.targ0 () package
Definition at line 264 of file HM5.java.
 { T2 targ = _targ0.find(); return targ==_targ0 ? targ : (_targ0=targ); }
References com.cliffc.aa.HM.HM5.Lambda2._targ0, and com.cliffc.aa.HM.HM5.T2.find().
Referenced by com.cliffc.aa.HM.HM5.Lambda2.add_occurs(), com.cliffc.aa.HM.HM5.Lambda2.hm(), and com.cliffc.aa.HM.HM5.Lambda2.lookup().
targ1()
T2 com.cliffc.aa.HM.HM5.Lambda2.targ1 () package
Definition at line 265 of file HM5.java.
 { T2 targ = _targ1.find(); return targ==_targ1 ? targ : (_targ1=targ); }
References com.cliffc.aa.HM.HM5.Lambda2._targ1, and com.cliffc.aa.HM.HM5.T2.find().
Referenced by com.cliffc.aa.HM.HM5.Lambda2.add_occurs(), com.cliffc.aa.HM.HM5.Lambda2.hm(), and com.cliffc.aa.HM.HM5.Lambda2.lookup().
toString()
final String com.cliffc.aa.HM.HM5.Syntax.toString () inherited
Definition at line 151 of file HM5.java.
 { return str(new SB()).toString(); }
References com.cliffc.aa.HM.HM5.Syntax.str(), and com.cliffc.aa.util.SB.toString().
Member Data Documentation
_arg0
final String com.cliffc.aa.HM.HM5.Lambda2._arg0 package
Definition at line 256 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Lambda2.Lambda2(), com.cliffc.aa.HM.HM5.Lambda2.lookup(), com.cliffc.aa.HM.HM5.Lambda2.p1(), com.cliffc.aa.HM.HM5.Lambda2.prep_lookup_deps(), and com.cliffc.aa.HM.HM5.Lambda2.str().
_arg1
final String com.cliffc.aa.HM.HM5.Lambda2._arg1 package
Definition at line 256 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Lambda2.Lambda2(), com.cliffc.aa.HM.HM5.Lambda2.lookup(), com.cliffc.aa.HM.HM5.Lambda2.p1(), com.cliffc.aa.HM.HM5.Lambda2.prep_lookup_deps(), and com.cliffc.aa.HM.HM5.Lambda2.str().
_body
final Syntax com.cliffc.aa.HM.HM5.Lambda2._body package
Definition at line 257 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Lambda2.add_kids(), com.cliffc.aa.HM.HM5.Lambda2.hm(), com.cliffc.aa.HM.HM5.Lambda2.Lambda2(), com.cliffc.aa.HM.HM5.Lambda2.more_work(), com.cliffc.aa.HM.HM5.Lambda2.p2(), com.cliffc.aa.HM.HM5.Lambda2.prep_tree(), and com.cliffc.aa.HM.HM5.Lambda2.str().
_nongen
VStack com.cliffc.aa.HM.HM5.Syntax._nongen package inherited
Definition at line 121 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Ident.hm(), and com.cliffc.aa.HM.HM5.Syntax.prep_tree_impl().
_par
Syntax com.cliffc.aa.HM.HM5.Syntax._par package inherited
Definition at line 120 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.T2._occurs_in(), com.cliffc.aa.HM.HM5.Ident.add_occurs(), com.cliffc.aa.HM.HM5.hm(), com.cliffc.aa.HM.HM5.Ident.hm(), com.cliffc.aa.HM.HM5.Lambda.lookup(), com.cliffc.aa.HM.HM5.Lambda2.lookup(), com.cliffc.aa.HM.HM5.Let.lookup(), com.cliffc.aa.HM.HM5.Apply.lookup(), com.cliffc.aa.HM.HM5.Ident.prep_tree(), and com.cliffc.aa.HM.HM5.Syntax.prep_tree_impl().
_t
T2 com.cliffc.aa.HM.HM5.Syntax._t package inherited
Definition at line 122 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Syntax.debug_find(), com.cliffc.aa.HM.HM5.Syntax.find(), com.cliffc.aa.HM.HM5.hm(), com.cliffc.aa.HM.HM5.Syntax.p0(), com.cliffc.aa.HM.HM5.Let.prep_tree(), and com.cliffc.aa.HM.HM5.Syntax.prep_tree_impl().
_targ0
T2 com.cliffc.aa.HM.HM5.Lambda2._targ0 package
Definition at line 258 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Lambda2.add_occurs(), com.cliffc.aa.HM.HM5.Lambda2.Lambda2(), com.cliffc.aa.HM.HM5.Lambda2.prep_lookup_deps(), com.cliffc.aa.HM.HM5.Lambda2.prep_tree(), and com.cliffc.aa.HM.HM5.Lambda2.targ0().
_targ1
T2 com.cliffc.aa.HM.HM5.Lambda2._targ1 package
Definition at line 259 of file HM5.java.
Referenced by com.cliffc.aa.HM.HM5.Lambda2.add_occurs(), com.cliffc.aa.HM.HM5.Lambda2.Lambda2(), com.cliffc.aa.HM.HM5.Lambda2.prep_lookup_deps(), com.cliffc.aa.HM.HM5.Lambda2.prep_tree(), and com.cliffc.aa.HM.HM5.Lambda2.targ1().
The documentation for this class was generated from the following file:
HM5.java