aa: com.cliffc.aa.type.Bits< B extends Bits< B > Class Template Reference
com.cliffc.aa.type.Bits< B extends Bits< B > Class Template Reference abstract
Classes
class Iter
class Tree
Public Member Functions
int abit ()
boolean above_center ()
abstract B ALL ()
abstract B ANY ()
int bitCount ()
IBitSet bitset ()
B clear (int bit)
B dual ()
abstract B EMPTY ()
boolean equals (Object o)
int getbit ()
int hashCode ()
boolean is_con ()
boolean is_empty ()
boolean is_nil ()
boolean isa (B bs)
Iterator< Integer > iterator ()
Bits< B > join (Bits< B > bs)
final B make (int... bits)
int max ()
B meet (final B bs)
B meet_nil ()
TypeObj oob (TypeObj t)
boolean overlaps (Bits< B > bs)
B set (int bit)
SB str (SB sb)
B strip_nil ()
Bits< B > subtract (Bits< B > bs)
boolean test (int i)
boolean test_recur (int i)
String toString ()
Package Functions
void init (int con, long[] bits)
final B make (int bit)
abstract B make_impl (int con, long[] bits)
boolean may_nil ()
B not_nil ()
abstract Tree< B > tree ()
Package Attributes
long[] _bits
int _con
int _hash
Private Member Functions
boolean check ()
B make (boolean any, long[] bits)
Static Private Member Functions
static void and (long[] bits, long con)
static long[] bits (int b)
static boolean check_multi_bits (long[] bits)
static int idx (long i)
static void join (Tree tree, long[] bits0, long[] bits1, long[] bits2)
static long mask (long i)
static void or (long[] bits, long con)
static boolean test (long[] bits, int i)
Detailed Description
Definition at line 61 of file Bits.java.
Member Function Documentation
abit()
int com.cliffc.aa.type.Bits< B extends Bits< B >.abit ()
Definition at line 203 of file Bits.java.
 { return _bits==null&&_con!=0 ? _con : -1; }
Referenced by com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.IntrinsicNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.type.TypeRPC.is_con(), com.cliffc.aa.type.TypeFunPtr.is_con(), com.cliffc.aa.type.TypeMemPtr.is_display_ptr(), com.cliffc.aa.type.TypeFunPtr.is_forward_ref(), com.cliffc.aa.node.CallNode.least_cost(), com.cliffc.aa.type.TypeFunPtr.may_be_con(), com.cliffc.aa.node.FunNode.names(), and com.cliffc.aa.node.FunNode.split_size().
above_center()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.above_center ()
Definition at line 204 of file Bits.java.
 { return _con<0; }
Referenced by com.cliffc.aa.type.TypeStruct._dull(), com.cliffc.aa.type.TypeRPC.above_center(), com.cliffc.aa.type.TypeFunPtr.above_center(), com.cliffc.aa.type.TypeMemPtr.above_center(), com.cliffc.aa.node.CallEpiNode.check_and_wire(), com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.node.CEProjNode.good_call(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.type.TypeMem.ld(), com.cliffc.aa.node.CallNode.least_cost(), com.cliffc.aa.node.CallNode.live(), com.cliffc.aa.node.CallEpiNode.live_use(), com.cliffc.aa.node.CallNode.live_use_call(), com.cliffc.aa.type.Bits< BitsRPC >.meet(), com.cliffc.aa.type.Bits< BitsRPC >.meet_nil(), com.cliffc.aa.type.TypeFunPtr.must_nil(), com.cliffc.aa.type.Bits< BitsRPC >.not_nil(), com.cliffc.aa.type.Bits< BitsRPC >.oob(), com.cliffc.aa.GVNGCM.remove_ambi(), com.cliffc.aa.type.TypeMemPtr.simple_ptr(), com.cliffc.aa.type.Bits< BitsRPC >.str(), com.cliffc.aa.node.CallEpiNode.value(), and com.cliffc.aa.node.CallNode.value().
ALL()
abstract B com.cliffc.aa.type.Bits< B extends Bits< B >.ALL () abstract
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.meet().
and()
static void com.cliffc.aa.type.Bits< B extends Bits< B >.and (long[] bits, long con) static private
Definition at line 282 of file Bits.java.
 { bits[idx(con)] &= ~mask(con); }
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.clear(), and com.cliffc.aa.type.Bits< BitsRPC >.not_nil().
ANY()
abstract B com.cliffc.aa.type.Bits< B extends Bits< B >.ANY () abstract
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.meet().
bitCount()
int com.cliffc.aa.type.Bits< B extends Bits< B >.bitCount ()
Definition at line 113 of file Bits.java.
{
     if( _bits==null ) return _con==0 ? 0 : 1;
     int sum=0;
     for( long b : _bits )
       sum += Long.bitCount(b);
     return sum;
   }
Referenced by com.cliffc.aa.node.CallNode.all_fcns_wired(), and com.cliffc.aa.node.CallNode.least_cost().
bits()
static long [] com.cliffc.aa.type.Bits< B extends Bits< B >.bits (int b) static private
Definition at line 283 of file Bits.java.
 { return new long[idx(b)+1]; }
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.and(), com.cliffc.aa.type.Bits< BitsRPC >.check_multi_bits(), com.cliffc.aa.type.Bits< BitsRPC >.init(), com.cliffc.aa.type.Bits< BitsRPC >.make(), com.cliffc.aa.type.Bits< BitsRPC >.meet(), com.cliffc.aa.type.Bits< BitsRPC >.meet_nil(), com.cliffc.aa.type.Bits< BitsRPC >.or(), com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.plus_kids(), and com.cliffc.aa.type.Bits< BitsRPC >.test().
bitset()
IBitSet com.cliffc.aa.type.Bits< B extends Bits< B >.bitset ()
Definition at line 391 of file Bits.java.
{
     IBitSet bs = new IBitSet();
     for( int alias : this )
       bs.set(alias);
     return bs;
   }
check()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.check () private
Definition at line 89 of file Bits.java.
{
     if( _bits==null ) return true;  // Must be a single bit#
     if( _con != 1 && _con != -1 ) return false;
     if( _bits.length==0 ) return false;  // Empty bits replaced by a con
     if( _bits.length==1 && _bits[0]== 0 ) return false; // NO bits is bad, use EMPTY instead
     if( _bits[_bits.length-1]==0 ) return false; // Array is "tight"
     if( _bits.length==1 && _bits[0]==1 ) return true; // NIL
     // No set bit has a parent bit set, because the parent overrides
     Tree<B> tree = tree();
     for( int i : this )
       while( (i = tree.parent(i)) != 0 )
         if( test(i) )
           return false;
     // For efficiency, 1 bit set uses 'con' instead of 'bits'
     return check_multi_bits(_bits); // Found multiple bits
   }
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.init().
check_multi_bits()
static boolean com.cliffc.aa.type.Bits< B extends Bits< B >.check_multi_bits (long[] bits) static private
Definition at line 105 of file Bits.java.
{
     int len = bits.length;
     long b = bits[len-1];             // Last word
     if( (b & (b-1))!=0 ) return true; // Last word has multiple bits
     // Check multiple bits spread over multiple words
     for( int i=0; i<len-1; i++ ) if( bits[i] != 0 ) return true;
     return false;                // Found a single bit in last word
   }
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.check(), and com.cliffc.aa.type.Bits< BitsRPC >.make().
clear()
B com.cliffc.aa.type.Bits< B extends Bits< B >.clear (int bit)
Definition at line 255 of file Bits.java.
{
     if( !test(bit) ) return (B)this;
     if( _bits == null ) return EMPTY();
     long[] bs = _bits.clone();
     and(bs,bit);
     return make(_con==-1,bs);
   }
Referenced by com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.Env.close_display(), com.cliffc.aa.HM.HM9.NotNil.hm(), com.cliffc.aa.node.NewObjNode.promote_forward(), com.cliffc.aa.type.Bits< BitsRPC >.subtract(), and com.cliffc.aa.HM.HM.T2.unify_nil().
dual()
B com.cliffc.aa.type.Bits< B extends Bits< B >.dual ()
Definition at line 368 of file Bits.java.
 { return make_impl(-_con,_bits); }
Referenced by com.cliffc.aa.HM.HM8.Field.hm(), com.cliffc.aa.node.StoreNode.ideal_grow(), com.cliffc.aa.type.Bits< BitsRPC >.join(), com.cliffc.aa.type.TypeMem.ld(), com.cliffc.aa.type.TypeRPC.meet_nil(), com.cliffc.aa.type.TypeFunPtr.meet_nil(), com.cliffc.aa.type.TypeMemPtr.oop_deep_impl(), com.cliffc.aa.type.TypeFunPtr.rdual(), com.cliffc.aa.type.TypeMemPtr.rdual(), com.cliffc.aa.type.TestApprox.testApprox8(), com.cliffc.aa.node.UnresolvedNode.value(), com.cliffc.aa.node.CallNode.value(), com.cliffc.aa.HM.HM9.T2.walk_types_in(), com.cliffc.aa.HM.HM.T2.walk_types_in(), com.cliffc.aa.type.TypeRPC.xdual(), com.cliffc.aa.type.TypeFunPtr.xdual(), and com.cliffc.aa.type.TypeMemPtr.xdual().
EMPTY()
abstract B com.cliffc.aa.type.Bits< B extends Bits< B >.EMPTY () abstract
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.clear(), and com.cliffc.aa.type.Bits< BitsRPC >.set().
equals()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.equals (Object o)
Definition at line 121 of file Bits.java.
{
     if( this==o ) return true;
     if( !(o instanceof Bits) ) return false;
     Bits bs = (Bits)o;
     if( _con != bs._con || _hash != bs._hash ) return false;
     if( _bits == bs._bits ) return true;
     if( _bits ==null || bs._bits==null ) return false;
     if( _bits.length != bs._bits.length ) return false;
     for( int i=0; i<_bits.length; i++ )
       if( _bits[i]!=bs._bits[i] ) return false;
     return true;
   }
getbit()
int com.cliffc.aa.type.Bits< B extends Bits< B >.getbit ()
Definition at line 202 of file Bits.java.
 { assert _bits==null && _con!=0; return _con; }
Referenced by com.cliffc.aa.type.TypeMemPtr.depth(), com.cliffc.aa.type.TypeFunPtr.fidx(), com.cliffc.aa.type.TypeMemPtr.getbit(), com.cliffc.aa.HM.HM8.Struct.hm(), and com.cliffc.aa.type.TypeRPC.rpc().
hashCode()
int com.cliffc.aa.type.Bits< B extends Bits< B >.hashCode ()
Definition at line 120 of file Bits.java.
 { return _hash; }
idx()
static int com.cliffc.aa.type.Bits< B extends Bits< B >.idx (long i) static private
Definition at line 199 of file Bits.java.
 { return (int)(i>>6); }
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.and(), com.cliffc.aa.type.Bits< BitsRPC >.bits(), com.cliffc.aa.type.Bits< B extends Bits< B >.Iter.hasNext(), com.cliffc.aa.type.Bits< B extends Bits< B >.Tree< B extends Bits< B >.is_parent(), com.cliffc.aa.type.Bits< B extends Bits< B >.Iter.next(), com.cliffc.aa.type.Bits< BitsRPC >.or(), com.cliffc.aa.type.Bits< BitsRPC >.str(), and com.cliffc.aa.type.Bits< BitsRPC >.test().
init()
void com.cliffc.aa.type.Bits< B extends Bits< B >.init (int con, long[] bits) package
Definition at line 80 of file Bits.java.
{
     _con = con;
     _bits=bits;
     long sum=_con;
     if( _bits != null ) for( long l : _bits ) sum += l;
     _hash = (int)((sum>>32)+sum);
     if( _hash==0 ) _hash=1;
     assert check();
   }
Referenced by com.cliffc.aa.type.BitsFun.make_impl(), com.cliffc.aa.type.BitsRPC.make_impl(), and com.cliffc.aa.type.BitsAlias.make_impl().
is_con()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.is_con ()
Definition at line 206 of file Bits.java.
 { return is_nil() || is_empty(); }
Referenced by com.cliffc.aa.type.TypeFunPtr.above_center().
is_empty()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.is_empty ()
Definition at line 207 of file Bits.java.
 { return _bits==null && _con==0; }
Referenced by com.cliffc.aa.node.CallNode._ideal_grow(), com.cliffc.aa.node.MemSplitNode.add_alias(), com.cliffc.aa.node.CallNode.err(), com.cliffc.aa.type.Bits< BitsRPC >.is_con(), and com.cliffc.aa.type.Bits< BitsRPC >.meet().
is_nil()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.is_nil ()
Definition at line 208 of file Bits.java.
 { return _bits!=null && _bits.length==1 && _bits[0]==1; }
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.is_con().
isa()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.isa (B bs)
Definition at line 372 of file Bits.java.
 { return meet(bs) == bs; }
Referenced by com.cliffc.aa.node.MemSplitNode.add_alias(), com.cliffc.aa.type.TypeMemPtr.ax_meet_nil(), com.cliffc.aa.node.MemJoinNode.can_bypass(), com.cliffc.aa.type.TypeRPC.meet_nil(), com.cliffc.aa.type.TypeFunPtr.meet_nil(), com.cliffc.aa.type.TypeMemPtr.meet_nil(), com.cliffc.aa.type.TypeMemPtr.oop_deep_impl(), and com.cliffc.aa.type.TypeMemPtr.widen().
iterator()
Iterator<Integer> com.cliffc.aa.type.Bits< B extends Bits< B >.iterator ()
Returns
an iterator
Definition at line 523 of file Bits.java.
 { return new Iter(); }
join() [1/2]
Bits<B> com.cliffc.aa.type.Bits< B extends Bits< B >.join (Bits< B > bs)
Definition at line 370 of file Bits.java.
 { return dual().meet(bs.dual()).dual(); }
join() [2/2]
static void com.cliffc.aa.type.Bits< B extends Bits< B >.join (Tree tree, long[] bits0, long[] bits1, long[] bits2) static private
Definition at line 349 of file Bits.java.
{
     // If a 'parent' bit is set, then no need to have any child bits set.
     for( int i=0; i<bits0.length; i++ ) { // For all words
       long l = bits0[i];
       if( l!=0 ) {
         // TODO: Use Long.numberOfTrailingZeros (or LeadingZeros probably) to
         // do this only once-per-set-bit.
         for( int j=0; j<64; j++ ) // For all bits in word
           if( (mask(j)&l) != 0 ) {
             for( int par = (i<<6)+j; par!=0; par = tree.parent(par) ) // Walk parent chain
               if( test(bits1,par) )                // If parent set
                 { bits2[i]|=mask(j); break; }      // then set kid
           }
       }
     }
   }
Referenced by com.cliffc.aa.node.LoadNode._find_previous_store_call(), com.cliffc.aa.node.MemSplitNode.add_alias(), com.cliffc.aa.node.LoadNode.find_previous_store(), and com.cliffc.aa.type.Bits< BitsRPC >.meet().
make() [1/3]
B com.cliffc.aa.type.Bits< B extends Bits< B >.make (boolean any, long[] bits) private
Definition at line 154 of file Bits.java.
{
     // If a 'parent' bit is set, then no need to have any child bits set.
     Tree<B> tree = tree();
     // TODO: Run this loop backwards, avoids most tree-walks; lowers O(n log n) to O(n).
     for( int i=0; i<bits.length; i++ ) { // For all words
       long l = bits[i];
       if( l!=0 ) {
         for( int j=0; j<64; j++ ) // For all bits in word
           if( (mask(j)&l) != 0 ) {
             int par = (i<<6)+j; // Kid index
             while( (par = tree.parent(par)) != 0 ) // Walk parent chain
               if( test(bits,par) )                 // If parent set
                 { bits[i]&=~mask(j); break; }      // then clear kid
           }
       }
     }
     // Remove any trailing empty words
     int len = bits.length;
     while( len > 1 && bits[len-1]==0 ) len--;
     if( bits.length != len ) bits = Arrays.copyOf(bits,len);
     // Check for a single bit or NO bits
     if( check_multi_bits(bits) ) return make_impl(any ? -1 : 1,bits);
     // Special check for +/-0
     if( len==1 && bits[0]==1 ) return make_impl(any ? -1 : 1,bits);
     // Empty is self-dual, ignores 'any'
     if( len==1 && bits[0]==0 ) return make_impl(0,null);
     // Single bit
     int bnum0 = 63 - Long.numberOfLeadingZeros(bits[len-1]);
     int bnum = bnum0 + ((len-1)<<6);
     if( any ) bnum = -bnum;
     return make_impl(bnum,null);
   }
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.clear(), com.cliffc.aa.type.Bits< BitsRPC >.make(), com.cliffc.aa.type.BitsRPC.make0(), com.cliffc.aa.type.BitsFun.make0(), com.cliffc.aa.type.BitsAlias.make0(), com.cliffc.aa.type.Bits< BitsRPC >.meet(), com.cliffc.aa.type.Bits< BitsRPC >.meet_nil(), com.cliffc.aa.type.Bits< BitsRPC >.not_nil(), com.cliffc.aa.type.Bits< BitsRPC >.set(), com.cliffc.aa.type.Bits< BitsRPC >.strip_nil(), com.cliffc.aa.HM.TestHM9.test36(), com.cliffc.aa.HM.TestHM.test52(), com.cliffc.aa.HM.TestHM.test55(), and com.cliffc.aa.HM.TestHM.test57().
make() [2/3]
final B com.cliffc.aa.type.Bits< B extends Bits< B >.make (int bit) package
Definition at line 189 of file Bits.java.
 { return bit==0 ? make_impl(1,new long[]{1}) : make_impl(bit,null); }
make() [3/3]
final B com.cliffc.aa.type.Bits< B extends Bits< B >.make (int... bits)
Definition at line 191 of file Bits.java.
{
     int max= 0;                // Find max bit
     for( int bit : bits ) max=Math.max(max,bit);
     long[] ls = bits(max);  // Big enuf bits
     for( int bit : bits ) or(ls,bit);
     return make(false,ls);
   }
make_impl()
abstract B com.cliffc.aa.type.Bits< B extends Bits< B >.make_impl (int con, long[] bits) abstract package
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.dual(), and com.cliffc.aa.type.Bits< BitsRPC >.make().
mask()
static long com.cliffc.aa.type.Bits< B extends Bits< B >.mask (long i) static private
Definition at line 200 of file Bits.java.
 { return 1L<<(i&63); }
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.and(), com.cliffc.aa.type.Bits< B extends Bits< B >.Iter.hasNext(), com.cliffc.aa.type.Bits< BitsRPC >.join(), com.cliffc.aa.type.Bits< BitsRPC >.make(), com.cliffc.aa.type.Bits< BitsRPC >.or(), and com.cliffc.aa.type.Bits< BitsRPC >.test().
max()
int com.cliffc.aa.type.Bits< B extends Bits< B >.max ()
Definition at line 284 of file Bits.java.
                     {
     return _bits==null ? Math.abs(_con) : (63 - Long.numberOfLeadingZeros(_bits[_bits.length-1]))+((_bits.length-1)<<6);
   }
Referenced by com.cliffc.aa.type.TypeMem.and_unused(), com.cliffc.aa.type.Bits< BitsRPC >.make(), com.cliffc.aa.type.TypeMem.make(), com.cliffc.aa.type.TypeMem.remove_no_escapes(), and com.cliffc.aa.type.TypeMem.slice_reaching_aliases().
may_nil()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.may_nil () package
Definition at line 209 of file Bits.java.
 { return _con==-1 && _bits != null && ((_bits[0]&1) == 1); }
Referenced by com.cliffc.aa.type.TypeMem.all_reaching_aliases(), com.cliffc.aa.type.TypeRPC.may_nil(), com.cliffc.aa.type.TypeFunPtr.may_nil(), and com.cliffc.aa.type.TypeMemPtr.may_nil().
meet()
B com.cliffc.aa.type.Bits< B extends Bits< B >.meet (final B bs)
Definition at line 298 of file Bits.java.
{
     if( this==bs ) return (B)this;
     B full = ALL();             // Subclass-specific version of full
     if( this==full || bs==full ) return full;
     B any  = ANY();             // Subclass-specific version of any
     if( this==any ) return bs;
     if( bs  ==any ) return (B)this;
     // Empty is a little odd; similar to meeting two JOIN sets with nothing in
     // common - it is on the center, and forces above values to fall, and
     // itself falls to below values.
     if( is_empty() ) return bs.above_center() ? (B)this : bs;
     if( bs.is_empty() ) return above_center() ? bs : (B)this;
     long[] bits0 = _bits, bits1 = bs._bits;
     int con0 = Math.abs(_con), con1 = Math.abs(bs._con);
     // Expand any single bits
     if( bits0==null ) or(bits0=bits(con0), con0);
     if( bits1==null ) or(bits1=bits(con1), con1);
     con0 =    _con < 0 ? -1 : 1;
     con1 = bs._con < 0 ? -1 : 1;
     // Bigger in bits0
     if( bits0.length < bits1.length ) { long[] tmp=bits0; bits0=bits1; bits1=tmp; int t=con0; con0=con1; con1=t; }
     // Both meets?  Set-union
     if( con0 == 1 && con1 == 1 ) {
       long[] bits = bits0.clone();        // Clone larger
       for( int i=0; i<bits1.length; i++ ) // OR in smaller bits
         bits[i] |= bits1[i];
       return make(false,bits);  // This will remove parent/child dups
     }
     // Both joins?  Set-intersection
     Tree<B> tree = tree();
     if( con0 == -1 && con1 == -1 ) {
       long[] bits = new long[bits0.length];// Result array
       join(tree,bits0,bits1,bits);         // Merge left into right
       join(tree,bits1,bits0,bits);         // Merge right into left
       // Nil is not part of the parent tree, so needs to be set explicitly
       if( (bits0[0]&1)==1 && (bits1[0]&1)==1 )  bits[0]|=1;
       // Just the intersection, which may be empty.
       return make(true,bits);
     }
     // Mixed meet/join.  Toss away the join, keep only the meet bits.
     return above_center() ? bs : (B)this;
   }
Referenced by com.cliffc.aa.HM.HM.T2._find_fidxs(), com.cliffc.aa.node.CallNode._ideal_grow(), com.cliffc.aa.HM.HM8.T2._unify(), com.cliffc.aa.node.MemSplitNode.add_alias(), com.cliffc.aa.type.TypeStruct.ax_meet(), com.cliffc.aa.type.TypeMemPtr.ax_meet_nil(), com.cliffc.aa.node.CallNode.escapees(), com.cliffc.aa.type.Bits< BitsRPC >.isa(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.HM.HM9.T2.meet_alias(), com.cliffc.aa.HM.HM.T2.meet_alias(), com.cliffc.aa.HM.HM9.T2.meet_fidxs(), com.cliffc.aa.HM.HM.T2.meet_fidxs(), com.cliffc.aa.type.TypeRPC.meet_nil(), com.cliffc.aa.type.TypeFunPtr.meet_nil(), com.cliffc.aa.type.TypeMemPtr.meet_nil(), com.cliffc.aa.type.Bits< BitsRPC >.set(), com.cliffc.aa.type.TestType.testFunction(), com.cliffc.aa.node.UnresolvedNode.value(), com.cliffc.aa.node.CallNode.value(), com.cliffc.aa.type.TypeRPC.xmeet(), com.cliffc.aa.type.TypeFunPtr.xmeet(), and com.cliffc.aa.type.TypeMemPtr.xmeet().
meet_nil()
B com.cliffc.aa.type.Bits< B extends Bits< B >.meet_nil ()
Definition at line 212 of file Bits.java.
                       {
     if( above_center() ) return make(0); // Crossing centerline, drop all above bits, just [0]
     if( test(0) ) return (B)this;// Already has nil
     long[] bs = _bits;
     if( bs==null )              // Is a single compressed bit
       or(bs = bits(Math.abs(_con)),Math.abs(_con)); // Decompress single bit into array
     else bs = _bits.clone();    // Make a private set
     bs[0] |= 1;                 // Set nil
     return make(false,bs);      // Its below center now, even if the original was above
   }
Referenced by com.cliffc.aa.HM.HM.T2._find_nil(), com.cliffc.aa.HM.TestHM.build_cycle(), com.cliffc.aa.HM.TestHM9.build_cycle(), com.cliffc.aa.HM.TestHM.build_cycle2(), com.cliffc.aa.HM.HM.NotNil.hm(), com.cliffc.aa.type.TypeMemPtr.make_nil(), com.cliffc.aa.type.TestApprox.testApprox7(), and com.cliffc.aa.type.TestType.testOOPsNulls().
not_nil()
B com.cliffc.aa.type.Bits< B extends Bits< B >.not_nil () package
Definition at line 246 of file Bits.java.
               {
     if( !above_center() || _bits == null ) return (B)this;  // Some constant not-nil
     if( !test(_bits,0) ) return (B)this; // No nil choice
     long[] bs = _bits.clone();           // Keep all other bits
     and(bs,0);                           // remove nil choice
     return make(true,bs);                // Choices without nil
   }
Referenced by com.cliffc.aa.type.TypeRPC.not_nil(), com.cliffc.aa.type.TypeFunPtr.not_nil(), and com.cliffc.aa.type.TypeMemPtr.not_nil().
oob()
TypeObj com.cliffc.aa.type.Bits< B extends Bits< B >.oob (TypeObj t)
Definition at line 397 of file Bits.java.
 { return above_center() ? (TypeObj)t.dual() : t; }
or()
static void com.cliffc.aa.type.Bits< B extends Bits< B >.or (long[] bits, long con) static private
Definition at line 281 of file Bits.java.
 { bits[idx(con)] |=  mask(con); }
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.make(), com.cliffc.aa.type.Bits< BitsRPC >.meet(), and com.cliffc.aa.type.Bits< BitsRPC >.meet_nil().
overlaps()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.overlaps (Bits< B > bs)
Definition at line 382 of file Bits.java.
{
     for( int alias : this )
       for( int kid=alias; kid!=0; kid = tree().next_kid(alias,kid) )
         if( bs.test_recur(kid) )
           return true;
     return false;
   }
Referenced by com.cliffc.aa.node.MemSplitNode.check_split().
set()
B com.cliffc.aa.type.Bits< B extends Bits< B >.set (int bit)
Definition at line 264 of file Bits.java.
{
     if( test(bit) ) return (B)this;
     B b = make(bit);
     if( this == EMPTY() ) return b;
     return meet(b);
   }
Referenced by com.cliffc.aa.HM.HM9.T2._fresh_unify(), com.cliffc.aa.node.MemSplitNode._update(), com.cliffc.aa.type.TypeMem.aliases(), com.cliffc.aa.type.TypeMem.all_reaching_aliases(), com.cliffc.aa.type.TypeMem.and_unused(), com.cliffc.aa.Env.init(), and com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay().
str()
SB com.cliffc.aa.type.Bits< B extends Bits< B >.str (SB sb)
Definition at line 134 of file Bits.java.
{
     if( _bits==null ) {
       if( _con== 0 ) return sb.p("[]"); // EMPTY
       if( _con== 1 ) return sb.p("[ALL]");
       if( _con==-1 ) return sb.p("[ANY]");
       return sb.p('[').p(_con).p(']');
     }
     sb.p('[');
     if( above_center() ) sb.p('~');
     char sep = above_center()?'+':',';
     if( test(_bits,1) ) {
       if( test(_bits,0) ) sb.p('0').p(sep);
       return sb.p(above_center() ? "ANY]" : "ALL]");
     }
     for( Integer idx : this ) sb.p(idx).p(sep);
     return sb.unchar().p(']');
   }
Referenced by com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM9.T2._p(), com.cliffc.aa.HM.HM8.Struct.p1(), com.cliffc.aa.type.TypeRPC.str(), com.cliffc.aa.type.TypeMemPtr.str(), com.cliffc.aa.type.TypeFunPtr.str(), com.cliffc.aa.HM.HM8.Struct.str(), com.cliffc.aa.HM.HM8.T2.str(), com.cliffc.aa.HM.HM9.T2.str(), com.cliffc.aa.HM.HM.T2.str(), and com.cliffc.aa.type.Bits< BitsRPC >.toString().
strip_nil()
B com.cliffc.aa.type.Bits< B extends Bits< B >.strip_nil ()
Definition at line 273 of file Bits.java.
{
     if( _bits == null ) return (B)this; // Should not be a nil to remove
     if( (_bits[0] &1)==0 ) return (B) this; // No nil
     long[] bs = _bits.clone();
     bs[0] &= ~1;                // Strip nil
     return make(_con==-1,bs);
   }
Referenced by com.cliffc.aa.type.TypeMemPtr.getbit0(), com.cliffc.aa.type.TypeMemPtr.is_display_ptr(), and com.cliffc.aa.TestParse.test_ptr0().
subtract()
Bits<B> com.cliffc.aa.type.Bits< B extends Bits< B >.subtract (Bits< B > bs)
Definition at line 374 of file Bits.java.
{
     Bits<B> bs0 = this;
     for( int alias : this )
       for( int kid=alias; kid!=0; kid = tree().next_kid(alias,kid) )
         if( bs.test_recur(kid) )
           bs0 = bs0.clear(kid);
     return bs0;
   }
test() [1/2]
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.test (int i)
Definition at line 226 of file Bits.java.
{
     if( _bits==null ) return i!=0 && i==Math.abs(_con);
     int idx = idx(i);
     return idx < _bits.length && test(_bits, i);
   }
test() [2/2]
static boolean com.cliffc.aa.type.Bits< B extends Bits< B >.test (long[] bits, int i) static private
Definition at line 224 of file Bits.java.
 { return idx(i) < bits.length && (bits[idx(i)]&mask(i))!=0; }
Referenced by com.cliffc.aa.HM.HM9.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._fresh_unify(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.node.MemSplitNode._update(), com.cliffc.aa.type.TypeStruct.ax_impl_ptr(), com.cliffc.aa.type.Bits< BitsRPC >.check(), com.cliffc.aa.type.TestApprox.check_leaf(), com.cliffc.aa.type.Bits< BitsRPC >.clear(), com.cliffc.aa.type.TypeMemPtr.depth(), com.cliffc.aa.node.ScopeNode.get_type(), com.cliffc.aa.HM.HM9.Apply.hm(), com.cliffc.aa.HM.HM9.Field.hm(), com.cliffc.aa.HM.HM.Field.hm(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.type.Bits< BitsRPC >.join(), com.cliffc.aa.type.Bits< BitsRPC >.make(), com.cliffc.aa.type.TypeMemPtr.max(), com.cliffc.aa.type.Bits< BitsRPC >.meet_nil(), com.cliffc.aa.type.TypeRPC.must_nil(), com.cliffc.aa.type.TypeFunPtr.must_nil(), com.cliffc.aa.type.TypeMemPtr.must_nil(), com.cliffc.aa.type.Bits< BitsRPC >.not_nil(), com.cliffc.aa.node.NewObjNode.promote_forward(), com.cliffc.aa.type.Bits< BitsRPC >.set(), com.cliffc.aa.node.FunNode.split_size(), com.cliffc.aa.type.TypeMemPtr.str(), com.cliffc.aa.type.Bits< BitsRPC >.str(), com.cliffc.aa.type.TypeRPC.test(), com.cliffc.aa.type.Bits< BitsRPC >.test(), com.cliffc.aa.TestParse.test_ptr0(), com.cliffc.aa.type.Bits< BitsRPC >.test_recur(), and com.cliffc.aa.type.TestType.testRecursive().
test_recur()
boolean com.cliffc.aa.type.Bits< B extends Bits< B >.test_recur (int i)
Definition at line 232 of file Bits.java.
{
     if( test(i) ) return true;
     Tree<B> tree = tree();
     while( (i = tree.parent(i)) != 0 )
       if( test(i) )
         return true;
     return false;
   }
Referenced by com.cliffc.aa.node.CallNode._ideal_grow(), com.cliffc.aa.type.TypeMem.and_unused(), com.cliffc.aa.node.LoadNode.find_previous_store(), com.cliffc.aa.node.CEProjNode.good_call(), com.cliffc.aa.node.LoadNode.ideal_mono(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.CallEpiNode.live_use(), com.cliffc.aa.node.CallNode.live_use_call(), com.cliffc.aa.type.Bits< BitsRPC >.overlaps(), com.cliffc.aa.type.TypeMem.remove_no_escapes(), com.cliffc.aa.type.TypeMem.slice_reaching_aliases(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.type.Bits< BitsRPC >.subtract(), and com.cliffc.aa.node.CallEpiNode.value().
toString()
String com.cliffc.aa.type.Bits< B extends Bits< B >.toString ()
Definition at line 133 of file Bits.java.
 { return str(new SB()).toString(); }
tree()
abstract Tree<B> com.cliffc.aa.type.Bits< B extends Bits< B >.tree () abstract package
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.check(), com.cliffc.aa.type.Bits< BitsRPC >.join(), com.cliffc.aa.type.Bits< BitsRPC >.make(), com.cliffc.aa.type.Bits< BitsRPC >.meet(), com.cliffc.aa.type.Bits< BitsRPC >.overlaps(), com.cliffc.aa.type.Bits< BitsRPC >.subtract(), and com.cliffc.aa.type.Bits< BitsRPC >.test_recur().
Member Data Documentation
_bits
long [] com.cliffc.aa.type.Bits< B extends Bits< B >._bits package
Definition at line 68 of file Bits.java.
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.abit(), com.cliffc.aa.type.Bits< BitsRPC >.bitCount(), com.cliffc.aa.type.Bits< BitsRPC >.check(), com.cliffc.aa.type.Bits< BitsRPC >.clear(), com.cliffc.aa.type.Bits< BitsRPC >.dual(), com.cliffc.aa.type.Bits< BitsRPC >.equals(), com.cliffc.aa.type.Bits< BitsRPC >.getbit(), com.cliffc.aa.type.Bits< B extends Bits< B >.Iter.hasNext(), com.cliffc.aa.type.Bits< BitsRPC >.init(), com.cliffc.aa.type.Bits< BitsRPC >.is_empty(), com.cliffc.aa.type.Bits< BitsRPC >.is_nil(), com.cliffc.aa.type.Bits< BitsRPC >.max(), com.cliffc.aa.type.Bits< BitsRPC >.may_nil(), com.cliffc.aa.type.Bits< BitsRPC >.meet(), com.cliffc.aa.type.Bits< BitsRPC >.meet_nil(), com.cliffc.aa.type.Bits< B extends Bits< B >.Iter.next(), com.cliffc.aa.type.Bits< BitsRPC >.not_nil(), com.cliffc.aa.type.Bits< BitsRPC >.str(), com.cliffc.aa.type.Bits< BitsRPC >.strip_nil(), and com.cliffc.aa.type.Bits< BitsRPC >.test().
_con
int com.cliffc.aa.type.Bits< B extends Bits< B >._con package
Definition at line 69 of file Bits.java.
Referenced by com.cliffc.aa.type.Bits< BitsRPC >.abit(), com.cliffc.aa.type.Bits< BitsRPC >.above_center(), com.cliffc.aa.type.Bits< BitsRPC >.bitCount(), com.cliffc.aa.type.Bits< BitsRPC >.check(), com.cliffc.aa.type.Bits< BitsRPC >.clear(), com.cliffc.aa.type.Bits< BitsRPC >.dual(), com.cliffc.aa.type.Bits< BitsRPC >.equals(), com.cliffc.aa.type.Bits< BitsRPC >.getbit(), com.cliffc.aa.type.Bits< BitsRPC >.init(), com.cliffc.aa.type.Bits< BitsRPC >.is_empty(), com.cliffc.aa.type.Bits< BitsRPC >.max(), com.cliffc.aa.type.Bits< BitsRPC >.may_nil(), com.cliffc.aa.type.Bits< BitsRPC >.meet(), com.cliffc.aa.type.Bits< BitsRPC >.meet_nil(), com.cliffc.aa.type.Bits< B extends Bits< B >.Iter.next(), com.cliffc.aa.type.Bits< BitsRPC >.str(), com.cliffc.aa.type.Bits< BitsRPC >.strip_nil(), and com.cliffc.aa.type.Bits< BitsRPC >.test().
_hash
int com.cliffc.aa.type.Bits< B extends Bits< B >._hash package
Definition at line 70 of file Bits.java.
Referenced by com.cliffc.aa.type.TypeRPC.compute_hash(), com.cliffc.aa.type.TypeMemPtr.compute_hash(), com.cliffc.aa.type.TypeFunPtr.compute_hash(), com.cliffc.aa.type.Bits< BitsRPC >.equals(), com.cliffc.aa.type.Bits< BitsRPC >.hashCode(), and com.cliffc.aa.type.Bits< BitsRPC >.init().
The documentation for this class was generated from the following file:
Bits.java