aa: com.cliffc.aa.HM.HM2 Class Reference
com.cliffc.aa.HM.HM2 Class Reference
Classes
class Apply
class Con
class HMType
class HMVar
class Ident
class Lambda
class Let
class Oper
class Syntax
Static Public Member Functions
static HMType hm (Syntax prog)
Static Package Functions
static void reset ()
Static Package Attributes
static final HashMap< String, HMType > ENV = new HashMap<>()
Detailed Description
Definition at line 67 of file HM2.java.
Member Function Documentation
hm()
static HMType com.cliffc.aa.HM.HM2.hm (Syntax prog) static
Definition at line 70 of file HM2.java.
{
     // Simple types
     HMVar bool  = new HMVar(TypeInt.BOOL);
     HMVar int64 = new HMVar(TypeInt.INT64);
     HMVar flt64 = new HMVar(TypeFlt.FLT64);
     HMVar strp  = new HMVar(TypeMemPtr.STRPTR);
     // Primitives
     HMVar var1 = new HMVar();
     HMVar var2 = new HMVar();
     ENV.put("pair",Oper.fun(var1, Oper.fun(var2, new Oper("pair",var1,var2))));
     HMVar var3 = new HMVar();
     ENV.put("if/else",Oper.fun(bool,Oper.fun(var3,Oper.fun(var3,var3))));
     ENV.put("dec",Oper.fun(int64,int64));
     ENV.put("*",Oper.fun(int64,Oper.fun(int64,int64)));
     ENV.put("==0",Oper.fun(int64,bool));
     // Print a string; int->str
     ENV.put("str",Oper.fun(int64,strp));
     // Factor
     ENV.put("factor",Oper.fun(flt64,new Oper("pair",flt64,flt64)));
     // Prep for SSA: pre-gather all the (unique) ids
     prog.get_ids();
     return prog.hm(new HashSet<>());
   }
References com.cliffc.aa.type.TypeInt.BOOL, com.cliffc.aa.HM.HM2.ENV, com.cliffc.aa.type.TypeFlt.FLT64, com.cliffc.aa.HM.HM2.Oper.fun(), com.cliffc.aa.HM.HM2.Syntax.get_ids(), com.cliffc.aa.HM.HM2.Syntax.hm(), com.cliffc.aa.type.TypeInt.INT64, and com.cliffc.aa.type.TypeMemPtr.STRPTR.
Referenced by com.cliffc.aa.HM.TestHM2.test00(), com.cliffc.aa.HM.TestHM2.test01(), com.cliffc.aa.HM.TestHM2.test02(), com.cliffc.aa.HM.TestHM2.test03(), com.cliffc.aa.HM.TestHM2.test04(), com.cliffc.aa.HM.TestHM2.test05(), com.cliffc.aa.HM.TestHM2.test06(), com.cliffc.aa.HM.TestHM2.test07(), com.cliffc.aa.HM.TestHM2.test08(), com.cliffc.aa.HM.TestHM2.test09(), com.cliffc.aa.HM.TestHM2.test10(), and com.cliffc.aa.HM.TestHM2.test11().
reset()
static void com.cliffc.aa.HM.HM2.reset () static package
Definition at line 100 of file HM2.java.
 { HMVar.reset(); }
References com.cliffc.aa.HM.HM2.HMVar.reset().
Referenced by com.cliffc.aa.HM.TestHM2.reset().
Member Data Documentation
ENV
final HashMap<String,HMType> com.cliffc.aa.HM.HM2.ENV = new HashMap<>() static package
Definition at line 68 of file HM2.java.
Referenced by com.cliffc.aa.HM.HM2.Lambda.get_ids(), com.cliffc.aa.HM.HM2.Let.get_ids(), com.cliffc.aa.HM.HM2.hm(), com.cliffc.aa.HM.HM2.Ident.hm(), com.cliffc.aa.HM.HM2.Lambda.hm(), and com.cliffc.aa.HM.HM2.Let.hm().
The documentation for this class was generated from the following file:
HM2.java