aa: com.cliffc.aa.util.BitSetSparse Class Reference
com.cliffc.aa.util.BitSetSparse Class Reference
Public Member Functions
void clear ()
boolean tset (int b0, int b1)
boolean tset (long b)
Package Attributes
NonBlockingHashMapLong< String > _set = new NonBlockingHashMapLong<>()
Detailed Description
Definition at line 4 of file BitSetSparse.java.
Member Function Documentation
clear()
void com.cliffc.aa.util.BitSetSparse.clear ()
Definition at line 8 of file BitSetSparse.java.
 { _set.clear(); }
References com.cliffc.aa.util.BitSetSparse._set, and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.clear().
tset() [1/2]
boolean com.cliffc.aa.util.BitSetSparse.tset (int b0, int b1)
Definition at line 6 of file BitSetSparse.java.
 { return tset(((long)b0<<32)|b1); }
References com.cliffc.aa.util.BitSetSparse.tset().
Referenced by com.cliffc.aa.HM.HM3.Oper._eq(), com.cliffc.aa.type.TypeStruct.ax_meet(), and com.cliffc.aa.util.BitSetSparse.tset().
tset() [2/2]
boolean com.cliffc.aa.util.BitSetSparse.tset (long b)
Definition at line 7 of file BitSetSparse.java.
 { return _set.put(b,"")!=null; }
References com.cliffc.aa.util.BitSetSparse._set, and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.put().
Member Data Documentation
_set
NonBlockingHashMapLong<String> com.cliffc.aa.util.BitSetSparse._set = new NonBlockingHashMapLong<>() package
Definition at line 5 of file BitSetSparse.java.
Referenced by com.cliffc.aa.util.BitSetSparse.clear(), and com.cliffc.aa.util.BitSetSparse.tset().
The documentation for this class was generated from the following file:
BitSetSparse.java