aa: com.cliffc.aa.type.TypeMem Class Reference
com.cliffc.aa.type.TypeMem Class Reference
Memory type; the state of all of memory; memory edges order memory ops.
Public Member Functions
boolean above (Type t)
boolean above_center ()
TypeObj[] alias2objs ()
BitsAlias aliases ()
BitsAlias all_reaching_aliases (BitsAlias aliases)
BitsAlias and_unused (BitsAlias escs)
TypeObj at (int alias)
boolean basic_live ()
final boolean contains (Type t)
TypeMem crush ()
boolean cycle_equals (Type o)
final T dual ()
boolean equals (Object o)
TypeMem flatten_fields ()
boolean fld_is_mod (BitsAlias aliases, String fld)
double getd ()
long getl ()
String getstr ()
boolean has_name ()
boolean has_used (BitSet aliases)
final int hashCode ()
Type high ()
boolean is_con ()
boolean is_display_ptr ()
boolean is_forward_ref ()
boolean is_live ()
boolean isa (Type t)
final boolean isa_scalar ()
byte isBitShape (Type t)
Type join (Type t)
TypeObj ld (TypeMemPtr ptr)
int len ()
TypeLive live ()
boolean live_no_disp ()
Type make_from (Type head, TypeMem map, VBitSet visit)
boolean may_be_con ()
boolean may_nil ()
final Type meet (Type t)
Type meet_loop (Type t2)
Type meet_nil (Type nil)
boolean must_nil ()
Type oob ()
Type oob (Type e)
TypeMem oob (TypeMem e)
TypeMemPtr oob (TypeMemPtr e)
TypeObj oob (TypeObj e)
TypeStruct oob (TypeStruct e)
Type oob_deep (Type t)
Type oop_deep_impl (Type t)
TypeMem remove (BitsAlias escs)
final T remove_name ()
TypeMem remove_no_escapes (BitsAlias escs, String fld, Type live)
TypeMem set (int alias, TypeObj obj)
final T set_name (String name)
TypeMemPtr sharpen (TypeMemPtr dull)
Type sharptr (Type ptr)
Type simple_ptr ()
TypeMem slice_reaching_aliases (BitsAlias aliases)
TypeMem st_new (int alias, TypeObj obj)
SB str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
final String toString ()
TypeMem update (BitsAlias aliases, Access fin, String fld, Type val)
TypeMem update (BitsAlias aliases, TypeInt idx, Type val)
void walk (Predicate< Type > p)
TypeMem widen ()
Static Public Member Functions
static Ary< Type > ALL_TYPES ()
static boolean eq (Type[] t0, Type[] t1)
static void init0 (HashMap< String, Type > types)
static boolean intern_check ()
static TypeMem make (BitsAlias aliases, TypeObj oop)
static TypeMem make (int alias, TypeObj oop)
static TypeMem make0 (TypeObj[] as)
static TypeMem make_live (TypeLive live)
Public Attributes
int _hash
String _name
int _uid
Static Public Attributes
static final Type ALL
static final Type ANY
static final TypeMem ANYMEM
static final Type CTRL
static final TypeMem DEAD
static final TypeMem EMPTY
static final TypeMem ESCAPE
static final TypeMem FULL
static final TypeMem MEM
static final TypeMem MEM_ABC
static final Type NIL
static final Type NSCALR
static final Type REAL
static int RECURSIVE_MEET
static final Type SCALAR
static final Type XCTRL
static final TypeMem XMEM
static final Type XNIL
static final Type XNSCALR
static final Type XSCALAR
Protected Member Functions
Type clone ()
T init (byte type, String name)
TypeMem xdual ()
Type xmeet (Type t)
Package Functions
int compute_hash ()
boolean contains (Type t, VBitSet bs)
final Type cross_nil (Type t)
final T hashcons_free ()
boolean intern_check1 ()
Type intern_lookup ()
boolean interned ()
boolean is_display ()
final String mtname (Type t, Type mt)
Type not_nil ()
T rdual ()
TypeStruct repeats_in_cycles (TypeStruct head, VBitSet bs)
final T retern ()
TypeMemPtr sharp_get (TypeMemPtr tmp)
TypeMemPtr sharput (TypeMemPtr dull, TypeMemPtr sharp)
RuntimeException typerr (Type t)
final T untern ()
Static Package Functions
[static initializer]
[static initializer]
static TypeObj at (TypeObj[] tos, int alias)
static int at_idx (TypeObj[]tos, int alias)
static boolean check_name (String n)
static boolean check_startup ()
static void concat (Ary< Type > ts, Type[] ts1)
static Type intern_find (int uid)
static int intern_size ()
static Type make (byte type)
Package Attributes
T _dual
byte _type
Static Package Attributes
static final TypeMem ALIVE
static final TypeMem ALLMEM
static final TypeMem LESC_NO_DISP
static final TypeMem LIVE_BOT
static final TypeMem LNO_DISP
static final TypeMem MEM_STR
static final Type NREAL
static final Pool[] POOLS
static final byte TALL
static final byte TANY
static final byte TARY
static final byte TCTRL
static final byte TFLD
static final byte TFLT
static final byte TFUNPTR
static final byte TFUNSIG
static final byte TINT
static final byte TLAST
static final byte TLIVE
static final byte TMEM
static final byte TMEMPTR
static final byte TNIL
static final byte TNREAL
static final byte TNSCALR
static final byte TOBJ
static final byte TREAL
static final byte TRPC
static final byte TSCALAR
static final byte TSIMPLE
static final byte TSTR
static final byte TSTRUCT
static final byte TTUPLE
static final byte TXCTRL
static final byte TXNIL
static final byte TXNREAL
static final byte TXNSCALR
static final byte TXREAL
static final byte TXSCALAR
static final TypeMem[] TYPES = new TypeMem[]{FULL,MEM,MEM_ABC.dual(),ALLMEM,ESCAPE}
Private Member Functions
T _set_name (String name)
int _uid ()
boolean check_commute (Type t, Type mt)
boolean check_symmetric (Type t, Type mt)
T hashcons ()
TypeMem init (TypeObj[] pubs)
boolean intern_check0 (Type v)
boolean is_num ()
boolean is_ptr ()
boolean is_simple ()
Type xmt_name (Type t, Type mt)
Static Private Member Functions
static TypeObj[] _make1 (TypeObj[] as)
static TypeObj _meet (TypeObj a, TypeObj b, boolean is_loop)
static TypeObj[] _meet (TypeObj[] as, TypeObj[] bs, boolean is_loop)
static TypeObj[] _st_new (TypeObj[] base, TypeObj[] as, int alias)
static boolean check (TypeObj[] as)
static TypeObj ld (TypeObj[] tos, BitsAlias aliases)
static TypeMem make (TypeObj[] pubs)
Private Attributes
TypeObj[] _pubs
HashMap< TypeMemPtr, TypeMemPtr > _sharp_cache
Static Private Attributes
static Ary< Type > ALL_TYPES
static int CNT
static final ConcurrentHashMap< Type, Type > INTERN
static final byte[] ISA_SCALAR
static final char[] LIVEC = new char[]{' ','#','R','3'}
static Type[] SCALAR_PRIMS
static final String[] STRS
static final Type XNREAL
static final Type XREAL
Detailed Description
Memory type; the state of all of memory; memory edges order memory ops.
Produced at the program start, consumed by all function calls, consumed be Loads, consumed and produced by Stores. Can be broken out in the "equiv- alence class" (Alias#) model of memory over a bulk memory to allow more fine grained knowledge. Memory is accessed via Alias::s, where all TypeObjs in an Alias class are Meet together as an approximation.
Conceptually, each alias# represents an infinite set of pointers - broken into equivalence classes. We can split such a class in half - some pointers will go left and some go right, and where we can't tell we'll use both sets. Any alias set is a tree-like nested set of sets bottoming out in individual pointers. The types are conceptually unchanged if we start using e.g. 2 alias::s instead of 1 everywhere - we've just explicitly named the next layer in the tree-of-sets.
Splitting happens during code-cloning (inlining) where we make a copy of an alias generator (NewNode). Both copies are alias renumbered to child alias numbers from the parent. The IR will be holding on to some copies of the original alias#, which is now confused with both children. After a full round of gcp() this confusion will be removed. While the confusion is not (yet) removed, we will have to deal with this mixture of the left child, right child, and parent.
We use an "all-memory" notion to handle the worse-case from e.g. all unknown calls. Really the worse a Call can be is to "leak" all aliases that come in to the the call (and are reachable from those) - but we need a convenient Bottom type. Missing aliases default to TypeObj.
The representation is a collection of TypeObjs indexed by alias#. Missing aliases are always equal to their nearest present parent. The root at alias#1 is only either TypeObj.BOT or TOP. Alias#0 is nil and is always missing. The structure is canonicalized; if a child is a dup of a parent it is removed (since an ask will yield the correct value from the parent).
There is no meet/join relationship between parent and child; a child can be precisely updated independently from the parent and other siblings.
CNC - Observe that the alias Trees on Fields applies to Indices on arrays as well - if we can group indices in a tree-like access pattern (obvious one being All vs some Constants).
Definition at line 53 of file TypeMem.java.
Member Function Documentation
[static initializer]() [1/2]
com.cliffc.aa.type.TypeMem.[static initializer] static package
[static initializer]() [2/2]
com.cliffc.aa.type.TypeMem.[static initializer] static package
_make1()
static TypeObj [] com.cliffc.aa.type.TypeMem._make1 (TypeObj[] as) static private
Definition at line 179 of file TypeMem.java.
{
     int len = as.length;
     if( len > 1 && as[1]==null ) {
       int i; for( i=2; i<len; i++ )
         if( as[i]!=null && as[i] != TypeObj.XOBJ )
           break;
       if( i==len ) return null; // All things are dead, so dead
       as[1] = TypeObj.XOBJ;     // Default memory is "do not care"
     }
     if( len <= 2 ) return as;
     // No dups of a parent
     for( int i=1; i<as.length; i++ )
       if( as[i] != null )
         for( int par = BitsAlias.TREE.parent(i); par!=0; par = BitsAlias.TREE.parent(par) )
           if( as[par] != null ) {
             if( as[par] == as[i] ) as[i] = null;
             break;
           }
     // Remove trailing nulls; make the array "tight"
     while( as[len-1] == null ) len--;
     if( as.length!=len ) as = Arrays.copyOf(as,len);
     return as;
   }
References com.cliffc.aa.type.TypeMem.len(), com.cliffc.aa.type.BitsAlias.TREE, and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.XOBJ.
Referenced by com.cliffc.aa.type.TypeMem.make0(), com.cliffc.aa.type.TypeMem.meet_loop(), com.cliffc.aa.type.TypeMem.update(), and com.cliffc.aa.type.TypeMem.xmeet().
_meet() [1/2]
static TypeObj com.cliffc.aa.type.TypeMem._meet (TypeObj a, TypeObj b, boolean is_loop) static private
Definition at line 297 of file TypeMem.java.
{
     return (TypeObj)(is_loop ? a.meet_loop(b) : a.meet(b));
   }
References com.cliffc.aa.type.Type< T extends Type< T >.meet(), and com.cliffc.aa.type.Type< T extends Type< T >.meet_loop().
_meet() [2/2]
static TypeObj [] com.cliffc.aa.type.TypeMem._meet (TypeObj[] as, TypeObj[] bs, boolean is_loop) static private
Definition at line 280 of file TypeMem.java.
{
     TypeObj mt_live = (TypeObj)as[0].meet(bs[0]);
     int  len = Math.max(as.length,bs.length);
     int mlen = Math.min(as.length,bs.length);
     if( mlen==1 ) {             // At least 1 is short
       // Short & low "wins": result is short.
       if( (!as[0].above_center() && as.length==1) ||
           (!bs[0].above_center() && bs.length==1) )
         return new TypeObj[]{mt_live};
     }
     TypeObj[] objs = new TypeObj[len];
     objs[0] = mt_live;
     for( int i=1; i<len; i++ )
       objs[i] = i<mlen && as[i]==null && bs[i]==null // Shortcut null-vs-null
         ? null : _meet(at(as,i),at(bs,i),is_loop);   // meet element-by-element
     return objs;
   }
References com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.above_center(), com.cliffc.aa.type.TypeMem.above_center(), com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.type.TypeMem.len(), and com.cliffc.aa.type.Type< TypeMem >.meet().
Referenced by com.cliffc.aa.type.TypeMem.meet_loop(), and com.cliffc.aa.type.TypeMem.xmeet().
_set_name()
T com.cliffc.aa.type.Type< T extends Type< T >._set_name (String name) private inherited
Definition at line 558 of file Type.java.
{
     POOLS[_type]._clone++;
     T t1 = (T)clone();
     t1._name = name;
     return t1.hashcons_free();
   }
_st_new()
static TypeObj [] com.cliffc.aa.type.TypeMem._st_new (TypeObj[] base, TypeObj[] as, int alias) static private
Definition at line 454 of file TypeMem.java.
{
     return base==as ? Arrays.copyOf(base,Math.max(base.length,alias+1)) : as;
   }
Referenced by com.cliffc.aa.type.TypeMem.st_new().
_uid()
int com.cliffc.aa.type.Type< T extends Type< T >._uid private inherited
Definition at line 103 of file Type.java.
 { return CNT++; }
above()
boolean com.cliffc.aa.type.Type< T extends Type< T >.above (Type< TypeMem > t) inherited
Definition at line 625 of file Type.java.
 { return t != this && meet(t)==t; }
above_center()
boolean com.cliffc.aa.type.TypeMem.above_center ()
Definition at line 548 of file TypeMem.java.
{
     for( TypeObj alias : _pubs )
       if( alias != null && !alias.above_center() && !alias.is_con() )
         return false;
     return true;
   }
References com.cliffc.aa.type.TypeMem._pubs.
Referenced by com.cliffc.aa.type.TypeMem._meet(), com.cliffc.aa.type.TypeMem.aliases(), com.cliffc.aa.type.TypeMem.check(), com.cliffc.aa.node.MemPrimNode.LValueLength.live_use(), and com.cliffc.aa.node.LoadNode.live_use().
alias2objs()
TypeObj [] com.cliffc.aa.type.TypeMem.alias2objs ()
Definition at line 148 of file TypeMem.java.
 { return _pubs; }
References com.cliffc.aa.type.TypeMem._pubs.
Referenced by com.cliffc.aa.type.TypeMemPtr.make_from(), and com.cliffc.aa.node.DefMemNode.make_mem().
aliases()
BitsAlias com.cliffc.aa.type.TypeMem.aliases ()
Definition at line 152 of file TypeMem.java.
{
     if( this== FULL ) return BitsAlias.NZERO;
     if( this==EMPTY ) return BitsAlias.EMPTY;
     BitsAlias bas = BitsAlias.EMPTY;
     for( int i = 0; i< _pubs.length; i++ )
       if( _pubs[i]!=null && !_pubs[i].above_center() )
         bas = bas.set(i);
     return bas;
   }
References com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.TypeMem.above_center(), com.cliffc.aa.type.BitsAlias.EMPTY, com.cliffc.aa.type.TypeMem.EMPTY, com.cliffc.aa.type.TypeMem.FULL, com.cliffc.aa.type.BitsAlias.NZERO, and com.cliffc.aa.type.Bits< B extends Bits< B >.set().
Referenced by com.cliffc.aa.type.TypeMem.all_reaching_aliases(), com.cliffc.aa.type.TypeMem.fld_is_mod(), com.cliffc.aa.type.TypeMem.has_used(), com.cliffc.aa.type.TypeMem.ld(), com.cliffc.aa.type.TypeMem.make(), com.cliffc.aa.type.TypeMem.slice_reaching_aliases(), and com.cliffc.aa.type.TypeMem.update().
all_reaching_aliases()
BitsAlias com.cliffc.aa.type.TypeMem.all_reaching_aliases (BitsAlias aliases)
Definition at line 349 of file TypeMem.java.
{
     if( aliases==BitsAlias.NIL || aliases==BitsAlias.EMPTY ) return BitsAlias.EMPTY;
     if( aliases==BitsAlias.FULL ) return aliases;
     AryInt work = new AryInt();
     VBitSet visit = new VBitSet();
     for( int alias : aliases )
       for( int kid=alias; kid!=0; kid = BitsAlias.next_kid(alias,kid) )
         { work.push(kid); visit.set(kid); }
     while( !work.isEmpty() ) {
       int alias=work.pop();
       if( alias==0 ) continue;
       TypeObj to = at(alias);
       if( to==TypeObj.OBJ || to==TypeObj.ISUSED )
         return BitsAlias.FULL;  // All structs with all possible pointers
       if( !(to instanceof TypeStruct) ) continue;
       TypeStruct ts = (TypeStruct)to;
       // Incomplete struct?  This is an early escapee from Parse times; more
       // fields may be added which we assume is a pointer to all.
       if( ts._open )
         return BitsAlias.FULL;  // Generic open struct points to all
       for( TypeFld tfld : ts.flds() ) {
         Type fld = tfld._t;
         if( TypeMemPtr.OOP.isa(fld) )
           fld = TypeMemPtr.OOP;                      // All possible pointers
         if( fld instanceof TypeFunPtr ) fld = ((TypeFunPtr)fld)._disp;
         if( !(fld instanceof TypeMemPtr) ) continue; // Not a pointer, no more aliases
         if( ((TypeMemPtr)fld)._aliases.test(1) )
           return BitsAlias.FULL; // All possible pointers
         // Walk the possible pointers, and include them in the slice
         for( int ptralias : ((TypeMemPtr)fld)._aliases )
           for( int kid=ptralias; kid!=0; kid = BitsAlias.next_kid(ptralias,kid) )
             if( !visit.tset(kid) ) {
               work.push(kid);
               aliases = aliases.set(kid);
             }
       }
     }
     assert !aliases.may_nil();
     return aliases;
   }
References com.cliffc.aa.type.TypeStruct._open, com.cliffc.aa.type.TypeMem.aliases(), com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.type.BitsAlias.EMPTY, com.cliffc.aa.type.TypeStruct.flds(), com.cliffc.aa.type.BitsAlias.FULL, com.cliffc.aa.type.Type< T extends Type< T >.isa(), com.cliffc.aa.util.AryInt.isEmpty(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.ISUSED, com.cliffc.aa.type.Bits< B extends Bits< B >.may_nil(), com.cliffc.aa.type.BitsAlias.next_kid(), com.cliffc.aa.type.BitsAlias.NIL, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.OBJ, com.cliffc.aa.type.TypeMemPtr.OOP, com.cliffc.aa.util.AryInt.pop(), com.cliffc.aa.util.AryInt.push(), com.cliffc.aa.type.Bits< B extends Bits< B >.set(), and com.cliffc.aa.util.VBitSet.tset().
Referenced by com.cliffc.aa.node.ScopeNode.compute_live_mem(), com.cliffc.aa.node.CallEpiNode.esc_out(), com.cliffc.aa.node.CallNode.live_use(), and com.cliffc.aa.node.CallNode.value().
ALL_TYPES()
static Ary<Type> com.cliffc.aa.type.Type< T extends Type< T >.ALL_TYPES static inherited
Definition at line 651 of file Type.java.
{
     if( ALL_TYPES != null ) return ALL_TYPES;
     Ary<Type> ts = new Ary<>(new Type[1],0);
     concat(ts,Type      .TYPES);
     concat(ts,TypeFlt   .TYPES);
     concat(ts,TypeFunPtr.TYPES);
     concat(ts,TypeFunSig.TYPES);
     concat(ts,TypeInt   .TYPES);
     concat(ts,TypeLive  .TYPES);
     concat(ts,TypeMem   .TYPES);
     concat(ts,TypeMemPtr.TYPES);
     concat(ts,TypeObj   .TYPES);
     concat(ts,TypeRPC   .TYPES);
     concat(ts,TypeStr   .TYPES);
     concat(ts,TypeStruct.TYPES);
     concat(ts,TypeTuple .TYPES);
     concat(ts,TypeAry   .TYPES);
     // Partial order Sort, makes for easier tests later.  Arrays.sort requires
     // a total order (i.e., the obvious Comparator breaks the sort contract),
     // so we hand-roll a simple bubble sort.
     for( int i=0; i<ts._len; i++ )
       for( int j=i+1; j<ts._len; j++ )
         if( ts._es[j].isa(ts._es[i]) ) { Type tmp = ts._es[i]; ts._es[i] = ts._es[j]; ts._es[j] = tmp; }
     return (ALL_TYPES = ts); // Preserve for tests
   }
and_unused()
BitsAlias com.cliffc.aa.type.TypeMem.and_unused (BitsAlias escs)
Definition at line 498 of file TypeMem.java.
{
     int len = Math.max(_pubs.length,escs.max()+1);
     BitsAlias bs = BitsAlias.EMPTY;
     for( int i=1; i<len; i++ )
       if( at(i)==TypeObj.UNUSED && escs.test_recur(i) )
         bs = bs.set(i);
     return bs;
   }
References com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.type.BitsAlias.EMPTY, com.cliffc.aa.type.TypeMem.len(), com.cliffc.aa.type.Bits< B extends Bits< B >.max(), com.cliffc.aa.type.Bits< B extends Bits< B >.set(), com.cliffc.aa.type.Bits< B extends Bits< B >.test_recur(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED.
Referenced by com.cliffc.aa.node.CallNode.escapees().
at() [1/2]
TypeObj com.cliffc.aa.type.TypeMem.at (int alias)
Definition at line 135 of file TypeMem.java.
 { return at(_pubs ,alias); }
References com.cliffc.aa.type.TypeMem._pubs, and com.cliffc.aa.type.TypeMem.at().
Referenced by com.cliffc.aa.type.TypeStruct._dull(), com.cliffc.aa.tvar.TV2._find_tvar(), com.cliffc.aa.type.TypeMem._meet(), com.cliffc.aa.node.NewNode< TypeStruct >.add_flow_def_extra(), com.cliffc.aa.type.TypeMem.all_reaching_aliases(), com.cliffc.aa.type.TypeMem.and_unused(), com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.type.TypeMem.fld_is_mod(), com.cliffc.aa.type.TypeMem.has_used(), com.cliffc.aa.node.MrgProjNode.ideal_reduce(), com.cliffc.aa.type.TypeMem.ld(), com.cliffc.aa.node.NewNode< TypeStruct >.live_use(), com.cliffc.aa.node.MrgProjNode.live_use(), com.cliffc.aa.node.DefMemNode.make_mem(), com.cliffc.aa.type.TypeMem.remove_no_escapes(), com.cliffc.aa.type.TypeMem.set(), com.cliffc.aa.type.TypeMem.slice_reaching_aliases(), com.cliffc.aa.type.TypeMem.st_new(), com.cliffc.aa.type.TypeMem.update(), com.cliffc.aa.node.MemJoinNode.value(), and com.cliffc.aa.node.CallEpiNode.value().
at() [2/2]
static TypeObj com.cliffc.aa.type.TypeMem.at (TypeObj[] tos, int alias) static package
Definition at line 136 of file TypeMem.java.
 { return tos.length==1 ? tos[0].oob(TypeObj.ISUSED): tos[at_idx(tos,alias)]; }
References com.cliffc.aa.type.TypeMem.at_idx(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.ISUSED, and com.cliffc.aa.type.Type< T extends Type< T >.oob().
at_idx()
static int com.cliffc.aa.type.TypeMem.at_idx (TypeObj[] tos, int alias) static package
Definition at line 138 of file TypeMem.java.
{
     if( alias==0 ) return 1;    // Either base memory, or assert
     while( true ) {
       if( alias < tos.length && tos[alias] != null )
         return alias;
       alias = BitsAlias.TREE.parent(alias);
       assert alias!=0;
     }
   }
References com.cliffc.aa.type.BitsAlias.TREE.
Referenced by com.cliffc.aa.type.TypeMem.at().
basic_live()
boolean com.cliffc.aa.type.TypeMem.basic_live ()
Definition at line 561 of file TypeMem.java.
 { return _pubs.length==1; }
References com.cliffc.aa.type.TypeMem._pubs.
Referenced by com.cliffc.aa.node.Node.live(), com.cliffc.aa.node.ProjNode.live_use(), com.cliffc.aa.node.CProjNode.live_use(), com.cliffc.aa.node.PhiNode.live_use(), com.cliffc.aa.node.ScopeNode.live_use(), com.cliffc.aa.node.CallNode.live_use(), and com.cliffc.aa.node.Node.live_uses().
check()
static boolean com.cliffc.aa.type.TypeMem.check (TypeObj[] as) static private
Definition at line 75 of file TypeMem.java.
{
     if( !(as[0] instanceof TypeLive) ) return false; // Slot 0 reserved for live-ness
     if( as.length == 1 ) return true;
     if( as[1]!=TypeObj.OBJ    && as[1]!=TypeObj.XOBJ   &&
         as[1]!=TypeObj.ISUSED && as[1]!=TypeObj.UNUSED &&
         !(as[1] instanceof TypeLive) &&
         as[1] != null )
       return false;             // Only 2 choices
     if( as[0].above_center()!=as[1].above_center() ) return false;
     if( as.length==2 ) return true; // Trivial all of memory
     // "tight" - something in the last slot
     if( as[as.length-1] == null ) return false;
     // No dups of any parent
     for( int i=2; i<as.length; i++ )
       if( as[i] != null )
         for( int par = BitsAlias.TREE.parent(i); par!=0; par = BitsAlias.TREE.parent(par) )
           if( as[par] != null ) {
             if( as[par] == as[i] ) return false; // Dup of a parent
             break;
           }
     return true;
   }
References com.cliffc.aa.type.TypeMem.above_center(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.ISUSED, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.OBJ, com.cliffc.aa.type.BitsAlias.TREE, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED, and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.XOBJ.
Referenced by com.cliffc.aa.type.TypeMem.init().
check_commute()
boolean com.cliffc.aa.type.Type< T extends Type< T >.check_commute (Type< TypeMem > t, Type< TypeMem > mt) private inherited
Definition at line 593 of file Type.java.
{
     if( t==this ) return true;
     if( is_simple() && !t.is_simple() ) return true; // By design, flipped the only allowed order
     Type mt2 = t.xmeet(this);   // Reverse args and try again
     // Also reverse names.
     Type nmt2 = t.xmt_name(this,mt2);
     if( mt==nmt2 ) return true;
     System.out.println("Meet not commutative: "+this+".meet("+t+")="+mt+",\n but "+t+".meet("+this+")="+nmt2);
     return false;
   }
check_name()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.check_name (String n) static package inherited
Definition at line 548 of file Type.java.
 { return n.isEmpty() || n.charAt(n.length()-1)==':'; }
check_startup()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.check_startup static package inherited
Definition at line 684 of file Type.java.
{
     Type[] ts = ALL_TYPES().asAry();
     // Confirm commutative & complete
     for( Type t0 : ts )
       for( Type t1 : ts ) {
         Type mt = t0.meet(t1);
         assert t0.check_commute  (t1,mt);
         assert t0.check_symmetric(t1,mt);
       }
     // Confirm associative
     int errs=0;
     for( Type t0 : ts )
       for( Type t1 : ts )
         for( Type t2 : ts ) {
           Type t01   = t0 .meet(t1 );
           Type t12   = t1 .meet(t2 );
           Type t01_2 = t01.meet(t2 );
           Type t0_12 = t0 .meet(t12);
           if( t01_2 != t0_12 && errs++ < 10 )
             System.err.println("("+t0+"&"+t1+") & "+t2+" == "+t0+" & ("+t1+" & "+t2+"); "+
                                "("+t01      +") & "+t2+" == "+t0+" & ("+t12        +"); "+
                                t01_2                  +" == "+t0_12);
         }
     assert errs==0 : "Found "+errs+" associative errors";
     // Confirm symmetry.  If A isa B, then A.join(C) isa B.join(C)
     for( Type t0 : ts )
       for( Type t1 : ts ) {
         if( t0.isa(t1) ) {
           for( Type t2 : ts ) {
             Type t02 = t0.join(t2);
             Type t12 = t1.join(t2);
             Type mt  = t02.meet(t12);
             if( mt != t12 && errs++ < 10 ) {
               System.err.println("("+t0+" ^ "+t2+") = "+t02+"; "+
                                  "("+t1+" ^ "+t2+") = "+t12+"; "+
                                  "their meet = "+mt+" which is not "+t12);
             }
           }
         }
       }
     assert errs==0 : "Found "+errs+" non-join-type errors";
     // Check scalar primitives; all are SCALARS and none sub-type each other.
     SCALAR_PRIMS = new Type[] { TypeInt.INT64, TypeFlt.FLT64, TypeMemPtr.OOP0, TypeFunPtr.GENERIC_FUNPTR, TypeRPC.ALL_CALL };
     for( Type t : SCALAR_PRIMS ) assert t.isa(SCALAR);
     for( int i=0; i<SCALAR_PRIMS.length; i++ )
       for( int j=i+1; j<SCALAR_PRIMS.length; j++ )
         assert !SCALAR_PRIMS[i].isa(SCALAR_PRIMS[j]);
     return true;
   }
check_symmetric()
boolean com.cliffc.aa.type.Type< T extends Type< T >.check_symmetric (Type< TypeMem > t, Type< TypeMem > mt) private inherited
Definition at line 608 of file Type.java.
{
     if( t==this ) return true;
     Type ta = mt._dual.meet(t._dual);
     Type tb = mt._dual.meet(  _dual);
     if( ta==t._dual && tb==_dual ) return true;
     System.err.print("("+this+" & "+t+")=="+mt+" but \n("+mt._dual+" & ");
     if( ta!=t._dual ) System.err.println(t._dual+")=="+ta+" \nwhich is not "+t._dual);
     else              System.err.println(  _dual+")=="+tb+" \nwhich is not "+  _dual);
     return false;
   }
clone()
Type com.cliffc.aa.type.Type< T extends Type< T >.clone protected inherited
Definition at line 304 of file Type.java.
{
     try {
       POOLS[_type]._clone++;
       Type t = (Type)super.clone();
       t._uid = _uid();
       t._dual = null;
       t._hash = 0;
       if( t instanceof TypeStruct )
         ((TypeStruct)t)._cyclic = false;
       return t;
     }
     catch( CloneNotSupportedException cns ) { throw new RuntimeException(cns); }
   }
compute_hash()
int com.cliffc.aa.type.TypeMem.compute_hash () package
Definition at line 97 of file TypeMem.java.
{
     int sum=TMEM;
     for( TypeObj obj : _pubs ) sum += obj==null ? 0 : obj._hash;
     return sum;
   }
References com.cliffc.aa.type.TypeMem._pubs, and com.cliffc.aa.type.Type< TypeMem >.TMEM.
concat()
static void com.cliffc.aa.type.Type< T extends Type< T >.concat (Ary< Type< TypeMem > > ts, Type< TypeMem >[] ts1) static package inherited
Definition at line 676 of file Type.java.
{
     for( Type t1 : ts1 ) {
       assert !t1.above_center(); // Always below-center or equal, because we'll dual anyways
       ts.push(t1);
       if( t1!=t1.dual() ) ts.push(t1.dual());
     }
   }
contains() [1/2]
final boolean com.cliffc.aa.type.Type< T extends Type< T >.contains (Type< TypeMem > t) inherited
Definition at line 926 of file Type.java.
 { return contains(t,null); }
contains() [2/2]
boolean com.cliffc.aa.type.Type< T extends Type< T >.contains (Type< TypeMem > t, VBitSet bs) package inherited
Definition at line 927 of file Type.java.
 { return this==t; }
cross_nil()
final Type com.cliffc.aa.type.Type< T extends Type< T >.cross_nil (Type< TypeMem > t) package inherited
Definition at line 865 of file Type.java.
 { return must_nil() || t.must_nil() ? SCALAR : NSCALR; }
crush()
TypeMem com.cliffc.aa.type.TypeMem.crush ()
Definition at line 425 of file TypeMem.java.
{
     TypeObj[] oops = _pubs.clone();
     oops[0] = null;
     for( int i=1; i<oops.length; i++ )
       if( oops[i]!=null ) oops[i] = oops[i].crush();
     return TypeMem.make0(oops);
   }
References com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.Type< T extends Type< T >.clone(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.crush(), and com.cliffc.aa.type.TypeMem.make0().
cycle_equals()
boolean com.cliffc.aa.type.TypeMem.cycle_equals (Type o)
Definition at line 113 of file TypeMem.java.
 { return equals(o); }
References com.cliffc.aa.type.TypeMem.equals().
dual()
final T com.cliffc.aa.type.Type< T extends Type< T >.dual inherited
Definition at line 361 of file Type.java.
 { return _dual; }
eq()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.eq (Type< TypeMem >[] t0, Type< TypeMem >[] t1) static inherited
Definition at line 136 of file Type.java.
{
     if( t0==t1 ) return true;
     if( t0==null || t1==null ) return false;
     if( t0.length != t1.length ) return false;
     for( int i=0; i<t0.length; i++ )
       if( t0[i] != t1[i] )
         return false;
     return true;
   }
equals()
boolean com.cliffc.aa.type.TypeMem.equals (Object o)
Definition at line 102 of file TypeMem.java.
{
     if( this==o ) return true;
     if( !(o instanceof TypeMem) ) return false;
     TypeMem tf = (TypeMem)o;
     if( _pubs .length != tf._pubs .length ) return false;
     for( int i = 0; i< _pubs.length; i++ )
       if( _pubs[i] != tf._pubs[i] ) // note '==' and NOT '.equals()'
         return false;
     return true;
   }
References com.cliffc.aa.type.TypeMem._pubs.
Referenced by com.cliffc.aa.type.TypeMem.cycle_equals().
flatten_fields()
TypeMem com.cliffc.aa.type.TypeMem.flatten_fields ()
Definition at line 522 of file TypeMem.java.
{
     TypeObj to, tof=null;
     int i; for( i=1; i< _pubs.length; i++ ) {
       if( (to = _pubs[i]) != null && (tof = to.flatten_fields())!=to )
         break;
     }
     if( i== _pubs.length ) return this;
     TypeObj[] tos = _pubs.clone();
     tos[0] = null;
     tos[i++] = tof;
     for( ; i< _pubs.length; i++ )
       if( tos[i] != null )
         tos[i] = tos[i].flatten_fields();
     return make0(tos);
   }
References com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.Type< T extends Type< T >.clone(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.flatten_fields(), and com.cliffc.aa.type.TypeMem.make0().
Referenced by com.cliffc.aa.node.ScopeNode.compute_live_mem(), com.cliffc.aa.node.ScopeNode.live_use(), and com.cliffc.aa.TestLive.testNewObj().
fld_is_mod()
boolean com.cliffc.aa.type.TypeMem.fld_is_mod (BitsAlias aliases, String fld)
Definition at line 508 of file TypeMem.java.
{
     for( int alias : aliases ) {
       if( alias != 0 ) {
         TypeObj to = at(alias);
         if( !(to instanceof TypeStruct) ) return true;
         TypeStruct ts = (TypeStruct)to;
         int idx = ts.fld_find(fld);
         if( idx == -1 || ts.fld(idx)._access != Access.Final )
           return true;          // Cannot check for R/O here, because R/O can lift to R/W
       }
     }
     return false;
   }
References com.cliffc.aa.type.TypeFld._access, com.cliffc.aa.type.TypeMem.aliases(), com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.type.TypeFld.Access.Final, com.cliffc.aa.type.TypeStruct.fld(), and com.cliffc.aa.type.TypeStruct.fld_find().
Referenced by com.cliffc.aa.node.LoadNode._find_previous_store_call().
getd()
double com.cliffc.aa.type.Type< T extends Type< T >.getd inherited
Definition at line 804 of file Type.java.
 { if( _type==TNIL || _type==TXNIL ) return 0.0; throw typerr(null); }
getl()
long com.cliffc.aa.type.Type< T extends Type< T >.getl inherited
Definition at line 802 of file Type.java.
 { if( _type==TNIL || _type==TXNIL ) return 0; throw typerr(null); }
getstr()
String com.cliffc.aa.type.Type< T extends Type< T >.getstr inherited
Definition at line 806 of file Type.java.
 { throw typerr(null); }
has_name()
boolean com.cliffc.aa.type.Type< T extends Type< T >.has_name inherited
Definition at line 549 of file Type.java.
 { return !_name.isEmpty(); }
has_used()
boolean com.cliffc.aa.type.TypeMem.has_used (BitSet aliases)
Definition at line 312 of file TypeMem.java.
{
     for( int alias = aliases.nextSetBit(0); alias != -1; alias = aliases.nextSetBit(alias + 1))
       if( at(alias)!= TypeObj.UNUSED )
         return true;            // Has a not-unused (some used) type
     return false;
   }
References com.cliffc.aa.type.TypeMem.aliases(), com.cliffc.aa.type.TypeMem.at(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED.
hashCode()
final int com.cliffc.aa.type.Type< T extends Type< T >.hashCode inherited
Definition at line 106 of file Type.java.
 { assert _hash!=0; return _hash; }
hashcons()
T com.cliffc.aa.type.Type< T extends Type< T >.hashcons private inherited
Definition at line 165 of file Type.java.
{
     _hash = compute_hash();     // Set hash
     T t2 = (T)INTERN.get(this); // Lookup
     if( t2!=null ) {            // Found prior
       assert t2._dual != null;  // Prior is complete with dual
       assert this != t2;        // Do not hashcons twice, should not get self back
       return t2;                // Return prior
     }
     if( RECURSIVE_MEET > 0 )    // Mid-building recursive types; do not intern
       return (T)this;
     // Not in type table
     _dual = null;                // No dual yet
     INTERN.put(this,this);       // Put in table without dual
     T d = xdual();               // Compute dual without requiring table lookup, and not setting name
     d._name = _name;             // xdual does not set name either
     d._hash = d.compute_hash();  // Set dual hash
     _dual = d;
     if( this==d ) return d;      // Self-symmetric?  Dual is self
     assert !equals(d);           // Self-symmetric is handled by caller
     assert d._dual==null;        // Else dual-dual not computed yet
     assert INTERN.get(d)==null;
     d._dual = (T)this;
     INTERN.put(d,d);
     return (T)this;
   }
hashcons_free()
final T com.cliffc.aa.type.Type< T extends Type< T >.hashcons_free package inherited
Definition at line 153 of file Type.java.
{
     T t2 = hashcons();
     return this==t2 ? t2 : (T)POOLS[_type].free(this,t2);
   }
high()
Type com.cliffc.aa.type.Type< T extends Type< T >.high inherited
Definition at line 796 of file Type.java.
 { return above_center() ? this : dual(); }
init() [1/2]
T com.cliffc.aa.type.Type< T extends Type< T >.init (byte type, String name) protected inherited
Definition at line 105 of file Type.java.
 { _type=type; _name=name; return (T)this; }
init() [2/2]
TypeMem com.cliffc.aa.type.TypeMem.init (TypeObj[] pubs) private
Definition at line 67 of file TypeMem.java.
{
     super.init(TMEM,"");
     assert check(pubs);    // Caller has canonicalized arrays already
     _pubs = pubs;
     return this;
   }
References com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.TypeMem.check(), com.cliffc.aa.type.TypeMem.init(), and com.cliffc.aa.type.Type< TypeMem >.TMEM.
Referenced by com.cliffc.aa.type.TypeMem.init(), com.cliffc.aa.type.TypeMem.make(), and com.cliffc.aa.type.TypeMem.xdual().
init0()
static void com.cliffc.aa.type.Type< T extends Type< T >.init0 (HashMap< String, Type< TypeMem > > types) static inherited
Definition at line 642 of file Type.java.
{
     types.put("real",REAL);
     types.put("scalar",SCALAR);
     TypeInt.init1(types);
     TypeFlt.init1(types);
     TypeStr.init1(types);
   }
intern_check()
static boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check static inherited
Definition at line 212 of file Type.java.
{
     int errs=0;
     for( Type k : INTERN.keySet() ) {
       Type v = INTERN.get(k);
       if( !k.intern_check0(v) ) {
         System.out.println("INTERN_CHECK FAIL: "+k._uid+":"+k+" vs "+v._uid+":"+v);
         errs++;
       }
     }
     return errs==0;
   }
intern_check0()
boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check0 (Type< TypeMem > v) private inherited
Definition at line 223 of file Type.java.
{
     if( this != v || _dual==null || _dual._dual!=this || compute_hash()!=_hash ) return false;
     return intern_check1();
   }
intern_check1()
boolean com.cliffc.aa.type.Type< T extends Type< T >.intern_check1 package inherited
Definition at line 227 of file Type.java.
 { return true; }
intern_find()
static Type com.cliffc.aa.type.Type< T extends Type< T >.intern_find (int uid) static package inherited
Definition at line 229 of file Type.java.
{
     for( Type k : INTERN.keySet() )
       if( k._uid==uid )
         return k;
     return null;
   }
intern_lookup()
Type com.cliffc.aa.type.Type< T extends Type< T >.intern_lookup package inherited
Definition at line 210 of file Type.java.
 { return INTERN.get(this); }
intern_size()
static int com.cliffc.aa.type.Type< T extends Type< T >.intern_size static package inherited
Definition at line 211 of file Type.java.
 { return INTERN.size(); }
interned()
boolean com.cliffc.aa.type.Type< T extends Type< T >.interned package inherited
Definition at line 209 of file Type.java.
 { return INTERN.get(this)==this; }
is_con()
boolean com.cliffc.aa.type.TypeMem.is_con ()
Definition at line 555 of file TypeMem.java.
 { return false;}
is_display()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_display package inherited
Definition at line 942 of file Type.java.
 { return false; }
is_display_ptr()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_display_ptr inherited
Definition at line 941 of file Type.java.
 { return _type==TSCALAR || _type==TXSCALAR || _type==TNIL || _type==TXNIL || _type==TANY || _type==TALL; }
is_forward_ref()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_forward_ref inherited
Definition at line 799 of file Type.java.
 { return false; }
is_live()
boolean com.cliffc.aa.type.TypeMem.is_live ()
Definition at line 560 of file TypeMem.java.
 { return _pubs.length>1 || (live()!=TypeLive.DEAD && live()!=TypeLive.LIVE.dual()); }
References com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.TypeLive.DEAD, com.cliffc.aa.type.TypeLive.LIVE, and com.cliffc.aa.type.TypeMem.live().
Referenced by com.cliffc.aa.node.Node.more_ideal().
is_num()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_num private inherited
Definition at line 353 of file Type.java.
 { byte t = _type;  return t == TREAL || t == TXREAL || t == TNREAL || t == TXNREAL || t == TINT || t == TFLT; }
is_ptr()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_ptr private inherited
Definition at line 352 of file Type.java.
 { byte t = _type;  return t == TFUNPTR || t == TMEMPTR; }
is_simple()
boolean com.cliffc.aa.type.Type< T extends Type< T >.is_simple private inherited
Definition at line 351 of file Type.java.
 { return _type < TSIMPLE; }
isa()
boolean com.cliffc.aa.type.Type< T extends Type< T >.isa (Type< TypeMem > t) inherited
Definition at line 623 of file Type.java.
 { return meet(t)==t; }
isa_scalar()
final boolean com.cliffc.aa.type.Type< T extends Type< T >.isa_scalar inherited
Definition at line 356 of file Type.java.
 { assert ISA_SCALAR.length==TLAST; return ISA_SCALAR[_type]!=0; }
isBitShape()
byte com.cliffc.aa.type.Type< T extends Type< T >.isBitShape (Type< TypeMem > t) inherited
Definition at line 814 of file Type.java.
{
     if( has_name() || t.has_name() ) throw com.cliffc.aa.AA.unimpl();
     if( _type == TNIL || _type==TXNIL ) return 0; // Nil is free to convert always
     if( above_center() && isa(t) ) return 0; // Can choose compatible format
     if( _type == t._type ) return 0; // Same type is OK
     if( t._type==TSCALAR ) return 0; // Generic function arg never requires a conversion
     if( _type == TALL || t._type==TALL || _type == TSCALAR || _type == TNSCALR ) return -1; // Scalar has to resolve
     if( (_type == TREAL || _type == TNREAL) && t.is_num() ) return -1; // Real->Int/Flt has to resolve
     if( t._type == TNIL || t._type == TXNIL ) return (byte)(may_nil() ? -1 : 99); // Must resolve to a NIL first
     throw typerr(t);  // Overridden in subtypes
   }
join()
Type com.cliffc.aa.type.Type< T extends Type< T >.join (Type< TypeMem > t) inherited
Definition at line 619 of file Type.java.
 { return dual().meet(t.dual()).dual(); }
ld() [1/2]
TypeObj com.cliffc.aa.type.TypeMem.ld (TypeMemPtr ptr)
Definition at line 325 of file TypeMem.java.
{
     if( ptr._aliases == BitsAlias.NIL.dual() || ptr._aliases == BitsAlias.NIL )
       return TypeObj.XOBJ;
     if( ptr._aliases == BitsAlias.EMPTY )
       return oob(TypeObj.OBJ);
     if( this== FULL ) return TypeObj. OBJ;
     if( this==EMPTY ) return TypeObj.XOBJ;
     return ld(_pubs,ptr._aliases);
   }
References com.cliffc.aa.type.TypeMemPtr._aliases, com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.Bits< B extends Bits< B >.dual(), com.cliffc.aa.type.BitsAlias.EMPTY, com.cliffc.aa.type.TypeMem.EMPTY, com.cliffc.aa.type.TypeMem.FULL, com.cliffc.aa.type.BitsAlias.NIL, com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.OBJ, com.cliffc.aa.type.Type< TypeMem >.oob(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.XOBJ.
Referenced by com.cliffc.aa.node.StoreNode.err(), com.cliffc.aa.node.LoadNode.err(), com.cliffc.aa.REPL.go_one(), com.cliffc.aa.node.StoreNode.ideal_reduce(), com.cliffc.aa.type.TypeMemPtr.make_from(), com.cliffc.aa.type.TypeMemPtr.str(), com.cliffc.aa.type.TestType.testOOPsNulls(), com.cliffc.aa.TestParse.testParse06(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.type.TestType.testStructTuple(), com.cliffc.aa.node.NewStrNode.AddStrStr.value(), and com.cliffc.aa.node.IntrinsicNode.value().
ld() [2/2]
static TypeObj com.cliffc.aa.type.TypeMem.ld (TypeObj[] tos, BitsAlias aliases) static private
Definition at line 334 of file TypeMem.java.
{
     boolean any = aliases.above_center();
     // Any alias, plus all of its children, are meet/joined.  This does a
     // tree-based scan on the inner loop.
     TypeObj obj1 = any ? TypeObj.ISUSED : TypeObj.UNUSED;
     for( int alias : aliases )
       for( int kid=alias; kid!=0; kid=BitsAlias.next_kid(alias,kid) ) {
         TypeObj x = at(tos,kid);
         obj1 = (TypeObj)(any ? obj1.join(x) : obj1.meet(x));
       }
     return obj1;
   }
References com.cliffc.aa.type.Bits< B extends Bits< B >.above_center(), com.cliffc.aa.type.TypeMem.aliases(), com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.ISUSED, com.cliffc.aa.type.Type< T extends Type< T >.join(), com.cliffc.aa.type.Type< T extends Type< T >.meet(), com.cliffc.aa.type.BitsAlias.next_kid(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED.
len()
int com.cliffc.aa.type.TypeMem.len ()
Definition at line 149 of file TypeMem.java.
 { return _pubs.length; }
References com.cliffc.aa.type.TypeMem._pubs.
Referenced by com.cliffc.aa.type.TypeMem._make1(), com.cliffc.aa.type.TypeMem._meet(), com.cliffc.aa.type.TypeMem.and_unused(), and com.cliffc.aa.node.CallEpiNode.value().
live()
TypeLive com.cliffc.aa.type.TypeMem.live ()
Definition at line 559 of file TypeMem.java.
 { return (TypeLive)_pubs[0]; }
References com.cliffc.aa.type.TypeMem._pubs.
Referenced by com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.type.TypeMem.is_live(), com.cliffc.aa.node.FunPtrNode.live(), com.cliffc.aa.node.MemJoinNode.live(), com.cliffc.aa.node.RetNode.live(), com.cliffc.aa.node.CallNode.live(), com.cliffc.aa.type.TypeMem.make_live(), and com.cliffc.aa.type.TypeMem.remove_no_escapes().
live_no_disp()
boolean com.cliffc.aa.type.TypeMem.live_no_disp ()
Definition at line 320 of file TypeMem.java.
{
     return this==TypeMem.LNO_DISP || this==TypeMem.LESC_NO_DISP || this==TypeMem.DEAD;
   }
References com.cliffc.aa.type.TypeMem.DEAD, com.cliffc.aa.type.TypeMem.LESC_NO_DISP, and com.cliffc.aa.type.TypeMem.LNO_DISP.
Referenced by com.cliffc.aa.node.LoadNode._live_use(), com.cliffc.aa.node.LoadNode.get_fld2(), and com.cliffc.aa.node.Node.walk_opt().
make() [1/4]
static TypeMem com.cliffc.aa.type.TypeMem.make (BitsAlias aliases, TypeObj oop) static
Definition at line 211 of file TypeMem.java.
{
     TypeObj[] as = new TypeObj[aliases.max()+1];
     as[1] = TypeObj.UNUSED;
     for( int alias : aliases )
       if( alias != 0 )
         as[alias] = oop;
     return make0(as);
   }
References com.cliffc.aa.type.TypeMem.aliases(), com.cliffc.aa.type.TypeMem.make0(), com.cliffc.aa.type.Bits< B extends Bits< B >.max(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED.
make() [2/4]
static Type com.cliffc.aa.type.Type< T extends Type< T >.make (byte type) static package inherited
Definition at line 147 of file Type.java.
{
     Pool P = POOLS[type];
     Type t1 = P.malloc();
     return t1.init(type,"").hashcons_free();
   }
make() [3/4]
static TypeMem com.cliffc.aa.type.TypeMem.make (int alias, TypeObj oop) static
Definition at line 205 of file TypeMem.java.
{
     TypeObj[] as = new TypeObj[alias+1];
     as[1] = TypeObj.UNUSED;
     as[alias] = oop;
     return make0(as);
   }
References com.cliffc.aa.type.TypeMem.make0(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED.
make() [4/4]
static TypeMem com.cliffc.aa.type.TypeMem.make (TypeObj[] pubs) static private
Definition at line 163 of file TypeMem.java.
{
     Pool P = POOLS[TMEM];
     TypeMem t1 = P.malloc();
     return t1.init(pubs).hashcons_free();
   }
References com.cliffc.aa.type.Type< T extends Type< T >.hashcons_free(), com.cliffc.aa.type.TypeMem.init(), com.cliffc.aa.type.Type< TypeMem >.POOLS, and com.cliffc.aa.type.Type< TypeMem >.TMEM.
Referenced by com.cliffc.aa.type.TypeMem.make0(), com.cliffc.aa.type.TypeMem.meet_loop(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.type.TypeMem.update(), and com.cliffc.aa.type.TypeMem.xmeet().
make0()
static TypeMem com.cliffc.aa.type.TypeMem.make0 (TypeObj[] as) static
Definition at line 170 of file TypeMem.java.
{
     assert as.length==1 || as[0]==null;
     if( as.length> 1 ) as[0] = as[1].oob(TypeLive.LIVE);
     TypeObj[] tos = _make1(as);
     if( tos==null ) return DEAD; // All things are dead, so dead
     return make(tos);
   }
References com.cliffc.aa.type.TypeMem._make1(), com.cliffc.aa.type.TypeMem.DEAD, com.cliffc.aa.type.TypeLive.LIVE, com.cliffc.aa.type.TypeMem.make(), and com.cliffc.aa.type.Type< T extends Type< T >.oob().
Referenced by com.cliffc.aa.type.TypeMem.crush(), com.cliffc.aa.type.TypeMem.flatten_fields(), com.cliffc.aa.type.TypeMem.make(), com.cliffc.aa.type.TypeMem.make_live(), com.cliffc.aa.type.TypeMem.remove(), com.cliffc.aa.type.TypeMem.remove_no_escapes(), com.cliffc.aa.type.TypeMem.set(), com.cliffc.aa.type.TypeMem.slice_reaching_aliases(), com.cliffc.aa.type.TypeMem.st_new(), com.cliffc.aa.type.TestType.testRecursive(), com.cliffc.aa.type.TestType.testStructTuple(), com.cliffc.aa.node.TestNodeSmall.tmem(), com.cliffc.aa.node.DefMemNode.value(), com.cliffc.aa.node.MemJoinNode.value(), com.cliffc.aa.node.CallEpiNode.value(), and com.cliffc.aa.type.TypeMem.widen().
make_from()
Type com.cliffc.aa.type.Type< T extends Type< T >.make_from (Type< TypeMem > head, TypeMem map, VBitSet visit) inherited
Definition at line 945 of file Type.java.
 { return this; }
make_live()
static TypeMem com.cliffc.aa.type.TypeMem.make_live (TypeLive live) static
Definition at line 220 of file TypeMem.java.
 { return make0(new TypeObj[]{live}); }
References com.cliffc.aa.type.TypeMem.live(), and com.cliffc.aa.type.TypeMem.make0().
Referenced by com.cliffc.aa.node.ConNode< T extends Type >.live().
may_be_con()
boolean com.cliffc.aa.type.TypeMem.may_be_con ()
Definition at line 554 of file TypeMem.java.
 { return false;}
may_nil()
boolean com.cliffc.aa.type.Type< T extends Type< T >.may_nil inherited
Definition at line 869 of file Type.java.
{
     switch(_type) {
     case TALL:
     case TREAL:
     case TSCALAR:
     case TXNSCALR: case TNSCALR:
     case TXNREAL:  case TNREAL:
     case TTUPLE:
       return false;
     case TANY:
     case TXREAL:
     case TXSCALAR:
     case TCTRL:  // Nonsense, only for IfNode.value test
     case TXCTRL: // Nonsense, only for IfNode.value test
     case TMEM:   // Nonsense, only for IfNode.value test
       return true;
     default: throw typerr(null); // Overridden in subclass
     }
   }
meet()
final Type com.cliffc.aa.type.Type< T extends Type< T >.meet (Type< TypeMem > t) inherited
Definition at line 412 of file Type.java.
{
     // Short cut for the self case
     if( t == this ) return this;
     // Short-cut for seeing this meet before
     Type mt = Key.get(this,t);
     if( mt != null ) return mt;
     // "Triangulate" the matrix and cut in half the number of cases.
     // Reverse; xmeet 2nd arg is never "is_simple" and never equal to "this".
     // This meet ignores the _name field, and can return any-old name it wants.
     mt = !is_simple() && t.is_simple() ? t.xmeet(this) : xmeet(t);
     // Meet the names.  Subclasses basically ignore the names as they have
     // their own complicated meets to perform, so we meet them here for all.
     Type nmt = xmt_name(t,mt);
     // Quick check on NIL: if either argument is NIL the result is allowed to
     // be NIL...  but nobody in the lattice can make a NIL from whole cloth, or
     // we get the crossing-nil bug.
     assert (nmt != NIL && nmt!=XNIL) || this==NIL || this==XNIL || t==NIL || t==XNIL;
     // Record this meet, to short-cut next time
     if( RECURSIVE_MEET == 0 )   // Only not mid-building recursive types;
       Key.put(this,t,nmt);
     return nmt;
   }
meet_loop()
Type com.cliffc.aa.type.TypeMem.meet_loop (Type t2)
Definition at line 302 of file TypeMem.java.
{
     if( t2._type != TMEM ) return ALL;
     TypeMem tf = (TypeMem)t2;
     // Meet of default values, meet of element-by-element.
     TypeObj[] as = _meet(_pubs,tf._pubs,true);
     TypeObj[] tos = _make1(as);
     return tos==null ? DEAD : make(tos); // All things are dead, so dead
   }
References com.cliffc.aa.type.TypeMem._make1(), com.cliffc.aa.type.TypeMem._meet(), com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.type.Type< TypeMem >.ALL, com.cliffc.aa.type.TypeMem.DEAD, com.cliffc.aa.type.TypeMem.make(), and com.cliffc.aa.type.Type< TypeMem >.TMEM.
meet_nil()
Type com.cliffc.aa.type.Type< T extends Type< T >.meet_nil (Type< TypeMem > nil) inherited
Definition at line 904 of file Type.java.
{
     assert nil==NIL || nil==XNIL;
     switch( _type ) {
     case TANY:
     case TXREAL:
     case TXSCALAR:
     case TXNIL:   return nil; // Preserve high/low flavor
     case TNIL:    return NIL;
     case TXNREAL:
     case TXNSCALR:  return TypeInt.BOOL;
     case TREAL:   case TNREAL:    return REAL;
     case TSCALAR: case TNSCALR:   return SCALAR;
     case TCTRL:   case TXCTRL:
     case TOBJ:
     case TSTR:
     case TSTRUCT:
     case TMEM:      return ALL;
     default:        throw typerr(null); // Overridden in subclass
     }
   }
mtname()
final String com.cliffc.aa.type.Type< T extends Type< T >.mtname (Type< TypeMem > t, Type< TypeMem > mt) package inherited
Definition at line 567 of file Type.java.
{
     Type   t0 = this,  t1 = t;
     String s0 = t0._name, s1 = t1._name;
     assert check_name(s0) && check_name(s1);
     if( Util.eq(s0,s1) ) return s0;
     // Sort by name length
     if( s0.length() > s1.length() ) { t1=this; t0=t; s0=t0._name; s1=t1._name; }
     int x = 0, i;  char c;    // Last colon separator index
     // Find split point
     for( i = 0; i < s0.length(); i++ ) {
       if( (c=s0.charAt(i)) != s1.charAt(i) )
         break;
       if( c==':' ) x=i;
     }
     // If s0 is a prefix of s1, and s0 is high then it can cover s1.
     if( i==s0.length() && t0.above_center() && (!t1.above_center() || mt.above_center()) )
       return s1;
     // Keep the common prefix, which might be all of s0
     String s2 = i==s0.length() ? s0 : s0.substring(0, x).intern();
     assert check_name(s2);
     return s2;
   }
must_nil()
boolean com.cliffc.aa.type.TypeMem.must_nil ()
Definition at line 556 of file TypeMem.java.
 { return false; } // never a nil
not_nil()
Type com.cliffc.aa.type.TypeMem.not_nil () package
Definition at line 557 of file TypeMem.java.
 { return this; }
oob() [1/6]
Type com.cliffc.aa.type.Type< T extends Type< T >.oob inherited
Definition at line 635 of file Type.java.
 { return oob(ALL); }
oob() [2/6]
Type com.cliffc.aa.type.Type< T extends Type< T >.oob (Type< TypeMem > e) inherited
Definition at line 636 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [3/6]
TypeMem com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeMem e) inherited
Definition at line 639 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [4/6]
TypeMemPtr com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeMemPtr e) inherited
Definition at line 640 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob() [5/6]
TypeObj com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeObj e) inherited
Definition at line 637 of file Type.java.
 { return above_center() ? (TypeObj)e.dual() : e; }
oob() [6/6]
TypeStruct com.cliffc.aa.type.Type< T extends Type< T >.oob (TypeStruct e) inherited
Definition at line 638 of file Type.java.
 { return above_center() ? e.dual() : e; }
oob_deep()
Type com.cliffc.aa.type.Type< T extends Type< T >.oob_deep (Type< TypeMem > t) inherited
Definition at line 632 of file Type.java.
 { return oop_deep_impl(t); }
oop_deep_impl()
Type com.cliffc.aa.type.Type< T extends Type< T >.oop_deep_impl (Type< TypeMem > t) inherited
Definition at line 634 of file Type.java.
 { return oob(); }
rdual()
T com.cliffc.aa.type.Type< T extends Type< T >.rdual package inherited
Definition at line 366 of file Type.java.
 { assert _dual!=null; return _dual; }
remove()
TypeMem com.cliffc.aa.type.TypeMem.remove (BitsAlias escs)
Definition at line 487 of file TypeMem.java.
{
     if( escs==BitsAlias.EMPTY ) return this;
     if( escs==BitsAlias.FULL  ) throw com.cliffc.aa.AA.unimpl(); // Shortcut
     TypeObj[] tos = _pubs.clone();
     for( int i = 1; i< _pubs.length; i++ )
       if( escs.test(i) )
         tos[i] = TypeObj.UNUSED;
     return make0(tos);
   }
References com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.Type< T extends Type< T >.clone(), com.cliffc.aa.type.BitsAlias.EMPTY, com.cliffc.aa.type.BitsAlias.FULL, com.cliffc.aa.type.TypeMem.make0(), com.cliffc.aa.AA.unimpl(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED.
remove_name()
final T com.cliffc.aa.type.Type< T extends Type< T >.remove_name inherited
Definition at line 556 of file Type.java.
 { return has_name() ? _set_name("") : (T)this; }
remove_no_escapes()
TypeMem com.cliffc.aa.type.TypeMem.remove_no_escapes (BitsAlias escs, String fld, Type live)
Definition at line 479 of file TypeMem.java.
{
     TypeObj[] tos = new TypeObj[Math.max(_pubs.length,escs.max()+1)];
     for( int i=1; i<tos.length; i++ )
       tos[i] = escs.test_recur(i) ? at(i).remove_other_flds(fld,live) : TypeObj.UNUSED;
     return make0(tos);
   }
References com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.type.TypeMem.live(), com.cliffc.aa.type.TypeMem.make0(), com.cliffc.aa.type.Bits< B extends Bits< B >.max(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.remove_other_flds(), com.cliffc.aa.type.Bits< B extends Bits< B >.test_recur(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED.
Referenced by com.cliffc.aa.node.NewStrNode.AddStrStr.live_use().
repeats_in_cycles()
TypeStruct com.cliffc.aa.type.Type< T extends Type< T >.repeats_in_cycles (TypeStruct head, VBitSet bs) package inherited
Definition at line 938 of file Type.java.
 { return null; }
retern()
final T com.cliffc.aa.type.Type< T extends Type< T >.retern package inherited
Definition at line 201 of file Type.java.
                     {
     assert _dual._dual == this;
     assert _hash != 0;
     assert INTERN.get(this)==null;
     INTERN.put(this,this);
     assert INTERN.get(this)==this;
     return (T)this;
   }
set()
TypeMem com.cliffc.aa.type.TypeMem.set (int alias, TypeObj obj)
Definition at line 434 of file TypeMem.java.
{
     if( at(alias)==obj ) return this; // Shortcut
     int max = Math.max(_pubs.length,alias+1);
     TypeObj[] tos = Arrays.copyOf(_pubs,max);
     tos[0] = null;
     tos[alias] = obj;
     return make0(tos);
   }
References com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.TypeMem.at(), and com.cliffc.aa.type.TypeMem.make0().
Referenced by com.cliffc.aa.node.ConTypeNode.value(), com.cliffc.aa.node.MrgProjNode.value(), and com.cliffc.aa.node.IntrinsicNode.value().
set_name()
final T com.cliffc.aa.type.Type< T extends Type< T >.set_name (String name) inherited
Definition at line 551 of file Type.java.
{
     assert check_name(name);
     return _set_name(name);
   }
sharp_get()
TypeMemPtr com.cliffc.aa.type.TypeMem.sharp_get (TypeMemPtr tmp) package
Definition at line 411 of file TypeMem.java.
 { return _sharp_cache==null ? null : _sharp_cache.get(tmp); }
References com.cliffc.aa.type.TypeMem._sharp_cache.
Referenced by com.cliffc.aa.type.TypeStruct._dull(), com.cliffc.aa.type.TypeStruct._sharp(), and com.cliffc.aa.type.TypeStruct.sharpen().
sharpen()
TypeMemPtr com.cliffc.aa.type.TypeMem.sharpen (TypeMemPtr dull)
Definition at line 402 of file TypeMem.java.
{
     assert dull==dull.simple_ptr();
     if( _sharp_cache != null ) { // Check the cache first
       TypeMemPtr sharp = _sharp_cache.get(dull);
       if( sharp != null ) return sharp;
     }
     // Switch to TypeStruct for building recursive structures.
     return TypeStruct.sharpen(this,dull);
   }
References com.cliffc.aa.type.TypeMem._sharp_cache, com.cliffc.aa.type.TypeStruct.sharpen(), and com.cliffc.aa.type.TypeMemPtr.simple_ptr().
Referenced by com.cliffc.aa.type.TypeMem.sharptr(), and com.cliffc.aa.TestParse.testParse07().
sharptr()
Type com.cliffc.aa.type.TypeMem.sharptr (Type ptr)
Definition at line 419 of file TypeMem.java.
{
     return ptr instanceof TypeMemPtr ? sharpen((TypeMemPtr)ptr) :
       (ptr instanceof TypeTuple ? ((TypeTuple)ptr).sharptr(this) : ptr);
   }
References com.cliffc.aa.type.TypeMem.sharpen(), and com.cliffc.aa.type.TypeTuple.sharptr().
Referenced by com.cliffc.aa.type.TypeTuple.sharptr(), and com.cliffc.aa.type.Type< TypeFlt >.sharptr().
sharput()
TypeMemPtr com.cliffc.aa.type.TypeMem.sharput (TypeMemPtr dull, TypeMemPtr sharp) package
Definition at line 412 of file TypeMem.java.
{
     assert dull.interned() && sharp.interned();
     if( _sharp_cache==null ) _sharp_cache = new HashMap<>();
     _sharp_cache.put(dull,sharp);
     return sharp;               // return new not old
   }
References com.cliffc.aa.type.TypeMem._sharp_cache, and com.cliffc.aa.type.Type< T extends Type< T >.interned().
Referenced by com.cliffc.aa.type.TypeStruct._dull(), com.cliffc.aa.type.TypeStruct._sharp(), and com.cliffc.aa.type.TypeStruct.sharpen().
simple_ptr()
Type com.cliffc.aa.type.Type< T extends Type< T >.simple_ptr inherited
Definition at line 358 of file Type.java.
 { return this; }
slice_reaching_aliases()
TypeMem com.cliffc.aa.type.TypeMem.slice_reaching_aliases (BitsAlias aliases)
Definition at line 392 of file TypeMem.java.
{
     if( aliases==BitsAlias.FULL ) return this;
     TypeObj[] tos = new TypeObj[Math.max(_pubs.length,aliases.max()+1)];
     tos[1] = at(1);
     for( int i=2; i<tos.length; i++ )
       tos[i] = aliases.test_recur(i) ? at(i) : TypeObj.UNUSED;
     return make0(tos);
   }
References com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.TypeMem.aliases(), com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.type.BitsAlias.FULL, com.cliffc.aa.type.TypeMem.make0(), com.cliffc.aa.type.Bits< B extends Bits< B >.max(), com.cliffc.aa.type.Bits< B extends Bits< B >.test_recur(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.UNUSED.
Referenced by com.cliffc.aa.node.ScopeNode.compute_live_mem(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.node.MemSplitNode.value(), and com.cliffc.aa.node.CallNode.value().
st_new()
TypeMem com.cliffc.aa.type.TypeMem.st_new (int alias, TypeObj obj)
Definition at line 446 of file TypeMem.java.
{
     TypeObj[] pubs  = _pubs ;
     TypeObj pub  = at(pubs ,alias); // Current value for alias
     if( pub==obj ) return this;     // Shortcut
     (pubs = _st_new(_pubs,pubs,alias))[alias] = (TypeObj)pub.meet(obj);
     pubs[0] = null;
     return make0(pubs);
   }
References com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.TypeMem._st_new(), com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.type.TypeMem.make0(), and com.cliffc.aa.type.Type< T extends Type< T >.meet().
Referenced by com.cliffc.aa.node.MrgProjNode.value().
str()
SB com.cliffc.aa.type.TypeMem.str (SB sb, VBitSet dups, TypeMem mem, boolean debug)
Definition at line 115 of file TypeMem.java.
{
     if( this==FULL ) return sb.p("[ all ]");
     if( this==EMPTY) return sb.p("[_____]");
     if( this== MEM ) return sb.p("[ mem ]");
     if( this==XMEM ) return sb.p("[~mem ]");
     if( _pubs.length==1 )
       return _pubs[0].str(sb.p('['),dups,mem,debug).p(']');
     if( _pubs[0]==TypeLive.DEAD ) sb.p('!');
     else _pubs[0].str(sb,dups,mem,debug);
     sb.p('[');
     for( int i = 1; i< _pubs.length; i++ )
       if( _pubs[i] != null )
         _pubs[i].str(sb.p(i).p(':'),dups,mem,debug).p(",");
     return sb.unchar().p(']');
   }
References com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.TypeLive.DEAD, com.cliffc.aa.type.TypeMem.EMPTY, com.cliffc.aa.type.TypeMem.FULL, com.cliffc.aa.type.TypeMem.MEM, com.cliffc.aa.util.SB.p(), com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.str(), com.cliffc.aa.util.SB.unchar(), and com.cliffc.aa.type.TypeMem.XMEM.
toString()
final String com.cliffc.aa.type.Type< T extends Type< T >.toString inherited
Definition at line 127 of file Type.java.
 { return str(new SB(),new VBitSet(),null,true).toString(); }
typerr()
RuntimeException com.cliffc.aa.type.Type< T extends Type< T >.typerr (Type< TypeMem > t) package inherited
Definition at line 947 of file Type.java.
{
     throw new RuntimeException("Should not reach here: internal type system error with "+this+(t==null?"":(" and "+t)));
   }
untern()
final T com.cliffc.aa.type.Type< T extends Type< T >.untern package inherited
Definition at line 193 of file Type.java.
                     {
     assert _hash != 0;
     assert INTERN.get(this)==this;
     Type rez = INTERN.remove(this);
     assert rez == this;
     return (T)this;
   }
update() [1/2]
TypeMem com.cliffc.aa.type.TypeMem.update (BitsAlias aliases, Access fin, String fld, Type val)
Definition at line 459 of file TypeMem.java.
{
     Ary<TypeObj> pubs  = new Ary<>(_pubs .clone());
     for( int alias : aliases )
       if( alias != 0 )
         for( int kid=alias; kid != 0; kid=BitsAlias.next_kid(alias,kid) )
           pubs.setX(kid,at(_pubs,kid).update(fin,fld,val)); // imprecise
     return make(_make1(pubs.asAry()));
   }
References com.cliffc.aa.type.TypeMem._make1(), com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.TypeMem.aliases(), com.cliffc.aa.util.Ary< E >.asAry(), com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.type.Type< TypeMem >.clone(), com.cliffc.aa.type.TypeMem.make(), com.cliffc.aa.type.BitsAlias.next_kid(), and com.cliffc.aa.util.Ary< E >.setX().
Referenced by com.cliffc.aa.type.TypeMem.update(), com.cliffc.aa.node.StoreNode.value(), com.cliffc.aa.node.MemPrimNode.LValueWrite.value(), and com.cliffc.aa.node.MemPrimNode.LValueWriteFinal.value().
update() [2/2]
TypeMem com.cliffc.aa.type.TypeMem.update (BitsAlias aliases, TypeInt idx, Type val)
Definition at line 469 of file TypeMem.java.
{
     Ary<TypeObj> pubs  = new Ary<>(_pubs .clone());
     for( int alias : aliases )
       if( alias != 0 )
         for( int kid=alias; kid != 0; kid=BitsAlias.next_kid(alias,kid) )
           pubs.setX(kid,at(_pubs,kid).update(idx,val)); // imprecise
     return make(_make1(pubs.asAry()));
   }
References com.cliffc.aa.type.TypeMem._make1(), com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.TypeMem.aliases(), com.cliffc.aa.util.Ary< E >.asAry(), com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.type.Type< TypeMem >.clone(), com.cliffc.aa.type.TypeMem.make(), com.cliffc.aa.type.BitsAlias.next_kid(), com.cliffc.aa.util.Ary< E >.setX(), and com.cliffc.aa.type.TypeMem.update().
walk()
void com.cliffc.aa.type.Type< T extends Type< T >.walk (Predicate< Type< TypeMem > > p) inherited
Definition at line 936 of file Type.java.
 { assert is_simple(); p.test(this); }
widen()
TypeMem com.cliffc.aa.type.TypeMem.widen ()
Definition at line 539 of file TypeMem.java.
{
     TypeObj[] tos = _pubs.clone();
     tos[0] = null;
     for( int i=1; i<tos.length; i++ )
       if( tos[i]!=null )
         tos[i] = tos[i].widen();
     return make0(tos);
   }
References com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.Type< T extends Type< T >.clone(), com.cliffc.aa.type.TypeMem.make0(), and com.cliffc.aa.type.TypeObj< O extends TypeObj< O >.widen().
xdual()
TypeMem com.cliffc.aa.type.TypeMem.xdual () protected
Definition at line 264 of file TypeMem.java.
{
     TypeObj[] pubs = new TypeObj[_pubs.length];
     for( int i = 0; i< _pubs.length; i++ )
       if( _pubs[i] != null )
         pubs[i] = (TypeObj) _pubs[i].dual();
     return new TypeMem().init(pubs);
   }
References com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.Type< TypeMem >.dual(), and com.cliffc.aa.type.TypeMem.init().
xmeet()
Type com.cliffc.aa.type.TypeMem.xmeet (Type t) protected
Definition at line 271 of file TypeMem.java.
{
     if( t._type != TMEM ) return ALL;
     TypeMem tf = (TypeMem)t;
     // Meet of default values, meet of element-by-element.
     TypeObj[] as = _meet(_pubs,tf._pubs,false);
     TypeObj[] tos = _make1(as);
     return tos==null ? DEAD : make(tos); // All things are dead, so dead
   }
References com.cliffc.aa.type.TypeMem._make1(), com.cliffc.aa.type.TypeMem._meet(), com.cliffc.aa.type.TypeMem._pubs, com.cliffc.aa.type.Type< T extends Type< T >._type, com.cliffc.aa.type.Type< TypeMem >.ALL, com.cliffc.aa.type.TypeMem.DEAD, com.cliffc.aa.type.TypeMem.make(), and com.cliffc.aa.type.Type< TypeMem >.TMEM.
xmt_name()
Type com.cliffc.aa.type.Type< T extends Type< T >.xmt_name (Type< TypeMem > t, Type< TypeMem > mt) private inherited
Definition at line 441 of file Type.java.
{
     String n = mtname(t,mt);    // Meet name strings
     // If the names are incompatible and the meet remained high then the
     // mismatched names force a drop.
     if( n.length() < _name.length() && n.length() < t._name.length() && mt.above_center() ) {
       if( mt.interned() ) // recursive type creation?
         mt = mt.dual();   // Force low
     }
     if( mt.is_simple() ) n=""; // No named simple types
     if( mt._type==TOBJ ) n=""; // OBJ splits into strings (arrays) and structs, which can keep their names
     // Inject the name
     if( !Util.eq(mt._name,n) )  // Fast path cutout
       mt = mt.set_name(n);
     return mt;
   }
Member Data Documentation
_dual
T com.cliffc.aa.type.Type< T extends Type< T >._dual package inherited
Definition at line 100 of file Type.java.
_hash
int com.cliffc.aa.type.Type< T extends Type< T >._hash inherited
Definition at line 97 of file Type.java.
_name
String com.cliffc.aa.type.Type< T extends Type< T >._name inherited
Definition at line 99 of file Type.java.
_pubs
TypeObj [] com.cliffc.aa.type.TypeMem._pubs private
Definition at line 58 of file TypeMem.java.
Referenced by com.cliffc.aa.type.TypeMem.above_center(), com.cliffc.aa.type.TypeMem.alias2objs(), com.cliffc.aa.type.TypeMem.aliases(), com.cliffc.aa.type.TypeMem.and_unused(), com.cliffc.aa.type.TypeMem.at(), com.cliffc.aa.type.TypeMem.basic_live(), com.cliffc.aa.type.TypeMem.compute_hash(), com.cliffc.aa.type.TypeMem.crush(), com.cliffc.aa.type.TypeMem.equals(), com.cliffc.aa.type.TypeMem.flatten_fields(), com.cliffc.aa.type.TypeMem.init(), com.cliffc.aa.type.TypeMem.is_live(), com.cliffc.aa.type.TypeMem.ld(), com.cliffc.aa.type.TypeMem.len(), com.cliffc.aa.type.TypeMem.live(), com.cliffc.aa.type.TypeMem.meet_loop(), com.cliffc.aa.type.TypeMem.remove(), com.cliffc.aa.type.TypeMem.remove_no_escapes(), com.cliffc.aa.type.TypeMem.set(), com.cliffc.aa.type.TypeMem.slice_reaching_aliases(), com.cliffc.aa.type.TypeMem.st_new(), com.cliffc.aa.type.TypeMem.str(), com.cliffc.aa.type.TypeMem.update(), com.cliffc.aa.type.TypeMem.widen(), com.cliffc.aa.type.TypeMem.xdual(), and com.cliffc.aa.type.TypeMem.xmeet().
_sharp_cache
HashMap<TypeMemPtr,TypeMemPtr> com.cliffc.aa.type.TypeMem._sharp_cache private
Definition at line 65 of file TypeMem.java.
Referenced by com.cliffc.aa.type.TypeMem.sharp_get(), com.cliffc.aa.type.TypeMem.sharpen(), and com.cliffc.aa.type.TypeMem.sharput().
_type
byte com.cliffc.aa.type.Type< T extends Type< T >._type package inherited
Definition at line 98 of file Type.java.
_uid
int com.cliffc.aa.type.Type< T extends Type< T >._uid inherited
Definition at line 96 of file Type.java.
ALIVE
final TypeMem com.cliffc.aa.type.TypeMem.ALIVE static package
Definition at line 226 of file TypeMem.java.
Referenced by com.cliffc.aa.node.MemPrimNode.LValueLength._live_use(), com.cliffc.aa.node.LoadNode._live_use(), com.cliffc.aa.node.ThunkNode.all_live(), com.cliffc.aa.node.CProjNode.all_live(), com.cliffc.aa.node.ConNode< T extends Type >.all_live(), com.cliffc.aa.node.IfNode.all_live(), com.cliffc.aa.node.ConTypeNode.all_live(), com.cliffc.aa.node.RegionNode.all_live(), com.cliffc.aa.node.ErrNode.live_use(), com.cliffc.aa.node.ThretNode.live_use(), com.cliffc.aa.node.ThunkNode.live_use(), com.cliffc.aa.node.DefMemNode.live_use(), com.cliffc.aa.node.ProjNode.live_use(), com.cliffc.aa.node.CProjNode.live_use(), com.cliffc.aa.node.FreshNode.live_use(), com.cliffc.aa.node.NewStrNode.ConvertI64Str.live_use(), com.cliffc.aa.node.NewStrNode.ConvertF64Str.live_use(), com.cliffc.aa.node.CastNode.live_use(), com.cliffc.aa.node.MemPrimNode.ReadPrimNode.live_use(), com.cliffc.aa.node.NewStrNode.AddStrStr.live_use(), com.cliffc.aa.node.PhiNode.live_use(), com.cliffc.aa.node.IntrinsicNode.live_use(), com.cliffc.aa.node.StoreNode.live_use(), com.cliffc.aa.node.RegionNode.live_use(), com.cliffc.aa.node.ScopeNode.live_use(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.live_use(), com.cliffc.aa.node.RetNode.live_use(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.node.PrimNode.AndThen.live_use(), com.cliffc.aa.node.PrimNode.OrElse.live_use(), and com.cliffc.aa.TestLive.testNewObj().
ALL
final Type com.cliffc.aa.type.Type< T extends Type< T >.ALL static inherited
Definition at line 324 of file Type.java.
ALL_TYPES
Ary<Type> com.cliffc.aa.type.Type< T extends Type< T >.ALL_TYPES static private inherited
Definition at line 650 of file Type.java.
ALLMEM
final TypeMem com.cliffc.aa.type.TypeMem.ALLMEM static package
Definition at line 228 of file TypeMem.java.
Referenced by com.cliffc.aa.node.MemPrimNode.LValueLength._live_use(), com.cliffc.aa.node.LoadNode._live_use(), com.cliffc.aa.node.StartMemNode.all_live(), com.cliffc.aa.node.ThretNode.all_live(), com.cliffc.aa.node.DefMemNode.all_live(), com.cliffc.aa.node.MemSplitNode.all_live(), com.cliffc.aa.node.MProjNode.all_live(), com.cliffc.aa.node.NewNode< TypeStruct >.all_live(), com.cliffc.aa.node.MrgProjNode.all_live(), com.cliffc.aa.node.PhiNode.all_live(), com.cliffc.aa.node.IntrinsicNode.all_live(), com.cliffc.aa.node.ScopeNode.all_live(), com.cliffc.aa.node.StoreNode.all_live(), com.cliffc.aa.node.MemJoinNode.all_live(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.all_live(), com.cliffc.aa.node.RetNode.all_live(), com.cliffc.aa.node.CallEpiNode.all_live(), com.cliffc.aa.node.CallNode.all_live(), com.cliffc.aa.node.PrimNode.AndThen.all_live(), com.cliffc.aa.node.PrimNode.OrElse.all_live(), com.cliffc.aa.node.ScopeNode.compute_live_mem(), com.cliffc.aa.node.NewStrNode.ConStr.ConStr(), com.cliffc.aa.node.NewStrNode.ConvertF64Str.ConvertF64Str(), com.cliffc.aa.node.NewStrNode.ConvertI64Str.ConvertI64Str(), com.cliffc.aa.Parse.gather_errors(), com.cliffc.aa.node.PhiNode.is_mem(), com.cliffc.aa.node.ThretNode.live(), com.cliffc.aa.node.ScopeNode.live(), com.cliffc.aa.node.RetNode.live(), com.cliffc.aa.node.CallNode.live(), com.cliffc.aa.node.ThunkNode.live_use(), com.cliffc.aa.node.MemPrimNode.ReadPrimNode.live_use(), com.cliffc.aa.node.NewStrNode.AddStrStr.live_use(), com.cliffc.aa.node.ScopeNode.live_use(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.node.PrimNode.AndThen.live_use(), com.cliffc.aa.node.PrimNode.OrElse.live_use(), com.cliffc.aa.type.TypeTuple.make(), com.cliffc.aa.type.TypeTuple.make_args(), com.cliffc.aa.node.NewAryNode.NewAryNode(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.NewPrimNode(), com.cliffc.aa.node.PhiNode.PhiNode(), com.cliffc.aa.node.PrimNode.PrimNode(), com.cliffc.aa.type.TestType.testLoad(), com.cliffc.aa.node.ThretNode.ThretNode(), com.cliffc.aa.Parse.type0(), com.cliffc.aa.node.DefMemNode.value(), com.cliffc.aa.node.StoreNode.value(), com.cliffc.aa.node.MemJoinNode.value(), com.cliffc.aa.node.RetNode.value(), and com.cliffc.aa.node.CallEpiNode.value().
ANY
final Type com.cliffc.aa.type.Type< T extends Type< T >.ANY static inherited
Definition at line 325 of file Type.java.
ANYMEM
final TypeMem com.cliffc.aa.type.TypeMem.ANYMEM static
Definition at line 228 of file TypeMem.java.
Referenced by com.cliffc.aa.node.MemPrimNode.LValueLength._live_use(), com.cliffc.aa.node.LoadNode._live_use(), com.cliffc.aa.node.ScopeNode.compute_live_mem(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.ProjNode.live_use(), com.cliffc.aa.node.CProjNode.live_use(), com.cliffc.aa.node.FP2DispNode.live_use(), com.cliffc.aa.node.PhiNode.live_use(), com.cliffc.aa.node.FunPtrNode.live_use(), com.cliffc.aa.node.ScopeNode.live_use(), com.cliffc.aa.type.TypeTuple.make_ret(), com.cliffc.aa.type.Type< TypeFlt >.sharptr(), com.cliffc.aa.TestLive.testBasic(), com.cliffc.aa.type.TestType.testLoad(), com.cliffc.aa.TestLive.testNewObj(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.node.DefMemNode.value(), com.cliffc.aa.node.StartMemNode.value(), com.cliffc.aa.node.MemJoinNode.value(), com.cliffc.aa.node.CallEpiNode.value(), and com.cliffc.aa.node.CallNode.value().
CNT
int com.cliffc.aa.type.Type< T extends Type< T >.CNT static private inherited
Definition at line 95 of file Type.java.
CTRL
final Type com.cliffc.aa.type.Type< T extends Type< T >.CTRL static inherited
Definition at line 326 of file Type.java.
DEAD
final TypeMem com.cliffc.aa.type.TypeMem.DEAD static
Definition at line 226 of file TypeMem.java.
Referenced by com.cliffc.aa.node.MemPrimNode.LValueLength._live_use(), com.cliffc.aa.node.LoadNode._live_use(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.node.FunNode.ideal_reduce(), com.cliffc.aa.node.Node.init1(), com.cliffc.aa.node.ScopeNode.live(), com.cliffc.aa.node.Node.live(), com.cliffc.aa.type.TypeMem.live_no_disp(), com.cliffc.aa.node.DefMemNode.live_use(), com.cliffc.aa.node.MProjNode.live_use(), com.cliffc.aa.node.NewNode< TypeStruct >.live_use(), com.cliffc.aa.node.MrgProjNode.live_use(), com.cliffc.aa.node.PhiNode.live_use(), com.cliffc.aa.node.MemPrimNode.LValueLength.live_use(), com.cliffc.aa.node.FunPtrNode.live_use(), com.cliffc.aa.node.NewObjNode.live_use(), com.cliffc.aa.node.ScopeNode.live_use(), com.cliffc.aa.node.LoadNode.live_use(), com.cliffc.aa.node.CallEpiNode.live_use(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.node.CallNode.live_use_call(), com.cliffc.aa.node.Node.live_uses(), com.cliffc.aa.type.TypeMem.make0(), com.cliffc.aa.type.TypeMem.meet_loop(), com.cliffc.aa.node.DefMemNode.value(), com.cliffc.aa.node.Node.walk_initype(), and com.cliffc.aa.type.TypeMem.xmeet().
EMPTY
final TypeMem com.cliffc.aa.type.TypeMem.EMPTY static
Definition at line 223 of file TypeMem.java.
Referenced by com.cliffc.aa.type.TypeMem.aliases(), com.cliffc.aa.node.RetNode.ideal_reduce(), com.cliffc.aa.type.TypeMem.ld(), com.cliffc.aa.type.TypeMem.str(), and com.cliffc.aa.node.ConTypeNode.value().
ESCAPE
final TypeMem com.cliffc.aa.type.TypeMem.ESCAPE static
Definition at line 227 of file TypeMem.java.
Referenced by com.cliffc.aa.node.CallNode.add_flow_extra(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.StartNode.live(), com.cliffc.aa.node.FunPtrNode.live(), com.cliffc.aa.node.ThretNode.live_use(), com.cliffc.aa.node.NewNode< TypeStruct >.live_use(), com.cliffc.aa.node.StoreNode.live_use(), com.cliffc.aa.node.FunPtrNode.live_use(), com.cliffc.aa.node.NewObjNode.live_use(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.live_use(), com.cliffc.aa.node.RetNode.live_use(), com.cliffc.aa.node.CallNode.live_use(), com.cliffc.aa.TestLive.testBasic(), and com.cliffc.aa.TestLive.testNewObj().
FULL
final TypeMem com.cliffc.aa.type.TypeMem.FULL static
Definition at line 222 of file TypeMem.java.
Referenced by com.cliffc.aa.type.TypeMem.aliases(), com.cliffc.aa.Parse.ifex(), com.cliffc.aa.type.TypeMem.ld(), com.cliffc.aa.type.TypeMem.str(), and com.cliffc.aa.TestLive.testBasic().
INTERN
final ConcurrentHashMap<Type,Type> com.cliffc.aa.type.Type< T extends Type< T >.INTERN static private inherited
Definition at line 162 of file Type.java.
ISA_SCALAR
final byte [] com.cliffc.aa.type.Type< T extends Type< T >.ISA_SCALAR static private inherited
Definition at line 355 of file Type.java.
LESC_NO_DISP
final TypeMem com.cliffc.aa.type.TypeMem.LESC_NO_DISP static package
Definition at line 226 of file TypeMem.java.
Referenced by com.cliffc.aa.type.TypeMem.live_no_disp(), and com.cliffc.aa.node.NewObjNode.live_use().
LIVE_BOT
final TypeMem com.cliffc.aa.type.TypeMem.LIVE_BOT static package
Definition at line 226 of file TypeMem.java.
Referenced by com.cliffc.aa.node.FreshNode.all_live(), com.cliffc.aa.node.ConNode< T extends Type >.all_live(), com.cliffc.aa.node.PhiNode.all_live(), com.cliffc.aa.node.Node.all_live(), com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.ErrNode.ErrNode(), com.cliffc.aa.node.Node.live(), com.cliffc.aa.node.ScopeNode.live_use(), com.cliffc.aa.node.PrimNode.AndThen.live_use(), com.cliffc.aa.node.PrimNode.OrElse.live_use(), and com.cliffc.aa.TestLive.testNewObj().
LIVEC
final char [] com.cliffc.aa.type.TypeMem.LIVEC = new char[]{' ','#','R','3'} static private
Definition at line 114 of file TypeMem.java.
LNO_DISP
final TypeMem com.cliffc.aa.type.TypeMem.LNO_DISP static package
Definition at line 226 of file TypeMem.java.
Referenced by com.cliffc.aa.type.TypeMem.live_no_disp(), com.cliffc.aa.node.FunPtrNode.live_use(), and com.cliffc.aa.node.CallNode.live_use_call().
MEM
final TypeMem com.cliffc.aa.type.TypeMem.MEM static
Definition at line 224 of file TypeMem.java.
Referenced by com.cliffc.aa.Parse._short_circuit_expr(), com.cliffc.aa.node.MemPrimNode.ReadPrimNode.as_fun(), com.cliffc.aa.node.MemPrimNode.WritePrimNode.as_fun(), com.cliffc.aa.node.PrimNode.as_fun(), com.cliffc.aa.node.NewNode< T extends TypeObj< T >.NewPrimNode< TypeAry >.as_fun(), com.cliffc.aa.node.IntrinsicNode.convertTypeName(), com.cliffc.aa.node.IntrinsicNode.convertTypeNameStruct(), com.cliffc.aa.Parse.do_exit(), com.cliffc.aa.node.FunNode.find_type_split(), com.cliffc.aa.node.FunPtrNode.forward_ref(), com.cliffc.aa.Parse.func(), com.cliffc.aa.node.AssertNode.ideal_grow(), com.cliffc.aa.node.PrimNode.AndThen.ideal_grow(), com.cliffc.aa.node.PrimNode.OrElse.ideal_grow(), com.cliffc.aa.node.ScopeNode.live(), com.cliffc.aa.node.DefMemNode.make_mem(), com.cliffc.aa.type.TypeMem.str(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.type.TestType.testLoad(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.type.TestType.testOOPsNulls(), and com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay().
MEM_ABC
final TypeMem com.cliffc.aa.type.TypeMem.MEM_ABC static
Definition at line 229 of file TypeMem.java.
Referenced by com.cliffc.aa.type.TestType.testLoad(), and com.cliffc.aa.type.TestType.testOOPsNulls().
MEM_STR
final TypeMem com.cliffc.aa.type.TypeMem.MEM_STR static package
Definition at line 229 of file TypeMem.java.
Referenced by com.cliffc.aa.node.NewStrNode.AddStrStr.AddStrStr().
NIL
final Type com.cliffc.aa.type.Type< T extends Type< T >.NIL static inherited
Definition at line 332 of file Type.java.
NREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.NREAL static package inherited
Definition at line 336 of file Type.java.
NSCALR
final Type com.cliffc.aa.type.Type< T extends Type< T >.NSCALR static inherited
Definition at line 330 of file Type.java.
POOLS
final Pool [] com.cliffc.aa.type.Type< T extends Type< T >.POOLS static package inherited
Definition at line 281 of file Type.java.
REAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.REAL static inherited
Definition at line 334 of file Type.java.
RECURSIVE_MEET
int com.cliffc.aa.type.Type< T extends Type< T >.RECURSIVE_MEET static inherited
Definition at line 163 of file Type.java.
SCALAR
final Type com.cliffc.aa.type.Type< T extends Type< T >.SCALAR static inherited
Definition at line 328 of file Type.java.
SCALAR_PRIMS
Type [] com.cliffc.aa.type.Type< T extends Type< T >.SCALAR_PRIMS static private inherited
Definition at line 349 of file Type.java.
STRS
final String [] com.cliffc.aa.type.Type< T extends Type< T >.STRS static private inherited
Definition at line 262 of file Type.java.
TALL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TALL static package inherited
Definition at line 239 of file Type.java.
TANY
final byte com.cliffc.aa.type.Type< T extends Type< T >.TANY static package inherited
Definition at line 240 of file Type.java.
TARY
final byte com.cliffc.aa.type.Type< T extends Type< T >.TARY static package inherited
Definition at line 269 of file Type.java.
TCTRL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TCTRL static package inherited
Definition at line 241 of file Type.java.
TFLD
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFLD static package inherited
Definition at line 271 of file Type.java.
TFLT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFLT static package inherited
Definition at line 264 of file Type.java.
TFUNPTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFUNPTR static package inherited
Definition at line 274 of file Type.java.
TFUNSIG
final byte com.cliffc.aa.type.Type< T extends Type< T >.TFUNSIG static package inherited
Definition at line 275 of file Type.java.
TINT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TINT static package inherited
Definition at line 263 of file Type.java.
TLAST
final byte com.cliffc.aa.type.Type< T extends Type< T >.TLAST static package inherited
Definition at line 277 of file Type.java.
TLIVE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TLIVE static package inherited
Definition at line 276 of file Type.java.
TMEM
final byte com.cliffc.aa.type.Type< T extends Type< T >.TMEM static package inherited
Definition at line 272 of file Type.java.
TMEMPTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TMEMPTR static package inherited
Definition at line 273 of file Type.java.
TNIL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNIL static package inherited
Definition at line 259 of file Type.java.
TNREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNREAL static package inherited
Definition at line 257 of file Type.java.
TNSCALR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TNSCALR static package inherited
Definition at line 253 of file Type.java.
TOBJ
final byte com.cliffc.aa.type.Type< T extends Type< T >.TOBJ static package inherited
Definition at line 267 of file Type.java.
TREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TREAL static package inherited
Definition at line 255 of file Type.java.
TRPC
final byte com.cliffc.aa.type.Type< T extends Type< T >.TRPC static package inherited
Definition at line 265 of file Type.java.
TSCALAR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSCALAR static package inherited
Definition at line 246 of file Type.java.
TSIMPLE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSIMPLE static package inherited
Definition at line 261 of file Type.java.
TSTR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSTR static package inherited
Definition at line 270 of file Type.java.
TSTRUCT
final byte com.cliffc.aa.type.Type< T extends Type< T >.TSTRUCT static package inherited
Definition at line 268 of file Type.java.
TTUPLE
final byte com.cliffc.aa.type.Type< T extends Type< T >.TTUPLE static package inherited
Definition at line 266 of file Type.java.
TXCTRL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXCTRL static package inherited
Definition at line 242 of file Type.java.
TXNIL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNIL static package inherited
Definition at line 260 of file Type.java.
TXNREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNREAL static package inherited
Definition at line 258 of file Type.java.
TXNSCALR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXNSCALR static package inherited
Definition at line 254 of file Type.java.
TXREAL
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXREAL static package inherited
Definition at line 256 of file Type.java.
TXSCALAR
final byte com.cliffc.aa.type.Type< T extends Type< T >.TXSCALAR static package inherited
Definition at line 247 of file Type.java.
TYPES
final TypeMem [] com.cliffc.aa.type.TypeMem.TYPES = new TypeMem[]{FULL,MEM,MEM_ABC.dual(),ALLMEM,ESCAPE} static package
Definition at line 261 of file TypeMem.java.
XCTRL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XCTRL static inherited
Definition at line 327 of file Type.java.
XMEM
final TypeMem com.cliffc.aa.type.TypeMem.XMEM static
Definition at line 225 of file TypeMem.java.
Referenced by com.cliffc.aa.Parse.do_exit(), com.cliffc.aa.node.CallEpiNode.ideal_reduce(), com.cliffc.aa.node.ScopeNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), and com.cliffc.aa.type.TypeMem.str().
XNIL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNIL static inherited
Definition at line 333 of file Type.java.
XNREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNREAL static private inherited
Definition at line 337 of file Type.java.
XNSCALR
final Type com.cliffc.aa.type.Type< T extends Type< T >.XNSCALR static inherited
Definition at line 331 of file Type.java.
XREAL
final Type com.cliffc.aa.type.Type< T extends Type< T >.XREAL static private inherited
Definition at line 335 of file Type.java.
XSCALAR
final Type com.cliffc.aa.type.Type< T extends Type< T >.XSCALAR static inherited
Definition at line 329 of file Type.java.
The documentation for this class was generated from the following file:
TypeMem.java