aa: com.cliffc.aa.GVNGCM Class Reference
com.cliffc.aa.GVNGCM Class Reference
Classes
class Build
enum Mode
Public Member Functions
void add_dead (Node n)
void add_flow (UQNodes deps)
void add_flow_defs (Node n)
void add_flow_uses (Node n)
void add_grow (Node n)
void add_inline (FunNode n)
void add_reduce_uses (Node n)
Node add_unuse (Node n)
Node add_work_all (Node n)
void gcp (Mode mode, ScopeNode rez)
void iter (Mode opt_mode)
Node iter (Node x, Work[] works)
boolean on_dead (Node n)
boolean on_flow (Node n)
boolean on_reduce (Node n)
void revalive (Node... ns)
Node xform (Node n)
Node xreduce (Node n)
Static Public Member Functions
static void add_work_defs (Work work, Node n)
static void add_work_uses (Work work, Node n)
static void retype_mem (BitSet aliases, Node mem, Node exit, boolean skip_calls)
Public Attributes
Mode _opt_mode =Mode.Parse
final Work[] _reduce_works = new Work[]{_work_dead,_work_flow,_work_reduce }
final Work _work_dom = new Work("dom" , false) { @Override public Node apply(Node n) { return n.do_mono (); } }
Package Functions
public< N extends Node > N add_flow (N n)
public< N extends Node > N add_mono (N n)
public< N extends Node > N add_reduce (N n)
public< N extends Node > N init (N n)
void init0 ()
void reset_to_init0 ()
Static Package Functions
static public< N extends Node > N add_work (Work work, N n)
Static Package Attributes
static int ITER_CNT
static int ITER_CNT_NOOP
Private Member Functions
void check_and_wire (CallEpiNode cepi)
boolean check_not_monotonic (Node n, Type ot, Type nt)
void remove_ambi (CallNode call)
Private Attributes
final Work[] _all_works = new Work[]{_work_dead,_work_flow,_work_reduce,_work_mono,_work_grow,_work_inline}
final Work[] _new_works = new Work[]{ _work_flow,_work_reduce,_work_mono,_work_grow }
final Work _work_dead = new Work("dead" , false) { @Override public Node apply(Node n) { return n._keep==0 && n._uses._len == 0 ? n.kill() : null; } }
final Work _work_flow = new Work("flow" , false) { @Override public Node apply(Node n) { return n.do_flow (); } }
final Work _work_grow = new Work("grow" , true) { @Override public Node apply(Node n) { return n.do_grow (); } }
final Work _work_inline = new Work("inline", false) { @Override public Node apply(Node n) { return ((FunNode)n).ideal_inline(false); } }
final Work _work_mono = new Work("mono" , true) { @Override public Node apply(Node n) { return n.do_mono (); } }
final Work _work_reduce = new Work("reduce", true) { @Override public Node apply(Node n) { return n.do_reduce(); } }
Static Private Attributes
static boolean HAS_WORK
static final VBitSet IDEAL_VISIT = new VBitSet()
Detailed Description
Definition at line 12 of file GVNGCM.java.
Member Function Documentation
add_dead()
void com.cliffc.aa.GVNGCM.add_dead (Node n)
Definition at line 48 of file GVNGCM.java.
 { add_work(_work_dead, n); }
References com.cliffc.aa.GVNGCM._work_dead, and com.cliffc.aa.GVNGCM.add_work().
Referenced by com.cliffc.aa.GVNGCM.add_unuse(), com.cliffc.aa.Env.close(), com.cliffc.aa.node.Node.do_grow(), com.cliffc.aa.node.FunNode.split_callers(), and com.cliffc.aa.Parse.term().
add_flow() [1/2]
public<N extends Node> N com.cliffc.aa.GVNGCM.add_flow (N n) package
Definition at line 50 of file GVNGCM.java.
 { return add_work(_work_flow  ,n); }
References com.cliffc.aa.GVNGCM._work_flow, and com.cliffc.aa.GVNGCM.add_work().
Referenced by com.cliffc.aa.tvar.TV2._fresh_unify(), com.cliffc.aa.Parse._short_circuit_expr(), com.cliffc.aa.node.CallNode.add_flow_def_extra(), com.cliffc.aa.node.CastNode.add_flow_extra(), com.cliffc.aa.node.FunPtrNode.add_flow_extra(), com.cliffc.aa.node.CallNode.add_flow_extra(), com.cliffc.aa.node.CProjNode.add_flow_use_extra(), com.cliffc.aa.node.MProjNode.add_flow_use_extra(), com.cliffc.aa.node.ParmNode.add_flow_use_extra(), com.cliffc.aa.node.NewStrNode.AddStrStr.add_flow_use_extra(), com.cliffc.aa.node.RegionNode.add_flow_use_extra(), com.cliffc.aa.node.LoadNode.add_flow_use_extra(), com.cliffc.aa.node.CallEpiNode.add_flow_use_extra(), com.cliffc.aa.node.CallNode.add_flow_use_extra(), com.cliffc.aa.node.MemSplitNode.add_reduce_extra(), com.cliffc.aa.node.NewNode< TypeStruct >.add_reduce_extra(), com.cliffc.aa.node.CallNode.add_reduce_extra(), com.cliffc.aa.GVNGCM.add_unuse(), com.cliffc.aa.GVNGCM.check_not_monotonic(), com.cliffc.aa.Env.close_display(), com.cliffc.aa.node.Node.con(), com.cliffc.aa.node.NewNode< TypeStruct >.copy(), com.cliffc.aa.node.NewObjNode.create_active(), com.cliffc.aa.Parse.do_call0(), com.cliffc.aa.node.Node.do_flow(), com.cliffc.aa.node.Node.do_grow(), com.cliffc.aa.node.Node.do_mono(), com.cliffc.aa.node.FunPtrNode.forward_ref(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.node.NewObjNode.ideal_mono(), com.cliffc.aa.Parse.ifex(), com.cliffc.aa.GVNGCM.init(), com.cliffc.aa.node.MemSplitNode.insert_split(), com.cliffc.aa.node.FunNode.make_new_fun(), com.cliffc.aa.node.Node.merge(), com.cliffc.aa.GVNGCM.remove_ambi(), com.cliffc.aa.Parse.stmts(), com.cliffc.aa.node.CallNode.swap_new(), com.cliffc.aa.node.Node.unelock(), com.cliffc.aa.tvar.TV2.unify_at(), com.cliffc.aa.tvar.TV2.union(), com.cliffc.aa.node.FunNode.unwire(), com.cliffc.aa.node.CallEpiNode.unwire(), com.cliffc.aa.node.Node.walk_initype(), com.cliffc.aa.GVNGCM.xform(), and com.cliffc.aa.GVNGCM.xreduce().
add_flow() [2/2]
void com.cliffc.aa.GVNGCM.add_flow (UQNodes deps)
Definition at line 56 of file GVNGCM.java.
 { if( deps != null ) for( Node dep : deps.values() ) add_flow(dep); }
References com.cliffc.aa.GVNGCM.add_flow(), and com.cliffc.aa.util.NonBlockingHashMapLong< TypeV >.values().
Referenced by com.cliffc.aa.GVNGCM.add_flow().
add_flow_defs()
void com.cliffc.aa.GVNGCM.add_flow_defs (Node n)
Definition at line 54 of file GVNGCM.java.
 { add_work_defs(_work_flow  ,n); }
References com.cliffc.aa.GVNGCM._work_flow, and com.cliffc.aa.GVNGCM.add_work_defs().
Referenced by com.cliffc.aa.node.CallNode.add_flow_extra(), com.cliffc.aa.node.RegionNode.add_flow_use_extra(), com.cliffc.aa.node.CallNode.add_flow_use_extra(), com.cliffc.aa.node.Node.do_flow(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.GVNGCM.revalive(), and com.cliffc.aa.node.CallEpiNode.unwire().
add_flow_uses()
void com.cliffc.aa.GVNGCM.add_flow_uses (Node n)
Definition at line 55 of file GVNGCM.java.
 { add_work_uses(_work_flow  ,n); }
References com.cliffc.aa.GVNGCM._work_flow, and com.cliffc.aa.GVNGCM.add_work_uses().
Referenced by com.cliffc.aa.node.Node.do_reduce(), com.cliffc.aa.node.StoreNode.ideal_reduce(), com.cliffc.aa.node.NewNode< TypeStruct >.kill2(), com.cliffc.aa.node.FunNode.make_new_fun(), com.cliffc.aa.node.FunPtrNode.merge_ref_def(), com.cliffc.aa.node.NewObjNode.promote_forward(), com.cliffc.aa.GVNGCM.retype_mem(), com.cliffc.aa.GVNGCM.revalive(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.node.CallNode.swap_new(), com.cliffc.aa.node.NewObjNode.update(), and com.cliffc.aa.node.Node.xval().
add_grow()
void com.cliffc.aa.GVNGCM.add_grow (Node n)
Definition at line 52 of file GVNGCM.java.
 { add_work(_work_grow  ,n); }
References com.cliffc.aa.GVNGCM._work_grow, and com.cliffc.aa.GVNGCM.add_work().
Referenced by com.cliffc.aa.node.MrgProjNode.add_flow_def_extra(), and com.cliffc.aa.node.PrimNode.as_fun().
add_inline()
void com.cliffc.aa.GVNGCM.add_inline (FunNode n)
Definition at line 53 of file GVNGCM.java.
 { add_work(_work_inline, n); }
References com.cliffc.aa.GVNGCM._work_inline, and com.cliffc.aa.GVNGCM.add_work().
Referenced by com.cliffc.aa.Parse.do_call0().
add_mono()
public<N extends Node> N com.cliffc.aa.GVNGCM.add_mono (N n) package
Definition at line 51 of file GVNGCM.java.
 { return add_work(_work_mono  ,n); }
References com.cliffc.aa.GVNGCM._work_mono, and com.cliffc.aa.GVNGCM.add_work().
Referenced by com.cliffc.aa.node.NewObjNode.add_flow_extra(), com.cliffc.aa.node.LoadNode.add_flow_use_extra(), com.cliffc.aa.node.StoreNode.add_reduce_extra(), com.cliffc.aa.node.Node.do_mono(), com.cliffc.aa.node.MemSplitNode.insert_split(), com.cliffc.aa.node.ScopeNode.set_mem(), and com.cliffc.aa.node.FunNode.split_callers().
add_reduce()
public<N extends Node> N com.cliffc.aa.GVNGCM.add_reduce (N n) package
Definition at line 49 of file GVNGCM.java.
 { return add_work(_work_reduce,n); }
References com.cliffc.aa.GVNGCM._work_reduce, and com.cliffc.aa.GVNGCM.add_work().
Referenced by com.cliffc.aa.Parse._args(), com.cliffc.aa.node.MrgProjNode.add_flow_def_extra(), com.cliffc.aa.node.RegionNode.add_flow_def_extra(), com.cliffc.aa.node.NewNode< TypeStruct >.add_flow_def_extra(), com.cliffc.aa.node.FreshNode.add_flow_extra(), com.cliffc.aa.node.StoreNode.add_flow_extra(), com.cliffc.aa.node.CallNode.add_flow_extra(), com.cliffc.aa.node.AssertNode.add_flow_use_extra(), com.cliffc.aa.node.FunPtrNode.add_flow_use_extra(), com.cliffc.aa.node.RegionNode.add_flow_use_extra(), com.cliffc.aa.node.LoadNode.add_flow_use_extra(), com.cliffc.aa.node.CallNode.add_flow_use_extra(), com.cliffc.aa.node.StoreNode.add_reduce_extra(), com.cliffc.aa.node.CallNode.add_reduce_extra(), com.cliffc.aa.GVNGCM.add_unuse(), com.cliffc.aa.node.Node.do_flow(), com.cliffc.aa.node.Node.do_grow(), com.cliffc.aa.node.Node.do_mono(), com.cliffc.aa.node.Node.do_reduce(), com.cliffc.aa.node.RegionNode.ideal_reduce(), com.cliffc.aa.node.CallNode.ideal_reduce(), com.cliffc.aa.Parse.ifex(), com.cliffc.aa.GVNGCM.init(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.Parse.term(), com.cliffc.aa.node.Node.unelock(), com.cliffc.aa.tvar.TV2.union(), and com.cliffc.aa.node.CallEpiNode.unwire().
add_reduce_uses()
void com.cliffc.aa.GVNGCM.add_reduce_uses (Node n)
Definition at line 57 of file GVNGCM.java.
 { add_work_uses(_work_reduce,n); }
References com.cliffc.aa.GVNGCM._work_reduce, and com.cliffc.aa.GVNGCM.add_work_uses().
Referenced by com.cliffc.aa.node.FunNode.ideal_reduce(), com.cliffc.aa.node.FunPtrNode.merge_ref_def(), com.cliffc.aa.node.CallEpiNode.set_is_copy(), and com.cliffc.aa.node.FunNode.set_is_copy().
add_unuse()
Node com.cliffc.aa.GVNGCM.add_unuse (Node n)
Definition at line 59 of file GVNGCM.java.
{
     if( n._uses._len==0 && n._keep==0 ) { add_dead(n); return n; } // might be dead
     return add_reduce(add_flow(n));
   }
References com.cliffc.aa.node.Node._keep, com.cliffc.aa.node.Node._uses, com.cliffc.aa.GVNGCM.add_dead(), com.cliffc.aa.GVNGCM.add_flow(), and com.cliffc.aa.GVNGCM.add_reduce().
Referenced by com.cliffc.aa.node.CallNode._ideal_grow(), com.cliffc.aa.GVNGCM.Build< N extends Node >.close(), com.cliffc.aa.node.FunNode.split_callers(), com.cliffc.aa.node.RetNode.tail_recursive(), and com.cliffc.aa.node.Node.unuse().
add_work()
static public<N extends Node> N com.cliffc.aa.GVNGCM.add_work (Work work, N n) static package
Definition at line 43 of file GVNGCM.java.
{
     if( n==null || n.is_dead() ) return n;
     if( !HAS_WORK ) HAS_WORK = true; // Filtered set
     return work.add(n);
   }
References com.cliffc.aa.node.Work.add(), and com.cliffc.aa.GVNGCM.HAS_WORK.
Referenced by com.cliffc.aa.GVNGCM.add_dead(), com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.GVNGCM.add_grow(), com.cliffc.aa.GVNGCM.add_inline(), com.cliffc.aa.GVNGCM.add_mono(), com.cliffc.aa.GVNGCM.add_reduce(), com.cliffc.aa.GVNGCM.add_work_all(), com.cliffc.aa.GVNGCM.add_work_defs(), and com.cliffc.aa.GVNGCM.add_work_uses().
add_work_all()
Node com.cliffc.aa.GVNGCM.add_work_all (Node n)
Definition at line 73 of file GVNGCM.java.
{
     if( n.is_dead() ) return n;
     if( !HAS_WORK ) HAS_WORK = true; // Filtered set
     for( Work work : _new_works ) work.add(n);
     if( n instanceof FunNode )
       add_work(_work_inline,(FunNode)n);
     return n;
   }
References com.cliffc.aa.GVNGCM._new_works, com.cliffc.aa.GVNGCM._work_inline, com.cliffc.aa.GVNGCM.add_work(), com.cliffc.aa.GVNGCM.HAS_WORK, and com.cliffc.aa.node.Node.is_dead().
Referenced by com.cliffc.aa.node.CallNode.add_flow_use_extra(), com.cliffc.aa.Env.close_display(), com.cliffc.aa.node.Node.copy(), com.cliffc.aa.Parse.do_call0(), com.cliffc.aa.node.LoadNode.ideal_grow(), com.cliffc.aa.Parse.ifex(), com.cliffc.aa.node.Node.init1(), com.cliffc.aa.node.MemSplitNode.insert_split(), com.cliffc.aa.node.ScopeNode.set_mem(), com.cliffc.aa.node.Node.unhook(), com.cliffc.aa.node.Node.walk_opt(), and com.cliffc.aa.GVNGCM.xform().
add_work_defs()
static void com.cliffc.aa.GVNGCM.add_work_defs (Work work, Node n) static
Definition at line 63 of file GVNGCM.java.
{
     for( Node def : n._defs )
       if( def != null && def != n )
         add_work(work,def);
   }
References com.cliffc.aa.node.Node._defs, and com.cliffc.aa.GVNGCM.add_work().
Referenced by com.cliffc.aa.GVNGCM.add_flow_defs().
add_work_uses()
static void com.cliffc.aa.GVNGCM.add_work_uses (Work work, Node n) static
Definition at line 68 of file GVNGCM.java.
{
     for( Node use : n._uses )
       if( use != n )
         add_work(work,use);
   }
References com.cliffc.aa.node.Node._uses, and com.cliffc.aa.GVNGCM.add_work().
Referenced by com.cliffc.aa.GVNGCM.add_flow_uses(), and com.cliffc.aa.GVNGCM.add_reduce_uses().
check_and_wire()
void com.cliffc.aa.GVNGCM.check_and_wire (CallEpiNode cepi) private
Definition at line 311 of file GVNGCM.java.
{
     if( !cepi.check_and_wire() ) return;
     assert Env.START.more_flow(false)==0;
   }
References com.cliffc.aa.node.CallEpiNode.check_and_wire(), com.cliffc.aa.node.Node.more_flow(), and com.cliffc.aa.Env.START.
Referenced by com.cliffc.aa.GVNGCM.gcp().
check_not_monotonic()
boolean com.cliffc.aa.GVNGCM.check_not_monotonic (Node n, Type ot, Type nt) private
Definition at line 317 of file GVNGCM.java.
{
     assert nt==nt.simple_ptr() || n instanceof ConTypeNode;    // Only simple pointers in node types
     if( ot.isa(nt) ) return false; // No bug
     _work_flow.del(n);             // Might be back on the lift
     add_flow(n);                   // Setup for a re-run
     System.out.println("Not monotonic");
     return true;    // Just single-step forward in debugging to re-run n.value
   }
References com.cliffc.aa.GVNGCM._work_flow, com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.node.Work.del(), com.cliffc.aa.type.Type< T extends Type< T >.isa(), and com.cliffc.aa.type.Type< T extends Type< T >.simple_ptr().
Referenced by com.cliffc.aa.GVNGCM.gcp().
gcp()
void com.cliffc.aa.GVNGCM.gcp (Mode mode, ScopeNode rez)
Definition at line 217 of file GVNGCM.java.
{
     _opt_mode = mode;
     // Set all values to ALL and lives to DEAD, their most optimistic types.
     VBitSet visit = new VBitSet();
     Env.START.walk_initype(this,visit);
     assert Env.START.more_flow(false)==0; // Initial conditions are correct
     // Collect unresolved calls, and verify they get resolved.
     Ary<CallNode> ambi_calls = new Ary<>(new CallNode[1],0);
     // Repeat, if we remove some ambiguous choices, and keep falling until the
     // graph stabilizes without ambiguity.
     while( !_work_flow.isEmpty() ) {
       // Analysis phase.
       // Work down list until all reachable nodes types quit falling
       Node n;
       while( (n=_work_flow.pop()) != null ) {
         if( n.is_dead() ) continue; // Can be dead functions after removing ambiguous calls
         // Forwards flow
         Type oval = n._val;                                // Old local type
         Type nval = n.value(_opt_mode);                    // New type
         if( oval != nval ) {                               // Progress
           if( check_not_monotonic(n, oval, nval) ) continue; // Debugging hook
           n._val = nval;            // Record progress
           for( Node use : n._uses ) // Classic forwards flow on change
             add_flow(use).add_flow_use_extra(n);
           n.add_flow_extra(oval);
           if( n instanceof CallEpiNode ) check_and_wire((CallEpiNode)n);
           for( Node use : n._uses )
             if( use instanceof CallEpiNode ) check_and_wire((CallEpiNode)use);
           // All liveness is skipped if may_be_con, since the possible constant
           // has no inputs.
           assert oval.may_be_con() || !nval.may_be_con(); // May_be_con is monotonic
           if( oval.may_be_con() && !nval.may_be_con() )
             add_flow_defs(n);   // Now check liveness
         }
         // Reverse flow
         TypeMem oliv = n._live;
         TypeMem nliv = n.live(_opt_mode);
         if( oliv != nliv ) {      // Liveness progress
           if( check_not_monotonic(n, oliv, nliv) ) continue; // Debugging hook
           n._live = nliv;           // Record progress
           n.add_flow_extra(nliv);
           for( Node def : n._defs ) // Classic reverse flow on change
             if( def!=null ) add_flow(def).add_flow_def_extra(n);
         }
         // See if we can resolve an unresolved
         if( n instanceof CallNode && n._live != TypeMem.DEAD ) {
           CallNode call = (CallNode)n;
           if( call.ctl()._val == Type.CTRL && call._val instanceof TypeTuple ) { // Wait until the Call is reachable
             // Track ambiguous calls: resolve after GCP gets stable, and if we
             // can resolve we continue to let GCP fall.
             BitsFun fidxs = CallNode.ttfp(call._val).fidxs();
             if( fidxs.above_center() && fidxs.abit() == -1 && ambi_calls.find(call) == -1 )
               ambi_calls.add(call);
           }
         }
         // Very expensive assert
         //assert Env.START.more_flow(false)==0; // Initial conditions are correct
       }
       // Remove CallNode ambiguity after worklist runs dry.  This makes a
       // 'least_cost' choice on unresolved Calls, and lowers them in the
       // lattice... allowing more GCP progress.
       while( !ambi_calls.isEmpty() )
         remove_ambi(ambi_calls.pop());
     }
     assert Env.START.more_flow(false)==0; // Final conditions are correct
     visit.clear();
     Env.START.walk_opt(visit);
   }
References com.cliffc.aa.node.Node._defs, com.cliffc.aa.node.Node._live, com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node._val, com.cliffc.aa.GVNGCM._work_flow, com.cliffc.aa.type.Bits< B extends Bits< B >.abit(), com.cliffc.aa.type.Bits< B extends Bits< B >.above_center(), com.cliffc.aa.util.Ary< E >.add(), com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.GVNGCM.add_flow_defs(), com.cliffc.aa.node.Node.add_flow_extra(), com.cliffc.aa.GVNGCM.check_and_wire(), com.cliffc.aa.GVNGCM.check_not_monotonic(), com.cliffc.aa.node.CallNode.ctl(), com.cliffc.aa.type.Type< T extends Type< T >.CTRL, com.cliffc.aa.type.TypeMem.DEAD, com.cliffc.aa.type.TypeFunPtr.fidxs(), com.cliffc.aa.util.Ary< E >.find(), com.cliffc.aa.node.Node.is_dead(), com.cliffc.aa.util.Ary< E >.isEmpty(), com.cliffc.aa.node.Work.isEmpty(), com.cliffc.aa.node.Node.live(), com.cliffc.aa.type.Type< T extends Type< T >.may_be_con(), com.cliffc.aa.node.Node.more_flow(), com.cliffc.aa.node.Work.pop(), com.cliffc.aa.util.Ary< E >.pop(), com.cliffc.aa.GVNGCM.remove_ambi(), com.cliffc.aa.Env.START, com.cliffc.aa.node.CallNode.ttfp(), com.cliffc.aa.node.Node.value(), com.cliffc.aa.node.Node.walk_initype(), and com.cliffc.aa.node.Node.walk_opt().
Referenced by com.cliffc.aa.Parse.go(), and com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay().
init()
public<N extends Node> N com.cliffc.aa.GVNGCM.init (N n) package
Definition at line 99 of file GVNGCM.java.
 { return add_flow(add_reduce(n.keep(2))); }
References com.cliffc.aa.GVNGCM.add_flow(), and com.cliffc.aa.GVNGCM.add_reduce().
Referenced by com.cliffc.aa.node.TestNodeSmall.check(), com.cliffc.aa.node.FunPtrNode.forward_ref(), com.cliffc.aa.node.ScopeNode.init(), com.cliffc.aa.Parse.init(), com.cliffc.aa.node.MemSplitNode.insert_split(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), and com.cliffc.aa.Env.top_scope().
init0()
void com.cliffc.aa.GVNGCM.init0 () package
Definition at line 83 of file GVNGCM.java.
                {
     for( Work work : _all_works ) assert work.isEmpty();
   }
References com.cliffc.aa.GVNGCM._all_works.
Referenced by com.cliffc.aa.Env.record_for_top_reset2().
iter() [1/2]
void com.cliffc.aa.GVNGCM.iter (Mode opt_mode)
Definition at line 147 of file GVNGCM.java.
{
     _opt_mode = opt_mode;
     boolean progress=true;
     while( progress ) {
       progress = false;
       iter(null,_all_works);
       // Only a very few nodes can make progress via dominance relations, and
       // these can make progress "very far" in the graph.  So instead of using
       // a neighbors list, we bulk revisit them here.
       for( int i=0; i<_work_dom.len(); i++ ) {
         Node dom = _work_dom.at(i);
         if( dom.is_dead() ) _work_dom.del(i--);
         else progress |= _work_dom.apply(dom)!=null;
       }
     }
     IDEAL_VISIT.clear();
     // Expensive assert
     assert !Env.START.more_ideal(IDEAL_VISIT);
   }
References com.cliffc.aa.GVNGCM._all_works, com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.GVNGCM._work_dom, com.cliffc.aa.node.Work.apply(), com.cliffc.aa.node.Work.at(), com.cliffc.aa.node.Work.del(), com.cliffc.aa.GVNGCM.IDEAL_VISIT, com.cliffc.aa.node.Node.is_dead(), com.cliffc.aa.node.Work.len(), com.cliffc.aa.node.Node.more_ideal(), and com.cliffc.aa.Env.START.
Referenced by com.cliffc.aa.Env.close(), com.cliffc.aa.Parse.go(), com.cliffc.aa.node.FunPtrNode.merge_ref_def(), com.cliffc.aa.Env.top_scope(), and com.cliffc.aa.GVNGCM.xform().
iter() [2/2]
Node com.cliffc.aa.GVNGCM.iter (Node x, Work[] works)
Definition at line 172 of file GVNGCM.java.
{
     if( !HAS_WORK ) return x;
     if( x!=null ) x.keep();
     while( true ) {
       Work W=null;
       for( Work work : works )
         if( !(W = work).isEmpty() )
           break;
       if( W.isEmpty() ) break;      // All worklists empty
       Node n = W.pop();
       Node m = n.is_dead() ? null : W.apply(n);
       if( m == null ) {       // not-null is progress
         ITER_CNT_NOOP++;      // No progress
       } else {
         // VERY EXPENSIVE ASSERT
         //assert W==_work_dead || Env.START.more_flow(true)==0; // Initial conditions are correct
         ITER_CNT++; assert ITER_CNT < 35000; // Catch infinite ideal-loops
         if( x==n ) x=m;       // Keep track of the replacement for x, if any
       }
     }
     HAS_WORK=false;
     Node.roll_back_CNT();       // Can reclaim node numbers
     if( x==null ) return null;  // No special node to track
     return x.unkeep();
   }
References com.cliffc.aa.node.Work.apply(), com.cliffc.aa.GVNGCM.HAS_WORK, com.cliffc.aa.node.Node.is_dead(), com.cliffc.aa.node.Work.isEmpty(), com.cliffc.aa.GVNGCM.ITER_CNT, com.cliffc.aa.GVNGCM.ITER_CNT_NOOP, com.cliffc.aa.node.Node.keep(), com.cliffc.aa.node.Work.pop(), com.cliffc.aa.node.Node.roll_back_CNT(), and com.cliffc.aa.node.Node.unkeep().
on_dead()
boolean com.cliffc.aa.GVNGCM.on_dead (Node n)
Definition at line 39 of file GVNGCM.java.
 { return _work_dead  .on(n); }
References com.cliffc.aa.GVNGCM._work_dead, and com.cliffc.aa.node.Work.on().
Referenced by com.cliffc.aa.node.Node.more_flow().
on_flow()
boolean com.cliffc.aa.GVNGCM.on_flow (Node n)
Definition at line 40 of file GVNGCM.java.
 { return _work_flow  .on(n); }
References com.cliffc.aa.GVNGCM._work_flow, and com.cliffc.aa.node.Work.on().
Referenced by com.cliffc.aa.node.Node.more_flow().
on_reduce()
boolean com.cliffc.aa.GVNGCM.on_reduce (Node n)
Definition at line 41 of file GVNGCM.java.
 { return _work_reduce.on(n); }
References com.cliffc.aa.GVNGCM._work_reduce, and com.cliffc.aa.node.Work.on().
remove_ambi()
void com.cliffc.aa.GVNGCM.remove_ambi (CallNode call) private
Definition at line 291 of file GVNGCM.java.
{
     TypeFunPtr tfp = CallNode.ttfpx(call._val);
     FunPtrNode fptr = null;
     BitsFun fidxs = tfp.fidxs();
     if( !fidxs.above_center() ) return; // Resolved after all
     if( fidxs!=BitsFun.ANY ) {          // And have choices
       // Pick least-cost among choices
       fptr = call.least_cost(fidxs,call.fdx());
       if( fptr==null ) { // Not resolving, program is in-error
         call._not_resolved_by_gcp = true; // will drop fdx in lattice
         add_flow(call);
         return;
       }
     }
     call.set_dsp(fptr.display());
     call.set_fdx(fptr);         // Set resolved edge
     add_flow(call);
     assert Env.START.more_flow(false)==0; // Post conditions are correct
   }
References com.cliffc.aa.node.CallNode._not_resolved_by_gcp, com.cliffc.aa.node.Node._val, com.cliffc.aa.type.Bits< B extends Bits< B >.above_center(), com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.type.BitsFun.ANY, com.cliffc.aa.node.FunPtrNode.display(), com.cliffc.aa.node.CallNode.fdx(), com.cliffc.aa.type.TypeFunPtr.fidxs(), com.cliffc.aa.node.CallNode.least_cost(), com.cliffc.aa.node.Node.more_flow(), com.cliffc.aa.node.CallNode.set_dsp(), com.cliffc.aa.node.CallNode.set_fdx(), com.cliffc.aa.Env.START, and com.cliffc.aa.node.CallNode.ttfpx().
Referenced by com.cliffc.aa.GVNGCM.gcp().
reset_to_init0()
void com.cliffc.aa.GVNGCM.reset_to_init0 () package
Definition at line 89 of file GVNGCM.java.
{
     for( Work work : _all_works ) work.clear();
     _work_dom.clear();
     _opt_mode = Mode.Parse;
     ITER_CNT = ITER_CNT_NOOP = 0;
   }
References com.cliffc.aa.GVNGCM._all_works, com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.GVNGCM._work_dom, com.cliffc.aa.node.Work.clear(), com.cliffc.aa.GVNGCM.ITER_CNT, com.cliffc.aa.GVNGCM.ITER_CNT_NOOP, and com.cliffc.aa.GVNGCM.Mode.Parse.
Referenced by com.cliffc.aa.Env.top_reset().
retype_mem()
static void com.cliffc.aa.GVNGCM.retype_mem (BitSet aliases, Node mem, Node exit, boolean skip_calls) static
Definition at line 330 of file GVNGCM.java.
{
     Ary<Node> work = new Ary<>(new Node[1],0);
     work.push(mem);
     // Update all memory ops
     while( !work.isEmpty() ) {
       Node wrk = work.pop();
       if( !wrk.is_mem() && wrk!=mem ) continue; // Not a memory Node?
       Type twrk = wrk._val;
       Type tmem0 = twrk instanceof TypeTuple ? ((TypeTuple)twrk).at(1) : twrk;
       if( !(tmem0 instanceof TypeMem) ) continue; // Node does have have a memory type?
       if( aliases!=null && !((TypeMem)tmem0).has_used(aliases) ) continue; // Not does not use the listed memory?
       if( wrk instanceof CallNode ) { // Do the CEPI for a Call, skipping in-between
         CallEpiNode cepi = ((CallNode)wrk).cepi();
         if( cepi != null ) work.push(cepi);
       }
       Type tval = wrk.value(Env.GVN._opt_mode); // Recompute memory value
       if( twrk == tval ) continue;              // No change
       wrk._val = tval;                          // Progress!!!
       Env.GVN.add_flow_uses(wrk);               // Forwards flow the update
       if( wrk==exit ) continue;                 // Stop at end
       if( skip_calls && wrk instanceof MProjNode && wrk.in(0) instanceof CallNode )
         continue;               // Skip the inside of calls
       work.addAll(wrk._uses);
     }
   }
References com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.node.Node._uses, com.cliffc.aa.node.Node._val, com.cliffc.aa.GVNGCM.add_flow_uses(), com.cliffc.aa.util.Ary< E >.addAll(), com.cliffc.aa.type.TypeTuple.at(), com.cliffc.aa.Env.GVN, com.cliffc.aa.node.Node.in(), com.cliffc.aa.node.Node.is_mem(), com.cliffc.aa.util.Ary< E >.isEmpty(), com.cliffc.aa.util.Ary< E >.pop(), com.cliffc.aa.util.Ary< E >.push(), and com.cliffc.aa.node.Node.value().
Referenced by com.cliffc.aa.node.MemJoinNode.ideal_reduce(), com.cliffc.aa.node.CallEpiNode.set_is_copy(), and com.cliffc.aa.node.FunNode.split_callers().
revalive()
void com.cliffc.aa.GVNGCM.revalive (Node... ns)
Definition at line 103 of file GVNGCM.java.
{
     for( Node n : ns ) {
       if( n == null ) continue;
       Type t = n.value(_opt_mode);
       if( t != n._val ) {
         n._val = t;
         add_flow_uses(n);
       }
     }
     for( int i=ns.length-1; i>=0; i-- ) {
       Node n = ns[i];
       if( n==null ) continue;
       TypeMem t = n.live(_opt_mode);
       if( t != n._live ) {
         n._live=t;
         add_flow_defs(n);
       }
     }
   }
References com.cliffc.aa.node.Node._live, com.cliffc.aa.GVNGCM._opt_mode, com.cliffc.aa.GVNGCM.add_flow_defs(), com.cliffc.aa.GVNGCM.add_flow_uses(), and com.cliffc.aa.node.Node.live().
Referenced by com.cliffc.aa.node.MemSplitNode.insert_split(), com.cliffc.aa.node.NewNode< TypeStruct >.kill2(), and com.cliffc.aa.node.CallNode.swap_new().
xform()
Node com.cliffc.aa.GVNGCM.xform (Node n)
Definition at line 126 of file GVNGCM.java.
{
     assert n._uses._len==0 && n._keep==0; // New to GVN
     Node x = iter(add_work_all(n),_all_works);
     assert !x.is_dead();
     return add_flow(x);         // No liveness (yet), since uses not known
   }
References com.cliffc.aa.GVNGCM._all_works, com.cliffc.aa.node.Node._keep, com.cliffc.aa.node.Node._uses, com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.GVNGCM.add_work_all(), com.cliffc.aa.node.Node.is_dead(), and com.cliffc.aa.GVNGCM.iter().
Referenced by com.cliffc.aa.node.ScopeNode.IfScope.check(), com.cliffc.aa.node.TestNodeSmall.check(), com.cliffc.aa.node.UnresolvedNode.filter(), com.cliffc.aa.Parse.gvn(), com.cliffc.aa.Env.init(), com.cliffc.aa.Env.lookup_filter_fresh(), com.cliffc.aa.node.ScopeNode.replace_mem(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.node.TestNodeSmall.testUnresolvedAdd(), and com.cliffc.aa.Env.top_scope().
xreduce()
Node com.cliffc.aa.GVNGCM.xreduce (Node n)
Definition at line 135 of file GVNGCM.java.
{
     assert n._uses._len==0 && n._keep==0; // New to GVN
     n.do_flow();                // Compute _val (for finding constants)
     Node x = n.do_reduce();     // Maybe find a more ideal Node
     if( x==null ) x=n;          // Ignore lack-of-progress
     return add_flow(x);         // No liveness (yet), since uses not known
   }
References com.cliffc.aa.node.Node._keep, com.cliffc.aa.node.Node._uses, com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.node.Node.do_flow(), and com.cliffc.aa.node.Node.do_reduce().
Referenced by com.cliffc.aa.node.IfNode.flip(), and com.cliffc.aa.node.IfNode.ideal_reduce().
Member Data Documentation
_all_works
final Work [] com.cliffc.aa.GVNGCM._all_works = new Work[]{_work_dead,_work_flow,_work_reduce,_work_mono,_work_grow,_work_inline} private
Definition at line 37 of file GVNGCM.java.
Referenced by com.cliffc.aa.GVNGCM.init0(), com.cliffc.aa.GVNGCM.iter(), com.cliffc.aa.GVNGCM.reset_to_init0(), and com.cliffc.aa.GVNGCM.xform().
_new_works
final Work [] com.cliffc.aa.GVNGCM._new_works = new Work[]{ _work_flow,_work_reduce,_work_mono,_work_grow } private
Definition at line 33 of file GVNGCM.java.
Referenced by com.cliffc.aa.GVNGCM.add_work_all().
_opt_mode
Mode com.cliffc.aa.GVNGCM._opt_mode =Mode.Parse
Definition at line 22 of file GVNGCM.java.
Referenced by com.cliffc.aa.node.TestNodeSmall._testMonotonicChain(), com.cliffc.aa.node.CallNode.add_flow_use_extra(), com.cliffc.aa.node.TestNodeSmall.check(), com.cliffc.aa.Env.close(), com.cliffc.aa.node.Node.do_flow(), com.cliffc.aa.Env.Env(), com.cliffc.aa.GVNGCM.gcp(), com.cliffc.aa.node.FunNode.ideal_inline(), com.cliffc.aa.node.ScopeNode.ideal_reduce(), com.cliffc.aa.node.Node.init1(), com.cliffc.aa.GVNGCM.iter(), com.cliffc.aa.node.Node.more_flow(), com.cliffc.aa.node.Node.more_ideal(), com.cliffc.aa.Parse.prog(), com.cliffc.aa.node.TestNode.redo_(), com.cliffc.aa.GVNGCM.reset_to_init0(), com.cliffc.aa.GVNGCM.retype_mem(), com.cliffc.aa.GVNGCM.revalive(), com.cliffc.aa.node.TestNode.set_value_type(), com.cliffc.aa.node.FunNode.split_size(), com.cliffc.aa.node.TestNode.test1jig(), com.cliffc.aa.TestLive.testBasic(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve(), com.cliffc.aa.node.TestNodeSmall.testCallNodeResolve2(), com.cliffc.aa.node.TestNode.testMonotonic(), com.cliffc.aa.TestLive.testNewObj(), com.cliffc.aa.node.TestNodeSmall.testRecursiveDisplay(), com.cliffc.aa.node.TestNodeSmall.testUnresolvedAdd(), com.cliffc.aa.node.TestNodeSmall.v(), and com.cliffc.aa.node.Node.xval().
_reduce_works
final Work [] com.cliffc.aa.GVNGCM._reduce_works = new Work[]{_work_dead,_work_flow,_work_reduce }
Definition at line 35 of file GVNGCM.java.
_work_dead
final Work com.cliffc.aa.GVNGCM._work_dead = new Work("dead" , false) { @Override public Node apply(Node n) { return n._keep==0 && n._uses._len == 0 ? n.kill() : null; } } private
Definition at line 25 of file GVNGCM.java.
Referenced by com.cliffc.aa.GVNGCM.add_dead(), and com.cliffc.aa.GVNGCM.on_dead().
_work_dom
final Work com.cliffc.aa.GVNGCM._work_dom = new Work("dom" , false) { @Override public Node apply(Node n) { return n.do_mono (); } }
Definition at line 31 of file GVNGCM.java.
Referenced by com.cliffc.aa.node.CastNode.CastNode(), com.cliffc.aa.node.CastNode.copy(), com.cliffc.aa.GVNGCM.iter(), and com.cliffc.aa.GVNGCM.reset_to_init0().
_work_flow
final Work com.cliffc.aa.GVNGCM._work_flow = new Work("flow" , false) { @Override public Node apply(Node n) { return n.do_flow (); } } private
Definition at line 27 of file GVNGCM.java.
Referenced by com.cliffc.aa.GVNGCM.add_flow(), com.cliffc.aa.GVNGCM.add_flow_defs(), com.cliffc.aa.GVNGCM.add_flow_uses(), com.cliffc.aa.GVNGCM.check_not_monotonic(), com.cliffc.aa.GVNGCM.gcp(), and com.cliffc.aa.GVNGCM.on_flow().
_work_grow
final Work com.cliffc.aa.GVNGCM._work_grow = new Work("grow" , true) { @Override public Node apply(Node n) { return n.do_grow (); } } private
Definition at line 29 of file GVNGCM.java.
Referenced by com.cliffc.aa.GVNGCM.add_grow().
_work_inline
final Work com.cliffc.aa.GVNGCM._work_inline = new Work("inline", false) { @Override public Node apply(Node n) { return ((FunNode)n).ideal_inline(false); } } private
Definition at line 30 of file GVNGCM.java.
Referenced by com.cliffc.aa.GVNGCM.add_inline(), and com.cliffc.aa.GVNGCM.add_work_all().
_work_mono
final Work com.cliffc.aa.GVNGCM._work_mono = new Work("mono" , true) { @Override public Node apply(Node n) { return n.do_mono (); } } private
Definition at line 28 of file GVNGCM.java.
Referenced by com.cliffc.aa.GVNGCM.add_mono().
_work_reduce
final Work com.cliffc.aa.GVNGCM._work_reduce = new Work("reduce", true) { @Override public Node apply(Node n) { return n.do_reduce(); } } private
Definition at line 26 of file GVNGCM.java.
Referenced by com.cliffc.aa.GVNGCM.add_reduce(), com.cliffc.aa.GVNGCM.add_reduce_uses(), and com.cliffc.aa.GVNGCM.on_reduce().
HAS_WORK
boolean com.cliffc.aa.GVNGCM.HAS_WORK static private
Definition at line 38 of file GVNGCM.java.
Referenced by com.cliffc.aa.GVNGCM.add_work(), com.cliffc.aa.GVNGCM.add_work_all(), and com.cliffc.aa.GVNGCM.iter().
IDEAL_VISIT
final VBitSet com.cliffc.aa.GVNGCM.IDEAL_VISIT = new VBitSet() static private
Definition at line 146 of file GVNGCM.java.
Referenced by com.cliffc.aa.GVNGCM.iter().
ITER_CNT
int com.cliffc.aa.GVNGCM.ITER_CNT static package
Definition at line 170 of file GVNGCM.java.
Referenced by com.cliffc.aa.GVNGCM.iter(), and com.cliffc.aa.GVNGCM.reset_to_init0().
ITER_CNT_NOOP
int com.cliffc.aa.GVNGCM.ITER_CNT_NOOP static package
Definition at line 171 of file GVNGCM.java.
Referenced by com.cliffc.aa.GVNGCM.iter(), and com.cliffc.aa.GVNGCM.reset_to_init0().
The documentation for this class was generated from the following file:
GVNGCM.java