aa: com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV Class Reference
com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV Class Reference
Public Member Functions
SnapshotV ()
boolean hasMoreElements ()
boolean hasNext ()
TypeV next ()
TypeV nextElement ()
void remove ()
Package Functions
Object key (int idx)
int length ()
Object val (int idx)
Package Attributes
Object _prevK
TypeV _prevV
final Object[] _sskvs
Private Attributes
int _idx
Object _nextK
TypeV _nextV
Detailed Description
Definition at line 1180 of file NonBlockingHashMap.java.
Constructor & Destructor Documentation
SnapshotV()
com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.SnapshotV ()
Definition at line 1182 of file NonBlockingHashMap.java.
{
       while( true ) {           // Verify no table-copy-in-progress
         Object[] topkvs = _kvs;
         CHM topchm = chm(topkvs);
         if( topchm._newkvs == null ) { // No table-copy-in-progress
           // The "linearization point" for the iteration.  Every key in this
           // table will be visited, but keys added later might be skipped or
           // even be added to a following table (also not iterated over).
           _sskvs = topkvs;
           break;
         }
         // Table copy in-progress - so we cannot get a clean iteration.  We
         // must help finish the table copy before we can start iterating.
         topchm.help_copy_impl(NonBlockingHashMap.this,topkvs,true);
       }
       // Warm-up the iterator
       next();
     }
References com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >._kvs, com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >._newkvs, com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._sskvs, com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.chm(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.CHM< TypeK, TypeV >.help_copy_impl(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.next().
Member Function Documentation
hasMoreElements()
boolean com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.hasMoreElements ()
Definition at line 1241 of file NonBlockingHashMap.java.
 { return hasNext(); }
References com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.hasNext().
hasNext()
boolean com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.hasNext ()
Definition at line 1206 of file NonBlockingHashMap.java.
 { return _nextV != null; }
References com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._nextV.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.hasMoreElements(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotK.hasNext(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotE.hasNext().
key()
Object com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.key (int idx) package
Definition at line 1201 of file NonBlockingHashMap.java.
 { return NonBlockingHashMap.key(_sskvs,idx); }
References com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._sskvs, and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.key().
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.next().
length()
int com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.length () package
Definition at line 1200 of file NonBlockingHashMap.java.
 { return len(_sskvs); }
References com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._sskvs, and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.len().
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.next().
next()
TypeV com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.next ()
Definition at line 1208 of file NonBlockingHashMap.java.
{
       // 'next' actually knows what the next value will be - it had to
       // figure that out last go-around lest 'hasNext' report true and
       // some other thread deleted the last value.  Instead, 'next'
       // spends all its effort finding the key that comes after the
       // 'next' key.
       if( _idx != 0 && _nextV == null ) throw new NoSuchElementException();
       _prevK = _nextK;          // This will become the previous key
       _prevV = _nextV;          // This will become the previous value
       _nextV = null;            // We have no more next-key
       Object nV;
       // Attempt to set <_nextK,_nextV> to the next K,V pair.
       // _nextV is the trigger: stop searching when it is != null
       while( _idx<length() ) {  // Scan array
         _nextK = key(_idx++);   // Get a key that definitely is in the set (for the moment!)
         if( _nextK != null &&   // Found something?
             _nextK != TOMBSTONE &&       // Key is not TOMBSTONE
             // Keys can be deleted and not TOMBSTONE, and after deletion had
             // their innards gutted... so you cannot use them to compute their
             // own hash or 'get' a Value.  So get the paired Value directly.
             (nV=val(_idx-1)) != null &&  // Get value
             nV != TOMBSTONE )            // Value is not TOMBSTONE
           { _nextV = (TypeV)nV; break; } // Got it!  _nextK/_nextV is a valid Key/Value
       }                         // Else keep scanning
       return _prevV;            // Return current value.
     }
References com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._idx, com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._nextK, com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._nextV, com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._prevK, com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._prevV, com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.key(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.length(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.TOMBSTONE, and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.val().
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotK.next(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotE.next(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.nextElement(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.SnapshotV().
nextElement()
TypeV com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.nextElement ()
Definition at line 1240 of file NonBlockingHashMap.java.
 { return next(); }
References com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.next().
remove()
void com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.remove ()
Definition at line 1234 of file NonBlockingHashMap.java.
{
       if( _prevV == null ) throw new IllegalStateException();
       putIfMatch( NonBlockingHashMap.this, _sskvs, _prevK, TOMBSTONE, _prevV );
       _prevV = null;
     }
References com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._prevK, com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._prevV, com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._sskvs, com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.putIfMatch(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.TOMBSTONE.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotK.remove(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotE.remove().
val()
Object com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.val (int idx) package
Definition at line 1202 of file NonBlockingHashMap.java.
 { return NonBlockingHashMap.val(_sskvs,idx); }
References com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._sskvs, and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.val().
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.next().
Member Data Documentation
_idx
int com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._idx private
Definition at line 1203 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.next().
_nextK
Object com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._nextK private
Definition at line 1204 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.next().
_nextV
TypeV com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._nextV private
Definition at line 1205 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.hasNext(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.next().
_prevK
Object com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._prevK package
Definition at line 1204 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.next(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotK.next(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotE.next(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.remove().
_prevV
TypeV com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._prevV package
Definition at line 1205 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.next(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotE.next(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.remove().
_sskvs
final Object [] com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV._sskvs package
Definition at line 1181 of file NonBlockingHashMap.java.
Referenced by com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.key(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.length(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.remove(), com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.SnapshotV(), and com.cliffc.aa.util.NonBlockingHashMap< TypeK, TypeV >.SnapshotV.val().
The documentation for this class was generated from the following file:
NonBlockingHashMap.java