aa: com.cliffc.aa.HM.HM3 Class Reference
com.cliffc.aa.HM.HM3 Class Reference
Classes
class Apply
class Con
class HMType
class HMVar
class Ident
class Lambda
class Let
class Oper
class Syntax
class VStack
class Worklist
Static Public Member Functions
static HMType hm (Syntax prog)
Static Package Functions
static void reset ()
Static Package Attributes
static final HashMap< String, HMType > ENV = new HashMap<>()
Detailed Description
Definition at line 31 of file HM3.java.
Member Function Documentation
hm()
static HMType com.cliffc.aa.HM.HM3.hm (Syntax prog) static
Definition at line 34 of file HM3.java.
{
     // Simple types
     HMVar bool  = new HMVar(TypeInt.BOOL);
     HMVar int64 = new HMVar(TypeInt.INT64);
     HMVar flt64 = new HMVar(TypeFlt.FLT64);
     HMVar strp  = new HMVar(TypeMemPtr.STRPTR);
     // Primitives
     HMVar var1 = new HMVar();
     HMVar var2 = new HMVar();
     ENV.put("pair",Oper.fun(var1, Oper.fun(var2, new Oper("pair",var1,var2))));
     // { pred:bool lhs:var3 rhs:var3 -> var3 }
     HMVar var3 = new HMVar();
     ENV.put("if/else",Oper.fun(bool,Oper.fun(var3,Oper.fun(var3,var3))));
     ENV.put("dec",Oper.fun(int64,int64));
     ENV.put("*",Oper.fun(int64,Oper.fun(int64,int64)));
     ENV.put("==0",Oper.fun(int64,bool));
     // Print a string; int->str
     ENV.put("str",Oper.fun(int64,strp));
     // Factor
     ENV.put("factor",Oper.fun(flt64,new Oper("pair",flt64,flt64)));
     // Prep for SSA: pre-gather all the (unique) ids.  Store a linked-list of
     // non-generative IDs (those mid-definition in Lambda & Let, or in the old
     // "nongen" HashSet), for use by Ident.hm.
     final Worklist work = new Worklist();
     prog.get_ids(null,work);
     // Worklist:
     int cnt=0;
     while( work.len()>0 ) {     // While not empty
       Syntax s = work.pop();    // Get work
       HMType nnn = s.hm(work);
       if( nnn!=null ) {             // If progress
         s._hm = nnn;                // Move progress state
         s.add_neighbors(work);      // Neighbors get reinspected for progress
       }
       assert prog.check_progress(work); // Everything that can make progress is on the worklist
       cnt++;                            // Which iter count, for debug only
     }
     return prog._hm;
   }
References com.cliffc.aa.HM.HM3.Syntax._hm, com.cliffc.aa.HM.HM3.Syntax.add_neighbors(), com.cliffc.aa.type.TypeInt.BOOL, com.cliffc.aa.HM.HM3.Syntax.check_progress(), com.cliffc.aa.HM.HM3.ENV, com.cliffc.aa.type.TypeFlt.FLT64, com.cliffc.aa.HM.HM3.Oper.fun(), com.cliffc.aa.HM.HM3.Syntax.get_ids(), com.cliffc.aa.HM.HM3.Syntax.hm(), com.cliffc.aa.type.TypeInt.INT64, com.cliffc.aa.HM.HM3.Worklist.len(), com.cliffc.aa.HM.HM3.Worklist.pop(), and com.cliffc.aa.type.TypeMemPtr.STRPTR.
Referenced by com.cliffc.aa.HM.TestHM3.test00(), com.cliffc.aa.HM.TestHM3.test01(), com.cliffc.aa.HM.TestHM3.test02(), com.cliffc.aa.HM.TestHM3.test03(), com.cliffc.aa.HM.TestHM3.test04(), com.cliffc.aa.HM.TestHM3.test05(), com.cliffc.aa.HM.TestHM3.test05a(), com.cliffc.aa.HM.TestHM3.test06(), com.cliffc.aa.HM.TestHM3.test07(), com.cliffc.aa.HM.TestHM3.test08(), com.cliffc.aa.HM.TestHM3.test09(), com.cliffc.aa.HM.TestHM3.test10(), com.cliffc.aa.HM.TestHM3.test11(), and com.cliffc.aa.HM.TestHM3.test12().
reset()
static void com.cliffc.aa.HM.HM3.reset () static package
Definition at line 80 of file HM3.java.
 { ENV.clear(); HMType.reset(); }
References com.cliffc.aa.HM.HM3.ENV, and com.cliffc.aa.HM.HM3.HMType.reset().
Referenced by com.cliffc.aa.HM.TestHM3.reset().
Member Data Documentation
ENV
final HashMap<String,HMType> com.cliffc.aa.HM.HM3.ENV = new HashMap<>() static package
Definition at line 32 of file HM3.java.
Referenced by com.cliffc.aa.HM.HM3.Ident.get_ids(), com.cliffc.aa.HM.HM3.Lambda.get_ids(), com.cliffc.aa.HM.HM3.Let.get_ids(), com.cliffc.aa.HM.HM3.hm(), com.cliffc.aa.HM.HM3.Ident.hm(), com.cliffc.aa.HM.HM3.Lambda.hm(), com.cliffc.aa.HM.HM3.Let.hm(), com.cliffc.aa.HM.HM3.Lambda.progress(), com.cliffc.aa.HM.HM3.Let.progress(), and com.cliffc.aa.HM.HM3.reset().
The documentation for this class was generated from the following file:
HM3.java