aa: com.cliffc.aa.util.VBitSet Class Reference
com.cliffc.aa.util.VBitSet Class Reference
Public Member Functions
VBitSet clr ()
boolean test (int idx)
boolean tset (int idx)
Detailed Description
Definition at line 5 of file VBitSet.java.
Member Function Documentation
clr()
VBitSet com.cliffc.aa.util.VBitSet.clr ()
Definition at line 9 of file VBitSet.java.
 { clear(); return this; }
Referenced by com.cliffc.aa.HM.HM9.Syntax.p0(), com.cliffc.aa.HM.HM.Syntax.p0(), com.cliffc.aa.tvar.TV2.str(), com.cliffc.aa.Env.VStack.toString(), and com.cliffc.aa.tvar.TV2.toString().
test()
boolean com.cliffc.aa.util.VBitSet.test (int idx)
Definition at line 8 of file VBitSet.java.
 { return get(idx); }
Referenced by com.cliffc.aa.type.TypeStruct.get_cyclic(), and com.cliffc.aa.node.Work.on().
tset()
boolean com.cliffc.aa.util.VBitSet.tset (int idx)
Definition at line 7 of file VBitSet.java.
 { boolean b = get(idx); set(idx); return b; }
Referenced by com.cliffc.aa.HM.HM.T2._find(), com.cliffc.aa.HM.HM.T2._find_fidxs(), com.cliffc.aa.HM.HM4.T2._get_dups(), com.cliffc.aa.HM.HM5.T2._get_dups(), com.cliffc.aa.HM.HM6.T2._get_dups(), com.cliffc.aa.HM.HM7.T2._get_dups(), com.cliffc.aa.HM.HM8.T2._get_dups(), com.cliffc.aa.HM.HM9.T2._get_dups(), com.cliffc.aa.HM.HM.T2._get_dups(), com.cliffc.aa.tvar.TV2._occurs_in_type(), com.cliffc.aa.HM.HM5.T2._occurs_in_type(), com.cliffc.aa.HM.HM6.T2._occurs_in_type(), com.cliffc.aa.HM.HM7.T2._occurs_in_type(), com.cliffc.aa.HM.HM8.T2._occurs_in_type(), com.cliffc.aa.HM.HM9.T2._occurs_in_type(), com.cliffc.aa.HM.HM.T2._occurs_in_type(), com.cliffc.aa.HM.HM4.T2._p(), com.cliffc.aa.HM.HM5.T2._p(), com.cliffc.aa.HM.HM6.T2._p(), com.cliffc.aa.HM.HM7.T2._p(), com.cliffc.aa.HM.HM8.T2._p(), com.cliffc.aa.HM.HM9.T2._p(), com.cliffc.aa.HM.HM.T2._p(), com.cliffc.aa.tvar.TV2._push_update(), com.cliffc.aa.HM.HM1.HMVar._str(), com.cliffc.aa.HM.HM3.HMVar._str(), com.cliffc.aa.HM.HM3.Oper._str(), com.cliffc.aa.node.Work.add(), com.cliffc.aa.HM.HM5.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM6.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM7.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM8.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM9.T2.add_deps_work_impl(), com.cliffc.aa.HM.HM.T2.add_deps_work_impl(), com.cliffc.aa.type.TypeMem.all_reaching_aliases(), com.cliffc.aa.type.TypeStruct.contains(), com.cliffc.aa.node.ConTypeNode.def_fref(), com.cliffc.aa.node.Node.dump(), com.cliffc.aa.node.Node.find(), com.cliffc.aa.node.FunNode.find_body(), com.cliffc.aa.tvar.TV2.find_dups(), com.cliffc.aa.type.TypeStruct.make_from(), com.cliffc.aa.node.Node.more_flow(), com.cliffc.aa.node.Node.more_ideal(), com.cliffc.aa.HM.HM3.HMType.occurs_in_type(), com.cliffc.aa.node.Node.postorder(), com.cliffc.aa.HM.HM4.T2.push_update_impl(), com.cliffc.aa.HM.HM5.T2.push_update_impl(), com.cliffc.aa.HM.HM6.T2.push_update_impl(), com.cliffc.aa.HM.HM7.T2.push_update_impl(), com.cliffc.aa.HM.HM8.T2.push_update_impl(), com.cliffc.aa.HM.HM9.T2.push_update_impl(), com.cliffc.aa.HM.HM.T2.push_update_impl(), com.cliffc.aa.type.TypeStruct.repeats_in_cycles(), com.cliffc.aa.type.TypeFld.str(), com.cliffc.aa.type.TypeMemPtr.str(), com.cliffc.aa.type.TypeFunPtr.str(), com.cliffc.aa.type.TypeStruct.str(), com.cliffc.aa.HM.HM4.T2.str(), com.cliffc.aa.HM.HM5.T2.str(), com.cliffc.aa.HM.HM6.T2.str(), com.cliffc.aa.HM.HM7.T2.str(), com.cliffc.aa.HM.HM8.T2.str(), com.cliffc.aa.HM.HM9.T2.str(), com.cliffc.aa.HM.HM.T2.str(), com.cliffc.aa.node.Node.walk_initype(), com.cliffc.aa.node.Node.walk_opt(), and com.cliffc.aa.node.Node.walkerr_def().
The documentation for this class was generated from the following file:
VBitSet.java